dd-java-agent/dd-java-agent.gradle
Remove builtin Kafka Instrumentation from agent jar.
=> Disable Kafka Instrumentation

dd-java-agent/instrumentation/aws-sdk/src/main/java/datadog/trace/instrumentation/aws/AWSClientInstrumentation.java, dd-java-agent/instrumentation/aws-sdk/src/test/groovy/AWSClientTest.groovy
Instead of requiring the builder.
=> Change AWS instrumentation to use constructor

dd-java-agent/instrumentation/aws-sdk/aws-sdk.gradle, dd-java-agent/instrumentation/aws-sdk/src/main/java/datadog/trace/instrumentation/aws/AWSClientInstrumentation.java, dd-java-agent/instrumentation/aws-sdk/src/main/java/datadog/trace/instrumentation/aws/SpanDecorator.java, dd-java-agent/instrumentation/aws-sdk/src/main/java/datadog/trace/instrumentation/aws/TracingRequestHandler.java, dd-java-agent/instrumentation/aws-sdk/src/test/groovy/AWSClientTest.groovy
Includes more details about the request.
=> Add additional tags for aws requests

dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java, dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDApiTest.groovy
Since endpointAvailable is called on construct, this can happen in premain when running with the agent. I included a simple retry just in case…
Not sure in what case the trace agent would respond so slowly…
/cc @gihad
=> Set short timeouts for api test to prevent startup delays

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ClassLoaderMatcherTest.groovy, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/HelperInjectionTest.groovy
(merging to scope manager branch)
Allow the agent to instrument bootstrap JVM classes.
Required for scala instrumentation.
=> bootstrap instrumentation

dd-java-agent/benchmark-integration/jetty-perftest/jetty-perftest.gradle, dd-java-agent/benchmark-integration/jetty-perftest/src/main/java/datadog/perftest/Worker.java, dd-java-agent/benchmark-integration/jetty-perftest/src/main/java/datadog/perftest/jetty/JettyPerftest.java, dd-java-agent/benchmark-integration/run-perf-test.sh
Include agent analysis as well as memory and CPU burn.
=> Add additional functionality to the integration benchmark perf test

dd-java-agent/benchmark/benchmark.gradle, dd-java-agent/benchmark/src/jmh/java/datadog/benchmark/ClassRetransformingBenchmark.java
Here are the results:
```
Benchmark                                                           Mode  Cnt      Score      Error  Units
ClassRetransformingBenchmark.WithAgent0210.testTracedRetransform    avgt   20   6781.182 ±  150.443  us/op
ClassRetransformingBenchmark.WithAgent0210.testUntracedRetransform  avgt   20   6522.991 ±  208.727  us/op
ClassRetransformingBenchmark.WithAgent0211.testTracedRetransform    avgt   20   6114.338 ±  181.992  us/op
ClassRetransformingBenchmark.WithAgent0211.testUntracedRetransform  avgt   20   8732.370 ± 6286.310  us/op
ClassRetransformingBenchmark.WithAgent0212.testTracedRetransform    avgt   20   6100.284 ±  187.610  us/op
ClassRetransformingBenchmark.WithAgent0212.testUntracedRetransform  avgt   20   5694.928 ±  223.363  us/op …
```
=> Add additional versions for benchmarking

dd-java-agent-ittests/dd-java-agent-ittests.gradle, dd-java-agent/instrumentation/jax-rs-annotations/src/main/java/datadog/trace/instrumentation/jaxrs/JaxRsAnnotationsInstrumentation.java, dd-java-agent/instrumentation/jax-rs-annotations/src/test/groovy/JaxRsAnnotationsInstrumentationTest.groovy, dd-java-agent/instrumentation/jax-rs-annotations/src/test/groovy/JerseyTest.groovy, dd-java-agent/instrumentation/jedis-1.4/src/main/java/datadog/trace/instrumentation/jedis/JedisInstrumentation.java, dd-java-agent/instrumentation/jedis-1.4/src/test/groovy/JedisClientTest.groovy, dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInstrumentation.java, dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java, dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy, dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsProcessorInstrumentation.java, dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsSourceNodeRecordDeserializerInstrumentation.java, dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy, dd-trace-java.gradle
These have been baking a while without any major concerns.  Lets wait a bit before we add to the official documentation though.
=> Enable instrumentation by default and rev version.

.circleci/config.yml, dd-trace-java.gradle, dd-trace-ot/dd-trace-ot.gradle, dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java, dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDApiTest.groovy, dd-trace-ot/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
@palazzem what other test cases do you think this should cover?
=> Add tests against an actual trace agent.

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInstrumentation.java, dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsProcessorInstrumentation.java, dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsSourceNodeRecordDeserializerInstrumentation.java
It might not be accessible on the classpath and cause failures.
=> Advice shouldn’t reference fields from non-injected classes

.circleci/config.yml, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java, dd-trace-api/src/main/java/datadog/trace/api/DDTraceApiInfo.java, dd-trace-java.gradle, dd-trace-ot/src/main/java/datadog/opentracing/DDTraceOTInfo.java, gradle/java.gradle
Seems like a good idea.  Had to fix some things first.
=> Add the errorprone compiler.

dd-java-agent/benchmark-integration/run-perf-test.sh
Also set mem limit to make mem usage more consistent with a real environment.
=> Add sampling for server mem usage after startup

.circleci/collect_artifacts.sh, .circleci/config.yml, .gitignore, dd-java-agent-ittests/dd-java-agent-ittests.gradle, dd-java-agent/instrumentation/aws-sdk/aws-sdk.gradle, dd-java-agent/instrumentation/datastax-cassandra-3.2/datastax-cassandra-3.2.gradle, dd-java-agent/instrumentation/jax-rs-client/jax-rs-client.gradle, dd-java-agent/instrumentation/okhttp-3/okhttp-3.gradle, dd-java-agent/instrumentation/play-2.4/play-2.4.gradle, dd-java-agent/instrumentation/play-2.4/play-2.6-testing/play-2.6-testing.gradle, dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play/PlayInstrumentation.java, dd-java-agent/instrumentation/servlet-2/src/test/groovy/JettyServletTest.groovy, dd-java-agent/instrumentation/servlet-3/servlet-3.gradle, dd-java-agent/instrumentation/servlet-3/src/test/groovy/JettyServletTest.groovy, dd-java-agent/instrumentation/servlet-3/src/test/groovy/TomcatServletTest.groovy, dd-java-agent/instrumentation/spring-web/src/test/java/test/TestForm.java, dd-trace-java.gradle, dd-trace-ot/dd-trace-ot.gradle, gradle/checkstyle.gradle, gradle/java.gradle, settings.gradle
Use workspaces to persist build between jobs.
=> Build with Java 8, but run tests with other JDKs

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/CallDepthThreadLocalMap.java, dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/CallDepthThreadLocalMapTest.groovy, dd-java-agent/instrumentation/classloaders/src/main/java/datadog/trace/instrumentation/classloaders/ClassLoaderInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
=> Remove various warnings and other cleanup

dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java, dd-trace-ot/src/main/java/datadog/opentracing/PendingTrace.java, dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy
Previous thread was not being shut down properly.
=> Add shutdown hook to span-cleaner thread

dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/muzzle/MuzzleBytecodeTransformTest.groovy, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/AdviceReferenceVisitor.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGradlePlugin.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVisitor.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/Reference.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceMatcher.java, dd-java-agent/instrumentation/instrumentation.gradle, dd-java-agent/testing/src/test/groovy/muzzle/AdviceReferenceVisitorTest.groovy
(merging to integration branch)
* Build instrumentation at references at compile-time
* Lazy-load instrumentationMuzzle field
* Cache classloader mismatches in reference matcher
=> muzzle optimize

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ExecutorInstrumentation.java
Closes https://github.com/DataDog/dd-trace-java/issues/325
=> Skip instrumenting slick thread pool

dd-java-agent/instrumentation/elasticsearch-transport-2/src/main/java/datadog/trace/instrumentation/elasticsearch2/Elasticsearch2TransportClientInstrumentation.java, dd-java-agent/instrumentation/elasticsearch-transport-2/src/main/java/datadog/trace/instrumentation/elasticsearch2/TransportActionListener.java, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/Elasticsearch5TransportClientInstrumentation.java, dd-java-agent/instrumentation/elasticsearch-transport-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/TransportActionListener.java, dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-6/src/main/java/datadog/trace/instrumentation/elasticsearch6/Elasticsearch6TransportClientInstrumentation.java, dd-java-agent/instrumentation/elasticsearch-transport-6/src/main/java/datadog/trace/instrumentation/elasticsearch6/TransportActionListener.java, dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6TransportClientTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/ListWriterAssert.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/SpanAssert.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TagsAssert.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TraceAssert.groovy, dd-trace-ot/src/main/java/datadog/opentracing/DDSpanContext.java, dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java, dd-trace-ot/src/main/java/datadog/opentracing/PendingTrace.java
I tried to get things that were somewhat generic, seemingly useful for troubleshooting, and not sensitive.
=> Add additional metadata to ES client calls.

dd-java-agent-ittests/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java, dd-java-agent/instrumentation/elasticsearch-transport-2/elasticsearch-transport-2.gradle, dd-java-agent/instrumentation/elasticsearch-transport-2/src/main/java/datadog/trace/instrumentation/elasticsearch2/Elasticsearch2TransportClientInstrumentation.java, dd-java-agent/instrumentation/elasticsearch-transport-2/src/main/java/datadog/trace/instrumentation/elasticsearch2/TransportActionListener.java, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2SpringTemplateTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/springdata/Config.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/springdata/Doc.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/springdata/DocRepository.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/Elasticsearch5TransportClientInstrumentation.java, dd-java-agent/instrumentation/elasticsearch-transport-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/TransportActionListener.java, dd-java-agent/instrumentation/elasticsearch-transport-6/src/main/java/datadog/trace/instrumentation/elasticsearch6/Elasticsearch6TransportClientInstrumentation.java, dd-java-agent/instrumentation/elasticsearch-transport-6/src/main/java/datadog/trace/instrumentation/elasticsearch6/TransportActionListener.java
Missing these helpers made the instrumentation fail.
I also included a bunch more tests covering spring data+elasticsearch.
=> Add some missing helper classes

dd-java-agent/instrumentation/lettuce-5/src/test/groovy/LettuceAsyncClientTest.groovy, dd-java-agent/instrumentation/lettuce-5/src/test/groovy/LettuceReactiveClientTest.groovy, dd-java-agent/instrumentation/lettuce-5/src/test/groovy/LettuceSyncClientTest.groovy
It looks like automatic reconnection was enabled which lead to random
traces popping up in random places when Redis server was shutdown.
Also make sure that server persists only during single test to weedout
all inter-test dependencies.
=> Fix some flakiness in Lettuce tests

.circleci/config.yml, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2SpringTemplateTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6TransportClientTest.groovy
This should prevent OOM errors
=> Reduce number of gradle workers during compile

dd-java-agent/instrumentation/akka-http-10.0/src/lagomTest/groovy/LagomTest.groovy, dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpInstrumentation.java, dd-java-agent/instrumentation/akka-http-10.0/src/test/groovy/AkkaHttpInstrumentationTest.groovy, dd-java-agent/instrumentation/play-2.4/src/latestDepTest/groovy/Play26Test.groovy
* rename config akkahttp -> akka-http-server
* renamed component value akkahttp-action -> akka-http-server
=> Akka-http-server renames

dd-java-agent/instrumentation/akka-http-10.0/src/lagomTest/groovy/LagomTest.groovy, dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpServerInstrumentation.java, dd-java-agent/instrumentation/akka-http-10.0/src/test/groovy/AkkaHttpServerInstrumentationTest.groovy
Rename some classes in akka http instrumentation to make integration of akka-http-client more consistent
=> akka http server renames

.circleci/config.yml, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExceptionHandlers.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/Reference.java, dd-java-agent/instrumentation/akka-http-10.0/src/lagomTest/java/EchoServiceImpl.java, dd-java-agent/instrumentation/classloaders/src/main/java/datadog/trace/instrumentation/classloaders/ClassLoaderInstrumentation.java, dd-java-agent/instrumentation/hystrix-1.4/src/main/java/datadog/trace/instrumentation/hystrix/HystrixCommandInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java, dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java, dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/rx/LettuceFluxCreationAdvice.java, dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/rx/LettuceFluxTerminationRunnable.java, dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/rx/LettuceMonoCreationAdvice.java, dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play/PlayInstrumentation.java, dd-java-agent/instrumentation/ratpack-1.4/src/main/java/datadog/trace/instrumentation/ratpack/RatpackHttpClientInstrumentation.java, dd-java-agent/instrumentation/ratpack-1.4/src/main/java8/datadog/trace/instrumentation/ratpack/impl/WrappedRequestSpec.java, dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java, dd-java-agent/testing/src/main/java/datadog/trace/agent/test/SpockRunner.java, dd-trace-java.gradle, dd-trace-ot/src/main/java/datadog/opentracing/PendingTrace.java, dd-trace-ot/src/main/java/datadog/trace/common/sampling/RateByServiceSampler.java, dd-trace-ot/src/main/java/datadog/trace/common/util/Clock.java, gradle/checkstyle.gradle
I think this might help with some of the formatting failures we've been seeing.
=> Upgrade java formatter version.

dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce/LettuceAsyncCommandsInstrumentation.java, dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce/LettuceClientInstrumentation.java, dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce/LettuceReactiveCommandsInstrumentation.java
Some changes landed on master that do not comply with new formatter rules
=> Fix Google Java Formater violations

.circleci/config.yml, dd-trace-java.gradle, gradle/dependencies.gradle, gradle/java.gradle, gradle/wrapper/gradle-wrapper.properties
=> Upgrade byte buddy version.

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java
These functions are not used anylonger
=> Remove functions that do reflection which is not Java10 compliant

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakMap.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakMapSuppliers.java, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/WeakConcurrentSupplierTest.groovy
* Improve tests to not depend on thread schedulting
* Test all underlying implementations
* Reduce number of static values
=> WeakMap improvements

dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/OkHttpClientSpanDecorator.java, dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/TracingInterceptor.java, dd-java-agent/instrumentation/okhttp-3/src/test/groovy/OkHttp3Test.groovy
OKHttp instrumentation will not be using the java util logger, also applies the string representation of IP address for IPV4/6 tags. Refactored test.
=> Remove Util Logger and Refactor test

dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/classloading/ClassLoadingTest.groovy, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ByteBuddyElementMatchers.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/DDCachingPoolStrategy.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/DDLocationStrategy.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceMatcher.java, dd-java-agent/testing/src/main/java/datadog/trace/agent/test/AgentTestRunner.java, dd-java-agent/testing/src/test/groovy/muzzle/ReferenceMatcherTest.groovy
* Cache type pools between transforms with weak-ref'd classloaders
* Fix classloading test
=> Cached type pool for Bytebuddy and Muzzle

dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/ChannelFutureListenerInstrumentation.java, dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/ChannelFutureListenerInstrumentation.java
Enabled the others in a separate PR and forgot to come back and enable this.
=> Enable new netty instrumentation by default

dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java
This might be more than is needed.  Maybe cut back later.
=> Enable executor instrumentation for gRPC server calls

buildSrc/src/main/groovy/MuzzleExtension.groovy, buildSrc/src/main/groovy/MuzzlePlugin.groovy, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java, dd-java-agent/instrumentation/akka-http-10.0/akka-http-10.0.gradle, dd-java-agent/instrumentation/apache-httpclient-4.3/apache-httpclient-4.3.gradle, dd-java-agent/instrumentation/apache-httpclient-4.3/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java, dd-java-agent/instrumentation/play-2.4/play-2.4.gradle, dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play/PlayInstrumentation.java
* Add version scanning to muzzle plugin
* Explicit pass/fail muzzle configuration block
* Allow version scanning with provided dependencies
* Convert apache-httpclient, akka-http, and play to muzzle
=> Add version scanning to muzzle gradle plugin

dd-trace-api/src/main/java/datadog/trace/api/interceptor/MutableSpan.java, dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java, dd-trace-ot/src/main/java/datadog/opentracing/PendingTrace.java, dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy
* getRootSpan() on MutableSpan
=> Add getRootSpan() to MutableSpan

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java, dd-java-agent/instrumentation/netty-4.0/netty-4.0.gradle, dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/ChannelFutureListenerInstrumentation.java, dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelPipelineInstrumentation.java, dd-java-agent/instrumentation/netty-4.1/netty-4.1.gradle, dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/ChannelFutureListenerInstrumentation.java, dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/NettyChannelPipelineInstrumentation.java, dd-java-agent/testing/src/test/groovy/muzzle/ReferenceCreatorTest.groovy, dd-java-agent/testing/src/test/java/muzzle/TestClasses.java
* Add ldc reference creating in muzzle
* Convert netty to muzzle scan blocks
* Inject full set of helpers in ChannelFutureListenerInstrumentation
=> Muzzle netty integrations

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/DDCachingPoolStrategy.java
Most items loaded are probably not often used.  Puts an upper limit on the size and evicts unused Resolution’s over time.
=> Add eviction to a TypePool.CacheProvider’s cache

dd-java-agent/instrumentation/jsp-2.3/jsp-2.3.gradle, dd-java-agent/instrumentation/jsp-2.3/src/main/java/datadog/trace/instrumentation/jsp/JSPInstrumentation.java, dd-java-agent/instrumentation/jsp-2.3/src/main/java/datadog/trace/instrumentation/jsp/JasperJSPCompilationContextInstrumentation.java, dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationBasicTests.groovy, dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationForwardTests.groovy
* Enable and muzzle jsp instrumentation
=> Enable and muzzle jsp instrumentation

dd-java-agent/instrumentation/spring-webflux/spring-webflux.gradle, dd-java-agent/instrumentation/spring-webflux/src/main/java/datadog/trace/instrumentation/springwebflux/DispatcherHandlerInstrumentation.java, dd-java-agent/instrumentation/spring-webflux/src/main/java/datadog/trace/instrumentation/springwebflux/HandlerFunctionAdapterInstrumentation.java, dd-java-agent/instrumentation/spring-webflux/src/main/java/datadog/trace/instrumentation/springwebflux/RequestMappingInfoHandlerMappingInstrumentation.java, dd-java-agent/instrumentation/spring-webflux/src/main/java/datadog/trace/instrumentation/springwebflux/RouterFunctionInstrumentation.java, dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/DispatcherHandlerAdvice.java, dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/DispatcherHandlerMonoBiConsumer.java, dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/HandlerFunctionAdapterAdvice.java, dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/RequestMappingInfoHandlerMappingAdvice.java, dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/RouterFunctionAdvice.java, dd-java-agent/instrumentation/spring-webflux/src/test/groovy/SpringWebfluxTest.groovy, dd-java-agent/instrumentation/spring-webflux/src/test/groovy/datadog/trace/instrumentation/springwebflux/EchoHandler.groovy, dd-java-agent/instrumentation/spring-webflux/src/test/groovy/datadog/trace/instrumentation/springwebflux/EchoHandlerFunction.groovy, dd-java-agent/instrumentation/spring-webflux/src/test/groovy/datadog/trace/instrumentation/springwebflux/FooModel.groovy, dd-java-agent/instrumentation/spring-webflux/src/test/groovy/datadog/trace/instrumentation/springwebflux/SpringWebFluxTestApplication.groovy, dd-java-agent/instrumentation/spring-webflux/src/test/groovy/datadog/trace/instrumentation/springwebflux/TestController.groovy, dd-java-agent/instrumentation/spring-webflux/src/test/java/datadog/trace/instrumentation/springwebflux/RedirectComponent.java, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/SpanAssert.groovy, settings.gradle
instruments spring webflux 5 as a child span under Netty spans
=> Spring webflux instrumentation

dd-java-agent/instrumentation/lettuce-5/lettuce-5.gradle, dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce/LettuceAsyncCommandsInstrumentation.java, dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce/LettuceClientInstrumentation.java, dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce/LettuceReactiveCommandsInstrumentation.java
Add muzzle block and remove class loader matcher methods.
=> Muzzle Lettuce 5 Instrumentation

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/SpanDecorator.java, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWSClientTest.groovy, dd-java-agent/instrumentation/aws-java-sdk-1.11.106/src/main/java/datadog/trace/instrumentation/aws/v106/SpanDecorator.java, dd-java-agent/instrumentation/aws-java-sdk-1.11.106/src/test/groovy/AWSClientTest.groovy, dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
can potentially contain sensitive data.
(See #461)
=> Stop sending params with AWS traces

dd-java-agent/instrumentation/jedis-1.4/jedis-1.4.gradle, dd-java-agent/instrumentation/jedis-1.4/src/main/java/datadog/trace/instrumentation/jedis/JedisInstrumentation.java
=> Muzzle Jedis Instrumentation

dd-java-agent/instrumentation/okhttp-3/okhttp-3.gradle, dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/OkHttp3Instrumentation.java
=> Muzzle OKHttp 3 Instrumentation

dd-java-agent/instrumentation/hystrix-1.4/hystrix-1.4.gradle, dd-java-agent/instrumentation/hystrix-1.4/src/main/java/datadog/trace/instrumentation/hystrix/HystrixThreadPoolInstrumentation.java
=> Muzzle Hystrix Instrumentation

dd-java-agent/instrumentation/spring-web/spring-web.gradle, dd-java-agent/instrumentation/spring-web/src/main/java/datadog/trace/instrumentation/springweb/HandlerAdapterInstrumentation.java
Add muzzle block and remove class loader matcher methods.
=> Muzzle Spring Web Instrumentation

dd-java-agent/instrumentation/grpc-1.5/grpc-1.5.gradle, dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/GrpcClientBuilderInstrumentation.java, dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcServerBuilderInstrumentation.java
Add muzzle block and remove class loader matcher methods.
=> Muzzle gRPC Instrumentation

dd-java-agent/instrumentation/kafka-clients-0.11/kafka-clients-0.11.gradle, dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInstrumentation.java, dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java, dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle, dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsProcessorInstrumentation.java, dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsSourceNodeRecordDeserializerInstrumentation.java
Add muzzle blocks and remove class loader matcher methods.
=> Muzzle Kafka Client & Streams Instrumentation

dd-java-agent/instrumentation/mongo-3.1/mongo-3.1.gradle, dd-java-agent/instrumentation/mongo-async-3.3/mongo-async-3.3.gradle
=> Muzzle Mongo Instrumentations

dd-java-agent/instrumentation/jetty-8/jetty-8.gradle, dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/HandlerInstrumentation.java
=> Muzzle Jetty Instrumentation

dd-java-agent/instrumentation/elasticsearch-transport-2/elasticsearch-transport-2.gradle, dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/Elasticsearch2NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/Elasticsearch2TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/springdata/Config.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/springdata/Doc.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/springdata/DocRepository.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5.3/elasticsearch-transport-5.3.gradle, dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/main/java/datadog/trace/instrumentation/elasticsearch5_3/TransportActionListener.java, dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/Elasticsearch53NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/Elasticsearch53TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/springdata/Config.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/springdata/Doc.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/springdata/DocRepository.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringRepositoryTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringTemplateTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5/elasticsearch-transport-5.gradle, dd-java-agent/instrumentation/elasticsearch-transport-5/src/latestDepTest/groovy/Elasticsearch5NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5/src/latestDepTest/groovy/Elasticsearch5TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/TransportActionListener.java, dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-6/src/main/java/datadog/trace/instrumentation/elasticsearch6/TransportActionListener.java, dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6TransportClientTest.groovy
It seems to potentially have sensitive contents, so removing to be safe.
Along with various other test improvements.
=> Remove elasticsearch.request.description

dd-java-agent/instrumentation/spymemcached-2.12/spymemcached-2.12.gradle, dd-java-agent/instrumentation/spymemcached-2.12/src/main/java/datadog/trace/instrumentation/spymemcached/MemcachedClientInstrumentation.java
=> Muzzle Spymemcached

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
* Allow instrumenting com.sun.messaging. namespace
https://github.com/DataDog/dd-trace-java/issues/517
=> Support sun JMS Clients

.circleci/config.yml, buildSrc/build.gradle, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/DDCachingPoolStrategy.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGradlePlugin.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVisitor.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ExceptionHandlerTest.groovy, gradle/dependencies.gradle
Includes some bug fixes and performance improvements.
=> Upgrade Byte Buddy to 1.9.0

.circleci/config.yml, dd-java-agent-ittests/dd-java-agent-ittests.gradle, dd-java-agent/instrumentation/akka-http-10.0/akka-http-10.0.gradle, dd-java-agent/instrumentation/akka-http-10.0/src/test/groovy/AkkaHttpClientInstrumentationTest.groovy, dd-java-agent/instrumentation/couchbase-2.0/couchbase-2.0.gradle, dd-java-agent/instrumentation/datastax-cassandra-2.3/datastax-cassandra-2.3.gradle, dd-java-agent/instrumentation/elasticsearch-rest-5/elasticsearch-rest-5.gradle, dd-java-agent/instrumentation/elasticsearch-transport-2/elasticsearch-transport-2.gradle, dd-java-agent/instrumentation/elasticsearch-transport-5.3/elasticsearch-transport-5.3.gradle, dd-java-agent/instrumentation/elasticsearch-transport-5/elasticsearch-transport-5.gradle, dd-java-agent/instrumentation/elasticsearch-transport-6/elasticsearch-transport-6.gradle, dd-java-agent/instrumentation/http-url-connection/http-url-connection.gradle, dd-java-agent/instrumentation/java-concurrent/java-concurrent.gradle, dd-java-agent/instrumentation/jdbc/jdbc.gradle, dd-java-agent/instrumentation/lettuce-5/lettuce-5.gradle, dd-java-agent/instrumentation/netty-4.0/netty-4.0.gradle, dd-java-agent/instrumentation/netty-4.1/netty-4.1.gradle, dd-java-agent/instrumentation/play-2.4/play-2.4.gradle, dd-java-agent/instrumentation/ratpack-1.4/ratpack-1.4.gradle, dd-java-agent/instrumentation/sparkjava-2.3/sparkjava-2.3.gradle, dd-java-agent/instrumentation/spring-webflux/spring-webflux.gradle, dd-trace-java.gradle, gradle/checkstyle.gradle, gradle/dependencies.gradle, gradle/java.gradle
To allow some JVMs runs only subset of tests
=> Rework the way multi-jvm tests work

dd-java-agent/instrumentation/servlet-3/servlet-3.gradle, dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/AbstractServlet3Instrumentation.java
=> Muzzle servlet-3 Instrumentation

dd-java-agent/instrumentation/servlet-2/servlet-2.gradle, dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/AbstractServlet2Instrumentation.java
=> Muzzle servlet-2 Instrumentation

dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java, dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanSerializationTest.groovy
=> Fix trace id can't be decoded by agent due to being transmitted as float

dd-java-agent/instrumentation/elasticsearch-rest-5/src/latestDepTest/groovy/Elasticsearch6RestClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-rest-5/src/test/groovy/Elasticsearch5RestClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/Elasticsearch2NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/Elasticsearch2TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/Elasticsearch53NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/Elasticsearch53TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringRepositoryTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringTemplateTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5/src/latestDepTest/groovy/Elasticsearch5NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5/src/latestDepTest/groovy/Elasticsearch5TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6TransportClientTest.groovy
Hopefully this will reduce false errors in the tests.
=> Add additional retries for ES tests.

dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ClientTest.groovy, dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ClientTest.groovy
Otherwise requests timeout and tests fail
=> Increase request timeout in netty client tests

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGradlePlugin.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/Reference.java, dd-java-agent/dd-java-agent.gradle, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java, dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce/LettuceReactiveCommandsInstrumentation.java, gradle/dependencies.gradle
=> Upgrade Byte Buddy to 1.9.2 and Shadow to 4.0.1

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle, dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java, dd-java-agent/instrumentation/akka-http-10.0/src/test/groovy/AkkaHttpServerInstrumentationTest.groovy, dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy, dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy, dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyHandlerTest.groovy, dd-java-agent/instrumentation/jms/src/latestDepTest/groovy/JMS2Test.groovy, dd-java-agent/instrumentation/jms/src/test/groovy/JMS1Test.groovy, dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy, dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy, dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ServerTest.groovy, dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ServerTest.groovy, dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy, dd-java-agent/instrumentation/servlet-2/src/test/groovy/JettyServlet2Test.groovy, dd-java-agent/instrumentation/servlet-3/src/test/groovy/JettyServlet3Test.groovy, dd-java-agent/instrumentation/servlet-3/src/test/groovy/TomcatServlet3Test.groovy, dd-java-agent/instrumentation/sparkjava-2.3/src/test/groovy/SparkJavaBasedTest.groovy, dd-java-agent/instrumentation/vertx/src/test/groovy/VertxServerTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/server/http/TestHttpServer.groovy, dd-java-agent/testing/testing.gradle, dd-trace-api/src/main/java/datadog/trace/api/Config.java, dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy, dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java, dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanBuilderTest.groovy, dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy, dd-trace-ot/src/test/groovy/datadog/opentracing/TraceInterceptorTest.groovy, dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy, dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
Also add runtime-id tag to root span and JMXFetch metrics
=> Add config for tags that propagate to JMXFetch and spans

.circleci/config.yml, dd-trace-java.gradle, gradle/java.gradle
The build scans are especially slow.
=> Attempt to increase worker count to improve build time.

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
No functional changes but this is the first version published on Maven Central
=> Update jmxfetch to latest version

dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/TracingClientInterceptor.java, dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java
This pr is for issue https://github.com/DataDog/dd-trace-java/issues/551
Its subject to change at the moment and largely depends on the discussion in https://github.com/grpc/grpc-java/issues/4864
=> Catch and log throwables to support kotlin exception handling

dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyHandlerAdvice.java, dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java, dd-java-agent/instrumentation/servlet-2/src/test/groovy/JettyServlet2Test.groovy, dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java, dd-java-agent/instrumentation/servlet-3/src/test/groovy/JettyServlet3Test.groovy, dd-java-agent/instrumentation/spring-web/spring-web.gradle, dd-java-agent/instrumentation/spring-web/src/test/groovy/test/SpringBootBasedTest.groovy, dd-java-agent/instrumentation/spring-web/src/test/java/test/Application.java, dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
=> Set user.principal in a way spring security can be covered

dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyHandlerAdvice.java
Do same thing we do for servlets
=> Better handle Jetty async calls

dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/ChannelFutureListenerInstrumentation.java, dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelPipelineInstrumentation.java, dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientRequestTracingHandler.java, dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientResponseTracingHandler.java, dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/ChannelFutureListenerInstrumentation.java, dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/NettyChannelPipelineInstrumentation.java, dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientRequestTracingHandler.java, dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientResponseTracingHandler.java
Also remove continuation when getting it
=> Set netty continuation only once

dd-java-agent-ittests/dd-java-agent-ittests.gradle, dd-java-agent/instrumentation/kafka-clients-0.11/kafka-clients-0.11.gradle, dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle, dd-java-agent/instrumentation/mongo-3.1/mongo-3.1.gradle, dd-trace-java.gradle, dd-trace-ot/dd-trace-ot.gradle, gradle/dependencies.gradle, gradle/java.gradle
Lombok to 1.8.4
Byte Buddy to 1.9.5
Test dependencies:
Test-sets plugin to 2.0.2
System-rules to 1.19.0
=> Update misc versions.

dd-java-agent/benchmark-integration/README.md, dd-java-agent/benchmark-integration/play-perftest/app/controllers/HomeController.scala, dd-java-agent/benchmark-integration/play-perftest/app/controllers/Worker.scala, dd-java-agent/benchmark-integration/play-perftest/conf/application.conf, dd-java-agent/benchmark-integration/play-perftest/conf/logback.xml, dd-java-agent/benchmark-integration/play-perftest/conf/messages, dd-java-agent/benchmark-integration/play-perftest/conf/routes, dd-java-agent/benchmark-integration/play-perftest/play-perftest.gradle, dd-java-agent/benchmark-integration/run-perf-test.sh, settings.gradle
- Created sample play server that performs busy wait to simulate work.
- Play server can be compiled using `./gradlew :dd-java-agent:benchmark-integration:play-perftest:dist`
- Updated testing script to work with Play and Jetty.
- Takes in an extra argument [play-zip | jar] to distinguish between the types of servers to test against.
=> Play Performance Test

dd-trace/src/main/java/datadog/trace/tracer/LogRateLimiter.java, dd-trace/src/test/groovy/datadog/trace/tracer/LogRateLimiterTest.groovy
Adds helper class to limit number of logs.
This should be reviewed after #642
=> Add log ratelimiter

dd-java-agent/instrumentation/vertx/src/test/java/VertxWebTestServer.java
By actiually waiting for test server to start listening.
=> Improve Vertx test stability

dd-java-agent/instrumentation/elasticsearch-transport-2/elasticsearch-transport-2.gradle, dd-trace-ot/dd-trace-ot.gradle, dd-trace/src/test/groovy/datadog/trace/tracer/JsonSpan.groovy, dd-trace/src/test/groovy/datadog/trace/tracer/writer/AgentClientTest.groovy, gradle/dependencies.gradle
There is a vulerability in prior versions, per the following CVE: https://nvd.nist.gov/vuln/detail/CVE-2018-1000873
=> Upgrade jackson to 2.9.8

dd-trace-api/src/main/java/datadog/trace/api/DDTags.java, dd-trace-ot/src/main/java/datadog/opentracing/decorators/DDDecoratorsFactory.java, dd-trace-ot/src/main/java/datadog/opentracing/decorators/EventSampleRateDecorator.java, dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy, dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
This only adds the API, no changes to the integrations.
=> Initial support for setting Event Sample Rate via tags

dd-java-agent/agent-tooling/agent-tooling.gradle, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/WeakConcurrentSupplierTest.groovy, dd-java-agent/dd-java-agent.gradle, dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ClassLoadingTest.groovy, dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TestUtils.java, dd-java-agent/testing/src/test/groovy/context/FieldBackedProviderTest.groovy, dd-java-agent/testing/src/test/java/muzzle/MuzzleWeakReferenceTest.java, dd-java-agent/testing/testing.gradle, dd-trace-ot/dd-trace-ot.gradle, dd-trace-ot/src/test/groovy/datadog/opentracing/PendingTraceTest.groovy, dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy, dd-trace/dd-trace.gradle, dd-trace/src/test/groovy/datadog/trace/tracer/TracerTest.groovy, settings.gradle, utils/gc-utils/gc-utils.gradle, utils/gc-utils/src/main/java/datadog/trace/util/gc/GCUtils.java
=> Move awaitGC to common utility package

dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/ChannelFutureListenerInstrumentation.java, dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelPipelineInstrumentation.java, dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientRequestTracingHandler.java
Copy recent improvements done for netty 4.1 into netty 4.0
=> netty40 improvements

dd-trace-ext/src/main/java/datadog/trace/tracer/ext/Examples.java, dd-trace/dd-trace.gradle, dd-trace/src/main/java/datadog/trace/tracer/Span.java, dd-trace/src/main/java/datadog/trace/tracer/Tracer.java, dd-trace/src/main/java/datadog/trace/tracer/writer/AgentWriter.java, dd-trace/src/test/groovy/datadog/trace/tracer/TracerTest.groovy
This will work better for long-term support without breaking compatibility for adding new fields.
=> Use lombok builder for Tracer construction.

dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java
Otherwise it’s difficult to determine why JMXFetch isn’t being initialized.
=> Add logging to JMXFetch initialization delay

.circleci/collect_reports.sh, dd-trace-java.gradle, gradle/java.gradle
So we could investigate them later.
=> Collect JVM crashes in circleci artifacts

dd-trace/src/main/java/datadog/trace/tracer/Clock.java, dd-trace/src/main/java/datadog/trace/tracer/Timestamp.java, dd-trace/src/main/java/datadog/trace/tracer/Tracer.java, dd-trace/src/test/groovy/datadog/trace/tracer/ClockTest.groovy, dd-trace/src/test/groovy/datadog/trace/tracer/TimestampTest.groovy
This is required for compatibility with OT.
=> New API:  Allow creating timestamp with custom time.

dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java, dd-trace/src/main/java/datadog/trace/tracer/Span.java, dd-trace/src/main/java/datadog/trace/tracer/SpanImpl.java, dd-trace/src/main/java/datadog/trace/tracer/Tracer.java, dd-trace/src/test/groovy/datadog/trace/tracer/JsonSpan.groovy, dd-trace/src/test/groovy/datadog/trace/tracer/SpanImplTest.groovy, dd-trace/src/test/groovy/datadog/trace/tracer/TracerTest.groovy
Also add getMeta() to Span interface.
=> New API: Add shutdown callback to shutdown the Tracer

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java
This is helpful to see what logs belong to what test
=> Log when test starts

dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java, dd-java-agent/src/test/java/jvmbootstraptest/LogManagerSetter.java
Resources must replace `.` -> `/` and add `.class` to the end.
=> Fix how we evaluate if customlogger is on classpath

dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java, dd-trace-api/src/main/java/datadog/trace/api/Config.java, dd-trace-api/src/main/java/datadog/trace/api/DDTags.java, dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy, dd-trace-ot/src/main/java/datadog/opentracing/decorators/AnalyticsSampleRateDecorator.java, dd-trace-ot/src/main/java/datadog/opentracing/decorators/DDDecoratorsFactory.java
Also make the instrumentation names a sorted list so the evaluation order is consistent.
=> Trace Analytics Config

dd-java-agent/agent-tooling/agent-tooling.gradle, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/BaseDecorator.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/ClientDecorator.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpClientDecorator.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpServerDecorator.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/ServerDecorator.java, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/BaseDecoratorTest.groovy, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/ClientDecoratorTest.groovy, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/HttpClientDecoratorTest.groovy, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/HttpServerDecoratorTest.groovy, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/ServerDecoratorTest.groovy, dd-java-agent/instrumentation/trace-annotation/src/test/groovy/ConfiguredTraceAnnotationsTest.groovy, dd-trace-api/src/main/java/datadog/trace/api/Config.java, dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Actual usage to follow in separate PRs.
=>  Introduce base decorators

dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationBasicTests.groovy, dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationForwardTests.groovy, dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/AbstractServlet2Instrumentation.java, dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java, dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Decorator.java, dd-java-agent/instrumentation/servlet-2/src/test/groovy/JettyServlet2Test.groovy, dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/AsyncContextInstrumentation.java, dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/FilterChain3Instrumentation.java, dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/HttpServlet3Instrumentation.java, dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java, dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Decorator.java, dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/TagSettingAsyncListener.java, dd-java-agent/instrumentation/servlet-3/src/test/groovy/AbstractServlet3Test.groovy, dd-java-agent/instrumentation/spring-web/src/test/groovy/test/SpringBootBasedTest.groovy
This also adopts the new Trace Analytics config.
=> Servlet migrate to decorators

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpClientDecorator.java, dd-java-agent/instrumentation/akka-http-10.0/src/main/scala/datadog/trace/instrumentation/akkahttp/AkkaHttpClientDecorator.java, dd-java-agent/instrumentation/akka-http-10.0/src/main/scala/datadog/trace/instrumentation/akkahttp/AkkaHttpClientInstrumentation.java, dd-java-agent/instrumentation/akka-http-10.0/src/main/scala/datadog/trace/instrumentation/akkahttp/AkkaHttpClientTransformFlow.scala, dd-java-agent/instrumentation/akka-http-10.0/src/main/scala/datadog/trace/instrumentation/akkahttp/AkkaHttpServerDecorator.java, dd-java-agent/instrumentation/akka-http-10.0/src/main/scala/datadog/trace/instrumentation/akkahttp/AkkaHttpServerInstrumentation.java, dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientDecorator.java, dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java, dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java, dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java, dd-java-agent/instrumentation/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseBucketInstrumentation.java, dd-java-agent/instrumentation/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseClientDecorator.java, dd-java-agent/instrumentation/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseClusterInstrumentation.java, dd-java-agent/instrumentation/datastax-cassandra-2.3/src/main/java/datadog/trace/instrumentation/datastax/cassandra/CassandraClientDecorator.java, dd-java-agent/instrumentation/datastax-cassandra-2.3/src/main/java/datadog/trace/instrumentation/datastax/cassandra/TracingSession.java, dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java, dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Decorator.java, dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java, dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Decorator.java, dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/TagSettingAsyncListener.java
In the instrumentation it reads better.
=> Rename and static import decorators instance

dd-java-agent/instrumentation/mongo-3.1/mongo-3.1.gradle, dd-java-agent/instrumentation/mongo-3.1/src/main/java/datadog/trace/instrumentation/mongo/DDTracingCommandListener.java, dd-java-agent/instrumentation/mongo-3.1/src/main/java/datadog/trace/instrumentation/mongo/MongoClientDecorator.java, dd-java-agent/instrumentation/mongo-3.1/src/main/java/datadog/trace/instrumentation/mongo/MongoClientInstrumentation.java, dd-java-agent/instrumentation/mongo-3.1/src/test/groovy/MongoClientDecoratorTest.groovy, dd-java-agent/instrumentation/mongo-3.1/src/test/java/datadog/trace/instrumentation/mongo/MongoClientInstrumentationTest.java, dd-java-agent/instrumentation/mongo-async-3.3/src/main/java/datadog/trace/instrumentation/mongo/MongoAsyncClientInstrumentation.java, dd-java-agent/instrumentation/ratpack-1.4/src/test/groovy/RatpackTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/SpanAssert.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy, dd-trace-ot/dd-trace-ot.gradle
I tried to improve the tests, but it resulted in an odd classloader issue.  I rolled back the testing change.  We can revisit this again in the future.
=> Migrate Mongo to Decorator

dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java, dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java
To ensure we do not pile up traces causing memory overconsumption if agent is slow to respond.
=> Implement HTTP timeout when sending traces to Datadog agent

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpClientDecorator.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpServerDecorator.java, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/HttpClientDecoratorTest.groovy, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/HttpServerDecoratorTest.groovy, dd-trace-api/src/main/java/datadog/trace/api/Config.java, dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Using the following defaults:
* `DD_HTTP_CLIENT_ERROR_STATUSES=400-499`
* `DD_HTTP_SERVER_ERROR_STATUSES=500-599`
=> Implement Http Status error mapping via config

dd-trace-api/src/main/java/datadog/trace/api/Config.java
Use the properly documented and agreed upon config keys.
=> Correct http status mapping config keys

gradle/dependencies.gradle, gradle/java.gradle, gradle/test-with-scala.gradle
=> Mar kolya/some java11 prep

dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java
=> Fix log message

dd-trace-java.gradle, dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
Otherwise it might get initialized by a different classloader which would prevent that classloader from being unloaded.
=> Ensure that PendingTrace.SPAN_CLEANER initialized with Tracer

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java, dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AdviceUtils.java, dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaExecutorInstrumentation.java, gradle/dependencies.gradle
and a few other minor code changes.
=> Upgrade Byte Buddy to 1.9.12

dd-trace-java.gradle
=> Bump version 0.27.0

dd-trace-java.gradle
Post release PR for begin of 0.28.0
=> Begin 0.28.0

dd-smoke-tests/play/play.gradle, dd-smoke-tests/springboot/springboot.gradle, dd-smoke-tests/wildfly/wildfly.gradle, gradle/java.gradle
Unfortunately Gradle seem to need some manual help to figure this one out.
=> Do not run smoke test servers when tests are disabled

dd-trace-api/src/main/java/datadog/trace/api/Config.java, dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Reverts DataDog/dd-trace-java#823
=> Revert "Enable JMXFetch by default"

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java, dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy, dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy, dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java, dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
These are breaking changes that need more vetting.
=> Revert Pull Request #854 and #855

.circleci/collect_reports.sh, .circleci/collect_results.sh
=> Enable '**' support in logs collection scripts

.circleci/config.yml
Will hopefully reduce retesting and the total testing time.
=> Run latestDepTests in a separate job

.circleci/collect_reports.sh
This reverts commit a0fc54936a2dc6fe64e6d5cd1f23398279bc381c.
=> Revert "Collect more debugging info"

dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java
Also add an 'identifying marker' to tracing log lines so we could
potentially automatically parse them.
=> Configure system logger to log timestamp

dd-trace-ot/src/main/java/datadog/opentracing/DDTraceOTInfo.java, dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java
This pull request sends the JVM vendor to the agent in the same manner as the JVM version
=> Send JVM vendor as header to agent

dd-java-agent/instrumentation/akka-http-10.0/src/test/groovy/AkkaHttpServerInstrumentationTest.groovy, dd-java-agent/instrumentation/jetty-8/jetty-8.gradle, dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyHandlerAdvice.java, dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyHandlerInstrumentation.java, dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyContinuationHandlerTest.groovy, dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyHandlerTest.groovy, dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyTestInstrumentation.java, dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ServerTest.groovy, dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ServerTest.groovy, dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/StatusSavingHttpServletResponseWrapper.java, dd-java-agent/instrumentation/servlet-2/src/test/groovy/JettyServlet2Test.groovy, dd-java-agent/instrumentation/servlet-3/src/test/groovy/AbstractServlet3Test.groovy, dd-java-agent/instrumentation/servlet-3/src/test/groovy/JettyServlet3Test.groovy, dd-java-agent/instrumentation/servlet-3/src/test/groovy/TomcatServlet3Test.groovy, dd-java-agent/instrumentation/spring-webflux/src/test/groovy/SpringWebfluxTest.groovy, dd-java-agent/instrumentation/vertx/src/test/groovy/server/VertxHttpServerTest.groovy, dd-java-agent/instrumentation/vertx/src/test/groovy/server/VertxRxCircuitBreakerHttpServerTest.groovy, dd-java-agent/instrumentation/vertx/src/test/groovy/server/VertxRxHttpServerTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/OkHttpUtils.groovy
Also add tests for redirects and refactoring.
=> Jetty 8 test migration and ignoreParent

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle, gradle/dependencies.gradle
This addresses the same security issue as #947.
=> Update JMXFetch to 0.30.1

dd-java-agent/instrumentation/jax-rs-annotations/src/main/java/datadog/trace/instrumentation/jaxrs/JaxRsAnnotationsDecorator.java, dd-java-agent/instrumentation/jax-rs-annotations/src/main/java/datadog/trace/instrumentation/jaxrs/JaxRsAnnotationsInstrumentation.java, dd-java-agent/instrumentation/jax-rs-annotations/src/test/groovy/JaxRsAnnotationsInstrumentationTest.groovy
Set static operation name on Jax-RS spans.
=> Static operation names for JaxRS instrumentation to be used as root span

dd-java-agent/instrumentation/aws-java-sdk-2.2/aws-java-sdk-2.2.gradle, dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java, dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java, dd-java-agent/instrumentation/aws-java-sdk-2.2/src/test/groovy/AwsClientTest.groovy
s3 -> bucket name
dynamodb -> table name
sqs -> queue name/url
kinesis -> stream name
=> Add additional tags for aws-sdk spans

dd-trace-api/src/main/java/datadog/trace/api/Config.java, dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
=> Rename SERVICE -> SERVICE_TAG constant

dd-trace-api/src/main/java/datadog/trace/context/TraceScope.java
=> when -> which

dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
Otherwise flish event gets stuck in disruptor forever.
=> Make sure flush cannot happen after disruptor shutdown

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/instrumentation/api/AgentPropagation.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/instrumentation/api/AgentScope.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/instrumentation/api/AgentSpan.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/instrumentation/api/AgentTracer.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/instrumentation/api/Propagation.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Constants.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/OpenTracing31.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java, dd-java-agent/instrumentation/osgi-classloading/src/test/groovy/OSGIClassloadingTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/SpockRunner.java, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/GlobalTracerUtils.java
Tests and comments are still needed, but can be added later...
This PR separates out the API additions from #936 and #1020 for better review.
=> Initial implementation of agent internal API.

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/OpenTracing32.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java, dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java, dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/GlobalTracerUtils.java, dd-trace-ot/docs/opentracing-api.md, dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java, dd-trace-ot/src/main/java/datadog/opentracing/DDSpanContext.java, dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java, dd-trace-ot/src/main/java/datadog/opentracing/propagation/B3HttpCodec.java, dd-trace-ot/src/main/java/datadog/opentracing/propagation/DatadogHttpCodec.java, dd-trace-ot/src/main/java/datadog/opentracing/propagation/HaystackHttpCodec.java, dd-trace-ot/src/main/java/datadog/opentracing/propagation/HttpCodec.java, dd-trace-ot/src/main/java/datadog/opentracing/propagation/TagContext.java, dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/ContextualScopeManager.java, dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy, gradle/dependencies.gradle
This seems backwards compatible with 0.31 since all changes are additional.
=> Minimal changes required for OT 0.32

dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java, dd-java-agent/instrumentation/dropwizard/dropwizard-views/src/main/java/datadog/trace/instrumentation/dropwizard/view/DropwizardViewInstrumentation.java, dd-java-agent/instrumentation/dropwizard/dropwizard-views/src/test/groovy/ViewRenderTest.groovy, dd-java-agent/instrumentation/jax-rs-client-1.1/src/main/java/datadog/trace/instrumentation/jaxrs/v1/JaxRsClientV1Instrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java, dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyHandlerAdvice.java, dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageListenerInstrumentation.java, dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageProducerInstrumentation.java, dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitChannelInstrumentation.java, dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java, dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java, dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerAdapterInstrumentation.java, dd-java-agent/instrumentation/spymemcached-2.12/src/main/java/datadog/trace/instrumentation/spymemcached/MemcachedClientInstrumentation.java, dd-java-agent/instrumentation/twilio/src/main/java/datadog/trace/instrumentation/twilio/TwilioAsyncInstrumentation.java, dd-java-agent/instrumentation/twilio/src/main/java/datadog/trace/instrumentation/twilio/TwilioSyncInstrumentation.java
Also prefer early return instead of deep nesting for null check.
I strongly advise ignoring whitespace changes for this PR review.
=> Skip spring controller and dropwizard trace if no trace present

dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java, dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
Sometimes servlets will call another servlet by “resetting” the request object.  This maintains the attributes previously set, including the span.  We want to allow the trace to start if there’s no “active trace” even if there is a span attribute.
=> Fix servlet propagation for “tail-call” situations

dd-trace-ot/dd-trace-ot.gradle
This seems to fix strange build errors
=> Update unixsocket dependenxy

dd-trace-ot/src/main/java/datadog/opentracing/decorators/AnalyticsSampleRateDecorator.java, dd-trace-ot/src/main/java/datadog/opentracing/decorators/ForceManualDropDecorator.java, dd-trace-ot/src/main/java/datadog/opentracing/decorators/ForceManualKeepDecorator.java, dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy
Since global tags can only be set as String.
=> Allow decorators to parse string values on tags.

dd-trace-api/src/main/java/datadog/trace/api/DDTraceApiInfo.java, dd-trace-ot/src/main/java/datadog/opentracing/DDTraceOTInfo.java
Added try with resources to couple places where we open an InputStreamReader and don't close it.
There are probably more locations, but I started with a couple easy ones.
=> Closing Readers

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
To check for existence, switching from getResourceAsStream to getResource
=> Fixing resource leak

LICENSE-3rdparty.csv, dd-java-agent/load-generator/Readme.md, dd-java-agent/load-generator/load-generator.gradle, dd-java-agent/load-generator/src/main/java/datadog/loadgenerator/LoadGenerator.java, settings.gradle
**Load generation tool that generates traces at a specified rate.**
The tool has a few options to control the size of each trace and other knobs such as threads used to generate.  Since the tool runs the full tracer, all environment variables and system properties work as normal.
This is a first stab at the tool to get some feedback so there may be features or controls that are missing.
=> Simple load generator tool

dd-java-agent/instrumentation/glassfish/src/test/groovy/GlassFishServerTest.groovy, dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyDecorator.java, dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationBasicTests.groovy, dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationForwardTests.groovy, dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Decorator.java, dd-java-agent/instrumentation/servlet/request-2/src/test/groovy/JettyServlet2Test.groovy, dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Decorator.java, dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy, dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy, dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/SpringWebHttpServerDecorator.java, dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/SpringBootBasedTest.groovy
Gives a little bit of extra context and potentially something we can use instead of url for resource naming.
=> Add servlet.path tag

gradle/dependencies.gradle
Docs: https://github.com/raphw/byte-buddy/releases
=> bytebuddy 1.10.4

dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java, dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
Otherwise it could block shutdown if executor is stopped before disruptor.
#1145
=> Allow flush to return if executor already shut down

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/aws-java-sdk-1.11.0.gradle, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSClientInstrumentation.java, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSHttpClientInstrumentation.java, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/OnErrorDecorator.java, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/RequestInstrumentation.java, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/RequestMeta.java, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWSClientTest.groovy, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test_before_1_11_106/groovy/AWSClientTest.groovy, dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
This brings it inline with the v2 instrumentation.
=> Add various tags for AWS SDK v1.x

dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcExtractAdapter.java, dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
Replacement PR for  #1119.  Added test and applied formatting.
Thanks @bruce-au for the contribution!
=> Fixing GRPC `-bin` header unmarshalling

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle, dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java, gradle/wrapper/gradle-wrapper.properties
https://github.com/DataDog/jmxfetch/releases/tag/0.34.0
=> Upgrade jmxfetch to latest version

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ByteBuddyElementMatchers.java
Same logic that was applied in #1169
=> Remove more declared method filtering for optimization

dd-trace-ot/src/main/java/datadog/trace/common/serialization/MsgpackFormatWriter.java, dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanSerializationTest.groovy
=> Fix NPE on serialization with no span type

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpServerDecorator.java, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/HttpServerDecoratorTest.groovy, dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpServerDecorator.java, dd-java-agent/instrumentation/dropwizard/src/test/groovy/DropwizardTest.groovy, dd-java-agent/instrumentation/finatra-2.9/src/main/java/datadog/trace/instrumentation/finatra/FinatraDecorator.java, dd-java-agent/instrumentation/glassfish/src/test/groovy/GlassFishServerTest.groovy, dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyDecorator.java, dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyDecorator.java, dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyHandlerTest.groovy, dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationBasicTests.groovy, dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationForwardTests.groovy, dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/NettyHttpServerDecorator.java, dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/NettyHttpServerDecorator.java, dd-java-agent/instrumentation/play-2.4/src/main/java8/datadog/trace/instrumentation/play24/PlayHttpServerDecorator.java, dd-java-agent/instrumentation/play-2.6/src/main/java8/datadog/trace/instrumentation/play26/PlayHttpServerDecorator.java, dd-java-agent/instrumentation/ratpack-1.4/src/main/java8/datadog/trace/instrumentation/ratpack/RatpackServerDecorator.java, dd-java-agent/instrumentation/ratpack-1.4/src/test/groovy/RatpackOtherTest.groovy, dd-java-agent/instrumentation/ratpack-1.4/src/test/groovy/server/RatpackHttpServerTest.groovy, dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Decorator.java, dd-java-agent/instrumentation/servlet/request-2/src/test/groovy/JettyServlet2Test.groovy, dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Decorator.java, dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy, dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy, dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy, dd-java-agent/instrumentation/sparkjava-2.3/src/test/groovy/SparkJavaBasedTest.groovy, dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/SpringWebfluxTest.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/SpringWebHttpServerDecorator.java, dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/SpringBootBasedTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
Getting peer hostname makes DNS request
=> Disable peer hostname tag for http servers

dd-java-agent/instrumentation/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseBucketInstrumentation.java, dd-java-agent/instrumentation/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseClusterInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java, dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelPipelineInstrumentation.java, dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/NettyChannelPipelineInstrumentation.java, dd-java-agent/instrumentation/spymemcached-2.12/src/main/java/datadog/trace/instrumentation/spymemcached/MemcachedClientInstrumentation.java
From https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/168
=> Make sure CallDepthThreadLocalMap is always reset

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
Apply same change as here: https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/191
=> Remove conversion from URI to String back to URI

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java, dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ProfilingSystemTest.java, dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java, dd-trace-api/src/main/java/datadog/trace/api/Config.java, dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Currently this blows up JVMs before 14
=> Add an option to force profiling right in the beginning of premain

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
Includes many improvements regarding memory footprint and allocations
=> Update JMXFetch to 0.35

dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/BaseDecoratorTest.groovy, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/CleanerTest.groovy, dd-java-agent/instrumentation/akka-http-10.0/src/test/groovy/AkkaHttpServerInstrumentationTest.groovy, dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/CouchbaseAsyncClientTest.groovy, dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/CouchbaseClientTest.groovy, dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringTemplateTest.groovy, dd-java-agent/instrumentation/couchbase-2.6/src/test/groovy/CouchbaseAsyncClient26Test.groovy, dd-java-agent/instrumentation/couchbase-2.6/src/test/groovy/CouchbaseClient26Test.groovy, dd-java-agent/instrumentation/google-http-client/src/test/groovy/GoogleHttpClientTest.groovy, dd-java-agent/instrumentation/jms/src/test/groovy/SpringTemplateJMS1Test.groovy, dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ClientTest.groovy, dd-smoke-tests/wildfly/src/test/groovy/datadog/smoketest/WildflySmokeTest.groovy, dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy, dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentApiTest.groovy
Add timeouts (to avoid a gradle level timeout) and retries (since we're doing it manually anyway).
I realize this is a band aid...
=> Attempt to improve test reliability

dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java, dd-java-agent/instrumentation/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseBucketInstrumentation.java, dd-java-agent/instrumentation/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseClusterInstrumentation.java, dd-java-agent/instrumentation/dropwizard/src/test/groovy/DropwizardTest.groovy, dd-java-agent/instrumentation/finatra-2.9/src/main/java/datadog/trace/instrumentation/finatra/FinatraInstrumentation.java, dd-java-agent/instrumentation/google-http-client/src/main/java/datadog/trace/instrumentation/googlehttpclient/GoogleHttpClientInstrumentation.java, dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyHttpHandlerInstrumentation.java, dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/GrpcClientBuilderInstrumentation.java, dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcServerBuilderInstrumentation.java, dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/InProcessServerStreamInstrumentation.java, dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/AsyncContextInstrumentation.java, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTestAdvice.java
And ordering of some `helperClassNames`
=> Improve consistency of `@Advice.OnMethodExit` params

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy, dd-trace-api/src/main/java/datadog/trace/api/Config.java, dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java, dd-trace-ot/src/main/java/datadog/opentracing/DDSpanContext.java, dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy
Reverts DataDog/dd-trace-java#1160
=> Revert "Add config to capture stacktrace when a span duration exceeds threshold"

dd-java-agent/instrumentation/netty-3.8/src/latestDepTest/groovy/Netty38ServerTest.groovy, dd-java-agent/instrumentation/netty-3.8/src/test/groovy/Netty38ServerTest.groovy
Otherwise netty gets really upset in an odd way
=> Make sure that netty exception message is not null

dd-java-agent/instrumentation/netty-3.8/src/latestDepTest/groovy/Netty38ServerTest.groovy, dd-java-agent/instrumentation/netty-3.8/src/test/groovy/Netty38ServerTest.groovy
I had been seeing the issue locally about 1 out of 10 runs. I ran this 20 times in a row without failure
=> Switch netty 3.8 startup and shutdown implementation

dd-java-agent/instrumentation/netty-3.8/src/latestDepTest/groovy/Netty38ClientTest.groovy, dd-java-agent/instrumentation/netty-3.8/src/test/groovy/Netty38ClientTest.groovy
Fixes http client tests to implement #1320
=> Fix netty 3.8 http client tests

dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ControllerFactory.java, dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ControllerFactoryTest.java
suggests to use zulu 1.8u212+ which includes JFR or OpenJDK11+
=> Add fix suggestion when JFR API not found

dd-trace-api/src/main/java/datadog/trace/api/Config.java, dd-trace-ot/src/main/java/datadog/opentracing/DDSpanContext.java, dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanSerializationTest.groovy, dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy, dd-trace-ot/src/test/groovy/datadog/trace/DDSpanContextTest.groovy, dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentApiTest.groovy, dd-trace-ot/src/test/groovy/datadog/trace/api/writer/LoggingWriterTest.groovy
Reverts DataDog/dd-trace-java#1336
=> Revert "add ..."metrics":{"_dd.measured":1}... to every span"

dd-trace-ot/dd-trace-ot.gradle, gradle/dependencies.gradle
This should fix 'index out of bounds' issue that happened in older client
=> Use newer version of statsd client

dd-java-agent/instrumentation/hibernate/core-4.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_3/SessionInstrumentation.java, dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/CallableInstrumentation.java, dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/FutureInstrumentation.java, dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java, dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableInstrumentation.java, dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ScalaExecutorInstrumentation.java, dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ScalaForkJoinTaskInstrumentation.java, dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceConfigInstrumentation.java
=> Use singletonMap for single entry maps

.github/workflows/create-next-milestone.yml
When a milestone is closed, automatically create the next milestone titled with the next minor version
=> Automatically create next milestone

dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/RediscalaInstrumentation.java
Noticed this while merging to opentelemetry-auto-instr-java.
=> Fix early close of rediscala span

dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/server/HttpServerResponseTracingHandler.java, dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/HttpServerResponseTracingHandler.java, dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/HttpServerResponseTracingHandler.java
This should allow us to better capture it in profiling
=> Add scopes to http server response

dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java
Could be accessed by different threads
=> Add volatile on started boolean in ProfilingSystem

dd-java-agent/instrumentation/lettuce-4/src/main/java/datadog/trace/instrumentation/lettuce4/LettuceAsyncCommandsInstrumentation.java, dd-java-agent/instrumentation/lettuce-4/src/main/java/datadog/trace/instrumentation/lettuce4/LettuceClientInstrumentation.java, dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceAsyncCommandsInstrumentation.java, dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceClientInstrumentation.java, dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceReactiveCommandsInstrumentation.java
Docs update: https://github.com/DataDog/documentation/pull/7442
=> Add version specific names to allow disabling only a specific version

.palantir/revapi.yml
Reformat of the `revapi.yml` file for easier diffs in the future.
=> Reformat the revapi file

dd-trace-core/src/main/java/datadog/trace/core/util/JmxThreadStackProvider.java, dd-trace-core/src/main/java/datadog/trace/core/util/NoneThreadStackProvider.java, dd-trace-core/src/main/java/datadog/trace/core/util/ThreadStackProvider.java, dd-trace-core/src/test/groovy/datadog/trace/core/util/ThreadStackAccessTest.groovy
=> Add new method returns ThreadInfo

dd-trace-core/dd-trace-core.gradle, dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ListWriter.java, dd-trace-core/src/main/java/datadog/trace/common/writer/LoggingWriter.java, dd-trace-core/src/main/java/datadog/trace/common/writer/Writer.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingDisruptor.java, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, dd-trace-core/src/main/java/datadog/trace/core/interceptor/TraceStatsCollector.java, dd-trace-core/src/main/java/datadog/trace/core/processor/TraceProcessor.java, dd-trace-core/src/main/java/datadog/trace/core/processor/rule/URLAsResourceNameRule.java, dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java, dd-trace-core/src/main/java/datadog/trace/core/scopemanager/TraceProfilingScopeManager.java, dd-trace-core/src/test/groovy/datadog/trace/core/processor/TraceProcessorTest.groovy, internal-api/src/main/java/datadog/trace/profiling/Profiler.java
The activation is determined by various attributes of the root span.  Additional testing is needed, which will be done in a separate PR.
=> Call the new MLT API on various Span Activations

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
should use Profiling classloader as accessed through this one
=> Change Classloader for ThreadStackAccess

dd-java-agent/agent-profiling/profiling-controller/profiling-controller.gradle, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/jfr/Annotation.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/jfr/BaseType.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/jfr/BuiltinType.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/jfr/CompositeType.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/jfr/ImmutableMapEntry.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/jfr/Metadata.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/jfr/ResolvableType.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/jfr/SingleFieldMap.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/jfr/TypeValueBuilderImpl.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/jfr/TypedField.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/jfr/TypedFieldValue.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/jfr/TypedValue.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/jfr/Types.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/mlt/SamplerContext.java, dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/util/NonZeroHashCode.java, dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/jfr/AnnotationTest.java, dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/jfr/CompositeTypeBuilderImplTest.java, dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/jfr/MetadataTest.java, dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/jfr/TypedFieldBuilderImplTest.java, dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/mlt/SamplerWriterTest.java, dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/util/NonZeroHashCodeTest.java
Fix hashCode and equals calculation on all types participating in metadata and constant pools.
=> PROF-1560: Fix simple type constant pool handling

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/MetricsAssert.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/SpanAssert.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/server/http/TestHttpServer.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/TraceUtils.groovy, dd-trace-core/src/main/java/datadog/trace/core/StringTables.java, dd-trace-core/src/test/groovy/datadog/trace/core/StringTablesTest.groovy
Recovers the metrics asserts from the abandoned #1484
Also interns some constant metric names I spotted.
=> add assertions about metrics

dd-java-agent/instrumentation/finatra-2.9/finatra-2.9.gradle
Cherry picked from https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/450
=> Fixes integration with latest version of Finatra

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/MetricsAssert.groovy
=> Add dd.measured as a default metric

dd-java-agent/instrumentation/dropwizard/dropwizard-views/src/main/java/datadog/trace/instrumentation/dropwizard/view/DropwizardViewInstrumentation.java, dd-java-agent/instrumentation/jax-rs-annotations-1/src/main/java/datadog/trace/instrumentation/jaxrs1/JaxRsAnnotationsInstrumentation.java, dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/JaxRsAnnotationsInstrumentation.java, dd-java-agent/instrumentation/ratpack-1.5/src/main/java8/datadog/trace/instrumentation/ratpack/TracingHandler.java, dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerAdapterInstrumentation.java
- add "_dd.measured": 1 metric 'jax-rs.request', 'ratpack.handler', 'spring.handler' method
- remove "_dd.measured": 1 from 'view.render' in DropwizardView
=> _dd.measured to 'jax-rs.request', 'ratpack.handler', 'spring.handler'

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java, dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java, dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java, dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/ProfilingIntegrationContinuousProfilesTest.groovy
* Make them warnings instead
* Also some renames to clarify code
=> Make profiling errors more clear and less scary

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
https://github.com/DataDog/jmxfetch/releases/tag/0.36.2
=> Upgrade jmxfetch to 0.36.2

dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/mlt/JMXSampler.java, dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java
Profiler API initialization before checking Profiler is enabled or
api key.
=> move Profiler API init

dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpClientInstrumentation.java, dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpServerInstrumentation.java, dd-java-agent/instrumentation/akka-http-10.0/src/test/groovy/AkkaHttpClientInstrumentationTest.groovy, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/DDSpanNames.java
=> Make client span have distinct name

dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
This applies the same change to OpenTracing32Test that was done to OpenTracing31Test in #1521
=> Fix OpenTracing32Test

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/NamedOneOfMatcher.java, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ExceptionHandlerTest.groovy, dd-java-agent/instrumentation/elasticsearch/rest-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/Elasticsearch5RestClientInstrumentation.java, dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/CriteriaInstrumentation.java, dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/QueryInstrumentation.java, dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/SessionFactoryInstrumentation.java, dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/SessionInstrumentation.java, dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/CriteriaInstrumentation.java, dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/QueryInstrumentation.java, dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/SessionFactoryInstrumentation.java, dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/SessionInstrumentation.java, dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/HttpUrlConnectionInstrumentation.java, dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java, dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2ResponseStatusInstrumentation.java, dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Instrumentation.java, dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseInstrumentation.java, dd-java-agent/instrumentation/spymemcached-2.12/src/main/java/datadog/trace/instrumentation/spymemcached/MemcachedClientInstrumentation.java, dd-java-agent/instrumentation/twilio/src/main/java/datadog/trace/instrumentation/twilio/TwilioAsyncInstrumentation.java, dd-java-agent/instrumentation/twilio/src/main/java/datadog/trace/instrumentation/twilio/TwilioSyncInstrumentation.java
This changes the complexity of evaluation of logical disjunctions of named rules from linear to constant.
=> introduce matcher for membership of a set of names

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java, dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
Please see #1582 for the equivalent configuration in the trace agent.
> When TLS was not configured in the JVM, the OkHttp client failed to
> start with java.lang.AssertionError: No System TLS despite the fact
> that we don't use TLS to communicate with the agent.
> This change fixes that issue by limiting the OkHttp client to http
> only.
=> Force cleartext connspec in the ProfilingUploader client

.circleci/config.yml, gradle.properties
this should speedup local builds
=> enable build cache

dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java, dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java, dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageListenerInstrumentation.java, dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageProducerInstrumentation.java
We currently have various small unit costs per class, I believe this removes the last instance of this pattern.
=> Remove anonymous classes from JMSDecorator

dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
Cherry picked from https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/558
=> Optimization for expensive type matcher

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
https://github.com/DataDog/jmxfetch/releases/tag/0.38.0
https://github.com/DataDog/jmxfetch/compare/0.36.2...0.38.0
=> Update jmxfetch to 0.38.0

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
This currently actually _increases_ the startup time for clojure koans on leiningen by 3 seconds (3s baseline, 13s on master, 16s on this branch, 37s prior to #1642).
=> improve startup performance for clojure apps

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java, dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerDepthTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
Simple change to allow turning off the scope depth limit
=> Turn off the scope depth limit when set to zero

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
smaller change compared to #1676
=> simplify disabled depth limit in ContinuableScopeManager

dd-trace-api/src/main/java/datadog/trace/api/Config.java, dd-trace-core/dd-trace-core.gradle, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
Logs diagnostic info in a standardised way. 
```json
{"os_name":"Mac OS X","os_version":"10.15.4","architecture":"x86_64","lang":"jvm","lang_version":"11.0.6","jvm_vendor":"AdoptOpenJDK","jvm_version":"11.0.6+10","java_class_version":"55.0","enabled":true,"service":"unnamed-java-app","agent_url":"http://localhost:8126","agent_error":false,"debug":false,"analytics_enabled":false,"sampling_rules":[{},{}],"priority_sampling_enabled":true,"logs_correlation_enabled":false,"profiling_enabled":false,"dd_version":"null","health_checks_enabled":false,"configuration_file":"no config file present","runtime_id":"b69deb26-8bc3-4c00-8952-d42bf8c2123b"}
```
=> log startup status

dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ListWriter.java, dd-trace-core/src/main/java/datadog/trace/common/writer/LoggingWriter.java, dd-trace-core/src/main/java/datadog/trace/common/writer/Writer.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingDisruptor.java, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, dd-trace-core/src/main/java/datadog/trace/core/interceptor/TraceHeuristicsEvaluator.java, dd-trace-core/src/main/java/datadog/trace/core/processor/TraceProcessor.java, dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java, dd-trace-core/src/main/java/datadog/trace/core/scopemanager/TraceProfilingScopeInterceptor.java, dd-trace-core/src/test/groovy/datadog/trace/core/interceptor/TraceHeuristicsEvaluatorTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/processor/MethodLevelTracingDataRuleTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/processor/TraceProcessorTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/TraceProfilingScopeInterceptorTest.groovy
Apparently histogram percentile calculation is relatively expensive, so we don't want to do it in the application thread.
=> MLT - Do heuristic processing off critical path

dd-java-agent/agent-mlt/src/main/java/com/datadog/mlt/sampler/ScopeManager.java, dd-java-agent/agent-mlt/src/main/java/com/datadog/mlt/sampler/ScopeStackCollector.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/IMLTChunk.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTChunk.java
This will allow for better root stack frame analysis.
=> MLT - Collect initial ("base") stacktrace for each MLT Scope.

dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java, dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
Reverts DataDog/dd-trace-java#1628
This has served its purpose.
=> Revert "add timestamp debug logging"

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
Otherwise can result in invalid classes being loaded which expect a unix environment.
=> Add guard to prevent UDS configuration on windows env

dd-java-agent/instrumentation/opentracing/src/main/java/datadog/trace/instrumentation/opentracing/DefaultLogHandler.java, dd-trace-ot/src/main/java/datadog/opentracing/DefaultLogHandler.java, dd-trace-ot/src/test/groovy/datadog/opentracing/DefaultLogHandlerTest.groovy
=> Check for error condition before setting ERROR_MSG

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java, dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
Also change the active span to the parent instead of the kafka producer span.
Added a test to exercise the native kafka producer... but there are other edge cases that could also be improved.
=> Enable Async Propagation of trace in Kafka producer callback

settings.gradle, utils/mlt-support/mlt-support.gradle, utils/mlt-support/src/main/java/com/datadog/mlt/io/AbstractLEB128Writer.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/ConstantPool.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/FrameElement.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/FrameSequence.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/IMLTChunk.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/LEB128ByteArrayReader.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/LEB128ByteBufferWriter.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/LEB128Writer.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTChunk.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTChunkCollector.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTConstants.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTReader.java, utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTWriter.java, utils/mlt-support/src/test/java/com/datadog/mlt/io/AbstractLEB128WriterTest.java, utils/mlt-support/src/test/java/com/datadog/mlt/io/ConstantPoolTest.java, utils/mlt-support/src/test/java/com/datadog/mlt/io/FrameElementTest.java, utils/mlt-support/src/test/java/com/datadog/mlt/io/FrameSequenceBuilder.java, utils/mlt-support/src/test/java/com/datadog/mlt/io/FrameSequenceTest.java, utils/mlt-support/src/test/java/com/datadog/mlt/io/IMLTChunkTest.java, utils/mlt-support/src/test/java/com/datadog/mlt/io/LEB128ByteArrayReaderTest.java, utils/mlt-support/src/test/java/com/datadog/mlt/io/MLTChunkBuilder.java, utils/mlt-support/src/test/java/com/datadog/mlt/io/MLTChunkTest.java, utils/mlt-support/src/test/java/com/datadog/mlt/io/MLTSerializationTest.java
Binary format described in https://docs.google.com/document/d/1GQFRVWi8oVKWAk2XvoEGW1_PceSKTuJld8BaVOnshaE
Co-authored-by: Jean-Philippe Bempel <jean-philippe.bempel@datadoghq.com>
Co-authored-by: Jaroslav Bachorik <jaroslav.bachorik@datadoghq.com>
Co-authored-by: Laplie Anderson <laplie.anderson@datadoghq.com>
=> Add the various MLT io classes - Used for serializing collected stacktraces

dd-java-agent/agent-mlt/src/main/java/com/datadog/mlt/sampler/JMXSampler.java
=> add catch for exceptions in sample method

.palantir/revapi.yml, dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy, dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/Monitor.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/Payload.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/PayloadDispatcher.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapper.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_4.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_5.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingDisruptor.java, dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java, dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java, dd-trace-core/src/main/java/datadog/trace/core/DDSpanData.java, dd-trace-core/src/main/java/datadog/trace/core/TagsAndBaggageConsumer.java, dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/EncodingCachingStrategies.java, dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/MessageFormatter.java, dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/Packer.java, dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/Util.java, dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentApiTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/api/writer/TraceMapperTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV05PayloadTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanSerializationTest.groovy, dd-trace-core/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
Implements discovery of the format made available here https://github.com/DataDog/datadog-agent/pull/5965
This has been verified to work with a manual integration test, but I have not updated the tests yet because they are "not very nice" to modify.
TODO 
* add v0.5 integration test once agent changes are finalised and released
=> trace agent v0.5

.circleci/config.yml, dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java, dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java, dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java, dd-trace-core/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy, internal-api/src/main/java/datadog/trace/api/Config.java
will convert to reviewable once the trace agent is released
=> trace agent v0.5 integration tests

gradle/dependencies.gradle
https://github.com/raphw/byte-buddy/compare/byte-buddy-1.10.10...byte-buddy-1.10.14
=> Update Byte Buddy to 1.10.14

dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyRequestExtractAdapter.java
Use lower level `MimeHeaders` instead.
=> don't use getHeader in GrizzlyRequestExtractAdapter

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/PortUtils.java
Hold on to the ports a bit longer and also wait for them to be closed before we start the web server to try to avoid things like this:
```
javax.ws.rs.ProcessingException: Failed to start Grizzly HTTP server: Address already in use
at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:270)
at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:93)
at GrizzlyIOStrategyTest.startServer(GrizzlyIOStrategyTest.groovy:15)
at datadog.trace.agent.test.base.HttpServerTest.setupSpec(HttpServerTest.groovy:69)
Caused by: java.net.BindException: Address already in use
at sun.nio.ch.Net.bind(Net.java:433)
at sun.nio.ch.Net.bind(Net.java:425)
at …
```
=> Try to avoid test port collisions

.github/workflows/gradle-wrapper-validation.yml
Continuing #1795 from @sullis 
https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action
=> Enable Gradle wrapper validation 

.circleci/config.yml, dd-trace-core/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
Use the released version of the agent in integration tests
=> update agent docker image for integration testing

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java, dd-trace-api/src/main/java/datadog/trace/api/DDId.java, dd-trace-api/src/main/java/datadog/trace/api/IdGenerationStrategy.java, dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java, dd-trace-api/src/test/groovy/datadog/trace/api/DDIdTest.groovy, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceGenerator.groovy, internal-api/src/main/java/datadog/trace/api/Config.java, internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java, internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
to make debugging and asserting about concurrent context propagation easier
=> pluggable id strategies

CONTRIBUTING.md
Added troubleshooting for `netty-transport-native-epoll-4.1.43.Final-linux-x86_64.jar` error in `CONTRIBUTING.md` doc.
=> Add troubleshooting for netty dep error.

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/TestDecorator.java, dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/TestDecoratorTest.groovy
Filter out the token in `git.repository_url` tag from test spans
=> Ci-App: Filter out token in `git.repository_url` tag from test spans

dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java, dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterTest.groovy, dd-trace-ot/src/test/groovy/datadog/opentracing/DDTracerTest.groovy
Fix NPE for DDAgentWriter default builder with default monitoring
=> Fix NPE for DDAgentWriter default builder with default monitoring

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
Clear message for when HelperInjector cant create a temp folder
=> Better messaging around unwritable temp folder

dd-trace-core/src/main/java/datadog/trace/core/monitor/Monitoring.java
So use noop statsd client like we do in other places
=> Monitoring counters expect statsd to exist

.circleci/config.yml, dd-java-agent/instrumentation/akka-http-10.0/src/test/groovy/AkkaHttpClientInstrumentationTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy, dd-java-agent/testing/src/main/java/datadog/trace/agent/test/utils/UnsafeUtils.java, gradle/dependencies.gradle, gradle/wrapper/gradle-wrapper.properties
=> Java 15 tests

dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatSettings.java, dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/DDLoggerTest.groovy
Using `try` with resources is nice, but I messed up and the log file was closed before being used ☹️
=> Don't close the log file early

dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
this adds a lot of noise so only log this at debug level
=> remove noisy class path element from status logger

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
A lot of these (fortunately) never get used, yet create background cleanup tasks. This PR initialises the weak map in `FieldBackedProvider` lazily, which requires that it be volatile, and fortunately volatile reads are basically free on x86 so this causes no performance impact except for the initialisation itself.
The synchronization instance required for the generated synchronized block now uses a private final `Object`.
I verified with Spring petclinic that `WeakMap`s are created for `Runnable` and for `Callable`, but no longer for the various instrumentations activated by the application (e.g Hibernate `SessionState` and `HttpServletRequest` no longer cause `WeakMap` creation with these changes).
=> initialise often unused WeakMap in FieldBackedProvider lazily

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/TestDecorator.java, dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/TestDecoratorTest.groovy, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java
Add `ci.pipeline.name` tag to test spans.
=> Add ci.pipeline.name tag to test spans

dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV05PayloadTest.groovy
These tests aim to demonstrate in a targeted way that each kind of buffer overflow event in the trace agent v0.5 serialisation result in valid messages.
=> add tests for trace agent v0.5 overflow scenarios

internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
This "test" doesn't test anything and just creates more work
=> Remove verify defaults test

utils/thread-utils/src/main/java/datadog/common/exec/AgentTaskScheduler.java
Handle edge-case where we're trying to register our shutdown hook while the JVM is shutting down. When this happens we'll get an `IllegalStateException` which we shouldn't propagate. Instead we log a warning that the scheduler is shutting down.
=> Avoid log spam if JVM shuts down exactly as we're starting the agent task scheduler

utils/thread-utils/src/main/java/datadog/common/exec/AgentTaskScheduler.java
This avoids a potential loop-back where the worker calling 'take' could trigger a transformation event
which would cause ByteBuddy to do instrumentation matching. That could go on to trigger class loading
in Datadog's class loaders, which may lead to internal exceptions, which are picked up by the exception
profiler.
If this happens when another thread is also throwing an exception that's being profiled the scheduled
worker thread can end up waiting on the exception profiler, while the exception profiler is waiting to
send work to the scheduled worker.
=> Make sure DelayQueue internal types are preloaded before starting the tracer's scheduled worker thread

dd-java-agent/instrumentation/apache-httpasyncclient-4/src/test/groovy/ApacheHttpAsyncClientCallbackTest.groovy, dd-java-agent/instrumentation/vertx/src/test/groovy/client/VertxHttpClientTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java, dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java, dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
This is to avoid blocking forever when an exception is thrown in the callback.
Other misc minor changes
=> Add failure handling for completableFuture in test

dd-java-agent/instrumentation/hibernate/core-4.3/core-4.3.gradle
Test are failing, Otel has done this https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1522
=> Hibernate instrumentation no longer works with latest spring JPA

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java, dd-java-agent/testing/src/test/groovy/context/FieldBackedProviderTest.groovy, dd-java-agent/testing/src/test/java/context/ContextTestInstrumentation.java
Reverts DataDog/dd-trace-java#2065
=> Revert "`FieldBackedProvider` should avoid modifying `Serializable` classes without `serialVersionUID`"

dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy
NB: fairly sure we don't want a `ForkJoinTask` field injected into this class...
=> make field injection smoke test break if CompletableFuture injection breaks

buildSrc/src/main/groovy/MuzzlePlugin.groovy
As an example `:dd-java-agent:instrumentation:netty-4.1:muzzle` goes from `232` to `158` tasks (which in itself is insane).
=> Add some more filtering to muzzle and limit the inverse directives

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java, internal-api/src/main/java/datadog/trace/util/AgentTaskScheduler.java
This causes very noisy logging especially now we use this as caffeine's executor
=> log at debug level in AgentTaskScheduler

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
We apparently take a global lock for every class load
=> use ConcurrentHashMap instead of synchronized HashMap for class load callbacks

dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AggregateMetricTest.groovy
Sometimes all the writers and the main thread finish before the reader is finished leading to test failures.
=> Wait for reader in AggregateMetricsTest to finish

dd-java-agent/instrumentation/datastax-cassandra-3/src/test/groovy/CassandraClientTest.groovy
This fixes the race with `callbackExecuted.get()` and the completion of the trace by using a `CountDownLatch`.  Additionally, I prophylactically changed the test to use a random port even though port conflicts haven't historically been an issue with this test.
=> Fix CassandraClientTest flakiness

dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/RouteHandlerWrapper.java, dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/VertxHttpServerTest.groovy, dd-java-agent/instrumentation/vertx-web-3.4/src/test/java/server/VertxChainingTestServer.java
I was able to rip out my custom test by copying ratpack
=> Support vertx chained handlers

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGradlePlugin.java
`MuzzleGradlePlugin` tells ByteBuddy which classes to add muzzle refs to at compile time (**_terrible_** naming for this class BTW).  This PR cleans up our custom class hierarchy walking with simple matchers.
Cherry-Picked from #1690 since that PR is closed.
=> Cleanup muzzle (bytebuddy) plugin

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ClientDecorator.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DBTypeProcessingDatabaseClientDecorator.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecorator.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/OrmClientDecorator.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ServerDecorator.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/TestDecorator.java, dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/BaseDecoratorTest.groovy, dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecoratorTest.groovy, dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecoratorTest.groovy, dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecoratorTest.groovy, dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/OrmClientDecoratorTest.groovy
When you get a hostname from an `InetAddress` there is a risk the code below will be run, which does a DNS lookup:
```java
/**
* Returns the hostname for this address.
*
* <p>If there is a security manager, this method first
* calls its {@code checkConnect} method
* with the hostname and {@code -1}
* as its arguments to see if the calling code is allowed to know
* the hostname for this IP address, i.e., to connect to the host.
* If the operation is not allowed, it will return
* the textual representation of the IP address.
*
* @return  the host name for this IP address, or if the operation
*    is not allowed by the security check, the textual
*    representation of the IP address.
*
* @param check make security check if true
*
* @see SecurityManager#checkConnect
*/
private static String …
```
=> Don't call getHostName() on unresolved addresses

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java, dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
Customers have reported that they see warnings for profile upload
failures in their application logs, coming from `dd-trace-java`.
However, the data is uploaded successfully and is available in the
Datadog app.
We see a similar behaviour internally with services configured to
send profiling data to multiple targets, we see failure warnings
in the logs, but the data is uploaded successfully and available
in the UI.
The cause of the problem is a timeout in the datadog-agent http server:
whenever the profile upload request takes longer than the 5s timeout
we have configured at present, the http server in `datadog-agent`
gracefully closes the connection, `dd-trace-java` sees an empty reply
from server and triggers the UnexpectedEndOfStream exception which is
logged.
This is more likely to …
=> Handle unexpected end of stream explicitly in ProfileUploader

dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java, dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java, dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java, dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Instrumentation.java, dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy, dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseInstrumentation.java
It isn't really needed since the advice already has a call depth check.
=> Remove `HttpServletResponse` InstrumentationContext

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java, dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseInstrumentation.java, dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/server/HandlerAdapterAdvice.java, dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/server/RouteOnSuccessOrError.java, dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/SpringWebHttpServerDecorator.java
These didn't match the regex I used to find the others in #2223, but these seem to be the last of that pattern.
=> remove remaining resource names set via tag

gradle/wrapper/gradle-wrapper.properties
Specifically interested in this change: https://github.com/gradle/gradle/issues/14960
=> Update Gradle to 6.8

internal-api/src/test/groovy/datadog/trace/api/RateLimitedLoggerTest.groovy
according to [this](http://spockframework.org/spock/docs/1.0/spock_primer.html) this shouldn't make any difference
=> remove shared mutable state in RateLimitedLoggerTest

dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy, dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TestServlet3.groovy, dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
We spend a lot of time sleeping in servlet tests, this PR investigates whether this time can be reduced.
=> shorten sleeps in servlet tests

dd-java-agent/instrumentation/jax-rs-client-2.0/src/test/groovy/JaxMultithreadedClientTest.groovy
`JaxMultithreadedClientTest` is flakey, but it's actually a symptom of CI being overloaded - see (now trimmed down) [logs](https://123049-89221572-gh.circle-artifacts.com/0/reports/dd-java-agent/instrumentation/jax-rs-client-2.0/tests/testJavaZULU11Generated/classes/JaxMultithreadedClientTest.html). This treats `ConnectException` as not caused by our instrumentation.
=> Don't fail JaxMultithreadedClientTest on ConnectException

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DriverInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
Accesses to the WeakHashMap show up in profiles - this is a simple fix for a small inefficiency.
=> Store dbinfo in Connection context store

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, gradle/dependencies.gradle
Reverts DataDog/dd-trace-java#2301
This seems to have caused gradually increasing CPU usage.
=> Revert "Update java-dogstatsd-client to 2.11.0"

dd-java-agent/instrumentation/aerospike-4/src/test/groovy/datadog/trace/instrumentation/aerospike4/AerospikeBaseTest.groovy, dd-java-agent/instrumentation/elasticsearch/transport-7.3/src/test/groovy/Elasticsearch73NodeClientTest.groovy, dd-java-agent/instrumentation/elasticsearch/transport-7.3/src/test/groovy/Elasticsearch73TransportClientTest.groovy, dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/CriteriaTest.groovy, dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/QueryTest.groovy, dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/SessionTest.groovy, dd-java-agent/instrumentation/hibernate/core-4.0/src/test/groovy/CriteriaTest.groovy, dd-java-agent/instrumentation/hibernate/core-4.0/src/test/groovy/QueryTest.groovy, dd-java-agent/instrumentation/hibernate/core-4.0/src/test/groovy/SessionTest.groovy, dd-java-agent/instrumentation/hibernate/core-4.3/src/test/groovy/ProcedureCallTest.groovy, dd-java-agent/instrumentation/hibernate/core-4.3/src/test/groovy/SpringJpaTest.groovy, dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy, dd-java-agent/instrumentation/jedis-1.4/src/test/groovy/JedisClientTest.groovy, dd-java-agent/instrumentation/jedis-3.0/src/test/groovy/Jedis30ClientTest.groovy, dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/MongoClientTest.groovy, dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ClientTest.groovy, dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ReactiveClientTest.groovy, dd-java-agent/instrumentation/mongo/driver-async-3.3/src/test/groovy/MongoAsyncClientTest.groovy, dd-java-agent/instrumentation/rediscala-1.8.0/src/test/groovy/RediscalaClientTest.groovy, dd-java-agent/instrumentation/spymemcached-2.12/src/test/groovy/datadog/trace/instrumentation/spymemcached/SpymemcachedTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/SpanAssert.groovy
this dictates whether metrics are computed or not
=> assert database and cache spans are top level when expected to be

dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
The code coverage of `ConflatingMetricsAggregator.ReportTask` fails on my machine sometimes, since if the tests run quick, `ReportTask` never gets to run, and there is no coverage of its `run` method.
=> Ensure code coverage of ConflatingMetricsAggregator.ReportTask

dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
Noticed that I messed up a bit and always do two `yeild()` during the flushing of the `PendingTraceBuffer`. Only affects test code.
=> Limit yields during pending trace flush in test

dd-java-agent/instrumentation/exception-profiling/src/test/java/com/datadog/profiling/exceptions/StreamingSamplerTest.java
This test is one of the tests that can take ages on the CI, and it's probably because it allocates a ton of transient objects to calculate a mean. And by a ton, I mean (pun intended) 3.5-4.5 GiB/s continuously for 13 seconds on my laptop. The total number of collections dropped from 203 to 34 with this change.
=> Allocate fewer transient objects in StreamingSamplerTest

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExcludeFilter.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExecutorInstrumentationUtils.java, dd-java-agent/instrumentation/aerospike-4/src/main/java/datadog/trace/instrumentation/aerospike4/NioEventLoopInstrumentation.java
This should solve the issue in #2366
=> Use exclude filter for tasks to benefit from caching

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java
This change registers the new wrapper types we're using to make sure they aren't field injected unnecessarily and to make sure we don't wrap twice.
=> avoid double wrapping or transforming wrapper types

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategy.java, gradle/dependencies.gradle
Reverts DataDog/dd-trace-java#2373
=> Revert "update byte-buddy to 1.10.20"

dd-java-agent/instrumentation/finatra-2.9/src/test/groovy/FinatraServerTest.groovy, dd-java-agent/instrumentation/finatra-2.9/src/test/scala/FinatraServer.scala
Among the top 3 failing ones right now. Times out during server start.
=> Don't spin wait for test FinatraServer to start

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ConcurrentState.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/State.java, dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
This reduces the weight of these classes slightly without changing semantics
=> replace atomics with volatile primitives in state and continuation

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExcludeFilter.java, dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java
There is no point in propagating through these tasks
=> do not transform CHM internal fork join tasks

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/FieldBackedContextStores.java, dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/SampleJavaClass.java, dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/VersionInfo.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/SafeHasSuperTypeMatcher.java, dd-java-agent/instrumentation/java-concurrent/src/test/java/ComparableAsyncChild.java, dd-java-agent/instrumentation/kotlin-coroutines/src/test/kotlin/KotlinCoroutineTests.kt, dd-java-agent/src/test/java/jvmbootstraptest/LogLevelChecker.java, dd-java-agent/src/test/java/jvmbootstraptest/LogManagerSetter.java, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/server/http/TestHttpServer.groovy, dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/ProfilingTestApplication.java, dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricKey.java, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogHttpCodec.java, dd-trace-core/src/main/java/datadog/trace/core/propagation/HaystackHttpCodec.java, dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/SmokeTest.java, dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/StringWritingTest.java, dd-trace-java.gradle, gradle/java.gradle, gradle/spotbugFilters/exclude.xml, gradle/spotbugs.gradle, internal-api/src/main/java/datadog/trace/api/Config.java, internal-api/src/main/java/datadog/trace/util/AgentTaskScheduler.java, utils/test-utils/src/main/java/datadog/trace/test/util/GCUtils.java
I added configurations to run spot bugs (`./gradlew spotbugsMain`) with some unnecessary detectors omitted. Most of the detectors, although may report false positives, seems relatively useful so I left it as is. Please let me know if I should add further configs to make it more fine tuned.
=> Added spotbugs task and configuration

.github/workflows/add-milestone-to-pull-requests.yaml
=> Fix milestone workflow

utils/histograms/histograms.gradle, utils/histograms/src/test/groovy/DDSketchHistogramTest.groovy
Picks up a [bug fix](https://github.com/DataDog/sketches-java/pull/41) and adds a test which would have caught this here.
=> upgrade DDSketch

dd-java-agent/instrumentation/reactor-core-3.1/src/main/java/datadog/trace/instrumentation/reactor/core/ReactorHooksInstrumentation.java, dd-java-agent/instrumentation/reactor-core-3.1/src/main/java/datadog/trace/instrumentation/reactor/core/TerminalSubscriberInstrumentation.java, dd-java-agent/instrumentation/reactor-core-3.1/src/main/java8/datadog/trace/instrumentation/reactor/core/TerminalSubscriberAdvices.java, dd-java-agent/instrumentation/reactor-core-3.1/src/main/java8/datadog/trace/instrumentation/reactor/core/TracingOperator.java, dd-java-agent/instrumentation/reactor-core-3.1/src/main/java8/datadog/trace/instrumentation/reactor/core/TracingSubscriber.java
=> various reactor instrumentation cleanups

dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientDecorator.java, dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/client/TraceWebClientSubscriber.java, dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/client/WebClientTracingFilter.java
=> webflux client cleanup

gradle/dependencies.gradle
https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.10.22
=> Upgrade bytebuddy to 1.10.22

dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/AttributeKeys.java, dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/AttributeKeys.java
@anuraaga has spotted a nice `WeakMap` removal opportunity in [opentelemetry](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2559) which can be applied here too.
=> replace WeakMap with ClassValue

dd-java-agent/instrumentation/reactor-core-3.1/src/main/java/datadog/trace/instrumentation/reactor/core/TaskClassInitDisableInstrumentation.java, dd-java-agent/instrumentation/reactor-core-3.1/src/main/java8/datadog/trace/instrumentation/reactor/core/DisableAsyncAdvice.java, dd-java-agent/instrumentation/spring-webflux-5/spring-webflux-5.gradle, dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/groovy/SingleThreadedSpringWebfluxTest.groovy, dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/groovy/SpringWebfluxTest.groovy, dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/groovy/dd/trace/instrumentation/springwebflux/server/SpringWebFluxTestApplication.groovy
**Submitter please read!**
[NO] are you making any modifications to a non thread-safe data structure in a method or an advice that might happen on multiple theads at the same time?
=> Add unit tests for spring-boot-webflux 2.4

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
https://github.com/aws/amazon-redshift-jdbc-driver/blob/master/src/main/java/com/amazon/redshift/jdbc/RedshiftConnectionImpl.java
https://github.com/aws/amazon-redshift-jdbc-driver/blob/master/src/main/java/com/amazon/redshift/jdbc/RedshiftPreparedStatement.java
=> Add support for redshift JDBC

dd-java-agent/instrumentation/axway-api/src/main/java/datadog/trace/instrumentation/axway/AxwayHTTPPluginDecorator.java
**Submitter please read!**
[no] are you making any modifications to a non thread-safe data structure in a method or an advice that might happen on multiple theads at the same time?
=> Remove lombok from axway

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
=> make sure bytebuddy raw setting is set early enough to work

dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/HostAndRequestAsHttpUriRequest.java, dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/HttpHeadersInjectAdapter.java, dd-java-agent/instrumentation/okhttp-2/src/main/java/datadog/trace/instrumentation/okhttp2/RequestBuilderInjectAdapter.java, dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/RequestBuilderInjectAdapter.java
Related: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2594
=> Prefer methods that avoid duplicate header values

dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricsAggregator.java, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
=> close metrics aggregator when CoreTracer is closed

dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
also reduce the number of class loads required
=> Log status asynchronously to prevent running in premain

.gitlab-ci.yml
This will be triggered manually for now, but later will be scheduled to align with key expiration.
=> Add job to generate signing keys

.gitlab-ci.yml
Previous yaml failed to validate and caused gitlab ci to fail.
=> Fix create_key script and enable publishing to keyserver

dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageExtractAdapter.java, dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageInjectAdapter.java, dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java, internal-api/src/main/java/datadog/trace/api/Config.java
=> revert JMS propagation changes to avoid breaking SQS senders

.github/pull_request_template.md
=> Remove GitHub Pull Request template

dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGDecorator.java, dd-java-agent/instrumentation/testng-6.4/src/test/groovy/TestNGTest.groovy, dd-java-agent/instrumentation/testng-6.4/src/test/java/org/example/TestParameterized.java
Add `test.parameters` tag to TestNG tests.
=> [CIAPP] Add test.parameters tag to TestNG tests

gradle/publish.gradle
It is causing problems locally when on a tagged commit and not actually trying to publish.
=> Remove publishing assert

.gitlab-ci.yml
Adds the ability to run a specific reliability env branch as the downstream pipeline
=> Add ability to specify reliability-env branch

internal-api/internal-api-8/src/main/java/datadog/trace/api/sampling/AdaptiveSampler.java
A small improvement which prevents allocating a new helper class each time a sampler window is rolled (usually 10-100ms).
=> Reduce allocations of helper counts instances

dd-java-agent/instrumentation/jedis-3.0/src/test/groovy/Jedis30ClientTest.groovy
Add tests for hmset/hgetAll and zadd/zrangeByScore
=> Add more Jedis tests

dd-java-agent/instrumentation/glassfish/src/test/groovy/GlassFishServerTest.groovy, dd-java-agent/instrumentation/jetty-9/src/test/groovy/Jetty9Test.groovy, dd-java-agent/instrumentation/servlet/request-2/src/test/groovy/JettyServlet2Test.groovy, dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/CustomBeanClassloaderTest.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SpringBootBasedTest.groovy, dd-java-agent/instrumentation/tomcat-5.5/src/latestDepTest/groovy/AbstractServletTest.groovy, dd-java-agent/instrumentation/tomcat-5.5/src/test/groovy/AbstractServletTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServer.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/WithHttpServer.groovy
Demonstrate change with Jetty9Test
=> Refactor WithHttpServer to allow random port

dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/HttpUrlConnectionInstrumentation.java, dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/UrlInstrumentation.java
The matcher here actually specified the contents of some packages, so I just took the class names from those packages.
=> simplify HTTPUrlConnection matchers

dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpServerInstrumentationTest.groovy, dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/scala/AkkaHttpTestWebServer.scala, dd-java-agent/instrumentation/akka-http-10.0/src/latestDepTest/groovy/AkkaHttp102ServerInstrumentationTests.groovy, dd-java-agent/instrumentation/play-2.3/src/test/groovy/server/PlayAsyncServerTest.groovy, dd-java-agent/instrumentation/play-2.3/src/test/groovy/server/PlayServerTest.groovy, dd-java-agent/instrumentation/play-2.3/src/test/scala/server/AsyncServer.scala, dd-java-agent/instrumentation/play-2.3/src/test/scala/server/SyncServer.scala, dd-java-agent/instrumentation/play-2.4/src/test/groovy/server/PlayAsyncServerTest.groovy, dd-java-agent/instrumentation/play-2.4/src/test/groovy/server/PlayHttpServer.groovy, dd-java-agent/instrumentation/play-2.4/src/test/groovy/server/PlayServerTest.groovy, dd-java-agent/instrumentation/play-2.6/src/test/groovy/server/PlayAsyncServerTest.groovy, dd-java-agent/instrumentation/play-2.6/src/test/groovy/server/PlayHttpServer.groovy, dd-java-agent/instrumentation/play-2.6/src/test/groovy/server/PlayServerTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/WithHttpServer.groovy
Also added some asserts to catch problems earlier on.
=> Random open port refactoring for Akka and Play tests

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
Avoid another use of `Pattern` in the startup code...
=> Replace regex Pattern with simple startWith+endsWith

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java, dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
This needs some discussion, since I'm not sure what effect this will have on the measured times.
=> Do not activate the ExtendedScopeListener for NoopAgentSpan

dd-java-agent/instrumentation/commons-httpclient-2/src/main/java/datadog/trace/instrumentation/commonshttpclient/CommonsHttpClientInstrumentation.java
This is a concrete class. It's not final, but I can't find any implementations of it either.
=> simpler matcher for HttpClient

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/ignite/IgniteQueryInfo.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/AdditionalLibraryIgnoresMatcher.java, dd-java-agent/instrumentation/ignite-2.0/ignite-2.0.gradle, dd-java-agent/instrumentation/ignite-2.0/src/main/java/datadog/trace/instrumentation/ignite/v2/IgniteInstrumentation.java, dd-java-agent/instrumentation/ignite-2.0/src/main/java/datadog/trace/instrumentation/ignite/v2/cache/AbstractIgniteCacheInstrumentation.java, dd-java-agent/instrumentation/ignite-2.0/src/main/java/datadog/trace/instrumentation/ignite/v2/cache/IgniteCacheAsyncInstrumentation.java, dd-java-agent/instrumentation/ignite-2.0/src/main/java/datadog/trace/instrumentation/ignite/v2/cache/IgniteCacheDecorator.java, dd-java-agent/instrumentation/ignite-2.0/src/main/java/datadog/trace/instrumentation/ignite/v2/cache/IgniteCacheSyncInstrumentation.java, dd-java-agent/instrumentation/ignite-2.0/src/main/java/datadog/trace/instrumentation/ignite/v2/cache/SpanFinishingCallback.java, dd-java-agent/instrumentation/ignite-2.0/src/test/groovy/test/AbstractIgniteTest.groovy, dd-java-agent/instrumentation/ignite-2.0/src/test/groovy/test/IgniteCacheAsyncTest.groovy, dd-java-agent/instrumentation/ignite-2.0/src/test/groovy/test/IgniteCacheFailureTest.groovy, dd-java-agent/instrumentation/ignite-2.0/src/test/groovy/test/IgniteCacheSyncTest.groovy, dd-java-agent/instrumentation/ignite-2.0/src/test/groovy/test/Person.groovy, dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java, internal-api/src/main/java/datadog/trace/api/Config.java, settings.gradle
Add support for Ignite Cache 2.0 and later
=> Ignite Cache Support

dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractTestAgentSmokeTest.groovy
Add port selection for test agent and change test agent to a new version with that enabled
=> Add port selection for test agent

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/JDBCConnectionUrlParser.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCConnectionUrlParserTest.groovy
Add explicit references to the JTDS Connection and PreparedStatement classes.
=> JDBC: Add support for JTDS Driver

dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java, dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java, dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java, dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java, dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDClientManager.java, dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDConnection.java, dd-trace-core/src/main/java/datadog/trace/core/monitor/LoggingStatsDClient.java, internal-api/internal-api.gradle, internal-api/src/main/java/datadog/trace/api/Config.java, internal-api/src/main/java/datadog/trace/api/Platform.java, internal-api/src/main/java/datadog/trace/api/StatsDClientManager.java, internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
* Add `DD_DOGSTATSD_PORT`/`HOST` as an alias for `DD_JMXFETCH_STATSD_PORT`/`HOST`
* Auto-detect `/var/run/datadog/apm.socket` and `/var/run/datadog/dsd.socket`
=> Onboarding improvements

dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentFeaturesDiscovery.java, dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDClientManager.java, dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDConnection.java
Recent trace agents include the StatsD port in their /info endpoint. When this information is available we use it to update the default StatsD port in the tracer. This will help with migration to a single port (TCP+UDP) for both trace and StatsD metrics.
If the StatsD port is changed on the agent while the tracer has an open StatsD client using the old default port then the tracer will close and re-open the client using the new default.
=> Discover StatsD port from trace agent /info endpoint

dd-java-agent/instrumentation/jetty-7.0/src/test/groovy/Jetty70Test.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
Statement asserts don't work inside if blocks.
=> Fix assertion

dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java, dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/SafeToLoadJFRCheckpointerTest.groovy
=> make sure JFRCheckpointer does not load on JDKs which do not support JFR

dd-trace-core/src/test/groovy/datadog/trace/core/monitor/HealthMetricsTest.groovy
This was failing when CI was overloaded because the sleep wasn't long enough to allow the metrics to report.
=> Remove sleep from HealthMetricsTest

dd-smoke-tests/quarkus/application/build.gradle, dd-trace-java.gradle, gradle/spotless.gradle, test-published-dependencies/build.gradle
Update spotless gradle plugin to 5.12.5 to pick up fix for https://github.com/diffplug/spotless/issues/835
=> spotless gradle plugin 5.12.5

dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java, dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ProfilingSystemTest.java
A simple change adding more descriptive message when we fail start profiling due to missing JVM arguments on Oracle JDK.
=> Provide better log message when Oracle JFR is not enabled.

dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatServerInstrumentation.java
I have seen a lot of contention on the `SynchronizedStack.push` in `NioEndpoint$SocketProcessor.doRun` during warmup, but not once the application is warmed up. 
```java
protected class SocketProcessor extends SocketProcessorBase<NioChannel> {
public SocketProcessor(SocketWrapperBase<NioChannel> socketWrapper, SocketEvent event) {
super(socketWrapper, event);
}
@Override
protected void doRun() {
NioChannel socket = socketWrapper.getSocket();
SelectionKey key = socket.getIOChannel().keyFor(socket.getPoller().getSelector());
try {
int handshake = -1;
try {
if (key != null) {
if (socket.isHandshakeComplete()) {
// No TLS handshaking required. Let the handler
// process this socket / event combination.
handshake = 0;
} else if (event == SocketEvent.STOP || event == SocketEvent.DISCONNECT || …
```
=> exclude some low level tomcat classes from instrumentation

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
Don't let exceptions from misbehaving class loaders propagate.
=> Be more defensive about resource loading

dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/server/AdviceUtils.java
* port https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3150/files
* cleanup dead code in the file
=> Fix WebFlux flaky tests + cleanup

dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/ProfilingIntegrationTest.java
The test is modified to use the target process log file instead of waiting for very long time to make sure no uploads were made.
The log file check is not optimal (reparsing the whole log several time) but still faster than waiting for 90s. If the extra parsing turns out to be a problem we might consider piping the test process stdout through a checker before writing it out to the log file.
=> Speed up the profiling bogus API key smoke test

.circleci/config.yml
Based on this guide https://circleci.com/blog/managing-secrets-when-you-have-pull-requests-from-outside-contributors via @juan-fernandez
=> Don't upload test results for forks since it needs credentials

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExcludeFilter.java, dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/ExcludeFilterTest.groovy, dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/main/java/datadog/trace/instrumentation/java/completablefuture/CompletableFutureUniCompletionInstrumentation.java, dd-java-agent/testing/src/test/groovy/excludefilter/ExcludeFilterForkedTest.groovy, dd-java-agent/testing/src/test/java/excludefilter/ExcludeFilterTestInstrumentation.java
We don't instrument callables or futures any more
=> clean up exclude filters

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/SpockRunner.java
Unfortunately the Intellij test runner will reflectively query for methods on the test class when running a specific test.  This causes a lot of classes to load that shouldn't, resulting in confusing error messages. This attempts to reduce the confusion by verifying this earlier.
=> Verify no bootstrap classes are loaded prematurely

dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/server/AdviceUtils.java
Re-Cherry picked from https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3150, but with changes from #2791 applied. We were missing a very important part that made the prior changes do nothing.
(Thanks @laurit for the original fix and helping to identify the problem here.)
=> Fix flaky spring webflux tests

dd-java-agent/instrumentation/kafka-clients-0.11/kafka-clients-0.11.gradle, dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/KafkaClientTest.groovy, dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/TextMapExtractAdapterTest.groovy
Kafka Streams seems to have other underlying changes that impact the tests.
=> Update Kafka Client latestDepTests

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java, dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/ScopeEvent.java, dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/ScopeEventFactory.java, dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ScopeEventTest.groovy, dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_4.java, dd-trace-core/src/main/java/datadog/trace/core/serialization/Writable.java, dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/MsgPackWriter.java, dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceGenerator.groovy
=> Cherry pick commits for 0.81.1 release

dd-java-agent/instrumentation/hazelcast-3.6/src/test/groovy/test/hazelcast/v3/HazelcastTest.groovy, dd-java-agent/instrumentation/hazelcast-3.9/src/test/groovy/test/hazelcast/v39/HazelcastTest.groovy, dd-java-agent/instrumentation/hazelcast-4.0/src/test/groovy/test/hazelcast/v4/HazelcastTest.groovy
Hazelcast span can come in quite delayed it seems, so avoid the problem by sorting.
Also formatting.
=> Add span sort for Hazelcast async test

dd-java-agent/instrumentation/ignite-2.0/ignite-2.0.gradle
The tests don't compile at the moment
=> Add upper bound to latestDepTest for ignite

.circleci/config.yml, dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/EventDispatcher.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/OrderedCallback.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/NoopFlow.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java, dd-java-agent/appsec/weblog/weblog-spring-app/src/main/groovy/io/sqreen/testapp/sampleapp/SaSdkController.groovy, dd-java-agent/appsec/weblog/weblog-spring-app/src/main/groovy/io/sqreen/testapp/sampleapp/posts/PostRepository.groovy
~~This is based on top of #2862 to get the build changes needed. Will rebase after it's been merged.~~
=> [AppSec] Minor code style changes

dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java, dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java, dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricsAggregatorFactory.java, dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentFeaturesDiscovery.java
=> debug logging for metrics system

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
as it's not necessary now we always delay starting JMX and just complicates class-loading
=> Remove pre-load of JMX

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/Wrapper.java, dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy, dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java
This one already worked fine, should be merged after #2893
=> Remove grpc netty context leak, verify correct gRPC checkpoints are emitted

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TimelineCheckpointer.groovy, dd-java-agent/testing/testing.gradle
This creates diagrams of thread activity for every agent test, which gives a visual understanding of how our instrumentation and async propagation works. 
This shows us where activity tracking makes sense, e.g. a sequence of 50 successful netty requests
```
nioEventLoopGroup-54-1:  |--------------|--------------|------------|------------|--------------|--------------|------------|------------|--------------|--------------|------------|------------|--------------|--------------|------------|------------|--------------|--------------|------------|------------|--------------|--------------|------------|------------|--------------|--------------|------------|------------|--------------|--------------|------------|------------|--------------|------ …
```
=> create activity diagram for every instrumentation test

dd-trace-ot/dd-trace-ot.gradle
=> Bundle new communication module with dd-trace-ot

dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java, dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
=> accept null throwable in DDSpan

dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/EventDispatcher.java
Results improve substantially for a low number of subscriptions: https://gist.github.com/cataphract/d1f6a4b3915b27a8aa47d0d0f7a010e4
=> Optimize appsec subscriber lookup

dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcServerBuilderInstrumentation.java, dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
I haven't dug in to what was different in the latest gRPC version but this fixes the test.
=> fix GrpcTest on latestDepTest

dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
The thread activity of the request/response flow test doesn't seem to be deterministic which makes the test flaky, but we just need the counts to balance.
=> make flaky checkpoints test more robust

internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/CIProviderInfo.java
=> [CIAPP] Fix NPE when `workspace` path cannot be detected

dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpServerInstrumentationTest.groovy, dd-java-agent/instrumentation/apache-httpasyncclient-4/src/test/groovy/CheckpointEmissionTest.groovy, dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy, dd-java-agent/instrumentation/jdbc/src/test/groovy/RemoteJDBCInstrumentationTest.groovy, dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5AsyncClientTest.groovy, dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ClientTest.groovy, dd-java-agent/instrumentation/netty-4.1/src/test/groovy/NettyClientCheckpointsTest.groovy
…which prevent the TimelineCheckpointer from seeing the checkpoints. The property based assertions are more useful anyway.
=> remove asserts on checkpoint interceptions 

dd-java-agent/instrumentation/scala-concurrent/src/main/java/datadog/trace/instrumentation/scala/concurrent/ScalaForkJoinTaskInstrumentation.java
This fixes checkpoint sequences in the scala 2.12 fork join pool, which is used by rediscala. All scala concurrent tests validate with this change.
=> exclude RF adapters for scala FJP, use endTaskScope

dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/main/java8/java/util/concurrent/CompletableFutureAdvice.java, dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/test/groovy/TestFanout.groovy, dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java
This also increases the number of validated test cases for `CompletableFuture`
=> fix lettuce-5 CompletableFuture checkpoints

dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java, dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
IIRC this used to work, but stopped with the changes to remove the Rules a while back.
This should allow users that configure a service name to still have their war files treated as separate services.
=> Allow `split-by-tag=servlet.context` to set service name.

dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SpringBootBasedTest.groovy
in order to verify consistent behavior for spring resource naming when configured with a servlet context.
=> Change servlet context for spring boot

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/IntervalValidator.groovy, dd-java-agent/testing/src/test/groovy/checkpoints/IntervalValidatorTest.groovy
This change will prevent intermittent test failures due to wrong interval checks.
=> Fix checkpoint interval validator

buildSrc/build.gradle.kts, buildSrc/src/test/groovy/InstrumentPluginTest.groovy, gradle/dependencies.gradle
Keeping up with the latest fixes and improvements: https://github.com/raphw/byte-buddy/releases
=> byte-buddy 1.11.18

dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/EndpointEvent.java, dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java
This is to facilitate searching for specific events in a recording for a given trace
=> Track Trace Id on EndpointEvent

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/report/EventEnrichment.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/report/EventEnrichmentSpecification.groovy, internal-api/src/main/java/datadog/trace/api/gateway/Events.java, internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java, internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java
Added http response status code and blocking status to appsec attack reports.
=> [AppSec] Attack reports with response status code and blocking status

dd-java-agent/appsec/appsec.gradle, dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java, dd-java-agent/dd-java-agent.gradle, dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
- Bump waf version to 3.0.2
- Added logging of AppSec config
- Added manual trace
=> Minor fixes

dd-java-agent/instrumentation/play-2.6/src/test/groovy/server/PlayAsyncServerWithErrorHandlerTest.groovy, dd-java-agent/instrumentation/play-2.6/src/test/groovy/server/PlayHttpServer.groovy, dd-java-agent/instrumentation/play-2.6/src/test/groovy/server/PlayServerWithErrorHandlerTest.groovy, dd-java-agent/instrumentation/play-2.6/src/test/java/server/TestHttpErrorHandler.java, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
Add tests to prove that we cover the error handler for play 2.6+
=> Add tests using Play 2.6+ error handler

dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java
When checkpoints sampling is disabled it does not make sense to try and emit the config event which is valid only for the adaptive sampler anyway.
=> Emit checkpoint sampler config event only if the config is available

dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AsyncProfilerConfigEvent.java
I forgot to add the `@Name` annotation in the original PR.
=> Add the event name

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
I noticed that I didn't take this into account when adding the tag
=> Prioritize forwarded host for hostname tag

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
Much of the time the `continuation` field is `null`, so introduce a specific sub-class for the case when we know there's a `continuation` so we can save 4 bytes in the more common case when we don't have a continuation. This PR also adjusts visibility of a few fields to avoid using a synthetic accessor method to access them.
Performance difference...
Java 11 (before)
---
Benchmark                      (activeScope)  Mode  Cnt    Score   Error  Units
ScopesBenchmark.runFutureTask           true  avgt   25  169.075 ± 7.670  ns/op
ScopesBenchmark.runFutureTask          false  avgt   25   41.800 ± 0.232  ns/op
Java 11 (after)
---
Benchmark                      (activeScope)  Mode  Cnt    Score   Error  Units
ScopesBenchmark.runFutureTask           true  avgt   25  154.088 ± 1.299  ns/op …
=> Reduce size of scope on stack when there's no continuation

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
Further improvement on top of #3217
=> Store current scope separate to previous scope history

dd-java-agent/instrumentation/grizzly-http-2.3.20/src/main/java/datadog/trace/instrumentation/grizzlyhttp232/GrizzlyDecorator.java
Better safe than sorry... Found a bit late for #3228
=> Add span null check in GrizzlyDecorator

dd-java-agent/agent-profiling/profiling-auxiliary-async/profiling-auxiliary-async.gradle
A simple bump in the async-profiler version to get the latest build
=> Bump the async-profiler version

CONTRIBUTING.md
A couple of issues I've encountered when I was trying to import project into IntelliJ
=> Add troubleshooting tips on how to import project to IntelliJ

dd-java-agent/appsec/src/main/resources/default_config.json
Updated security rules to latest version
=> [AppSec] Bump rules to 1.2.4

dd-java-agent/instrumentation/log4j1/src/main/java/datadog/trace/instrumentation/log4j1/LoggingEventInstrumentation.java
=> log4j1/LoggingEventInstrumentation: Inject correct value for dd.span_id

dd-java-agent/instrumentation/spymemcached-2.12/src/main/java/datadog/trace/instrumentation/spymemcached/CompletionListener.java
=> Memcached result tag: fixing typo

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle, dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java, dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/ServiceNameCollectingTraceInterceptor.java, dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java, dd-trace-api/src/main/java/datadog/trace/api/DDSpanTypes.java, dd-trace-api/src/main/java/datadog/trace/api/config/JmxFetchConfig.java, internal-api/src/main/java/datadog/trace/api/Config.java
Depends on https://github.com/DataDog/jmxfetch/pull/375
=> Inform JMXFetch of service names to support multi-service

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/SessionState.java, dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/jms/SessionStateTest.groovy, dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/DatadogMessageListener.java, dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java, dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java, dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageProducerInstrumentation.java, dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/SessionInstrumentation.java, dd-java-agent/instrumentation/jms/src/test/groovy/TimeInQueueForkedTest.groovy, dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/KafkaClientTest.groovy, dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy, dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitChannelInstrumentation.java, dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java, dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java, dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java, internal-api/src/main/java/datadog/trace/api/Config.java
Also add some aliases to support old settings while aligning messaging flags with their instrumentation names.
=> Refactor messaging related config to make it easier to add new integrations

dd-java-agent/appsec/appsec.gradle
=> [AppSec] Bump WAF version

gradle/dependencies.gradle
=> Bump async-profiler to 2.6-DD-20220125

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/TestDecorator.java, dd-java-agent/instrumentation/ignite-2.0/src/main/java/datadog/trace/instrumentation/ignite/v2/cache/IgniteCacheDecorator.java, dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java, dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java, dd-java-agent/instrumentation/mongo/common/src/main/java/datadog/trace/instrumentation/mongo/MongoDecorator.java, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InternalSpanTypes.java
... as it performs better when serializing trace payloads
=> Prefer using InternalSpanTypes in Decorators

dd-java-agent/appsec/appsec.gradle
=> [AppSec] Update libddwaf 1.0.17

dd-java-agent/appsec/src/main/resources/default_config.json
=> [AppSec] Updated rules (v1.2.5)

.circleci/config.yml, dd-cws-tls/dd-cws-tls.gradle, dd-java-agent/agent-profiling/profiling-auxiliary/profiling-auxiliary.gradle, dd-java-agent/agent-tooling/agent-tooling.gradle, dd-java-agent/appsec/weblog/weblog-spring-app/weblog-spring-app.gradle, dd-java-agent/benchmark-integration/README.md, dd-java-agent/benchmark-integration/play-perftest/app/controllers/HomeController.scala, dd-java-agent/benchmark-integration/play-perftest/app/controllers/Worker.scala, dd-java-agent/benchmark-integration/play-perftest/play-perftest.gradle, dd-java-agent/benchmark-integration/run-perf-test.sh, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/aws-java-sdk-1.11.0.gradle, dd-java-agent/instrumentation/micronaut-http-server-netty-2/micronaut-http-server-netty-2.gradle, dd-java-agent/instrumentation/okhttp-2/okhttp-2.gradle, dd-java-agent/instrumentation/spray-1.3/spray-1.3.gradle, dd-smoke-tests/play-2.4/play-2.4.gradle, dd-smoke-tests/play-2.4/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy, dd-smoke-tests/play-2.5/play-2.5.gradle, dd-smoke-tests/play-2.5/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy, dd-smoke-tests/play-2.6/play-2.6.gradle, dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/PlaySmokeTest.groovy, dd-smoke-tests/wildfly/wildfly.gradle, dd-trace-core/dd-trace-core.gradle, dd-trace-java.gradle, dd-trace-ot/dd-trace-ot.gradle, utils/histograms/histograms.gradle, utils/socket-utils/socket-utils.gradle
Reverts DataDog/dd-trace-java#3330
=> Revert "Some gradle cleanup in preparation for 7.x"

.github/workflows/codeql-analysis.yml
=> Pin github actions versions

buildSrc/build.gradle.kts, buildSrc/src/test/groovy/InstrumentPluginTest.groovy, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/AdditionalLibraryIgnoresMatcher.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/HasSuperMethodMatcher.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/NameMatchers.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/SafeHasSuperTypeMatcher.java, dd-java-agent/instrumentation/jetty-11/src/main/java/datadog/trace/instrumentation/jetty11/JettyServerInstrumentation.java, dd-java-agent/instrumentation/jetty-9/src/main/java/datadog/trace/instrumentation/jetty9/JettyServerInstrumentation.java, dd-java-agent/instrumentation/spring-cloud-zuul-2/spring-cloud-zuul-2.gradle, gradle/dependencies.gradle
https://github.com/raphw/byte-buddy/releases
=> byte-buddy 1.12.7

dd-java-agent/appsec/appsec.gradle, dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/KnownAddresses.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/AppSecSystemSpecification.groovy, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy, dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
Implemented code to collect and report pre-defined HTTP response headers
=> [AppSec] Collect and report pre-defined HTTP response headers

dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java, dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
disabling propagation should result in disconnected trace regardless of active context
=> Make RabbitMQ trace propagation consistent with other messaging integrations

buildSrc/build.gradle.kts, buildSrc/src/test/groovy/InstrumentPluginTest.groovy, gradle/dependencies.gradle
https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.8
=> byte-buddy 1.12.8

.github/workflows/gradle-wrapper-validation.yaml
Updates the gradle wrapper validation workflow
Include any bug fixes and security fixes that might have happened
=> Update gradle wrapper validator

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
We need this message to confirm issue reported by customer
=> [AppSec] Added extra log message for classloader creation

dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/FormDataMap.java, dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/FormDataParserInstrumentation.java, dd-java-agent/instrumentation/undertow-2.0/src/test/groovy/UndertowTest.groovy
Intercepts the parsing of form data in undertow and provides it to the instrumentation gateway for processing in the appsec module.
=> Appsec: Support parsed urlencoded data on undertow 2

dd-java-agent/appsec/src/main/resources/default_config.json, dd-smoke-tests/appsec/springboot-grpc/src/test/groovy/datadog/smoketest/appsec/SpringBootWithGRPCAppSecTest.groovy, dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
=> [AppSec] Updated security rules (v1.3.1)

internal-api/src/main/java/datadog/trace/util/ProcessSupervisor.java, internal-api/src/test/groovy/datadog/trace/util/ProcessSupervisorTest.groovy
Removes some possible races in ProcessSupervisorTest
A day at the races is no fun
=> Remove some possible races in ProcessSupervisorTest

gradle/wrapper/gradle-wrapper.properties
Upgrades gradle to 7.4.2
Latest and greatest
=> Upgrade gradle to 7.4.2

communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java, communication/src/test/groovy/datadog/communication/ddagent/DDAgentFeaturesDiscoveryTest.groovy, communication/src/test/resources/agent-features/agent-info.json
add config endpoint (for polling Remote Configs)
add debugger endpoint (for sending snapshots)
expose datadog version
Features required by upcoming Live Debugger product
=> Add support for debugger in features discovery

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java, dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java, internal-api/src/main/java/datadog/trace/api/Config.java, internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Add debugger config options
Config options required by upcoming Live Debugger product
=> Add debugger config

dd-java-agent/instrumentation/jms/jms.gradle, dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/scala-promise-2.10.gradle, dd-java-agent/instrumentation/scala-promise/scala-promise-2.13/scala-promise-2.13.gradle, dd-java-agent/instrumentation/spring-jms-3.1/spring-jms-3.1.gradle, dd-java-agent/instrumentation/vertx-mysql-client-3.9/vertx-mysql-client-3.9.gradle, dd-java-agent/instrumentation/vertx-redis-client-3.9/vertx-redis-client-3.9.gradle, dd-java-agent/instrumentation/vertx-rx-3.5/vertx-rx-3.5.gradle, dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/RouteHandlerWrapper.java, dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/RouteHandlerWrapperAdvice.java, dd-java-agent/instrumentation/vertx-web-3.4/vertx-web-3.4.gradle, gradle/configure_tests.gradle, gradle/java_no_deps.gradle
It cleans up some code and _actually_ runs the forked tests with latest dependencies.
Running tests and not only thinking that you are runnings tests is better.
Yes, some of the tests fail 😭
=> Run forked tests with latest dependencies

dd-java-agent/agent-debugger/debugger-bootstrap/debugger-bootstrap.gradle, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedStackFrame.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CorrelationAccess.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DiagnosticMessage.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/FieldExtractor.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Fields.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/ProbeDiagnostic.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/ProbeRateLimiter.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/SnapshotProvider.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/ValueConverter.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/DebuggerScript.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ReflectiveFieldValueResolver.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ValueReferenceResolver.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ValueReferences.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/Values.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/test/java/datadog/trace/bootstrap/debugger/CorrelationAccessTest.java, settings.gradle
Classes use by the Live Debugger and called by the instrumentation
Those classes need to be inserted into the bootstrap classloader
Classes required by upcoming Live Debugger product
=> Add bootstrap Debugger project

dd-java-agent/instrumentation/grizzly-2/grizzly-2.gradle
Skip new grizzly `4.0.0` version
=> Fixing muzzle check in grizzly-2 instrumentation

internal-api/src/main/java/datadog/trace/api/cache/CHMCache.java, internal-api/src/main/java/datadog/trace/api/cache/DDCache.java, internal-api/src/main/java/datadog/trace/api/cache/FixedSizeCache.java
This lets us invalidate/remove the entire cache when appropriate.
=> Support clearing of DDCaches

dd-java-agent/instrumentation/grpc-1.5/grpc-1.5.gradle, dd-smoke-tests/springboot-grpc/springboot-grpc.gradle
Makes the project compile on M1 Macs
Need to work on M1 Macs
=> Make project compile on Mac M1

dd-java-agent/instrumentation/aerospike-4/aerospike-4.gradle, dd-java-agent/instrumentation/aerospike-4/src/test/groovy/datadog/trace/instrumentation/aerospike4/AerospikeBaseTest.groovy, dd-java-agent/instrumentation/jdbc/jdbc.gradle, dd-java-agent/instrumentation/spring-rabbit/spring-rabbit.gradle, dd-java-agent/instrumentation/vertx-mysql-client-3.9/vertx-mysql-client-3.9.gradle, dd-smoke-tests/spring-boot-rabbit/spring-boot-rabbit.gradle, dd-smoke-tests/springboot-mongo/springboot-mongo.gradle, dd-smoke-tests/springboot-mongo/src/main_java8/java/datadog/smoketest/springboot/SpringbootApplication.java, dd-smoke-tests/springboot-mongo/src/test/groovy/datadog/smoketest/SpringBootMongoIntegrationTest.groovy, gradle/dependencies.gradle
Ensures that the Testcontainers based tests work on Mac M1
=> Ensure that Testcontainers based tests work on Mac M1

dd-java-agent/instrumentation/aws-lambda-handler/src/main/java/datadog/trace/instrumentation/aws/v1/lambda/LambdaHandlerInstrumentation.java, dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
Using UTF8BytesString were causing `java.lang.NoClassDefFoundError` in Lambda instrumentation, this PR fixes it
=> [Serverless] fix no class found error

buildSrc/build.gradle.kts, gradle/java_no_deps.gradle, gradle/wrapper/gradle-wrapper.properties
https://docs.gradle.org/7.5/release-notes.html
=> Upgrade gradle to 7.5

.gitlab-ci.yml, lib-injection/application/build.gradle.kts, lib-injection/src/test/shell/functions.sh
Changes the name of the docker image created for lib injection
=> [alpha][lib-injection] Change name of docker image

communication/src/main/java/datadog/communication/http/OkHttpUtils.java, dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java, dd-java-agent/agent-crashtracking/src/test/java/com/datadog/crashtracking/CrashUploaderTest.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/DebuggerSink.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java, dd-trace-api/src/main/java/datadog/trace/api/config/CrashTrackingConfig.java, internal-api/src/main/java/datadog/trace/api/Config.java
Adds uploading to logs track the crash files on top of telemetry track.
For it to get to the customer's org as well.
=> Upload crash files to Logs as well

dd-java-agent/instrumentation/mongo/src/test/groovy/MongoBaseTest.groovy
We allocated a port for MongoDB before extracting the embedded MongoDB
distribution. When running multiple test workers, extracting the
embedded MongoDB may lock for a while, enough time to get a port
conflict.
Allocate the port later, to reduce the probability of port conflicts.
* Follow up to https://github.com/DataDog/dd-trace-java/pull/3728
* Example of failed job: https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/15222/workflows/20764ab3-af5f-4f4d-b16f-7895662ae399/jobs/345236
```
java.io.IOException: Could not start process: failed errno:98 Address already in use for socket: 127.0.0.1:37615
2022-08-23T23:00:18.578+0000 E NETWORK  [initandlisten]   addr already in use
2022-08-23T23:00:18.578+0000 E STORAGE  [initandlisten] Failed to set up sockets during startup. …
```
=> Prevent port conflict in MongoDB tests

.gitlab-ci.yml
=> Deploy `latest` tag to docker registries

.circleci/collect_reports.sh, .circleci/config.yml, dd-trace-java.gradle
=> Save heap dump in CI

gradle/dependencies.gradle
=> Bump async-profiler to 20220829

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
Used additional checkers to avoid NPE in case if request has non-web span. In given scenario AppSec should ignore the trace.
This issue already resolved in #3642. Current PR it's temporary fix until proper solution will be merged.
Related tickets:
[SCRS-347](https://datadoghq.atlassian.net/browse/SCRS-347)
[APMS-7865](https://datadoghq.atlassian.net/browse/APMS-7865)
=> Fixed AppSec NullPointerException for non-web spans.

telemetry/src/main/java/datadog/telemetry/dependency/JbossVirtualFileHelper.java
Fixes the Jboss VFS helper when the content type inside the connection is null.
After upgrading the Docker build image some of the jboss vfs tests started to fail:
`datadog.telemetry.dependency.DependencyServiceImplTests#jboss_vfs_zip_url`
`datadog.telemetry.dependency.DependencyServiceImplTests#jboss_vfs_url`
=> Fix Jboss VFS when content type is not null

.github/CODEOWNERS, dd-smoke-tests/debugger-integration-tests/debugger-integration-tests.gradle, dd-smoke-tests/debugger-integration-tests/latest-jdk-app/.gitignore, dd-smoke-tests/debugger-integration-tests/latest-jdk-app/latest-jdk-app.gradle, dd-smoke-tests/debugger-integration-tests/latest-jdk-app/src/main/java/App.java, dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/DebuggerTestApplication.java, dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/ServerDebuggerTestApplication.java, dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/SpringBootTestApplication.java, dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/TestApplicationHelper.java, dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/controller/WebController.java, dd-smoke-tests/debugger-integration-tests/src/main/resources/application.properties, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/DebuggerIntegrationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ProcessBuilderHelper.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/RemoteConfigHelper.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ServerDebuggerIntegrationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java, settings.gradle
Add smoke tests for Live Debugger product
Open sourcing Live Debugger product
=> Add debugger smoke tests project

dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java, dd-java-agent/instrumentation/aws-java-sdk-2.2/src/test/groovy/Aws2ClientTest.groovy
Record storage class for S3 PutObject requests
Since PutObject requests incur different fees according to storage class, this is an interesting tag to capture.
=> record storage class for S3 PutObject requests

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
https://nvd.nist.gov/vuln/detail/CVE-2022-38752
=> Upgrade snakeyaml to 1.32 to mitigate CVE-2022-38752

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle, telemetry/src/main/java/datadog/telemetry/dependency/JbossVirtualFileHelper.java
=> Fixes for releasing v0.108.2

dd-java-agent/instrumentation/ratpack-1.5/src/test/groovy/server/RatpackHttpServerTest.groovy, dd-java-agent/instrumentation/rmi/src/test/groovy/RmiTest.groovy, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy, dd-smoke-tests/play-2.4/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy
=> Disable more flaky tests

dd-smoke-tests/springboot-openliberty/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySnapshotTest.groovy
=> disable openliberty flaky test

dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisAPITestBase.groovy
=> disable flaky test

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/Event.groovy
Disable stack trace dumps at checkpoints by default
Easier to read logs, use less resources running test suite
=> disable stacktrace collection by default

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ServerDebuggerIntegrationTest.java
Cover all probe statuses by smoke tests
=> Add smoke test for probe error status

dd-java-agent/iast/src/test/groovy/com/datadog/iast/model/VulnerabilityTypeTest.groovy
Add some further test cases for hash calculation that I used previously.
=> Additional cases for VulnerabilityType tests

dd-java-agent/instrumentation/jetty-11/src/main/java/datadog/trace/instrumentation/jetty11/JettyServerInstrumentation.java, dd-java-agent/instrumentation/jetty-7.0/src/main/java/datadog/trace/instrumentation/jetty70/JettyServerInstrumentation.java, dd-java-agent/instrumentation/jetty-7.6/src/main/java/datadog/trace/instrumentation/jetty76/JettyServerInstrumentation.java, dd-java-agent/instrumentation/jetty-9/src/main/java/datadog/trace/instrumentation/jetty9/JettyServerInstrumentation.java
Merging #3701 after #3902 without rebasing broke the build
Make the code compile again
=> update advice transformers for latest bytebuddy version

dd-java-agent/appsec/src/main/resources/default_config.json
=> Updated AppSec rules (v1.4.1)

gradle/dependencies.gradle
Update the async-profiler lib to the latest release tag
There was a bunch of fixes and improvements done in async-profiler since the last release.
=> Update the async-profiler dependency

.circleci/config.yml, dd-java-agent/agent-debugger/agent-debugger.gradle, dd-java-agent/agent-profiling/agent-profiling.gradle, dd-java-agent/iast/iast.gradle
* Creates a separate test matrix for profiling
* Skips (profiling|iast|debugger) tests unless (profiling|iast|debugger) code has been modified
* Skips muzzle unless instrumentation code has been modified
* Skips instrumentation tests unless instrumentation or dependencies (bootstrap, installer, iast, appsec, etc.) have been modified
* Always runs smoke tests
* Runs everything on master and release branches
=> Make tests run conditional on changes made

.circleci/config.yml
Authenticates github requests using a new PAT installed in circleci
Avoid API throttling
=> authenticate github requests to avoid api throttling

dd-java-agent/appsec/appsec.gradle
=> Updated AppSec WAF to 5.1.0

.circleci/config.yml
=> Strip quotes from target branch

dd-trace-java.gradle
=> experiment with removing tasktree plugin

buildSrc/src/main/groovy/InstrumentPlugin.groovy, dd-java-agent/instrumentation/akka-http-10.0/akka-http-10.0.gradle, dd-java-agent/instrumentation/finatra-2.9/finatra-2.9.gradle, dd-java-agent/instrumentation/jdbc/scalikejdbc/scalikejdbc.gradle, dd-java-agent/instrumentation/play-2.3/play-2.3.gradle, dd-java-agent/instrumentation/slick/slick.gradle, gradle/test-with-kotlin.gradle
This removes some noise from the gradle build scan
=> Fix some gradle deprecations

.circleci/collect_reports.sh, .circleci/config.yml
Collapses `build` and `check` to not run tests if there are any code violations.
=> Collapse build and check on CircleCI

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
=> Add missing size for map values in snapshots

dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy, dd-java-agent/appsec/src/test/resources/another_actions_config.json, dd-java-agent/appsec/src/test/resources/no_actions_config.json, dd-java-agent/appsec/src/test/resources/override_actions_config.json
Added missing default `block` action for the AppSec.
AppSec wasn't blocking malicious requests in case if no actions defined in rules
=> Fix IP blocking (added default AppSec action)

.circleci/config.yml
Add some more build files that should trigger full tests.
=> Trigger full tests on CI for more build files

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java, dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/TestApplicationHelper.java
=> Add some info log for debugger

internal-api/src/main/java/datadog/trace/api/Platform.java, internal-api/src/test/groovy/datadog/trace/api/PlatformTest.groovy
=> Handle strange versions properties in JvmRuntime

gradle/dependencies.gradle
=> bump async-profiler

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
Following the comment in https://github.com/DataDog/dd-trace-java/pull/3827#discussion_r986916396
=> Avoid creating new limits in loop

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
Following comment on https://github.com/DataDog/dd-trace-java/pull/4005#discussion_r992796647
=> Refactor logHasErrors

buildSrc/call-site-instrumentation-plugin/build.gradle.kts
Adds a missing dependency 
Unable to build locally
=> Add missing dependency on Objenesis

.github/workflows/add-assets-to-release.yaml
* Follow up to https://github.com/DataDog/dd-trace-java/pull/4024
=> Fix github actions tag

dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/ContextThreadFilter.java, dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
Verifies this works as expected, in case it doesn't or if it ceases to work.
=> Context thread listener attach test

dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfiler.java, dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfilerConfig.java, dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/ContextThreadFilter.java, dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
=> add asyncprofiler configuration settings (loglevel, toggle thread filtering)

communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
=> Delay feature discovery in configuration poller

communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
Log config endpoint on feature discovery when debug logging is enabled.
=> Log config endpoint on feature discovery

gradle/dependencies.gradle
=> bump async-profiler to 20221024_1

dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy, dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
Tries to fix the flaky tests
The tests was failing from time to time in CI
=> Fix '_dd.iast.enabled' flaky related test

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
This reverts commit 520f781b9ae0a513be6655755f104c648cf51f8d, reversing changes made to 5d5473969a2667e4ecd92870b5bee244cd050060.
Reverts https://github.com/DataDog/dd-trace-java/pull/4072
=> Revert "Merge pull request #4072 from DataDog/vzakharov/lazy_waf"

dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedMapTest.groovy, utils/test-utils/src/main/java/datadog/trace/test/util/CircularBuffer.java
Tries to fix the flaky tests regarding the tainted map
=> Try to fix flaky tainted map test

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
WAF loads lazily to reduce startup time (second attempt with fix for tests)
=> WAF lazy loading

.circleci/config.yml
=> make sure base tests run when appsec changes are made

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
Reverts DataDog/dd-trace-java#4106
This skipped base tests, revert first, then will make sure appsec changes trigger base tests
=> Revert "WAF lazy loading"

buildSrc/src/main/groovy/MuzzlePlugin.groovy, dd-java-agent/instrumentation/commons-httpclient-2/commons-httpclient-2.gradle, dd-java-agent/instrumentation/glassfish/glassfish.gradle, dd-java-agent/instrumentation/grizzly-http-2.3.20/grizzly-http-2.3.20.gradle, dd-java-agent/instrumentation/jms/jms.gradle, dd-java-agent/instrumentation/play-2.3/play-2.3.gradle, dd-java-agent/instrumentation/play-2.4/play-2.4.gradle, dd-java-agent/instrumentation/play-2.6/play-2.6.gradle, dd-java-agent/instrumentation/restlet-2.2/restlet-2.2.gradle, dd-java-agent/instrumentation/servlet/request-2/request-2.gradle, dd-java-agent/instrumentation/servlet/request-3/request-3.gradle, dd-java-agent/instrumentation/testng-6.4/testng-6.4.gradle, dd-java-agent/instrumentation/tomcat-5.5/tomcat-5.5.gradle
=> Remove jcenter from build dependencies

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java, dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
The listener mechanism to identify traced threads in #4049 is a little over-eager in that it notifies whenever the thread-local scope stack is initialised, which happens in any instrumented code if a check for an active scope is in the instrumentation. This delays notification until the first scope is activated on the thread.
=> delay notification until a scope has been pushed to the scope stack

dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/KafkaClientTest.groovy
=> wait for records to be available before starting assertions

gradle/dependencies.gradle
Upgrade to https://github.com/DataDog/async-profiler/releases/tag/DD-20221101
=> bump async-profiler to latest version

dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
=> Add assertions for sampling debugger configuration

dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java
Fixes https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/17676/workflows/f606ead5-a587-4ac8-918f-1207af26da9d/jobs/427255
=> handle null thread names

.circleci/config.yml
Integration system-tests and CI Visibility. Pipeline configuration to send data to CI Visibility
Observe the system-tests executions over main branch
=> system-tests and CI Visibility integration

dd-java-agent/appsec/src/main/resources/default_config.json
* Source for the rules: https://github.com/DataDog/appsec-event-rules/blob/1.4.2/build/recommended.json
=> Update AppSec event rules to v1.4.2

dd-java-agent/agent-iast/agent-iast.gradle, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/AdapterFactory.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/EvidenceAdapter.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/EvidenceEncodingTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/VulnerabilityEncodingTest.groovy
Update the JSON of the vulnerabilities to support the new evidence format according to the RFC
=> Update generated IAST json with new RFC for ranges

dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java, gradle/dependencies.gradle
Picks up 
* https://github.com/DataDog/async-profiler/releases/tag/DD-20221102
* https://github.com/DataDog/async-profiler/releases/tag/DD-20221103
* https://github.com/DataDog/async-profiler/releases/tag/DD-20221103_1
* https://github.com/DataDog/async-profiler/releases/tag/DD-20221104
=> bump async-profiler to 20221104

dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedMapTest.groovy, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy
WAF loads lazily to reduce startup time (third attempt with fix for tests)
=> Load WAF library lazily

telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
Reuse MessageDigest, instead of creating new instance each time
=> Minor improvement of Dependency collection

gradle/dependencies.gradle
Pick up changes from https://github.com/DataDog/async-profiler/releases/tag/DD-20221107
=> Update async-profiler to 20221107

communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfig.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java, dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java, telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java, telemetry/src/main/java/datadog/telemetry/dependency/DependencyServiceImpl.java
Reduced amount of logs by default. Affected AppSec, Remote-config, Telemetry.
=> Less logs verbosity by default

dd-java-agent/instrumentation/reactor-core-3.1/reactor-core-3.1.gradle, dd-java-agent/instrumentation/spring-webflux-5/spring-webflux-5.gradle
=> Limit reactor ranges for muzzle and tests due to incompatibilities

buildSrc/build.gradle.kts, buildSrc/call-site-instrumentation-plugin/build.gradle.kts, buildSrc/src/test/groovy/CallSiteInstrumentationPluginTest.groovy, dd-java-agent/instrumentation/kotlin-coroutines/src/test/kotlin/KotlinCoroutineTests.kt, dd-smoke-tests/play-2.4/app/controllers/SController.scala, dd-smoke-tests/play-2.5/app/controllers/SController.scala, dd-smoke-tests/play-2.6/app/controllers/SController.scala, dd-smoke-tests/play-2.7/app/controllers/SController.scala, dd-smoke-tests/play-2.8/app/controllers/SController.scala, dd-smoke-tests/quarkus/application/build.gradle, dd-smoke-tests/spring-boot-2.7-webflux/application/build.gradle, dd-trace-java.gradle, gradle/enforcement/spotless-scalafmt.conf, gradle/spotless.gradle, gradle/spotless/spotless-kotlin.gradle, gradle/test-with-kotlin.gradle, test-published-dependencies/build.gradle
=> Upgrade axion-release and spotless gradle plugins

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java, dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
async-profiler event labeling replaces both of these legacy mechanisms
=> don't emit checkpoints or scope events if async-profiler is enabled

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/SnapshotProvider.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/test/java/datadog/trace/bootstrap/debugger/SnapshotSummaryTest.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java, dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/sink/snapshotCapturedValueRegex.txt
Consider this as a regular object argument. it should have type and
field attributes
This argument is a special argument, but it should also handled as a regular object value for simplifying snapshot processing
=> Adjust snapshot structure for this object

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
=> Remove Java 8 checks from Agent

.github/CODEOWNERS
=> Add iast-instrumenter to iast code owners

lib-injection/src/main/docker/Dockerfile
Resolves https://github.com/DataDog/dd-trace-java/issues/4200
Please refer the linked issue
=> Use a high UID/GID and specify the UID value in the USER instruction

gradle/dependencies.gradle
https://github.com/DataDog/async-profiler/releases/tag/DD-20221111
=> upgrade async-profiler to 20221111

dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy, internal-api/src/main/java/datadog/trace/api/Platform.java
=> Ignore failing test on Semeru 8

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java
Disables `TracerDebuggerIntegrationTest`
Output #4231
=> Disable Flaky TracerDebuggerIntegrationTest

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ServerDebuggerIntegrationTest.java
=> Change message when not finding line

dd-java-agent/agent-iast/src/jmh/java/com/datadog/iast/propagation/AbstractBenchmark.java
Fixes compilation issue with the propagation benchmark
=> Fix issue with the propagation benchmark
