DataDog/dd-trace-java

.circleci/config.yml

* Create a fan-in job for every fan-out group so that we can keep the number of required rules small
* Rename the fan-out jobs so that they get sorted last in the GitHub UI

Use simple job to do fan-in in on CircleCI

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java

About half the time publishing metrics on the application threads is spent in CHM operations, this use NonBlockingHashMap which performed better in some microbenchmarks I ran.

use NonBlockingHashMap in ConflatingMetricsAggregator

---

internal-api/internal-api-8/internal-api-8.gradle
internal-api/internal-api-8/src/jmh/java/datadog/trace/api/sampling/AdaptiveSamplerBenchmark.java
internal-api/internal-api-8/src/jmh/java/datadog/trace/api/sampling/SamplerCounters.java
internal-api/internal-api-8/src/main/java/datadog/trace/api/sampling/AdaptiveSampler.java

I just spotted a capturing lambda here which this removes. Also uses `AtomicLongFieldUpdater`, not because I have evidence it is better, but because I like them.

remove capturing lambda and use ALFU in AdaptiveSampler

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/BaseDecoratorTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy

Broken pipes happen when the client aborts the connection, and this tends to be a symptom of a web application being in an overloaded state, or warming up. Always keeping the trace because it is marked as an error, and then recording the stack trace (which is expensive) exacerbates this. This PR changes `BaseDecorator` to allow `DDSpan` to decide when a span with an error is considered an error, and avoids situations where we have errors with status code 200 (the response is never sent so the status code is not updated). `DDSpan` just excludes errors with the name "Broken pipe".

don't treat broken pipes as errors

---

.circleci/config.yml
dd-java-agent/instrumentation/spring-rabbit/src/main/java/datadog/trace/instrumentation/springamqp/AbstractMessageListenerContainerInstrumentation.java

Runnable class was ignored by additional matcher.  The class has been around for a while, but likely just wasn't loaded during our test until `2.5.0` was released.

Fix latestDepTest for SpringAmqpTest

---

dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentFeaturesDiscovery.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/DDAgentFeaturesDiscoveryTest.groovy

We can't switch on metrics collection when an upgrade to an agent version which supports metrics is detected because the publishing of metrics happens on the application threads, and switching the implementation out would lead to deoptimisation, so the user needs to restart the application to start using tracer metrics. This just makes sure that after an agent version is detected, the status of support for dropping and metrics don't change. This means unless a tracer is already producing metrics, it won't start dropping traces after the upgrade.

never enable dropping if metrics wasn't enabled at startup

---

internal-api/internal-api.gradle
internal-api/src/main/java/datadog/trace/api/function/BiConsumer.java
internal-api/src/main/java/datadog/trace/api/function/BiFunction.java
internal-api/src/main/java/datadog/trace/api/function/Supplier.java
internal-api/src/main/java/datadog/trace/api/function/TriConsumer.java
internal-api/src/main/java/datadog/trace/api/gateway/CallbackProvider.java
internal-api/src/main/java/datadog/trace/api/gateway/EventType.java
internal-api/src/main/java/datadog/trace/api/gateway/Events.java
internal-api/src/main/java/datadog/trace/api/gateway/Flow.java
internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java
internal-api/src/main/java/datadog/trace/api/gateway/RequestContext.java
internal-api/src/main/java/datadog/trace/api/gateway/Subscription.java
internal-api/src/main/java/datadog/trace/api/gateway/SubscriptionService.java
internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java

A minimal Instrumentation Gateway interface that only supports one subscriber to each `EventType`.
The whole API is based around callbacks, that try to provide the least expensive version of the data from the instrumentation/tracer point of view. Grouping of the data should be done on the subscriber side, i.e. combining headers into a `Map` to send to `PowerWAF`.
There will be a separate PR for hooking this into the tracer/instrumentations.

Minimal Instrumentation Gateway API and test

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java

I found this digging in to something else - when runnables are executed by `ScheduledThreadPoolExecutor` they are actually scheduled, so wrapped in a `ScheduledFutureTask` anyway.

Don't wrap runnables in ScheduledThreadPoolExecutor.execute

---

internal-api/src/main/java/datadog/trace/api/Config.java

This PR removes the `PREFIX` added on `getEnumValue` because the prefix is already added when the `ConfigProvider` tries to obtain the property from `ConfigProvider.Source`.
This was not easily detected because it was only used to configure the `prioritization.type` for development mode (CI App).

Remove duplication of prefix 'dd' on config.getEnumValue

---

dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/util/AbstractCouchbaseTest.groovy

Many of the test failures seem related to errors during cleanup.

Ignore exceptions thrown during couchbase cleanup

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AdviceUtils.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ConcurrentState.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ContinuationClaim.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/State.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/Wrapper.java
dd-java-agent/instrumentation/guava-10/src/main/java/datadog/trace/instrumentation/guava10/ListenableFutureInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/main/java/datadog/trace/instrumentation/java/completablefuture/AsyncTaskInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/main/java8/java/util/concurrent/CompletableFutureAdvice.java
dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/test/groovy/TestFanout.groovy
dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/test/java/Fanout.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinPoolInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableFutureInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/CheckpointThreadMigrationTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/test/java/CheckpointTask.java
dd-java-agent/instrumentation/opentelemetry/src/test/groovy/OpenTelemetryTest.groovy
dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScope.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

Because of futures and promises, capturing a continuation is far too general and frequent an event to represent a span migrating thread - it can happen at any time, e.g. blocking the current thread to wait for completable futures will capture and cancel a continuation:
```java
CompletableFuture.allOf(futures.toArray(CompletableFuture[]::new)).get();
```
This PR limits the cases where a thread migration event is emitted to the following cases:
* an instrumented `RunnableFuture` is constructed - this practically always means submission to a thread pool
* a `ForkJoinTask` is pushed from an external thread, or `ForkJoinTask.fork` is called
* `execute` is called on instrumented `Executor`s
* we construct a `Wrapper` - which only exists for context propagation
* a `UniRun` or `UniApply`, which …

record thread migrations more accurately

---

dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/util/AbstractCouchbaseTest.groovy
dd-trace-core/src/main/java/datadog/trace/common/writer/ListWriter.java

The span gets reported eventually and will mess up a future trace assertion if ignored.

Increase timeout rather than ignore

---

dd-java-agent/instrumentation/play-2.3/src/main/java8/datadog/trace/instrumentation/play23/PlayAdvice.java
dd-java-agent/instrumentation/play-2.3/src/main/java8/datadog/trace/instrumentation/play23/PlayHttpServerDecorator.java
dd-java-agent/instrumentation/play-2.3/src/main/java8/datadog/trace/instrumentation/play23/RequestCompleteCallback.java
dd-java-agent/instrumentation/play-2.3/src/test/groovy/server/PlayServerTest.groovy
dd-java-agent/instrumentation/play-2.4/src/main/java8/datadog/trace/instrumentation/play24/PlayAdvice.java
dd-java-agent/instrumentation/play-2.4/src/main/java8/datadog/trace/instrumentation/play24/PlayHttpServerDecorator.java
dd-java-agent/instrumentation/play-2.4/src/main/java8/datadog/trace/instrumentation/play24/RequestCompleteCallback.java
dd-java-agent/instrumentation/play-2.4/src/test/groovy/server/PlayServerTest.groovy
dd-java-agent/instrumentation/play-2.6/src/main/java8/datadog/trace/instrumentation/play26/PlayHttpServerDecorator.java
dd-java-agent/instrumentation/play-2.6/src/main/java8/datadog/trace/instrumentation/play26/RequestCompleteCallback.java
dd-java-agent/instrumentation/play-2.6/src/test/groovy/server/PlayServerTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

There have been cases where the status code is wrong/different when compared with the parent server span.
This behavior can be reenabled using the following config:
```
-Ddd.trace.play.report-http-status=true
```

Stop collecting http status code on play span by default

---

dd-trace-java.gradle

```
./gradlew :dd-trace-core:jmhJar
```
```
Execution failed for task ':dd-trace-core:jmhJar'.
> Could not expand ZIP 'dd-java-agent/agent-tooling/build/classes/java/main_java11/datadog/trace/agent/tooling/bytebuddy/DDJava9ClassFileTransformer$1.class'.
```
The fix went into 0.6.3 as https://github.com/melix/jmh-gradle-plugin/commit/bc5a3d4f0fce332c420b2ba22f41e54cb72be398 but we might as well upgrade to the latest version

Upgrade JMH gradle plugin to 0.6.5 to fix issue where it was attempting to unzip a class file

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
gradle/dependencies.gradle

https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.11.1
- Add JNA based ClassInjector for use if JNA is already available.
- Allow HashCodeEqualsPlugin to derive hash code from instrumented type rather then lowest type in hierarchy.
- Retain this variable name for index 0 when using advice with remapped locals.
- Rework AnnotationDescription for TypePool to mirror JVM behavior if annotation properties are changed inconsistently.
- Add several StackManipulations for common operations.
- Remove unwanted dependency to Instrumentation API from JavaModule type.
- Rework use of reflection to use JavaDispatcher API which also allows for custom generation of proxies without use of reflection.
- Fully rework JavaConstant API to integrate with Java's ConstantDesc API and to allow for …

ByteBuddy 1.11.1

---

dd-trace-core/src/main/java/datadog/trace/common/sampling/DeterministicSampler.java
dd-trace-core/src/test/groovy/datadog/trace/common/sampling/DeterministicSamplerTest.groovy

`BigDecimal` and `BigInteger` are surprisingly expensive, even if used relatively infrequently 
This reimplements the cutoff logic with floating point arithmetic and verifies it produces the same cutoffs plus or minus 1 for each increment of 0.0001 (I have tested this for 2 orders of magnitude smaller increments but the test takes too long).

implement deterministic sampling with floating point arithmetic

---

.circleci/config.yml
.circleci/upload_ciapp.sh

This enables a new facet to filter tests by: `base`, `instrumentation` or `smoke` across all jobs.
More importantly it adds `runtime.name` and `runtime.version` tags so that we can separate flakiness depending on runtime.

[CIAPP] Add runtime & bundle configuration tags for ci-app

---

.circleci/config.yml

Idea being that this should help us know how to tweak usage.
https://support.circleci.com/hc/en-us/articles/360043994872-How-to-record-a-job-s-memory-usage

Display max memory used for each CI job

---

dd-java-agent/instrumentation/trace-annotation/trace-annotation.gradle

[Latest NR version dropped support for java 7](https://github.com/newrelic/newrelic-java-agent/commit/efa51bda0de8e605e70000341a0c4825306a7370), so we need to pin to the prior version.
TODO: We probably don't need this test anymore...

Fix Java 7 Build

---

dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/JfpUtils.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkController.java

Fixes regression when enabling `jdk.OldObjectSample` on JDKs < 17
causes profiling to be disabled.

Fix handling of jdk.OldObjectSample config for <17 JDKs

---

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogHttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/HaystackHttpCodec.java
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpExtractorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpExtractorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpExtractorTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

Add the following config to enable:
```
-Ddd.propagation.extract.log_header_names.enabled=true
```
When enabled (along with debug logging), results in a log line like this:
```
[main] DEBUG d.t.c.propagation.DatadogHttpCodec - Header: X-DATADOG-TRACE-ID
```

Add config to output received header names on extract.

---

.circleci/config.yml
dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
gradle/java.gradle

These should not be used together.  Also, dd-trace-java should never be declared as a dependency, but rather only on the classpath via `-javaagent`. (Unfortunately this is harder to detect and warn about.)

Log error when dd-java-agent is used with dd-trace-ot.

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java

#2633 introduced a regression that resulted in the ClassLoaderMatcher being ignored when the TypeMatcher was a "RawMatcher". This caused both OpenTracing instrumentation classes to be applied resulting in a duplicate "register" attempt.
(There might be other instrumentation effected by this as well.)

Ensure ClassLoaderMatchers aren't bypassed when using RawMatchers

---

.gitlab-ci.yml

Previously, the gitlab cache would continue grow and slow down the build. This PR fixes that in the following ways:
- Single cache based on master build.  Some inefficiencies on branches, but almost all of the cache is applicable to all branches
- Most jobs **_only pull_** from the cache
- A single job (`build_with_cache`) that pushes to the cache
That single job can be run on a schedule.
This PR takes build time in gitlab from 8-10 minutes to 2-3 minutes.

Better Gitlab cache

---

.circleci/upload_ciapp.sh

The expanding of `JAVA_(JDK)_HOME` was not working properly and we were falling back always to `which java`.

[CIAPP] Fix configuration tags for JDK in CI-App script

---

dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_4.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/Writable.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/MsgPackWriter.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceGenerator.groovy

Introduced in #2729 with the payload encoding changes.  This ensures that values encoded in the `meta` section are encoded as strings as expected by the agent.

Fix encoding of boolean tags causing payloads to be dropped

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingList.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy

Since we're wrapping the List, we need to also ensure the subList result is wrapped as well.

Ensure Kafka ConsumerRecords subList is also traced properly.

---

dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/CouchbaseAsyncClientTest.groovy

Retry was causing cleanup to fail because it can't be shutdown called multiple times with the same instance.
Strict is needed because we can't guarantee root span is finished last.

Make couchbase async test not strict and remove retry

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy

When troubleshooting async tracing behavior, it is helpful to understand the state of the pending trace.  Added that extra bit of info to the span finished log message rather than create a new log.
I also added a debug message to report that a trace is being discarded when using `strictTraceWrites`.

Log PendingTrace state after span finish

---

dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
dd-smoke-tests/cli/src/test/groovy/datadog/smoketest/CliApplicationSmokeTest.groovy

Some containers have "boot" lib folders and automatically add any jars found there to the bootclasspath with `-Xbootclasspath`.  If someone has added the agent jar to one of these "boot" lib folders then the classloader for `AgentBootstrap` will be `null`.
This PR handles this scenario gracefully by using `Class.forName`

Gracefully handle scenario where agent has been added to the bootclasspath with -Xbootclasspath

---

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/PidHelper.java

avoids leaving a lengthy exception stack in the logs when we know this class won't be available

Don't try and load java.lang.ProcessHandle on Java 8

---

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
dd-trace-core/dd-trace-core.gradle
dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDConnection.java
dd-trace-core/src/test/groovy/datadog/trace/core/monitor/DDAgentStatsDClientTest.groovy
gradle/dependencies.gradle
internal-api/src/main/java/datadog/trace/api/Platform.java
internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java

... and switch to use the new client builder for DogStatsD
For reference, here's a similar change in JMXFetch when they upgraded their DogStatsD dependency:
https://github.com/DataDog/jmxfetch/commit/20d5e6297e476c3f64cb78bfb3de45e4f7057a71#diff-e65e4230f75557bac2c582a0c18a5a6c0327e6fc7c7dea6ed10f5ffb14c20298L44
one thing to note: this reduces the StatsD processing queue limit from `Integer.MAX_VALUE` to the new default of `4096` (the StatsD client will start to drop messages if the processing queue limit is ever reached.)  We can restore the original limit if we wish, or we can use the smaller limit like JMXFetch.

Upgrade to JMXFetch 0.44.1 and DogStatsD 2.13.0

---

buildSrc/src/main/groovy/InstrumentPlugin.groovy

After way too much time wondering about what I had broken, and cleaning/compiling/jaring I finally came up with this. Not sure it's completely right but it fixes my issues.
Without this change, running something like
```
./gradlew :dd-java-agent:instrumentation:jetty-9:clean
./gradlew :dd-java-agent:instrumentation:jetty-9:test -Prerun.tests.jetty-9
```
would result in instrumentations not being applied, and the test failing in mysterious ways.

Run instrument task before tests as well

---

dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/HttpUrlConnectionInstrumentation.java
dd-java-agent/instrumentation/http-url-connection/src/test/groovy/HttpUrlConnectionConnectFirstTest.groovy

Alternative fix for #2859 - this has the benefit of also working for IBM JDKs which we weren't instrumenting before.

Fix regression where HTTPS requests don't propagate trace if connect() is called first

---

.gitignore
dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/JfpUtils.java
dd-java-agent/agent-profiling/profiling-controller-jfr/src/test/java/com/datadog/profiling/controller/jfr/JfpUtilsTest.java
dd-java-agent/agent-profiling/profiling-controller-jfr/src/test/resources/overrides-nativemethodsample.jfp
dd-java-agent/agent-profiling/profiling-controller-jfr/src/test/resources/overrides-objectallocation.jfp
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkControllerTest.java
dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkController.java
dd-java-agent/agent-profiling/profiling-controller-oracle/src/test/java/com/datadog/profiling/controller/oracle/JfrMBeanHelperTest.java

We want to disable events enabled by default in dd.jfp based on the
version. For example, OldObjectSample or NativeMethodSample have poor
performance on older versions. We don't want to penalize customers who
are on these older versions and just use the default profile.
However, we still want to allow users to override any settings they
want as they may have perfectly valid reasons to do so and to accept to
pay the cost for them.

Rework how JFR events are disabled based on JVM version

---

dd-java-agent/instrumentation/akka-concurrent/src/akka23Test/groovy/AkkaActorTest.groovy
dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaActorCellInstrumentation.java
dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaEnvelopeInstrumentation.java
dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinExecutorTaskInstrumentation.java
dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinPoolInstrumentation.java
dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinTaskInstrumentation.java
dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaRoutedActorCellInstrumentation.java
dd-java-agent/instrumentation/scala-concurrent/src/main/java/datadog/trace/instrumentation/scala/concurrent/ScalaForkJoinPoolInstrumentation.java
dd-java-agent/instrumentation/scala-concurrent/src/main/java/datadog/trace/instrumentation/scala/concurrent/ScalaForkJoinTaskInstrumentation.java

This tracks akka envelopes, enforces exclusion of mailbox scheduling and prevents tracing of a `ForkJoinTask` internal to `Dispatcher`

emit checkpoints on Envelope construction and invocation

---

dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/ApacheHttpAsyncClientInstrumentation.java
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/BasicFutureInstrumentation.java
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/HttpAsyncClientExchangeHandlerInstrumentation.java
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/TraceContinuedFutureCallback.java
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/test/groovy/CheckpointEmissionTest.groovy

HttpAsyncClient calls work like this
```
caller thread:              t0 |-| t1
server:                          |xxxxxxxxxxxxxx|
io thread:                                   t2 |----------| t3
```
Where `t0` is the time the request is made, `t1` is the request returns control to the caller (`t0`~`t1`), `t2` is when the client receives a response from the server and starts doing things like downloading and deserializing content, and `t3` is when the response is complete. If the server doesn't respond or there is an error, the gantt chart is similar.
Currently we only record that a span has started at `t0`, and that it has finished at `t3`. This PR emits an event at `t1` to indicate that span activity will migrate to an IO thread, and completes this migration at `t2` so that `[t2, t3]` can …

Better activity recording for Apache HttpAsyncClient

---

.circleci/config.yml

Now the weekly build with a clean cache from `master` failed with an OOM as well. This limits the number of workers during the build in an attempt to not exhaust the available memory of the node (since we're already running on an XL instance)

Limit workers during build

---

.circleci/config.yml

While only using the `branch` name as a cache identifier is convenient, it has the unfortunate side effect of picking up old caches for new `PR`s where the `branch` name is reused. This has led to misconfigured repositories slipping through CI, and later causing failures to resolve all dependencies on unrelated `PR`s.
This PR adds a checksum of the `branch` name and `PR` number to make the caches unique and the builds a bit cleaner.

Use PR number to ensure unique caches for builds

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java
dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ClientTest.groovy
dd-java-agent/instrumentation/netty-4.1/src/test/groovy/NettyClientCheckpointsTest.groovy

This incidentally also allows us to run the netty client tests in strict mode.

Prevent netty context leak from causing spurious emission of thread migration events

---

dd-java-agent/instrumentation/quartz-2/src/main/java/datadog/trace/instrumentation/quartz/QuartzSchedulingInstrumentation.java

spotted while browsing the code, the extra call doesn't actually change the resulting spans

Avoid duplicate call to finish quartz span

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AdviceUtils.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableFutureInstrumentation.java

I have been meaning to do this for a while:
* `AdviceUtils.capture` calls `ContextStore.putIfAbsent` which locks the object. This is quite a risky thing to do if the object is shared and the lock is contended, but it almost never is anyway as it is almost always called on exit from a constructor. Fixing `ContextStore.putIfAbsent` to make `FieldBackedContextAccessor` use an `AtomicReferenceFieldUpdater` to CAS the injected field is a possible mitigation that I have attempted before but a nontrivial unit of work. 
* We instrument every constructor in the hierarchies under `java.util.concurrent.FutureTask`, `*.com.google.common.util.concurrent.TrustedListenableFutureTask`, and `*.netty.util.concurrent.PromiseTask` (so all shaded versions of the last two) which means the same capturing logic …

Improve runnable future constructor instrumentation efficiency

---

internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/JenkinsInfo.java
internal-api/src/test/resources/ci/jenkins.json

Sometimes multiple repositories can be involved (e.g. forks). Jenkins can use the pattern `GIT_URL_N` with `N` {1,2,…}. 
By convention, `GIT_URL_1` should be the same as `GIT_URL`.

[CIAPP] Support `GIT_URL_1` to extract repository url info in tests executed in Jenkins

---

communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
communication/src/test/groovy/datadog/communication/ddagent/DDAgentFeaturesDiscoveryTest.groovy
communication/src/test/resources/agent-features/agent-info-without-metrics.json
dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricsAggregatorFactory.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/OkHttpSink.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/Sink.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/FootprintTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/MetricsAggregatorFactoryTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/OkHttpSinkTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy

This fixes a bug which would occur if the application started up before a trace agent with tracer metrics enabled, and the metric sink would fail validation, disabling metrics aggregation. The tracer would eventually receive a response from the trace agent once it would start up, and find that it supports metrics, setting a header to indicate that tracer metrics had already been computed, bypassing metrics aggregation in the trace agent. This is remedied by making `DDAgentFeaturesDiscovery` the golden source of trace agent feature availability, making inconsistency impossible.

Use DDAgentFeaturesDiscovery to enable/disable metrics aggregator

---

internal-api/src/main/java/datadog/trace/util/AgentProxySelector.java

The 0.83.0 release contains a change that means `Config.get().getNoProxyHosts()` will be backed by an immutable collection on recent JDKs. Unfortunately immutable collections have stronger restrictions over their arguments compared to regular collections. For example, `noProxyHosts.contains(null)` will throw a NPE with the new immutable set, whereas the same call would simply return `false` for a regular `HashSet`.
This PR fixes the regression by checking that the host is not `null` before checking the set.
I'll expand our tests of this code in a separate PR, I want to get this out asap so I'm keeping this PR as just the fix.

Avoid NPE when noProxyHosts is backed by an immutable set that disallows null arguments (Java9+)

---

dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/test/groovy/Aws2ClientTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java

There is a context leak in to a timer thread in the AWS-SDK 1 instrumentation.
Before
```
Test worker: |-startSpan/12-|-suspend/12-|-startSpan/13-|-----------|------------|-endSpan/13-|-suspend/12-|-startSpan/14-|-----------|------------|-endSpan/14-|-suspend/12-|-startSpan/15-|-----------|------------|-endSpan/15-|-suspend/12-|-startSpan/16-|-----------|------------|-endSpan/16-|-endSpan/12-|
Thread-31:   |--------------|------------|--------------|-resume/12-|-endTask/12-|------------|------------|--------------|-resume/12-|-endTask/12-|------------|------------|--------------|-----------|------------|------------|------------|--------------|-resume/12-|-endTask/12-|------------|------------|
Thread-33: …
```

remove AWS-SDK context leaks, record thread migrations in AWS-SDK 2 requests

---

dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/LettuceAsyncBiFunction.java
dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5AsyncClientTest.groovy

Tracks the entry of `LettuceAsyncBiFunction` into the fork join pool. There are some odd events still but this is because of the netty instrumentation.
Before
```
Test worker:                      |-startSpan/1-|-suspend/1-|----------|-suspend/1-|-suspend/1-|-suspend/1-|-----------|-----------|----------|-----------|----------|----------|----------|-----------|-startSpan/2-|-suspend/2-|----------|-suspend/2-|-----------|----------|-----------|-startSpan/3-|-suspend/3-|-suspend/3-|-suspend/3-|-suspend/3-|----------|-----------|-----------|----------|-----------|----------|----------|----------|-----------|
lettuce-nioEventLoop-4-1:         |-------------|-----------|-resume/1-|-----------|-----------|-----------|-suspend/1-|-endTask/1-|-resume/ …
```

emit checkpoints in span finishing bifunction

---

dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkControllerTest.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

We want to make it as easy as possible to enable the Allocation
Profiler. The override files are a neat and complete solution but are
not as easy to use. Customers can now enable the Allocation Profiler
with either:
- the command line parameter: `-Ddd.profiling.allocation.enabled=true`
- the environment variable: `DD_PROFILING_ALLOCATION_ENABLED=true`
It can always be enabled with https://docs.datadoghq.com/tracing/profiler/profiler_troubleshooting/#enabling-the-allocation-profiler

Add config toggle for Allocation Profiler

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java

Prevents context from leaking in to this:
```java
void put(RealConnection connection) {
assert (Thread.holdsLock(this));
if (!cleanupRunning) {
cleanupRunning = true;
executor.execute(cleanupRunnable);
}
connections.add(connection);
}
```
Before:
```
Test worker:           |-startSpan/11-|-suspend/11-|-----------|--------------|------------|-endSpan/11-|
OkHttp ConnectionPool: |--------------|------------|-resume/11-|--------------|------------|------------|
qtp1515428219-41:      |--------------|------------|-----------|-startSpan/12-|-endSpan/12-|------------|
```
After
```
Test worker:      |-startSpan/11-|--------------|------------|-endSpan/11-|
qtp1729586410-41: …
```

prevent context from leaking into okhttp3 ConnectionPool

---

dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/src/main/java/datadog/trace/instrumentation/scala/concurrent/CallbackRunnableInstrumentation.java
dd-java-agent/instrumentation/slick/slick.gradle
dd-java-agent/instrumentation/slick/src/main/java/datadog.trace.instrumentation.slick/SlickRunnableInstrumentation.java

Checkpoints now balance properly
Before:
```
Test worker: |-startSpan/5-|-------------|-----------|-----------|----------|-----------|-endSpan/5-|-----------|-startSpan/7-|-------------|-----------|-----------|-endSpan/7-|-startSpan/9-|--------------|------------|-----------|-endSpan/9-|
test-1:      |-------------|-startSpan/6-|-endSpan/6-|-suspend/5-|-resume/5-|-endTask/5-|-----------|-endTask/5-|-------------|-startSpan/8-|-endSpan/8-|-endTask/7-|-----------|-------------|-startSpan/10-|-endSpan/10-|-endTask/9-|-----------|
```
After:
```
Test worker: |-startSpan/5-|-suspend/5-|----------|-suspend/5-|-------------|-----------|----------|-----------|-----------|-endSpan/5-|-startSpan/7-|-suspend …
```

straighten out checkpoints in slick database driver

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerCallback.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java

Before:
```
Test worker:                                |-startSpan/1-|-startSpan/2-|-----------|-------------|-------------|-----------|-endSpan/1-|-----------|
kafka-producer-network-thread | producer-1: |-------------|-------------|-endSpan/2-|-------------|-startSpan/4-|-endSpan/4-|-----------|-----------|
-C-1:                                       |-------------|-------------|-----------|-startSpan/3-|-------------|-----------|-----------|-endSpan/3-|
```
After:
```
Test worker:                                |-startSpan/1-|-startSpan/2-|-suspend/2-|----------|-----------|----------|-------------|-------------|-----------|-----------|-endSpan/1-|-----------|
kafka-producer-network-thread | …
```

emit checkpoints to track kakfa producer span migration

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableInstrumentation.java

This allows the `RunnableInstrumentation`, which is _mostly_ unnecessary now we instrument other things like `RunnableFuture`, to be disabled by users who understand the **potential** risk for broken traces, but also prevents us from transforming every `AFn` in clojure applications.
To disable the instrumentation, set `-Ddd.integration.runnable.enabled=false`

namespace RunnableInstrumentation so it can be disabled in clojure apps

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AdviceUtils.java
dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpServerInstrumentationTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/CheckpointThreadMigrationTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScope.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

This fixes an issue where we see duplicate endTask events in akka-http, and will allow for other events to be eliminated (e.g. slick runnables).

only emit end checkpoints when a scope underwent a thread migration

---

dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcServerBuilderInstrumentation.java
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy

We have the same problem as OpenTelemetry had for server registration (https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3544), but not for client registration where there was already a guard against double registration.

prevent double registration of tracing interceptor when server builder is reused

---

dd-java-agent/instrumentation/jdbc/jdbc.gradle
dd-java-agent/instrumentation/jdbc/scalikejdbc/scalikejdbc.gradle

Also introduce latestDepJava11Test to test HikariCP 5.+

Cap HikariCP to 4.+ for latestDepTest because 5.+ requires Java 11

---

dd-java-agent/instrumentation/rediscala-1.8.0/rediscala-1.8.0.gradle
dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/OnCompleteHandler.java
dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/RediscalaInstrumentation.java

The rediscala instrumentation relies on `CallbackRunnable` but doesn't make good use of it, and since we instrument `CallbackRunnable` our testing is unrealistic. This makes the tests depend on the supporting instrumentation which will be active when the instrumentation is active for real, and removes the allocation of the completion handler. We can also see that the checkpoints emitted cover activity over the entire execution:
```
Test worker:                                            |-startSpan/2-|-suspend/2-|----------|-----------|----------|-----------|----------|-----------|----------|-----------|----------|-----------|----------|-----------|-----------|-startSpan/3-|-suspend/3-|----------|-----------|----------|-----------|----------|- …
```

make rediscala instrumentation scala-promise aware

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AdviceUtils.java

This prevents from allocating a new `State` object when we won't capture the scope, and is a necessary step towards making `Continuation.activate()` calls monomorphic when restoring context (i.e. make `NoopContinuation` redundant).

cheaper capturing of non-async-propagating scopes

---

dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkControllerTest.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

As it's still very much in Beta, we want to make it as easy as possible
for customers to try it out, without enabling it by default.

Add configuration knob to enable Heap Profiler

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TimelineCheckpointer.groovy
dd-java-agent/testing/testing.gradle

This mode is used for generating test cases for the profiling backend.
The generated files are parsed for test cases, and the profiling backend
uses them to verify that it can reconstruct the timeline appropriately.
We need "real world" scenarios for the profiling backend to support
every possible cases of valid (or not so valid) sequence of checkpoints.

Add printing mode for TimelineCheckpointer

---

dd-java-agent/instrumentation/opentelemetry/src/main/java/datadog/trace/instrumentation/opentelemetry/OtelTracer.java
dd-java-agent/instrumentation/opentelemetry/src/test/groovy/OpenTelemetryTest.groovy
dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTScopeManager.java
dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTScopeManager.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTTracer.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-ot/src/main/java/datadog/opentracing/OTScopeManager.java
dd-trace-ot/src/test/groovy/datadog/opentracing/OpenTracingAPITest.groovy

This makes sure that bad requests via the public OpenTracing/OpenTelemetry APIs don't affect auto-instrumentation traces.

Attempting to activate a null span should not leave the scope stack in an invalid state

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/MessageConsumerState.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageProducerInstrumentation.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/SessionInstrumentation.java
dd-java-agent/instrumentation/jms/src/test/groovy/JMS1Test.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

New config options:
- jms.propagation.enabled
- jms.propagation.disabled.topics
- jms.propagation.disabled.queues

Add config option to disable context propagation for specified JMS topics and queues

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/AdditionalLibraryIgnoresMatcher.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java

This class was already special cased, but wasn't updated when we stopped instrumenting `Callable` in favour of `RunnableFuture`, because we would instrument this code:
```java
protected V createEntry(final K key, KK cacheKey, Object v) {
boolean creator = false;
FutureTask task;
Object result;
if (v != null) {
task = (FutureTask)v;
} else {
task = new FutureTask(new Callable<V>() {
public V call() throws Exception {
return LoadingCache.this.loader.apply(key);
}
});
result = this.map.putIfAbsent(cacheKey, task);
if (result == null) {
creator = true;
task.run();
} else {
if (!(result instanceof FutureTask)) {
return result;
}
task = (FutureTask)result;
}
}
try {
result = task.get();
} catch (InterruptedException var9) {
throw new IllegalStateException("Interrupted while loading cache item", …
```

update additional ignores matcher ignore to avoid spurious context propagation

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java

Prevents propagation into this event loop:
```java
private void runOnEventLoop() {
assert eventLoop.inEventLoop();
boolean didSomeWork = false;
Write write;
while ((write = writes.poll()) != null) {
Channel channel = write.channel;
channels.add(channel);
channel.write(write.message, write.writePromise);
didSomeWork = true;
}
for (Channel channel : channels) {
channel.flush();
}
channels.clear();
if (didSomeWork) {
runsWithNoWork = 0;
} else if (++runsWithNoWork > maxRunsWithNoWork) {
// Prepare to stop
running.set(false);
// If no new writes have been enqueued since the previous line, we can return safely
if (writes.isEmpty()) {
return;
}
// Otherwise check if those writes have triggered a new run. If not, we need to do that
// ourselves (i.e. not return yet)
if …
```

prevent leaking into flusher event loop

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java

Cassandra: 
before:
```
=== Invalid checkpoint events encountered
resume/1 (thread: s0-admin-0)
=== Activity checkpoints by thread ordered by time
===== Invalid event sequences were detected. Affected spans are highlited by '***'
Test worker: |-startSpan/1-|-suspend/1-|----------|-suspend/1-|-suspend/1-|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|----------|-----------|-----------|-----------|----------|-----------|-----------|----------|-----------|-----------|-----------|----------|-----------|----------|-----------|-----------|----------|-----------|-----------|---- …
```

Remove cassandra and okhttp2 leaks

---

dd-trace-java.gradle

Adds support for the version of gradle we're using (`6.8.x`).
https://github.com/dorongold/gradle-task-tree/releases

Update task-tree to 2.1.0

---

dd-trace-ot/src/main/java/datadog/opentracing/OTSpan.java
dd-trace-ot/src/main/java/datadog/opentracing/TypeConverter.java

Various methods in OTSpan are returning the underlying span object, not the wrapped one.  This is problematic because users expect to be able to cast back to an OT type.

Prevent DDSpan from escaping unwrapped with OT

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/TagSettingAsyncListener.java

This is enough to get servlet checkpoints to line up, ignoring out of order span finishes, which are tolerated. The way the servlet instrumentations layer, it can be ambiguous which span is active, which is hard to address and isn't important except for things like profiler integration.
This also revealed some scope leaks in the glassfish service locator.
```
=== Activity checkpoints by thread ordered by time
===== Invalid event sequences were detected. Affected spans are highlited by '***'
dw-42:                |-startSpan/1-|-------------|-----------|----------|-suspend/1-|-------------|----------|-----------|-------------|-------------|-----------|-----------|----------|-------------|----------|-----------|-----------------|-----------------|-startSpan/7-|-------------|-----------|-susp …
```

emit thread migrations in TagSettingAsyncListener

---

dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle
dd-java-agent/instrumentation/kafka-streams-0.11/src/latestDepTest/groovy/KafkaStreamsTest.groovy
dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsProcessorInstrumentation.java

The method signature of what we're instrumenting changed in 2.6 from `process()` to `process(long)`.  By removing the no arg constraint, we now instrument either method.
I've also extended the test to verify the latest version of the library. In order to do so, I had to split the tests to resolve a compilation issue.
Inspired by https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3438.  Thanks @GuillaumeWaignier!

Fix instrumentation for Kafka Streams 2.6+

---

dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/HttpAsyncClientExchangeHandlerInstrumentation.java
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/TraceContinuedFutureCallback.java
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/test/groovy/CheckpointEmissionTest.groovy

Making the state machine resilient to redirects and failure is complicated, so this change cheats for finishing the span - it _always_ resumes before finishing.
The most interesting callbacks worth profiling are here:
```java
public void consumeContent(
final InternalState state,
final ContentDecoder decoder,
final IOControl ioctrl) throws IOException {
if (this.log.isDebugEnabled()) {
this.log.debug("[exchange: " + state.getId() + "] Consume content");
}
if (state.getFinalResponse() != null) {
final HttpAsyncResponseConsumer<?> responseConsumer = state.getResponseConsumer();
responseConsumer.consumeContent(decoder, ioctrl);
} else {
final ByteBuffer tmpbuf = state.getTmpbuf();
tmpbuf.clear();
decoder.read(tmpbuf);
}
}
public void produceContent(
final InternalState state,
final …
```

httpasyncclient checkpoints resilience

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java

this class uses a pool of invoker threads to deliver incoming messages to listeners
(the JMS message carries the span context so we don't need async propagation here, and as the invokers are re-used we don't want to risk scopes being captured when creating/rescheduling invokers)

Avoid potential scope leak in spring-jms' DefaultMessageListenerContainer

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerCallback.java

This fixes checkpoint validation for kafka-client and kafka-streams so it can be included for checkpoint regression testing

migrate parent span to network thread before it is reactivated on completion

---

buildSrc/src/main/groovy/InstrumentPlugin.groovy
buildSrc/src/main/groovy/MuzzlePlugin.groovy

Muzzle got broken when the byte buddy plugin changes were made that changed the compile directory to `raw`, causing the muzzle inspection to skip everything.
I also added an assert to the classloader creation to ensure that the instrumentation set is never empty.

Various muzzle fixes

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java

This matcher was added in #2963 - that PR originally disabled async propagation for `SelectorManager.connect`:
https://github.com/DataDog/dd-trace-java/commit/f56cf48#diff-95106a2e3e98d1d80bf3c90929ae2377454a9e151cd3eddb4990e3a97789501cR131
but during the life of the PR that `SelectorManager.connect` advice was removed:
https://github.com/DataDog/dd-trace-java/pull/2963/files#diff-95106a2e3e98d1d80bf3c90929ae2377454a9e151cd3eddb4990e3a97789501cR81
Since there no longer appears to be a context leak in `jetty-client` after the other changes from #2963 this PR simply removes the unused type matcher.

Remove unused org.eclipse.jetty.io.SelectorManager type matcher

---

dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTSpan.java
dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/TypeConverter.java
dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTSpan.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/TypeConverter.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
dd-smoke-tests/opentracing/src/main/java/datadog/smoketest/opentracing/OTWithAgentApplication.java
dd-trace-ot/src/main/java/datadog/opentracing/OTSpan.java

This was previously fixed with `dd-trace-ot` in #2967, but I forgot to apply the same change to the agent.
Also make OTSpan copies more consistent.

Prevent DDSpan from escaping unwrapped with OpenTracing Via the Agent

---

dd-java-agent/instrumentation/classloading/tomcat-testing/tomcat-testing.gradle
dd-java-agent/instrumentation/java-concurrent/lambda-testing/lambda-testing.gradle
dd-java-agent/instrumentation/jdbc/jdbc.gradle
dd-java-agent/instrumentation/jdbc/scalikejdbc/scalikejdbc.gradle
dd-java-agent/instrumentation/servlet/request-3/request-3.gradle
dd-java-agent/instrumentation/tomcat-5.5/tomcat-5.5.gradle

10.1+ seems will require Java 11 which is not compatible with our build currently.

Limit tomcat latest test to 10.0.+

---

dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/client/HttpClientResponseTracingHandler.java
dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientResponseTracingHandler.java
dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientResponseTracingHandler.java
dd-java-agent/instrumentation/netty-4.1/src/test/groovy/ReactorNettyTest.groovy

If the client times out or another exception is thrown after
the request is sent the span will not be closed

Ensure netty.client.request spans are finished

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/ContextStore.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/FieldBackedContextStore.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakMap.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakMapContextStore.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakMapSuppliers.java
dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/ClientCallImplInstrumentation.java
dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcServerDecorator.java
dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java
dd-trace-core/src/jmh/java/datadog/trace/core/PendingTraceWrite.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

The stacktrace is unlikely to be useful and not something that should be treated as an error.

Ignore exceptions thrown when canceling GRPC streaming

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInstrumentation.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterable.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterableDelegator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingList.java
dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle
dd-java-agent/instrumentation/kafka-streams-0.11/src/latestDepTest/groovy/KafkaStreamsTest.groovy
dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java
dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy

Internally `StreamTask` iterates through each `ConsumerRecord` and adds them to the queue.  This iteration triggers an extra span from the kafka instrumentation.  While evaluating implementation of #3001, I realized we could achieve similar behavior by unwrapping the Iterable.  This relies on specific behavior between the kafka and kafka streams instrumentation, but accomplishes the removal of the extra span.

Suppress extra span from Kafka Streams internal queuing

---

dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageProducerInstrumentation.java
dd-java-agent/instrumentation/jms/src/test/groovy/JMS1Test.groovy
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientCustomPropagationConfigTest.groovy
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitChannelInstrumentation.java
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/TracedDelegatingConsumer.java
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

Move destination checks into `Config` rather than repeat the same pattern many times.

DRY messaging propagation checks

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/MessageConsumerState.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/SessionState.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/jms/SessionStateTest.groovy
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/DatadogMessageListener.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageProducerInstrumentation.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageInjectAdapter.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageInstrumentation.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/SessionInstrumentation.java

... and create it lazily when the consumer is created instead of when the session is constructed
No change in external behaviour - this refactoring makes it easier to add features like time-in-queue spans.

Capture JMS session state in consumer state

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java

This avoids recursive interactions between the two agents which eventually complete, but take up a lot of startup time.

Globally exclude `com.contrastsecurity` types from instrumentation

---

buildSrc/build.gradle.kts
buildSrc/src/test/groovy/InstrumentPluginTest.groovy
gradle/dependencies.gradle

Several fixes and features added since 1.11.5: https://github.com/raphw/byte-buddy/releases
Note: this PR doesn't use the new `warmup` feature yet - that will be tested in a separate PR

byte-buddy 1.11.13

---

dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpClientInstrumentationTest.groovy
dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpServerInstrumentationTest.groovy
dd-java-agent/instrumentation/akka-http-10.0/src/latestDepTest/groovy/AkkaHttp102ServerInstrumentationTests.groovy
dd-java-agent/instrumentation/datastax-cassandra-3/src/test/groovy/CassandraClientTest.groovy
dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/test/groovy/CompletableFuturePromiseTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ForkJoinPoolPropagationTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/NettyExecutorInstrumentationTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/RejectedExecutionTest.groovy
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientCustomPropagationConfigTest.groovy
dd-java-agent/instrumentation/kotlin-coroutines/src/test/groovy/KotlinCoroutineInstrumentationTest.groovy
dd-java-agent/instrumentation/lettuce-4/src/test/groovy/Lettuce4AsyncClientTest.groovy
dd-java-agent/instrumentation/lettuce-4/src/test/groovy/Lettuce4SyncClientTest.groovy
dd-java-agent/instrumentation/opentelemetry/src/test/groovy/OpenTelemetryTest.groovy
dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
dd-java-agent/instrumentation/play-2.3/src/test/groovy/server/PlayAsyncServerTest.groovy
dd-java-agent/instrumentation/play-2.4/src/test/groovy/server/PlayAsyncServerTest.groovy
dd-java-agent/instrumentation/play-2.6/src/test/groovy/server/PlayAsyncServerTest.groovy
dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/groovy/SpringWebfluxTest.groovy
dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisAPITestBase.groovy
dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisClientForkedTest.groovy
dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisForkedTest.groovy
dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/client/VertxRxCircuitBreakerWebClientForkedTest.groovy
dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/client/VertxRxWebClientForkedTest.groovy
dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/client/VertxHttpClientForkedTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/CheckpointValidator.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/TimelineCheckpointer.groovy

This wraps up enabling most test cases which are passing the checkpoint validator. Now most test cases which are disabled fail consistently the checkpoint sequence validator without much noise.

Unmask most test cases passing the checkpoint validator

---

dd-java-agent/instrumentation/kafka-streams-0.11/src/latestDepTest/groovy/KafkaStreamsTest.groovy
dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java
dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy

When finishing the span, remove it to allow it to be GC'd and not linger.  Don't think it's causing any problems... just more sanitary.
Also fix a flake in the test.

Kafka Streams: remove span/scope from task

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/MessageConsumerState.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/SessionState.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/jms/SessionStateTest.groovy
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java

Follow on to #3026
This assumes that if a thread receives a message from the same session, any previous message scope associated with that thread is closed whether the message is received via the same consumer or not.
All active message scopes are still closed when the session is closed.

Simplify management of active message scopes by tracking them per-session-thread

---

dd-java-agent/instrumentation/jetty-client-9.1/src/main/java/datadog/trace/instrumentation/jetty_client/ResponseListenerAdapterInstrumentation.java
dd-java-agent/instrumentation/jetty-client-9.1/src/test/groovy/JettyClientTest.groovy

In Jetty Client 9.4.* the default implementation of `org.eclipse.jetty.client.api.Response$Listener.onBegin()` and `org.eclipse.jetty.client.api.Response$Listener.onFailure()` methods was moved from `org.eclipse.jetty.client.api.Response$Listener$Adapter` abstract class back to the `org.eclipse.jetty.client.api.Response$Listener` interface (with it targeting Java 8 it is possible to use the interface default methods).
That move broke the instrumentation emitting the 'resume span' checkpoint. This patch is fixing the instrumentation and removing the checkpoint sequence validation exclusions.

Fix jetty-client instrumentation for 9.4+

---

internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/CIProviderInfo.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/git/GitInfo.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/git/PersonInfo.java
internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/ci/CIProviderInfoTest.groovy
internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/ci/UserSuppliedCIInfoTest.groovy
internal-api/src/test/resources/ci/usersupplied.json

This PR extends the `CIProviderInfo` logic to allow setting manual Git information via environment variables.

[CIAPP] Allow setting manual Git information via env vars

---

dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkOngoingRecording.java

A snapshot is a frequent operation which doesn't require to be logged at
the warn level.

Fix log level for debug message

---

dd-java-agent/agent-profiling/profiling-uploader/profiling-uploader.gradle
dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/util/JfrCliHelperTest.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

When receiving a 413 error code, we only know that the profile is too
big to be accepted by the backend. However, we have no idea why the
profile is too big.
With this change, we try to extract information about the size of the
events and log it to the command line. This allows us to ask customers
for more informations, and react accordingly. For example, if the
profile is too big due to too many exceptions being thrown and
overloading the profile, we can advise the customer to disable the
Exception profiler.

 Dump information when a profile fails to upload because it's too big

---

dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/RouteHandlerDecoratorTest.groovy
dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyByteBodyInstrumentationTest.groovy
dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyCharBodyInstrumentationTest.groovy
dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/SessionFactoryInstrumentation.java
dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/SessionTest.groovy
dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/SessionFactoryInstrumentation.java
dd-java-agent/instrumentation/jax-rs-client-2.0/src/test/groovy/JaxRsClientAsyncTest.groovy
dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/KafkaClientTest.groovy
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientCustomPropagationConfigTest.groovy
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
dd-java-agent/instrumentation/kafka-streams-0.11/src/latestDepTest/groovy/KafkaStreamsTest.groovy
dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy
dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientBase.groovy
dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/client/VertxRxCircuitBreakerWebClientForkedTest.groovy
dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/client/VertxRxWebClientForkedTest.groovy
dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/client/VertxHttpClientForkedTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/IntervalValidator.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/server/http/TestHttpServer.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/TraceUtils.groovy
dd-java-agent/testing/src/test/groovy/TraceCorrelationTest.groovy
dd-java-agent/testing/src/test/groovy/checkpoints/IntervalValidatorTest.groovy
dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ScopeEventTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTestBase.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

Current state of the instrumentation will open a new span when a hibernate session is created. This span is closed when the session is closed. From the checkpoint PoV this has the consequence of attributing any work done between opening and closing the session (with the closing possibly happening on a completely different thread) would be attributed to hibernate, if not enclosed in some other span.
While it would be possible to pepper the checkpoint sequence with suspends/resumes which would put the session span to 'sleep' immediately after it has been created and then wake it up just for the time while an operation is being executed on behalf of that session this would create quite a lot of checkpoints without any additional value.
Therefore I am proposing to enhance the internal API for …

Fix Hibernate checkpoints sequence

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/report/EventEnrichment.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/report/EventEnrichmentSpecification.groovy

Fixed inconsistent between apm traces and appsec event

[AppSec] Attack events contains decimal spanId and traceId

---

.github/workflows/codeql-analysis.yml

Static code analysis on dd-trace-java using Github's Code Scanning.
This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to default branch. As of now only default security based CodeQL queries are configured. We can gradually add queries for Code Quality later. The SARIF results for the code-scanning job is uploaded as an artifact for reference.
The alerts will not show up on master branch until the PR gets merged. However we can see the code-scanning alerts introduced with this PR from here: https://github.com/DataDog/dd-trace-java/security/code-scanning?query=pr%3A3072+tool%3ACodeQL

Setting up codescanning for dd-trace-java

---

dd-java-agent/agent-tooling/agent-tooling.gradle
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/UnionMap.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/log/UnionMapTest.groovy
dd-java-agent/instrumentation/jboss-logmanager/src/main/java/datadog/trace/instrumentation/jbosslogmanager/ExtLogRecordInstrumentation.java
dd-java-agent/instrumentation/logback-1/src/main/java/datadog/trace/instrumentation/logback/LoggingEventInstrumentation.java

Also reduce capacity of correlation map to match expected size
Behaviour of the reworked `UnionMap` is validated by using Guava's `MapTestSuiteBuilder`

Rework UnionMap to allow mutable operations

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/KafkaClientTest.groovy
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerCallback.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientCustomPropagationConfigTest.groovy
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy

This reverts commit 72112cb829305400f21a797db3cb1c00cb721128.
This change lead to incorrect suspends for active spans. It fixes the `kafka-clients-0.11` and `kafka-streams-0.11` instrumentations.

Revert "migrate parent span to network thread before it is reactivated on completion (#2977)"

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/UnionMap.java

Optimizes for the common case where only `get` is called as well as when the primary MDC map is empty.

Make UnionMap deduplication lazy

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/MessageBatchState.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/MessageConsumerState.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/MessageProducerState.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/SessionState.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/TimeInQueue.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/jms/SessionStateTest.groovy
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/DatadogMessageListener.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageProducerInstrumentation.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageExtractAdapter.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageInjectAdapter.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/SessionInstrumentation.java
dd-java-agent/instrumentation/jms/src/test/groovy/TimeInQueueForkedTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

To enable the new “time-in-queue” feature set the following system property to turn off the legacy JMS mode:
```
-Ddd.jms.legacy.tracing.enabled=false
```
or alternatively set this environment variable:
```
DD_JMS_LEGACY_TRACING_ENABLED=false
```
When legacy mode is off you should see JMS queues/topics appear in the service map, with connections to the services that use them.

Support synthetic "time-in-queue" for JMS

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java

Turning off async propagation for `TransactionBroker.beginTransaction` stops those `FutureTask` instances from being captured when the transaction is constructed and results in better checkpoints for ActiveMQ (we can't exclude these instances by type because their type is `FutureTask`, ie. they don't extend it.)
Before:
```
Test worker:                                    |-startSpan/1-|-suspend/1-|----------|-endSpan/1-|-startSpan/2-|-endSpan/2-|-startSpan/3-|-endSpan/3-|-----------|-----------|----------|-----------|----------|-----------|----------|-----------|-----------|-----------|----------|-----------|----------|-----------|-startSpan/4-|-----------|-----------|----------|-suspend/4-|-----------|-----------|----------|-endSpan/4-|----------|-----------|-----------|-----------|------ …
```

ActiveMQ's Transaction class creates two instances of `FutureTask` that are only ever used synchronously and could be re-used

---

dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java

This follows the same pattern as in RabbitMQ, where the producer and consumer both use the configured service name for the new "time-in-queue" approach.

Store local service name for JMS in static field

---

dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisAPIInstrumentation.java
dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/RedisAPIImplSendAdvice.java
dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_redis_client/ResponseHandlerWrapper.java
dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisAPITestBase.groovy

In this PR the main point of change is actually activating the span started in `RedisAPICallAdvice` and dealing with the `Future` handler in `RedisAPIImplSendAdvice` where we are hooking into `RedisAPIImpl.send()` method to be able to get our hands on the `Future` instance we need to set the handler to.
In that advice we will try to add the handler if the future is not already completed and simply run the handler if the future is completed. However, this still does not prevent double firing because the future may be completed in between two checks for being complete - therefore the handler is enhanced to ignore the second attempt to run the handling logic.

Fix scope activation in vertx-redis client

---

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWS1ClientTest.groovy
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/test/groovy/Aws2ClientTest.groovy

This is a breaking change, but only for specific AWS requests that relate to messaging.
Users who rely on the old behaviour can use the following service mapping:
```
-Ddd.service.mapping=sqs:java-aws-sdk,sns:java-aws-sdk
```

Use 'sqs' as service name when sending/receiving messages and 'sns' when publishing

---

dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Decorator.java
dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
dd-java-agent/instrumentation/junit-4.10/src/test/java/org/example/TestParameterized.java
dd-java-agent/instrumentation/junit-5.3/src/main/java8/datadog/trace/instrumentation/junit5/JUnit5Decorator.java
dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestParameterized.java
dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGDecorator.java
dd-java-agent/instrumentation/testng-6.4/src/test/groovy/TestNGTest.groovy
dd-java-agent/instrumentation/testng-6.4/src/test/java/org/example/TestParameterized.java
internal-api/src/main/java/datadog/trace/util/Strings.java
internal-api/src/test/groovy/datadog/trace/util/StringsTest.groovy

This PRs adds the `escapeToJson` method to the `Strings` class to prepare the string used as argument to be JSON compatible. 
This method is used in the builder to create the `test.parameters` JSON attribute for the test instrumentation.

[CIAPP] Escape test parameters to be JSON compatible.

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java

AppSec can produce NPE if web server provide null values for addresses.
To avoid this, we will ignore addresses with null values.

[AppSec] Fixed NPE caused by absent address values

---

dd-java-agent/agent-profiling/profiling-auxiliary-async/profiling-auxiliary-async.gradle

The musl x64 async profiler build was left out previously to minimize the footprint but it seems to be required for the relenv deployments.

Add the musl specific build of async profiler for the relevn

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecoratorTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

- `DB_CLIENT_HOST_SPLIT_BY_INSTANCE` is set to `true` and
-  The database name is the same as the service name (for example `jdbc:postgresql://db.example.com:5432/myservice` gives database name `myservice`)
Two services with the same name `myservice` but different types. one of type web and another of type db. 
Found only one service with name `myservice` of type web (and no database service). All database traces are mapped to the web service. 
Introduce a new boolean variable `DB_CLIENT_HOST_SPLIT_BY_INSTANCE_TYPE_SUFFIX` to control adding the database type as a suffix to the database service name in case of `DB_CLIENT_HOST_SPLIT_BY_INSTANCE` sets to `true`. For instance `myservice-postgresql`

Add database client by host split by instance type suffix

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/testing/src/test/groovy/synthetic/SyntheticForkedTest.groovy
dd-java-agent/testing/src/test/java/synthetic/SyntheticTestInstrumentation.java

This is necessary to instrument the inner workings of some Scala frameworks.
* The default behavior is still to skip synthetic methods, but that can be changed on a per instrumentation basis.
* My highly unscientific running of the class loading benchmark with the whole of `http4s-blaze-client` and dependencies on the class path did not show any slowdown du to the changes in matchers.

Enable instrumentation of synthetic methods

---

dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java
utils/container-utils/src/main/java/datadog/common/container/ServerlessInfo.java
utils/container-utils/src/test/groovy/ServerlessInfoTest.groovy

This PR adds support for the Serverless extension by
- detecting whether the extension is present
- depending on the result, switch the `PrinterWriter` for the regular `DDAgentWriter`
- flushing immediately after the write().
Note that I was not able to use the existing `flushFrequencySeconds` as when set to 0, switch to another behaviour (cc : https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingWorker.java#L124 )

[Serverless] add extension support

---

buildSrc/build.gradle.kts
buildSrc/src/test/groovy/InstrumentPluginTest.groovy
gradle/dependencies.gradle

Changes since last upgrade...
1.12.0
- Introduce detection for Graal native image execution.
- Correctly resolve interface implementations in revers order when compiling method graph.
- Adjust lambda instrumentation strategy to support Java 17.
1.11.22
- Remove automatic frame padding mechanism in favor of explicit NOP instruction after injected blocks.
1.11.21
- Allow Advice.PostProcessor to emitt frames.
- Add possibility for Advice.AssignReturned to suppress exceptions.
- Add frame when rebasing constructors to avoid breakage if frames are assumed prior to super constructor call.
1.11.20
- Add option for AsScalar annotation to assign default value instead of ignoring it.
- Add transform-runtime goal to Byte Buddy Mojo to allow for running plugins with runtime class path included. …

byte-buddy 1.12.0

---

.github/workflows/codeql-analysis.yml
dd-java-agent/agent-profiling/profiling-auxiliary-async/profiling-auxiliary-async.gradle
dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AsyncProfilerConfigEvent.java
dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
dd-java-agent/agent-profiling/profiling-auxiliary/src/main/java/com/datadog/profiling/auxiliary/ProfilingMode.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

In order to correctly interpret the async profiler collected samples a config describing event is needed.

Generate async profiler config event when async profiler is enabled.

---

.gitlab-ci.yml

I noticed the gitlab build complaining about OOM in some daemon workers

Update gitlab heap settings to match circleci

---

dd-java-agent/agent-profiling/profiling-auxiliary-async/profiling-auxiliary-async.gradle

... in case main build JDK is Java8
Same technique as used in https://github.com/DataDog/dd-trace-java/blob/v0.90.0/dd-trace-core/jfr-openjdk/jfr-openjdk.gradle#L31 and https://github.com/DataDog/dd-trace-java/blob/v0.90.0/dd-java-agent/agent-profiling/profiling-controller-openjdk/profiling-controller-openjdk.gradle#L38

Fork Java11 compiler for profiling-auxiliary-async

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AdviceUtils.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ContinuationClaim.java
dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/src/main/java/datadog/trace/instrumentation/scala/concurrent/CallbackRunnableInstrumentation.java
dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseObjectInstrumentation210.java
dd-java-agent/instrumentation/scala-promise/scala-promise-2.13/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseObjectInstrumentation213.java
dd-java-agent/instrumentation/scala-promise/scala-promise-2.13/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseTransformationInstrumentation.java
dd-java-agent/instrumentation/scala-promise/src/main/java/datadog/trace/instrumentation/scala/PromiseHelper.java
dd-java-agent/instrumentation/scala-promise/src/test/groovy/ScalaUnitPromiseTestBase.groovy
dd-java-agent/instrumentation/scala-promise/src/test/scala/PromiseUtils.scala
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-ot/src/test/groovy/datadog/opentracing/CustomScopeManagerTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScope.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

This PR fixes a Scope leak (thanks @charliegracie) and moves common code that was repeated and diverging in 2.10/2.13 into the shared `PromiseHelper`, while also removing some workarounds for profiling migration events.

Clean up Scala promise instrumentation

---

dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpServerInstrumentationTest.groovy
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/test/groovy/CheckpointEmissionTest.groovy
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/test/groovy/Aws2ClientTest.groovy
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
dd-java-agent/instrumentation/jdbc/src/test/groovy/RemoteJDBCInstrumentationTest.groovy
dd-java-agent/instrumentation/mongo/driver-3.10-sync-test/src/test/groovy/MongoSyncClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-3.7-core-test/src/test/groovy/MongoCore37ClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-4.0-test/src/test/groovy/Mongo4ClientTest.groovy
dd-java-agent/instrumentation/netty-4.1/src/test/groovy/NettyClientCheckpointsTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/TimelineCheckpointer.groovy
dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/EndpointEvent.java
dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/EndpointTracker.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
internal-api/src/main/java/datadog/trace/api/Checkpointer.java
internal-api/src/main/java/datadog/trace/api/SamplingCheckpointer.java
internal-api/src/main/java/datadog/trace/api/SpanCheckpointer.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
internal-api/src/test/groovy/datadog/trace/api/SamplingCheckpointerTest.groovy

We seem to be having a problem with a slack between the checkpoints generated for a certain local root span and the corresponding `EndpointEvent` - the checkpoints _may_ all get written into a recording preceding the one containing the `EndpointEvent` for that particular local root span. 
In order to ease debugging and allow us to confirm or reject this assumption this PR is modifying the `EndpointEvent` to capture the start and end time as well as the time it took to handle that endpoint.
Most of the changes are in the checkpoint tests where it is necessary to match a new call `onRootSpanStarted()` when a local root span is created/started. 
The rest is rather straightforward and the only 'controversial' thing may be adding a new volatile field to `DDSpan` - if there is a better way to …

Make EndpointEvent durational to ease debugging any slack issues

---

dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkControllerTest.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

With unlimited checkpoints the raw JFR recording can grow significantly and this leads to truncated profiling data which can be particularly misleading.
The PR adds the possibility to change the maximum recording size while keeping the currently used value as the default (eg. nothing will change unless a user will override the default)

Make the JFR recording max size configurable

---

dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle

New release of `spring-kafka` that pulls in kafka `3.x` causes latestDepTest to start failing (They're on 2.x)

Limit spring-kafka version used in latestDepTest to 2.7.x

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java

This PR adds the logic to configure the `Agent` disabling all the agent features but CI Visibility if this one is enabled.
The override only happens if the user does not explicitly set the property.
Additionally, the `dd.prioritization.type` is set to `ENSURE_TRACE` if CI Visibility is enabled.

[CIAPP] Agent configuration preset when CI Visibility is enabled

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
internal-api/src/main/java/datadog/trace/api/Platform.java
internal-api/src/test/groovy/datadog/trace/api/PlatformTest.groovy

If running with the profiler enabled on Oracle JDK 7, we log that we found Oracle JDK 8.

Don't log that Oracle JDK 8 was found and try to start Profiler on JDK 7

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java

This PR allows installing tracer and instrumentations if `dd.civisibility.enabled` is `true`.
Context: CI Visibility also uses the tracer and instrumentations to provide its features. As we can disable `tracing` and enable `civisibility` manually, we need to add these checks explicitly to continue installing the tracer and instrumentations if `tracing` has been disabled.

[CIAPP] Ensure both the tracer and instrumentations are installed if `dd.civisibility.enabled` is `true`

---

dd-trace-core/src/main/java/datadog/trace/civisibility/CiVisibilityTraceInterceptor.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/civisibility/CiVisibilityTraceInterceptorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/TraceInterceptorTest.groovy
dd-trace-core/src/test/java/datadog/trace/TestInterceptor.java

This PR adds a new `CiVisibilityTraceInterceptor` that applies the following changes:
* If the root span type is not `test`,  the entire trace is dropped.
* If the root span type is `test`, we ensure all spans have the CI Visibility origin metadata.
Context:
The `CI Visibility` mode can use the same integrations used by the `Tracing` mode to have the same visibility in end-to-end tests. That means a test span potentially can have HTTP, SQL, Kafka, etc. children spans. This fact may have implications with Billing. 
We want to ensure that all generated traces are billed by CI App and not by APM if CI Visibility is enabled.

[CIAPP] Avoid sending non-CIVisibility traces if `CIVisibility` mode is enabled.

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/report/ReportServiceImpl.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/report/ReportStrategy.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/report/ReportServiceImplTests.groovy
dd-smoke-tests/appsec/appsec.gradle
dd-smoke-tests/appsec/springboot/springboot.gradle
dd-smoke-tests/appsec/springboot/src/main/java/datadog/smoketest/appsec/springboot/SpringbootApplication.java
dd-smoke-tests/appsec/springboot/src/main/java/datadog/smoketest/appsec/springboot/controller/WebController.java
dd-smoke-tests/appsec/springboot/src/main/resources/application.properties
dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
dd-smoke-tests/appsec/src/main/groovy/datadog/smoketest/appsec/AbstractAppSecServerSmokeTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
settings.gradle

AppSec smoke test implemented based on SpringBoot smoke test.
Added AppSec report simulator to track if the malicious request reported correctly.
Thу test is a sequence of 200 malicious requests. Each request will be detected by AppSec and should be sent 200 events to the backend with corresponding information about the attack. To validate AppSec we are checking events reported by AppSec.
Since the event dispatch mechanism has a timeout (minimum and maximum time between dispatches), I added the `appsec.report.timeout` configuration option to force the maximum interval between dispatches. Thus, for tests, we set the value `-Dappsec.report.timeout=0`, which allows perform tests fast as possible (event commitment happens almost instantly).
To use the additional option, I had to modify …

[AppSec] Added smoke test to validate WAF

---

dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java

A followup fix moving the 'recordingSampleLimit' field out of the sampler configuration so that it can be used even if the rate limit is disabled.

Fix NPE when no checkpoint rate limit is set

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
dd-java-agent/instrumentation/grizzly-http-2.3.20/src/main/java/datadog/trace/instrumentation/grizzlyhttp232/GrizzlyDecorator.java
dd-java-agent/instrumentation/jetty-7.0/src/main/java/datadog/trace/instrumentation/jetty70/JettyServerInstrumentation.java
dd-java-agent/instrumentation/spray-1.3/src/main/scala/datadog/trace/instrumentation/spray/SprayHelper.scala
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/TraceUtils.groovy

This is to ensure that every web server that tracing supports also reports all data to AppSec. A few of the instrumentations didn't call `DECORATOR.beforeFinish`, and have now been fixed.

[AppSec] Check that all IG callbacks are called

---

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java

A follow up to https://github.com/DataDog/dd-trace-java/pull/3172 .  `ProfilingUploader` doesn't use `OkHttpUtils` so uploading profiles via named pipe was missed.

Support uploading profiles via windows named pipe

---

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/IterationSpansForkedTest.groovy
dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
dd-trace-ot/src/main/java/datadog/opentracing/TypeConverter.java
dd-trace-ot/src/test/groovy/datadog/opentracing/CustomScopeManagerTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/IterationSpansForkedTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScope.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScopeManager.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ScopeSource.java

When iterating over a potentially open-ended iteration, such as polling messages from a queue:
* Call `AgentTracer.closePrevious(finishSpan)` just before receiving the message
* set `finishSpan` to `false` if you intend to finish spans on a different condition, such as on a `commit`
* Create a new span for consuming the message
* Call `AgentTracer.activateNext(messageSpan)` to activate that span and register it for cleanup
There's no need to store the resulting scope - it will be automatically closed either when the next message is received, when a surrounding non-iterating scope is closed, or when the span times out. A background task is only scheduled when there's no surrounding non-iterating scope to detect when the iteration scope should be closed, or when a custom scope manager is …

Implement 'closePrevious' and 'activateNext' to help track potentially open-ended iterations

---

dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogHttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/HaystackHttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/XRayHttpCodec.java
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpExtractorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpExtractorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpExtractorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpExtractorTest.groovy

Previously we weren't extracting `Forwarded` headers because the code was only called when the header started with `X`
(`Forwarded` is the new [standard header](https://datatracker.ietf.org/doc/html/rfc7239) replacing `X-Forwarded-For` etc.)

Fix 'Forwarded' header extraction

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyByteBodyInstrumentationTest.groovy
dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyCharBodyInstrumentationTest.groovy
dd-java-agent/instrumentation/opentelemetry/src/test/groovy/OpenTelemetryTest.groovy
dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedContext.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/ForwardedExtractedContext.java
dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
internal-api/internal-api.gradle
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ForwardedTagContext.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TagContext.java

Saves space when there's no Forwarded headers, such as when propagating traces over non-HTTP routes such as JMS or other messaging systems.

Reduce extracted cost when no forwarded data

---

dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedContext.java

it's only ever set just after construction time and is never read

Remove unused 'samplingPriorityLocked' flag from ExtractedContext

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExcludeFilter.java

Please don't instrument the Runnables internal to the `WeakCache` implementation

Don't instrument Runnables internal to ConcurrentLinkedHashMap

---

dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy

Estimated size before according to [JOL](https://github.com/openjdk/jol):
```
datadog.trace.core.DDSpan object internals:
OFF  SZ                                 TYPE DESCRIPTION                  VALUE
0   8                                      (object header: mark)        N/A
8   4                                      (object header: class)       N/A
12   1                              boolean DDSpan.forceKeep             N/A
13   1                              boolean DDSpan.withCheckpoints       N/A
14   2                                      (alignment/padding gap)      
16   8                                 long DDSpan.startTimeMicro        N/A
24   8                                 long DDSpan.startTimeNano         N/A
32   8                                 long DDSpan.durationNano …
```

Reduce size of emittingCheckpoints field from 4 bytes to 1 byte

---

dd-java-agent/appsec/appsec.gradle
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy

Changed the way we are calling WAF to enforce stateful mode (using WAF Additive API).
Since we are calling WAF several times at different stages of request processing, we need to keep state of WAF (collected data) between calls. 
For example, we will call WAF three times:
1. At the beginning, when parsed URI and http headers;
2. When request body read;
3. When response status available.
For each stage, we need to keep information about perviously collected data related to current request. This requirement based on fact that some of attacks could be detected by compounded data received at different stages.
Enforce using Additive API, allows to share collected data between WAF calls and will be bounded by request context lifetime.
Basically, we are creating WAF Additive context, during the …

[AppSec] Enabled WAF stateful mode (WAF Additive API)

---

dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy

This also avoids one call to `Clock.currentMicroTime()` / `System.currentTimeMillis()` for every internal-clock based span
One important historical behaviour to call out is "[stopping with a timestamp disables nanotime](https://github.com/DataDog/dd-trace-java/blob/v0.91.0/dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy#L203)" - in other words when `finish` is called with a duration and the start time is from the internal clock then we need to remove the tick-based part (effectively anything smaller than millisecond precision.)
Estimated size before according to JOL: 
```
datadog.trace.core.DDSpan object internals:
OFF  SZ                                 TYPE DESCRIPTION                  VALUE
0   8                                      (object header: mark)        N/A
8 …
```

Save space by only storing the start-time in DDSpan once and converting it as appropriate

---

dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/CheckpointSamplerConfigEvent.java
dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/CheckpointSummaryEvent.java
dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java

Moves the information about the hard limit for the number of checkpoints in the recording to `CheckpointSummaryEvent` as the limit is applied even when no rate limit is specified and the `CheckpointSamplerConfigEvent` would not be emitted.
Make the information about the checkpoint hard limit always available.

Move the checkpoint hard limit info to CheckpointSummaryEvent

---

gradle/wrapper/gradle-wrapper.properties

Upgrades gradle to the latest `6.x` version `6.9.1`
Get bug fixes
This has support for running gradle natively on Apple Silicon

Upgrade gradle to 6.9.1

---

.githooks/pre-commit
gradle/codenarc.gradle

Update CodeNarc to the latest version 2.2.0.
Added a git hook to run CodeNarc check.
Running CodeNarc prior the git push will catch Groovy issues before CI does it.
N/A

Bump CodeNarc to 2.2.0

---

dd-java-agent/appsec/appsec.gradle
dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfig.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
dd-java-agent/appsec/src/main/resources/default_config.json
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/test/StubAppSecConfigService.groovy
dd-java-agent/appsec/src/test/resources/test_multi_config.json

Fixed AppSec rules file parser.
Added support fo both rules formats `1.x` and `2.x`
Using rules file, downloaded from dashboard, caused an exception at AppSec startup, because of inconsistent rules file format. This been preventing AppSec to protect customers application, when they are trying to use external rules file.

[AppSec] Fixed rules file parser

---

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle

Upgrades JMXFetch to `0.44.5` that has upgraded the `log4j` dependency to `2.12.2` which has fixed the vulnerability.
Ease fears of `dd-trace-java` possibly being affected by the `log4j` vulnerability, which wasn't the case since the build explicitly excludes the `log4j` artefacts and never use or ship them.

Upgrade JMXFetch to 0.44.5 even though we exclude log4j

---

dd-java-agent/agent-profiling/profiling-auxiliary-async/src/test/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfilerTest.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

This tries to use perf and fallbacks to wall
`itimer` is very broken on Linux, we don't want to depend on it.

Default to cpu mode for async-profiler

---

dd-trace-core/src/main/java/datadog/trace/common/sampling/RuleBasedSampler.java
dd-trace-core/src/test/groovy/datadog/trace/common/sampling/RuleBasedSamplingTest.groovy

Mark the ruler based sample's decisions with user priority.
Decisions that are originated from any user configuration to the `RuleBasedSampler` use priority values -1 (for forced rejection) and 2 (for forced keeping). This means that `RuleBasedSampler` sampling configurations will always be strictly respected by the whole Datadog processing pipeline.
See https://github.com/DataDog/dd-trace-rb/pull/1769

Use USER_(KEEP/REJECT) for RuleBasedSampler

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy

Fixed AppSec events reporting issue.
In case of multiple attacks in request, were reported only the first one (all remaining were missed).

[AppSec] Report multiple events per request

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy

Fixed AppSec events reporting issue. (same as #3280 but for legacy reporting system)
In case of multiple attacks in request, were reported only the first one (all remaining were missed).

[AppSec] Report multiple events per request (legacy)

---

dd-java-agent/agent-profiling/profiling-auxiliary-async/profiling-auxiliary-async.gradle
gradle/dependencies.gradle

Uses a fixed (non-snapshot) async profiler dependency.
With only snapshot dependency it is hard to invoke rebuild with the update version without introducing some bogus PRs and rebuilds.
Also, the resulting build artifact will be reproducible as it will refer a pinned version.

Peg the async-profiler dependency version to avoid surprises

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
dd-java-agent/instrumentation/opentelemetry/src/test/groovy/OpenTelemetryTest.groovy
dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogHttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedContext.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/ForwardedExtractedContext.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/XRayHttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpExtractorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpInjectorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpExtractorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpInjectorTest.groovy
dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

instead use a dedicated field in PendingTrace along with new internal span methods. These methods are also used to record end-to-end duration for iteration spans when they are overdue or go out-of-scope - this helps move messaging integrations over to iteration spans when consuming.
The old baggage headers are used when propagating end-to-end data, just in case we're receiving messages from an old tracer or sending messages to an old tracer.
There's also a new flag `dd.trace.legacy.e2e.duration.enabled` which re-enables the old baggage approach when `true`

Replace end-to-end baggage implementation

---

dd-java-agent/dd-java-agent.gradle
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingListIterator.java

Enables use of `AgentSpan.closePrevious` and `AgentSpan.activateNext` when consuming Kafka records.
Use the new shared mechanism introduced in #3194 for tracking and cleaning up Kafka iteration scopes.

Use AgentSpan iteration API when consuming Kafka records.

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingListIterator.java

This is a small optimization - the last scope of the iteration will timeout if nothing closes it, but this is a good signal it can be closed early

Close last record scope when iterator indicates there are no more records

---

dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AsyncProfilerConfigEvent.java
dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/resources/jfr/dd.jfp
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/JfrProfilerSettings.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkOngoingRecording.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/ProfilerSettingEvent.java
dd-java-agent/agent-profiling/profiling-controller/profiling-controller.gradle
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilerSettingsSupport.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/ProfilingIntegrationTest.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

Emits JFR events describing the current profiler configuration
We want to be able to read the profiler settings and use them in other calculations/checks

Emit profiler setting events

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

AppSec reports metrics/events for span with `web` type.  
Several customers reported that database services were showing up in their list of AppSec services (which is obviously wrong as we only support web services as of now).

[AppSec] Report metrics for web span only

---

dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
dd-trace-ot/src/main/java/datadog/opentracing/TypeConverter.java

Avoids code in `TypeConverter` calling a method in the OpenTracing API that was deprecated and later removed
Fixes a third-party build issue where the GraalVM step fails due to use of the missing method (this particular call is not used for 0.33.0 because we don't support custom scope managers with 0.33.0 but the existence of this call in the bytecode is tripping a check during GraalVM's static analysis)
Note that `CustomScopeManagerWrapper` still calls the removed method - but it also calls `ScopeManager.active()` which was also removed in 0.33.0. This wrapper class is only ever used when someone installs a custom scope manager, so it doesn't cause the same GraalVM failure as the call in `TypeConverter`. It would only be an issue if someone installed a custom scope manager when using …

Avoid calling `Scope.span()` which was removed in OT 0.33.0

---

dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/PropertiesConfigSource.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Replace it with the actual path which ConfigProvider loaded properties from

Remove incorrect check that meant 'trace.config' location was never logged

---

dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
dd-trace-ot/src/main/java/datadog/opentracing/TypeConverter.java
dd-trace-ot/src/ot31CompatabilityTest/groovy/OT31ApiTest.groovy
dd-trace-ot/src/ot33CompatabilityTest/groovy/OT33ApiTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/IterationSpansForkedTest.groovy

To do this we avoid deprecated/removed methods as much as possible even if it means taking
a more circuitous route. We also need to support having an active span but no active scope
when querying the scope manager because the API to retrieve the scope was removed in OT33.

Support custom scope managers with OT33

---

dd-java-agent/agent-profiling/profiling-uploader/profiling-uploader.gradle
dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

This PR add supports for the V2.4 format uploads. It allows to send requests compliant with a new format used by Datadog profiling intake.
The new format can be activated by enabling `-Ddd.profiling.format.v4.enabled=true` flag, the new format is disabled by default.
The new format will supersede the current one for which the support will be removed afterwards.

Switch to profiling V2.4 format uploads

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/KnownAddresses.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
internal-api/src/main/java/datadog/trace/api/gateway/Events.java
internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java
internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java

Implemented support for HTTP response code analysis - required for Rule 404.
Reading and analysis of the response status happens at the beginning of http response, BEFORE actual data will be committed.
Status code type in KnownAddresses changed to String, because of WAF currently able to process only strings.

[AppSec] Added response status code analysis

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/SessionState.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java

* Avoid creating captured spans buffer in auto-ack mode
* Finish time-in-queue span on consumer close when using auto-ack (otherwise leave it to the session)

Minor JMS related cleanup

---

buildSrc/src/test/groovy/InstrumentPluginTest.groovy

Two changes:
1) use a local test-kit directory, in case the global one has become corrupted as discussed in Gradle issue 4506
2) enable debug mode to stop GradleRunner from launching a daemon that's still running for a while after test cleanup, leaving undeleted files
According to https://discuss.gradle.org/t/testkit-how-to-turn-off-daemon/17843 this is the only way at the moment to turn off this daemon.
PS. the global test-kit directory is usually `$TMPDIR/.gradle-test-kit-${USER}` - if you happen to see GradleRunner failures involving `InstrumentPluginTest` before this is merged then removing this directory should resolve them.

Make our use of GradleRunner when testing our buildSrc 'Instrumentation' plugin more robust

---

dd-java-agent/agent-profiling/profiling-auxiliary-async/profiling-auxiliary-async.gradle
dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
gradle/dependencies.gradle

Updates the async-profiler version to 2.6-DD-20220115
Get the latest fixes and improvements:
- using perf to deliver sampling signals (on linux)
- properly mark hidden frames
- and more

Update the async-profiler version

---

buildSrc/build.gradle.kts
gradle/repositories.gradle

This should help avoid timeouts when checking jcenter for artifacts that we know live elsewhere.

Move jcenter to last in repo list (pending removal)

---

dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy
dd-java-agent/src/test/java/jvmbootstraptest/JmxStartedChecker.java
gradle/dependencies.gradle

Updates the internal statsd client to the latest version: 4.0.0
The updated version is required for windows named pipe support
`JMXFetchTest` initially failed. Adding a sleep in `JmxStartedChecker` fixed the issue. Since I was already looking at the code, I cleaned up the test class a bit:
- Added a socket timeout so a failing test doesn't hang the build forever
- Created a new socket instance per test so that they are isolated
- Cleaned up some of the `setup`/`when`/`then` statements

Update statsd client to the latest

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/MessageConsumerState.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
dd-java-agent/instrumentation/jms/src/test/groovy/TimeInQueueForkedTest.groovy
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Setting this flag makes messaging integrations use a different broker service name according to the destination.
The new system property is
```
-Ddd.message.broker.split-by-destination=true
```
You can also set this environment variable:
```
DD_MESSAGE_BROKER_SPLIT_BY_DESTINATION=true
```
Also note that this only applies when legacy tracing is turned off for the messaging integration since it relies on the new "time-in-queue" trace structure, ie:
```
-Ddd.jms.legacy.tracing.enabled=false
```

Add '-Ddd.message.broker.split-by-destination=true' flag

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableFutureInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/FutureTaskContinuationTest.groovy

(ie. without running the task)
Some libraries implement settable futures by extending `FutureTask`, like Spring's `SettableListenableFuture`. When this is used in `KafkaTemplate` the future value is set directly without actually running the task, so we need to cancel the continuation to stop if from keeping the surrounding span alive indefinitely.

Cancel continuation when FutureTask value/exception is set directly

---

buildSrc/build.gradle.kts
dd-java-agent/benchmark-integration/benchmark-integration.gradle
dd-java-agent/benchmark-integration/play-perftest/play-perftest.gradle
dd-java-agent/instrumentation/apache-httpclient-4/apache-httpclient-4.gradle
dd-java-agent/instrumentation/commons-httpclient-2/commons-httpclient-2.gradle
dd-java-agent/instrumentation/glassfish/glassfish.gradle
dd-java-agent/instrumentation/grizzly-http-2.3.20/grizzly-http-2.3.20.gradle
dd-java-agent/instrumentation/guava-10/guava-10.gradle
dd-java-agent/instrumentation/jms/jms.gradle
dd-java-agent/instrumentation/play-2.3/play-2.3.gradle
dd-java-agent/instrumentation/play-2.4/play-2.4.gradle
dd-java-agent/instrumentation/play-2.6/play-2.6.gradle
dd-java-agent/instrumentation/restlet-2.2/restlet-2.2.gradle
dd-java-agent/instrumentation/servlet/request-2/request-2.gradle
dd-java-agent/instrumentation/servlet/request-3/request-3.gradle
dd-java-agent/instrumentation/testng-6.4/testng-6.4.gradle
dd-java-agent/instrumentation/tomcat-5.5/tomcat-5.5.gradle
dd-smoke-tests/play-2.4/play-2.4.gradle
dd-smoke-tests/play-2.5/play-2.5.gradle
dd-smoke-tests/play-2.6/play-2.6.gradle
dd-trace-java.gradle
test-published-dependencies/build.gradle

Removes the JCenter repository in all places where it's possible
Make our JCenter dependencies explicit and minimize impact of JCenter service disruptions

Remove jcenter from projects where it is possible

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java

Small cleanup of some of our logging code
Do not create objects for no reason and make the code more readable
I had a much larger change which wrapped all logging with the appropriate `isXXXEnabled()` but it seemed like overkill at this point. With this change there are no String concatenations left and all of the `log.XXX(String, Object ...)` in hot paths are properly wrapped.

Small fixes to logging

---

gradle/repositories.gradle

Really removes jcenter from the default repositories, which was missed in #3325 due to a bad merge.

Really remove jcenter from the default repositories

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RejectedExecutionHandlerInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/RejectedExecutionTest.groovy

The tracer wraps runnables passed into `execute` with its own wrapper to track propagation,
but we should remove this wrapper when the task is rejected so the `RejectedExecutionHandler`
sees the original runnable (some frameworks rely on this behaviour.)
Note that runnables passed to `submit` do not use our wrapper because they are already wrapped
by `ThreadPoolExecutor` with `FutureTask` . The expected behaviour there is that the `FutureTask`
wrapper is passed to `RejectedExecutionHandler` to match what `ThreadPoolExecutor` does.

Expand RejectedExecutionTest to cover rejected calls to 'execute'

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/ClientIpAddressResolver.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/AppSecSystemSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/ClientIpAddressResolverSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeIGRegistrationSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
dd-smoke-tests/appsec/src/main/groovy/datadog/smoketest/appsec/AbstractAppSecServerSmokeTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

It determines the value of the `actor.ip` tag and includes it (when there is an appsec event).
This is currently done on the backend, but will need to be moved to the tracer so that blocking decisions can be made on the same request.
See "Client IP addresses resolution" on the wiki and "AppSec Span tags RFC" on docs.

[AppSec] Provide actor.ip in the trace

---

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

This PR moves profiling configuration options to the profiling specific configuration holder. It removes some duplicated options as well.
Moving out configuration out of the deprecated `Config.java` class.
Address comment from https://github.com/DataDog/dd-trace-java/pull/3234#discussion_r775573328

[PROF-4688] Move profiling config out of config defaults

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java

Removed code duplication
Customers discovered in logs warning message `Illegal attempt to replace context value for Address{key='server.response.status'}`

[AppSec] Fixed double status assignment

---

.circleci/config.yml
dd-cws-tls/dd-cws-tls.gradle
dd-java-agent/agent-profiling/profiling-auxiliary/profiling-auxiliary.gradle
dd-java-agent/agent-tooling/agent-tooling.gradle
dd-java-agent/appsec/weblog/weblog-spring-app/weblog-spring-app.gradle
dd-java-agent/benchmark-integration/README.md
dd-java-agent/benchmark-integration/play-perftest/app/controllers/HomeController.scala
dd-java-agent/benchmark-integration/play-perftest/app/controllers/Worker.scala
dd-java-agent/benchmark-integration/play-perftest/play-perftest.gradle
dd-java-agent/benchmark-integration/run-perf-test.sh
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/aws-java-sdk-1.11.0.gradle
dd-java-agent/instrumentation/micronaut-http-server-netty-2/micronaut-http-server-netty-2.gradle
dd-java-agent/instrumentation/okhttp-2/okhttp-2.gradle
dd-java-agent/instrumentation/spray-1.3/spray-1.3.gradle
dd-smoke-tests/play-2.4/play-2.4.gradle
dd-smoke-tests/play-2.4/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy
dd-smoke-tests/play-2.5/play-2.5.gradle
dd-smoke-tests/play-2.5/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy
dd-smoke-tests/play-2.6/play-2.6.gradle
dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/PlaySmokeTest.groovy
dd-smoke-tests/wildfly/wildfly.gradle
dd-trace-core/dd-trace-core.gradle
dd-trace-java.gradle
dd-trace-ot/dd-trace-ot.gradle
utils/histograms/histograms.gradle
utils/socket-utils/socket-utils.gradle

* Changes all compile/runtime configurations to implementation/runtimeOnly
* Switches to the new supported play framework plugin
These constructs are no longer supported on gradle 7.x and would fail the build
The biggest blocker now is the muzzle `instrumentation` plugin that is beyond my current understanding of gradle, as well as the `:dd-java-agent:appsec:weblog:weblog-spring-app` that uses old versions of Spring and the Spring Boot plugin.

Some gradle cleanup in preparation for 7.x

---

dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageProducerInstrumentation.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageExtractAdapter.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageInjectAdapter.java

Avoids having to list both injector and extractor helpers twice in the producer and consumer instrumentations.

Share JMS propagation headers via the common decorator class

---

communication/src/main/java/datadog/communication/serialization/Codec.java
communication/src/test/java/datadog/communication/serialization/msgpack/MsgPackWriterTest.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceGenerator.groovy
dd-trace-core/src/traceAgentTest/groovy/TraceGenerator.groovy

Any metric that is a `Number` but not one of the _primitive_ sub types will have its `double` value serialized.
A user setting a tag with for example a `BigDecimal` will encounter a serialization error in the Datadog agent since it is a `Number` and treated as a _metric_, but the serialization will store the `String` representation.
Reported in #3349

Serialize the double value of unknown Number metric types

---

dd-java-agent/instrumentation/mongo/common/src/main/java/datadog/trace/instrumentation/mongo/MongoCommandListener.java
dd-java-agent/instrumentation/mongo/driver-3.1-core-test/src/test/groovy/MongoCore31ClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/MongoJava31ClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-3.4/src/main/java/datadog/trace/instrumentation/mongo/MongoClient34Instrumentation.java
dd-java-agent/instrumentation/mongo/driver-3.4/src/test/groovy/MongoJava34ClientTest.groovy

Fixes the issue raised in #3361 with MongoDB Command Listeners. The tests were also updated to cover this so that in the future we will catch this type of error. Also, I fixed the mongodb 3.4 instrumentation priority for one of it's Command Listeners.
Fix a broken instrumentation

Fix MongoDB CommandListener instrumentation

---

buildSrc/src/main/groovy/InstrumentPlugin.groovy

byte-buddy 1.12.3 added support for explicitly setting the classfile version of auxiliary types in the byte-buddy gradle task. Previously this was deduced from the gradle project. It also added a warning when this task property was not set to let users know that it was now implicitly using the classfile version of the JDK running the build:
Could not locate Java target version, build is JDK dependant: 8
We don't currently use auxiliary types so this doesn't alter the final build output, but it's better to explicitly set the classfile version to the current minimum of Java 7 - this also avoids the above warning from appearing multiple times during the build

Explicitly set classFileVersion of auxiliary types to avoid byte-buddy warning

---

dd-java-agent/instrumentation/spring-jms-3.1/src/main/java/datadog/trace/instrumentation/springjms/AbstractPollingMessageListenerContainerInstrumentation.java
dd-java-agent/instrumentation/spring-jms-3.1/src/test/groovy/MaxMessagesPerTaskForkedTest.groovy
dd-java-agent/instrumentation/spring-jms-3.1/src/test/groovy/SpringSAListenerTest.groovy
dd-java-agent/instrumentation/spring-jms-3.1/src/test/groovy/salistener/MaxMessagesPerTaskConfig.groovy

Complete the last polled message span as soon as we know its execution phase is complete - this results in more accurate durations than if we used the iteration span cleaner fallback, as that has to rely on a timeout.

Complete last polled JMS span when Spring JmsListener is done

---

dd-java-agent/instrumentation/elasticsearch/rest-7/src/test/groovy/Elasticsearch7RestClientTest.groovy

Fixes the flaky `Elasticsearch7RestClientTest`
Flaky tests are flaky.
Since the finishing of the spans are done async in a callback, it's quite possible for them to finish _out of order_, so let's just sort them by start time before comparing.

Fix Elasticsearch7RestClientTest by sorting the spans by start time

---

dd-java-agent/agent-profiling/profiling-auxiliary-async/profiling-auxiliary-async.gradle

Updates the shadowJar configuration to the new async profiler artifact name
The datadog specific async profiler artifact was renamed to reduce the potential confusion. However, the shadow gradle plugin needs to match the jars and since the jar name is now different no async profiler content gets included.

Update the async profiler packaging to the new artifact name

---

gradle/dependencies.gradle

Fixes some crashes when collecting stacktraces + Fixes some too verbose logs

Bump async-profiiler to DD-2.6-20220210

---

dd-java-agent/agent-profiling/profiling-auxiliary-async/profiling-auxiliary-async.gradle

The PR fixes the custom ap-tools jar support because the current version is not working reliably.
Everything boils down to the fact that downloading a jar and adding it as a dependency seems to mess up the gradle model and the build results can be quite surprising eg. `shadowJar` step not seeing the dependency at all most of the time.
Another surprising issue was the inability to read an environment variable set at the `gradlew` command line - so using the project property instead.

Fix the custom ap-tools jar support

---

gradle/dependencies.gradle

* Relax CallTraceStorage locking to cover only necessary code

Bump async-profiler to DD-2.6-20220211

---

dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AsyncProfilerConfigEvent.java
dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java

When heaps are non-trivial (bigger than 2g), it would overflow an int
leading to non-sensical value for maxheap, leading to interval of 1M.

Fix computation overflow

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java

Classes with names that include `$$EnhancerByGuice$$` are proxy (sub)classes generated by Guice at runtime and can safely be ignored because we'll instrument their superclass. Ignoring them also means we can avoid creating duplicate spans, ie. one for the proxy and one for the real class.

Ignore Guice generated proxy classes

---

dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ControllerFactory.java
dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ControllerFactoryTest.java

Dumps the java.vendor, java.version and java.runtime.name in the log message.
It's regularly an issue during escalations that we don't know the version of the runtime and we have to ask customers to provide it to us manually when the "; it requires ..." message shows up. Instead, let's dump the information along the log.

Put the vendor, version, and runtime name in log message

---

dd-java-agent/instrumentation/apache-httpclient-5/src/test/groovy/ApacheHttpClientResponseHandlerTest.groovy
dd-java-agent/instrumentation/apache-httpclient-5/src/test/groovy/ApacheHttpClientTest.groovy

This sets the `ConnectTimeout` instead of the `ConnectionRequestTimeout` timeout (which is the connection lease request timeout from the internal pool).
Each `"connection error non routable address"` test for the apache http client 5 tests took ~2 minutes, instead of the supposed ~3 seconds.

Set connect timeout for apache http client 5 tests

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecModule.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/util/StandardizedLogging.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/AppSecSystemSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy

Added checkers to avoid double calling of AppSec.
Some combinations of instrumentations can cause events’ reduplication. Customer reported the application built based on Ratpack produces exceptions. In sample RatPack app, I discovered there are `HttpServerDecorator.onRequest()` and  `HttpServerDecorator.onResponse()`, are called twice per request. First time from `netty-4.1` instrumentation and the second time from `ratpack-1.5`. Overall this looks reasonable, but in terms of AppSec, doubling events results in redundant analysis iteration (calling WAF).

[AppSec] Fixed double calling

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletRequestBodyInstrumentation.java
dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java

Another step towards fully decoupling `Instrumenter`s from `AgentBuilder` so we can try different agent approaches

Introduce API to decouple custom transformers from AgentBuilder

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/HttpUrlConnectionInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/NonStandardExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableFutureInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableInstrumentation.java
dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/context/client/RmiClientContextInstrumentation.java
dd-java-agent/testing/src/test/java/context/FieldInjectionTestInstrumentation.java
dd-java-agent/testing/src/test/java/excludefilter/ExcludeFilterTestInstrumentation.java

The only places using this method don't have custom `classLoaderMatcher`s, so it doesn't add value. It also makes the `Instrumenter` API fragile as it relies on implementers choosing the right method for a corner-case that no longer exists (where an `Instrumenter` with a narrow `classLoaderMatcher` wants to use a context store available to all) - imho if this corner-case ever comes up again it would be better to solve it in how we apply field-injection rather than leak this into the API.
For example both `JavaForkJoinTaskInstrumentation` and `JavaForkJoinPoolInstrumentation` declare a context-store for `java.util.concurrent.ForkJoinTask`, but one declared it with `contextStoreForAll` while the other used `contextStore` :)

Simplify instrumenter API by dropping `contextStoreForAll`

---

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSClientInstrumentation.java
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSHttpClientInstrumentation.java
dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsJmsMessageInstrumentation.java
dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsReceiveRequestInstrumentation.java
dd-java-agent/instrumentation/guava-10/src/main/java/datadog/trace/instrumentation/guava10/ListenableFutureInstrumentation.java
dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/client/WebClientFilterInstrumentation.java
dd-java-agent/instrumentation/tomcat-appsec-6/src/main/java/datadog/trace/instrumentation/tomcat6/ParsedBodyParametersInstrumentation.java

These instrumentations match on class names and have no context-stores so they don't need class-loader filtering.
Also document that the class-loader matcher in ListenableFutureInstrumentation helps avoid Runnable instrumentation when Guava is not on the classpath.

Drop redundant classLoaderMatchers

---

dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy

Ensures that a `PendingTrace` is not enqueued multiple times in the `PendingTraceBuffer`.
Repeatedly enqueueing the same `PendingTrace` for multiple `Span`s of the same `Trace` can lead to the `PendingTraceBuffer` filling up and forcefully writing single `Span`s as they finnish. Writing large numbers of `Span`s one by one, can in turn overload the Datadog Agent.

Avoid enqueueing PendingTrace multiple times

---

dd-java-agent/instrumentation/mongo/driver-3.1-core-test/src/test/groovy/MongoCore31ClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/MongoJava31ClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-3.10-sync-test/src/test/groovy/MongoSyncClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-3.3-async-test/src/test/groovy/MongoAsyncClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-3.4/src/test/groovy/MongoJava34ClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-3.7-core-test/src/test/groovy/MongoCore37ClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-4.0/driver-4.0.gradle
dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/Mongo4ClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/MongoReactiveClientTest.groovy

Tries to make test setup more robust by waiting for the actual `setup` span to be reported. Also upgrades the async test for `mongodb-driver-reactivestreams` to run against `4.0.1` as a minimum, since there was a race condition bug in earlier versions, that sometimes triggered during testing.
Flaky tests are flaky.
Has run this commit fully 5+ times in CI without any failures in the mongo tests. Not sure that is enough testing, but at least it doesn't seem to get worse 😉

Make mongo tests setup more robust

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/KnownAddresses.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/data/KnownAddressesSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
dd-smoke-tests/appsec/springboot-grpc/springboot-grpc.gradle
dd-smoke-tests/appsec/springboot-grpc/src/test/groovy/datadog/smoketest/appsec/SpringBootWithGRPCAppSecTest.groovy
dd-smoke-tests/springboot-grpc/src/main_java8/java/datadog/smoketest/springboot/AsyncTask.java
dd-smoke-tests/springboot-grpc/src/main_java8/java/datadog/smoketest/springboot/controller/WebController.java
dd-smoke-tests/springboot-grpc/src/main_java8/java/datadog/smoketest/springboot/grpc/AsynchronousGreeter.java
internal-api/src/main/java/datadog/trace/api/gateway/Events.java
internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java
internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java
settings.gradle

Basic implementation of interception of server received GRPC messages and their delivery to the instrumentation gateway and the appsec subsystem. Because there might me multiple messages per grpc server span (which creates an appsec request context), the grpc message is not saved along with other appsec data, and the WAF run is one-shot as well (no accumulation of data).
A limitation is that these messages are all reported in the grpc server span and for long running requests there may be many of them.

Appsec: basic grpc support

---

dd-java-agent/appsec/appsec.gradle
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy

Moves to libsqreen to version 3.0.8, which removes `finalize()` implementations. Adds extra checks to make it more likely that `Additive` objects are closed and don't leak memory.
So that we don't pay the performance penalty of having `finalize()` methods.
Perhaps different strategies for calling `close()` when the root span finishes are more appropriate, like using `TraceInterceptor`.

[Appsec] Move to libsqreen w/ finalizers; add guardrails

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/TagContextExtractor.java
dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
internal-api/src/main/java/datadog/trace/util/Strings.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Make dd.trace.header.tags apply to both request and response headers
* Key only headers are automatically mapped to `http.request.headers.*` and `http.response.headers.*` for cross tracer consistency
* Setting of request and response header mappings separately via `dd.trace.request_header.tags` and `dd.trace.response_header.tags`
* Revert to old parsing and behavior via `dd.trace.header.tags.legacy.parsing=true`
The Java Tracer behavior of only mapping request header tags is inconsistent with other Datadog tracers.

Make dd.trace.header.tags apply to both request and response headers

---

dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy

Marks the `PendingTrace` as not enqueued when queue is full.
If we don't mark the `PendingTrace` as not enqueued, it will never be reenqueued and we might miss writing out further spans.
This issue doesn't need release notes, since it was introduced by #3406 and hasn't been released yet.

Mark PendingTrace as not enqueued when queue is full

---

.circleci/config.yml
gradle/java_no_deps.gradle

Changes the CI test result upload script to use the correct parameter.
TL;DR: Wrong parameter is wrong.
The `upload_ciapp.sh` script expects the JVM name as its second parameter, and previously that was in the aptly named `testTask` parameter, which now exclusively contains the actual test task, and not a mix.
The gradle configuration has also been updated to not override the test JVM if it is the same one that is running the gradle build, in the same way it did before.

Use correct parameter for report upload script on CI

---

dd-java-agent/agent-profiling/profiling-auxiliary-async/profiling-auxiliary-async.gradle
dd-java-agent/dd-java-agent.gradle

Ensures that the `shadowJar` file in the `dd-java-agent` directory doesn't get overwritten by the `sharedShadowJar` in the same project.
Having two jar files writing to the same name, where one depends on the other leads the gradle being unable to cache the results causing the two build steps to be repeated on every run that depends on the `:dd-java-agen:shadowJar` 
Completely unscientific measurements on my laptop got the time for being ready to run the tests of a smoke test down from 25s to 10s, if all the files had been compiled before.

Don't overwrite the shadow jar with the shared shadow jar

---

dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerMappingResourceNameFilter.java

as the bean processor may not have access to all dependencies at configure time, for example when using Spring with OSGi

Use lazy initialization for HandlerMappingResourceNameFilter

---

dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
gradle/dependencies.gradle

Updates in async-profiler since last bump:
* Support for OpenJ9
* Dwarf stack unwinding
* Improve static analysis on CI
* Remove stacktrace field from jdk.ActiveSetting
* Logging improvements
Full diff at https://github.com/datadog/async-profiler/compare/DD-20220212...DD-20220303

Bump async-profiler to 2.7-DD-20220303

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java

`DrillPreparedStatementImpl` extends `AvaticaPreparedStatement` and while it does override most of its methods it doesn’t override `executeQuery` - this means we need to move up to trace `AvaticaPreparedStatement` to catch that call
Tracing the super-class is safe here because `DrillPreparedStatementImpl` ends up calling the `AvaticaPreparedStatement` methods to do the actual work of talking to the database - the `DrillPreparedStatementImpl` sub-class just adds some pre/post-condition checks that we don’t need to cover with tracing, as well as some non-JDBC methods specific to Apache/Drill
This is slightly complicated by the fact that drill-jdbc-all-1.15.0.jar refactors its copy of `AvaticaPreparedStatement` under the `oadd` prefix, so we need to add it twice - once with and once without …

Adjust Apache/Drill tracing to cover the shared superclass from Apache/Calcite that the Drill class delegates to

---

dd-java-agent/appsec/src/main/resources/default_config.json

[AppSec] Updated security rules (v1.2.6)

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/FieldBackedContextStores.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextProvider.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextRequestRewriter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/Reference.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceMatcher.java
dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceConfigInstrumentation.java
dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy
dd-smoke-tests/osgi/src/test/groovy/datadog/smoketest/AbstractOSGiSmokeTest.groovy

My goal is to make it easier to see all lines in debug logs related to a specific instrumentation or instrumenter class. Being able to correlate lines easily is great when we work with spans and traces, so working with the matchers and transformers should be as easy
TODO:
AgentInstaller$TransformLoggingListener

Make it easier to correlate startup debug log lines

---

.circleci/config.yml

Add system tests in CI
System tests in a functional test workbench that perform black box testing across all tracers. More info here : https://github.com/DataDog/system-tests/tree/main/docs
* Validate that feature implementation are consistent across all tracers
* catch integration issues
* perform end-to-end testing
* Quite fast, adding new tests does not add noticeable CI time (well, actually, on java tracer, the build step is terribly long 😞 . The test phase itself takes 4mn )
* unit test with test isolation
* provides good explanation about issues. It use black box testing, so even if you're trying to give good feedback, we are not able to dig inside components, so the information is often very poor.
System tests are pretty stable. The build phase can be flaky if the third party …

Add system tests in CI

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfig.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/StringKVPair.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/report/AppSecEventWrapper.java
dd-java-agent/instrumentation/hystrix-1.4/src/main/java/datadog/trace/instrumentation/hystrix/HystrixDecorator.java
dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTSpan.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTSpan.java
dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/RateByServiceSampler.java
dd-trace-ot/src/main/java/datadog/opentracing/OTScopeManager.java
dd-trace-ot/src/main/java/datadog/opentracing/OTSpan.java
dd-trace-ot/src/main/java/datadog/opentracing/OTSpanContext.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/CIProviderInfo.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/git/CommitInfo.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/git/GitInfo.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/git/GitObject.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/git/PersonInfo.java

Remove all instances of `Objects.hash()` since it is poorly optimized by the JVM. 
Calls to `Objects.hash()` will allocate an array to hold the parameters and all primitive parameters will be autoboxed. There are some caches for primitives in the JVM but they are limited and common values for things like a web server port will not be in the cache. This causes unneeded object allocations. 
I will add some JMH results comparing the results for an inline version of `Objects.hash()` (like this change) and calling `Objects.hash()` for different sets of parameters.

Remove uses of Objects.hash()

---

dd-java-agent/instrumentation/jms/src/test/groovy/TimeInQueueForkedTest.groovy
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/ListWriterAssert.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

With this change we call `System.currentTimeMillis()` once when creating the tracer - we then use `System.nanoTime()` for all relative times of traces under that tracer, plus a periodic adjustment. As well as reducing the CPU overhead of each trace it also saves us 16 bytes in `PendingTrace` because we no longer need to save the start time and start ticks per-trace.
Every 30 seconds (configurable) we check for clock drift/skew by calling `System.currentTimeMillis()` and comparing that to our calculated time from the initial tracer wall clock time. Any difference more than 1ms is taken from future trace times while keeping the sub-nanosecond time intact.
Note: trace tests that don't involve synthetic spans now sort their test traces by the start time of the local root span (before we used …

Move relative time calculations to tracer instance

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java

Added extra parsing properties/env variables, in case if customer tries to enable feature(modules) with "0", "1".
In case, if try to enable module with value `1`, it will be displayed as enabled, but nothing in practice module will not be started.
For example if customer tries to enable AppSec with environment variable `DD_APPSEC_ENABLED=1`, the AppSec module will not be loaded, however in logs we will be able to see:
`DATADOG TRACER CONFIGURATION {... "appsec_enabled":true ...}`
The problem exist because of property/env reading happens in two places: in `Agent::isFeatureEnabled(...)` and in `Config` but with the different logic.

Added extra parsing for property/env

---

communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
communication/src/test/groovy/datadog/communication/ddagent/DDAgentFeaturesDiscoveryTest.groovy

1) Simplify the features discovery logic by removing needlessly complicated reverse iteration
2) Fix a bug where feature discovery was invoked after every trace request
The agent returns `Datadog-Agent-State` (a hash of the info endpoint) for all endpoints _except_ the info endpoint. Previous to this PR, if the `/info` endpoint exists on the agent, the `state==null` **always**. With trace requests, `state!=null` **always**. As a result, after ever trace request `DDAgentApi.handleAgentChange()` would always call `discover()`.
This PR changes that behavior by probing the discovered trace endpoint once even if the endpoint was found via `/info`
I discovered these issue while adding another discovery endpoint
The behavior when dealing Datadog agents that do not return `Datadog-Agent-State` …

Fix issues with features discovery

---

dd-java-agent/instrumentation/jakarta-rs-annotations-3/jakarta-rs-annotations-3.gradle

Changes the `jakarta` instrumentation dependency to `compileOnly`. Otherwise, it is added to the final agent jar. Also, adds the api dependency to the `latestDepTest` configuration.
I noticed this issue while debugging another problem
We may think of adding custom configuration names like [open-telemetry](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/conventions/src/main/kotlin/io.opentelemetry.instrumentation.base.gradle.kts) to prevent issues like this. They have `library`, `testLibrary`, and `latestDepTestLibrary` that automatically does the right thing

Fix jakarta instrumentation dependencies

---

communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
communication/src/test/groovy/datadog/communication/ddagent/DDAgentFeaturesDiscoveryTest.groovy
dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/PayloadDispatcher.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/PayloadDispatcherTest.groovy
internal-api/src/main/java/datadog/trace/util/Strings.java
internal-api/src/test/groovy/datadog/trace/util/StringsTest.groovy

Takes the result of the Datadog agent `/info` endpoint and avoids probing the endpoints by computing the state hash of the response.
Avoid probing the Datadog agent with incomplete requests that show up as a failure to decode in the agent logs, that might confuse customers/support.
I also changed the probing to send valid but empty payloads to the Datadog agent, but that broke the old `test-agent` that's used in some smoke tests, so it was changed back. Replacing the `test-agent` is a bigger task.

Skip probing agent trace endpoints when info is available

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/RunnableWrapper.java
dd-java-agent/instrumentation/spring-scheduling-3.1/src/main/java/datadog/trace/instrumentation/springscheduling/SpringSchedulingRunnableWrapper.java
dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/UndertowInstrumentation.java
dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/UndertowRunnableWrapper.java

Stop instrumentations from extending `RunnableWrapper` in their injected helper classes, because if this class is loaded during helper injection then we can miss the initial load event where we need to add the context-store fields.
Update `UndertowRunnableWrapper` to use continuations instead of extending `RunnableWrapper`.

Fix undertow runnable wrapping to avoid extending RunnableWrapper

---

dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/UndertowDecorator.java

Fixes the peer host ip in the new undertow instrumentation. This is returning the incorrect address (that of the server, not the client).

Undertow: fix peerHostIP

---

dd-java-agent/instrumentation/classloading/src/main/java/datadog/trace/instrumentation/classloading/ClassloadingInstrumentation.java

even when using `-Ddd.integrations.enabled=false` because sometimes people use that to turn everything off before re-enabling selected integrations, and most (if not all) integrations rely on the classloading instrumentation. This is a stop-gap until we can declare dependencies between integrations.
Note: it can still be explicitly turned off by using `-Ddd.integration.classloading.enabled=false`

Default classloading instrumentation to always on

---

dd-trace-ot/dd-trace-ot.gradle

Adds the `time-utils` project to the list of projects bundled for dd-trace-ot
The current release is missing this library. For developers attempting manual instrumentation, there's a `NoClassDefFoundError` on startup.

Add time-utils to list of bundled projects

---

dd-java-agent/instrumentation/hibernate/core-4.0/core-4.0.gradle

Update the muzzle range to match the new expectation that the 4.0 instrumentation will no longer match the 6.0 API
https://github.com/hibernate/hibernate-orm/blob/main/migration-guide.adoc#legacy-hibernate-criteria-api

Hibernate 6.0.0.Final removed the Criteria query API

---

dd-trace-ot/src/main/java/datadog/opentracing/OTSpan.java
dd-trace-ot/src/test/groovy/datadog/opentracing/OTSpanTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ResourceNamePriorities.java

Adds a priority level for resource names set by users using dd-trace-ot.
A customer issue where instrumentation was overwriting a resource name that they were adding to the root span

Add resource name priority for changes made through dd-trace-ot

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/TPEHelper.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/Wrapper.java
dd-java-agent/instrumentation/guava-10/src/test/groovy/ListenableFutureTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/test/java/PeriodicTask.java
dd-java-agent/instrumentation/jetty-util/src/test/groovy/JettyExecutorInstrumentationTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Changes the `ThreadPoolExecutorInstrumentation` to avoid wrapping the `Runnable` before it is put into the work queue.
Wrapping the `Runnable` is not always safe since the work queue implementation can be of a type that not only expects something that implements `Runnable` but another interface/class that it will happily try to cast to, resulting in exceptions since the internal wrapper class doesn't implement/inherit it properly.
This can change the behavior of when the scopes and spans get activated, which might lead to differences in span structure, and maybe it should be labeled a breaking change.
* A `ThreadPoolExecutor` class can be excluded from propagation by using the `dd.trace.thread-pool-executors.exclude` setting
* The old behavior can be reverted to by setting …

Change ThreadPoolExecutorInstrumentation to avoid wrapping Runnable

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDClassFileLocator.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Adds a new flag:
```
-Ddd.trace.classloaders.exclude=name1,name2
```
to exclude named classloaders from both matching **and** class-file resource lookups
Gives us a way to exclude problematic classloaders from being touched by instrumentation

Support excluding named classloaders from matching and class-file resource lookups

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/FieldBackedContextStore.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InstanceStore.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakMapContextStore.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/InstanceStoreTest.groovy
dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/UndertowDecorator.java

Creates a class global instance registry for things like keys used to attach information to HTTP Requests/Responses.
Part of the Undertow instrumentation is based on classes implementing a certain interface, which means that the helper classes can get injected into multiple class loaders, while the main Undertow code lives in another class loader. While looking at a reported issue @ValentinZakharov noticed that this can lead to our helper classes being injected multiple times, and the `AttachmentKey` instances being different across multiple classes in the same server, leading to doubling of calls.

Add registry to use same keys across class loaders

---

dd-java-agent/instrumentation/slick/src/main/java/datadog.trace.instrumentation.slick/SlickRunnableInstrumentation.java

`implementsInterface` should be used to match instrumented types that implement a particular interface (`hasInterface` is used to check argument/return interface types)

Use correct interface matcher in slick instrumentation

---

dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2ResponseStatusInstrumentation.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Instrumentation.java

`HttpServletResponse` is an interface, so we only need `implementsInterface` rather than `safeHasSuperType` (as that searches both interfaces and superclasses)
Also document how certain servlet instrumentations use `safeHasSuperType` to search for both `FilterChain` (an interface) and `HttpServlet` (a superclass) rather than have separate matchers

Cleanup servlet matchers

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/KnownAddresses.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
dd-java-agent/instrumentation/ratpack-1.5/ratpack-1.5.gradle
dd-java-agent/instrumentation/ratpack-1.5/src/main/java/datadog/trace/instrumentation/ratpack/ContextParseInstrumentation.java
dd-java-agent/instrumentation/ratpack-1.5/src/main/java/datadog/trace/instrumentation/ratpack/PathHandlerInstrumentation.java
dd-java-agent/instrumentation/ratpack-1.5/src/main/java8/datadog/trace/instrumentation/ratpack/ContextParseAdvice.java
dd-java-agent/instrumentation/ratpack-1.5/src/main/java8/datadog/trace/instrumentation/ratpack/PathBindingPublishingHandler.java
dd-java-agent/instrumentation/ratpack-1.5/src/main/java8/datadog/trace/instrumentation/ratpack/PathHandlerAdvice.java
dd-java-agent/instrumentation/ratpack-1.5/src/main/java8/datadog/trace/instrumentation/ratpack/TokenPathBinderInspector.java
dd-java-agent/instrumentation/ratpack-1.5/src/test/groovy/server/RatpackAsyncHttpServerTest.groovy
dd-java-agent/instrumentation/ratpack-1.5/src/test/groovy/server/RatpackForkedHttpServerTest.groovy
dd-java-agent/instrumentation/ratpack-1.5/src/test/groovy/server/RatpackHttpServerTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/TemplateAndMatrixVariablesInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/TemplateVariablesUrlHandlerInstrumentation.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
internal-api/src/main/java/datadog/trace/api/gateway/Events.java

Adds support in ratpack for transmitting to the IG extract path tokens (only the first ones) as well as converted request entities.

ratpack: pass converted request body / path tokens

---

.circleci/config.yml
.circleci/upload_ciapp.sh

Support for the `--logs` flag added in https://github.com/DataDog/dd-trace-java-docker-build/pull/36 
This is a new feature for junitxml imports in CI Visibility where we also send texts from `<system-out>` and `<system-err>` to the logs product. This has additional cost so a flag to opt-in is required but it's not available in a standard release of datadog-ci yet.
We want this because the exports from dd-trace-java are the ones that we've seen the biggest load with and we do not want to make the flag and docs public to customers until we've ensured reliability with dogfooding.
Once this is working you should be able to check it out with the query `Source: junitxml` in logs. Although we are not configuring rules to ensure 100% sampling for these logs.

[CIAPP-1862] Enable --logs for junitxml upload to CI Visibility

---

dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/CriteriaInstrumentation.java
dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/QueryInstrumentation.java
dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/SessionInstrumentation.java
dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/TransactionInstrumentation.java
dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/CriteriaInstrumentation.java
dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/QueryInstrumentation.java
dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/SessionInstrumentation.java
dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/TransactionInstrumentation.java
dd-java-agent/instrumentation/hibernate/core-4.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_3/ProcedureCallInstrumentation.java
dd-java-agent/instrumentation/hibernate/src/main/java/datadog/trace/instrumentation/hibernate/SessionMethodUtils.java

These jlr.Method values are recreated* on every read and are not used in the decorator
(except for method name which byte-buddy makes available in cached form by using '#m')
Removing them should reduce tracer overhead on every hibernate call.
\* see warning in the [@Advice.Origin](https://javadoc.io/doc/net.bytebuddy/byte-buddy/1.12.8/net/bytebuddy/asm/Advice.Origin.html) javadoc
> Note: A constant representing a `Method` or `Constructor` is not cached but is recreated for every read

Remove unused Method handles from Hibernate instrumentation

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/KafkaClientTest.groovy
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerGroupInstrumentation.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInstrumentation.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterable.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingList.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingListIterator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
dd-java-agent/instrumentation/kafka-streams-0.11/src/latestDepTest/groovy/KafkaStreamsTest.groovy
dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTestBase.groovy
dd-trace-core/src/main/java/datadog/trace/core/datastreams/MsgPackDatastreamsPayloadWriter.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InstrumentationTags.java

This adds the Kafka consumer group as the `kafka.group` span tag and as an edge tag in data streams monitoring.
Consumer group is only available during the construction of the `KafkaConsumer`. This instrumentation:
1. Maps `KafkaConsumer` -> Group at construction
2. When a new `ConsumerRecords` is created
a) Looks up the group of the consumer created it
b) Maps `ConsumerRecords`-> Group
3. When the `ConsumerRecords` is iterated, the group is available to the wrapper classes
Consumer group is a wanted feature of data streams monitoring.
* `kafka.group` is the tag used by `dd-trace-rb`. I couldn't find any other tracers implementing consumer group as a tag. Most other tracers also use `kafka.partition` and `kafka.offset` rather than just `partition` and `offset` like the java tracer.
* The …

Extract and tag Kafka consumer group

---

dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTSpan.java
dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTSpan.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy

Complete the feature within opentracing manual instrumentation so that resource names set are not overridden

Add resource name priority for changes made through instrumented opentracing

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/ExceptionHandlers.java

Removes the classloader value from the ExceptionHandler code that is generated. It will cause an instrumentation error on some classloaders that have extremely long toString values

Remove classloader toString() logging from generated ExceptionHandler

---

dd-java-agent/instrumentation/jakarta-rs-annotations-3/jakarta-rs-annotations-3.gradle

The gradle changes were cribbed from the jdbc module - if any of this can be simplified let me know :)

jakarta-rs-annotations 3.1.x requires Java 11 for testing

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategy.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Controls how many type definitions are kept in the resolver's type pool before it starts evicting old entries.
The default pool size of 64 (per-classloader) is likely too small for large enterprise applications leading to class resources repeatedly being requested, slowing down startup. Providing a flag to control its size allows users to accept a larger pool to reduce startup costs with the trade-off being potentially increased memory use.
The equivalent environment variable is `DD_RESOLVER_TYPE_POOL_SIZE`

Add '-Ddd.resolver.type.pool.size' to control maximum size of resolver's type pool

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java

When setting the same data in the context of the request, the same data will be ignored for further analysis using AppSec WAF.
Issue reported by customer: #3484 
Different instrumentations (Play and Akka) populate same data to distinct spans, but all of them consolidates in same AppSecRequestContext, which cause forbidden data replacement. As a workaround we ignores replacement if the values are the same.

[AppSec] Play/Akka double instrumentation

---

communication/src/main/java/datadog/communication/RemoteFeaturesDiscovery.java
communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/RateByServiceSampler.java
dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/PayloadDispatcher.java
dd-trace-core/src/main/java/datadog/trace/common/writer/RemoteApi.java
dd-trace-core/src/main/java/datadog/trace/common/writer/RemoteMapperDiscovery.java
dd-trace-core/src/main/java/datadog/trace/common/writer/RemoteResponseListener.java
dd-trace-core/src/main/java/datadog/trace/common/writer/RemoteWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentMapperDiscovery.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentResponseListener.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/HealthMetrics.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentApiTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/PayloadDispatcherTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/TraceProcessingWorkerTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/monitor/HealthMetricsTest.groovy
dd-trace-core/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
dd-trace-core/src/traceAgentTest/groovy/TraceMapperRealAgentTest.groovy

As part of the initiative to transition CI Visibility to the agentless mode, the traces generated by the instrumentations need to be sent to a new HTTP public intake.
This PR refactors the code to decouple buffering + common transport logic from specific Datadog Agent implementation details. For that purpose, some common abstract classes and interfaces were created. 
The change in this PR only refactors the code and has no collateral effects on the current configuration and/or behavior. It has no changes related to the agentless mode, just the preparation.
Tested on a spring-boot application.

[CIAPP][Agentless][Writer] Decouple common buffer+transport logic from DDAgent details

---

gradle/java_no_deps.gradle

Sets a hard timeout for test task to 9 minutes, so they will fail before the default CircleCI 10 minute inactivity timeout triggers.
Having gradle fail the test instead of CircleCI will hopefully give us more information about what was failing.

Force timeout on test tasks before CircleCI inactivity timeout

---

internal-api/src/main/java/datadog/trace/util/ProcessSupervisor.java
internal-api/src/test/groovy/datadog/trace/util/ProcessSupervisorTest.groovy

Slow down `ProcessSupervisorTest` a bit for more reliable code coverage.
The `ProcessSupervisorTest` sometimes fails the code coverage checks, since the test code manages to close `ProcessSuperVisor` before the code under test has run all the relevant code paths.

 Slow down ProcessSupervisorTest a bit for code coverage

---

dd-java-agent/agent-profiling/profiling-uploader/profiling-uploader.gradle

Avoids this security vulnerability found in older versions of the jnr-posix package by upgrading it:
https://security.snyk.io/vuln/SNYK-JAVA-COMGITHUBJNR-1570422
This ‘use after free’ vulnerability was fixed in this diff for version 3.1.8 of jnr-posix:
https://github.com/jnr/jnr-posix/compare/jnr-posix-3.1.7...jnr-posix-3.1.8
Wanting to fix security vulnerabilities in our system which uses the dd-java-agent jar.

Upgrade jnr-posix dependency to avoid 'use after free' vulnerability

---

dd-trace-core/src/test/groovy/datadog/trace/core/propagation/LambdaContextTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/lambda/LambdaHandlerTest.groovy

Add the cleanup step to close the test server in `dd-trace-core/src/test/groovy/datadog/trace/lambda/LambdaHandlerTest.groovy`

[Serverless] add cleanup in tests

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java

Avoids an extra proxy span appearing between the incoming request and the JAX-RS call when using Weld (CDI)

Ignore generated Weld (CDI) proxy class

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ClassLoaderMatchers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/CustomExcludes.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnores.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ProxyClassIgnores.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ProxyIgnores.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ClassLoaderMatchersTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
gradle/tries.gradle
internal-api/internal-api.gradle
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/util/ClassNameTrie.java

* Uses `ClassNameTrie` to create a trie-based filter for custom excludes configured with
`-Ddd.trace.classes.exclude`
* Adds support for configuring a list of excluded classes/packages in an external file with
`-Ddd.trace.classes.exclude.file`
* Separates out matching of generated proxy names so we can do that (slower check) after any custom excludes
* Make `GlobalIgnoresMatcher` a `RawMatcher` and move the `skipClassLoader` check inside it (avoids creating several instances inside byte-buddy that each do part of the match - now we call these simple matches inside a single global-ignores method)
* Removes extraneous classes from the (hot) matching path where possible, preferring static methods
A trie should be faster than the previous approach of creating many chained `named` matchers.

Use ClassNameTrie for custom excludes

---

dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/TracingListener.java
dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
dd-java-agent/instrumentation/junit-5.3/src/main/java8/datadog/trace/instrumentation/junit5/TracingListener.java
dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TracingListener.java
dd-java-agent/instrumentation/testng-6.4/src/test/groovy/TestNGTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/SpanAssert.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

This PR fixes the span duration for the skipped test spans instrumented by CI Visibility.
**Root cause**: The `finish(duration)` method does expect the end time in microseconds. As the `start time` is based on nanoseconds, the duration was completely wrong for skipped tests.
**Proposed solution**: Adds a new `finishWithDuration` method in the internal DDSpan API to allow us to set a fixed duration.
**Context**: In CI Visibility, the skipped tests need to have a duration of `0 ns`. This issue was not detected before because CI Visibility spans were fixed by the Datadog Agent. Now the CI Visibility traces can be sent directly to a public intake, this bug has been detected.
_**Note:**_ As the tracer has a special treatment for spans with duration == `0 ns`, for the moment let's set the …

[CIAPP] Fix span duration for skipped tests

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
dd-trace-core/src/main/java/datadog/trace/civisibility/CiVisibilityTraceInterceptor.java
dd-trace-core/src/test/groovy/datadog/trace/civisibility/CiVisibilityTraceInterceptorTest.groovy

This PR adds the `library_version` root tag for CI Visibility traces leveraging the `CIVisibilityTraceInterceptor`.

[CIAPP] Add `library_version` root tag for CI Visibility traces

---

dd-trace-api/src/main/java/datadog/trace/api/config/CiVisibilityConfig.java
dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddintake/DDIntakeApi.java
internal-api/src/main/java/datadog/trace/api/Config.java

This PR adds the `dd.civisibility.agentless.url` config property (or environment variable equivalent) to allow configuring the Intake host URL externally. This will be particularly useful for configuring e2e tests on CI Visibility agentless mode.
The change in this PR is a feature used only by CI Visibility. It has no changes that might affect customers in production mode for APM Java.

[CIAPP][Agentless] Allow setting host URL via configuration

---

dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy

This widens the check introduced in #2754 by one level of wrapping, so broken pipe exceptions wrapped inside another exception are also not treated as errors.
Broken pipe `IOExceptions` are checked exceptions which may be wrapped inside unchecked exceptions or more web-app-friendly exceptions.
I decided to avoid widening this to the entire exception chain as usually there's only one level of wrapping, and checking one extra level shouldn't add much cost.
An alternative approach would be to do a `contains` check of the outer exception's message, since the outer exception often sets its message to be `cause.toString()`. Unfortunately though there's no `containsIgnoreCase` and changing the case of the message would involve allocating a new string. It's also possible that the outer exception …

Don't treat wrapped broken pipe exceptions as errors

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/CodeSourceExcludes.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Excludes any code-source location that contains one of the configured strings somewhere in its path.
This lets users exclude specific named jars or directories from being instrumented, this could be useful when all jars are loaded using the same classloader (so we can't exclude by classloader) and excluding each class in the jar would be too verbose.
```
-Ddd.trace.codesources.exclude=/classes,/antlr-2.7.7.jar
```
The matching is just a simple `contains` check, so you should avoid using short words that could appear elsewhere in the code-source location (this is also a feature, because you can then exclude several code-sources with similar locations.)

Add '-Ddd.trace.codesources.exclude=example-1.jar' flag to exclude named code-sources from matching

---

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/PidHelper.java

In the UX, tracing is using process_id (automatically mapped) and the processes product will also work with process_id.

Rename profiling pid tag to process_id to align with other products

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy

Prevent race condition that occurs if request end event, happens in two parallel threads (because of double instrumentation).
Customer reported about an exception that arise occasionally.

Fixed race condition

---

dd-java-agent/instrumentation/testng-6.4/testng-6.4.gradle

... so we can't validate with muzzle which uses Java 8.
This follows the example set in https://github.com/DataDog/dd-trace-java/commit/8a8771cb044#diff-86fe7e2d35e228e4efdb21811bca4dce7fe6d8e2e430ef619117e32ce7ba5c5eR3 - long term we should look at how to run Muzzle to allow matching against a wider range of JDK versions.

Limit TestNG muzzle range because TestNG 7.6+ is compiled with Java 11

---

dd-java-agent/instrumentation/synapse-3/src/main/java/datadog/trace/instrumentation/synapse3/SynapseServerDecorator.java
dd-java-agent/instrumentation/synapse-3/src/main/java/datadog/trace/instrumentation/synapse3/SynapseServerInstrumentation.java
dd-java-agent/instrumentation/synapse-3/src/test/groovy/datadog/trace/instrumentation/synapse3/SynapseTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Changes the synapse server operation name to match the patterns for other servers. Adds a config to revert to the previous behavior.

Change synapse server operation name to match other servers

---

dd-java-agent/agent-profiling/agent-profiling.gradle
dd-java-agent/agent-profiling/profiling-context/profiling-context.gradle
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/IntervalEncoder.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/LongSequence.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/PositionDecoder.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/ProfilerTracingContextTracker.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/allocator/heap/HeapAllocator.java
dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/IntervalEncoderTest.java
dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/IntervalParser.java
dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/PositionDecoderTest.java
dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/ProfilerTracingContextTrackerTest.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

This adds hard limits on the size of the data representing the span activation intervals.
The span metadata size (this includes the span tags) is limited to 25000 bytes - therefore it does not make sense to generate and keep more data if that is going to be discarded anyway. It is better to have the limit applied directly in the agent where we have control over when to cut off the data collection (saving CPU cycles) and the data export (where we can assure valid data).
For the sakes of minimizing the costs of `Long.valueOf()` this change is also adding a few classes from JCTools which are necessary to support `NonBlockingHashMapLong` class that is used instead of `ConcurrentHashMap`.
The JCTools classes are stripped to the bare minimum required for the code to run and they are not adding …

Support span activation intervals size limit

---

gradle/dependencies.gradle

Update to latest async-profiler version [DD-20220530](https://github.com/DataDog/async-profiler/releases/tag/DD-20220530)
async-profiler diff: https://github.com/DataDog/async-profiler/compare/DD-20220527...DD-20220530
Differentiate profiles comings from OpenJ9.

Bump async-profiler

---

dd-java-agent/instrumentation/undertow-2.0/undertow-2.0.gradle

undertow 2.3 (alpha) builds against Java 11 and `jakarta.servlet` , so exclude 2.3 from the range of versions expected to work with our `undertow-2.0` module

Exclude undertow 2.3 (alpha) from latestDepTest / muzzle

---

dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie

Ignore CHM (which has a lot of uninteresting nested classes) as well as all the atomic/lock classes
Ignore all JDK URL protocols except HTTP and HTTPS (i.e. currently file, ftp, jar, jmod, jrt, mailto)

Small tweak to the list of JDK classes we globally ignore

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/DDElementMatchers.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextProvider.java
dd-java-agent/agent-builder/src/test/groovy/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcherTest.groovy
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/HierarchyMatchers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextInjector.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsState.java

- splits management of the persistent `ShouldInjectFields` state out from the matcher
- refactors `ShouldInjectFieldsMatcher` so it can be moved under `HierarchyMatchers`
- some logic that requires knowing if we're redefining a class without the accessor API is moved to the raw matcher which then calls to the element matcher provided by `HierarchyMatchers`
- some logging is simplified to remove details of the classloader, which we don't know inside element matchers
- a stray call to `excludeStoreForType` that was only called when debug logging was on is removed
- this call was an attempt at an optimization, but it was never actually called in production (when debug is off)
This lets us memoize all non-trivial matchers that work on the type hierarchy, both instrumentation and field …

Include context field matching in hierarchy matchers

---

dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/LongSequence.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/ProfilerTracingContextTracker.java

Adds the concept of 'captured' long sequence size to allow concurrent updates to the sequence without causing buffer overflow when persisting that sequence.
Currently, the profiler span context is serialized to a byte buffer which is pre-sized to the sum of sizes of all relevant interval sequences. However, the serialization is done in a subsequent step and this means that there might be few extra intervals added to each sequence in the meantime and writing them out would cause buffer overflow.

Attempt to prevent buffer overflow due to data race

---

dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/HttpServerResponseEndHandlerInstrumentation.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RouteHandlerInstrumentation.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RouteImplInstrumentation.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextImplInstrumentation.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/VertxVersionMatcher.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java8/datadog/trace/instrumentation/vertx_4_0/server/EndHandlerWrapper.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java8/datadog/trace/instrumentation/vertx_4_0/server/EndHandlerWrapperAdvice.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java8/datadog/trace/instrumentation/vertx_4_0/server/PathParameterPublishingHelper.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java8/datadog/trace/instrumentation/vertx_4_0/server/RouteHandlerWrapper.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java8/datadog/trace/instrumentation/vertx_4_0/server/RouteHandlerWrapperAdvice.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java8/datadog/trace/instrumentation/vertx_4_0/server/RouteMatchesAdvice.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java8/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextJsonAdvice.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java8/datadog/trace/instrumentation/vertx_4_0/server/VertxDecorator.java
dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/client/VertxHttpClientForkedTest.groovy
dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/server/VertxHttpServerForkedTest.groovy
dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/server/VertxMiddlewareHttpServerForkedTest.groovy
dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/server/VertxSubrouterForkedTest.groovy
dd-java-agent/instrumentation/vertx-web-4.0/src/test/java/server/VertxMiddlewareTestServer.java
dd-java-agent/instrumentation/vertx-web-4.0/src/test/java/server/VertxSubrouterTestServer.java
dd-java-agent/instrumentation/vertx-web-4.0/src/test/java/server/VertxTestServer.java
dd-java-agent/instrumentation/vertx-web-4.0/vertx-web-4.0.gradle
settings.gradle

- providing support for Vert.x web 4
- Vert.x HttpServerResponseImpl class was replaced between versions 3 and 4. Reflect changes in instrumentation.
- Migrate other parts of code to Vert.x 4
- Migrate all Vert.x 3 tests to 4.
- provide instrumentation for Vert.x 4 (currently broken)
- main instrumentation related change is in `HttpServerResponseEndHandlerInstrumentation` class when the change in underlying Vert.x classes is reflected
- some test fails currently: 
```
./gradlew :dd-java-agent:instrumentation:vertx-web-4.0:test
136 tests completed, 90 failed, 23 skipped
```
- What is a minimal test suite to get this merged? I couldn't really see from run of Vert.x vertx-3.4 tests what is the number of successful tests there as the final output doesn't provide this (the immediate step …

3143 add support for vertx web 4

---

dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/SqsClientTest.groovy
dd-java-agent/instrumentation/instrumentation.gradle
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/ListWriterAssert.groovy

Adds consistent trace sorting and conditional tag to `SqsClientTest`.
There has been some changes to span order and tags in the 1.10+ versions of `amazon-sqs-java-messaging-lib`

Fix changes to Amazon AWS-SQS messaging lib

---

internal-api/src/main/java/datadog/trace/api/Config.java

Add JMXFetch multiple runtime services configs to startup output

Add JMXFetch multiple runtime services configs to startup output

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextProvider.java

it doesn't tell us anything we need to act on (we expect there to be duplicates when several instrumentations share the same context store)

Remove redundant logging from FieldBackedContextProvider

---

dd-java-agent/agent-profiling/profiling-context/profiling-context.gradle
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/ProfilerTracingContextTrackerFactory.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/StatsDAccessor.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/allocator/direct/DirectAllocator.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/allocator/heap/HeapAllocator.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

Avoids unnecessary array copies in the the routine handling the queue of inactive spans.
Adds a config knob to configure the amount of time after which a span is considered inactive.
Apparently, there are services out there creating a large numbers of mostly inactive spans which need to be tracked and then properly cleaned up in the per span context tracker. With this large number of inactive spans the performance issues related to arraylist resizing in the queue draining procedure became obvious.
First, there is a bug when the `drainTo()` method is not called with the maximum number of elements - leading to several rounds of resizing the target array list (even though the array list is pre-sized, the incorrect invocation defeats the pre-sizing).
And then there is the issue with …

Minor performance fix for span context tracking

---

dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAnnotationsInstrumentation.java

We only apply custom trace advice to declared methods that are directly annotated with the trace annotation:
https://github.com/DataDog/dd-trace-java/blob/v0.102.0/dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAnnotationsInstrumentation.java#L76
so there's no point in also matching sub-classes because:
* either they don't override the method, in which case there's nothing to instrument as the super-class implementation has already been instrumented
* or they override the method but don't annotate it, in which case the declared method will not have the annotation (overridden methods do not inherit annotations declared on the super-method) and the current advice matcher won't apply to the un-annotated method
* or they …

Simplify trace-annotation matcher

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java

We now ignore interface/field/return/param/constant references to tracer types that are guaranteed to exist
Saves space (over 100k) and time not checking types that we already know will exist...

Ignore additional muzzle references to tracer types that are guaranteed to exist

---

buildSrc/build.gradle.kts
buildSrc/src/test/groovy/InstrumentPluginTest.groovy
gradle/dependencies.gradle

Changes since we last updated...
[Byte Buddy 1.12.12](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.12)
* Use correct annotation in Byte Buddy Gradle plugin.
* Correctly resolve generified anonymous/local types that are declared within a method.
[Byte Buddy 1.12.11](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.11)
* Remove use of thread-local to guarantee Loom compatibility.
* Allow usage of byte-buddy-parent as BOM for imports.
* Add convenience for Maven to disable type validation on entry point.
* Allow Gradle plugin to consume pluginName property and discoverySet to only load plugins in the plugin class loader.
[Byte Buddy 1.12.10](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.10)
* Correctly resolve temporary folder, if custom …

Byte Buddy 1.12.12

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/RecordingDataListener.java
dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ProfilingSystemTest.java
dd-java-agent/agent-profiling/profiling-uploader/profiling-uploader.gradle
dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java

It triggers shutdown of ProfilingAgent to support profile upload on shutdown.
This is to be used by other integrations that want to guarantee that data will be flushed and uploaded before the shutdown of the process. It will be used by CI app for example to guarantee we have all profiling data.

Add Agent.shutdown API

---

dd-java-agent/agent-profiling/profiling-controller-async/src/test/java/com/datadog/profiling/controller/ControllerFactoryTest.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ControllerFactory.java

Some distributions of J9 wouldn't be detected as they wouldn't come from the open source Ecplise OpenJ9 distribution.
Fix a customer's case.

Properly detect non-OpenJ9 J9 distributions

---

dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java

Previously metrics were included in the toString of DDSpanContext.
They're no longer includd in the string representation, but the
label for them is still there, so this commit removes the obsolete
metrics label.

Remove obsolete 'metrics' label in toString

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentTransformerBuilder.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/instrumentation/aws-lambda-handler/src/main/java/datadog/trace/instrumentation/aws/v1/lambda/LambdaHandlerInstrumentation.java
dd-java-agent/instrumentation/aws-lambda-handler/src/test/groovy/LambdaHandlerInstrumentationTest.groovy
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java

This helps us separate out statically named instrumented types which we can index at build time from instrumented types where the name is only known at runtime.

Separate out configured type matching from static constant matching

---

dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationsTest.groovy
dd-java-agent/instrumentation/trace-annotation/src/test/java/dd/test/trace/annotation/TracedInterface.java
dd-java-agent/instrumentation/trace-annotation/src/test/java/dd/test/trace/annotation/TracedSubClass.java
dd-java-agent/instrumentation/trace-annotation/src/test/java/dd/test/trace/annotation/TracedSuperClass.java
dd-java-agent/instrumentation/trace-annotation/trace-annotation.gradle

This codifies what we currently expect when using `@Traced` with interface/class methods when they're overridden or implemented without explicitly copying over the `@Traced` annotation from the original interface/class method.
The current expected behaviour is that only methods that are directly annotated with `@Trace` produce spans. These methods can be declared in super-classes or as default interface methods, but if they are overridden in a sub-class then the overriding method also needs to be annotated with `@Trace` in order for that method to produce spans (note the original method will still produce its own spans if it is invoked from the overriding method with `super.method(...)`)
If a method is overridden (or implemented in the case of an interface or abstract method) and the …

Add some simple trace-annotation inheritance tests

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
dd-java-agent/src/test/groovy/datadog/trace/agent/ListIntegrationsTest.groovy
dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java

Register simple matchers/type-pool to avoid NPE when querying the various `Instrumenter`s in the CLI

Fix NPE when listing integrations with 'java -jar dd-java-agent.jar -li'

---

internal-api/src/main/java/datadog/trace/util/ClassNameTrie.java
internal-api/src/test/groovy/datadog/trace/util/ClassNameTrieTest.groovy

* Allow querying while the trie is being built
*  Allow overwriting of existing mapped values when building trie
* Reject null or empty class names when building trie

Miscellaneous ClassNameTrie improvements

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-installer/src/main/java/datadog/trace/agent/installer/AgentInstaller.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenters.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java

Provides a stable sequence of `Instrumenter`s registered as `META-INF` services as well as access to the id of the `Instrumenter` currently being installed (available via static context to avoid need to pass it around as parameter.)
The stable instrumentation id will be used in various memoization techniques as well as allowing use of a trie to match against instrumentations that target statically named types. (This means we can perform a single trie check across all statically named types rather than multiple `named` checks.)

Provide a stable sequence of Instrumenter ids

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/HierarchyMatchers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/NameMatchers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextInjector.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsState.java
dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAnnotationsInstrumentation.java

* split implementation back into separate specialized classes so we can tell them apart at runtime
* only apply deduplication to single-name matchers (the other name matchers rarely have duplicates)
* enforce that annotation matching only uses named/oneOf matchers to allow type parsing optimization
* prefer `TypeDescription.getName()` (when available) over other type-name methods for consistency
By limiting annotation matchers to `named` and `namedOneOf` we can optimize parsing of annotation elements to specific annotations only and pre-cache their descriptions. This will then avoid having to lookup (and parse) the actual annotation class at runtime.
Currently there are 839 individual requests for `named` matchers, of which only 464 are unique.
The cache was sized at 256 because that …

Simplify name matcher implementation

---

.github/workflows/test-lib-injection.yaml
.gitlab-ci.yml
lib-injection/run-local.sh

Adds a publish step for tracer tags that is part of the tracer injection image for kubernetes
The jar used in the image is not the exact same file as the one that gets published to maven central. This isn't ideal in my mind so I think this is something we could address

[alpha] Add a publish step to tracer injection image for kubernetes

---

dd-java-agent/instrumentation/aws-java-sqs-1.0/aws-java-sqs-1.0.gradle

`amazon-sqs-java-messaging-lib` v2 was just released and that requires v2 of the AWS SDK - since our `aws-java-sqs-1.0` integration uses v1 of the AWS SDK we should limit the version of this library to match.
(a separate integration will be added to support `aws-java-sqs-2.0`)

Limit amazon-sqs-java-messaging-lib to 1.x when testing aws-java-sqs-1.0 integration

---

dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
dd-java-agent/instrumentation/jms/src/test/groovy/JMS1Test.groovy

A null MessageListener is passed in when the user wants to remove the current listener, so we should just leave the null alone and pass it onto the consumer without wrapping it.

Avoid wrapping null JMS MessageListeners

---

dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java

If the `CodeSource.getLocation` returns null, attempt to fall back to parsing the `-javaagent` argument
Fix NPE on bootstrap:
```
ERROR datadog.trace.bootstrap.AgentBootstrap
at datadog.trace.bootstrap.AgentBootstrap.installBootstrapJar(AgentBootstrap.java:81)
at datadog.trace.bootstrap.AgentBootstrap.agentmain(AgentBootstrap.java:52)
at datadog.trace.bootstrap.AgentBootstrap.premain(AgentBootstrap.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at …
```

Fall back to -javaagent if CodeSource#codeLocation is null

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/AgentClassLoading.java

`AgentClassLoading` is set/reset a lot, while this doesn't take up a lot of time compared to the whole of startup, using a holder array is ~4 times faster than continually removing and recreating the thread-local entry.

use a holder array to reduce AgentClassLoading thread-local churn

---

dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGDecorator.java

NullPointerException when I instrument with trace library the test developed with testng framework.
The case can be reproduced when DataProviders returns null values.
fix #APMJAVA-790
https://datadoghq.atlassian.net/browse/APMJAVA-790

[TestNG] APMJAVA-790: Avoid npe testng framework (TestNGDecorator)

---

dd-cws-tls/dd-cws-tls.gradle
dd-java-agent/agent-debugger/agent-debugger.gradle
dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
dd-java-agent/agent-profiling/agent-profiling.gradle
dd-java-agent/agent-tooling/agent-tooling.gradle
dd-java-agent/appsec/appsec.gradle
dd-java-agent/dd-java-agent.gradle
dd-java-agent/instrumentation/instrumentation.gradle
gradle/dependencies.gradle
telemetry/telemetry.gradle

* rename 'deps.sharedInverse' to 'deps.excludeShared'
* include shared projects in 'deps.excludeShared' to reduce repetition
* make some implicit generated-source task dependencies explicit
* this lets gradle keep certain build optimizations enabled
Reduces repetition in the build and also cleans up some duplicated content in the current jar

Cleanup exclusion of shared content when creating shadow jars

---

gradle/dependencies.gradle

Bumps the async-profiler library to the latest release
Async-profiler 2.8.3 contains a fix preventing a lot of crashes when collecting CPU stacktraces. 
Merging the upstream to our fork and updating the lib in dd-trace-java will make the async-profiler usage much safer.

Bump async-profiler 2.8.3-DD-20220720

---

dd-java-agent/agent-crashtracking/agent-crashtracking.gradle
dd-java-agent/dd-java-agent.gradle
gradle/dependencies.gradle

* Add `process-utils` (new shared utils library) to `excludeShared`
* Remove `agent-crashtracking` duplicates in final agent jar, keep version included in `agent-tooling`
* simplified project setup as it doesn't really need its own `shadowJar`
* since `CrashUploader` is used directly by `AgentCLI` it currently needs to reside in the same class-loader
* we can promote it to a `shadowJar` if it becomes large enough, but would then need indirection in `AgentCLI`
Removes duplicate content from final `dd-java-agent` jar.

Fix packaging duplicates

---

dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java

Removes an unused argument, fixes logging formats and renames the config param for checkpoints hard limit
These changes should have been a part of the original PR (#3232) - unfortunately, they slipped through so they should be fixed now (thanks goes to @mar-kolya for pointing this out!)

A simple unused code artifacts cleanup

---

dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitChannelInstrumentation.java
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/datastreams/RecordingDatastreamsPayloadWriter.groovy

This PR adds datastreams monitoring support to RabbitMQ, by extracting any existing pathway context in the `RabbitDecorator` and injecting pathway context in `RabbitChannelInstrumentation`. This follows similar pattern we already have today for datastreams monitoring instrumentation in Kafka Client and gRPC.
To allow end-to-end monitoring of datastreams on RabbitMQ.
This was tested manually using example apps built with `com.rabbitmq:amqp-client:5.15.0`. This was also tested with example apps built with RabbitMQ via springboot.

Adds datastreams monitoring support to RabbitMQ

---

buildSrc/build.gradle.kts
gradle/java_no_deps.gradle
gradle/wrapper/gradle-wrapper.properties

This reverts commit bded91a7a5f7f78de242a598cda84bfca85f2e8f.
Reverts upgrade to Gradle 7.5
gradle release fails with `Failed to parse secret key`:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':release'.
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
at …
```

Revert "Upgrade gradle to 7.5 (#3655)"

---

buildSrc/build.gradle.kts
gradle/java_no_deps.gradle
gradle/wrapper/gradle-wrapper.properties

This reverts commit 5d3677cb28adb32029c32555f5c653c07f4fabab.
Reverts back https://github.com/DataDog/dd-trace-java/pull/3680
It didn't help to fix the release issue, still getting ` Failed to parse secret key`

Revert "Revert "Upgrade gradle to 7.5 (#3655)""

---

.github/CODEOWNERS

This PR adds CODEOWNERS for the `ci-app-libraries-java` Github team.

Add CODEOWNERS for ci-app-libraries-java

---

dd-java-agent/instrumentation/junit-5.3/src/main/java8/datadog/trace/instrumentation/junit5/JUnit5Decorator.java
dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestAssumptionLegacy.java

This PR includes the logic to report a particular test as `skipped` when the `org.junit.AssumptionViolatedException` is thrown during a test execution run in a JUnit5 runner.
The `org.junit.AssumptionViolatedException` exception belongs to the JUnit4 world, but as you can execute JUnit4 tests using JUnit5 engines, the tests that throw this type of exception in JUnit5 must be reported as `skipped`.

[CI-APP] Report test as `skipped` when `org.junit.AssumptionViolatedException` is thrown in JUnit5

---

dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java

The `dd_version` reported by `StatusLogger` should be the configured app/service version, not the tracer version.
For example: https://github.com/DataDog/dd-trace-go/blob/v1.40.1/ddtrace/tracer/log.go#L48

StatusLogger should report the 'dd_version' configured for the app/service

---

dd-java-agent/agent-profiling/agent-profiling.gradle
dd-java-agent/agent-profiling/profiling-context/profiling-context.gradle
dd-trace-core/dd-trace-core.gradle
gradle/dependencies.gradle

This library is currently used by both the tracer and profiling which results in some duplication that this PR removes

Move jctools-core to shared dependency

---

internal-api/src/main/java/datadog/trace/util/ClassNameTrie.java
internal-api/src/test/groovy/datadog/trace/util/ClassNameTrieTest.groovy

The trie data is stored using the same "modified-UTF8" format used by the JDK:
https://docs.oracle.com/javase/8/docs/api/java/io/DataInput.html#modified-utf-8
This PR also removes some unnecessary aliasing of `/` to `.` when building tries.

Support exporting and re-importing ClassNameTrie content to an external resource

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java

… when Iast is enabled
This PR fixes a mistake in HttpServerDecorator that causes AppSec callbacks to fail when IAST is enabled.
This stopped us from enabling IAST for testing.

Fixing mistake in HttpServletDecorator. 

---

.github/workflows/codeql-analysis.yml
.github/workflows/test-lib-injection.yaml
dd-java-agent/testing/src/test/groovy/AgentTestRunnerTest.groovy
gradle.properties
gradle/dependencies.gradle
internal-api/internal-api-8/internal-api-8.gradle
internal-api/internal-api-8/src/jmh/java/datadog/trace/util/stacktrace/HotSpotStackWalkerBenchmark.java
internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/AbstractStackWalker.java
internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/DefaultStackWalker.java
internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/HotSpotStackTraceIterator.java
internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/HotSpotStackWalker.java
internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/StackWalker.java
internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/StackWalkerFactory.java
internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/DefaultStackWalkerTest.java
internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/HotSpotStackTraceIteratorTest.java
internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/HotSpotStackWalkerTest.java
internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/StackWalkerFactoryTest.java
internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/StackWalkerTestUtil.java
internal-api/internal-api-9/internal-api-9.gradle
internal-api/internal-api-9/src/jmh/java/datadog/trace/util/stacktrace/JDK9StackWalkerBenchmark.java
internal-api/internal-api-9/src/main/java/datadog/trace/util/stacktrace/JDK9StackWalker.java
internal-api/internal-api-9/src/test/groovy/datadog/trace/util/stacktrace/JDK9StackWalkerTest.groovy
settings.gradle
utils/test-utils/src/main/java/external/util/stacktrace/RecursiveRunner.java

Util to do partial walks of stacktraces. Excludes elements that belong to the dd-trace-java project.
In IAST, when we detect a vulnerability, we need to get the class and line where it happened. The relevant class and the line will not be the last in the stack. The relevant class and line will be calculated ignoring internal dd-trace-java classes, usually applying a filter of classes on top of that (e.g standard library).
So the filtering of dd-trace-java elements is built-in, and the API uses streams for further filtering operations.
In most cases, only a few elements need to be walked through (e.g. 2-4), and only in some rare cases the whole stack needs to be examined.
This functionality will be used whenever a vulnerability is found, so its performance is critical to vulnerability …

Util to get stacktrace for reported vulnerabilities

---

dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/IntervalEncoder.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/LEB128Support.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/ProfilerTracingContextTracker.java
dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/IntervalEncoderTest.java
dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/IntervalParser.java
dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/LEB128SupportTest.java

- fixes the bug when the size of a varint is calculated incorrectly
- switches to `Instant.now()` 'epoch nanos' to peg the context intervals data instead of `System.currentTimeMillis()` - the clock source used by `Instant.now()` is used by JFR too and it will avoid big drifts between the JFR recordings and the context interval data caused by coarse granularity of `System.currentTimeMillis()`
The time drift between the JFR recordings and the context intervals data can lead to very surprising stacktraces shown in code hotspots.
While working on that change I also identified a bug in the varint size calculation leading to some context intervals not being properly written.

Per-span context tracking fixes

---

dd-java-agent/agent-profiling/profiling-controller-jfr/profiling-controller-jfr.gradle
dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/parser/ChunkHeader.java
dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/parser/ChunkParserListener.java
dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/parser/LongMapping.java
dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/parser/MetadataEvent.java
dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/parser/RecordingStream.java
dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/parser/StreamingChunkParser.java
dd-java-agent/agent-profiling/profiling-controller-jfr/src/test/java/com/datadog/profiling/controller/jfr/TestJfrRecorder.java
dd-java-agent/agent-profiling/profiling-controller-jfr/src/test/java/com/datadog/profiling/controller/jfr/parser/ParserEvent.java
dd-java-agent/agent-profiling/profiling-controller-jfr/src/test/java/com/datadog/profiling/controller/jfr/parser/StreamingChunkParserTest.java

Brings in a light-weight streaming JFR parser.
This is necessary for running some heuristics for tweaking profiling settings between recordings based on the numbers of various collected JFR events.
The parser is in no way a replacement for the JMC parser nor the JDK built-in parser. In its current form it can not read the actual event values. This is by design as we really don't need the event values and are with basically event type histo.
However, it should be possible to add support for event body processing without sacrificing the performance when/if it is needed.

Lightweight streaming JFR chunk parser

---

dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/PerSpanTracingContextTracker.java
dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/IntervalEncoderTest.java

Fixes the epoch nanos calculation
Apparently, using epoch millis to extract epoch nanos from an `Instant` does not work. The `getNano()` call returns the number of nanos after the epoch second - and that already includes also the milliseconds so by using the epoch millis the calculation gets completely messed up.

Epoch nano calculation can not use epoch millis

---

lib-injection/src/test/shell/functions.sh

Change the admission controller annotation, `admission.datadoghq.com/java-lib.custom-image` instead of `admission.datadoghq.com/java-tracer.custom-image`
Use more inclusive terminology
Related to https://github.com/DataDog/datadog-agent/pull/13094

[alpha][lib-injection] Change admission annotation

---

internal-api/src/main/java/datadog/trace/api/iast/IastModule.java
internal-api/src/main/java/datadog/trace/api/iast/InstrumentationBridge.java
internal-api/src/test/groovy/datadog/trace/api/iast/InstrumentationBridgeTest.groovy

Introduces a bridge class between instrumentations and an IAST module. All hooks in IAST instrumentation will call static methods of this bridge.
Due to the potentially large amount of callbacks the IAST module will receive and performance requirements for certain operations, we have decided to introduce a custom bridge for direct communication between instrumentations and IAST.
This bridge will have static methods for each of the callbacks that the IAST will be installing. Static methods are selected mostly because they need simpler instrumentation, with less stack operations and better performance.
The callbacks will be added to client code by instrumentation modules. The callback implementations will be in the dd-java-agent/iast module.
`IASTModule` will be implemented in future pull …

Bridge between instrumentation and IAST

---

telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
telemetry/src/main/java/datadog/telemetry/dependency/DependencyPeriodicAction.java
telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java
telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolverQueue.java
telemetry/src/main/java/datadog/telemetry/dependency/DependencyService.java
telemetry/src/main/java/datadog/telemetry/dependency/DependencyServiceImpl.java
telemetry/src/main/java/datadog/telemetry/dependency/JbossVirtualFileHelper.java
telemetry/src/test/groovy/datadog/telemetry/TelemetrySystemSpecification.groovy
telemetry/src/test/groovy/datadog/telemetry/dependency/DepSpecification.groovy
telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyPeriodActionSpecification.groovy
telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverQueueSpecification.groovy
telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverSpecification.groovy
telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyServiceImplSpecification.groovy
telemetry/src/test/java/datadog/telemetry/dependency/DependencyServiceImplTests.java
telemetry/telemetry.gradle

Reworked dependency resolution. Now - distributed in time.
Always computing hash if there is no reliable (built-in) maven info inside the dependency jar-file.
Dependency resolution and hash computation can take a lot of resource depends on jar-file size. In practice this will looks like CPU usage spike at application startup.
In current implementation we are resolving one new dependency every second. We assume that 1 second is enough to traverse entries of one jar and compute hash. E.g. in one minute we will recognise 60 dependencies without huge impact to a customer's application.

Dependencies resolution distributed in time.

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ProbeStatus.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/ProbeStatusSink.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/ProbeStatusSinkTest.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/sink/diagnosticsRegex.txt
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/sink/multipleDiagnosticsRegex.txt

Adds timestamp to probe diagnostics message so the status would appear when it was sent and not when it was received by the backend.
Two bugs:
1. Wrong probe status appear when multiple status messages are sent on the same batch
2. timestamp not updated when probe status been reemitted

Add timestamp to debugger probe diagnostics messages

---

dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy
dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
dd-java-agent/src/test/java/jvmbootstraptest/JmxStartedChecker.java

Avoid relying on an arbitrary sleep in JmxStartedChecker, which might be
not enough if the system is under heavy load.
Instead of sleeping within the process under test, we print `READY` from
the process when it's ready and continue the test right away. Under normal
circumstances, this is faster (JMXFetchTest goes from 15s to 11 on my machine)
and under heavy load, it shouldn't fail because of the arbitrary 500ms sleep
(unless it's delayed up to the 30s timeout for the test).
This test occasionally fails with a timeout, possibly because the process under
test exits before the JMX data has been sent.

Fix JMXFetchTest

---

internal-api/src/test/groovy/datadog/trace/util/ProcessSupervisorTest.groovy

Adds missing `assert`s within closures.
Spock does not introduce implicit asserts in closures. This means that
everything in the `conditions.eventually` blocks in these tests is being
ignored unless it throws an exception.
In some cases, this makes the `Process respawns when killed` test case
fail on the `secondProcess != null` assertion.

Fix ProcessSupervisorTest flakiness

---

dd-java-agent/instrumentation/mongo/mongo.gradle
dd-java-agent/instrumentation/mongo/src/test/groovy/MongoBaseTest.groovy

The embedded mongo installed had a race condition when multiple modules
tried to install it concurrently. There was a workaround at gradle
level, which did not work reliably.
Removed the gradle-level solution, and synchronize install across
multiple modules with a file lock and a timeout.

Fix race condition in embedded mongo tests

---

.circleci/upload_ciapp.sh

Reverts DataDog/dd-trace-java#3488
Too much volume with the debug logs just for dogfooding and we have customers now using it so at least there is some usage

Revert "[CIAPP-1862] Enable --logs for junitxml upload to CI Visibility"

---

dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfiler.java

The argument name was changed in async-profiler but not in dd-trace-java

Fix wall time profiler filter parameter

---

gradle/dependencies.gradle

Updates the async-profiler lib to fix an error when emitting HeapLiveObject events
async-profiler hotfix

Update async-profiler to 2.8.3-DD-20220822_1

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java

Create a new entry in AgentThread enum for Debugger Upload dispatcher thread
Following comment on https://github.com/DataDog/dd-trace-java/pull/3582#discussion_r914845377

Use AgentThreadFactory for upload dispatcher

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/dd-java-agent.gradle
dd-java-agent/iast/iast.gradle
dd-java-agent/iast/src/main/java/com/datadog/iast/IastRequestContext.java
dd-java-agent/iast/src/main/java/com/datadog/iast/IastSystem.java
dd-java-agent/iast/src/main/java/com/datadog/iast/Reporter.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/Evidence.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/Location.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/Range.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/Source.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/SourceType.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/Vulnerability.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/VulnerabilityBatch.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/json/AdapterFactory.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/json/SourceIndex.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/json/SourceTypeAdapter.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/json/SourceTypeString.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/json/VulnerabilityEncoding.java
dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastSystemTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/model/LocationTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/model/json/VulnerabilityEncodingTest.groovy
dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
gradle/dependencies.gradle
internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/AbstractStackWalker.java
internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/DefaultStackWalkerTest.java
settings.gradle
utils/test-utils/src/main/groovy/datadog/trace/test/util/DDSpecification.groovy

Add initial vulnerability reporting API for IAST. This PR includes:
* `iast` module and initial skeleton and initialization of the IAST subsystem.
* IAST callbacks when requests start, and end.
* Request context for IAST data.
* Vulnerability model.
* Reporter to add vulnerabilities to a request, and serialize them at the end of the request.
When IAST is enabled, we’ll add vulnerabilities for each request in a JSON-encoded object, stored in an internal tag (_dd.iast.json). The vulnerability objects are accumulated during the request, and encoded to JSON at the end of the request.
This API will be used whenever a vulnerability is found. It will attach a vulnerability to the current request, and it will encode them in an internal tag in JSON once the request ends.
Out of scope of this PR …

IAST vulnerability reporting API

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/TransformerDefinitionMatcher.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/TransformerDefinitionMatcherTest.java

We are using the path delimiter to anchor the filename and match it correctly inside the reversed trie.
Fix matching issue for source filenames that may match partially the probe filename. For example a probe for `VetController.java` will match for `Controller.java`.

Fix when filenames are matching partially

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
dd-java-agent/src/test/java/jvmbootstraptest/LogManagerSetter.java

Delays starting tracer/profiler when custom `LogManager` is detected and we're running on an IBM JDK.
IBM JDKs don't currently include JFR, so don't suffer from the indirect loading of JUL via JFR that happens with Java 8.
However they do include an IBM specific security provider, `IBMSASL`, which touches JUL when our embedded OkHttp instance uses TLS. For this reason we should always delay starting the tracer and profiler when a custom `LogManager` is detected and we're running on an IBM JDK.
This PR also cleans up some method names to make it a bit clearer what we're checking and why.

Fix custom logger delay on IBM JDKs

---

dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/EndHandlerWrapper.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java8/datadog/trace/instrumentation/vertx_4_0/server/EndHandlerWrapper.java
dd-smoke-tests/quarkus/src/test/groovy/datadog/smoketest/QuarkusSmokeTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/ProcessManager.groovy

injected helper will be in different package to modified VertX class, so cannot rely on package-private access
Error seen in quarkus smoke test logs before this fix:
```
[dd.trace 2022-08-22 18:12:21:819 +0000] [executor-thread-1] DEBUG datadog.trace.bootstrap.ExceptionLogger - Failed to handle exception in instrumentation for io.vertx.core.http.impl.HttpServerResponseImpl
java.lang.IllegalAccessError: Class io/vertx/core/http/impl/HttpServerResponseImpl illegally accessing "package private" member of class datadog/trace/instrumentation/vertx_3_4/server/EndHandlerWrapper
at io.vertx.core.http.impl.HttpServerResponseImpl.endHandler(HttpServerResponseImpl.java:297)
at io.quarkus.resteasy.runtime.standalone.VertxBlockingOutput.<init>(VertxBlockingOutput.java:45)
at …
```

Fix capturing of vertx.route-handler spans

---

dd-java-agent/agent-profiling/profiling-context/profiling-context.gradle
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/AsyncProfilerTracingContextTracker.java

Removes the implicit context activation in the tracker constructor
A concurrent change in the context tracking code made this activation redundant and, in fact, it will cause weird span activation intervals.

Fix the async-profiler context tracking

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy
remote-config/src/main/java/datadog/remoteconfig/ConfigurationChangesListener.java
remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java
remote-config/src/test/groovy/datadog/remoteconfig/ConfigurationPollerSpecification.groovy

Add support for multiple configurations to be applied per product for ConfigurationPoller.
Listeners now accept configKey (string) to indicate which config to apply or remove (indicated by null configuration)
Live debugger can receive multiple configurations.

Add support for multiple configurations per product

---

.circleci/config.yml

Adds a CircleCI fan-in job named `required` that depends on all the other CircleCI jobs that are required for a PR to be merged on github.
When we start having multiple versions with different JVM requirements et.c. it would be easier to maintain github branch protection if it only needs to care about one CircleCI job.

Add a CircleCI job named required that github can enforce

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/DBQueryInfo.java

Prevents storing extremely large SQL input strings in memory as cache keys.

Enforce max size on cached key string

---

dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

It turns the `profiling.start-force-first` option from experimental to a regular one.
After https://bugs.openjdk.org/browse/JDK-8233197 fixed we have a good choice of JDKs where this option would be safely supported. Allowing the option with a safety-break when we detect an unsupported JDK seems like the right way to go.
The PR also contains some additional cleanups discovered while working on the main feature.

Allow the 'start-force-first' option on newer JDKs

---

dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/IntervalEncoder.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/IntervalSequencePruner.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/LongSequence.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/PerSpanTracingContextTracker.java

It fixes the per-span context serialization such that it properly calculates the required size of buffers.
The original implementation forgot about the pruning process possibly inserting one synthetic element and this would have lead to incorrect sizing of the serialization buffers and spurious buffer underflow exceptions.
Fixing the per-span context serialization.

Fix spurious buffer underflow error in per-span context serialization

---

dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java

An after fix for wrong method call `Platform.isJavaVersion()` instead of `Platform.isJavaVersionAtLeast()`

'isJavaVersion()' -> 'isJavaVersionAtLeast()'

---

.circleci/config.yml
communication/communication.gradle
dd-java-agent/instrumentation/grizzly-2/src/test/groovy/GrizzlyTest.groovy
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
dd-java-agent/instrumentation/hibernate/core-4.3/core-4.3.gradle
dd-java-agent/instrumentation/instrumentation.gradle
gradle/java_no_deps.gradle
telemetry/telemetry.gradle

Changes source and destination target to Java 8 and removes the Java 7 test job from CircleCI
Version 1.x of dd-trace-java will have Java 8 as a minimum so we can upgrade dependencies
Upgraded dependencies and other changes in the build will follow in subsequent PRs

Compile for Java 8, and don't test on Java 7

---

dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTTracer.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTTracer.java

Reduce OT Wrappers footprint by removing the converter field

Remove an extra field converter from OT Wrappers

---

dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
dd-java-agent/agent-crashtracking/src/test/java/com/datadog/crashtracking/CrashUploaderTest.java

This allows to integrate crash tracking to error tracking product by extracting a message and a kind. We also want to extract a stacktrace.

Extract message and kind from native Java crash

---

dd-java-agent/instrumentation/slick/slick.gradle

Limits the version range for latestDepTest for the slick instrumentaton
The 3.4+ version of slick pulls in slf4j-2.+ which is incompatible with the test harness

Limit latestDepTest for slick instrumentation because of incompatible slf4j

---

dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/TagsHelperTest.java
dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/CompressionTypeTest.java
dd-smoke-tests/springboot-openliberty/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySmokeTest.groovy
internal-api/src/test/java/datadog/trace/util/TagsHelperTest.java

Sets the initial capacity in tests with largish or humongous `StringBuilder` instances
Don't stress the heap

Set initial capacity for StringBuilder in tests

---

dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/PerSpanTracingContextTracker.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/PerSpanTracingContextTrackerFactory.java
dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/PerSpanTracingContextTrackerFactoryTest.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

This is adding another config knob for the maximum number of in-flight spans which will be tracked by the per-span context tracking mechanism.
Once the limit is reached the per-span context tracking will be automatically disabled for the application as there is a good chance the application is rapidly generating high number of spans and tracking them would blow up the memory and cost a lot of CPU in terms of GC and maintaining the delay queues. This kind of application is simply not possible to use with the per-span context tracking and therefore turning it off as soon as possible is the best thing we can do.
There are applications out there generating 10s of 1000s of spans per second. This is putting a huge strain on the per-span context tracking because we need to keep extra data …

Introduce a hard limit for in-flight spans with tracked context

---

.github/CODEOWNERS

Add CODEOWNERS entry for the @DataDog/iast-java team.

Add CODEOWNERS entry for the IAST team

---

internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/AbstractStackWalker.java
internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/DefaultStackWalker.java
internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/DefaultStackWalkerTest.java
internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/HotSpotStackWalkerTest.java
internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/StackWalkerTestUtil.java
internal-api/internal-api-9/src/test/groovy/datadog/trace/util/stacktrace/JDK9StackWalkerTest.groovy
utils/test-utils/src/main/java/datadog/trace/test/util/AnyStackRunner.java

`Thread.currentThread().getStackTrace()` seems to be the same as `new
Throwable.getStackTrace()` for the general case, but it results in an
additional frame. This might result in a slight performance loss, and
also was the source of a bug where we got an unexpected result.
Refactored stack walker tests to spot this kind of issue.
This is a follow up to https://github.com/DataDog/dd-trace-java/pull/3647

Fix issue in default stack walker implementation

---

communication/src/main/java/datadog/communication/http/OkHttpUtils.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java

A quick change in HTTP client builder in order to support `null` URL.
Some URL might be null when using `Http.parse` instead of `HttpUrl.get` and break the client creation while testing for URL scheme.

Handle invalid URL at HTTP client creation

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/SnapshotProbe.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java

If only one field is present, the others get the default values.
We have added default values for `SnapshotProbe.Capture` class and a private no-arg constructor for Moshi to trigger execution of this constructor ans assign default values
with only one value in Json configuration, the other values for `SnapshotProbe.Capture` are 0 which is not expected

Fix capture deserialization for snapshot probes

---

.circleci/autoforward.py
.circleci/config.yml
dd-java-agent/instrumentation/jdbc/src/test/groovy/RemoteJDBCInstrumentationTest.groovy
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/rabbitmq-amqp-2.7.gradle
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
dd-java-agent/instrumentation/vertx-mysql-client-3.9/src/test/java/TestDatabases.java

Updates the `autoforward.py` utility to create the SSH tunnels when the Docker API asks for the actual container information. It will try to create the forward using the same port or pick a random one if it's in use, if a random one is chosen, then the return JSON will be update accordingly. The SSH forward is not established right  away, it will be delayed until the remote endpoint is actually listening, so the tescontainers waiting strategies are not mislead by the forward.
Testcontainers are causing lots of failures in the CI environment due to waiting strategies failing to check if containers are started successfully.

On demand port forwarding for testcontainers on CI

---

internal-api/internal-api-8/internal-api-8.gradle
internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/StackWalkerFactory.java

If we cannot instantiate JDK9StackWalker, a warning is printed, which is
fair if we're on JDK 9+, but pointless otherwise. Check the JDK version
for trying to instantiate StackWalker implementations, to avoid
unnecessary noise.
cc @robertomonteromiguel this removes the warning you found

Avoid warning when using StackWalker on JDK <9

---

dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/HelperInjectionTest.groovy
dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ClassLoadingTest.groovy
dd-java-agent/testing/src/test/groovy/context/FieldInjectionForkedTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
utils/test-utils/src/main/java/datadog/trace/test/util/GCUtils.java

Defines a default timeout of 1 minute for the method `datadog.trace.test.util.GCUtils#awaitGC` in order to prevent a gradle timeout on CI
Currently on CI some builds for the IBM JDK8 are failing after 9 minuties with timeouts at gradle level, in those builds there's no information about the tests that failed due to the timeout:
```
> Task :dd-java-agent:agent-tooling:test FAILED
Requesting stop of task ':dd-java-agent:agent-tooling:test' as it has exceeded its configured timeout of 9m.
> Task :dd-java-agent:agent-tooling:forkedTest
FAILURE: Build failed with an exception.
Execution failed for task ':dd-java-agent:agent-tooling:test'.
> Timeout has been exceeded
* Try:
> Run with --info or --debug option to get more log output.
* Exception is: …
```

Add temporal bound to awaitGC method

---

dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
dd-trace-api/src/main/java/datadog/trace/api/config/IastConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

* Move all keys to `IastConfig`
* Do not prefix with `AppSec`.
* Some other tweaks.
Ensure some degree of consistency of config flags within dd-trace-java, and also across IAST implementations in other languages (e.g. Node).

Standarize IAST config flags

---

dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
dd-java-agent/iast/src/main/java/com/datadog/iast/IastSystem.java
dd-java-agent/iast/src/main/java/com/datadog/iast/Reporter.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/Evidence.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/Range.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/Source.java
dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplCipherTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplHashTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplTestBase.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy

Since every IAST callback passes through an instance of IastModule, we
can use instances of things like `Reporter` and rely less on static
methods. This will improve testability.
Tests are adjusted and simplified accordingly.
`equals`/`hashCode` are implemented in some models to ease testing
assertions.

Improve IAST testability with less statics

---

.circleci/autoforward.py

Use autossh to ensure that SSH forwards for testcontainers are kept running during the builds on CI
If the tunnel breaks for any reason it can cause test to fail

Add autossh to maintain forwards for testcontainers

---

.github/workflows/lib-injection.yaml

Address Charles comment: https://github.com/DataDog/system-tests/pull/453#issuecomment-1231452953.
The library injection tests do not reuse any system test code. They're effectively two cocolated projects. Charles recommends using different build and run scripts to fully isolate the library injection tests. This should improve the readability and maintainability.

fix: use custom shell scripts to run lib injection system tests

---

.github/workflows/add-assets-to-release.yaml

This action will update the `download-latest-vX` releases body and attachment to the latest version available.
This action takes place in the Java 7 deprecation context.
We will need to create releases with stable tags in order to provide permanent links for download each major version.
Those releases will be based on orphan branch tagged `download-latest-vX` and will contains a copy of the latest attachment available.
On each new release, this action will update this meta release. It can also be trigger manually if needed, proving the major version to update.
This PR replaces the original one: #3757.
The related releases [Latest](https://github.com/DataDog/dd-trace-java/releases/tag/untagged-2b8162a904f048aad041) and [Latest v0](https://github.com/DataDog/dd-trace-java/releases/tag/untagg …

Add download release update to the asset upload workflow

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/TimelinePrinter.groovy

Should fix this exception seen occasionally on CircleCI:
```
java.lang.NegativeArraySizeException
at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
at java.lang.StringBuilder.<init>(StringBuilder.java:107)
at datadog.trace.agent.test.checkpoints.TimelinePrinter.repeat(TimelinePrinter.groovy:78)
at datadog.trace.agent.test.checkpoints.TimelinePrinter.print(TimelinePrinter.groovy:42)
at datadog.trace.agent.test.checkpoints.TimelineCheckpointer.throwOnInvalidSequence(TimelineCheckpointer.groovy:64)
at org.spockframework.mock.runtime.ByteBuddyMethodInvoker.respond(ByteBuddyMethodInvoker.java:20)
at org.spockframework.mock.runtime.MockInvocation.callRealMethod(MockInvocation.java:59)
at org.spockframework.mock.CallRealMethodResponse.respond(CallRealMethodResponse.java:30) …
```

Avoid NegativeArraySizeException when printing invalid timeline sequence

---

dd-java-agent/appsec/appsec.gradle
dd-java-agent/dd-java-agent.gradle

Update AppSec WAF to 4.4.0
Changes:
- Support for ARM processors (Linux/MacOS)
- Updated WAF to version 1.5.0 ([see changes](https://github.com/DataDog/libddwaf/releases/tag/1.5.0-alpha0))

Update AppSec WAF to 4.4.0

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentTransformerBuilder.java
dd-java-agent/agent-tooling/agent-tooling.gradle
dd-java-agent/agent-tooling/src/jmh/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteBenchmark.java
dd-java-agent/agent-tooling/src/jmh/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteBenchmarkHelper.java
dd-java-agent/agent-tooling/src/jmh/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteBenchmarkInstrumenter.java
dd-java-agent/agent-tooling/src/jmh/java/datadog/trace/agent/tooling/bytebuddy/csi/CalleeBenchmarkInstrumenter.java
dd-java-agent/agent-tooling/src/jmh/java/foo/bar/DummyApplication.java
dd-java-agent/agent-tooling/src/jmh/java/foo/bar/DummyController.java
dd-java-agent/agent-tooling/src/jmh/resources/META-INF/services/datadog.trace.agent.tooling.Instrumenter
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/Advices.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteInstrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteTransformer.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/csi/CallSiteAdvice.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/csi/Pointcut.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/AdvicesTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/BaseCallSiteTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteInstrumenterTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteTransformerTest.groovy
dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/csi/StringConcatExample.java
dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/csi/TestCallSiteAdvice.java
dd-java-agent/agent-tooling/src/test/resources/META-INF/services/datadog.trace.agent.tooling.csi.TestCallSiteAdvice
dd-java-agent/agent-tooling/src/test/resources/datadog/trace/agent/tooling/bytebuddy/csi/call_site.trie

This PR contains the basics to do Call Site Instrumentation in the tracer. It defines a new type of instrumenter `datadog.trace.agent.tooling.bytebuddy.csi.CallSiteInstrumenter` that is able to register instances of `datadog.trace.agent.tooling.csi.CallSiteAdvice` to perform the instrumentation via ASM.
Instrumentations related to IAST often affect core parts of the JDK (String, StringBuilder...) where using callee instrumentation (by default in ByteBuddy) is not good enough for performance. Call site instrumentation focuses on the calls to the instrumented methods enabling the use of inclusion/exclusion lists to fine tune where to instrument.
Following this PR comes [[IAST] Call Site Instrumentation plugin #3729](https://github.com/DataDog/dd-trace-java/pull/3729) where advices can be …

[IAST] Call Site Instrumentation support

---

.github/workflows/lib-injection.yaml

https://github.com/DataDog/system-tests/pull/453 has been merged.

Use main system-tests branch for lib injection tests

---

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/DebuggerIntegrationTest.java

avoid asserting locals for debugger smoke test on IBM JDK

Don't assert locals/arguments for IBM JDK

---

dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java

Avoid AppSec callback being called with IAST context.
A `ClassCastException` was being thrown for gRPC with both AppSec and IAST enabled.

Fix gRPC instrumentation callback for IAST/AppSec

---

CONTRIBUTING.md

Clarifies required environment variables for command line build.  The build requires PATH, JAVA_8_HOME, JAVA_11_HOME and JAVA_HOME, if present, all being set correctly.   If either JAVA_HOME or PATH point to a different JDK the build will fail.

Clarify required env vars

---

dd-smoke-tests/debugger-integration-tests/debugger-integration-tests.gradle
settings.gradle

Disables the `latest-jdk-app` part of the `debugger-smoke-tests`.
The `latest-jdk-app` project fails often enough with a hard to diagnose `jgit` failure that it is affecting normal CI builds and runs. Disable the test until someone has the time to look at the build properly and fix it.

Disable latest-jdk-app in debugger-smoke-tests until jgit issue is fixed

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/KafkaClientTest.groovy
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
dd-java-agent/instrumentation/kafka-streams-0.11/src/latestDepTest/groovy/KafkaStreamsTest.groovy
dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTestBase.groovy

Retry kafka based tests
These tests appear to be pretty flaky, which should be investigated, but their failures block unrelated work.

retry all kafka clients tests

---

.circleci/config.yml

Add more heap for tests.
Looking closely to heap dump after test OOM shows that there is just not enough heap to hold all required objects in memory. Special tests like
`com.datadog.debugger.sink.DebuggerSinkTest#splitSnapshotBatch`, `com.datadog.debugger.sink.DebuggerSinkTest#tooLargeSnapshot` or
`com.datadog.debugger.sink.DebuggerSinkTest#tooLargeUTF8Snapshot`
require more memory than usual, without leaking.
fix OOME

Bumping test forked max heap to 768MB

---

dd-java-agent/agent-bootstrap/agent-bootstrap.gradle
dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy

Ensure `internal-api-9` is included in the final jar.
We were logging a ClassNotFound exception for `JDK9StackWalker`, because the class was not included in the final jar.

Fix missing JDK9StackWalker from final jar

---

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle

Excludes jcommander from our JMXFetch transitives, depends on https://github.com/DataDog/jmxfetch/pull/397
The version of jcommander has a CVE, this also makes our jar smaller

Exclude jcommander

---

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ServerDebuggerIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java

`TracerDebuggerIntegrationTest` seems to face a race between Tracer instrumentation and Debugger instrumentation:
while a class is loading
(`org.springframework.web.servlet.DispatcherServlet`), Tracer is transforming it while Debugger receiving configuration and add new transformer, but this transformer will not be take into account because class is already transforming and after that will be considered as loaded.
Debugger perform also a retransformation for already loaded classes but as this class is currently transforming with Tracer it is not part of loaded classes.
Workaround is to try to re-instrument the class.
While topping Server app for `ServerDebuggerIntegrationTest`, Http server could be stopped before sending Http response. Catch exception as it is not an issue.
Smoke test …

Fix debugger smoke test flakiness

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/StatsdMetricForwarder.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerAgentTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java

`debugger` -> `dynamic.instrumentation`
debugger product is renamed dynamic instrumentation

Rename debugger config properties

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java

The advice expects a `Runnable` as the first method argument, so the method matcher should check that (we don't expect to wrap overloaded `execute` methods that have sub-types of `Runnable`)

Add missing argument constraint to ThreadPoolExecutorInstrumentation.execute

---

.github/workflows/add-assets-to-release.yaml
.github/workflows/update-download-releases.yaml

Add a workflow to update download releases that can be manually triggered.
So it can update or fix download releases when needed.
It was requested by Bjorn.
This workflow is not triggered on release publication as it is not safe to assume the upload asset workflow will finish before this one starts.

Add workflow to update download releases

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakCache.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakCaches.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ClassLoaderMatchers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java

[ depends on #3802 and #3804 ]
* Replaces multiple class-loader matcher caches with single cache of 'hasClass' masks
* this saves space, because we only need to have one compressed mapping per-class-loader
* Performs all class-loader matches in a single sweep for each class-loader, rather than on-demand
* while this can mean more up-front resource checks, it also means less context-switching
* simple tests show a startup improvement of half a second off an overall startup time of 10 seconds

Introduce class loader masks

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerAgentTest.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/DebuggerIntegrationTest.java

debugger should start and subscribe to RC before starting to poll
Product (Debugger or AppSec) shouldn't start ConfigurationPoller, but only perform in one place once everybody has subscribed to it
fix race condition spotted by smoke tests

Fix race condition between RC and debugger

---

.circleci/collect_libs.sh

Tries to save any error log files or heap dumps that happen during the build of the project on CI

Collect error logs and heap dumps during CI build

---

gradle/java_no_deps.gradle

Limit heap of java exec tasks and compile tasks to 256M

---

dd-java-agent/iast/iast.gradle
dd-java-agent/iast/src/jmh/java/com/datadog/iast/overhead/OverheadControllerBenchmark.java
dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
dd-java-agent/iast/src/main/java/com/datadog/iast/IastRequestContext.java
dd-java-agent/iast/src/main/java/com/datadog/iast/IastSystem.java
dd-java-agent/iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
dd-java-agent/iast/src/main/java/com/datadog/iast/RequestStartedHandler.java
dd-java-agent/iast/src/main/java/com/datadog/iast/overhead/Operation.java
dd-java-agent/iast/src/main/java/com/datadog/iast/overhead/Operations.java
dd-java-agent/iast/src/main/java/com/datadog/iast/overhead/OverheadContext.java
dd-java-agent/iast/src/main/java/com/datadog/iast/overhead/OverheadController.java
dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplCipherTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplHashTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplTestBase.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/RequestEndedHandlerTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/RequestStartedHandlerTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/overhead/OverheadContextTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/overhead/OverheadControllerTest.groovy
dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/IastConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Implement Overhead Control Engine (OCE) for IAST operations. It creates a module that by design ensures the maximum overhead for IAST operations. The OCE will be responsible for assuring performance and short circuiting the logic if it reaches the maximum.
Low overhead is a mandatory requirement for a software that is running in production. The main constraint is that having to introduce many hooks for taint tracking keeping a low overhead is a challenging task.
The OCE is an element that by design ensures that the overhead does not go over a maximum limit. It will measure operations being executed in a request and it will deactivate detection (and therefore reduce the overhead to nearly 0) if a certain threshold is reached.
First approach set threshold (configurable) to: 
- Only about …

[IAST] Add overhead controller to add caps on analyzed requests and reported vulnerabilities

---

dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfilerRecording.java
dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfilerRecordingData.java
dd-java-agent/agent-profiling/profiling-auxiliary/src/main/java/com/datadog/profiling/auxiliary/AuxiliaryRecordingData.java
dd-java-agent/agent-profiling/profiling-auxiliary/src/test/java/com/datadog/profiling/auxiliary/AuxiliaryRecordingDataTest.java
dd-java-agent/agent-profiling/profiling-controller-async/src/main/java/com/datadog/profiling/controller/async/AsyncOngoingRecording.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkOngoingRecording.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkRecordingData.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkRecordingDataTest.java
dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkOngoingRecording.java
dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkRecordingData.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/OngoingRecording.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/RecordingData.java
dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ProfilingSystemTest.java
dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
dd-java-agent/instrumentation/shutdown/src/main/java/datadog/trace/instrumentation/shutdown/ShutdownInstrumentation.java
dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/ProfilingTestApplication.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/ProfilingIntegrationTest.java
internal-api/internal-api.gradle
internal-api/src/main/java/datadog/trace/api/profiling/ProfilingSnapshot.java

Extends the functionality created for the CI integration to always upload the active profile on orderly JVM exit.
An orderly JVM exit is observed when the application exits either voluntarily or due to a Java exception, and also when the process is 'soft' killed (eg. JVM has a chance to clean up).
'Hard' kills and VM crashes will not be handled since the JVM is stopped immediately and there is nothing left running that could take care of uploading the profile.
Reusing the existing functionality to provide better profiling coverage.

Upload profile on JVM exit

---

communication/communication.gradle
communication/src/test/groovy/datadog/communication/http/SafeRequestBuilderTest.groovy
gradle/dependencies.gradle
utils/test-agent-utils/decoder/decoder.gradle

Adds checks for the exception message content for the `SafeRequestBuilder` to make sure that sensitive header values don't leak.
Show that the mitigations for header value leaking in OkHttp3 [SNYK-JAVA-COMSQUAREUPOKHTTP3-2958044](https://security.snyk.io/vuln/SNYK-JAVA-COMSQUAREUPOKHTTP3-2958044) added in #3682 is effective.

Make SafeRequestBuilderTest check that header values don't leak

---

gradle/java_no_deps.gradle

Limits the amount of memory the tasks to compile Groovy and Kotlin can use
The build of the project in CircleCI started to fail due to memory issues. The max memory for compile Java and Scala was limited to 256M but it was missing Groovy and Kotlin

Limit memory for compile groovy and kotlin tasks

---

dd-java-agent/iast/src/main/java/com/datadog/iast/IastSystem.java
dd-java-agent/iast/src/main/java/com/datadog/iast/Reporter.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/Vulnerability.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
dd-java-agent/iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/model/VulnerabilityTypeTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/model/json/VulnerabilityEncodingTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/IastConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

- Add the `hash` property to vulnerability model,  this will be used to determine if two vulnerabilities are equals
- Add logic to `Reporter` that manages duplicated vulnerabilities reporting
Because we discover vulnerabilities by analyzing the requests, and different requests can lead to vulnerabilities with same type in the same file and line, we need mechanisms to not be reporting vulnerabilities persistently referencing same code issue.
PR fixing system tests: https://github.com/DataDog/system-tests/pull/508
For this first version:
- We are going to define that whenever a vulnerability has same type and occurs in the same file and line, they will be considered equals regardless of the rest of the parameters. This is the reason to add a hash field composed with type, file and line to …

[IAST] Vulnerability hashing and deduplication V0

---

dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2ResponseStatusInstrumentation.java

`Servlet2ResponseStatusAdvice` expects the first argument of `sendError`/`setStatus` to be an integer status code - update the method matcher in `Servlet2ResponseStatusInstrumentation` to record that constraint
Avoids instrumentation warnings when sub-classes of `HttpServletResponse` overload the `sendError`/`setStatus` methods.

Update Servlet2 "sendError" matcher to reflect expectations in its advice

---

dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/QueueBufferConfigInstrumentation.java
dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsReceiveRequestInstrumentation.java

Split SQS receive request instrumentation so we can apply structural constraint to the `QueueBufferConfig` part
The `QueueBufferConfig` advice expects there to be a field called `receiveAttributeNames` so we should reflect that in the type matcher as a structural check. Note that since this constraint is recorded as a byte-buddy `@Advice.FieldValue` it is not currently picked up by the muzzle plugin, and therefore doesn't appear as a muzzle constraint.

Split SQS receive request instrumentation

---

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java
telemetry/src/main/java/datadog/telemetry/TelemetryService.java
telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java
telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
telemetry/src/test/groovy/datadog/telemetry/TelemetryRunnableSpecification.groovy
telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
telemetry/src/test/resources/telemetry_intake_emu.py

Introduced `DD_TELEMETRY_HEARTBEAT_INTERVAL` option that should be used to testing purpose only. The value of the variable should determine the interval in which the client sends heartbeat updates in seconds and must be in the range of 1-3600. (The default value is 60).

Telemetry heartbeat interval option.

---

dd-java-agent/instrumentation/jdbc/src/test/groovy/RemoteJDBCInstrumentationTest.groovy
dd-java-agent/instrumentation/mongo/src/test/groovy/MongoBaseTest.groovy
dd-java-agent/instrumentation/netty-3.8/src/latestDepTest/groovy/Netty38ClientTest.groovy

Disables some flaky tests:
- Netty38ClientTest - "connection error (unopened port)" https://github.com/DataDog/dd-trace-java/issues/3886
- MongoBaseTest https://github.com/DataDog/dd-trace-java/issues/3884
CI Cleanup

Disabled flaky tests

---

dd-java-agent/instrumentation/osgi-4.3/src/main/java/datadog/trace/instrumentation/osgi43/BundleWiringHelper.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

In practice we've only needed to check the first-level of OSGi dependencies and removing the search depth option makes the helper much simpler. If we ever need to support further widening of the search then a more targeted automatic approach would be better than having a manual switch that affects all OSGi resource/class lookups.

Simplify OSGi helper to only check the first-level of bundle wiring

---

buildSrc/build.gradle.kts
buildSrc/src/test/groovy/InstrumentPluginTest.groovy
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentTransformerBuilder.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDTransformers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteTransformer.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/HelperInjectionTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/BaseCallSiteTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteInstrumenterTest.groovy
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/ServletRequestBodyInstrumentation.java
dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RequestImplInstrumentation.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
dd-java-agent/testing/src/test/java/locator/ClassInjectingTransformer.java
gradle/dependencies.gradle
utils/test-utils/src/main/groovy/datadog/trace/test/util/DDSpecification.groovy

Changes since last update:
[Byte Buddy 1.12.17](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.17)
* Use decorating EntryPoint in Android Gradle plugin.
* Introduce PatchMode on AgentBuilder patching to allow for control over overlap.
[Byte Buddy 1.12.16](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.16)
* Fix Gradle release script to publish plugin.
[Byte Buddy 1.12.15](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.15)
* Introduce ClassVisitorFactory which allows to translate to and from class wrappers in a different ASM namespace.
* Allow builders to change to ClassVisitors.
* Add support for Android instrumentation from Gradle plugin.
[Byte Buddy 1.12.14](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.14)
* Add …

byte-buddy 1.12.17

---

dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/ChannelFutureListenerInstrumentation.java

Since we use the future's channel as a context-store key, and context-store keys must be non-null.
Without this check the inserted advice would throw a NPE if `future.getChannel()` was ever null.

Add defensive check to Netty 3.8 advice in case future.getChannel() is null

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java

Keep track of capturing probeIds based on condition evaluations before adding snapshots to the sink
Support for conditions for duplicated probes

Add support conditions for duplicated probes

---

dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java

It removes JDK 8 from the list of versions to 'force-start-first' profiler.
Although the original issue https://bugs.openjdk.org/browse/JDK-8233197 seems to be backported to JDK 8 it is not the case as the fix was later reverted because it was breaking JVMTI spec.
This change is not going to affect anyone else but users having set `dd.profiling.start-force-first` system property to true and running on JDK 8 - I expect that the number of such users is very close to zero.

Remove JDK 8 from the list of versions safe to 'force-start-first'

---

dd-java-agent/agent-profiling/profiling-auxiliary/src/main/java/com/datadog/profiling/auxiliary/AuxiliaryProfiler.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/AsyncProfilerTracingContextTrackerFactory.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ControllerFactory.java
internal-api/src/main/java/datadog/trace/api/Platform.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java

Also cleans up some unnecessary keywords in `ConfigProvider` where I thought about adding a new API to support contingent settings. This isn't necessary but it wouldn't warrant its own PR and might never get done otherwise.
Async-profiler doesn't work on windows or macos, so if a user accidentally enables it we shouldn't load it.

Disable async-profiler except on Linux

---

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/DebuggerIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ServerDebuggerIntegrationTest.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

no longer use URLs as everything is going through datadog agent

Remove snapshot & probe URLs config

---

.circleci/config.yml
gradle/wrapper/gradle-wrapper.properties

Splits the cache on CircleCI into two parts. One large with all the dependencies, that is only saved for `master` and `project/...` branches, and a smaller cache that is saved every time. This leads to new dependencies being downloaded multiple times, but that should hopefully not be a big problem for short lived branches.
This cuts 4-5 minutes off a build in a PR.
Slow builds are slow.

Split CircleCI gradle cache into two parts

---

remote-config/src/main/java/datadog/remoteconfig/PollerRequestFactory.java

Backend expects tracer version to be reported in format of Semantic Versioning 2.0.0
https://semver.org/spec/v2.0.0.html#spec-item-10
A build version must be separated with `+` instead of `~`. 
Ex: `0.109.0+bf0a771b10`

Tracer version now corresponds Semantic Versioning 2.0.0

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/blocking/BlockingActionHelper.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/blocking/BlockingActionHelperSpecification.groovy
dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/TestSpan.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/EventDispatcherSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
dd-java-agent/appsec/src/test/resources/test_multi_config.json
dd-java-agent/instrumentation/jetty-9/jetty-9.gradle
dd-java-agent/instrumentation/jetty-common/src/main/java/datadog/trace/instrumentation/jetty/HandleRequestVisitor.java
dd-java-agent/instrumentation/jetty-common/src/main/java/datadog/trace/instrumentation/jetty/JettyBlockingHelper.java
dd-java-agent/instrumentation/jetty-common/src/main/java/datadog/trace/instrumentation/jetty9/HandleVisitor.java
dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/ServletBlockingHelper.java
dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatBlockingHelper.java
dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatServerInstrumentation.java
dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/HandlerInstrumentation.java
dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/UndertowBlockingHandler.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
internal-api/src/main/java/datadog/trace/api/gateway/Flow.java
internal-api/src/main/java/datadog/trace/api/gateway/IGSpanInfo.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java

Instead of hardcoding the presumed ids of actions that should elicit blocking a request, the spec is fully implemented. The action returned by the WAF is actually interpreted as an action id and the that id is looked up in the "actions" entry of the WAF configuration. Then the type of the action is looked up, and "block_request" is recognized. The parameters of the action (http response code to send and the content type of the response: one of html, json and out) are also taken into account.

Appsec: support parameterization of blocking responses

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentTransformerBuilder.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/MuzzleMatcher.java
dd-java-agent/agent-builder/src/test/groovy/datadog/trace/agent/test/DefaultInstrumenterForkedTest.groovy
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterState.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenters.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceMatcher.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/muzzle/ReferenceMatcherTest.groovy

Tracks instrumentation state in a single place, rather than have a muzzle cache per-instrumentation.
More compact - this refactoring also lets us have a clean way to notify when an instrumentation is applied, rather than as a hack inside the muzzle matcher.

Track instrumentation state

---

dd-java-agent/agent-tooling/agent-tooling.gradle
dd-java-agent/agent-tooling/src/jmh/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteBenchmarkInstrumenter.java
dd-java-agent/agent-tooling/src/jmh/java/datadog/trace/agent/tooling/bytebuddy/csi/CalleeBenchmarkInstrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/Advices.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteInstrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteTransformer.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteUtils.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/ConstantPool.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/csi/CallSiteAdvice.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/csi/InvokeAdvice.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/csi/InvokeDynamicAdvice.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/AdvicesInvokeDynamicTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/AdvicesTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/BaseCallSiteTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteInstrumenterTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteTransformerInvokeDynamicTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteTransformerTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteUtilsTest.groovy
dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/csi/StringConcatCategory2Example.java
dd-java-agent/agent-tooling/src/test/java11/datadog/trace/agent/tooling/csi/StringPlusConstantsExample.java
dd-java-agent/agent-tooling/src/test/java11/datadog/trace/agent/tooling/csi/StringPlusExample.java
dd-java-agent/agent-tooling/src/test/java11/datadog/trace/agent/tooling/csi/StringPlusLoadWithTagsExample.java
dd-java-agent/agent-tooling/src/test/java11/datadog/trace/agent/tooling/csi/UnknownArityExample.java

Add support for Invoke Dynamic instructions to the Call Site instrumenter
From JDKs >= 9 the solution for `+` concatenation is based on invoke dynamic instructions instead of the traditional `StringBuilder` approach

[IAST] Add support for invoke dynamic csi advices

---

telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java

Provides graceful Error message instead of Exception while run Telemetry on aarch64.
To make Telemetry works we need update `jnr_ffi` to latest version after get rid of Java 7 support.
We will need to remove that try/catch after.

Stub for Telemetry running on aarch64

---

dd-java-agent/iast/iast.gradle
dd-java-agent/iast/src/jmh/java/com/datadog/iast/taint/TaintedMapEmptyBenchmark.java
dd-java-agent/iast/src/jmh/java/com/datadog/iast/taint/TaintedMapGetsBenchmark.java
dd-java-agent/iast/src/jmh/java/com/datadog/iast/taint/TaintedMapPutsBenchmark.java
dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
dd-java-agent/iast/src/main/java/com/datadog/iast/IastRequestContext.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/Range.java
dd-java-agent/iast/src/main/java/com/datadog/iast/model/SourceType.java
dd-java-agent/iast/src/main/java/com/datadog/iast/taint/DefaultTaintedMap.java
dd-java-agent/iast/src/main/java/com/datadog/iast/taint/Ranges.java
dd-java-agent/iast/src/main/java/com/datadog/iast/taint/TaintedMap.java
dd-java-agent/iast/src/main/java/com/datadog/iast/taint/TaintedObject.java
dd-java-agent/iast/src/main/java/com/datadog/iast/taint/TaintedObjects.java
dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplOnConcatTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplOnParameterNameTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplOnParameterValueTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/model/RangeTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/model/SourceTypeTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/taint/HashCodeTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/taint/RangesTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/taint/TaintUtils.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/taint/TaintUtilsTest.groovy
dd-java-agent/iast/src/test/groovy/com/datadog/iast/taint/TaintedMapTest.groovy
internal-api/src/main/java/datadog/trace/api/iast/IastModule.java
utils/test-utils/src/main/java/datadog/trace/test/util/CircularBuffer.java

Add taint tracking API
Includes:
- A hash map implementation optimized to store tainted objets. This is a
weak identity hash map, with fixed capacity, some concurrency
guarantees (it can lose concurrent writes, but not throw), and
self-purging.
- Callbacks to taint HTTP parameter names and values (in taint tracking
jargon: sources), and propagate taints on string concatenation.
This is one of the main building blocks to do taint tracking for IAST:

Taint tracking API

---

dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/SqsClientTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/propagation/XRayHttpCodec.java
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpExtractorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpInjectorTest.groovy

As recently reported in #3861:
> Per [X-Ray documentation](https://docs.aws.amazon.com/general/latest/gr/xray.html#limits_xray), trace IDs are only accepted if they are from the last 7 days, as identified by their epoch timestamp, so this trace header is not valid. To fix this issue, the SDK just needs to generate a hex epoch timestamp with the current time

Populate epoch timestamp part of `X-Amzn-Trace-Id` tracing header

---

dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/Batch.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricKey.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AggregateMetricTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy
dd-trace-core/src/traceAgentTest/groovy/MetricsIntegrationTest.groovy

This PR improve the stats behavior by:
- Adding missing `synthetic` to the aggregation key,
- Support the `_dd.measured` custom tag to mark span as measured.
Measured spans will take part of stats like top level span.
Those changes improves the results of [Java tracer system tests](https://github.com/DataDog/system-tests/pull/504).
Synthetic span detection is based on `origin` value comparison.
The comparison I use calls `CharSequence.toString()`. I fear there might be unnecessary allocation behind it but I didn't think I can rely on `CharSequence.equals` according to the Javadoc:
> The result of comparing two objects that implement CharSequence is therefore, in general, undefined.
Let me know if there is a better solution for this comparison.

Improve tracer stats behavior

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/HelperInjectionTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Removes support for late injection of helper classes onto the boot-class-path. After this is merged any request to inject a helper class where the target class-loader is the boot-loader (ie. `null`) will result in a transformation exception in the logs and the relevant transformation will not be applied.
Note: no exception will leak out to the application, it's only the transfiormation that will be blocked.
For example. this is what happens when the `ShutdownHelper` fix is temporarily reverted:
```
[dd.trace 2022-09-30 11:37:38:035 +0100] [main] DEBUG datadog.trace.agent.tooling.AgentInstaller$TransformLoggingListener - Transformation failed - instrumentation.target.class=java.lang.Shutdown instrumentation.target.classloader=null
java.lang.UnsupportedOperationException: Cannot inject …
```

Remove HelperInjector.injectBootstrapClassLoader

---

.circleci/config.yml

Reintroduces xlarge images for jobs, because instrumentation, smoke and base tests are CPU bound on large images

allow xlarge images for some tests

---

dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/HashCodeTest.groovy

Increase the tolerance for hashcode distribution in `HashCodeTest`.
This test flaked in IBM 8.

Tune HashCodeTest to avoid flaky test

---

.circleci/collect_profiles.sh
.circleci/config.yml

Allows setting `profile: true` on a non-IBM8/non-ORACLE8 test job to collect a JFR
Diagnose test reliability/test problems

profile tests

---

gradle/dependencies.gradle

Bumping async-profiler lib version
To bring in J9 fixes

Bump async-profiler to DD-20221005

---

dd-smoke-tests/springboot-openliberty/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySmokeTest.groovy

Makes the openliberty smoke test lighter weight by not allocating huge strings (which need to be converted to UTF-8) over and over again
Reduce resource requirement for smoke tests so they can run faster => faster, more reliable CI
This is from a profile of just the test side of the openliberty smoke test:

allocate fewer large strings in openliberty test

---

.circleci/config.yml

Adds the `testJvm` setting to the `agent_integration_tests` job so the `bash` checks don't fail when it tries to run.
Failing on `master` https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/16664/workflows/72d70af2-4427-4f9a-899e-57d747ad2480/jobs/389440
Success triggered by dummy commit https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/16667/workflows/cbce97de-2379-49a3-8d6c-c7d483e1b9df/jobs/389496

Add testJvm for agent_integration_tests

---

dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfiler.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ControllerFactory.java
internal-api/src/main/java/datadog/trace/api/Platform.java

Disables the wallclock profiler for J9 by default
The wallclock profiler for J9 is rather useless as of now but can easily generate large amounts of data.
It makes sense not to have it on as default.

Disable wallclock profiling on J9 by default

---

dd-java-agent/instrumentation/hibernate/core-4.3/src/test/groovy/SpringJpaTest.groovy
dd-java-agent/instrumentation/hibernate/core-4.3/src/test/java/spring/hibernate/jpa/Customer.java
dd-java-agent/instrumentation/hibernate/core-4.3/src/test/java/spring/hibernate/jpa/CustomerRepository.java
dd-java-agent/instrumentation/hibernate/core-4.3/src/test/java/spring/hibernate/jpa/PersistenceConfig.java

Moves the hibernate specific JPA test support classes to a separate package.
The JPA related tests were using 'spring.jpa' package to scan for JPA configs/repos etc.
This could have lead to interference between Spring Core and Spring Hibernate tests when one would pick the others stuff by accident, resulting in flaky tests.

Prevent interference between tests using JPA

---

.circleci/config.yml

Uses the merge commit in the PR merge branch to find changed files. Does not depend on target branch. Also fails the build if the `git` commands fail.
PRs with a different base branch than `master` did not get a correct diff and failures of the `git` commands where silently swallowed.

Use the PR merge commit to do the diff for changed files

---

dd-smoke-tests/log-injection/src/test/groovy/datadog/smoketest/LogInjectionSmokeTest.groovy
dd-smoke-tests/osgi/src/test/groovy/datadog/smoketest/AbstractOSGiSmokeTest.groovy
dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy

Changes the log level for smoke tests to info
Some smoke tests are quite resource intensive but a most of the allocation in these cases come from debug logging e.g. for springboot-grpc:

don't log smoke tests at debug level

---

dd-java-agent/agent-iast/agent-iast.gradle
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/AdapterFactory.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/DDIdAdapter.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/VulnerabilityEncodingTest.groovy

* Added a test exercising serialization of null DDId.
* Extract adapter to top-level class.
* Exclude DDIdAdapter from code coverage thresholds (even after the test, it won't pass the method coverage requirements).
Avoid coverage errors in CI.

Improve test coverage for DDIdAdapter

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/FieldOutline.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/MethodOutline.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeOutline.java

likewise if there are no fields / methods / interfaces...

Reduce allocation when matching types with no annotations

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Fields.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/SnapshotProvider.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ReflectiveFieldValueResolver.java
dd-java-agent/agent-debugger/debugger-el/debugger-el.gradle
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/StaticValueRefResolver.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MethodProbeInstrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/el/ELIntegrationSanityTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/SnapshotSummaryTest.java
dd-java-agent/agent-debugger/src/test/java/datadog/trace/bootstrap/debugger/FieldExtractorTest.java
gradle/dependencies.gradle

The changes in this PR allow the debugger EL engine to evaluate early using only the runtime values (no cached snapshot is available at that time). The evaluation will happen before the rate limiting sampling can kick in, increasing the chance of capturing 'interesting' snapshots.
Change the order of EL evaluation and sampling to reduce the chance of missing interesting snapshots due to rate limiting.
The EL evaluation is possible only while the captured values were not 'frozen' - freezing a captured value will effectively serialize the Java instance it is pointing to to a JSON in order to prevent subsequent changes to that instance affecting the  previously captured data.
Since the value is represented as JSON only after freezing, evaluating EL against such value would be possible only …

Debugger EL evaluation before sampling

---

.circleci/collect_reports.sh
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/ProcessManager.groovy

IBM JVMs use the setting [here](https://www.ibm.com/docs/en/sdk-java-technology/8?topic=options-xdump) to determine where crash files are written to, so the smoke tests need to set command line args when the JVM is IBM. When e.g. smoke tests crash, this change is enough to get the javacore files uploaded, e.g. [here](https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/16834/workflows/3c3832bd-9bd6-42b9-8362-077d06559420/jobs/394752/artifacts)

Set IBM -Xdump arg to collect smoke test crash info

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/FieldOutline.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/MethodOutline.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeOutline.java

Since most type elements don't have any annotations, these lists remain empty for the duration of the cached type.
Delaying creation of the lists saves a few K during startup for spring-petclinic.

Type parsing: avoid creating annotation ArrayLists that will never get populated

---

.circleci/collect_reports.sh

Changes broken default behavior in `collect_reports.sh` that deleted reports instead of saving them.

Correct broken default behavior in collect_reports

---

.circleci/collect_profiles.sh
.circleci/collect_reports.sh
.circleci/config.yml

tars uploaded large files (coredumps, profiles etc.) see example [here](https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/16857/workflows/493a8288-d31f-453c-85e6-4a219e38bb3d/jobs/395323/artifacts)
reduces upload time and storage in circleci

compress and upload .trc and .dmp files for IBM JVMs, compress collected profiles

---

dd-java-agent/dd-java-agent.gradle
gradle/dependencies.gradle
telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java

Upgrades `jnr_unixsocket` and `jnr_ffi`
Removes [free after use security vulnerability](https://security.snyk.io/vuln/SNYK-JAVA-COMGITHUBJNR-1570422) in `jnr_posix` that is a dependency of `jnr_unixsocket`, and allows Telemtry to work on ARM since `aarch64` is now supported.

Upgrade jnr_unixsocket and jnr_ffi

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteUtils.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/BaseCallSiteTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteTransformerTest.groovy
dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/csi/CallSiteWithArraysExample.java

When the arity of a method forces CSI to duplicate parameters in the stack using an array, we have to take care of boxing/unboxing of the elements that will be inserted in the array. 
One condition was missing for when a parameter of the stack is of array type, causing those methods to fail.

Fix issue with array handling for boxing / unboxing in CSI

---

gradle/dependencies.gradle

^
The new release contains a fix preventing SEGFAULT due to mishandling of input arguments

Bump async-profiler to 20221010

---

dd-java-agent/instrumentation/jetty-common/jetty-common.gradle
dd-java-agent/instrumentation/jetty-common/src/main/java/datadog/trace/instrumentation/jetty/JettyBlockingHelper.java
dd-java-agent/instrumentation/jetty-common/src/test/groovy/datadog/trace/instrumentation/jetty/JettyBlockingHelperSpecification.groovy

Jetty replaced Response.complete() with Response.closeOutput() some time ago. See https://github.com/eclipse/jetty.project/commit/bacff75b311

jetty blocking: fix calling of old method

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/DebuggerIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java

Add Datadog Classloader as TypePool for resolving type coming from DD instrumentations.
Interactions with AppSec or Tracer instrumentation leading to VerifyError in some circumstances

Fix issue with other Datadog instrumentations

---

buildSrc/call-site-instrumentation-plugin/build.gradle.kts

Add byte buddy to test dependencis of the CSI plugin 
After upgrading CSI dynamic addvices bytebuddy is needed to run the tests of the plugin

Add bytebudy to deps of csi plugin

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/http/ClientIpAddressResolver.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecoratorTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/http/ClientIpAddressResolverSpecification.groovy

Now reports private IP addresses (if no public one is available neither in the headers nor as the peer address) and adds a tag when multiple headers are present. Adds also two ranges of IPv6 addresses that are to be considered private.

Bring client ip resolution in line with spec

---

dd-java-agent/instrumentation/twilio/src/test/groovy/test/TwilioClientTest.groovy

Changes the Twilio IDs in the tests to obviously fake ones, and adds a comment that they are fake.
Secret scanning alert found the keys. Their pedigree is unknown and it's better to switch them to these fake keys.

Use obviously fake Twilio IDs in tests

---

dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java

Simplifies the event checks in `OpenJdkController` and disables `jdk.ClassLoaderStatistics` on older JVMs
Prior to JDK15, `jdk.ClassLoaderStatistics` was expensive, but it was fixed in [JDK-8244733](https://bugs.openjdk.org/browse/JDK-8244733). The first LTS to support this event efficiently was JDK17, so disable the event before JDK17.

Disable `jdk.ClassLoaderStatistics` unless running on JDK17 or later

---

dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfiler.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

Adds a config option to enable/disable wallclock sample collapsing

Add config knob for collapsing wallclock samples

---

.github/workflows/add-assets-to-release.yaml

Gets the $VERSION (e.g "0.123.0") from the tag instead of the user supplied Release Name field and strips the leading 'v' automatically. Release Name will be populated automatically so the user should leave it empty when drafting the release. 
In the case that Release Name is populated however, if it does not match up with stripped $VERSION, the workflow will be forced to fail.
Currently the user must remove the 'v' from the tag like "v0.123.0" -> "0.123.0" and put this new value in the _Release Title_ field.  The value later populates $VERSION.  If the user does not strip the 'v', subsequent release steps fail.  
Currently [update-issues-on-release.yaml](https://github.com/DataDog/dd-trace-java/blob/master/.github/workflows/update-issues-on-release.yaml#:~:text=github.event.release.name) …

strip 'v' from version tag

---

telemetry/src/main/java/datadog/telemetry/RequestBuilderSupplier.java
telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java
telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy

JRN and RequestBuilder initialisation moved into separated thread to reduce startup overhead
Benchmarks:

Telemetry lazy loading

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy

On ASM_ACTIVATION, default to false if there is no payload.
We were expecting enable: false, but the value can also be not set.
At some point, we might want to just change the deserializer to guarantee that this is never null.

Fix ASM 1-click de-activation

---

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java

Enabled telemetry by default. 
To disable it explicitly - use env variable `DD_INSTRUMENTATION_TELEMETRY_ENABLED=false` or startup option `-Ddd.instrumentation.telemetry.enabled=false`

Telemetry enabled by default

---

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java

Enabled remote config by default.
To disable it explicitly - use env variable `DD_REMOTE_CONFIG_ENABLED=false` or startup option `-Ddd.remote_config.enabled=false`

Remote config enabled by default

---

.circleci/config.yml

Changes the amount of memory assigned to the Gradle Daemon
The Gradle Daemon garbage collects itself to death trying to build up the project structure. Example here https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/17157/workflows/edbac560-d6af-4eb4-b169-524e8a763efd/jobs/406167

Give the gradle daemon enough memory for our large project

---

dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfiler.java
dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/AsyncProfilerTracingContextTrackerFactory.java
dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/AsyncProfilerTracingContextTrackerFactoryTest.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
gradle/dependencies.gradle

Reuses the same config flag for tracing context enablement, and retires the old flag. No longer sends a command to async-profiler to enable context explicitly since the native side will soon be passive leaving dd-trace-java in control of whether context updates are made.

Upgrade async-profiler, simplify tracing context filtering

---

gradle/dependencies.gradle

Bumps async-profiler lib to [DD-20221020](https://github.com/DataDog/async-profiler/releases/tag/DD-20221020)

Bump async-profiler to 20221020

---

buildSrc/call-site-instrumentation-plugin/build.gradle.kts
buildSrc/src/test/groovy/CallSiteInstrumentationPluginTest.groovy
buildSrc/src/test/groovy/InstrumentPluginTest.groovy

Ensure the call site instrumentation plugin is compiled for JDK8 and the same for the plugin tests.
Gradle compiles the code and runs all the tests in the `buildSrc` folder, so any issue completely blocks the build process, in our case a wrong JDK was causing the problem due to the tests failing.

Ensure buildSrc can be tested with JDKs > 11

---

dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
gradle/dependencies.gradle

* Enables context tracking in all smoke tests, just in case it crashes something
* Adds a sanity check for embedded context in Datadog events whenever they are emitted in `ProfilingIntegrationTest`

add sanity check for embedded JFR event context, enable profiling context integration for all smoke tests

---

dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfiler.java
dd-java-agent/agent-profiling/profiling-async/src/test/java/com/datadog/profiling/async/AsyncProfilerRecordingTest.java
dd-java-agent/agent-profiling/profiling-async/src/test/java/com/datadog/profiling/async/AsyncProfilerTest.java

Make the async profiler support instantiation more resilient for unsupported envs

Do not throw exception on systems not supported by async-profiler

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfiler.java
dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfilerConfig.java
dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/ContextThreadFilter.java

By the time the rest of the profiler gets installed, there might have been a lot of tracing, so we need to install this listener earlier. This imposes constraints on the listener, which its current implementation meets (it doesn't matter when `AsyncProfiler` is created) but care needs to be taken not to introduce a dependency on JFR here in the future.

register ContextThreadListener earlier to capture all tracing interactions

---

dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/JfrProfilerSettings.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilerSettingsSupport.java

emit a profiler settings event with perf_events_paranoid setting

---

dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy

Fix IastSpringBootSmokeTest flakiness, wait for traces
This test occasionally flaked in CI with the following error:
```
Condition not satisfied:
foundEnabledTag
|
false
at datadog.smoketest.IastSpringBootSmokeTest.iast.enabled tag is present(IastSpringBootSmokeTest.groovy:96)
```
It seems the log is sometimes checked before the traces are written to it.

Fix IastSpringBootSmokeTest flakiness, wait for traces

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Default is `inactive`, but on empty string it was falling back to `false`.
* Spotted while testing system-test changes https://github.com/DataDog/system-tests/pull/565 where `DD_APPSEC_ENABLED` was expected to set the default, not `false`.
* We may want to fix other inconsistencies for empty values in system properties and environment variables everywhere.

Fix fallback for empty dd.appsec.enabled/DD_APPSEC_ENABLED

---

dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AsyncAfterTransmissionInterceptorCallingResponseHandlerInstrumentation.java

Adds missing helper classes to an instrumentation, this was noticed because of a large number of `IllegalAccessError`s picked up by exception profiling:
Modifying the `ThrowableInstrumentation` to print the stack trace was the only way to get the error message (should this be made available as setting?):
```
java.lang.IllegalAccessError: class software.amazon.awssdk.core.internal.http.async.AsyncAfterTransmissionInterceptorCallingResponseHandler tried to access field datadog.trace.instrumentation.aws.v2.TracingExecutionInterceptor.SPAN_ATTRIBUTE (software.amazon.awssdk.core.internal.http.async.AsyncAfterTransmissionInterceptorCallingResponseHandler and datadog.trace.instrumentation.aws.v2.TracingExecutionInterceptor are in unnamed module of loader 'app')
at …
```

add missing helper class names to avoid IllegalAccessErrors

---

dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AsyncAfterTransmissionInterceptorCallingResponseHandlerInstrumentation.java
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java

#4084 was the wrong fix for the problem, it was actually enough to just make the `SPAN_ATTRIBUTE` public (the helper classes were already added by the base class)

make SPAN_ATTRIBUTE public to avoid IllegalAccessError in AWS-SDK instrumentation

---

dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/exceptions/ExceptionProfiling.java
dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/exceptions/ExceptionSampleEvent.java

This adds the active span and local root span ID to exception sample events so they can be used to explain span latency.

add span context to exception samples

---

dd-java-agent/instrumentation/exception-profiling/src/main/java11/datadog/exceptions/instrumentation/ThrowableInstanceAdvice.java

This exception type is an abuse of `Throwable`, don't fill in their stack traces unless a very high level of tracking is configured by `-Dio.netty.leakDetection.level=LEVEL`, and pollute the exception profile. Matches on the suffix of the name because netty is so widely shaded.

ignore netty resource leak monitoring in exception profiling

---

remote-config/src/test/groovy/datadog/remoteconfig/PollerRequestFactoryTest.groovy

Avoid Config mock in PollerRequestFactoryTest.
Mocking Config here was producing some instrumentation failures in DDSpecification.
This test was introducing in https://github.com/DataDog/dd-trace-java/pull/4025 and apparently it works in CI (no failure in master for CI, and I get local failures).
The error I'm seeing:
```
Config will not be modifiable
java.lang.IllegalStateException: Could not install class file transformer
at net.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:11142)
at net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:11044)
at net.bytebuddy.agent.builder.AgentBuilder$installOn$4.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at …
```

Avoid Config mock in PollerRequestFactoryTest

---

remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java

If the agent has remote config enabled, the library discovers the endpoint, and then the agent is restarted with remote config disabled, we want to keep the logs quiet. We keep a debug-level message, but no warning or exception.

Do not log exceptions when remote config returns 404

---

communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java
remote-config/src/main/java/datadog/remoteconfig/PollerRequestFactory.java
remote-config/src/test/groovy/datadog/remoteconfig/PollerRequestFactoryTest.groovy

Make remote config quiet until endpoint is discovered
Also make some more initialization lazy.
Remote config poller has a lower polling interval than feature discovery. In the previous version, remote config polling every 5 seconds got too verbose until a remote config endpoint was discovered (which would never happened if the agent simply had no remote config enabled).
Example of log before this PR:
```
web_1    | [dd.trace 2022-10-21 11:18:21:216 +0000] [dd-remote-config] DEBUG datadog.remoteconfig.ConfigurationPoller - Failed to poll remote configuration from (no endpoint discovered yet)
web_1    | java.io.IOException: Endpoint has not been discovered yet
web_1    | 	at datadog.remoteconfig.ConfigurationPoller.fetchConfiguration(ConfigurationPoller.java:201)
web_1    | 	at …
```

Make remote config quiet until endpoint is discovered

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java

WAF loads lazily to reduce startup time.
Based on numbers the `telemetry`, `remote-config`, `appsec` gives **+2.14% of overhead**.

WAF lazy loading

---

communication/src/test/groovy/datadog/communication/monitor/DDAgentStatsDClientTest.groovy
dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy
gradle/dependencies.gradle

Upgrades dogstatsd, which has a significant performance improvement (see https://github.com/DataDog/java-dogstatsd-client/pull/194)

upgrade to dogstatsd v4.1.0

---

.circleci/config.yml
dd-smoke-tests/dd-smoke-tests.gradle

The smoke tests are currently CPU bound despite having a lot of RAM headroom, and circleci doesn't offer a way to trade RAM for vCPUs https://circleci.com/docs/configuration-reference/#docker-execution-environment so the only option is to double the size of the image for now.

larger smoke tests image

---

dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedMapTest.groovy

These are flaky, especially under high load, and in OpenJ9.
The approach to test this class needs to change significantly. This is a temporary measure.

Tune TaintedMapTest thresholds

---

dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDIntakeWriterCombinedTest.groovy
internal-api/src/test/groovy/datadog/trace/util/ProcessSupervisorTest.groovy

Makes assertion work inside `eventually` blocks
Assertions without the explicit `assert` keyword inside the `eventually` block will always pass
N/A

Fix assertions inside `eventually` block

---

dd-java-agent/instrumentation/graphql-java-14.0/src/main/java8/datadog/trace/instrumentation/graphqljava/GraphQLInstrumentation.java
dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLInstallationTest.groovy

When GraphQLInstrumentation#install is called with a ChainedInstrumentation object the resulting Instrumentation contains duplicates (the individual Instrumentation objects contained within the ChainedInstrumentation as well as the ChainedInstrumentation itself). This fixes that.
Open this PR from the original repository branch to be able run the entire test suit.
Original fix #4088 fails to run system-tests with `DD_API_KEY is missing in env, please add it.` because the PR is open from a fork repository.

Fix duplicate GraphQL instrumentation bug

---

dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java
dd-smoke-tests/profiling-integration-tests/profiling-integration-tests.gradle
dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/CodeHotspotsApplication.java
dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/ParallelProcessing.java
dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/QueueProcessing.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/DisableOnJ9Condition.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/DisabledOnJ9.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/SmokeTestUtils.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

This PR is adding smoke tests for the accepted coverage percentage for various types of applications.
For this there are several simulations - a batch application, a concurrent application and reactive/async application. Each of these types of applications has a different expected minimal coverage, due to the nature of the workload, and the smoke tests are asserting it.
The idea is to have a 'no-dependency' tests allowing to verify the basic assertions about the code hotspots coverage.
This is not supposed to exhaustively cover the problem space but rather give us specific numbers we can use when talking about how precisely and how extensively code hotspots are describing the profiled app.
The test may turn out to be flaky although the limits were set based on the values we are getting …

Profiler context smoke tests

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/agent-crashtracking/agent-crashtracking.gradle
dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/ScriptInitializer.java
dd-java-agent/agent-crashtracking/src/main/resources/com/datadog/crashtracking/upload_crash.bat
dd-java-agent/agent-crashtracking/src/main/resources/com/datadog/crashtracking/upload_crash.sh
dd-java-agent/agent-crashtracking/src/test/java/com/datadog/crashtracking/ScriptInitializerTest.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java

When `-XX:OnError=<action>` JVM arg is specified and `<action>` is a script file named `dd_crash_uploader.sh` or `dd_crash_uploader.bat` (for windows), regardless of in which directory that script should be located, the action script will be 'automagically' generated at the agent startup.
In case of a failure to generate the script (non-accessible location, already existing etc.) this step will be just skipped without affecting the rest of the agent startup.
Although we are able to pick up the crash log file and upload it to our intake, the configuration itself is pretty involved. One needs to create a script to redirect the on-crash action to our `AgentCLI` action, set it up to pick up the crash log file (which can be located in some other place using `-XX:ErrorLogFile` JVM argument) and …

"Automagically" create dd_crash_uploader script for crash tracking.

---

communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java

Found during testing. If a feature discovery call got no `statsd_port` in the response, we logged a long NullPointerException.
This PR makes the handling of missing port gentler on logging.
Exception with enabled telemetry and disabled tracer:

Less verbose error on missing statsd_port

---

.github/workflows/add-assets-to-release.yaml

Go back to actions/github-script@v6.
Current version is incompatible with the script.
* This is a follow up to #4048, which reverted the action to an incompatible version.
* We'll need to add `actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0` to the repository allowlist.
* **Not tested.**

Go back to actions/github-script@v6

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/JsonSnapshotSerializer.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/DebuggerSink.java
internal-api/src/main/java/datadog/trace/util/TagsHelper.java
internal-api/src/test/java/datadog/trace/util/TagsHelperTest.java

using the tracer global tags that includes DD_TAGS we can add custom tags to the snapshot or probe statuses.
This is useful for Source Code Integration which requires tags for commit sha and repository

Add DD_TAGS tags into snapshot/probe status tags

---

dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java

Disable codehotspots asserts (for now)

temporarily disable CodeHotspots asserts

---

internal-api/src/main/java/datadog/trace/api/ConfigCollector.java
telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java

ConfigCollector.put could be called concurrently from Config/ConfigProvider concurrently with Telemetry iterating it. Changed it to a ConcurrentHashMap.
Also call go `Config.get()` before starting telemetry to ensure it is initialized at that point.
Reported exception:
```
Uncaught exception in dd-telemetry [exception:java.util.ConcurrentModificationException. at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756) at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788) at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:786) at datadog.telemetry.TelemetryServiceImpl.addConfiguration(TelemetryServiceImpl.java:65) at datadog.telemetry.TelemetryRunnable.run(TelemetryRunnable.java:48) at …
```

Fix concurrency issue in telemetry initialization

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/Configuration.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationComparerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java

Remove OpsConfiguration from Configuration
With RemoveConfig this is no longer used.
It was used for configuring the library behavior from the backend (polling interval)

Remove OpsConfiguration from Configuration

---

dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
dd-trace-core/src/test/groovy/datadog/trace/core/datastreams/DefaultPathwayContextTest.groovy

This PR adds a simple loop protection to the PathwayContext, aiming to detect and resolve situations when two identical operations become logically nested. 
A simple example:
You have a Google PubSub listener, which receives a message and then pushes it to two separate gRPC destinations, sequentially. All 3 operations will share the same context, and each time you're calling setCheckpoint, your PathwayContext will get modified. As the result, the second gRPC outgoing call will consider the first one its parent, creating a loop.

Loop protection for PathwayContext

---

dd-java-agent/instrumentation/liberty-20/src/main/java/datadog/trace/instrumentation/liberty20/RequestFinishInstrumentation.java
dd-java-agent/instrumentation/liberty-20/src/main/java/datadog/trace/instrumentation/liberty20/ResponseFinishInstrumentation.java

`SRTServletResponse#getAttribute()` will throw NPE if called after response has been closed.
This resulted in a logged exception (at debug logging level):
```
[dd.trace 2022-11-03 22:41:09:340 +0100] [Default Executor-thread-31] DEBUG datadog.trace.bootstrap.ExceptionLogger - Failed to handle exception in instrumentation for com.ibm.ws.webcontainer.srt.SRTServ
letRequest
at com.ibm.ws.webcontainer.srt.SRTServletRequest$SRTServletRequestHelper.access$300(SRTServletRequest.java:3424)
at com.ibm.ws.webcontainer.srt.SRTServletRequest.getAttribute(SRTServletRequest.java:402)
at com.ibm.ws.webcontainer.srt.SRTServletRequest.finish(SRTServletRequest.java:2781)
at com.ibm.ws.webcontainer31.osgi.srt.SRTConnectionContext31.finishConnection(SRTConnectionContext31.java:2 …
```

Fix logged NullPointerException in OpenLiberty on getAttribute

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java

Some OpenJ9-based JVMs (e.g. old IBM SDK 8.0) have issues with AppSec, so we're disabling it by default. This will prevent issues when enabling remote config by default, and it will also disable 1-click activation of AppSec for OpenJ9.
Also disable on architectures other than x86 and amd64, since PowerWAF is not supported anywhere else yet. So trying to enable it later is pointless.

AppSec default to false on OpenJ9 and non supported archs

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
telemetry/src/main/java/datadog/telemetry/dependency/LocationsCollectingTransformer.java
telemetry/src/test/groovy/datadog/telemetry/TelemetrySystemSpecification.groovy

Enables telemetry by default (take 2). Changes tests for Telemetry to assume it's on by default.
In 0.113.0 we changed the default of the telemetry setting in Config to true, but that's not enough, as it needs to be updated in `Agent` too.

Enable telemetry by default

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-smoke-tests/appsec/src/main/groovy/datadog/smoketest/appsec/AbstractAppSecServerSmokeTest.groovy
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractTestAgentSmokeTest.groovy

Enable remote config by default.
Also:
* Make sure that smoke tests for remote activation run on gradle test task.
* Tweak tests to avoid explicit remote config enablement.
In 0.113.0 we changed the default of the telemetry setting in Config to true, but that's not enough, as it needs to be updated in `Agent` too.

Enable remote config by default

---

telemetry/src/main/java/datadog/telemetry/HostInfo.java

Telemetry failing to read a file because of a SecurityManager led to Telemetry thread ending with an uncaught exception.
Test case:
```
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;
import org.xml.sax.SAXNotRecognizedException;
public class Bug6359330 {
public static void main(String[] args) throws Throwable {
System.setSecurityManager(new SecurityManager());
try {
SAXParserFactory spf = SAXParserFactory.newInstance();
spf.setNamespaceAware(true);
spf.setValidating(true);
SAXParser sp = spf.newSAXParser();
// The following line shouldn't throw a
// java.security.AccessControlException.
sp.setProperty("foo", "bar");
} catch (SAXNotRecognizedException e) {
// Ignore this expected exception.
}
}
}
```
Exception:
```
[dd.trace 2022-11-07 09:19:14:898 +0100] …
```

Catch AccessControlException in telemetry HostInfo

---

telemetry/src/main/java/datadog/telemetry/HostInfo.java
telemetry/src/main/java/datadog/telemetry/dependency/LocationsCollectingTransformer.java
telemetry/src/test/groovy/datadog/telemetry/dependency/LocationsCollectingTransformerSpecification.groovy

It does not report tracer internal dependencies in telemetry
Currently internal dependencies were reported as if they were from the application

Exclude tracer deps in telemetry

---

utils/container-utils/src/main/java/datadog/common/container/ContainerInfo.java
utils/container-utils/src/test/groovy/ContainerInfoTest.groovy

This is the same fix as applied to other languages:
https://github.com/DataDog/dd-trace-go/pull/1549/files
https://github.com/DataDog/dd-trace-py/pull/4405/files

Add support for PCF containers

---

dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Add an option to exclude rabbitMQ routing key from the publisher's resource name. This can be used to reduce the cardinality of generated spans' resources.
The feature is driven by the system property  `dd.trace.rabbit.include.routingkey.in.resource` (or env `DD_TRACE_RABBIT_INCLUDE_ROUTINGKEY_IN_RESOURCE`) which is enabled by default (it's the current behaviour).
Setting it to false will exclude the routingKey to be part of the span resource name
Being a breaking change, the option is disabled by default

add option to exclude rabbitmq routingKey from resource name

---

dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java

Fix the error message for MacOS.
The instruction to fix the error is wrong.

fix: Fix error message for MacOS

---

lib-injection/src/main/docker/Dockerfile

Adds a non-root user to the `dd-lib-java-init` image
Resolves https://github.com/DataDog/dd-trace-java/issues/4181
In Kubernetes Pod definitions where the following configuration is used, the init-container created from this image fails to start
```
securityContext:
runAsNonRoot: true
```

Add non-root user to the `dd-lib-java-init` image

---

dd-java-agent/dd-java-agent.gradle
dd-trace-ot/dd-trace-ot.gradle

This PR removes Maven, Proguard configurations and kotlin module files from shaded `dd-trace-ot` and `dd-java-agent` artifacts.
Asked by @bantonsson for `project/java-8`.
Here is the difference of included resources (left = before patch / right = after patch):
```diff
./META-INF							 ./META-INF
./META-INF/MANIFEST.MF						 ./META-INF/MANIFEST.MF
./META-INF/moshi.kotlin_module				      <
./META-INF/NOTICE						 ./META-INF/NOTICE
./META-INF/proguard					      <
./META-INF/proguard/okhttp3.pro			      <
./META-INF/proguard/moshi.pro				      <
./META-INF/services						 ./META-INF/services
./META-INF/services/io.opentracing.contrib.tracerresolver.Tr	 ./META-INF/services/io.opentracing.contrib.tracerresolver.Tr
```
```diff
./iast/META-INF						 ./iast/META-INF
./iast/META-INF/MANIFEST.MF …
```

Clean up shaded resources  

---

dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfiler.java
dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfilerConfig.java
dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/ContextThreadFilter.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/SmokeTestUtils.java
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

* Disable wallclock profiler by default, which we are less confident in than the CPU profiler. This allows us to GA the CPU profiler without risking users inadvertently using the wallclock profiler.
* When the wallclock profiler is enabled, we will always collapse samples and will always filter threads, so these options are removed. If users disabled these features very large profiles full of irrelevant samples would be produced.
* Enable tracing context by default, this means that whenever async-profiler is used, the profile will contain labeled events which already drastically improves code-hotspots.

simplify async-profiler config flags

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/checkpoints/TimelineCheckpointer.groovy
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java
dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ScopeEventTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
internal-api/build.gradle
internal-api/src/main/java/datadog/trace/api/Checkpointer.java
internal-api/src/main/java/datadog/trace/api/EndpointCheckpointer.java
internal-api/src/main/java/datadog/trace/api/SamplingCheckpointer.java
internal-api/src/main/java/datadog/trace/api/SpanCheckpointer.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
internal-api/src/test/groovy/datadog/trace/api/SamplingCheckpointerTest.groovy

* Always emit `EndpointEvent`s, regardless of whether there are any checkpoints, so that it can be used in conjunction with profile events labelled by async-profiler
* Decouple from `Checkpointer` so the latter can be deleted
* Deprecate everything to do with `Checkpointer` for removal

decouple endpoint events from checkpoints

---

dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/AsyncProfilerScopeListener.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java

Currently the `spanId` and `rootSpanId` fields are transposed, this fixes it and adds a check to detect this.

Fix profiler event labeling

---

dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java

mark all endpoints as sampled when async-profiler is enabled

---

.circleci/config.yml
dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java

Catch `UnsatisfiedLinkError` on `Class.forName("sun.management.ManagementFactoryHelper")`.
Previous code caught `ReflectiveOperationException`, which seems to be ok for IBM SDK 8.0, but fails on IBM Semeru Runtime 8.
This can be tested with:
```
JAVA_IBM8_HOME=<path to semeru> ./gradlew :dd-java-agent:test -PtestJvm=IBM8 --tests "datadog.trace.agent.LogLevelTest" -i
```
Without this PR, it failed with:
```
OUTPUT> Could not get bootstrap jar from code source, using -javaagent arg
ERROR> ERROR datadog.trace.bootstrap.AgentBootstrap
ERROR> java.lang.UnsatisfiedLinkError: sun/management/VMManagementImpl.getVersion0()Ljava/lang/String;
ERROR>      at sun.management.VMManagementImpl.<clinit>(VMManagementImpl.java:64)
ERROR>      at sun.management.ManagementFactoryHelper.<clinit>(ManagementFacto …
```

Fix agent bootstrap on IBM Semeru Runtime 8

---

dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java
dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ProfilingSystemTest.java

Reduce user confusion, add polish.

Improve error message when using oracle jdk 8 w/o commercial features unlocked

---

dd-java-agent/instrumentation/datastax-cassandra-3/build.gradle

This should fix the failures seen under SEMERU8 on Circle-CI

Upgrade jamm to fix NumberFormatException when running Cassandra under openj9

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java

Adds support for the older `ConnectionJDBC2` class from JTDS 1.2

Add support for JTDS 1.2 connections

---

dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedMapTest.groovy

This is particularly flaky on OpenJ9, presumably because of its default GC policy.
When we get to review this test case, we'll need to revisit what and how we want to test here.

Ignore TaintedMapTest case on J9

---

dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
dd-java-agent/src/test/java/jvmbootstraptest/LogManagerSetter.java
internal-api/src/main/java/datadog/trace/api/Platform.java

This class runs isolated from the tracer code, so it can't re-use Platform. It's important to have the same check in both places so their expectations about delayed startup match.
Normally these values are identical, however for the recent Semeru builds 'java.vendor' is 'IBM Corporation' while 'java.vm.vendor' is 'Eclipse OpenJ9' leading to inconsistent expectations.

LogManagerSetter should check 'java.vm.vendor', not 'java.vendor' to match Platform check

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/SnapshotProvider.java

rate limiting is applied at snapshot creation time only if no condition is defined, and rate limiting is applied at commit time only if a condition is defined.
Having the rate limiting only at commit time makes the serialization cost paid for all snapshots even if they are dropped in the end

Modify rate limit regarding probe conditions

---

README.md
SECURITY.md
SUPPORT.md

This PR tries to make the GitHub project a little more welcoming.
Compared to the other tracers README ([.Net](https://github.com/DataDog/dd-trace-dotnet), [JavaScript](https://github.com/DataDog/dd-trace-js), [PHP](https://github.com/DataDog/dd-trace-php), [Python](https://github.com/DataDog/dd-trace-py) and [C++](https://github.com/DataDog/dd-trace-cpp)), our really feels minimal.
As the v1 is coming, I thought it might be the right time to upgrade it before users come back to check latest changes, migration guide, bug reports…
This PR is mainly a proposal.
As a non native english, it might worth it to review and update its content to fit the product vision.
I encourage you to add commits to the PR 🙏

Update the README and add SECURITY and SUPPORT pages

---

CONTRIBUTING.md

Adds a note about installing JDK8 on arm-based MacOS and a troubleshooting section for the "too many open files" error.
Document the issues I've found so far trying to setup my dev environment.

Improve CONTRIBUTING docs

---

dd-java-agent/build.gradle
dd-java-agent/instrumentation/build.gradle

Reverts the third party dependency shading in #4046 and excludes a vertx stub project so those classes are not packaged with the final `dd-java-agent.jar`
The relocation inadvertently moved some instrumentations so they targeted the wrong classes and some helper classes to the wrong package so they lost access to some classes.

Don't shade third party dependencies for now

---

dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy

This reverts commit 1e1592c4e9d492a96017a74e87a1267146cd98c4.
Should have happened together with #4246
Why did this not run on CI for that PR? There is something broken with the short circuit things!

Revert "fix: Fix agent shading specification"

---

buildSrc/build.gradle.kts
buildSrc/src/test/groovy/InstrumentPluginTest.groovy
gradle/dependencies.gradle

https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.18
* Allow writing to field from enter `Advice` in constructor, as byte code allows it.
* Refactor Android plugin processor to avoid skipping local classes.
* Improve staleness filter for Maven plugin.
* Fix incorrect resolution of custom bound invokedynamic values in `Advice`.

byte-buddy 1.12.18

---

buildSrc/src/main/groovy/MuzzlePlugin.groovy
dd-java-agent/instrumentation/spring-data-1.8/build.gradle
dd-java-agent/instrumentation/spring-jms-3.1/build.gradle
dd-java-agent/instrumentation/spring-webflux-5/build.gradle

We need to lock `latestDepTestImplementation` to 5.+, as 6.x targets Java 17

Lock down spring-framework versions

---

dd-trace-ot/build.gradle

I added exclusions to cover all the packages in `dd-trace-api` as well as those in the original `dd-trace-ot`.
Without this change subpackages like `datadog.trace.api.interceptor` are shaded when they should be left untouched.

Fix shading of dd-trace-ot to leave all public API packages untouched

---

dd-java-agent/instrumentation/spring-webmvc-3.1/build.gradle

Update muzzle to reflect this and temporarily disable 'assertInverse' while we clean-up muzzle references to be consistent

spring-webmvc-3.1 integration is not compatible with spring-webmvc-6.0.0

---

dd-smoke-tests/opentracing/src/main/java/datadog/smoketest/opentracing/ApiVerification.java
dd-smoke-tests/opentracing/src/main/java/datadog/smoketest/opentracing/OTWithAgentApplication.java
dd-smoke-tests/opentracing/src/main/java/datadog/smoketest/opentracing/OTWithoutAgentApplication.java

Adds a simple sanity check of the `TraceInterceptor` API to the OpenTracing smoke test that uses `dd-trace-ot`.
Verify that shading and relocation doesn't move the public classes.

Add dd-api sanity check to dd-trace-ot smoke test

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/DDElementMatchers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/HierarchyMatchers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGradlePlugin.java
dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java
dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/ApacheHttpClientInstrumentation.java
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSHttpClientInstrumentation.java
dd-java-agent/instrumentation/ratpack-1.5/src/main/java/datadog/trace/instrumentation/ratpack/ServerErrorHandlerInstrumentation.java
dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/HandlerAdapterInstrumentation.java
dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/RouterFunctionInstrumentation.java
dd-java-agent/instrumentation/twilio/src/main/java/datadog/trace/instrumentation/twilio/TwilioAsyncInstrumentation.java
dd-java-agent/instrumentation/twilio/src/main/java/datadog/trace/instrumentation/twilio/TwilioSyncInstrumentation.java
gradle/forbiddenApiFilters/main.txt

This is so we can optimize them - this PR also removes a few unnecessary abstract method checks
(because only non-abstract methods declared on each matched class can have advice applied)

Move abstract checks to hierarchy matchers

---

dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/AbstractServletInputStreamWrapper.java
dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/BufferedReaderWrapper.java
dd-java-agent/instrumentation/servlet/request-2/build.gradle
dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2ResponseStatusInstrumentation.java
dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/ServletInputStreamWrapper.java
dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/ServletRequestBodyInstrumentation.java
dd-java-agent/instrumentation/servlet/request-2/src/test/groovy/WrapperForkedTest.groovy
dd-java-agent/instrumentation/servlet/request-3/build.gradle
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/AsyncContextInstrumentation.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet31InputStreamWrapper.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet31RequestBodyInstrumentation.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Instrumentation.java

Takes advantage of recent muzzle changes that let you specify different directives for instrumentations in the same module. 
The `ServletInputStreamWrapper` located under the `request-2` module covers both servlet 2.x and 3.0.x
A new `Servlet31InputStreamWrapper` is located under the `request-3` module and covers the additional methods introduced in servlet 3.1.x. A class-loader check for `javax.servlet.ReadListener`, a new type used in one of the methods added in 3.1, makes sure that at most one of these request-body instrumentations applies to a given class-loader.
Most of the low-level wrapping of `ServletInputStream` has been moved to `servlet-common` to reduce duplication.
This PR also skips the `javax.servlet.ServletRequestWrapper` / `javax.servlet.http.HttpServletRequestWrapper` …

Replace run-time patching of ServletInputStreamWrapper with build-time equivalent

---

.circleci/config.yml

This is more robust than #4256 or #4257 - just run these test suites as part of the base job.

remove exclusions of IAST, profiling, debugger tests from base test job

---

dd-java-agent/agent-profiling/profiling-async/build.gradle

Excludes one-liner plumbing code now included in the base job which runs jacoco

add jacoco excludes

---

dd-java-agent/instrumentation/opentelemetry/src/main/java/datadog/trace/instrumentation/opentelemetry/OtelSpan.java
dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTSpan.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTSpan.java
dd-trace-api/build.gradle
dd-trace-api/src/main/java/datadog/trace/api/interceptor/MutableSpan.java
dd-trace-ot/src/main/java/datadog/opentracing/OTSpan.java

This pushes `AgentSpan.getTag` up to `MutableSpan` so that it can be used from `TraceInterceptor`s. Otherwise, the user has to take a copy of the tags to check a tag value, which is inefficient.

move `AgentSpan.getTag` up to `MutableSpan` for more efficient `TraceInterceptor`s

---

.circleci/config.yml

Fixes build spec error introduced in #4271

skip profiling tests to make sure we don't try to use JFR on J9

---

internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/AppVeyorInfo.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/BitriseInfo.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/BuddyInfo.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/CIProviderInfo.java
internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/ci/BuddyInfoTest.groovy
internal-api/src/test/resources/ci/appveyor.json
internal-api/src/test/resources/ci/bitrise.json
internal-api/src/test/resources/ci/buddy.json

* On Bitrise, tag the commit author and commiter by reading the env vars.
* On AppVeyor, read both the body and subject of the commit message, which come in separate env vars.
* Add support for Buddy CI.

[CI] Add support for Buddy CI and improve other providers

---

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java

This means that any work done between `receive` requests when polling is associated with the most recent `receive` request, just like we do for JMS/Kafka/RabbitMQ.
I also bumped the keep-alive timeout for iteration/polling scopes to cover the maximum long polling wait time for SQS.

Use closePrevious/activateNext for SQS receive polling

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ClassLoaderMatchers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java

This matches the current expectation that agent installation is single-threaded
which lets us keep the installer/builder code simple while still allowing for parallel
MuzzleVersionScan tasks in the same JVM.

Ensure that only one muzzle task is building instrumenters at a given time

---

dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/ContextualEvent.java
dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/directallocation/DirectAllocationProfiling.java
dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/directallocation/DirectAllocationSampleEvent.java
dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/exceptions/ExceptionProfiling.java
dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/exceptions/ExceptionSampleEvent.java
dd-java-agent/instrumentation/java-directbytebuffer/src/test/groovy/DirectAllocationTrackingTest.groovy

Puts the context fields back on the exception sample events and makes sure they are present on direct allocation samples. This was broken by #4283

Fix contextual profiling events

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDRediscoveryStrategy.java
dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
dd-smoke-tests/custom-systemloader/build.gradle
dd-smoke-tests/custom-systemloader/src/main/java/datadog/smoketest/systemloader/TestHelper.java
dd-smoke-tests/custom-systemloader/src/main/java/datadog/smoketest/systemloader/TestLoader.java
dd-smoke-tests/custom-systemloader/src/main/java/sample/app/App.java
dd-smoke-tests/custom-systemloader/src/main/java/sample/app/Resource.java
dd-smoke-tests/custom-systemloader/src/test/groovy/datadog/smoketest/CustomSystemLoaderSmokeTest.groovy
settings.gradle

When the Java tracer is installed it looks at classes that have already been loaded into the JVM so it can re-transform them. It does this in batches, because re-transforming might bring in additional classes. This stops when there are no more loaded classes to be re-transformed.
One of the re-transformations we need to do is make sure custom class-loaders delegate to the boot-class-path for key tracer types. If we're not able to do this then the class-loader will fail the delegation check in `ClassLoaderMatchers` and it will be marked as skipped from that point onwards. This means that anything loaded by that class-loader will be ignored by the Java tracer.
If a user specifies a custom system class-loader with `-Djava.system.class.loader=<class-name>` then it's possible for that …

Retransform class-loader types before transforming any types loaded by them

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/FieldExtractor.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Fields.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/el/ELIntegrationSanityTest.java
dd-java-agent/agent-debugger/src/test/java/datadog/trace/bootstrap/debugger/FieldExtractorTest.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot18.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/sink/snapshotCapturedValueRegex.txt

Respect max field count starting from the leaf up to the root. if max field count is reached during parent traversal, we stop in the middle.
Exception captured was not collecting relevant data as the exception is message is defined in `Throwable` class.

Add parent field support collecting fields

---

dd-java-agent/agent-iast/build.gradle
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastModuleImpl.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/AdapterFactory.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/VulnerabilityTypeAdapter.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/IastModuleImplCommandInjectionTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/RangesTest.groovy
dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/ProcessBuilderCallSite.java
dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/RuntimeCallSite.java
dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/ProcessBuilderCallSiteTest.groovy
dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/RuntimeCallSiteTest.groovy
dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestProcessBuilderSuite.java
dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestRuntimeSuite.java
dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
internal-api/src/main/java/datadog/trace/api/iast/IastModule.java
internal-api/src/main/java/datadog/trace/api/iast/InstrumentationBridge.java
internal-api/src/test/groovy/datadog/trace/api/iast/InstrumentationBridgeTest.groovy

Add support for command injection detection by instrumenting calls to `Runtime.exec(...)` and `ProcessBuilder.start()`

Command Injection detection

---

dd-java-agent/instrumentation/rabbitmq-amqp-2.7/build.gradle
dd-java-agent/instrumentation/spring-rabbit/build.gradle

Limit Spring AMQP versions to avoid Spring 6 that requires Java 17

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastModuleImpl.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/IastModuleFindValidPackageForVulnerability.groovy
dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog.trace.instrumentation.iastinstrumenter/iast_exclusion.trie
dd-java-agent/instrumentation/iast-instrumenter/src/test/groovy/IastExclusionTrieTest.groovy

Filter out from stack classes that matches the IAST exclusion trie
Filter out frameworks (e.g. Spring) from vulnerability stack
Add a new value to IAST exclusion trie to manage all combinations
Keep a last resort fallback (e.g. if all frames are filtered, keep the first non-DD frame

Refine stacktrace filtering

---

communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
communication/src/test/groovy/datadog/communication/ddagent/DDAgentFeaturesDiscoveryTest.groovy
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/datastreams/MockFeaturesDiscovery.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsCheckpointer.java

* ~Separate feature discovery instance creation from actual discovery.~
* Allow forced discovery (`discovery()`) for cases where we want to force discovery, such as detecting an agent downgrade or config change (e.g. receiving a 404 error on a known endpoint).
* For other cases, use `discoveryIfOld()`. Which will only run discovery if it has not been done in a while.
* Synchronize discovery to debounce requests.
We were doing some ugly hacks in remote config to ensure we didn't send extra feature discovery requests. As we extend this usage to telemetry, we saw ourselves doing the same hack again. Previous discussion is available at https://github.com/DataDog/dd-trace-java/pull/4042#discussion_r998163980
* This PR does not address resetting `dataStreamsEndpoint`, which was missing from …

Avoid redundant feature discovery requests

---

dd-java-agent/instrumentation/jetty-11/build.gradle
dd-java-agent/instrumentation/jetty-11/src/main/java11/datadog/trace/instrumentation/jetty11/SetContextPathAdvice.java
dd-java-agent/instrumentation/jetty-11/src/test/groovy/Jetty11Test.groovy

Usually, servlet instrumentations are setting the tag servlet.context and servlet.path.
When setting servlet.context some interceptors are triggered in order to also set the service name.
By debugging it turns out that:
1. `contextPath` is not the contextPath but contains the concatenation of contextPath + servlet request URI
2. servlet path was missing
This PR aims fixing this behaviour and the test case supports it.
I also tested with a jetty sample the different behaviour. It's a simple war deploying a servlet with a context path `/test` .
Without it looks like:
And with this PR is now showing more coherent information:

jetty11: fix servletpath and context path instrumentations

---

dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

Fixes a copy-paste caused incorrect config key

Fix the config key for enabled profiling events

---

telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java
telemetry/src/test/groovy/datadog/telemetry/TelemetryRunnableSpecification.groovy

* Absent telemetry endpoint (error 404) will only log to debug, and drop remaining messages in the telemetry iteration.
* IO errors will log a warning with the exception message, not the full stacktrace.
* Fixed telemetry interval to honor the default (60 seconds), rather than capping it at 10 seconds.
See https://github.com/DataDog/dd-trace-java/issues/4203
When telemetry was disabled in the agent, we were spamming logs with warnings.
* A more comprehensive solution will be merged soon: https://github.com/DataDog/dd-trace-java/pull/4289 (this PR stems from that work, thanks @ValentinZakharov)
* This PR takes a modest approach to just mitigate the ongoing issues with agents with telemetry disabled (or old agents).
After this PR, starting with an agent that does not support telemetry, then …

Handle telemetry errors gracefully

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/SnapshotProvider.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/SnapshotSummaryBuilder.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/SummaryBuilder.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/test/java/datadog/trace/bootstrap/debugger/SnapshotSummaryTest.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/ValueScript.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/LogMessageTemplateSummaryBuilder.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Instrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/SnapshotInstrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SnapshotProbe.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/LogProbeTest.java

Reuse snapshot instrumentation but with custom summary builder allowing to generate a message as log.
Variables are resolved reusing ValueScript class.
generate log line for log probes
Right now, logs will generate the same data than regular snapshots, but we will remove that later to just the data required for filling the template variable.
Error during evaluation will be also reported  in the snapshot in a later PR

Implement log probe instrumentation

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategy.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/SharedTypePools.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/TypeInfoCache.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypePoolFacade.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java

Periodically resets the type-resolver state by clearing its shared type-pools.
Type transformations happen mainly at startup. By clearing the type-pools at a long enough interval after start we can reduce long-term memory overhead without impacting performance. The type-pools continue to be cleared at the same interval in case further types are transformed over the life of the application.
Defaults to every 5 minutes

Add scheduled task to clear the resolver's type pools

---

dd-smoke-tests/profiling-integration-tests/build.gradle
dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/NativeLibrariesApplication.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java

Start adding smoke test coverage for simple applications using native libraries to uncover async-profiler native library issues.
Libraries tested so far include basic usage of:
* lz4
* xxhash
* snappy

add some smoke tests for native library usage

---

dd-java-agent/instrumentation/tomcat-5.5/build.gradle
dd-java-agent/instrumentation/tomcat-5.5/src/latestDepTest/groovy/AbstractServletTest.groovy
dd-java-agent/instrumentation/tomcat-5.5/src/latestDepTest/groovy/TomcatServletTest.groovy
dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/ExtractAdapter.java

Starting from Tomcat 10.1.X `MessageBytes` class has been refactored and now caches string representation when calling toString(). 
We're calling toString on `MimeHeaders` before the service method  causing changing byte buffers to string.  When the postParse is called, the request is parsed starting from the content of the mime headers.
This is corrupting the request processing making unusable the agent on spring boot 3 or tomcat 10.1.x powered webapps.
We did not detect because of latestDep tests were not done with this version and also we lacked tests with http headers.
I added both

[Tomcat 10.1.x] Fix request corruption

---

dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/GenerativeStackTraces.java
dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/NativeLibrariesApplication.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java

This adds a code hotspots test which stresses large numbers of unique stack traces by choosing methods at random recursively. The assertions are weak - the application should not crash and the profiler should produce some `datadog.ExecutionSample`s.

add code hotspots test for large number of unique stack traces

---

dd-java-agent/instrumentation/spring-webmvc-5.3/src/main/java/datadog/trace/instrumentation/springweb/OrderedServletPathRequestFilter.java

Spring Mvc 5.3 instrumentation defines a filter complying with servlet >= 4 spec. If using an older servlet spec defaults methods like init and destroy are not defaulted in the interface.

spring mvc filter: complies with servlet < 4 specs

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/MetricProbe.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SnapshotProbe.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/EnvironmentAndVersionCheckerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/TransformerDefinitionMatcherTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/LogProbeTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/MetricProbeTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/SnapshotProbeTest.java

Introduced evaluateAt attribute in probe configs
Refactored probe config builders
attribute is not used right now, but will be wired in a next PR

Introduced evaluateAt attribute in probe configs

---

dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog.trace.instrumentation.iastinstrumenter/iast_exclusion.trie

Do not exclude OWASP benchmark

Allow call sites in the benchmark

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteUtils.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteTransformerTest.groovy

Fixes APPSEC-6856.
The problem occurs when some call site advice for
a) an instance method
b) that is not interested in the receiver of the call (doesn't use `@This`),
c) doesn't use all the arguments (or not all arguments in order), and
d) there is no stack manipulation capable of duplicating the required arguments in the stack without using an intermediary array.
In this case, the following code is executed:
```java
public static void dup(MethodVisitor mv, Type[] argumentTypes, int[] indices) {
int[] opcodes = lookupParamDupOpcodes(argumentTypes, indices);
if (opcodes == null) {
pushArray(mv, argumentTypes.length, argumentTypes);
loadArray(mv, argumentTypes.length, argumentTypes);
loadArray(mv, argumentTypes, indices);
mv.visitInsn(POP); // pop out array
} else {
// ...
}
```
The …

Fix side effects in CallSiteUtils causing bug

---

dd-java-agent/instrumentation/spring-webmvc-5.3/src/main/java/datadog/trace/instrumentation/springweb/ServletPathRequestFilterInstrumentation.java

Stops the instrumentation from adding `OrderedServletPathRequestFilter` when there is no `...Filter` interface available on the class path.

Only add OrderedServletPathRequestFilter when Filter interface is available

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java

Remove ClassFormatError handling during initialization. This should not be needed since dd-trace-java v1.0.0.

Remove ClassFormatError handling during initialization

---

dd-java-agent/instrumentation/spring-webmvc-5.3/src/main/java/datadog/trace/instrumentation/springweb/OrderedServletPathRequestFilter.java
dd-java-agent/instrumentation/spring-webmvc-5.3/src/main/java/datadog/trace/instrumentation/springweb/ServletPathRequestFilterInstrumentation.java

Avoid referencing Filter interface but it relies on spring DelegatingFilterProxy for the same.
Also allow disabling the instrumentation by providing an alternate name `spring-path-filter` to inject the `OrderedServletPathRequestFilter`
Tested on:
* Spring web 5.3 with tomcat 8 -> working ok
* Spring web 5.3 (boot 2.7.x) -> working ok
* Spring webflux 5.3 (boot 2.7.x) -> Muzzled expected
* Spring webflux 6 (boot 3) -> Muzzled expected
* Spring web 6 (boot 3) -> Muzzled expected

do not reference Filter interface

---

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java

Replaces a notification on first push to a scope stack with notifications for becoming empty/non-empty
This allows the profiler to know which threads have an active context, without needing to care which one is active, which limits the occurrence of the relatively expensive operation of updating the wallclock profiler's thread filter. Just doing this once is not enough because in over-provisioned applications with large thread pools we see some threads might do some traced activity once and become idle.

notify context thread listeners when the scope stack becomes empty or non-empty

---

communication/src/main/java/datadog/communication/monitor/DDAgentStatsDClientManager.java
communication/src/main/java/datadog/communication/monitor/DDAgentStatsDConnection.java
communication/src/test/groovy/datadog/communication/monitor/DDAgentStatsDClientTest.groovy
internal-api/build.gradle
internal-api/src/main/java/datadog/trace/api/StatsDClientManager.java

Makes the `StatsDClient` used in tests flush immediately, so we don't wait 10 seconds between a lot of the test cases. The test time goes from more than 1 minute 30 seconds to less than 10 seconds.
Slow tests are slow...

Make StatsDClient flush immediately in tests

---

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/ProbeCondition.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java

serialize DSL expression of the probe condition into probe details section of the snapshot
if a condition is set in a probe, it was not serialized in the probeDetails section of the snapshot

Fix ProbeCondition snapshot serialization

---

dd-java-agent/instrumentation/jboss-logmanager/src/main/java/datadog/trace/instrumentation/jbosslogmanager/ExtLogRecordInstrumentation.java
dd-java-agent/instrumentation/log4j-2.7/src/main/java/datadog/trace/instrumentation/log4j27/SpanDecoratingContextDataInjector.java
dd-java-agent/instrumentation/log4j1/src/main/java/datadog/trace/instrumentation/log4j1/LoggingEventInstrumentation.java
dd-java-agent/instrumentation/logback-1/src/main/java/datadog/trace/instrumentation/logback/LoggingEventInstrumentation.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java

This allows instrumentation of logging backends during `native-image` analysis without having to load the entire `Config`

Move Config.isLogsMDCTagsInjectionEnabled() to InstrumenterConfig

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Instrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/SnapshotInstrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/MetricProbe.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SnapshotProbe.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/sink/multipleSnapshotRegex.txt
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/sink/snapshotCapturedValueRegex.txt
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/sink/snapshotRegex.txt
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/sink/snapshotWithCorrelationIdsRegex.txt

* Snapshot: indicates for method probe where conditions are evaluated before serializing data. Either at entry or exit of the method.
* Metric: indicates for method probe where the metric is emitted and with which values. For example at Exit of the method you can emit the return value of the method.
* Log: use the same mechanism than snapshot but can report for example at exit of the method the return value.
following #4313

Add evaluateAt support for probe instrumentations

---

utils/test-utils/src/main/groovy/datadog/trace/test/util/ConfigInstrumentationFailedListener.groovy
utils/test-utils/src/main/groovy/datadog/trace/test/util/ConfigTransformSpockExtension.groovy
utils/test-utils/src/main/groovy/datadog/trace/test/util/DDSpecification.groovy
utils/test-utils/src/main/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension

DDSpecification requires transforming the Config class to make its INSTANCE field non-final and volatile. This will fail in the presence of some testing tooling (e.g. pitest). By moving this instrumentation to a Spock global extension, it runs at an earlier stage, fixing the problem.
Make tests compatible with pitest.
This should also prevent `DDSpecification` fail if a different type of test is run first in the same JVM.

Early transform of Config class in tests

---

telemetry/build.gradle
telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolverQueue.java
telemetry/src/main/java/datadog/telemetry/dependency/LocationsCollectingTransformer.java
telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverQueueSpecification.groovy
telemetry/src/test/groovy/datadog/telemetry/dependency/LocationsCollectingTransformerSpecification.groovy

Telemetry gets blocked (or extremely slowed down) when many classes are loaded in parallel. The standard `WeakHashMap` implementation seems to be the culprit, and using our `WeakCache` solves it.

Fix bug in dependency resolution under high concurrency

---

dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java

The reactive test is flaky anyway, and without it we can likely maintain the asserts in the other scenarios.

re-enable asserts, disable reactive test

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/CachingType.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/OutlineTypeParser.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeOutline.java

For certain metadata (class modifiers, the names of interfaces and any super-class) we only need the outline of the declaring type, regardless whether we're matching or transforming. This PR temporarily switches the type-factory to always create outlines when looking up this kind of metadata.
The delegate check in `LazyType` has also been adjusted to allow re-use of full-types even when we only want outlines. 
Outline type parsing is faster and uses less memory than full-type parsing.
For a small apps like petclinic this reduces the amount of full-types parsed from ~1200 to less than 300

Reduce the amount of full-type parsing needed for instrumentation

---

dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfiler.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

Allows a user to choose which perf event should be used to schedule sampling, overloading the CPU engine. E.g. to capture stack traces every 1000 `L1-dcache-load-misses`, set:
```
-Ddd.profiling.experimental.async.scheduling.event=L1-dcache-load-misses
-Ddd.profiling.experimental.async.scheduling.event.interval=1000
```
Omitting `dd.profiling.experimental.async.scheduling.event.interval` will result in defaults for each event chosen by the profiler. To drive sampling based on branch misses, with a default interval, set:
```
-Ddd.profiling.experimental.async.scheduling.event=branch-misses
```
Setting an alternative scheduling event is mutually exclusive with the default CPU profiling.

allow specification of arbitrary perf events to schedule samples

---

dd-trace-api/src/main/java/datadog/trace/api/internal/InternalTracer.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/Batch.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/InboxItem.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/NoOpMetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
dd-trace-ot/build.gradle
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

This PR creates a new *internal* API in order to control traces and metrics flush.
Its goal is to improve test stability and allow proper `system tests` implementation (no more introspection from Java client code).
Tracer will also try to flush at close in order prevent data loss.

Add flush traces and metrics API

---

dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
dd-trace-core/src/main/java/datadog/trace/core/datastreams/TagsProcessor.java

This PR will remove any null tags that we try to send along in a data streams checkpoint.
Null tags cause deserialization issues in the Data Streams backend, causing checkpoints to be dropped.

[DSM] Don't send null tags with data streams checkpoint

---

dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfiler.java
dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/ContextThreadFilter.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TestProfilingContextIntegration.groovy
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
gradle/dependencies.gradle
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ProfilingContextIntegration.java

use native threadid for attach/detach events

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/DefaultTaintedMap.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/ObjectGen.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/ObjectGenTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedMapTest.groovy

* Avoid depending directly on the garbage collector during testing. Each GC scenario is simulated with a mocked ReferenceQueue.
* Finer-grained control over edge cases.
Previous approach was dependent on GC, which made it slow, and flaky.
See https://github.com/DataDog/dd-trace-java/issues/4098

Rework TaintedMapTest

---

dd-java-agent/instrumentation/resteasy-appsec/src/nettyTest/groovy/datadog/trace/instrumentation/resteasy/NettyResteasyAppsecTest.groovy

Fix port conflict in NettyResteasyAppsecTest
This should fix test flakiness in this suite.
* Fixes https://github.com/DataDog/dd-trace-java/issues/3862 (probably).

Fix port conflict in NettyResteasyAppsecTest

---

dd-java-agent/instrumentation/liberty-20/src/test/groovy/datadog/trace/instrumentation/liberty20/Liberty20Test.groovy
dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/ServletBlockingHelper.java

`Liberty20Test` creates an embedded instance of Liberty, which is based on OSGi. This means the application and servlet jars are isolated from the rest of the test JVM.
Note that the instrumentation being tested still uses the `org.slf4j` package for its logging because the repackaging to `datadog.slf4j` only happens when all instrumentations are collected in the final `dd-java-agent` jar. It also doesn't have the classloading instrumentation installed which would normally delegate `datadog.slf4j` requests to the boot-class-path.
The end result of this was that the original `ServletBlockingHelper` was failing to load for `Liberty20Test`, because it referred to `org.slf4j` and the embedded liberty server was not allowing requests for that package to delegate to the boot-class-path.
So PR …

Fix embedded test so we can remove redundant MethodHandles

---

dd-java-agent/instrumentation/datastax-cassandra-3/build.gradle
dd-java-agent/instrumentation/datastax-cassandra-3/src/test/groovy/CassandraClientTest.groovy
dd-java-agent/instrumentation/datastax-cassandra-4/build.gradle
dd-java-agent/instrumentation/datastax-cassandra-4/src/test/groovy/CassandraClientTest.groovy

Migrate Cassandra to testcontainers, previously using cassandraunit.
Hopefully less flaky.

Migrate Cassandra tests to testcontainers

---

internal-api/build.gradle
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
telemetry/src/main/java/datadog/telemetry/HostInfo.java

* In telemetry, use the hostname discovered in Config initialization.
* In Config, try `/proc/sys/kernel/hostname` and `/etc/hostname` before the `hostname` command.
We detected hostname twice, and in slightly different ways (Telemetry wouldn't use environment variables, Config wouldn't use hostname files).
Initially discovered while monitoring the execution of external process, which was triggered Config's execution of `hostname`

Unify hostname detection in config and telemetry

---

lib-injection/src/main/docker/Dockerfile

+ ADD docker commands should be avoided as they can invoke shell scripts. - COPY is more cache friendly
Example use after this change (not requires latest docker - esp buildx and buildkit - to be installed)
```
mkdir build/
touch build/dd-java-agent.jar
docker buildx build https://github.com/DataDog/dd-trace-java.git#pawel/better_lib_injection_dockerfile:lib-injection/src/main/docker --build-context java_agent=./build/
```

[lib-injection] Set the pre built artifact that is used to build the image as its own stage 

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy

Ensure metrics aggregator thread is running and will handle the report signal.
Signal was not dispatched if the metrics aggregator thread was not running yet.
Required for https://github.com/DataDog/system-tests/pull/683.

feat(core): Ensure aggregator thread starts for flush request

---

dd-trace-core/src/jmh/java/datadog/trace/common/writer/ddagent/TraceMapperBenchmark.java
dd-trace-core/src/jmh/java/datadog/trace/core/DDSpanHelper.java

Adds a benchmark for trace serialization measuring DDSpan and `TraceMapper` interactions.
Will be used to validate changes to `DatadogTags` during W3C tracecontext implementation.

Add benchmark for trace serialization

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/datastreams/RecordingDatastreamsPayloadWriter.groovy

This will hopefully fix the test failures in assertions added by #4266 (merged around the same time as #4355)

Bump RecordingDatastreamsPayloadWriter timeout to account for metrics timing changes in #4355

---

build.gradle
dd-java-agent/agent-iast/build.gradle
dd-java-agent/appsec/build.gradle
gradle/java_no_deps.gradle
gradle/pitest.gradle

Add [pitest](http://pitest.org/) support (mutation testing).
Tested modules: iast, appsec, telemetry.
Even after https://github.com/DataDog/dd-trace-java/pull/4330, there are larger changes related to `Config` handling, `SpockRunner`, etc, to be able to use pitest in some submodules, such as `instrumentation/*`.
Running pitest for the iast module: `./gradlew :dd-java-agent:agent-iast:pitest`
Reports are at `dd-java-agent/agent-iast/build/reports/pitest/index.html`.

Add pitest support (mutation testing)

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java

In snapshot, when field count reached the maximum set, the attribute notCapturedReason was along with the list of fields. We move this up along with value attributes (fields, type, ...)
make snapshot structure more coherent and easier to parse

Adjust notCapturedReason FieldCount location

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/test/java/datadog/trace/bootstrap/debugger/SnapshotSummaryTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot08.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/sink/snapshotWithEvalErrorRegex.txt

Reports runtime evaluation error (like NPE) into snapshots in `evaluationErrors` attribute.

Add evaluation error reporting for expressions

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
dd-trace-core/src/main/java/datadog/trace/core/datastreams/DataStreamsCheckpointer.java
dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsCheckpointer.java
dd-trace-core/src/main/java/datadog/trace/core/datastreams/StubDataStreamsCheckpointer.java

Fix flaky tests for DSM caused by DataStreamsCheckpointer not clearing between tests

---

dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy

Runs the smoke tests with async-profiler allocation profiling enabled, except on J9 where we know it can crash.

enable async allocation profiling in non-J9 smoke tests

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeOutline.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactoryForkedTest.groovy

When mixing full and outline types, byte-buddy might resort to checking the enclosing type
(when this happens we can fall back to the declaring type of the outline, if there is one)

Fix intermittent failure in Lettuce4SyncClientTest

---

buildSrc/build.gradle.kts
buildSrc/src/test/groovy/InstrumentPluginTest.groovy
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategy.java
dd-java-agent/agent-builder/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/CacheProviderTest.groovy
dd-java-agent/agent-builder/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/matcher/FailSafeRawMatcherTest.groovy
dd-java-agent/agent-iast/src/jmh/java/com/datadog/iast/propagation/StringConcatFactoryBatchBenchmark.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/CachingType.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java
dd-java-agent/instrumentation/spring-cloud-zuul-2/src/main/java/datadog/trace/instrumentation/springcloudzuul2/ZuulProxyRequestHelperInstrumentation.java
gradle/dependencies.gradle

https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.19
* Avoid possible lock through circular class loading of TypeDescription subtypes.
* Avoid access error when using unsafe API on Java 17 with an active security manager.
* Close URL class loader used in Gradle plugin.

byte-buddy 1.12.19

---

dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/Arch.java
dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfiler.java
dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/AsyncProfilerConfig.java
dd-java-agent/agent-profiling/profiling-async/src/main/java/com/datadog/profiling/async/OperatingSystem.java
dd-java-agent/agent-profiling/profiling-controller/build.gradle
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ControllerFactory.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

Enables async-profiler on any JVM running on x86/x64 or J9
Depends on #3992 because this needs to be tested on more J9 and OpenJ9 distributions

enable async-profiler by default on x86/x64

---

dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogHttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedContext.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/HaystackHttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/XRayHttpCodec.java
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpExtractorTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TagContext.java

Splits up the B3 propagator into multi header and single header versions
They are separate
This is in preparation for new configuration variables and propagation style names.

Split up B3 propagator into multi and single header

---

dd-java-agent/instrumentation/rmi/build.gradle

Makes `rmic` Gradle task use `rmic` binary provided with Java 8 toolchain. Also changes the task type to `Exec` and refactors the command a bit.
Also, this ( 7c875e842adf387d8b162e487ca2356a2d823790 ) makes the paths to resolve properly on Windows (or any other OS). Not sure if the rest of the project will work properly on Windows, but this part will work now. :slightly_smiling_face: 
Without this change the task will fail if `rmic` binary is not on the Path env var. 
This is bad for 2 reasons:
- [Contribution guide](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md) doesn't mention anywhere it has to be on the path.
- Makes the build unpredictable. Since the rest of the modules are built with Java 8, it's better to explicitly specify the toolchain to use here.
Without …

Fix rmic Gradle task

---

dd-java-agent/instrumentation/synapse-3/src/test/groovy/datadog/trace/instrumentation/synapse3/SynapseTest.groovy

Fixes flaky `SynapseTest` by ensuring the traces are sorted before asserting them.
To make the CI more stable. I was going to push it here ( #4401 ), but was too slow. :sweat_smile:

Fix flaky SynapseTest

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/AppSecSystemSpecification.groovy

Added checkers to validate if remote config is `null`
Reported NullPointerException:
```[dd.trace 2022-12-06 10:42:24:019 +0100] [dd-remote-config] WARN datadog.remoteconfig.state.ProductState - Error handling configuration removal for datadog/2/ASM/asm_configuration/config (Will not log errors for 5 minutes)
at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
at com.datadog.appsec.config.AppSecConfigServiceImpl.lambda$subscribeConfigurationPoller$2(AppSecConfigServiceImpl.java:111)
at datadog.remoteconfig.ConfigurationChangesTypedListener$Builder.lambda$useDeserializer$0(ConfigurationChangesTypedListener.java:24)
at …
```

Fixed NPE if the remote config is absent

---

dd-trace-api/src/main/java/datadog/trace/api/internal/InternalTracer.java
dd-trace-core/build.gradle
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-ot/build.gradle
dd-trace-ot/correlation-id-injection/build.gradle
dd-trace-ot/correlation-id-injection/src/main/java/datadog/trace/correlation/AbstractCorrelationIdInjector.java
dd-trace-ot/correlation-id-injection/src/main/java/datadog/trace/correlation/CorrelationIdInjectors.java
dd-trace-ot/correlation-id-injection/src/main/java/datadog/trace/correlation/Log4j2CorrelationIdInjector.java
dd-trace-ot/correlation-id-injection/src/main/java/datadog/trace/correlation/Log4jCorrelationIdInjector.java
dd-trace-ot/correlation-id-injection/src/main/java/datadog/trace/correlation/Slf4jCorrelationIdInjector.java
dd-trace-ot/correlation-id-injection/src/test/groovy/CorrelationIdInjectorTest.groovy
dd-trace-ot/correlation-id-injection/src/test/groovy/Log4j2CorrelationIdInjectorTest.groovy
dd-trace-ot/correlation-id-injection/src/test/groovy/Slf4jCorrelationIdInjectorTest.groovy
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
settings.gradle

This PR adds automatic injection of Trace / Span Ids to MDC (Mapped Diagnostic Context) to `dd-trace-ot`.
As `ScopeListener` was removed from public API from `1.0.0` version, there is no way for users to do such injection.
I add it as a feature of `dd-trace-ot` but it's implemented in a separated module that can be reused for a coming OTEL support.
Fix #2066

Add correlation id injection to dd-trace-ot

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java

also use simple name-length check to skip checking the primitive type cache for the majority of type lookups

Remove cache of ForLoadedType common types as outlining is faster

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentStrategies.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
internal-api/src/main/java/datadog/trace/api/ResolverCacheConfig.java
internal-api/src/test/groovy/datadog/trace/api/InstrumenterConfigTest.groovy

The following named presets are currently supported:
```
DEFAULT     # Pool sizes to fit the average sized app
LARGE       # Pool sizes to fit large enterprise apps
SMALL       # Pool sizes to fit small microservice apps
LEGACY      # Revert to the behaviour before 0.104.0
```
System property:
```
-Ddd.resolver.cache.config=LARGE
```
Environment variable:
```
DD_RESOLVER_CACHE_CONFIG=LARGE
```
I also adjusted the default sizes to allow for more outline types vs full types, by profiling how many outlines vs full-types were parsed for a selection of applications. (Recent changes mean we now use type outlines more than we did before.)

Introduce named presets for the resolver cache, to make it easier to configure

---

telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolverQueue.java

Changes the log level of the DependencyResolverQueue log statement
Customers are seeing the log statement because it is at WARN level.

Changed dependency detection resolver log level from warn to debug

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastModuleImpl.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Location.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
dd-smoke-tests/springboot/src/main/java/ddtest/client/sources/Hasher.java
dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/DDSpanTypes.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InternalSpanTypes.java

Creates a new span for vulnerabilities where there is no current context
Vulnerabilities are not only found during the execution of a request, they can be present at boot time, background processes ... this PR tries to enable the creation of custom spans when there is no requests.

Create spans for vulnerabilities outside of requests

---

dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java

This PR makes the MDC injection from `dd-trace-ot` respects the `dd.logs.injection` config.
Requested by @bantonsson. It will match the instrumentation behavior.
Complement to #4396

feat(dd-trace-ot): Add MDC injection config support

---

dd-trace-core/src/main/java/datadog/trace/common/writer/SpanSamplingWorker.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/SpanSamplingWorkerTest.groovy

Fixes the dropped spans metric call. It must pass number of dropped spans instead of number of sampled spans.
`healthMetrics.onPartialPublish` expects number of dropped spans passed as a param.
@PerfectSlayer, thanks for you help finding this issue!

Fix number of dropped spans metric in the Single Span Sampling worker

---

dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie

Prevent `IllegalAccessError` in OpenJDK 17.0.4 by excluding javax.management.* & javax.swing.*
Customer case APMS-8366
```
java.lang.IllegalAccessError: superinterface check failed: class javax.swing.RepaintManager$ProcessingRunnable (in module java.desktop) cannot access class datadog.trace.bootstrap.FieldBackedContextAccessor (in unnamed module @0x3ed242a4) because module java.desktop does not read unnamed module @0x3ed242a4
```

Prevent IllegalAccessError in OpenJDK 17.0.4 by excluding javax.management.* & javax.swing.*

---

dd-java-agent/instrumentation/elasticsearch/transport-2/build.gradle
dd-java-agent/instrumentation/elasticsearch/transport-5.3/build.gradle
dd-java-agent/instrumentation/elasticsearch/transport-5/build.gradle
dd-java-agent/instrumentation/elasticsearch/transport-6/build.gradle
dd-java-agent/instrumentation/elasticsearch/transport-7.3/build.gradle
dd-java-agent/instrumentation/elasticsearch/transport/build.gradle

Exclude bogus `org.elasticsearch:elasticsearch` release from muzzle checks
The CI is failing.
I reported the issue on their GH repo: https://github.com/elastic/elasticsearch/issues/92383

fix(dd-java-agent): Exclude bogus elasticsearch release

---

dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

We found a crash related to musl so will disable until it's been fixed.

disable async-profiler for the time being

---

dd-java-agent/instrumentation/liberty-20/src/main/java/datadog/trace/instrumentation/liberty20/LibertyServerInstrumentation.java

A blocking response would cause a CacheServletWrapper to be created that contained an empty mapping because dispatchContext::servletMapping never had the opportunity to be filled. The next request to the same endpoint would then fail (and only then would this corrupted cache entry be evicted).
Seen in the system tests (PR https://github.com/DataDog/system-tests/pull/510).

Openliberty: fix NPE after blocking response

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastTag.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/IastTagTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/RequestEndedHandlerTest.groovy

Updates the usage of the tag `_dd.iast.enabled` in order to set a value when the request is skipped by the overhead controller
Overrides https://github.com/DataDog/dd-trace-java/pull/4425 due to issues with CI

Update _dd.iast.enabled tag usage

---

dd-trace-core/src/main/java/datadog/trace/common/sampling/RateByServiceTraceSampler.java

Avoids allocation in `RateByServiceTraceSampler.setSamplingPriority`:
Before:
```java
RateSampler sampler = rates.getSampler(new EnvAndService(env, serviceName));
```
After:
```java
RateSampler sampler = rates.getSampler(env, serviceName);
```
`RateByServiceTraceSampler.setSamplingPriority` is an allocation hot spot.
APMS-8440 Memory allocation issue

Avoid EnvAndService allocation on lookup triggered by setSamplingPriority call

---

internal-api/src/main/java/datadog/trace/api/Config.java

enable async-profiler by default

---

dd-trace-core/src/main/java/datadog/trace/core/monitor/HealthMetrics.java

Count the number of dropped traces by serialization failure.
Where a trace is sampled, it can be lost if something unexpected happens during serialization and it was not counted as a dropped trace.

Add metric for serialization failure

---

dd-java-agent/agent-iast/src/jmh/java/com/datadog/iast/overhead/OverheadControllerBenchmark.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastRequestContext.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastSystem.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/overhead/Operations.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/overhead/OverheadController.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/DefaultTaintedMap.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/TaintedObjects.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/NonBlockingSemaphore.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/overhead/OverheadContextTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/overhead/OverheadControllerLogTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/overhead/OverheadControllerTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedObjectsLogTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/NonBlockingSemaphoreTest.groovy
dd-java-agent/agent-iast/src/testFixtures/groovy/com/datadog/iast/NoopOverheadController.groovy
dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/IastConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Extract atomic semaphores from overhead controller and tainted objects and adds debug information to troubleshoot issues.
We are getting an increased level of flaky tests in system-tests due to the overhead controller.

Update overhead controller and add debug info

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/Configuration.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanProbe.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationComparerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/TransformerDefinitionMatcherTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java

Add support for incoming debugger span probes.
Add in debugger configuration and deserialization model
Configuration model for new debugger span probes

Add span probe configuration

---

dd-trace-ot/correlation-id-injection/build.gradle

removes the publish task from `correlation-id-injection`, only a select top-level modules should have this task
`correlation-id-injection` is shaded into `dd-trace-ot` and shouldn't be published as a separate artifact

remove publish task from correlation-id-injection

---

telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java
telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java

Reduce Telemetry warnings. In particular, log all network and HTTP errors to debug, since there are many scenarios where this is frequent (but not harmful).
These warnings are too alarming for customers, for scenarios that are common and safe.
There are still some possible warning messages in the module, but the ones I reviewed seem to be unexpected conditions that we do want customers to notice.

Reduce Telemetry warnings

---

.github/workflows/lib-injection.yaml

Build lib injection image from tags too, so the jar doesn't have a snapshot version

---

dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/ServletInstrumentation.java
dd-java-agent/instrumentation/undertow-2.0/src/test/groovy/UndertowServletTest.groovy

Set servlet.context & servlet.path for Undertow Servlet Request
UndertowDecorator doesn't set servlet.context as opposed to Servlet2Decorator that sets servlet.context tag used by TagInterceptor to set the span’s service name.
APMS-8274

Set servlet.context & servlet.path for Undertow Servlet Request

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/PosixPidSupplier.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/PidHelperTest.groovy
internal-api/build.gradle
internal-api/internal-api-9/src/main/java/datadog/trace/util/JDK9PidSupplier.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/util/PidHelper.java
internal-api/src/test/java/datadog/trace/util/PidHelperForkedTest.java

Improvement on PR #4393 that only calls the `PidHelper` fallback on Java 8 when something actually uses `PidHelper`, rather than when setting up `AgentInstaller`. This also includes some clean-up of PID parsing.
Services like the tracing and profiling always use the PID, but `PidHelper` may never get called for some configurations of the Java tracer, for example if tracing and profiling are turned off but CI visibility is turned on. This PR means that we only pay the cost of looking up the PID when we actually need it.

Make PidHelper fallback lazy

---

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/JsonToExpressionConverter.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_05.json
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java

add support for `ne` json operator in expression Language as specified (instead of `neq`).
Fix also the way we parse Json numbers for separating integers from decimals

Fix NotEqual operator

---

dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/HelperMethods.java
dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientRequestTracingHandler.java
dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientRequestTracingHandler.java
dd-trace-api/build.gradle
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/PropagationStyle.java
dd-trace-api/src/main/java/datadog/trace/api/TracePropagationStyle.java
dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
dd-trace-core/src/jmh/java/datadog/trace/core/propagation/InjectorBenchmark.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpExtractorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpInjectorTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentPropagation.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

This deprecates the `dd.propagation.style.extract` and `dd.propagation.style.inject` settings in favor of the three new settings `dd.trace.propagation.style`, `dd.trace.propagation.style.extract`, and `dd.trace.propagation.style.inject`.
The new `dd.trace.propagation.style*` settings makes a distinction between `B3` which is [single header b3 propagation](https://github.com/openzipkin/b3-propagation/tree/master#single-header) and `B3MULTI` which is [multiple header b3 propagation](https://github.com/openzipkin/b3-propagation/tree/master#multiple-headers).
The change is backwards compatible and using the deprecated settings will only result in a deprecation warning being logged, and the settings being translated into the new ones, including the old `B3` setting being translated into both …

Deprecate dd.propagaion.style for dd.trace.propagation.style

---

dd-java-agent/agent-iast/src/jmh/java/com/datadog/iast/propagation/StringJoinBenchmark.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringCallSite.java
dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/StringCallSiteTest.groovy
dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringSuite.java
internal-api/src/main/java/datadog/trace/api/iast/propagation/StringModule.java

Adds all the instrumentation needed to perform taint tacking in join operations for String objects
IAST requires to track all modifications that happen to strings in the code, this PR implements the join operations for String class
The instrumentation for the join method with the iterable param is based on the premise of iterating only once since these iterators may not be immutable.
Don't panic for te use of `new ArrayList<>()` in `StringCallSite.java` 😅  it has been discussed with @anderruiz and @smola and we have decided to assume the List overhead to keep it simple in this first iteration.
|Benchmark |                                                                   Mode|    Cnt|       Score |    Error|   Units|
| --- | ---| ---|---|---| ---|
|StringJoinBenchmark.baseline    | …

String taint tracking - join methods

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
dd-java-agent/src/test/groovy/datadog/trace/bootstrap/AgentBootstrapTest.groovy
dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/util/throwable/FatalAgentMisconfigurationError.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

When in Agentless mode, the Datadog API key is required to send payloads to the intake.
If we detect there’s no API Key, currently we silently continue without sending payloads.
We want to fail the process instead.
It is easy to overlook such misconfiguration, so we want to make it more obvious by failing the process rather than silently continuing.
This only applies to scenarios where CI visibility feature is enabled.
If CI visibility is disabled, previous behaviour remains unchanged (proceed with starting the process even if the API key is missing).

Fail process when running in Agentless mode and API key is not set

---

dd-trace-core/src/main/java/datadog/trace/civisibility/writer/ddintake/CiTestCycleMapperV1.java
dd-trace-core/src/main/java/datadog/trace/common/writer/DDIntakeWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/Payload.java
dd-trace-core/src/test/groovy/datadog/trace/civisibility/writer/ddintake/CiTestCycleMapperV1PayloadTest.groovy

* Change the `DDIntakeWriter` default for `alwaysFlush` so we batch traces together.
* Fixes the `CiTestCycleMapperV1` mapper so it doesn't add N headers when sending N traces. It now generates the header separately and sends it only once at the beginning of every payload.
* Updates the test so we only expect one header followed by any number of traces in a payload.
Generating the header once in the mapper this way is similar to what we do in `TraceMapperV0_4` and `TraceMapperV0_5`.
Using the `DDIntakeWriter` was painfully slow because it was making one request per trace (ie: one per test in CI Visibility).
This only affected CI Visibility users in Agentless mode before, but after #4369 would also affect Agent users.

DDIntakeWriter: Do not flush after every single trace

---

dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java

Guard against agent being initialized twice. Instead of producing later errors, it will just print a warning and stop any further work.
Some customers are defining `-javaagent` more than once. This produces later failures, in very non-obvious ways.

Guard against agent being initialized twice

---

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/DSL.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/JsonToExpressionConverter.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_06.json

Can check accessing reference against null
Able to write `field != null` in expression language

Add null literal support

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentTransformerBuilder.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/MuzzleMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterState.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleCheck.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGenerator.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceMatcher.java
dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/muzzle/TestInstrumentationClasses.java

Moves muzzle matching code to outside of `Instrumenter`.
Also changes the generated `Muzzle` classes to be static factories that create `ReferenceMatcher`s, rather than `ReferenceMatcher`s themselves. This will allow each `Muzzle` class to be unloaded once its `ReferenceMatcher` instance has been created.
Second step towards being able to unload muzzle/instrumentation classes after they've been applied

Decouple muzzle matching

---

dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy
dd-smoke-tests/log-injection/src/test/groovy/datadog/smoketest/LogInjectionSmokeTest.groovy

as its debug output can interfere with the smoke test's log-file scraping, causing intermittent failures on CI

Turn off remote-config during field-injection / log-injection smoke tests

---

dd-trace-core/src/main/java/datadog/trace/common/sampling/SpanSamplingRules.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/TraceSamplingRules.java

Adds logging for JSON sampling rules when failed to parse for easier debugging.
When it couldn't parse provided JSON sampling rules it would be useful the rules logged to simplify debugging.
APMS-8472

Log JSON sampling rules when failed to parse for easier debugging.

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/DatadogClassLoader.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InstrumentationClassLoader.java
dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java
dd-java-agent/src/test/groovy/datadog/trace/agent/InstrumenterUnloadTest.groovy
dd-java-agent/src/test/java/jvmbootstraptest/UnloadingChecker.java

Redirects class-loading requests for `...$Muzzle` and `...Instrumentation` classes to a separate class-loader, which is kept in a weak reference. Once the byte-buddy agent has been built these classes are no longer referenced and the `InstrumentationClassLoader` can be unloaded.
For a simple Spring-Web application this results in 400 tracer-related classes being unloaded by the time the application is ready to serve requests  - the majority are `..Instrumentation` classes.
This should reduce the memory (metaspace) overhead of the Java tracer over time.
Some instrumentations create instances of statically nested classes that are passed back to the byte-buddy agent installer, typically for custom transformations or custom muzzle checks. These nested classes will continue to be loaded in the …

Load instrumentation classes in separate classloader so they can be unloaded after use

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/ClassFileLocators.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/TypeInfoCache.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypePoolFacade.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/WithLocation.java

The main change in this PR is the introduction of an interface `WithLocation` that lets us share the class-file location of `TypeDescription`s supplied by our type-pool. This also lets us re-use the original bytecode when replacing an outline type with its fully-parsed description, instead of having to re-read the class-file.
Other additions in this PR:
* Support temporarily switching back to type outlines during transformation (e.g. for last-minute memoization)
* Support getting the class-loader context of the current transformation
plus a few other related improvements to the type-pool internals.
Mostly preparation for memoization of type matching, so we can distinguish between `TypeDescription`s with the same name that come from different class-files. The ability to re-use the bytecode …

Provide access to the original location of TypeDescriptions

---

remote-config/src/main/java/datadog/remoteconfig/state/ParsedConfigKey.java
remote-config/src/test/groovy/datadog/remoteconfig/state/ParsedConfigKeyTests.groovy

The Java tracer incorrectly parses the configuration path as it checks it ends with `/config`. This suffix is not guaranteed and should be ignored by the tracer.
Example from .NET: https://github.com/DataDog/dd-trace-dotnet/blob/8c965716755179efa64fbef4543251c0dc100e8d/tracer/src/Datadog.Trace/RemoteConfigurationManagement/RemoteConfigurationPath.cs#L13.
System tests are on the way to test this behavior.

(rcm) fix configuration path parsing

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/IastModuleImplOnStringTrimTest.groovy
dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringCallSite.java
dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/StringCallSiteTest.groovy
dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringSuite.java
internal-api/src/main/java/datadog/trace/api/iast/propagation/StringModule.java

Instrument the String.trim() function so we can track tainted objects for iast vulnerability detection
This is part of an effort to instrument all of the String and StringBuilder calls that will require taint object tracking instrumentation.
~This depends on a lot of non reviewed PRs so I am marking it as draft for now until we can rebase it after the other PRs are merged.~

Taint propagation for String.trim

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java

Store each eval errors by probe Ids into Snapshot object Reset CapturedContext's evalErrors before evaluating additional probes copy eval errors by probe Ids for corresponding snapshot evaluate conditions only for entry when evaluateAt is DEFAULT
For duplicated probes eval errors were not reported correctly

Fix evaluation error reporting for merged probes

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java

as well as `groovy.lang.GroovyClassLoader$InnerLoader` because they are not re-entrant.
This avoids having to turn the `loadClass` fallback off completely with `-Ddd.resolver.use.loadclass=false`
(see https://issues.apache.org/jira/browse/GROOVY-9742 for why `GroovyClassLoader` is not re-entrant)

Avoid using type resolver `loadClass` fallback with `groovy.lang.GroovyClassLoader`

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/overhead/OverheadController.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/overhead/OverheadControllerTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java

Updates the max concurrent request and reset period of the overhead controller to prevent the agent from skipping to many requests.

Update IAST overhead rates

---

dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSupport.java

Disables this event for version where there was a [bug in calculating the duration](https://bugs.openjdk.org/browse/JDK-8296733) introduced in JDK15. We only put LTS versions and the known fix version in these checks, so erroneously disable on JDK12-14, because we don't expect these unsupported non-LTS JDKs to still be in use.

disable jdk.FileWrite on OpenJDK versions where durations are incorrect

---

dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/EndpointEvent.java

This adds a 10ms threshold to datadog.EndpointEvent, which prevents emission of these events for very short traces, where we are unlikely to have sampled any CPU or walltime, which keeps recording sizes small.

add 10 ms threshold to datadog.EndpointEvent

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Allows configuring the max time any single run of the WAF can take. This also changes the default from an effectively infinite value down to 100 ms (defined in microseconds).
* Envronment variable: `DD_APPSEC_WAF_TIMEOUT`
* System property: `dd.appsec.waf.timeout`

Add configuration timeout for the WAF

---

dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/model/TestBean.java
dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy

- Ignore org.springframework.web.util.WebUtils from exclusion list
- Add IAST smoke test for springframework parameter binding
IAST needs to instrument this class to taint source parameters when parameter binding is used in  spring framework

Ignore org.springframework.web.util.WebUtils from exclusion list

---

telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java
telemetry/src/test/groovy/datadog/telemetry/dependency/DependencySpecification.groovy

Fixes issue in dependency resolution when artifactId is empty
See https://github.com/DataDog/dd-trace-java/issues/4527

Fix issue resolving dependency with empty artifactId

---

dd-java-agent/agent-profiling/profiling-auxiliary/build.gradle
dd-java-agent/agent-profiling/profiling-auxiliary/src/main/java/com/datadog/profiling/auxiliary/AuxiliaryProfiler.java
dd-java-agent/agent-profiling/profiling-auxiliary/src/test/java/com/datadog/profiling/auxiliary/AuxiliaryProfilerTest.java
dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
internal-api/src/main/java/datadog/trace/api/Config.java

Owing to complexities in configuring the profiler, we haven't been actually enabling async-profiler when we could have been since 1.3.0. This really activates it.

fix and log async-profiler activation

---

internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/codeowners/Codeowners.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/codeowners/Entry.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/codeowners/EntryBuilder.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/codeowners/matcher/AsteriskMatcher.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/codeowners/matcher/CharacterMatcher.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/codeowners/matcher/CompositeMatcher.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/codeowners/matcher/DoubleAsteriskMatcher.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/codeowners/matcher/EndOfLineMatcher.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/codeowners/matcher/EndOfSegmentMatcher.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/codeowners/matcher/Matcher.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/codeowners/matcher/NegatingMatcher.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/codeowners/matcher/QuestionMarkMatcher.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/codeowners/matcher/RangeMatcher.java
internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/ci/codeowners/CodeownersTest.groovy
internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/ci/codeowners/EntryBuilderTest.groovy
internal-api/src/test/resources/ci/codeowners/CODEOWNERS

This change adds a parser for [github's CODEOWNERS files](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners).
We want CI visibility to report code owners for each executed test case.
The goal is to search for a CODEOWNERS file in the client's repo, parse it and use the data to determine which teams or people own specific tests.
This change only contains the parsing logic. The rest will follow in a separate PR, to keep the review scope small.

Implement CODEOWNERS parsing and matching

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerSpan.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTracer.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/SpanInstrumentor.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTracerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanProbeInstrumentationTest.java

When exception is thrown during the instrumented span, we store the throwable inside the span for reporting it as error span.

Set error in instrumented span on exception

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java

Exception is reported in the snapshot anyway

Remove debug log line when handling exception during field extract for JSON serialization

---

gradle/dependencies.gradle

allow to read class files from JDK 19 & JDK 20

Upgrade ASM version to 9.4

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java

this is no longer needed after recent refactoring

Remove redundant reflection in MuzzleVersionScanPlugin.printMuzzleReferences

---

buildSrc/build.gradle.kts
buildSrc/src/test/groovy/InstrumentPluginTest.groovy
gradle/dependencies.gradle

Main change of interest to us between 1.12.20 and 1.12.22:
> Support `MethodHandle` and `MethodType` in `Advice.Origin` annotation.
> Support `MethodHandles.Lookup` in `Origin` and `Advice.Origin` annotations.
https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.21
https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.22

byte-buddy 1.12.22

---

dd-java-agent/agent-tooling/src/jmh/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteBenchmarkInstrumentation.java
dd-java-agent/instrumentation/iast-instrumenter/src/main/java/datadog/trace/instrumentation/iastinstrumenter/IastInstrumentation.java
dd-java-agent/instrumentation/iast-instrumenter/src/test/groovy/IastInstrumentationTest.groovy

Don't mix concerns - `Instrumenter`s should be declarative and shouldn't implement other APIs with different lifecycles

Cleanup IAST Instrumenters

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/BasicFutureInstrumentation.java
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/HttpAsyncClientExchangeHandlerInstrumentation.java
dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/HttpAsyncClientExchangeHandlerInstrumentation.java
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSClientInstrumentation.java
dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/QueueBufferConfigInstrumentation.java
dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/SqsReceiveRequestInstrumentation.java
dd-java-agent/instrumentation/mongo/bson-document/src/main/java/datadog/trace/instrumentation/mongo/ByteBufBsonDocumentInstrumentation.java
dd-java-agent/instrumentation/mongo/driver-3.1/src/main/java/datadog/trace/instrumentation/mongo/MongoClient31Instrumentation.java
dd-java-agent/instrumentation/mongo/driver-3.4/src/main/java/datadog/trace/instrumentation/mongo/MongoClient34Instrumentation.java

We don't need the wider generic range, it's a leftover from a previous refactoring

Cleanup structureMatcher return type

---

dd-trace-ot/build.gradle
test-published-dependencies/ot-is-shaded/build.gradle

Remove the `dd-trace-api` dependencies from shaded dependencies of `dd-trace-ot` artifact.
Restore the initial behavior before `1.0.0`.

Remove dd-trace-api from dd-trace-ot artifact

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java

add a tag to the metric with the probe id
Identify metric generated by Dynamic Instrumentation

Add ProbeId as metric tag

---

dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/BeanDefinitionRepairer.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/BeanFactoryInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerMappingResourceNameFilter.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/WebApplicationContextInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-5.3/build.gradle
dd-java-agent/instrumentation/spring-webmvc-5.3/src/main/java/datadog/trace/instrumentation/springweb/OrderedServletPathRequestFilter.java
dd-java-agent/instrumentation/spring-webmvc-5.3/src/main/java/datadog/trace/instrumentation/springweb/ServletPathRequestFilterInstrumentation.java
dd-smoke-tests/wildfly/build.gradle
dd-smoke-tests/wildfly/spring-ear/.gitignore
dd-smoke-tests/wildfly/spring-ear/build.gradle
dd-smoke-tests/wildfly/spring-ear/settings.gradle
dd-smoke-tests/wildfly/spring-ear/war/build.gradle
dd-smoke-tests/wildfly/spring-ear/war/src/main/java/com/example/hello/HelloController.java
dd-smoke-tests/wildfly/spring-ear/war/src/main/webapp/WEB-INF/dispatcher-servlet.xml
dd-smoke-tests/wildfly/spring-ear/war/src/main/webapp/WEB-INF/web.xml
dd-smoke-tests/wildfly/src/test/groovy/datadog/smoketest/WildflySmokeTest.groovy

Introduces `BeanDefinitionRepairer` to help make the existing bean definition repair approach more re-usable. Bean definitions registered by the tracer now just have to register their classes with `BeanDefinitionRepairer` and these will be re-applied to bean definitions with matching names, even if the original bean class has been lost, for example due to the definition being cloned.
Includes a new smoke test to verify that bean definition repair works for both old and new spring-webmvc definitions.

Refactor BeanFactory advice so we can repair other injected bean definitions

---

dd-java-agent/appsec/src/main/resources/default_config.json

Update ASM (AppSec) event rules to v1.4.3.
* See https://github.com/DataDog/appsec-event-rules/releases/tag/1.4.3

Update ASM event rules to v1.4.3

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/TracerHealthMetrics.java

Add a new health metric to track client (span type) spans without context (ie without parent span).
Have a better understanding of incomplete traces.
I also included a small refactoring commit for readability (one method extraction). I can remove it if needed.

Add client span without context health metric

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/agent-profiling/profiling-ddprof/build.gradle
dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingIntegration.java
dd-java-agent/agent-profiling/profiling-ddprof/src/test/java/com/datadog/profiling/ddprof/DatadogProfilerTest.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TestProfilingContextIntegration.groovy
dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/ProfilingTestApplication.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
dd-trace-api/build.gradle
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
dd-trace-api/src/main/java/datadog/trace/api/experimental/ProfilingContext.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
dd-trace-ot/build.gradle
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
gradle/dependencies.gradle
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ProfilingContextIntegration.java

Let's a user register arbitrary attributes for profiling context by setting:
`-Ddd.profiling.experimental.context.attributes=foo,bar`
Which then allows the user to call 
`ProfilingContext.get().setContextValue("foo", stringValue);`
and have the tags "foo=`stringValue`" appended to each JFR event emitted.

implement profiler context tagging API

---

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

Enables the wallclock profiler by default.

enable wallclock profiler by default, add config flags

---

dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
dd-trace-core/src/test/groovy/datadog/trace/core/datastreams/DefaultPathwayContextTest.groovy

This change simplifies previous attempt to resolve cycles in DSM context propagation. The main idea behind this change is that two edges going in the same direction within a single context can't be a part of a correct hierarchy / data flow. Hence we will use the direction tag to determine more correct parent for a pathway checkpoint.
One of the scenarios when the old logic would not handle correctly:
The client has Spring Kafka handler, which receives data from topic `Input`. The same handler modifies the data and forwards it to two different topics: `Destination 1` and `Destination 2`. Under the hood, we gonna make 3 different checkpoints:
1. When we receive the message. The pathway context hash will be extracted from message headers or will be 0, if nothing was passed though the queue. …

DSM - direction tag is now used to prevent loops / hash explosions

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ValueReferenceResolver.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/ValueScript.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/IndexExpression.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/ComparisonExpressionTest.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java

When accessing collection through index expression, we can now report runtime error like index out of bounds with an explicit expression that failed to be resolved.
example:
`index[10] out of bounds: [0-3]`
Gives explicit feedback in case of runtime error evaluating conditions

Add report of index expression error

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/sink/snapshotWithCorrelationIdsLineRegex.txt
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/DebuggerIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java

when `captureSnapshot=false`, don't freeze data and serialize into the snapshot.
Snapshot handling is also refactored by introducing SnapshotStatus which help to handle all combinations of cases when generating snapshots

Do not serialize captured data for Log Probes

---

buildSrc/src/main/groovy/MuzzlePlugin.groovy
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPluginTest.groovy

Updates the generated `muzzle` tasks to execute via Gradle's `WorkerExecutor` and `WorkQueue`. This enables us to run these tasks on different processes based on the required Java version. (For this first step the tasks still run without any process isolation, but I have verified that they still behave as expected when process isolation is selected.)

Update muzzle to run on Gradle's WorkerExecutor

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/WellKnownClasses.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java

We add two sets of well known classes on which we can safely toString for String representation/serialization.
Having a better string representation than extract fields for classes like `Duration` or `UUID`

Add well known classes as primitive-like objects

---

dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie

This avoids a potential deadlock scenario where one thread might be loading a bouncycastle type which triggers type-matching causing a related class file to be fetched from a signed jar. When the JVM verifies the signed jar entry it might need to access the shared X509Factory certificate store.
Meanwhile another thread is checking some SSL certificates when it needs to load a bouncycastle implementation class.
The first thread has acquired a class-loading lock and wants the X509Factory lock.
The second thread has acquired the X509Factory lock and wants a class-loading lock.
I ran the bouncycastle test-suite with the tracer attached and no types of interest matched our existing instrumentations, so it is safe to ignore these classes. This is the simplest solution to avoid the potential …

Ignore org.bouncycastle.* types

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AdviceStack.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/CombiningMatcher.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/CombiningTransformerBuilder.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/MatchRecorder.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/SplittingTransformer.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterState.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/KnownTypesIndex.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextMatcher.java
dd-java-agent/build.gradle
dd-java-agent/instrumentation/build.gradle
internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
internal-api/src/main/java/datadog/trace/util/ClassNameTrie.java

Builds on top of #4552 to merge together matchers and transformers so we only register a single matcher+transformer pair with byte-buddy. A thread-local bitset is used to record which specific matchers actually applied during the matching phase, which is then used to decide which transformers need to apply to the final transformed type. 
This PR also includes generation of a known-types index, which records the instrumentations that apply to specific named types known at build-time.
This simplifies the byte-buddy side of our configuration and also makes it easier to use ahead-of-time indexes, such as the new `known-types.index` which replaces several string matchers with a single trie comparison. It should also make it easier to measure matching time.

Support combining instrumenter matchers

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
dd-java-agent/build.gradle

Widens the list of ignored muzzle prefixes from an explicit subset to cover all prefixes that the Java Tracer delegates to the boostrap class-loader. By definition everything under these prefixes will always be available and doesn't need to be included in the generated muzzle references.
Fewer muzzle references to check (~800 less) as well as smaller muzzle classes (saves ~300KB uncompressed)

Ignore everything under BOOTSTRAP_PACKAGE_PREFIXES when recording muzzle references

---

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java

This can happen when the profiler runs on an unsupported architecture and produces a stack trace:
```
[dd-profiler-recording-scheduler] WARN com.datadog.profiling.auxiliary.ddprof.AuxiliaryDatadogProfiler - Exception occurred while attempting to emit config event
at com.datadog.profiling.ddprof.DatadogProfiler.getVersion(DatadogProfiler.java:183)
at com.datadog.profiling.auxiliary.ddprof.AuxiliaryDatadogProfiler.emitConfiguration(AuxiliaryDatadogProfiler.java:67)
at jdk.jfr/jdk.jfr.internal.RequestEngine$RequestHook$1.run(RequestEngine.java:85)
at jdk.jfr/jdk.jfr.internal.RequestEngine$RequestHook$1.run(RequestEngine.java:81)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at …
```

fix profiler version when the profiler hasn't  loaded
