.circleci/config.yml
=> make sure base tests run when files in dd-java-agent module are modified

dd-smoke-tests/opentracing/src/main/java/datadog/smoketest/opentracing/ApiVerification.java, dd-smoke-tests/opentracing/src/main/java/datadog/smoketest/opentracing/OTWithAgentApplication.java, dd-smoke-tests/opentracing/src/main/java/datadog/smoketest/opentracing/OTWithoutAgentApplication.java
Cherry pick of c07a944 to `master`
=> [🍒] Add dd-api sanity check to dd-trace-ot smoke test

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/Configuration.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationComparerTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ProbeMetricsOnDemandTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/TransformerDefinitionMatcherTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/LogProbeTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
Add support for incoming debugger log probes.
Add in debugger configuration and deserialization model
Configuration model for new debugger log probes
=> Add log probe configuration

dd-java-agent/instrumentation/spring-data-1.8/build.gradle
=> Limit spring-data-commons test version

.github/workflows/lib-injection.yaml, .gitlab-ci.yml
=> Update lib injection publishing after 1.0.0

dd-trace-api/src/test/groovy/datadog/trace/api/DDSpanIdTest.groovy, dd-trace-api/src/test/groovy/datadog/trace/api/DDTraceIdTest.groovy
Test that the `IdGenerationStrategy` at least returns some different ids.
=> Test some uniqueness in IdGenerationStrategy

communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java, dd-java-agent/agent-profiling/profiling-auxiliary-async/build.gradle, dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/AppSecSystemSpecification.groovy, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsCheckpointer.java
This PR keeps cleaning the code base after the Java 7 removal.
=> Remove some Java 7 indirections

dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/directallocation/DirectAllocationTotalEvent.java, dd-java-agent/instrumentation/java-directbytebuffer/src/test/groovy/DirectAllocationTrackingTest.groovy
=> change name of allocation source in DirectAllocationTotalEvent

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/SourceType.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/SourceTypeTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/VulnerabilityEncodingTest.groovy
Align IAST source types with the ones defined in the spec
=> Align source types with the spec

.github/CODEOWNERS
=> update codeowners to request profiling reviews to changes to profiling code assets

dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakCipherInstrumentationCallSite.java, dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakHashInstrumentationCallSite.java, dd-java-agent/instrumentation/java-security/src/test/groovy/test/WeakCipherTest.groovy, dd-java-agent/instrumentation/java-security/src/test/groovy/test/WeakHashTest.groovy, dd-java-agent/instrumentation/java-security/src/test/java/foo/bar/TestSuite.java
There where a missing call sites for the weak hash and cipher instrumentations
=> Add missing call sites for weak hash an cipher

dd-java-agent/instrumentation/spring-webmvc-5.3/src/main/java/datadog/trace/instrumentation/springweb/ServletPathRequestFilterInstrumentation.java
=> [🍒] Only add OrderedServletPathRequestFilter when Filter interface is available

dd-trace-core/src/test/groovy/datadog/trace/common/sampling/DeterministicSamplerTest.groovy
Speeds up this test from > 30s to < 1s
=> speed up test cutoff calculation

dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/RangesTest.groovy
=> Improve tests for Ranges#rangesProvidedFor in IAST

dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy, dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
=> disable native stackwalking by default

dd-trace-api/src/main/java/datadog/trace/api/config/IastConfig.java
=> Change IAST max concurrent requests setting to align with spec

gradle/dependencies.gradle
Picks up https://github.com/DataDog/async-profiler/releases/tag/DD-20221202
=> bump async-profiler to 20221202

CONTRIBUTING.md
Remove confusing text as environment variables are also required for building from the IDE. See #4357
=> fix(doc): Update contributing requirements

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentTransformerBuilder.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperScanner.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
For native-image we need to inject complex class hierarchies and manually listing all classes is not scalable and too fragile.
=> Support transitive injection of helper classes

gradle/dependencies.gradle
* https://github.com/DataDog/async-profiler/releases/tag/DD-20221204
* https://github.com/DataDog/async-profiler/releases/tag/DD-20221212
* https://github.com/DataDog/async-profiler/releases/tag/DD-20221213
* https://github.com/DataDog/async-profiler/releases/tag/DD-20221216
=> upgrade to async-profiler 20221216

buildSrc/build.gradle.kts, buildSrc/src/test/groovy/InstrumentPluginTest.groovy, gradle/dependencies.gradle
https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.20
Main item of interest to us:
* Avoid stack overflow error when type variable cannot be resolve during error message generation
=> byte-buddy 1.12.20

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/SourceType.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/SourceTypeTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/source/WebModuleTest.groovy, dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java, dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/ServletRequestCallSite.java, dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletRequestCallSiteTest.groovy, dd-java-agent/instrumentation/servlet/src/test/java/datadog/smoketest/controller/TestHttpServletRequestCallSiteSuite.java, internal-api/src/main/java/datadog/trace/api/iast/source/WebModule.java
Add support for tainting of header names and values
=> Add support for tainting headers

telemetry/build.gradle, telemetry/src/main/java/datadog/telemetry/RequestBuilder.java, telemetry/src/test/groovy/datadog/telemetry/RequestBuilderSpecification.groovy
Serializer didn't know how to handle `Number` objects.
=> Fix serialization of telemetric metrics

dd-trace-core/src/main/java/datadog/trace/common/writer/RemoteWriter.java, dd-trace-core/src/main/java/datadog/trace/common/writer/SpanSamplingWorker.java, dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java, dd-trace-core/src/test/groovy/datadog/trace/common/writer/SpanSamplingWorkerTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
Introduce a NOOP implementation of `SingleSpanSampler` to simplify null checks from `TraceProcessingWorker`.
=> Minor refactoring about trace metrics

buildSrc/src/main/groovy/MuzzlePlugin.groovy, dd-java-agent/instrumentation/elasticsearch/transport-2/transport-2.gradle, dd-java-agent/instrumentation/elasticsearch/transport-5.3/transport-5.3.gradle, dd-java-agent/instrumentation/elasticsearch/transport-5/transport-5.gradle, dd-java-agent/instrumentation/elasticsearch/transport-6/transport-6.gradle, dd-java-agent/instrumentation/elasticsearch/transport-7.3/transport-7.3.gradle, dd-java-agent/instrumentation/elasticsearch/transport/transport.gradle, dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy, dd-java-agent/instrumentation/rabbitmq-amqp-2.7/rabbitmq-amqp-2.7.gradle, dd-java-agent/instrumentation/reactor-core-3.1/reactor-core-3.1.gradle, dd-java-agent/instrumentation/spring-data-1.8/spring-data-1.8.gradle, dd-java-agent/instrumentation/spring-jms-3.1/spring-jms-3.1.gradle, dd-java-agent/instrumentation/spring-rabbit/spring-rabbit.gradle, dd-java-agent/instrumentation/spring-scheduling-3.1/spring-scheduling-3.1.gradle, dd-java-agent/instrumentation/spring-webflux-5/spring-webflux-5.gradle, dd-java-agent/instrumentation/spring-webmvc-3.1/spring-webmvc-3.1.gradle
=> Cherry pick dependency and muzzle fixes to release/v0.x

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
It doesn't seem to be crashing anymore.
=> Reenable appsec on IBM J9

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerSpan.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTracer.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Instrumentor.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/SnapshotInstrumentor.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/SpanInstrumentor.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Types.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanProbe.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTracerTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ProbeInstrumentationTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanProbeInstrumentationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
Add object model into bootstrap for abstracting span API manipulation
Add Span Probe instrumentation for method probe
generate spans for span probes
=> Add Span Probe instrumentation for method probe

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java, dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentJar.java, telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
New command line tool to scan dependencies in a jar/war file or in a folder
Provide a tool that gathers more information that what it is stored in the backend to be able to debug weird scenarios
=> AgentCLI command to debug detected dependencies

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentTransformerBuilder.java, dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/InjectContextFieldMatcher.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsState.java, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactoryForkedTest.groovy
Small cleanup task that will also help with further refactoring
=> Refactor context field checks to avoid conjunction object

dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/ApacheHttpAsyncClientInstrumentation.java, dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/DelegatingRequestChannel.java, dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/DelegatingRequestProducer.java, dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/HttpAsyncClientExchangeHandlerInstrumentation.java, dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/TraceContinuedFutureCallback.java, dd-java-agent/instrumentation/apache-httpclient-5/src/test/groovy/ApacheHttpAsyncClientTest.groovy
Provides instrumentation and distributed tracing for apache httpclients5 async
=> apache httpclient5 async instrumentation

dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/ApacheHttpAsyncClientInstrumentation.java
Change http async client 5 instrumentation : Use scope instead of span to capture error details for profiling.
=> use scope across jointpoints in httpclient5 instrumentation

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/benchmark/StaticEventLogger.java, dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java
Added events logging into CSV to track initialisation time.
This changes is a part of initiative to integrate microbenchmarking platform with java tracer
=> Tracer startup benchmark events

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/DSL.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/JsonToExpressionConverter.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/IndexExpression.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/ListValue.java, dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java, dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_07.json
to support array, list and map accesses
=> Add index operator in Expression Language

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastTag.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/IastTagTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
Adds the `_dd.iast.enabled` tag to custom spans
=> Add _dd.iast.enabled tag to custom spans

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
At same location they are duplicated and handle specially. 
Log template (summary) for duplicated probes was not processed.
Duplicated method log probes had the same log template
=> Fix method log probes at same location

dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java
This avoids a potential issue where the netty integration might capture the SQS scope in a continuation, but never complete/cancel it. (see `AwsHttpClientInstrumentation` for more discussion about the interaction between these two instrumentations.)
=> Delay activating next iteration scope when SQS polling until after netty call is complete

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/InjectContextFieldMatcher.java, dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/MuzzleMatcher.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextMatcher.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleCheck.java
Small refactoring of context-store/muzzle matchers in preparation for reworking how we install matchers.
=> Miscellaneous matcher cleanup

dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
=> Do not exclude IAST instrumentation in com.datadog.demo

gradle/dependencies.gradle
=> Java profiler library 0.10.0

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
if captureSnapshot=true 1 snapshot per second
if captureSnapshot=false 5000 snapshots per second
=> Add default rate limit for not capturing Log probe

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AbstractTransformerBuilder.java, dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java, dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentTransformerBuilder.java, dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/LegacyTransformerBuilder.java, dd-java-agent/agent-builder/src/test/groovy/datadog/trace/agent/test/DefaultInstrumenterForkedTest.groovy, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java, dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java, internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
Preparation to support an alternative approach for installing multiple matchers and transformers with byte-buddy.
=> Support alternative agent install

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/DSL.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/JsonToExpressionConverter.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/ProbeCondition.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/ValueScript.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/ContainsExpression.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/EndsWithExpression.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/MatchesExpression.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/StartsWithExpression.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/StringPredicateExpression.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/SubStringExpression.java, dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java, dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/ContainsExpressionTest.java, dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/EndsWithExpressionTest.java, dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/MatchesExpressionTest.java, dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/StartsWithExpressionTest.java, dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/SubStringExpressionTest.java, dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_08.json, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
Add following operations:
- substring
- startsWith
- endsWith
- contains
- matches
=> Add string operations for Expression Language

dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/ClientCallImplInstrumentation.java
Using Kotlin gPRC client, `io.grpc.internal.ClientCallImpl.cancel()` can be called before `io.grpc.internal.ClientCallImpl.closeObserver()` leading to no handle the client error.
This PR adds the error handling in `cancel` too. 
This issue was discovered by a customer.
=> feat(grpc): Improve error status handling

.gitlab-ci.yml
=> Allow deploying to DI backend

.github/workflows/lib-injection.yaml
Recent changes in system-tests caused failures in dd-trace-xx. Fix
=> Fix lib-injection tests (system-tests)

dd-java-agent/appsec/src/main/resources/default_config.json
Update ASM event rules to 1.5.0. See https://github.com/DataDog/appsec-event-rules/releases/tag/1.5.0
=> Update ASM event rules to 1.5.0

.github/workflows/lib-injection.yaml
=> Use fixed commits for system-tests/lib-injection

dd-java-agent/appsec/build.gradle
Bumps libsqreen to 5.4.0 (libddwaf to 1.6.2)
=> Bump libddwaf to 1.6.2

.github/workflows/lib-injection.yaml
=> Fix lib-injection tests

.github/workflows/lib-injection-manual-release.yaml
=> Attempt a manual publish pipeline

.github/workflows/lib-injection-manual-release.yaml
=> Fixed issues with lib injection manual publish after testing

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java, dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/DebuggerTestApplication.java, dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/TestApplicationHelper.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/DebuggerIntegrationTest.java
before loading the class to be instrumented wait for the transformer including the probe configs to be installed
Fix racy smoke tests
=> Fix race condition with transformer in smoke tests

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java, dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingIntegration.java
If users find the feature flag here we don't want them using it at the moment as the results are unsatisfactory. We will expand on the same idea in future, so keeping the rest of the changes in place.
=> unhook profiler queueing time

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/DebuggerIntegrationTest.java
* https://github.com/DataDog/dd-trace-java/issues/4696
* https://github.com/DataDog/dd-trace-java/issues/4690
=> More flaky test marks

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/SpanInstrumentor.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanProbeInstrumentationTest.java
=> fix span's ResourceName package representation

dd-java-agent/instrumentation/spymemcached-2.12/src/main/java/datadog/trace/instrumentation/spymemcached/CompletionListener.java, dd-java-agent/instrumentation/spymemcached-2.12/src/main/java/datadog/trace/instrumentation/spymemcached/MemcacheClientDecorator.java, dd-java-agent/instrumentation/spymemcached-2.12/src/test/groovy/datadog/trace/instrumentation/spymemcached/SpymemcachedTest.groovy
Naming schema changes for v1 - memcached:
* service: `{{DD_SERVICE}}-memcached`
* operation: `memcached.command`
=> Naming schema: memcached

.gitlab-ci.yml
This PR introduces automatic deployment for demo services on every commit to the default branch.
=> Automatic demo service deployment

dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
=> test context propagation when executor wrapped in ExecutorCompletionService

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Instrumentor.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/SpanInstrumentor.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanProbeInstrumentationTest.java
add a tag to the span with the probe id
Identify span generated by Dynamic Instrumentation
=> Add ProbeId as span tag

index.yml
=> Add 1.8.3 java release.

dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseClientDecorator.java, dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseOnSubscribe.java, dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/test/groovy/CouchbaseAsyncClientTest.groovy, dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/test/groovy/CouchbaseClientTest.groovy, dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringRepositoryTest.groovy, dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/test/groovy/util/AbstractCouchbaseTest.groovy, dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java/datadog/trace/instrumentation/couchbase_31/client/CouchbaseClientDecorator.java, dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java/datadog/trace/instrumentation/couchbase_31/client/DatadogRequestTracer.java, dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/test/groovy/CouchbaseClient31Test.groovy, dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java/datadog/trace/instrumentation/couchbase_32/client/CouchbaseClientDecorator.java, dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java/datadog/trace/instrumentation/couchbase_32/client/DatadogRequestTracer.java, dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/test/groovy/CouchbaseClient32Test.groovy, dd-java-agent/instrumentation/rxjava-1/src/main/java/datadog/trace/instrumentation/rxjava/TracedOnSubscribe.java, internal-api/src/main/java/datadog/trace/api/naming/v0/DatabaseNamingV0.java
v1 naming schema changes for couchbase:
* service: `{{DD_SERVICE}}-couchbase`
* operation: `couchbase.query`
=> naming schema: couchbase

dd-java-agent/appsec/build.gradle, dd-java-agent/appsec/src/jmh/java/datadog/appsec/benchmark/PowerwafBenchmark.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfig.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecUserConfig.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/CollectedUserConfigs.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/CurrentAppSecConfig.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecUserConfigDeserializerSpecification.groovy, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
Will wait for 1.8.2 though, so that https://github.com/DataDog/libddwaf/pull/140#pullrequestreview-1303252952 is included
=> Upgrade to libsqreen 6.1.0/libddwaf 1.8.2

dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpServerInstrumentationTest.groovy, dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpServerDecorator.java, dd-java-agent/instrumentation/undertow/undertow-2.0/src/test/groovy/UndertowServletTest.groovy, internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
v1 naming changes for akka http server :
* operation: http.server.request
=> service naming: akka http server

dd-java-agent/instrumentation/liberty-20/build.gradle, dd-java-agent/instrumentation/liberty-20/src/main/java/datadog/trace/instrumentation/liberty20/LibertyDecorator.java, dd-java-agent/instrumentation/liberty-20/src/test/groovy/datadog/trace/instrumentation/liberty20/Liberty20Test.groovy
v1 naming schema changes for openliberty:
=> naming schema: openliberty

telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
=> Remove unused RequestBuilder from Telemetry

.circleci/config.yml
=> Update remote docker to latest (default) version

dd-java-agent/appsec/src/main/resources/default_config.json
See https://github.com/DataDog/appsec-event-rules/releases/tag/1.5.2
=> Update ASM rules to 1.5.2

dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
=> update profiler smoke test flags

dd-java-agent/appsec/build.gradle
Improves detection of libc.
Solves https://github.com/DataDog/dd-trace-java/issues/4833
=> Update to libsqreen 6.1.1: Improve libc detection

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategy.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextInjector.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextMatcher.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsState.java, internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
Separating this out into its own PR to avoid cluttering up a related PR.
=> Miscellaneous clean-up of comments/logging

dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java
Flaky https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/22499/workflows/bea141fc-f508-4344-822f-659b2efc4a08/jobs/627236/tests
=> Mark test as flaky

telemetry/src/main/java/datadog/telemetry/HostInfo.java, telemetry/src/main/java/datadog/telemetry/RequestBuilder.java, telemetry/src/main/java/datadog/telemetry/TelemetryService.java, telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java, telemetry/src/main/java/datadog/telemetry/api/Application.java, telemetry/src/main/java/datadog/telemetry/api/DistributionSeries.java, telemetry/src/main/java/datadog/telemetry/api/Distributions.java, telemetry/src/main/java/datadog/telemetry/api/Host.java, telemetry/src/main/java/datadog/telemetry/api/LogMessage.java, telemetry/src/main/java/datadog/telemetry/api/LogMessageLevel.java, telemetry/src/main/java/datadog/telemetry/api/Logs.java, telemetry/src/main/java/datadog/telemetry/api/Metric.java, telemetry/src/main/java/datadog/telemetry/api/Product.java, telemetry/src/main/java/datadog/telemetry/api/ProductError.java, telemetry/src/main/java/datadog/telemetry/api/Products.java, telemetry/src/main/java/datadog/telemetry/api/RequestType.java, telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
Implemented latest changes according to specification for Telemetry API v1
Requires for metrics over telemetry
=> Telemetry API v1 updated to the latest version

dd-java-agent/instrumentation/jdbc/src/jmh/java/datadog.trace.instrumentation.jdbc/SQLCommenterBenchmark.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractConnectionInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractPreparedStatementInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DBMCompatibleConnectionInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DBMTraceInjectionConnectionInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DefaultConnectionInstrumentation.java, dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java, dd-java-agent/instrumentation/jdbc/src/test/groovy/RemoteJDBCInstrumentationTest.groovy
=> Fix tests / re-org logic a bit / check call stack depth before mutating sql 

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java, dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java, dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
This lets users use these names for custom context.
=> add _dd.trace prefix to built in tracing based profiling attributes

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/CurrentAppSecConfig.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/MergedAsmData.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy, dd-java-agent/appsec/src/test/resources/rules_with_data_config.json
Rule data provided in the waf rules file was being ignored.
=> Fix merge of rule data provided in the config file

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java, dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerContextSetter.java, dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingIntegration.java, dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingScope.java, dd-java-agent/agent-profiling/profiling-ddprof/src/test/java/com/datadog/profiling/ddprof/DatadogProfilerTest.java, dd-java-agent/testing/build.gradle, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TestProfilingContextIntegration.groovy, dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/ProfilingTestApplication.java, dd-trace-api/build.gradle, dd-trace-api/src/main/java/datadog/trace/api/experimental/Profiling.java, dd-trace-api/src/main/java/datadog/trace/api/experimental/ProfilingContext.java, dd-trace-api/src/main/java/datadog/trace/api/experimental/ProfilingContextSetter.java, dd-trace-api/src/main/java/datadog/trace/api/experimental/ProfilingScope.java, dd-trace-api/src/main/java/datadog/trace/api/internal/InternalTracer.java, dd-trace-api/src/test/groovy/datadog/trace/api/EventTrackerTest.groovy, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ProfilingContextIntegration.java
=> rework profiling context API

dd-java-agent/instrumentation/graphql-java-14.0/src/main/java/datadog/trace/instrumentation/graphqljava/ExecutionInstrumentationContext.java, dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
Resolves #4961
Align with dd-trace-js
N/A
=> Rename GraphQL query->source tag to align it with the dd-trace-js instrumentaion

dd-trace-core/src/main/java/datadog/trace/common/writer/RemoteWriter.java, dd-trace-core/src/main/java/datadog/trace/common/writer/SpanSamplingWorker.java, dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
Adds some missing debug statements.
This was useful while debugging system tests.
N/A
=> Add missing debug statements

.github/CODEOWNERS
=> Update codeowners for appsec

dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
=> Disable flaky tests

gradle/dependencies.gradle
=> bump jplib to 0.28.0

dd-java-agent/agent-debugger/build.gradle, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
=> Fix flakiness of serialization timeout tests

internal-api/src/main/java/datadog/trace/api/Config.java
Reverts DataDog/dd-trace-java#5004
=> Revert "disable datadog profiler by default"

buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/impl/AdviceGeneratorImpl.java, buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/impl/CallSiteSpecification.java, buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/util/ErrorCode.java, buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/AdviceGeneratorTest.groovy, dd-java-agent/agent-iast/src/jmh/java/com/datadog/iast/propagation/StringBuilderInitBenchmark.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/PropagationModuleTest.groovy, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteUtils.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/csi/CallSiteAdvice.java, dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteUtilsTest.groovy, dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringBuilderCallSite.java, dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringCallSite.java, dd-java-agent/instrumentation/java-net/src/main/java/datadog/trace/instrumentation/java/net/URICallSite.java, dd-java-agent/instrumentation/java-net/src/test/groovy/datadog/trace/instrumentation/java/net/URICallSIteTest.groovy, dd-java-agent/instrumentation/java-net/src/test/java/foo/bar/TestURICallSiteSuite.java, internal-api/src/main/java/datadog/trace/api/iast/PropagationTypes.java, internal-api/src/main/java/datadog/trace/api/iast/propagation/PropagationModule.java
Add required propagation call sites for java.net.URI in IAST
=> Add IAST propagation for java.net.URI

dd-java-agent/appsec/src/main/resources/default_config.json
See https://github.com/DataDog/appsec-event-rules/releases/tag/1.6.0
=> Upgrade WAF rules to v1.6.0

dd-java-agent/instrumentation/resteasy-appsec/src/main/java/datadog/trace/instrumentation/resteasy/FormParamInjectorAdvice.java
=> Remove stray println from RESTEasy IAST instrumentation

buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/impl/ext/IastExtension.java, buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/BaseCsiPluginTest.groovy, buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/ext/IastExtensionTest.groovy
This PR fixes the gradle build error on Windows platform.
=> Add Windows support to call-site-instrumentation plugin

dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/IastQueryInstrumentation.java, dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/IastQueryInstrumentationTest.groovy, dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/IastQueryInstrumentation.java, dd-java-agent/instrumentation/hibernate/core-4.0/src/test/groovy/IastQueryInstrumentationTest.groovy
Add IAST support to hibernate queries for SQL injection
=> Add IAST support to hibernate queries

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpanContext.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelTracer.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
* Add sampled flag support for span context
* Fix span id format from span context
* Fix span resource name
Those changes come from parametric test feedback.
=> [OTel] Improve OpenTelemetry instrumentation

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
https://github.com/DataDog/dd-trace-java/pull/5048#discussion_r1163086128
=> Remove commit method in Snapshot

dd-java-agent/appsec/build.gradle, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfig.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecUserConfig.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/CurrentAppSecConfig.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
Updates to libsqreen 6.2.0 and starts using its support for custom_rules.
=> Upgrade to libddwaf 1.9.0 (libsqreen 6.2.0)

.circleci/config.yml
=> Avoid a second Python install (and build) in parametric-tests

.circleci/config.yml, build.gradle
=> Split check job to use the right build caches

.circleci/config.yml, buildSrc/build.gradle.kts, buildSrc/call-site-instrumentation-plugin/build.gradle.kts, buildSrc/src/main/groovy/CallSiteInstrumentationPlugin.groovy, dd-java-agent/instrumentation/build.gradle, dd-java-agent/instrumentation/junit-4.10/build.gradle, dd-java-agent/instrumentation/scala-promise/build.gradle, dd-smoke-tests/java9-modules/build.gradle, dd-smoke-tests/vertx-3.4/application/gradle/wrapper/gradle-wrapper.properties, dd-smoke-tests/vertx-3.9-resteasy/application/gradle/wrapper/gradle-wrapper.properties, dd-smoke-tests/vertx-3.9/application/gradle/wrapper/gradle-wrapper.properties, gradle/configure_tests.gradle, gradle/dependencies.gradle, gradle/forbiddenapis.gradle, gradle/java_no_deps.gradle, gradle/spotless.gradle, gradle/test-suites.gradle, gradle/wrapper/gradle-wrapper.properties
Upgrades `gradle` to version 8.1
All our memory patches should be in the upstream
=> Upgrade gradle to 8.1

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
=> disable ddprof allocation profiling

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java, dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/ProbeImplementation.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/LogMessageTemplateBuilder.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogMessageTemplateBuilderTest.java
Store specific values in each Status depending ont he probe type
https://github.com/DataDog/dd-trace-java/pull/5048#discussion_r1163335694
=> Create specific status for Log & Span Decoration

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java
=> Add support of line probe for span decoration

.gitlab-ci.yml, .gitlab/benchmarks.yml
=> Enable continuous benchmarks in Gitlab

dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
=> Re-enable rule toggling test for AppSec

dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
=> Add AppSec blocking smoke test

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Location.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/LocationTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/VulnerabilityEncodingTest.groovy
=> Add method to vulnerability location in IAST

dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
reverting https://github.com/DataDog/dd-trace-java/pull/5109
this comment: https://github.com/DataDog/dd-trace-java/pull/5109#discussion_r1175818508
=> [data streams] Add back consumer group as hashable

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/TypeInfoCache.java
If we can assume that class names will be unique (at least when caching a particular piece of information) then we can simplify the type-info cache and omit the class-loader and class-file elements. This refactoring will be used in a follow-up PR, the new feature is separated out here to make reviewing easier.
=> Provide simpler type-info cache for when we know class names are unique

dd-java-agent/appsec/src/main/resources/default_config.json
See https://github.com/DataDog/appsec-event-rules/releases/tag/1.7.0
=> Upgrade WAF rules to v1.7.0

dd-trace-core/src/main/java/datadog/trace/lambda/SkipAbstractTypeJsonSerializer.java, dd-trace-core/src/test/groovy/datadog/trace/lambda/SkipTypeJsonSerializerTest.groovy
- error handling around deserialization
- make sure that platform classes can be skipped if not deserializable
- add unit tests against main used event (pojo, sns, sqs, gateway)
fix stack overflow issue
=> [Serverless] fix stackoverflow json deserialization

dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
Add inclusion for `org.springframework.security.web.authentication.*`
=> Add inclusion for org.springframework.security.web.authentication.*

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
Avoid spammy logs when batch uploader fails repeatedly
=> Change regular logger to rate limited logger

dd-java-agent/appsec/build.gradle
=> Upgrade to libddwaf v1.10.0 (libsqreen 6.3.0)

dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java, dd-smoke-tests/spring-boot-2.6-webmvc/src/test/groovy/IastSpringBootSmokeTest.groovy, dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java, dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
Adds a few smoke tests for the SSRF support in IAST
=> Add SSRF smoke tests for IAST

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/telemetry/IastTelemetry.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/telemetry/IastTelemetryImpl.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/telemetry/IastTelemetryTest.groovy, dd-smoke-tests/spring-boot-2.6-webmvc/src/test/groovy/IastSpringBootSmokeTest.groovy, dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
Unwraps the telemetry tags included by IAST in spans
=> Unwrap IAST telemetry tags stored in spans

dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatServerInstrumentation.java, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
=> set traceid and spanid on catalina request

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/PrettyPrintVisitor.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/Visitor.java, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/NullValue.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/MoshiConfigTestHelper.java
=> Add null support for metric values

internal-api/src/main/java/datadog/trace/api/Config.java
Fix environment variable names for IAST redaction
=> Fix environment variables for IAST redaction

dd-java-agent/instrumentation/kafka-clients-0.11/build.gradle, dd-java-agent/instrumentation/kafka-streams-0.11/build.gradle
=> Fix assertj-core version for Kafka tests

telemetry/src/test/groovy/datadog/telemetry/TelemetryRunnableSpecification.groovy
Required for https://github.com/DataDog/dd-trace-java/pull/5227
=> Fix TelemetryRunnableSpecification

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/TPEHelper.java, dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/ProfilingTestApplication.java, dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java, dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java, dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/SmokeTestUtils.java
=> reenable profiling tests

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/ValueScript.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/LogMessageTemplateBuilder.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java, dd-java-agent/agent-debugger/src/test/resources/test_span_decoration_probe.json
Tag values now are using string interpolation like log template
=> Change span decoration config for interpolation

dd-java-agent/appsec/src/main/resources/default_config.json, dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
See https://github.com/DataDog/appsec-event-rules/releases/tag/1.7.1
=> Update to ASM rules 1.7.1

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWS1ClientTest.groovy, dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java, dd-java-agent/instrumentation/aws-java-sdk-2.2/src/test/groovy/Aws2ClientTest.groovy, internal-api/src/main/java/datadog/trace/api/naming/v1/PeerServiceNamingV1.java, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InstrumentationTags.java
Adds `peer.service` for aws sdk managed services
=> add peer service for eligible aws sdk services

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
=> Fix format (spotless)

.circleci/config.yml
* https://github.com/DataDog/system-tests/pull/1212
=> Update system-tests to 6e40e4a9ba37df994cbe0bf5fbc872c25d16a0d4

dd-java-agent/instrumentation/jackson-core/build.gradle, dd-java-agent/instrumentation/jackson-core/jackson-core-1/src/main/java/datadog/trace/instrumentation/jackson/codehouse/core/Json1FactoryInstrumentation.java, dd-java-agent/instrumentation/jackson-core/jackson-core-1/src/main/java/datadog/trace/instrumentation/jackson/codehouse/core/Json1ParserInstrumentation.java, dd-java-agent/instrumentation/jackson-core/jackson-core-1/src/test/groovy/Json1FactoryInstrumentationTest.groovy, dd-java-agent/instrumentation/jackson-core/jackson-core-1/src/test/groovy/Json1ParserInstrumentationTest.groovy, dd-java-agent/instrumentation/jackson-core/src/main/java/datadog/trace/instrumentation/jackson/core/Json2FactoryInstrumentation.java, dd-java-agent/instrumentation/jackson-core/src/main/java/datadog/trace/instrumentation/jackson/core/Json2ParserInstrumentation.java, dd-java-agent/instrumentation/jackson-core/src/test/groovy/Json2FactoryInstrumentationTest.groovy, dd-java-agent/instrumentation/jackson-core/src/test/groovy/Json2ParserInstrumentationTest.groovy
Fix the matchers in the instrumentation and add support for SSRF while parsing a tainted URL
=> Fix Json2FactoryInstrumentation matchers and add support for SSRF

dd-java-agent/instrumentation/tomcat-5.5/src/latestDepTest/groovy/InactiveAppSecTest.groovy, dd-java-agent/instrumentation/tomcat-5.5/src/latestDepTest/groovy/TomcatServer.groovy, dd-java-agent/instrumentation/tomcat-5.5/src/latestDepTest/groovy/TomcatServletTest.groovy, dd-java-agent/instrumentation/tomcat-appsec-7/src/main/java/datadog/trace/instrumentation/tomcat7/ParameterCollector.java, dd-java-agent/instrumentation/tomcat-appsec-7/src/main/java/datadog/trace/instrumentation/tomcat7/ParsePartsInstrumentation.java
Solves  https://github.com/DataDog/dd-trace-java/issues/5298
Backport of https://github.com/DataDog/dd-trace-java/pull/5301 to v1.15.x.
=> Fix NPE on tomcat with appsec inactive [1.15.x backport]

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
cherry picked from https://github.com/DataDog/dd-trace-java/tree/release/v1.15.x
=> Disabled v05 by default (#5317)

.circleci/config.yml
=> Update system-tests to 1aab7b726729ed4fea324169f66c36340b246558

dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
while investigating the cause of this flakiness
=> Disable debugger flaky test

dd-java-agent/agent-profiling/profiling-auxiliary-ddprof/src/main/java/com/datadog/profiling/auxiliary/ddprof/AuxiliaryDatadogProfiler.java, gradle/dependencies.gradle
* Upgrades ddprof with [fixes](https://github.com/DataDog/java-profiler/releases/tag/v_0.45.0)
* Start refactoring to encapsulate logic in dd-trace-java which should be in the profiler
=> bump ddprof to 0.45.0

dd-java-agent/appsec/build.gradle, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFInitializationResultReporter.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
=> Upgrade to libddwaf 1.11.0

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/InsecureCookieModuleImpl.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/NoHttpOnlyCookieModuleImpl.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/UnvalidatedRedirectModuleImpl.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/InsecureCookieModuleTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/NoHttpCookieModuleTest.groovy, dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/JakartaWSResponseInstrumentation.java, dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/JavaxWSResponseInstrumentation.java, dd-java-agent/instrumentation/jersey/src/test/groovy/datadog/trace/instrumentation/jersey/JakartaWSResponseInstrumentationTest.groovy, dd-java-agent/instrumentation/resteasy-appsec/src/main/java/datadog/trace/instrumentation/resteasy/JavaxWSResponseInstrumentation.java, dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/HttpServletResponseInstrumentation.java, dd-java-agent/instrumentation/servlet-common/src/test/groovy/HttpServletResponseInstrumentationTest.groovy, dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaHttpServletResponseInstrumentation.java, dd-java-agent/instrumentation/servlet/request-5/src/test/groovy/JakartaHttpServletResponseInstrumentationTest.groovy, dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServerResponseInstrumentation.java, dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/Vertx34InsecureCookieTest.groovy, internal-api/src/main/java/datadog/trace/api/iast/InstrumentationBridge.java, internal-api/src/main/java/datadog/trace/api/iast/sink/HttpHeaderModule.java, internal-api/src/main/java/datadog/trace/api/iast/sink/HttpResponseHeaderModule.java, internal-api/src/main/java/datadog/trace/api/iast/sink/InsecureCookieModule.java, internal-api/src/main/java/datadog/trace/api/iast/sink/NoHttpOnlyCookieModule.java, internal-api/src/main/java/datadog/trace/api/iast/sink/UnvalidatedRedirectModule.java, internal-api/src/test/groovy/datadog/trace/api/iast/InstrumentationBridgeTest.groovy
Refactor to simplify how we deal with response headers / cookies
=> Refactor HttpHeaderModule.java

dd-java-agent/agent-bootstrap/src/main/resources/META-INF/native-image/com.datadoghq/dd-java-agent/reflect-config.json, dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java
* Fix boolean method name in reflect-config.json
* Defer some JNR classes from build-time to run-time
=> Minor fixes for Quarkus Native

dd-java-agent/instrumentation/spark/src/test/groovy/SparkTest.groovy
Fix the spark flaky test `generate error tags in failed spans` by correctly waiting for child spans to finish before closing the spark session
=> Fix spark flaky test

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/ClassFileLocators.java
as it might throw SecurityException if a security manager is installed, and we'd then lose the successful result
=> Avoid calling ClassLoader.getParent() once we've found a class resource

.circleci/config.yml
=> Update system-tests to 733e06a4e535c970fc62a33c7eca7c00b52a730c

dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/ReaderInterceptorExecutorInstrumentation.java
=> Fix integration name for jersey ReaderInterceptorExecutorInstrumentation

telemetry/src/main/java/datadog/telemetry/dependency/JbossVirtualFileHelper.java
These are inocuous and confusing to users.
=> Log dependency collection errors in JBoss to debug level

dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/ReaderInterceptorExecutorInstrumentation.java
=> Fix jersey ReaderInterceptorExecutorInstrumentation base class

gradle/dependencies.gradle
Contains a candidate fix for a buffer overflow reported in #5449
=> upgrade to ddprof 0.52.0

.circleci/config.yml
=> test on ubuntu openjdk17

.github/workflows/lib-injection.yaml
fix lib-injection tests pipeline
=> [system-tests] fix lib injection

.circleci/config.yml
* https://github.com/DataDog/system-tests/pull/1281
* https://github.com/DataDog/system-tests/pull/1287
* https://github.com/DataDog/system-tests/pull/1290
* https://github.com/DataDog/system-tests/pull/1301
* https://github.com/DataDog/system-tests/pull/1297
* https://github.com/DataDog/system-tests/pull/1299
* https://github.com/DataDog/system-tests/pull/1320
* https://github.com/DataDog/system-tests/pull/1311
* https://github.com/DataDog/system-tests/pull/1315
=> Update system-tests to 6f47824f32add0efbd8329707c7fb27a437f0b23

.circleci/config.yml
=> Update CI caches for Gradle 8.2

dd-java-agent/instrumentation/maven-3.2.1/src/test/groovy/MavenTest.groovy
Stabilises flaky Maven instrumentation test.
The test runs a Maven build with Maven instrumentation enabled. As part of running the build, Maven downloads project dependencies. Sometimes download fails because of intermittent network issues.
This change adds "warmup runs" that execute `dependency:go-offline` goal (which does nothing other than asks Maven to resolve and download the project dependencies). Warmup is executed up to 3 times, until either dependencies are resolved successfully, or we run out of retry attempts.
Reduce test flakiness.
A similar fix was done for Maven smoke test previously. This test is a different one (instrumentation test).
=> Stabilize flaky Maven instrumentation test

dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/JakartaWSResponseInstrumentation.java, dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/JavaxWSResponseInstrumentation.java, dd-java-agent/instrumentation/resteasy-appsec/src/main/java/datadog/trace/instrumentation/resteasy/JavaxWSResponseInstrumentation.java, dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/HttpServletResponseInstrumentation.java, dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaHttpServletResponseInstrumentation.java, dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServerResponseInstrumentation.java, dd-java-agent/instrumentation/vertx-web-3.9/src/main/java/datadog/trace/instrumentation/vertx_3_9/Vertx39HttpServertResponseInstrumentation.java, dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/core/HttpServerResponseInstrumentation.java
=> Add missing IAST guards for response headers

.circleci/config.yml
Comparison: https://github.com/datadog/system-tests/compare/6f47824f32add0efbd8329707c7fb27a437f0b23..6873c9577ddc15693a98f9683075a1b9d4e587f0
Relevant PRs:
* https://github.com/datadog/system-tests/pull/1284
* https://github.com/datadog/system-tests/pull/1323
* https://github.com/datadog/system-tests/pull/1312
* https://github.com/datadog/system-tests/pull/1295
* https://github.com/datadog/system-tests/pull/1326
* https://github.com/datadog/system-tests/pull/1248
* https://github.com/datadog/system-tests/pull/1327
* https://github.com/datadog/system-tests/pull/1328
* https://github.com/datadog/system-tests/pull/1288
* https://github.com/datadog/system-tests/pull/1316
* https://github.com/datadog/system-tests/pull/1293
* https://github.com/datadog/system-tests/pull/1333
* …
=> Update system-tests to 6873c9577ddc15693a98f9683075a1b9d4e587f0

.circleci/config.yml, dd-trace-core/src/test/groovy/datadog/trace/TracerConnectionReliabilityTest.groovy
Enables APM Test Agent Service Naming and Peer Service checks for all integrations
=> enable apm test agent service naming checks

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/PropagationModuleTest.groovy, dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringCallSite.java, dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/StringCallSiteTest.groovy, dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringSuite.java, internal-api/src/main/java/datadog/trace/api/iast/propagation/PropagationModule.java
Add String toCharArray propagation 
Needed to keep propagation in owasp benchmark
=> Add String#toCharArray taint tracking

.circleci/config.yml
Comparison: https://github.com/datadog/system-tests/compare/6873c9577ddc15693a98f9683075a1b9d4e587f0..7b39609e7bc21c951e78ed1f2ec7a88e8d042c6a
Relevant PRs:
* https://github.com/DataDog/system-tests/pull/1372
* https://github.com/DataDog/system-tests/pull/1386
* https://github.com/DataDog/system-tests/pull/1342
* https://github.com/DataDog/system-tests/pull/1335
* https://github.com/DataDog/system-tests/pull/1397
* https://github.com/DataDog/system-tests/pull/1398
* https://github.com/DataDog/system-tests/pull/1382
=> Update system-tests to 7b39609e7bc21c951e78ed1f2ec7a88e8d042c6a

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy, dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringCallSite.java, dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/StringCallSiteTest.groovy, dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringSuite.java, internal-api/src/main/java/datadog/trace/api/iast/propagation/StringModule.java
Add String#split taint tracking
Needed to keep propagation in owasp benchmark
=> Add String#split taint tracking

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/AdapterFactory.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/EvidenceAdapter.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/SourceAdapter.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sensitive/SensitiveHandler.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sensitive/SensitiveHandlerImpl.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/CharUtils.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/Ranged.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/RangedDeque.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/EvidenceRedactionTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/VulnerabilityEncodingTest.groovy, dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite.yml
Updates the redaction algorithm to be more lenient
=> Update IAST redaction algorithm

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/QueueTimeTracker.java, gradle/dependencies.gradle
=> Upgrade to ddprof 0.65.0

buildSrc/src/main/groovy/MuzzlePlugin.groovy
Uses `evaluationDependsOn` to prevent errors with configureondemand. This makes some usages of afterEvaluate {} unnecessary.
agent-tooling needs now to be added explicitly to a classloader because not using project.afterEvaluate {} means the classpath calculation can't rely on agent-tooling being added before to the runtimeClasspath configuration of the project by subproject.afterEvalute {} in instrumentation/build.gradle.
=> Fix MuzzlePlugin with configureondemand

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastSystem.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/SinkModuleBase.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/TrustBoundaryViolationModuleImpl.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/CookieSecurityDetails.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/TrustBoundaryViolationModuleTest.groovy, dd-java-agent/instrumentation/servlet-common/build.gradle, dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/HttpSessionInstrumentation.java, dd-java-agent/instrumentation/servlet-common/src/test/groovy/HttpSessionInstrumentationTest.groovy, dd-java-agent/instrumentation/servlet-common/src/test/java/foo/bar/DummyHttpSession.java, dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaHttpSessionInstrumentation.java, dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy, dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java, dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java, internal-api/src/main/java/datadog/trace/api/iast/InstrumentationBridge.java, internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityMarks.java, internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityTypes.java, internal-api/src/main/java/datadog/trace/api/iast/sink/TrustBoundaryViolationModule.java
Implements trust boundary violation vulnerability detection
We need to cover all owasp vulnerabilities
=> Implemented trust boundary violation vulnerability detection

CONTRIBUTING.md
Add a note on how to properly setup git submodule for the project.
This wasn't mentioned in `CONTRIBUTING.md`
#5522
=> Git submodule setup note

.gitlab-ci.yml
Runs di downstream pipeline in different new repo.
=> Run backend CI in new repo

.circleci/config.yml
Comparison: https://github.com/datadog/system-tests/compare/7b39609e7bc21c951e78ed1f2ec7a88e8d042c6a..18afda441d6e92fe3befeddd4dd20ff558ca4f0c
* https://github.com/datadog/system-tests/pull/1411
* https://github.com/datadog/system-tests/pull/1422
=> Update system-tests to 18afda441d6e92fe3befeddd4dd20ff558ca4f0c

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelExtractedContext.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpanBuilder.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelTracerProvider.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
=> Fix possible invalid parent span using OpenTelemetry API

.gitignore, .gitlab/benchmarks.yml, benchmark/Dockerfile, benchmark/README.MD, benchmark/benchmarks.sh, benchmark/load/insecure-bank/benchmark.json, benchmark/load/insecure-bank/k6.js, benchmark/load/petclinic/benchmark.json, benchmark/load/petclinic/k6.js, benchmark/load/run.sh, benchmark/run.sh, benchmark/startup/insecure-bank/benchmark.json, benchmark/startup/petclinic/benchmark.json, benchmark/startup/run.sh, benchmark/utils/k6.js, benchmark/utils/run-k6-load-test.sh, benchmark/utils/run-on-server-ready.sh, benchmark/utils/run-sirun-benchmarks.sh, benchmark/utils/update-java-version.sh
Brings startup benchmarks code to the tracer repository and introduces new load benchmarks based on petclinic and insecure-bank
=> Add initial version of tracer benchmarks

remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java
=> Add debug log when sending RC request

.circleci/config.yml
=> Remove docker-compose install in system-tests

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastRequestContext.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastSystem.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestHeaderHandler.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HstsMissingHeaderModuleImpl.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/IastSystemTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/RequestEndedHandlerTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/RequestHeaderHandlerTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/HstsMissingHeaderModuleTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/HttpResponseHeaderModuleTest.groovy, dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy, dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java, dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java, internal-api/src/main/java/datadog/trace/api/iast/InstrumentationBridge.java, internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityTypes.java, internal-api/src/main/java/datadog/trace/api/iast/sink/HstsMissingHeaderModule.java
Detect and report HSTS header missing vulnerabilities
To cover all of the header vulnerabilities
=> HSTS missing header vulnerability detection

.circleci/config.yml
Comparison:
https://github.com/datadog/system-tests/compare/18afda441d6e92fe3befeddd4dd20ff558ca4f0c..68da674b83d7a1a1730387a3b27a1d4328392f3c
* https://github.com/DataDog/system-tests/pull/1447
* https://github.com/DataDog/system-tests/pull/1442
* https://github.com/DataDog/system-tests/pull/1450
* https://github.com/DataDog/system-tests/pull/1444
* https://github.com/DataDog/system-tests/pull/1451
* https://github.com/DataDog/system-tests/pull/1448
* https://github.com/DataDog/system-tests/pull/1439
* https://github.com/DataDog/system-tests/pull/1457
* https://github.com/DataDog/system-tests/pull/1455
* https://github.com/DataDog/system-tests/pull/1460
* https://github.com/DataDog/system-tests/pull/1463
* https://github.com/DataDog/system-tests/pull/1462
* …
=> Update system-tests to 68da674b83d7a1a1730387a3b27a1d4328392f3c

dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie, dd-java-agent/instrumentation/rabbitmq-amqp-2.7/build.gradle, dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitChannelInstrumentation.java, dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/reactorTest/groovy/ReactorRabbitMQTest.groovy
=> Fix exception in reactor-rabbit

dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigDeserializerSpecification.groovy
=> Test deserialization with unknown keys in AppSec rules

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastRequestContext.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestEndedHandler.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestHeaderHandler.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HstsMissingHeaderModuleImpl.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/UnvalidatedRedirectModuleImpl.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/XContentTypeOptionsModuleImpl.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/HttpHeader.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/IastSystemTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/RequestHeaderHandlerTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/HstsMissingHeaderModuleTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/HttpResponseHeaderModuleTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/XContentTypeOptionsModuleTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/HttpHeaderTest.groovy, internal-api/src/main/java/datadog/trace/api/iast/sink/HstsMissingHeaderModule.java, internal-api/src/main/java/datadog/trace/api/iast/sink/HttpRequestEndModule.java, internal-api/src/main/java/datadog/trace/api/iast/sink/XContentTypeOptionsModule.java
Little refactor of header handling logic to improve readability
=> Littler refactor for header handling logic

dd-java-agent/agent-debugger/build.gradle, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/uploader/BatchUploaderTest.java
=> Fix coverage of BatchUploader

dd-java-agent/instrumentation/jetty-11/build.gradle, dd-java-agent/instrumentation/jetty-9/build.gradle, dd-java-agent/instrumentation/jetty-appsec-9.3/build.gradle
=> Exclude Jetty server 12 from Jetty instrumentations support

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpan.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
This PR is a backport of #5722
=> Ensure OpenTelemetry spans are not modifiable when finished

dd-java-agent/instrumentation/servlet-common/src/test/groovy/HttpServletResponseInstrumentationTest.groovy, dd-java-agent/instrumentation/servlet-common/src/test/java/foo/bar/DummyResponse.java, dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaHttpServletResponseInstrumentation.java, dd-java-agent/instrumentation/servlet/request-5/src/test/groovy/JakartaHttpServletResponseInstrumentationTest.groovy, dd-java-agent/instrumentation/servlet/request-5/src/test/java/foo/bar/smoketest/DummyResponse.java
=> Set concrete types for the response instrumentation

dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenProjectConfigurator.java
Fixes automatic Javac plugin configuration in Maven projects that use annotation processors.
Javac plugin can be added either as a regular dependency, or as an annotation processor.
In the first case it's added to project's compile classpath, in the second case it's added to the compiler's processor classpath ("`-processorpath path` Specifies where to find annotation processors. If this option is not used, then the class path is searched for processors").
If `<annotationProcessorPaths>` property is present in Maven Compiler plugin's config, the Javac plugin has to be added there (since in that case "regular" classpath will not be searched for processors and compiler plugins - see excerpt from `javac` documentation above).
However, if this property is absent, it is better to add the plugin …
=> Fix automatic Javac plugin configuration in Maven projects that use annotation processors

dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie, dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaTimerInstrumentation.java, dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/TimerTaskInstrumentation.java, dd-java-agent/instrumentation/java-concurrent/src/test/groovy/TimerTaskContinuationTest.groovy
Support context propagation on `java.util.Timer` for non repeated executions
=> Support java.util.Timer once scheduling

dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy, dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java, dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/XssController.java, dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java, dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/XssController.java
- Add more xss tests for springboot
- Place all the XSS springboot xss endpoint in a new XssController
Test all instrumented PrintWriter instrumented methods
=> Upgrade IAST XSS smoke tests

dd-java-agent/instrumentation/java-net/src/main/java/datadog/trace/instrumentation/java/net/URLEncoderCallSite.java, dd-java-agent/instrumentation/java-net/src/test/groovy/datadog/trace/instrumentation/java/net/URLEncoderCallSiteTest.groovy, dd-java-agent/instrumentation/java-net/src/test/java/foo/bar/TestURLEncoderCallSiteSuite.java
Add java.net.URLEncoder#encode tainting support
=> Add URLEncoder tainting support

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
This PR avoids allocating a new `ContinuingScope` when the top of the scope stack is already keeping the same span alive as the continuation. Instead we increment the existing scope's reference count and cancel the continuation.
In other words instead of stacking another scope onto the stack for the same span, we collapse it into the existing scope. 
The main difference is that we cancel the continuation immediately rather than when the scope finally closes, but I believe this is acceptable because the existing scope should already be keeping the trace alive - either by the span if it's on the original thread or by a different continuation (in the existing `ContinuingScope`) if it's on a different thread.
Reduces the number of `ContinuingScope` allocations when using fork-join pools.
=> Avoid creating new ContinuingScope if the top scope is already keeping the span alive

communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
config endpoint and event platform proxy endpoint were swapped.
=> Fix debug log for endpoint discovery

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/JsonSnapshotSerializer.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/Snapshot.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java
Adding trace id and span id for both snapshot and log probes
=> Add correlation Ids for dynamic logs

dd-smoke-tests/appsec/springboot-security/src/main/java/datadog/smoketest/appsec/springbootsecurity/WebSecurityConfig.java, dd-smoke-tests/appsec/springboot-security/src/main/resources/application.properties, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
* Fixed SpringSecurity NullPointerException when user creation happens outside request.
* That exception used to be caught and logged to debug level.
Backport of #5732
=> Fix NPE in user events tracking (#5732)

dd-java-agent/instrumentation/jetty-11/build.gradle, dd-java-agent/instrumentation/jetty-11/src/main/java11/datadog/trace/instrumentation/jetty11/JettyServerAdvice.java, dd-java-agent/instrumentation/jetty-9/src/main/java_jetty10/datadog/trace/instrumentation/jetty10/HandleAdvice.java
=> Fix simultaneous jetty 10/11 instrumentation when jakarta/javax servlet are both present (#5787)

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/JDBCConnectionUrlParser.java, dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCConnectionUrlParserTest.groovy
=> Add redshift support to JDBC URL parser

buildSrc/src/main/groovy/MuzzlePlugin.groovy
Updates Muzzle plugin to run validation with correct artifacts when artifact classifier is provided in the Muzzle directive.
Muzzle check for Jacoco instrumentation needs to be done against `org.jacoco.agent` dependency with `runtime` classifier.
=> Fix Muzzle plugin to fetch correct artifacts when muzzle directive includes classifier

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
Send probe status error for all probes applied on the same class indicating instrumentation could not be applied for this class.
=> Reports instrumentation failure

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/AgentDebuggerIntegrationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/MetricProbesIntegrationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SimpleAppDebuggerIntegrationTest.java
Refactor smoke test to separate them by category:
- Log probes
- metric probes
- agent related tests
=> Add metric smoke tests

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
=> make `@duration` a float value in ms

gradle/dependencies.gradle
Reports the sizes of all internal data structures in the profiling recording.
=> Upgrade ddprof to 0.72.0

dd-java-agent/appsec/src/main/resources/default_config.json
See https://github.com/DataDog/appsec-event-rules/releases/tag/1.7.2
=> Upgrade ASM rules to v1.7.2

.circleci/config.continue.yml.j2
Comparison:
https://github.com/datadog/system-tests/compare/1a721f777d95a50144b8d9a195c20684a9a2b265..3598f2583cd5c25326cd7a5c01097374d94c1993
Previous update: https://github.com/DataDog/dd-trace-java/pull/5794
* https://github.com/datadog/system-tests/pull/1558
* https://github.com/datadog/system-tests/pull/1566
* https://github.com/datadog/system-tests/pull/1568
=> Update system-tests to 3598f2583cd5c25326cd7a5c01097374d94c1993

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
=> WAF refactoring

gradle/dependencies.gradle
* contains fixes to counter events which record how large internal profiler data structures get
=> Upgrade to ddprof 0.74.0

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/overhead/OverheadController.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/overhead/OverheadControllerTest.groovy, dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
Reworked sampling logic to provide more precise results.
=> Improved IAST sampling mechanism.

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/DebuggerSink.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/Sink.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ProbeInstrumentationTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanProbeInstrumentationTest.java
Using directly DebuggerSink instead going through Sink interface 
Centralize sending probe status
=> Refactor diagnostic messages

.github/pull_request_template.md, CONTRIBUTING.md
Adds information about draft pull requests to the guidelines.
=> Add information about draft pull request to guidelines

dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java, dd-java-agent/instrumentation/spark/src/test/groovy/SparkTest.groovy
Add custom spark spans tags that can be changed at runtime using the sparkContext localProperty
```scala
// All spark computations launched will have the extra tag
sparkContext.setLocalProperty("spark.datadog.tags.key", "value")
spark.read.parquet(...)
// Remove the custom tag for all next spark computations
sparkContext.setLocalProperty("spark.datadog.tags.key", null)
```
Asked by a design partner on spark monitoring. Spark application can be running for a long time and perform multiple computations that custom tags allow to distinguish. 
[setLocalProperty](https://github.com/apache/spark/blob/d8298bffd91de01299f9456b37e4454e8b4a6ae8/core/src/main/scala/org/apache/spark/SparkContext.scala#L784-L795) is the usual spark way to propagate properties to the next submitted jobs
The [current …
=> Custom spark spans tags at runtime

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SpanDecorationProbesIntegrationTests.java
=> flag SpanDecoration smoke tests Flaky

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SpanDecorationProbesIntegrationTests.java
make sure we are asserting on the right span (name + resource)
Fix smoke test flakiness
=> Fix Span decoration smoke tests flakiness

gradle/dependencies.gradle
* stability fixes for usage of JVMTI and AsyncGetCallTrace
=> Upgrade to ddprof 0.78.0

dd-java-agent/instrumentation/jax-rs-client-2.0/build.gradle
=> skip faulty version for muzzle

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
Reset for each test the Probe rate limiter
=> Fix flaky sampling smoke tests

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryContextInstrumentation.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryInstrumentation.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpan.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpanBuilder.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
This PR improve OpenTelemetry span attributes of array values into tags.
Array values will now properly be displayed in UI.
=> Improve OpenTelemetry span attributes encoding

dd-java-agent/instrumentation/undertow/undertow-2.2/src/test/groovy/UndertowServletTest.groovy, dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java, dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java, internal-api/src/main/java/datadog/trace/api/Config.java, telemetry/src/main/java/datadog/telemetry/BufferedEvents.java, telemetry/src/main/java/datadog/telemetry/ExtendedHeartbeatData.java, telemetry/src/main/java/datadog/telemetry/TelemetryRequest.java, telemetry/src/main/java/datadog/telemetry/TelemetryRequestBody.java, telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java, telemetry/src/main/java/datadog/telemetry/TelemetryService.java, telemetry/src/main/java/datadog/telemetry/api/RequestType.java, telemetry/src/test/groovy/datadog/telemetry/BufferedEventsSpecification.groovy, telemetry/src/test/groovy/datadog/telemetry/ExtendedHeartbeatDataSpecification.groovy, telemetry/src/test/groovy/datadog/telemetry/TelemetryRunnableSpecification.groovy, telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
Implements Extended Heartbeat telemetry request
Telemetry V2 implementation
=> Telemetry v2 Extended Heartbeat

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpan.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpanContext.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OpenTelemetryContextInstrumentation.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OpenTelemetryContextStorageInstrumentation.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OtelContext.java, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14ContextTest.groovy, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
This PR should improve OpenTelemetry Context API compatibility.
Fix regression introduced in #5880
=> Add support for OpenTelemetry root context manipulation

dd-trace-api/build.gradle, dd-trace-api/src/main/java/datadog/trace/api/experimental/DataStreamsCheckpointer.java, dd-trace-api/src/main/java/datadog/trace/api/experimental/DataStreamsContextCarrier.java, dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsMonitoring.java, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentDataStreamsMonitoring.java, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
This reverts commit 6e2751fb61b2f14cf553dff63df6bde725a35f14.
Further manual testing showed a flaw in this approach, will revisit with changes
=> Revert "Add DSM API changes to support kinesis use case (#5982)"

dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/XssController.java
Fix warning: non-varargs call of varargs method with inexact argument type for last parameter
=> Fix smoke tests warning

.github/pull_request_template.md
Document how to link JIRA tickets in PR for our repository.
=> Update pull request template for JIRA tickets

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java
=> Relax assert for log sampling smoke test

.circleci/config.continue.yml.j2
Update the system-tests
Include the latest parametric test suites
Jira ticket: [APMJAVA-1093]
[APMJAVA-1093]: https://datadoghq.atlassian.net/browse/APMJAVA-1093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update system-tests to edfea31b7a9ceaed03b705de34a4e525853444c0

gradle/dependencies.gradle
* Reduces overhead in symbolization
* Includes a new mode to opt out of line numbers to reduce overhead
Jira ticket: [PROF-8361]
[PROF-8361]: https://datadoghq.atlassian.net/browse/PROF-8361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Upgrade to ddprof 0.81.0

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java, dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java
Set status code on error if a response is available.
Reported issue.
Jira ticket: [APMS-10578]
[APMS-10578]: https://datadoghq.atlassian.net/browse/APMS-10578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AWS set reponse status on error

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/TaintedObjects.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/telemetry/taint/TaintedObjectsWithTelemetry.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/RangesTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedObjectsLazyTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedObjectsLogTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedObjectsNoOpTest.groovy
deal with CharSequence when tainting inputs
Jira ticket: [APPSEC-11756]
[APPSEC-11756]: https://datadoghq.atlassian.net/browse/APPSEC-11756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add CharSequence  support

.circleci/config.continue.yml.j2
=> Update system-tests to 97bada5205ff411ec62ba9c2c15e66cd5a49fbb0

internal-api/src/main/java/datadog/trace/api/Config.java
Consistent logging
Better consistency
N/A
=> Format Config.toString

dd-smoke-tests/osgi/build.gradle, dd-smoke-tests/osgi/src/main/java/datadog/smoketest/osgi/app/OSGiApplication.java, dd-smoke-tests/osgi/src/test/groovy/datadog/smoketest/KnopflerfishSmokeTest.groovy
Add smoke test for Knopflerfish
Make it easier to debug Knopflerfish issues.
Jira ticket: [APPSEC-11213](https://datadoghq.atlassian.net/browse/APPSEC-11213) (partial)
[APPSEC-11213]: https://datadoghq.atlassian.net/browse/APPSEC-11213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add smoke test for Knopflerfish

dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/TracingListener.java
Fixes instrumentation for [jqwik](https://jqwik.net/) framework.
The framework is used by one of the DD repos that are used for dogfooding.
The specific problem being fixed is incorrect suite name calculation in testcase start/finish events.
Previous logic calculated suite name based on the class where the given test method was defined.
It was incorrect in some cases, since the test case can be defined in a parent class, while the suite that runs this test case can be defined in the child class.
Jira ticket: [CIVIS-7825]
[CIVIS-7825]: https://datadoghq.atlassian.net/browse/CIVIS-7825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix suite name calculation for jqwik framework

dd-java-agent/instrumentation/opentelemetry/opentelemetry-0.3/src/test/groovy/TypeConverterTest.groovy, dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/TypeConverterTest.groovy, dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/TypeConverterTest.groovy, dd-trace-core/src/jmh/java/datadog/trace/core/DDSpanHelper.java, dd-trace-core/src/jmh/java/datadog/trace/core/PendingTraceWrite.java, dd-trace-core/src/jmh/java/datadog/trace/core/TracerMapperMap.java, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java, dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java, dd-trace-core/src/main/java/datadog/trace/core/DDSpanLink.java, dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDIntakeWriterCombinedTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDIntakeWriterTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/common/writer/PayloadDispatcherImplTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanLinkTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanSerializationTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/test/DDCoreSpecification.groovy, dd-trace-ot/src/test/groovy/datadog/opentracing/TypeConverterTest.groovy, internal-api/build.gradle, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpanLink.java, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/SpanLink.java, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/SpanLinkAttributes.java, internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/SpanLinkTest.groovy
- Add API to add span links to spans
- Add trace flags field
- Add dedicated attributes structure
- Add new attribute encoding
- Add max tag size encoding
- Add late encoding at serialization
Implement the new span links RFC
Jira ticket: [APMJAVA-1073]
[APMJAVA-1073]: https://datadoghq.atlassian.net/browse/APMJAVA-1073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update span links implementation

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/PropagationModuleTest.groovy
Ensure that no strong references are create due to tainted objects where the actual tainted value is used as the name.
Creating the strong reference via the source name will prevent the GC from collecting the value generating a memory leak.
For previous releases, the memory leak will only span the request duration. These objects will still be GC'd at end request.
Jira ticket: [APPSEC-11977]
[APPSEC-11977]: https://datadoghq.atlassian.net/browse/APPSEC-11977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensure no strong references are kept due to source names

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
Jira ticket: [DEBUG-1910]
[DEBUG-1910]: https://datadoghq.atlassian.net/browse/DEBUG-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Sample log probes with errors on condition

dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java, dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot19.java
=> Add test for object array

gradle/dependencies.gradle
Adds a safety check when parsing ELF
=> Upgrade to ddprof 0.84.0

dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java
Add test to make sure `@return` and `@duration` is working properly for span decoration probes
Jira ticket: [DEBUG-1854]
[DEBUG-1854]: https://datadoghq.atlassian.net/browse/DEBUG-1854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add tests for synthetic vars on span deco probes

dd-java-agent/appsec/src/main/resources/default_config.json
ASM rules updated to 1.9.0
See: https://github.com/DataDog/appsec-event-rules/releases/tag/1.9.0
=> Update to ASM rules 1.9.0

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/build.gradle, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWS1ClientTest.groovy, dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/LegacyAWS1ClientForkedTest.groovy, dd-java-agent/instrumentation/aws-java-sqs-1.0/build.gradle, dd-java-agent/instrumentation/aws-java-sqs-2.0/build.gradle, dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/LegacySqsClientForkedTest.groovy, dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/SqsClientTest.groovy, dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/TimeInQueueForkedTest.groovy, dd-java-agent/instrumentation/build.gradle
Support json encoding for mocked request needed on latest aws-sdk-1 calls
=> Fix AWS SDK latestDepTests

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java
Add smoke tests for line log probes and tracer
Jira ticket: [DEBUG-1462]
[DEBUG-1462]: https://datadoghq.atlassian.net/browse/DEBUG-1462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add line probe tracer smoke tests

dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
This will prevent ContextVisitor to extract and format as string headers multiple times per extraction style.
It should decrease CPU cost (the purple part) when multiple extractors are set (which is now the default behavior) at the expect of an array allocation (ArrayList cache of headers):
I also prevent using CompoundExtractor when only 0 or 1 extractor is used (avoid to create cache if no multiple extractors) 
Jira ticket: [APMJAVA-1066]
[APMJAVA-1066]: https://datadoghq.atlassian.net/browse/APMJAVA-1066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Optimize trace context extraction

gradle/dependencies.gradle
* Stability improvement to prevent CPU and wall clock unwinding from interrupting each other
=> Upgrade to ddprof 0.85.0

gradle/dependencies.gradle
This has exposed issues which need to be fixed in the profiler library before integrating
=> Revert "Upgrade to ddprof 0.85.0"

dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
=> change default safemode to avoid last Java pc retry strategy

gradle/dependencies.gradle
* includes change to prevent CPU and wallclock profiler from interrupting each other
=> Update ddprof to 0.86.0

dd-java-agent/instrumentation/google-pubsub/src/main/java/datadog/trace/instrumentation/googlepubsub/PubSubDecorator.java, dd-java-agent/instrumentation/google-pubsub/src/main/java/datadog/trace/instrumentation/googlepubsub/PublisherInstrumentation.java, dd-java-agent/instrumentation/google-pubsub/src/test/groovy/PubSubTest.groovy, dd-trace-core/src/main/java/datadog/trace/core/datastreams/TagsProcessor.java
Adds DSM support to google pubsub instrumentation
Jira ticket: [APMJAVA-932]
[APMJAVA-932]: https://datadoghq.atlassian.net/browse/APMJAVA-932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add DSM for google pubsub

.circleci/config.continue.yml.j2
This PR updates the system-tests.
This will fix the current OpenTelemetry parametric tests.
=> Update system-tests to 4e82927b4c93b78339a3e9d89b41b6dce7790075

gradle/dependencies.gradle
=> Upgrade ddprof to 0.87.0

dd-java-agent/instrumentation/spring-scheduling-3.1/build.gradle, dd-java-agent/instrumentation/spring-scheduling-3.1/src/main/java/datadog/trace/instrumentation/springscheduling/SpringSchedulingInstrumentation.java, dd-java-agent/instrumentation/spring-scheduling-3.1/src/test/groovy/SpringSchedulingTest.groovy, dd-java-agent/instrumentation/spring-scheduling-3.1/src/test/java/TriggerTaskConfig.java
Solves #5651 
Also add tests for spring 6
=> Spring scheduling: have actuator display the right task class name

.github/CODEOWNERS
=> Change Spring Security ownership to ASM

CONTRIBUTING.md
Adds GraalVM native image build instructions
=> Add GraalVM native image build instructions

.circleci/config.continue.yml.j2
Relevant PRs:
* https://github.com/DataDog/system-tests/pull/1824
* https://github.com/DataDog/system-tests/pull/1798
* https://github.com/DataDog/system-tests/pull/1884
* https://github.com/DataDog/system-tests/pull/1887
=> Update system-tests to ca7566bf7e66c0afdf29b0d3c07b2972e5869997

dd-trace-core/src/main/java/datadog/trace/common/sampling/RuleBasedTraceSampler.java, dd-trace-core/src/main/java/datadog/trace/common/sampling/SpanSamplingRules.java, dd-trace-core/src/main/java/datadog/trace/common/sampling/TraceSamplingRules.java, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, dd-trace-core/src/test/groovy/datadog/trace/common/sampling/SpanSamplingRulesTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/common/sampling/TraceSamplingRulesTest.groovy, internal-api/src/main/java/datadog/trace/api/DynamicConfig.java, internal-api/src/main/java/datadog/trace/api/TraceConfig.java, internal-api/src/main/java/datadog/trace/api/sampling/SamplingRule.java, internal-api/src/test/groovy/datadog/trace/api/sampling/SamplingRuleTest.groovy
Cleans up Sampling Rules after #5164 review
Code review
N/A
=> Clean up Sampling Rules

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilitySystem.java, dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/PackageTree.java, dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexBuilder.java, dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexSourcePathResolver.java, dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/index/RepoIndexSourcePathResolverTest.groovy, dd-trace-api/src/main/java/datadog/trace/api/config/CiVisibilityConfig.java, internal-api/src/main/java/datadog/trace/api/Config.java
=> Cherrypick: Fix root coverage packages calculation in large repositories (#6317)

dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
=> fix grpc test failures

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy, dd-trace-core/src/main/java/datadog/trace/core/DDSpanLink.java, dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanLinkTest.groovy
This PR fixes span links serialization as span tags.
JSON encoding is broken according the RFC.
Jira ticket: [APMJAVA-1060]
[APMJAVA-1060]: https://datadoghq.atlassian.net/browse/APMJAVA-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix span links serialization as tag

dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java, dd-java-agent/agent-crashtracking/src/test/java/com/datadog/crashtracking/CrashUploaderTest.java, dd-java-agent/agent-crashtracking/src/test/resources/redacted-stacktrace.txt, dd-java-agent/agent-crashtracking/src/test/resources/sample-crash-for-telemetry.txt
* set the language tag to "jvm"
* add redacted stack traces to telemetry requests
=> cleanup crashtracking

internal-api/src/main/java/datadog/trace/api/cache/CHMCache.java, internal-api/src/main/java/datadog/trace/api/cache/DDCache.java, internal-api/src/main/java/datadog/trace/api/cache/FixedSizeCache.java, internal-api/src/main/java/datadog/trace/api/cache/FixedSizeWeakKeyCache.java, internal-api/src/main/java/datadog/trace/api/cache/FixedSizeWeightedCache.java, internal-api/src/test/groovy/datadog/trace/api/cache/FixedSizeCacheTest.groovy
For triage/debug purposes
Jira ticket: [APMJAVA-1136]
[APMJAVA-1136]: https://datadoghq.atlassian.net/browse/APMJAVA-1136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow introspection of cached keys and values

dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlarePoller.java, dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlareService.java, internal-api/src/main/java/datadog/trace/api/DynamicConfig.java, internal-api/src/main/java/datadog/trace/api/flare/TracerFlare.java, internal-api/src/test/groovy/datadog/trace/api/flare/TracerFlareTest.groovy
Jira ticket: [APMJAVA-1136]
[APMJAVA-1136]: https://datadoghq.atlassian.net/browse/APMJAVA-1136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Populate tracer-flare zip with configuration details

gradle/dependencies.gradle
Upgrades Testcontainers to 1.19.3
Living on the edge (and bug fixes)
=> Upgrade Testcontainers to 1.19.3

dd-java-agent/instrumentation/mongo/build.gradle, dd-java-agent/instrumentation/mongo/driver-3.1-core-test/build.gradle, dd-java-agent/instrumentation/mongo/driver-3.1/build.gradle, dd-java-agent/instrumentation/mongo/driver-3.10-sync-test/build.gradle, dd-java-agent/instrumentation/mongo/driver-3.3-async-test/build.gradle, dd-java-agent/instrumentation/mongo/driver-3.4/build.gradle, dd-java-agent/instrumentation/mongo/driver-3.7-core-test/build.gradle, dd-java-agent/instrumentation/mongo/driver-4.0/build.gradle, dd-java-agent/instrumentation/mongo/driver-4.0/src/main/java/datadog/trace/instrumentation/mongo/Arg2Advice.java, dd-java-agent/instrumentation/mongo/driver-4.0/src/main/java/datadog/trace/instrumentation/mongo/BaseClusterInstrumentation410.java, dd-java-agent/instrumentation/mongo/driver-4.0/src/main/java/datadog/trace/instrumentation/mongo/DefaultConnectionPoolInstrumentation410.java, dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/Mongo4ClientTest.groovy, dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/MongoReactiveClientTest.groovy, dd-java-agent/instrumentation/mongo/src/test/groovy/MongoBaseTest.groovy
=> [🍒 6358] MongoDB 4.10-11 instrumentation fix

dd-trace-core/src/main/java/datadog/trace/core/propagation/ptags/DatadogPTagsCodec.java, dd-trace-core/src/main/java/datadog/trace/core/propagation/ptags/W3CPTagsCodec.java, internal-api/src/main/java/datadog/trace/relocate/api/RatelimitedLogger.java, internal-api/src/test/groovy/datadog/trace/relocate/api/RateLimitedLoggerTest.groovy
=> [🍒 6385] Rate limit Datadog tags decoding warnings

dd-java-agent/agent-jmxfetch/build.gradle
Changes since last update:
* https://github.com/DataDog/jmxfetch/releases/tag/0.48.0
* https://github.com/DataDog/jmxfetch/releases/tag/0.49.0
=> JMXFetch 0.49.0

telemetry/src/main/java/datadog/telemetry/TelemetryRequest.java, telemetry/src/main/java/datadog/telemetry/TelemetryRequestBody.java, telemetry/src/main/java/datadog/telemetry/TelemetryService.java, telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy, telemetry/src/test/groovy/datadog/telemetry/TestTelemetryRouter.groovy
Adds `install_signature` to the `app-started` event
Jira ticket: [AIT-9228]
[AIT-9228]: https://datadoghq.atlassian.net/browse/AIT-9228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add install_signature to app-started

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
Reverts DataDog/dd-trace-java#6427
=> Revert "Enable diagnostics on debugger track"

dd-java-agent/agent-debugger/debugger-el/build.gradle, dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/IndexExpression.java, dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/TestHelper.java, dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/GetMemberExpressionTest.java, dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/IndexExpressionTest.java, dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/ValueRefExpressionTest.java
add unit tests for redacted values and types
=> Fix support of string primitives for index in EL

dd-java-agent/instrumentation/iast-instrumenter/src/test/groovy/IastExclusionTrieTest.groovy, dd-java-agent/instrumentation/iast-instrumenter/src/test/groovy/IastInstrumentationTest.groovy, dd-java-agent/instrumentation/iast-instrumenter/src/test/java/MockCallSites.java, dd-java-agent/instrumentation/iast-instrumenter/src/test/java/MockCallSitesWithTelemetry.java, dd-java-agent/instrumentation/iast-instrumenter/src/test/resources/META-INF/services/datadog.trace.api.iast.IastCallSites
Refactos `IastInstrumentation` related tests and includes new ones for testing call site suppliers
=> Improve testing in iast-instrumenter module

dd-java-agent/agent-profiling/profiling-controller-ddprof/src/main/java/com/datadog/profiling/controller/ddprof/DatadogProfilerCheckpointer.java, dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/EndpointEvent.java, dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java, gradle/dependencies.gradle
Adds the operation name to endpoint events which allows for more profiling metrics
Jira ticket: [PROF-8874]
[PROF-8874]: https://datadoghq.atlassian.net/browse/PROF-8874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add operation label to endpoint events

dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlareService.java
Provides additional detail about the application being traced when triaging issues.
=> Add thread-dump to tracer-flare when triage or debug mode is enabled

dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/ProcessImplInstrumentationSpecification.groovy
* Test refactor spun out of https://github.com/DataDog/dd-trace-java/pull/6481
* Related to [APPSEC-10243](https://datadoghq.atlassian.net/browse/APPSEC-10243)
[APPSEC-10243]: https://datadoghq.atlassian.net/browse/APPSEC-10243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Extend ProcessImpl instrumentation tests

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
instead of hardcoded /tmp dir
Jira ticket: [DEBUG-2050]
[DEBUG-2050]: https://datadoghq.atlassian.net/browse/DEBUG-2050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Use java.io.tmpdir for classfile dump directory

dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
Jira ticket: [APPSEC-18261](https://datadoghq.atlassian.net/browse/APPSEC-18261)
[APPSEC-18261]: https://datadoghq.atlassian.net/browse/APPSEC-18261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add IAST exclusion for org.openjdk.jol.vm

.circleci/config.continue.yml.j2
=> Update system-tests to 706b4eb3ff053068e961a684d21dfe2ff4487d37

dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlareService.java
In case other products in the same tracer distribution want to record their versions separately
Jira ticket: [APMJAVA-1076]
[APMJAVA-1076]: https://datadoghq.atlassian.net/browse/APMJAVA-1076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Rename version.txt to tracer_version.txt in tracer-flare

dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/resources/jfr/dd.jfp
=> stop collecting jdk.ClassLoadingStatistics

.circleci/config.continue.yml.j2
=> Update system-tests to ed41a27fd2900491e459b9ceac534f4c65ff0ba8

.github/workflows/codeql-analysis.yml
=> Upload SARIF from CodeQL to CI Static Analysis

telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java, telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverSpecification.groovy, telemetry/src/test/groovy/datadog/telemetry/dependency/DependencySpecification.groovy
=> Remove dead code in dependency resolver

.github/workflows/README.md
=> Update GitHub Actions README.md

dd-trace-core/src/main/java/datadog/trace/core/DDBaggage.java, dd-trace-core/src/main/java/datadog/trace/core/DDScopedContext.java, dd-trace-core/src/test/groovy/datadog/trace/core/DDBaggageTest.groovy, dd-trace-core/src/test/groovy/datadog/trace/core/DDScopedContextTest.groovy
Implements the ScopedContext and Baggage API introduced in #6517
Further PRs will wire this up to scope management and surface them via the OTel API
Jira ticket: [AIT-9446]
[AIT-9446]: https://datadoghq.atlassian.net/browse/AIT-9446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Implement ScopedContext and Baggage API

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFStatsReporter.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
This tag counts number of timeouts in a request.
Jira ticket: [APPSEC-51507](https://datadoghq.atlassian.net/browse/APPSEC-51507)
[APPSEC-51507]: https://datadoghq.atlassian.net/browse/APPSEC-51507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add _dd.appsec.waf.timeouts tag

buildSrc/src/main/groovy/InstrumentingPlugin.groovy
This should resolve intermittent failures when switching between branches that change key instrumentation types:
```
> Task :dd-java-agent:instrumentation:aerospike-4:instrumentJava FAILED
Failed to transform class datadog.trace.instrumentation.aerospike4.CommandInstrumentation
```
Previously the only workaround was to restart Gradle's build daemon:
```
./gradlew --stop
```
=> Avoid caching class-file resources in build-workers during instrument tasks

dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaHttpServletResponseInstrumentation.java, dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/IastServletContextInstrumentation.java, internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityTypes.java, internal-api/src/test/groovy/datadog/trace/api/iast/telemetry/IastMetricTest.groovy
Adds the IAST application vulnerability instrumenter to telemetry
=> Add application vulnerabilities to telemetry

.circleci/config.continue.yml.j2
=> Update system-tests to a0064c4012f19fbec5b9f0583efc80ab5f37c35e

dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeManagerTest.java
following comment: https://github.com/DataDog/dd-trace-java/pull/6641#discussion_r1483076785
=> Add test for class filtering

communication/src/main/java/datadog/communication/http/OkHttpUtils.java
Fixes OKHTTP tests that were broken when #6660 got merged.
The PR uses an OKHTTP feature (event listeners) available since v3.12.0
The tests for OKHTTP instrumentation use v3.0.0 (the oldest that is supported).
In "real-life" scenarios the OKHTTP classes used by the tracer core do not conflict with the classes that may be used by the application since the tracer classes are relocated.
However, this does not happen in instrumentation tests. As the result, the tracer ends up using old OKHTTP version - the one that is being tested.
=> Fix OKHTTP instrumentation tests

.circleci/config.continue.yml.j2
Avoid this sort of breakage: https://github.com/DataDog/dd-trace-java/pull/6682
=> Add communication module as affecting instrumentation tests

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/ReflectionInjectionModuleImpl.java, internal-api/src/main/java/datadog/trace/api/iast/sink/ReflectionInjectionModule.java
Improve ReflectionInjectionModule code
Jira ticket: [APPSEC-17150](https://datadoghq.atlassian.net/browse/APPSEC-17150)
[APPSEC-17150]: https://datadoghq.atlassian.net/browse/APPSEC-17150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Reflection Injection code improvements

dd-java-agent/appsec/build.gradle
Updated WAF bindings to 9.0.2
**Incident-25401**: Spotted issue that can cause crash. For more details see [PR-95](https://github.com/DataDog/libddwaf-java/pull/95)
=> Update WAF bindings to 9.0.2

telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java, telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java, telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverSpecification.groovy
Backport of https://github.com/DataDog/dd-trace-java/pull/6712
Jira ticket: [APPSEC-51864](https://datadoghq.atlassian.net/browse/APPSEC-51864)
[APPSEC-51864]: https://datadoghq.atlassian.net/browse/APPSEC-51864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "Fix dependency resolution to nested JARs (#6603)" (v1.30.x backport of #6712)

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/ContextTest.groovy, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/AbstractPropagatorTest.groovy, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/TextMap.groovy, dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/W3cPropagatorTracestateTest.groovy
This PR brings some tests of unknown supported cases to try against the new tracer context implementation.
This will help to test and validate the new tracer context implementation.
Jira ticket: [AIT-9852]
Related to #6329
I don’t know why spotless formatting changed 🤷 
[AIT-9852]: https://datadoghq.atlassian.net/browse/AIT-9852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add unsupported (disabled) test cases for OpenTelemetry context

.circleci/config.continue.yml.j2
=> Update system-tests to 54517a50d663b92d8b0a2f599261105768e92a72

.circleci/config.continue.yml.j2
See https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176
=> Update Docker used in Circle CI

.circleci/config.continue.yml.j2
Includes https://github.com/DataDog/system-tests/pull/2192 which is required to minify AppSec rules json.
=> Update system-tests to 454b41b414ba9e4b534893c2fe77477428d3bdca

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/Redaction.java
Jira ticket: [DEBUG-2179]
[DEBUG-2179]: https://datadoghq.atlassian.net/browse/DEBUG-2179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add "applicationkey" as redacted keyword

CONTRIBUTING.md, docs/add_new_instrumentation.md, docs/how_instrumentations_work.md
Adds docs in Github that detail our new instrumentation process
This combines the existing information in CONTRIBUTING.md and @am312 's internal document
Make this information available and easily accessible for internal and external contributors
Jira ticket: N/A
=> Add documentation for adding new instrumentations and how instrumentations work

dd-smoke-tests/spring-boot-3.0-native/build.gradle, dd-smoke-tests/spring-boot-3.0-native/src/test/groovy/SpringBootNativeInstrumentationTest.groovy, gradle/dependencies.gradle
Jira ticket: [PROF-9265]
[PROF-9265]: https://datadoghq.atlassian.net/browse/PROF-9265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make the native image smoke test check presence of ExecutionSample events

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelSpan.java, internal-api/src/main/java/datadog/trace/api/Config.java
Few minor changes when reviewing code during ER.
=> Fix typo and missing assignment

dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
closes https://github.com/DataDog/dd-trace-java/issues/6903
What I suppose is happening is that the DSM data can come in 3 groups, and since we only wait for 2, we can run the asserts before everything is there. 
https://github.com/DataDog/dd-trace-java/blob/bd114faddf0fa79e10cac21769ba7121b8e761de/dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy#L638
Adding retries around it allows more time for the data to arrive.
=> Add some retries around flaky RabbitMQ DSM test

dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/telemetry/TelemetryRequestEndedHandlerTest.groovy
Fixes `TelemetryRequestEndedHandlerTest` that recently started to fail on master
=> Fix TelemetryRequestEndedHandlerTest

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ThirdPartyLibraries.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/ClassNameFiltering.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ThirdPartyLibrariesTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeManagerTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymDBEnablementTest.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/ClassNameFilteringTest.java
=> Swap meaning of includes and excludes

BUILDING.md, CONTRIBUTING.md, gradle/spotless.gradle, setup.sh
This PR improves the documentation to get starting contributing to the project.
It updates and splits the original contributing guidelines into two documents:
- The contributing guidelines,
- The build documentation.
It also introduces a script to quickly check its environment development.
This should improve the onboarding experience for new contributors.
This PR also introduces a new formatting setting for Markdown files to allow line-breaking sequence (two trailing spaces).
=> Improve environment setup documentation

gradle/dependencies.gradle
=> Upgrade to ddprof 1.5.0

.circleci/config.continue.yml.j2
=> Update system-tests to 832e4d8514a06cbe9484ace1fedb3b9344a9ef44

dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ThirdPartyLibrariesTest.java
=> fix ThirdPartyLibraries coverage

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/Fingerprinter.java, dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/DefaultExceptionDebuggerTest.java
Do not process errors for exception Debugging
=> Filter out Errors for Exception Debugging

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymbolExtractor.java
=> Fix log level and message for SymDB extraction

gradle/dependencies.gradle
Upgrades profiler to 1.7.0, details [here](https://github.com/DataDog/java-profiler/compare/v_1.6.0...v_1.7.0)
=> Upgrade ddprof to 1.7.0

dd-java-agent/instrumentation/spring-boot/build.gradle
=> fix spring boot latest dep logging dependencies

.circleci/config.continue.yml.j2
=> Ensure tests are run for dd-trace-api and dd-trace-ot

.circleci/config.continue.yml.j2
=> Update system-tests to 4d979bdcab25754d38a8d190525bef87dad66a6e

dd-java-agent/instrumentation/spring-messaging-4/src/test/groovy/listener/Config.groovy
=> Fix spring-messaging tests

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/ExtensionFinder.java, dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExtensionHandler.java
=> Rework the bytecode cache for extensions so it works across connections

dd-java-agent/instrumentation/aws-java-sns-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sns/SnsInterceptor.java, dd-java-agent/instrumentation/aws-java-sns-1.0/src/test/groovy/SnsClientTest.groovy, dd-java-agent/instrumentation/aws-java-sns-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sns/SnsInterceptor.java, dd-java-agent/instrumentation/aws-java-sns-2.0/src/test/groovy/SnsClientTest.groovy
=> SNS integration: do not modify readonly message attributes map

.github/workflows/README.md, .github/workflows/add-release-to-cloudfoundry.yaml
=> Add cloudfoundry release automation

dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/OtelContext.java, dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/trace/OtelTracerProvider.java
=> Update shim fields to have the types expected by OtelShimInjector

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java, dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java, dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java, internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java, internal-api/src/main/java/datadog/trace/bootstrap/config/provider/OtelEnvironmentConfigSource.java, internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/OtelEnvironmentConfigSourceTest.groovy
=> Map OpenTelemetry environment variables to their Datadog equivalents

dd-java-agent/appsec/src/main/resources/default_config.json
Upgrade to the latest Application Security rules.
The new configuration provides SSRF, LFI and SQLi rules for exploit prevention.
=> Upgrade to AppSec rules v1.12.0

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/ConsumerCoordinatorInstrumentation.java
=> Fix NPE when kafka consumer info is not available

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
=> Only call `shutdownLogsIntake` at shutdown if we called `maybeStartLogsIntake` at startup

dd-java-agent/agent-otel/otel-bootstrap/build.gradle, dd-java-agent/agent-otel/otel-bootstrap/src/main/java/datadog/trace/bootstrap/otel/context/StrictContextStorage.java
=> Swap original StrictContextStorage with simple wrapper when embedding

.gitlab-ci.yml
=> Fix GitLab deployment to Sonatype

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java, dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java, dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java, gradle/dependencies.gradle
This adds the ability to enable the light-weight live object tracking in order to capture the distribution of the surviving generations.
^^^
Jira ticket: [PROF-9743]
[PROF-9743]: https://datadoghq.atlassian.net/browse/PROF-9743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add configuration parameter for GC generation count tracking

.circleci/config.continue.yml.j2
Run dynamic instrumentation system tests as part of CI
=> [Dynamic Instrumentation]  Run dynamic instrumentation system tests as part of CI

.circleci/config.continue.yml.j2
=> Update system-tests to 0f27f203c90bba8bce7b58e2b75ff9d7035169eb

gradle/dependencies.gradle
=> Update ddpfrof to 1.9.0

dd-java-agent/agent-ci-visibility/build.gradle
This PR is a follow up of #7298 
Nightly still broken
=> Add missing dependency to unlock dependency lock updates

.circleci/config.continue.yml.j2
Based on https://github.com/DataDog/dd-trace-php/pull/2748
=> Update system-tests to 06cbfad5f9facbc6e258d9c8208c466cd46efeea and use Python 3.12

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastSystem.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/UntrustedDeserializationModuleImpl.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/UntrustedDeserializationModuleTest.groovy, dd-java-agent/instrumentation/java-io/src/main/java/datadog/trace/instrumentation/java/lang/ObjectInputStreamCallSite.java, dd-java-agent/instrumentation/java-io/src/test/groovy/datadog/trace/instrumentation/java/io/ObjectInputStreamCallSiteTest.groovy, dd-java-agent/instrumentation/java-io/src/test/java/foo/bar/TestObjectInputStreamSuite.java, dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java, dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy, internal-api/src/main/java/datadog/trace/api/iast/InstrumentationBridge.java, internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityMarks.java, internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityTypes.java, internal-api/src/main/java/datadog/trace/api/iast/sink/UntrustedDeserializationModule.java, internal-api/src/test/groovy/datadog/trace/api/iast/VulnerabilityTypesTest.groovy
Add Untrusted Deserialization vulnerability
Add a new vulnerability
Jira ticket: [APPSEC-17165]
[APPSEC-17165]: https://datadoghq.atlassian.net/browse/APPSEC-17165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Untrusted Deserialization vulnerability

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/SsrfModuleImpl.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/SsrfModuleTest.groovy, dd-java-agent/instrumentation/apache-httpclient-4/build.gradle, dd-java-agent/instrumentation/apache-httpclient-4/src/iastIntegrationTest/groovy/IastHttpClientIntegrationTest.groovy, dd-java-agent/instrumentation/apache-httpclient-4/src/iastIntegrationTest/java/SsrfController.java, dd-java-agent/instrumentation/apache-httpclient-4/src/iastIntegrationTest/java/foo/bar/VulnerableUrlBuilder.java
Improves SSRF accuracy when using apache http client
=> Improve SSRF detection in apache http client

dd-java-agent/appsec/build.gradle
Upgrade to libddwaf 1.19.0 (libddwaf-java 10.1.0)
New version of `libddwaf` been released. It brings new functionality, required to implement support of new vulnerabilities for ASM Exploit prevention.
=> Upgrade to libddwaf 1.19.0 (libddwaf-java 10.1.0)

dd-java-agent/instrumentation/avro/build.gradle
Fixes versioning issue for latestDepTest
=> Fix Avro latestDepTests

dd-java-agent/instrumentation/avro/build.gradle
https://github.com/DataDog/dd-trace-java/pull/7392/files
(cherry picked from commit 42eee0817dea458b72582b5f853790dac7e1915c)
Fix latest test jobs in the release branch
=> [🍒 7392] Fix Avro latestDepTests

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy, dd-trace-api/src/main/java/datadog/trace/api/DDTags.java, dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/RemoteHostnameAdder.java, dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/TagsPostProcessorFactory.java, dd-trace-core/src/test/groovy/datadog/trace/core/test/DDCoreSpecification.groovy
Cherry picked from https://github.com/DataDog/dd-trace-java/pull/7388/files
=> Add _dd.tracer_host to local root spans

buildSrc/src/main/groovy/InstrumentPlugin.groovy
Rather than have a single cached class-loader that we then have to switch based on the plugin class-path, have a class-loader for each distinct set of plugins. This should be more stable and less complicated to manage.
Also avoids a potential concurrency issue where the `pluginCL` field was being accessed outside the `synchronized` block and could have been updated in another thread to use a different plugin class-path. Since each plugin set has its own stable class-loader and `pluginCL` is now a local variable this can no longer occur.
More stable builds 🍀
=> [🍒 7435] Cache separate InstrumentPlugin class-loader for each distinct set of plugins

buildSrc/src/main/groovy/InstrumentPlugin.groovy
Rather than have a single cached class-loader that we then have to switch based on the plugin class-path, have a class-loader for each distinct set of plugins. This should be more stable and less complicated to manage.
Also avoids a potential concurrency issue where the `pluginCL` field was being accessed outside the `synchronized` block and could have been updated in another thread to use a different plugin class-path. Since each plugin set has its own stable class-loader and `pluginCL` is now a local variable this can no longer occur.
More stable builds 🍀
=> Cache separate InstrumentPlugin class-loader for each distinct set of plugins

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymbolExtractor.java
Add support for module and mandated modifiers
Jira ticket: [DEBUG-2696]
[DEBUG-2696]: https://datadoghq.atlassian.net/browse/DEBUG-2696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add modifiers for extracting symbols

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ClassesToRetransformFinder.java
need to clone the list in classNamesBySourceFile Map to avoid concurrent modification of it while registering a new class
Jira ticket: [DEBUG-2575]
[DEBUG-2575]: https://datadoghq.atlassian.net/browse/DEBUG-2575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix concurrent modification

dd-java-agent/instrumentation/couchbase/couchbase-3.1/build.gradle, dd-java-agent/instrumentation/couchbase/couchbase-3.2/build.gradle
=> Skip couchbase-client 3.6.3 from muzzle checks

dd-java-agent/agent-otel/otel-bootstrap/build.gradle
* Include OTel instrumentation-api incubator types for messaging
=> OpenTelemetry drop-in fixes for Apache Pulsar

.circleci/config.continue.yml.j2
This PR add a smoke tests variant with SSI enabled
This should make sure to catch any issue introduced by SSI.
Jira ticket: [APMLP-110]
[APMLP-110]: https://datadoghq.atlassian.net/browse/APMLP-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add smoke test with SSI enabled

dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploaderScriptInitializer.java, dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/OOMENotifierScriptInitializer.java, dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/ScriptInitializer.java, dd-java-agent/agent-crashtracking/src/test/java/com/datadog/crashtracking/ScriptInitializerTest.java
Improve Crash Tracking and OOME notification scripts initialization to capture and explain as much as possible setup issues and avoid to add stacktraces in log events.
It also splits Crash Tracking and OOME Notifier initialization logic for readability.
Having stacktraces in startup log events bother the customers and creates escalations.
Jira ticket: [APMS-12931]
[APMS-12931]: https://datadoghq.atlassian.net/browse/APMS-12931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Improving crash tracking script initialization error handling

dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/ScriptInitializer.java
Stop printing the caught exception stacktrace unless logging at debug level.
Customers are scared and mislead by the exception stack tracer, mistaking it for application going down because of the exception.
Most of the work was already done in #7427 - this PR is just changing not to log full stacktrace for completely unexpected exceptions.
Jira ticket: [PROF-10405]
[PROF-10405]: https://datadoghq.atlassian.net/browse/PROF-10405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make the warning in ScriptInitializer less scary

dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
If smoke tests "mock agent" fails to decode a trace, bubble the exception up to waitForTraces (or eventually to cleanup). This way we get a clearer indication of the issue, rather than just a timeout on receiving the traces.
Faster troubleshooting.
Before this change:
```
Condition not satisfied after 30.00 seconds and 69 attempts
at spock.util.concurrent.PollingConditions.within(PollingConditions.java:185)
at spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:140)
at datadog.smoketest.AbstractSmokeTest.waitForTraceCount(AbstractSmokeTest.groovy:231)
at datadog.smoketest.AbstractSmokeTest.waitForTraceCount(AbstractSmokeTest.groovy:227)
at datadog.smoketest.appsec.SpringBootSmokeTest.rasp reports stacktrace on sql injection(SpringBootSmokeTest.groovy:282)
Caused by: …
```
=> Fail smoke tests if received traces cannot be decoded

dd-java-agent/appsec/src/main/resources/default_config.json
Updated ASM rules to version `1.13.1`
Enabled Exploit Prevention rules
=> Updated ASM rules to 1.13.1

.circleci/config.continue.yml.j2
This PR updates the pinned version of system tests.
Relevant changes from system tests:
* https://github.com/DataDog/system-tests/pull/2931
=> Update system-tests to 15713a66e48f82b7d995cea2eb6eb78bec0270df

.circleci/config.continue.yml.j2
Run all system-tests variants on CI.
Maximize functional test coverage.
Next step will be running all scenarios.
Jira ticket: [APPSEC-11137](https://datadoghq.atlassian.net/browse/APPSEC-11137) (partially)
[APPSEC-11137]: https://datadoghq.atlassian.net/browse/APPSEC-11137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Run all system-tests variants in CI

.circleci/config.continue.yml.j2
This PR updates the system tests
https://github.com/DataDog/system-tests/pull/2959
=> Update system-tests to 4145fd051e6d73685c443f373a3c7e4eb29b0309

.github/workflows/add-milestone-to-pull-requests.yaml
=> Fix GitHub milestone automation

dd-java-agent/instrumentation/jms/src/test/groovy/JMS1Test.groovy
Some tests seem to be leaking messages to queues to the next test. Make sure each test uses unique topics/queues.
=> Fix JMS flaky tests

.circleci/config.continue.yml.j2
This PR updates the system tests
Ship this fix: https://github.com/DataDog/system-tests/pull/2973
=> Update system-tests to 39bf65e0d94278c60fdd6ff85ba668cb436467f0

.circleci/config.continue.yml.j2
Includes https://github.com/DataDog/system-tests/pull/2998, which fixes builds.
=> Update system-tests to c87bd359aad64a29f280fc5c70a879f7c7f4846e

dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
=> add JFR queuetime threshold to recording settings

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/JDBCConnectionUrlParser.java
Some refactoring of logic warning I found while reviewing #7607 
cc @amarziali 
=> Clean up Maria DB parsing logic warnings

.circleci/config.continue.yml.j2
=> Consider Maven wrapper a global change for job skip script

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy
(cherry picked from commit 5f325b0e1498c3678de408ef6856d5fcebf0f156)
(#7586)
=> [🍒 7586] Fix Exploit Prevention capability announcement on remote config

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFStatsReporter.java
(cherry picked from commit 4ef9a807fb9d836196eec612e8fc2c4bfbd6603b)
(#7654)
=> [🍒 7654] Fix NPE in RASP metrics

dd-java-agent/appsec/build.gradle, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
(cherry picked from commit 0eb6f8c7c991183359caa33bde353a64312bbf5b)
(#7655)
=> [🍒 7655] Update libsqreen library to 11.0.1 fixing fingerprint generation

.circleci/config.continue.yml.j2
Includes https://github.com/DataDog/dd-trace-java/pull/7562 in the v1.39.1 patch milestone so that system tests succeed.
This needs to be a cherry picked commit.
=> Backport systest bump for release v1.39.x

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java, dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/SpringBootBasedTest.groovy, dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/TestEndpoint.groovy, dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/UserController.groovy
Ensures that duplicate addresses messages are sent only via telemetry and do not popup on customer logs.
Jira ticket: [APPSEC-55075]
[APPSEC-55075]: https://datadoghq.atlassian.net/browse/APPSEC-55075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensure 'attempt to replace context value' logs are set to debug

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java, dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/SpringBootBasedTest.groovy, dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/TestEndpoint.groovy, dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/UserController.groovy
Backport #7698 to release/v1.40.x
=> [🍒 7698] Ensure 'attempt to replace context value' logs are set to debug

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy, dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/SpringBootBasedTest.groovy
Backport #7699 to release/v1.40.x
=> [🍒 7699] Prevent publishing the same usr.id to the WAF twice

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/spanorigin/CodeOriginInfo.java
This will help resolve conflicts in `Where` definition conflicts.
Jira ticket: [DEBUG-2385]
[DEBUG-2385]: https://datadoghq.atlassian.net/browse/DEBUG-2385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update signatures to match symDB format

dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/RangesTest.groovy
This uncomment some tests that were commented
Jira ticket: [APPSEC-5758]
[APPSEC-5758]: https://datadoghq.atlassian.net/browse/APPSEC-5758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Uncomment tests for the forIndentation method

.circleci/config.continue.yml.j2, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java
make run flaky tests for debugger module
=> Add new assert to help troubleshoot flaky test

dd-java-agent/instrumentation/zio/zio-2.0/build.gradle
=> Run zio muzzle with java 11

dd-java-agent/instrumentation/protobuf/build.gradle
Follow up of #7746 
Muzzle step still broken in CI for protobuf instrumentation
=> Fix muzzle configuration for protobuf instrumentation

dd-java-agent/agent-iast/build.gradle, dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/ObjectVisitor.java, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/GrpcRequestMessageHandlerTest.groovy, dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/ObjectVisitorTest.groovy
Backport #7764 to release/v1.40.x
=> [🍒 7764] Limit the collections that the iast visitor can handle

.github/workflows/update-gradle-dependencies.yaml
follow up on https://dd.slack.com/archives/C047YAMGZ7T/p1728891323908619?thread_ts=1728885120.046349&cid=C047YAMGZ7T
we want code fixes for new versions support to show up in release notes.
=> Add a reminder to update the title of update PRs when fixes are needed

BUILDING.md
Improve BUILDING.md clarity and organization.
This document is very helpful for java onboarding and general referencing. While going through it myself, I thought the document could be edited and improved for clarity and organization.
=> Improve BUILDING.md

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java, dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
Add statistics about skipped frames (native or third-party) and the full stacktrace folded in order to troubleshoot
=> Add new debug logs when no probe for exception

.circleci/config.continue.yml.j2
Update system-tests, including https://github.com/DataDog/system-tests/pull/3274 which was blocking parametric upgrades.
=> Update system-tests to 53d9b2c43876a39e5c0426f4df4dd5fd79d062e8

dd-java-agent/instrumentation/kafka-clients-3.8/build.gradle, dd-java-agent/instrumentation/kafka-clients-3.8/src/test/groovy/KafkaClientCustomPropagationConfigTest.groovy, dd-java-agent/instrumentation/kafka-clients-3.8/src/test/groovy/KafkaClientTestBase.groovy
=> Disabled kafka tests due to flakiness

metadata/denied-environment-variables.tsv, metadata/requirements.json
Removes Hadoop from the requirements.json SSI denylist
DJM relies on the Hadoop instrumentation to integrate with Spark jobs. We didn't originally consider DJM to be in scope for SSI, hence the original addition. However as some customers are already using DJM with SSI we are removing it from the list.
DJM will add additional integration tests for the integration and SSI at a later date
Jira ticket: [APMLP-175]
[APMLP-175]: https://datadoghq.atlassian.net/browse/APMLP-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove hadoop from the denylist

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
This adds a visible warning when a user decides to modify the part of the profiler configuration that might lead to a JVM crash.
The 'safemode' comes from async-profiler and it allows for various heuristics to recover a stacktrace, otherwise unwalkable by ASGCT. However, this will increase the chance of crashing. 
The default value we provide is a very conservative one and we haven't seen any crashes induced by the heuristics enabled by that value. Therefore, we are quite confident that it is safe to be used in continuous profiling.
Any other values/safemodes are completely unsupported and up to the user to live with the risk. Hence, we want to be very vocal about this to avoid any confusion. …
=> Emit warning if a user overrides profiler safemode flag

.gitlab-ci.yml
Cherry pick https://github.com/DataDog/dd-trace-java/pull/7859
This weblog are tested on the nightly build.
The onboarding tests should be lightweight due to in the near future we are going to add more vms
=> [🍒 7859] Remove onboarding container jdk15 and buildpack tests

dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/ApplicationModuleTest.groovy
This PR fixes test name uniqueness.
This will help with CI monitoring to keep track of test execution.
=> Fix test name uniqueness

dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/resources/jfr/dd.jfp, dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/resources/jfr/overrides/comprehensive.jfp
=> enable SystemGC events

metadata/denied-environment-variables.tsv, metadata/requirements.json
Backport #7916 to release/v1.42.x
=> [🍒 7916] Remove SSI guardrails entries for hbase and hive

.circleci/config.continue.yml.j2
=> Make latest dep tests required in CI

tooling/backport-pr-to-patch-release.sh
This PR checks that back-ported PRs don't contain merge commit.
The script was unexpectedly failing when trying to cherry-pick a merge commit (did not know which was the parent to compute diff from as merge commits have multiple parents).
Instead of failing, the script will now propose the caller to merge the PR merge commit instead.
Doing so will no more back-port every single commit of the PR but only the single merge commit of the PR (the resulting commit of merging the PR to back-port).
```shell
- Checking gh is installed
- Checking jq is installed
- Checking there is no local changes
- Checking remote release branch exists
- Checking PR exists
- Checking PR does not contain merge commit
PR 7900 contains a merge commit: e91eeda194fd91799ca643238faf0ada641886e1
Merge commit changes: …
```
=> Improve PR back-port script to handle merge commit

dd-java-agent/appsec/src/main/resources/default_config.json
Updated ASM rules to version `1.13.3`
=> Updated ASM rules to 1.13.3

.circleci/config.continue.yml.j2
=> Update system-tests to 67fe30ac7504997685859d31feae1782f3527f39

internal-api/src/test/java/datadog/trace/util/stacktrace/StackUtilsTest.java
=> Unique test names in StackUtilsTest

dd-java-agent/instrumentation/grpc-1.5/build.gradle, dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcCodeOriginTest.groovy
Simplifies the test to check a smaller set of data that we need to actively worry about.
=> Only check that the first frame tags are present.  

dd-java-agent/instrumentation/ignite-2.0/src/main/java/datadog/trace/instrumentation/ignite/v2/cache/SpanFinishingCallback.java
=> Remove dangling stderr print

.circleci/config.continue.yml.j2
Latest system tests, include fixes for less flakiness on system tests builds. …
=> Update system-tests to 6a8c4e9ba065bc52a630051a5b7bb7a4ec84e245

.circleci/config.continue.yml.j2
Updates pinned commit of system-tests to the latest one in `main` …
=> Update system-test commit to 752456136fab0642446d124ead05aa7d8f4fa5c4

.circleci/config.continue.yml.j2
Update system-tests to last version
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/j …
=> Update system-tests to 2d531d6f809cfcdd5d6d375f92bda86202dea332

static-analysis.datadog.yml
=> Remove more test files from static analysis

dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
With this change we make less redundant a block of code that was calling multiple times one method.
Make more readable the code.
- Update …
=> Refactor appsec.waf.updates and appsec.waf.init success tag

dd-java-agent/instrumentation/wildfly-9/build.gradle, dd-java-agent/instrumentation/wildfly-9/src/test/java/test/ModulePatchInstrumentation.java
Uses maven artifact for pulling wildfly distributions
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collectio …
=> fix wildfly module dependencies

.github/workflows/analyze-changes.yaml
Removed unused deprecated input to the Datadog static analyzer
Check https://github.com/DataDog/datadog-static-analyzer-github-action#deprecated-inputs …
=> Clean up deprecated input of static analyzer

.circleci/config.continue.yml.j2
Update system-tests commit
It is necessary to update to a version that has the IAST stacktrace vulnerability tests disabled, as they have been modified to comply with the specifications in the RFC
related with APPSEC-56772
Use `solves` instead, and assign …
=> Update system-tests commit

.github/CODEOWNERS
=> Amend CODEOWNERS for some ASM classes

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/CodeOriginIntegrationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ExceptionDebuggerIntegrationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ProbeStateIntegrationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ServerAppDebuggerIntegrationTest.java, dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SpanDecorationProbesIntegrationTests.java
refactor smoke test to be able to add JVM options/properties 
add smoke test for max captured frames …
=> Add Exception Replay smoke test

.circleci/config.continue.yml.j2
Enable the following system-tests scenarios:
```
APPSEC_API_SECURITY
APPSEC_API_SECURITY_RC
APPSEC_API_SECURITY_WITH_SAMPLING
```
Not adding `APPSEC_API_SECURITY_NO_RESPONSE_BODY` which is currently irrelevant for Java, since we do not implement this functionality at all.
Ensure we do not break anything as we start modifying API Security features now.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-reque …
=> Enable system-tests scenarios for API Security

dd-java-agent/agent-profiling/profiling-controller/build.gradle, dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/TempLocationManagerTest.java
Mark profiling test as flaky
Keep CI green
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_c …
=> Mark profiling test as flaky

.circleci/config.continue.yml.j2
=> Update system-tests to 0509dbd094c9cbf15f58db96f62276a0adff7efa

.circleci/config.continue.yml.j2
Including:
* https://github.com/DataDog/system-tests/pull/4048
* https://github.com/DataDog/system-tests/pull/4235 …
=> Update system-tests to ffc1cfbe944dcf466606a84b4a442b990f675979

.circleci/config.continue.yml.j2
Includes:
* https://github.com/DataDog/system-tests/pull/4248 …
=> Update system-tests to 344e4abc912ada8004f2d0828a09efb65b5ee1e1

.circleci/config.continue.yml.j2
Unblock CI for previously failing system-tests for the following [PR](https://github.com/DataDog/dd-trace-java/pull/8489).  Fixed by the following system-tests [PR](https://github.com/DataDog/system-tests/pull/4251). …
=> Update system-tests to 590162e1f5223cbbcd2876fdb820837cb13a85e1

dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.3/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/KotlinCoroutines13Instrumentation.java, dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.5/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/KotlinCoroutines15Instrumentation.java, dd-java-agent/instrumentation/kotlin-coroutines/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/AbstractCoroutinesInstrumentation.java, dd-java-agent/instrumentation/kotlin-coroutines/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/CoroutineContextHelper.java, dd-java-agent/instrumentation/kotlin-coroutines/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/DatadogCoroutineContext.java
That's why the final target of this stacked PR is the `project/context` feature branch. …
=> Migrate kotlin coroutines instrumentation to new Context API

dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTScopeManager.java, dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTScopeManager.java, dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java, dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScope.java, dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java, dd-trace-ot/src/main/java/datadog/opentracing/OTScopeManager.java, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScope.java, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/NoopScope.java
No reason to leak this into the instrumentation API
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/ …
=> Remove AgentScope.source() from instrumentation API

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/percentage/CoverageCalculator.java, dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/percentage/JacocoCoverageCalculator.java, dd-java-agent/instrumentation/gradle-8.3/src/main/groovy/datadog/trace/instrumentation/gradle/AndroidGradleUtils.groovy
Backport #8521 to release/v1.47.x
=> 🍒 8521 - Fix NPE when calculating code coverage for Gradle projects with non-standard directory layout

internal-api/build.gradle, internal-api/src/main/java/datadog/trace/bootstrap/config/provider/EnvironmentConfigSource.java, internal-api/src/main/java/datadog/trace/bootstrap/config/provider/SystemPropertiesConfigSource.java
Backport #8544 to release/v1.47.x
=> 🍒 8544 - Make the default config sources more robust when a security manager is installed

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/InProductEnablementIntegrationTest.java
=> mark as flaky testExceptionReplayEnablement

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/WebsocketDecorator.java, dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
Reverts DataDog/dd-trace-java#8578
It looks like it will be a metric :)
=> Revert "Inherited decision maker is a meta"

dd-java-agent/instrumentation/spring-webmvc-3.1/build.gradle, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/datadog/trace/instrumentation/springweb/HandlerMappingResourceNameFilterForkedTest.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/datadog/trace/instrumentation/springweb/ResteasySpringBeanProcessorForkedTest.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/datadog/trace/instrumentation/springweb/SingleEndpointController.java, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/SetupSpecHelper.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/AppConfig.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/AuthServerConfig.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/CustomBeanClassloaderTest.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/CustomClassloaderConfig.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/SavingAuthenticationProvider.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/SecurityConfig.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/SpringBootBasedTest.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/SpringBootServer.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/SpringInactiveAppSecTest.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/TestController.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/TestProvider.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/WebsocketConfig.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/WebsocketEndpoint.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/iast/HandlerMethodReturnValueHandlerCompositeInstrumentationTest.groovy, dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/resources/logback.xml
Add the latest test for spring boot 2 that was missing
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collecti …
=> Add latestdeptest for spring boot 2

.circleci/config.continue.yml.j2
=> Increase parallelism of check_inst, rather than bump heap max

gradle/libs.versions.toml
[Release notes](https://spockframework.org/spock/docs/2.3/release_notes.html)
`RepeatUntilFailure` ([PR](https://github.com/spockframework/spock/pull/1522)) is particularly interesting for flaky test troubleshooting. …
=> Upgrade to Spock 2.3

.circleci/config.continue.yml.j2
=> Update system-tests to 1de04c42cbd9783432258004e46eb5982bbc9fe5

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java, dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ScopeContinuation.java, dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
Follow-up to #8636 to handle the edge case where non-span context should be continued along with the span …
=> When continuing a span merge it with any non-span context

dd-java-agent/instrumentation/lettuce-5/build.gradle, dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ClientTestBase.groovy
=> Do not use strict write with latest lettuce

utils/socket-utils/src/main/java17/datadog/common/socket/TunnelingJdkSocket.java
Deletes print line creating *millions of log messages for customers.
Address support tickets such as: https://datadog.zendesk.com/agent/tickets/2101785, https://datadog.zendesk.com/agent/tickets/2101966 …
=> Delete print line

internal-api/src/main/java/datadog/trace/api/Config.java
Backport #8715 to release/v1.48.x
=> 🍒 8715 - Turn off JDK socket support by default

dd-java-agent/instrumentation/opensearch/rest/build.gradle
=> align opensearch rest muzzle to latestdep coverage

dd-java-agent/instrumentation/mule-4/build.gradle
Improve comment in the `build.gradle` file for mule instrumentation.
I made the original comment in #8731 and think it can be improved.
- …
=> Improve comment for mule instrumentation

dd-java-agent/instrumentation/vertx-mysql-client-4.0/build.gradle, dd-java-agent/instrumentation/vertx-mysql-client-4.4.2/build.gradle
Extend muzzle to latest. However muzzle passes because the advices are not applied . Implies we are not supporting version 5+
- Update the …
=> adjust muzzle for vertx-mysql-client

.circleci/config.continue.yml.j2
Bump check_base to xlarge
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in …
=> chore: bump check base to xlarge

.circleci/config.continue.yml.j2
=> Update system-tests to ab6cf66b9c744f4fc273907423e93598440cd211

metadata/README.md
Replace metadata/README.md content with link
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master/.github/CODEOWNE …
=> Replace SSI ReadMe content with link to Confluence

benchmark/README.MD
Improves the benchmark README file a bit
Improve documentation
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/maste …
=> Improve benchmark readme

.gitlab-ci.yml, build.gradle, gradle/repositories.gradle
Backport #8807 to `release/v1.50.x` branch
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master/.github/CODEOWNERS …
=> 🍒 8807 - Migrate publishing to Maven Central Portal 

internal-api/src/main/java/datadog/trace/api/Config.java
Follow up PR of #9063 
Fix the build
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master/.github/CODEOWNERS) …
=> Fix wildcard import

.gitlab-ci.yml
Add the `simple_onboarding_appsec` to the gitlab workflow.
Add system tests scenario for SSI Appsec.
- Update the …
=> Add SSI Appsec System tests

buildSrc/build.gradle.kts, buildSrc/call-site-instrumentation-plugin/build.gradle.kts, buildSrc/settings.gradle.kts, dd-java-agent/instrumentation/spring-webflux-6/build.gradle, gradle/libs.versions.toml
Refactored build scripts to use Spock version from catalog.
It is better to have versions to be in single place. This will simplify migration to next version. …
=> Refactored build scripts to use Spock version from catalog.

dd-smoke-tests/dynamic-config/src/test/groovy/datadog/smoketest/AppSecActivationSmokeTest.groovy
=> Flaky test for REMOTE CONFIG telemetry configuration annotated

.github/workflows/update-gradle-dependencies.yaml
Increase -Xmx2G -> -Xmx3G.
Fix OOM during action execution.
Action failed with error: `Cause 1: java.lang.OutOfMemoryError: GC overhead limit exceeded`
=> Attempt to fix OOM for `Update Gradle dependencies` action.

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/buffer/InjectingPipeOutputStream.java, dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/buffer/InjectingPipeWriter.java, dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/RumAsyncContextInstrumentation.java, dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/RumHttpServletRequestWrapper.java, dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/RumHttpServletResponseWrapper.java, dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java, dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Instrumentation.java, dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/WrappedServletOutputStream.java, dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaServletInstrumentation.java, dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/RumAsyncContextInstrumentation.java, dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/RumHttpServletRequestWrapper.java, dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/RumHttpServletResponseWrapper.java, dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/WrappedServletOutputStream.java, dd-java-agent/instrumentation/servlet/request-5/src/testFixtures/groovy/datadog/trace/instrumentation/servlet5/AsyncRumServlet.groovy, dd-java-agent/instrumentation/tomcat-5.5/src/latestDepTest/groovy/TomcatServletTest.groovy, dd-smoke-tests/rum/src/main/groovy/datadog/smoketest/rum/AbstractRumServerSmokeTest.groovy, dd-smoke-tests/rum/tomcat-10/src/main/java/com/example/HtmlAsyncServlet.java, dd-smoke-tests/rum/tomcat-10/src/main/java/com/example/Main.java, dd-smoke-tests/rum/tomcat-11/src/main/java/com/example/HtmlAsyncServlet.java, dd-smoke-tests/rum/tomcat-11/src/main/java/com/example/Main.java, dd-smoke-tests/rum/tomcat-9/src/main/java/com/example/HtmlAsyncServlet.java, dd-smoke-tests/rum/tomcat-9/src/main/java/com/example/Main.java, internal-api/src/main/java/datadog/trace/api/Config.java, internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java, internal-api/src/main/java/datadog/trace/api/rum/RumInjector.java, internal-api/src/test/groovy/datadog/trace/api/rum/RumInjectorTest.groovy
Backport #9333 to release/v1.52.x
=> 🍒 9333 - Support async servlet for RUM injection

communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
Backport #9353 to release/v1.52.x
=> 🍒 9353 - Avoid NPE on featureDiscovery creation

internal-api/src/main/java/datadog/trace/api/Config.java, internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Backport #9401 to release/v1.52.x
=> 🍒 9401 - Properly fall-back on UDS profiling URL

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ScopeContinuation.java, internal-api/build.gradle.kts, internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScope.java
Assist further migration of instrumentations to Context-first API
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/ma …
=> Provide access to the captured Context from its Continuation

dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java
Reverts DataDog/dd-trace-java#9473
This PR should be rolled back since what done inside does not prevent any race condition. I will remove that PR from the release notes. Also, concerning the system tests failing because of missing stats, this is due to the agent feature discovery that's not updated atomically (see #9497  that is the real fix)
=> Revert "Avoid race conditions between contributing and writing to a stat aggregate"

dd-java-agent/appsec/build.gradle, dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/ddwaf/WAFModule.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java, dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java, dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/ddwaf/WAFModuleSpecification.groovy, dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/TraceTaggingSmokeTest.groovy
statuses can now be int and corrects a small bug for sampling
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master …
=> Upgrade libddwaf to 1.28.1

buildSrc/src/main/kotlin/datadog/gradle/plugin/muzzle/MuzzleMavenRepoUtils.kt
Auto retry version resolution range. It seems that the maven proxy might answer incorrect ranges.
THis code detects this case and retries the resolution, if this failed after 3 more attempts, a failure is
raised suggesting to restart the job later.
Use …
=> Retries the version range resolution in MuzzlePlugin

docs/how_instrumentations_work.md, docs/how_to_test.md
Update the developer documentation with the latest instrumentation layout, the new instrumentation tests runner, and add a  note about exception suppression on constructor.
Keep the documentation up-to-date …
=> Update doc with latest layout, instrumentation tests updated, and exception suppress note

dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleLauncherSmokeTest.groovy
- Adds retries to the `./gradlew wrapper` command in `GradleLauncherSmokeTest` to avoid flakiness due to connection issues.
- Update the …
=> Add retries to Gradle wrapper test command in Launcher smoke test

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
in a loop can generate a lot of logs
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master/.github/CODEOWNERS) file …
=> Throttle warning log when resolving probe
