DataDog/dd-trace-java

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java
This lets us skip various location checks and immediately re-use the cached `java.` type description regardless of where it was originally cached from. Otherwise we have to compare the class-file location to be confident that class `Foo` cached while processing a class from class-loader `A` is the same as class `Foo` needed to process a different class from class-loader `B` (The location check is still needed for non `java.` types because `A` and `B` might well end up resolving different versions of `Foo` in modular environments.)
This is especially beneficial on large modular systems where the class-loaders don't follow the classic delegation model.
> Optimization: assume there is only one version of 'java.*' classes in the JVM process

- dd-java-agent/agent-profiling/profiling-auxiliary-ddprof/src/main/java/com/datadog/profiling/auxiliary/ddprof/AuxiliaryDatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
* We should be checking if the auxiliary profiler is available before registering the periodic event, not just that the instance isn't null
* We should make a bit more noise in the logs if the user has installed the profiler and we can't instantiate the profiler, so issues can be resolved faster
* We don't need to rethrow exceptions from the periodic event once they have been logged
> profiler availability check

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/Arch.java
amr64 and aarch64 are the same thing. This change means we try to load profiler libraries built as "arm64" on aarch64. Really, we should prefer "aarch64" but this would require two coordinated changes and I think we can live with arm64 as our canonical representation.
> conflate arm64 with aarch64 correctly

- dd-java-agent/agent-debugger/build.gradle
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/SnapshotSummaryBuilder.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/SummaryBuilder.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/ListValue.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/MapValue.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/LogMessageTemplateSummaryBuilder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/ValueSerializer.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogMessageTemplateSummaryBuilderTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/CapturedValueAdapterTest.java
Primitives are printed as is,
collections/maps are printed up to 3 elements/entries Complex classes are printed with fields up to 5 and deep level 1. Refactored how we serializew value for sharing with Json snapshot serializations and applied limits
Coherent log line parameter representation
> Add formatting object values for log lines

- build.gradle
jcraft jsch was unmaintained for years.  Use com.github.mwiede fork instead.
> substitute jsch fork

- dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpExtractorTest.groovy
Solves #4511
During the cleanup of the map, derived from the configuration, the baggage keys were converted to lowercase.
This PR skips the conversion to lowercase strings for baggage keys.
Keep case sensitivity of baggage keys throughout the library.
> Handle mapped baggage keys as case sensitive

- dd-java-agent/instrumentation/spring-cloud-zuul-2/src/test/groovy/ProxyRequestHelperTest.groovy
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedContext.java
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpExtractorTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TagContext.java
Solves #4516
This PR modifies which extracted information is used when creating a new trace.
Due to Baggage mapping, there now is a possible need to map headers into new created traces.
No failing test - If someone can point me to the correct test cases to improve to cover this change please do so.
> Consider Baggage when creating new root traces

- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ProfilingContextIntegration.java
I'm not sure how this compiles at all (@mcculls probably does 😅 ), but IntelliJ finds the type name `NoOp` ambiguous because there are two of them in scope.
> fix IDE error because of ambiguity

- internal-api/src/main/java/datadog/trace/api/cache/CHMCache.java
- internal-api/src/main/java/datadog/trace/api/cache/DDCache.java
- internal-api/src/main/java/datadog/trace/api/cache/DDCaches.java
- internal-api/src/main/java/datadog/trace/api/cache/DDPartialKeyCache.java
- internal-api/src/main/java/datadog/trace/api/cache/FixedSizeCache.java
- internal-api/src/test/groovy/datadog/trace/api/cache/FixedSizeCacheTest.groovy
Changes the `FixedSizeCache` implementation to allow for a partial key cache, where two extra integers are provided as arguments to hash, compare and produce functions.
This is in preparation for doing value lookups from of parts of strings while not creating any extra objects (i.e. substring instances or wrappers holding the arguments).
Naming is hard.
> Add partial key cache to enable cache lookup from parts of keys

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ClassesToRetransformFinder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationComparer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/SourceFileTrackingTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/TransformerDefinitionMatcher.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/ClassFileHelper.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationComparerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/InnerHelper.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SourceFileTrackingTransformerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/TransformerDefinitionMatcherTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/ClassFileHelperTest.java
Allows the DebuggerTransformer to find inner classes when using file+line probe definitions.
Reporting of line not found was removed because it can be found latter by loading inner/top-level class.
When class are already loaded, we need to retransform them for passing through the `DebuggerTransformer`.
But to detect which class need to be retransformed, we rely on the naming. However inner classes or Top-Level classes are independent class files and the only way to associate them is the sourcefile attribute in each class file.
Track all dependent classes by their source file, so it easier to find all related class given a filename.
This avoids scanning all loaded classes to parse their sourcefile and try to match with actual probe definitions.
Support line probe in inner/top-level classes …
> Fix inner classes matching for line probes

- .github/workflows/lib-injection.yaml
There is a slack thread where lib injection images cannot be pushed to GCR due to changes to buildx
> pin buildx version for publishing to GCP

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/DebuggerScript.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/ProbeCondition.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/ValueScript.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/LogMessageTemplateSummaryBuilder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogMessageTemplateSummaryBuilderTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
ValueScript is storing result value in a field which can be overwritten by another execution. Now the execute method returns directly the result value and ValueScript became effectively stateless regarding execution.
Bug in log template evaluation for concurrent requests
> Fix log template evaluation

- dd-java-agent/instrumentation/servlet/request-5/build.gradle
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaServletRequestCallSite.java
- dd-java-agent/instrumentation/servlet/request-5/src/test/groovy/JakartaCallSiteTest.groovy
- dd-java-agent/instrumentation/servlet/request-5/src/test/java/foo/bar/smoketest/JakartaTestSuite.java
Instrument the jakarta servlet API
This API is used in a number of frameworks (spring) and web servers. We need to instrument it so we can taint the API output for IAST use.
> Support Jakarta servlet in IAST

- dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/exceptions/ExceptionProfiling.java
- dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/exceptions/ExceptionSampleEvent.java
- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Allows users to opt out of exception message capture by setting `-Ddd.profiling.exception.record.message=false` or `DD_PROFILING_EXCEPTION_RECORD_MESSAGE=false`
> Add flag to disable collection of exception messages in exception profiling

- dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatSettings.java
Prevent a NPE when the system property datadog.slf4j.simpleLogger.logFile doesn't contain a path, only a filename.
> Fix NPE when the configured log file doesn't have a path (current directory)

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Instrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/LogInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/controller/WebController.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java
The fix consists to reassigned local var information to arg slot. 
Added smoke tests for this case.
When instrumenting a method with a debugger probe that contains also tracer instrumentation (using @trace annotation or `trace.methods` property) argument names was not mapped correctly and p0, p1, appears in the snapshot.
This is due to ByteBuddy transformation messing up the LocalVariableTable that helps to maps local vars with names. Args are also local vars and following the JVM spec, the first local vars must match the methods args.
LocalVariableTable is optional and only used for debugger so it does not prevent the actual execution of the method.
Example with petclinic:
`VetController.processWithArg` method:
```
LocalVariableTable:
Start  Length  Slot  Name   Signature
0       8     0 …
```
> Fix incorrect arg name for already traced methods

- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/ClientCallImplInstrumentation.java
Activates the client span in the request method, which ensures context propagation throughout the call. 
Better profiler integration for code hotspots.
> activate grpc.client span in ClientCall.request and ClientCall.halfClose

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ValueReferences.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/Values.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/Value.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/ObjectValue.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ExpressionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/RefResolverHelper.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/HasAllExpressionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/HasAnyExpressionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/ValueRefExpressionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_01.json
- dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_04.json
- dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_05.json
- dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_06.json
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/LogMessageTemplateSummaryBuilder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/LogInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CaptureAssertionHelper.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java
Capture `this` object as arguments for instance method. Then can be resolved as normal object reference and be used in EL
Be able to use `this` as real object reference instead of string field prefix in Expression Language
> Add support for `this` as object reference in Expression Language

- .circleci/config.yml
If reference `refs/pull/<PR>/merge` is not up-to-date, fallback to `refs/pull/<PR>/head`.
We test PRs in CI based on their merge branch. Whenever there is a conflict with master, that git reference will point to outdated code.
> Fallback to run CI in /head of PR /merge

- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
Fix build for agent-iast.
Somehow these final parameters produce (flaky!) build errors after Spock transformations.
```
> Task :dd-java-agent:agent-iast:compileTestGroovy
startup failed:
/home/circleci/dd-trace-java/dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy: -1: The variable [builder] is declared final but is reassigned
. At [-1:-1]  @ line -1, column -1.
1 error
```
> Fix build for agent-iast tests

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
remove disabling the DebugerAgent if datadog agent config was not found at boot time. 
Unlike other endpoints, configEndpoint get attached after datadog agent [remote config client started](https://github.com/DataDog/datadog-agent/blob/7b816420a1774438524b392342f8fa3f94880473/cmd/trace-agent/run.go#L204).
The solution is to remove this check and let configurationPoller discovery that endpoint at later point in time.
Our customer have setup that start both library and datadog-agent almost at the same time.
That causes DebuggerAgent to cancel it boot sequence because config endpoint was not found. 
On the other hand, ASM products doesn't check for config endpoint and register itself.
Therefore, configurationPoller retried agent discovery until it find the configEndpoint and start getting …
> remove debugger check for config endpoint at bootstrap

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerProductChangesListener.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerProductChangesListenerTest.java
copy a log probe when receive new configuration to detect changes for a duplicated probe
Since we keep the same instance of deserialized probe and for duplicated we add them in the log definition as additional probes, changes are not detected with ConfigurationComparer
> Fix duplicated probe not instrumented

- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4SuiteEventsInstrumentation.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Utils.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/TracingListener.java
This PR modifies `junit-4` instrumentation so that it injects our custom code before/after `org.junit.runners.ParentRunner#run()` method.
The injected code examines registered JUnit listeners, and if Datadog CI Visibility listener is found, its custom event hooks are executed:
* `testSuiteStarted()`
* `testSuiteFinished()`
The event hooks will be used by CI Visibility logic to support test suites instrumentation and reporting.
Latest version of JUnit 4 (.13) has similar hooks, but we have to support older versions as well so custom hooks were introduced.
The custom hooks are invoked from the same places as the standard JUnit 4.13 hooks.
> Add test suite start/finish notifications to JUnit 4

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
Remove a check in DebuggerAgent bootstrap to ensure DebuggerEndpoint is available on the agent. This is always true as remote config endpoint which is also required was added after the debugger endpoint to the agent.
Simplify the logic
> remove unnecessary check when debugger agent bootstraps

- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/ClientCallImplInstrumentation.java
- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/ManagedChannelImplInstrumentation.java
- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AbstractExecutorInstrumentation.java
This moves starting the span to `ManagedChannelImpl#newCall`, which ensures there is an active span when `PendingCall`s are created and reprocessed (where the real call is created) within a synchronization context, which requires whitelisting one of grpc's executors.
Better code hotspots for grpc client
> Ensure propagation to gRPC pending calls to improve Code Hotspots for gRPC client

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/sink/snapshotWithEvalErrorRegex.txt
Creates a copy of the current snapshot and depending of the probe definition indicates capturing or not, includes the captured data (`Captures` object)
When creating 2 log probes on the same method (duplicated), one is capturing the other not, snapshots with captured data included are sent in both cases.
> Fix mixing capturing and non-capturing log probes

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastRequestContext.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/TaintedObjects.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedMapTest.groovy
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedObjectsLogTest.groovy
Use an object pool for `TaintedObject` instances.
Allocating 16k TaintedObject[] tables within TaintedMap creates a considerable GC churn. We use a small object pool for TaintedObjets instead, and use it to reuse instances between requests.
Note that, with asynchronous processing, there might be cases where a request gets a TaintedObject instance that is already being used by next request. This should be no problem: usually get calls will find nothing.
This change means that TaintedMap.clear needs to be thread-safe, so added tests checking that.
> Reuse TaintedMap instances in IAST

- .circleci/config.yml
- .circleci/fetch_docker_images.sh
- .circleci/prepare_docker_env.sh
- .circleci/start_docker_autoforward.sh
Prefetch Docker images in tests in a background CI job.
This should speed up container start time by pulling images early in the pipeline, in the background.
> Prefetch Docker images in tests and reorganize Docker scripts

- dd-trace-core/src/jmh/java/datadog/trace/core/propagation/InjectorBenchmark.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/PropagationTags.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/PropagationTagsFactory.java
- dd-trace-core/src/test/groovy/datadog/trace/common/sampling/SingleSpanSamplerTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogPropagationTagsTest.groovy
Fix Single Span Sampling for root spans to keep an SSS decision separate from a trace sampling priority, so child spans will be dropped when the entire trace has to be dropped even if the parent span is kept by SSS.
Fix for when a root span is sampled by the single span sampling but the entire span is dropped.
The problem is that when a span doesn’t have an explicitly set sampling priority then it gets it from the root span context. It’s done to preserve a sampling priority in case of partial flush (https://github.com/DataDog/dd-trace-java/pull/3412). This logic was implemented before single span sampling was introduced.
Now, when a root span is sampled by the single span sampling mechanism, it overrides the already set dropping priority causing a child span (without priority -128) to use …
> Fix Single Span Sampling for parent spans

- .circleci/config.yml
- dd-java-agent/agent-bootstrap/src/main/resources/META-INF/native-image/com.datadoghq/dd-java-agent/reflect-config.json
This allows spring-native to load our custom filter beans which are registered dynamically via the bean registry
> Add the tracer's new springweb6 filters to reflect-config.json

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingIntegration.java
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TestProfilingContextIntegration.groovy
- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
- gradle/dependencies.gradle
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ProfilingContextIntegration.java
> Profiler API to record time spent in queues

- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/SynchronizationContextInstrumentation.java
- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/TimedRunnable.java
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TestProfilingContextIntegration.groovy
Tells the profiler how long gRPC requests spend scheduled in the `SynchronizationContext`. This work is temporary and will eventually be superseded by a generic implementation that will support any kind of asynchronous scheduling.
> track gRPC scheduling time in SynchronizationContext

- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
Removes adding `_dd.p.dm` for spans selected by Single Span Sampling.
This tag should only be added for the trace, not individual spans.
Related to the recent fix: #4674
> Do not add the `_dd.p.dm` tag for spans selected by SSS

- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/ClientCallImplInstrumentation.java
- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/MessagesAvailableInstrumentation.java
- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AbstractExecutorInstrumentation.java
- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java
`SerializingExecutor` is implemented as follows:
```java
public final class SerializingExecutor implements Executor, Runnable {
...
/**
* Runs the given runnable strictly after all Runnables that were submitted
* before it, and using the {@code executor} passed to the constructor.     .
*/
@Override
public void execute(Runnable r) {
runQueue.add(checkNotNull(r, "'r' must not be null."));
schedule(r);
}
private void schedule(@Nullable Runnable removable) {
if (atomicHelper.runStateCompareAndSet(this, STOPPED, RUNNING)) {
boolean success = false;
try {
executor.execute(this);
success = true;
} finally {
// It is possible that at this point that there are still tasks in
// the queue, it would be nice to keep trying but the error may not
// be recoverable.  So we update our state and …
```
> Fix context propagation in gRPC `SerializingExecutor`

- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/ClientCallImplInstrumentation.java
#4680 accidentally removed some instrumentation which isn't tested without creating a remote gRPC server (a testing gap) which we just picked up. I have verified this fixes the issue manually but it would be a big effort to rework the test suite to prevent this from regressing.
> fix gRPC client span start

- dd-java-agent/instrumentation/apache-httpclient-5/src/test/groovy/ApacheHttpAsyncClient5Test.groovy
- dd-java-agent/instrumentation/mule-4/src/test/groovy/mule4/MuleForkedTest.groovy
- dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisAPITestBase.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
* Mark more tests as flaky, see issues below.
* Rename `ApacheHttpAsyncClientTest` to `ApacheHttpAsyncClient5Test` in `apache-httpclient-5` to distinguish it in test results, IDE, and make it easier to use flaky test selectors.
* https://github.com/DataDog/dd-trace-java/issues/3874
* https://github.com/DataDog/dd-trace-java/issues/4681
* https://github.com/DataDog/dd-trace-java/issues/4689
* https://github.com/DataDog/dd-trace-java/issues/4690
> Mark some more tests as flaky

- .circleci/cancel_workflow.sh
- .circleci/config.yml
- buildSrc/build.gradle.kts
- buildSrc/call-site-instrumentation-plugin/build.gradle.kts
* Split `check` job out of the critical path. If it fails, it cancels the whole workflow.
* Add a `spotless` job that runs early in the pipeline. No tests are run if formatting fails.
* Skip `buildSrc` tests in every job except in `check`.
So we don't delay starting tests, but if check fails, we still cancel the whole workflow.
> Split check job out of the critical path

- .circleci/config.yml
Use JDK 11 for spotless
spotlessCheck is flaky when using JDK 8. It sometimes gives this error:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dd-trace-ot:spotlessGroovy'.
[...]
Caused by: com.diffplug.spotless.ThrowingEx$WrappedAsRuntimeException: java.lang.Exception: You are running Spotless on JVM 8, which limits you to eclipse groovy formatter 4.19.0.
If you upgrade your JVM to 11+, then you can use eclipse groovy formatter 4.21.0, which may have fixed this problem.
[...]
Caused by: java.lang.Exception: You are running Spotless on JVM 8, which limits you to eclipse groovy formatter 4.19.0.
If you upgrade your JVM to 11+, then you can use eclipse groovy formatter 4.21.0, which may have fixed this problem.
at …
```
> Use JDK 11 for spotless

- dd-java-agent/agent-ci-visibility/build.gradle
- internal-api/build.gradle
Moves `dd-javac-plugin-client` dependency to from `agent-ci-visibility` module to `internal-api` module
`dd-javac-plugin-client` contains `SourcePath` annotation.
Customer classes can be annotated with this annotation in order to inform the runtime about source code location for a specific class (the annotation can be done automatically by the compiler plugin).
In case of customer classes the annotation will be loaded by the system class loader.
While `agent-ci-visibility` module is loaded by the agent's internal classloader, and so the annotation class that it loads is different from the annotation class with which the customer classes are annotated.
On the other hand, `internal-api` module is loaded by the system classloader.
So moving the dependency to that module (and loading it along …
> Move dd-javac-plugin-client dependency to internal-api module

- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- dd-trace-core/src/test/groovy/datadog/trace/common/sampling/SingleSpanSamplerTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
Cleans up Single Span Sampling logic to avoid changing the trace sampling priority.
The Agent doesn't care about the effective trace sampling priority and accepts single sampled spans anyway. So, this PR cleans this up to keep the original trace sampling priority.
https://github.com/DataDog/system-tests/pull/848#discussion_r1100563935
> Clean up Single Span Sampling logic. It shouldn't change trace sampling priority.

- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
Ignores when a customer uses a null resource name, either through APIs of the tag interceptor
A customer was overwriting a resource name when trying to set it to null. We decided ignoring the call is the best fix
> ignore null resource name

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerProductChangesListenerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogMessageTemplateSummaryBuilderTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/LogProbeTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/LogProbeTestHelper.java
only used for tests
code cleanup
> Move parseTemplate for log probes to tests part

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/JsonSnapshotSerializer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/CapturedValueAdapterTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/MoshiSnapshotTestHelper.java
- dd-smoke-tests/debugger-integration-tests/build.gradle
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
Snapshot deserialization is only used for test code. Isolate deserialization code from Moshi adapters to test helper class and share it also for smoke tests
Isolate snapshot deserialization code into test only
> Refactor Json deserialization for test code only

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
- dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringCallSite.java
- dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/StringCallSiteTest.groovy
- dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringSuite.java
- internal-api/src/main/java/datadog/trace/api/iast/propagation/StringModule.java
Instrument the String constructor
This is needed so tainted strings are propagated when the String constructor is called.
> String constructor instrumentation for IAST propagation

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilitySystem.java
This PR changes CI visibility subsystem initialisation so that it does not fail in case the tracer cannot detect customer's Git information.
Some customers use non-standard set ups and run CI visibility in environments where Git info is not available.
While many CI visibility features rely on Git info being there, the core functionality does not require it.
So in case it is missing, we should still do as much as we can, and not fail.
> Do not fail if git info is missing

- dd-java-agent/instrumentation/opentelemetry/src/test/groovy/TypeConverterTest.groovy
- dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/TypeConverterTest.groovy
- dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/TypeConverterTest.groovy
- dd-trace-core/build.gradle
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/monitor/HealthMetrics.java
- dd-trace-core/src/main/java/datadog/trace/core/monitor/NoOpHealthMetrics.java
- dd-trace-core/src/main/java/datadog/trace/core/monitor/TracerHealthMetrics.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/AbstractContinuation.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ConcurrentContinuation.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScope.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuingScope.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ScopeStack.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/SingleContinuation.java
- dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeAndContinuationLayoutTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerDepthTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
- dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
- dd-trace-ot/src/test/groovy/datadog/opentracing/TypeConverterTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScopeManager.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
This class splits the `ContinuableScopeManager` to introduce the future changes related to scoped context storage.
It does not change any logic from the original single file.
There will be different scope related changes. Splitting the `ContinuableScopeManager` will make things clearer, and git changes easier to merge.
All the commits will be squashed at merge.
> Refactor ScopeManager for future scoped context improvements

- .circleci/config.yml
- communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
- dd-trace-core/build.gradle
- dd-trace-core/src/test/groovy/datadog/trace/TracerConnectionReliabilityTest.groovy
Add some agent connection reliability tests to ensure the tracer is capable of sending traces on late agent start or after agent restart.
Ensure reliable tracer connection to the agent.
> Add agent connection reliability tests

- .circleci/config.yml
* Build cache does not need to be restored before the initial build, since we always `--rerun-tasks`.
* Gradle wrapper is already present in the dependency cache, and it does not change often, so it doesn't need to be saved on every build.
* System tests do not require any cache, just the built artifacts which are present in the workspace.
> Remove redundant caches from CI

- .gitlab-ci.yml
Two fixes:
* Change image path: from system-tests to dd-trace-java
* Remove manual trigger in order to avoid not ending checks in pull request. The build proccess will only trigger on a commit on master
> Fix docker base image gitlab jobs

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerProductChangesListener.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTracer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/SpanInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerProductChangesListenerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTracerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanProbeInstrumentationTest.java
Use constant for OperationName (spanName)
Use method name eventually + line numbers for resource name 
make it deserializable from remote config
> Remove span name

- dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.3/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/KotlinCoroutines13Instrumentation.java
- dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.5/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/KotlinCoroutines15Instrumentation.java
- dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.5/src/test/groovy/KotlinCoroutineInstrumentationTest.groovy
- dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.5/src/test/kotlin/KotlinCoroutineTests.kt
- dd-java-agent/instrumentation/kotlin-coroutines/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/AbstractCoroutinesInstrumentation.java
- dd-java-agent/instrumentation/kotlin-coroutines/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/CoroutineContextHelper.java
- dd-java-agent/instrumentation/kotlin-coroutines/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/ScopeStateCoroutineContext.java
Makes `ScopeStateCoroutineContext` inheritable by introducing an internal map of a child coroutine (aka Job) (inheriting the context) to the context item holding the continuation. This way each child coroutine will hold the same context element while having individual state internally.
Solves #4718 .
To fix an `IllegalStateException` thrown by [this](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/flow/internal/SafeCollector.common.kt) Flows collector in case of a modified context.
This is a followup to #4405 and  #4624
> Fix IllegalStateException caused by Flows instrumentation in Kotlin coroutines

- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnit5Instrumentation.java
This PR changes JUnit5 instrumentation: instead of adding CI Visibility listener in `org.junit.platform.launcher.Launcher#<init>` it now does so in `org.junit.platform.launcher.core.LauncherConfig#getAdditionalTestExecutionListeners`
Previous version hooked into every implementation of `org.junit.platform.launcher.Launcher`.
Sometimes, e.g. when JUnit5 is run with Maven, there are multiple nested launchers.
Adding the listener when each of these launchers is created leads to duplicates in the listeners collection.
As the result, every event is processed by CI Visibility multiple times (which is not a problem currently, due to various safety checks that exist in the code, but makes the code fragile and leads to redundant computation). 
Tested with Gradle/Jupiter engine, Maven/Jupiter …
> Fix duplicate listeners registration for JUnit5

- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/ConsumerCoordinatorInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerCallback.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
Add null check to fix a crash introduced by https://github.com/DataDog/dd-trace-java/pull/4616/files#diff-6228932522cfbf261e1cacb00103a4eaf3d68aafbc6f42494d57b9aa0eeb79c8R33
When metadata is null.
I also added null checks every else where not having them could crash the application.
> [data streams] Add null checks in Kafka

- dd-trace-api/src/main/java/datadog/trace/api/DDId.java
- dd-trace-api/src/main/java/datadog/trace/api/DDSpanId.java
- dd-trace-api/src/main/java/datadog/trace/api/DDTraceId.java
- dd-trace-api/src/main/java/datadog/trace/api/internal/util/HexStringUtils.java
- dd-trace-api/src/test/groovy/datadog/trace/api/DDSpanIdTest.groovy
- dd-trace-api/src/test/groovy/datadog/trace/api/DDTraceIdTest.groovy
Breaks out some hex string utilities used for both DDId and W3C headers.
Reuse all the things!
> Break out some hex string utilities used for W3C headers

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ProxyClassIgnores.java
Ignore additional proxy classes generated by Weld
https://github.com/DataDog/dd-trace-java/pull/3534 added certain classes generated by Weld to the ignore list, this PR adds additional classes based on real world usage.
> Ignore additional proxy classes generated by Weld

- dd-trace-core/src/main/java/datadog/trace/common/writer/ddintake/DDIntakeTraceInterceptor.java
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddintake/DDIntakeTraceInterceptorTest.groovy
- internal-api/src/main/java/datadog/trace/util/TraceUtils.java
This change fixes DD Intake trace interceptor.
The span writer ignored the interceptor because of deduplication logic (the writer stores a set of interceptors that are differentiated by priority; if multiple interceptors with the same priority are added to the writer, all but one will be ignored).
The fix is to change the priority of the interceptor, making it unique.
The goal of the interceptor is to normalise spans/tags submitted directly to DD Intake in agentless mode.
Normalisation includes filling in empty span fields with default values, or truncating fields that are too long.
The normalised fields are service name, operation name, resource name, span type, etc.
This normalisation logic is similar to what is done by the agent, which is why it needs to be replicated in agentless …
> Fix DD Intake trace interceptor

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
A trace may leak to the subsequent test.
> Fix flakiness in HttpServerTest

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
Fixes a problem introduced in commit 02dd2cea245c90da90443f5ae29ffa98149476eb. The theory being that when waiting for 1 trace, either 1 (the appsec-span) or 2 traces will be obtained. If 2 traces are obtained, then the cleanup wait for an extra trace will cause a longish delay.
> More appropriate fix for flakiness in HttpServerTest

- dd-java-agent/instrumentation/mongo/build.gradle
- dd-java-agent/instrumentation/mongo/common/src/main/java/datadog/trace/instrumentation/mongo/MongoCommandListener.java
- dd-java-agent/instrumentation/mongo/common/src/main/java/datadog/trace/instrumentation/mongo/MongoDecorator.java
- dd-java-agent/instrumentation/mongo/driver-3.1-core-test/build.gradle
- dd-java-agent/instrumentation/mongo/driver-3.1-core-test/src/test/groovy/MongoCore31ClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-3.1/build.gradle
- dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/MongoJava31ClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-3.10-sync-test/build.gradle
- dd-java-agent/instrumentation/mongo/driver-3.10-sync-test/src/test/groovy/MongoSyncClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-3.3-async-test/build.gradle
- dd-java-agent/instrumentation/mongo/driver-3.3-async-test/src/test/groovy/MongoAsyncClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-3.4/build.gradle
- dd-java-agent/instrumentation/mongo/driver-3.4/src/test/groovy/MongoJava34ClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-3.7-core-test/build.gradle
- dd-java-agent/instrumentation/mongo/driver-3.7-core-test/src/test/groovy/MongoCore37ClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-4.0/build.gradle
- dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/Mongo4ClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/MongoReactiveClientTest.groovy
- dd-java-agent/instrumentation/mongo/src/test/groovy/MongoBaseTest.groovy
- internal-api/src/main/java/datadog/trace/api/naming/NamingSchema.java
- internal-api/src/main/java/datadog/trace/api/naming/v0/DatabaseNamingV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v0/NamingSchemaV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v1/DatabaseNamingV1.java
- internal-api/src/main/java/datadog/trace/api/naming/v1/NamingSchemaV1.java
Implements naming schema changes for mongodb instrumentations (all drivers):
* service name: `{{DD_SERVICE}}-mongodb`
* operation: `mongodb.query`
> Naming schema: mongodb changes

- dd-java-agent/instrumentation/elasticsearch/rest-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/Elasticsearch5RestClientInstrumentation.java
- dd-java-agent/instrumentation/elasticsearch/rest-5/src/test/groovy/Elasticsearch5RestClientTest.groovy
- dd-java-agent/instrumentation/elasticsearch/rest-6.4/src/main/java/datadog/trace/instrumentation/elasticsearch6_4/Elasticsearch6RestClientInstrumentation.java
- dd-java-agent/instrumentation/elasticsearch/rest-7/src/main/java/datadog/trace/instrumentation/elasticsearch7/Elasticsearch7RestClientInstrumentation.java
- dd-java-agent/instrumentation/elasticsearch/src/main/java/datadog/trace/instrumentation/elasticsearch/ElasticsearchRestClientDecorator.java
- dd-java-agent/instrumentation/elasticsearch/src/main/java/datadog/trace/instrumentation/elasticsearch/ElasticsearchTransportClientDecorator.java
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/main/java/datadog/trace/instrumentation/elasticsearch2/Elasticsearch2TransportClientInstrumentation.java
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/main/java/datadog/trace/instrumentation/elasticsearch5_3/Elasticsearch53TransportClientInstrumentation.java
- dd-java-agent/instrumentation/elasticsearch/transport-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/Elasticsearch5TransportClientInstrumentation.java
- dd-java-agent/instrumentation/elasticsearch/transport-6/src/main/java/datadog/trace/instrumentation/elasticsearch6/Elasticsearch6TransportClientInstrumentation.java
- dd-java-agent/instrumentation/elasticsearch/transport-7.3/src/main/java/datadog/trace/instrumentation/elasticsearch7_3/Elasticsearch73TransportClientInstrumentation.java
- internal-api/src/main/java/datadog/trace/api/naming/v1/DatabaseNamingV1.java
v1 Naming schema changes for elasticsearch (both rest and node transport):
* service: `{{DD-SERVICE}}-elasticsearch`
* operation: `elasticsearch.query`
> Naming schema: elasticsearch

- dd-java-agent/instrumentation/datastax-cassandra-3/src/main/java/datadog/trace/instrumentation/datastax/cassandra/CassandraClientDecorator.java
- dd-java-agent/instrumentation/datastax-cassandra-3/src/main/java/datadog/trace/instrumentation/datastax/cassandra/TracingSession.java
- dd-java-agent/instrumentation/datastax-cassandra-3/src/test/groovy/CassandraClientTest.groovy
- dd-java-agent/instrumentation/datastax-cassandra-4/src/main/java/datadog/trace/instrumentation/datastax/cassandra4/CassandraClientDecorator.java
- dd-java-agent/instrumentation/datastax-cassandra-4/src/main/java/datadog/trace/instrumentation/datastax/cassandra4/TracingSession.java
- dd-java-agent/instrumentation/datastax-cassandra-4/src/test/groovy/CassandraClientTest.groovy
v1 changes for cassandra naming schema:
* service: `{{DD_SERVICE}}-cassandra`
* operation: `cassandra.query`
> Naming schema: cassandra

- gradle/dependencies.gradle
* Introduces rate limiting for non-JFR allocation profiling
* Combines allocation sampling for memory leak and allocation profiles (halves the overhead of having both profile types enabled)
* More efficient chunk rotation (reduces overhead)
> update to Java profiler library 0.15.0

- dd-java-agent/instrumentation/aerospike-4/src/main/java/datadog/trace/instrumentation/aerospike4/AerospikeClientDecorator.java
- dd-java-agent/instrumentation/aerospike-4/src/test/groovy/datadog/trace/instrumentation/aerospike4/AerospikeAsyncClientTest.groovy
- dd-java-agent/instrumentation/aerospike-4/src/test/groovy/datadog/trace/instrumentation/aerospike4/AerospikeBaseTest.groovy
- dd-java-agent/instrumentation/aerospike-4/src/test/groovy/datadog/trace/instrumentation/aerospike4/AerospikeClientTest.groovy
v1 naming schema changes for aerospike:
* service: `{{DD_SERVICE}}-aerospike`
* operation: `aerospike.query`
> naming schema: aerospike

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
- dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
- dd-java-agent/instrumentation/jdbc/src/test/groovy/RemoteJDBCInstrumentationTest.groovy
- internal-api/src/main/java/datadog/trace/api/naming/v1/DatabaseNamingV1.java
v1 naming schema changes for jdbc:
* service: `{{DD_SERVICE}}-{{DB_DRIVER}}`
* operation: `{{DB_DRIVER}}.query`
Special case for `postgresql` which will be renamed to `postgres`
> service naming: jdbc

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/RepoIndexSourcePathResolver.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/RepoIndexSourcePathResolverTest.groovy
This change updates logic that detects class source file paths, so that Kotlin classes are supported.
The logic is used by CI Visibility part of the tracer to set source code related tags.
Some of CI Visibility customers are using it with Kotlin-based projects.
The change consisted of three main parts:
* update the list of file extensions that are added to repository index, adding `.kt`
* add logic to infer class source language
* update condition for parsing class information to obtain the source file name attribute (previously that was done only for package-private classes, not it is also done for non-Java classes)
> Add source file path detection for Kotlin

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecorator.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/UriBasedClientDecorator.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/UrlConnectionDecorator.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/httpurlconnection/HttpUrlState.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/UrlConnectionDecoratorTest.groovy
- dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/UrlInstrumentation.java
- dd-java-agent/instrumentation/http-url-connection/src/test/groovy/HttpUrlConnectionTest.groovy
- dd-java-agent/instrumentation/http-url-connection/src/test/groovy/UrlConnectionTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
- internal-api/src/main/java/datadog/trace/api/naming/NamingSchema.java
- internal-api/src/main/java/datadog/trace/api/naming/v0/ClientNamingV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v0/NamingSchemaV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v1/ClientNamingV1.java
- internal-api/src/main/java/datadog/trace/api/naming/v1/NamingSchemaV1.java
v1 naming schema for url connection client spans:
* operation `{{protocol}}.client.request`
special cases for {{protocol}} :
* http/https -> will use http
* ftp/ftps -> will use ftp
> Naming schema: http url connection

- dd-trace-core/src/main/java/datadog/trace/common/writer/ddintake/DDIntakeTraceInterceptor.java
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddintake/DDIntakeTraceInterceptorTest.groovy
- internal-api/src/main/java/datadog/trace/util/TraceUtils.java
- internal-api/src/test/groovy/datadog/trace/util/TraceUtilsTest.groovy
This change updates span data normalisation logic used by DD Intake writer (i.e. in configurations where the tracer writes directly to backend, with no DD Agent involved).
The logic is updated so that `env` tag is set to `none` if no other value is provided for it (or if provided value is empty).
This was requested by the backend.
Normally this data normalisation is done by the agent, but in configurations where the tracer writes directly to the backend, it has to be replicated in the tracer.
> Set 'env' to 'none' if not set or empty

- build.gradle
- dd-smoke-tests/quarkus/application/build.gradle
- dd-smoke-tests/spring-boot-2.7-webflux/application/build.gradle
- dd-smoke-tests/spring-boot-3.0-webflux/application/build.gradle
- dd-smoke-tests/spring-boot-3.0-webmvc/application/build.gradle
- dd-smoke-tests/wildfly/spring-ear/build.gradle
- test-published-dependencies/build.gradle
Removes the dependency on `axion-release` from _external_ gradle projects and makes `test-published-dependencies` use a file with the right version written by the `main` project.
The `scmVersion.repository.directory` setting of the `axion-release` plugin doesn't seem to work in the same way anymore and the `currentVersion` task returns the wrong version, i.e. `1.8.0` instead of `1.9.0-SNAPSHOT`, so we test the wrong version in `test-published-dependencies`.
The dependency on the `axion-release` plugin in a number of smoke tests had already been _removed_ in 0e306a78196 by setting `version = ""`.
> Test the right version in test-published-dependencies

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
This change updates property names used by `AgentFeature` enum instances to refer to constants defined in config classes.
The property names are supposed to correspond to the constants, but it's easy to introduce a mistake (e.g. when a constant changes).
There was a mistake in `TRACING` instance, which referred to `"dd.tracing.enabled"` property, while the constant defined in the config was `"dd.trace.enabled"`.
As the result, tracing was enabled by default for customers that used CI visibility.
It was decided to leave it this way, since this is the behaviour that we've had for a while (due to the mismatch in property names).
> Update agent feature keys to refer to corresponding properties

- internal-api/build.gradle
Forces JDK 8 when compiling internal-api tests.
Unless JAVA_HOME was set to JDK 8, internal-api test compilation would fail.
> Fix internal-api test compile with JDK >8 default

- dd-java-agent/appsec/src/main/resources/default_config.json
Update ASM event rules to 1.5.1
See https://github.com/DataDog/appsec-event-rules/releases/tag/1.5.1
> Update ASM event rules to 1.5.1

- dd-trace-ot/build.gradle
- test-published-dependencies/ot-is-shaded/build.gradle
- test-published-dependencies/ot-pulls-in-api/src/test/java/CreateTracerTest.java
because it contains native methods that have to match to the embedded native libraries
> Avoid relocating com.kenai.jffi in dd-trace-ot

- dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java
- dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/HelperMethods.java
- dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/ApacheHttpClientInstrumentation.java
- dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/HelperMethods.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWS1ClientTest.groovy
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/LegacyAWS1ClientForkedTest.groovy
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test_before_1_11_106/groovy/AWS0ClientTest.groovy
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test_before_1_11_106/groovy/LegacyAWS0ClientForkedTest.groovy
- dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
- dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java
- dd-java-agent/instrumentation/aws-java-sdk-2.2/src/test/groovy/Aws2ClientTest.groovy
- dd-java-agent/instrumentation/aws-java-sdk-2.2/src/test/groovy/LegacyAws2ClientForkedTest.groovy
- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/LegacySqsClientForkedTest.groovy
- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/SqsClientTest.groovy
- dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/LegacySqsClientForkedTest.groovy
- dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/SqsClientTest.groovy
- dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientRequestTracingHandler.java
- dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientRequestTracingHandler.java
This PR removes the underlying HTTP client spans beneath AWS-SDK calls. The HTTP client span is an implementation detail of the AWS-SDK call, rather than a request to a different service, and collapsing the trace to just show the AWS-SDK calls makes distributed traces easier to follow.
Users who require the old behaviour can re-enable it with this system property:
```
-Ddd.aws-sdk.legacy.tracing.enabled=true
```
or by setting this environment variable:
```
DD_AWS_SDK_LEGACY_TRACING_ENABLED=true
```
We want to make SQS receive spans more consistent with other messaging integrations. This will involve excluding certain SQS calls from our AWS-SDK instrumentation and adding new SQS specific instrumentation. The new SQS instrumentation will avoid creating spans when no messages are received, …
> Simplify aws-sdk traces [1 of 3]

- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSHttpClientInstrumentation.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/OnErrorDecorator.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
- dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsHttpClientInstrumentation.java
- dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java
Avoid storing the scope in the v1 attributes; instead close any active AWS-SDK span when the client finishes its execution, like we do for v2. Also introduce a no-op scope when calling out from AWS to Netty in async mode to make sure that it can't accidentally capture continuations which incorrectly keep the AWS trace alive. (We close the AWS scope but there may be other scopes left on the stack that need protecting when the async AWS client calls Netty.)
> Simplify scope activation in AWS-SDK instrumentations [2 of 3]

- dd-trace-api/src/main/java/datadog/trace/api/PropagationStyle.java
- dd-trace-api/src/main/java/datadog/trace/api/TracePropagationStyle.java
- dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/NoneCodec.java
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpInjectorTest.groovy
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Changes some names of `DD_TRACE_PROPAGATION_STYLE_*` settings to align with other Datadog tracers.
Minimize discrepancies in configuration between Datadog tracers.
This is a breaking change if someone started using `DD_TRACE_PROPAGATION_STYLE*` settings and the `B3` propagator since `B3` now mean [B3 multi header](https://github.com/openzipkin/b3-propagation/tree/master#multiple-headers) while before it meant [B3 single header](https://github.com/openzipkin/b3-propagation/tree/master#single-header). The risk of this is considered low, since the setting has not been documented yet.
> Align DD_TRACE_PROPAGATION_STYLE* names with other tracers

- dd-trace-ot/build.gradle
Excludes `datadog.trace.api.internal.util` from shading in `dd-trace-ot`
It should not be shaded.
Does not affect anything right now by pure luck, since none of the `core` classes access anything in that package directly. The W3C propagator will, and then things break since the class won't exist.
> Exclude datadog.trace.api.internal.util from shading in dd-trace-ot

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
- dd-trace-core/src/main/java/datadog/trace/common/writer/ddintake/DDIntakeTraceInterceptor.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java
This change updates integration tests that verify test frameworks instrumentation (junit4, junit5, test NG).
The update is to add `env` tag assertion for every emitted span.
A [recent change](https://github.com/DataDog/dd-trace-java/pull/4765) introduced logic that populates `env` tag with a default value if it is missing (only when running the tracer in agentless mode).
The integration tests require every span tag to be asserted, which is why assert for `env` tag needs to be added.
It is only verified that the tag is always present, its contents are checked by the tests that were added for the earlier change.
> Add 'env' tag assertion to test frameworks integration tests

- .circleci/config.yml
- build.gradle
- dd-java-agent/agent-debugger/build.gradle
- dd-java-agent/agent-iast/build.gradle
- dd-java-agent/agent-profiling/build.gradle
- dd-java-agent/instrumentation/build.gradle
- dd-smoke-tests/build.gradle
Create gradle tasks for the various test subsets used in CI.
After this change:
* `test -PskipInstTests -PskipSmokeTests -PskipProfilingTests"` -> `:baseTest` or `:baseTest -PskipInstTests -PskipSmokeTests -PskipProfilingTests"` (skip flags should not be strictly needed, keeping them just in case we have some weird task dependencies)
* `:dd-smoke-tests:test` -> `:smokeTest`
* `:dd-java-agent:instrumentation:test` -> `:instrumentationTest`
* `:dd-java-agent:agent-debugger:test` -> `:debuggerTest`
* `:dd-java-agent:agent-profiling:test` -> `:profilingTest`
* `:dd-java-agent:agent-iast:test` stays the same  (no submodules)
* Makes it easier to run only tests in the parent module but not in child modules (convenient for task parallelization).
* Avoids compiling tests (and other gradle tasks …
> Move aggregate tasks to gradle

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingIntegration.java
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TestProfilingContextIntegration.groovy
- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java
- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ScopeStack.java
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
- gradle/dependencies.gradle
- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ProfilerContext.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ProfilingContextIntegration.java
This allows the span operation name to be recorded on profiling events (i.e. CPU, allocation, wall-time, memory leak samples). It does this by adding an operation attribute to the custom tags provided by the user, and every time a scope is activated, the operation name is set along with the span id and root span id we already set per scope activation. Profiling context can't store strings directly because we don't have enough space in each thread-local slot to do that, so they need to be dictionarized (replace them with an integer encoding) so we can store the dictionary code in the thread-local slot. The dictionary is then stored in a constant pool in the JFR recording.
Since scope activation can be an incredibly high frequency operation in some kinds of applications, the …
> Tag profile events with span operation name 

- dd-smoke-tests/appsec/src/main/groovy/datadog/smoketest/appsec/AbstractAppSecServerSmokeTest.groovy
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/RemoteConfigConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
- remote-config/src/main/java/datadog/remoteconfig/PollerScheduler.java
Renames the environment variable used to configure the remote config polling interval.
After this change, remote config polling interval (default: 5 seconds) can be set with `DD_REMOTE_CONFIG_POLL_INTERVAL_SECONDS`.
The main motivation for this PR is to align all remote config implementations in the tracers to use the same env variable (name and default value) to configure the polling interval.
> Rename remote config poll interval environment variable

- .circleci/config.yml
- buildSrc/build.gradle.kts
* Skip buildSrc tests by default
* Run them with `-PrunBuildSrcTests`.
* The `check` job in CI will run them.
These tests are triggered on the gradle configuration stage, which can get on your nerves pretty quickly. Running them is rarely needed, since we touch them only once in a while. So we can get them out of every step (and local development) except for the `check` job.
> Skip buildSrc tests by default

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerRecording.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/test/java/com/datadog/profiling/ddprof/DatadogProfilerTest.java
- updates the jplib dependency to 0.19.0
- modifies the integration to use 'continuous dump' rather than stop/start profiler for periodic recording uploads
- modifies how the memory profiling is configured
The 'continuous dump' mode is a bit less expensive than full stop/start seuqence.
The allocation profiling and live object tracking was merged in jplib 0.15.0 but the integration code was not updated - this PR fixes that.
> Adjust profiling integration for changes in jplib 0.19.0

- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/ClientCallImplInstrumentation.java
- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/GrpcClientDecorator.java
- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/MessagesAvailableInstrumentation.java
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/HierarchyMatcherGrpcStreamingTest.groovy
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/HierarchyMatcherGrpcTest.groovy
- internal-api/src/main/java/datadog/trace/api/naming/v0/ClientNamingV0.java
v1 naming schema changes for grpc clients:
* operation: `grpc.client.request`
> naming schema: grpc client

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/rmi/RmiClientDecorator.java
- dd-java-agent/instrumentation/rmi/src/test/groovy/RmiTest.groovy
- internal-api/src/main/java/datadog/trace/api/naming/v0/ClientNamingV0.java
v1 naming schema changes for rmi clients:
* operation: `rmi.client.request`
> naming schema: rmi clients

- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcServerDecorator.java
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/HierarchyMatcherGrpcStreamingTest.groovy
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/HierarchyMatcherGrpcTest.groovy
- internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v1/ServerNamingV1.java
v1 naming schema changes for grpc server:
* operation: `grpc.server.request`
> naming schema: grpc server

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/rmi/RmiServerDecorator.java
- dd-java-agent/instrumentation/rmi/src/test/groovy/RmiTest.groovy
v1 naming schema changes for rmi server:
* operation: `rmi.server.request`
> naming schema: rmi server

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
No need to resolve `evaluateAt` attribute for line probe.
config for the probe can now embed `evaluateAt` with any value, even for line probe
Conditions was not evaluated for line probes
> Fix evaluateAt resolution for line probe

- internal-api/src/main/java/datadog/trace/api/cache/DDCaches.java
- internal-api/src/main/java/datadog/trace/api/cache/FixedSizeCache.java
- internal-api/src/main/java/datadog/trace/api/cache/FixedSizePartialKeyCache.java
By tolerating a small amount of duplication we can simplify the internals for each case while still sharing some helper methods. IMHO this is better than trying to share the loop code, which results in several (internal-only) generics and intermediate virtual methods.
I did consider extracting the loop into a static helper, but that also results in similar virtual dispatch...
> Separate FixedSizePartialKeyCache from FixedSizeCache.

- dd-java-agent/instrumentation/java-lang/java-lang-9/src/main/java/datadog/trace/instrumentation/java/lang/invoke/StringConcatFactoryCallSite.java
- dd-java-agent/instrumentation/java-lang/java-lang-9/src/test/groovy/datadog/trace/instrumentation/java/lang/invoke/StringConcatFactoryCallSiteTest.groovy
- dd-java-agent/instrumentation/java-lang/java-lang-9/src/test/java/foo/bar/TestStringConcatFactorySuite.java
Adapts the method signature for the conversion of bytes and shorts to strings, since `String#valueOf` does not have specific methods we were using the integer version but forgot to revert the signature before passing it to the `StringConcatFactory`
The call site for invoke dynamic started failing with:
```
java.lang.BootstrapMethodError: CallSite bootstrap method initialization exception
at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:336)
at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:258)
at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:248)
at foo.bar.TestStringConcatFactorySuite.stringPlusWithPrimitive(TestStringConcatFactorySuite.java:61)
at …
```
> Fix issue when converting bytes and floats to string in invoke dynamic

- dd-java-agent/instrumentation/undertow/src/main/java/datadog/trace/instrumentation/undertow/UndertowDecorator.java
- dd-java-agent/instrumentation/undertow/undertow-2.0/src/test/groovy/UndertowDispatcherTest.groovy
- dd-java-agent/instrumentation/undertow/undertow-2.0/src/test/groovy/UndertowServletTest.groovy
- internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
v1 naming schema changes for undertow:
> naming schema: undertow

- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/api/cache/DDCaches.java
- internal-api/src/main/java/datadog/trace/api/cache/FixedSizeWeakKeyCache.java
- internal-api/src/test/groovy/datadog/trace/api/cache/FixedSizeCacheTest.groovy
Adds a new fixed-size `DDCache` implementation where the keys are weakly referenced.
Cache slots whose keys have been GC'd are considered unused when adding new entries.
Provide a smaller alternative to the current `WeakCache` implementation, which is based on `ConcurrentLinkedHashMap` wrapped with  `WeakConcurrentMap`. The map implementation has a large upfront memory cost, even for small caches.
For example, here are the bytes retained by each implementation for a small weak cache:
(The "retained bytes" were calculated by capturing a heap dump and running a heap analysis tool against it. The test class caches the same value under different key instances, and uses the same set of key instances for each implementation. So the retained bytes should approximate the internal overhead of each …
> Support fixed-sized weak-key caches

- dd-java-agent/instrumentation/finatra-2.9/src/main/java/datadog/trace/instrumentation/finatra/FinatraDecorator.java
- dd-java-agent/instrumentation/finatra-2.9/src/test/groovy/FinatraServerTest.groovy
- internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
v1 naming changes for finatra: 
> naming schema: finatra

- dd-java-agent/instrumentation/spray-1.3/src/main/scala/datadog/trace/instrumentation/spray/SprayHttpServerDecorator.java
- dd-java-agent/instrumentation/spray-1.3/src/main/scala/datadog/trace/instrumentation/spray/SprayHttpServerRunSealedRouteAdvice.java
- dd-java-agent/instrumentation/spray-1.3/src/test/groovy/SprayServerTest.groovy
- internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
v1 naming schema changes for spray:
> naming schema: spray

- dd-java-agent/instrumentation/restlet-2.2/build.gradle
- dd-java-agent/instrumentation/restlet-2.2/src/baseTest/groovy/RestletTest.groovy
- dd-java-agent/instrumentation/restlet-2.2/src/main/java/datadog/trace/instrumentation/restlet/RestletDecorator.java
- dd-java-agent/instrumentation/restlet-2.2/src/test/groovy/RestletTestBase.groovy
- internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
v1 naming schema changes for restlet:
> naming schema: restlet

- dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/server/NettyHttpServerDecorator.java
- dd-java-agent/instrumentation/netty-3.8/src/test/groovy/datadog/trace/instrumentation/netty38/Netty38ServerTest.groovy
- dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/NettyHttpServerDecorator.java
- dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ServerTest.groovy
- dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/NettyHttpServerDecorator.java
- dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ServerTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/naming/NamingConventions.groovy
- internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
v1 naming changes for netty servers:
> naming schema: netty server

- dd-java-agent/instrumentation/synapse-3/src/main/java/datadog/trace/instrumentation/synapse3/SynapseServerDecorator.java
- dd-java-agent/instrumentation/synapse-3/src/test/groovy/datadog/trace/instrumentation/synapse3/SynapseTest.groovy
- internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
v1 naming changes for  synapse server:
> naming schema: synapse server

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/http/AntPatternPathNormalizer.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/http/HttpResourceDecorator.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/http/AntPatternPathNormalizerTest.groovy
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/http/HttpResourceDecoratorTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Introduces `TRACE_HTTP_CLIENT_PATH_RESOURCE_NAME_MAPPING` to define mapping for HTTP client paths.
It provides a way to define rules to map URL paths matching a pattern to a resource name and thus reduce unwanted cardinality, e.g. to collapse all JSP page calls into one resource name:
`/some/path/main/page.jsp`
`/some/path/settings/user/profile.jsp`
And with the `/some/**/*.jsp:some-jsp` mapping it will group those paths into one resource `some-jsp`.
Also, it supports excluding certain resources from being normalized, it's enabled with a resource name is `*`. E.g.
with mapping`/foo/*/bar:*` it preserves original `/foo/123/bar` whereas without this rule it would be normalized `/foo/?/bar`. This can be useful to tune Java Tracer to disable normalization for defined paths. E.g.
There are two …
> HTTP client path mapping

- .circleci/config.yml
Use separate builds and caches for different types of job. This reduce cache save and restore time. Each dependency cache goes from +4GB to +2GB, build caches (which now include the workspace) go from +2GB to a few 100MB. This also reduces time on the critical path before tests start.
> Use specialized build caches in CI

- .circleci/config.yml
- dd-trace-ot/build.gradle
Enables Java parametric tests in CircleCI.
```
============================= test session starts ==============================
platform linux -- Python 3.9.16, pytest-7.1.3, pluggy-1.0.0
rootdir: /home/circleci/project/system-tests/parametric, configfile: conftest.py
plugins: json-report-1.2.1, ddtrace-1.4.4, metadata-2.0.2, anyio-3.6.2
collected 111 items                                                            
test_headers_b3.py ....ssssss                                            [  9%]
test_headers_b3multi.py ........ssssssssssss                             [ 27%]
test_headers_datadog.py s....                                            [ 31%]
test_headers_none.py ..........                                          [ 40%]
test_headers_precedence.py ssss …
```
> Enable Java parametric tests in CircleCI

- dd-java-agent/instrumentation/aws-java-sqs-2.0/build.gradle
(amazon-sqs-java-messaging-lib 2.1.x uses jakarta.jms-api and requires Java 17)
> Limit latestDep of amazon-sqs-java-messaging-lib to 2.0.x

- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ClassLoaderMatchers.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ClassLoaderMatchersTest.groovy
Both `DDClassFileTransformer` and its Java9+ equivalent as well as `DDRediscoveryStrategy` already check `canSkipClassLoaderByName` before allowing a transform request to proceed, so we don't need to repeat that particular test in `GlobalIgnoresMatcher`.
That leaves the boot-class-path delegation test. Since we expect every class-loader to pass this test (thanks to `ClassloadingInstrumentation`) we should move this to the end of `GlobalIgnoresMatcher`, where it can act as a final safety net. This also gives us the chance to merge its state with the `hasClass` checks.
Note we use a distinct object to represent an `INCOMPATIBLE_CLASS_LOADER` result, because it avoids having to change the return type or create unnecessary container objects. And since an incompatible class-loader has no …
> Combine class-loader delegation check with 'hasClass' checks

- gradle/dependencies.gradle
Picks up fixes to avoid unwinding stacks when the ZGC load barrier slow path is active.
> upgrade jplib to 0.21.0

- buildSrc/src/main/groovy/MuzzlePlugin.groovy
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
- dd-java-agent/instrumentation/trace-annotation/build.gradle
- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAdvice.java
- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceDecorator.java
Now that the boot delegation check has been merged with the class-loader state, the muzzle plugin must ensure the test and instrumentation class-paths share the same boot class-loader.
As part of fixing this I had to pull in a related fix to `trace-annotation` that makes it compatible with very old versions of the `@Trace` annotation. This means we can drop some special handling in the Muzzle Plugin that put some bootstrap related classes  at a different point in the generated class-path, just to allow an artificial muzzle check that would not really apply in practice.
> Fix failing muzzle classloader tests on CI

- dd-java-agent/agent-bootstrap/src/main/resources/META-INF/native-image/com.datadoghq/dd-java-agent/reflect-config.json
- dd-smoke-tests/spring-native/src/test/groovy/SpringNativeWebmvcIntegrationTest.groovy
and update the `spring-native` smoke-test to trigger the use of moshi for parsing sampling rules
> Register that moshi needs reflective access to adapters in TraceSamplingRules/SpanSamplingRules

- gradle/dependencies.gradle
Includes a revised fix to handle sampling the ZGC load barrier
> Upgrade to jplib 0.22.0

- dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
- telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java
- telemetry/src/test/groovy/datadog/telemetry/TelemetryRunnableSpecification.groovy
otherwise telemetry connections can build up in CLOSE_WAIT state
(also fixed a similar leak in `CrashUploader`)
> Make sure telemetry responses are always closed

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/TypeInfoCache.java
Tracks when entries were last used to decide which slot to overwrite when the cache is full - this is necessary to avoid evicting heavily used types from the cache when other less used slots could be evicted.
The LRU approach was tuned to get as close as possible to the behaviour in `ConcurrentLinkedHashMap` while still keeping the simple rehashing approach. The basic idea is to track when each slot was last used so we can choose the least-recently used slot (out of the original and rehashed locations) when the array is full, rather than always choosing the original slot.
After this is merged only one place uses `ConcurrentLinkedHashMap` - the legacy caching strategy which is off by default.
> Replace map-based TypeInfoCache with a fixed-sized array approach derived from FixedSizeCache

- .circleci/config.yml
This PR enables the APM end-to-end (E2E) tests for the `spring-boot` variant, in CircleCI. All other variants will still run the jobs, but are skipped (in system-tests terms they are expectedly failing).
Once we verify that this works well, we can implement the rest variants too.
- Example run for `spring-boot`: https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/22405/workflows/f98e6efd-9512-4955-82c0-ef02d0fe2668/jobs/621610
- Check both: `Run APM E2E default tests` and `Run APM E2E Single Span tests` passing!
- Example run for `ratpack `: https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/22405/workflows/f98e6efd-9512-4955-82c0-ef02d0fe2668/jobs/621654
- Check `Run APM E2E default tests` passing, and `Run APM E2E Single Span tests` expectedly-failing …
> Add APM e2e tests in CircleCI

- dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
- dd-java-agent/instrumentation/iast-instrumenter/src/test/groovy/IastExclusionTrieTest.groovy
Include two new packages that need to be excluded:
- com.mongodb
- software.amazon.awssdk
We are reporting vulnerabilities on those libraries that are not custom code, and can be considered false positives (weak hash on MD5 usage).
> Add software.amazon and com.mongodb to exclusions

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastSystem.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
Reset vulnerability deduplication every hour. We have a set of vulnerability hashes we've seen before. We clear this every hour to periodically send recurrent vulnerabilities.
Help the backend when assessing exposure windows.
> Reset vulnerability deduplication every hour

- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AbstractTransformerBuilder.java
This extends our previous check to ignore classes annotated with `javax.decorator.Decorator` to also include those annotated with `jakarta.decorator.Decorator`
> Ignore classes annotated with jakarta.decorator.Decorator

- dd-smoke-tests/spring-native/application/build.gradle
- dd-smoke-tests/spring-native/application/settings.gradle
Switch over to Spring's `milestone` repository which now has a version of `org.springframework.experimental/spring-aot-gradle-plugin` we can use. This is just a temporary fix until we update these smoke tests to use the Spring 6 / Spring-Boot 3 native tooling.
> Fix spring-native smoke tests

- dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.5/build.gradle
Currently breaks with 1.7-beta
> Add upper bound for kotlinx-coroutines-core

- gradle/dependencies.gradle
Reverts DataDog/dd-trace-java#4859
There are some changes I don't feel confident releasing in this upgrade
> Revert "Upgrade to jplib 0.22.0"

- .circleci/config.yml
They are currently not compressed, which takes more time to upload, and more space to store.
> Archive system-tests logs before uploading

- .circleci/config.yml
- dd-smoke-tests/spring-native/build.gradle
- gradle/java_no_deps.gradle
* Use the new, smaller, Docker images for CI. See https://github.com/DataDog/dd-trace-java-docker-build/pull/51
* Change job names to lowercase. This is more convenient for JDK names at places that need lowercase (Docker tags), and there's no support in Circle CI template variables to do tolower/toupper. Developers don't need to change anything, since gradle should now be case insensitive for these cases.
* Rename ibm11 and ibm17 to semeru11 and semeru17, which is the actual vendor we use here.
Shorter setup times for jobs, especially useful when increasing parallelism.
> Use per-JDK Docker images

- internal-api/src/main/java/datadog/trace/api/Platform.java
- internal-api/src/test/groovy/datadog/trace/api/PlatformTest.groovy
Removes any pre-release suffix before parsing versions.
We supported the -ea suffix, but according to the standard, it can be any string.
Solves https://github.com/DataDog/dd-trace-java/issues/4875
> Fix Java version parsing for pre-releases

- gradle/dependencies.gradle
* Robust detection of ZGC load barrier
* Clear thread set when dumping the profile to avoid an ever growing thread constant pool when the application creates and renames lots of threads
> upgrade jplib to 0.24.0

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/SourceType.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/source/WebModuleTest.groovy
- dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
- dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletRequestCallSiteTest.groovy
- dd-java-agent/instrumentation/servlet/src/test/java/datadog/smoketest/controller/TestHttpServletRequestCallSiteSuite.java
- dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
- dd-smoke-tests/spring-boot-2.6-webmvc/src/test/groovy/IastSpringBootSmokeTest.groovy
- dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
- dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
- internal-api/src/main/java/datadog/trace/api/iast/model/SourceTypes.java
- internal-api/src/main/java/datadog/trace/api/iast/source/WebModule.java
Add required call sites for the `HttpServletRequest#getQueryString()` method to taint the query string value.
The data coming from the `HttpServletRequest#getQueryString()` method is under the control of the user and should be considered as unstrusted.
> Call site instrumentation for request#getQueryString()

- dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitChannelInstrumentation.java
- dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitCommandInstrumentation.java
- dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
- dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
- internal-api/src/main/java/datadog/trace/api/naming/NamingSchema.java
- internal-api/src/main/java/datadog/trace/api/naming/v0/MessagingNamingV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v0/NamingSchemaV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v1/MessagingNamingV1.java
- internal-api/src/main/java/datadog/trace/api/naming/v1/NamingSchemaV1.java
Changes for v1 naming schema:
* Producer:
- service: `{{DD_SERVICE}}`
- operation:  `amqp.send`
* Consumer:
- service: `{{DD_SERVICE}}`
- operation:  `amqp.process`
* Time in queue :
- service: `rabbitmq-queue`
- operation:  `amqp.deliver`
Interactions with other options:
* v1 schema implies legacy tracing disabled by default. However the user can explicitly force the legacy tracing and have service = 'rabbitmq' like v0
> naming schema: rabbitmq

- dd-java-agent/instrumentation/graphql-java-14.0/src/main/java/datadog/trace/instrumentation/graphqljava/GraphQLDecorator.java
- dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
v1 naming schema changes for graphql (request only):
* operation: `graphql.server.request`
Note: the resource name will also change on v1 to `graphql.server.request` since the decorator does not set any and thus defaulting to operation name.
> naming schema: graphql

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/MessageConsumerState.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
- dd-java-agent/instrumentation/jms/src/test/groovy/TimeInQueueForkedTest.groovy
Changes for v1 naming schema:
* Producer:
- service: `{{DD_SERVICE}}`
- operation:  `jms.send`
* Consumer:
- service: `{{DD_SERVICE}}`
- operation:  `jms.process`
* Time in queue :
- service: `jms-queue`
- operation:  `jms.deliver`
Interactions with other options:
* v1 schema implies legacy tracing disabled by default. However the user can explicitly force the legacy tracing and have service = 'jms' like v0
> naming schema: jms changes

- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
- dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsDecorator.java
- dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTestBase.groovy
Changes for v1 naming schema:
* Producer:
- service: `{{DD_SERVICE}}`
- operation:  `kafka.send`
* Consumer:
- service: `{{DD_SERVICE}}`
- operation:  `kafka.process`
* Time in queue :
- service: `kafka-queue`
- operation:  `kafka.deliver`
Interactions with other options:
* v1 schema implies legacy tracing disabled by default. However the user can explicitly force the legacy tracing and have service = 'kafka' like v0
> naming schema: kafka changes

- internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
- internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/ConfigConverterTest.groovy
Hardens the map from string parsing code so it doesn't misstep on values that contain both spaces and colons, i.e. a string like this `key1:val1 with_space:and_colon, key2:val2`. This previously resulted in a substring call with `end` smaller than `start`.
Don't throw `IndexOutOfBoundsException`.
> Harden config map parsing

- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/source/WebModuleTest.groovy
- dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/CookieCallSite.java
- dd-java-agent/instrumentation/servlet/src/test/groovy/CookieCallSiteTest.groovy
- dd-java-agent/instrumentation/servlet/src/test/java/datadog/smoketest/controller/CookieTestSuite.java
- dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
- dd-smoke-tests/spring-boot-2.6-webmvc/src/test/groovy/IastSpringBootSmokeTest.groovy
- dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
- dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
- internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
- internal-api/src/test/groovy/datadog/trace/api/iast/SourceTypesTest.groovy
Remove cookie related call sites that are part of the response but not the request
The cookie header can only contain a list of key/value tuples: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie
> Remove not needed cookie call sites

- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/main/java/datadog/trace/api/normalize/HttpResourceNames.java
- internal-api/src/test/groovy/datadog/trace/api/normalize/HttpResourceNamesTest.groovy
Adds a setting to remove a trailing slash from the http resource name.
Datadog treats otherwise identical http path resources with and without a trailing slash as two different resource. This addition will help to instruct Java Tracer to group them into one resource by removing a trailing slash.
FRAPMS-1972
This change supersedes #4870
> A setting to remove http resource name trailing slash

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/http/ClientIpAddressResolver.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecoratorTest.groovy
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/http/ClientIpAddressResolverSpecification.groovy
- dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
- dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/W3CHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpExtractorTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TagContext.java
Update behavior to match the changes in the spec. The differences are:
* Forwarded and Via are not to be used anymore.
* Client-ip is changed to X-Client-Ip.
* Added Fast-client-ip, Cf-connecting-ip and Cf-connecting-ipv6
* We report only the first public ip found in the headers.
* We don't report that there are multiple tags presents anymore.
> Update client ip resolver

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingIntegration.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ProfilerContext.java
Adds service and resource name tags to profile events (e.g. cpu, wall, allocation).
> add service name and resource name to profiling context

- dd-java-agent/agent-profiling/profiling-auxiliary-ddprof/src/main/java/com/datadog/profiling/auxiliary/ddprof/AuxiliaryDatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkOngoingRecording.java
- dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/JfrMBeanHelper.java
- dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkOngoingRecording.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
Changes log statements which indicate that something unexpected has happened but do not constitute a loss of functionality to debug to avoid alarming users.
> reduce the number of noisy log statements

- dd-java-agent/agent-jmxfetch/build.gradle
- dd-java-agent/instrumentation/aws-java-sqs-2.0/build.gradle
- dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.5/build.gradle
Upgrades jmx fetch to `0.47.5` to fix [CVE-2022-1471](https://nvd.nist.gov/vuln/detail/CVE-2022-1471)
Solves #4910
> Upgrade jmxfetch to 0.47.5 to fix CVE-2022-1471

- gradle/dependencies.gradle
Clears out the old slot in the call trace storage hashmap when there are collisions
> bump jplib to 0.26.0

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
- dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentJar.java
Cleans up how we load classes via the CLI to avoid checking the code source location unless we really need it.
For example, if the agent classloader is already installed then we don't need the tracer's code source location.
This avoids a potential exception when `dd-java-agent` is used with both `-javaagent` and `-jar` at the same time.
(The original exception occurred because the code source location of `AgentJar` became `null` after we added `dd-java-agent` to the boot-class-path - determining that we're running `dd-java-agent` with `-jar` from `premain` turns out to be non-trivial, it was easier to adjust the code so `dd-java-agent` can work in both places.)
> Support using the Java tracer with both -javaagent and -jar at the same time

- buildSrc/src/main/groovy/MuzzlePlugin.groovy
so types like `java.net.http.HttpRequest` are visible when checking against Java11
(this is a pre-req for the Java11 HttpClient instrumentation)
> Include JDK system classes in muzzle build-time checks

- dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/BeanDefinitionRepairer.java
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/SpringBeanProcessorInstrumentation.java
This replaces the previous workaround which was limited to listing tracer beans by name.
After #4543 we now have a single place to track and resolve these beans, so re-use that here.
> Avoid ClassNotFoundException when resteasy-spring attempts to process tracer-related beans

- buildSrc/src/main/groovy/InstrumentPlugin.groovy
- buildSrc/src/main/groovy/InstrumentingPlugin.groovy
- buildSrc/src/test/groovy/InstrumentPluginTest.groovy
- dd-java-agent/agent-tooling/build.gradle
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGenerator.java
- dd-java-agent/instrumentation/build.gradle
Runs build-time instrumentation tasks on the appropriate Java version
Certain build-time instrumentation tasks, such as generation of muzzle references, need to run on the appropriate Java version - otherwise some bytecode references will not be resolvable. This is a companion PR to #4913
> Build-time instrumenting toolchain support

- internal-api/src/main/java/datadog/trace/api/sampling/SamplingMechanism.java
- internal-api/src/test/groovy/datadog/trace/api/sampling/SamplingMechanismTest.groovy
Allows sampling priorities outside of the _known_ range from external sources. This is per the spec, where we should just pass those through.
> Allow unknown sampling priorities from external sources

- dd-java-agent/instrumentation/graphql-java-14.0/build.gradle
- dd-java-agent/instrumentation/graphql-java-14.0/src/main/java/datadog.trace.instrumentation.graphqljava/GraphQLJavaInstrumentation.java
- dd-java-agent/instrumentation/graphql-java-14.0/src/main/java/datadog/trace/instrumentation/graphqljava/InstrumentedDataFetcher.java
- dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
- dd-java-agent/instrumentation/graphql-java-14.0/src/test/java/Book.java
- dd-java-agent/instrumentation/graphql-java-14.0/src/test/resources/schema.graphqls
Addresses https://github.com/DataDog/dd-trace-java/issues/4050
- Provide significant context pertinent to field retrieval
- Significantly improve the usability and usefulness of the GraphQL resource view in Datadog APM
- Always provide the field's type, as it was coded it would only provide the type if it was not wrapped
https://github.com/graphql/graphql-wg/blob/main/rfcs/SchemaCoordinates.md felt like the natural solution for the naming of the resource being fetched and providing as its own tag.  Having the resource view in Datadog APM broken down by this will provide immense utility in determining where to dig into.
> graphql.field spans: Fix graphql.type tag and add graphql.coordinates tag

- dd-java-agent/instrumentation/graphql-java-14.0/build.gradle
- dd-java-agent/instrumentation/graphql-java-14.0/src/main/java/datadog.trace.instrumentation.graphqljava/GraphQLJavaInstrumentation.java
Excludes graphql-java 13.x from instrumentation to make tests pass.
I mistakenly [included v13](https://github.com/DataDog/dd-trace-java/pull/4663/commits/79f1a50036eca929e37b93e0e3062bb3aa746675) as supported version but it's not correct. 
N/A
> Fix GraphQL tests by excluding graphql-java v13.0

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/IndexExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/GetMemberExpressionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/HasAllExpressionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/ValueRefExpressionTest.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/LogMessageTemplateSummaryBuilder.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogMessageTemplateSummaryBuilderTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
instead of reporting UNDEFINED we put the the evaluation error message in curly braces:
ex: this is a log line with arg={Cannot find symbol: var42}
Having evaluation error message directly into the log message
> Report evaluation error inline in message

- .circleci/config.yml
This PR installs python 3.9 for system tests jobs
System test executor will run on the host rather than inside a container (see https://github.com/DataDog/system-tests/pull/958). It will allow users to do step-by-step debugging, and will allow to unify architecture with parametric tests.
As now, the change will do nothing but installing python 3.9 on system tests job. Once the PR on system repo will be merge, it'll work silently (and we'll be able to remove the installation of docker compose, not required anymore).
> Setup python 3.9 for system tests

- gradle/dependencies.gradle
https://github.com/DataDog/java-profiler/releases/tag/v0.27.0
JPLib 0.27.0 is fixing a native memory leak introduced in JPLib 0.15.0
> [wip] Update jplib to 0.27.0

- dd-trace-core/src/jmh/java/datadog/trace/core/propagation/InjectorBenchmark.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpInjectorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpInjectorTest.groovy
- internal-api/src/main/java/datadog/trace/api/Config.java
- utils/test-utils/src/main/groovy/datadog/trace/test/util/StringUtils.groovy
Adds padding to B3 propagation headers to be compliant with other tracers behavior.
This behavior can be turned off by the setting the java property `-Ddd.trace.propagation.style.b3.padding.enabled=false` or the environment variable `DD_TRACE_PROPAGATION_STYLE_B3_PADDING_ENABLED=false`
> Add padding to B3 propagation headers

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ClassesToRetransformFinder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationComparer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Instrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/LogInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/SpanInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/MetricProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationComparerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerProductChangesListenerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/TransformerDefinitionMatcherTest.java
Probes are merged by location before applying instrumentation and only the first LogProbe for this location is instrumented passing the duplicated probe ids that will be generated in the instrumented code
Remove the infamous additional probes concept
> Remove additional probes in ProbeDefinition

- .gitlab-ci.yml
Currently we are generating latest_snapshot docker image when we push to master branch 
But we are not generating latest (release) when we generate new version/tag. 
This PR fix that problem.
> Docker base image on release Fix

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/TransformerDefinitionMatcher.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/Trie.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/TransformerDefinitionMatcherTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/TrieTest.java
Separate matching for qualified filenames and simple filenames collect all definitions matching the prefix and not just one as path could be different outside the prefix
issue with multiple probe having different path for the same source code ex: `VetController.java` & `org/springframework/samples/petclinic/vet/VetController.java`
> Fix matching source filename with different paths

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryContextInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelContext.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpanBuilder.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
This PR follows the original experimental support #4669 to fix new trace creation and bring root span retrieval from `Context`.
Open Telemetry API does not provide a way to get local root span.
This change introduce a such feature using a custom `ContextKey`.
```java
ContextKey rootSpanKey = ContextKey.named("datadog-root-span-key");
Span rootSpan = Context.current().get(rootSpanKey);
```
Please note:
* The `Context` instance is immutable so its (current and root) spans will be snapshot during the `Context.current()` call.
* Setting attributes for the root span is not guaranteed as the root span might no more be eligible for modification.
Check the full discussion about those changes from #4935
> Improve Open Telemetry tracer API instrumentation

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/civisibility/TestEventsHandler.java
- dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
- dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
- dd-java-agent/instrumentation/testng/src/testFixtures/groovy/datadog/trace/instrumentation/testng/TestNGTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
Updates test-case spans to always be root spans.
CI Visibility backend mandates that a span corresponding to an individual test case should always be a root span.
Otherwise (e.g. if test-case span has test-suite span as its parent) multiple test-case spans may share the same trace ID, in which case the UI will render test-case trace incorrectly.
> Fix test-case spans to always be root spans

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InstrumentationContext.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextRequestRewriter.java
- dd-java-agent/testing/src/test/groovy/context/FieldInjectionForkedTest.groovy
- dd-java-agent/testing/src/test/java/context/FieldInjectionTestInstrumentation.java
This is for situations where the key/context are only available as string constants at compile time, ie. it is difficult to arrange access to the class literals (for example when the dependency is not available on Maven central)
> Support retrieving context-stores by class name

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
This modifies the default value of the ddprof based allocation profiling enablement.
The allocation profiling in the DD java profiler lib is now ready to be used as default when possible. This means that when `ddprof` is enabled (either manually or automatically) and we are running on JDK 11+ the ddprof allocation profiling will be activated.
It is still possible to manually disable by config as well as enable for systems where we don't enable it automatically if users are feeling adventurous.
Make the ddprof allocation profiling automatically available where possible.
> Enable ddprof allocation profiling for JDK 11+ by default

- dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
Handles `IllegalArgumentException` thrown by `java.net.URLDecoder` when illegal escape patterns are decoded.
> Catch IllegalArgumentException for URLDecoder

- dd-java-agent/instrumentation/aws-java-sdk-2.2/build.gradle
- dd-java-agent/instrumentation/aws-java-sqs-2.0/build.gradle
because 2.20.34 is an incomplete release (the jar is listed on Maven Central but cannot be downloaded)
> Temporarily pin awssdk to 2.20.33 for aws-java-sqs-2.0:latestDepTest

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot05.java
include context with uncaught exception to the snapshot and add an evaluation error with the type + message of it.
Help to contextualize why evaluation of a condition may fail (locals not available)
> Report eval error in case of uncaught exception

- communication/src/main/java/datadog/communication/serialization/FlushingBuffer.java
- dd-trace-core/src/main/java/datadog/trace/common/writer/PayloadDispatcher.java
- dd-trace-core/src/main/java/datadog/trace/common/writer/RemoteWriter.java
- dd-trace-core/src/main/java/datadog/trace/common/writer/SpanSamplingWorker.java
- dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
- dd-trace-core/src/main/java/datadog/trace/core/monitor/HealthMetrics.java
- dd-trace-core/src/main/java/datadog/trace/core/monitor/TracerHealthMetrics.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScope.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDIntakeWriterCombinedTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDIntakeWriterTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/PayloadDispatcherTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/SpanSamplingWorkerTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/monitor/HealthMetricsTest.groovy
Adds health metrics around trace and span construction:
`queue.dropped.spans` - number of dropped spans tagged by sampling priority
`span.pending.finished` - number of spans that are finished
`span.sampling.sampled` - number of spans sampled by the single span sampler
`span.sampling.unsampled` - number of spans that are considered unsampled by the single span sampler
`scope.activate.count` - number of activated ContinuableScopes
`scope.close.count` - number of closed ContinuableScopes
`scope.error.stack-overflow` - counts the number of times that the Scope depth limit is exceeded
The goal of implementing these metrics is to increase visibility into potential issues in trace/span creation or delivery.
> Added health metrics around trace construction

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/Configuration.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerProductChangesListener.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
- dd-java-agent/agent-debugger/src/test/resources/test_span_decoration_probe.json
- dd-java-agent/agent-debugger/src/test/resources/test_span_probe.json
Add support for decorating current active or root span with dynamic tag values taken from the context where the probe is set. Adding the tag can also depend on condition
Introduced new kind of probe to decorate existing span with dynamic tags
Instrumentation will be implemented in next PR
> Add span decoration config

- dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
Marks GraphQLVxForkedTest as flaky.
Flaky tests are flaky.
This is just one example. They break a lot.
https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/23372/workflows/34d367e4-93bf-49c0-ab54-ddb727e0e0c5/jobs/676542
> Mark GraphQLVxForkedTest as flaky

- dd-java-agent/instrumentation/synapse-3/src/test/groovy/datadog/trace/instrumentation/synapse3/SynapseTest.groovy
The parent class was already marked as flaky.
> Mark SynapseVxForkedTest as flaky

- dd-java-agent/instrumentation/zio/build.gradle
- dd-java-agent/instrumentation/zio/zio-2.0/build.gradle
- dd-java-agent/instrumentation/zio/zio-2.0/src/main/java/datadog/trace/instrumentation/zio/v2_0/FiberContext.java
- dd-java-agent/instrumentation/zio/zio-2.0/src/main/java/datadog/trace/instrumentation/zio/v2_0/TracingSupervisor.java
- dd-java-agent/instrumentation/zio/zio-2.0/src/main/java/datadog/trace/instrumentation/zio/v2_0/ZioRuntimeInstrumentation.java
- dd-java-agent/instrumentation/zio/zio-2.0/src/test/groovy/ZioRuntimeInstrumentationTest.groovy
- dd-java-agent/instrumentation/zio/zio-2.0/src/test/scala/ZioTestFixtures.scala
- settings.gradle
Adds instrumentation for  [ZIO 2.0](https://zio.dev/).
ZIO is a popular Scala library for asynchronous and concurrent programming. Its runtime uses green threads (fibers) which breaks instrumentation because scope state is stored in `ThreadLocal` variable. This PR takes care of synchronizing scope state between fibers and JVM threads on which they are executed.
Implementation was tested on a [non-trivial distributed application](https://github.com/dmytr/zio-otel-instrumentation/tree/6de68991ac932473f1d7d8b3151e9cf84e494900).
> ZIO 2.0 instrumentation

- .circleci/config.yml
- build.gradle
- gradle/configure_tests.gradle
Parallelized test jobs in CI:
* Use Circle CI job parallelism for tests: https://circleci.com/docs/parallelism-faster-jobs/
* Partition test tasks at gradle level using CIRCLE_NODE_TOTAL and CIRCLE_NODE_INDEX. See https://circleci.com/docs/parallelism-faster-jobs/#using-environment-variables-to-split-tests
* Adjust [resource class](https://circleci.com/product/features/resource-classes/) for test jobs: moved all to `large` (4 CPU, 8 GB), some where previously `xlarge` and `2xlarge`. Adjust number of gradle workers and parallelism accordingly.
* Disable Docker layer caching: cheaper, faster setup.
* Fold IAST jobs back to `base` tests.
Make pipelines faster.
* Replaces https://github.com/DataDog/dd-trace-java/pull/4694 and https://github.com/DataDog/dd-trace-java/pull/4659
* Includes …
> Parallelized test jobs in CI

- dd-java-agent/instrumentation/osgi-4.3/src/main/java/datadog/trace/instrumentation/osgi43/BundleWiringHelper.java
`Bundle.adapt(...)` may return null if a bundle is uninstalled during the search
See #4826 for an example stack trace
> Guard against potential NPE when searching bundle wiring during shutdown

- buildSrc/build.gradle.kts
- buildSrc/src/test/groovy/InstrumentPluginTest.groovy
- gradle/dependencies.gradle
Byte Buddy 1.14.3
* Make MethodGraph.Compiler failsafe when processing incomplete methods.
* Update ASM.
Byte Buddy 1.14.2
* Fix offset mapping for local variable array remapping in Advice.
* Add possibility to specify an index for skipOn and repeatOn which resolves the checked value from a returned array.
Byte Buddy 1.14.1
* Add extended scope for Maven Byte Buddy plugin to include all non-test-dependencies.
Byte Buddy 1.14.0
* Add Step.Factory.ForDelegation in MemberSubstitution that allows for delegation similar to MethodDelegation but in-code.
* Add handlers for MethodDelegation and Advice that leverage method handles for field access and self-invocation.
* Add Step.Factory for type assignment that allows casting the return value from a previous step to another type.
* Avoid usage of …
> byte-buddy 1.14.3 + asm 9.5

- dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
…upport to align with updated behavior
Because https://github.com/DataDog/dd-trace-java/pull/4896 and https://github.com/DataDog/dd-trace-java/pull/4960 were being worked on independently and merged on around the same time, the changes in behavior introduced in https://github.com/DataDog/dd-trace-java/pull/4960 were not updated in the newly added unit test in https://github.com/DataDog/dd-trace-java/pull/4896.
This MR changes the test to properly expect the right value now.
To help address https://github.com/DataDog/dd-trace-java/pull/5001/files where these tests were marked Flaky, this will reduce the failure rate
> Update resource name expected by recently added GraphQL CompletionStage support test

- dd-java-agent/instrumentation/spring-scheduling-3.1/src/test/groovy/ShedlockTest.groovy
avoids potential issue where the task runs before the table is created
> Create ShedLockedTask after creating shedlock table

- dd-java-agent/instrumentation/jedis-1.4/src/main/java/datadog/trace/instrumentation/jedis/JedisClientDecorator.java
- dd-java-agent/instrumentation/jedis-1.4/src/main/java/datadog/trace/instrumentation/jedis/JedisInstrumentation.java
- dd-java-agent/instrumentation/jedis-1.4/src/test/groovy/JedisClientTest.groovy
- dd-java-agent/instrumentation/jedis-3.0/build.gradle
- dd-java-agent/instrumentation/jedis-3.0/src/main/java/datadog/trace/instrumentation/jedis30/JedisClientDecorator.java
- dd-java-agent/instrumentation/jedis-3.0/src/main/java/datadog/trace/instrumentation/jedis30/JedisInstrumentation.java
- dd-java-agent/instrumentation/jedis-3.0/src/test/groovy/Jedis30ClientTest.groovy
- dd-java-agent/instrumentation/jedis-4.0/src/main/java/datadog/trace/instrumentation/jedis40/JedisInstrumentation.java
- dd-java-agent/instrumentation/jedis-4.0/src/main/java/redis/clients/jedis/JedisClientDecorator.java
- dd-java-agent/instrumentation/jedis-4.0/src/test/groovy/Jedis40ClientTest.groovy
Instrument jedis connection instead of command (on jedis < 4) and set `peer.hostname` on jedis spans
> Provide peer.hostname on jedis spans

- dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java/datadog/trace/instrumentation/couchbase_31/client/DatadogRequestSpan.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java/datadog/trace/instrumentation/couchbase_32/client/DatadogRequestSpan.java
Under high load, we can observe Couchbase integration getting set to success early, and not getting set to error after an exception is raised.
This can fail on `CouchbaseClient32V0ForkedTest` and `CouchbaseClient32V1ForkedTest` suites, in the `check basic error spans` case. Example:
```
Condition failed with Exception:
assertTraces(1) { sortSpansByStart() trace(2) { // Span might have already been created, but still not marked as error. blockUntil { trace.any { it.isError() } } assertCouchbaseCall(it, "get", [ 'db.couchbase.collection' : '_default', 'db.couchbase.document_id': { String }, 'db.couchbase.retries'    : { Long }, 'db.couchbase.scope'      : '_default', 'db.couchbase.service'    : 'kv', 'db.name'                 : BUCKET, 'db.operation'            : 'get' ], false, ex) …
```
> Fix Couchbase client race condition

- .circleci/config.yml
- buildSrc/call-site-instrumentation-plugin/build.gradle.kts
We already have -PrunBuildSrcTests
> Remove -PskipBuildSrcTest

- dd-trace-api/src/main/java/datadog/trace/api/DD128bTraceId.java
- dd-trace-api/src/main/java/datadog/trace/api/DD64bTraceId.java
- dd-trace-api/src/main/java/datadog/trace/api/DDTraceId.java
- dd-trace-api/src/test/groovy/datadog/trace/api/DDTraceIdTest.groovy
- dd-trace-core/src/main/java/datadog/trace/core/propagation/B3TraceId.java
Fix broken public API due to changing `DDTraceId` from class into an interface.
Fixes #4918
Related to #4938
> Restore public DDTraceId class API

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryInstrumentation.java
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
Add TRACE_OTEL_ENABLED configuration flag for zero touch configuration of Open Telemetry Tracing API support.
> [OTel] Add TRACE_OTEL_ENABLED flag for zero touch configuration

- gradle/dependencies.gradle
Consists of a fix to profiler context storage when there are small numbers of hardware threads on the host
> bump jplib to 0.30.0

- dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
Add iast_enabled=true to StatusLogger.
Omit iast_enabled=false at the moment, to avoid noise before GA.
> Add iast_enabled to StatusLogger (if enabled)

- dd-java-agent/instrumentation/lettuce-4/src/main/java/datadog/trace/instrumentation/lettuce4/InstrumentationPoints.java
- dd-java-agent/instrumentation/lettuce-4/src/main/java/datadog/trace/instrumentation/lettuce4/LettuceAsyncCommandsAdvice.java
- dd-java-agent/instrumentation/lettuce-4/src/main/java/datadog/trace/instrumentation/lettuce4/LettuceAsyncCommandsInstrumentation.java
- dd-java-agent/instrumentation/lettuce-4/src/main/java/datadog/trace/instrumentation/lettuce4/LettuceClientDecorator.java
- dd-java-agent/instrumentation/lettuce-4/src/main/java/datadog/trace/instrumentation/lettuce4/LettuceClientInstrumentation.java
- dd-java-agent/instrumentation/lettuce-4/src/main/java/datadog/trace/instrumentation/lettuce4/RedisConnectionAdvice.java
- dd-java-agent/instrumentation/lettuce-4/src/test/groovy/Lettuce4AsyncClientTest.groovy
- dd-java-agent/instrumentation/lettuce-4/src/test/groovy/Lettuce4SyncClientTest.groovy
- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/ConnectionContextBiConsumer.java
- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/ConnectionFutureAdvice.java
- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceAsyncBiConsumer.java
- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceAsyncCommandsAdvice.java
- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceAsyncCommandsInstrumentation.java
- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceClientDecorator.java
- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceClientInstrumentation.java
- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceReactiveClientInstrumentation.java
- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/rx/RedisSubscriptionConnectionContextAdvice.java
- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/rx/RedisSubscriptionState.java
- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/rx/RedisSubscriptionSubscribeAdvice.java
- dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5AsyncClientTest.groovy
- dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ReactiveClientTest.groovy
- dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5SyncClientTest.groovy
This PR wants to surface information we have at connection time on all lettuce spans.
Those tags are:
* peer.hostname
* peer.port
* db.redis.dbIndex
This works for all types of lettuce clients: sync, async and reactive
> lettuce: surface remote host and db index information

- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/CombiningTransformerBuilder.java
- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/LegacyTransformerBuilder.java
- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/KnownTypesMatcher.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AbstractExecutorInstrumentation.java
PR #4578 introduced a build-time index of instrumentations that matched based on known types (`ForKnownTypes`)
This accidentally removed support for custom `dd.trace.executors` because that config option was being added at runtime to the list of known-types, and is not available at build-time. Since known-types are supposed to only include types that we know at build-time the solution is to instead report any custom `dd.trace.executors` via `ForConfiguredTypes`, which is mixed correctly at runtime with the build-time index.
> Restore support for matching custom 'dd.trace.executors'

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ValueReferenceResolver.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/EvaluationException.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/GetMemberExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/IndexExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/SubStringExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/ValueRefExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/ComparisonExpressionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/SubStringExpressionTest.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/LogMessageTemplateBuilder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogMessageTemplateBuilderTest.java
Introduced EvaluationException that help bubble up errors during evaluation of Expressions and centralized them to add EvaluationError into the CapturedContext's status.
Removed list of evaluation errors from CapturedContext
> Refactoring handling evaluation errors

- .circleci/config.yml
- buildSrc/src/main/groovy/MuzzlePlugin.groovy
Updates the muzzle plugin to use configurations for cross project dependencies instead of source sets.
Cross project source set access has been removed in gradle 8.
Also enabled `--warning-mode=fail` for CI to avoid depending on deprecated gradle features.
> Update Muzzle plugin for gradle 8

- dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
This PR removes the `parseAsSystemProperties` method introduced in #4813, as it conflicts with, and duplicates, the functionalities added in #4888.
> bootstrap: remove parseAsSystemProperties

- dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/OnCompleteHandler.java
- dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/RedisClientActorInstrumentation.java
- dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/RedisConnectionInfo.java
- dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/RediscalaClientDecorator.java
- dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/RediscalaInstrumentation.java
- dd-java-agent/instrumentation/rediscala-1.8.0/src/test/groovy/RediscalaClientTest.groovy
Adds redis connection remote host, port and dbIndex to rediscala spans
> add remote peer info for rediscala

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/ProbeImplementation.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java
https://github.com/DataDog/dd-trace-java/pull/5048#discussion_r1163116379
> move resolveEvaluateAt method to CapturedContext

- dd-java-agent/agent-debugger/build.gradle
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
not used, difficult to maintain
> Remove parametric testTransformations

- .circleci/config.yml
We still have deprecations in the configuration stage, so the project is not ready for this mode.
> Remove gradle's --warning-mode=fail

- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
- dd-java-agent/agent-iast/src/jmh/java/com/datadog/iast/propagation/AbstractBenchmark.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastSystem.java
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
- internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
- internal-api/src/test/groovy/datadog/trace/api/InstrumenterConfigTest.groovy
This state enables IAST instrumentation, but does not enable the IAST subsystem itself.
At the moment, this is meant for dogfooding IAST instrumentation, as well as measuring the impact of IAST with instrumentation only.
> Add inactive state for IAST

- dd-java-agent/agent-profiling/profiling-controller-ddprof/src/main/java/com/datadog/profiling/controller/ddprof/DatadogProfilerController.java
- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ControllerFactory.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
Fixes the logic used to detect and instantiate a standalone ddprof profiler (when OpenJDK profiler is not available eg.)
Currently it is not possible to use profiler on non-OpenJDK and non-OracleJDK platforms.
> Fix enablement of the ddprof profiler in standalone mode

- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/DisableOnJ9Condition.java
Re-enables CodeHotspot profiler smoke test for recent J9 JDKs
The recent update to OpenJ9 (and J9 based JDKs) made it possible to use the ddprof library for profiling so it makes sense to assert the functionality.
> Try enabling smoke test for the latest OpenJ9

- internal-api/src/main/java/datadog/trace/api/Config.java
Turns off the automatic enablement of the ddprof profiler for J9 versions of JDK 11.0.18 and JDK 17.0.6
There is a bug in then J9 JVMTI implementation causing JVM to crash when a `jmethodId` of a method that was recently unloaded is used. According to the specification the JVMTI must be resilient to such calls and store the minimal info necessary to describe the method even if the class is unloaded.
> Do not automatically enable ddprof for J9 JDK 11/17

- dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTTracer.java
Avoids a situation when the OpenTracing `Tracer.close()` method is called when Wildfly applications are re-deployed, prematurely closing the wrapped Datadog tracer.
> When the OpenTracing wrapper is closed, flush any traces but keep the wrapped tracer open

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpan.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpanContext.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Add empty string value support for span attribute,
Fix span context sampling flag,
Fix tests after RFC change.
Empty string value is a meaningful attribute value for OTel span.
So it should not be ignored nor cleared from span tags.
> Improve OpenTelemetry instrumentation

- telemetry/src/main/java/datadog/telemetry/RequestBuilder.java
- telemetry/src/test/groovy/datadog/telemetry/RequestBuilderSpecification.groovy
Add missing headers in telemetry requests, according to the spec.
> Add missing request headers in telemetry

- telemetry/src/main/java/datadog/telemetry/metric/MetricPeriodicAction.java
- telemetry/src/test/groovy/datadog/telemetry/metric/MetricPeriodicActionSpecification.groovy
Last version of the spec changed triggered/blocked to rules_triggered/request_blocked.
> Update tag names for WAF metrics

- dd-java-agent/agent-profiling/profiling-ddprof/build.gradle
- dd-java-agent/build.gradle
- gradle/dependencies.gradle
Brings the ddprof dependency to the latest version
https://github.com/DataDog/java-profiler/releases/tag/v_0.33.0
---
- Use gradle as the build system
- Update J9 checks for commercial IBM JDK 8 versioning
- Adjust JVM version parsing for IBM JDK 8 quirks
- Use stripped release binaries
The artifact name changed from `jplib` to `ddprof` so the dependencies were updated accordingly
> Bump ddprof lib to 0.33.0

- dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java
- dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/HelperMethods.java
- dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/ApacheHttpClientInstrumentation.java
- dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/HelperMethods.java
We only reset the call-depth when we're finishing an HTTP span, so we must only increment it when we know we'll create and activate an HTTP span.
Previously it was possible the call-depth would be incremented, but an HTTP span might then not be created if the request came from the AWS SDK.
Workaround when using versions of the tracer without this fix - either add this JVM option:
```
-Ddd.aws-sdk.legacy.tracing.enabled=true
```
```
DD_AWS_SDK_LEGACY_TRACING_ENABLED=true
```
> Fix potential issue with apache-httpclient call-depth tracking

- dd-java-agent/instrumentation/aws-lambda-handler/src/main/java/datadog/trace/instrumentation/aws/v1/lambda/LambdaHandlerInstrumentation.java
- dd-java-agent/instrumentation/aws-lambda-handler/src/test/groovy/HandlerStreaming.java
- dd-java-agent/instrumentation/aws-lambda-handler/src/test/groovy/LambdaHandlerInstrumentationTest.groovy
Fixes a bug with Lambda span generation, when using an abstract base class. 
Also fixes a bug where com.amazonaws.services.lambda.runtime.RequestStreamHandler was not being wrapped correctly, because it has a void return type, which the ExtensionAdvice class wasn't matching properly. I've added a test case for this.
Before:
After:
If a customer creates an Abstract Base Class, which implements the `com.amazonaws.services.lambda.runtime.RequestHandler`, currently our instrumentation won't correctly wrap the `handleRequest` method, leading to broken traces. This changes the instrumentation matcher to find all classes in the hierachy which implement the RequestHandler interface.
> Support AWS Lambda parent inheritance

- dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/KafkaClientTest.groovy
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
- dd-java-agent/instrumentation/kafka-streams-0.11/src/latestDepTest/groovy/KafkaStreamsTest.groovy
- dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java
- dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTestBase.groovy
- dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
partition tag on this metric is making cardinality really high.
We have data by partition on consumer lag, so removing it from here.
We also don't use that information in the UI.
> [data streams] Remove partition tag from latency metrics

- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDIntakeWriterCombinedTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDIntakeWriterTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/PayloadDispatcherTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy
- dd-trace-ot/src/test/groovy/datadog/opentracing/TypeConverterTest.groovy
- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/api/DynamicConfig.java
- internal-api/src/main/java/datadog/trace/api/TraceConfig.java
Initial API for dynamic configuration which supports capturing a snapshot for the duration of a trace.
More elements will be added to `TraceConfig` as selected static config elements are made dynamic.
> Add initial DynamicConfig API and use it to maintain service mappings

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryContextInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelExtractedContext.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpanBuilder.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TagContext.java
This PR brings the support of OpenTelemetry ContextPropagator API.
It will allow to inject and extract context using OpenTelemetry API.
Improve the support of OpenTelemetry Tracing APIs.
> Add support for OpenTelemetry programmatic context propagation

- gradle/dependencies.gradle
Bumps ddprof to 0.34.0
A severe bug is fixed in 0.34.0 which might lead to incorrect data or JVM crash
* Allow sanitizers to run with unit tests
* Remove object sampler's dependency on JVM symbols
* Test with Ubuntu OpenJDK
* Set pointers to NULL when cleaning dictionary
* Add JMH stresstests
* Add 'scan-build' run to build/CI
* Add counters for thread filter size
* Add and remove thread for wallclock filtering before and after tasks in ContextExecutor
**Full Changelog**: https://github.com/DataDog/java-profiler/compare/v_0.33.0...v_0.34.0
> Bump ddprof lib to 0.34.0

- telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java
- telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
The default namespace is `tracers`, not `tracer`. The backend is rejecting payloads if they have this namespace at payload-level, even if the individual metrics are in separate, valid namespaces.
> Change default telemetry metrics namespace to "tracers"

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/SsrfModuleImpl.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/SsrfModuleTest.groovy
- dd-java-agent/instrumentation/commons-httpclient-2/build.gradle
- dd-java-agent/instrumentation/commons-httpclient-2/src/main/java/datadog/trace/instrumentation/commonshttpclient/IastCommonsHttpClientInstrumentation.java
- dd-java-agent/instrumentation/commons-httpclient-2/src/main/java/datadog/trace/instrumentation/commonshttpclient/IastHttpMethodBaseInstrumentation.java
- dd-java-agent/instrumentation/commons-httpclient-2/src/test/groovy/IastCommonsHttpClientInstrumentationTest.groovy
- dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
- dd-java-agent/instrumentation/java-net/src/main/java/datadog/trace/instrumentation/java/net/URICallSite.java
- dd-java-agent/instrumentation/java-net/src/main/java/datadog/trace/instrumentation/java/net/URLCallSite.java
- dd-java-agent/instrumentation/java-net/src/test/groovy/datadog/trace/instrumentation/java/net/URICallSIteTest.groovy
- dd-java-agent/instrumentation/java-net/src/test/groovy/datadog/trace/instrumentation/java/net/URLCallSiteTest.groovy
- dd-java-agent/instrumentation/java-net/src/test/java/foo/bar/TestURICallSiteSuite.java
- dd-java-agent/instrumentation/java-net/src/test/java/foo/bar/TestURLCallSiteSuite.java
- dd-java-agent/instrumentation/okhttp-2/build.gradle
- dd-java-agent/instrumentation/okhttp-2/src/main/java/datadog/trace/instrumentation/okhttp2/IastHttpUrlInstrumentation.java
- dd-java-agent/instrumentation/okhttp-2/src/main/java/datadog/trace/instrumentation/okhttp2/IastInterceptor.java
- dd-java-agent/instrumentation/okhttp-2/src/main/java/datadog/trace/instrumentation/okhttp2/IastOkHttp2Instrumentation.java
- dd-java-agent/instrumentation/okhttp-2/src/test/groovy/IastOkHttp2InstrumentationTest.groovy
- dd-java-agent/instrumentation/okhttp-3/build.gradle
- dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/IastHttpUrlInstrumentation.java
- dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/IastInterceptor.java
- dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/IastOkHttp3Instrumentation.java
- dd-java-agent/instrumentation/okhttp-3/src/test/groovy/IastOkHttp3InstrumentationTest.groovy
- internal-api/src/main/java/datadog/trace/api/iast/InstrumentationBridge.java
- internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityTypes.java
- internal-api/src/main/java/datadog/trace/api/iast/sink/SsrfModule.java
Adds support for SSRF detection via jdk (URL/URI), okhttp (versions 2 and 3) and commons httpclient (versions 1 and 2)
Support for other frameworks like apache commons (4 and 5), spring rest-template will come later
> Add support for SSRF vulnerabilities

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java
* Keep 'java.lang.Object' outline in its own field as it's used a lot
* Avoid creating single-character strings when looking up primitive types by descriptor
> Small type pool optimizations

- .gitlab-ci.yml
Use GitHub Container Registry to get docker build images from.
Images are now published to GHCR rather than Docker Hub.
> Use GHCR for docker build images

- .circleci/config.yml
- .gitlab-ci.yml
- dd-java-agent/instrumentation/aws-java-sqs-1.0/aws-java-sqs-1.0.gradle
Use GitHub Container Registry to get docker build images from.
Images are now published to GHCR rather than Docker Hub.
Backport #5127
> chore: Use GHCR for docker build images

- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/DDElementMatchers.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/HierarchyMatchers.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGradlePlugin.java
- dd-java-agent/instrumentation/ratpack-1.5/src/main/java/datadog/trace/instrumentation/ratpack/ServerErrorHandlerInstrumentation.java
- dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/HandlerAdapterInstrumentation.java
- dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/RouterFunctionInstrumentation.java
This works better with memoization, because we end up asserting a positive fact rather than negative.
> Prefer asserting concrete class status, rather than the negative 'not(abstract)'

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/SessionState.java
- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsDecorator.java
- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/TracingIterator.java
- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/SqsClientTest.groovy
- dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/SqsDecorator.java
- dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/TracingIterator.java
- dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/SqsClientTest.groovy
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/DatadogMessageListener.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageProducerInstrumentation.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/SessionInstrumentation.java
- dd-java-agent/instrumentation/jms/src/test/groovy/TimeInQueueForkedTest.groovy
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
- dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java
- dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsDecorator.java
- dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTestBase.groovy
- dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitChannelInstrumentation.java
- dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
- dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
- internal-api/src/main/java/datadog/trace/api/Config.java
Decouple time in queue tracking from legacy tracing.
The time in queue can be driven independently with the parameter `dd.<instrumentation>.time-in-queue.enabled`
By default it will be enabled if legacy tracing is disabled (as today)
Quick note: for the v1 naming schema, time in queue is disabled by default because synthetic spans should not be present in the service map
> Decouple time in queue from legacy tracing

- dd-java-agent/instrumentation/sslsocket/src/main/java/datadog/trace/instrumentation/sslsocket/SslSocketInstrumentation.java
- dd-java-agent/instrumentation/sslsocket/src/main/java/datadog/trace/instrumentation/sslsocket/SslSocketStreamsInstrumentation.java
Avoid instrumenting abstract `BaseSSLSocketImpl` 
added additional condition to `hierarchyMatcher` function
> [USM] - Fix SSLSocket instrumentation ForTypeHierarchy filter

- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/ValueScript.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/DiagnosticMessage.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java
use the expression visitor to emit byte code instructions and replace the valueRefResolver that was used before but was limiting the scope of values.
It will help to support for feature form the Expression Language like count/len on map/list/set, or array indexing
> Refactor Metric instrumentation

- .gitlab-ci.yml
Currently, the demo applications deployment to the backend is not triggered when a new version is released. 
This is because the deployment is only triggered for the default branch, and the new version is committed to the release branch. 
The current PR fix this issue by adding a trigger from the release branch to ensure that the deployment is also triggered when a new version is released.
> Fix automatic demo application deploy on release

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java
Add toString for Span decoration probe objects to pretty print in debug logs
> Fix hashcode and equals for Span Decoration Probes

- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InstrumentationTags.java
Adds kafka bootstrap servers list (tag `messaging.kafka.bootstrap.servers` to the kafka producer span (used to compute later `peer.service`).
> add kafka bootstrap server to producer span

- gradle/dependencies.gradle
* Contains a fix for a crash in the beta contextual allocation profiler (disabled by default)
* [Profiler release notes](https://github.com/DataDog/java-profiler/releases/tag/v_0.35.0)
> upgrade to ddprof 0.35.0

- dd-java-agent/instrumentation/testng/build.gradle
Changes back a `strictly` directive to a `force` clause
When running `dependencies` on the `testng` project `gradle` reports a `FAILURE` and IntelliJ IDEA will report an `ERROR` when importing the project.
> Don't use strictly for testng dependency

- internal-api/src/main/java/datadog/trace/api/git/GitInfoProvider.java
- internal-api/src/main/java/datadog/trace/util/Strings.java
- internal-api/src/test/groovy/datadog/trace/api/git/GitInfoProviderTest.groovy
- internal-api/src/test/groovy/datadog/trace/util/StringsTest.groovy
There is a component in the tracer that handles Git metadata (repository URL, commit sha, commit author email, etc).
This component uses a variety of sources (env variables set by CI provider, local `.git` folder, user-supplied values, etc).
If a particular value is not available in one source, the component falls back to alternative sources.
This PR changes the notion of "not available": not only `null` strings, but also empty or blank strings will now result in fallback.
Some CI providers (e.g. Azure Pipelines) sometimes set Git-related environment variables to empty strings.
> Fix Git info extraction logic to fall back to alternative providers when encountering empty or blank strings

- dd-java-agent/instrumentation/jetty-7.0/build.gradle
- dd-java-agent/instrumentation/jetty-7.6/build.gradle
- dd-java-agent/instrumentation/jetty-9/build.gradle
- gradle/test-suites.gradle
Two problems:
* The `addTestSuiteForDir` calls were for adding only targets that don't run the `*ForkedTest`s.
* When adding `ForkedTest` targets, the gradle "configurations"' name are based upon the sourceSet name. `DefaultJvmTestSuite` uses as the sourceSet name the name of the task. Consequently, if we add a target called `latestDepForkedTest`, the created configurations are named `latestDepForkedTestImplementation` and so on, whereas the current `dependencies {}` blocks are only adding dependencies on `latestDepTestImplementation`. Fix this by making the ForkedTest configurations extend from the non-Forked ones (e.g. `latestDepForkedTestImplementation` extends from `latestDepTestImplementation`; `latestDepTestImplementation` is created if it doesn't exist).
> Fix test targets in jetty other than 'test'

- dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisAPICallAdvice.java
- dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisAPIImplSendAdvice.java
- dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisAPIInstrumentation.java
- dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisConnectAdvice.java
- dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisConnectionConstructAdvice.java
- dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisInstrumentation.java
- dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/RedisSendAdvice.java
- dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/ResponseHandlerWrapper.java
- dd-java-agent/instrumentation/vertx-redis-client-3.9/src/main/java/datadog/trace/instrumentation/vertx_redis_client/VertxRedisClientDecorator.java
- dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisTestBase.groovy
- dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisV1ForkedTest.groovy
Implements opt-in v1 naming convestions:
* operation: redis.command
* service: DD_SERVICE
Surface remote host connection tags:
* peer.hostname
* peer.port
> vertx-redis: implement v1 naming and surface remote connection info

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/CILocalGitInfoBuilder.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/CIProviderGitInfoBuilder.java
- internal-api/src/main/java/datadog/trace/api/git/EmbeddedGitInfoBuilder.java
- internal-api/src/main/java/datadog/trace/api/git/GitInfoBuilder.java
- internal-api/src/main/java/datadog/trace/api/git/GitInfoProvider.java
- internal-api/src/main/java/datadog/trace/api/git/UserSuppliedGitInfoBuilder.java
- internal-api/src/test/groovy/datadog/trace/api/git/GitInfoProviderTest.groovy
There is a component in the tracer that fetches git metadata associated with the traced code.
The component has a few sources that it uses to obtain the data:
- environment variables set explicitly by the user
- `git.properties` file available on the classpath (injected either manually or by a Maven/Gradle plugin)
- environment variables set by CI provider (e.g. Jenkins or CircleCI)
- `.git` folder that is available locally
The sources are listed in order of priority.
The last two sources are only available if CI Visibility subsystem is enabled in the tracer.
This PR changes the relative priorities of git metadata sources, making `git.properties` the least preferable one.
`git.properties` is the least reliable of the sources, as we have no way of ensuring that the file located on the …
> Make embedded git.properties have lower priority than other git metadata sources

- dd-java-agent/instrumentation/undertow/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/ServletInstrumentation.java
- dd-java-agent/instrumentation/undertow/undertow-2.0/src/test/groovy/NotHereServlet.groovy
- dd-java-agent/instrumentation/undertow/undertow-2.0/src/test/groovy/UndertowServletTest.groovy
Sets the server request span's resource name to a resolved Undertow servlet route and sets the `http.route` tag.
Adds a test for a servlet returning 404 explicitly to make sure it won't use 404 as for non-existing resource.
Excluding the servlet context from the resource name.
#4999
> Set a resolved Undertow servlet route

- .gitlab-ci.yml
Adds steps to build and deploy `.deb` and `.rpm` packages in Gitlab.
Previously, this was done in the `auto_inject` repo. The goal is to have these steps done in individual language repos.
I put the ~6 lines to build the package directly in the gitlab.yml file. Another choice might be to have that in a separate `.sh` file
> Create deb and rpm packages in gitlab

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanProbeInstrumentationTest.java
Avoid modifying behavior of user code when instrumenting code
> Catch exceptions throws from instrumented code

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastSystem.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/InsecureCookieModuleImpl.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/InsecureCookieModuleTest.groovy
- dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/HttpServletResponseInstrumentation.java
- dd-java-agent/instrumentation/servlet-common/src/test/groovy/HttpServletResponseInstrumentationTest.groovy
- dd-java-agent/instrumentation/servlet-common/src/test/java/foo/bar/DummyResponse.java
- dd-java-agent/instrumentation/servlet/request-2/build.gradle
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaHttpServletResponseInstrumentation.java
- dd-java-agent/instrumentation/servlet/request-5/src/test/groovy/JakartaHttpServletResponseInstrumentationTest.groovy
- dd-java-agent/instrumentation/servlet/request-5/src/test/java/foo/bar/smoketest/DummyResponse.java
- dd-smoke-tests/springboot/build.gradle
- dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
- dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
- internal-api/src/main/java/datadog/trace/api/iast/InstrumentationBridge.java
- internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityTypes.java
- internal-api/src/main/java/datadog/trace/api/iast/sink/InsecureCookieModule.java
Instrument HttpServletRequest so we can examine cookies and make sure they have the Secure flag enabled.
This enables IAST to report insecure cookie vulnerabilities
> Insecure cookies detection for servlet

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/InstrumentationResult.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationComparerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java
Dispatch diagnostic messages per probe id as multiple probes can be instrumented independently on the same location (example metric probes).
We need to keep a list of diagnostic messages per probe id for a location so we change list by a map.
> Fix Diagnostic Messages on multi probes

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastSystem.java
Fix registration for SSRF detection module.
SSRF were simply not being detected outside of tests without this.
> Add missing SSRF setup for IAST

- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ClassLoaderMatchers.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/memoize/HasContextField.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/memoize/HasSuperMethod.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/memoize/MemoizedMatchers.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/memoize/Memoizer.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/memoize/NoMatchFilter.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypePoolFacade.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextInjector.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
- internal-api/src/main/java/datadog/trace/api/ResolverCacheConfig.java
Enables memoization of hierarchical type matchers to reduce the number of times we need to sweep a given type hierarchy.
To turn off memoization add this JVM option:
```
-Ddd.resolver.cache.config=NO_MEMOS
```
```
DD_RESOLVER_CACHE_CONFIG=NO_MEMOS
```
For applications with deep type inheritance each sweep of a hierarchy might result in a complete churn of the type cache. When this happens types cached at the start of each sweep get replaced by others by the end, leading to repeated parsing of the same types for each sweep. This can lead to long startup times when resource lookup is relatively expensive, such as certain OSGi configurations.
Each hierarchy matcher is assigned a unique id as it is requested from `HierarchyMatchers` and a replacement matcher …
> Memoized type matching

- remote-config/src/main/java/datadog/remoteconfig/tuf/RemoteConfigRequest.java
- remote-config/src/test/groovy/datadog/remoteconfig/ConfigurationPollerSpecification.groovy
Only the first remote config capabilities were sent, others were truncated.
> Fix encoding of remote config capabilities

- .gitlab-ci.yml
What does this PR do?
The correct value of CI_PIPELINE_SOURCE is schedule not scheduled. See https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
Motivation
Typo from a previous commit
> Fix scheduled deploys

- dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
- dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Instrumentations will typically have spans to hand, but if they don't then they can use the usual API to find if there's an active span and from that get the appropriate `TraceConfig`.
No-op spans have no `TraceConfig` since there is no trace associated with them.
> Provide access to the trace's TraceConfig given a span from that trace

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-0.3/src/test/groovy/OpenTelemetryTest.groovy
- dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
- dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedContext.java
- dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
- dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextPropagationTagsTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TagContext.java
Avoids capturing the trace config twice and ensures config consistency between extract/trace/inject
> Pass captured TraceConfig from extractor to trace

- dd-smoke-tests/log-injection/build.gradle
> Exclude jboss-logmanager 3.0.0-alpha1 from log-injection smoke tests

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ReflectiveFieldValueResolver.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Types.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot04.java
Call helper methods when trying to access a field that is not accessible directly by GETFIELD bytecode. Those helpers will try by reflection to set accessible to true and get he value of the field For primitive access need special call for each type of primitive
> Add support for private fields for metric values

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ProbeInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java
Add probe id as `_dd.di.dynamictag.probe_id` tag
Add evaluation error as `_dd.di.dynamictag.evaluation_error` tag send snapshot containing evaluation errors when decoration condition evaluation has errors
correlation between probe and span tags
report evaluation errors
> Add probe id and eval errors as _dd tags

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/JsonSnapshotSerializer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ProbeStatus.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ProbeStatusTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
Adds the runtimeId to probe statuses.
Probe statuses can be different for a single probe in a service fleet. Probe status were originally introduced when only one instance per service was applying instrumentation. With DI logs, metrics and spans probe statuses are emitted from more instances of a service.
> Add runtimeId to probe statuses

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/TaskWrapper.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AdviceUtils.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/State.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/TPEHelper.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/TaskWrapperTest.groovy
- dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/resources/jfr/dd.jfp
- dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/JFRTimer.java
- dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/QueueTimeEvent.java
- dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/JFRTimerTest.java
- dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/SafeToLoadJFRCheckpointerTest.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/profiling/UnwrappingVisitor.java
- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/TaskWrapperInstrumentation.java
- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java
- dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
- dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/ProfilingTestApplication.java
- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
- dd-smoke-tests/profiling-integration-tests/src/test/resources/overrides.jfp
- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/main/java/datadog/trace/api/profiling/QueueTiming.java
- internal-api/src/main/java/datadog/trace/api/profiling/Timer.java
- internal-api/src/main/java/datadog/trace/api/profiling/Timing.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Records time spent in the `ThreadPoolExecutor` work queue and emits an event before the scheduled task runs if a threshold of 100ms is breached.
This is the first step in better accounting for time spent off-CPU. Currently we have some profiling for off-CPU time in our wallclock profiler, but this only can only records samples when a thread is blocked. Reactive frameworks tend to avoid blocking, so instead we emit latency thresholded events. The timer itself currently emits an OpenJDK JFR event for ease of development, but in the future this will be moved into our native profiler to better support non-OpenJDK JVMs such as J9. 
The timer state is propagated as a field in `State`. This was chosen over `Continuation` to have more control over which context switches are timed, since there can …
> record time spent in TPE work queue

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
Adding the tags `app_id` and `spark_version` to all spark spans. Before this PR `app_id` was only present on the application span, adding it to all the spark spans will make it easier to get all the spans of a given execution and `spark_version` was not present
> [Spark] Add appId and sparkVersion tags to all spark spans

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sensitive/SqlRegexpTokenizer.java
- dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite.yml
Add support for double quoted string literals in SQLite to IAST redaction
> Add double-quoted string literal in sqlite to IAST redaction

- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
- gradle/dependencies.gradle
- internal-api/src/main/java/datadog/trace/api/Config.java
* Fall back to JFR on JDK18 because it does not contain AsyncGetCallTrace fixes from 17.0.5
* Default to unwinding native portions of stacks via frame pointers
* No longer fall back to JFR because ZGC is active
* Upgrade profiler to [0.36.0](https://github.com/DataDog/java-profiler/releases/tag/v_0.36.0)
> Upgrade ddprof to 0.36.0, change profiler defaults

- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/InsecureCookieModuleTest.groovy
Fix a mistake on a unit test in iast-agent. The test is failing, but CI is not reporting it as failed. It passes after the fix.
To make sure that all tests work in master
> Fix InsecureCookieModuleTest

- dd-trace-core/src/test/groovy/datadog/trace/core/monitor/HealthMetricsTest.groovy
CountDownLatch was initialized to 1 but we needed to wait for 3 calls.
Test introduced at https://github.com/DataDog/dd-trace-java/pull/4966
> Fix HealthMetricsTest flaky tests

- dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RouteHandlerWrapper.java
Fixes use case when the current route path is null
`routingContext.currentRoute().getPath()` can be null
#5177
> Fix for Vert.x 4.0 null path case

- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/jms/SessionStateTest.groovy
In #5015 the meaning of the boolean flag to SessionState constructor was inverted, but it was not updated in tests.
Note that this test is currently not running in CI. See https://github.com/DataDog/dd-trace-java/pull/5213
> Fix SessionStateTest

- dd-smoke-tests/wildfly/build.gradle
See:
```
A problem was found with the configuration of task ':dd-smoke-tests:wildfly:unzip' (type 'Copy').
- Gradle detected a problem with the following location: '/home/circleci/dd-trace-java/workspace/dd-smoke-tests/wildfly/build'.
Reason: Task ':dd-smoke-tests:wildfly:compileTestGroovy' uses this output of task ':dd-smoke-tests:wildfly:unzip' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
Possible solutions:
1. Declare task ':dd-smoke-tests:wildfly:unzip' as an input of ':dd-smoke-tests:wildfly:compileTestGroovy'.
2. Declare an explicit dependency on ':dd-smoke-tests:wildfly:unzip' from ':dd-smoke-tests:wildfly:compileTestGroovy' using Task#dependsOn. 3. Declare an explicit …
```
> Fix :dd-smoke-tests:wildfly build

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastSystem.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/InsecureCookieModuleImpl.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/UnvalidatedRedirectModuleImpl.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/InsecureCookieModuleTest.groovy
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/UnvalidatedRedirectModuleTest.groovy
- dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/HttpServletResponseInstrumentation.java
- dd-java-agent/instrumentation/servlet-common/src/test/groovy/HttpServletResponseInstrumentationTest.groovy
- dd-java-agent/instrumentation/servlet-common/src/test/java/foo/bar/DummyResponse.java
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaHttpServletResponseInstrumentation.java
- dd-java-agent/instrumentation/servlet/request-5/src/test/groovy/JakartaHttpServletResponseInstrumentationTest.groovy
- dd-java-agent/instrumentation/servlet/request-5/src/test/java/foo/bar/smoketest/DummyResponse.java
- dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
- dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/AbstractSpringBootIastTest.groovy
- dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootRedirectSmokeTest.groovy
- dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
- internal-api/src/main/java/datadog/trace/api/iast/InstrumentationBridge.java
- internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityTypes.java
- internal-api/src/main/java/datadog/trace/api/iast/sink/HttpHeaderModule.java
- internal-api/src/main/java/datadog/trace/api/iast/sink/InsecureCookieModule.java
- internal-api/src/main/java/datadog/trace/api/iast/sink/UnvalidatedRedirectModule.java
- internal-api/src/test/groovy/datadog/trace/api/iast/InstrumentationBridgeTest.groovy
Add instrumentation to javax.servlet.http.HttpServletResponse:
- addHeader/setHeader for location headers
- sendRedirect
Add tainting support to javax.servlet.http.HttpServletResponse:
- encodeURL
- encodeRedirectURL
Unify Header instrumentation callbacks, we need to analice the headers with multiple sink modules at the same time
- Support Unvalidated redirect vulnerability
This is a first iteration, only supports servlet unvalidated redirect vulnerability
> Detect unvalidated redirect vulnerabilities in servlets

- build.gradle
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/DBTypeProcessingDatabaseClientDecoratorTest.groovy
- dd-java-agent/agent-iast/src/testFixtures/groovy/com/datadog/iast/test/IastRequestContextPreparationTrait.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
- dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpServerInstrumentationTest.groovy
- dd-java-agent/instrumentation/grizzly-2/src/test/groovy/GrizzlyTest.groovy
- dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyTest.groovy
- dd-java-agent/instrumentation/java-lang/java-lang-11/build.gradle
- dd-java-agent/instrumentation/java-lang/java-lang-9/build.gradle
- dd-java-agent/instrumentation/jedis-4.0/src/test/groovy/Jedis40ClientTest.groovy
- dd-java-agent/instrumentation/netty-3.8/src/latestDepTest/groovy/datadog/trace/instrumentation/netty38/latestdep/Netty38ServerTest.groovy
- dd-java-agent/instrumentation/netty-3.8/src/test/groovy/datadog/trace/instrumentation/netty38/Netty38ServerTest.groovy
- dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ServerTest.groovy
- dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ServerTest.groovy
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
- dd-java-agent/instrumentation/redisson-2.0.0/src/test/redisson20/groovy/RedissonClientTest.groovy
- dd-java-agent/instrumentation/redisson-2.0.0/src/test/redisson23/groovy/RedissonClientTest.groovy
- dd-java-agent/instrumentation/redisson-2.0.0/src/test/redissonLatest/groovy/RedissonClientTest.groovy
- dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServletHandlerTest.groovy
- dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/Servlet3TestGetParameterInstrumentation.groovy
- dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
- dd-java-agent/instrumentation/spring-cloud-zuul-2/src/test/groovy/SpringBootZuulTest.groovy
- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java
- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
- dd-trace-core/src/test/groovy/datadog/trace/core/tagprocessor/PeerServiceCalculatorTest.groovy
Fix test partitioning, which used project path hashCode without considering it can be negative.
Tests that are disabled by this PR:
* `PowerWAFModuleSpecification.rule toggling data given through configuration` which was disabled until recently anyway.
PRs fixing issues that were previously masked by this:
* https://github.com/DataDog/dd-trace-java/pull/5212
* https://github.com/DataDog/dd-trace-java/pull/5216
* https://github.com/DataDog/dd-trace-java/pull/5217
* https://github.com/DataDog/dd-trace-java/pull/5218
* https://github.com/DataDog/dd-trace-java/pull/5225
* https://github.com/DataDog/dd-trace-java/pull/5229
* https://github.com/DataDog/dd-trace-java/pull/5230
Effectively, some removed from this list since they run in non-parallelized jobs):
```
:dd-java-agent:agent-bootstrap …
```
> Fix job partitioning in CI

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sensitive/SqlRegexpTokenizer.java
- dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite.yml
Fix issue with SQL tokenizer being too greedy when dealing with oracle and postgresql escaped strings
> Improve support for SQL escaped literals in redaction

- telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java
- telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
* Fix telemetry heartbeat in presence of other messages
* Removed some mocking from telemetry tests to avoid masking bugs.
Telemetry heartbeats were not being sent in any telemetry interval with other pending telemetry messages. This leads to backend issues when detecting vulnerable services.
This PR is limited to the heartbeat issues, but there are still a few issues with telemetry intervals that will need to be addresses separately.
> Fix telemetry heartbeat in presence of other messages

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/UnvalidatedRedirectModuleImpl.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/UnvalidatedRedirectModuleTest.groovy
- dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/JakartaWSResponseInstrumentation.java
- dd-java-agent/instrumentation/jersey/src/test/groovy/datadog/trace/instrumentation/jersey/JakartaWSResponseInstrumentationTest.groovy
- dd-java-agent/instrumentation/resteasy-appsec/src/main/java/datadog/trace/instrumentation/resteasy/JavaxWSResponseInstrumentation.java
- dd-java-agent/instrumentation/resteasy-appsec/src/test/groovy/JavaxWSResponseInstrumentationTest.groovy
- dd-smoke-tests/jersey-3/src/main/java/smoketest/resource/MyResource.java
- dd-smoke-tests/jersey-3/src/test/groovy/datadog/smoketest/Jersey3SmokeTest.groovy
- dd-smoke-tests/resteasy/src/main/java/smoketest/resteasy/Resource.java
- dd-smoke-tests/resteasy/src/test/groovy/smoketest/ResteasySmokeTest.groovy
- internal-api/src/main/java/datadog/trace/api/iast/sink/UnvalidatedRedirectModule.java
Add jakarta.ws.rs.core.Response header and location instrumentation
Add javax.ws.rs.core.Response header and location instrumentation
Modify UnvalidatedRedirectModule to accept URI objects
Add new test cases to jersey and resteasy smoke tests
> resteasy and jersey unvalidated redirect instrumentation

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatabricksParentContext.java
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkTest.groovy
Databricks spark spans are generated from this spark instrumentation, while databricks workflow task spans are generated from the databricks API. The traceId/spanId is computed using the same hash on both sides to link everything in the same trace
Those hash are computed using a combinaison of the `job_id`, `job_run_id` and `task_run_id`
> [Spark] Link databricks spark jobs to databricks workflow tasks

- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
If the span is missing or doesn't have a trace config then the tracer will return its current trace config.
Users can therefore rely on these always returning a non-null trace config when using our core tracer.
> Provide 'traceConfig(span)' and 'traceConfig()' static helpers

- internal-api/src/main/java/datadog/trace/api/git/GitInfoProvider.java
Disables [embedded Git metadata extraction](https://github.com/DataDog/dd-trace-java/pull/4951).
Component that extracts embedded Git metadata looks for it in `git.properties` files that are available on the classpath.
The idea is that customers should configure build system plugins that would add this file to their release artifacts.
The problem is that these files can be found inside 3rd party libraries too, and there is no telling whether a file comes from the customer's jar or from a dependency.
The feature is disabled temporarily until a long-term solution is agreed upon (most likely the filename will be changed to a non-standard one).
> Disable embedded Git metadata extraction

- gradle/dependencies.gradle
Contains fixes:
* thread states recorded more accurately on wallclock samples - [tag](https://github.com/DataDog/java-profiler/releases/tag/v_0.38.0)
* live heap profiling under ZGC - [tag](https://github.com/DataDog/java-profiler/releases/tag/v_0.39.0)
> bump ddprof to 0.39.0

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/Advices.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteTransformer.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/AdvicesInvokeDynamicTest.groovy
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/AdvicesTest.groovy
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/BaseCallSiteTest.groovy
This PR reuses the class file buffer present in the `AbstractInliningDynamicTypeBuilder` via reflection before attempting a resolution of the class file before doing the constant pool analysis for the call sites
The main motivation for this PR is to reduce the time it takes for the CSI instrumentation to decide if a class has to be instrumented or not.
> Optimize CSI advices when fetching class file buffers

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
- dd-java-agent/instrumentation/resteasy-appsec/src/main/java/datadog/trace/instrumentation/resteasy/PathParamInjectorAdvice.java
- internal-api/src/main/java/datadog/trace/api/iast/source/WebModule.java
Fixes the vulnerability source when reporting vulnerabilities if the source is parameter path since it was wrongly reported
Reporting the correct parameter source to the user so he can understand the vulnerability properly.
> Fix path parameter vulnerability source in resteasy

- dd-java-agent/agent-profiling/profiling-controller-ddprof/src/main/java/com/datadog/profiling/controller/ddprof/DatadogProfilerOngoingRecording.java
- dd-java-agent/agent-profiling/profiling-controller-ddprof/src/main/java/com/datadog/profiling/controller/ddprof/DatadogProfilerSettings.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
- gradle/dependencies.gradle
Emits `datadog.ProfilerSetting` events when on J9 (which does not support JFR)
> Emit datadog.ProfilerSetting events on J9

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
- dd-java-agent/agent-profiling/profiling-controller-ddprof/src/main/java/com/datadog/profiling/controller/ddprof/DatadogProfilerCheckpointer.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
Implements and registers an `EndpointCheckpointer` which doesn't use JFR to record the endpoint events required for endpoint profiling to work. This means endpoint profiling can be used on non-OpenJDK JVMs such as J9. This is simple glue code for a component which is well tested across a range of architectures/libc/JDK distributions in the java-profiler repository, so no new tests beyond the existing smoke tests are added.
> implement endpoint profiling for JDKs which don't have JFR

- dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/server/HttpServerResponseTracingHandler.java
- dd-java-agent/instrumentation/netty-3.8/src/test/groovy/datadog/trace/instrumentation/netty38/Netty38ServerTest.groovy
- dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/HttpServerResponseTracingHandler.java
- dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ServerTest.groovy
- dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/HttpServerResponseTracingHandler.java
- dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ClientTest.groovy
- dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ServerTest.groovy
- dd-java-agent/instrumentation/undertow/undertow-2.0/src/test/groovy/UndertowDispatcherTest.groovy
- dd-java-agent/instrumentation/undertow/undertow-2.0/src/test/groovy/UndertowServletTest.groovy
- dd-java-agent/instrumentation/undertow/undertow-2.0/src/test/groovy/UndertowTest.groovy
- dd-java-agent/instrumentation/undertow/undertow-2.2/src/test/groovy/UndertowDispatcherTest.groovy
- dd-java-agent/instrumentation/undertow/undertow-2.2/src/test/groovy/UndertowServletTest.groovy
- dd-java-agent/instrumentation/undertow/undertow-2.2/src/test/groovy/UndertowTest.groovy
- dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/server/VertxRxCircuitBreakerHttpServerForkedTest.groovy
- dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/server/VertxRxHttpServerForkedTest.groovy
- dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/VertxHttpServerForkedTest.groovy
- dd-java-agent/instrumentation/vertx-web-3.4/src/test/java/server/VertxTestServer.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/server/VertxHttpServerForkedTest.groovy
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/java/server/IastSourcesVerticle.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/java/server/VertxTestServer.java
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/OkHttpUtils.java
- dd-smoke-tests/vertx-3.4/application/src/main/java/datadog/vertx_3_4/IastVerticle.java
- dd-smoke-tests/vertx-3.4/application/src/main/java/datadog/vertx_3_4/MainVerticle.java
- dd-smoke-tests/vertx-3.9/application/src/main/java/datadog/vertx_3_9/IastVerticle.java
- dd-smoke-tests/vertx-3.9/application/src/main/java/datadog/vertx_3_9/MainVerticle.java
When the client request a 100 continue to early check the validity of the request without sending the full body, the netty server can send downstream its pipeline a http response with the 100 continue status.
However, this is not the final http response status since there will be another upon termination.
The issue with our instrumentation is that we set the status once and we finish the span. This will cause to create two root spans with wrong information
Example:
> [netty] don't create two root spans if 100 continue is expected

- .circleci/config.yml
Fix CI for parametric tests. They now rely on the requirements.txt in the root directory.
After this PR https://github.com/DataDog/system-tests/pull/1190 we need to use the `requirements.txt` in the root directory of system tests.
> Fix CI for parametric tests

- gradle/dependencies.gradle
* Removes lock tracer
* Reverts change which attaches wallclock sampler thread for JVMTI, which made it a participant in safepoints
> upgrade to ddprof 0.41.0

- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
- dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
- dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
Fix IAST smoke tests in spring boot 2.6 due to slight differences on how it deals with matrix parameters
> Fix matrix parameters test in spring boot 2.6

- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
Enables the v0.5 trace agent protocol by default
v0.5 brings significant performance improvements over previous version. v0.5 was implemented ~3 years ago.
> Enable v0.5 protocol by default

- dd-smoke-tests/springboot-openliberty/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySnapshotTest.groovy
We moved to trace protocol v0.5, but the mock agent used for this suite does not support it.
See https://github.com/DataDog/dd-trace-java/pull/5174
> Fix SpringBootOpenLibertySnapshotTest

- telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java
Before the PR all jar files were opened to calculate the jar file SHA1 signature, even before checking if maven information was available (and in that case the signature was avoided)
> Avoid opening jar files before checking in pom is available

- gradle/dependencies.gradle
* fixes fd leak in full process wallclock profile mode
* avoids elf parsing unknown libraries unless cstack=dwarf
> Upgrade ddprof to 0.42.0

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/DBQueryInfo.java
- internal-api/src/main/java/datadog/trace/api/cache/DDCaches.java
- internal-api/src/main/java/datadog/trace/api/cache/FixedSizeWeightedCache.java
- internal-api/src/test/groovy/datadog/trace/api/cache/FixedSizeCacheTest.groovy
This adds a new cache type `FixedSizeWeightedCache` that tracks the total weight of cached elements, based on a supplied `weigher` function. Elements will be evicted to maintain the total weight below the configured limit.
This PR also updates the shared `DBQueryInfo` cache to use  `FixedSizeWeightedCache`. The total weight limit (in terms of the length of cached SQL statements) was based on the previous check, ie. `512` slots x `4096` maximum-length SQL is the equivalent of `2 * 1024 * 1024` overall characters.
#3744 added a simple check to avoid caching very large SQL queries, because storing several hundred of these used up a noticeable amount of memory. Unfortunately in some situations this check can have the opposite effect - SQL queries just over the limit won't be cached, and …
> Limit SQL cache by overall content size

- buildSrc/call-site-instrumentation-plugin/build.gradle.kts
- buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/impl/AsmSpecificationBuilder.java
- buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/AsmSpecificationBuilderTest.groovy
- dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringBuilderCallSite.java
- dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/StringBuilderCallSiteTest.groovy
- dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestAbstractStringBuilderSuite.java
- dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringBufferSuite.java
- dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringBuilderSuite.java
- internal-api/src/main/java/datadog/trace/util/stacktrace/StackUtils.java
- internal-api/src/test/java/datadog/trace/util/stacktrace/StackUtilsTest.java
Makes sure that the `StringBuilder.append(String, Object)` is properly handled and propagation is not lost
> Ensure StringBuilder.append(String, Object) is properly instrumented

- telemetry/build.gradle
- telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java
- telemetry/src/main/java/datadog/telemetry/TelemetryService.java
- telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
- telemetry/src/main/java/datadog/telemetry/api/KeyValue.java
- telemetry/src/test/groovy/datadog/telemetry/TelemetryRunnableSpecification.groovy
- telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
- telemetry/src/test/groovy/datadog/telemetry/TelemetrySystemSpecification.groovy
- telemetry/src/test/groovy/datadog/telemetry/metric/MetricPeriodicActionTest.groovy
Functional changes:
* Telemetry messages should be sent only at the heartbeat interval.
* The metrics interval is used to accumulate metrics, not sending messages.
* Remove all retry logic, no backoff.
Refactor:
* Separate concerns: `TelemetryRunnable` knows about timing, not HTTP requests. `TelemetryService` knows about HTTP requests, not about timing.
> Improve telemetry intervals behavior

- gradle/dependencies.gradle
Bumps the ddprof lib to 0.44.0
* Improved thread-local thread state
* Record heap usage events to help recovering live heap size
**Full Changelog**: https://github.com/DataDog/java-profiler/compare/v_0.42.0...v_0.44.0
> Bump ddprof lib to 0.44.0

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
- dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
- internal-api/src/main/java/datadog/trace/api/normalize/HttpResourceNames.java
Fixes the urlAsAResource rule on the tag interceptor. A couple of things:
1.  Uses the path and not the full url to match against the http resource mapping ant patterns
2. Uses the client settings for http client spans (currently uses always the server patterns which is wrong)
> fix http resource mapping

- dd-java-agent/instrumentation/spark/build.gradle
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkTest.groovy
Instrument the spark [yarn.ApplicationMaster.finish()](https://github.com/apache/spark/blob/master/resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/ApplicationMaster.scala#L378) function in order to
- catch the exit code and exit message of the application
- make sure the `spark.application` span is finished before the trace processor is exited
An application can fail during spark computations (when performing operations on the data) or in the user code (like trying to select a column that does not exists)
Failures during spark computations are caught by the SparkListener, but not the errors in the user code so instrumenting the finish function allows to also capture those
The spark.application span is the local root span and is finished when the event `onApplicationEnd` …
> [Spark] Instrument YARN application end to not drop traces

- .circleci/config.yml
- dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
Uses the built `dd-java-agent` in the parametric tests.
Previous versions of the parametric build and test used `dd-trace-ot` to drive the test server, but that was changed to use pure OpenTracing/Datadog API, and the Java Tracer. The CI was missed in the update, making the parametric tests use a fixed version of `1.12.1`.
> Use built dd-java-agent in parametric tests

- .gitlab-ci.yml
- .gitlab/exploration-tests.yml
- dd-java-agent/agent-debugger/exploration-tests/Dockerfile.exploration-tests
- dd-java-agent/agent-debugger/exploration-tests/exclude.txt
- dd-java-agent/agent-debugger/exploration-tests/run-exploration-tests.sh
Special mode for dd-java-agent instrumenting every methods in loaded class. We run tests from jackson library with dd-trace-java and this mode enabled and expect no error.
Running those tests with Gitlab. Each job generate an agent.log file containing debug logs of instrumentation
> Add exploration tests for debugger

- dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/HttpServletResponseInstrumentation.java
Fix a problem in cookie instrumentation where it would not instrument jetty response object because addCookie signature takes a different cookie class.
To make sure Response is always instrumented
See https://github.com/DataDog/dd-trace-java/pull/5117
> Fix addCookie instrumentation in Jetty

- dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/ParamValueFactoryWithSourceInstrumentation.java
- dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/PathParamValueFactoryInstrumentation.java
- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractJerseySmokeTest.groovy
Adds instrumentation for the path parameters injector in the Jersey framework
IAST needs to report the correct sources for vulnerabilities and this allows us to set the correct source in the case of path parameters
> Fix missing path parameter source from Jersey framework

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkTest.groovy
- dd-java-agent/instrumentation/spark/src/test/java/TestSparkComputation.java
Before this PR, the full error message from spark (which also contained the stack trace) was added to the `span.setErrorMessage`. Changing that to separate the message from the stack trace in the span so it can be better represented in the UI
Another change is to only send task errors that `countTowardsTaskFailures` as the ones that don't count as a failure tend to be very noisy (`FetchFailed`, `Resubmitted`, ...)
> [Spark] Separate the error stack trace from the error message

- dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/JavaxWSResponseInstrumentation.java
- dd-java-agent/instrumentation/jersey/src/test/groovy/datadog/trace/instrumentation/jersey/JakartaWSResponseInstrumentationTest.groovy
- dd-smoke-tests/jersey-2/src/main/java/com/restserver/Resource.java
- dd-smoke-tests/jersey-3/src/main/java/smoketest/Resource.java
- dd-smoke-tests/resteasy/src/main/java/smoketest/resteasy/Resource.java
- dd-smoke-tests/resteasy/src/test/groovy/smoketest/ResteasySmokeTest.groovy
Instruments Response object in the javax.ws.rs and jakarta.ws.rs so we can report when insecure cookies are created
To increase the number of vulnerabilities that IAST monitors and reports
This PR depends on both https://github.com/DataDog/dd-trace-java/pull/5117 and https://github.com/DataDog/dd-trace-java/pull/4931 so I will keep it as draft until this two are merged.
> IAST Insecure cookie detection for JAX-RS frameworks

- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGClassListener.java
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGUtils.java
- dd-java-agent/instrumentation/testng/src/testFixtures/groovy/datadog/trace/instrumentation/testng/TestNGTest.groovy
- dd-java-agent/instrumentation/testng/testng-7.5/src/main/java/datadog/trace/instrumentation/testng75/TestNGClassListenerInstrumentation.java
Fixes Test NG integration for cases when parallel execution mode is set to tests and when XML configuration is used.
There are clients who use CI Visibility with Test NG in tests parallel mode and with explicit XML configuration.
When Test NG is configured explicitly using XML (rather than when Maven/Gradle plugins create an implicit XmlSuite instance), some of the assumptions made previously do not hold: it is possible to have multiple ITestClass instances for the same Java class and multiple ITestMethod instances for the same test case method.
> Fix TestNG integration for TESTS parallel mode

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Instrumentor.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot23.java
Add protection about array out of bounds
in some cases there is no match between method arguments and local variable tables (hidden arg, inherited method with no info in local variable table)
> Fix handling of local variable table

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/SerializerWithLimits.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/StringTokenWriterTest.java
if null elements are present in map or collections, serialization was throwing NullPointerException
> Fix NullPointerException in map/list serialization

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/SessionState.java
This avoids a potential issue with long-running client-ack sessions where we might continue to use the time of the oldest previously captured span, even when messages are continually acknowledged. This could then result in message spans finishing a bit earlier than expected, but this would only happen once per-hour as the oldest capture time would then be reset.
After this fix the oldest capture time is always reset after a message ack.
> Reset oldest capture time on JMS message-ack

- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
Disables the use of v05 trace protocol by default.
Some customers have reported issues since enabling v05 by default.
> Disabled v05 by default

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/SerializerWithLimits.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/StringTokenWriter.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/MoshiSnapshotTestHelper.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/StringTokenWriterTest.java
Catch exception and report it safely into the snapshot
Some implementation of collections or maps may throw exceptions in somce situations which can happen during our serialization process
> Fix Collection/Map serialization

- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
- dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsDecorator.java
- dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/SqsDecorator.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
- dd-java-agent/instrumentation/jms/src/test/groovy/JMS1Test.groovy
- dd-java-agent/instrumentation/jms/src/test/groovy/TimeInQueueForkedTest.groovy
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
- dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsDecorator.java
- dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
- dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/main/java/datadog/trace/api/naming/NamingSchema.java
- internal-api/src/main/java/datadog/trace/api/naming/v0/CacheNamingV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v0/ClientNamingV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v0/CloudNamingV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v0/DatabaseNamingV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v0/MessagingNamingV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v0/NamingSchemaV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v1/NamingSchemaV1.java
- internal-api/src/test/groovy/datadog/trace/api/naming/NamingV0ForkedTest.groovy
This PR allow to flatten every service name to `DD_SERVICE` also in v0 if the env `DD_TRACE_REMOVE_CLIENT_SERVICE_NAMES_ENABLED` is set to true
Please note that having this activated (like happening in v1) implies:
* legacy tracing disabled (otherwise we'll have fake services like `kafka`)
*  time in queue disabled (same reasons)
I took the time hence to refactor the way we determined if legacy tracing was enabled in the decorators by getting rid of checks like `schemaVersion == 0` that can cause nasty coupling
> allow removal of fake services in v0

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/TracingConfigPoller.java
- dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
- internal-api/src/main/java/datadog/trace/api/DynamicConfig.java
- remote-config/src/main/java/datadog/remoteconfig/Product.java
Activation of remote-config's shared poller now occurs earlier than before, because it is now activated when installing the tracer rather than when setting up AppSec (note the remote-config poller is used even when AppSec is inactive, to allow users to fully activate AppSec.) This shows up in the benchmarks below where the `GlobalTracer` phase has increased by ~50ms while the `AppSec` phase has decreased by the same amount. The overall startup time however has remained the same.
> Apply APM tracing overrides from remote-config

- dd-java-agent/instrumentation/vertx-web-3.4/build.gradle
- dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/HttpServerResponseInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/IastVertx34Server.groovy
- dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/Vertx34InsecureCookieTest.groovy
- dd-java-agent/instrumentation/vertx-web-3.4/src/test/java/server/IastVertxTestVerticle.java
- dd-smoke-tests/vertx-3.4/application/src/main/java/datadog/smoketest/vertx_3_4/IastHandler.java
- dd-smoke-tests/vertx-3.4/src/test/groovy/datadog/smoketest/IastVertxSmokeTest.groovy
- dd-smoke-tests/vertx-3.9/application/src/main/java/datadog/smoketest/vertx_3_9/IastHandler.java
- dd-smoke-tests/vertx-3.9/src/test/groovy/datadog/smoketest/IastVertxSmokeTest.groovy
Instruments Vertx's SeverResponse in order to detect insecure cookies.
Insecure cookie detection needs to cover the main frameworks.
> IAST insecure cookie - vertx instrumentation

- .circleci/config.yml
Speeds up the parametric tests by running them on a larger instance with more concurrency as well as switching to a Java 17
Slow tests are slow
> Run parametric tests on larger instance with newer JVM

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/ProbeRateLimiter.java
Global rate limiter (more permissive) should be test before the per probe one and condition the test of the second on the validity of the first
> Fix mixing global and per probe rate limiting

- telemetry/src/main/java/datadog/telemetry/TelemetryService.java
- telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
While the real agent/intake currently responds to telemetry submissions with 202, the test agent uses 200
It seems odd to classify 200 as unsuccessful, so I'm widening the check to consider all 2xx responses as successful
> Accept any telemetry 2xx response as successful, not just 202

- dd-java-agent/instrumentation/spark/src/test/groovy/SparkTest.groovy
The order in which spark is generating the spans is not deterministic, leading to flakiness in the `generate error tags in failed spans` test
Using `blockUntilChildSpansFinished` to finish the spans in a deterministic order
> Fix spark flaky test

- .circleci/config.yml
Adds JUnit XML test output to the parametric tests to make it easier to directly see the failing test and the test output without looking in the log file.
> Use JUnit XML test results in parametric tests

- .circleci/config.yml
Runs the instrumentation check concurrently on 4 nodes.
By far the slowest task taking more than 20 minutes. With 4 nodes, it's down to 8 minutes.
> Run instrumentation check in parallel

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/ProbeRateLimiter.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
We need to store if the probe capture snapshot or not for choosing the right global rate limiter.
ProbeRateLimiter having only one global rate for snapshot, we need to have a separate one for logs with higher rate.
> Introduced separate global rate limiter for logs

- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ControllerFactory.java
This allows Oracle JDK8 users to get profiling without using its commercial JFR facility.
> Use Datadog profiler on Oracle JDK8u361+

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
- dd-trace-core/src/jmh/java/datadog/trace/core/propagation/ExtractorBenchmark.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/TracingConfigPoller.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
- dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpInjectorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/W3CHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpInjectorTest.groovy
- internal-api/src/main/java/datadog/trace/api/DynamicConfig.java
- internal-api/src/main/java/datadog/trace/api/TraceConfig.java
Follow-up to https://github.com/DataDog/dd-trace-java/pull/5154 but for response header processing.
Note: users can still statically configure separate tag mappings for request and response headers
> Apply any dynamically overridden header-tags to response headers as well

- dd-trace-core/src/main/java/datadog/trace/core/TracingConfigPoller.java
- dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
- internal-api/src/main/java/datadog/trace/api/DynamicConfig.java
* config-id is now a hash and should be ignored
* service mapping and header tags are now passed as a series of structured entries rather than a map
* we parse these into a collection of map entries and process as before, without needing to call to `entrySet`
> Update dynamic-config to reflect latest schema changes

- buildSrc/build.gradle.kts
- buildSrc/src/test/groovy/InstrumentPluginTest.groovy
- gradle/dependencies.gradle
[Byte Buddy 1.14.5](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.14.5)
* Avoid use of location if agent argument separator is contained
* Allow failure of member substitution if no element is separated
* Allow retry in case of parallel class injection
^ this last improvement might help avoid some of the "duplicate class definition" errors we've seen in the past
[Byte Buddy 1.14.4](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.14.4)
* Include instrumented type and auxiliary types in TypePool that is passed to TypeWriter
> byte-buddy 1.14.5

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
By default (AppSec inactive), log to debug instead of info. This prevents getting an uninteresting (by default) early log line with:
>  AppSec is ENABLED_INACTIVE with powerwaf(libddwaf: 1.10.0)
> Less verbose AppSec start log

- gradle/dependencies.gradle
Upgrades to [ddprof 0.46.0](https://github.com/DataDog/java-profiler/releases/tag/v_0.46.0) to pick up bug fixes
> upgrade to ddprof 0.46.0

- dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/exceptions/ExceptionProfiling.java
- dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/exceptions/ExceptionSampleEvent.java
- dd-java-agent/instrumentation/exception-profiling/src/main/java/datadog/exceptions/instrumentation/ThrowableInstrumentation.java
- dd-java-agent/instrumentation/exception-profiling/src/main/java11/datadog/exceptions/instrumentation/ThrowableInstanceAdvice.java
This addresses a fairly large source of overhead in exception profiling when applications throw lots of exceptions: 
The instrumentation will only activate if the `Throwable` class has a field called `stackTrace` (rather than crash) which means exception profiling would be unavailable, but this is unlikely ever to happen.
> get stack depth from Throwable stackTrace to avoid copy

- gradle/dependencies.gradle
Links libstdc++ statically, which was erroneously undone in 0.46.0.
> Upgrade to ddprof 0.47.0

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/BaseDecoratorTest.groovy
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecoratorTest.groovy
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/DispatcherServletInstrumentation.java
- dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java17/datadog/trace/instrumentation/springweb6/ErrorHandlerAdvice.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ErrorPriorities.java
Similarly to resource names, it adds priority based error flag settings.
The http servers will set error using a lower priority than the user one. The errors set elsewhere will stay untouched (but it should be changed in the future as well).
It solves a particular two use cases: 
* The error set by the user should have higher prio than the one set according to a http response status code
* The application server throws an error but, despite logged, the error flag should be set according to the http status code
> Add priorities for server set errors

- communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
- telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
Before:
```
[dd-remote-config] DEBUG datadog.communication.ddagent.DDAgentFeaturesDiscovery - Error querying info at null
at datadog.communication.ddagent.DDAgentFeaturesDiscovery.doDiscovery(DDAgentFeaturesDiscovery.java:137)
at datadog.communication.ddagent.DDAgentFeaturesDiscovery.discoverIfOutdated(DDAgentFeaturesDiscovery.java:123)
at datadog.communication.ddagent.DDAgentFeaturesDiscovery.discoverIfOutdated(DDAgentFeaturesDiscovery.java:112)
at datadog.communication.ddagent.SharedCommunicationObjects$RetryConfigUrlSupplier.get(SharedCommunicationObjects.java:119)
at datadog.communication.ddagent.SharedCommunicationObjects$RetryConfigUrlSupplier.get(SharedCommunicationObjects.java:102)
at datadog.remoteconfig.ConfigurationPoller.initialize(ConfigurationPo …
```
> Generate useful error that includes the bad agent URL instead of unhelpful NullPointerExceptions

- dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/FinishAsyncDispatchListener.java
The supplied request may be `null` according to the javadoc:
https://docs.oracle.com/javaee/7/api/javax/servlet/AsyncEvent.html#getSuppliedRequest--
> Returns:
> the ServletRequest that was used to initialize this AsyncEvent, or null if this AsyncEvent was initialized without any ServletRequest
The supplied response may also be `null`, but this is already covered by an `instanceof` check.
> Handle when Servlet3 AsyncEvent was initialized without any ServletRequest

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkAggregatedTaskMetrics.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkListenerTest.groovy
The available executor time is defined as `sum(executor uptime * number of cores)` it is already computed for the whole spark application
This PR introduce the computation to attribute it for each stage
- when only one stage is running, the executor time of the full executor time is attributed to the stage
- when multiple stages are running at the same time, the executor time attribution is weighted by the run time of each stage
> [Spark] Compute available executor time per stage

- gradle/dependencies.gradle
- internal-api/src/main/java/datadog/trace/api/Config.java
* Changes the thread state when contention is detected in wallclock samples from BLOCKED to CONTENDED
* Disables Datadog profiler on OpenJDK8/aarch64 because we saw some AsyncGetCallTrace crashes in testing
> upgrade ddprof 0.49.0, disable on OpenJDK8/aarch64

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot24.java
Use a ThreadLocal storage for a boolean to avoid it.
in some case serialization can enter in an infinite loop
only support log/snapshot probes, will support other kind of probe later
> Avoid having infinite recursive loop serialization

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
Enables our new allocation profiler by default on any JDK >= 11 or when any allocation profiling is explicitly enabled.
> enable contextual allocation profiler by default

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
Updates the profiler config keys to be in sync with the final feature name.
The feature name changed from quite misleading ‘Memleak Profiler’ to more fitting ‘Live Heap Profiler’, yet we released several versions with ‘memleak’ in the config keys.
Although the releases were not public, there definitely may be deployments out there. Therefore it is required to keep the backward compatibility while changing the `memleak` part to `liveheap`.
> Update the live heap profiling config keys

- .circleci/config.yml
Updates the `system-tests` and `paramteric-tests` commit to a version that contains some fixes for sampling tests that had lots of spurious failures.
Relevant commit Datadog/system-tests@6a8304779165bfc221303794f9941bd2a8615647
> Newer parametric tests with some sampling test fixes

- dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/CompressingRequestBody.java
- dd-java-agent/build.gradle
Stops using the JNI implementations in lz4-java, and then removes the bundled native libraries. I have extensive experience with this library and have found that compressing large binaries via JNI is bad for time-to-safepoint, and that on more recent JDKs the Java code is very competitive with native code (LZ4 and XXHash32 are extremely simple algorithms).
Slightly reduces the agent jar size: 
before:
```
27180	dd-java-agent-1.16.0-SNAPSHOT.jar
inflated top level breakdown of contents:
45776	inst
19556	shared
12400	appsec
7016	profiling
3336	datadog
3224	metrics
1296	debugger
540	iast
452	ci-visibility
```
after:
```
26664	dd-java-agent-1.16.0-SNAPSHOT.jar
inflated top level breakdown of contents:
45776	inst
19556	shared
12400	appsec
5708	profiling
3340	datadog
3224	metrics
1304	debugger …
```
> Stop using LZ4 via JNI, remove lz4-java native libraries

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
Reverts DataDog/dd-trace-java#5378
This appears not to be working well when there is a high rate of class unloading
> Revert "enable contextual allocation profiler by default"

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/ProbeRateLimiter.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/SerializerWithLimits.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/StringTokenWriterTest.java
Remove duplicate serialization of `this`
`this` instance was serialized twice by instrumentation adding this as
argument and by explicit serialization in json adapters.
This duplicate was deduplicated automatically when parsed on the backend side
Fix unit tests that were incorrect and cannot use directly fields anymore
> Fix `this` duplicate serialization in snapshot

- dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java
Quarkus Native adds some additional settings to the GraalVM `native-image` build that prevent the `Config` object from being re-resolved at runtime. This PR adds some additional instructions to guarantee that `Config` is re-run at runtime.
It's useful to be able to change non-instrumentation config settings like trace debug at runtime.
> Enable reloading of Config in Quarkus Native

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/TPEHelper.java
- internal-api/src/main/java/datadog/trace/api/Config.java
This resolves a circular dependency where `TPEHelper` depends on `Config` for a feature flag check, but `Config.<clinit>` depends on `Runtime.exec` to get the hostname, which depends on `ThreadPoolExecutor` which depends on `TPEHelper` once instrumented. All of this has been set up by the time `InstrumentationBasedProfiling`'s flag is flipped.
> Break potentially circular dependency between Config and TPEHelper

- dd-trace-core/build.gradle
- dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
- internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java
This PR changes the logic that publishes traces: if CI Visibility is enabled, the thread that does the publishing is not marked as daemon, and upon receiving an interrupt request the thread will wait up to 5 seconds to ensure all pending traces were published.
CI Visibility differs from production APM: when a customer shuts down a production service, it is acceptable for some operations that happened right before the shutdown to be missing in Datadog. When running tests, however, customers expect every executed test to be visible in Datadog. That means there's a need to wait until publishing is finished, even when all the tests have executed and JVM is ready to shut down.
> Wait for traces to be published before exiting if CI Visibility is enabled

- dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java/datadog/trace/instrumentation/couchbase_31/client/CoreEnvironmentBuilderAdvice.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java/datadog/trace/instrumentation/couchbase_31/client/CoreEnvironmentBuilderInstrumentation.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java/datadog/trace/instrumentation/couchbase_31/client/CoreInstrumentation.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java/datadog/trace/instrumentation/couchbase_31/client/DatadogRequestSpan.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java/datadog/trace/instrumentation/couchbase_31/client/DatadogRequestTracer.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java/datadog/trace/instrumentation/couchbase_31/client/SeedNodeHelper.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/test/groovy/CouchbaseClient31Test.groovy
- dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java/datadog/trace/instrumentation/couchbase_32/client/ConnectionStringHelper.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java/datadog/trace/instrumentation/couchbase_32/client/CoreEnvironmentBuilderAdvice.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java/datadog/trace/instrumentation/couchbase_32/client/CoreEnvironmentBuilderInstrumentation.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java/datadog/trace/instrumentation/couchbase_32/client/CoreInstrumentation.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java/datadog/trace/instrumentation/couchbase_32/client/DatadogRequestSpan.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java/datadog/trace/instrumentation/couchbase_32/client/DatadogRequestTracer.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java/datadog/trace/instrumentation/couchbase_32/client/SeedNodeHelper.java
- dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/test/groovy/CouchbaseClient32Test.groovy
- internal-api/src/main/java/datadog/trace/api/naming/v1/PeerServiceNamingV1.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InstrumentationTags.java
Extract the couchbase seed nodes information (provided as part of the connection string) under the tag `db.couchbase.seed.nodes`
> Couchbase 3.x: extract seed nodes info

- dd-java-agent/instrumentation/elasticsearch/src/main/java/datadog/trace/instrumentation/elasticsearch/ElasticsearchRestClientDecorator.java
- dd-java-agent/instrumentation/opensearch/src/main/java/datadog/trace/instrumentation/opensearch/OpensearchRestClientDecorator.java
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Adds a feature-flag to control tagging of search request body/parameters to the Elasticsearch & Opensearch instrumentations (default: enabled). Limits tagging of search request bodies to those below 25,000 characters.
Starting the Java trace agent with the JVM option `-Ddd.trace.elasticsearch.body-and-params.enabled=false` or setting `DD_TRACE_ELASTICSEARCH_BODY_AND_PARAMETERS_ENABLED=false` in the environment will disable the inclusion of body and params fields in Elasticsearch/Opensearch traces.
> Add feature-flag to control tagging of search request body/parameters

- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/api/DynamicConfig.java
This PR adds support for extending the type used to store snapshots of dynamic-config.
This lets us store more complex items alongside the dynamic-config they're derived from.
We want to dynamically configure the trace/span samplers. This PR means we can save the re-configured samplers, whose types are specific to `dd-trace-core`, alongside their related dynamic-config. This avoids the need for extra consistency checks whenever starting a new trace, since the dynamic-config and new samplers are contained in the same snapshot.
> Support extending dynamic-config snapshots

- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
Bump the default maximum remote config payload size to 5Mb.
`ASM_DATA` to block IPs has increased our expectations for remote config payload sizes. While there might be upcoming changes to have lighter payloads, bumping the RC payload size limit to 5Mb should be enough to keep up with the limits that are currently tested for all tracers.
Note that RC esponses are cached, so payloads this big should not be seen at every polling interval.
> Bump default max remote config payload size limit to 5Mb

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/UnvalidatedRedirectModuleImpl.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/UnvalidatedRedirectModuleTest.groovy
Not report unvalidated redirect vulnerability if all tainted object ranges have header Referer as source
Avoid unvalidated redirect false positives
> Unvalidated redirect not reported if Referer header is the source

- dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/HttpServletResponseInstrumentation.java
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaHttpServletResponseInstrumentation.java
Make method matchers in IAST instrumenter for servlet more precise. Avoids matching the wrong methods in Jetty.
Some unvalidated redirects were not detected in Jetty.
> Fix unvalidated redirect detection in Jetty

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/ASMHelper.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/instrumentation/ASMHelperTest.java
We introduced a helper method that require to provide the name of the class currently being transformed to ensure it is not the same. We also catch Throwable in transform method to ensure whatever happens during transformation we do not bubble up to the user code and load the original class
Loading a class during transformation/instrumentation MUST not be the current class being transformed otherwise a LinkageError happen with message "attempted duplicate class definition" because we have loaded the class before it was transformed, so when transformation finish the original load of the class is happening and boom!
> Ensure safe class loading in instrumentation

- .circleci/config.yml
Runs the `parametric` tests with the standard top level `run.sh` script.
DataDog/system-tests#1279 changed to using the top level `run.sh` for `parametric` tests as well as moved the test result files so they weren't added to CI.
> Run parametric tests with the standard runner

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/ExceptionHelper.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/ExceptionHelperTest.java
when trying access fields during capture/serialization and debug logs
> Fold stacktrace for exception

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/QueueTimerHelper.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/TPEHelper.java
- dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java
- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinPoolInstrumentation.java
- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java
- dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/ProfilingTestApplication.java
Tracks time spent in FJP queues and records it if a latency threshold is breached. Disabled by default, can be enabled with `-Ddd.profiling.experimental.queueing.time.enabled=true`
> track time in FJP shared queues

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteInstrumentation.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteTransformer.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/BaseCallSiteTest.groovy
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteInstrumentationTest.groovy
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteTransformerTest.groovy
- dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/callsite/HttpServlet3RequestCallSite.java
- dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/Servlet3TestGetParameterInstrumentation.groovy
- dd-java-agent/instrumentation/servlet/request-3/src/test/java/foo/bar/smoketest/HttpServlet3TestSuite.java
- dd-java-agent/instrumentation/servlet/request-3/src/test/java/foo/bar/smoketest/HttpServletWrapper3TestSuite.java
- dd-java-agent/instrumentation/servlet/request-3/src/test/java/foo/bar/smoketest/Servlet3TestSuite.java
- dd-java-agent/instrumentation/servlet/request-3/src/test/java/foo/bar/smoketest/ServletSuite.java
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaHttpServletRequestCallSite.java
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaHttpServletRequestInputStreamCallSite.java
- dd-java-agent/instrumentation/servlet/request-5/src/test/groovy/JakartaServletRequestCallSiteTest.groovy
- dd-java-agent/instrumentation/servlet/request-5/src/test/java/foo/bar/smoketest/JakartaHttpServletRequestTestSuite.java
- dd-java-agent/instrumentation/servlet/request-5/src/test/java/foo/bar/smoketest/JakartaHttpServletRequestWrapperTestSuite.java
- dd-java-agent/instrumentation/servlet/request-5/src/test/java/foo/bar/smoketest/JakartaServletRequestTestSuite.java
- dd-java-agent/instrumentation/servlet/request-5/src/test/java/foo/bar/smoketest/JakartaServletRequestWrapperTestSuite.java
- dd-java-agent/instrumentation/servlet/request-5/src/test/java/foo/bar/smoketest/ServletRequestTestSuite.java
- dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
- dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestInputStreamCallSite.java
- dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/ServletRequestCallSite.java
Separates call sites for `javax.servlet.ServletRequest` and `javax.servlet.http.HttpServletRequest` to prevent issues when classes are loaded in an OSGI environment.
A customer reported an exception during initialization:
```
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletRequest not found by security-connector-oauth2-client [328]
at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1585)
at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1970)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
... 78 more
```
The Apache Felix driven class loader of the instrumented class is only …
> Fix NoClassDefFoundError due to OSGI/servlet issues in IAST

- dd-java-agent/instrumentation/aws-lambda-handler/build.gradle
- dd-java-agent/instrumentation/aws-lambda-handler/src/main/java/datadog/trace/instrumentation/aws/v1/lambda/LambdaHandlerInstrumentation.java
- dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
- dd-trace-core/src/main/java/datadog/trace/lambda/ReadFromInputStreamJsonAdapter.java
- dd-trace-core/src/test/groovy/datadog/trace/lambda/LambdaHandlerTest.groovy
Prevent calling `start-invocation` and `end-invocation` on the aws lambda extension multiple times.
The lambda event needs to be serialized to json and shared with the extension. This event was properly serialized for the second wrapping, but not for the first. This means that once the extra handler wrapping is ignored, only one `aws.lambda` span is being created, but the lack of event json means we won't be able to create inferred spans or properly handle trace context.
The solution for this second problem is to add a new json adapter to serialize these types.
In the most recent version of the java tracing layer for aws lambda, the request handler is being wrapped at least twice.
```log
[dd.trace 2023-05-18 21:41:20:530 +0000] [main] DEBUG datadog.trace.agent.tooling.InstrumenterState - …
```
> Ensure lambda instrumentation only notifies extension once.

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/LineMap.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/instrumentation/LineMapTest.java
for loops generate 2 entries in LineNumberTable, 1 before the loop, 1 for the incrementation part. the second part was only kept into the line map (overwritten). We now always keep the first mapping.
> Fix inserting line probe before for-loops

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/SerializerWithLimits.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/MoshiSnapshotTestHelper.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot23.java
We are serializing then the enum constant name in the snapshot instead of handling enum as regular complex class
Enum in java are in fact regular classes with a special treatment by the java compiler. from the POV of the JVM there is no difference. From user perspective however it would be nice to have constant name as enum values.
> Add special support for enum values

- dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/TestApplicationHelper.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ServerDebuggerIntegrationTest.java
> Fix smoke tests

- .github/workflows/draft-release-notes-on-tag.yaml
Fix the changelog generation with the new GitHub label names.
> Update label detection

- gradle/dependencies.gradle
> Upgrade ddprof to 0.53.0 to unlink libgcc

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/StatsdMetricForwarder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/MetricProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot25.java
for gauge and histogram metric types
> Add support for double values for metric probes

- dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
- gradle/dependencies.gradle
- internal-api/src/main/java/datadog/trace/api/Config.java
On JDK versions where it's not safe to enable ddprof, override the user's config, and log that this has happened in the status logger.
> explicitly disable ddprof unsupported jdk versions

- communication/src/main/java/datadog/communication/monitor/DDAgentStatsDClient.java
- communication/src/main/java/datadog/communication/monitor/LoggingStatsDClient.java
- communication/src/test/groovy/datadog/communication/monitor/DDAgentStatsDClientTest.groovy
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/DebuggerMetrics.java
- dd-trace-core/src/test/groovy/datadog/trace/core/monitor/HealthMetricsTest.groovy
- internal-api/src/main/java/datadog/trace/api/NoOpStatsDClient.java
- internal-api/src/main/java/datadog/trace/api/StatsDClient.java
Allow to provide distribution metrics for Dynamic Instrumentation probes
> Add distribution metric for StatsDClient

- gradle/dependencies.gradle
Adds defensive buffer flushes to native code paths invoked since 1.15.0 (changes introduced in #5250 and #5251)
> uupgrade ddprof to 0.55.0

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/test/java/com/datadog/profiling/ddprof/DatadogProfilerTest.java
- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
Adds a configuration option to enable/disable the live heap size tracking
The live heap size tracking is using JVM internals and may rarely cause an issue in a particular environment.
We want the users to be able to disable the live heap size tracking without sacrificing the whole live heap profiling capability. 
When the tracking is disabled, the live heap size will be estimated from the statistical distribution of the collected samples instead - which is less precise but does not depend on JVM internals.
> Add a config to enable/disable live heap size tracking

- gradle/dependencies.gradle
Backports #5469 to release as v1.16.3
> upgrade ddprof to 0.55.0

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
Broken by previous class move.
> Fix scanDependencies CLI

- dd-smoke-tests/log-injection/src/test/groovy/datadog/smoketest/LogInjectionSmokeTest.groovy
The log inject test rely on a specific format to parse out log details from `stdout`. These are correlated with the log files generated by the logger.
Lines in `stdout` sometimes get merged together in a racy manner. The previous code handled the next line getting merged into the important line, but not vice versa. IE, it handled:
```
SECONDTRACEID 2799463272611004066 2799463272611004067[dd.trace 2023-06-26 19:26:17:127 +0000]next line of text
```
but not
```
[dd.trace 2023-06-26 19:26:17:127 +0000]previous linetextSECONDTRACEID 2799463272611004066 2799463272611004067
```
This lead to rare, but annoying, test failures.
> Fix source of flakiness in logs injection smoke test

- dd-smoke-tests/dynamic-config/src/test/groovy/datadog/smoketest/DynamicServiceMappingSmokeTest.groovy
- dd-smoke-tests/log-injection/src/test/groovy/datadog/smoketest/LogInjectionSmokeTest.groovy
- dd-trace-core/src/main/java/datadog/trace/core/TracingConfigPoller.java
- dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
`log_injection_enabled` instead of `logs_injection_enabled`
inside `tracing_service_mapping`...`from_key` instead of `from_name`
> Latest dynamic-config schema changes

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/StatsdMetricForwarder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/ASMHelper.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Types.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/MetricProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java
add a new kind of metric: Distribution that is already supported by DogStatsD, but was not exposed before to the tracer metric interface
> Add support for distribution metrics

- .github/workflows/draft-release-notes-on-tag.yaml
This should fix the release creation. It will also brings the capability of rerunning the action on an existing tag.
This step was not tested on repository to prevent creating test releases...
> fix: Fix release creation

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/MetricProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot25.java
byte, short, char and boolean are treated as int so we can handle them
in metric values
> Fix support for small type metric values

- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
- internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityTypes.java
Implements smoke tests for No SameSite and No HttpOnly cookie vulnerabilities. It also fixes the description string for NoSameSite cookie.
> Fix NoSameSiteCookie vulnerability name

- dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
- internal-api/src/main/java/datadog/trace/api/metrics/CoreCounter.java
- internal-api/src/main/java/datadog/trace/api/metrics/SpanMetricRegistry.java
- internal-api/src/main/java/datadog/trace/api/metrics/SpanMetricRegistryImpl.java
- internal-api/src/main/java/datadog/trace/api/metrics/SpanMetrics.java
- internal-api/src/main/java/datadog/trace/api/metrics/SpanMetricsImpl.java
- internal-api/src/main/java/datadog/trace/api/telemetry/CoreMetricCollector.java
- internal-api/src/main/java/datadog/trace/api/telemetry/MetricCollector.java
- internal-api/src/test/groovy/datadog/trace/api/metrics/SpanMetricRegistryTest.groovy
- internal-api/src/test/groovy/datadog/trace/api/telemetry/TelemetryCollectorsTest.groovy
- telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
- telemetry/src/main/java/datadog/telemetry/metric/CoreMetricsPeriodicAction.java
- telemetry/src/test/groovy/datadog/telemetry/metric/CoreMetricsPeriodActionTest.groovy
This PR introduces span metrics.
The first to metrics available are:
* Span created
* Span finish
Those metrics are connected to telemetry by a new core metrics collector and period action.
This PR is the second part of the Span Metrics PR https://github.com/DataDog/dd-trace-java/pull/5382
> Add span metrics

- dd-trace-core/src/main/java/datadog/trace/core/TracingConfigPoller.java
- dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
This fixes an issue seen during system-tests where the remote-config id may change between updates, leading to remote-config calling 'accept' for the new id before calling 'remove' for the old id.
> wait until the remote-config change is committed before deciding we didn't receive any dynamic-config overrides

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/KnownAddresses.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/data/KnownAddressesSpecification.groovy
Whenever we load the WAF, we issue a warning `WAF has rule against unknown address grpc.server.request.metadata`. This is not actionable: it is a known address, even if we don't support it yet.
> Remove warning about unknown grpc.server.request.metadata address

- .github/workflows/README.md
This PR adds a README about installed GitHub actions and their usage.
`create-next-milestone` action looks suspicious.
Should we clean the `gradle-wrapper-validation` action?
> Add GitHub actions documentation

- dd-java-agent/instrumentation/datastax-cassandra-4/src/main/java/datadog/trace/instrumentation/datastax/cassandra4/ContactPointsUtil.java
Tested as a real case, even if the contact points are a set, once mapped to a string representation, the guarantee of uniqueness is no more valid. Hence explicitly adding it.
Tested in a real situation, I got duplicates on this host list tag
> avoid having duplicates in db.cassandra.contact.points

- dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedContext.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TagContext.java
This PR will add diagnostic information to debug logs for context propagation investigation issues.
I had to address few context propagation issues the past weeks and it feels this kind of information will be helpful.
I don't think logging this kind of information will be problematic as they are send/receive from outside.
> Add context propagation diagnostic information to debug logs

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AdviceUtils.java
- dd-java-agent/agent-profiling/profiling-controller-ddprof/src/main/java/com/datadog/profiling/controller/ddprof/DatadogProfilerTimer.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/QueueTimeTracker.java
- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/TaskWrapperInstrumentation.java
- gradle/dependencies.gradle
* Makes the time threshold decision within the profiler, where we know the TSC frequency so can convert ticks to millis
* Makes application of context to queue time events implicit, which means we don't need to duplicate propagated information.
* Makes `CompletableFuture$AsyncSupply` and `CompletableFuture$AsyncRun` unwrappable so we can get back to the user's code to report as the task which waited in the queue.
> rework queue time profiling

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/TaskWrapper.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/TaskWrapperTest.groovy
- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/TaskWrapperInstrumentation.java
- dd-java-agent/instrumentation/java-concurrent/src/test/groovy/TaskWrapperTest.groovy
* Instruments some more concurrency carriers so they can be unwrapped to access the user-submitted task
* Increases the maximum depth of unwrapping from 3 to 5
* Adds some testing for the application of the instrumentation for key concurrency carrier types
> increase unwrapping depth, add new test

- buildSrc/build.gradle.kts
- buildSrc/call-site-instrumentation-plugin/build.gradle.kts
- dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
- dd-smoke-tests/vertx-3.4/application/gradle/wrapper/gradle-wrapper.properties
- dd-smoke-tests/vertx-3.9-resteasy/application/gradle/wrapper/gradle-wrapper.properties
- dd-smoke-tests/vertx-3.9/application/gradle/wrapper/gradle-wrapper.properties
- dd-smoke-tests/vertx-4.2/application/gradle/wrapper/gradle-wrapper.properties
- gradle/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
https://docs.gradle.org/8.2/release-notes.html
Note: `TestKit` dropped support for testing Gradle 2.6: https://github.com/gradle/gradle/pull/24891/files
> Gradle 8.2

- telemetry/src/main/java/datadog/telemetry/TelemetryService.java
- telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
Per the spec: the first time telemetry runs, only app-started is sent. Other messages start at the end of the first heartbeat interval.
> Telemetry app-heartbeat starts one interval after app-started

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkInstrumentation.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkTest.groovy
Instrument the `SparkSubmit.runMain(...)` function to capture all errors occurring in a spark application
This SparkSubmit class is used by spark to launch the application in non YARN/Mesos environnements. The YARN case is already covered by instrumenting the `ApplicationMaster.finish()` function (from this PR https://github.com/DataDog/dd-trace-java/pull/5267)
We are currently using the interface `SparkListener` to receive events from spark. However, this interface is only capturing errors that occur during the spark computations, but not in arbitrary user code
```scala
def main() = {
val spark = SparkSession.builder.getOrCreate()
val df = spark.read.parquet("...")
// Exception will be captured because it's happening during spark computations
df.map(x => new RuntimeException("Some …
```
> [Spark] Instrument SparkSubmit to capture errors outside of SparkListener interface

- dd-smoke-tests/spring-boot-3.0-native/application/build.gradle
Upgrade gradle `native-build-tools` to fix this issue: https://github.com/graalvm/native-build-tools/issues/359
https://github.com/DataDog/dd-trace-java-docker-build/commit/8821ea94e0aae0592341643ed38a2241eed259fc introduces a regression in `native-image` smoke tests.
> Fix GraalVM version detection

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
- dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java
- dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
- dd-trace-core/src/test/groovy/datadog/trace/core/datastreams/DefaultPathwayContextTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/PathwayContext.java
DSM will now use message timestamp to measure latency at the beginning on the pathway.
When the customer has consumer instrumented, but not producer they will see `0` as edge latency.  At the same time, most of the queueing tech have a way of injecting message timestamp, which shows the time when the message was produced. We want to use this timestamp if we can't calculate the latency in any other way.
Changes affect DSM only, in particular DSM instrumentation for Kafka and RabbitMQ.
> [DSM] - calculate edge latency using message timestamp

- dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/context/client/RmiClientContextInstrumentation.java
- dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/context/server/RmiServerContextInstrumentation.java
- dd-smoke-tests/spring-boot-3.0-native/build.gradle
Disable RMI client/server context instrumentation during native-image
* This instrumentation is no longer compatible with the latest native-image process 
Grant native-image process access to complete test environment, so it can see `DD_TRACE_METHODS`
* the latest GraalVM JDK only passes selected environment values onto the `native-image` process
* we use `NATIVE_IMAGE_DEPRECATED_BUILDER_SANITATION` to restore the old behaviour (no filtering)
* we could also have used a system property to pass the test `dd.trace.methods` setting to `native-image`
> Support native-image using latest GraalVM JDK

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintUtils.groovy
- dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringCallSite.java
- dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/StringCallSiteTest.groovy
- dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringSuite.java
- internal-api/src/main/java/datadog/trace/api/iast/propagation/StringModule.java
Adds callsites for propagation of `String.format`
> Add required callsites for String.format

- dd-java-agent/agent-jmxfetch/build.gradle
- gradle/dependencies.gradle
After this is merged be careful switching to old branches that predate this PR, because `git` does not automatically update submodules when switching branches.
I would recommend setting:
```
git config --local submodule.recurse true
```
for the `dd-trace-java` repository
Otherwise you will need to remember to add `--recurse-submodules` to `git checkout` when switching to old branches.
--------
https://github.com/DataDog/jmxfetch/releases/tag/0.47.9
https://github.com/DataDog/java-dogstatsd-client/releases/tag/v4.2.0
This PR also updates the `dd-java-agent/agent-jmxfetch/integrations-core` submodule from 7.19.0 to 7.45.0
New metrics configs:
* hazelcast.yaml
* hivemq.yaml
* hudi.yaml
* ignite.yaml
* sonarqube.yaml
* weblogic.yaml
Updated metrics configs:
* activemq.yaml
* cassandra.yaml
* …
> JMXFetch 0.47.9 + DogStatsD 4.2.0

- dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleBuildListenerInstrumentation.java
- dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleProjectConfigurator.groovy
- dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
Stabilises Gradle Daemon smoke test which is currently flaky.
Gradle itself and project dependencies cannot be downloaded sometimes because of intermittent network problems
This is addressed by repeatedly running a "warmup build" (that triggers downloading Gradle and project dependencies) before starting the build with the tracer. The warmup build is run up to five times until either downloading is successful, or all attempts have been exhausted.
Reduce test flakiness.
Warmup build runs in "dependency verification" mode in order to trigger downloading of all dependencies.
Component that automatically configures instrumented project with DD Javac Plugin and Jacoco plugin was updated to disable verification for corresponding dependencies.
> Stabilise flaky Gradle smoke test 

- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/TaskUnwrappingInstrumentation.java
- dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
- dd-java-agent/instrumentation/java-concurrent/src/test/groovy/TaskUnwrappingForkedTest.groovy
- dd-java-agent/instrumentation/netty-concurrent-4/src/main/java/datadog/trace/instrumentation/netty40/concurrent/SingleThreadEventExecutorInstrumentation.java
- dd-java-agent/instrumentation/netty-concurrent-4/src/test/groovy/TimingTest.groovy
This minimises the footprint from queue time instrumentation unless the feature is enabled
> disable queue time instrumentations unless feature enabled

- dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleBuildListener.java
- dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleBuildListenerInstrumentation.java
- dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleProjectConfigurator.groovy
- dd-smoke-tests/gradle/build.gradle
- dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
Implements Intelligent Test Runner in Gradle builds.
Parent process (Gradle) requests remote settings (code coverage enabled, intelligent test runner enabled), and the list of skippable tests from the backend. Then the settings and the skippable tests are propagated to the children processes (JVMs forked to run tests).
Intelligent Test Runner is a feature of CI Visibility product.
Request for settings and skippable tests must include JVM executable details.
It is possible to use multiple JVMs during the build (e.g. some tests are run with Java 8, while others are run with Java 11).
Calculating the list of skippable tests is an expensive operation, therefore in order to make as few requests as possible, first all the Gradle test tasks are grouped by the JVM that they use, then a single …
> Implement ITR skippable tests request for Gradle

- dd-java-agent/agent-bootstrap/build.gradle
- dd-java-agent/agent-bootstrap/src/jmh/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecoratorBenchmark.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecorator.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecoratorTest.groovy
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecoratorTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
- internal-api/src/main/java/datadog/trace/api/normalize/SimpleHttpPathNormalizer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/URIUtils.java
- internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/URIUtilsTest.groovy
Optimizes some of the code called by `HttpServerDecorator.onRequest`, by making String creation lazy and reusing information that exists in the `HttpServerDecorator` when doing processing in the `TagInterceptor`.
Path normalization and re-added URL parsing has introduced unnecessary overhead.
```
Base
HttpServerDecoratorBenchmark                               (url)  Mode  Cnt     Score    Error   Units
onRequest                       https://foo.bar:4711/normal/path  avgt    4     0.124 ±  0.002   us/op
onRequest:·gc.alloc.rate.norm   https://foo.bar:4711/normal/path  avgt    4   304.000 ±  0.001    B/op
onRequest                       https://foo.bar:4711/numb3r/path  avgt    4     0.127 ±  0.002   us/op
onRequest:·gc.alloc.rate.norm   https://foo.bar:4711/numb3r/path  avgt    4 …
```
> Speed up HttpServerDecorator onRequest

- .github/workflows/README.md
- .github/workflows/lib-injection-prune-registry.yaml
This PR introduces GitHub workflow to clean up GitHub container registry from lib-injection docker images.
`lib-injection` produces nearly 2k docker images per week. This should cut our costs on GH storage.
I spent few days to clean up GHCR first and removed two others unused packages (`dd-java-agent` and `dd-trace-java`).
> Clean up lib-injection docker images

- telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java
- telemetry/src/test/groovy/datadog/telemetry/TelemetryRunnableSpecification.groovy
- telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
* Compute the deadline to next telemetry action based on incrementing the previous deadline (rather than based on the current time). This should ensure that telemetry intervals do not drift as long as they do not take longer than the interval itself.
* If heartbeat interval is exceeded (can happen with a faulty network), start the next interval immediately, and reset the interval deadlines.
* If metrics interval is exceed (should not happen except, perhaps, under extreme load), skip one interval.
Mitigate telemetry interval drift.
> Mitigate telemetry interval drift

- communication/src/main/java/datadog/communication/ddagent/ExternalAgentLauncher.java
- internal-api/src/main/java/datadog/trace/util/ProcessSupervisor.java
Refactors `ProcessSupervisor` so we can provide more detailed health-checks to decide when to spawn external agent processes on Azure. Note this feature is not used yet in this PR, this is preparing the ground and making the process supervision more robust.
Other improvements:
* Automatically discard output from the external processes. We're not interested in this output and discarding it means we don't have to have additional threads consuming the output. It also avoids a potential issue where the external process could get stuck if nothing is consuming the output.
* Waits a short time for the supervisor thread to stop, giving it a chance to destroy the child process.
* If the original call to `destroy` doesn't stop the child process then try `destroyForcibly`
* Use a shorter delay when …
> Improve external agent process supervision on Azure

- dd-java-agent/agent-ci-visibility/build.gradle
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilitySystem.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestModuleImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestSessionImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/TestModuleRegistry.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/BuildEventsHandlerImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestEventsHandlerImpl.java
- dd-java-agent/agent-ci-visibility/src/testFixtures/groovy/datadog/trace/civisibility/CiVisibilityTest.groovy
- dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleBuildListener.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/TracingListener.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/TracingListener.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenExecutionListener.java
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TracingListener.java
- dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
- dd-trace-api/src/main/java/datadog/trace/api/civisibility/DDTestModule.java
- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/api/civisibility/events/BuildEventsHandler.java
- internal-api/src/main/java/datadog/trace/api/civisibility/events/TestEventsHandler.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java
Implements passing tests execution results from children processes (JVMs forked to run tests) to the parent process (Gradle or Maven).
The overall execution result (success or failure) is already available in the parent process, but for CI Visibility there's a need to pass more data (such as whether the tests were executed with code coverage, or if any of the test cases were skipped by Intelligent Test Runner).
The data is passed via TCP using `SignalServer` and`SignalClient` introduced for this purpose previously (in a separate PR).
> Implement passing module execution results from children processes to parent process

- internal-api/src/main/java/datadog/trace/api/naming/v1/DatabaseNamingV1.java
Updates (similarly to elasticsearch) naming conventions for op names in v1 for opensearch
> opensearch: naming conventions for v1

- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/ItrFilter.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnit5Instrumentation.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnit5ItrInstrumentation.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnit5Utils.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/TestFrameworkUtils.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/TracingListener.java
- dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
- dd-java-agent/instrumentation/junit-5.3/src/test/groovy/SpockTest.groovy
Implements Intelligent Test Runner for JUnit 5: framework instrumentation is updated to skip test cases that were marked as skippable by the backend.
Intelligent Test Runner is a CI Visibility feature that allows skipping tests that are not relevant for a specific commit.
Requesting the list of skippable tests from the backend and passing it to JVM running the tests was implemented previously in a separate PR.
The changes in this PR simply use the already available list of skippable tests.
> Implement tests skipping for JUnit 5

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestEventsHandlerImpl.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/ItrFilter.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Instrumentation.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4ItrInstrumentation.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4SuiteEventsInstrumentation.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Utils.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/SkippedByItr.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/TracingListener.java
- dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
- internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java
Implements Intelligent Test Runner for JUnit 4: framework instrumentation is updated to skip test cases that were marked as skippable by the backend.
Intelligent Test Runner is a CI Visibility feature that allows skipping tests that are not relevant for a specific commit.
Requesting the list of skippable tests from the backend and passing it to JVM running the tests was implemented previously in a separate PR.
The changes in this PR simply use the already available list of skippable tests.
> Implement tests skipping for JUnit 4

- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/ItrFilter.java
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGInstrumentation.java
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGItrInstrumentation.java
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGUtils.java
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TracingListener.java
- dd-java-agent/instrumentation/testng/src/testFixtures/groovy/datadog/trace/instrumentation/testng/TestNGTest.groovy
Implements Intelligent Test Runner for TestNG: framework instrumentation is updated to skip test cases that were marked as skippable by the backend.
Intelligent Test Runner is a CI Visibility feature that allows skipping tests that are not relevant for a specific commit.
Requesting the list of skippable tests from the backend and passing it to JVM running the tests was implemented previously in a separate PR.
The changes in this PR simply use the already available list of skippable tests.
> Implement tests skipping for TestNG

- dd-java-agent/instrumentation/jetty-11/src/main/java11/datadog/trace/instrumentation/jetty11/JettyServerAdvice.java
- dd-java-agent/instrumentation/jetty-7.0/src/main/java/datadog/trace/instrumentation/jetty70/JettyServerInstrumentation.java
- dd-java-agent/instrumentation/jetty-7.6/src/main/java/datadog/trace/instrumentation/jetty76/JettyServerInstrumentation.java
- dd-java-agent/instrumentation/jetty-9/src/main/java/datadog/trace/instrumentation/jetty9/JettyServerInstrumentation.java
- dd-java-agent/instrumentation/liberty-20/src/main/java/datadog/trace/instrumentation/liberty20/LibertyServerInstrumentation.java
- dd-java-agent/instrumentation/play-2.3/src/main/java/datadog/trace/instrumentation/play23/PlayAdvice.java
- dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play24/PlayAdvice.java
- dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/PlayAdvice.java
- dd-java-agent/instrumentation/restlet-2.2/src/main/java/datadog/trace/instrumentation/restlet/RestletInstrumentation.java
- dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
- dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
- dd-java-agent/instrumentation/spray-1.3/src/main/scala/datadog/trace/instrumentation/spray/SprayHttpServerRunSealedRouteAdvice.java
- dd-java-agent/instrumentation/synapse-3/src/main/java/datadog/trace/instrumentation/synapse3/SynapseServerInstrumentation.java
- dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatServerInstrumentation.java
- dd-java-agent/instrumentation/undertow/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/HandlerInstrumentation.java
- dd-java-agent/instrumentation/undertow/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/HttpRequestParserInstrumentation.java
This means that any tracing latency overhead can be explained by the profiler, which helps users understand request latency
> activate spans before calling decorators

- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
This reduces the default number of direct allocations we will unwind the stack for in a 60s recording when a user enables direct allocation profiling, because the overhead of the unwinding can be quite high.
> reduce direct allocation profiling rate limit

- dd-java-agent/agent-ci-visibility/build.gradle
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/RepoIndexSourcePathResolver.java
We noticed that _sometimes_ `@test.source.file` and therefore `@test.codeowners` fields are not set. It looks like it's related to the `currentSourceRoot` field is not being updated while visiting subdirectories.
https://github.com/DataDog/dd-trace-java/blob/de6aaed8c3392035b1e1265312be64974bf4b275/dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/RepoIndexSourcePathResolver.java#L267-L268
In some cases, the repo index has only one source root.
```
Indexing took 1227 ms ... source roots found: 1
```
I suspect we set `currentSourceRoot` to the repo root folder and it never became `null` until we visit all directories and files. https://github.com/DataDog/dd-trace-java/blob/de6aaed8c3392035b1e1265312be64974bf4b275/dd-java-agent/agent-ci-visibility/src/main/jav …
> Fix incorrect current source root in `RepoIndexSourcePathResolver`

- gradle/dependencies.gradle
* Fixes for cases where users modify `/proc/sys/kernel/pid_max` at runtime
* Adds execution state labels to samples (Java vs JVM vs Native etc.)
> Upgrade ddprof to 0.63.0

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
- dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
- internal-api/src/main/java/datadog/trace/api/DynamicConfig.java
- internal-api/src/main/java/datadog/trace/api/TraceConfig.java
- internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
- internal-api/src/main/java/datadog/trace/util/Strings.java
- utils/test-utils/src/main/groovy/datadog/trace/test/util/DDSpecification.groovy
Apply the same `http.request.headers.<header>` and `http.response.headers.<header>` default tag names to header tags configured via dynamic-config as we currently apply to the static-config. These default tag names are only used when no tag name is provided in the header tag mapping.
This PR also updates `AgentTestRunner` to rebuild the test tracer's dynamic-config when it rebuilds the static-config.
> Apply default tag name when setting header tags via dynamic-config

- dd-java-agent/agent-ci-visibility/build.gradle
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestSessionImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/TestModuleRegistry.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/AckResponse.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/ChannelContext.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/ErrorResponse.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/ModuleExecutionResult.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/SignalClient.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/SignalResponse.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/SignalServer.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/SignalServerRunnable.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/SignalType.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ipc/ChannelContextTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ipc/SignalServerTest.groovy
Updates `SignalServer` and `SignalClient` adding possibility of sending a response from the server to the client.
Clients (child processes - JVMs running tests) need to receive data from the server (parent process - build system): list of skippable tests, repository index, etc.
> Update signal server and client with mechanism to send/receive signal responses

- .gitlab/exploration-tests.yml
- dd-java-agent/agent-debugger/exploration-tests/Dockerfile.exploration-tests
- dd-java-agent/agent-debugger/exploration-tests/exclude.txt
- dd-java-agent/agent-debugger/exploration-tests/exclude_jackson-databind.txt
- dd-java-agent/agent-debugger/exploration-tests/run-exploration-tests.sh
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SnapshotSink.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Introduced multiple exclude files for known issue with some classes one exclude file general, and one specific per project. If an instrumentation error is detected it is reported into instrumentation.log file that is tested at the end of the job for indicating if a failure occurred.
> Fix exploration tests

- .circleci/config.yml
Add the INTEGRATIONS scenario from System Tests to the Java Tracer's CI.
Enabling INTEGRATIONS scenario allow us to catch potential breakages to integrations early for future PRs.
> Add INTEGRATIONS system tests to Java Tracer CI

- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenExecutionListener.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenLifecycleParticipant.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenUtils.java
Adds support for instrumenting `tycho-surefire-plugin` in Maven builds.
When a Maven build is run with the tracer attached, `tycho-surefire-plugin` executions are identified and their configuration is updated so that the JVMs that are forked by the plugin also run with the tracer attached (similar to the way this is already done for standard Surefire and Failsafe plugins).
`tycho-surefire-plugin` is an alternative to standard Surefire and Failsafe plugins that is used for testing Eclipse plugins.
There are CI Visibility customers that are using this plugin and would like to have visibility into tests that are run with it.
> Add support for tycho-surefire-plugin instrumentation in Maven builds

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestDescriptor.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestEventsHandlerImpl.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/TracingListener.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/TracingListener.java
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TracingListener.java
- dd-java-agent/instrumentation/testng/src/testFixtures/groovy/datadog/trace/instrumentation/testng/TestNGTest.groovy
- internal-api/src/main/java/datadog/trace/api/civisibility/events/TestEventsHandler.java
Updates TestNG instrumentation to correctly handle scenarios where the same test case is executed concurrently from multiple threads.
It is possible to create a TestNG XML configuration that will have the same test case included in multiple "tests".
In its simplest form such configuration will look like this:
```
<suite name="API Test Suite" configfailurepolicy="continue">
<test name="Test A">
<classes>
<class name="org.example.TestSucceed">
<methods>
<include name="test_succeed"/>
</methods>
</class>
</classes>
</test>
<test name="Test B">
<classes>
<class name="org.example.TestSucceed">
<methods>
<include name="test_succeed"/>
</methods>
</class>
</classes>
</test>
</suite>
```
It is then possible to set `parallel="tests"` attribute on the suite, which will result in two test cases …
> Update TestNG instrumentation to differentiate between identical test cases executed concurrently

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpan.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpanBuilder.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
This PR fixes empty string as OpenTelemetry Span attribute values.
Empty string attribute values are [meaningful for OpenTelemetry](https://opentelemetry.io/docs/specs/otel/common/#attribute):
> Attribute values expressing a numerical value of zero, an empty string, or an empty array are considered meaningful and MUST be stored and passed on to processors / exporters.
It also:
* Restore the related broken unit tests
* Remove previous work-around (based on `setAttributes()` method)
* Add tag key null check
Fix the OpenTelemetry API instrumentation behavior.
> Fix empty string attribute value

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/PropagationModuleTest.groovy
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/iast/helpers/TaintRequestContextFunction.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/iast/helpers/TaintRequestFunction.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/iast/helpers/TaintUnmarshaller.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/iast/helpers/TaintUriFunction.java
- dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/InboundMessageContextInstrumentation.java
- dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/ReaderInterceptorExecutorInstrumentation.java
- dd-java-agent/instrumentation/jose-jwt/src/main/java/datadog/trace/instrumentation/josejwt/JSONObjectUtilsInstrumentation.java
- dd-java-agent/instrumentation/jose-jwt/src/main/java/datadog/trace/instrumentation/josejwt/JWTParserInstrumentation.java
- dd-java-agent/instrumentation/jose-jwt/src/test/groovy/JWTParserInstrumentationTest.groovy
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaHttpServletRequestInputStreamCallSite.java
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaServletRequestCallSite.java
- dd-java-agent/instrumentation/servlet/request-5/src/test/groovy/JakartaServletRequestCallSiteTest.groovy
- dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
- dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestInputStreamCallSite.java
- dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/ServletRequestCallSite.java
- dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletRequestCallSiteTest.groovy
- dd-java-agent/instrumentation/servlet/src/test/groovy/ServletRequestCallSiteTest.groovy
- dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/TaintFluxElementsFunction.java
- dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/TaintGetBodyAdvice.java
- dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/core/AbstractHttpServerRequestInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/core/Http2ServerRequestInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/core/HttpServerRequestInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/IastRoutingContextImplInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/IastSourceTest.groovy
- dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/core/AbstractHttpServerRequestInstrumentation.java
- internal-api/src/main/java/datadog/trace/api/iast/propagation/PropagationModule.java
Use `taintObject` (single `Object`) and `taintObjects` (array or collection of `Object`) to taint non-Strings.
* Too many overloads for `taint`, sometimes leading to calls to the incorrect versions.
* It is easy to call a taint method that is meant for non-Strings (and does not handle range sizes for strings appropriately).
* Avoid some unnecessary work at runtime when these are called with single objects (most calls).
> Clearer API to taint non-Strings

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestModuleImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestSuiteImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestEventsHandlerImpl.java
- dd-java-agent/agent-ci-visibility/src/testFixtures/groovy/datadog/trace/civisibility/CiVisibilityTest.groovy
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/TracingListener.java
- dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/TracingListener.java
- dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
- dd-java-agent/instrumentation/junit-5.3/src/test/groovy/SpockTest.groovy
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TracingListener.java
- dd-java-agent/instrumentation/testng/src/testFixtures/groovy/datadog/trace/instrumentation/testng/TestNGTest.groovy
- internal-api/src/main/java/datadog/trace/api/civisibility/events/TestEventsHandler.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java
Adds `test.source.method` tag to each test span. The tag contains concatenation of test method name and method descriptor.
Adds `test.source.class` tag that contains test class. This tag is only set if the contents of existing `test.suite` tag do not match class name (should be a very rare case when Manual API is used and test suite is set to something other than test class name).
The new tags are needed in order to identify Java method that corresponds to a test case.
More details can be found in the [RFC](https://docs.google.com/document/d/1MACBTUmRfWoFpjYiu9RQ8CgytdU0zFPb0Xdc_9UHBq0/edit).
> Tag test spans with method description

- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGInstrumentation.java
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGUtils.java
- dd-java-agent/instrumentation/testng/testng-6.4/src/test/groovy/TestNG64Test.groovy
Supports test framework version extraction for older TestNG verisons.
Each test span should be tagged with test framework version according to CI Visibility spec.
> Support test framework version extraction for legacy TestNG

- dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/JfpUtils.java
- dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/resources/jfr/safepoints.jfp
- dd-java-agent/agent-profiling/profiling-controller-jfr/src/test/java/com/datadog/profiling/controller/jfr/JfpUtilsTest.java
- dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/TaskUnwrappingInstrumentation.java
- dd-java-agent/instrumentation/java-directbytebuffer/src/main/java/datadog/trace/instrumentation/directbytebuffer/ByteBufferInstrumentation.java
- dd-java-agent/instrumentation/java-directbytebuffer/src/main/java/datadog/trace/instrumentation/directbytebuffer/DirectByteBufferInstrumentation.java
- dd-java-agent/instrumentation/java-directbytebuffer/src/main/java/datadog/trace/instrumentation/directbytebuffer/FileChannelImplInstrumentation.java
- dd-java-agent/instrumentation/java-directbytebuffer/src/test/groovy/DirectAllocationTrackingTest.groovy
- dd-java-agent/instrumentation/netty-concurrent-4/src/main/java/datadog/trace/instrumentation/netty40/concurrent/SingleThreadEventExecutorInstrumentation.java
- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
* Introduces an ultra minimal mode: it just traces safepoints and only the CPU profiler will be enabled. All profiling instrumentation is disabled in this mode. The motivation is profiling middleware and users are discouraged from enabling this mode because it doesn't collect much information.
* Wallclock profiler automatically disabled whenever tracing is disabled, because without tracing no threads are sampled anyway. The motivation is to avoid starting the wallclock sampler thread unnecessarily.
* DD allocation profiling controlled by `dd.profiling.allocation.enabled` unless the user explicitly opts in with `dd.profiling.ddprof.alloc.enabled` which is now deprecated. The motivation is the user should not need to know to which allocation profiler is enabled, and once the new allocation …
> profiler config ergonomics improvements

- dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
- dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/TraceConfigExitWatcher.java
Stops the embedded JMXFetch instance when dynamic-config disables runtime metrics.
The JMXFetch thread will then poll the dynamic-config until runtime metrics are re-enabled.
Assumes JMXFetch starts enabled in static config, otherwise the necessary hooks will not be in place to (re)enable it later.
> Enable/disable embedded JMXFetch with dynamic config

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/ASMHelper.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/MoshiSnapshotTestHelper.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot19.java
Capture static fields in dedicated section in snapshots. Static final fields are not captured.
Only static fields of the class of the instrumented methods are captured, not for every instance.
> Add capture of static fields

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecorator.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecoratorTest.groovy
Avoids a potential exception if the status retrieved by an instrumentation was ever negative.
> Only check CLIENT/SERVER_ERROR_STATUSES when we know we have a status to check

- .gitlab-ci.yml
Adds the commit short sha to downstream pipelines.
For versioning artefacts in di backend.
> Add commit short sha to variables passed down to di backend

- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TracingListener.java
Fixes two issues in TestNG instrumentation:
* `ITestResult.getName()` is used for test case names instead of `ITestResult.getTestName()`: the latter is mutable - if a customer modifies test name during execution (for instance, using TestNG event hooks), the same test might have a different name on start and on finish, which breaks CI Vis logic
* Entire `ITestResult` is used as test qualifier instead of `ITestResult.getTestContext().getName()`: it is possible to have test cases with the same test case name in the same TestNG Test (for instance, if the test class overrides `ITest` and supplies the same name for each of its test case methods)
If these issues are not addressed, it is not always possible to look up the correct test span when test finish event is triggered in TestNG
> Fix TestNG instrumentation to use immutable ITestResult.getName() instead of mutable ITestResult.getTestName()

- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenExecutionListener.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenLifecycleParticipant.java
- dd-java-agent/instrumentation/maven-3.2.1/src/test/groovy/MavenTest.groovy
- dd-java-agent/instrumentation/maven-3.2.1/src/test/resources/test_maven_build_with_tests_in_multiple_modules_run_in_parallel_generates_spans/module-a/pom.xml
- dd-java-agent/instrumentation/maven-3.2.1/src/test/resources/test_maven_build_with_tests_in_multiple_modules_run_in_parallel_generates_spans/module-a/src/test/java/com/example/TestSucceed.java
- dd-java-agent/instrumentation/maven-3.2.1/src/test/resources/test_maven_build_with_tests_in_multiple_modules_run_in_parallel_generates_spans/module-b/pom.xml
- dd-java-agent/instrumentation/maven-3.2.1/src/test/resources/test_maven_build_with_tests_in_multiple_modules_run_in_parallel_generates_spans/module-b/src/test/java/com/example/TestSucceed.java
- dd-java-agent/instrumentation/maven-3.2.1/src/test/resources/test_maven_build_with_tests_in_multiple_modules_run_in_parallel_generates_spans/pom.xml
Changes Maven test session key from `MavenSession` to `MavenExecutionRequest`.
CI Visibility has a registry of currently executed builds.
Test session key is used to lookup a build in the registry.
The key has to be immutable and has to uniquely identify its corresponding build.
When a Maven build is executed in parallel mode (`-T N` arg), different threads will have different `MavenSession` instance associated with them, even though they service the same build.
Because of that `MavenSession` is not a suitable test session key.
There is a one-to-one relationship between the build and `MavenExecutionRequest` instance, so the latter is a suitable session key.
> Fix Maven instrumentation for parallel builds

- dd-java-agent/agent-ci-visibility/build.gradle
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestModuleChild.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestModuleImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestModuleParent.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestSessionImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/context/ParentProcessTestContext.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestEventsHandlerImpl.java
Splits `DDTestModuleImpl` class into two different classes: one that is used in the parent process (build system) and the other that is used in the child process (JVM forked to run tests).
Test module tracking logic differs based on which process the tracer is attached to: when build system is instrumented, module span is created in the build system process, and module abstraction in the child process is used only for accumulating execution results and reporting them to the parent process.
Before this change `DDTestModuleImpl` class hosted both the parent and the child logic.
Splitting the class in two results in code that is easier to understand and maintain.
> Split DDTestModuleImpl into parent process and child process implementations

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
This minor PR updates the existing test cases to ensure the current beharior: spans generated from OpenTelemetry instrumentation should have their operation name and resource name set with the OpenTelemetry span name.
Ensure consistant behavior between tracer implementations.
> Add OpenTelemetry span name tests

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkAggregatedTaskMetrics.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkListenerTest.groovy
Before this PR, the peak execution memory was summed across all stages, which did not made much sense. Using the max will correctly reflect the peak execution memory for the whole job / application
> [Spark] Aggregate peak execution memory using the max of all stages

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ReflectiveFieldValueResolver.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/ASMHelper.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot19.java
lookup for inherited (static) fields and capture them to be able evaluate expressions on it.
Inherited instance fields were captured through `this`, but evaluation required to capture them with `CapturedContext::addFields`
Capture instance & static inherited fields
> Add capture of inherited (static) fields

- internal-api/src/main/java/datadog/trace/api/metrics/SpanMetricsImpl.java
- internal-api/src/test/groovy/datadog/trace/api/telemetry/TelemetryCollectorsTest.groovy
- telemetry/src/test/groovy/datadog/telemetry/metric/CoreMetricsPeriodActionTest.groovy
This PR fixes the metric names for created and finished spans.
This span metric names changes from the RFC to comply with _telemetry naming conventions_.
> Fix span metric names

- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DBMCompatibleConnectionInstrumentation.java
- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
This PR adds IBM Informix to JBDC instrumentation.
A customer asked for supporting this database and tested the change using `dd.trace.jdbc.connection.class.name=com.informix.jdbc.IfmxConnection` and `dd.trace.jdbc.prepared.statement.class.name=com.informix.jdbc.IfxPreparedStatement` properties.
> Add IBM Informix support to JDBC instrumentation

- dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanLink.java
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpanLink.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/SpanLink.java
This PR introduce span links features.
It allows linking spans to each others. Linked spans do not have to be part of the same trace.
Span links feature will help to implement OpenTelemetry span links.
OpenTelemetry span link feature is coming in another PR to ease code review.
> Add span links support

- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ipc/ChannelContextTest.groovy
This PR marks a ci-visibility test as flaky.
This should improve CI stability.
I opened an issue related to this PR: #5618
> Mark ci-visibility test as flaky

- dd-java-agent/instrumentation/spark/build.gradle
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkAggregatedTaskMetrics.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkListenerTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- dd-trace-core/src/main/java/datadog/trace/common/metrics/AggregateMetric.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/datastreams/StatsGroup.java
- dd-trace-core/src/main/java/datadog/trace/core/histogram/Histogram.java
- dd-trace-core/src/main/java/datadog/trace/core/histogram/Histograms.java
- dd-trace-core/src/main/java/datadog/trace/core/monitor/Timer.java
- dd-trace-core/src/test/groovy/datadog/trace/core/histogram/HistogramsTest.groovy
- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentHistogram.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
- Expose a new tracer interface `AgentHistogram` backed by a DDSketch, that can be used inside an instrumentation
- Use a `LogarithmicMapping` since it is the mapping supported by the most languages, with a relative error of 3%
- Serialize the DDSketch and encode it in base64 to add it as an hidden span tag
Using a total of 6 histogram to capture the most important spark metrics. For most of the stages, only 3 histograms will contain non-zero values (stages generally only have either input/output or shuffle read/write)
- Duration
- Input bytes
- Output bytes
- Shuffle Read bytes
- Shuffle Write bytes
- Spill
Added the histogram behind the feature flag `-Ddd.spark.task-histogram.enabled` (or `DD_SPARK_TASK_HISTOGRAM_ENABLED`). It is enabled by default, but can be disabled if histograms are …
> [Spark] Compute distribution of task metrics for each stage

- dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
Do not exclude generated JSPs from instrumentation in IAST
> Update IAST exclusions to not filter JSPs and hdiv related classes

- dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/TraceConfigExitWatcher.java
- dd-java-agent/instrumentation/jboss-logmanager/src/main/java/datadog/trace/instrumentation/jbosslogmanager/LoggerNodeInstrumentation.java
- dd-java-agent/instrumentation/log4j-2.7/src/main/java/datadog/trace/instrumentation/log4j27/SpanDecoratingContextDataInjector.java
- dd-java-agent/instrumentation/log4j1/src/main/java/datadog/trace/instrumentation/log4j1/CategoryInstrumentation.java
- dd-java-agent/instrumentation/logback-1/src/main/java/datadog/trace/instrumentation/logback/LogbackLoggerInstrumentation.java
- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/api/DynamicConfig.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
* Introduce `NoopTraceConfig` for when there is no tracer
* Remove redundant null-checks to simplify the code
> Refactor dynamic-config internals to be more null-safe

- dd-java-agent/agent-debugger/build.gradle
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
Change the way we construct our `OkHttpClient` in Dynamic Instrumentation to match the way it is constructed in Profiling.
At the moment, Dynamic Instrumentation does not work in environment where the tracer is configured to use UDS (e.g. k8s with the Admissions Controller where [the configuration](https://docs.datadoghq.com/containers/cluster_agent/admission_controller/?tab=operator#configure-apm-and-dogstatsd-communication-mode) for `admission_controller.inject_config.mode` or `admission.datadoghq.com/config.mode` is set to `socket`).
System tests will be added in a separate PR.
> Add UDS support for the debugger by using `OkHttpUtils.buildHttpClient`

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkConfAllowList.java
Adding those 4 spark parameters to the list that are captured since they are quite important
|                                   |                                                                                                                               |
|-----------------------------------|-------------------------------------------------------------------------------------------------------------------------------|
| spark.default.parallelism         | Default number of partitions in RDDs returned by transformations like join, reduceByKey, and parallelize when not set by user |
| spark.executor.instances          | Number of executors when not using dynamic allocation                                                                         |
| spark.files.maxPartitionBytes     | The …
> Capture more Spark parameters

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestModuleChild.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestModuleImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestModuleParent.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestSessionImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/TestModuleRegistry.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/ModuleExecutionResult.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ipc/ModuleExecutionResultTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ipc/SignalServerTest.groovy
- dd-java-agent/agent-ci-visibility/src/testFixtures/groovy/datadog/trace/civisibility/CiVisibilityTest.groovy
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/SkippedByItr.java
- dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnit5ItrInstrumentation.java
- dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
- dd-java-agent/instrumentation/junit-5.3/src/test/groovy/SpockTest.groovy
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGItrInstrumentation.java
- dd-java-agent/instrumentation/testng/src/testFixtures/groovy/datadog/trace/instrumentation/testng/TestNGTest.groovy
- dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
- dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
- internal-api/src/main/java/datadog/trace/api/civisibility/InstrumentationBridge.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java
Adds ITR (Intelligent Test Runner) metadata tags to test session and test module spans:
* `test.itr.tests_skipping.type`: `"test"` - to indicate that Java tracer skips individual test cases when ITR is enabled
* `test.itr.tests_skipping.count`: `number` - to tell how many test cases were skipped in a given session / module
And to test spans:
`test.skipped_by_itr`: `true` - if the test was skipped by ITR
The tracer needs to provide this info so that it could be displayed to the customers in the UI.
More details can be found in the [RFC](https://docs.google.com/document/d/105YXO2r2hQqwkbEgKOoO8MuT2OAawa5Wh8PwujJC9LY/edit).
> Implement Intelligent Test Runner metadata tags

- dd-java-agent/build.gradle
- gradle/dependencies.gradle
The profiler now statically links libstdc++ so can be loaded on more platforms.
> Upgrade to ddprof 0.67.0

- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageProducerInstrumentation.java
When sending JMS messages over SQS we already store the trace context in 'X-Amzn-Trace-Id' / 'AWSTraceHeader',
so we can skip storing the same context as JMS message properties.
Avoids a potential issue where adding JMS message properties might exceed the SQS limit of 10 attributes per message.
One alternative approach would be to instrument `SQSMessage` (which implements the JMS message API) and filter out setting of any trace context related properties.
Alternatively we could instrument the `propertyToMessageAttribute` method in `SQSMessageProducer` which copies the JMS message properties into SQS message attributes and filter out any trace context related properties there instead.
Both of these alternatives involve generating and injecting the distributed trace context via the JMS API, …
> Avoid sending trace context twice when using JMS-over-SQS

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
We don't have context support on windows so we shouldn't attempt to create the integration
> skip creating profiling context integration on windows

- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/WrapRunnableAsNewTaskInstrumentation.java
- dd-smoke-tests/quarkus/src/test/groovy/datadog/smoketest/QuarkusSmokeTest.groovy
The executor that netty uses in more recent versions is not instrumented.
> Fix async propagation in some versions of undertow

- dd-java-agent/instrumentation/elasticsearch/rest-7/src/test/groovy/Elasticsearch7RestClientTest.groovy
This PR improves test coverage of the elasticsearch REST client instrumentation by covering the instrumented async call.
Only the one of the two instrumented methods was tested (the sync one).
> Add elasticsearch async call instrumentation tests

- dd-java-agent/agent-profiling/profiling-controller-jfr/build.gradle
- gradle/dependencies.gradle
- gradle/repositories.gradle
https://github.com/DataDog/dd-trace-java/pull/5661
> Use JMC 8.1.0 release from Maven Central (1.18.x backport)

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/CookieSecurityDetails.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/CookieSecurityParserTest.groovy
Backports the bugfix for the parsing of the HttpOnly for cookies
> Fix missing HttpOnly cookie vulnerability detection (1.18.x backport)

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelExtractedContext.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpanBuilder.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelTracerProvider.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
This PR fixes an issue with the OpenTelemetry instrumentation.
When setting a parent context to a `SpanBuilder`, it might not have a current span within.
If not, the tracer will reuse this invalid span context and generate a new (OTel) span with a Trace ID to 0.
Instead, if the span context is not valid, we want to generate a new trace.
This issue was encounter using [the Clojure `clj-otel` library](https://github.com/steffan-westcott/clj-otel) that always set parent context (even empty ones) when creating spans.
> Fix possible invalid parent span using OpenTelemetry API

- .circleci/config.yml
Archive parametric tests results before upload, just like we do with system-tests.
> Archive parametric tests results before upload

- .circleci/config.yml
Moves a few CircleCI jobs to smaller resource classes.
Smaller is smaller.
> Scale down CircleCI runner resource classes

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryContextInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14ActivationTest.groovy
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
This PR fixes OTel activation requirement to be enabled when `trace.otel.enabled` is set to `true`.
Disabling context instrumentation cause issues when trying to retrieve the current active span.
Only OTel API instrumentation was enabled, Context API instrumentation wasn't.
> Fix OpenTelemetry Context instrumentation activation

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
- gradle/dependencies.gradle
Bumps the ddprof dependency to 0.68.0 and adds a new experimental config flag to enable the jmethodid cache in the profiler.
The JVMTI jmethodids are used to identify frames returned from the JVMTI functions like `GetStackTrace`.
The problem is that those ids are guaranteed to be valid only while the class defining the method that is pointed to by the particular jmethodid is still loaded. And, with concurrent class unloading, this assumption may be broken immediately after the stacktrace has been obtained, unless the caller of the `GetStackTrace` manages to create strong references to all classes referenced from the stack trace, which is utterly impossible.
While the invalid jmethodid will manifest as a NULL pointer and that will be treated correctly by the JVMTI there are situations …
> Add support for the profiler jmethodid cache

- gradle/dependencies.gradle
Bug fix for a crash when determining the execution state of non-Java threads
> Upgrade to ddprof 0.70.0

- internal-api/src/main/java/datadog/trace/api/telemetry/CoreMetricCollector.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
- internal-api/src/test/groovy/datadog/trace/api/telemetry/TelemetryCollectorsTest.groovy
- telemetry/src/test/groovy/datadog/telemetry/metric/CoreMetricsPeriodActionTest.groovy
This PR fixes the span metrics `spans_created` and `spans_finished`  `integration_name` tag.
It also updates the default name (when no integration name is provided) to `datadog` which seems more inline with other tracers behavior.
Integration names are missing from metrics.
> Fix span metrics tag

- dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
- dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
- dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTestBase.groovy
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Adds a setting for disabling partial flushing `DD_TRACE_PARTIAL_FLUSH_ENABLED` and aligns the use of `DD_TRACE_PARTIAL_FLUSH_MIN_SPANS` with other tracer implementations.
> Make partial flushing settings consistent with other tracer libraries

- internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
- internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Updates the  config integer range parsing logic to handle single and double digit integers for handling grpc response codes.
https://github.com/DataDog/dd-trace-java/issues/5679
> Updated config parsing for integer ranges

- dd-java-agent/instrumentation/spark/build.gradle
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkStructuredStreamingTest.groovy
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkTest.groovy
- dd-java-agent/instrumentation/spark/src/test/java/TestSparkComputation.java
[Spark structured streaming](https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html) is a stream processing engine built on the Spark SQL. It process data streams as a series of small batch jobs, where each batch jobs is composed of the regular spark operations (job / stage / task)
A streaming applications is composed of 
- one or more long running queries, identified a `queryId`
- each query continuously executes batches identified by a incrementing `batchId`
Spark is emitting 3 type of events in structured streaming:
- `QueryStartedEvent` 
- `QueryTerminatedEvent` 
- `QueryProgressEvent`
`QueryProgressEvent` is emitted at the end of each micro-batch in the [finishTrigger](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/ex …
> [Spark] Add support for spark structured streaming

- .gitignore
- .gitlab-ci.yml
- .gitlab/ci-visibility-tests.yml
Adds a manual Gitlab job that triggers CI Visibility [test-environment](https://github.com/DataDog/test-environment) run with the tracer built in the current branch.
Make it easier to run these external tests before tracer changes are merged.
The job is only triggered manually, so it will not interfere with the other products.
> Add manual Gitlab job for running CI Visibility test environment

- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Utils.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/TestFrameworkUtils.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/TracingListener.java
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGUtils.java
Updates CI Visibility utility classes to use `MethodHandle` invocations instead of `Method` reflection calls.
Reducing performance overhead: method handles are considerably faster than "plain" reflection calls.
The reasons for using reflection in utility classes are the following:
* We have to compile our code against the minimum supported versions of the test frameworks that we instrument. Therefore we cannot directly invoke certain methods that were introduced to those frameworks in later releases. At the same time we would like to use those methods to get additional tests data, therefore we have to resort to runtime lookup.
* In certain environments (mainly Gradle) parts of the test frameworks are loaded using different classloaders, so we have to lookup the right classes and invoke …
> Replace reflection calls with method handle invocations in test utils

- benchmark/Dockerfile
- benchmark/load/insecure-bank/k6.js
- benchmark/load/petclinic/benchmark.json
- benchmark/startup/insecure-bank/benchmark.json
- benchmark/startup/petclinic/benchmark.json
- benchmark/utils/k6.js
- benchmark/utils/run-sirun-benchmarks.sh
Reduces the number of benchmarks run in the bench-marking platform and moves towards the parallel version
Now the time taken by the benchmark task should be around 40min.
> Reduce the amount of benchmarks run in the benchmarking platform

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestModuleChild.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestModuleParent.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestSessionParent.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/context/AbstractTestContext.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/context/ParentProcessTestContext.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/BuildEventsHandlerImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/ModuleExecutionResult.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ipc/ModuleExecutionResultTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ipc/SignalServerTest.groovy
- dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleBuildListener.java
- dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleBuildListenerInstrumentation.java
- dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleUtils.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenExecutionListener.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenInstrumentation.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenLifecycleParticipant.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenUtils.java
- dd-java-agent/instrumentation/maven-3.2.1/src/test/groovy/MavenTest.groovy
- internal-api/src/main/java/datadog/trace/api/civisibility/events/BuildEventsHandler.java
Update CI Visibility: test framework name and version are now sent from children processes to the parent process using signal server.
Improving the accuracy of test framework name and version detection.
Test session and test modules spans are created by the parent process.
These spans need to be tagged with test framework name and version.
Previous implementation attempted to extract that data by parsing the list of project's Maven or Gradle dependencies.
That approach often gave inaccurate results (for instance, in cases when a project had JUnit dependency but ran another framework such as Spock or Cucumber on top of JUnit).
The new approach is more accurate since the data is obtained from test framework instrumentations.
> Report test framework data from child processes instead of parsing project dependencies

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestImpl.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/DDTestImplTest.groovy
Updates CI Visibility logic to check if there are any active (unfinished) spans when a "test finished" event is received.
If any active spans are found that are children of the span corresponding to finished test, they are closed.
We cannot properly finish the test span if its scope is not on top of the scopes stack.
Tests often perform operations that trigger APM instrumentation code: sending an HTTP request, executing a database query, etc. APM instrumentations create spans that correspond to those operations. Ideally, the instrumentations close these spans once their corresponding operations are finished.
However, this is not always the case, especially with tests: sometimes developers do not perform proper resources disposal (such as closing a connection) in tests code. Not finalizing …
> Close outstanding APM spans before finishing test span

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
Change the instrumentation to call in any cases readyToCapture method that invoke sampling except for SpanDecorationProbe.
With evaluateAt == EXIT for a log probe, sampling was not invoked.
> Fix sampling when log probe is evaluation at Exit

- dd-java-agent/instrumentation/jetty-11/build.gradle
- dd-java-agent/instrumentation/jetty-9/build.gradle
- dd-java-agent/instrumentation/jetty-appsec-9.3/build.gradle
Jetty server 12 was released and our instrumentations do not seem compatible with it.
This PR exclude any version equals or older than 12.
> Exclude Jetty server 12 from Jetty instrumentations support

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/AgentJarIndex.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/JDBCConnectionUrlParser.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
- dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/KnownTypesIndex.java
- dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/csi/StringConcatExample.java
- dd-java-agent/agent-tooling/src/test/java11/datadog/trace/agent/tooling/csi/StringPlusConstantsExample.java
- dd-java-agent/agent-tooling/src/test/java11/datadog/trace/agent/tooling/csi/StringPlusExample.java
- dd-java-agent/agent-tooling/src/test/java11/datadog/trace/agent/tooling/csi/StringPlusLoadWithTagsExample.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
- dd-java-agent/instrumentation/jsp-2.3/src/main/java/datadog/trace/instrumentation/jsp/JSPDecorator.java
- dd-trace-core/src/main/java/datadog/trace/common/writer/TraceStructureWriter.java
- dd-trace-core/src/main/java/datadog/trace/common/writer/ddintake/DDEvpProxyApi.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-ot/correlation-id-injection/src/main/java/datadog/trace/correlation/CorrelationIdInjectors.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
- remote-config/src/main/java/datadog/remoteconfig/state/ProductState.java
debug, error and warn logging statements that report both a resource and an exception have been changed so they use placeholders instead of string operations.
Exception reports filed by DDLogger will be sent to our servers using the telemetry API. If the message is composed using placeholders instead of string operations, the placeholders will not be substituted when sending this information over the wire to the telemetry API. This will make sure we don't send any sensitive information to the telemetry service once the telemetry API is merged.
This changes are related to the new telemetry functionality implemented by https://github.com/DataDog/dd-trace-java/pull/4521
> Improved logging using placeholders

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/EvidenceAdapter.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/Ranged.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/EvidenceRedactionTest.groovy
- dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite.yml
When redacting SQL queries, an empty literal should be redacted as well or we would be leaking information.
> Redact empty sensitive ranges

- dd-java-agent/instrumentation/servlet-common/src/test/groovy/HttpServletResponseInstrumentationTest.groovy
- dd-java-agent/instrumentation/servlet-common/src/test/java/foo/bar/DummyResponse.java
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaHttpServletResponseInstrumentation.java
- dd-java-agent/instrumentation/servlet/request-5/src/test/groovy/JakartaHttpServletResponseInstrumentationTest.groovy
- dd-java-agent/instrumentation/servlet/request-5/src/test/java/foo/bar/smoketest/DummyResponse.java
Adds concrete types for the response instrumentation methods
Instrumentation errors lead to logged exceptions in Undertow and Jetty.
> Set concrete types for the response instrumentation

- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
Excludes `org.mockito` package from CI Visibility code coverage. 
When customer uses Jacoco injected by tracer, there is a list of packages that are by default excluded from Jacoco instrumentation.
This change extends this list with `org.mockito`.
Instrumenting classes in `org.mockito` may cause `StackOverflowError` - some of the tracer code that handles coverage probe activations uses certain classes (`ConcurrentHashMap` in particular) that are transformed by Mockito.
As the result, activating a coverage probe in a Mockito class leads to invoking a Mockito class which leads to activating a coverage probe.
This continues until method execution stack is overflown.
> Exclude org.mockito package from CI Visibility code coverage by default

- dd-java-agent/instrumentation/jax-rs-client-2.0/connection-error-handling-jersey/build.gradle
- dd-java-agent/instrumentation/jax-rs-client-2.0/connection-error-handling-jersey/src/main/java/org/glassfish/jersey/client/WrappingResponseCallback.java
- dd-java-agent/instrumentation/jax-rs-client-2.0/connection-error-handling-jersey/src/test/groovy/WrappingResponseCallbackTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- utils/test-utils/src/main/groovy/datadog/trace/test/util/Flaky.java
Adds a new configuration option via `DD_TRACE_JAX_RS_EXCEPTION_AS_ERROR_ENABLED` which, when set to `false` forces exceptions from JAX-RS to not be treated as errors. This does not drop the underlying exception if it exists
This is helpful for situations for situations where a 3xx level response returned triggers a custom exception in the underlying code since the span should not be considered an error
> Add configuration option to allow Jax-RS exceptions to not be handled as errors

- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenProjectConfigurator.java
- dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_with_jacoco_and_argline/pom.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_with_jacoco_and_argline/src/test/java/datadog/smoke/TestSucceed.java
Fixes automatic tracer configuration for Maven projects that use Jacoco.
Jacoco Maven plugin modifies the project's `<argLine>` property, adding Jacoco agent argument.
In order for things to work, Surefire plugin's `<argLine>` has to contain a reference to the project's arg line: `@{argLine}` (this form is "late-substitution", meaning value is substituted after Jacoco plugin has run).
The logic that does automatic tracer configuration adds this reference when changing Surefire plugin's arg line.
The reference is added unconditionally.
The problem is that if Surefire's original arg line (as specified in `pom.xml`) already contains the `@{argLine}` bit, the one we're adding is a duplicate, and this breaks the build.
The fix is to check whether the original configuration already has the …
> Fix automatic tracer configuration for Maven projects that use Jacoco

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
- dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/BaseServiceAdder.java
- dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/PostProcessorChain.java
- dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/TagsPostProcessor.java
- dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/TagsPostProcessorFactory.java
- dd-trace-core/src/test/groovy/datadog/trace/core/tagprocessor/BaseServiceAdderTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/test/DDCoreSpecification.groovy
When the service name is different to the configured one (DD_SERVICE) we add a tag `_dd.base_service` that's used internally to improve the service map
> add _dd.base_service to disambiguate service map

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpan.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
The OpenTelemetry spans should not be modifiable when finished.
[Specification reference](https://opentelemetry.io/docs/specs/otel/trace/api/#isrecording)
> Ensure OpenTelemetry spans are not modifiable when finished

- dd-smoke-tests/appsec/springboot-security/src/main/java/datadog/smoketest/appsec/springbootsecurity/WebSecurityConfig.java
- dd-smoke-tests/appsec/springboot-security/src/main/resources/application.properties
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
Fixed SpringSecurity NullPointerException when user creation happens outside request context.
Reported exception message in debug log:
```
[dd.trace 2023-08-16 12:27:42:204 +0000] [main] DEBUG datadog.trace.bootstrap.ExceptionLogger - Failed to handle exception in instrumentation for org.springframework.security.provisioning.InMemoryUserDetailsManager
at datadog.trace.agent.core.CoreTracer.getTraceSegment(CoreTracer.java:1232)
at datadog.trace.bootstrap.instrumentation.decorator.AppSecUserEventDecorator.getSegment(AppSecUserEventDecorator.java:68)
at datadog.trace.bootstrap.instrumentation.decorator.AppSecUserEventDecorator.onSignup(AppSecUserEventDecorator.java:41)
at datadog.trace.instrumentation.springsecurity5.SpringSecurityUserEventDecorator.onSignup(Spr …
```
> Fixed NPE in User Events Tracking

- dd-java-agent/build.gradle
- dd-trace-ot/build.gradle
- telemetry/src/main/java/datadog/telemetry/dependency/LocationsCollectingTransformer.java
- telemetry/src/test/groovy/datadog/telemetry/dependency/LocationsCollectingTransformerSpecification.groovy
* Remove the telemetry check we previously added to avoid reporting dd-trace-java vendored dependencies to telemetry.
* Amend the exclusion of `META-INF/maven` to not include `pom.properties` (introduced in 5346d91d34c), which we use to report dependencies to telemetry.
While this might be sometimes confusing, we want to report the runtime dependencies as accurately as possible, include those that are introduced by the tracer.
* This leads to a ~0.5ms regression in telemetry startup, presumably because now loading classes from the tracer hits the regular codepath that hits `DDCache#computeIfAbsent` for `seenDomains`.
> Report dd-trace-java and its dependencies to telemetry

- .circleci/config.continue.yml.j2
- .circleci/update_pinned_system_tests.sh
* Fix the update script for the new dynamic config.
* Comparison:
https://github.com/datadog/system-tests/compare/68da674b83d7a1a1730387a3b27a1d4328392f3c..9659a5e409cf8bacabd739b6af07c5f03c9bcbd6
Previous update: https://github.com/DataDog/dd-trace-java/pull/5703
* https://github.com/DataDog/system-tests/pull/1480
* https://github.com/DataDog/system-tests/pull/1482
* https://github.com/DataDog/system-tests/pull/1344
* https://github.com/DataDog/system-tests/pull/1481
* https://github.com/DataDog/system-tests/pull/1494
* https://github.com/DataDog/system-tests/pull/1431
> Update system-tests to 9659a5e409cf8bacabd739b6af07c5f03c9bcbd6

- dd-java-agent/agent-ci-visibility/build.gradle
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilitySystem.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/CILocalGitInfoBuilder.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/GitClientGitInfoBuilder.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitClient.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitDataUploaderImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/utils/IOUtils.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/utils/ShellCommandExecutor.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ci/CITagsProviderTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ci/UnknownCIInfoTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/CILocalGitInfoBuilderTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/GitClientGitInfoBuilderTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/tree/GitClientTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/tree/GitDataUploaderImplTest.groovy
- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/api/git/GitInfoProvider.java
- internal-api/src/test/groovy/datadog/trace/api/git/GitInfoProviderTest.groovy
Adds a new `GitInfoBuilder` instance to `GitInfoProvider`.
The new instance fetches git data using shell commands.
Also repository URL in Git data upload now uses `GitInfoProvider` instead of directly invoking the shell command.
Previously Git data upload relied solely on executing a shell command to obtain Git remote URL, while the other logic that used Git remote URL extracted it from a variety of sources: CI provider or user-supplied environment variables, locally available `.git` folder, etc.
This change makes Git data upload consistent with the other places in the code that use Git info.
In addition to that, the other places can now benefit from info fetched with shell commands, in case it cannot be obtained from other sources.
The new shell-command-based `GitInfoBuilder` has lower …
> Add git command line client builder to GitInfoProvider

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
Following #4619, the exception was not logged as before.
> fix log error throwable

- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
Makes it so that `elasticsearch.params` and `opensearch.params` are omitted by default
The original behavior can be maintained by setting `trace.elasticsearch.body-and-params.enabled` to `true
This is beneficial in the case that they contain sensitive information
Also closes #5718
> Elasticsearch and Opensearch should omit `params` by default

- .github/CODEOWNERS
Rename `iast-java` and `appsec-java` teams to `asm-java`.
Revamp of ASM GitHub teams.
> Update codeowners for ASM

- gradle/dependencies.gradle
Updates ddprof-lib to [0.70.1](https://github.com/DataDog/java-profiler/releases/tag/v_0.70.1)
The 0.70.0 seems to be containing a slow memory leak. The 0.70.1 patch rolls back the suspected functionality.
> Update ddprof-lib to 0.70.1

- dd-java-agent/instrumentation/spring-webflux-6/build.gradle
- dd-java-agent/instrumentation/spring-webmvc-6.0/build.gradle
- dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java/datadog/trace/instrumentation/springweb6/TemplateAndMatrixVariablesInstrumentation.java
- dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java17/datadog/trace/instrumentation/springweb6/HandleMatchAdvice.java
- dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java17/datadog/trace/instrumentation/springweb6/PairList.java
Re-enable muzzle for spring 6
I had to duplicate PairList class because otherwise muzzle classpath would need stuff like `javax.servlet` (brung from spring web 5 and 3) while spring 6 is purely relying on jakarta
At time spring 6 instrumentation has been implemented, muzzle did not support a JDK17. Now it does
> re-enable muzzle for spring 6

- gradle/dependencies.gradle
Updates ddprof-lib to [0.70.1](https://github.com/DataDog/java-profiler/releases/tag/v_0.70.1)
The 0.70.0 seems to be containing a slow memory leak. The 0.70.1 patch rolls back the suspected functionality.
(cherry picked from commit d7ef89215f6065edf5618f0addfcdf284299cb79)
> Update ddprof-lib to 0.70.1 (#5752)

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/UnvalidatedRedirectModuleImpl.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/UnvalidatedRedirectModuleTest.groovy
Under some circumstances, the `name` field of an IAST source can be `null` (very rare, and generally an indicative of another issue, but it's currently legal). In this case, the unvalidated redirect detection can throw a NPE.
This NPE is caught in the instrumentation, so it will not break the app, but it will log to debug:
```
[dd.trace 2023-08-22 18:49:20:322 +0200] [http-nio-20002-exec-3] DEBUG datadog.trace.bootstrap.ExceptionLogger - Failed to handle exception in instrumentation for org.springframework.web.method.support.InvocableHandlerMethod
at com.datadog.iast.sink.UnvalidatedRedirectModuleImpl.isRefererHeader(UnvalidatedRedirectModuleImpl.java:102)
at com.datadog.iast.sink.UnvalidatedRedirectModuleImpl.checkUnvalidatedRedirect(UnvalidatedRedirectModul …
```
> Fix NullPointerException in unvalidated redirect detection

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/UnvalidatedRedirectModuleImpl.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/UnvalidatedRedirectModuleTest.groovy
Under some circumstances, the `name` field of an IAST source can be `null` (very rare, and generally an indicative of another issue, but it's currently legal). In this case, the unvalidated redirect detection can throw a NPE.
This NPE is caught in the instrumentation, so it will not break the app, but it will log to debug
Backport of #5755
> Fix NullPointerException in unvalidated redirect detection (#5755)

- dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/BaseServiceAdder.java
- dd-trace-core/src/test/groovy/datadog/trace/core/tagprocessor/BaseServiceAdderTest.groovy
Use case insensitive comparison when deciding if adding `_dd.base_service` tag
> use case insensitive comparison for _dd.base_service

- dd-java-agent/instrumentation/spring-security-5/src/main/java17/datadog/trace/instrumentation/springsecurity5/AbstractUserDetailsAuthenticationProviderAdvice.java
- dd-java-agent/instrumentation/spring-security-5/src/main/java17/datadog/trace/instrumentation/springsecurity5/AuthenticationProviderAdvice.java
- dd-java-agent/instrumentation/spring-security-5/src/main/java17/datadog/trace/instrumentation/springsecurity5/UserDetailsManagerAdvice.java
Fixed activation for User Event Tracking.
Active only if AppSec is active with `DD_APPSEC_ENABLED=true` or via remote config.
Customer reported an issue when User Event Tracking was working even with inactive AppSec.
> Enable user event tracking only when AppSec is enabled

- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenExecutionListener.java
- dd-java-agent/instrumentation/maven-3.2.1/src/test/groovy/MavenTest.groovy
- dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
Changes the way CI Visibility test module names are calculated in instrumented Maven projects.
Previous module name used to include project name and lifecycle phase.
New module name includes project name, plugin name, and execution ID.
Project name and lifecycle phase combination gives a module name that is not necessarily unique: it is possible to have a project configuration that binds multiple test executions in the same module to the same phase.
Project name, plugin name and execution ID combination is unique, Maven itself enforces this.
Non-unique module names may cause the following issues:
- if two modules with the same name execute in parallel the build will fail (due to some internal details of the test module registry implementation that uses the module name to uniquely identify …
> Make Maven test module names unique

- dd-java-agent/instrumentation/spring-security-5/src/main/java17/datadog/trace/instrumentation/springsecurity5/AbstractUserDetailsAuthenticationProviderAdvice.java
- dd-java-agent/instrumentation/spring-security-5/src/main/java17/datadog/trace/instrumentation/springsecurity5/AuthenticationProviderAdvice.java
- dd-java-agent/instrumentation/spring-security-5/src/main/java17/datadog/trace/instrumentation/springsecurity5/UserDetailsManagerAdvice.java
Fixed activation for User Event Tracking.
Active only if AppSec is active with DD_APPSEC_ENABLED=true or via remote config.
Customer reported an issue when User Event Tracking was working even with inactive AppSec.
Backport of #5756
> Enable user event tracking only when AppSec is enabled (#5756)

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/usm/Payload.java
- dd-java-agent/instrumentation/sslengine/src/main/java/datadog/trace/instrumentation/sslengine/SslEngineInstrumentation.java
- Support response that is split into multiple buffers
- limited the Payload buffer to 160 bytes (max buffer size supported by USM on a kernel side)
> Fix multi-buffers response case

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilitySystem.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/BestEffortMethodLinesResolver.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/BestEffortSourcePathResolver.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/ByteCodeMethodLinesResolver.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/CompilerAidedMethodLinesResolver.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/MethodLinesResolver.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/BestEffortMethodLinesResolverTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/BestEffortSourcePathResolverTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/ByteCodeMethodLinesResolverTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/CompilerAidedMethodLinesResolverTest.groovy
- dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- internal-api/build.gradle
Updates CI Visibility logic that extracts lines metadata for test methods.
The update is to use `@MethodLines` annotation injected by [dd-javac-plugin](https://github.com/DataDog/dd-javac-plugin/tree/master) if available, and fall back to the previously used method (class bytecode traversing) if not.
Data injected by the compiler plugin is more accurate (as it includes method declaration lines - method name, modifiers, annotations) and can be retrieved with less overhead (as getting a runtime annotation does not required reading class data from disk, which is needed for bytecode traversing).
> Use DD Javac Plugin metadata to resolve method lines

- dd-java-agent/instrumentation/elasticsearch/src/main/java/datadog/trace/instrumentation/elasticsearch/ElasticsearchRestClientDecorator.java
- dd-java-agent/instrumentation/opensearch/src/main/java/datadog/trace/instrumentation/opensearch/OpensearchRestClientDecorator.java
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Expands upon #5749 to separate the configuration options for `body` and `params` so that they can be individually selected
After this, the usage of `dd.trace.elasticsearch.body-and-params.enabled` will be discouraged in favor of the individual options, `dd.trace.elasticsearch.body.enabled` and `dd.trace.elasticsearch.params.enabled`
Gives users of the library increased flexibility when it comes to configuring their elasticsearch instrumentation
> Separate config for Elasticsearch body and params

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
Skips span creation when a duplicate vulnerability is detected and there is no active span.
We have detected excessive span creation by IAST due to duplicated vulnerabilities creating span that latter were not used.
> Prevent IAST from creating empty spans for duplicated vulnerabilities

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/WeakRandomnessModuleImpl.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/WeakRandomnessModuleTest.groovy
Check for overhead limits before reporting weak randomness vulnerability
> Check for overhead constraints in weak randomness module

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/QueueTimerHelper.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/QueueTimeTracker.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/profiling/UnwrappingVisitor.java
- dd-java-agent/instrumentation/java-concurrent/src/test/groovy/TaskUnwrappingForkedTest.groovy
- dd-java-agent/instrumentation/netty-concurrent-4/src/main/java/datadog/trace/instrumentation/netty40/concurrent/SingleThreadEventExecutorInstrumentation.java
- dd-java-agent/instrumentation/netty-concurrent-4/src/test/groovy/TimingTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/timer/TestTimer.groovy
- internal-api/src/main/java/datadog/trace/api/profiling/QueueTiming.java
- internal-api/src/main/java/datadog/trace/api/profiling/Timing.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TaskWrapper.java
- internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/TaskWrapperTest.groovy
* Move `TaskWrapper` from bootstrap to internal api so it can be used by the profiler
* Track a weak reference to the task rather than an eagerly unwrapped task, the unwrapping will take place if the queue time threshold is breached
* Stop filtering out Netty chores because filtering them out by unwrapped class name may be too expensive - they will probably be filtered out by the duration threshold anyway.
Interface `instanceof` checks are dangerous in instrumentation because they may lead to flip-flopping of `secondary_super_cache` which can be a scalability bottleneck. This change delays unwrapping the task type until we know we will record a queue time sample, and therefore there is already a bottleneck anyway.
> rework Queue time tracking to avoid unwrapping the task type unless the event will be recorded

- dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientResponseTracingHandler.java
- dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientResponseTracingHandler.java
- dd-java-agent/instrumentation/vertx-web-4.0/build.gradle
- dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/client/HttpClientRequestBaseInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/client/VertxHttpClientForkedTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
Fix for an issue with Vert.x HTTP timed out client requests. It was keeping a request span unfinished.
Vert.x uses Netty under the hood. Netty instrumentation already has timeout handling but turns out that Vert.x has its own timeout handling that have not been covered with instrumentation.
There are two main pieces. First, closing a span in Netty instrumentation in case of the `channelInactive` event. Second, decorating a span on Vert.x instrumentation side with the original exception, so it's clear that the request has been timed out.
A client reported issue about created but never finished client http spans in case of timeout.
Example of a timed out span:
```json
[
{
"service": "service-name",
"name": "netty.client.request",
"resource": "GET /?",
"trace_id": "2178227018975193174", …
```
> Fix for Vert.x 4.0 instrumentation to close span on timeout

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
If bytecode generation fails for any reason we should returns null for cancelling the current class transformation
> Fix instrumentation when bytecode generation fails

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/SmokeTestUtils.java
- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
- gradle/dependencies.gradle
Updates the ddprof dependendcy.
The new version dropped the jmethodid cache because it is not really possible to implement it in a performant way.
Instead of cache a 'deep' jmethodId check function was added which seems to be preventing all the (so far) observed crashes related to jmethodIDs.
See https://github.com/DataDog/java-profiler/releases/tag/v_0.71.0
> Update ddprof to 0.71.0

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/TaintedObjects.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedObjectsNoOpTest.groovy
Remove the need to acquire a full tainted objects instance when reporting with a custom span
> Use a NoOp tainted objects for vulnerabilities without context

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/telemetry/TelemetryRequestStartedHandler.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/telemetry/taint/TaintedObjectsWithTelemetry.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/telemetry/TelemetryRequestStartedHandlerTest.groovy
- internal-api/src/main/java/datadog/trace/api/iast/telemetry/IastMetricCollector.java
Improve IAST metrics by:
- Removing the need to have extra accesses to the current context in the tainted 
- Removing `replaceAll` method call with a simpler `replace`
> Improve performance while computing IAST metrics

- dd-java-agent/instrumentation/jetty-11/build.gradle
- dd-java-agent/instrumentation/jetty-11/src/main/java11/datadog/trace/instrumentation/jetty11/JettyServerAdvice.java
- dd-java-agent/instrumentation/jetty-9/src/main/java_jetty10/datadog/trace/instrumentation/jetty10/HandleAdvice.java
See https://github.com/DataDog/dd-trace-java/issues/5782
> Fix simultaneous jetty 10/11 instrumentation when jakarta/javax servlet are both present

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndex.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/SourceType.java
- dd-java-agent/agent-ci-visibility/src/testFixtures/groovy/datadog/trace/civisibility/CiVisibilityTest.groovy
- dd-java-agent/instrumentation/junit-4.10/build.gradle
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Instrumentation.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4ItrInstrumentation.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4SuiteEventsInstrumentation.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Utils.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/TracingListener.java
- dd-java-agent/instrumentation/junit-4.10/src/test/groovy/CucumberTest.groovy
- dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
- dd-java-agent/instrumentation/junit-4.10/src/test/groovy/MUnitTest.groovy
- dd-java-agent/instrumentation/junit-4.10/src/test/java/org/example/TestFailedSuiteSetUpAssumption.java
- dd-java-agent/instrumentation/junit-4.10/src/test/java/org/example/TestSucceedSuite.java
- dd-java-agent/instrumentation/junit-4.10/src/test/java/org/example/TestSuite.java
- dd-java-agent/instrumentation/junit-4.10/src/test/scala/org/example/TestFailedAssumptionMUnit.scala
- dd-java-agent/instrumentation/junit-4.10/src/test/scala/org/example/TestSkippedMUnit.scala
- dd-java-agent/instrumentation/junit-4.10/src/test/scala/org/example/TestSkippedSuiteMUnit.scala
- dd-java-agent/instrumentation/junit-4.10/src/test/scala/org/example/TestSucceedMUnit.scala
- dd-java-agent/instrumentation/junit-5.3/src/test/groovy/CucumberTest.groovy
Adds support for Scala [MUnit](https://scalameta.org/munit/) testing framework to CI Visibility.
There is a [feature request](https://github.com/DataDog/dd-trace-java/issues/5760).
MUnit is built on top of JUnit 4.
In order to support it, the following things were done:
- reworked test suite events mechanism: "custom" suite events implemented via bytecode instrumentation are now used only for JUnit < 4.13. Versions 4.13 and above now use "native" suite events that are available as part of the framework. The reason to change this was that the custom events were not working properly with custom runner implementations
- reworked logic that detects if a `Description` contains direct children that are atomic test cases: it was not working properly with `MUnit`, causing all suites to be ignored …
> Add basic Scala MUnit support

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkAggregatedTaskMetrics.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkListenerTest.groovy
Spark metrics had a separate prefix for each operation (application, job, stage) which turned out to be complicated to use from the UI. This PR unifies the prefix to "spark" for all operations
There is already a processing in the backend to rename those prefix, so spans already appear with the name "spark" in datadog UI
> Unify spark metrics naming

- dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakCipherInstrumentationCallSite.java
- dd-java-agent/instrumentation/java-security/src/test/groovy/test/WeakCipherTest.groovy
- dd-java-agent/instrumentation/java-security/src/test/java/foo/bar/TestSuite.java
- dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
- dd-smoke-tests/iast-util/src/main/java/ddtest/client/sources/Hasher.java
- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
Instruments javax.crypto.KeyGenerator so we can detect weak cypher vulnerabilities
We need to cover all of the calls where the user can create a cypher with a weak algorithm including KeyGenerator and SecretKeyFactory
> Weak cipher detection in javax.crypto.KeyGenerator

- dd-java-agent/instrumentation/netty-concurrent-4/build.gradle
Filters out versions of dependencies containing `alpha` or `beta`
The dependency `io.netty:netty-common:5.0.0.Alpha2` failed the `latestDepTest`
> Filter out alpha and beta versions of dependencies

- .circleci/config.continue.yml.j2
Comparison:
https://github.com/datadog/system-tests/compare/9659a5e409cf8bacabd739b6af07c5f03c9bcbd6..3749ab47dba7ceb1ac48bc9de6c89cb6427b0daa
Previous update: https://github.com/DataDog/dd-trace-java/pull/5738
* https://github.com/DataDog/system-tests/pull/1461
* https://github.com/DataDog/system-tests/pull/1487
* https://github.com/DataDog/system-tests/pull/1516
* https://github.com/DataDog/system-tests/pull/1476
> Update system-tests to 3749ab47dba7ceb1ac48bc9de6c89cb6427b0daa

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/ClassFileLocators.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
Some deployments will want to use URL caches for performance reasons. Others may want to skip URL caches as they can lead to JarFiles being pinned in memory (or keeping files locked in Windows)
The Java tracer will now use the default URLConnection 'UseCaches' setting, but this can be overriden (to false or true) by adding this JVM option:
```
-Ddd.resolver.use.url.caches=false
```
or by setting this environment variable:
```
DD_RESOLVER_USE_URL_CACHES=false
```
> Type resolver's use of URL caches should be configurable

- dd-java-agent/instrumentation/rxjava-2/build.gradle
- dd-java-agent/instrumentation/rxjava-2/src/main/java/datadog/trace/instrumentation/rxjava2/RxJavaAsyncResultSupportExtension.java
- dd-java-agent/instrumentation/rxjava-2/src/main/java/datadog/trace/instrumentation/rxjava2/RxJavaPluginsInstrumentation.java
- dd-java-agent/instrumentation/rxjava-2/src/test/groovy/RxJava2ResultSupportExtensionTest.groovy
- dd-java-agent/instrumentation/rxjava-2/src/test/java/annotatedsample/RxJava2TracedMethods.java
This features is a follow up of #5593 and #5737.
This brings the support for RxJava types: `Completable`, `Maybe`, `Single`, `Observable`, and `Flowable`.
Those are the fourth asynchronous type according the most used libraries.
> Add RxJava async result types support for OpenTelemetry annotations

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkConfAllowList.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkStructuredStreamingTest.groovy
Capture spark application, job and databricks parameters in spark streaming spans
Those parameters are currently missing on streaming spans, preventing to link those back to databricks tasks
> Capture app, job and databricks parameters in spark streaming spans

- dd-java-agent/instrumentation/reactor-core-3.1/build.gradle
- dd-java-agent/instrumentation/reactor-core-3.1/src/main/java/datadog/trace/instrumentation/reactor/core/MonoFluxInstrumentation.java
- dd-java-agent/instrumentation/reactor-core-3.1/src/main/java/datadog/trace/instrumentation/reactor/core/ReactorAsyncResultSupportExtension.java
- dd-java-agent/instrumentation/reactor-core-3.1/src/test/groovy/ReactorAsyncResultSupportExtensionTest.groovy
- dd-java-agent/instrumentation/reactor-core-3.1/src/test/java/annotatedsample/ReactorTracedMethods.java
This features is a follow up of #5593 and #5737.
This brings the support for Reactor types: `Mono` and `Flux`.
Those are the third asynchronous types according the most used libraries.
> Add Reactor async result types support for OpenTelemetry annotations

- dd-java-agent/instrumentation/guava-10/build.gradle
- dd-java-agent/instrumentation/guava-10/src/main/java/datadog/trace/instrumentation/guava10/GuavaAsyncResultSupportExtension.java
- dd-java-agent/instrumentation/guava-10/src/main/java/datadog/trace/instrumentation/guava10/ListenableFutureInstrumentation.java
- dd-java-agent/instrumentation/guava-10/src/test/groovy/GuavaAsyncResultSupportExtensionTest.groovy
- dd-java-agent/instrumentation/guava-10/src/test/java/annotatedsample/GuavaTracedMethods.java
This features is a follow up of #5593 and #5737.
This brings the support for Guava type: `ListenableFuture`.
This is the second asynchronous type according the most used libraries.
> Add Guava async result type support for OpenTelemetry annotations

- dd-java-agent/appsec/src/main/resources/default_config.json
- dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
* Inject test rules that we need for tests at test time.
* Avoid polluting the production ruleset.
* Follow up to https://github.com/DataDog/dd-trace-java/pull/5594
* Spotted while working on https://github.com/DataDog/dd-trace-java/pull/5815
> Inject WAF custom rules for testing in smoke tests

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
Fixes regression introduced in #5583 where `-Ddd.integrations.<name>.enabled` flag would no longer be checked. This does not affect other profiling instrumentations (direct allocation profiling, queue time) which have profiling scoped flags.
> restore exception profiling instrumentation enablement

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTracer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/InstrumentationResult.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Instrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/SpanInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/MetricProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SpanProbesIntegrationTest.java
- utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/v04/raw/SpanV04.java
Also refactor the status of the instrumentation to be returned by instrument method. It avoids to send a probe status INSTALLED first then received later the ERROR one.
Report a probe status error when trying to instrument a single line span probe.
> Add span smoke tests

- dd-java-agent/appsec/build.gradle
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
There is a single implementation of AppSec module, and we do not expect more.
> Avoid ServiceLoader in AppSec

- .circleci/config.continue.yml.j2
- dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/QueryObfuscator.java
Changes the default regular expression used to obfuscate credentials in query strings. This new regexp is the new standard form for all tracers.
This can be overridden with the `DD_TRACE_OBFUSCATION_QUERY_STRING_REGEXP` environment variable.
Depends on https://github.com/DataDog/system-tests/pull/1550
> Improve query obfuscation regular expression

- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGUtils.java
- dd-java-agent/instrumentation/testng/src/testFixtures/groovy/datadog/trace/instrumentation/testng/TestNGTest.groovy
- dd-java-agent/instrumentation/testng/src/testFixtures/java/org/example/TestSucceedDataProvider.java
Fixes `NullPointerException` that occurs when checking if a TestNG `@Factory` test with `@DataProvider` is skippable.
There is a Github [issue](https://github.com/DataDog/dd-trace-java/issues/5268) reported by a CI Visibility user.
In legacy instrumentation mode (when only JVMs running the tests are instrumented, and the build system is not), ITR instrumentations are applied even if ITR is not enabled (since it is impossible to make a request for remote config before applying instrumentations - when the latter is done, CI Visibility is not initialised yet).
So even though ITR will not skip tests when it is disabled, some ITR-related code will still execute.
Therefore this issue may impact even customers that do not use ITR.
> Fix NullPointerException when calculating ITR skippable tests in TestNG

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
Prevent a logged NullPointerException (not propagated to the app) while GatewayBridge is being updated.
A few cases were not included in https://github.com/DataDog/dd-trace-java/pull/5383
Example exception:
```
Callback for EventType{name='http.server.client_socket_address'} threw. [exception:java.lang.NullPointerException: Cannot invoke "com.datadog.appsec.event.EventDispatcher$DataSubscriberInfoImpl.isEventDispatcher(com.datadog.appsec.event.EventDispatcher)" because "subscribers" is null.
at com.datadog.appsec.event.EventDispatcher.publishDataEvent(EventDispatcher.java:185)
at com.datadog.appsec.event.ReplaceableEventProducerService.publishDataEvent(ReplaceableEventProducerService.java:33)
at com.datadog.appsec.gateway.GatewayBridge.maybePublishRequestData(GatewayBridge.java:537)
at …
```
> Fix race condition in AppSec GatewayBridge

- dd-java-agent/instrumentation/grpc-1.5/build.gradle
`InProcessChannelBuilder` used in the tests was moved to `grpc-inprocess`
> Update build to reflect refactoring in grpc-java 1.58

- dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
Exclude `net.jpountz.xxhash.*` from IAST instrumentation.
There is currently a weak randomness false positive in net.jpountz.xxhash.XXHashFactory.
See https://github.com/lz4/lz4-java/blob/7c931bef32d179ec3d3286ee71638b23ebde3459/src/java/net/jpountz/xxhash/XXHashFactory.java#L184-L188
> Exclude net.jpountz.xxhash in IAST

- .github/workflows/README.md
- .github/workflows/trivy-analysis.yml
Enables [Trivy](https://trivy.dev/) security scanning for the published artifacts.
Get notifications about potential security issues as soon as possible.
> Enable Trivy security scanning for published artifacts

- dd-java-agent/instrumentation/jetty-9/build.gradle
- dd-java-agent/instrumentation/jetty-9/src/main/java/datadog/trace/instrumentation/jetty10/DispatchableInstrumentation.java
- dd-java-agent/instrumentation/jetty-9/src/main/java_jetty10/datadog/trace/instrumentation/jetty10/DispatchableAdvice.java
The change in jetty was also applied on jetty 12.0.1, but we don't support AppSec on jetty-12 yet.
> Fix blocking for jetty 10.0.16 and 11.0.16

- dd-java-agent/instrumentation/akka-http-10.0/build.gradle
Tests rely on Akka + Akka HTTP, but latest Akka HTTP does not support Akka 2.9.0-M1 yet. So limiting tests to Akka 2.8.x at the moment.
> Fix IAST Akka tests for latest dependency versions

- dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
- dd-java-agent/src/test/groovy/datadog/trace/bootstrap/AgentBootstrapTest.groovy
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
When a user adds the tracer with `-javaagent` to `JAVA_TOOL_OPTIONS` that option will be picked up not only by any `java` command launched from that environment, but also short-lived JDK tools such as `jstack`, `javac` or `jcmd`. 
This PR stops the Java tracer from activating when we know we're attaching to a JDK tool run on Java 9 or later. Specifically it checks the `jdk.module.main` system property for modules under the `jdk.` namespace, which covers the majority of JDK tools that we want to skip.
Skipping these tools avoids potential log-spam such as reported in #5838
> Skip attaching the tracer when we know the JVM is running a JDK tool such as `jstack`

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkStructuredStreamingTest.groovy
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkTest.groovy
This PR introduce the `spark.sql` spans which are created whenever the SQL API is used
[Spark SQL](https://spark.apache.org/docs/latest/sql-programming-guide.html) is the higher level API to perform spark computation following the SQL standard. A Spark SQL query is then broken down by spark into multiple `spark.job` and `spark.stage`
The hierarchy of a spark.job span is now
```
spark.application | spark.batch | databricks.task depending on the environment where spark is running
\          |         /
[spark.sql] optional, only present if using spark-sql
|
spark.job
```
> Add Spark SQL spans

- dd-trace-core/src/main/java/datadog/trace/core/datastreams/MsgPackDatastreamsPayloadWriter.java
- dd-trace-core/src/test/groovy/datadog/trace/core/datastreams/DataStreamsWritingTest.groovy
Add version tag to data stream stats. This will help us track changes in throughput / latency during deployments.
> [data streams] Tag with version

- dd-java-agent/agent-jmxfetch/build.gradle
Main item of interest is a fix to avoid an exception if JMXFetch is just starting up, right as the JVM is shutting down:
https://github.com/DataDog/jmxfetch/releases/tag/0.47.10
> JMXFetch 0.47.10

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestSessionImpl.java
- dd-java-agent/agent-ci-visibility/src/testFixtures/groovy/datadog/trace/civisibility/CiVisibilityTest.groovy
Ensures that CI Visibility's test session spans always have `test.command` tag.
`test.command` is part of the session fingerprint - the set of tags that are used by CI Visibility backend to identify sessions.
Due to that the backend requires these tags to always be populated.
> Always populate test.command tag in session spans

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryContextInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14ContextTest.groovy
... otherwise when there's no active span leave the non-Datadog context in place.
> Only invalidate current OTel context if we created it

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/SignalServerRunnable.java
Fixes deadlock that can occur when `SignalServer` is stopped.
`SignalServer` that hangs while trying to stop prevents JVM from exiting.
`SignalServer` is used by CI Visibility for communication between the build system and the JVMs that are forked for tests execution.
The deadlock happened because the thread that stops the server was sending interruption signal, then waited for the server thread to finish, and only after it closed the selector used by the server.
The problem was that if selector was not closed, the server thread could simply ignore the interruption signal (if it was waiting for the `select()` method to return when the signal was received).
The fix is to add a 5-second timeout to the `select()` method, so that the interruption flag is checked at least once in 5 seconds.
> Fix deadlock occuring when stopping SignalServer

- dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
Fixes instrumentation for spring boot 2.7.5 
Maintenance bug fix for the new version of spring boot using a new class NonClosingStream that was in the instrumentation exclussion list.
> Fix request body tainting in spring boot 2.7.5

- gradle/dependencies.gradle
Updates the ddprof dependency to 0.76.0
https://github.com/DataDog/java-profiler/releases/tag/v_0.76.0
> Update ddprof to 0.76.0

- .github/CODEOWNERS
Updates CODEOWNERS to reflect ASM ownership 
This change ensures that asm-java is correctly requested for reviews in cases where apm-java was previously requested
> Update CODEOWNERS to reflect additional ASM ownership

- dd-trace-api/src/main/java/datadog/trace/api/IdGenerationStrategy.java
This PR introduce a minor fix for trace and span id generation.
The `RANDOM` generator generated number between `[1, 2^63-1[` instead of `[1, 2^63-1]`.
> Fix trace and span id generation

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpan.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
- dd-java-agent/instrumentation/spring-ws-2/src/main/java/datadog/trace/instrumentation/springws2/MethodEndpointInstrumentation.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
This PR brings support for _record exception_ event in OpenTelemetry Span API ([documentation](https://opentelemetry.io/docs/specs/otel/trace/api/#record-exception)). 
This should increase our compatibility with the OpenTelemetry API.
There are few limitation though:
* We will only keep one event (the last one),
* We will drop the event timestamp and attributes.
I also backported the new `setErrorFlag()` behavior to a past instrumentation that needed it (`spring-ws-2`).
> Add support for OpenTelemetry record exception span event

- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAdvice.java
- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceDecorator.java
- dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationsAsyncTest.groovy
- dd-java-agent/instrumentation/trace-annotation/src/test/java/dd/test/trace/annotation/SayTracedHello.java
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
This PR brings the asynchronous result type support from OpenTelemetry annotations (see #5593) to the original `@Trace` annotation.  
This should improve the generated span by having more precise span duration (span end will be at the end of the async operation).
As a behavior change, this is not the default behavior despite it should be closer of the expected behavior.
The feature must be enabled by setting `dd.trace.annotation.async` to `true`.
> Add asynchronous type support for trace annotation instrumentation

- internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityTypes.java
- internal-api/src/main/java/datadog/trace/api/iast/telemetry/IastMetric.java
- internal-api/src/test/groovy/datadog/trace/api/iast/telemetry/IastMetricCollectorTest.groovy
Add missing case for IAST wrapped spring response metric
> Fix spring response wrapped IAST metric

- telemetry/src/main/java/datadog/telemetry/dependency/LocationsCollectingTransformer.java
Logging each new protection domain while collecting dependencies led to long multi-line debug logs with mostly irrelevant information.
Old log:
```
[dd.trace 2023-09-18 15:28:40:334 +0000] [s0-admin-1] DEBUG datadog.telemetry.dependency.LocationsCollectingTransformer - Saw new protection domain: ProtectionDomain  (jar:file:/app/app.jar!/BOOT-INF/lib/netty-resolver-4.1.70.Final.jar!/ <no signer certificates>)
org.springframework.boot.loader.LaunchedURLClassLoader@4defd42
<no principals>
java.security.Permissions@23d0b9f5 (
("java.io.FilePermission" "/app/app.jar" "read")
)
```
New log:
```
[dd.trace 2023-09-18 15:23:41:196 +0000] [s0-admin-1] DEBUG datadog.telemetry.dependency.LocationsCollectingTransformer - New protection domain with location …
```
> Less verbose dependency collection debug logs

- dd-java-agent/agent-ci-visibility/build.gradle
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDBuildSystemModuleImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDBuildSystemSessionImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestFrameworkModuleProxy.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/TestModuleRegistry.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/ModuleExecutionResult.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/TestFramework.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/utils/SpanUtils.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ipc/ModuleExecutionResultTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ipc/SignalServerTest.groovy
- dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
- dd-smoke-tests/gradle/src/test/resources/datadog/smoketest/successMultiForks/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/datadog/smoketest/successMultiForks/settings.gradleTest
- dd-smoke-tests/gradle/src/test/resources/datadog/smoketest/successMultiForks/src/main/java/datadog/smoke/Calculator.java
- dd-smoke-tests/gradle/src/test/resources/datadog/smoketest/successMultiForks/src/test/java/datadog/smoke/TestSucceed.java
- dd-smoke-tests/gradle/src/test/resources/datadog/smoketest/successMultiForks/src/test/java/datadog/smoke/TestSucceedJunit5.java
- dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
- dd-trace-core/src/main/java/datadog/trace/civisibility/writer/ddintake/CiTestCycleMapperV1.java
Updates build system instrumentations to correctly handle cases when tests for a specific module are executed in multiple JVMs.
Also handles cases when tests for a specific module use different testing frameworks (this is orthogonal to multiple forks, can happen even if there is only one fork per module).
When tests for one module run in multiple forked JVMs, we want the reported module span to contain the aggregated data (that is, all the test frameworks used in all the forks, combined code coverage data from all the forks, the total number of tests skipped by ITR for all the forks, etc).
Depending on the build configuration it is possible to have multiple JVM forks started for the one module: in Gradle this is achieved with `maxParallelForks` or `forkEvery` properties of the `Test` …
> Correctly handle cases when there are multiple JVM forks per single test module

- dd-java-agent/instrumentation/spark/src/test/groovy/SparkStructuredStreamingTest.groovy
When there is a failure in spark, events can be out of order. Using the parameter `sortByName=true` so that the order does not matter for this test
> Fix Spark streaming flaky test

- dd-trace-core/src/test/groovy/datadog/trace/core/tagprocessor/PeerServiceCalculatorTest.groovy
- internal-api/src/main/java/datadog/trace/api/naming/v1/PeerServiceNamingV1.java
.... when the peer service value has been manually overridden by component
> Use _component_override for peer service source

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/iast/HeaderNameCallSite.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/iast/HttpHeaderSubclassesInstrumentation.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/iast/HttpRequestInstrumentation.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/iast/RequestContextInstrumentation.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/iast/helpers/TaintRequestContextFunction.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/iast/helpers/TaintRequestFunction.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/iast/helpers/TaintUriFunction.java
- dd-java-agent/instrumentation/pekko-http-1.0/src/main/java/datadog/trace/instrumentation/pekkohttp/iast/HeaderNameCallSite.java
- dd-java-agent/instrumentation/pekko-http-1.0/src/main/java/datadog/trace/instrumentation/pekkohttp/iast/HttpHeaderSubclassesInstrumentation.java
- dd-java-agent/instrumentation/pekko-http-1.0/src/main/java/datadog/trace/instrumentation/pekkohttp/iast/HttpRequestInstrumentation.java
- dd-java-agent/instrumentation/pekko-http-1.0/src/main/java/datadog/trace/instrumentation/pekkohttp/iast/RequestContextInstrumentation.java
- dd-java-agent/instrumentation/pekko-http-1.0/src/main/java/datadog/trace/instrumentation/pekkohttp/iast/helpers/TaintRequestContextFunction.java
- dd-java-agent/instrumentation/pekko-http-1.0/src/main/java/datadog/trace/instrumentation/pekkohttp/iast/helpers/TaintRequestFunction.java
- dd-java-agent/instrumentation/pekko-http-1.0/src/main/java/datadog/trace/instrumentation/pekkohttp/iast/helpers/TaintUriFunction.java
- internal-api/src/main/java/datadog/trace/api/iast/propagation/PropagationModule.java
Removes direct references to `Taintable` from advices
There are cases where we might not be able to introduce the interface (e.g. already loaded classes). So it's better to let the propagation module handle the taint logic.
> Remove direct references to Taintable from advices

- .circleci/config.continue.yml.j2
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- telemetry/src/main/java/datadog/telemetry/BatchRequestBuilder.java
- telemetry/src/main/java/datadog/telemetry/BufferedEvents.java
- telemetry/src/main/java/datadog/telemetry/EventSink.java
- telemetry/src/main/java/datadog/telemetry/EventSource.java
- telemetry/src/main/java/datadog/telemetry/HostInfo.java
- telemetry/src/main/java/datadog/telemetry/RequestBuilder.java
- telemetry/src/main/java/datadog/telemetry/TelemetryRequest.java
- telemetry/src/main/java/datadog/telemetry/TelemetryRequestState.java
- telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java
- telemetry/src/main/java/datadog/telemetry/TelemetryService.java
- telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
- telemetry/src/main/java/datadog/telemetry/api/RequestType.java
- telemetry/src/test/groovy/datadog/telemetry/BufferedEventsSpecification.groovy
- telemetry/src/test/groovy/datadog/telemetry/RequestBuilderSpecification.groovy
- telemetry/src/test/groovy/datadog/telemetry/TelemetryRequestStateSpecification.groovy
- telemetry/src/test/groovy/datadog/telemetry/TelemetryRunnableSpecification.groovy
- telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
- telemetry/src/test/groovy/datadog/telemetry/TestHttpClient.groovy
Adjustments for Telemetry V2 protocol.
Add app-started product info (appsec, profiler).
Retry app-started for limited number of times (3), and every heartbeat interval until it's been successfully sent.
Message-batching and message buffering for retries on next heartbeat interval as required by RFC. When sending a request fails it keeps unsent data till the next heartbeat interval for a retry. If it fails again we discard data.
Telemetry V2 implementation.
System-tests use this version: https://github.com/DataDog/system-tests/pull/1551
> Telemetry v2 and message-batching

- .github/workflows/draft-release-notes-on-tag.yaml
Fix a crash when generating a release changelog with community contribution.
> Fix changelog generation crash on community contribution

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/PortUtils.java
Small clean up of Java 7 support leftovers.
> Use process.isAlive() in PortUtils

- dd-java-agent/agent-bootstrap/src/main/resources/META-INF/native-image/com.datadoghq/dd-java-agent/reflect-config.json
This avoids the following exception when running a native-image that uses Netty-Reactor:
```
Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.<init>()
at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:345) ~[na:na]
at java.base@17.0.6/java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:223) ~[na:na]
at java.base@17.0.6/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085) ~[na:na]
at java.base@17.0.6/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114) ~[na:na]
```
One of the helper classes in the Netty integration uses `GenericClassValue.constructing(ConcurrentHashMap.class)`
> Register that we will reflect on ConcurrentHashMap constructor at runtime

- dd-java-agent/agent-ci-visibility/build.gradle
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilitySystem.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDBuildSystemModuleImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDBuildSystemSessionImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestFrameworkModuleImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ModuleExecutionSettingsFactoryImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/PackageResolver.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/PackageResolverImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/PackageTree.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndex.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexBuilder.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexSourcePathResolver.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/index/PackageResolverImplTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/index/RepoIndexSourcePathResolverTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/index/RepoIndexTest.groovy
- dd-java-agent/agent-ci-visibility/src/testFixtures/groovy/datadog/trace/civisibility/CiVisibilityTest.groovy
- dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleBuildListener.java
- dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleProjectConfigurator.groovy
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenInstrumentation.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenLifecycleParticipant.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenProjectConfigurator.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenTestExecution.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenUtils.java
- dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
- dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/main/java/datadog/trace/api/civisibility/config/ModuleExecutionSettings.java
Automatically computes the list of packages that should be instrumented with Jacoco when automatic Jacoco plugin injection is used (whenever build system instrumentation detects that code coverage is enabled).
Previously the customers were required to configure the list of packages by hand (which might not be trivial, depending on the project) or allow Jacoco to instrument all the packages (which can lead to significant performance overhead).
The data about which packages to instrument is retrieved from repository index.
> Automatically configure list of packages for Jacoco instrumentation

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestFrameworkModule.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestFrameworkModuleImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestFrameworkModuleProxy.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestSuiteImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestEventsHandlerImpl.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/DDTestImplTest.groovy
- dd-java-agent/agent-ci-visibility/src/testFixtures/groovy/datadog/trace/civisibility/CiVisibilityTest.groovy
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnit5ItrInstrumentation.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnitPlatformLauncherUtils.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnitPlatformUtils.java
- dd-java-agent/instrumentation/junit-5.3/src/test/groovy/CucumberTest.groovy
- dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
- dd-java-agent/instrumentation/junit-5.3/src/test/groovy/SpockTest.groovy
- dd-java-agent/instrumentation/junit-5.3/src/test/groovy/org/example/TestSucceedSpockUnskippable.groovy
- dd-java-agent/instrumentation/junit-5.3/src/test/groovy/org/example/TestSucceedSpockUnskippableSuite.groovy
- dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestSucceedCucumberUnskippable.java
- dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestSucceedCucumberUnskippableSuite.java
- dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestSucceedUnskippable.java
- dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestSucceedUnskippableSuite.java
- dd-java-agent/instrumentation/junit-5.3/src/test/resources/org/example/cucumber/calculator/basic_arithmetic_unskippable.feature
- dd-java-agent/instrumentation/junit-5.3/src/test/resources/org/example/cucumber/calculator/basic_arithmetic_unskippable_suite.feature
- internal-api/src/main/java/datadog/trace/api/civisibility/InstrumentationBridge.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java
Implements a mechanism to mark tests as "unskippable" for CI Visibility Intelligent Test Runner.
This PR only contains implementation for JUnit 5, other frameworks will be covered in later pull-requests.
Having the ability to instruct Intelligent Test Runner to never skip a specific test is a feature requested by the customers.
> Imlpement ITR unskippable tests for JUnit 5

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
- dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java
When it detects the tracer running in AWS Lambda, refuse to start the profiler.
Profiling is not yet supported in Java in AWS Lambda. Node and Python though are currently in public beta. We are specifically not charging customers in this public beta. However, if a customer were to turn on profiling with the java tracer, they would be billed. We want to prevent the situation where the customer is billed for profiles created in serverless environments.
> Do not start profiler if running in AWS Lambda.

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDBuildSystemModule.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDBuildSystemModuleImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDBuildSystemSessionImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/TestModuleRegistry.java
Fixes module coverage percentage calculation issue.
Module coverage percentage should be calculated based only on the tests that were run as part of that module.
Percentage calculation should be reproducible and the value should not depend on the timing of individual modules execution.
The issue was caused by the fact that module and session objects were sharing `ExecutionData` instances that were stored in their `ExecutionDataStore`s.
Whenever data was updated in the session if, for instance a Module B finished, this update could propagate to Module A because Module A and session shared their state.
> Fix module coverage calculation issue where data from one module could influence data from another module

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/messaging/DatadogAttributeParser.java
- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/MessageExtractAdapter.java
- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/SqsClientTest.groovy
- dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/MessageExtractAdapter.java
- dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/SqsClientTest.groovy
- dd-java-agent/instrumentation/spring-messaging-4/src/main/java/datadog/trace/instrumentation/springmessaging/SpringMessageExtractAdapter.java
- dd-java-agent/instrumentation/spring-messaging-4/src/test/groovy/SpringListenerSQSTest.groovy
- dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
- dd-trace-core/src/test/groovy/datadog/trace/core/datastreams/DefaultPathwayContextTest.groovy
The `_datadog` message attribute is used by DSM and certain language tracers to propagate context instead of AWS' `AWSTraceHeader`. The attribute contains trace context as a JSON string, or encoded with Base64 as a binary value.
> Extract trace context from embedded SQS message attribute '_datadog'

- communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
Replace catch `Throwable` to `Exception`
Avoid NPE when no config in agent response on `/info`
> Fix NPE when there is no config in agent response

- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/iast/TaintableRedefinitionStrategyListener.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/iast/TaintableVisitor.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/iast/MrReturnAdvice.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/iast/TaintableVisitorTest.groovy
- dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/bytebuddy/LoadedTaintableClass.java
Introduces a new `AgentBuilder.RedefinitionStrategy.Listener` to disable our `datadog.trace.agent.tooling.bytebuddy.iast.TaintableVisitor` in cases of a failure while retransforming already loaded classes.
Since classes are retransformed in batches, a failure transforming a class with the visitor might cause the whole batch to fail. This PR ensures that the taintable visitor will be disabled and a new attempt at retransformation will occur.
> Add redefinition listener to disable taintable visitor in case of failure

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitClient.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitDataUploaderImpl.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/tree/GitClientTest.groovy
Updates Git repository unshallowing logic in CI Visibility:
- if HEAD points to a commit that does not exist in the remote repo, an attempt is made to calculate the HEAD of the tracked upstream branch and unshallow from that
- if current local branch does not track any remote branch, or if HEAD is detached, no SHA is specified for unshallowing, that is all the commit data is checked out from the remote repo
The command that is used for unshallowing currently has a drawback: if the local HEAD is a commit that has not been pushed to the remote, it will fail.
If that happens, the tracer should fall back to another command that will attempt to use the tracked branch for the current branch in order to unshallow.
It could be that the CI is working on a detached HEAD or maybe branch tracking …
> Update Git unshallow logic to handle cases when HEAD points to a local-only commit

- dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogHttpCodec.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/HaystackHttpCodec.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/W3CHttpCodec.java
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpInjectorTest.groovy
This will prevent encoding the baggage into HTTP header using the `application/x-www-form-urlencoded` MIME type format but use the W3C baggage RFC instead.
This will increase compatibility by using the right encoding.
The new encoding is compatible of the current decoding so no compatibility flag was introduce to restore the old behavior.
> Fix baggage HTTP header encoding

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestEventsHandlerImpl.java
- dd-java-agent/instrumentation/junit-4.10/cucumber/src/main/java/datadog/trace/instrumentation/junit4/JUnit4CucumberItrInstrumentation.java
- dd-java-agent/instrumentation/junit-4.10/cucumber/src/test/groovy/CucumberTest.groovy
- dd-java-agent/instrumentation/junit-4.10/cucumber/src/test/java/org/example/cucumber/TestSucceedCucumberUnskippable.java
- dd-java-agent/instrumentation/junit-4.10/cucumber/src/test/java/org/example/cucumber/TestSucceedCucumberUnskippableSuite.java
- dd-java-agent/instrumentation/junit-4.10/cucumber/src/test/resources/org/example/cucumber/calculator/basic_arithmetic_unskippable.feature
- dd-java-agent/instrumentation/junit-4.10/cucumber/src/test/resources/org/example/cucumber/calculator/basic_arithmetic_unskippable_suite.feature
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Instrumentation.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4ItrInstrumentation.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Utils.java
- dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
- dd-java-agent/instrumentation/junit-4.10/src/test/java/org/example/TestSucceedUnskippable.java
- dd-java-agent/instrumentation/junit-4.10/src/test/java/org/example/TestSucceedUnskippableSuite.java
Implements a mechanism to mark JUnit 4 tests as "unskippable" for CI Visibility Intelligent Test Runner.
Having the ability to instruct Intelligent Test Runner to never skip a specific test is a feature requested by the customers.
> Imlpement ITR unskippable tests for JUnit 4

- .circleci/config.continue.yml.j2
- .circleci/render_config.py
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/MetricProbesIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ProbeStateIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ServerAppDebuggerIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SpanDecorationProbesIntegrationTests.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SpanProbesIntegrationTest.java
skip tests that requires accessing arguments/local vars
fix flakiness of probe statuses and sending probe config
> Fix smoke tests for J9 JVMs

- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/AsyncCommandInstrumentation.java
- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/CommandHandlerInstrumentation.java
- dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5AsyncClientTest.groovy
- dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ReactiveClientTest.groovy
Currently lettuce spans don't propagate to where the network IO is done, which prevents us from attributing CPU samples to the decoding loop, and prevents wallclock sampling of the event loop at all. This pair of instrumentations solves this problem by attaching the active span to an `AsyncCommand` when it is created (the existing `LettuceAsyncCommandsInstrumentation` currently creates the span before this happens). The `CommandHandler` processes commands and is made to reactivate the span by the `CommandHandlerInstrumentation`. 
This has no functional impact on traces, but allows for better attribution of resource consumption to the trace.
> propagate span into lettuce CommandHandler event loop

- dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/ChannelFutureListenerInstrumentation.java
- dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/NettyChannelPipelineInstrumentation.java
- dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/server/BlockAllWritesHandler.java
- dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/server/BlockingResponseHandler.java
- dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/server/NettyHttpServerDecorator.java
- dd-java-agent/instrumentation/play-2.3/src/test/groovy/datadog/trace/instrumentation/play23/test/client/PlayWSClientTest.groovy
- dd-java-agent/instrumentation/play-2.3/src/test/groovy/datadog/trace/instrumentation/play23/test/server/PlayAsyncServerTest.groovy
- dd-java-agent/instrumentation/play-2.3/src/test/groovy/datadog/trace/instrumentation/play23/test/server/PlayServerTest.groovy
- dd-java-agent/instrumentation/play-2.3/src/test/scala/datadog/trace/instrumentation/play23/test/server/AsyncServer.scala
- dd-java-agent/instrumentation/play-2.3/src/test/scala/datadog/trace/instrumentation/play23/test/server/ControllerClosureAdapter.scala
- dd-java-agent/instrumentation/play-2.3/src/test/scala/datadog/trace/instrumentation/play23/test/server/Settings.scala
- dd-java-agent/instrumentation/play-2.3/src/test/scala/datadog/trace/instrumentation/play23/test/server/SyncServer.scala
The problem shows with play 2.3. After committing the blocking response and throwing BlockingExcpetion, another response is produced by the Play handler. So suppress this response. There was also a missing call to mark the future as completed.
> Fix blocking in netty 3.8

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/communication/BackendApiFactory.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/communication/IntakeApi.java
- dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
- dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
Removes application key header from requests that are made to CI Visibility endpoints.
The endpoints have been updated recently, and the API key is no longer required.
> Remove application key header from settings and ITR requests

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/shutdown/ShutdownHelper.java
- telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java
- telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
- telemetry/src/test/groovy/datadog/telemetry/TelemetryRunnableSpecification.groovy
- telemetry/src/test/groovy/datadog/telemetry/TelemetrySystemSpecification.groovy
Ensures that pending telemetry data is sent to the backend before JVM shuts down.
Current telemetry implementation reports aggregated metrics in periodic requests.
Telemetry-reporting loop runs in a daemon thread, so when the JVM shuts down metrics data that was queued since the last request gets discarded.
Loosing a few seconds' worth of metrics data may be fine for APM use cases, where it is not uncommon for a JVM to run for several days.
Future PRs will introduce telemetry metrics for CI Visibility.
Since the lifetimes of JVMs instrumented with CI Visibility are very different (it is typical for the process to live for a few minutes or even seconds), there is a need to flush pending telemetry data before shutting down the JVM.
This may also be beneficial for serverless setups where …
> Flush telemetry data on JVM shutdown

- dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/DebuggerTestApplication.java
- dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/ServerDebuggerTestApplication.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/MetricProbesIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SpanProbesIntegrationTest.java
add smoke tests for log probes snapshot & dynamic logs with default sampling and custom one
> Add sampling smoke tests for log probes

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/WellKnownClasses.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/LenExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/ListValue.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/MapValue.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/SerializerWithLimits.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/StringTokenWriterTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot24.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot26.java
we are preventing to call on unsafe implementation. We are limiting to JDK implementation first.
Collection and Map interfaces can be implemented by anyone and therefore may not be safe to call. example: persistent layer that load lazily large amount of rows from DB.
> Prevent calling size method from unknown classes

- dd-java-agent/appsec/build.gradle
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/api/security/ApiSecurityRequestSampler.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/CurrentAppSecConfig.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/KnownAddresses.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/api/security/ApiSecurityRequestSamplerTest.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/data/KnownAddressesSpecification.groovy
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Added data classification for Api Security. In addition, the schema extraction processor also take advantage of the data scanners to determine he classification of each value.
Also added sampler to reduce overhead. We assume that schema extraction and data classification will be performed for only 10% of requests.
Added env variable `DD_API_SECURITY_REQUEST_SAMPLE_RATE` to define Api Security request sampling rate. The value should be in range `0.0 - 1.0`. Where `0.0` - means 0% requests will be sampled, and `1.0` means 100% requests will be sampled.
Default value sampling rate for ApiSecurity is `0.1` (e.g. 10% or requests)
> Added Api Security request data classification

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy
- remote-config/src/main/java/datadog/remoteconfig/tuf/RemoteConfigRequest.java
Added Trusted IPs capability.
Organizations often require that their security tools provide a way to specify and manage a list of trusted IP addresses, primarily to reduce outage from blocking on false positives or true positives or misconfigurations.
> Added trusted IPs protocol

- dd-java-agent/instrumentation/akka-http-10.0/build.gradle
Limits the versions of latestDepTests for akka-http.
Java 8 has been dropped from the latest akka-http: https://github.com/akka/akka-http/releases/tag/v10.6.0-M1
> Limit akka-http version for latestDepTests following dropping of Java 8

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/HttpHeader.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/HttpResponseHeaderModuleTest.groovy
- dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastServerSmokeTest.groovy
- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
Fix the header string for the X-Content-Type-Options vulnerability detection
The functionality wasn't working
> Fix the X-Content-Type-Options header string

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
Fixes the enablement logic for the wallclock profiler, which was broken in #5583.
> fix wallclock profiler enablement logic

- gradle/dependencies.gradle
Contains miscellaneous minor bug fixes
> Upgrade to ddprof 0.79.0

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/EvidenceAdapter.java
- dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite.yml
Fixes issue while redacting consecutive tainted values, previous implementation was repeating the tainted values after the redaction.
> [APPSEC-11378] Fix issue redacting consecutive tainted values

- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/BooleanValueExpressionAdapter.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/DSL.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/JsonToExpressionConverter.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/BooleanValueExpressionAdapterTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogMessageTemplateBuilderTest.java
- dd-java-agent/agent-debugger/src/test/resources/test_log_probe.json
Add support of any predicate or boolean expression inside a log template message is evaluated as 'true' or 'false' by converting this expression as value expression with an adapter
Refactor the parsing of the DSL to support all boolean functions
Support having a boolean expression inside a log template parameter liek `{contains(arg, 'foo')}`
> Fix boolean expression eval as template parameter

- .gitlab-ci.yml
Uses the correct gitlab name for the build job so that reliability environment deployment can download the artifacts.
The scheduled build uses a job named `build_with_cache` but the relenv deployment always tried to download the artifacts from the `build` job.
We now use an environment variable to propagate the proper name.
> Use correct job name for gitlab relenv deploy

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkStructuredStreamingTest.groovy
Rename `spark.batch` operation name to `spark.streaming_batch`. This is a breaking change that is already done in the backend.
It’s not clear that spark.batch is a spark stream operation. By using streaming_batch we match the [spark streaming listener terminology and make it clear it’s a stream](https://spark.apache.org/docs/2.2.1/api/java/org/apache/spark/streaming/scheduler/StreamingListener.html)
> Rename operation name spark.batch to spark.streaming_batch

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/QueueTimerHelper.java
- dd-java-agent/instrumentation/netty-concurrent-4/src/test/groovy/TimingTest.groovy
Because the profiler's TSC hacks into JFR, it can read the frequency before it has been initialised, and get a default value instead, which is then saved into a constant. This delays recording queue time until JFR has been initialised, so we won't read the frequency before it's available.
> do not record queue time before JFR is initialised

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkTest.groovy
Add a default databricks service, if not set by the user based on
- the databricks `RunName` [available for job clusters](https://docs.databricks.com/en/administration-guide/account-settings/usage-detail-tags.html)
- the databricks cluster name for all other cases
If not set by the user, the service name is inferred by the tracer using the class name that was launched. For databricks this name is always `com.databricks.backend.daemon.driver.driverdaemon` which is not very informative
> Add Databricks default service name if not set by the user

- .github/workflows/draft-release-notes-on-tag.yaml
This will remove tags from PR titles when generating release changelog.
JIRA / PR tracking conflict with PR title conventions.
> Remove tags from PR titles in release notes

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/ProbeStatusSink.java
- dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/TestApplicationHelper.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/MetricProbesIntegrationTest.java
Application in test wait for a timeout instead of uploads
> Fix flaky metric smoke tests

- dd-trace-api/build.gradle
- dd-trace-api/src/main/java/datadog/trace/api/experimental/DataStreamsCheckpointer.java
- dd-trace-api/src/main/java/datadog/trace/api/experimental/DataStreamsContextCarrier.java
- dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsMonitoring.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentDataStreamsMonitoring.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Modified the DSM API to allow adding consumer checkpoints for kinesis. Where we don't have a full pathway context but only have a timestamp
> [AIT-8165] Add DSM API changes to support kinesis use case

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sensitive/SensitiveHandlerImpl.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sensitive/TaintedRangeBasedTokenizer.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/Ranged.java
- dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite.yml
Add new TaintedRangeBasedTokenizer to XSS vulnerability
redact IAST XSS Vulnerability
TaintedRangeBasedTokenizer involves redact everything in the evidence value that is not within a range
`dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite.yml` is really helpful to understand the behaviour
> Add tainted range based redaction for XSS vulnerabilities

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/ProbeRateLimiter.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
Apply rate limit for a probe before applying configuration change
that generate instrumentation and retransformation because execution
of the new instrumented code can happen before rate limit settings
are applied and then create default (snapshot ones) rate limit.
Fix flaky sampling smoke tests
> Fix race condition for applying probe rate limits 

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelExtractedContext.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpan.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/propagation/AgentTextMapPropagator.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/propagation/OtelContextPropagators.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/ContextTest.groovy
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/AbstractPropagatorTest.groovy
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/AgentPropagatorTest.groovy
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/B3MultiPropagatorTest.groovy
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/B3SinglePropagatorTest.groovy
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/DatadogPropagatorTest.groovy
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/OtelW3cPropagatorTest.groovy
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/W3cPropagatorTest.groovy
This PR brings the support for the OpenTelemetry context propagator API.
Previously, getting the context propagator from the GlobalOpenTelemetry would return a noop propagator, leading to the loss of context while trying to propagate it.
The returned propagator is now be based on the agent internal propagator. 
I start refactoring the OTel instrumentation by creating package dedicated to the different APIs for the new instrumentation parts. I will keep refactoring the rest of the instrumentation in a dedicated PR.
The test `test parent span using active span` was broken by https://github.com/DataDog/dd-trace-java/pull/5880 and need to be fixed in another PR too. It should be fixed with #5970.
> Add OpenTelemetry context propagator instrumentation support

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
Add the spark streaming metric `spark.event_time.watermark_gap` corresponding to the gap between batch timestamp and global watermark for the batch
Expose the same metric as in the Spark UI https://github.com/apache/spark/blob/v3.5.0/sql/core/src/main/scala/org/apache/spark/sql/streaming/ui/StreamingQueryStatisticsPage.scala#L181
> Add spark streaming watermark gap metric

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
- dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/MultipartInstrumentation.java
- dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/MultipartInstrumentationForkedTest.groovy
- dd-java-agent/instrumentation/servlet/request-3/src/test/java/foo/bar/smoketest/MockPart.java
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaMultipartInstrumentation.java
- dd-java-agent/instrumentation/servlet/request-5/src/test/groovy/JakartaMultipartInstrumentationTest.groovy
- dd-java-agent/instrumentation/servlet/request-5/src/test/java/foo/bar/smoketest/MockPart.java
- dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
- internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
- internal-api/src/main/java/datadog/trace/api/iast/source/WebModule.java
Adds instrumentation for Multipart headers so they can be tainted for IAST use
To cover all of the possible tainted object sources.
> Add multipart support as IAST source for servlet

- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java
Increase the range for accepted snapshots
Flaky tests
> Fix flaky sampling test

- buildSrc/build.gradle.kts
- buildSrc/src/test/groovy/InstrumentPluginTest.groovy
- gradle/dependencies.gradle
Changes since we last updated byte-buddy:
* Correctly read versions from class file that would use both bytes.
* Correct field and static method access on subtypes in MemberSubstitution.
* Correctly read minor version from class file.
* Add PatchMode.SUBSTITUTE and ResettableClassFileTransformer.Substitutable for in-order patching.
* Allow for explicit specification of differential matcher when patching an AgentBuilder.
* Correctly resolve accessors for fields with capitalized first letter.
This PR also updates ASM to 9.6
> byte-buddy 1.14.8

- dd-java-agent/instrumentation/osgi-4.3/src/main/java/datadog/trace/instrumentation/osgi43/BundleReferenceInstrumentation.java
- dd-java-agent/instrumentation/osgi-4.3/src/main/java/datadog/trace/instrumentation/osgi43/BundleWiringHelper.java
When tracing a library we often need to inject a helper type into its class-loader. Occasionally when a library is deployed across multiple OSGi bundles the helper being injected may need to refer to a super-type that isn't imported. This is usually because the bundle being injected doesn't directly use the super-type, it only uses sub-types exported from a different package. The super-type is in a separate bundle indirectly used by the original bundle, but its package is not accessible due to modularity rules.
When this happens the tracer must temporarily bypass these modularity rules to access that super-type. Previously the tracer did this by searching all direct bundle dependencies for the type. However in rare circumstances this can lead to loader constraint issues.
For example, an …
> Use package prefix to direct search for helper dependencies in OSGi

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java
…when resolving a type without a classfile resource
This avoids the following rare exception on GlassFish:
```
java.lang.LinkageError: loader org.apache.jasper.servlet.JasperLoader@...
attempted duplicate class definition...
```
> Skip falling back to 'org.apache.jasper.servlet.JasperLoader.loadClass'

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecoratorTest.groovy
- dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpServerInstrumentationTest.groovy
- dd-java-agent/instrumentation/akka-http-10.0/src/lagomTest/groovy/LagomTest.groovy
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpServerDecorator.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpServerHeaders.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/appsec/ConfigProvideRemoteAddressHeaderInstrumentation.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/appsec/FormDataToStrictInstrumentation.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/appsec/JacksonUnmarshallerInstrumentation.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/appsec/MultipartUnmarshallersInstrumentation.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/appsec/PredefinedFromEntityUnmarshallersInstrumentation.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/appsec/SprayUnmarshallerInstrumentation.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/appsec/StrictFormCompanionInstrumentation.java
- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/appsec/UnmarshallerHelpers.java
- dd-java-agent/instrumentation/play-2.6/src/test/groovy/server/PlayServerTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
- internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java
* Provide peer information on akka-http.
* Fix body interception after StrictForm unmarshaller fails.
* Filterout synthetic headers.
* Report content-{length,type} for strict entities.
> Fix  AppSec-related problems in akka-http

- benchmark/load/insecure-bank/benchmark.json
- benchmark/startup/insecure-bank/benchmark.json
- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/CombiningTransformerBuilder.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/iast/IastPostProcessorFactory.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/iast/IastPostProcessorFactoryTest.groovy
- dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/iast/IastAnnotatedAdvice.java
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/TemplateAndMatrixVariablesInstrumentation.java
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/TemplateVariablesUrlHandlerInstrumentation.java
- dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java/datadog/trace/instrumentation/springweb6/TemplateAndMatrixVariablesInstrumentation.java
- dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java/datadog/trace/instrumentation/springweb6/TemplateVariablesUrlHandlerInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/RouteImplInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RouteImplInstrumentation.java
Adds a `net.bytebuddy.asm.Advice.PostProcessorFactory` to generate the required code to provide IAST related metrics in bytebuddy advices. 
The post processor does two things:
- Calls `IastMetricCollector.add(IastMetric.INSTRUMENTED_$TYPE, $TAG, 1)` whenever a new instrumentation point is detected.
- Injects the required bytecode to call `IastMetricCollector.add(IastMetric.EXECUTED_$TYPE, $TAG, 1)` when the actual code of the advice is executed at runtime.
From the IAST part we need very concrete metrics to understand if the vulnerability detection engine is working correctly. Having these kind of metrics allows us to check if customer spans that have certain operations (for instance a SQL call) are handled correctly by the engine.
> Add telemetry to IAST advices

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
- dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
- dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
- dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletRequestCallSiteTest.groovy
- dd-java-agent/instrumentation/servlet/src/test/java/datadog/smoketest/controller/TestHttpServletRequestCallSiteSuite.java
- dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
- internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
- internal-api/src/main/java/datadog/trace/api/iast/source/WebModule.java
Added instrumentation for getRequestURI, getPathTranslated and getPathInfo in ServletRequest 
To cover all of the cases where intput needs to be tainted in order to detect vulnerabilities.
> Support servlet getRequestURI/getPathTranslated/getPathInfo as IAST sources

- dd-trace-ot/build.gradle
`DDTracer` uses `Functions.UTF8_ENCODE` when creating spans. `Functions` is currently excluded from relocation while `UTF8BytesString` which it depends on is relocated. This can lead to class-cast issues when attaching `dd-java-agent` and `dd-trace-ot` even when automatic tracing is explicitly disabled.
A similar issue can occur with the `Endpoint*` internal API so we also relocate that.
An alternative solution would have been to not relocate the `datadog.trace.bootstrap.instrumentation.api` package. But that then exposes more of the internal API, which could potentially lead to similar class-cast issues later on.
Note: the solution here is more complicated than it would have been if we didn't put `internal-api` types such as `datadog.trace.ap.iFunctions` in the same package as …
> Make sure internal 'datadog.trace.api.Functions' class is relocated in dd-trace-ot

- .circleci/start_docker_autoforward.sh
Forcefully downgrades the `urllib3` python dependency used by the testcontainer tunnels to `1.x` to avoid failures and test timeouts.
https://github.com/docker/docker-py/issues/3113
> Donwgrade urllib3 to work around testcontainer tunnel timeouts

- .circleci/config.continue.yml.j2
- .circleci/start_docker_autoforward.sh
Locks down the version of the `dd-trace-java-docker-build` image in a few places that was missing it. Also removes the `urllib3` downgrade workaround from #6015 
Using the versioned images makes sure that we don't get accidental breakage from newer releases of the tools in the image.
> Lock down CircleCI build images and remove workaround

- dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsMonitoring.java
Avoid calling `inbox.clear()` from the producer side when shutting down DSM, as it might block
First reported in https://github.com/DataDog/dd-trace-java/issues/6010
> Avoid potential blocking operation on tracer shutdown

- .github/CODEOWNERS
Makes all `**/appsec/` directories owned by `@DataDog/asm-java`
Make it easier to see relevant changes for APM Java Core team.
> Change code owner of appsec directories

- dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/AnnotationSubstitutionProcessorInstrumentation.java
- dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/Target_org_jctools_counters_FixedSizeStripedLongCounterFields.java
- dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/Target_org_jctools_util_UnsafeRefArrayAccess.java
Adds Graal `RecomputeFieldValue` for the required jctools so native image works correctly.
All projects that uses it (netty, quarkus) already does the same thing for the shaded classes (eg.: https://github.com/quarkusio/quarkus/blob/6a38570b295b4f696a39da0c6cf27ab90f81431f/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/graal/UnsafeRefArrayAccess.java#L8 && https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/svm/UnsafeRefArrayAccessSubstitution.java ) .
Fixes: https://github.com/DataDog/dd-trace-java/issues/6019
> Add Graal Native image support for jctools

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/ProbeRateLimiter.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
- dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/ServerDebuggerTestApplication.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ServerAppDebuggerIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SpanDecorationProbesIntegrationTests.java
As span decoration probes are sharing the same instrumented code than Log probes, we also evaluate the sampling during the execution which does not bring any value in the case of Span decoration probes. We set the rate limiter for span decoration probe to a constant one.
Jira ticket: [DEBUG-1767]
[DEBUG-1767]: https://datadoghq.atlassian.net/browse/DEBUG-1767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Disable sampling for span decoration probe

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
Allows the user to set `-Ddd.profiling.ddprof.linenumbers=false` to omit linenumbers, which can reduce overhead. Line numbers are on by default and this is unlikely to change.
Jira ticket: [PROF-8363]
[PROF-8363]: https://datadoghq.atlassian.net/browse/PROF-8363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> expose omit linenumbers mode for profiler

- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceDecorator.java
- dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationsTest.groovy
- dd-java-agent/instrumentation/trace-annotation/src/test/java/dd/test/trace/annotation/SayTracedHello.java
- dd-trace-api/src/main/java/datadog/trace/api/Trace.java
This is the annotation equivalent of building a new span with no parent context.
> Support `@Trace(noParent=true)` to always start a new trace at that method

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/AwsCodePipelineInfo.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/CIProviderInfoFactory.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ci/AwsCodePipelineInfoTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/resources/ci/awscodepipeline.json
Adds support for AWS CodePipeline CI provider.
Some metadata is extracted from available environment variables.
Jira ticket: [CIAPP-786]
[CIAPP-786]: https://datadoghq.atlassian.net/browse/CIAPP-786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add support for AWS CodePipeline CI provider

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitClient.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitDataUploaderImpl.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/tree/GitClientTest.groovy
Fixes logic that gets upstream branch reference to return commit SHA which corresponds to the last commit in the branch, rather than the branch name.
Previous version of the logic returned branch in the form of `upstream/branch` - e.g. `origin/master` - and this form cannot be used by `git fetch` command.
Jira ticket: [CIAPP-7835]
[CIAPP-7835]: https://datadoghq.atlassian.net/browse/CIAPP-7835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix getting upstream branch name for unshallowing

- dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/HttpUrlConnectionInstrumentation.java
It overrides `connect`, `getInputStream`, and `getOutputStream` without delegating
Jira ticket: [APMS-10509]
[APMS-10509]: https://datadoghq.atlassian.net/browse/APMS-10509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add `weblogic.net.http.HttpURLConnection` to list of traced connection classes

- dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/HttpUrlConnectionInstrumentation.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
We have a short list of instrumented `HttpURLConnection` types which most implementations delegate to. Occasionally an application server might register its own `HttpURLConnection` that doesn't delegate upwards, but instead calls a completely different service. This feature will allow users to temporarily add such an implementation for tracing without needing a new release of the tracer.
```
DD_TRACE_HTTP_URL_CONNECTION_CLASS_NAME=<fully.qualified.class.name>
```
System property equivalent:
```
-Ddd.trace.http.url.connection.class.name=<fully.qualified.class.name>
```
Jira ticket: [APMS-10509]
[APMS-10509]: https://datadoghq.atlassian.net/browse/APMS-10509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Support tracing of custom (non-JDK) HttpURLConnection implementations

- communication/src/main/java/datadog/communication/monitor/DDAgentStatsDConnection.java
- dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Adds support for configuration of StatsD client queue size:
```
DD_STATSD_CLIENT_QUEUE_SIZE=<items>
```
as well as buffer size and timeout when using UDS:
```
DD_STATSD_CLIENT_SOCKET_BUFFER=<bytes>
DD_STATSD_CLIENT_SOCKET_TIMEOUT=<ms>
```
System property equivalents:
```
-Ddd.statsd.client.queue.size=<items>
-Ddd.statsd.client.socket.buffer=<bytes>
-Ddd.statsd.client.socket.timeout=<ms>
```
Jira ticket: [APMS-10560]
[APMS-10560]: https://datadoghq.atlassian.net/browse/APMS-10560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Support StatsD client tuning

- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/test/groovy/SparkStructuredStreamingTest.groovy
Rename spark streaming query attributes to make it clear that it is coming from a streaming query
- id -> streaming_query.id
- name -> streaming_query.name
- run_id -> streaming_query. run_id
- batch_id -> streaming_query.batch_id
The renaming is already done in the backend
Make it clear that those fields are coming from the streaming_query
> Rename spark streaming query attributes

- dd-java-agent/build.gradle
- dd-java-agent/instrumentation/build.gradle
- dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/ResourcesFeatureInstrumentation.java
This will let us relocate some dependencies used by the tracer without affecting instrumentation for the same libraries.
> Move dd-trace-core to separate section of shaded dd-java-agent jar

- telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java
- telemetry/src/main/java/datadog/telemetry/dependency/DependencyService.java
- telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverSpecification.groovy
- telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyServiceSpecification.groovy
Fixes an exception converting spaced paths for discovered dependencies:
```
java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/IBM/WebSphere/AppServer_1/plugins/com.ibm.cds_2.1.0.jar
at java.net.URI$Parser.fail(URI.java:2858)
at java.net.URI$Parser.checkChars(URI.java:3031)
at java.net.URI$Parser.parseHierarchical(URI.java:3115)
at java.net.URI$Parser.parse(URI.java:3063)
at java.net.URI.<init>(URI.java:599)
at java.net.URL.toURI(URL.java:975)
at datadog.telemetry.dependency.DependencyService.convertToURI(DependencyService.java:84)
at datadog.telemetry.dependency.DependencyService.addURL(DependencyService.java:66)
at datadog.telemetry.dependency.LocationsCollectingTransformer.addDependency(LocationsCollectingTransformer.java:44)
at …
```
> Fix dependency service for spaced paths

- dd-java-agent/build.gradle
- gradle/dependencies.gradle
This will let us relocate some dependencies used by the tracer without affecting instrumentation for the same libraries.
> Move agent-crashtracking to shared section of shaded dd-java-agent jar

- dd-java-agent/build.gradle
- dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/LinkAtBuildTimeInstrumentation.java
- dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/ResourcesFeatureInstrumentation.java
- dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy
Relocates OkHttp used in the agent so it doesn't clash with versions used in the App
Fixes: https://github.com/DataDog/dd-trace-java/issues/6017
> Relocate OkHttp to avoid conflicts

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/Redaction.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/test/java/datadog/trace/bootstrap/debugger/util/RedactionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/ExpressionHelper.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/GetMemberExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/IndexExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/ValueRefExpression.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DenyListHelper.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/SerializerWithLimits.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot27.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot28.java
- dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Add property/env `dynamic.instrumentation.redacted.types` to customize the redaction data based on type.
Redaction happening at:
- expression language for reference, index and getmember operations
- serialization for snapshot or template values including maps For conditions (log or span decoration probes) evaluation of a redacted values triggers an evaluation exception that will be reported as evaluation error into a snapshot.
PII redaction
Jira ticket: [DEBUG-1846]
[DEBUG-1846]: https://datadoghq.atlassian.net/browse/DEBUG-1846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add config for custom redacted types

- dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
- dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletRequestCallSiteTest.groovy
- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
It changes to http.request.path the source reported when a vulnerability is found and the source of the tainted object was acquired using HttpServletRequest.getRequestURI since this API doesn't return the full URL.
To be consistent when reporting vulnerability sources.
Jira ticket: [APPSEC-11729]
[APPSEC-11729]: https://datadoghq.atlassian.net/browse/APPSEC-11729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Changed HttpServletRequest.getRequestURI reported souce to http.request.path

- dd-java-agent/instrumentation/spark/spark_2.12/build.gradle
- dd-java-agent/instrumentation/spark/spark_2.13/build.gradle
For Spark Tests, skip JDKs:
- OpenJ9 because of https://issues.apache.org/jira/browse/HADOOP-18174
- IBM8 because of https://issues.apache.org/jira/browse/HADOOP-17971
Failing on master: https://github.com/DataDog/dd-trace-java/runs/17880700556
> Skip problematic JDK for spark tests

- dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/VMRuntimeInstrumentation.java
Avoids unexpected allocation [issue](https://github.com/DataDog/dd-trace-java/issues/6068) when using G1-GC
> Skip task scope creation for Graal VMOperation threads

- dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSupport.java
- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
Collects a histogram of the heap once every 60s. This feature is opt in. The underlying data collection is done in parallel from JDK21+ and was backported to JDK17.0.9. If the user opts in on JDK versions where the collection is serial, a warning and recommendation to upgrade the JDK is printed.
Jira ticket: [PROF-8468]
[PROF-8468]: https://datadoghq.atlassian.net/browse/PROF-8468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add heap histogram option

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
Avoids potential `ClassNotFoundException` shutting down the generated image
> Mark some default services as off during native-image build

- dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDLoggerFactory.java
- dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleDaemonLoggingInstrumentation.java
- internal-api/src/main/java/datadog/trace/api/Resettable.java
- internal-api/src/main/java/datadog/trace/logging/GlobalLogLevelSwitcher.java
- internal-api/src/main/java/datadog/trace/logging/LogLevelSwitcher.java
Fixes tracer logging to work when instrumenting Gradle Daemon.
Tracer logs contain data that is important for debugging.
When Gradle Daemon initialises, it closes original `System.out` and `System.err` streams, replacing them with daemon log streams.
Tracer logging is initialised before the daemon, so it refers to the original streams that are closed.
In order for the logging to work, it needs to refer to the daemon log streams.
This is achieved by reinitialising logging settings after Gradle Daemon has finished its initialisation.
Jira ticket: [CIVIS-7730]
[CIVIS-7730]: https://datadoghq.atlassian.net/browse/CIVIS-7730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix tracer logging when instrumenting Gradle Daemon

- dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
Be more explicit about which JDK tools we won't attach the tracer to.
Reduces log-spam by not tracing non-interesting tools like `keytool`
Jira ticket: [APMS-10600]
[APMS-10600]: https://datadoghq.atlassian.net/browse/APMS-10600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Skip attaching the tracer to the keytool command

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/EvidenceAdapter.java
- dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite.yml
When serializing vulnerability evidence, we could trigger an NPE when the data source has no value (e.g. this happens with request body as source). The end result is losing these vulnerabilities.
Jira ticket: [APPSEC-11847]
[APPSEC-11847]: https://datadoghq.atlassian.net/browse/APPSEC-11847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix NPE in IAST evidence redaction

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/MethodLocation.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/ProbeImplementation.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/ProbeRateLimiter.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
Move sampling into context evaluation
Sampling is now done into LogProbe context evaluation:
- if no condition sample at eval entry
- if has condition, sample after condition and if condition is true
keep sample status in LogStatus, use to know if:
- we should freeze eval context
- we should send snapshot
Sampling was done unconditionally before capturing, and with condition was also performed at commit which reduce the number of snapshot matching the condition
Jira ticket: [DEBUG-1890]
[DEBUG-1890]: https://datadoghq.atlassian.net/browse/DEBUG-1890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix sampling with probe condition

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/VulnerabilityEncoding.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/VulnerabilityEncodingTest.groovy
Prevent serialization exceptions from breaking traces. See https://github.com/DataDog/dd-trace-java/pull/6099
> Handle serialization exceptions in IAST

- dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpServerHeaders.java
- dd-java-agent/instrumentation/play-2.6/build.gradle
Prevents the content of the request uri to be reported to the WAF as a header.
> Akka: skip synthetic header Raw-Request-Uri

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
- dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
- dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletRequestCallSiteTest.groovy
- dd-java-agent/instrumentation/servlet/src/test/java/datadog/smoketest/controller/TestHttpServletRequestCallSiteSuite.java
- dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
- internal-api/src/main/java/datadog/trace/api/iast/source/WebModule.java
Adds instrumentation to Servlet.getServletURL call
To be able to taint the output of the function so it can be used by IAST to detect vulnerabilities.
Jira ticket: [APPSEC-11729](https://datadoghq.atlassian.net/browse/APPSEC-11729)
[APPSEC-11729]: https://datadoghq.atlassian.net/browse/APPSEC-11729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IAST Servlet.getRequestURL instrumentation

- dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/core/MultiMapInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/core/MultiMapInstrumentationTest.groovy
- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastVertxSmokeTest.groovy
- dd-smoke-tests/vertx-3.4/application/src/main/java/datadog/smoketest/vertx_3_4/IastHandler.java
- dd-smoke-tests/vertx-3.9/application/src/main/java/datadog/smoketest/vertx_3_9/IastHandler.java
- dd-smoke-tests/vertx-4.2/application/src/main/java/datadog/smoketest/vertx_4_2/IastHandler.java
Adds the source name to the header and parameter names for Vertx.4 which was removed after the refactor in https://github.com/DataDog/dd-trace-java/pull/6033
> Add name in sources for vertx 4 header names and param values

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingIntegration.java
- dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ProfilerContext.java
Adds APM resource name labels to profile samples, which allows flamegraphs to be filtered by resource name. This is enabled by default but can be disabled with `-Ddd.profiling.context.attributes.resource.name.enabled=false`.
Jira ticket: [PROF-8531]
[PROF-8531]: https://datadoghq.atlassian.net/browse/PROF-8531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add resource name to profile samples

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymbolExtractor.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymbolExtractionTransformerTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symbol/SymbolExtraction09.java
Jira ticket: [DEBUG-1892]
[DEBUG-1892]: https://datadoghq.atlassian.net/browse/DEBUG-1892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add support of lambdas as CLOSURE scope type

- dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
- dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- telemetry/src/main/java/datadog/telemetry/TelemetryClient.java
- telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
- telemetry/src/test/groovy/datadog/telemetry/TelemetrySystemSpecification.groovy
Removes `telemetry.intake.url` in favor of constructing it out of DD_SITE according to [the clarified RFC rules](https://github.com/DataDog/instrumentation-telemetry-api-docs/blob/main/GeneratedDocumentation/ApiDocs/v2/development.md#agentless)
Decide on Telemetry Intake URL without expecting a user setting it explicitly.
> Telemetry v2 URL from DD_SITE

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Replace `DD_DYNAMIC_INSTRUMENTATION_SYMBOL_ENABLED`
to `DD_SYMBOL_DATABASE_UPLOAD_ENABLED`
Add `DD_INTERNAL_FORCE_SYMBOL_DATABASE_UPLOAD` for testing
Jira ticket: [DEBUG-1898]
[DEBUG-1898]: https://datadoghq.atlassian.net/browse/DEBUG-1898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change SymDB config

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/Redaction.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/RedactedException.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/ExpressionHelper.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/LogMessageTemplateBuilder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/SerializerWithLimits.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/StringTokenWriter.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
in log template use `{redacted}` instead of the evaluation error message 
for snapshot indicated the by which part it was redacted:
- `redactedIdent` for keyword redaction
- `redactedType` for type redaction
Jira ticket: [DEBUG-1897]
[DEBUG-1897]: https://datadoghq.atlassian.net/browse/DEBUG-1897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change redacted values in snapshot & log templates

- dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/exceptions/ExceptionProfiling.java
- dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/exceptions/ExceptionSampleEvent.java
- dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
- dd-java-agent/instrumentation/exception-profiling/src/main/java/datadog/exceptions/instrumentation/ThrowableInstrumentation.java
- dd-java-agent/instrumentation/exception-profiling/src/main/java11/datadog/exceptions/instrumentation/ThrowableInstanceAdvice.java
This instruments the `Exception` and `Error` classes in  the `java.lang` and [`kotlin`](https://github.com/JetBrains/kotlin/blob/236a76f779d208cadd4462fb99cb2b6d2336eee2/libraries/stdlib/js/src/kotlin/exceptions.kt#L15) packages, instead of `Throwable` which avoids several throwable types used for control flow, such as Scala's [`ControlThrowable`](https://www.scala-lang.org/api/3.0.2/scala/util/control/ControlThrowable.html). This also avoids resource tracking mechanisms such as Netty's `ResourceLeakDetector` which we were filtering out. 
Avoiding the instrumentation altogether in these non-exceptional cases is important because the instrumentation interferes with escape analysis and ensuing optimisations which can reduce the cost of these exception types to practically nothing.
Jira …
> instrument Exception and Error classes to avoid instrumenting generic throwables used for control flow

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/MethodLocation.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
In the case of a line probe MethodLocation is DEFAULT and we should not consider the evaluteAt attribute as it is meant for method probe only
no sampling for line probe without condition
Jira ticket: [DEBUG-1908]
[DEBUG-1908]: https://datadoghq.atlassian.net/browse/DEBUG-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix sampling for line probe without condition

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/LanguageSpecifics.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/Scope.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/Symbol.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymbolExtractor.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymbolExtractionTransformerTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symbol/SymbolExtraction13.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symbol/SymbolExtraction14.java
LanguageSpecifics add specific information to symbol/scopes for Classes, methods and fields. It's relate to
- access modifiers
- annotations
- super class
- interfaces
- return type
Enrich the symbol extraction
Jira ticket: [DEBUG-1891]
[DEBUG-1891]: https://datadoghq.atlassian.net/browse/DEBUG-1891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Language Specifics in Symbol Extraction

- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
add line probe condition and ensure call sampling
> Rename sampling tests

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CorrelationAccess.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java
Checking for trace enabled needs to be true by default if no token
> Fix tracer enabled detection default value

- remote-config/src/main/java/datadog/remoteconfig/PollerRequestFactory.java
- remote-config/src/main/java/datadog/remoteconfig/tuf/RemoteConfigRequest.java
- remote-config/src/test/groovy/datadog/remoteconfig/PollerRequestFactoryTest.groovy
Send git repository url and git commit sha as tags on each Remote Config request
Transmit git metadata to link with SCI for Dynamic Instrumentation through heartbeats
Jira ticket: [DEBUG-1831]
[DEBUG-1831]: https://datadoghq.atlassian.net/browse/DEBUG-1831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add git repository and sha in RC request tags

- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Utils.java
- dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
- dd-java-agent/instrumentation/junit-4.10/src/test/java/org/example/TestParameterized.java
Fixes `NullPointerException` when JUnit 4 tracing listener receives events from a named parameterised test case.
When a named parameterised test case is executed, there is a "test suite started" notification with a description that corresponds to a set of parameters.
The tracing listener is not interested in this event, but it should discard it rather than fail with exception.
Jira ticket: [CIVIS-7864]
[CIVIS-7864]: https://datadoghq.atlassian.net/browse/CIVIS-7864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix NPE when tracing named parameterised tests in JUnit 4 instrumentation

- .github/CODEOWNERS
- dd-java-agent/instrumentation/karate/src/main/java/datadog/trace/instrumentation/karate/KarateTracingHook.java
- dd-java-agent/instrumentation/karate/src/test/groovy/KarateTest.groovy
- dd-java-agent/instrumentation/karate/src/test/java/org/example/TestWithSetupKarate.java
- dd-java-agent/instrumentation/karate/src/test/java/org/example/karate-config.js
- dd-java-agent/instrumentation/karate/src/test/java/org/example/test_with_setup.feature
Fixes `NullPointerException` when Karate tests with `@setup` blocks are instrumented.
This is a bug that breaks test runs.
`@setup` is a special tag in Karate that can be used to mark a scenario that is a part of another scenario's setup.
The problem for CI Visibility is that `beforeScenario` and `afterScenario` events for these setup blocks are fired before events that demarcate the start of their "parent" scenario and feature.
"Manually" reconstructing feature starts for these setup scenarios is error-prone, besides we do not want to report them as separate tests (given that they aren't tests), so for now the decision is to not track them.
Jira ticket: [CIVIS-7898]
[CIVIS-7898]: https://datadoghq.atlassian.net/browse/CIVIS-7898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
> Fix NPE in @setup calls when tracing Karate

- dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleProjectConfigurator.groovy
Fixes Gradle test tasks configurator: to run the forked JVM with the tracer, it modifies JVM arguments of Gradle test tasks.
It did so by calling `Test.jvmArgs()`,  which appended the new arguments to the existing ones.
Since the compiled list of arguments already contains the existing ones, it should replace rather than be added to the list of existing args.
So the code was updated to call `Test.setJvmArgs()`, which has the desired semantics.
Duplicating some args (e.g. `--patch-module`) can cause the forked JVM to fail.
Jira ticket: [CIVIS-7901]
[CIVIS-7901]: https://datadoghq.atlassian.net/browse/CIVIS-7901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix forked JVM args duplication when auto-configuring Gradle test tasks

- communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilitySystem.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/communication/BackendApiFactory.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/communication/EvpProxyApi.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/config/ConfigurationApiImplTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/tree/GitDataApiTest.groovy
- dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java
- dd-trace-core/src/main/java/datadog/trace/common/writer/ddintake/DDEvpProxyApi.java
Fixes CI Visibility to work correctly in Kubernetes setups where tracer is injected automatically by Datadog Admission Controller.
Using Datadog Admission Controller is much easier for the customers than injecting the tracer manually in a containerised environment.
It should work correctly with CI Visibility.
Admission Controller, among other things, creates a volume and mounts it both to the agent containers and to the application containers. In the volume there is a Unix domain socket. Instrumented applications write to this socket, and the agent reads from it.
The tracer logic responsible for discovering the socket is in `datadog.common.socket.SocketUtils#discoverApmSocket`.
`datadog.communication.ddagent.SharedCommunicationObjects` handles socket detection transparently for the rest …
> Fix CI Visibility to work with DD Admission Controller

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingIntegration.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ProfilingContextIntegration.java
Without this change we would encode operation and resource names even if attaching them to profile samples was disabled.
Jira ticket: [PROF-8531]
[PROF-8531]: https://datadoghq.atlassian.net/browse/PROF-8531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> guard operation and resource name encoding properly when encoding is disabled

- .circleci/config.continue.yml.j2
Add more heap for muzzle dependency report
> more heap for muzzledoc

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/ASMHelper.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot19.java
When some fields are not accessible directly because of the visibility we emit a relfection call to get the value but arrays was not supported
> Fix accessing array field by reflection
