DataDog/dd-trace-java

dd-java-agent/instrumentation/opentelemetry/opentelemetry-0.3/src/test/groovy/OpenTelemetryTest.groovy
dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-ot/src/ot31CompatibilityTest/groovy/OT31ApiTest.groovy
dd-trace-ot/src/ot33CompatibilityTest/groovy/OT33ApiTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

This PR changes the default propagator style from `datadog` to `datadog,tracecontext`.
This will improve W3C tracecontext standard compatibility by default. 
System-tests are failing are they are not ready for the W3C trace context change initiative:
```
E       AssertionError: assert 'traceparent' not in {'traceparent': '00-00000000000000001d98b30ac29490fa-2af1f8d62c1057b4-01', 'tracestate': 'dd=s:1;t.dm:-1', 'x-datadog-parent-id': '3094528017726199732', 'x-datadog-sampling-priority': '1', ...}
```
This will be handled later when merging project branch to master, expecting the system-tests to be ready by then.
Jira ticket: [APMJAVA-1122]
[APMJAVA-1122]: https://datadoghq.atlassian.net/browse/APMJAVA-1122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …

Switch default propagation style from datadog to datadog,tracecontext

---

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingIntegration.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TestProfilingContextIntegration.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ProfilingContextIntegration.java

Records the profiling context integration in use on the root span, which helps with trace to profile correlation.
Jira ticket: [PROF-8581]
[PROF-8581]: https://datadoghq.atlassian.net/browse/PROF-8581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

report profiling context integration on root span

---

gradle/dependencies.gradle

Bumps the dependency version for ddprof
To bring in the fix for ZGC related crashes on JDK 21 when Live Heap profiling is enabled (https://github.com/DataDog/java-profiler/pull/41)
Jira ticket: [PROF-8526]
[PROF-8526]: https://datadoghq.atlassian.net/browse/PROF-8526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bump ddprof dep to 0.83.0

---

internal-api/src/main/java/datadog/trace/api/Config.java

Removes the `@Deprecated` annotation from `Config`
The annotation was added back when `Config` was part of the public api (#1577). The purpose was to discourage its use so that we could make internal changes to how config is handled. As the class is now in the `internal-api` module, and is the de facto config management class for the whole library, the annotation just leads to confusion, extra warnings on the command line, and extra warnings in IDEs.

Remove @Deprecated from Config

---

dd-java-agent/instrumentation/maven-3.2.1/build.gradle

which aren't currently compatible with maven-embedder

Ignore alpha builds of org.apache.maven.resolver 2.x

---

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java

This PR enables the generation of 128-bit trace identifier (instead of 64-bit only) by default. 
This change will increase interoperability with other tracing systems.
Jira ticket: [APMJAVA-1085]
This breaks B3 parametric tests. 
I made a PR to fix them too: https://github.com/DataDog/system-tests/pull/1810 
[APMJAVA-1085]: https://datadoghq.atlassian.net/browse/APMJAVA-1085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enable 128-bit trace identifier generation by default

---

internal-api/src/main/java/datadog/trace/api/http/StoredByteBody.java
internal-api/src/main/java/datadog/trace/api/http/StoredCharBody.java
internal-api/src/test/groovy/datadog/trace/api/http/StoredByteBodyTest.groovy

Ensure the class `AbstractServletInputStreamWrapper` does not leak exceptions when called from customer code.
We have received a couple of tickets due to the following exception in their services after activating appsec:
```
java.lang.IllegalStateException: Current state = CODING_END, new state = CODING
at java.base/java.nio.charset.CharsetDecoder.throwIllegalStateException(Unknown Source)
at java.base/java.nio.charset.CharsetDecoder.decode(Unknown Source)
at datadog.trace.api.http.StoredByteBody.commit(StoredByteBody.java:139)
at datadog.trace.api.http.StoredByteBody.appendData(StoredByteBody.java:49)
at datadog.trace.instrumentation.servlet.AbstractServletInputStreamWrapper.read(AbstractServletInputStreamWrapper.java:31)
```
Jira ticket: [APPSEC-12101]
[APPSEC-12101]: …

Make sure AbstractServletInputStreamWrapper does not propagate exceptions

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/Utils.java
dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java

Skip costly message size calculation for kafka when DSM is off
Note: I could directly shortcut the whole checkpointing but I preferred to keep code changes minimal

Avoid calculate Kafka message size when DSM is not enabled

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java

Add support of `@return` and `@duration` for method metric probes if the return value of the method is compatible with long or double (like integer, byte, short or float) we can use `@return` as input for the metric.
`@duration` is now supported as input for metric also the value is a double representing the ms elapsed for the execution of the method
There was no support for `@return` and `@duration` for metric probes
Jira ticket: [DEBUG-1854]
[DEBUG-1854]: https://datadoghq.atlassian.net/browse/DEBUG-1854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for synthetic vars for metric probes

---

dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymbolExtractionTransformerTest.java

flaky tests that needs to be resolved later

disable symdb tests for IBM JVM

---

index.yml

The updated URL in the cloudfoundry index.yml is incorrect

Fix incorrect cloudfoundry url to 1.23.0

---

dd-trace-ot/src/ot31CompatibilityTest/groovy/OT31ApiTest.groovy
dd-trace-ot/src/ot33CompatibilityTest/groovy/OT33ApiTest.groovy

This will fix the OpenTracing module tests.
As 128-bit trace identifier generation is now enabled by default, some tests need update.
Jira ticket: [APMJAVA-1085]
[APMJAVA-1085]: https://datadoghq.atlassian.net/browse/APMJAVA-1085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix OpenTracing tests for 128-bit trace identitifer

---

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/MetricProbesIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/MoshiConfigTestHelper.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ProbeStateIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SpanProbesIntegrationTest.java

- log probes conditions at exit with synthetic vars and failed
- metric probes with invalid conditions (name and type)
- fixes some tests
Jira ticket: [DEBUG-1462]
[DEBUG-1462]: https://datadoghq.atlassian.net/browse/DEBUG-1462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add smoke tests for probes with conditions

---

dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/DebuggerTestApplication.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/MetricProbesIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ServerAppDebuggerIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SpanProbesIntegrationTest.java

Jira ticket: [DEBUG-1462]
[DEBUG-1462]: https://datadoghq.atlassian.net/browse/DEBUG-1462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add caught/uncaught exception smoke tests

---

.circleci/config.continue.yml.j2

Update system-tests to 6998b307ce0e8d206ca6eb99045651dcc8bc853f

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/SkippableTestsSerializer.java
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/config/SkippableTestsSerializerTest.groovy

Fixes serialisation of `SkippableTest` objects whose suite or test case names contain non-ASCII characters.
Such tests are valid, exist and should be supported.
Skippable tests are serialised when sent from the parent process (build system) to the children processes (JVMs forked for tests execution). 
Jira ticket: [CIVIS-7964]
[CIVIS-7964]: https://datadoghq.atlassian.net/browse/CIVIS-7964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix error when serializing skippable tests whose names contain non-ASCII characters

---

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/build.gradle
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryInstrumentation.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OpenTelemetryContextInstrumentation.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OpenTelemetryContextStorageInstrumentation.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelSpanBuilder.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelSpanLink.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy

This PR adds OpenTelemetry span links support for its instrumentation.
This should improve OpenTelemetry API support and compatibility.
This relies on [the past span links to core addition](https://github.com/DataDog/dd-trace-java/pull/5569) and [its update](https://github.com/DataDog/dd-trace-java/pull/6009).
JIRA ticket: [APMJAVA-1087]
[APMJAVA-1087]: https://datadoghq.atlassian.net/browse/APMJAVA-1087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add span links support to OpenTelemetry instrumentation

---

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelConventions.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelTracer.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/ContextTest.groovy

This PR will remove the default operation name that should never be used has OpenTelemetry spans are supposed to always have a kind (`internal` by default).
This change will comply with the latest specification update.
Jira ticket: [APMJAVA-1062]
[APMJAVA-1062]: https://datadoghq.atlassian.net/browse/APMJAVA-1062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update the OpenTelemtry default operation name

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/GrpcRequestMessageHandler.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/GrpcRequestMessageHandlerTest.groovy
internal-api/src/main/java/datadog/trace/api/iast/propagation/PropagationModule.java

Add the code needed to generate metrics when tainting GRPC payloads
In order to validate the support for GRPC payloads we must ensure we generate proper metrics

Ensure grpc message handler generates telemetry metrics

---

dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/test/groovy/CouchbaseClient31Test.groovy

Fix flakyness of one couchbase test after query normalization

fix flaky couchbase test

---

dd-java-agent/instrumentation/google-pubsub/src/main/java/datadog/trace/instrumentation/googlepubsub/PublisherInstrumentation.java
dd-java-agent/instrumentation/google-pubsub/src/main/java/datadog/trace/instrumentation/googlepubsub/ReceiverInstrumentation.java
dd-java-agent/instrumentation/google-pubsub/src/main/java/datadog/trace/instrumentation/googlepubsub/ReceiverWithAckInstrumentation.java
dd-java-agent/instrumentation/google-pubsub/src/test/groovy/PubSubTest.groovy

Disables google-pubsub instrumentation by default.  It will reverted back at beginning of december 2023.
In order to enable that instrumentation the customer can act on:
* The sys property `-Ddd.integration.google-pubsub.enabled=true`
* The env variable `DD_INTEGRATION_GOOGLE_PUBSUB_ENABLED=true`

google-pubsub temporary disabled by default

---

dd-java-agent/agent-iast/build.gradle
dd-java-agent/instrumentation/vertx-mysql-client-4.4.2/build.gradle
dd-java-agent/instrumentation/vertx-web-4.0/build.gradle

Excludes VertX 4.4.+. Fix Java release param issue
Fixes 
```
unable to resolve class io.vertx.core.http.impl.NoStackTraceTimeoutException
```
after Vert.X 4.5.0 release
Fixes
```
Cannot specify --release via `CompileOptions.compilerArgs` when using `JavaCompile.release
```
when building with `OpenJDK Runtime Environment Zulu11.64+19-CA (build 11.0.19+7-LTS)` and the next Java toolchain:
```
❯ ./gradlew -q javaToolchains
+ Options
| Auto-detection:     Disabled
| Auto-download:      Disabled
+ AdoptOpenJDK 1.8.0_292-b10
| Location:           /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
| Language Version:   8
| Vendor:             AdoptOpenJDK
| Architecture:       x86_64
| Is JDK:             true
| Detected by:        environment variable 'JAVA_8_HOME'
+ Azul Zulu …
```

Exclude VertX 4.4.+. Fix Java release param issue

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/UnionMap.java

Replaces `UnionMap` with a standard `HashMap` when serializing to a remote logger.
Avoids `NotSerializableException`s in the remote logger when it tries to read the serialized log event.
Jira ticket: [APMS-10855]
[APMS-10855]: https://datadoghq.atlassian.net/browse/APMS-10855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support remote logging over logback's SocketAppender

---

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java

surface cause when DD profiler can't be instantiated

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilitySystem.java

Changes logic that calculates module names for CI Visibility executions that run without build system instrumentation.
A check is added: if current folder of the JVM running the tests is outside of the project's repository, service name is used to populate module name. Otherwise, module name is the path to the current folder relative to the project root (previous behaviour).
Bazel, whose instrumentation is not supported, runs tests in temporary folders with randomly generated names.
As the result, with the previous logic module name is randomised.
Since module name is a part of the test fingerprint, the fingerprints change with every run, which breaks certain features (execution history, ITR, etc.).
The motivation to use service name as the module name is to avoid adding another …

Fix module name calculation for test executions whose working dir is outside of project repository

---

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelConventions.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelSpanBuilder.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14ConventionsTest.groovy
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/ContextTest.groovy
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/AbstractPropagatorTest.groovy

This PR changes the OpenTelemetry instrumentation behavior to store the OpenTelemetry span kind to the `span.kind` tag instead of the (underlying Datadog) span type. 
> [!WARNING]  
> This will change the span type for span issued from OpenTelemetry instrumentations.
As the OpenTelemetry instrumentation is currently in beta and the past behavior was not the one expected, no feature flag was introduce to revert to the past behavior.
This is the expected behavior from OpenTelemetry API support RFC.
Jira ticket: [APMJAVA-1062]
I run the changes against the latest system-tests with more [some additional tests enabled](https://github.com/DataDog/system-tests/pull/1818).
[APMJAVA-1062]: https://datadoghq.atlassian.net/browse/APMJAVA-1062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …

Store OpenTelemetry span kind as tag instead of span type

---

dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java

Useful for debugging to see if data streams is enabled, when the stats aren't showing up in Datadog.

[data streams] Log config

---

dd-java-agent/instrumentation/commons-fileupload/src/main/java/datadog/trace/instrumentation/commons/fileupload/CommonsFileuploadInstrumenter.java

Replaces `ForConfiguredTypes` with `ForKnownTypes`.  `ForKnownTypes` is preferred because we know we can statically build that into the tracer and optimize it, whereas `ForConfiguredTypes` implies it might change at runtime and therefore shouldn't be optimized.
Jira ticket: [[APPSEC-11821](https://datadoghq.atlassian.net/browse/APPSEC-11821)]
[APPSEC-11821]: https://datadoghq.atlassian.net/browse/APPSEC-11821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

implement ForKnownTypes

---

gradle/dependencies.gradle

Bumps ddprof to 0.84.1
Include https://github.com/DataDog/java-profiler/pull/46
Jira ticket: [PROF-8660]
[PROF-8660]: https://datadoghq.atlassian.net/browse/PROF-8660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Hot-patch for J9 profiler regression

---

.circleci/render_config.py
.gitlab-ci.yml

This PR update the docker builder image.
This will bring Temurin 21 and GraalVM native-image 21 as long as patch updates for the existing JDK.
This PR also changes the behavior for the GitLab CI.
It moves from latest to a stable version, the same as Circle CI.

Update docker builder image

---

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelConventions.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelSpan.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelSpanBuilder.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14ConventionsTest.groovy
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/ContextTest.groovy
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/AbstractPropagatorTest.groovy

This PR is a port of #6232 bug fix.
It also prevents reserved attributes being sent as span tags.
> [!WARNING]  
> This will change the span type for span issued from OpenTelemetry instrumentations.
As the OpenTelemetry instrumentation is currently in beta and the past behavior was not the one expected, no feature flag was introduce to revert to the past behavior.
This behavior was recently describes in the OTel API support RFC. 
Jira ticket: [APMJAVA-1062]
[APMJAVA-1062]: https://datadoghq.atlassian.net/browse/APMJAVA-1062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Store OpenTelemetry span kind as tag instead of span type and drop reserved attributes from span tags

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymDBEnablement.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymbolAggregator.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymDBEnablementTest.java

When we register the symbol extraction transformer and when we snapshot all loaded classes there is a race where a class can be loaded by a classloader and process by the transformer but can also be part of the loaded classes and then be processed twice. we add a temporary concurrent set to track class names that are parsed by the SymbolAggregator
Jira ticket: [DEBUG-1916]
[DEBUG-1916]: https://datadoghq.atlassian.net/browse/DEBUG-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix race for SymDB enablement

---

.circleci/config.continue.yml.j2

Enables tracer-flare system tests for the development version of the Java tracer (1.25.0)
```
[gw2] [ 98%] PASSED tests/parametric/test_tracer_flare.py::TestTracerFlareV1::test_flare_log_level_order[library_env0] 
[gw0] [ 98%] PASSED tests/parametric/test_tracer_flare.py::TestTracerFlareV1::test_telemetry_app_started[library_env0] 
tests/parametric/test_tracer_flare.py::TestTracerFlareV1::test_no_tracer_flare_for_other_task_types[library_env0] 
[gw1] [ 99%] PASSED tests/parametric/test_tracer_flare.py::TestTracerFlareV1::test_tracer_flare_with_debug[library_env0] 
[gw3] [ 99%] PASSED tests/parametric/test_tracer_flare.py::TestTracerFlareV1::test_tracer_flare[library_env0] 
[gw0] [100%] PASSED tests/parametric/test_tracer_flare.py::TestTracerFlareV1::test_no_tracer_flare_for_other_task_type …
```

Update system-tests to 268c7ddfba2c45085dc29434e677ff13307445ef

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/WellKnownClasses.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/ValueRefExpression.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_10.json

WellKnown classes (like `UUID`) need to be treated as string primitives to be use in Expression Language and conditions
Add a list of string primitives
coherency with serialization behavior
Jira ticket: [DEBUG-1689]
[DEBUG-1689]: https://datadoghq.atlassian.net/browse/DEBUG-1689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle WellKnown classes as primitives in EL

---

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java

wider the range for snapshots received as the CI nodes are slower
Flaky smoke tests

Adjust range for sampling smoke test

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/StringTokenWriter.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java

Instead of using ellipsis to indicate timeout happened, use `{timeout}`
Boost timeout for smoke tests
Flaky smoke tests
Jira ticket: [DEBUG-1931]
[DEBUG-1931]: https://datadoghq.atlassian.net/browse/DEBUG-1931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make timeout error explicit on log serialization

---

dd-smoke-tests/agent-bootstrap/build.gradle
dd-smoke-tests/agent-bootstrap/src/another-agent/java/datadog/smoketest/agent/AnotherAgent.java
dd-smoke-tests/agent-bootstrap/src/main/java/datadog/smoketest/app/App.java
dd-smoke-tests/agent-bootstrap/src/main/java/datadog/smoketest/classloader/NoProtectionDomainClassLoader.java
dd-smoke-tests/agent-bootstrap/src/test/groovy/datadog/smoketest/MultiAgentWithNoProtectionDomainSystemLoaderSmokeTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/ProcessManager.groovy
settings.gradle

Adds a smoke test for 
* #6126
This is basically the same PR #6244 but from Datadog/dd-trace-java instead of my fork bric3/dd-trace-java. As such this PR supersede #6244.
Verify the changes in #6126, where the agent is now able to determine its location when there are other agents and the classloader strips the protection domain.
Jira ticket: [CIVIS-7865](https://datadoghq.atlassian.net/browse/CIVIS-7865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
_Note this is the Jira of #6126._
[CIVIS-7865]: https://datadoghq.atlassian.net/browse/CIVIS-7865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add smoke test for multiple agents and NoProtectionDomain system loader

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ValueReferences.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/DSL.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/JsonToExpressionConverter.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/IsUndefinedExpression.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/IsUndefinedExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/ValueRefExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_10.json
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_11.json
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot20.java

Uncaught exception captured by method probe (log, snapshot or span decoration) can be accessed through @exception synthetic variable with expression language in conditions, log template or span tags
Jira ticket: [DEBUG-1940]
[DEBUG-1940]: https://datadoghq.atlassian.net/browse/DEBUG-1940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support of `@exception` for uncaught exception

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/Where.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/instrumentation/TypesTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/WhereTest.java

the dollar character in inner class is interpreted as regex and replacement special character. Need to be escaped.
Supporting inner classes in probe method signature
Jira ticket: [DEBUG-1620]
[DEBUG-1620]: https://datadoghq.atlassian.net/browse/DEBUG-1620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix inner class signature matching

---

dd-java-agent/instrumentation/spring-security-5/src/main/java17/datadog/trace/instrumentation/springsecurity5/SpringSecurityUserEventDecorator.java

Our Spring Security instrumentation is detecting all OAuth events as login attempts, which is incorrect. This can lead to a high volume of kept traces for Spring Security oauth-authorization-server.
These events might be captured in the future once we define which events need to be emitted for OAuth.
Jira ticket: [APPSEC-12547](https://datadoghq.atlassian.net/browse/APPSEC-12547)
[APPSEC-12547]: https://datadoghq.atlassian.net/browse/APPSEC-12547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Exclude OAuth from Spring Security instrumentation

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ModuleExecutionSettingsFactoryImpl.java
internal-api/src/main/java/datadog/trace/api/Config.java

Allows to enable automatic Jacoco injection in Maven and Gradle builds even if ITR is disabled for the tested service.
Now automatic injection will happen either if coverage is enabled according to the remote settings or if the user sets `DD_CIVISIBILITY_JACOCO_PLUGIN_VERSION` environment variable.
Done as part of the new Coverage feature in CI Visibility.
Jira ticket: [CIVIS-8160]
[CIVIS-8160]: https://datadoghq.atlassian.net/browse/CIVIS-8160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow Jacoco auto-instrumentation even when ITR is disabled

---

dd-smoke-tests/spring-boot-3.0-native/src/test/groovy/SpringBootNativeInstrumentationTest.groovy

ClassNotFoundException is common in native-image when reflection is used. Add a check in smoke tests to ensure there is no ClassNotFoundException printed at runtime when native-image is used.

Test native-image builds have no ClassNotFoundException

---

dd-smoke-tests/spring-boot-3.0-native/application/build.gradle
dd-smoke-tests/spring-boot-3.0-native/build.gradle

This ensures that native image build is triggered whenever source used in the agent changes. No more --rerun-tasks needed.

Fix spring-boot-3.0-native gradle dependencies

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/CiVisibilitySettings.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ConfigurationApi.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ModuleExecutionSettingsFactoryImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/TracerEnvironment.java
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/config/ConfigurationApiImplTest.groovy

Updates ITR logic to reduce overhead on default branches.
Remote settings returned by the backend now include new boolean field `require_git`.
If the new field is set to true, the tracer should wait until Git data upload finishes and retry the settings request.
Most of the overhead when using ITR comes from having to run test with code coverage on default branches.
Based on the git data contents, the backend might decide to disable code coverage for a specific run.
Jira ticket: [CIVIS-8068]
[CIVIS-8068]: https://datadoghq.atlassian.net/browse/CIVIS-8068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reduce ITR overhead on default branches

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/TracingConfigPoller.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/api/DynamicConfig.java
internal-api/src/main/java/datadog/trace/api/TraceConfig.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

Adds a triage mode to static and dynamic config. Explicitly enabling full debug implicitly enables triage mode.
Triage mode will enable lightweight checks to help triage common issues without having to enable full debug mode.
JVM option:
```
-Ddd.trace.triage=true
```
Environment variable:
```
DD_TRACE_TRIAGE=true
```
Jira ticket: [APMJAVA-1134]
[APMJAVA-1134]: https://datadoghq.atlassian.net/browse/APMJAVA-1134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Configuration changes to support triage mode

---

dd-trace-api/src/main/java/datadog/trace/api/config/IastConfig.java

Fix config DD_IAST_TRUNCATION_MAX_VALUE_LENGTH value typo
Bug

Fix config DD_IAST_TRUNCATION_MAX_VALUE_LENGTH value typo

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/DebuggerSink.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/Sink.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerAgentHelper.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanProbeInstrumentationTest.java

Sink interface was introduced because snapshot was created and send to sink from bootstrap classes. This is not the case anymore so the usage of this interface is no more necessary.

Remove obsolete Sink interface

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilitySystem.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/PackageTree.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexBuilder.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexSourcePathResolver.java
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/index/RepoIndexSourcePathResolverTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/CiVisibilityConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

1. Updates repository indexer to only scan the project folder (and not the entire repository).
2. Adds a new config property that sets the limit on the number of root packages calculated by the indexed.
Both changes are needed to handle builds in repositories that contain multiple projects.
One of the things that the repository indexer does is determining the set of packages that should be instrumented with code coverage (limiting the set of packages is needed to reduce coverage overhead, as instrumenting 3rd party dependencies and core JDK classes adds a lot of overhead and serves no purpose).
The set of packages determined by the indexer is passed to Jacoco agent via the command line.
The length of the command line is finite (exact max length is OS-dependant), so the number of packages …

Fix root coverage packages calculation in large repositories

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilitySystem.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexBuilder.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexSourcePathResolver.java

Fixes source path detection in projects where repo root is not the same as project root.
Repo indexer only scans the project root (to save time and to work around some issues with calculating root packages), however all the source code paths submitted to the backend should be relative to the repo root.
Jira ticket: [CIVIS-8234]
[CIVIS-8234]: https://datadoghq.atlassian.net/browse/CIVIS-8234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix source path detection in multi-project repos

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/SinkModuleBase.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/AbstractSinkModuleTest.groovy

When reporting a vulnerability where the source tainted value has a single unbounded range (happens when we lose propagation over objects like `URL`, `URI`, ...), try to match the original source value with the final representation of the tainted object to do a better reporting,.
From a customer standpoint sometimes is difficult to correlate the vulnerability with its original source in the cases that we lose exact propagation (for instance when creating URLs).
Jira ticket: [APPSEC-11922]
[APPSEC-11922]: https://datadoghq.atlassian.net/browse/APPSEC-11922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Match tainted objects with sources when checking unbounded vulnerabilities

---

dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java
dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/DatabricksParentContext.java
dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/AbstractSparkStructuredStreamingTest.groovy
dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/AbstractSparkTest.groovy
internal-api/src/main/java/datadog/trace/api/sampling/SamplingMechanism.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
internal-api/src/test/groovy/datadog/trace/api/sampling/SamplingMechanismTest.groovy

Enforce new ingestion reason for spark traces
It is critical to keep all spark traces as customers closely monitor job runs. The new ingestion reason will allow tracking of ingested bytes for billing. Analysis on ingested bytes can be found in [here](https://docs.google.com/document/d/1uIG4zlgism09V6u4nhXl8F5IXj7eX1o8H4yqoJrSK7w/edit)
Added the method `AgentSpan setSamplingPriority(final int newPriority, int samplingMechanism)` in the `AgentSpan` interface so that it can be called from an instrumentation

Enforce new ingestion reason for spark traces

---

dd-java-agent/instrumentation/spark/spark_2.12/src/main/java/datadog/trace/instrumentation/spark/DatadogSpark212Listener.java
dd-java-agent/instrumentation/spark/spark_2.13/src/main/java/datadog/trace/instrumentation/spark/DatadogSpark213Listener.java
dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java
dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/AbstractSparkTest.groovy

Add field `parent_stage_ids` to `spark.stage` spans
In a spark job, input of a stage can be the output of a previous stage. This new fields parent_stage_ids will capture the dependency between stage to display it in the UI
Specific implementation based on the scala version because the signature of scala.Seq changed in scala 2.13

Add field parent_stage_ids to `spark.stage` spans

---

.gitlab/benchmarks.yml

This PR adds automatic kafka benchmark runs (benchmarks developed by DSM team, @hokitam) on changes in kafka-clients instrumentation.
Also the benchmark can be run manually.
Regardless if run was manually or automatically triggered, PR comment will be posted in corresponding PR (if PR exists).
More detailed results of benchmark runs (with visualizations) are available in Gitlab artifacts and in BP UI.
Add performance regression testing for Kafka instrumentation to prevent uncontrollable overhead increase.

Add BP trigger for DSM Kafka Benchmark

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/KnownAddresses.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/data/KnownAddressesSpecification.groovy

Avoid the following warning:
> WAF has rule against unknown address graphql.server.all_resolvers
Jira ticket: [APPSEC-16696](https://datadoghq.atlassian.net/browse/APPSEC-16696)
[APPSEC-16696]: https://datadoghq.atlassian.net/browse/APPSEC-16696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove warning about unknown graphql.server.all_resolvers

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DBMCompatibleConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/MySQLConnectionInstrumentation.java

Fix for reported customer issue around calling procedures for `postgresql` while having DBM-APM link enabled 
```
2023-11-10 13:30:52.870 [Thread-66184] [Error] [modifyJdbcCall] [api_call_unique_identifier-2026618091699623052870] [Client_Id-0] [span_id-99074af426ba7b60ccc2] - com.paymentology.payapi.v1.logging.ApiLogger
Malformed function or procedure escape syntax at offset 40.
org.postgresql.util.PSQLException: Malformed function or procedure escape syntax at offset 40.
at org.postgresql.core.Parser.modifyJdbcCall(Parser.java:1146)
at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:48)
at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:19)
at org.postgresql.util.LruCache.borrow(LruCache.java:123)
at …
```

Append DBM trace context comments for SQL Server & Postgres

---

communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
communication/src/test/groovy/datadog/communication/ddagent/DDAgentFeaturesDiscoveryTest.groovy
communication/src/test/resources/agent-features/agent-info.json
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/DebuggerSink.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/ProbeStatusSink.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SymbolSink.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/ProbeStatusSinkTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/SymbolSinkTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/uploader/BatchUploaderTest.java

datadog agent is now exposing a new endpoint: /debugger/v1/diagnostics This endpoint is used to send probe statuses to a dedicated debugger track.
we add detection o this new endpoint and create a dedicated BatchUploader to this endpoint using attachment.
if the endpoint is not available (old datadog agent) we send to the previous url as before.
Jira ticket: [DEBUG-1853]
[DEBUG-1853]: https://datadoghq.atlassian.net/browse/DEBUG-1853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Send probe statuses to new debugger track

---

dd-java-agent/agent-profiling/profiling-controller-jfr/implementation/src/main/java/com/datadog/profiling/controller/jfr/SimpleJFRAccess.java
dd-java-agent/agent-profiling/profiling-controller-jfr/implementation/src/test/java/com/datadog/profiling/controller/jfr/JFRAccessTest.java

It fixes a bug causing exception when running on some non-hotspot JDK 8 versions.
To fix the bug.
Jira ticket: [PROF-8805]
[PROF-8805]: https://datadoghq.atlassian.net/browse/PROF-8805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix the JFRAccess lookup

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymbolExtractor.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymbolExtractionTransformerTest.java
dd-java-agent/agent-debugger/src/test/java/utils/InstrumentationTestHelper.java
dd-java-agent/agent-debugger/src/test/java/utils/SourceCompiler.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot29.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symbol/SymbolExtraction15.java

upgrade ASM api version to 9
symbol extraction class modifiers
Jira ticket: [DEBUG-1997]
[DEBUG-1997]: https://datadoghq.atlassian.net/browse/DEBUG-1997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support of Java records

---

dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/JFREventContextIntegration.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ProfilerInstaller.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/nativeimage/TracerActivation.java
dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java

It enables TimelineEvent for native image
Providing code hotspots view for native image based apps
Jira ticket: [PROF-8742]
[PROF-8742]: https://datadoghq.atlassian.net/browse/PROF-8742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enable TimelineEvent in GraalVM native image

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/ContextStore.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/FieldBackedContextStore.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakMapContextStore.java

Fixes `ContextStore#putIfAbsent` implementations following a change introduced in [PR#6332](https://github.com/DataDog/dd-trace-java/pull/6332)
Jira ticket: [CIVIS-8243]
[CIVIS-8243]: https://datadoghq.atlassian.net/browse/CIVIS-8243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix ContextStore#putIfAbsent method to not use a lambda

---

dd-java-agent/instrumentation/opentelemetry/opentelemetry-0.3/src/test/groovy/TypeConverterTest.groovy
dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/TypeConverterTest.groovy
dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/TypeConverterTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDIntakeWriterCombinedTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDIntakeWriterTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/PayloadDispatcherImplTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/LongRunningTracesTrackerTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/TypeConverterTest.groovy

Changes some `Mock` instances to `Stub` instances when the interactions are not validated. 
Had an OOM failure locally when running `:dd-trace-core:test`, and the heap dump showed `org.spockframework.mock.runtime.InteractionScope` holding on to 190 MB in `DDAgentWriterCombinedTest`.
Changed all applicable `Mock` calls of `CoreTracer` and `PendingTrace` in all tests, since those where the culprits in `DDAgentWriterCombinedTest`.

Switch some unused Mocks to Stubs to avoid recording actions

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
dd-trace-core/build.gradle
dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/TagContextExtractor.java
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpExtractorTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

Allows the trace header tags values to contain commas (previously the value was split at the first comma, and only the first part was used).
It is possible to switch to the old behavior by setting the Java property `-Ddd.trace.request_header.tags.comma.allowed=false` or the environment variable `DD_TRACE_REQUEST_HEADER_TAGS_COMMA_ALLOWED=false`
Splitting at the first value breaks some encodings that use commas in the values. This was also the default behavior for some propagators up until `v1.4.0`.
Although it's not possible in HTTP to distinguish between multiple instances of the same header being combined into a comma separate list of the values, and a single header with a value with comma in it, we could be lenient here since the header names to read are user supplied.
Jira ticket: …

Allow comma in request header tag values

---

dd-java-agent/instrumentation/scalatest/build.gradle

Skips scalatest alpha and beta versions since there are half-published versions that breaks the build.

Skip Scalatest alpha and beta versions

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDBuildSystemSessionImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ModuleExecutionSettingsFactoryImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/TestDataRequest.java
internal-api/src/main/java/datadog/trace/api/civisibility/config/ModuleExecutionSettings.java
internal-api/src/main/java/datadog/trace/api/civisibility/config/TestIdentifier.java

Ignores configuration objects when comparing `TestIdentifier` objects.
Test identifiers comparison is done when determining whether to skip a test with ITR, or whether to retry a flaky test.
There are some inconsistencies in how the backend populates test configurations (depending on some conditions it may return a partially filled configuration block, an empty object, or a null).
Rather than trying to replicate the backend's logic in the tracer, it was decided to not use test configurations for comparison: the relevant fields are not be present in the backend's response anyway (since they are provided by the tracer when requesting tests data, the backend does not include them in the response).
Jira ticket: [CIVIS-8358]
[CIVIS-8358]: …

Ignore configuration blocks when comparing skippable test identifiers

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/NoopCoverageProbeStore.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/SegmentlessTestProbes.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/TestProbes.java
dd-java-agent/instrumentation/jacoco/src/main/java/datadog/trace/instrumentation/jacoco/ProbeInserterInstrumentation.java
internal-api/src/main/java/datadog/trace/api/civisibility/InstrumentationBridge.java
internal-api/src/main/java/datadog/trace/api/civisibility/coverage/CoverageProbeStore.java

Reduces the overhead of per-test code coverage in CI Visibility 
Jira ticket: [CIVIS-8357]
[CIVIS-8357]: https://datadoghq.atlassian.net/browse/CIVIS-8357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reduce per-test code coverage overhead

---

dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/AppSecSystemSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/blocking/BlockingServiceImplSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/EventDispatcherSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy

Changes some Mock instances to Stub instances when the interactions are not validated.
Inspired by initial improvement done for core tracer in https://github.com/DataDog/dd-trace-java/pull/6372

Replaced unused Mocks with Stubs in AppSec

---

dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/LocationTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/VulnerabilityTypeTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/EvidenceRedactionTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/VulnerabilityEncodingTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/overhead/OverheadControllerTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/AbstractSinkModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/CommandInjectionModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/HstsMissingHeaderModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/HttpResponseHeaderModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/InsecureCookieModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/LdapInjectionModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/NoHttpCookieModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/NoSameSiteCookieModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/PathTraversalModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/SqlInjectionModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/SsrfModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/TrustBoundaryViolationModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/UnvalidatedRedirectModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/WeakCipherModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/WeakHashModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/WeakRandomnessModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/XContentTypeOptionsModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/XPathInjectionModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/XssModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/RangesTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/telemetry/taint/TaintedObjectsWithTelemetryTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/RangedDequeueTest.groovy

Changes some Mock instances to Stub instances when the interactions are not validated.
Inspired by initial improvement done for core tracer in https://github.com/DataDog/dd-trace-java/pull/6372

Replaced unused Mocks with Stubs in IAST

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerProductChangesListener.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerProductChangesListenerTest.java

For supporting compatibility with new config ids, don't throw exception of an actual non supporting id format.
Compatibility
Jira ticket: [DEBUG-1793]
[DEBUG-1793]: https://datadoghq.atlassian.net/browse/DEBUG-1793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Accept any config id from Remote Config

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExcludeFilter.java
dd-java-agent/instrumentation/kafka-clients-0.11/build.gradle

Do not wrap `org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer$...` (inner class and lambdas) when advice spring scheduling `schdule(atFixedRate)`
Jira ticket: [APMS-10946]
[APMS-10946]: https://datadoghq.atlassian.net/browse/APMS-10946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

exclude spring-kafka runnables from spring scheduling wrapping

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy
remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java
remote-config/src/main/java/datadog/remoteconfig/state/ProductState.java
remote-config/src/main/java/datadog/remoteconfig/tuf/RemoteConfigRequest.java
remote-config/src/test/groovy/datadog/remoteconfig/ConfigurationPollerSpecification.groovy

Improved Configuration poller to support multiple listeners per product.
The changes needed to follow implementation of Api Security Sample Rate configuration via remote config.
This is preparation for https://github.com/DataDog/dd-trace-java/pull/6340

RC config poller with multiple listeners per product

---

dd-trace-core/src/main/java/datadog/trace/core/propagation/ptags/DatadogPTagsCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/ptags/W3CPTagsCodec.java
internal-api/src/main/java/datadog/trace/relocate/api/RatelimitedLogger.java
internal-api/src/test/groovy/datadog/trace/relocate/api/RateLimitedLoggerTest.groovy

This rate limits the warnings for illegal Datadog tags for both W3C and Datadog headers.
Other language tracers in mixed language systems that keep sending traces with broken headers are filling up the logs with these warnings.
Jira ticket: [APMJAVA-1042]
GitHub ticket: #5930
[APMJAVA-1042]: https://datadoghq.atlassian.net/browse/APMJAVA-1042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rate limit Datadog tags decoding warnings

---

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/kinesisDsmTest/groovy/AWS1KinesisClientTest.groovy
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/kinesisDsmTest/groovy/Aws2KinesisDataStreamsTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy

Increase the bucket duration to be sure that the number of stats that are assumed to be collected fits in one bucket duration.
Note: I could not increase the bucket duration for all the tests since that caused other issues on other kafka related dsm tests. Hence limiting only to kinesis

Fix kinesis dsm flaky tests

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DBMCompatibleConnectionInstrumentation.java

Seen on a recent ticket: if the `prepareCall` is throwing exception, the return value will be null hence the WeakHashMap that's backing the context store will throw a NPE because does not support null keys
```
DEBUG datadog.trace.bootstrap.ExceptionLogger - Failed to handle exception in instrumentation for org.postgresql.jdbc.PgConnection
at com.blogspot.mydailyjava.weaklockfree.WeakConcurrentMap.get(WeakConcurrentMap.java:109)
at datadog.trace.agent.tooling.WeakMaps$Adapter.get(WeakMaps.java:68)
at datadog.trace.bootstrap.WeakMapContextStore.get(WeakMapContextStore.java:25)
at datadog.trace.bootstrap.FieldBackedContextStore.get(FieldBackedContextStore.java:19)
at org.postgresql.jdbc.PgConnection.prepareCall(PgConnection.java:459)
at …
```

dbm connection: do not access contextstore with null key

---

dd-java-agent/instrumentation/mongo/build.gradle
dd-java-agent/instrumentation/mongo/driver-3.1-core-test/build.gradle
dd-java-agent/instrumentation/mongo/driver-3.1/build.gradle
dd-java-agent/instrumentation/mongo/driver-3.10-sync-test/build.gradle
dd-java-agent/instrumentation/mongo/driver-3.3-async-test/build.gradle
dd-java-agent/instrumentation/mongo/driver-3.4/build.gradle
dd-java-agent/instrumentation/mongo/driver-3.7-core-test/build.gradle
dd-java-agent/instrumentation/mongo/driver-4.0/build.gradle
dd-java-agent/instrumentation/mongo/driver-4.0/src/main/java/datadog/trace/instrumentation/mongo/Arg2Advice.java
dd-java-agent/instrumentation/mongo/driver-4.0/src/main/java/datadog/trace/instrumentation/mongo/BaseClusterInstrumentation410.java
dd-java-agent/instrumentation/mongo/driver-4.0/src/main/java/datadog/trace/instrumentation/mongo/DefaultConnectionPoolInstrumentation410.java
dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/Mongo4ClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/MongoReactiveClientTest.groovy
dd-java-agent/instrumentation/mongo/src/test/groovy/MongoBaseTest.groovy

MongoDB 4.10-11 instrumentation fix
In mongo-java-driver starting from 4.10 some instrumented classes has changed method signatures.
Specifically, the `BaseCluster` and `DefaultConnectionPool` classes have changed the `selectServerAsync` and `getAsync` method signatures:
`BaseCluster` class:
4.9 - `public void selectServerAsync(final ServerSelector serverSelector, final SingleResultCallback<ServerTuple> callback)`
4.10 - `public void selectServerAsync(final ServerSelector serverSelector, final OperationContext operationContext, final SingleResultCallback<ServerTuple> callback)`
`DefaultConnectionPool` class:
4.9 - `public void getAsync(final SingleResultCallback<InternalConnection> callback)`
4.10 - `public void getAsync(final OperationContext operationContext, final …

MongoDB 4.10-11 instrumentation fix

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/TaintedMap.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/TaintedObject.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/TaintedObjects.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedMapTest.groovy
internal-api/src/main/java/datadog/trace/api/iast/telemetry/IastMetric.java

This PR adds two different boundaries to the tainted map implementation:
- **Max age**: limits the max time an entry can stay in the map. A bug in the code can cause us to create strong references to the original values, in that case, their respective tainted values will stay forever in the map causing memory issues. This limit will ensure that this case does not happen.
- **Max bucket size**: when adding tainted values to the same bucket, the performance can quickly degrade due to the linked list nature of the map. This PR limits the max size of each bucket to prevent the performance degradation.
Maps of tainted objects can grow a lot (specially if we move to a global tainted dictionary strategy). This PR ensures that we put in place the required boundaries to enforce a correct memory …

Add time and bucket size boundaries to the tainted map

---

dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/test/groovy/CouchbaseClient31Test.groovy
dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/test/groovy/CouchbaseClient32Test.groovy

Silently ignores `cluster.disconnect()` error on cleanup

couchbase tests: ignore errors on cleanup

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexBuilder.java

Updates repository indexing logic: if the repository contains a symlink that points inside the repository, this symlink will not be indexed.
The folder/file that the symlink points to will be indexed anyway, since it is located inside the repository.
Moreover, if we do index the symlink, the index will contain two paths for the same file - one containing the symlink, the other containing the actual folder path. This can lead to errors, since depending on the indexing order the source path for a class can be resolved into either of the two paths.
This is a duplicate of [PR#6401](https://github.com/DataDog/dd-trace-java/pull/6401) for v1.26.1 patch release.
Jira ticket: [CIVIS-8403]
[CIVIS-8403]: https://datadoghq.atlassian.net/browse/CIVIS-8403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

Update repo indexer to not follow symlinks that point inside the repo

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/iast/NamedContext.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/iast/NamedContextTest.groovy
dd-java-agent/instrumentation/akka-http-10.0/src/iastTest/groovy/datadog/trace/instrumentation/akkahttp/iast/IastAkkaTest.groovy
dd-java-agent/instrumentation/jackson-core/build.gradle
dd-java-agent/instrumentation/jackson-core/jackson-core-1/build.gradle
dd-java-agent/instrumentation/jackson-core/jackson-core-1/src/main/java/datadog/trace/instrumentation/jackson/codehouse/core/Json1ParserInstrumentation.java
dd-java-agent/instrumentation/jackson-core/jackson-core-1/src/test/groovy/Json1ParserInstrumentationTest.groovy
dd-java-agent/instrumentation/jackson-core/src/main/java/datadog/trace/instrumentation/jackson/core/Json2ParserInstrumentation.java
dd-java-agent/instrumentation/jackson-core/src/test/groovy/Json2FactoryInstrumentationTest.groovy
dd-java-agent/instrumentation/jackson-core/src/test/groovy/Json2ParserInstrumentationTest.groovy
dd-java-agent/instrumentation/pekko-http-1.0/src/iastTest/groovy/datadog/trace/instrumentation/pekkohttp/iast/IastPekkoTest.groovy
dd-java-agent/instrumentation/spring-webflux-5/src/iastTest/groovy/datadog/trace/instrumentation/springwebflux/server/IastTestController.groovy
dd-java-agent/instrumentation/spring-webflux-5/src/iastTest/groovy/datadog/trace/instrumentation/springwebflux/server/IastWebFluxTest.groovy
dd-java-agent/instrumentation/spring-webflux-6/src/iastTest/groovy/datadog/trace/instrumentation/springwebflux6/server/IastWebFluxTest.groovy

Adds a new context to store property names to be used when tainting values in Jackson deserialization.
Jira ticket: [APPSEC-11919]
[APPSEC-11919]: https://datadoghq.atlassian.net/browse/APPSEC-11919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for names in jackson propagation

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastSystem.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sensitive/SensitiveHandlerImpl.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HeaderInjectionModuleImpl.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/HttpHeader.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/HttpResponseHeaderModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintUtils.groovy
dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite.yml
dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/AbstractServerHttpRequestInstrumentation.java
dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/HttpHeadersInstrumentation.java
dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/HttpMessageInstrumentation.java
dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/ReactorServerHttpRequestInstrumentation.java
dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/ServerServletHttpRequestInstrumentation.java
dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/TaintHttpHeadersGetAdvice.java
dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/TaintHttpHeadersToSingleValueMapAdvice.java
dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/iast/TaintReadOnlyHttpHeadersAdvice.java
dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/HeadersAdviceForkedTest.groovy
dd-java-agent/instrumentation/spring-webflux-5/src/test/java/foo/bar/DummyRequest.java
dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
internal-api/src/main/java/datadog/trace/api/iast/InstrumentationBridge.java
internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityMarks.java
internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityTypes.java
internal-api/src/main/java/datadog/trace/api/iast/sink/HeaderInjectionModule.java

Implements detection of header injection vulnerabilities
To increase the scope of the security vulnerability detection functionality
Please note that there is instrumentation for webflux so we can separate the cases where the headers come from the request from the cases where the headers come from the response. Previously all headers were tainted even if they were response headers, this would cause false header injection positives.

Header injection vulnerability detection

---

buildSrc/build.gradle.kts
buildSrc/src/test/groovy/InstrumentPluginTest.groovy
gradle/dependencies.gradle

Updates byte-buddy to a version compiled with ASM 9.6 (we previously upgraded ASM in #5992)

byte-buddy 1.14.9

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterFlare.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterState.java

Will end up in `instrumenter_state.txt` in the tracer-flare. Example output:
```
org.springframework.boot.loader.LaunchedURLClassLoader
APPLIED  datadog.trace.instrumentation.classloading.ClassloadingInstrumentation  [classloading]
APPLIED  datadog.trace.instrumentation.hibernate.core.v4_0.QueryInstrumentation  [hibernate, hibernate-core]
APPLIED  datadog.trace.instrumentation.hibernate.core.v4_0.SessionFactoryInstrumentation  [hibernate, hibernate-core]
APPLIED  datadog.trace.instrumentation.hibernate.core.v4_0.SessionInstrumentation  [hibernate, hibernate-core]
APPLIED  datadog.trace.instrumentation.hibernate.core.v4_3.SessionInstrumentation  [hibernate, hibernate-core]
APPLIED  datadog.trace.instrumentation.java.concurrent.AsyncPropagatingDisableInstrumentation  [java_concurrent] …
```

Report instrumenter state in tracer-flare

---

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OtelContext.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/ContextTest.groovy

This PR changes the Context key to retrieve the local root span from OpenTelemetry `Context`.
It will now use the same key as the OpenTelemetry SDK making it compatible with SDK `LocalRootSpan` behavior. 
This will increase compatibility with OTel SDK and OTel instrumenter API. 
This behavior change is following the gap analysis of Micronaut Tracing features.
The related documentation update PR: https://github.com/DataDog/documentation/pull/21122
Jira ticket: [APMJAVA-1151]
[APMJAVA-1151]: https://datadoghq.atlassian.net/browse/APMJAVA-1151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use OpenTelemetry SDK context key instead of Datadog proprietary one for local root span

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/AvroSchemaExtractor.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/AvroMock.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/AvroMockSerializer.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
dd-smoke-tests/datastreams/kafkaschemaregistry/build.gradle
dd-smoke-tests/datastreams/kafkaschemaregistry/src/main/java/datadog/smoketest/datastreamskafka/KafkaProducerWithSchemaRegistry.java
dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsMonitoring.java
dd-trace-core/src/main/java/datadog/trace/core/datastreams/SchemaSampler.java
dd-trace-core/src/test/groovy/datadog/trace/core/datastreams/DefaultDataStreamsMonitoringTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/datastreams/SchemaSamplerTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentDataStreamsMonitoring.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
settings.gradle

This PR adds the Avro schema definition as a tag on the span if the schema can be found in the schema field of the sent object.
This is only done if data streams is enabled.

Track Kafka Avro schemas using Data Streams

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/SegmentlessTestProbes.java

Optimises code coverage for multi-threaded tests.
Reducing code coverage overhead.
Tests that are multi-threaded are different from tests that are executed concurrently: the latter imply running multiple tests in parallel in different threads. A multi-threaded test is a single test that runs in multiple threads (e.g. a test that creates a thread pool or uses a fork-join pool). 
Previous version of the code used a single `ConcurrentHashMap` instance per test to store covered classes, but given how often coverage probes are activated, some tests showed heavy contention and a lot of overhead.
The new version maintains a separate map of covered classes for each execution thread of a test, thus reducing contention.
`com.dd.logs.shardingbalancer.ShardingWFZBalancerTest#it_should_be_better` test …

Optimise per-test code coverage for multi-threaded tests

---

dd-trace-core/src/main/java/datadog/trace/civisibility/writer/ddintake/CiTestCovMapperV2.java
dd-trace-core/src/test/groovy/datadog/trace/civisibility/writer/ddintake/CiTestCovMapperV2Test.groovy

Fixes test coverage reporter to avoid submitting multiple identical coverage reports for test traces that contain children spans that are "top-level".
Code coverage logic obtains coverage probes store by examining the currently active span.
If the active span is a child of a test span (e.g. if coverage probe is triggered inside a database request inside a test), it refers to the same coverage store as its parent test.
Therefore, when coverage reporter receives a trace, it may contain multiple spans that refer to the same coverage store.
All of such spans except for the test spans (that are trace roots) should be ignored, when obtaining test coverage reports for submission.
Submitting multiple identical report does not break anything in the backend but is a waste of computational …

Avoid submitting multiple identical coverage reports when test span has children that are top-level spans

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/TracingConfigPoller.java
internal-api/src/main/java/datadog/trace/api/DynamicConfig.java
internal-api/src/main/java/datadog/trace/api/TraceConfig.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

Avoids inconsistencies by having a single canonical place to track dynamic debug state. Since all code that checks dynamic debug state currently uses `log.isDebugEnabled()` it makes sense for that to be `GlobalLogLevelSwitcher`.
This also lets us simplify the `TraceConfig` interface.
At the same time also remove the triage flag from `TraceConfig` which is not being used yet. Instead we'll provide `prepare` and `cleanup` methods in `TracerFlare.Reporter` which will let individual reporters decide how best to temporarily collect triage data. 

Make logging the canonical holder of the dynamic debug state

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ProxyClassIgnores.java

Javassist proxy separator changed in https://github.com/jboss-javassist/javassist/commit/3358dc269352383eb5e9c186d24ff4a292eeb637
Not sure about the order if we can optimize some checks

add new javaassist proxy separator to ignores

---

dd-java-agent/instrumentation/spring-messaging-4/build.gradle

Help understanding failures of `SpringListenerSQSTest`. It fixes slf4j dependences that today are too recent and fails binding logback factory. 

fix logging dependencies for spring-messaging tests

---

dd-java-agent/instrumentation/maven-3.2.1/build.gradle

maven-embedder 4.0.0-alpha-10 made these dependencies provided (ie non-transitive), so we now need to declare them for testing purposes

Fix maven tests for 4.0.0-alpha-10

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/WellKnownClasses.java
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_12.json
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/SerializerWithLimits.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/StringTokenWriter.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot08.java

We access directly to the value of an Optional through the `java.util.Optional` API rather than using the reflection as since JDK 16 it will be prohibited.
Avoid using reflection on some JDK classes that is prohibited since JDK 16
Jira ticket: [DEBUG-1980]
[DEBUG-1980]: https://datadoghq.atlassian.net/browse/DEBUG-1980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add specific support for Optional

---

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/AgentDebuggerIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SpanProbesIntegrationTest.java

take into account the new emitting probe status sent when generating data

Fix flaky smoke tests

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterFlare.java
dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlarePoller.java
dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlareService.java
internal-api/src/main/java/datadog/trace/api/flare/TracerFlare.java
internal-api/src/test/groovy/datadog/trace/api/flare/TracerFlareTest.groovy

Tracer-flare lifecycle:
1. Agent creates an RC config to prepare the tracer for the flare
* tracer calls `prepareForFlare` for each registered reporter
2. Agent creates an RC task to create and send the tracer flare
* tracer starts to build a zip and adds basic details (config, etc.)
* tracer calls `addReportToFlare` for each registered reporter
* tracer completes the zip and sends it back to the agent
3. Agent removes the previous RC config and task
* tracer calls `cleanupAfterFlare` for each registered reporter
If the flare RC config sets logging to debug then the tracer temporarily overrides its logging to be debug too.
This logging override is removed as part of cleanup.
If the agent forgets to remove the RC config then the tracer automatically triggers cleanup after 20 minutes.
Jira …

Allow tracer-flare reporters to participate in the prepare+cleanup lifecycle

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java

Previously, in case of failed resolution from probe id we retransformed the current class to make sure the code is in sync with probe definitions. if a loop was still executing instrumented code, this can lead to a storm of retransformation which can hurt significantly performance of the application (retransform is STW). we now do nothing except log a warning and send it as telemetry.
avoid performance issue in rare cases
Jira ticket: [DEBUG-2022]
[DEBUG-2022]: https://datadoghq.atlassian.net/browse/DEBUG-2022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove retransformation on failed resolution

---

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/DSL.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/JsonToExpressionConverter.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/ComparisonExpression.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/ComparisonOperator.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/ComparisonExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_05.json
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java

Add comparison operator `instanceof` to test object value against a class type provided as string.
class type is looked up using `Class::forName` and the classloader of the left value.
Jira ticket: [DEBUG-1979]
[DEBUG-1979]: https://datadoghq.atlassian.net/browse/DEBUG-1979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `instanceof` operator in Expression Language

---

dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ControllerFactory.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

Adds a debug config option to allow manually disabling the JFR profiler
Debugging weird issues with JFR repository we are seeing at some customers
Jira ticket: [PROF-8843]
[PROF-8843]: https://datadoghq.atlassian.net/browse/PROF-8843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow disabling JFR profiler manually via configuration

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java

Manually reverts https://github.com/DataDog/dd-trace-java/pull/6367
Enable diagnostics to be sent to DEBUGGER track if datadog agent supports it.

Enable diagnostics on debugger track

---

telemetry/src/main/java/datadog/telemetry/TelemetryRequest.java
telemetry/src/main/java/datadog/telemetry/TelemetryRequestBody.java
telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
telemetry/src/test/groovy/datadog/telemetry/TestTelemetryRouter.groovy

Includes info about Dynamic Instrumentation into the app-started telemetry event.
The Dynamic Instrumentation (also known as Live Debugger) were not included in the app-started telemetry event.
[RFC: Dynamic Instrumentation Schema](https://github.com/DataDog/instrumentation-telemetry-api-docs/blob/main/GeneratedDocumentation/ApiDocs/v2/SchemaDocumentation/Schemas/dynamic_instrumentation.md)

Include dynamic_instrumentation product into the app_started telemetry event

---

dd-java-agent/instrumentation/opentelemetry/opentelemetry-0.3/src/test/groovy/OpenTelemetryTest.groovy
dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
dd-trace-core/src/main/java/datadog/trace/core/monitor/TracerHealthMetrics.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDIntakeWriterCombinedTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/monitor/HealthMetricsTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/OpenTracingAPITest.groovy

This will help us report these counts to tracer-flare in the near future.
It also reduces the number of immediate statsd requests, by accumulating counts and sending them on a fixed schedule.
The remaining immediate statsd requests in `TracerHealthMetrics` are reporting the tracer queue size on startup (which only happens once) and API responses where the status was not OK (where the metrics tag is derived from the status.) 
Note for tracer-flare it is enough to just have the number of OK responses - if that is drastically different to the number of requests then the full set of metrics with their status code tags can be examined in the UI.
[APMJAVA-1078]: https://datadoghq.atlassian.net/browse/APMJAVA-1078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

Introduce more local counters for tracer health metrics

---

dd-trace-core/src/main/java/datadog/trace/core/monitor/TracerHealthMetrics.java
internal-api/src/main/java/datadog/trace/api/metrics/SpanMetricsImpl.java

...while still reporting delta metrics between each report (assumes single reporter)
This lets us report total counts in the tracer-flare triage report, instead of just the counts since the last report.

Keep historical tracer health/span counts

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/DDTestSessionImpl.java

Adds synchronous flush of pending traces after test session finishes.
When build system is instrumented, it is the build process that handles the session event - Maven or Gradle daemon.
When running a Gradle build inside a CI provider (e.g. Github Actions), the daemon is killed as soon as it reports that the build has been completed.
Depending on the timing, this can happen before pending traces (including the session event) have been flushed.
Flushing the traces synchronously ensures that no events get lost.
Jira ticket: [CIVIS-8453]
[CIVIS-8453]: https://datadoghq.atlassian.net/browse/CIVIS-8453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Synchronously flush test session finish event

---

dd-java-agent/instrumentation/spring-messaging-4/src/test/groovy/SpringListenerSQSTest.groovy

Wait for async completion before closing parent span on sqs spring messaging test. Not waiting might cause the parent to finish before the children and have it (the root) buffered (clashing with strict trace writing and make the test fail)

spring sqs listener test: block on send

---

dd-trace-core/src/main/java/datadog/trace/core/monitor/HealthMetrics.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/TracerHealthMetrics.java

Minor cleanup:
* Arrange metrics into groupings in the code
* Remove unused `manualTraces` metric, was never called
* Publish metrics that were collected but never submitted:
* `serialFailedDroppedSpans` and `capturedContinuations`
* Consistent naming
[APMJAVA-1077]: https://datadoghq.atlassian.net/browse/APMJAVA-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tidy up tracer health metrics

---

dd-java-agent/src/test/groovy/datadog/trace/agent/CustomMBeanServerBuilderTest.groovy

According to some failed test logs, telemetry thread termination can take some additional time (also because retries before deciding to directly send things to intake). In the scope of this test, telemetry is not required hence disabled in order to let the test pass easier

avoid extra time due to telemetry for jmx tests

---

dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/AgentStatsdReporter.java
dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java

This PR temporarily records JMXFetch metrics sent between preparing for the tracer-flare and capturing the flare.
It's expected that several minutes will elapse between the remote-config events to prepare for the flare and capture it, which is more than enough time to cover at least one JMXFetch report cycle.

Provide summary of JMXFetch for tracer-flare

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Instrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java

To make sure we measure the duration of method using `@duration` metric value in case of exception, we add a finally block with the metric call
Jira ticket: [DEBUG-1946]
[DEBUG-1946]: https://datadoghq.atlassian.net/browse/DEBUG-1946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add finally block for `@duration` metric

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/TPEHelper.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinPoolInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaTimerInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java

* add missing checks to `JavaForkJoinPoolInstrumentation` and `JavaTimerInstrumentation`
* move `startQueuingTimer` from `ThreadPoolExecutorInstrumentation` to when we know we've captured the task in `TPEHelper`
Avoids attempts to access context-stores of task types that have been explicitly excluded.

Be consistent when checking if tasks are excluded from wrapping/injection

---

dd-java-agent/instrumentation/aerospike-4/build.gradle

Aerospike 8 requires java 21 according to the [release notes](https://download.aerospike.com/download/client/java/notes.html#8.0.0). We lock latestDep and muzzle since a jdk 21 will be officially part of the CI build

lock aerospike to < 8

---

telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java

It adds a pause between retries that allows OkHttp to release a non-daemon Writer thread that would otherwise prevent the application from exiting.
Fix for #6432

Fix Telemetry App-Started event retry that prevents the application from exiting.

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymDBEnablement.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymbolExtractionTransformer.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymbolExtractionTransformerTest.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction01.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction02.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction03.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction04.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction05.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction06.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction07.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction08.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction09.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction10.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction11.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction12.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction13.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction14.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/symboltest/SymbolExtraction15.java

Hard code exclusion of `com.datadog.debugger.symbol` package to avoid duplicate class definition when loading a class from this package that will be transform by SymbolExtractionTransformer

Fix issue for parsing classes from debugger.symbol

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java

left over during some debug session

Remove debug logs when not sampled

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/TaintedMap.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedMapTest.groovy

Fixes tainted map test being flaky due to relying on `Thread.sleep` to ensure items are purged after a certain amount of time.

Fix flaky test due to usage of Thread.sleep

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ConfigurationApiImpl.java

Updates URI and expected response format for the endpoint that provides the list of known flaky tests.
Fetching the list of flaky tests is needed for implementing flaky tests retries.
The backend API was unstable and has changed recently.
Flaky tests retries has not been officially released yet.
Jira ticket: [CIVIS-8243]
[CIVIS-8243]: https://datadoghq.atlassian.net/browse/CIVIS-8243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update flaky tests endpoint URI and response format

---

dd-java-agent/instrumentation/zio/zio-2.0/src/main/java/datadog/trace/instrumentation/zio/v2_0/FiberContext.java
dd-java-agent/instrumentation/zio/zio-2.0/src/main/java/datadog/trace/instrumentation/zio/v2_0/ZioRuntimeInstrumentation.java

Provides several fixes to the zio instrumentation hence resolving as well the flakiness of tests.
* Excludes `zio.internal.FiberRuntime` from context propagation since this is done via the instrumentation itself (supervisor)

zio: fix context propagation

---

dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/main/java/datadog/trace/instrumentation/jakarta3/JakartaRsAnnotationsDecorator.java
dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/main/java/datadog/trace/instrumentation/jakarta3/JakartaRsAnnotationsInstrumentation.java
dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/test/groovy/JakartaRsAnnotations3InstrumentationTest.groovy
dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/test/java/CustomMethod.java
dd-java-agent/instrumentation/jax-rs-annotations-1/src/main/java/datadog/trace/instrumentation/jaxrs1/JaxRsAnnotationsDecorator.java
dd-java-agent/instrumentation/jax-rs-annotations-1/src/main/java/datadog/trace/instrumentation/jaxrs1/JaxRsAnnotationsInstrumentation.java
dd-java-agent/instrumentation/jax-rs-annotations-1/src/test/groovy/JaxRsAnnotations1InstrumentationTest.groovy
dd-java-agent/instrumentation/jax-rs-annotations-1/src/test/java/CustomMethod.java
dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/JaxRsAnnotationsDecorator.java
dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/JaxRsAnnotationsInstrumentation.java
dd-java-agent/instrumentation/jax-rs-annotations-2/src/test/groovy/JaxRsAnnotations2InstrumentationTest.groovy
dd-java-agent/instrumentation/jax-rs-annotations-2/src/test/java/CustomMethod.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java

Supports the following jaxrs annotations:
* `io.dropwizard.jersey.PATCH` (custom for dropwizard)
* `javax.rs.ws.PATCH` (standard from jaxrs 2.1)
* `jakarta.rs.ws.PATCH` (standard)
Also allows including other annotations for method advising by providing comma separed list of annotation classnames on the system property `dd.trace.jax-rs.additional.annotations` or the env `DD_TRACE_JAX_RS_ADDITIONAL_ANNOTATIONS`
Please note that, for simplicity, we do not check that the annotation is complying with the jaxrs spec (i.e. be annotated with `@HttpMethod`). 
Also, the method name on the resource is no more the annotation name (that's conceptually wrong) but the value of the annotation `HttpMethod`. This is not a breaking change since today the annotations have the same name than the http method …

support PATCH and other custom jaxrs annotations

---

dd-java-agent/agent-bootstrap/src/main/resources/META-INF/native-image/com.datadoghq/dd-java-agent/reflect-config.json
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryInstrumentation.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/propagation/AgentTextMapPropagator.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/propagation/TraceStateHelper.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelSpanContext.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelSpanLink.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/AbstractPropagatorTest.groovy
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/B3MultiPropagatorTest.groovy
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/B3SinglePropagatorTest.groovy
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/DatadogPropagatorTest.groovy
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/OtelW3cPropagatorTest.groovy
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/W3cPropagatorTest.groovy
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/propagation/W3cPropagatorTracestateTest.groovy

This PR will ensure that extracted context from OpenTelemetry API will respect W3C tracestate if any.
Such context can then be used as parent span or span links.
This will improve OpenTelemetry interoperability.
Previously, the W3C tracestate was dropped and not propagated to any downstream service.
Jira ticket: [APMJAVA-1060]
[APMJAVA-1060]: https://datadoghq.atlassian.net/browse/APMJAVA-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for tracestate extraction from OpenTelemetry API

---

dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlareService.java

For consistency with .NET tracer flare, also helps when multiple flare files might get generated for the same case.

Add case_id and epoch time to flare_file name

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/CombiningMatcher.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/MatchRecorder.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/SplittingTransformer.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterFlare.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterMetrics.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/ClassFileLocators.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/memoize/Memoizer.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java

To enable collection use `DD_TRACE_TRIAGE=true`
Reports the following metrics under `instrumenter_metrics.txt` in the tracer-flare:
```
----------------------------------------------------------------
Matching:              4512         557.6 ms
Transforming:          140          254.7 ms
----------------------------------------------------------------
Known type hit:        26           0.2 ms
Known type miss:       4486         1.9 ms
Type hierarchy hit:    104          1.0 ms
Type hierarchy miss:   527793       389.1 ms
Context store hit:     29           0.3 ms
Context store miss:    397027       48.9 ms
Narrow location hit:   141          21.1 ms
Narrow location miss:  21           2.1 ms
Narrow type hit:       0            0.0 ms
Narrow type miss:      0            0.0 ms …
```

Add Instrumenter metrics to tracer-flare

---

dd-java-agent/instrumentation/grpc-1.5/build.gradle
dd-java-agent/instrumentation/mongo/driver-4.0/build.gradle
dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/Mongo4ClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/MongoReactiveClientTest.groovy

Because 5.0.0-beta0 is out and the version parser was broken

fix mongo 4 tests

---

dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/ProcessImplStartAdvice.java

Skips creating a process span for process execution that is initialized from one of the agent internal threads.
Internal calls to `hostname` and other commands from the agent during setup runs at various times and pollute smoke tests with unrelated traces.

Don't create a process span for agent internal threads

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTracerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanProbeInstrumentationTest.java

To make sure on a same method all probe defined on this location are instrumented in right order to interact each other. Order of instrumentation is:
- metric probes
- log probes
- span decoration probes
- span probes 
This way the last probe wraps method body and all other instrumented code.
Span should be first to be executed to create a span for the current method then span decoration should add tags for this new span. Logs should be decorated with trace/span ids for the current method. Finally metric are last because no dependency.
Jira ticket: [DEBUG-1752]
[DEBUG-1752]: https://datadoghq.atlassian.net/browse/DEBUG-1752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enforce ordering of probe instrumentation

---

dd-java-agent/instrumentation/log4j1/build.gradle
dd-java-agent/instrumentation/log4j1/src/main/java/datadog/trace/instrumentation/log4j1/LoggingEventInstrumentation.java
dd-java-agent/instrumentation/log4j1/src/test/groovy/MdcTest.groovy

Recently the log4j1 instrumentation has been changed to be compatible with dynamic config but a regression has been introduced. The copyMdcMethod is returning without effectively copying the mdc when the injection is disabled.
The MDC copy is especially used on asynchronous loggers when the logged event should carry contextual information since logged after on another thread.  So, potentially, customers using async appenders and explicitly disabling log injection could experience in this situation having the mdc wiped out
This PR fixes this behaviour and adds a test for both logs injection enabled and disabled. Also, shunting methods is quite dangerous so I preferred not to skip the original `getMdcCopy` method. I put also some simplifications by not copying the mdc hashtable, since, …

log4j: preserve mdc when copied and injection is disabled

---

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

It adjusts the enablement logic for allocation and liveheap profiling when using ddprof-java
In the anticipation of [JDK-8313816](https://bugs.openjdk.org/browse/JDK-8313816) it will become completely safe to enable allocation and liveheap profiling on the latest updates of LTS Java versions.
The liveheap will not be enabled by default, however, since it is still not considered GA, but rather will log a warning when explicitly enabled on an inherently unsafe JDK version.
Jira ticket: [PROF-8839]
[PROF-8839]: https://datadoghq.atlassian.net/browse/PROF-8839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update the enablement logic for allocation and liveheap

---

.circleci/config.continue.yml.j2
build.gradle
dd-java-agent/agent-debugger/build.gradle
dd-java-agent/agent-profiling/build.gradle

Skips the `debugger` tests in the `base` configuration to avoid running them twice.
While looking at upgrading some test dependencies I noticed that it seem like the `debugger` tests run as part of the `base` tests https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/33016/workflows/da5dc872-792f-4c99-ba27-27a2c6e22726/jobs/1149959/tests

Don't run debugger tests twice in CI

---

dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy

Skips the failing maven version `v4.0.0-alpha-12` in the maven smoke tests.
Blocks CI

Skip failing maven version v4.0.0-alpha-12

---

dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

Hides the cleanup code behind a debug flag
Do not run the clean up automatically but only as requested because it might cause issues with multiple profiled processes on the same machine when running a non-hotspot JVM.

Guard the JFR repo cleanup by a debug flag

---

dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/ProcessImplStartAdvice.java
dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/ProcessImplInstrumentationSpecification.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/java/lang/ProcessImplInstrumentationHelpers.java

Process spans for failed process executions had `error.message`, but not `error.type` and `error.stack`.

Add missing error tags to process spans

---

dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenUtils.java
dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy

- Fixes Maven smoke tests following release `4.0.0-alpha-12`
- Disables Maven smoke tests for "alpha" versions
Alpha versions are unstable and lately have been released frequently.
Maven instrumentation will be updated (if needed), when 4.0 is officially released.
Jira ticket: [CIVIS-8583]
[CIVIS-8583]: https://datadoghq.atlassian.net/browse/CIVIS-8583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Maven instrumentation following the latest release. Disable Maven smoke tests for alpha versions

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlareService.java
internal-api/src/main/java/datadog/trace/api/Config.java

To schedule a triage report two minutes after startup add this JVM option:
```
-Ddd.triage.report.trigger=2m
```
```
DD_TRIAGE_REPORT_TRIGGER=2m
```
Units of `h` (hours) and `s` (seconds) are also accepted, the default unit when omitted is seconds.
The report will be written to `$TMPDIR` by default, to choose a different location use:
```
-Ddd.triage.report.dir=/example/reports/
```
or
```
DD_TRIAGE_REPORT_DIR=/example/reports/
```
the report zip will be named `dd-java-flare-<epoch-time-in-millis>.zip`
For situations where remote-config or the tracer-flare endpoint is not available but we'd like to capture a triage report.
[APMJAVA-1078]: https://datadoghq.atlassian.net/browse/APMJAVA-1078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …

Support delayed trigger of local triage report

---

dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlareService.java

This makes the remote and local names consistent and helps identify flares from different JVMs under the same case-id.
Jira ticket: [APMJAVA-1076]
[APMJAVA-1076]: https://datadoghq.atlassian.net/browse/APMJAVA-1076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Java tracer flare name to be `dd-java-flare-<runtimeId>-<currentTimeMillis>.zip`

---

dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java

Adds a guard not to change the JFR repository location unless the cleanup-on-startup is required.
Changing the JFR repo location behind-the-scenes may be confusing

Do not change JFR repo location if cleanup not required

---

dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie

Enables call site generation for springs `LdapTemplate` (same logic as with `JdbcTemplate`)

Add call sites in spring ldap template

---

dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie

We had a weak randomness false positive here, and there's probably nothing else interesting in the rest of the package.
Jira ticket: [APPSEC-18259](https://datadoghq.atlassian.net/browse/APPSEC-18259)
[APPSEC-18259]: https://datadoghq.atlassian.net/browse/APPSEC-18259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add IAST exclusion for OpenTelemetry SDK package

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/telemetry/TelemetryRequestEndedHandler.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/telemetry/TelemetryRequestEndedHandlerTest.groovy
internal-api/src/main/java/datadog/trace/api/iast/telemetry/IastMetricCollector.java

Removes costly String.format operations that are not really needed

Replace string.format calls with regular concatenation

---

dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDLogger.java
dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDTelemetryLogger.java
dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/ddlogger/DDTelemetryLoggerTest.groovy

Logs for errors (e.g. exceptions) will be sent to telemetry regardless of minimum log level. This will ensure we receive logged exceptions from instrumentations (debug level) even if debug level is not set.
Our most important use case is detecting instrumentation bugs leading to internal exceptions, which are logged to debug level.
* Jira ticket: [APPSEC-17021](https://datadoghq.atlassian.net/browse/APPSEC-17021)
* Initial PR for this feature: #6057
[APPSEC-17021]: https://datadoghq.atlassian.net/browse/APPSEC-17021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Decouple telemetry logs from minimum log level

---

.github/workflows/README.md
.github/workflows/increment-milestones-on-tag.yaml
.github/workflows/update-issues-on-release.yaml

Skips the GitHub workflow milestone update when tags contain "-RC".  This allows multiple Release Candidates to be published with the same issues in the release notes.  Also does not update & close issues for releases of type `prerelease`.

Skip milestone and issues gh workflows for Release Candidates

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/RequestHeaderHandler.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HeaderInjectionModuleImpl.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/UnvalidatedRedirectModuleImpl.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/HttpHeader.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/HttpHeaderMap.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/HttpResponseHeaderModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/RangesTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/HttpHeaderMapTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/HttpHeaderTest.groovy

Refactors the `HttpHeader` class in order to reduce memory allocations while checking headers.

Refactor http headers to reduce memory allocations

---

.github/workflows/draft-release-notes-on-tag.yaml

This PR adds support for RC release to the release note draft generation.
The introduction of RC broke the tag naming conventions, so the milestone lookup.
Jira ticket: [APMJAVA-1197]
[APMJAVA-1197]: https://datadoghq.atlassian.net/browse/APMJAVA-1197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add release not draft support for RC

---

internal-api/build.gradle
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Baggage.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ImplicitContextKeyed.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ScopedContext.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ScopedContextKey.java

Draft API for supporting arbitrary context propagated across APIs, threads, etc.
We'd like to minimise the gap between our current context propagation model and OpeTelemetry's model.
This is the initial API, which follows the same semantics as OpenTelemetry - namely that each update results in an immutable context. We also introduce a specific interface to represent `Baggage` which should be propagated to child spans in the same context.
Jira ticket: [AIT-9455]
[AIT-9455]: https://datadoghq.atlassian.net/browse/AIT-9455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Scoped context API

---

.circleci/render_config.py
dd-java-agent/agent-debugger/build.gradle
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/BaseExceptionHandlerTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ExceptionHandlerExitOnFailureForkedTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ExceptionHandlerForkedTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinPoolInstrumentation.java
dd-java-agent/instrumentation/spring-scheduling-3.1/src/test/groovy/SpringSchedulingTest.groovy
dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/AdviceUtils.java
dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/RouteOnSuccessOrError.java
gradle/dependencies.gradle
internal-api/src/main/java/datadog/trace/util/MethodHandles.java

Enables Java 21 as one of the required JVM versions in CircleCI
We need to test on Java 21
* Corrects a number of smaller issues that failed some tests
* Does **_not_** add support for virtual threads executors
Jira ticket: [APMJAVA-1202]
[APMJAVA-1202]: https://datadoghq.atlassian.net/browse/APMJAVA-1202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enable Java 21 in CI

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot05.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java

When uncaught exceptions are captured we put them as local variables like return values. This way we can explore fields from custom exceptions from snapshots
Jira ticket: [DEBUG-2042]
[DEBUG-2042]: https://datadoghq.atlassian.net/browse/DEBUG-2042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `@exception` as local var in snapshots

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ProbeStatus.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/InstrumentationResult.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/ProbeStatusSink.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SymbolSink.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java

When a Java Tracer Flare is triggered we will collect some specific Dynamic Instrumentation information:
- Snapshot url
- Diagnostic url
- SymbolDB url
- Probe definitions
- Instrumentation done
- probe statuses
- SymbolDB stats
```
Snapshot url: http://localhost:8126/debugger/v1/input
Diagnostic url: http://localhost:8126/debugger/v1/diagnostics
SymbolDB url: http://localhost:8126/symdb/v1/input
Probe definitions:
{a73eb042-fd9f-4973-8fe2-7ca79d40ba7e:0=LogProbe{language='java', id='a73eb042-fd9f-4973-8fe2-7ca79d40ba7e', version=0, tags=[], tagMap={}, where=Where{typeName='null', methodName='null', sourceFile='CrashController.java', signature='null', lines=[57]}, evaluateAt=EXIT, template='In CrashController.java, line 57', segments=[Segment{str='In CrashController.java, line 57', …
```

Add TriageReport for Dynamic Instrumentation

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot05.java

We declare the missing local var if not present and store the exception present on the stack in it. then we collect as usual the local vars and the exception will be then present in the snapshot
if you want to put a line probe in an empty catch block, exception variable is not declared in that special case, so to capture it as local var we need to explicitly add it.
```
try {
throw new IllegalArgumentException("oops");
} catch (IllegalArgumentException ex) {
}
```
Jira ticket: [DEBUG-2045]
[DEBUG-2045]: https://datadoghq.atlassian.net/browse/DEBUG-2045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support special case of empty catch block

---

dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/ddlogger/DDTelemetryLoggerTest.groovy
internal-api/src/main/java/datadog/trace/api/telemetry/LogCollector.java
internal-api/src/test/groovy/datadog/trace/api/telemetry/LogCollectorTest.groovy
telemetry/src/main/java/datadog/telemetry/TelemetryRequestBody.java
telemetry/src/main/java/datadog/telemetry/api/LogMessage.java
telemetry/src/main/java/datadog/telemetry/log/LogPeriodicAction.java
telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
telemetry/src/test/groovy/datadog/telemetry/TestTelemetryRouter.groovy
telemetry/src/test/groovy/datadog/telemetry/log/LogPeriodicActionTest.groovy

* Fix deduplication for log messages with exceptions (throwable and usual implementations do not override equals/hashCode).
* Use the new `count` field for deduplicated messages.
We're getting several duplicated logs when exceptions are present.
Jira ticket: [APPSEC-51229](https://datadoghq.atlassian.net/browse/APPSEC-51229)
[APPSEC-51229]: https://datadoghq.atlassian.net/browse/APPSEC-51229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve telemetry log deduplication

---

remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java
remote-config/src/main/java/datadog/remoteconfig/state/ProductState.java
remote-config/src/test/groovy/datadog/remoteconfig/ConfigurationPollerSpecification.groovy

Improved remote config. Now you can define RC listener for both: _product_ and _product config_
- **product listener** (all configs are handled with the same listener). The legacy approach, and should be used only if remote config provides only one config with single well defined structure. In case if several configs provided, each will be processed by the same listener.
- **config listener** (only certain config will be handled by listener). New approach, created to handle cases when remote config provides multiple configs per product with different structures, so each config will be deserialised and parsed by it's own listener.
This PR is preparation work for #6340 
To add product listener:
```
ConfigurationPoller.addListener(product, deserialiser, listener)
```
To add config specific …

Added RC product listeners per config

---

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Reduce long running default flush interval to 120 seconds
User feedback: 5 minutes not being reactive enough
All internal spark jobs are already using 120 seconds for their flush interval

Reduce long running default flush interval to 120 seconds

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Range.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Source.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/VulnerabilityEncodingTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/PropagationModuleTest.groovy
internal-api/src/main/java/datadog/trace/api/iast/propagation/PropagationModule.java

Removes the string copies used for the `Source`'s name and values and replaces them with weak references to the original value. Once a vulnerability is found, the values are consolidated using copies.
The number of tainted objects present at runtime can vary quite a lot so we have to ensure we consume the minimum amount of memory.

Reduce the memory footprint of IAST sources

---

.circleci/config.continue.yml.j2

Add a latestDep pipeline on the CI build using a JVM 21

Add latestDepTest for Jvm 21 on CI

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInfoInstrumentation.java

Protect unsafe context access:
```
Failed to handle exception in instrumentation for org.apache.kafka.clients.consumer.KafkaConsumer
at datadog.trace.agent.tooling.WeakMaps$Adapter.put(WeakMaps.java:74)
```

KafkaConsumer: avoid null key context access

---

.gitlab-ci.yml

Forwards the build job ID to the downstream job
The downstream 'dogfooding' job will need the 'build' ID as well so it is able to download the build artifacts.
Jira ticket: [PROF-9001]
[PROF-9001]: https://datadoghq.atlassian.net/browse/PROF-9001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Forward the build job ID to downstream job

---

dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkSQLUtils.java
dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/AbstractSpark24SqlTest.groovy
dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/AbstractSpark32SqlTest.groovy

Relationships are captured with the two new fields
- `_dd.spark.sql_parent_stage_ids`, the list of stageIds that the current stage is dependant on
- `nodeId` for each node of the existing JSON plan in `_dd.spark.sql_plan`. It allows to capture which SQL nodes are used by multiple stages
Capture relationships between spark SQL stages so that they can be displayed linked together

Capture relationships between spark SQL stages

---

dd-java-agent/instrumentation/aerospike-4/build.gradle

* Add aerospike 8 latestDepTests (requires java 21)
* Keep latest test on 7.x branch since aerospike will maintain for some time

Add aerospike 8 latestDepTests

---

gradle/dependencies.gradle

This change syncs the vmstructs-based unwinder from async-profiler along with some performance optimisations to it: https://github.com/DataDog/java-profiler/releases/tag/v_0.96.0

Upgrade to ddprof 0.96.0

---

dd-trace-core/build.gradle
dd-trace-core/src/main/java/datadog/trace/common/sampling/SpanSamplingRules.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/TraceSamplingRules.java

This aims to prevent `No @ToJson` when `TraceSamplingRules` get initialized.
Fix for #6494
#6494

Fix for No @ToJson SamplingRules deserialization exception

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexBuilder.java

Changes log level of repo indexing error messages from ERROR to DEBUG.
Logging something as error implies that something is wrong with the application/build - ie. either the result can't be trusted or the system will eventually fail.
In the case of repo indexing errors, the issue breaks neither the tests, nor the tracer. Moreover, it is something that the users have no influence over, so we're effectively spamming their logs with errors they cannot remove.
Jira ticket: [CIVIS-8777]
[CIVIS-8777]: https://datadoghq.atlassian.net/browse/CIVIS-8777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adjust log level or error messages written by repo indexer

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InstrumentationErrors.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/ExceptionHandlers.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/BaseExceptionHandlerTest.groovy
dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java
dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyTest.groovy
dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaServletBlockingHelper.java
dd-java-agent/instrumentation/servlet/request-5/src/test/groovy/JakartaHttpServletResponseInstrumentationTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy

Force test failure on unhandled instrumented exception

---

telemetry/src/main/java/datadog/telemetry/log/LogPeriodicAction.java
telemetry/src/test/groovy/datadog/telemetry/log/LogFilteringTest.groovy

Our backend will process both, so just use the simplest convention.

Use \n for new line in telemetry log stacktraces

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/StringTemplateBuilder.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java

Telemetry log will send log with exception as parameter. Exceptions for expression evaluation can be very noisy because evaluated for each execution.
too much telemetry logs for faulty expression in probe definitons

Remove noisy telemetry log with exception

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/core/BlackholeSpanTest.groovy

When `trace.128.bit.traceid.logging.enabled` is `true` and the aws instrumentation is not using the legacy tracing (by default) a NumberFormatException like this is thrown:
```
java.lang.NumberFormatException: String value xxxxxxxxx exceeds range of unsigned long.
at datadog.trace.api.internal.util.LongStringUtils.numberFormatOutOfLongRange(LongStringUtils.java:130)
at datadog.trace.api.internal.util.LongStringUtils.parseUnsignedLong(LongStringUtils.java:91)
at datadog.trace.api.DDTraceId.from(DDTraceId.java:38)
at datadog.trace.agent.core.CoreTracer.blackholeSpan(CoreTracer.java:894)
```
This PR adds a tests and fix to remediate to it

Avoid NumberFormatException when logging 128bit trace ID

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/IastConnectionCallSite.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/IastStatementCallSite.java

Uses context stores to cache the `DBInfo` instances computed for JDBC connections
The computation of the DBInfo is not cheap, so we should use the cached instances included in the context stores.

Do not compute DBInfo on every statement call

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/CookieSecurityParser.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/HttpHeader.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/HttpResponseHeaderModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/CookieSecurityParserTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/HttpHeaderTest.groovy

Improves the performance of the cookie parser by reducing string allocations and avoiding going over the string more than once, and only creating new strings for what is needed
In applications making heavy usage of cookies the parse might become effectively a bottleneck.

Improve the performance of the IAST cookie parser

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/telemetry/TelemetryRequestEndedHandler.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/telemetry/TelemetryRequestEndedHandlerTest.groovy
internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityTypes.java
internal-api/src/main/java/datadog/trace/api/iast/telemetry/IastMetric.java
internal-api/src/main/java/datadog/trace/api/iast/telemetry/IastMetricCollector.java
internal-api/src/test/groovy/datadog/trace/api/iast/SourceTypesTest.groovy
internal-api/src/test/groovy/datadog/trace/api/iast/VulnerabilityTypesTest.groovy
internal-api/src/test/groovy/datadog/trace/api/iast/telemetry/IastMetricCollectorTest.groovy
internal-api/src/test/groovy/datadog/trace/api/iast/telemetry/IastMetricTest.groovy
telemetry/src/test/groovy/datadog/telemetry/metric/IastMetricPeriodicActionTest.groovy

Caches the tag values to be used in telemetry metrics and also the values to be used in the span tags in order to troubleshoot IAST.
There's quite a performance overhead of having to compute those tags every time, having them cached reduced the number of string allocation and the time spent while generating the metrics.

Cache IAST metric tag values to be used in metrics and spans

---

internal-api/src/main/java/datadog/trace/util/stacktrace/StackUtils.java
internal-api/src/test/java/datadog/trace/util/stacktrace/StackUtilsTest.java
telemetry/src/main/java/datadog/telemetry/log/LogPeriodicAction.java
telemetry/src/test/groovy/datadog/telemetry/log/LogPeriodicActionTest.groovy

* If a frame or group of consecutive frames are redacted, a line will still be sent (e.g. `  at [redacted: 2 frames]`). This will simplify finding the root cause.
* Avoid redacting jdk, sun, com.sun packages.
Before this PR, we could see something like this:
```
Failed to handle exception in instrumentation for org.apache.kafka.clients.consumer.KafkaConsumer
at datadog.trace.agent.tooling.WeakMaps$Adapter.put(WeakMaps.java:74)
at datadog.trace.bootstrap.WeakMapContextStore.put(WeakMapContextStore.java:31)
at datadog.trace.bootstrap.FieldBackedContextStore.put(FieldBackedContextStore.java:28)
...
```
Now we'll get:
```
Failed to handle exception in instrumentation for org.apache.kafka.clients.consumer.KafkaConsumer
at [redacted] …
```

Improve content of redacted stacktraces in telemetry logs

---

internal-api/src/main/java/datadog/trace/api/telemetry/LogCollector.java
internal-api/src/test/groovy/datadog/trace/api/telemetry/LogCollectorTest.groovy

Tracer time in logs is UNIX timestamp in seconds, per the spec.

Change telemetry logs tracer time to seconds

---

communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
communication/src/main/java/datadog/communication/http/OkHttpUtils.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/uploader/BatchUploaderTest.java
remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java
remote-config/src/main/java/datadog/remoteconfig/PollerRequestFactory.java
remote-config/src/test/groovy/datadog/remoteconfig/ConfigurationPollerSpecification.groovy
remote-config/src/test/groovy/datadog/remoteconfig/PollerRequestFactoryTest.groovy
remote-config/src/test/groovy/datadog/remoteconfig/Rcte1TestVectorsSpecification.groovy
telemetry/src/main/java/datadog/telemetry/TelemetryRequest.java
telemetry/src/test/groovy/datadog/telemetry/TestTelemetryRouter.groovy
utils/container-utils/src/main/java/datadog/common/container/ContainerInfo.java
utils/container-utils/src/test/groovy/datadog/common/container/ContainerInfoTest.groovy
utils/container-utils/src/test/groovy/datadog/common/container/ServerlessInfoTest.groovy

Adds `Datadog-Entity-ID` header.
Send a new HTTP header `Datadog-Entity-ID` to the trace-agent. This will allow us to cover more container tagging scenarios.
The reference implementation is in Go: https://github.com/DataDog/dd-trace-go/blob/main/internal/container_linux.go 
If the container ID (the value used for the `Datadog-Container-ID` header) is available and not empty, the value of `Datadog-Entity-ID` must be `cid-<container ID>` 
Else if the tracer runs in the host cgroup namespace (see [isHostCgroupNamespace](https://github.com/DataDog/dd-trace-go/blob/cb699a6311a6036cb3f4589b79db6169f9bbfd01/internal/container_linux.go#L170)), do not report `Datadog-Entity-ID`
Else the value of `Datadog-Entity-ID` must be `in-<cgroup inode>` (see …

Add Datadog-Entity-Id header

---

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/GetterAccess.java
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWS1ClientTest.groovy
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/LegacyAWS1ClientForkedTest.groovy
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test_before_1_11_106/groovy/AWS0ClientTest.groovy
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test_before_1_11_106/groovy/LegacyAWS0ClientForkedTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InstrumentationTags.java

Add `aws.object.key` for aws-sdk-1 to know which key is targeted by S3 get/put requests
More information on S3 request by having the key of the targeted object. It also unlocks object-level data lineage for S3

Add `aws.object.key` tag for aws-sdk-1

---

remote-config/src/main/java/datadog/remoteconfig/ConfigurationPoller.java
remote-config/src/test/groovy/datadog/remoteconfig/ConfigurationPollerSpecification.groovy

When there are no configuration changes, the agent can answer with HTTP 204 No Content. In that case, the tracer is working but produces an internal exception, which pollutes logs (and telemetry logs).
If we find HTTP 204 code, we just skip any further RC processing.

Handle remote config 204 responses gracefully

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastRequestContext.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
dd-trace-api/src/main/java/datadog/trace/api/internal/TraceSegment.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java

Add getters to query for data from the top of the current trace segment.
From IAST we want to be able to add vulnerabilities even when there is no active request (e.g. Kafka)
Jira ticket: [APPSEC-10440]
This is required to make IAST work in Kafka consumers: https://github.com/DataDog/dd-trace-java/pull/6465
[APPSEC-10440]: https://datadoghq.atlassian.net/browse/APPSEC-10440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Get access to tag values from the top of TraceSegments

---

dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilerSettingsSupport.java
dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/ProcessImplStartAdvice.java
internal-api/src/main/java/datadog/trace/api/Config.java

The tracer sometimes runs external processes in some cases. Currently, `hostname` and `getenforce`. The subprocess instrumentation creates spans for these, leading to visible `command_execution` spans for `hostname` and/or `enforce` which may be confusing to users.
This commit uses the bew blackhole span API (#6326) to mute tracing during when `hostname` and `getenforce` are run, preventing the creation of these spans.
Also reverts #6478, which would be redundant with the current cases.

Mute tracing for subprocesses executed in by the tracer

---

dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/ProcessImplStartAdvice.java
dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/ProcessImplInstrumentationSpecification.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/java/lang/ProcessImplInstrumentationHelpers.java

* cmd.exit_code was present but as an integer (metric).
* component tag was missing.
* 

Add component and fix cmd.exit_code tag in subprocess instrumentation

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/Fingerprinter.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/DefaultExceptionDebuggerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeManagerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/FingerprinterTest.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
dd-trace-core/build.gradle
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
internal-api/src/main/java/datadog/trace/api/Config.java

Hook into DDSpan::addThrowable to callback into debugger module to instrument the stacktrace and send snapshots.
This is still work-in-progress. We first introduce the hook with a fingerprint of the exception only if the
`DD_DYNAMIC_INSTRUMENTATION_EXCEPTION_ENABLED` config parameter is set to true

Add exception debugging for span error

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/CookieSecurityParser.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/CookieSecurityParserTest.groovy

Fix issue with the cookie parser and empty cookies like `Set-Cookie: user-id=`

Fix issue with cookie parser and empty cookie values

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sensitive/HeaderRegexpTokenizer.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sensitive/SensitiveHandlerImpl.java
dd-java-agent/agent-iast/src/test/resources/redaction/evidence-redaction-suite.yml

Headers could store sensitive information, we should redact whole <header_value> if:
- <header_name> matches with configured sensitive name pattern
- <header_value> matches with configured sensitive value pattern
We should redact the sensitive information from the evidence when tainted range is considered sensitive value
Jira ticket: [[PROJ-IDENT]](https://datadoghq.atlassian.net/browse/APPSEC-45956)

Improve header injection redaction

---

.gitlab-ci.yml

Migrates from `docker:runner` to `arch:amd64` to support internal efforts to migrate to K8s-based docker runners
Support internal efforts to migrate to K8s-based docker runners
Jira ticket: APMJAVA-1223

Migrate from docker:runner to arch:amd64

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy

Trigger WAF request metrics only at end of request only. Otherwise, they can be incremented multiple times per request if there are multiple WAF calls.
Jira ticket: [APPSEC-51509](https://datadoghq.atlassian.net/browse/APPSEC-51509)
[APPSEC-51509]: https://datadoghq.atlassian.net/browse/APPSEC-51509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Trigger WAF request metrics only at end of request only

---

dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlareService.java

Makes it easier to identify what period the tracer flare covers.

Add requested and completed times to flare_info.txt

---

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
dd-trace-core/src/main/java/datadog/trace/core/LongRunningTracesTracker.java
dd-trace-core/src/test/groovy/datadog/trace/core/LongRunningTracesTrackerTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Add the parameter `trace.experimental.long-running.initial.flush.interval` defaulting to 20s to control how long before flushing long running traces for the first time
Reduce the delay to see long running spans in datadog, without having to set a frequent flush interval

Initial flush interval for long running spans

---

.circleci/config.continue.yml.j2

Muzzle seems often short of memory.
Reduce the probability of failure by decreasing the number of tasks per executor.

increase muzzle parallelism

---

.github/workflows/ci-static-analysis.yml
static-analysis.datadog.yml

Add a GitHub Workflow to run DataDog's Static Analyzer.
* See [docs](https://docs.datadoghq.com/static_analysis/github_actions)
* And https://github.com/DataDog/datadog-static-analyzer-github-action

Add CI Static Analysis integration

---

internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/test/groovy/datadog/trace/api/AzureAppServicesTagsTest.groovy

It adds the AAS related tags to uploaded profiles
Supporting billing for AAS profiles
Jira ticket: [PROF-9104]
[PROF-9104]: https://datadoghq.atlassian.net/browse/PROF-9104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include aas related tags in profile tag-map

---

dd-java-agent/instrumentation/axis-2/src/main/java/datadog/trace/instrumentation/axis2/AxisMessageDecorator.java
dd-java-agent/instrumentation/axis-2/src/test/groovy/datadog/trace/instrumentation/axis2/AxisEngineTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

When using Axis2 to deploy jaxrpc services, this PR allows to use the axis2 span resource name as the entry point resource name. 
In order to activate this the either the system property `dd.trace.axis.promote.resource-name` either the env `DD_TRACE_AXIS_PROMOTE_RESOURCE_NAME` should be explicitly set to true
As an additional change (not opt-in) this PR marks the axis2 spans as measured. In fact, lacking of a span kind, those spans are never used to aggregate statistics, unlike other span of type server or client.
This will allow seeing that soap call as a dependency on the service catalog. (otherwise the servlet URL will be used as a resource)
A "better" approach would have been to instrument the AxisServlet and have this logic only applied at that level. This however required more …

Allow axis server span to set local root resource name

---

telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java
telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverSpecification.groovy

When finding nested jar (e.g. in Spring Boot), we were only applying a
subset of the dependency resolution logic. Now the same heuristics are
applied to nested jars.
In practice, this means that for nested JARs we will:
* Identify the dependency more accurately (e.g. extract group id).
* Find shaded dependencies.
Jira ticket: [APPSEC-11822](https://datadoghq.atlassian.net/browse/APPSEC-11822)
[APPSEC-11822]: https://datadoghq.atlassian.net/browse/APPSEC-11822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix dependency resolution for nested JARs

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/MySQLConnectionInstrumentation.java

Same fix as #6400 but for MySQLConnectionInstrumentation

Fix context store access with null key on DBM MySQL connection

---

static-analysis.datadog.yml

Exclude some directories with test apps and other code that generates unnecessary static analysis noise.

Reduce noise in CI Static Analysis

---

.circleci/checkout_merge_commit.sh
.circleci/config.continue.yml.j2
.circleci/config.yml

* Move logic to a standalone script (easier to test).
* Use it during pipeline setup. This ensures changes to Circle CI config itself are tested in the post-merge state.

Refactor checkout merge commit in CI

---

dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/ApacheHttpAsyncClientInstrumentation.java
dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/ApacheHttpClientDecorator.java
dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/ApacheHttpClientInstrumentation.java

Align the instrumentation names used for apache http client 5 with the one expected according to the documentation

Align apache http client 5 instrumentation names

---

.circleci/config.continue.yml.j2

The main build_lib job should not spend time building shadow JARs that are only used for intermediate stages (these are covered by other jobs).

Build only release artifacts in build_lib CI job

---

dd-java-agent/instrumentation/java-concurrent/src/test/groovy/RecursiveThreadPoolPropagationTest.groovy

Avoids mutating the trace list when sorting by depth in `RecursiveThreadPoolPropagationTest`

Fix ConcurrentModificationException in RecursiveThreadPoolPropagationTest

---

internal-api/src/main/java/datadog/trace/util/AgentTaskScheduler.java
internal-api/src/test/groovy/datadog/trace/util/AgentTaskSchedulerTest.groovy

Add this method to `AgentTaskScheduler` to ensure that there is a fixed delay between tasks, even if the task duration is significantly long.
Equivalent to `ScheduledExecutorServier::scheduleWithFixedDelay` from JDK
Provide feature equivqlent to `ScheduledExecutorServier::scheduleWithFixedDelay`
Some tasks can last as long as the delay and avoiding executing right away the next cycle.
Jira ticket: [DEBUG-2076]
[DEBUG-2076]: https://datadoghq.atlassian.net/browse/DEBUG-2076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `scheduledWithFixedDelay` method

---

dd-java-agent/instrumentation/java-lang/java-lang-9/src/main/java/datadog/trace/instrumentation/java/lang/invoke/StringConcatFactoryCallSite.java
dd-java-agent/instrumentation/java-lang/java-lang-9/src/test/groovy/datadog/trace/instrumentation/java/lang/invoke/StringConcatFactoryCallSiteTest.groovy

Fixes call sites for string concat factory in IBM J9
Jira ticket: [APPSEC-10807]
[APPSEC-10807]: https://datadoghq.atlassian.net/browse/APPSEC-10807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix dynamic invoke for string concat in IBM J9

---

dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/HardcodedSecretController.java
dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy

Extract hardcoded secret vulnerability to another controller to avoid modify the vulnerability line in the test assertion every time the IastWebController is modified to add more vulnerability cases

Refactor hardcoded secret smoke test

---

dd-java-agent/instrumentation/java-lang/java-lang-9/src/test/groovy/datadog/trace/instrumentation/java/lang/invoke/StringConcatFactoryCallSiteTest.groovy

Fixes the `StringConcatFactoryTest` that should not run under JDK8 that was broken due to: https://github.com/DataDog/dd-trace-java/pull/6634

Fix issue with call site test that should not run in JDK8

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java

Exclude WAF timeout from telemetry logs.
WAF timeouts produces too many telemetry logs. Looking at the stacktrace is somewhat useful to check where the timeout comes from, but we can look at this per-customer. We now have a metric https://github.com/DataDog/dd-trace-java/pull/6597 to check this, and we'll soon also have a telemetry metric.

Exclude WAF timeout from telemetry logs

---

internal-api/build.gradle
internal-api/src/main/java/datadog/trace/api/telemetry/MetricCollector.java
telemetry/src/main/java/datadog/telemetry/TelemetryService.java
telemetry/src/main/java/datadog/telemetry/api/DistributionSeries.java
telemetry/src/main/java/datadog/telemetry/metric/MetricPeriodicAction.java
telemetry/src/test/groovy/datadog/telemetry/TelemetryRunnableSpecification.groovy
telemetry/src/test/groovy/datadog/telemetry/metric/MetricPeriodicActionTest.groovy

Adds support for periodical polling and submission of distribution series telemetry.
Distribution series will be used by future CI Visibility telemetry logic.
Most of the logic for sending distribution series data was implemented previously.
This PR adds the missing part - polling periodic metric collectors, aggregating drained data and passing it over to telemetry service.

Add support for periodic submission of telemetry distribution series

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/Fingerprinter.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Instrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/SpanInstrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ExceptionProbe.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/ClassNameFiltering.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/DefaultExceptionDebuggerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeManagerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/FingerprinterTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/TestSnapshotListener.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot20.java

Exception probes are capturing only for uncaught exception exception that matches the fingerprint stored
Add exception probe instrumentation tests
Filtering is hardcoded for JDK packages
Exception probe instrumentation is using line from the stack frame to identify the right method. In the snapshot the probe drop the line number to make sure it is interpreted as correct method probe snapshot
Exception debugging

Add class filtering and exception probe conditions

---

dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
dd-smoke-tests/gradle/src/test/resources/test-succeed-junit-5/build.gradleTest
dd-smoke-tests/gradle/src/test/resources/test-succeed-multi-forks-legacy-instrumentation/build.gradleTest
dd-smoke-tests/gradle/src/test/resources/test-succeed-multi-forks-new-instrumentation/build.gradleTest

Updates Gradle smoke tests:
- changes Gradle version from 7.6.3 to 7.6.4 following a recent release
- add missing (or updates incorrect) JUnit version in some of the test fixture projects

Update Gradle smoke tests

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-trace-api/src/main/java/datadog/trace/api/config/RemoteConfigConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Fix remote config activation configuration name according to the RFC from `DD_REMOTE_CONFIG_ENABLED` to `DD_REMOTE_CONFIGURATION_ENABLED`.
This is a follow up fix for the issue #6640 

Fix remote config activation configuration name

---

telemetry/src/main/java/datadog/telemetry/TelemetryRouter.java
telemetry/src/test/groovy/datadog/telemetry/TelemetryRouterSpecification.groovy

Updates telemetry client switch logic.
Prior to the change the logic could switch from intake client to agent client in the following circumstances:
- if a telemetry request fails
- if agent is available and has telemetry proxy endpoint
With the change the logic is to do the switch if:
- if a telemetry request fails
- if agent is available, has telemetry proxy endpoint and _the tracer is not configured for "agentless" mode_.
If the tracer is explicitly configured to work in agentless mode, the intake telemetry client should be the preferred one.

Do not switch to agent telemetry client on detecting agent telemetry endpoint availability when intake client is preferred

---

telemetry/src/main/java/datadog/telemetry/TelemetryClient.java
telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
telemetry/src/test/groovy/datadog/telemetry/TelemetryClientTest.groovy

Updates telemetry intake client to use CI Visibility agentless URL if CI Visibility agentless mode is enabled and the URL is configured.
Some users who run the tracer in agentless mode might need to use a non-standard URL.
A non-standard URL is also needed in smoke tests that start a mock intake server.
The custom URL is only used if CI Visibility is enabled.

Update telemetry intake client to use CI Visibility agentless URL, if configured

---

dd-java-agent/appsec/build.gradle

Upgraded libddwaf to the latest version, see:
* https://github.com/DataDog/libddwaf/releases/tag/1.15.0
* https://github.com/DataDog/libddwaf/releases/tag/1.15.1
* https://github.com/DataDog/libddwaf/releases/tag/1.16.0
To proceed #6375 we need critical updates from latest version of libddwaf.
Jira ticket: [APPSEC-51687]
[APPSEC-51687]: https://datadoghq.atlassian.net/browse/APPSEC-51687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Upgrade to libddwaf 1.16.0 (libsqreen 9.0.1)

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/Configuration.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationAcceptor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerProductChangesListener.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerProductChangesListenerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/DefaultExceptionDebuggerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeInstrumentationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ProbeStateIntegrationTest.java

Introducing the concept of source for `ConfigurationUpdater` that is just a list of `ProbeDefinition`. As RemoteConfig configuration are only for probes for now, we are reducing it to this list. Hence the `accept`
method in `ConfigurationUpdater` is taking a source (`REMOTE_CONFIG` or `EXCEPTION`) and a list of `ProbeDefinition`. For RemoteConfig part, we are building this list instead of `Configuration` object and capping the number of probes per type at that level now instead of `ConfigurationUpdater`. The side effect of this is that now there is no capping for probe definitions coming from file. `Configuration::accept` method is now responsible to merge definitions from all source (`REMOTE_CONFIG` and `EXCEPTION`) and create a `Configuration` object that will be applied as before. As a …

Decouple ConfigurationUpdater and exception probes

---

dd-java-agent/instrumentation/akka-concurrent/src/test/groovy/AkkaExecutorInstrumentationTest.groovy
dd-java-agent/instrumentation/java-concurrent/lambda-testing/src/test/groovy/ExecutorLambdaTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/NettyExecutorInstrumentationTest.groovy
dd-java-agent/instrumentation/jetty-util/src/test/groovy/JettyExecutorInstrumentationTest.groovy
dd-java-agent/instrumentation/scala-concurrent/src/test/groovy/ScalaExecutorInstrumentationTest.groovy

Use pool class name rather than relying on `Object.toString()` to get fixed test names
This causes issues with CI visibility.
Jira ticket: [APMJAVA-1241]
[APMJAVA-1241]: https://datadoghq.atlassian.net/browse/APMJAVA-1241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use pool class name to get fixed test names

---

gradle/dependencies.gradle

Fix bug in stackwalker when kernel frames are walkable
Default to `create_timer` (reduces number of file handles required)
https://github.com/DataDog/java-profiler/releases/tag/v_0.97.0

Upgrade to ddprof 0.97.0

---

dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy

This PR will change the smoketests not to use ddprof on J9
On J9 the jmethoidID handling is very brittle and leads to frequent crashes. We want to avoid the crashes in smoketests.
Jira ticket: [PROF-9151]
[PROF-9151]: https://datadoghq.atlassian.net/browse/PROF-9151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Do not use ddprof in J9 smoketests

---

dd-trace-core/src/main/java/datadog/trace/core/TracingConfigPoller.java
dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy

Add the target service and env checks.
Prevent remote config update if service+env doesn't match.
Jira ticket: [APMJAVA-1222]
[APMJAVA-1222]: https://datadoghq.atlassian.net/browse/APMJAVA-1222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remote Config. Add target service+env check.

---

dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java

Flush spans when the spark application finishes
Default timeout for the remoteWriter is [1 second](https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-core/src/main/java/datadog/trace/common/writer/RemoteWriter.java#L61) so it will not block the main thread for more than 1 second
Customer losing their spans because the JVM was shut down to quickly, with those debug logs:
```
[dd.trace 2024-02-09 14:12:48:023] [main] DEBUG datadog.trace.agent.core.DDSpan - Finished span (WRITTEN): DDSpan [...]
[dd.trace 2024-02-09 14:12:48:097] [dd-trace-processor] DEBUG datadog.trace.agent.common.writer.ddagent.DDAgentApi - Error while sending 1 (size=61KB) traces. Total: 1, Received: 1, Sent: 0, Failed: 1.
java.io.InterruptedIOException: interrupted
at …
```

Flush traces when spark application is finished

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/CILocalGitInfoBuilder.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/GitClientGitInfoBuilder.java
dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Utils.java
dd-java-agent/instrumentation/junit-5.3/spock-junit-5/src/main/java/datadog/trace/instrumentation/junit5/SpockUtils.java
dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnitPlatformUtils.java
dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenLifecycleParticipant.java
dd-java-agent/instrumentation/scalatest/src/main/java/datadog/trace/instrumentation/scalatest/ScalatestUtils.java
dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGUtils.java

Updates CI Visibility core and instrumentations so that caught exceptions are never swallowed.
In future releases of the tracer it will be possible to report exceptions in the tracer code to Datadog using telemetry.
The goal is to see if there are any unexpected exceptions when CI Visibility is used in various envs.

Do not ignore caught exceptions in CI Visibility code

---

dd-java-agent/agent-ci-visibility/build.gradle
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilityServices.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilitySystem.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitClient.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/utils/ShellCommandExecutor.java
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/GitClientGitInfoBuilderTest.groovy
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/tree/GitClientTest.groovy
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/tree/GitDataUploaderImplTest.groovy

Implement telemetry for shell git commands

---

dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java

Instead of creating a new tcp connection with each call to the extension (ie start and end invocation), use a pool of available connections.
This change reduces `aws.lambda.enhanced.runtime_duration` by approximately 2%.
See https://ddserverless.datadoghq.com/notebook/2987494/reys-purple-notebook?range=3600000&view=view-mode&start=1703617009962&live=false

Use connection pool for http communications with extension.

---

gradle/dependencies.gradle

* Fixes potential slow memory leak in reporting
* Handles native stacks without frame pointers better
* More robust musl/glibc detection
https://github.com/DataDog/java-profiler/releases/tag/v_0.98.0
https://github.com/DataDog/java-profiler/releases/tag/v_0.99.0

Upgrade to ddprof 0.99.0

---

communication/build.gradle
communication/src/main/java/datadog/communication/http/OkHttpUtils.java
communication/src/test/groovy/datadog/communication/http/OkHttpUtilsTest.groovy

Adds a mechanism for registering ad-hoc event listeners for okhttp requests.
A listener can be registered when building a request:
```
class MyListener extends OkHttpUtils.CustomListener {
// override event handlers
} 
final Request request =
new Request.Builder()
.url(...)
.post(...)
.tag(OkHttpUtils.CustomListener.class, new MyListener())
.build();
```
This is needed for CI Visibility telemetry. There are metrics like requests count, errors count, request size, etc for events/coverages intake, CI Visibility Git API and other endpoitns.
`EventListener.NONE` is what all the requests are using by default: it is a listener that has an empty handler for every event.
With the new mechanism this "empty" listener is replaced with a custom one for those requests that have the corresponding tag. …

Implement a mechanism for adding ad-hoc listeners to OKHTTP requests

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestEventsHandlerImpl.java
dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/TracingListener.java

Fixes test framework name calculation in JUnit 5 instrumentation: test framework name is calculated based on the ID of test engine (a JUnit 5 abstraction that encapsulates some framework-specific details) used to execute test cases.
With the fix if the ID of the test engine is `null`, a generic "junit5" framework name will be used.
Also fixes the generic CI Vis logic to only set the test framework version tag if the framework name is available (both because framework version is not very useful without a name, and because there is some logic that depends on either both being present, or both absent.
Fixing the following error:
```
[13:02:51 UTC]  JUnit Jupiter executionError FAILED
[13:02:51 UTC]  
[13:02:51 UTC]    java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: …
```

Fix null test framework name in JUnit 5 instrumentation

---

telemetry/src/main/java/datadog/telemetry/TelemetryClient.java
telemetry/src/test/groovy/datadog/telemetry/TelemetryClientTest.groovy

Fixes URL that is used by intake telemetry client when the tracer is configured to work with EU Datadog site.
The list of possible site parameters can be found [here](https://docs.datadoghq.com/getting_started/site/#access-the-datadog-site).
The list of agentless telemetry URLs for different sites can be found [here](https://github.com/DataDog/instrumentation-telemetry-api-docs/blob/main/GeneratedDocumentation/ApiDocs/v2/development.md#agentless).

Fix intake telemetry client URL for EU site

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/testing/src/test/groovy/locator/ClassInjectingForkedTest.groovy
dd-java-agent/testing/src/test/groovy/locator/ClassInjectingLoadClassDisabledForkedTest.groovy
dd-java-agent/testing/src/test/java/locator/ClassInjectingTestInstrumentation.java
dd-java-agent/testing/src/test/java/locator/ClassInjectingTransformer.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java

Configures byte-buddy to use a simpler method graph compiler which just considers locally declared methods. This approach is enough for our transformations which insert advice into methods. And since our transformations use either `@Advice` or `AsmVisitorWrapper` we can also turn off generation of visibility bridges and use a simpler type strategy.
To disable this optimization add this JVM option:
```
-Ddd.resolver.simple.method.graph=false
```
```
DD_RESOLVER_SIMPLE_METHOD_GRAPH=false
```
For spring-petclinic this reduces the number of class-file lookups by a fifth.
OTel uses a similar configuration for byte-buddy: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/v2.0.0/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/to …

Configure byte-buddy to use simpler method-graph

---

.circleci/render_config.py

Fix undefined symbol in CI setup job, only for non-PR builds. Previously broken by https://github.com/DataDog/dd-trace-java/pull/6610

Fix setup job in CI

---

dd-java-agent/agent-ci-visibility/build.gradle
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilityRepoServices.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/communication/BackendApi.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/communication/EvpProxyApi.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/communication/IntakeApi.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/communication/TelemetryListener.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/CiVisibilitySettings.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ConfigurationApiImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitDataApi.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitDataUploaderImpl.java
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/config/ConfigurationApiImplTest.groovy
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/tree/GitDataApiTest.groovy
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/tree/GitDataUploaderImplTest.groovy
internal-api/src/main/java/datadog/trace/api/civisibility/telemetry/CiVisibilityDistributionMetric.java

Implements sending telemetry metrics for API endpoints that are specific to CI Visibility (events and coverage data intakes, Git data API, etc).
Monitoring CI Visibility behaviour to detect unexpected errors/problems.

Implement telemetry for CI Visibility APIs

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/ApplicationModuleImpl.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/StringUtils.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/ApplicationModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/StringUtilsTest.groovy
dd-java-agent/agent-iast/src/test/resources/application/insecurejsplayout/secure/nested/README.md

Uses the NIO file visitor API to traverse the folders in order to ensure proper performance and depth bounds for the traversal.

Improve application module performance and security bounds

---

dd-trace-api/src/main/java/datadog/trace/api/interceptor/AbstractTraceInterceptor.java
dd-trace-core/build.gradle
dd-trace-core/src/main/java/datadog/trace/civisibility/interceptor/CiVisibilityTelemetryInterceptor.java
dd-trace-core/src/main/java/datadog/trace/civisibility/writer/ddintake/CiTestCovMapperV2.java
dd-trace-core/src/main/java/datadog/trace/civisibility/writer/ddintake/CiTestCycleMapperV1.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddintake/DDEvpProxyApi.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddintake/DDIntakeApi.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddintake/TelemetryListener.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddintake/DDEvpProxyApiTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddintake/DDIntakeApiTest.groovy
internal-api/src/main/java/datadog/trace/api/intake/TrackType.java

Implements sending telemetry metrics for CI Visibility intakes (test events intake and per-test code coverages intake).
Monitoring CI Visibility behaviour to detect unexpected errors/problems.

Implement telemetry for CI Visibility intakes

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/classloading/ClassDefining.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/memoize/MemoizedMatchers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/memoize/PreloadHierarchy.java
dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
dd-java-agent/instrumentation/classloading/src/main/java/datadog/trace/instrumentation/classloading/DefineClassInstrumentation.java

Updates `j.l.ClassLoader` to notify the tracer before defining a class. The tracer can then attempt to preload the superclass and any interfaces, which will make sure those types are memoized/cached before the initial type is matched.
To disable this optimization add this JVM option:
```
-Ddd.integration.defineclass.enabled=false
```
```
DD_INTEGRATION_DEFINECLASS_ENABLED=false
```
For spring-petclinic (when memoization is enabled) this reduces the number of class-file lookups by over a third.
(from 1970 lookups to 1226 lookups) 
Jira ticket: [APMS-11443]
[APMS-11443]: https://datadoghq.atlassian.net/browse/APMS-11443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ensure superclasses and interfaces are loaded before classes that extend/implement them

---

.circleci/config.continue.yml.j2

Make system-tests required for PRs. They have been fairly stable for quite some time, and they are important for ASM products.
This does not include parametric tests.

Make system-tests required in CI

---

dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/ScriptInitializer.java

For the crash tracking it adjusts the folder and file permissions such that they are not restricted to a single user/group.
The crash tracking script initialization routine is creating the script on the fly. By default the defined folder and the script itself will be accessing only to the user/group that created them. This is causing issues on mutli-user systems where the script and the directory hierarchy may be created by one user and then used by another one.
Jira ticket: [PROF-9159]
[PROF-9159]: https://datadoghq.atlassian.net/browse/PROF-9159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Avoid permission issues for the crash uploader script

---

.gitlab-ci.yml

The deploy of the latest master commit now happens on a schedule.

Remove automated deploy to DI backend

---

telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java
telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverSpecification.groovy

Revert https://github.com/DataDog/dd-trace-java/pull/6603
This reverts commit 00ed7e722ee9c8accb8946ef6e6ba882b5a50b13.
This seems to be the cause of prematurely closed streams during Spring Boot classloading (#6704). While #6711 might be a proper fix, we have not been able to reproduce the original issue yet, so I'm reverting the original PR until we can reproduce the issue and verify the fix.
Jira ticket: [APPSEC-51864](https://datadoghq.atlassian.net/browse/APPSEC-51864)
[APPSEC-51864]: https://datadoghq.atlassian.net/browse/APPSEC-51864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "Fix dependency resolution to nested JARs (#6603)"

---

dd-java-agent/instrumentation/tomcat-5.5/build.gradle
dd-java-agent/instrumentation/tomcat-5.5/src/latestDepTest/groovy/TomcatNoPropagationForkedTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/NoneCodec.java
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpExtractorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/NoneHttpExtractorTest.groovy

When the propagation style is none, today we loose some tags on server spans like:
* client_ip
* x-forwarded-for
* user_agent
The problem is that the extraction of those tags is linked to the extraction of the whole context.
This PR aims to keep extracting a TagContext on propagation style none in order to surface those headers along with mapped headers and mapped baggage.
The tracing and pathway context are anyway not extracted that will make a new trace to be started on the receiver style as supposed to be with none propagation style
Jira ticket: [APMS-11334]
[APMS-11334]: https://datadoghq.atlassian.net/browse/APMS-11334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

extract headers and baggage when propagation is disabled

---

dd-java-agent/agent-profiling/profiling-controller-ddprof/src/main/java/com/datadog/profiling/controller/ddprof/DatadogProfilerSettings.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/JfrProfilerSettings.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkOngoingRecording.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkOngoingRecordingTest.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ControllerContext.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilerSettingsSupport.java
dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/CompositeController.java

Publishes reason the dd profiler failed to load as a recurrent event (assuming there is JFR present, this makes debugging easier). Tested end to end with a contrived failure.

add failure to load dd profiler as periodic JFR event

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilityServices.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/SignalClient.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/SignalServerRunnable.java
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ipc/SignalServerTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/CiVisibilityConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Makes the timeout of CI Visibility signal client configurable.
Adds some debug logging to signal client and signal server.
There is a CI Visibility user who experiences intermittent signal client timeout.
Jira ticket: [CIVIS-9220]
[CIVIS-9220]: https://datadoghq.atlassian.net/browse/CIVIS-9220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make signal client timeout configurable

---

dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Added Api security env variable `DD_API_SECURITY_ENABLED` and `dd.api-security.enabled`.
The old one `experimental.api-security.enabled` left as a fallback option
This change is required to make API Security enabled by default. See #6701

Added API Security option dd.api-security.enabled

---

telemetry/build.gradle
telemetry/src/jmh/java/datadog/telemetry/dependency/DependencyResolverBenchmark.java
telemetry/src/jmh/resources/logback.xml

Add JMH benchmark for dependency resolution
Upcoming changes for nested JARs will have an impact here: https://github.com/DataDog/dd-trace-java/pull/6720
Current results in my machine:
```
Benchmark                                                Mode  Cnt    Score    Error   Units
DependencyResolverBenchmark.resolveNestedSpringBootJar  thrpt   25  306.740 ± 16.075  ops/ms
DependencyResolverBenchmark.resolveSimpleJar            thrpt   25   21.441 ±  1.665  ops/ms
```

Add JMH benchmark for dependency resolution

---

dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java

* Decrease default WAF timeout to 5ms. This covers ~p95 of our tests so far. It can be changed with `DD_APPSEC_WAF_TIMEOUT` environment variable or `-Ddd.appsec.waf.timeout`. It is set in microseconds.
* Smoke test adjusted to tolerate some timeouts under high load.
Minimize the maximum latency impact the WAF may have by default.
* Note that latency is improving in the benchmarks results here, so it seems we are hitting the timeout in the benchmark. This should be fine, since the benchmark is a load test which is precisely one of the scenarios where we should be timing out.

Decrease default WAF timeout to 5ms

---

dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java

Revert "Decrease default WAF timeout to 5ms (#6733)"
This reverts commit b2a77cb772acebce465f859556d1461607127806.
So many tests started failing in master per new timeouts.

Revert "Decrease default WAF timeout to 5ms (#6733)"

---

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolverQueue.java
telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverQueueSpecification.groovy

Allows the user to set a limit to the size of the telemetry `DependencyResolverQueue` to prevent OOM errors when there are a large number of dependencies
Introduces a new config variable (`dd.telemetry.dependency-resolution.queue.size`) which takes an integer to set as the limit for the number of dependencies to store in the queue.
Resolve [APMS-11445](https://datadoghq.atlassian.net/browse/APMS-11445?atlOrigin=eyJpIjoiYWJjZmQzOGIyMzhhNDRlOTkyZDZmMWE1ZDc4YTM2YTMiLCJwIjoiaiJ9)
Jira ticket: [APMS-11445]
[APMS-11445]: https://datadoghq.atlassian.net/browse/APMS-11445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APMS-11445]: https://datadoghq.atlassian.net/browse/APMS-11445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …

Limit DependencyResolverQueue size with a config flag

---

dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/RangeBuilderTest.groovy

Fix a test failing on some VMs due to groovy equality with integers
IBM 8 [example](https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/34594/workflows/36819e3b-e45c-4fa7-b88a-ac1114d43daa/jobs/1226445)

Fix equality in the range builder test causing failures in some VMs

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ConfigurationApiImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/AbstractTestSession.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/buildsystem/BuildSystemModuleImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/buildsystem/BuildSystemSessionImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/headless/HeadlessTestModule.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/headless/HeadlessTestSession.java
internal-api/src/main/java/datadog/trace/api/civisibility/CIConstants.java
internal-api/src/main/java/datadog/trace/api/civisibility/telemetry/CiVisibilityCountMetric.java
internal-api/src/main/java/datadog/trace/api/civisibility/telemetry/CiVisibilityDistributionMetric.java
internal-api/src/main/java/datadog/trace/api/civisibility/telemetry/tag/EarlyFlakeDetectionAbortReason.java
internal-api/src/main/java/datadog/trace/api/civisibility/telemetry/tag/EarlyFlakeDetectionEnabled.java
internal-api/src/main/java/datadog/trace/api/civisibility/telemetry/tag/IsNew.java

Adds telemetry metrics to early flakiness detection logic.
Jira ticket: [CIVIS-8329]
[CIVIS-8329]: https://datadoghq.atlassian.net/browse/CIVIS-8329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Implement telemetry for early flakiness detection

---

dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy

Tolerate `increaseTimeouts` calls in this particular test. This seems to be flaky since https://github.com/datadog/dd-trace-java/pull/6597 with the introduction of timeouts reporting (hence the `increaseTimeouts` call). The WAF might have been timing out before without affecting the logic of the test.
So we'll just ignore timeouts here, and will further investigate any other failure (when breaking because of other assertions).
The failure is reproducible locally under high load (e.g. `stress --cpu 16 --vm 8`).

Fix PowerWAFModuleSpecification flaky test

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/FastCodecModule.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/BaseCodecModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/FastCodecModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/PropagationModuleTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/RangesTest.groovy
dd-java-agent/instrumentation/java-io/src/main/java/datadog/trace/instrumentation/java/lang/ByteBufferCallSite.java
dd-java-agent/instrumentation/java-io/src/test/groovy/datadog/trace/instrumentation/java/io/ByteBufferTest.groovy
dd-java-agent/instrumentation/java-io/src/test/java/foo/bar/TestByteBufferSuite.java
dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringCallSite.java
dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/StringCallSiteTest.groovy
dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringSuite.java
internal-api/src/main/java/datadog/trace/api/iast/propagation/CodecModule.java
internal-api/src/main/java/datadog/trace/api/iast/propagation/PropagationModule.java

Adds support for accurate tainting of byte array instances.
We need to keep track of multiple ranges in order to add proper support for Kafka 3.x as they use byte buffers extensively.

Add support for precise tainting of byte array objects

---

.github/workflows/draft-release-notes-on-tag.yaml

Improve release candidate detection and the related changelog warning

Improve release candidate detection and its changelog warning

---

internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/SpanLink.java
internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/SpanLinkTest.groovy

Make sure span links trace ids and attributes can't be `null`.
Follow up PR of #6758 

Ensure span links attributes can't be null

---

benchmark/startup/insecure-bank/benchmark.json
benchmark/startup/petclinic/benchmark.json

Fixes startup benchmarks that where failing due to missing reports folder:
```
FileNotFoundError: [Errno 2] No such file or directory: '/go/src/github.com/DataDog/apm-reliability/dd-trace-java/reports/startup/insecure-bank/iast_HARDCODED_SECRET_DISABLED/benchmark-baseline.json'
```

Move -Ddd.benchmark.output.dir to the main run parameter

---

dd-java-agent/instrumentation/axis-2/build.gradle
dd-java-agent/instrumentation/axis-2/src/main/java/datadog/trace/instrumentation/axis2/AxisMessageDecorator.java
dd-java-agent/instrumentation/axis-2/src/main/java/datadog/trace/instrumentation/axis2/AxisTransportInstrumentation.java
dd-java-agent/instrumentation/axis-2/src/main/java/datadog/trace/instrumentation/axis2/TextMapInjectAdapter.java
dd-java-agent/instrumentation/axis-2/src/main/java/datadog/trace/instrumentation/axis2/WebSphereAsyncInstrumentation.java
dd-java-agent/instrumentation/axis-2/src/test/groovy/datadog/trace/instrumentation/axis2/AxisEngineTest.groovy
dd-java-agent/instrumentation/axis-2/src/test/groovy/datadog/trace/instrumentation/axis2/AxisTransportForkedTest.groovy
dd-java-agent/instrumentation/axis-2/src/test/java/test/TestSender.java
dd-java-agent/instrumentation/axis-2/src/test/java/test/TestService.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java

Adds `axis2.transport` spans around calls to selected Axis2 transport senders, currently:
```
com.ibm.ws.websvcs.transport.http.HTTPTransportSender
```
and injects the current trace context into the outgoing `TRANSPORT_HEADERS`.
Also provides a configuration option to do the same for an arbitrary transport sender, for test / triage purposes:
```
-Ddd.trace.axis.transport.class.name=<sender.class.name>
```
```
DD_TRACE_AXIS_TRANSPORT_CLASS_NAME=<sender.class.name>
```
Asynchronous WebSphere JAX-WS requests are handled by storing the `axis2.transport` span created by the transport sender instrumentation in the message context being processed and closing out that span once the response has been processed, when the async resources are released - or earlier in the case of an error. This …

Support context propagation over selected Axis2 transport senders

---

dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/test/groovy/Aws2ClientTest.groovy
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/test/groovy/LegacyAws2ClientForkedTest.groovy

Add `aws.object.key` for aws-sdk-2 to know which key is targeted by S3 get/put requests. Similar to this PR https://github.com/DataDog/dd-trace-java/pull/6555 where it was done for aws-sdk-1 
More information on S3 request by having the key of the targeted object. It also unlocks object-level data lineage for S3

Add `aws.object.key` tag for aws-sdk-2

---

dd-java-agent/appsec/src/main/resources/default_config.json

Upgrade to the latest Application Security rules.
The new rules produce a small fixed increase in startup time for users with `DD_APPSEC_ENABLED=true`. This is 2-4ms in our benchmarks. We will try to improve this in future versions.

Upgrade to AppSec rules v1.11.0

---

gradle/dependencies.gradle

Updates the ddprof dependency to 1.1.0
The version [1.1.0](https://github.com/DataDog/java-profiler/releases/tag/v_1.1.0) contains a bug fix preventing occasional sigsegv when using wallclock profiler.

Bump ddprof-java to 1.1.0

---

docs/how_instrumentations_work.md

improve instrumentation doc

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/instrumentation/CoverageInstrumentationFilter.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/PackageResolver.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/PackageResolverImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexBuilder.java
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/index/PackageResolverImplTest.groovy

Fixes source path calculation for classes that reside in default package.
ITR coverage instrumentation is also fixed to always consider classes in default package.
Jira ticket: [CIVIS-9338]
[CIVIS-9338]: https://datadoghq.atlassian.net/browse/CIVIS-9338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix source path calculation for classes in default package

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/instrumentation/CoverageInstrumentationFilter.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/PackageResolver.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/PackageResolverImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexBuilder.java
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/index/PackageResolverImplTest.groovy

Fixes source path calculation for classes that reside in default package.
ITR coverage instrumentation is also fixed to always consider classes in default package.
Jira ticket: [CIVIS-9338]
[CIVIS-9338]: https://datadoghq.atlassian.net/browse/CIVIS-9338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[🍒 6781] Fix source path calculation for classes in default package

---

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java

It will suffix the 'runtime_version' tag with `-graalvm` if running as a native image.
The SubstrateVM (GraalVM native image runtime) implementation of JFR does not properly trim the stacktraces, leaving several frames of runtime internals there. 
We can trim those stacktraces in our backend but doing that for all incoming recordings would be too costly - therefore we need to have a quick way to identify such recordings based on the tags.
Jira ticket: [PROF-9285]
[PROF-9285]: https://datadoghq.atlassian.net/browse/PROF-9285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enhance 'runtime_version' tag to encode graalvm source

---

dd-java-agent/agent-profiling/profiling-controller-jfr/implementation/src/main/java/com/datadog/profiling/controller/jfr/SimpleJFRAccess.java
dd-java-agent/agent-profiling/profiling-controller-jfr/implementation/src/main/java11/com/datadog/profiling/controller/jfr/JPMSJFRAccess.java
dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/JFRAccess.java
dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/QueueTimeTracker.java
dd-java-agent/agent-profiling/profiling-utils/src/main/java/com/datadog/profiling/utils/Timestamper.java
dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java

Exposes and feeds TSC counter from JFR to be used in queue time tracking. WIP because this exercise exposed need for refactoring to make changes like this maintainable. Will rebase on top of the pending refactoring.
WIP - this change 
Do not incur JNI overhead when recording time in queue

use JFR timestamping for queue time thresholds

---

telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java
telemetry/src/main/java/datadog/telemetry/dependency/JarReader.java
telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverSpecification.groovy

* Fixes dependency resolver for nested dependencies when URI has no trailing slash.
* Also fix fallback resolver when a nested dependency has no Maven metadata.
For v1.31.0+, this issue would result in exceptions logged at debug level:
```
[dd.trace 2024-03-08 13:32:35:110 +0100] [dd-task-scheduler] DEBUG datadog.telemetry.dependency.DependencyResolver - Failed to determine dependency for uri jar:file:/work/dd-trace-java/dd-smoke-tests/spring-boot-3.0-webmvc/build/application/libs/webmvc-3.0-smoketest.jar!/BOOT-INF/lib/spring-boot-3.0.0.jar!/
java.io.FileNotFoundException: /work/dd-trace-java/dd-smoke-tests/spring-boot-3.0-webmvc/build/application/libs/webmvc-3.0-smoketest.jar!/BOOT-INF/lib/spring-boot-3.0.0.jar! (No such file or directory)
at …
```

Fix nested JAR resolver when URI has no trailing slash

---

dd-java-agent/appsec/build.gradle

Minify AppSec rules.
Reduce JAR size and load time.
This partially offsets the startup time regression introduced by https://github.com/DataDog/dd-trace-java/pull/6754 when `DD_APPSEC_ENABLED=true`.

Minify AppSec rules

---

buildSrc/src/main/groovy/MuzzlePlugin.groovy
dd-java-agent/instrumentation/spring-data-1.8/build.gradle

Remove `spring-aop` from being reported as supported due to the muzzle reports even though it is simply a dependency for `spring-data-commons`
Cleaning up reporting code to improve future endeavors to rely on version data from tracer telemetry data extracted from Muzzle reports

Fixes muzzle reporting to be more accurate for telemetry

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy

Fixes the handling of tainted parameters in `String#format` when escaped patterns like `%%` and `%n` are used.
The current code is throwing `java.lang.ArrayIndexOutOfBoundsException` due to bad argument handling.
Jira ticket: [APPSEC-52173]
[APPSEC-52173]: https://datadoghq.atlassian.net/browse/APPSEC-52173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix string format when escaped patterns are used

---

dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/BaseServiceAdder.java
dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/PeerServiceCalculator.java
dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/PostProcessorChain.java
dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/QueryObfuscator.java
dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/TagsPostProcessor.java
dd-trace-core/src/test/groovy/datadog/trace/core/tagprocessor/BaseServiceAdderTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/tagprocessor/PeerServiceCalculatorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/tagprocessor/PostProcessorChainTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/tagprocessor/QueryObfuscatorTest.groovy

Removed redundant proxy-methods. Merged `TagsPostProcessor.processTags()` and `TagsPostProcessor.processTagsWithContext()` into single method.
This is preparation for to future work on span late post processing

Refactoring of TagsPostProcessor

---

.gitlab-ci.yml
.gitlab/build_java_package_oci.sh

Adds OCI packaging support to the `dd-trace-java` library, following https://github.com/DataDog/auto_inject/pull/147 & https://github.com/DataDog/auto_inject/pull/149
Package tracing libraries to be downloaded at runtime
N/A
Jira ticket: [RC-1645]
[RC-1645]: https://datadoghq.atlassian.net/browse/RC-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(packaging): Add OCI packaging support

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy

#6795 backport
(cherry picked from commit e8da14ea490f30651fcdc5f4526246e79a3543a7)
Jira ticket: [APPSEC-52173](https://datadoghq.atlassian.net/browse/APPSEC-52173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
[APPSEC-52173]: https://datadoghq.atlassian.net/browse/APPSEC-52173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix string format when escaped patterns are used (#6795) (1.31.x backport)

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy

This pull request signifies an important enhancement in ASM. Originally, we employed a transient mechanism to manage temporary data submissions to the WAF. The recent introduction of ephemeral addresses in `libddwaf` presents a native and more efficient implementation of this transient mechanism. Through this PR, we are transitioning from the older transient method to utilizing ephemeral addresses.
This improvement is required by #6375 
Upgrading WAF to version `1.16.0` made it possible to start using ephemeral addresses (see: #6658)
Jira ticket: [APPSEC-51774]
[APPSEC-51774]: https://datadoghq.atlassian.net/browse/APPSEC-51774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Replace ASM transient mechanism with WAF ephemeral addresses

---

lib-injection/Dockerfile

Updates the base image for lib injection.
The old image has reported vulnerabilities
Jira ticket: VULN-5886

Update base image used for lib injection

---

internal-api/internal-api-9/build.gradle

Removes the error during the assemble of the `internal-api-9` module due to using the wrong JDK to build the JavaDoc documentation.

Use JDK11 to build javadoc of the internal-api-9 module

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/CombiningTransformerBuilder.java

Avoids recreating the same helpers when a module contains several instrumenters.
Jira ticket: [AIT-9441]
[AIT-9441]: https://datadoghq.atlassian.net/browse/AIT-9441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Re-use helpers across all instrumenters in a module

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ModuleExecutionSettingsFactoryImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/buildsystem/ProxyTestModule.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/headless/HeadlessTestModule.java
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/config/ModuleExecutionSettingsSerializerTest.groovy
dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/CiVisibilityConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/api/civisibility/config/ModuleExecutionSettings.java

When flaky test retries are enabled in CI Visibility, by default every failed test will be retried up to N times.
A config property is added to switch the tracer to its previous behaviour: only retry the tests that are known to be flaky.
Jira ticket: [CIVIS-9432]
[CIVIS-9432]: https://datadoghq.atlassian.net/browse/CIVIS-9432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add possibility to retry every failed test when retries are enabled

---

dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java
dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/AbstractSparkStructuredStreamingTest.groovy
dd-java-agent/instrumentation/spark/src/testFixtures/java/datadog/trace/instrumentation/spark/TestSparkComputation.java

Add support for [SpanLinks](https://docs.datadoghq.com/tracing/trace_collection/span_links/) in spark instrumentation to correlate `spark.streaming_batch` span with its parent `databricks.task.execution` span from a different trace. 
`spark.streaming_batch` spans are not linked to the parent `databricks.task.execution` span as this would have created traces with too many spans. 
However, without such casual relationship tracked inside the same trace, it's cumbersome to navigate from the `spark.streaming_batch` span to its parent span in order to understand larger context. Instead, users need to manually narrow down parent trace by filtering [Databricks Workflows](https://docs.databricks.com/en/workflows/index.html) related tags common to both `spark.streaming_batch` span and …

create SpanLink from spark.streaming_batch span to databricks.task.execution span for spark instrumentation if applicable.

---

dd-java-agent/agent-debugger/build.gradle
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/Fingerprinter.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/ASMHelper.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ExceptionProbe.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/Snapshot.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/ExceptionHelper.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/WeakIdentityHashMap.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/DefaultExceptionDebuggerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/ExceptionHelperTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/TestTraceInterceptor.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/WeakIdentityHashMapTest.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
gradle/spotbugFilters/exclude.xml

Collect snapshot generated by an exception probe frame in ThrowableState class that is generated by exception instance. Those exception instances are tracked by a WeakIdentityHashMap in ExceptionProbeManager. Key is directly the exception instance. The Weak nature of the hash map allow to remove the entry upon the exception is no longer reachable.
When unwinding, once the exception reaches the frame level where it is added to the span (DDSpan::addThrowable) we process all the collected snapshots and and add tags with frame index for each snapshot id. The frame index is computed based on the generated mapping between original exception (the one added to the span) and the inner most exception which was used to generated exception probes and snapshots.
An instrumentation bug is also fixed: …

Add frame tags and send snapshots on addThrowable

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ModuleExecutionSettingsFactoryImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/CoverageUtils.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitDataUploaderImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ipc/SignalServerRunnable.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexBuilder.java

Decreases log level of `INFO` logs to `DEBUG`.
The only log statement with level `INFO` left is the one that prints CI Visibility settings when the tracer is initialised.
Also updates logic that propagates system properties from parent process (Maven/Gradle) to children processes: not only `dd.*` properties are now propagated, but also `datadog.*` properties.
This is needed to ensure that `datadog.slf4j.simpleLogger.defaultLogLevel` property is propagated from parent to children.
There is a CI Visibility customer complaining about the logs being too noisy.
Jira ticket: [APMS-11714]
[APMS-11714]: https://datadoghq.atlassian.net/browse/APMS-11714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reduce logging noise in CI Visibility

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/TPEHelper.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/QueueTimingForkedTest.groovy

This fixes a regression in an unreleased profiling feature (queue time) which times how long is spent scheduling tasks which run in thread pools. This was inadvertently broken by #6446 but there wasn't a test in place to prevent this. The root cause was that FutureTask is excluded as a `RUNNABLE` so the timer was no longer started after being moved into `TPEHelper`, but the original instrumentation was using the wrong context field within FutureTask (the one for `Runnable`, not `RunnableFuture`) in the first place. The solution is to move the starting the queue timer back into the instrumentation, and (hopefully, temporarily) complicating the instrumentation slightly to handle `RunnableFuture`s whenever excluded as `RUNNABLE`. A test is also added to verify the fix and prevent regression. …

ensure queue timer is started for RunnableFuture types

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastSystem.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterModule.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/iast/IastPostProcessorFactoryTest.groovy
dd-java-agent/instrumentation/iast-instrumenter/src/main/java/datadog/trace/instrumentation/iastinstrumenter/IastInstrumentation.java
internal-api/src/main/java/datadog/trace/api/iast/telemetry/IastMetricCollector.java
internal-api/src/test/groovy/datadog/trace/api/iast/telemetry/IastMetricCollectorTest.groovy
telemetry/src/test/groovy/datadog/telemetry/metric/IastMetricPeriodicActionTest.groovy

Removes IAST from triggering inactive opt-out advices when appsec starts in inactive mode, only when appsec is fully enabled IAST opt-out advices will be triggered (also fully enabled).
Since there is no benefit from starting IAST opt-out advices in inactive mode besides testing stability (in fact the advices are no-ops so no vulnerabilities will be discovered), it's better simply to skip them.

Ensure no IAST advices are added unless appsec is fully enabled

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/TaskUnwrappingInstrumentation.java

Unwraps another adapter so we can get to the underlying task name for queueing in the FJP.

unwrap ForkJoinTask$AdaptedInterruptibleCallable

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/ExceptionHelper.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/DefaultExceptionDebuggerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeManagerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/ExceptionHelperTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/TestHelper.java
dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java

Rename config option for exception debugging from
`DD_DYNAMIC_INSTRUMENTATION_EXCEPTION_ENABLED` to `DD_EXCEPTION_DEBUGGING_ENABLED`
Fix frame index following the change in Error Tracking UI

Make Exception debugging instrumentation async

---

benchmark/load/petclinic/benchmark.json

Changes the variant name for the petclinic benchmark in the scenario where AppSec starts with IAST completely disabled.

Fix AppSec without IAST petclinic benchmark variant

---

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java

Restricts the runtime version augmentation to AOT native image only
The JIT GraalVM based JFR profiles are fully compatible with the Hotspot ones. Therefore we don't need to have this special distinguishing postfix that allows working around some GraalVM native image JFR implementation quirks in our backend.

Amend the runtime version for the AOT native image only

---

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingIntegration.java

#6261 introduced a regression by conflating detachment from wallclock profiling with clearing profiling context, but sometimes we have to detach the current thread to avoid signalling it when it goes off CPU in certain states (e.g. to workaround a JDK bug where interrupted socket connects do not reduce the timeout before resuming) but the current thread should retain its context for all purposes.

fix spurious context clear when thread detached from wallclock profiling

---

internal-api/src/main/java/datadog/trace/api/iast/telemetry/IastMetric.java
internal-api/src/main/java/datadog/trace/api/iast/telemetry/IastMetricCollector.java
internal-api/src/test/groovy/datadog/trace/api/iast/telemetry/IastMetricCollectorTest.groovy

Improves the handling of wrapped metrics from two fronts:
- Removes the Function to check if a metric is wrapped that was causing unnecessary wrapped types conversion
- Removes the wrapping logic from the happy path so most tags are not affected by the wrapping

Improve IAST metric unwrapping logic

---

gradle/dependencies.gradle

Two minor [changes](https://github.com/DataDog/java-profiler/releases/tag/v_1.3.0):
1. Change the way queue timestamps are recorded
2. Add a start time to internal counters to make the .jfr files we produce readable by the JFR CLI tool

Upgrade ddprof to 1.3.0

---

build.gradle

Adds `allowInsecureProtocol` so that publishing to a dockerized maven repo works. Also updates the comment
I was testing local sonatype publishing and it was broken

Fix publishing to local sonatype

---

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsDecorator.java
dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/SqsClientTest.groovy
dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/SqsDecorator.java
dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/SqsClientTest.groovy
dd-java-agent/instrumentation/jakarta-jms/src/main/java/datadog/trace/instrumentation/jakarta/jms/JMSDecorator.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsDecorator.java
dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientRequestTracingHandler.java
dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientRequestTracingHandler.java
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
internal-api/src/main/java/datadog/trace/api/Config.java

The legacy tracing option was coupled to the fact that the current schema version allows or not inferred services (to avoid using 'fake' services like kafka, sqs, jms).
While this is working for all the instrumentation using this setting to mutate the service name or not, it is not working when the an instrumentation is using a legacy tracing option to put a breaking change under a feature flag (i.e. httpasyncclient4 for url parsing).
In order to fix it I decoupled the two conditions and also factorized a bit the commonly used legacy tracing options (for sqs, jms, kafka, aws-sdk) to avoid code duplication

refactor isLegacyTracingEnabled usages

---

dd-java-agent/instrumentation/undertow/src/main/java/datadog/trace/instrumentation/undertow/UndertowDecorator.java
dd-java-agent/instrumentation/undertow/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/ServletInstrumentation.java
dd-java-agent/instrumentation/undertow/undertow-2.0/src/test/groovy/UndertowDispatcherTest.groovy
dd-java-agent/instrumentation/undertow/undertow-2.0/src/test/groovy/UndertowServletTest.groovy

Undertow  is today setting `http.route` from `HttpServletMapping#getMappingMatch()`. There few issues with that:
* Other servlet/application server instrumentations are not doing this hence we have an incoherent behaviour
* It's only happening on undertow < 2.2. For more recent versions of undertow based on jakarta servlet, that's not happening
* `http.route` should be set by more specific frameworks (i.e. jax-rs, spring mvc) and should not contain a part of the relative uri that can lead to high cardinality resources
This PR allows preventing undertow instrumentation from setting  the`http.route` tag by explicitly setting:
* The env `DD_UNDERTOW_LEGACY_TRACING_ENABLED=false`
* The sysprop `-Ddd.undertow.legacy.tracing.enabled=false`
This cannot be done as an easy change this it will …

Optionally prevent undertow from setting http.route

---

dd-java-agent/appsec/build.gradle

* Upgrade to libddwaf-java 9.1.0. There are no changes to libddwaf itself or bindings code here, only build changes. libc++ was upgraded too.
* These builds are smaller, saving 535KB on our final dd-java-agent.jar. Also resulting in faster initialization.

Upgrade to libddwaf-java 9.1.1

---

.github/workflows/lib-injection.yaml

Migrate the system-tests lib injection test to the new approach
Lib Injection tests were build using bash scripting, new tests use kubernetes python client

System-tests: new k8s lib injection tests

---

buildSrc/build.gradle.kts
buildSrc/call-site-instrumentation-plugin/build.gradle.kts
buildSrc/src/test/groovy/CallSiteInstrumentationPluginTest.groovy
buildSrc/src/test/groovy/InstrumentPluginTest.groovy
gradle/dependencies.gradle

Changes of note since last upgrade (1.14.9)
* Add support for Java 23
* Pin proxy class file version to avoid implicit changes when using Graal native image
* Add lazy facade to default TypePool in AgentBuilder to avoid parsing of types ignored by name

byte-buddy 1.14.12

---

dd-java-agent/build.gradle
gradle/dependencies.gradle

[Send in-{inode} using the cgroup controller when container-id cannot be retrieved](https://github.com/DataDog/java-dogstatsd-client/pull/232)
[Don't send partial messages when the utf8 encoder overflows ](https://github.com/DataDog/java-dogstatsd-client/pull/224)
[Fix a bug in address resolution order](https://github.com/DataDog/java-dogstatsd-client/commit/87832f03f3471985f335e16f9926bd189ce39f31)

java-dogstatsd-client 4.3.0

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterIndex.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterModule.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/InstrumenterIndexTest.groovy
dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/test/TestIndexFirstModule.java
dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/test/TestIndexLastModule.java
dd-java-agent/agent-tooling/src/test/resources/META-INF/services/datadog.trace.agent.tooling.InstrumenterModule

Allows modules to be applied in a particular order, rather than just the order they appear in the buiild.
Note: this ordering is applied at build-time before generating the `instrumenter.index` used at runtime.
Jira ticket: [AIT-9441]
[AIT-9441]: https://datadoghq.atlassian.net/browse/AIT-9441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support ordering of InstrumenterModules

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
dd-java-agent/instrumentation/kafka-common/src/main/java/datadog/trace/instrumentation/kafka_common/StreamingContext.java
dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java

This PR fixes a bug reported by KStreams users. See [this](https://datadoghq.atlassian.net/browse/DSMS-12) ticket for context.
`STREAMING_CONTEXT` relies on topology builder to get all source / sink / system topics. The issue with this approach is that some topics may not be part of the topology when it's created. An example may be `.to(` call which uses some logic to determine the downstream sink. In the example below `RE_KEYED_BACKLOGS` topic will not be added to the streaming context, since it's not resolved when topology builder is invoked. The solution is to allow DSM checkpoints for all topics which are not known at the start of the application.
```
builder
.<Integer, String>stream(RESOLVED_BACKLOGS)
.selectKey((key, val) -> key + 1)
.to((key, value, ctx) -> { …
```

[DSM] - Fix KStreams with dynamic queue names

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterMetrics.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java

Moves initial calculation of the `triageEnabled` flag to `InstrumenterConfig` so `InstrumenterMetrics` can check it without triggering load of the larger `Config` object. The triage section of `Config` is updated to use that initial calculation.
Avoids performance cost of loading `Config` early on during instrumentation, also avoids potentially loading additional JDK types if debug is enabled (since loading `Config` while debug is turned on can trigger a process call to `hostname`)

Avoid touching Config in InstrumenterMetrics

---

utils/container-utils/src/main/java/datadog/common/container/ContainerInfo.java
utils/container-utils/src/test/groovy/datadog/common/container/ContainerInfoTest.groovy

Fixes Datadog-Entity-ID detection by skipping a root inode
It was returning the root inode
Jira ticket: [APMJAVA-1283]
[APMJAVA-1283]: https://datadoghq.atlassian.net/browse/APMJAVA-1283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Datadog-Entity-ID detection by skipping a root inode

---

remote-config/src/main/java/datadog/remoteconfig/tuf/RemoteConfigRequest.java

Adds additional Remote Config capability bits to ClientInfo as defined here:
https://datadoghq.atlassian.net/wiki/spaces/RC/pages/2594702792/Client+capabilities+list

Expand remote config ClientInfo

---

utils/container-utils/src/main/java/datadog/common/container/ContainerInfo.java
utils/container-utils/src/test/groovy/datadog/common/container/ContainerInfoTest.groovy

Fixes Datadog-Entity-ID detection by joining paths properly.
It used Path.resolve that clears path when joined with '/'.
Jira ticket: [APMJAVA-1283]
This is continuation of previously merged PR: #6858
[APMJAVA-1283]: https://datadoghq.atlassian.net/browse/APMJAVA-1283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Datadog-Entity-ID detection paths joining

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/buildsystem/ProxyTestSession.java

Adds a synchronous flush of pending traces to `TestFrameworkSession#end` invocation.
`TestFrameworkSession` is used by CI Vis children processes (JVMs that a build system forks for tests execution).
The `end` method is invoked by a shutdown hook when a child process terminates.
As soon as all the tests have executed, the build system can terminate the child process that it previously forked to run the tests.
We need to ensure that all the pending traces have been flushed before the process shuts down, otherwise test events may be lost.
Jira ticket: [CIVIS-9567]
[CIVIS-9567]: https://datadoghq.atlassian.net/browse/CIVIS-9567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Flush pending traces synchronously before terminating child process

---

.gitlab/benchmarks.yml

Adds `allow_failure: true` to DSM benchmark jobs. Without it being set, all Gitlab jobs are in the `blocked` state. This is a quirk of Gitlab for pipelines using `rules` config with manual jobs.
I noticed all gitlab pipelines were blocked for months.

Prevent gitlab pipelines from always being "blocked"

---

buildSrc/build.gradle.kts
buildSrc/call-site-instrumentation-plugin/build.gradle.kts
buildSrc/src/test/groovy/CallSiteInstrumentationPluginTest.groovy
buildSrc/src/test/groovy/InstrumentPluginTest.groovy
gradle/dependencies.gradle

Changes of note since last upgrade (1.14.12)
- Avoid resolving type variables when generic type processing is disabled.
- Improve error message for Byte Buddy agent external attach.
- Fix build for modular jars when using later version than Java 8.
There is a [commit](https://github.com/raphw/byte-buddy/commit/aa5c04a2b5c7fc6d71a257b19952f8817e828706) included in this release that affects IAST, it fixes this [issue](https://github.com/DataDog/dd-trace-java/issues/6723)

Update byte-buddy to 1.14.13

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/IsPublicFilter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java
internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
internal-api/src/main/java/datadog/trace/api/ResolverCacheConfig.java

Reduces the number of class-file lookups needed when byte-buddy checks which types are visible from other types.
(cuts the number of additional class-file lookups by almost 50% - most of the remaining lookups relate to muzzle)

Keep track of public classes in compact filter

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java

This PR allows setups which turn off trace instrumentation, but enable CI-Vis instrumentation (which creates spans independently and doesn't rely on trace instrumentation)
We can't just use `config.isTraceEnabled()` because that is historically used to control whether trace instrumentation is applied and there are other products (CI-Vis) which generate spans and don't rely on `isTraceEnabled` being `true`.
We could create a new method which tells us whether the tracer should be installed, which uses the same logic as in [TracerInstaller](https://github.com/DataDog/dd-trace-java/blob/v1.31.2/dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java#L18) but I think a simpler approach is to always default it to `true` if the `CoreTracer` is installed.
(The …

Installation of CoreTracer implies tracing submission is on initially

---

dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceDecorator.java

since `DECORATE` just points to itself (this is leftover from when that code was moved from the advice to the decorator)

Remove redundant use of DECORATE in TraceDecorator

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ReflectiveFieldValueResolver.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot30.java

To fix this we need to catch eventual exception thrown by accessing field values. For that we continue to try to access directly to field when possible because it will be faster, but when we detect fields are not accessible we use another method that try to access it through reflection but could catch exception if not and returns a CapturedValue instance filled with the reason of this exception.
NoSuchFieldException can be thrown if we try to capture, through reflection, (static) fields from JDK classes or from another module. 
Jira ticket: [DEBUG-2270]
[DEBUG-2270]: https://datadoghq.atlassian.net/browse/DEBUG-2270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix inaccessible fields capture

---

communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java

When setting the timeout for the tracer's default HTTP client, an increased value is used if CI Visibility is enabled (30 seconds vs 10 seconds).
CI Visibility has a "get skippable tests" endpoint that might take more than 15 seconds to respond in some cases.
Jira ticket: [CIVIS-9601]
[CIVIS-9601]: https://datadoghq.atlassian.net/browse/CIVIS-9601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Increase default timeout for requests made to CI Visibility backend through EVP proxy

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/ExceptionHelper.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/DefaultExceptionDebuggerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/ExceptionHelperTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/MoshiSnapshotTestHelper.java
dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot20.java

Instead of relying solely on matching class and method name for snapshot assignment on exception debugging we are using the stack depth of the snapshot of the current frame. It allows to support recursive calls

Use stack depth to do snapshot assignment

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInstrumentation.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/NoopTextMapInjectAdapter.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TextMapInjectAdapter.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TextMapInjectAdapterInterface.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamTaskInstrumentation.java

This PR allows customers to enable a limited version of Data Streams monitoring, but without passing context through headers.
This can be useful is really high throughput pipelines with small message size, in which the header size would hugely impact the total throughput through Kafka.

Enable Data Streams without adding context into Kafka headers

---

dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie

Exclude `oracle.j2ee.*` packages from being selected as vulnerability locations.
Jira ticket: [APPSEC-52409](https://datadoghq.atlassian.net/browse/APPSEC-52409)
[APPSEC-52409]: https://datadoghq.atlassian.net/browse/APPSEC-52409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Exclude oracle.j2ee from vulnerability locations

---

dd-java-agent/agent-bootstrap/src/main/resources/META-INF/native-image/com.datadoghq/dd-java-agent/reflect-config.json
dd-trace-core/src/main/java/datadog/trace/core/DDSpanLink.java

Uses a initialization-on-demand holder idiom for the DDSpanLink encoder to make sure that it is not initialized more than once, so it is thread safe. During debugging we saw a bunch of
```
java.lang.IllegalArgumentException: Expected at least one @ToJson or @FromJson method on datadog.trace.agent.core.DDSpanLink$SpanLinkAdapter
at com.squareup.moshi.AdapterMethodsFactory.get(AdapterMethodsFactory.java:153)
at com.squareup.moshi.Moshi$Builder.add(Moshi.java:223)
at datadog.trace.agent.core.DDSpanLink.getEncoder(DDSpanLink.java:99)
at datadog.trace.agent.core.DDSpanLink.toTag(DDSpanLink.java:77)
at datadog.trace.agent.core.DDSpanContext.processTagsAndBaggage(DDSpanContext.java:789)
at datadog.trace.agent.core.DDSpan.processTagsAndBaggage(DDSpan.java:703)
at …
```

Register SpanLinkAdapter and SpanLinkJson for reflection 

---

.gitlab-ci.yml
.gitlab/single-step-instrumentation-tests.yml

Add the onboarding tests on gitlab pipeline. These tests will be executed after deb and rpm packages generation.
System-tests nightly build pipeline is launching the onboarding tests agains latest released packages.
We need to launch the onboarding tests for current branch generated packages.
These tests are adding for auto-inject and dd-trace-rb repositories. We are trying to expand to all dd-trace-lang repos.

Add Onboarding test on gitlab pipelines

---

dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/core/BufferInstrumentationTest.groovy
dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/core/HeadersAdaptorInstrumentationTest.groovy
dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/core/BufferInstrumentationTest.groovy
dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/core/MultiMapInstrumentationTest.groovy

This PR fix few test names to not rely on toString() for generated names, making them unique across runs.
This will help identify tests in CI visibility.

Fix test names to be unique

---

gradle/dependencies.gradle

Brings in the memory leak fix from https://github.com/DataDog/java-profiler/pull/83
Jira ticket: [SCP-414]
[SCP-414]: https://datadoghq.atlassian.net/browse/SCP-414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update ddprof to 1.4.0

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/ApplicationModuleImpl.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/ApplicationModuleTest.groovy

- Add a new method Reporter#noDepupReport to allow report vulnerabilities without deduplication
- Remove deduplication for session rewriting vulnerability report
If several apps are deployed in the same server  only the first one session rewriting vulnerability find will be reported 
Jira ticket: [APPSEC-52434]
[APPSEC-52434]: https://datadoghq.atlassian.net/browse/APPSEC-52434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove deduplication for session rewriting vulnerability report

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/ApplicationModuleImpl.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/ApplicationModuleTest.groovy

The current implementation uses the default  VulnerabilityTypeImpl but this is conceptually wrong as there is no error in a file. 
Change VulnerabilityType ADMIN_CONSOLE_ACTIVE implementation to  ServiceVulnerabilityType
Jira ticket: [APPSEC-52435]
[APPSEC-52435]: https://datadoghq.atlassian.net/browse/APPSEC-52435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Admin Console Active vulnerability hash calculation

---

.gitlab/benchmarks.yml

Separates load and startup benchmarks in different jobs.
The main reason for the separation is to improve the time it takes to run the benchmaks

Run load and startup benchmarks in different jobs

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/ApplicationModuleImpl.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/ApplicationModuleTest.groovy
dd-java-agent/agent-iast/src/test/resources/application/adminconsoleactive/insecure/WEB-INF/web.xml
dd-java-agent/agent-iast/src/test/resources/application/adminconsoleactive/insecure/tomcat/host/WEB-INF/web.xml
dd-java-agent/agent-iast/src/test/resources/application/adminconsoleactive/insecure/tomcat/manager/WEB-INF/web.xml

- Parameterize Admin console active report implementation to be able to report more Admin consoles and not only Tomcat Manager Application
- Report Admin console active vulnerability when `<display-name>Tomcat Host Manager Application</display-name>` is found in application web.xml
Report Admin console active vulnerability if Tomcat Host Manager Application  is deployed in a Tomcat server

Detect Tomcat's host manager tomcat application as admin console

---

dd-java-agent/instrumentation/vertx-redis-client-3.9/src/test/groovy/VertxRedisAPITestBase.groovy

This PR marks Vert.X Redis Client 4 integration test as flaky.
See #6910
Jira ticket: [AIDM-12]
[AIDM-12]: https://datadoghq.atlassian.net/browse/AIDM-12?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mark Vert.X Redis Client 4 integration test as flaky

---

build.gradle
buildSrc/build.gradle.kts
buildSrc/call-site-instrumentation-plugin/build.gradle.kts
buildSrc/src/test/groovy/CallSiteInstrumentationPluginTest.groovy
dd-smoke-tests/armeria-grpc/application/build.gradle
dd-smoke-tests/kafka-3/application/build.gradle
dd-smoke-tests/quarkus/application/build.gradle
dd-smoke-tests/spring-boot-2.7-webflux/application/build.gradle
dd-smoke-tests/spring-boot-3.0-native/application/build.gradle
dd-smoke-tests/spring-boot-3.0-webflux/application/build.gradle
dd-smoke-tests/spring-boot-3.0-webmvc/application/build.gradle
dd-smoke-tests/wildfly/spring-ear/build.gradle
test-published-dependencies/build.gradle

Updates spotless plugin v6.11.0 -> v6.13.0
v6.13.0 is the last version usable w/JDK-8.  v6.14.1 requires JDK-11+
v6.11.0 was showing this NPE which v6.13.0 fixes:
```
$ ./gradlew :dd-smoke-tests:java9-modules:spotlessGroovyGradle
> Task :dd-smoke-tests:java9-modules:spotlessGroovyGradle
internal error
at org.codehaus.groovy.eclipse.refactoring.formatter.GroovyIndentation.isLastClosureArg(GroovyIndentation.java:405)
at org.codehaus.groovy.eclipse.refactoring.formatter.GroovyIndentation.setAdditionalIndentation(GroovyIndentation.java:372)
at org.codehaus.groovy.eclipse.refactoring.formatter.GroovyIndentation.getIndentationEdits(GroovyIndentation.java:135)
at org.codehaus.groovy.eclipse.refactoring.formatter.DefaultGroovyFormatter.format(DefaultGroovyFormatter.j …
```

update spotless to v6.13.0

---

.gitignore
.gitlab/benchmarks.yml
benchmark/Dockerfile
benchmark/benchmarks.sh
benchmark/dacapo/benchmark.json
benchmark/dacapo/run.sh
benchmark/startup/petclinic/benchmark.json

Add some benchmarks from the Dacapo benchmarking suite in order to test the tracer
Operations with plenty of string manipulation calls are specially harmful for IAST, these new benchmarks (e.g. biojava) simulates hostile envs for IAST to validate performance improvements. 

Add some Dacapo benchmarks to be run on PRs

---

communication/src/main/java/datadog/communication/http/HttpRetryPolicy.java
communication/src/main/java/datadog/communication/http/OkHttpUtils.java
communication/src/test/groovy/datadog/communication/http/HttpRetryPolicyTest.groovy
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/communication/BackendApiFactory.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/communication/EvpProxyApi.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/communication/IntakeApi.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddintake/DDEvpProxyApi.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddintake/DDIntakeApi.java

Updates utility method that executes (and retries, if necessary) an HTTP request.
The method is used exclusively by CI Visibility logic that sends spans to the backend.
When a child JVM that was forked for tests execution finishes its work, the build system shuts the process down.
As part of this shutdown the tracer threads receive interrupts.
It is possible that when these interrupts are received some tests spans are still being dispatched.
Acting on interrupt results in these spans being lost.
The logic is updated in a way that an interrupted request will be reattempted.
If an interrupt is received at any point during request execution, the thread's interrupted flag is restored on method exit.
Jira ticket: [CIVIS-9801]
[CIVIS-9801]: …

Do not abort CI Visibility spans dispatch on interrupt

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/utils/ShellCommandExecutor.java

Updates `ShellCommandExecutor` component so that it mutes tracing for the processes that it spawns.
If not muted, the processes may show up as spans in the user's traces, which is incorrect since those processes are started by the tracer and not by the traced application.
Jira ticket: [CIVIS-9821]
[CIVIS-9821]: https://datadoghq.atlassian.net/browse/CIVIS-9821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Do not trace processes spawned by internal shell command executor

---

buildSrc/call-site-instrumentation-plugin/build.gradle.kts
buildSrc/src/main/groovy/CallSiteInstrumentationPlugin.groovy

This PR fixes the CSI (Call Site Plugin) build script which is part of the project build script. 
There are two main fixes:
CSI plugin shadowed jar was built for every gradle command runned as part of the project configuration:
With the changes, all plugin gradle tasks are properly cached (`UP-TO-DATE` state):
CSI plugin drops generated call site source files (from `build/generated/sources/csi/`) for every build, breaking the task cache and making the plugin needed to re-run.
Running `gradlew :dd-java-agent:shadowJar` multiple times shows CSI plugin tasks are not cached and are the slowest taks to run:
After the fix, all `generateCallSiteJava` generated tasks are properly cached:
The generated source files will still be cleared as part of the `clean` gradle task and will still be updated …

Fix call-site-plugin build script to avoid rebuilding plugin every time

---

settings.gradle

Updates the build scan plugin to the latest artifact coodinates.
The previous version, `3.0`, was 17 minor version old. It failed constantly in Gitlab, likely due to incompatibilities with the latest Gradle versions. Gradle has moved the plugin from `com.gradle.enterprise` to `com.gradle.develocity`. See [Migration guide](https://docs.gradle.com/develocity/gradle-plugin/legacy/#develocity_migration)

Update buildscan plugin to latest version

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/BaseCodecModuleTest.groovy
dd-java-agent/agent-iast/src/testFixtures/groovy/com/datadog/iast/test/IastRequestContextPreparationTrait.groovy
dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/iast/PathMatcherInstrumentation.java
dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/iast/helpers/TaintSingleParameterFunction.java
dd-java-agent/instrumentation/akka-http-10.2-iast/src/main/java/datadog/trace/instrumentation/akkahttp102/iast/helpers/TaintParametersFunction.java
dd-java-agent/instrumentation/java-io/src/main/java/datadog/trace/instrumentation/java/lang/StringReaderCallSite.java
dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringCallSite.java
dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractParamValueExtractorInstrumentation.java
dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderAdvice.java
dd-java-agent/instrumentation/jose-jwt/src/main/java/datadog/trace/instrumentation/josejwt/JSONObjectUtilsInstrumentation.java
dd-java-agent/instrumentation/org-json/src/main/java/datadog/trace/instrumentation/json/JSONArrayInstrumentation.java
dd-java-agent/instrumentation/org-json/src/main/java/datadog/trace/instrumentation/json/JSONObjectInstrumentation.java
dd-java-agent/instrumentation/pekko-http-1.0/src/main/java/datadog/trace/instrumentation/pekkohttp/iast/PathMatcherInstrumentation.java
dd-java-agent/instrumentation/pekko-http-1.0/src/main/java/datadog/trace/instrumentation/pekkohttp/iast/helpers/TaintParametersFunction.java
dd-java-agent/instrumentation/pekko-http-1.0/src/main/java/datadog/trace/instrumentation/pekkohttp/iast/helpers/TaintSingleParameterFunction.java
dd-java-agent/instrumentation/resteasy-appsec/src/main/java/datadog/trace/instrumentation/resteasy/CookieParamInjectorAdvice.java
dd-java-agent/instrumentation/resteasy-appsec/src/main/java/datadog/trace/instrumentation/resteasy/FormParamInjectorAdvice.java
dd-java-agent/instrumentation/resteasy-appsec/src/main/java/datadog/trace/instrumentation/resteasy/HeaderParamInjectorAdvice.java
dd-java-agent/instrumentation/resteasy-appsec/src/main/java/datadog/trace/instrumentation/resteasy/PathParamInjectorAdvice.java
dd-java-agent/instrumentation/resteasy-appsec/src/main/java/datadog/trace/instrumentation/resteasy/QueryParamInjectorAdvice.java
dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/HttpServletResponseInstrumentation.java
dd-java-agent/instrumentation/spring-core/src/main/java/datadog/trace/instrumentation/springcore/StreamUtilsInstrumentation.java
dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/core/BufferInstrumentation.java
internal-api/src/main/java/datadog/trace/api/iast/propagation/PropagationModule.java

Refactors the ```PropagationModule``` in order to separate the APIs to taint strings and objects. In the process, the `IastContext` is always passed as a parameter to simplify the API.
Tainting objects is more convoluted than tainting simple strings, this PR ensures that the extra overhead does not apply to strings.
This is a huge PR as the `PropagationModule` is used extensively around code, feel free to skip the PR as only IAST is affected by it.

Refactor propagation module with APIs for strings and objects

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/VulnerabilityEncoding.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/VulnerabilityEncodingTest.groovy
internal-api/src/main/java/datadog/trace/api/iast/telemetry/IastMetric.java

Add a new telemetry metric to mesure how many times iast-json tag exceeds max tag size
We need metrics related with how many times source code vulnerabilities information exceeds the maximum size allowed
Jira ticket: [APPSEC-11540]
[APPSEC-11540]: https://datadoghq.atlassian.net/browse/APPSEC-11540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Report via telemetry if _dd.iast.json tag exceeds max tag size

---

.gitlab-ci.yml

https://github.com/DataDog/dd-trace-java/pull/6931 inadvertently broke Gitlab builds because of the interactions between the Gitlab cache and gradle:
* Gradle always attempts to change permissions of the `.gradle` folder. See [here](https://github.com/gradle/gradle/blob/master/platforms/core-execution/persistent-cache/src/main/java/org/gradle/cache/internal/FileBackedObjectHolder.java#L114)
* With Gitlab caching, `.gradle` is owned by root
* Gradle's attempt fails and the build fails
This PR adds a workaround by copying moving back the cache folder so that it is owned by the gitlab runner user.
Related Gradle issues:
https://github.com/gradle/gradle/issues/14200
https://github.com/gradle/gradle/issues/8673

Fix folder permission interaction with Gitlab and gradle

---

dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie

Exclude package `ibm.security.*` from IAST transformations
The clases are loaded in the boot class-path so they cannot be instrumented as helpers cannot be injected there:
```
[dd.trace 2024-04-05 16:19:06:528 -0400] [Default Executor-thread-79] DEBUG datadog.trace.agent.tooling.AgentInstaller$TransformLoggingListener - Transformation failed - instrumentation.target.class=ibm.security.internal.spec.TlsMasterSecretParameterSpec instrumentation.target.classloader=null
java.lang.UnsupportedOperationException: Cannot inject helper classes onto boot-class-path
```

Exclude package ibm.security.* from IAST

---

.gitlab-ci.yml

The latest stable version of the packaging template now includes a tool `dd-pkg`. This PR uses this tool to lint the produced DEB and RPM packages.
This lint has been run at the time of package promotion, this change moves this step to the left and lets teams identify issues _before_ they're trying to release to production.
Jira ticket: [BARX-245](https://datadoghq.atlassian.net/browse/BARX-245)
[BARX-245]: https://datadoghq.atlassian.net/browse/BARX-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lint produced deb and rpm packages

---

dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyTest.groovy

This PR marks Grizzly HTTP  integration test as flaky.
See #6933

Mark Grizzly HTTP integration test as flaky

---

dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/AbstractSpark32SqlTest.groovy

This PR marks Spark integration test as flaky.
See #6957
Jira ticket: [DJM-206]
[DJM-206]: https://datadoghq.atlassian.net/browse/DJM-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mark Spark integration test as flaky

---

dd-java-agent/agent-tooling/build.gradle
dd-java-agent/instrumentation/iast-instrumenter/build.gradle
dd-smoke-tests/springboot-tomcat/build.gradle
gradle/java_no_deps.gradle

This PR removes the broken `packageSources` task.
This task creates "-sources.jar" like the `withSourcesJar()` from the [Java gradle plugin](https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.plugins/-java-plugin-extension/with-sources-jar.html).
The artifact produced by the `packageSources` tasks were overridden by the Java plugin ones at every build and broke the build cache.
I checked the artifact that should be produced by the `packageSources` task are the same (in size and in file count) that the ones the Java plugin builds. We should be able to safely remove the task without trying to fix it.
This task breaks the build cache by creating artifacts that are always overridden.
Fixing it finally makes the all the `gradle assemble` command tasks _up-to-date_:
```bash
BUILD …
```

Fix CI broken sources artifact

---

dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/SmokeTestUtils.java

Fix system property declared after classname.
Also dump for log file if the application failed to run.
Dumping the application log file when run failed should helps to identify flaky tests with `255` exit code.

Fix profiling integration test app startup

---

buildSrc/src/main/groovy/InstrumentPlugin.groovy

This PR improves our custom Instrumer plugin by using Gradle plugin development conventions like:
* Late task creation with one-time configuration,
* Using Task action rather than task execution callbacks,
* Properly declare task inputs and outputs to improve cache behavior,
* Build inputs like the instrumenting classpath at task definition rather than execution to avoid passing and serializing heavy objects like `Project` and `Configuration`
* Removing deprecated Gradle API usage
This improves our build performance and cache. It also make the plugin compatible with Gradle configuration cache feature.
The commits will be squashed when merging.

Improve custom Instrumenter Gradle plugin

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextInjector.java

This avoids the need to create (and catch) `NoSuchMethodError`s when we fail to inject the super-class.
For example starting the profiler before byte-buddy can trigger loading of various JDK concurrent classes that we would usually inject context into. This is more noticeable on Java 22+ where more of these JDK classes are sub-classed.

Check target super-class implements `FieldBackedContextAccessor` before delegating to it

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/RefResolverHelper.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java

Perform redaction test at instrumentation time instead at runtime
In some cases add significant overhead
Jira ticket: [DEBUG-2335]
[DEBUG-2335]: https://datadoghq.atlassian.net/browse/DEBUG-2335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Optimize Redaction detection when capturing values

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/TaskUnwrappingInstrumentation.java

Makes akka `TaskInvocation` instances unwrappable so we can access the name of the `Runnable` they carry. 
```scala
final case class TaskInvocation(eventStream: _root_.akka.event.EventStream, runnable: _root_.java.lang.Runnable, cleanup: () => _root_.scala.Unit) extends _root_.akka.dispatch.Batchable {
override final def isBatchable: _root_.scala.Boolean = ???
def run(): _root_.scala.Unit = ???
}
```
Also allows access to Scala's `CalbackRunnable`'s `onComplete` field.
This will allow the time spent queueing by `TaskInvocation`s to be disaggregated.
Jira ticket: [PROF-9696]
[PROF-9696]: https://datadoghq.atlassian.net/browse/PROF-9696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

unwrap akka `TaskInvocation` and scala `CallbackRunnable`

---

dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java
dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractSparkInstrumentation.java
dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/AbstractSparkTest.groovy

Finish pyspark-shell application span when the spark listener is receiving the `SparkListenerApplicationEnd` event
The application span is currently finished [when exiting the runMain](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractSparkInstrumentation.java#L56-L63) method to capture JVM errors ([from this PR](https://github.com/DataDog/dd-trace-java/pull/5505)), however this function is not exited as expected (System.exit(0)) when executing as pyspark-shell
Pyspark application can be launched [using multiple method](https://spark.apache.org/docs/latest/quick-start.html#self-contained-applications), mainly:
- `spark-submit script.py` 
- `python script.py` 
The spark instrumentation is …

Finish pyspark-shell trace using SparkListenerApplicationEnd

---

dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java

Add logs for creation/completion of datadog spark listener
Easier troubleshooting to validate that everything is running as expected

Add logs on datadog spark listener lifecycle

---

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/QueueTimeTracker.java

This fixes a design flaw where RDTSC derived values are compared across cores which can have frequency scaling applied differently, and just uses the system time instead for the sake of computing the threshold.

use real time threshold for queue times

---

dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/RuleFlags.java
dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy

Processes `sampling.priority` tags as defined by [OpenTracing](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table):
> If greater than 0, a hint to the Tracer to do its best to capture the trace. If 0, a hint to the trace to not-capture the trace. If absent, the Tracer should use its default sampling mechanism.
Improves consistency with other tracers that process `sampling.priority` tags. 

Process 'sampling.priority' tags

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/CombiningMatcher.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/CombiningTransformerBuilder.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ClassLoaderMatchers.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlareService.java
internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java
utils/time-utils/build.gradle
utils/time-utils/src/main/java/datadog/trace/api/time/TimeUtils.java
utils/time-utils/src/test/groovy/datadog/trace/api/time/TimeUtilsTest.groovy

Environment variable:
```
DD_EXPERIMENTAL_DEFER_INTEGRATIONS_UNTIL=10m
```
Units of h (hours) and s (seconds) are also accepted, the default unit when omitted is seconds.
Equivalent JVM option:
```
-Ddd.experimental.defer.integrations.until=10m
```
You can also limit this feature to particular class-loaders with this environment variable:
```
DD_TRACE_CLASSLOADERS_DEFER=name1,name2
```
or this JVM option:
```
-Ddd.trace.classloaders.defer=name1,name2
```
Allows matching and transformation to be moved out of startup to a point later on in the application's runtime, but at a cost of not being able to apply certain structural changes.
Bootstrap transformations are still applied at startup because some of them are essential to installation of the tracer (for example ensuring boot-delegation …

[EXPERIMENTAL] Support deferred matching and transformation for particular class-loaders

---

dd-trace-core/src/main/java/datadog/trace/common/sampling/SpanSamplingRules.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/TraceSamplingRules.java
internal-api/src/main/java/datadog/trace/api/sampling/SamplingRule.java

Initial change to key data structures; for rules supplied by static config the provenance is "customer"
Jira ticket: [AIT-9975]
[AIT-9975]: https://datadoghq.atlassian.net/browse/AIT-9975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add provenance to sampling rules

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/CombiningTransformerBuilder.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterModule.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteTransformer.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/HelperInjectionTest.groovy
dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradlePluginInjectorInstrumentation.java

Fixes the Gradle plugin injected by CI Visibility so that it does not cause Gradle build scans to fail.
Attaching tracer with CI Visibility to a Gradle build that has scanning enabled causes the following error (the code is obfuscated since build scans are part of Gradle Enterprise):
```
Gradle version: 8.6
23562Plugin version: 3.15.1
23563
23564com.gradle.scan.plugin.internal.operations.a: Build operation dispatch of started notification failed.
23565Operation context:
23566 org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$1 (1): {}
23567 org.gradle.configuration.BuildOperationFiringProjectsPreparer$ConfigureBuild$1 (104): {getBuildPath=:}
23568 org.gradle.initialization.buildsrc.BuildSourceBuilder$2$1 (169): {getBuildPath=:}
23569 …
```

Fix CI Visibility Gradle plugin to be compatible with Gradle build scans

---

dd-java-agent/instrumentation/selenium/src/main/java/datadog/trace/instrumentation/selenium/SeleniumUtils.java
dd-java-agent/instrumentation/selenium/src/test/groovy/datadog/trace/instrumentation/selenium/SeleniumUtilsTest.groovy

Updates Selenium instrumentation to avoid setting cookies for pages whose URL cannot be parsed (`about:blank` is one example of such page).
Some Selenium tests explicitly open `about:blank` before starting a test case.
Trying to set a cookie for this page will lead to a Selenium driver exception.
Selenium instrumentation adds cookies for loaded pages in order to integrate with DD RUM (if the page has RUM instrumentation configured, RUM will use the cookie to establish correspondence between a RUM session and a CI Visibility test case).
Jira ticket: [CIVIS-9921]
[CIVIS-9921]: https://datadoghq.atlassian.net/browse/CIVIS-9921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Selenium instrumentation to avoid trying to set cookies for about:blank and other similar pages

---

dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java

Increase the maximum number of retained events for the injected spark listener
Assuming spans are taking up to ~2kB of memory, going from 1000 to 5000 events can increase the memory impact from 2MB up to 10MB. This should be acceptable since only one listener is injected per spark driver
Customer with some big spark clusters reaching this limit

Increase spark listener max collection size

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ExceptionProbe.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MockSampler.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeManagerTest.java

if the first stack level generates a snapshot after sampling
we keep continuing to generate snapshot for next levels by forcing
sampling (not calling the sampler).
For each evaluation of exception probe we query the state by throwable
instance and based on this state (list of snapshots) we take the
decision keep sampling or drop)
Having complete stacks with all snpashots without depending on the sampling for each stack level

Add coordinated sampling for Exception Debugging

---

dd-trace-core/build.gradle
dd-trace-core/src/main/java/datadog/trace/common/sampling/RateSamplingRule.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/RuleBasedTraceSampler.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/Sampler.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/SingleSpanSampler.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/SpanSamplingRules.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/TraceSamplingRules.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/TracingConfigPoller.java
internal-api/build.gradle
internal-api/src/main/java/datadog/trace/api/DynamicConfig.java
internal-api/src/main/java/datadog/trace/api/sampling/SamplingRule.java

Adds capability to receive tracing sampling rules from remote-config.
Jira ticket: [AIT-9975]
[AIT-9975]: https://datadoghq.atlassian.net/browse/AIT-9975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Accept trace sampling rules via remote-config

---

dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/IastServlet2Instrumentation.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/IastServlet3Instrumentation.java
dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/IastJakartaServletInstrumentation.java

Enable opt-out for instrumentations that calls ApplicationModule
We are not reporting servlet misconfiguration vulnerabilities with opt-out configuration

Report servlet misconfiguration vulnerabilities with opt-out configuration

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/DefaultExceptionDebuggerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeManagerTest.java

Keep a timestamp associated to the fingerprint to know when last time we capture snapshots for this exception. Hardcoded once an hour will probably make it a config token for this later

Capture exception snapshots only once an hour

---

dd-java-agent/instrumentation/spring-security-5/src/main/java17/datadog/trace/instrumentation/springsecurity5/SpringSecurityUserEventDecorator.java
dd-java-agent/instrumentation/spring-security-5/src/main/java17/datadog/trace/instrumentation/springsecurity5/UserDetailsManagerAdvice.java
dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/SpringBootBasedTest.groovy

Skip generating `appsec.events.users.signup.*` events in case there is an error in the sign up process.

Skip auto user events when sign-up logic fails

---

dd-java-agent/instrumentation/spring-security-5/src/main/java17/datadog/trace/instrumentation/springsecurity5/SpringSecurityUserEventDecorator.java
dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/SecurityConfig.groovy
dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/SpringBootBasedTest.groovy
dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/TestEndpoint.groovy
dd-java-agent/instrumentation/spring-security-5/src/test/java/custom/CustomAuthenticationFilter.java
dd-java-agent/instrumentation/spring-security-5/src/test/java/custom/CustomAuthenticationProvider.java
dd-java-agent/instrumentation/spring-security-5/src/test/java/custom/CustomAuthenticationToken.java

Skips auto user tracking events for authentication tokens other than username and password.
Detection of account take over campaigns are very sensitive to false positives in regards of events, having authentication events from systems like OAuth or Saml only introduces noise that might affect the detection.
Jira ticket: [APPSEC-53059]
[APPSEC-53059]: https://datadoghq.atlassian.net/browse/APPSEC-53059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Exclude non username and password authentication from user tracking

---

dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java

This PR marks the last profiling integration smoke tests as flaky.
All the tests from `CodeHotspotsTest` are either disabled or flaky except this one.
It was the most frequent flaky test to break the CI.

Mark test profiling smoke test as flaky

---

dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java

Removes `sampling_rules` from StatusLogger
The `sampling_rules` field in StatusLogger does not currently work with our new sampling mechanism. This has caused confusion for users as they're setting up sampling. This PR removes that log to alleviate confusion
We intend to re-add a sampling log statement back in the future as part of [APMAPI-61](https://datadoghq.atlassian.net/browse/APMAPI-61)
Jira ticket: [APMS-12002](https://datadoghq.atlassian.net/browse/APMS-12002)
[APMAPI-61]: https://datadoghq.atlassian.net/browse/APMAPI-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APMS-12002]: https://datadoghq.atlassian.net/browse/APMS-12002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove sampling_rules from StatusLogger

---

dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

PR #6990 accidentally uses a `Config` method that is going away as part of the cleanup in #6996
The `getSpanTags` method was only recently added and isn't really the same thing as `getLocalRootSpanTags`
While `getLocalRootSpanTags` returns tracer-defined tags to be added to the local root span, `getSpanTags` was returning user-defined tags to be added to every span. User-defined tags are supposed be ignored if remote-config overrides them via `tracing_tags`. Mixing tracer-defined tags with user-defined tags in the same config method makes it difficult to remove one without removing the other, leading to subtle bugs.
Once this revert is applied, I'll merge #6996 and propose an alternative approach.

Revert PR #6990 (Add product tags to each span if products are enabled)

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/main/java/datadog/trace/core/TracingConfigPoller.java
dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

Avoids continually repeating the same merge for every span context built.
Other fixes:
* Remote 'tracing_tags' now replace all static tracer tags except `env` and `version`
Previously remote 'tracing_tags' would completely replace any static configuration
such as `DD_TAGS`,` DD_TRACE_TAGS`, or `DD_TRACE_GLOBAL_TAGS` - but would not replace
`DD_TRACE_SPAN_TAGS` - the old merge code also accidentally omitted `env` and `version`
tags which are stored under global tags, but should be merged with remote-config.
* If 'tracing_tags' is not overridden in remote-config we revert to the static config
Previously a null 'tracing_tags' override was mapped to the empty list, which is
not the same (empty list means replace the static config with nothing, whereas a
missing/null override means revert to …

Only rebuild tracer tags when the remote-config 'tracing_tags' change

---

dd-java-agent/agent-bootstrap/src/main/resources/META-INF/native-image/com.datadoghq/dd-java-agent/reflect-config.json
dd-java-agent/build.gradle
dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/AnnotationSubstitutionProcessorInstrumentation.java
dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/Target_datadog_jctools_counters_FixedSizeStripedLongCounterFields.java
dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/Target_datadog_jctools_util_UnsafeRefArrayAccess.java

Relocates JCTools
DD JCTools usage is clashing with Quarkus 3.10, since they both use JCTools and it requires GraalVM substitutions. Quarkus has the GraalVM config to do substitutions, and DD does as well, so this yields the following error `Error: Substition: org.jctools.util.UnsafeRefArrayAccess.REF_ELEMENT_SHIFT conflicts with previously registered: org.jctools.util.UnsafeRefArrayAccess.REF_ELEMENT_SHIFT`... which means that there are two substitutions being registered for the same target.
Relocating JCTools fixes not only that but prevents it from happening with other Java frameworks, as GraalVM (https://github.com/oracle/graal/blob/481625b5da2b293cc672fd4b9348612483b6e76c/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/substitute/AnnotationSubstitutionProcessor.java#L9 …

Relocate JCTools

---

.github/CODEOWNERS

Adds IDM to codeowners
Jira ticket: [AIDM-66]
[AIDM-66]: https://datadoghq.atlassian.net/browse/AIDM-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updated codeowners to add idm

---

dd-java-agent/appsec/build.gradle
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy

Upgraded libddwaf to the latest version, see:
* https://github.com/DataDog/libddwaf/releases/tag/1.17.0
* https://github.com/DataDog/libddwaf/releases/tag/1.18.0
This PR is preparatory work for the ASM Exploit Prevention (RASP)
Jira ticket: [APPSEC-52825](https://datadoghq.atlassian.net/browse/APPSEC-52825)
[APPSEC-52825]: https://datadoghq.atlassian.net/browse/APPSEC-52825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Upgrade to libddwaf 1.18.0 (libddwaf-java 10.0.0)

---

build.gradle

to perform jacoco verification for debugger tests

Add jacoco tasks to debuggerTest 

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/ASMHelper.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/instrumentation/ASMHelperTest.java

Add a protection against index out of bounds but also adjust local var array for long or double.
`ArrayIndexOutOfBoundsException` was thrown because size of the args and local vars were not correctly took into account. with Long/Double type it actually takes 2 slots into the local var tables.
```
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 8
at com.datadog.debugger.instrumentation.ASMHelper.adjustLocalVarsBasedOnArgs(ASMHelper.java:246)
at com.datadog.debugger.symbol.SymbolExtractor.extractArgs(SymbolExtractor.java:314)
at com.datadog.debugger.symbol.SymbolExtractor.extractMethods(SymbolExtractor.java:107)
at com.datadog.debugger.symbol.SymbolExtractor.extractScopes(SymbolExtractor.java:41)
at com.datadog.debugger.symbol.SymbolExtractor.extract(SymbolExtracto …
```

Fix ArrayIndexOutOfBoundsException in adjustLocalVarsBasedOnArgs

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

This is a re-worked version of https://github.com/DataDog/dd-trace-java/pull/6990 and a followup to https://github.com/DataDog/dd-trace-java/pull/6967.
Adding product tags only to local root is not enough, as there's no guarantee that every trace segment received by the backend will have this tag (due to partial flushing, trace segment splitting etc). We need a simple and robust way of marking all data coming from DSM / DJM products. Adding the tag only when the product is enabled will add the overhead only for customers of this product.
[Jira](https://datadoghq.atlassian.net/browse/DSMON-356)

[DSM] - Tag every span with the product tag if it is enabled

---

dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlareService.java

Add tracer log file to tracer flare, requested by the UI or by Triage mode:
- if a tracer log file has been defined with datadog.slf4j.simpleLogger.logFile
- and if the size of the tracer log file is < 15MB
Getting tracer logs in tracer flare to get as much information as possible to better troubleshoot issues
This is only a Draft
Jira ticket: [APMAPI-32]
[APMAPI-32]: https://datadoghq.atlassian.net/browse/APMAPI-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add log file if size is not too big

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy

Always collects `Accept`, `Content-Type` and `User-Agent` when appsec is enabled
Jira ticket: [APPSEC-52885]
[APPSEC-52885]: https://datadoghq.atlassian.net/browse/APPSEC-52885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Always collect accept, content-type and user-agent when appsec is enabled

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy

Collect common WAF request header values by default
https://docs.google.com/document/d/1xf-s6PtSr6heZxmO_QLUtcFzY_X_rT94lRXNq6-Ghws/edit
Jira ticket: [APPSEC-51375]
[APPSEC-51375]: https://datadoghq.atlassian.net/browse/APPSEC-51375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Collect common WAF request header values by default

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java

remove unnecessary verbose debug log
verbose logs

Remove debug log on sampling

---

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/JsonToExpressionConverter.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/Value.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_13.json

Add support of boolean
support characters as strings
Jira ticket: [DEBUG-2371]
[DEBUG-2371]: https://datadoghq.atlassian.net/browse/DEBUG-2371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix support of literals in Expression Language

---

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/DSL.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/PrettyPrintVisitor.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/Value.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/Visitor.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/SetValue.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/values/SetValueEmptyTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/values/SetValueNullTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/values/SetValueTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_11.json
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_13.json
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_14.json
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/MoshiConfigTestHelper.java

When having a value with a Set interface creates a SetValue to hold that Set instance
Allow to call size() on it if it safe list for lists and maps
Support `count(set)`
Jira ticket: [DEBUG-2329]
[DEBUG-2329]: https://datadoghq.atlassian.net/browse/DEBUG-2329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support of Set in Expression Language

---

dd-java-agent/instrumentation/undertow/undertow-2.0/build.gradle
dd-java-agent/instrumentation/undertow/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/ServletInstrumentation.java
dd-java-agent/instrumentation/undertow/undertow-2.2/build.gradle

LatestDep (and some muzzle) where locked to 2.2 while the stable latest undertow branch is 2.3
More in the detail the undertow-jakarta-servlet artifact seems no to be maintained but moved to regular undertow-servlet since 2.3.0

extend latest dep test for undertow

---

.circleci/config.continue.yml.j2

This PR  aims to fixing parametric tests job flakiness.
The root cause of parametric tests run not completing was not found.
The R&P team recommend to use timeouts and retries.

Add parametric tests flakiness workaround

---

dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy

This PR marks the Gradle and Maven smoke tests as flaky.
See #7024 and #7025 

Mark Gradle and Maven smoke tests as flaky

---

gradle/dependencies.gradle

The 1.6.0 version of the profiler library contains changes preventing intermittent crashes and lockups in the profiler itself.
Details [here](https://github.com/DataDog/java-profiler/releases/tag/v_1.6.0)
Bring rather important fixes in.
Jira ticket: [PROF-9733]
[PROF-9733]: https://datadoghq.atlassian.net/browse/PROF-9733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bump ddprof to 1.6.0

---

dd-java-agent/instrumentation/spring-boot/src/main/java/datadog/trace/instrumentation/springboot/SpringApplicationInstrumentation.java
dd-java-agent/instrumentation/spring-boot/src/test/groovy/SpringBootApplicationTest.groovy

Enable by default spring boot environment instrumentation that infer the service name to the value of `spring.application.name` if the user did not provide any `DD_SERVICE`
The instrumentation was in beta. I'm turning it on by default. It can be disabled by adding
* A sysprop `-Ddd.trace.integration.spring-boot.enabled=false`
* An env `DD_TRACE_INTEGRATION_SPRING_BOOT_ENABLED=false`
This change is a breaking change for applications that meets all following conditions:
* The application is a standalone spring boot jar
* The property `spring.application.name` is defined in the spring environment (properties, env, etc...)
* The service name is not provided using `DD_SERVICE` or `-Ddd.service`
In this specific use case, without this change, the service name would have been the default …

Enable spring boot service name detection from spring.application.name

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/ExtensionsLoader.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java

Users can add trace extensions to the `dd-java-agent` jar at runtime by setting this environment variable:
```
DD_TRACE_EXTENSIONS_PATH=my_extension.jar,my_other_extensions_dir
```
or adding this JVM option:
```
-Ddd.trace.extensions.path=my_extension.jar,my_other_extensions_dir
```
This PR supports extensions based on `InstrumenterModule`; future PRs will add support for other modules.
Provide a mechanism to add custom integrations to an existing installation of the Java tracer.
Jira ticket: [APMAPI-66]
[APMAPI-66]: https://datadoghq.atlassian.net/browse/APMAPI-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support loading trace extensions from a comma-separated list of jars, or directories containing jars

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/WellKnownClasses.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/ListValue.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/MapValue.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/SetValue.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/values/MapValueEmptyTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/values/MapValueTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_conditional_07.json
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/SerializerWithLimits.java

Accessing Map and set is only safe for JDK classes so all accesses are not protected to be a JDK implementation
Fix also when a key is not in the map it returns null so we can test against null in EL

Protect Map and Set accesses to be only in-memory

---

internal-api/src/main/java/datadog/trace/api/Config.java

It fixes the faulty safety-check logic which lead to enabling the ddprof library on Java versions where it is not completely safe.
Jira ticket: [PROF-9778]
[PROF-9778]: https://datadoghq.atlassian.net/browse/PROF-9778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix the ddprof safety check

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy

This PR dumps the specification name to help identify flaky tests.
There is something wrong with the tests reports where parametrized spock tests are no more attached to their class.
It might be due to using a deprecated JUnit 4 runner.
As we are losing the class name, we can't identify flaky tests using features from a parent specification.

Print the specification name to help identify flaky tests

---

dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit38SuiteEventsInstrumentation.java
dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Instrumentation.java

Fixes instrumentation of JUnit 3.8 tests.
There are two instrumentation modules that play a part:
- `JUnit4Instrumentation` that registers the test tracing listener
- `JUnit38SuiteEventsInstrumentation` that adds missing tracing events to legacy JUnit 3.8 runner adapter.
The code added by the second implementation relies on the code in the first one: it expects the tracing listener to be already initialised by the time it fires.
Thus, instrumentation order should be set explicitly in this case.
Some CI Visibility users still use legacy JUnit 3.8-based tests, even though they are executed with the newer JUnit 4 runner.
Jira ticket: [CIVIS-10040]
[CIVIS-10040]: https://datadoghq.atlassian.net/browse/CIVIS-10040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …

Fix instrumentation for legacy JUnit 3.8 tests

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java

foldExceptionStackTrace can be expensive and must be called only in debug level log.
This happens when a field is not accessible (cross module since JDK16)
undesirable overhead
Jira ticket: [DEBUG-2388]
[DEBUG-2388]: https://datadoghq.atlassian.net/browse/DEBUG-2388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix expensive folding only in debug level

---

dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/CiVisibilityPluginExtension.java

Fixes CI Visibility's Gradle instrumentation: if the instrumentation determines that Gradle Jacoco plugin is used in the instrumented project, it modifies Jacoco's list of ignored classloaders (the main reason is to add the tracer's classloader to the list to avoid instrumenting tracer classes).
It is possible for the modified list to be immutable, in which case it needs to be replaced with a newly constructed list.
Jira ticket: [CIVIS-10049]
[CIVIS-10049]: https://datadoghq.atlassian.net/browse/CIVIS-10049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Gradle instrumentation: do not fail if Jacoco excluded CL list is immutable

---

dd-java-agent/agent-debugger/build.gradle
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java

Having fingerprint maps into the DI flare helps to know how many exceptions are tracked and when are the last time the snapshots were reported.
Exception probes are reported in Probe definitions section.
Example:
```
Snapshot url: 
http://localhost:8126/debugger/v1/input
Diagnostic url: 
http://localhost:8126/debugger/v1/diagnostics
SymbolDB url: 
http://localhost:8126/symdb/v1/input
Probe definitions:
{893f0968-5f64-4eb8-b86f-02339c801aba:0=ExceptionProbe{language='java', id='893f0968-5f64-4eb8-b86f-02339c801aba', version=0, tags=null, tagMap={}, where=Where{typeName='org.springframework.samples.petclinic.vet.VetController', methodName='processUUId', sourceFile='null', signature='null', lines=[240]}, evaluateAt=EXIT, template='null', segments=null, captureSnapshot=true, when=null, …
```

Add fingerprint info into Tracer flare

---

BUILDING.md
CONTRIBUTING.md
README.md
docs/how_to_test.md
setup.sh

This PR improves the project onboarding and documentation.
The README now has a list of documentation to improve discoverability,
The setup documentation now has MacOS, Linux and Windows guidelines,
The test document is introduced. 
This should improve the overall onboarding experience.
The test document could include an _how to write tests_ section but it will require some more time.
The next documentation should be about how to setup IntelliJ IDEA and how to troubleshoot build/gradle issues.

Improve onboarding documentation

---

dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie

Adds the common package for Mockito-generated classes to the list of global ignores.
Whenever a class is mocked with Mockito, a new class is generated that replaces the original class' methods with the mocked ones.
If the tracer contains instrumentations that transform the original class, the same instrumentations will most likely be applied to the mocked class as it extends the original one.
Transforming the mocked class' code leads to errors: some instrumentations, when executed a transformed method, call another method of the same instance. Mockito does not handle this well: if a mocked method is called from inside another mocked method, Mockito's internal state gets corrupted.
The solution is to avoid transforming Mockito-generated classes, both because it fixes the errors and because …

Do not transform Mockito-generated classes

---

dd-java-agent/agent-debugger/build.gradle
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/WellKnownClasses.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/SerializerWithLimits.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
gradle/java_no_deps.gradle

We introduce in `WellKnownClasses` the mechanism to fetch fields through dedicated call to getter for registered classes.
In the special case of `Throwable` we are allowing any inherited classes to capture the `Throwable` fields as well as custom fields. Though, to capture `Throwable` fields (like `detailMessage`) we need to call getter that could be overridden. Hence ,we are checking before calling them that they are not overridden by checking the declaring class of the getter.
Add option in build to not allow reflection access for debugger tests to assess that we can access correctly even for recent JDKs
Since JDK16 it's not possible to extract values by reflection for JDK modules without adding `--add-opens=java.base/java.lang=ALL-UNNAMED` so when capturing an exception (like in …

Add Throwable capturing fields support for JDK16+

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ReflectiveFieldValueResolver.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/test/java/datadog/trace/bootstrap/debugger/el/ReflectiveFieldValueResolverTest.java

Instead of relying on exception using `getDeclaredField(String)` we are using `getDeclaredFields()` and scanning the field by name.
Overhead because of too many exceptions
Benchmarks Before/After:
```
---
Benchmark                                    Mode  Cnt     Score    Error  Units
GetFieldBenchmark.getFieldGetAllDeclared     avgt    5    24.734 ±  0.437  ns/op
GetFieldBenchmark.getFieldGetDeclaredByName  avgt    5  1756.905 ± 47.458  ns/op
---
@State(Scope.Benchmark)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@Fork(1)
public class GetFieldBenchmark {
@Benchmark
public void getFieldGetDeclaredByName(Blackhole bh) {
bh.consume(getField(GrokProcessor.class, "id"));
}
@Benchmark
public void getFieldGetAllDeclared(Blackhole bh) { …
```

Fix perf issue when accessing fields by reflection

---

dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

add as alias for EXCEPTION_DEBUGGING_ENABLED to maintain backward compat

Add `EXCEPTION_REPLAY_ENABLED` config token

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/GitConfig.java

Fixes the logic that parses Git config files.
The fix is to replace a regular expression with a more ad-hoc logic.
The logic contains a regular expression that can require polynomial time to match (the one that splits a config line into key and value, polynomial since greedy quantifiers are used).
Since the contents of Git config files comes from outside the tracer, this regular expression can be leveraged for a DDoS attack.
Jira ticket: [VULN-6863]
[VULN-6863]: https://datadoghq.atlassian.net/browse/VULN-6863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix 'polynomial regular expression used on uncontrolled data' vulnerability in Git config parsing logic

---

dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedContext.java

fix copy/paste errors in the toString
(span ID and endToEndStartTime were mix-mashed)

Fix `ExtractedContext`'s  `toString`

---

dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy

Closing channels may raise wider type of error.
Uncaught errors make the CI flaky.

Fix error handling on RabbitMQ channel cleanup

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy

This PR marks Jetty9 integration test as flaky
See #7061 

Mark Jetty9 integration test as flaky

---

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/BinaryExpression.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/BinaryOperator.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/BinaryExpressionTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java

We are just delegating to the operator evaluation the evaluation of the left and right instead of evaluating operands before the operator.
Boolean expressions with AND (&&) or OR (||) should short circuit as expected for any languages. It helps to support correctly expressions like
`isDefined(@exception) && contains(@exception.detailMessage, 'closed')` 
Jira ticket: [DEBUG-2232]
[DEBUG-2232]: https://datadoghq.atlassian.net/browse/DEBUG-2232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix short circuiting of boolean expressions

---

dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeInstrumentationTest.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
internal-api/src/main/java/datadog/trace/api/Config.java

Add `DD_INTERNAL_EXCEPTION_REPLAY_ONLY_LOCAL_ROOT` config option to handle exception by exception debugging only for local root span (Service entry span) or all spans

Add config param for local root exception handling

---

internal-api/src/main/java/datadog/trace/api/Config.java

This avoids reporting `datadog_profiler_enabled` as true when profiling as a whole is not enabled, which makes the status log less confusing.

make datadog_profiler_enabled flag conditional on profiling_enabled

---

dd-java-agent/cws-tls/src/main/java/datadog/cws/tls/ErpcTls.java

This fixes the CWS on systems using musl, which doesn't expose the `gettid()` syscall. We replace it instead by directly calling syscall with the related syscall ID.
Be able to retrieve trace spans on docker images build upon alpine.
Only AMD64 and ARM64 archs are handled.

Fix the cws tracer on systems using musl libc (like alpine)

---

dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/UrlInstrumentation.java
dd-java-agent/instrumentation/http-url-connection/src/test/groovy/UrlConnectionTest.groovy

Exceptions during HTTP connections are already captured by `HttpUrlConnectionInstrumentation` so we don't need to also instrument the generic `URL` connection code.
The alternative would be to have an allow (or deny) list of protocols to decide when to report URL connection exceptions as spans.
Avoids creating unnecessary spans when exceptions occur during custom non-HTTP connections, like the custom Jar connection recently added in #7049.
* The URL instrumentation can be re-enabled with `DD_INTEGRATION_URLCONNECTION_ENABLED=true`
* The respective instrumentation in OpenTelemetry was also removed for the same reason.

Disable URL instrumentation by default

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
dd-trace-api/src/main/java/datadog/trace/api/internal/TraceSegment.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_4.java
dd-trace-core/src/main/java/datadog/trace/core/CoreSpan.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SimpleSpan.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentApiTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/TraceGenerator.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV04PayloadTest.groovy
dd-trace-core/src/traceAgentTest/groovy/TraceGenerator.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

This PR allows adding `meta_struct` data to spans, the `meta_struct` is lazy initialized to reduce memory consumption and uses a double locking mechanism to be initialized (same as baggage).
The new RASP module requires this new data structure in order to be able to send binary data efficiently to the backend.
The agent fully supports `meta_struct` from version v7.35.0 (April 2022).
Jira ticket: [APPSEC-52826]
Agent: https://github.com/DataDog/datadog-agent/pull/10366
.NET: https://github.com/DataDog/dd-trace-dotnet/pull/5287
JS: https://github.com/DataDog/dd-trace-js/pull/4287
Sample result of adding a stack to the `metra_struct`:
[APPSEC-52826]: https://datadoghq.atlassian.net/browse/APPSEC-52826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

Add support for meta_struct field in API v4

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/CircuitBreaker.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/DefaultExceptionDebuggerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/CircuitBreakerTest.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

To avoid having a spike of exceptions to analyze
(fingerprint/instrument) we put in front of handling the exception a circuit breaker which open when we reach more than 100 (configurable via `DD_EXCEPTION_REPLAY_MAX_EXCEPTION_ANALYSIS_LIMIT`) per second
Avoid spike of exception to be analyzed which can add overhead

Add circuit breaker for Exception Debugging

---

.gitlab/benchmarks.yml

Adds a Circle CI token to the benchmarks workflow so they can use the Circle CI API to query for artifacts and download them. 
The benchmarks runs started to fail without the token intermitently.
Depends on: https://github.com/DataDog/benchmarking-platform/pull/65

Update benchmarks gitlab workflow with circle ci token

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
internal-api/src/main/java/datadog/trace/api/EndpointCheckpointer.java

Ensure that AppSec hooks for root span finished run only once.
We had some hooks in `CoreTracer.write` meant to be run whenever a root span is finished. However, they were effectively called not just when the root span finished, but also whenever a partial flush on a child span was performed. This ended up calling the hooks multiple teams, and earlier than expected.
When `DD_APPSEC_ENABLED=true`, this led to `WAF object had not been closed` warnings whenever a partial flush was triggered and the root span was not finished yet.
Reproducing the issue is easier when setting `-Ddd.trace.partial.flush.min.spans=1`.
Jira ticket: [APPSEC-53203](https://datadoghq.atlassian.net/browse/APPSEC-53203)
[APPSEC-53203]: https://datadoghq.atlassian.net/browse/APPSEC-53203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …

Prevent AppSec context from being closed more than once on partial flush

---

.gitlab/single-step-instrumentation-tests.yml

Adds installer-based tests to the single step instrumentation steps, using the OCI package that is now pushed to the QA registry on every commit
Single step instrumentation using the datadog installer
N/A

upgrade(CI): Run installer system tests using the QA OCI registry

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeManagerTest.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Use `DD_EXCEPTION_REPLAY_MAX_FRAMES_TO_CAPTURE` to limit number of frame in user code (i.e. not third-party code) to instrument and capture per exception. Default value is 3
limit the amount of snapshots generated

Add option to limit number of frames captured

---

dd-java-agent/agent-ci-visibility/src/testFixtures/groovy/datadog/trace/civisibility/CiVisibilitySmokeTest.groovy
dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenUtils.java
dd-smoke-tests/backend-mock/build.gradle
dd-smoke-tests/backend-mock/src/main/groovy/datadog/smoketest/MockBackend.groovy
dd-smoke-tests/gradle/build.gradle
dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
dd-smoke-tests/maven/build.gradle
dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
settings.gradle

Moves test fixtures that mock Datadog backend to a separate module.
With the implementation of agentless log submission, there will be more smoke test modules that will benefit from using the mock backend. 
The CI Visibility subprojects contains some text fixtures that are used by Maven and Gradle instrumentations smoke tests.
These test fixtures contain logic that allows to start a mock Datadog backend.
Jira ticket: [CIVIS-10104]
[CIVIS-10104]: https://datadoghq.atlassian.net/browse/CIVIS-10104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Create commmon backend-mock module to use in smoke tests

---

communication/build.gradle
communication/src/main/java/datadog/communication/BackendApi.java
communication/src/main/java/datadog/communication/BackendApiFactory.java
communication/src/main/java/datadog/communication/EvpProxyApi.java
communication/src/main/java/datadog/communication/IntakeApi.java
communication/src/main/java/datadog/communication/util/IOThrowingFunction.java
communication/src/main/java/datadog/communication/util/IOUtils.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilityRepoServices.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilityServices.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ConfigurationApiImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitClient.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitDataApi.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/utils/ShellCommandExecutor.java
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/config/ConfigurationApiImplTest.groovy
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/GitClientGitInfoBuilderTest.groovy
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/tree/GitClientTest.groovy
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/tree/GitDataApiTest.groovy
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/tree/GitDataUploaderImplTest.groovy
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/utils/ShellCommandExecutorTest.groovy
dd-java-agent/instrumentation/selenium/src/testFixtures/groovy/datadog/trace/instrumentation/selenium/AbstractSeleniumTest.groovy

Moves logic for direct ("agentless") communication with the Datadog backend to the common module.
With the implementation of agentless log submission, there will be other modules besides CI Visibility that will reuse this logic.
Jira ticket: [CIVIS-10104]
[CIVIS-10104]: https://datadoghq.atlassian.net/browse/CIVIS-10104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Move backend communication logic to common module

---

dd-java-agent/agent-builder/build.gradle
dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/ExtensionFinder.java
dd-java-agent/agent-otel/otel-bootstrap/build.gradle
dd-java-agent/agent-otel/otel-bootstrap/src/main/java/datadog/trace/bootstrap/otel/Java8BytecodeBridge.java
dd-java-agent/agent-otel/otel-bootstrap/src/main/java/package-info.java
dd-java-agent/agent-otel/otel-tooling/build.gradle
dd-java-agent/agent-otel/otel-tooling/src/main/java/datadog/opentelemetry/tooling/OtelExtensionHandler.java
dd-java-agent/agent-otel/otel-tooling/src/main/java/datadog/opentelemetry/tooling/OtelInstrumentationMapper.java
dd-java-agent/agent-otel/otel-tooling/src/main/java/datadog/opentelemetry/tooling/OtelInstrumenter.java
dd-java-agent/agent-otel/otel-tooling/src/main/java/datadog/opentelemetry/tooling/OtelInstrumenterModule.java
dd-java-agent/agent-otel/otel-tooling/src/main/java/datadog/opentelemetry/tooling/OtelTransformer.java
dd-java-agent/agent-otel/otel-tooling/src/main/java/datadog/opentelemetry/tooling/OtelTransformerState.java
dd-java-agent/agent-otel/otel-tooling/src/main/java/datadog/opentelemetry/tooling/shim/OtelShimGradlePlugin.java
dd-java-agent/agent-otel/otel-tooling/src/main/java/datadog/opentelemetry/tooling/shim/OtelShimInjector.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExtensionHandler.java

Provides initial drop-in support for OpenTelemetry instrumentations at runtime, enough to load the OpenTelemetry demo instrumentation.
Mapping of muzzle declarations and virtual fields will be in another PR, followed by wider configuration support.
Builds on #7049 and #7072
Jira ticket: [APMAPI-68]
[APMAPI-68]: https://datadoghq.atlassian.net/browse/APMAPI-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Runtime drop-in support for OpenTelemetry instrumentations

---

dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDLoggerFactory.java
internal-api/src/main/java/datadog/trace/api/Config.java

* Enable telemetry logs by default if IAST or CI Visibility are activated.
* This is part of a gradual rollout of telemetry logs, prioritizing first products that need it the most.
* This code will be removed once telemetry logs are fully enabled by default. If everything goes well, that should be in about 2 releases after this PR.
* Jira ticket: [APPSEC-53106](https://datadoghq.atlassian.net/browse/APPSEC-53106)
[APPSEC-53106]: https://datadoghq.atlassian.net/browse/APPSEC-53106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enable telemetry logs for IAST, CI Visibility and Dynamic Instrumentation users

---

communication/src/main/java/datadog/communication/monitor/DDAgentStatsDConnection.java
gradle/dependencies.gradle

https://github.com/DataDog/java-dogstatsd-client/pull/243

java-dogstatsd-client 4.4.0 (fix potential file-descriptor leak)

---

dd-java-agent/agent-otel/otel-bootstrap/build.gradle
dd-java-agent/agent-otel/otel-tooling/build.gradle

This should hopefully address the intermittent failure to find `OtelShimGradlePlugin` seen recently in CI

Use same approach as agent-tooling to setup otel-tooling instrumentPluginClasspath

---

dd-smoke-tests/backend-mock/src/main/groovy/datadog/smoketest/MockBackend.groovy
dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy

Fixes logic that waits for coverage messages in Gradle and Maven smoke tests: now coverage records are counted instead of coverage requests, so asserts are not affected by batching in the tracer.
Disables smoke tests for older Gradle versions when testing with OpenJ9: Gradle Jacoco plugin does not work with this combination, and neither does the coverage solution built on top of Jacoco.
Gradle and Maven builds triggered by the smoke tests now run with tracer debug logging to simplify debugging any future failures.
"Flaky" annotation is removed from Gradle and Maven smoke tests.
Re-enabling Gradle and Maven instrumentations testing.
Jira ticket: [SDTEST-384]
[SDTEST-384]: https://datadoghq.atlassian.net/browse/SDTEST-384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …

Fix flakiness in Maven and Gradle smoke tests

---

dd-trace-ot/build.gradle

Bumps io.opentracing.contrib:opentracing-tracerresolver version to 0.1.6
Current version ([0.1.0](https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-tracerresolver/0.1.0)) depends on [opentracing-api 0.21.0](https://mvnrepository.com/artifact/io.opentracing/opentracing-api/0.21.0) while the project depends on [opentracing-api 0.32.0](https://mvnrepository.com/artifact/io.opentracing/opentracing-api/0.32.0).
Setting dependency version to [0.1.6](https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-tracerresolver/0.1.6) aligns the opentracing-api version.
* [opentracing-tracerresolver-0.1.6.pom](https://repo1.maven.org/maven2/io/opentracing/contrib/opentracing-tracerresolver/0.1.6/opentracing-tracerresolver-0.1.6.pom)
* …

Bumps opentracing-tracerresolver to 0.1.6

---

communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/MetricsAggregatorFactoryTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Avoids merging in any additional host/port settings when dealing with `unix:` URLs.
If the user has configured a `unix:` agent URL that means they want the tracer to communicate over the given UDS file, in which case we shouldn't then check for any additional agent host or agent port settings, because they won't be applicable. Instead it should just use the default host/port and not rebuild the agent URL.
This does mean that consumers of the agent URL should handle that it might now start with `unix:` - in practice this only affects one place, `SharedCommunicationObjects` which now uses a placeholder `http://{agent.host}:{agent.port}` for `unix:` URLs. Note this is just to satisfy the OkHttp API, the actual communication will be tunnelled over UDS.
The other updates were to a couple of …

Preserve `unix:` agent URLs

---

dd-trace-ot/src/main/java/datadog/opentracing/resolver/DDTracerFactory.java

This fixes CI failures involving `DDTracerResolverTest` that occurred since #7093 was merged.
`opentracing-tracerresolver` 0.1.5 added a new way to supply tracers, `TracerFactory` - this is checked before `TracerResolver` so we should provide our own `TracerFactory` to supply our tracer, like in `DDTracerResolver`.

Add a TracingFactory (since opentracing-tracerresolver 0.1.5) which resolves our tracer

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationAcceptor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerProductChangesListener.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerProductChangesListenerTest.java

Send probe diagnostic messages when an error occurred during config deserialization (compatibility issue, unsupported feature, malformed json, parsing bug)
Report error to the user
Jira ticket: [DEBUG-2418]
[DEBUG-2418]: https://datadoghq.atlassian.net/browse/DEBUG-2418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Report exception when deserializing config

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/Where.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/ClassFileLines.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/WhereTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/ClassFileLinesTest.java
dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot07.java

Multiple methods can match a line if inline lambdas are defined on the same line.
we need to collect all methods associated to a line and pick one. Here the first which will be the enclosing method
ClassFileLines now collect all methods for a same line
line probe on line 3
```
1  private int multiLambda(String arg) {
2    return (int)Arrays.stream(arg.split(","))
3        .map(s -> s.toUpperCase()).filter(s -> s.startsWith("FOO"))
4        .count();
5  }
```
throws:
```
Cannot transform:  [exception:java.lang.ArrayIndexOutOfBoundsException: Index 62 out of bounds for length 21. 
at org.objectweb.asm.ClassReader.readLabel(ClassReader.java:2695) 
at org.objectweb.asm.ClassReader.createLabel(ClassReader.java:2711) 
at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1853)
at …
```

Fix line probe in method with inline lambdas

---

buildSrc/build.gradle.kts
buildSrc/call-site-instrumentation-plugin/build.gradle.kts
buildSrc/src/test/groovy/CallSiteInstrumentationPluginTest.groovy
buildSrc/src/test/groovy/InstrumentPluginTest.groovy
gradle/dependencies.gradle

Supports transforming Java 23 bytecode
Changes since last update:
* Update ASM and introduce support for Java 23.
* Allow attaching from root on J9.
* Adjust type validation to accept additional names that are legal in the class file format.
* Fix dynamic attach on Windows when a service user is active.
* Avoid failure when using Android's strict mode.
Also updates the ASM dependencies in our build to 9.7 to match

Bump byte-buddy to 1.14.16

---

.circleci/config.continue.yml.j2

The weekly gradle cache build has been failing for many weeks with GC issues.
This PR bumps the heap by 512m so we get a successful cache build, which should reduce the resources needed by subsequent builds.

Bump heap by 512m for the weekly cache job

---

dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java

Avoids misleading `agent_error` statuses when the simple `host:port` check fails, but UDS would have succeeded. 
Jira ticket: [APMJAVA-1147]
[APMJAVA-1147]: https://datadoghq.atlassian.net/browse/APMJAVA-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve agentServiceCheck to handle scenarios where the tracer is configured to use UDS

---

dd-java-agent/agent-bootstrap/src/main/resources/META-INF/native-image/com.datadoghq/dd-java-agent/reflect-config.json
dd-trace-core/build.gradle
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/TracingConfigPoller.java
internal-api/src/main/java/datadog/trace/api/DynamicConfig.java

The approach take here is to cache the original JSON that was parsed into the rules, for both the original static config and any updates to the dynamic config. This required a custom Moshi adapter to capture the raw JSON before it was parsed, but it was simpler than trying to reconstruct the JSON from the rule objects and more consistent with what we were sent.
Jira ticket: [APMAPI-78]
[APMAPI-78]: https://datadoghq.atlassian.net/browse/APMAPI-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Report updated `trace.sampling.rules` to telemetry

---

dd-java-agent/instrumentation/spark-executor/build.gradle
dd-java-agent/instrumentation/spark/spark_2.13/build.gradle

* Limit Spark tests to 3.x.
```
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
[...]
Caused by: java.lang.UnsupportedClassVersionError: org/apache/spark/sql/SparkSession has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[...]
```

Skip tests for Spark 4.x

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfig.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecDataDeserializerSpecification.groovy
dd-java-agent/appsec/src/test/resources/rules_with_data_config.json

Fix parsing of IP denylist in remote configuration when an expiration date does not fit an integer.
https://github.com/DataDog/dd-trace-java/pull/5888 changed JSON deserialization, breaking parsing denylists with expiration dates not fitting an integer. This leads to remote configuration updates failing with the following error in that case:
```
[dd.trace 2024-05-30 14:02:26:998 +0000] [dd-remote-config] WARN datadog.remoteconfig.state.ProductState - Error processing config key datadog/152608/ASM_DATA/blocked_ips/9fac00de04816f5c402a0bc5d4e649758e0d3a5246c9ae3b9b7a5a8f6af99721: Expected an int but was 3676668445 at path $.rules_data[0].data[1].expiration (Will not log warnings for 5 minutes)
com.squareup.moshi.JsonDataException: Expected an int but was 3676668445 at path …
```

Fix IP denylist parsing when expiration date does not fit an integer

---

dd-java-agent/instrumentation/jetty-11/src/test/groovy/HttpChannelAppSecTest.groovy
dd-java-agent/instrumentation/jetty-common/src/main/java/datadog/trace/instrumentation/jetty9/DelayCertainInsMethodVisitor.java
dd-java-agent/instrumentation/jetty-common/src/main/java/datadog/trace/instrumentation/jetty9/HandleVisitor.java

Updates `HandleVisitor` used to instrument `HttpChannel` for blocking purposes in jetty, after version 11.16.0 the original code slightly changed causing a failure in the visitor and a warning message. Blocking was still working thanks of the instrumentation done in `DispatchableInstrumentation`, this just effectively removes the logger error and allows to block the request earlier.
The instrumentation done by `HandleVisitor` is required to provide blocking capabilities in jetty.
https://github.com/jetty/jetty.project/commit/9e16d81cf8922c75e3d2d96c66442b896a9c69e1
Jira ticket: [APPSEC-52394]
[APPSEC-52394]: https://datadoghq.atlassian.net/browse/APPSEC-52394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix HandleVisitor instrumentation for jetty >= 11.16.0 (avoids logged error)

---

dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/QueuedCommandInstrumentation.java
dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/AbstractClientStreamInstrumentation.java
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/TaskUnwrappingInstrumentation.java

Context propagation in gRPC interactions is incomplete because gRPC flows are complex, and instrumenting `ClientStreamListener` is enough for tracing. For profiling, we need to propagate the trace down to the channel level, which is managed by pushing commands to a write queue. This change takes the active span from the `ClientStreamListener` (for convenience, the span is embedded in the listener and it's just activated here to ensure later operations pick the span up) when a client stream is started, and propagate it into the `WriteQueue` with the `WriteQueue$Command`. We also time how long the command waits before being run, so we can highlight delays, head of line blocking and so on.
For context, the relevant code in `WriteQueue`:
1. `enqueue`
```java
ChannelFuture …
```

extend gRPC context propagation into `WriteQueue`, add queue timing to `WriteQueue` commands

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/KnownAddresses.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/data/KnownAddressesSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/api/gateway/Events.java
internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java
internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java

This PR introduces support for SQL capturing which can be used for detecting SQL injection attacks, e.i. added ability to collect data for `server.db.system` and `server.db.statement`  addresses via instrumentation gateway with subsequent forwarding to RASP (ex-WAF).
* `server.db.system` - sql dialect (mysql, postgresql, etc.)
* `server.db.statement` - raw sql-query to check for sql-injection attacks
This PR is part of ASM Exploit Prevention initiative (Runtime application self-protection).
The current set of dialects supported is:
* mysql
* sqlite
* pgsql
Jira ticket: [APPSEC-47228]
[APPSEC-47228]: https://datadoghq.atlassian.net/browse/APPSEC-47228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added support for SQLi exploit prevention

---

dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

Adds a detailed debugging mode for the profiler to diagnose when the tracer sets zero span context unexpectedly.

Add detailed debug logging for tracing/profiler context integration

---

dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/backpressure/BackpressureProfiling.java
dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/backpressure/BackpressureSampleEvent.java
dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/backpressure/BackpressureSampler.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RejectedExecutionHandlerInstrumentation.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

This emits a custom JFR event with the name of the rejected execution handler type and the name of the user's code when execution is rejected. Emission of these events is controlled by a PID controller with the same parameters as the exception profiler. The feature is disabled by default, and given the structure of the project (in particular with respect to JDK8 + JFR), unit testing this feature is difficult. I would like to merge the change as is and iterate on it on internal systems, and undergo the rigmarole of unit tests before enabling it by default.
Show task rejection in the profiling timeline and Code Hotspots.
Jira ticket: [PROF-9882]
[PROF-9882]: https://datadoghq.atlassian.net/browse/PROF-9882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …

emit rate limited JFR events when RejectedExecutionHandlers run

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/ASMHelper.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java

Verify that where the metric is inserted, the local variable that we
try to access is in scope (from the LocalVariableTable)
We are doing this for CapturedContext now we add this for metrics to avoid having a VerifyError raised because the variable is not accessible or reused with another type than expected.
avoid VerifyError exception when loading the instrumented class
Jira ticket: [DEBUG-2400]
[DEBUG-2400]: https://datadoghq.atlassian.net/browse/DEBUG-2400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ensure locals are in scope when generating metrics

---

dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientResponseTracingHandler.java
dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientResponseTracingHandler.java

Avoid finishing the parent span when `channelInactive` is called. 
Jira ticket: [APMS-12066]
[APMS-12066]: https://datadoghq.atlassian.net/browse/APMS-12066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

netty client: don't finish parent span

---

dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/OtelContext.java
dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/trace/OtelSpanBuilder.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryInstrumentation.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OpenTelemetryContextInstrumentation.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OpenTelemetryContextStorageInstrumentation.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy

Uses a thread-local to track the last propagated context from OpenTelemetry that isn't already captured on the scope stack.
This is a short-term solution while we rework how we track context in the Java tracer.
It assumes that the propagated context will be used to build a span before any other span is activated on that thread.
Jira ticket: [APMAPI-104]
[APMAPI-104]: https://datadoghq.atlassian.net/browse/APMAPI-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Track OpenTelemetry propagated context

---

dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/OtelContext.java
dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/OtelScope.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/ContextTest.groovy

Records custom OpenTelemetry context (keys and values) as adjacent entries in a simple array.
When a context associated with an agent span is activated (made current) we cache any custom entries in the wrapped agent scope. This lets us retrieve previous context entries later on in the lifetime of the scope without having to maintain a separate stack of OpenTelemetry contexts.
This is a short-term solution while we rework how we track context in the Java tracer.
Jira ticket: [APMAPI-105]
[APMAPI-105]: https://datadoghq.atlassian.net/browse/APMAPI-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support custom OpenTelemetry context

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/report/AppSecEvent.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy

Added `spanId` in AppSec events. It points to the span where the AppSec detected malicious data.
This is preparation work for stack trace reporting in Exploit prevention initiative (RASP)
Jira ticket: [APPSEC-46818]
[APPSEC-46818]: https://datadoghq.atlassian.net/browse/APPSEC-46818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SpanId in reported AppSec events

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Added configs for stack trace collection for the Exploit Prevention (RASP)
This is preparation work for stack trace reporting in Exploit prevention initiative (RASP)
Jira ticket: [APPSEC-46818]
[APPSEC-46818]: https://datadoghq.atlassian.net/browse/APPSEC-46818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added config for stack trace collection

---

dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/trace/OtelConventions.java
dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/trace/OtelSpanBuilder.java
dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14ConventionsTest.groovy

Translates the `http.response.status_code` attribute (OpenTelemetry) to `http.status_code` (Datadog)
This PR also fixes an issue where the `AttributeKey` form of the `setAttribute` method was not covered for non-array reserved attributes.

Ensure manually created OpenTelemetry spans are compliant with trace metrics

---

static-analysis.datadog.yml

* Disable some rules that are considered fine in our codebase.
* Disable all rules for `src/test` and `src/jmh`, since the results are generally irrelevant there.
Reduce noise in Static Analysis results.

Tune static analysis rules

---

dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/ExtensionFinder.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExtensionHandler.java

This is a performance improvement to avoid re-mapping OpenTelemetry class files even when the surrounding `URLConnection` request is different (for example byte-buddy may repeatedly access the advice class while applying it to different types.)
The shared cache can be small because extension requests are typically localized - in other words we are more likely to get a repeated sequence of requests involving the same advice class, than random requests over all classes in the extension.
Jira ticket: [APMAPI-6]
[APMAPI-6]: https://datadoghq.atlassian.net/browse/APMAPI-6?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rework the bytecode cache for extensions so it works across connections

---

dd-java-agent/instrumentation/spring-messaging-4/src/test/groovy/listener/Config.groovy

Statically forces the AWS region that's mandatory. On dev laptops can work because of `.aws` directory on the home

Fix spring-messaging tests

---

dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/OtelContext.java
dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/trace/OtelTracerProvider.java

Fix for an issue I found while doing manual testing - the [shim injector](https://github.com/DataDog/dd-trace-java/blob/v1.35.0-RC1/dd-java-agent/agent-otel/otel-tooling/src/main/java/datadog/opentelemetry/tooling/shim/OtelShimInjector.java) used for drop-in support expects the `ROOT` and `INSTANCE` fields to have the OTel type, not our implementation type (all the other reflected fields in the shim have the expected types)
Jira ticket: [APMAPI-6]
[APMAPI-6]: https://datadoghq.atlassian.net/browse/APMAPI-6?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update shim fields to have the types expected by OtelShimInjector

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/VMRuntimeInstrumentation.java
dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Users can now configure the tracer's log level by setting `DD_LOG_LEVEL` in their environment:
```
DD_LOG_LEVEL=WARN
```
They can also use the `-Ddd.log.level` JVM option
Make it easier to apply a tracer log level for all Java tracers running in the same environment.
`DD_TRACE_DEBUG=true` implies a log level of `DEBUG`, but `DD_LOG_LEVEL=DEBUG` does not imply `DD_TRACE_DEBUG` is enabled.
Jira ticket: [AIT-9801]
[AIT-9801]: https://datadoghq.atlassian.net/browse/AIT-9801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support DD_LOG_LEVEL

---

.gitlab-ci.yml

This PR tries to fix two issues of the GitLab CI:
* Avoid publishing release candidates to Sonatype,
* Upload the same artifacts we send to Sonatype as GitHub release assets
Our release process is broken. We ship three different binaires for the same version.
If this works, Maven central and GitHub release should be the same. Only lib-injection will be wrong.
I could not test the pipeline, so it will be test as part of the next release.
Added @randomanderson for review as he might have a better understanding of the whole pipeline and [the GitLab workflow syntax](https://docs.gitlab.com/ee/ci/yaml/#needs).

Avoid publishing RC to Sonatype and upload the right assets to GitHub release

---

.github/workflows/README.md
.github/workflows/add-release-to-cloudfoundry.yaml

This PR adds a GitHub workflow to automate the Cloud Foundry repository update when releasing.
We had too many typo error while doing it manually.
The workflow can only be tested during release.
If it fails, it should not impact production and can be easily recovered by doing the repository update manually.

Add Cloud Foundry release automation

---

dd-java-agent/instrumentation/scala/src/main/java/datadog/trace/instrumentation/scala/ScalaJavaConverters.java
dd-java-agent/instrumentation/scala/src/main/java/datadog/trace/instrumentation/scala/StringContextCallSite.java
dd-java-agent/instrumentation/scala/src/main/java/datadog/trace/instrumentation/scala/StringOpsCallSite.java
dd-smoke-tests/iast-propagation/build.gradle
dd-smoke-tests/iast-propagation/src/main/groovy/GroovyPropagation.groovy
dd-smoke-tests/iast-propagation/src/main/java/JavaPropagation.java
dd-smoke-tests/iast-propagation/src/main/java/datadog/smoketest/springboot/PropagationController.java
dd-smoke-tests/iast-propagation/src/main/java/datadog/smoketest/springboot/SpringbootApplication.java
dd-smoke-tests/iast-propagation/src/main/kotlin/KotlinPropagation.kt
dd-smoke-tests/iast-propagation/src/main/scala/ScalaPropagation.scala
dd-smoke-tests/iast-propagation/src/test/groovy/datadog/smoketest/IastPropagationSmokeTest.groovy
settings.gradle

Removes lambdas and anonymous classes from `datadog.trace.instrumentation.scala.ScalaJavaConverters` and ensures that the new ones are added as helpers.
We started to get telemetry logs regarding an issue with scala call sites due to missing classes:
```
afterInterpolation threw
java.lang.NoClassDefFoundError: datadog/trace/instrumentation/scala/ScalaJavaConverters$1
at datadog.trace.instrumentation.scala.ScalaJavaConverters.lambda$toIterable$0(ScalaJavaConverters.java:12)
at com.datadog.iast.propagation.StringModuleImpl.onStringFormat(StringModuleImpl.java:526)
at datadog.trace.instrumentation.scala.StringContextCallSite.afterInterpolation(StringContextCallSite.java:28)
at [redacted: 65 frames]
at datadog.trace.instrumentation.spray.SprayHelper$$anonfun$wrapRoute$1.apply(SprayHelper.scala …
```

Removed scala converter lambdas and ensure they are added as helpers

---

dd-java-agent/instrumentation/log4j2/logs-intake/src/main/java/datadog/trace/instrumentation/log4j2/LoggerConfigInstrumentation.java

Fixes agentless log submission for Log4j2: some Log4j versions require appenders to be started explicitly before they can be used. Otherwise log messages forwarded to an appender that is not started are ignored.
Also adds a check that prevents multiple Datadog appenders from being added to the same logging config.
Jira ticket: [CIVIS-10104]
[CIVIS-10104]: https://datadoghq.atlassian.net/browse/CIVIS-10104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Start Datadog appender when doing agentless log submission for Log4j2

---

internal-api/src/main/java/datadog/trace/api/Config.java

These direct uses of `Config.agentUrl` were missed in #7094
This PR fixes them the same way we fixed uses of `Config.getAgentUrl()` in the original PR; i.e. when using UDS any endpoint using `Config.agentUrl` directly rather than `SharedCommunicationObjects` should use a placeholder of `http://${agentHost}:${agentPort}` instead of `unix:...` to satisfy OkHttp's `HttpUrl.get`. 
This is necessary because the `agentUrl` captured in `Config` will now preserve the original connection string, which when using UDS will start with `unix:`. This protocol will be rejected by OkHttp's `HttpUrl.get`, so to satisfy that call we use the above `http:` placeholder - note the actual connection will be tunnelled over UDS, which is why the URL is a placeholder.
Ideally all remote connections to the agent …

Fix debugger batch upload URL when using UDS

---

dd-smoke-tests/iast-propagation/build.gradle

If using version 2.0.0 gradle will fail to lock versions with a messages like:
```
No matching variant of org.spockframework:spock-core:2.2-groovy-3.0 was found. 
The consumer was configured to find sources for use during runtime, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' ...
```

Use kotlin plugin 1.9.24 in iast-propagation

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/OtelEnvironmentConfigSource.java
internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/OtelEnvironmentConfigSourceTest.groovy

Warns when both are set, preferring the Datadog configuration.
Also checks system properties and  OpenTelemetry's optional configuration file.
Jira ticket: [AIT-9801]
[AIT-9800]: https://datadoghq.atlassian.net/browse/AIT-9800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AIT-9801]: https://datadoghq.atlassian.net/browse/AIT-9801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Map OpenTelemetry environment variables to their Datadog equivalents

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/KnownAddresses.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/data/KnownAddressesSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
dd-java-agent/instrumentation/armeria-grpc/src/main/java/datadog/trace/instrumentation/armeria/grpc/server/TracingServerInterceptor.java
dd-java-agent/instrumentation/armeria-grpc/src/test/groovy/ArmeriaGrpcTest.groovy
dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
dd-smoke-tests/appsec/springboot-grpc/src/test/groovy/datadog/smoketest/appsec/AbstractSpringBootWithGRPCAppSecTest.groovy
dd-smoke-tests/appsec/springboot-grpc/src/test/groovy/datadog/smoketest/appsec/ServerMethodTest.groovy
dd-smoke-tests/appsec/springboot-grpc/src/test/groovy/datadog/smoketest/appsec/ServerRequestMessageTest.groovy
dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
dd-smoke-tests/appsec/src/main/groovy/datadog/smoketest/appsec/AbstractAppSecServerSmokeTest.groovy
internal-api/src/main/java/datadog/trace/api/gateway/Events.java
internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java
internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java

Adds a new WAF address named `grpc.server.method` with the FQN of the grpc method
Jira ticket: [APPSEC-51748]
[APPSEC-51748]: https://datadoghq.atlassian.net/browse/APPSEC-51748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add grpc.server.method to WAF addresses with FQN of the grpc method

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/KnownAddresses.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/data/KnownAddressesSpecification.groovy

Added addresses for Server-side request forgery (SSRF) and Local File Inclusion (LFI) exploits
This is part of AM Exploit Prevention initiative

Added addresses for SSRF and LFI exploits

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/ConsumerCoordinatorInstrumentation.java

The `ConsumerCoordinatorInstrumentation` is accessing kafka consumer info through the context store but does not checks for nullity 

Fix NPE when kafka consumer info is not available

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFResultData.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/report/AppSecEvent.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/stack_trace/StackTraceCollection.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/stack_trace/StackTraceEvent.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/util/ObjectFlattener.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/util/ObjectFlattenerSpecification.groovy
dd-java-agent/appsec/src/test/resources/test_multi_config.json

Implemented reporting RASP events and Stack traces.
- Implemented Stack trace generation when WAF returns `generate_stack` action type
- Implemented Reporting Stack traces for exploits (for IAST vulnerabilities and APM exceptions will be implemented later)
- Extended `rule_match` structure to report detected exploits (added support for `resources`, `params` and `db_types`)
- Added `ObjectFlattener` for accurate serialisation of reported data
This is part of Exploit prevention initiative (RASP)
Jira ticket: [APPSEC-46818]
[APPSEC-46818]: https://datadoghq.atlassian.net/browse/APPSEC-46818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Collect and report RASP events (+Stack traces)

---

dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/CiVisibilityGradleListener.java
dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/legacy/GradleUtils.groovy
dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenLifecycleParticipant.java
dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenUtils.java

Updates logic that puts together test session commands for Maven and Gradle builds: system properties are no longer a part of the command.
System properties have no effect on the subset of executed tests (this is usually controlled with specifying tasks and/or profiles).
The downside of including them in session commands is that test session fingerprint may become unstable (if a property value changes from run to run, e.g. contains a path that has branch name in it).
They might also contain sensitive info that we don't want to send to Datadog.
Jira ticket: [SDTEST-454]
[SDTEST-454]: https://datadoghq.atlassian.net/browse/SDTEST-454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Do not include system-properties in test session command tag

---

dd-java-agent/appsec/build.gradle
dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/api/security/ApiSecurityRequestSampler.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecFeatures.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/api/security/ApiSecurityRequestSamplerTest.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy

Move remote configuration config code away from `ApiSecurityRequestSampler` and ensure we are dealing with the removal of configuration files correctly.

Rework the listeners for AMS_FEATURES

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java

This avoids a `ClassNotFoundException` when shutting down native images - the native-image won't contain the `LogsIntakeSystem` class because it wasn't started when the native-image was built, therefore we should avoid trying to shut it down unconditionally.

Only call `shutdownLogsIntake` at shutdown if we called `maybeStartLogsIntake` at startup

---

dd-java-agent/agent-otel/otel-bootstrap/build.gradle
dd-java-agent/agent-otel/otel-bootstrap/src/main/java/datadog/trace/bootstrap/otel/context/StrictContextStorage.java

Replaces the original class with a simple wrapper to avoid missing reference issue on native-image.
The original class is only used for testing purposes when a particular property is set, but native-image follows the reference in `LazyStorage` and attempts to load everything it touches, including some types we are not embedding. This simple replacement fixes this issue.

Swap original StrictContextStorage with simple wrapper when embedding

---

dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14ConventionsTest.groovy

This PR adds more tests about the OpenTelemetry attributes conventions.
This is a follow up from the discussion on #7138

Add more tests about OpenTelemetry attributes conventions

---

.github/workflows/add-release-to-cloudfoundry.yaml

This PR add the missing git configuration to Cloud Foundry release process automation.
I won't backport this fix to 1.35.x branch as it is too late.
It will be tested for 1.36 now.

Add missing git configuration to cloudfoundry automation

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitDataUploaderImpl.java

Suppresses `IllegalStateException` that can be thrown when removing Git data upload shutdown hook.
The Git data upload shutdown hook is needed to make JVM wait before shutting down if Git data upload hasn't had enough time to finish.
If Git data upload finishes while the JVM is running, no shutdown hook is needed.
Which is why the hook is removed when the upload completes.
However, if by the time the upload completes the JVM has already started shutdown, an attempt to remove the shutdown hook will result in exception.
This exception does not indicate any problem and can be annoying for the users, therefore it's best if it is suppressed.
Jira ticket: [CIVIS-10174]
[CIVIS-10174]: https://datadoghq.atlassian.net/browse/CIVIS-10174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

Ignore exception when trying to remove Git data upload shutdown hook during JVM shutdown

---

.gitlab-ci.yml

This PR removes the hardcoded Sonatype login.
Sonatype move from login/password to token authentication.
See https://central.sonatype.org/publish/generate-token/

Fix GitLab deployment to Sonatype

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/AppSecUserEventDecorator.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/AppSecUserEventDecoratorTest.groovy
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFInitializationResultReporter.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
dd-trace-api/src/main/java/datadog/trace/api/EventTracker.java
dd-trace-api/src/test/groovy/datadog/trace/api/EventTrackerTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java

Add new `asm.keep` tag to be able to set `PrioritySampling.USER_KEEP` with `SamplingMechanism.APPSEC`
Current implementation is using `manual.keep` tag to force keep spans, this is not correct as is setting a  `SamplingMechanism.MANUAL `(4) instead of `SamplingMechanism.APPSEC`(5)
Jira ticket: [APPSEC-52909]
[APPSEC-52909]: https://datadoghq.atlassian.net/browse/APPSEC-52909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set _dd.p.dm to -5 for IAST and AppSec spans

---

dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

Enables timeline events by default when JFR profiler is used, which allows for better integration into the timeline.
Jira ticket: [PROF-10003]
[PROF-10003]: https://datadoghq.atlassian.net/browse/PROF-10003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

enable timeline events by default when ddprof disabled

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/ObjectIntrospection.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/data/ObjectIntrospectionSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy

* When converting parsed body or grpc messages, preserve types to the extent that they are supported by libddwaf. Rules that apply only to strings can be skipped for numbers, booleans, etc.
* For anything that is not supported by libddwaf, such as non-string keys in maps, just convert to strings.
* When a key cannot be converted, use `invalid_key:$i` string
* Skip fields that are known to be useless, such as `memoizedHashCode` and `memoizedSize` in protobuf.
Originally motivated by spurious matches of internal protobuf fields, then also realized there are several cases where we are doing unnecessary work. This turns out to be the first of a possible series of performance optimizations.
Jira ticket: [APPSEC-53469](https://datadoghq.atlassian.net/browse/APPSEC-53469)
Future work:
* When an …

Preserve original types before passing data to the WAF

---

.circleci/config.continue.yml.j2

Rename run from `Run APM Integrations tests` to `Run Dynamic Instrumentation system tests`

Rename Dynamic Instrumentation system tests run name

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/AppSecUserEventDecorator.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/AppSecUserEventDecoratorTest.groovy
dd-java-agent/instrumentation/spring-security-5/src/main/java17/datadog/trace/instrumentation/springsecurity5/SpringSecurityUserEventDecorator.java
dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/SpringBootBasedTest.groovy
internal-api/src/main/java/datadog/trace/api/UserEventTrackingMode.java

Updates support of user event tracking to support all functionality from the RFC, specially:
- Use lower case values for the modes included in the spans
- Allow to send user ids when alphanumeric/uuid in the safe mode.
[RFC](https://docs.google.com/document/d/1-trUpphvyZY7k5ldjhW-MgqWl0xOm7AMEQDJEAZ63_Q/edit)

Update missing RFC parts for user event tacking

---

dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java

Also clears `lastParentId` when resetting ContextInterpreter
Jira ticket: [[AIT-9906](https://datadoghq.atlassian.net/browse/AIT-9906)]
[AIT-9906]: https://datadoghq.atlassian.net/browse/AIT-9906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include lastParentId when resetting ContextInterpreter state

---

dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java

clears `propagationTags` when resetting ContextInterpreter.
Jira ticket: [[AIT-9906](https://datadoghq.atlassian.net/browse/AIT-9906)]
[AIT-9906]: https://datadoghq.atlassian.net/browse/AIT-9906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include propagationTags when resetting ContextInterpreter state

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestImpl.java
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/TestImplTest.groovy
dd-trace-core/src/main/java/datadog/trace/civisibility/writer/ddintake/CiTestCovMapperV2.java

Updates code coverage processing logic so that code coverage is not processed/reported for skipped tests.
If a test is skipped, code coverage is likely to be empty or incomplete. The backend has no use for this coverage, at least as of now, so we can save some resources by not processing it and not reporting it.
Jira ticket: [SDTEST-493]
[SDTEST-493]: https://datadoghq.atlassian.net/browse/SDTEST-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Do not report code coverage for skipped tests

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/TaintedObject.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/ObjectGen.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedMapTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedObjectTest.groovy

Add logs to the tainted map `garbage-collected entries are purged` test in order to understand why it might flake under JDK 21.
The test has been observed to fail with no reason in some builds: [example](https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/37529/workflows/b88508d7-a0dc-4304-a38e-9e1d4f38f920/jobs/1362143/tests)

Add logs to tainted map 'garbage-collected entries are purged' flaky test

---

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java

Updates the versions of DD Javac plugin and Jacoco plugin that CI Visibility injects into the traced application's build.
The new versions of the plugins fix various issues.
Jira ticket: [SDTEST-495]
[SDTEST-495]: https://datadoghq.atlassian.net/browse/SDTEST-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update default versions of DD Javac plugin and Jacoco plugin used by CI Visibility

---

.github/workflows/README.md
.github/workflows/add-milestone-to-pull-requests.yaml

This PR fixes the GitHub milestone automation when patch release are opened.
This will fix the behavior for both minor and patch target PRs.
The PRs where randomly affected to either the patch or the minor release milestone.
I tested the workflow using act, a PAT and some event payload file.
It should catch most of the issues...
I also update GitHub script action version.

 Add support for patch release to milestone automation

---

.gitlab-ci.yml

Save the artifacts generated by the deploy to sonatype jobs
The `deploy_artifacts_to_github` job is broken because artifacts are not available

Save sonatype artifacts in Gitlab pipeline

---

.gitlab-ci.yml

Increase CPU and memory assigned to gitlab build jobs. Additionally, unify argument declarations
Speed up the build by giving more resources

Increase memory and CPU for gitlab builds

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/AppSecUserEventDecorator.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/AppSecUserEventDecoratorTest.groovy
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java

Add appsec propagation tag:
- On appsec user event tracking
- On appsec request end  (this is necessary as we can't guarantee right now that the span is available when the event is detected)
JIRA: [APPSEC-10459](https://datadoghq.atlassian.net/browse/APPSEC-10459)
[APPSEC-10459]: https://datadoghq.atlassian.net/browse/APPSEC-10459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add missing appsec propagation tag on appsec events

---

dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy

* Add `/info` and `/telemetry` endpoints to the test agent used in smoke tests.
* Make it closer to a real agent.
* Avoid logs noise from telemetry errors.
* Avoid unnecessary probing for feature discovery, stressing the most usual path with real agent, and reducing noise in logs and debugging.
Possible future work:
* Intercept telemetry messages, this would enable better smoke tests for telemetry.
* Make `/info` responses configurable to test different scenarios.

Add /info and /telemetry endpoints to smoke tests agent

---

dd-smoke-tests/appsec/src/main/groovy/datadog/smoketest/appsec/AbstractAppSecServerSmokeTest.groovy
dd-smoke-tests/spring-boot-2.4-webflux/src/test/groovy/datadog/smoketest/SpringBootWebfluxIntegrationTest.groovy

Use the default trace protocol version (v0.4 at the moment) in smoke tests.
Support for decoding v0.4 in smoke tests agent was added in 2022, we can now just test the default behavior.

Use default trace protocol version in smoke tests

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java

* Always set `appsec.blocked:true` in the local root span.
* In some cases, such as mid-request blocks (e.g. path params, RASP) or certain web frameworks, a block will happen while the active span is not the root span. We use `appsec.blocked` to mark local roots, so make sure we always set the tag there.
Jira ticket: [APPSEC-53857](https://datadoghq.atlassian.net/browse/APPSEC-53857)
[APPSEC-53857]: https://datadoghq.atlassian.net/browse/APPSEC-53857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set appsec.blocked in local root span

---

dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java
dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/AbstractSparkTest.groovy

`DD_SPARK_APP_NAME_AS_SERVICE` also use `spark.app.name` as the default service if service is set to `spark`
USM can auto-infer the service to spark, in this case we still want to use the spark app name as the service
https://datadoghq.atlassian.net/browse/DJM-30
`DD_SPARK_APP_NAME_AS_SERVICE` was introduced in this PR: https://github.com/DataDog/dd-trace-java/pull/6460

Use spark application name when service is set to spark

---

dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java
dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/SparkConfAllowList.java
dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/AbstractSparkTest.groovy

Capture all spark conf properties. Use the `spark.redaction.regex` pattern to redact secret in the same way spark is doing
Also changed capturing the job parameters to only capture those for local root spans
Only capturing a subset meant that important properties for users could be missed
https://datadoghq.atlassian.net/browse/DJM-150

Capture all spark conf parameter

---

.github/workflows/add-milestone-to-pull-requests.yaml

This PR tries to fix a regression from https://github.com/DataDog/dd-trace-java/pull/7217
The workflow is failing to identify `master` branch.
See: https://dd.slack.com/archives/C047YAMGZ7T/p1719847370062669

Fix milestone assignment automation

---

dd-java-agent/instrumentation/jakarta-jms/src/main/java/datadog/trace/instrumentation/jakarta/jms/JMSMessageProducerInstrumentation.java
dd-java-agent/instrumentation/jakarta-jms/src/test/groovy/JMS2Test.groovy
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageProducerInstrumentation.java
dd-java-agent/instrumentation/jms/src/test/groovy/JMS1Test.groovy

The java agent today is not instrumenting jms send for signatures `QueueProducer.send(Queue, Message, ..)` or `TopicPublisher.send(Topic, Message)`.
Instead, we trace `MessageProducer.send(Destination, Message, ..)` only. 
This is generally OK when specialized classes are delegating to superclasses. In fact for ActiveMQ we have
```
public class ActiveMQQueueSender extends ActiveMQMessageProducer implements QueueSender {
....
public void send(Queue queue, Message message) throws JMSException {
super.send(queue, message);
}
```
But it's not OK when the specialized class does not delegate to super. Hence we lost the tracing on the producer.

JMS: trace Queue and Topic producers when destination is explicit

---

communication/src/main/java/datadog/communication/monitor/DDAgentStatsDClient.java
communication/src/main/java/datadog/communication/monitor/LoggingStatsDClient.java
dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/OOMENotifier.java
internal-api/src/main/java/datadog/trace/api/StatsDClient.java

Follow-up to #10025 to move the `recordEvent` to `StatsDClient` interface
Jira ticket: [PROF-10025]
[PROF-10025]: https://datadoghq.atlassian.net/browse/PROF-10025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Move 'recordEvent' method to StatsDClient interface

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
internal-api/src/main/java/datadog/trace/api/profiling/ProfilingEnablement.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
internal-api/src/test/java/datadog/trace/api/profiling/ProfilingEnablementTest.java

Adds a support for a new state `auto` for `profiling.enabled` config option.
For SSI (Single Step Instrumentation) a new state for the profiler enablement was added - 'auto'.
The enablement used to be a boolean flag, so the only supported values were `true` and `false` , regardless of the case.
Therefore, a specific support for `auto` must be added.
Since the 'auto' activation presumes a 'testing' period before enabling profiling (eg. an app must have been running for 10-20 seconds so we don't activate for something like command line utilities) a part of the 'auto' enablement is making sure that the user defined values for the initial delay and 'force-start-first' flag are ignored.
Jira ticket: [PROF-10082]
[PROF-10082]: https://datadoghq.atlassian.net/browse/PROF-10082?atlOrigin=eyJpIjoiN …

PROF-10082: Add support for 'auto' value in DD_PROFILING_ENABLED

---

dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java

Collapses wall samples by default, which avoids unwinding the same stack trace twice

collapse wall samples by default

---

.github/workflows/add-release-to-cloudfoundry.yaml

Fix CloudFoundry repository update automation.
This happens when the generated PR is not merged.

Fix case where past automation branch where not deleted

---

.circleci/config.continue.yml.j2
build.gradle
buildSrc/src/main/kotlin/datadog.dependency-locking.gradle.kts
gradle/java.gradle

This PR moves the version locking into a Gradle convention plugin as `subprojects` and `allprojects` [must be avoid for shared project configuration](https://docs.gradle.org/current/userguide/sharing_build_logic_between_subprojects.html#sec:convention_plugins_vs_cross_configuration).
It also updates the pinned version before building nightly versions.
Version locking was broken. Nightly build does no more test latest library versions.
Not sure about the CI script update... Can it mess with the cache?

Fix Gradle version locking

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFResultData.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/InstrumentationLogger.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
dd-smoke-tests/appsec/springboot/build.gradle
dd-smoke-tests/appsec/springboot/src/main/java/datadog/smoketest/appsec/springboot/controller/WebController.java
dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
dd-smoke-tests/appsec/src/main/groovy/datadog/smoketest/appsec/AbstractAppSecServerSmokeTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
gradle/spotbugFilters/exclude.xml
internal-api/src/main/java/datadog/trace/api/gateway/Events.java
internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java
internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java

Implemented blocking functionality for the SQL-injection Exploit Prevention.
This is part of Exploit prevention initiative (RASP)
Jira ticket: [APPSEC-46818]
[APPSEC-46818]: https://datadoghq.atlassian.net/browse/APPSEC-46818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Exploit prevention for SQL injection (blocking support)

---

.gitlab/benchmarks.yml
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/Snapshot.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SnapshotSink.java

UUID generation is not cheap, and therefore should be performed only when the snapshot is about to be sent.
Moving UUID generation at seriazliation time makes it out of the critical path.
Performance
Jira ticket: [DEBUG-2346]
[DEBUG-2346]: https://datadoghq.atlassian.net/browse/DEBUG-2346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Move snapshot UUID generation at serialization

---

.gitlab-ci.yml

The gitlab pipeline for scheduled jobs was broken. Gitlab is not smart enough to handle "If B needs A, and A's rule says not to run, don't run B either"
`generate-lib-init-tag-values` didn't run when `POPULATE_CACHE` was set. `deploy-lib-init-trigger` needs to have the same rules.
Gitlab pipeline broken overnight.

Fix reliability env deploy / Gitlab scheduled pipeline

---

dd-java-agent/instrumentation/spring-scheduling-3.1/src/main/java/datadog/trace/instrumentation/springscheduling/SpringSchedulingInstrumentation.java
dd-java-agent/instrumentation/spring-scheduling-3.1/src/main/java/datadog/trace/instrumentation/springscheduling/SpringSchedulingRunnableWrapper.java

This PR rollbacks instrumenting spring scheduling `TaskScheduler` which was wrapping the `Runnable` in each schedule.
This was done as part of #6249  in order to have the right Runnable names displayed on actuator's endpoints. 
Wrapping the runnable on each schedule can cause side effects if a custom task scheduler is used and if inside the `schedule` method `instanceof` is used to check whenever the Runnable is of a certain type since we're wrapping it with `SpringSchedulingRunnableWrapper`. 
In order to be less invasive and, at same time, preserve the right labelling on actuator, I've restored the old approach instrumenting `Task` instead of `TaskScheduler` which was causing that bad behaviour. I've also overridden the `toString` method of `SpringSchedulingRunnableWrapper` in order to …

Spring scheduling: do not wrap runnables on each schedule

---

dd-java-agent/appsec/src/jmh/java/datadog/appsec/benchmark/EventDispatcherBenchmark.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/blocking/BlockingServiceImpl.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/DataListener.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/EventDispatcher.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/EventProducerService.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/ReplaceableEventProducerService.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFStatsReporter.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/AppSecModuleSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/blocking/BlockingServiceImplSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/EventDispatcherSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFStatsReporterSpecification.groovy

Added new span metrics for Exploit prevention:
- `_dd.appsec.rasp.duration` - cumulative runtime in nanoseconds of every call to libddwaf thought a RASP instrumentation with a request
- `_dd.appsec.rasp.duration_ext` - cumulative runtime in nanoseconds of libddwaf call + binginds cost through RASP instrumentation with a request
- `_dd.appsec.rasp.rule.eval` - counts the number of times libddwaf calls per request
This is part of Exploit prevention to let collect useful metrics for future analysis of effectiveness.
Jira ticket: [APPSEC-47228]
[APPSEC-47228]: https://datadoghq.atlassian.net/browse/APPSEC-47228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Report span metrics for Exploit Prevention

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/SerializerWithLimits.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/StringTokenWriterTest.java

We specially serialize collections/maps into snapshot using interfaces and calling methods like `size()` but we restrict this for JDK collections that are guarantee to be only in-memory. For all others we are raising an exception. Instead we should just serialize then as regular object with fields.
https://github.com/DataDog/dd-trace-java/issues/7254
Jira ticket: [DEBUG-2502]
[DEBUG-2502]: https://datadoghq.atlassian.net/browse/DEBUG-2502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Serialize restricted collections as regular object

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java

On same location, if we have different probes like log or span decoration probe with different characteristics (capture, snapshot, evaluateAt,...), instrumentation needs the correct definition to apply
the shared CapturedContextInstrumentor.
We are creating a synthetic definition for applying instrumentation and merging all characteristics required for instrumentation.
Jira ticket: [DEBUG-2498]
[DEBUG-2498]: https://datadoghq.atlassian.net/browse/DEBUG-2498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix mixing log/span decoration probes

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SymbolSink.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/ClassNameFilteringTest.java

Sanitizes env and version in SymbolSink.
We're matching RC tags with these tags, so they have to be sanitized the same way.
https://github.com/DataDog/dd-trace-java/blob/65d7de13ac6a58d949af75fef4e9531bcaed5aab/remote-config/src/main/java/datadog/remoteconfig/PollerRequestFactory.java#L54-L57

Fix service version sanitize tags

---

dd-java-agent/appsec/src/jmh/java/datadog/appsec/benchmark/EventDispatcherBenchmark.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/blocking/BlockingServiceImpl.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/DataListener.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/EventDispatcher.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/EventProducerService.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/ReplaceableEventProducerService.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/AppSecModuleSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/blocking/BlockingServiceImplSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/EventDispatcherSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy

Introduced GatewayContext. It used to describe instrumentations data traits that are passes through the InstrumentationGateway. Currently, each instrumentation data has:
- `isTransient` - to identify if the data is ephemeral or persistent within the request
- `isRasp` - to identity data origin for Exploit Prevention
This is part of Exploit prevention to let provide `ruleType` for the RASP instrumentations.
Jira ticket: [APPSEC-47228]
[APPSEC-47228]: https://datadoghq.atlassian.net/browse/APPSEC-47228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Introduce GatewayContext to propagate instrumentation specific traits

---

dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java
dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/AbstractSparkTest.groovy

`DD_SPARK_APP_NAME_AS_SERVICE` also use spark.app.name as the default service if service is set to `hadoop`
USM can auto-infer the service to hadoop, in this case we still want to use the spark app name as the service
Follow up of: https://github.com/DataDog/dd-trace-java/pull/7252

Use spark application name when service is set to hadoop

---

dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/CiVisibilityGradleListenerInjector.java
dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleBuildScopeServicesInstrumentation.java

Fixes Gradle instrumentation following release v8.9
Previous version of the code used `org.gradle.internal.service.DefaultServiceRegistry#addProvider(Object)` method to register CI Visibility plugin.
In Gradle v8.9 this method was replaced with `org.gradle.internal.service.DefaultServiceRegistry#addProvider(org.gradle.internal.service.ServiceRegistrationProvider)`.
The new `ServiceRegistrationProvider` interface is introduced in Gradle v8.9.
The fixed version of the code uses alternative service registration method which works both in v8.9 and in older versions.
Jira ticket: [SDTEST-566]
[SDTEST-566]: https://datadoghq.atlassian.net/browse/SDTEST-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Gradle v8.9 instrumentation

---

dd-java-agent/agent-profiling/profiling-controller-ddprof/src/main/java/com/datadog/profiling/controller/ddprof/DatadogProfilerSettings.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/JfrProfilerSettings.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilerSettingsSupport.java

It captures the values from settings related to auto-injection in the JFR recording.
Make the debugging of service with auto-injected and auto-enabled functionality like profiling.
Jira ticket: [PROF-10157]
[PROF-10157]: https://datadoghq.atlassian.net/browse/PROF-10157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Capture the auto-injection related settings in JFR recording

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/DebuggerSink.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/ProbeStatusSink.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SnapshotSink.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SymbolSink.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ProbeInstrumentationTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/SnapshotSinkTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/TestSnapshotListener.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java
internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java

We introduce a dedicated high rate queue with dedicated threads with better reactivity (max 100ms between polls). All non-capturing snapshots are added into this queue.
Historically, the Queue inside SnapshotSink was designed for a low rate number of snapshots (1 per second) and the consumer thread is the one shared with all other tasks (AgentTaskScheduler.INSTANCE). So the reactivity of the thread to consume the queue is not enough for handling up to 5000 snapshots/s allowed for log template probes. 
Jira ticket: [DEBUG-2499]
[DEBUG-2499]: https://datadoghq.atlassian.net/browse/DEBUG-2499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add high rate queue for log template snapshots

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java

Reset call depth counter in `StatementInstrumentation` if query with SQL-injection is blocked.
In case of multiple blocking of sql queries, an error occurred leading to blocking failure
Jira ticket: [APPSEC-47228]
[APPSEC-47228]: https://datadoghq.atlassian.net/browse/APPSEC-47228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reset call depth counter if query is blocked

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Evidence.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Range.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Source.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/EvidenceTest.groovy

Creates new ranges without weak references for evidences in vulnerabilities
Before the vulnerability is written to the span in the end of the request, there's still the chance that the original value is GCed causing flaky tests in our pipelines.

Create new ranges for vulns to prevent GC issues

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/CodecModuleImpl.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/CodecModuleTest.groovy
dd-java-agent/instrumentation/java-net/src/main/java/datadog/trace/instrumentation/java/net/URICallSite.java
dd-java-agent/instrumentation/java-net/src/main/java/datadog/trace/instrumentation/java/net/URLCallSite.java
dd-java-agent/instrumentation/java-net/src/main/java/datadog/trace/instrumentation/java/net/URLEncoderCallSite.java
dd-java-agent/instrumentation/java-net/src/test/groovy/datadog/trace/instrumentation/java/net/URICallSIteTest.groovy
dd-java-agent/instrumentation/java-net/src/test/groovy/datadog/trace/instrumentation/java/net/URLCallSiteTest.groovy
dd-java-agent/instrumentation/java-net/src/test/groovy/datadog/trace/instrumentation/java/net/URLEncoderCallSiteTest.groovy
dd-java-agent/instrumentation/okhttp-2/src/test/groovy/IastOkHttp2InstrumentationTest.groovy
dd-java-agent/instrumentation/okhttp-3/src/test/groovy/IastOkHttp3InstrumentationTest.groovy
dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
internal-api/src/main/java/datadog/trace/api/iast/propagation/CodecModule.java

Updates the URL and URI call sites to ensure that we keep tracking of the different ranges on a best effort basis.
SSRF vulnerability has different scores depending on the part of the url that is coming from an external source (e.g. the host is the most important part to track as it gives big room for attacks).
Jira ticket: [APPSEC-53838]
[APPSEC-53838]: https://datadoghq.atlassian.net/browse/APPSEC-53838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update URI and URL call sites for precise taint tracking

---

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/HasAllExpression.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/HasAnyExpression.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/IndexExpression.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/IsEmptyExpression.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/LenExpression.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/StringPredicateExpression.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/ContainsExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/EndsWithExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/HasAllExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/HasAnyExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/IndexExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/IsEmptyExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/LenExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/MatchesExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/StartsWithExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/resources/null_expressions.txt

Change behavior to send evaluation error when value is null for
- len/count
- hasAny
- hasAll
- isEmpty
- index
- string predicates (startsWith, endsWith, contains, matches)
Conformance with other client libraries
Jira ticket: [DEBUG-2487]
[DEBUG-2487]: https://datadoghq.atlassian.net/browse/DEBUG-2487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix EL function behavior for null values

---

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/JsonToExpressionConverter.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ValueScriptTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_one_liner_value_expr_01.txt
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_one_liner_value_expr_02.txt
dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_value_expr_01.json

Add `instanceof` among the predicate functions when parsing value expressions.
Add test for parsing top level value expressions
Jira ticket: [DEBUG-2527]
[DEBUG-2527]: https://datadoghq.atlassian.net/browse/DEBUG-2527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix `instanceof` as predicate for value expression

---

dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/CiVisibilityGradleListenerInjector.java
dd-java-agent/instrumentation/gradle/src/main/groovy/datadog/trace/instrumentation/gradle/GradleBuildScopeServicesInstrumentation.java

Fixes Gradle instrumentation following release v8.9
Previous version of the code used `org.gradle.internal.service.DefaultServiceRegistry#addProvider(Object)` method to register CI Visibility plugin.
In Gradle v8.9 this method was replaced with `org.gradle.internal.service.DefaultServiceRegistry#addProvider(org.gradle.internal.service.ServiceRegistrationProvider)`.
The new `ServiceRegistrationProvider` interface is introduced in Gradle v8.9.
The fixed version of the code uses alternative service registration method which works both in v8.9 and in older versions.
Jira ticket: [SDTEST-566]
[SDTEST-566]: https://datadoghq.atlassian.net/browse/SDTEST-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[🍒 7319] Fix Gradle v8.9 instrumentation

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/LogContextScopeListener.java
dd-java-agent/cws-tls/src/main/java/datadog/cws/tls/TlsScopeListener.java
dd-java-agent/cws-tls/src/test/groovy/datadog/cws/tls/TlsTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScope.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
internal-api/src/main/java/datadog/trace/api/scopemanager/ExtendedScopeListener.java

This PR reduces the API of the `ExtendedScopeListener`.
It also replaces the implementation of the `LogContextScopeListener` to use the common `CorrelationIdentifier` that already support 128-bit TID correlation.
Limit the internal API to what’s needed.
Now, only CWS-TLS needs the `ExtendedScopeListener`.
I kept it for performance reason as it needs ID using the `long` form.

Reduce scope listener API

---

dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterTest.groovy

Changes `TraceProcessingWorker#serializerThread` to always be a daemon thread (before the changes the thread was started as non-daemon if CI Visibility was enabled).
This thread runs an infinite loop, polling traces that are ready to be processed.
If it is not daemon the JVM will never exit, unless the thread is interrupted or `System#exit` is called.
Maven and Gradle do the latter, which is why the builds do not hang.
However, if CI Visibility is enabled in an app that does not call `System#exit`, the tracer will never exit.
The easiest way to reproduce is tracing something simple like `java -version`.
The reason for making this thread non-daemon was to allow it to flush all the pending traces before the build finishes.
However, this is redundant because the tracer shutdown sequence …

Fix tracer freeze when CI Visibility is enabled

---

.github/workflows/update-gradle-dependencies.yaml

This PR should fix the workflow that automates the dependency lock update.
Workflow failed to create commit and PR.

Fix dependency lock update workflow

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/messaging/DatadogAttributeParser.java
dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/SqsClientTest.groovy
dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/SqsClientTest.groovy

The binary data we receive when the data type is marked as binary is not base64, it's the string itself, so we don't need to decode it.
Jira ticket: AIDM-205

Fix parsing of binary datadog headers in SQS

---

dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/HasAllExpression.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/HasAnyExpression.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/HasAllExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/HasAnyExpressionTest.java

Jira ticket: [DEBUG-2488]
[DEBUG-2488]: https://datadoghq.atlassian.net/browse/DEBUG-2488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `Set` support for `hasAny`/`hasAll` expression

---

dd-java-agent/agent-logging/build.gradle
dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LogReporter.java
dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/PrintStreamWrapper.java
dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatSettings.java
dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/simplelogger/SLCompatSettingsTest.groovy
dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java
dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlareService.java

Collect tracer logs in a tracer log file in the tracer flare:
Changes:
- handle the case when no tracer log file is configured in the tracer configuration and we're able to create a temporary log file to collect the logs
- move the logic when a tracer log file is configured from TracerFlareService.java to LogReporter.java to avoid having multiple locations for handling the tracer log in tracer flare depending on the use cases
Note that:
- Use case when no tracer log file is configured in the tracer configuration and we're not able to create a temporary log file to collect the logs is not supported right now ( tracer.log file generated but no tracer logs inside)
- Use case when no tracer log file is configured  and the tracer flare is requested by Remote Config without DEBUG log level will …

Add tracer log file to tracer flare when datadog.slf4j.simpleLogger.logFile is NOT defined 

---

.gitlab-ci.yml
.gitlab/benchmarks.yml
.gitlab/macrobenchmarks.yml

Add k6 + petclinic macrobenchmark that measures:
* CPU and RSS Usage;
* JVM internal metrics like young cycles, old gen size, metaspace size, etc.;
* Latency;
* Throughput.
The benchmark runs on every master branch commit automatically, and manually runnable on PR branches.
There are 3 variants at the moment:
* baseline -- uninstrumented application;
* only-tracing -- application instrumented with DD Java agent;
* otel-latest -- application instrumented with latest OTel agent.
Add performance testing coverage for JVM metrics and CPU / RSS usage in case of simple macrobenchmarks.
The work is based on @nayeem-kamal 's original ben-runner petclinic macrobenchmark, but couple of things were changed:
* Instead of H2 database, PostgreSQL is used;
* Warmup phase was added;
* The benchmark was …

Add k6 + petclinic macrobenchmark

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/WellKnownClasses.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/DSL.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/JsonToExpressionConverter.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/PrettyPrintVisitor.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/ContainsExpression.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/CollectionValue.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/ListValue.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/MapValue.java
dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/values/SetValue.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/ProbeConditionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/ContainsExpressionTest.java
dd-java-agent/agent-debugger/debugger-el/src/test/resources/contains_expressions.txt

Add support for array/list/map/set of the `contains` EL expression when calling `contains` on array/list or set it will iterate on all elements to find it. On Maps we are using the `containsKey` method.
Jira ticket: [DEBUG-2488]
[DEBUG-2488]: https://datadoghq.atlassian.net/browse/DEBUG-2488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extend `contains` EL expression

---

.gitlab-ci.yml

Fixes the github artifact upload by using explicit file names
The previous way of using `*.jar` is broken because there are `-source.jar` and `-javadoc.jar` when using artifacts from the `deploy_to_sonotype` job. We know the exact name of the files because it is only run when there is an explicit `CI_COMMIT_TAG` set.

Fix github artifact upload using explicit jar names

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
dd-java-agent/agent-debugger/debugger-bootstrap/src/test/java/datadog/trace/bootstrap/debugger/DebuggerContextTest.java

break in switch was missing generating an exception each time
Jira ticket: [DEBUG-2569]
[DEBUG-2569]: https://datadoghq.atlassian.net/browse/DEBUG-2569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix exception thrown for distribution metric

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/AppSecUserEventDecorator.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/AppSecUserEventDecoratorTest.groovy
dd-java-agent/instrumentation/spring-security-5/src/main/java17/datadog/trace/instrumentation/springsecurity5/SpringSecurityUserEventDecorator.java
dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/SpringBootBasedTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/api/UserIdCollectionMode.java
internal-api/src/main/java/datadog/trace/api/telemetry/WafMetricCollector.java
internal-api/src/main/java/datadog/trace/util/Strings.java
internal-api/src/test/groovy/datadog/trace/api/ConfigCollectorTest.groovy
internal-api/src/test/groovy/datadog/trace/api/UserIdCollectionModeTest.groovy
internal-api/src/test/groovy/datadog/trace/api/telemetry/WafMetricCollectorTest.groovy
internal-api/src/test/groovy/datadog/trace/util/StringsTest.groovy

Applies the new erratum/addendum of automated user events trancking. The new RFC defines three different modes based on the env `DD_APPSEC_AUTO_USER_INSTRUMENTATION_MODE`
- `identification` (by default) user ids are sent the backend without any modification
- `anonymization` user ids are hashed with SHA256
- `disabled` auto user event tracking is disabled
This new option deprecates `DD_APPSEC_AUTOMATED_USER_EVENTS_TRACKING`, the deprecated option will be automatically converted to the new schema following the next table:
| DD_APPSEC_AUTOMATED_USER_EVENTS_TRACKING |  DD_APPSEC_AUTO_USER_INSTRUMENTATION_MODE |
|---|---|
|`extended`|`identification`|
|`safe`|`anonymization`|
|`disabled`|`disabled`|
Tracking of real user ids is very important for the detection of account take over campaigns, …

Use three modes for auto user id collection: identification (default), anonymization and disabled

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/CachingJvmInfoFactory.java
dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenLifecycleParticipant.java

Updates Maven instrumentation logic that determines JVM used for tests execution.
If the JVM could not be determined, current JVM (the one running the parent Maven process) is assumed. 
The previous logic did not work correctly because the cache used for storing resolved JVMs does not support `null` keys (and `null` was used to indicate that JVM path could not be determined).

Fix null JvmInfo exception in Maven instrumentation

---

.github/workflows/update-gradle-dependencies.yaml

This PR should fix the gradle dependency automation by creating signed commit.
It also brings permissions configuration for the coming permission limitation.
The original solution was creating non-signed commits that can't be merged 😞 
This uses a rather complicated setup that leverages a CLI tool to make GraphQL calls to create commits on a remote branch.
As the new file content must be (base64) encoded and added to the GraphQL mutation query payload, I had to:
* split the changes into multiple commits, 
* fetch the new commits sha in order to keep adding child commits.
Then, create a PR using another CLI to target master from the built branch.

Fix Gradle dependency automation

---

.github/workflows/add-milestone-to-pull-requests.yaml

This PR fixes some issues how the CI retrieves the milestone to assign to PRs.
When multiple milestones are open, it (obviously) picks the wrong one 😞 

Fix milestone parsing for PR assignment

---

dd-java-agent/instrumentation/aws-java-sns-1.0/src/test/groovy/SnsClientTest.groovy
dd-java-agent/instrumentation/aws-java-sns-2.0/src/test/groovy/SnsClientTest.groovy

Fixes flaky sns test by removing order check for `edgeTags`

Fix SNS tests to not test for order of tags

---

.github/workflows/add-release-to-cloudfoundry.yaml

This PR automates the Cloud Foundry repository update.
It won't use PR anymore but push a commit with the update as soon as the release is available on Maven Central.
Previously, it created a PR with a non-signed commit.
I decided to go for the final version right now and directly create commit (now signed) to the `cloudfoundry` branch. 
A new GitHub actions was allowed in the repository settings in order to create signed commit using the GitHub GraphQL API.

Automate Cloud Foundry repository update

---

dd-java-agent/cws-tls/src/main/java/datadog/cws/tls/ErpcTls.java
dd-java-agent/cws-tls/src/main/java/datadog/cws/tls/NoTls.java
dd-java-agent/cws-tls/src/main/java/datadog/cws/tls/TlsScopeListener.java
dd-java-agent/cws-tls/src/test/groovy/datadog/cws/tls/ErpcTlsTest.groovy
dd-java-agent/cws-tls/src/test/groovy/datadog/cws/tls/TlsTest.groovy

It switches used trace IDs to 128 bits.
Be compliant with the new tracer

Switch to 128-bit trace ID tracking

---

.github/pull_request_template.md

Fixes the links in the pull request template
The relative links don't work in the pull request even though the work correctly when browsing to `.github/pull_request_template.md` . You can see them broken in the Contributor Checklist below. This PR uses the full URL to CONTRIBUTING.md

Fix links in pull request template

---

.gitlab-ci.yml
.gitlab/macrobenchmarks.yml

Fixes the schedule deploy:
* The previous `SKIP_SHARED_PIPELINE: $POPULATE_CACHE` variable assignment doesn't work. It needs to be done as a workflow rule
* The `macrobenchmarks` and `deploy_to_sonatype` jobs depended on `build` which was not available during nightly jobs
Additionally:
* I changed the nightly to run `build` in addition to `build_with_cache` so any dependency issues won't bork the build in the future
The nightly deploy has been broken for months despite occasional efforts to fix it
I tested this be creating a scheduled job with `POPULATE_CACHE=true` and ensuring everything works as expected

Fix nightly deploys

---

dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
dd-java-agent/agent-crashtracking/src/test/java/com/datadog/crashtracking/CrashUploaderTest.java

Adds tags section to the crashtracking telemetry payload such that it is recognized by the crashtracking.
Jira ticket: [PROF-10230]
[PROF-10230]: https://datadoghq.atlassian.net/browse/PROF-10230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add severity tag to crash upload

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java
dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Add parameter `dd.data.jobs.command.pattern` to only inject the tracer on specific command pattern for Data Jobs
In the context of Data Jobs Monitoring, change the Java tracer to become more selective about which Java process to instrument when Data Jobs is enabled and a Java command regex pattern is specified. In runtime environment where we are not sure the command pattern to use, the java tracer should just behave as before by continuing the Agent start.
With single step instrumentation, Java tracer is injected for all Java processes, this is causing some initial system overhead as Java tracer starts in those JVMs. In resource limited environment, this can cause the host to be replaced due to high system load. For Data Jobs Monitoring, the Java tracer only cares about Spark process …

Add Parameter to only inject data jobs for particular java commands

---

dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java
internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java

Add shutdown hook to finish the application span from a shutdown hook, in case where the JVM is shutdown using `System.exit(code)`
Spans not being send to Datadog when JVM is exited with `System.exit(code)`
Jira ticket: https://datadoghq.atlassian.net/browse/DJM-379

Add shutdown hook to finish the spark application trace

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java

Catch exception when compiling data jobs command pattern
Not failing tracer installation if the pattern is invalid
`dd.data.jobs.command.pattern` was introduced in this PR: https://github.com/DataDog/dd-trace-java/pull/7366

Catch invalid patterns exception from dd.data.jobs.command.pattern

---

dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy

Fix the checkSmoke pipeline by correcting a test
Make green the checkSmoke

Fix checkSmoke

---

.gitlab-ci.yml

Retries the upload to Github job in case of failure.
This job has transient failures. By auto-retrying, one less manual action is needed for release.

Retry github upload in case of failure

---

dd-java-agent/instrumentation/avro/build.gradle

Creates a separate test suite for Java 8 for Avro because there are class version errors after version 1.11.3 of Avro.

Add separate test suite for Avro for java 8

---

dd-java-agent/build.gradle

Relocate embedded `jpountz` classes to avoid conflict with flat class-path when using GraalVM native-images.
In this case both the Java tracer and Kafka 3.7 contained `net.jpountz` LZ4 classes at slightly different versions.
Jira ticket: [APMS-12871]
[APMS-12871]: https://datadoghq.atlassian.net/browse/APMS-12871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix ClassNotFoundException: net.jpountz.lz4.LZ4JavaSafeCompressor when instrumenting Kafka 3.7 with Quarkus native

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextInjector.java

When an instrumentation fails the `visitEnd` method in `FieldBackedContextInjector` may not be called. This method is responsible for removing a thread local which collects the store ids injected so far, across all field-injectors of a class.
If the thread-local is not removed then collected store ids may leak across to another class, leading to getters/setters referring to a non-existent field. This doesn't cause an issue with most JVMs because that particular generated branch will never be called (since the class is not expected to hold that store). But it leads to an unresolved field on GraalVM/Quarkus because the native-image builder performs additional checks that fields exist.
The instrumentation failure in Kafka 3.7 that exposed this bug was:
```
java.lang.IllegalStateException: …
```

Fix unresolved field error when instrumenting Kafka 3.7 with Quarkus native

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecData.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecDataDeserializer.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/CurrentAppSecConfig.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/MergedAsmData.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecDataDeserializerSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/MergedAsmDataSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
dd-java-agent/appsec/src/test/resources/rules_suspicious_attacker_blocking.json

Adds the new `exclusion_data` feature to the WAF, this new property also belongs to the `ASM_DATA` remote config payload.
This PR adds a new feature called suspicious attacker blocking to appsec, which allows the ASM libraries to block specific attackers only when an attack has been detected. 
[RFC](https://docs.google.com/document/d/123wRO_ha5aZMzIXXJlGHobZrK8F4w5YuzyINncIQVLw/edit) describing the new feature.
Jira ticket: [APPSEC-54438]
[APPSEC-54438]: https://datadoghq.atlassian.net/browse/APPSEC-54438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for suspicious attacker blocking to appsec

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java

Finish span in the `finally` block to avoid leaks after exceptions.

Fix exception handling for SQL Server full mode

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java

Improve the readability by localizing exception handling. 
Following @dougqh 's [recommendation](https://github.com/DataDog/dd-trace-java/pull/7186#discussion_r1707539484). 

Improve exception handling in full mode for SQL Server

---

dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/ScriptInitializer.java
dd-java-agent/agent-crashtracking/src/test/java/com/datadog/crashtracking/ScriptInitializerTest.java

It fixes a (embarrassing) bug in the crash uploader script initialization
Jira ticket: [PROF-10324]
[PROF-10324]: https://datadoghq.atlassian.net/browse/PROF-10324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix crash-tracking uploader script overwrite warning

---

dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie

Adds IAST exclusions for `org.openid4java` and `org.seasar`
We've seen issues in one customer related to classes that get instrumented by IAST, since it provides no value it's better to exclude them.

Add exclusions for openid4java and seasar frameworks

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/RemoteHostnameAdder.java
dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/TagsPostProcessorFactory.java
dd-trace-core/src/test/groovy/datadog/trace/core/test/DDCoreSpecification.groovy

This PR lazily adds the hostname to the tag `_dd.tracer_host` to every local root span.

Add _dd.tracer_host to local root spans

---

dd-java-agent/build.gradle

Relocate embedded `jpountz` classes to avoid conflict with flat class-path when using GraalVM native-images.
In this case both the Java tracer and Kafka 3.7 contained `net.jpountz` LZ4 classes at slightly different versions.
Jira ticket: [APMS-12871]
[APMS-12871]: https://datadoghq.atlassian.net/browse/APMS-12871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[🍒 7404] Fix ClassNotFoundException: net.jpountz.lz4.LZ4JavaSafeCompressor when instrumenting Kafka 3.7 with Quarkus native

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextInjector.java

When an instrumentation fails the `visitEnd` method in `FieldBackedContextInjector` may not be called. This method is responsible for removing a thread local which collects the store ids injected so far, across all field-injectors of a class.
If the thread-local is not removed then collected store ids may leak across to another class, leading to getters/setters referring to a non-existent field. This doesn't cause an issue with most JVMs because that particular generated branch will never be called (since the class is not expected to hold that store). But it leads to an unresolved field on GraalVM/Quarkus because the native-image builder performs additional checks that fields exist.
The instrumentation failure in Kafka 3.7 that exposed this bug was:
```
java.lang.IllegalStateException: …
```

[🍒 7403] Fix unresolved field error when instrumenting Kafka 3.7 with Quarkus native

---

dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie

https://github.com/DataDog/dd-trace-java/pull/7417
(cherry picked from commit 8b3304e3e653bd02825109b9d549f16fde303377)

[🍒 7417] Add exclusions for openid4java and seasar frameworks

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/Fingerprinter.java

Create MessageDigest instance each time we are fingerprinting
Fix thread safety issue

Fix Fingerprinter thread safety

---

dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenLifecycleParticipant.java
dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenProjectConfigurator.java
dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenUtils.java

Fixes Maven instrumentation to support tracing build commands that contain plugin goals (e.g. `surefire:test`) as opposed to regular lifecycle phases (e.g. `test`).
Logic that determines forked JVM path for tests execution is also updated to handle mojo executions that are proxies.
Jira ticket: [SDTEST-691]
[SDTEST-691]: https://datadoghq.atlassian.net/browse/SDTEST-691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Maven instrumentation to support command-line plugin goals invocation

---

dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenLifecycleParticipant.java
dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenProjectConfigurator.java
dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenUtils.java

This is a cherry-pick of #7430 
Fixes Maven instrumentation to support tracing build commands that contain plugin goals (e.g. `surefire:test`) as opposed to regular lifecycle phases (e.g. `test`).
Logic that determines forked JVM path for tests execution is also updated to handle mojo executions that are proxies.
Jira ticket: [SDTEST-691]
[SDTEST-691]: https://datadoghq.atlassian.net/browse/SDTEST-691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[🍒 7430] Fix Maven instrumentation to support command-line plugin goals invocation

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/Fingerprinter.java

This is a cherry-pick of #7429 
Create MessageDigest instance each time we are fingerprinting

[🍒 7429] Fix Fingerprinter thread safety

---

dd-java-agent/build.gradle
dd-java-agent/cws-tls/build.gradle

Makes the `cws-tls` module use the same JNA dependency as the instrumentations in the final packaged jar, and includes it by default.
The `cws-tls` module was not included by default since it was under development and added significantly to the overall jar size. The JNA dependency used has since been included by other instrumentations and the `cws-tls` module can now be included.

Make cws-tls use the same JNA dependency as instrumentations

---

internal-api/src/main/java/datadog/trace/api/telemetry/LogCollector.java

Reduce maximum number of unique telemetry logs per minute from 1024 to 10.
This is plenty for most organizations and services, while it keeps misbehaving services under control.
Jira ticket: [APPSEC-53432](https://datadoghq.atlassian.net/browse/APPSEC-53432) (partially)
[APPSEC-53432]: https://datadoghq.atlassian.net/browse/APPSEC-53432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reduce telemetry log messages per minute to 10

---

dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
test-published-dependencies/agent-logs-on-java-7/src/test/java/StartWithAgentTest.java

This PR removes usage of `stdout` for reporting agent bootrapping errors.
Using `stdout` instead of `stderr` breaks CLI tools used in shell sub-commands if anything goes wrong.
Solves #7413

Avoid using stdout to report bootstrapping errors

---

dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
test-published-dependencies/agent-logs-on-java-7/src/test/java/StartWithAgentTest.java

This is a cherry-pick of https://github.com/DataDog/dd-trace-java/pull/7432.
This PR removes usage of `stdout` for reporting agent bootrapping errors.
Using `stdout` instead of `stderr` breaks CLI tools used in shell sub-commands if anything goes wrong.
Solves #7413

[🍒 7432] Avoid using stdout to report bootstrapping errors

---

dd-java-agent/instrumentation/aws-java-sns-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sns/SnsInterceptor.java
dd-java-agent/instrumentation/aws-java-sns-1.0/src/test/groovy/SnsClientTest.groovy
dd-java-agent/instrumentation/aws-java-sns-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sns/SnsInterceptor.java
dd-java-agent/instrumentation/aws-java-sns-2.0/src/test/groovy/SnsClientTest.groovy

Avoid NPE when only a phone number is provided in an SNS publish request
Both `topicArn` and `targetArn` are optional for SNS publish requests: https://docs.aws.amazon.com/sns/latest/api/API_Publish.html
`topicARN` is required for SNS publish batch requests: https://docs.aws.amazon.com/sns/latest/api/API_PublishBatch.html so we don't need to change that part of the code.
Jira ticket: [APMS-13002]
[APMS-13002]: https://datadoghq.atlassian.net/browse/APMS-13002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Avoid NullPointerException when publishing SNS messages to phone numbers

---

dd-java-agent/instrumentation/aws-java-sns-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sns/SnsInterceptor.java
dd-java-agent/instrumentation/aws-java-sns-1.0/src/test/groovy/SnsClientTest.groovy
dd-java-agent/instrumentation/aws-java-sns-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sns/SnsInterceptor.java
dd-java-agent/instrumentation/aws-java-sns-2.0/src/test/groovy/SnsClientTest.groovy

Avoid NPE when only a phone number is provided in an SNS publish request
Both `topicArn` and `targetArn` are optional for SNS publish requests: https://docs.aws.amazon.com/sns/latest/api/API_Publish.html
`topicARN` is required for SNS publish batch requests: https://docs.aws.amazon.com/sns/latest/api/API_PublishBatch.html so we don't need to change that part of the code.
Jira ticket: [APMS-13002]
[APMS-13002]: https://datadoghq.atlassian.net/browse/APMS-13002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[🍒 7448] Avoid NullPointerException when publishing SNS messages to phone numbers

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestEventsHandlerImpl.java
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/main/java/datadog/trace/instrumentation/junit4/CucumberTracingListener.java
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/main/java/datadog/trace/instrumentation/junit4/CucumberUtils.java
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/groovy/CucumberTest.groovy
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/resources/org/example/cucumber/calculator/name_with_brackets.feature
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/resources/test-name-with-brackets/coverages.ftl
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/resources/test-name-with-brackets/events.ftl

Fixes Cucumber JUnit 4 instrumentation to correctly work if the name of traced feature/scenario contains bracket characters.
Previously the instrumentation logic relied on standard `Description.getClassName()` and `Description.getMethodName()` methods available in JUnit 4.
The problem is how these method are implemented: the description instance only stores a single string that combines the name of the class and method (or feature and scenario in case of cucumber). Brackets are used to separate the name of the class from the name of the method, the resulting string looks like this: `MethodName(ClassName)`.
The methods' implementation uses a regex to split the string into parts, and it doesn't work correctly if any of the parts contains bracket characters.
To circumvent this, a separate …

Fix Cucumber JUnit 4 instrumentation to correctly handle feature and scenario names with brackets

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestEventsHandlerImpl.java
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/main/java/datadog/trace/instrumentation/junit4/CucumberTracingListener.java
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/main/java/datadog/trace/instrumentation/junit4/CucumberUtils.java
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/groovy/CucumberTest.groovy
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/resources/org/example/cucumber/calculator/name_with_brackets.feature
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/resources/test-name-with-brackets/coverages.ftl
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/resources/test-name-with-brackets/events.ftl

Cherry pick #7446
Fixes Cucumber JUnit 4 instrumentation to correctly work if the name of traced feature/scenario contains bracket characters.
Previously the instrumentation logic relied on standard `Description.getClassName()` and `Description.getMethodName()` methods available in JUnit 4.
The problem is how these method are implemented: the description instance only stores a single string that combines the name of the class and method (or feature and scenario in case of cucumber). Brackets are used to separate the name of the class from the name of the method, the resulting string looks like this: `MethodName(ClassName)`.
The methods' implementation uses a regex to split the string into parts, and it doesn't work correctly if any of the parts contains bracket characters.
To circumvent …

[🍒 7435] Fix Cucumber JUnit 4 instrumentation to correctly handle feature and scenario names with brackets

---

dd-java-agent/agent-otel/otel-bootstrap/src/main/java/datadog/trace/bootstrap/otel/instrumentation/api/incubator/semconv/db/SqlStatementInfo.java

(this create method is not used at runtime because this class gets replaced with the OTel version - it's only used for compilation purposes, but we should make it consistent)
https://github.com/datadog/dd-trace-java/pull/7444

[🍒 7444] Backport review feedback from master

---

dd-java-agent/build.gradle

Increases the allowed size for the final agent jar from 29 to 30MB.
Our current master branch is already pretty close to the limit `30400971 < 30408704` 

Increase the allowed size of the agent jar to 30MB

---

.github/workflows/README.md
.github/workflows/add-milestone-to-pull-requests.yaml
.github/workflows/update-gradle-dependencies.yaml

This PR:
* Improves automatic milestone assignment to support patch release in addition to the original minor release.
* Fix formatting of the automatic Gradle dependency lock update PR description.
Cleaning and keeping stuff working

Improve Github automation

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymDBEnablement.java

In some cases, extracted jar path from the CodeSource of a class can point to a directory instead of a jar file.
Now we are skipping this case to avoid having an exception trying to open it as a jar file
Jira ticket: [DEBUG-2576]
[DEBUG-2576]: https://datadoghq.atlassian.net/browse/DEBUG-2576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix considering directory as jar file

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractPreparedStatementInstrumentation.java

If the query info is missing, the jdbc advice onEnter is returning a null scope but the threadlocal for its calldepth is not reset.
That means that subsequent queries done on the same thread will not be traced because the calldepth threadlocal is dirty
Jira ticket: [APMS-12988]
[APMS-12988]: https://datadoghq.atlassian.net/browse/APMS-12988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Do not leak call depth threadlocal in jdbc instrumentation

---

dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/trace/OtelTracer.java

Helps distinguish span metrics from OTel extensions with those from manual OTel instrumentation.
Metrics for spans created manually via the OTel API continue to be tagged with 'otel'.
Jira ticket: [APMAPI-153]
[APMAPI-153]: https://datadoghq.atlassian.net/browse/APMAPI-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tag span metrics with 'otel.library' when we know it was created by an OTel extension

---

.circleci/config.continue.yml.j2
build.gradle
dd-java-agent/agent-debugger/build.gradle
dd-java-agent/agent-profiling/build.gradle
dd-java-agent/instrumentation/build.gradle
dd-smoke-tests/build.gradle

The way we called jacoco tasks for gradle will trigger tests outside those selected by `:baseTests` at al. Remove explicit calls to these tasks from CI, and use a `-PcheckCoverage` property instead. When combined with `:baseTests`, it will run jacoco tasks only for the selected tests.
Remove legacy properties `-PskipInstTests`, `-PskipSmokeTests`, etc. These are now obsolete, and together with the above fix, they do not serve any purpose in CI anymore.
`:debuggerTest` have test coverage always enabled. This behavior is preserved.
- ~[ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration …

Fix test selection logic with coverage

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java

Better clearing of calldepth threadlocal on jdbc statements.

Don't leak calldepth threadlocal on statements

---

.github/workflows/add-release-to-cloudfoundry.yaml

It seems Maven Central added HTTP/2 support, leading to different curl output in our automation. For HTTP 1.1 it's `HTTP/1.1 200 OK` and for HTTP 2 it's `HTTP/2 200`. Currently workflow gets stuck because of this:  https://github.com/DataDog/dd-trace-java/actions/runs/10418982507/job/28856149889

Update cloudfoundry automation with HTTP 2 support

---

dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/RemoteHostnameAdder.java
dd-trace-core/src/main/java/datadog/trace/core/tagprocessor/TagsPostProcessorFactory.java
internal-api/src/main/java/datadog/trace/api/Config.java

Avoid hard-reference to `Config` in `RemoteHostnameAdder` because it causes issues with Quarkus + GraalVM.
Instead we use the `Supplier` API to keep the hostname lookup lazy while avoiding eager analysis of the `Config` class.
Note we deliberately avoid using a method-reference to `Config` because that can also lead to unexpected resolution.
The `Config` class contains all configuration data after the point at which instrumentation is configured (configuration that affects which instrumentation is applied must go in `InstrumenterConfig` which ends up baked into the final native image.)
Because we want to re-run `Config` whenever the native-image executes we must be careful not to refer to that type in certain types that get eagerly loaded during the native-image build. That's why …

Avoid RemoteHostnameAdder.config resolution error when building Quarkus native images

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java

Remove unknown WAF address warning. These happens whenever we receive rules for an address that is not supported by the current version, which is bound to happen for previously released tracers. This has proved to be non-helpful so far, and confusing to customers. Other tracers are not logging this either.
Jira ticket: [APPSEC-54587](https://datadoghq.atlassian.net/browse/APPSEC-54587)
[APPSEC-54587]: https://datadoghq.atlassian.net/browse/APPSEC-54587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …

Remove warning whenever we receive an unknown WAF address

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/UntrustedDeserializationModuleImpl.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/UntrustedDeserializationModuleTest.groovy
dd-java-agent/instrumentation/java-io/src/main/java/datadog/trace/instrumentation/java/lang/ObjectInputStreamCallSite.java
dd-java-agent/instrumentation/java-io/src/test/groovy/datadog/trace/instrumentation/java/io/ObjectInputStreamCallSiteTest.groovy
internal-api/src/main/java/datadog/trace/api/iast/sink/UntrustedDeserializationModule.java

Refactors the UntrustedDeserializationModule to a more generic call.
We want to avoid having the same function duplicated for different types of objects such as InputStream, Reader, Strings...
Jira ticket: [APPSEC-54452]
[APPSEC-54452]: https://datadoghq.atlassian.net/browse/APPSEC-54452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor UntrustedDeserializationModule to be more generic

---

telemetry/src/main/java/datadog/telemetry/log/LogPeriodicAction.java
telemetry/src/test/groovy/datadog/telemetry/log/LogPeriodicActionTest.groovy

Tweak our stackframe redaction format to make it compatible with current error tracking parser.

Tweak telemetry log stacktrace redaction for error tracking compatibility

---

dd-java-agent/instrumentation/commons-fileupload/build.gradle
dd-java-agent/instrumentation/commons-fileupload/src/test/groovy/MultipartInstrumentationTest.groovy

This removes references to the commons-fileupload2 library is not being use at the moment
Make coherence between naming and classes
Jira ticket: [APPSEC-54157]
[APPSEC-54157]: https://datadoghq.atlassian.net/browse/APPSEC-54157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove commons-fileupload2 references

---

dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/main/java/datadog/trace/instrumentation/junit4/CucumberUtils.java
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/groovy/CucumberTest.groovy
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/resources/org/example/cucumber/calculator/empty_scenario_name.feature
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/resources/test-empty-name-5.4.0/coverages.ftl
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/resources/test-empty-name-5.4.0/events.ftl
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/resources/test-empty-name-latest/coverages.ftl
dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/test/resources/test-empty-name-latest/events.ftl

Fixes Cucumber JUnit 4 instrumentation to correctly work with scenarios that have no name.
It is possible to declare a Cucumber scenario that has an empty name (this only works for JUnit4-backed Cucumber):
```
Feature: Name of the feature
Scenario:
...
```
If the feature contains multiple scenarios that do not have names, Cucumber will assign synthetic names for them (`#1`, `#2`, etc).
However, if there is only one such scenario, its name will remain empty.
This causes problems in the backend, because scenario name maps to test name, and the latter is needed to calculate test fingerprint.
The solution is to update the tracing logic to generate synthetic names in case Cucumber does not do it.
The logic will try to calculate the line where scenario is declared and use that as the name …

Fix Cucumber JUnit 4 instrumentation to support empty scenario names

---

dd-java-agent/instrumentation/tomcat-appsec-7/src/main/java/datadog/trace/instrumentation/tomcat7/ErrorReportValueAdvice.java

Suppress internal exceptions from ErrorReportValueAdvice.
Unclear if this has ever happened, but there's a support case where this could be the case and we do not have any debug logs.

Suppress internal exceptions in tomcat stacktrace leak detection

---

dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/propagation/AgentTextMapPropagator.java
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/ApacheHttpClientRedirectInstrumentation.java
dd-java-agent/instrumentation/apache-httpclient-4/build.gradle
internal-api/build.gradle
internal-api/src/main/java/datadog/trace/util/PropagationUtils.java

This PR avoids copying the original request headers when a redirect happen. The issue here is that the original request may contain headers like `Host`. In this case, if we copy it on the redirected one, apache http client will keep this one (which might be wrong).
This PR takes the request instead from the context. That request is always a Wrapped request. Having access to the wrapped request we can get the original one that contains only the headers manually added (by the user and by us) but not added by the library itself (i.e. Host, Content-Type, ...)
I also added the tag `httpclient-redirect` to that instrumentation in order to unplug easily in case of issues
Jira ticket: [APMS-12746]
[APMS-12746]: https://datadoghq.atlassian.net/browse/APMS-12746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

Apache http client 4: do not copy all request headers on redirect

---

dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDLoggerFactory.java
internal-api/src/main/java/datadog/trace/api/Config.java

This starts a progressive rollout using product independent sample.
Enabling error tracking for more customers should help to raise any log volume issue, and help with SSI safeguards. 
Jira ticket: [APMLP-102]
[APMLP-102]: https://datadoghq.atlassian.net/browse/APMLP-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enable telemetry logs for a subset of Java versions

---

dd-java-agent/instrumentation/tomcat-appsec-7/src/main/java/datadog/trace/instrumentation/tomcat7/ErrorReportValueAdvice.java

Initial advice skipped the original method on <400 http status code and responses not marked as errors. But we should not be changing the original behavior by default.
Ensure we do not change original application behavior by default, we should be passive unless blocking a request.

Do not skip ErrorReportValve.report in any case

---

.circleci/render_config.py

This PR upgrades to docker build image to https://github.com/DataDog/dd-trace-java-docker-build/actions/runs/10056908860
Use update versions to build `dd-trace-java`

Upgrade builds to latest JDK versions

---

.circleci/config.continue.yml.j2

This PR update the system-tests pinned version.
It also restore worker count, use bigger runner and update the timeout accordingly.
Add latest scenarios and new parametric client implementation.

Update system-tests to 20b61e9be1e8c922804f8e5ddc80ba4a1f4cdd5b

---

dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenLifecycleParticipant.java
dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenUtils.java

Implements a fallback method for getting effective JVM for a traced Maven Surefire plugin invocation.
The original logic looks up and invokes a private `getEffectiveJvm()` method from the plugin's configured MOJO - this is the method that Surefire plugin itself uses to determine the JVM to use for forking.
It is not always possible to look up the method and invoke it - one example is when the MOJO is proxied (although I could not reproduce this locally, this happens for some customers).
The fallback logic tries to follow the steps of the `getEffectiveJvm()` as closely as possible.
Jira ticket: [SDTEST-723]
[SDTEST-723]: …

Implement a fallback method for getting effective JVM for Maven Surefire executions

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestImpl.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/buildsystem/ProxyTestModule.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/headless/HeadlessTestModule.java
dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/retry/RetryIfFailed.java
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/domain/TestImplTest.groovy
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/domain/buildsystem/ProxyTestModuleTest.groovy
dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/domain/headless/HeadlessTestModuleTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/CiVisibilityConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/api/civisibility/telemetry/CiVisibilityCountMetric.java
internal-api/src/main/java/datadog/trace/api/civisibility/telemetry/tag/IsRetry.java

Updates auto-test retries logic in CI Visibility:
- Adds new `is_retry` tag for `event_finished` telemetry metric
- Implements global per-JVM retries limit (in addition to existing per-test retries limit)
The required changes are described in this [RFC](https://docs.google.com/document/d/1Cy6n-CHu0QPV1_Jn9yLCa3aBvgm1JjviFDEq6oUzyuQ/edit#heading=h.4t5xapveah86).
Jira ticket: [SDTEST-697]
[SDTEST-697]: https://datadoghq.atlassian.net/browse/SDTEST-697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Implement telemetry and global per-JVM limit for auto test retries

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/WellKnownClasses.java

protobuf collections used are specific ones implementing JDK interfaces. They are in-memory collection so it is safe to handle them like the JDK ones.
https://github.com/protocolbuffers/protobuf/tree/main/java/core/src/main/java/com/google/protobuf
DSM live payload feature
Jira ticket: [DEBUG-2779]
[DEBUG-2779]: https://datadoghq.atlassian.net/browse/DEBUG-2779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add protobuf collections as safe ones

---

dd-java-agent/instrumentation/armeria-grpc/src/main/java/datadog/trace/instrumentation/armeria/grpc/client/GrpcClientDecorator.java
dd-java-agent/instrumentation/armeria-grpc/src/main/java/datadog/trace/instrumentation/armeria/grpc/server/GrpcServerDecorator.java
dd-java-agent/instrumentation/armeria-grpc/src/test/groovy/ArmeriaGrpcTest.groovy
dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/GrpcClientDecorator.java
dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcServerDecorator.java
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy

This PR fixes the way the grpc server spans are marked as errored. 
In fact, in case a server service was returning a status through a `StatusException` or `StatusRuntimeException`, the span was marked as errored (because `onError` generally does it) despite the fact  that `dd.grpc.server.error.statuses` was excluding it.
Now the `setError` on the span is called always. For info, a similar issue occurred for the http server decorator in the past and was due to the same buggy setError conditional logic.
Jira ticket: [APMS-12919]
[APMS-12919]: https://datadoghq.atlassian.net/browse/APMS-12919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

Fix grpc server error mark

---

dd-java-agent/instrumentation/junit-4.10/munit-junit-4/build.gradle

Restrict max version on munit because currently the latest version breaks the tests.
See https://github.com/scalameta/munit/issues/813
This is not meant to be permanent, but just to make sure the "update gradle dependencies" bot doesn't try to update that lib every week.

add restriction on munit version in build.gradle

---

dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/TaintedObject.java
dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/TaintedObjects.java
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedObjectTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedObjectsLogTest.groovy
dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedObjectsTest.groovy

Adds information to troubleshoot and issue with null values in ranges.
Recently we've starting receiving issues at:
```
afterAppend threw
java.lang.NullPointerException: <unknown>
at com.datadog.iast.taint.Ranges.copyShift(Ranges.java:92)
at com.datadog.iast.taint.Ranges.copyShift(Ranges.java:75)
at com.datadog.iast.propagation.StringModuleImpl.onStringBuilderAppend(StringModuleImpl.java:117)
```
This PR should help us pinpoint the issue.

Add debug info to tainted objects to troubleshoot null ranges

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SymbolSink.java
dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/SymbolSinkTest.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymbolExtractionTransformerTest.java

SymbolSink was emitting an upload requests for every scope added into the sink queue. As the queue was 1024 entries in capacity we could easily end up in a situation where more than 20 requests are made when draining the Q. to avoid that we are batching the scope together in a single larger upload request and ensure that the sink queue is flushed when full before adding new element and not losing any symbols.
avoid dropping SymDB requests
Jira ticket: [DEBUG-2685]
[DEBUG-2685]: https://datadoghq.atlassian.net/browse/DEBUG-2685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix SymDB upload dropped requests

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
dd-java-agent/appsec/src/test/resources/test_multi_config.json
dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/DecodedSpan.java
utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/v04/raw/SpanV04.java
utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/v05/raw/SpanV05.java

Enable `generate_stack` WAF action by default. These will only be emitted by RASP (aka Exploit Prevention) at the moment.
To support smoke tests, also added support to decode meta_struct in SpanV04.
There is little reason for anyone to disable this, except the need to troubleshoot or workaround a bug.
This PR is part of enabling RASP for AppSec users.
Jira ticket: [APPSEC-53837](https://datadoghq.atlassian.net/browse/APPSEC-53837) (partially)
[APPSEC-53837]: …

Enable WAF generate_stack action by default

---

dd-java-agent/instrumentation/iast-instrumenter/src/main/java/datadog/trace/instrumentation/iastinstrumenter/IastInstrumentation.java
dd-java-agent/instrumentation/iast-instrumenter/src/test/groovy/IastInstrumentationForkedTest.groovy
dd-java-agent/instrumentation/iast-instrumenter/src/test/groovy/IastInstrumentationTest.groovy

Makes sure that RASP call sites are not installed unless appsec is explicitly enabled.
Call sites should be rolled on to customers which are explicitly setting appsec to active, once it's stable enough we will change it so it's enabled with appsec set as inactive.

Ensure RASP call sites are only installed with appsec fully enabled

---

dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/utils/ProcessHierarchyUtils.java

Fixes the logic that determines whether the tracer is attached to a JVM that runs Gradle Daemon.
Previous version of the logic only relied on `org/gradle/launcher/daemon/` package being present on the classpath.
This failed when the traced process was a Gradle Worker that ran tests for a Gradle Plugin (and as a consequence had plugin API classes on its classpath, some of which lived in `org/gradle/launcher/daemon/` package).
Jira ticket: [CIVIS-10218]
[CIVIS-10218]: https://datadoghq.atlassian.net/browse/CIVIS-10218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Gradle Daemon process detection

---

dd-smoke-tests/appsec/src/main/groovy/datadog/smoketest/appsec/AbstractAppSecServerSmokeTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java

Sets `DD_APPSEC_RASP_ENABLED=true` by default. Only effective when `DD_APPSEC_ENABLED=true` (or enabled at runtime by remote config).
Jira ticket: [APPSEC-53837](https://datadoghq.atlassian.net/browse/APPSEC-53837)
[APPSEC-53837]: https://datadoghq.atlassian.net/browse/APPSEC-53837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set DD_APPSEC_RASP_ENABLED to true by default

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy

Changes the RASP addresses for SQLi and SSRF in order to make them ephemeral.
Ephemeral addresses should be used for data that has to be evaluated only once and makes no sense to hold them for future evaluations of the WAF, this is the case for SQLi and SSRF which might happen multiple times during the context of a request.

Make RASP addresses ephemeral

---

dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ProbeStateIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SpanDecorationProbesIntegrationTests.java

Disabled flaky tests for IBM JVM

---

dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDLoggerFactory.java
internal-api/src/main/java/datadog/trace/api/Config.java

Default telemetry logs to enabled for services with `DD_APPSEC_ENABLED=true`.
As we rollout Exploit Prevention, we'd like to be sure to catch any unexpected error.

Enable telemetry logs for services using AppSec

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

Free all retained data structures by the `AppSecRequestContext` when the request ends.
When the span holding the reference to the `AppSecRequestContext` is in pending state, there is a lot of data retained by AppSec (headers, cookies, addresses...) that are no longer required as they have already being flushed to the span. The only catch is for the cases were additional post processing is required (e.g. API security).
Screenshots with the retained sizes of `AppSecRequestContext`:
Before
After

Free AppSecRequestContext resources when the request ends

---

.github/workflows/add-milestone-to-pull-requests.yaml

This PR fixes workflow permission regression introduced by #7531 
Jira ticket: [VULN-8166]
[VULN-8166]: https://datadoghq.atlassian.net/browse/VULN-8166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix workflow permissions

---

.circleci/config.continue.yml.j2

Add missing parallelization to z_test_8_ssi_smoke job. Same parameters as the rest of smoke test job.
`z_test_8_ssi_smoke job` is taking 27 minutes, delaying the overall pipeline time.

Add missing parallelization to z_test_8_ssi_smoke job

---

dd-java-agent/appsec/src/main/resources/default_config.json

This reverts commit 44c20d2736298bc5eab9bdc868daeb3151104085 (https://github.com/DataDog/dd-trace-java/pull/7536).
Rollout of the Exploit Prevention rules enabled by default is delayed.

Revert "Updated ASM rules to 1.13.1 (#7536)"

---

.github/workflows/analyze-changes.yaml

This PR improves the code analysis workflow by:
* Adding build cache save/restore
* Disabling CodeQL SARIF result upload to Datadog
Improve the Trivy scan time
Remove CodeQL job error

Improve code analysis workflow

---

settings.gradle

Update to develocity 3.18. Includes CPU, memory and network usage graph in build scans.

Update to develocity 3.18 (resource usage)

---

dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java

Makes the profiling smoke tests nicer towards mac users
Let's not fail the test - rather log an explanatory message and skip if the requirements are not fulfilled.
I haven't opened a JIRA ticket for this trivial change.

Do not fail profiler smoke tests on macos

---

.circleci/config.continue.yml.j2

This PR fixes the nightly build commands.
The build is failing with the following error:
```
Task 'MAVEN_OPTS=-Xms64M -Xmx256M' not found in root project 'dd-trace-java' and its subprojects.
```
Regression from: https://github.com/DataDog/dd-trace-java/pull/7239

Fix nightly build command line

---

dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/RouteHandlerInstrumentation.java
dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/RouteHandlerWrapper.java
dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/RouteHandlerWrapperAdvice.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RouteHandlerInstrumentation.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RouteHandlerWrapper.java
dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RouteHandlerWrapperAdvice.java

When doing `blockingHandler` vertx create a inner route that we do not wrap. because of this the context is not propagated hence the span generated while executing this handler are attached to the wrong trace/parent
This PR makes sure that all the handlers can activate the right scope by using the one created for the route stored in the routing context

Vertx: wrap internal routes to let the context propagate for blocking handlers

---

dd-java-agent/instrumentation/google-pubsub/src/main/java/datadog/trace/instrumentation/googlepubsub/PubSubDecorator.java
dd-java-agent/instrumentation/google-pubsub/src/test/groovy/PubSubTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

Google pubsub was lacking of the possibility to turn off the legacy tracing mode. When off, the consumer will use the value of `DD_SERVICE` instead that `google-pubsub` as a service name.
The feature can be activated by:
* A system property `-Ddd.google-pubsub.legacy.tracing.enabled=false`
* An environment variable `DD_GOOGLE_PUBSUB_LEGACY_TRACING_ENABLED=false`
see #7209 

Google PubSub: implement switchable legacy tracing mode

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/ServerDebuggerTestApplication.java
dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/TestApplicationHelper.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ExceptionDebuggerIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ServerAppDebuggerIntegrationTest.java
dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SpanDecorationProbesIntegrationTests.java

Verifies that basic Exception Replay is working as expected using a
`@trace` annotation
No new capture after the first one for an hour and only 3 frames are
captured
Jira ticket: [DEBUG-2735]
[DEBUG-2735]: https://datadoghq.atlassian.net/browse/DEBUG-2735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add smoke test for Exception Replay

---

dd-smoke-tests/springboot-tomcat/build.gradle
dd-smoke-tests/wildfly/build.gradle

Adds task ordering for certain sections of dd-smoke-tests
Consistently getting errors with `dd-smoke-tests:springboot-tomcat:forbiddenApisMain` when trying to build a clean version of dd-trace-java from master branch (`./gradlew clean build`), following the https://github.com/DataDog/dd-trace-java/blob/master/BUILDING.md instructions.
- possible solution/ thought that task ordering was causing the error, tried to add these changes to ordering 
```
FAILURE: Build failed with an exception.
Some problems were found with the configuration of task ':dd-smoke-tests:springboot-tomcat:forbiddenApisMain' (type 'CheckForbiddenApis').
- Gradle detected a problem with the following location: '/Users/jordan.wong/dd-trace-java/dd-smoke-tests/springboot-tomcat/build/classes/java/main' …
```

Change Gradle task ordering to fix build issues with dd-smoke-tests

---

internal-api/src/main/java/datadog/trace/util/PidHelper.java
internal-api/src/main/java/datadog/trace/util/ProcessSupervisor.java

This PR avoids reporting to customers internal process start.
Avoid reporting internal spans.
Avoid issues with unexpected spans during tests too.
Need to revert https://github.com/DataDog/system-tests/pull/2973

Mute internal process start

---

.circleci/config.continue.yml.j2

ubuntu:2404 images from Circle CI already include Python 3.12 by default.
Minor build time improvement in CI.

Avoid redundant Python 3.12 in system-tests

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeInstrumentationTest.java

For Exception Replay we add also the `_dd.debug.error.exception_hash`
tag along with exception_id and snapshot ids
fix system tests 
Jira ticket: [DEBUG-2787]
[DEBUG-2787]: https://datadoghq.atlassian.net/browse/DEBUG-2787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add exception_hash tag for span

---

dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java

Disabled test for local vars on IBM JDK

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/ProbeStatusSink.java
internal-api/src/main/java/datadog/trace/relocate/api/RatelimitedLogger.java
internal-api/src/test/groovy/datadog/trace/relocate/api/RateLimitedLoggerTest.groovy

Use a rate limited logger to warn the queue for probe status is full and send it explicitly to telemetry
Jira ticket: [DEBUG-2700]
[DEBUG-2700]: https://datadoghq.atlassian.net/browse/DEBUG-2700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Send telemetry log when Probe status queue is full

---

dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java

Don't emit the status when no tag are set for the span
Jira ticket: [DEBUG-2825]
[DEBUG-2825]: https://datadoghq.atlassian.net/browse/DEBUG-2825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix span decoration probe  EMITTING status

---

dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/WellKnownClasses.java
dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java

We added special field access for Optional but forgot about specialized version for primitives: Int, Double and Long
Jira ticket: [DEBUG-2777]
[DEBUG-2777]: https://datadoghq.atlassian.net/browse/DEBUG-2777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for Optional(Int|Double|Long)

---

dd-java-agent/instrumentation/spring-scheduling-3.1/src/main/java/datadog/trace/instrumentation/springscheduling/SpringSchedulingRunnableWrapper.java
dd-java-agent/instrumentation/spring-scheduling-3.1/src/test/groovy/SpringSchedulingTest.groovy
dd-java-agent/instrumentation/spring-scheduling-3.1/src/test/java/SchedulingConfig.java

According to our tests the spring scheduling spans should have no parent. This PR ensure that the spans are created with a noop parent scope. Temporary, I also added a way to restore the old behaviour (that's nondeterministic anyway) by
* the sys prop `-Ddd.spring-scheduling.legacy.tracing.enabled=true`
* the env `DD_SPRING_SCHEDULING_LEGACY_TRACING_ENABLED=true`

Spring scheduling: ensure spans have no parent

---

dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy

Fix Exploit Prevention (aka RASP) capability announcement for remote configuration. For v1.39.0, this has been addressed in the backend with a capability override. For v1.40.0+, we'll properly announce the capabilities, including not announcing them if the user sets `DD_APPSEC_RASP_ENABLED=false`.

Fix Exploit Prevention capability announcement on remote config

---

dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/test/groovy/util/AbstractCouchbaseTest.groovy

Mute tracing on cleanup, instead of waiting for a cleanup span. This test is flaky when it does not receive the cleanup span in time (under heavy load).
Also, do not shallow exceptions on cleanup. If we ever get them, we can address them, or add a more specific catch.
Trick copied from @amarziali at https://github.com/DataDog/dd-trace-java/pull/7597
The same pattern could be used in quite a few more (potentially flaky) tests.

Fix couchbase flaky test (cleanup phase)

---

dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy

Under high load, the order of spans by duration might be altered. Make sure we check local root spans, and that we allow for different order in traces and access logs.

Fix flaky test on TomcatServlet3TestAsync

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/JDBCConnectionUrlParser.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DefaultConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCConnectionUrlParserTest.groovy

Add support for connection parsing and prepared statement tracing for intersystems jdbc driver.
The documentation for the connection url: https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=BJAVA_connecting#BJAVA_connecting_create_url_parms
Jira ticket: [APMS-13205]
[APMS-13205]: https://datadoghq.atlassian.net/browse/APMS-13205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for Intersystems IRIS jdbc driver

---

.github/workflows/comment-on-submodule-update.yaml

Add pull_requests write permission to comment-on-submodule-update
The workflow execution broke with the recent default permission change.

Fix submodule update automation

---

dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java

Adds the spark.stage details attribute at the end of the stage, rather than at the beginning.
The details attribute contains a large amount of data, including the full stack trace that initiated the stage. When using long-running spans, the span is flushed multiple times, which can significantly increase the ingestion volume.
By adding the details attribute at the end of the stage, we reduce the ingestion volume while still ensuring the information is available once the stage has completed.

Add `spark.stage` details attribute at the end of the stage

---

dd-java-agent/instrumentation/junit-4.10/munit-junit-4/build.gradle
dd-java-agent/instrumentation/junit-4.10/munit-junit-4/src/main/java/datadog/trace/instrumentation/junit4/MUnitTracingListener.java

Fixes tracing of skipped suites in MUnit 1.0.1
In MUnit 1.0.1 release a different set of events is fired for skipped test suites.
Previous versions of the framework fixed start/ignore/finish events for such suites.
The new version of the framework only fires the ignore event.
This appears to be an accidental side-effect of an unrelated change, and an [issue](https://github.com/scalameta/munit/issues/813) was reported in the framework repo.
It does not look, however, like this is getting fixed any time soon, so a workaround is introduced in the tracer.
Jira ticket: [SDTEST-843]
[SDTEST-843]: https://datadoghq.atlassian.net/browse/SDTEST-843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …

Fix tracing skipped suites in MUnit 1.0.1

---

dd-java-agent/instrumentation/freemarker/freemarker-2.3.24/src/test/groovy/datadog/trace/instrumentation/freemarker24/ObjectWrapperInstrumentationTest.groovy

Fix the test with newer versions of freemarker
This is motivated by an upgrade of the freemarker latest version that was showing error in the specific test

Fix freemarker test with newer versions

---

dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy

Retry tests in `JettyServlet3ServeFromAsyncTimeout` when there's a `SocketTimeoutException`. This needs to be done with `SETUP_FEATURE_CLEANUP` to ensure that cleanup is run, and leftover spans do not leak between iterations.
This test suite is, by far, the most flaky in our test suites. However, being in a very widely used code path, I'm reluctant to simply mark as `@Flaky` and hide any regression here.

Retry JettyServlet3ServeFromAsyncTimeout on socket timeout

---

.gitlab-ci.yml

Adds a profiling scenario to the onboarding tests. You can see it in action as it now ran in the Gitlab checks in this PR!
Profiler now supports SSI, so adding a test for it in the test matrix here ensures we quickly notice if it gets broken. 
The `test-app-java-buildpack` weblog is excluded for now, as it is known to fail due to unrelated reasons in system-tests build.
Jira ticket: [PROF-10521]
[PROF-10521]: https://datadoghq.atlassian.net/browse/PROF-10521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add profiling scenario to onboarding tests

---

dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy

Same as https://github.com/DataDog/dd-trace-java/pull/7625

Retry JettyServlet3TestAsyncDispatchOnAsyncTimeout on socket timeout
