DataDog/dd-trace-java

.circleci/collect_libs.sh
dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
dd-java-agent/agent-jmxfetch/copy-metric-configs.sh

Otherwise there seems to be a race condition which results in the metric config files being overwritten.

 Ensure the copyMetricConfigs task runs after processResources

---

dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java

Some applications seem to have this jboss class on the classpath, but don’t actually use it.  When coupled with not actually using JUL, this means that we may never actually start JMXFetch.
Checking for JBOSS_HOME instead should be safer.

Replace jboss classpath check with ENV check for jmxfetch delay

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java

Using dd-java-agent with our Clojure applications, they will fail to start with a ClassNotFoundException when loading a Clojure protocol class.  Skipping instrumentation of the `clojure.lang.DynamicClassLoader` class seems to resolve the issue for us.
However, if there is a better way to resolve this problem, we are open to investigating it further.

Don't break Clojure's protocols

---

dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java
dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Enable each individually by setting `-Ddd.integration.<integration_name>.enabled=true`.

JMXFetch bundled integrations disabled by default

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/State.java
dd-java-agent/instrumentation/java-concurrent/akka-2.5-testing/src/test/groovy/AkkaExecutorInstrumentationTest.groovy
dd-java-agent/instrumentation/java-concurrent/scala-testing/src/test/groovy/ScalaExecutorInstrumentationTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ExecutorInstrumentationUtils.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/FutureInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/TraceUtils.groovy
dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/ContinuableScope.java
dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy

Some executors cannot handle tasks that have been wrapped into
`{Runnable,Callable}Wrapper` because they require certain subclass of
`{Callable,Runnable}` in order to work. We have a test that
effectively disables instrumentation for such executors.
This change makes sure that tasks that do not need to be
wrapped (which essentially means anything that is not lambda) still
get traced in such executors. One notable example of affected executor
type is `ScheduledThreadPoolExecutor`.

Allow non-wrapped tasks in disabled executors

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java

I considered excluding Interfaces too, but that would break people that added `@Trace` to their default methods.
Just a hunch, but I don’t think we want to instrument classes marked as synthetic, for example proxies.  We may want to extend this to our method matchers (and maybe exclude native methods too).
We might want to instrument enums/annotations, but that seems unlikely.

Exclude several type identifications from instrumentation

---

dd-java-agent/instrumentation/elasticsearch-rest-6.4/elasticsearch-rest-6.4.gradle

It looks like beta 7.x.x was released and our instrumentation doesn't
work with it at the moment.

Limit ES-rest tests to 6.x.x versions

---

gradle/java.gradle

Tests run under regular classpath, not the custom one defined by the plugin.  This works for some tests where this is expected, but other tests it’s just retesting the `test` sourceset tests, not the custom provided ones (ex: slickTest).

Exclude tests generated by “test-sets” plugin from alternate JVM tests

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java

It generates a lot of noise when running tests and likely shouldn’t be instrumented.

Exclude groovy macro package from instrumentation

---

dd-java-agent/instrumentation/hystrix-1.4/hystrix-1.4.gradle
dd-java-agent/instrumentation/hystrix-1.4/src/main/java/datadog/trace/instrumentation/hystrix/HystrixCommandInstrumentation.java
dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixTest.groovy

Related to issue #707 
Changes:
- Added hystrix `Command Group` to resource name for a better grouping of commands.
- Added `Command Key`, `Command Group` and "is Circuit Breaker Open" as tags.
Example of resource name change:
Old name: `ExampleCommand.run`
New name: `ExampleGroup.ExampleCommand.run`

Hystrix metadata added to tags and Command Group included in resource name

---

dd-smoke-tests/play/play.gradle
dd-smoke-tests/springboot/springboot.gradle
dd-smoke-tests/wildfly/wildfly.gradle

Default 60 seconds often pass when run on laptop in paralle mode.

Increase time we wait for smoke tests servers to start up

---

dd-java-agent/instrumentation/tomcat-classloading/src/main/java/datadog/trace/instrumentation/tomcat/TomcatClassloadingInstrumentation.java
dd-java-agent/instrumentation/tomcat-classloading/src/test/groovy/TomcatClassloadingTest.groovy
dd-java-agent/instrumentation/tomcat-classloading/tomcat-classloading.gradle
settings.gradle

This is really the same thing we already do for OSGi and jboss.

Add instrumentation for Tomcat webapp classloading

---

dd-java-agent/instrumentation/jsp-2.3/src/main/java/datadog/trace/instrumentation/jsp/JSPDecorator.java
dd-java-agent/instrumentation/jsp-2.3/src/main/java/datadog/trace/instrumentation/jsp/JSPInstrumentation.java
dd-java-agent/instrumentation/jsp-2.3/src/main/java/datadog/trace/instrumentation/jsp/JasperJSPCompilationContextInstrumentation.java
dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationBasicTests.groovy
dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationForwardTests.groovy

Remove span kind and type from generated spans since these classify more as specialized @Trace spans.

Migrate JSP instrumentation to Decorator

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/server/http/TestHttpServer.groovy

I notice occasionally some of the instrumentation tests fail due to port
conflicts in TestHttpServer, esp when using the `--parallel` option in
gradle. I think the previous method is subject to a race where two
concurrent workers will both get the same port from `randomOpenPort()`.

Avoid race in TestHttpServer port selection

---

dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java

Support DogStatsD over Unix Domain Socket in jmxfetch by letting the user configure the UDS path. The path should be set through the usual agent hostname config option with a `unix://` prefix.

Add UDS support for jmxfetch

---

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWSClientTest.groovy
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test_1_11_106/groovy/AWSClientTest.groovy
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/test/groovy/AwsClientTest.groovy

I don’t think these are helping us and we may still risk messing up the signed request if this happens too late.

Remove trace injection into AWS requests

---

.circleci/config.yml
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/PatchLogger.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Constants.java
dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/TracingInterceptor.java
dd-java-agent/instrumentation/okhttp-3/src/test/groovy/OkHttp3Test.groovy
dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
dd-trace-java.gradle
dd-trace-ot/dd-trace-ot.gradle
dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/Writer.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/unixdomainsockets/TunnelingUnixSocket.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/unixdomainsockets/UnixDomainSocketFactory.java
dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDApiTest.groovy
dd-trace-ot/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy

Users can now provide path to Unix Domain Socket using `dd.trace.agent.unix.domain.socket` system property. This is be used to communicate with Datadog agent to send traces. Main intended use case is to be able to direct traces traffic to some sort of proxy to later be sent to potentially remote Datadog agent.

Support unix domain sockets

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/BaseDecorator.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/BaseDecoratorTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

This now aligns with the config key used by other language tracers.

Fix Trace Search + Analytics integration config key

---

dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
dd-trace-ot/src/main/java/datadog/opentracing/DDSpanContext.java
dd-trace-ot/src/test/groovy/datadog/trace/DDSpanContextTest.groovy

Convert to doubles instead.
Agent was throwing the following error on ingest:
```
cannot decode v0.4 traces payload: msgp: attempted to decode type "float32" with method for "float64"
```
This is because [this method](https://github.com/DataDog/datadog-agent/blob/6.10.1/pkg/trace/pb/decoder.go#L39) doesn't handle floats, only integers and doubles.

Agent doesn’t like getting floats.

---

dd-trace-api/dd-trace-api.gradle
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
dd-trace-ot/src/main/java/datadog/opentracing/propagation/B3HttpCodec.java
dd-trace-ot/src/main/java/datadog/opentracing/propagation/DatadogHttpCodec.java
dd-trace-ot/src/main/java/datadog/opentracing/propagation/HttpCodec.java
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/B3HttpExtractorTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/B3HttpInjectorTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/DatadogHttpExtractorTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/DatadogHttpInjectorTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/HttpExtractorTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/HttpInjectorTest.groovy
dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy

Support extracting and injecting B3 headers.
By default  only Datadog headers are used. Configuration is done with `dd.propagation.style.extract` and `dd.propagation.style.inject` system properties for extraction and injection respectively. These system properties contain comma (or space) separated lists of propagation style to enable. For Datadog it is 'Datadog' for B3 the value is 'B3'. So to enable both styles one sets these properties to `Datadog B3'.
For extraction the order in which styles are specified is used when extracting and first headers successfully extracted are used.

Implement B3 headers extraction and injection

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/InstrumentationContextProvider.java
dd-java-agent/instrumentation/hibernate/core-3.3/core-3.3.gradle
dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/QueryInstrumentation.java
dd-java-agent/instrumentation/hibernate/core-4.0/core-4.0.gradle
dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/QueryInstrumentation.java
dd-java-agent/instrumentation/hibernate/core-4.3/core-4.3.gradle
dd-java-agent/instrumentation/hibernate/core-4.3/src/test/groovy/SpringJpaTest.groovy
dd-java-agent/instrumentation/hibernate/core-4.3/src/test/java/spring/Customer.java
dd-java-agent/instrumentation/hibernate/core-4.3/src/test/java/spring/CustomerRepository.java
dd-java-agent/instrumentation/hibernate/core-4.3/src/test/java/spring/PersistenceConfig.java

Fixing problems where muzzle prevents an integration from loading because the class for the new field being added may not be injected.  This resulted in an error:
```
Caused by: java.lang.NoClassDefFoundError: datadog/trace/bootstrap/instrumentation/context/FieldBackedProvider$ContextAccessor$org$hibernate$Session$datadog$trace$bootstrap$instrumentation$hibernate$SessionState
```

Fix NPE in hibernate instrumentation and fix InstrumentationContext+Muzzle

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/InstrumentationContextProvider.java
dd-java-agent/instrumentation/http-url-connection/src/test/groovy/HttpUrlConnectionTest.groovy

Currently helpers will not be injected if instrumentation doesn't
apply. Unfortunately it is possible for some classes to have context
fields added even if instrumentation is not allied (i.g. instrumented
classes are not used). Fix this by always injecting all helpers if we
inject context fields.

Fix helper injection in context provider

---

dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java
dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDApiTest.groovy
dd-trace-ot/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
dd-trace/src/test/groovy/datadog/trace/tracer/writer/AgentWriterTest.groovy

Failure to calculate this correctly causes the agent to drop the request.

Fix content length calculation for larger trace counts

---

buildSrc/src/main/groovy/MuzzlePlugin.groovy
dd-java-agent/instrumentation/datastax-cassandra-3/datastax-cassandra-3.gradle
dd-java-agent/instrumentation/datastax-cassandra-3/src/main/java/datadog/trace/instrumentation/datastax/cassandra/TracingSession.java

Recent versions of Guava removed method `Futures::transform(input, function)` in favor of `Futures::transform(input, function, executor)`.
Guava is one of the dependencies that we declare in `gradle/dependencies.gradle` and is pinned to `20.0` for Java 7 compatibility. This version is then used by the cassandra driver even if older versions are declared:
```
$ gradle -q :dd-java-agent:instrumentation:datastax-cassandra-3:dependencyInsight --dependency guava
com.google.guava:guava:20.0
variant "default+runtime" [
org.gradle.status = release (not requested)
Requested attributes not found in the selected variant:
org.gradle.usage  = java-api
]
Selection reasons:
- Was requested
- By conflict resolution : between versions 20.0, 16.0.1 and 19.0
com.google.guava:guava:20.0
\--- compileClasspath …
```

 Have cassandra integration to work with recent versions of Guava

---

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/aws-java-sdk-1.11.0.gradle
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWSClientTest.groovy
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test_before_1_11_106/groovy/AWSClientTest.groovy

Idea complains about duplicates root because we run latest dep tests
and 'later version' tests from the same dir. This is ultimately
TestSetd plugin bug by the looks of it, but we can work around it by
swapping old and new version tests.
Also run both old and new version tests under 'test' task.

Fix AWS instrumentation warning in Idea

---

CONTRIBUTING.md
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
dd-java-agent/testing/src/test/groovy/context/FieldBackedProviderTest.groovy
dd-java-agent/testing/testing.gradle

Class `FieldBackedProvider` uses ByteBuddy to add a field and its respective getters and setters to store the context object.
Assuming that we have a class `A` that implements runnable and that we wrap with a `FieldBackedProvider`
`Runnable` interfaces, if later on we use a cglib's `Enancher` class on `A` then the our mechanism will kick in again and try
to add the methods again. This causes a `java.lang.ClassFormatError: Duplicate method name "get__datadogContext$java$lang$Runnable" with signature "()Ljava.lang.Object;"`
to be thrown because CGLIB already copied over those methods from the original class `A` to the newly created class.
With this commit we now check that method were not previously defined before adding them, and if they were then we avoid adding them
again.
The reason why …

Make trace agent to work nicely with cglib library

---

dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

This should help reduce memory impact of large traces and reduce risk if scope is opened and never closed.

Set default value for partial trace flush to 1k

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/instrumentation/ratpack-1.4/src/main/java8/datadog/trace/instrumentation/ratpack/TracingHandler.java
dd-java-agent/instrumentation/reactor-core-3.1/src/main/java/datadog/trace/instrumentation/reactor/core/FluxAndMonoInstrumentation.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/TraceUtils.groovy
dd-java-agent/testing/src/test/groovy/AgentTestRunnerTest.groovy
dd-java-agent/testing/src/test/java/config/exclude/SomeClass.java
dd-java-agent/testing/src/test/java/config/exclude/packagename/SomeClass.java
dd-java-agent/testing/testing.gradle
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java

Add the following system property or corresponding environment variable:
```
dd.trace.classes.exclude=some.packagename.*,some.classname.MyClass$NestedClass
```

 Add config allowing classes to be excluded from transformation

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExceptionHandlers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVisitor.java

Avoid corrupting the class file for any subsequent Java agents.

Fixes #813: Only add frames if class file version supports attribute

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ByteBuddyElementMatchers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/DDLocationStrategy.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExceptionHandlers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ExceptionHandlerTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ResourceLocatingTest.groovy
dd-java-agent/instrumentation/osgi-classloading/osgi-classloading.gradle
dd-java-agent/instrumentation/osgi-classloading/src/main/java/datadog/trace/instrumentation/osgi/OSGIClassloadingInstrumentation.java
dd-java-agent/instrumentation/osgi-classloading/src/test/groovy/OSGIClassloadingTest.groovy
dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ClassLoadingTest.groovy

Glassfish’s WebappClassLoader caches when a resource or class load fails, so we can’t load as a resource first to see if it is available.
Also apply bootloader delegation automatically.
Related: https://github.com/eclipse-ee4j/glassfish/issues/22566

Improve classloading issues for OSGi and Glassfish.

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
dd-java-agent/testing/src/test/groovy/context/FieldBackedProviderTest.groovy

This should prevent the field from being serialized with the object.
@mar-kolya do you think it should be marked as volatile too?

Add transient modifier to added context fields.

---

dd-java-agent/instrumentation/ratpack-1.4/src/main/java8/datadog/trace/instrumentation/ratpack/RatpackServerDecorator.java
dd-java-agent/instrumentation/ratpack-1.4/src/test/groovy/RatpackTest.groovy

Previous fallback would inadvertently include query parameters in the resource name.

Fix resource name for Ratpack

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AbstractExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/Config.java

Or all executors, bypassing the allow list.
`dd.trace.executor=com.MyCustomExecutor,com.OtherExecutor`
`dd.trace.executors.all=true`
Turns out in many cases, executors that we say we’re skipping, are still being traced because they extend from an already instrumented executor. (Perhaps argument that we should just remove the allow list?)

Add config to enable individual executors

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java

Kafka message bundles with versions below 2 (e.d. 0.10) do not support
headers so do not inject them. Otherwise client gets really upset.

Do not send headers to old kafka servers

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy

So that spans inheriting from that client span have application
service name rather than 'kafka'

Set kafka client service name to application default service name.

---

dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy

So spans parented by consumer span had reasonable service name

Use default service name for RabbitMQ consumer

---

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
dd-java-agent/agent-jmxfetch/src/main/resources/jmxfetch-config.yaml
dd-java-agent/dd-java-agent.gradle
dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy
dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
gradle/java.gradle

JMXFetch is now enabled by default.  It can be disabled by adding the following:
* System Property: `dd.jmxfetch.enabled=false`
* Environment Variable: `DD_JMXFETCH_ENABLED=false`
Bundled jmx integrations must now be configured via (default still disabled):
* System Property `dd.jmxfetch.<integration>.enabled=true`
* Environment Variable `DD_JMXFETCH_<INTEGRATION>_ENABLED=true`
Expose new options for configuring JMXFetch with standard datadog-agent config files with `jvm_direct: true` set as an instance attribute (this will be ignored by the datadog-agent).
For Example:
* `dd.jmxfetch.config.dir=/opt/datadog-agent/etc/conf.d`
* `dd.jmxfetch.config=activemq.d/conf.yaml,jmx.d/conf.yaml`
will load jmx configs in those two files that have `jvm_direct: true` in their `instance` setup. …

Enable JMXFetch by default and add configs for more standard custom metrics

---

dd-java-agent/instrumentation/couchbase-2.0/couchbase-2.0.gradle

Looks like 2.7.5 has now fully propagated through the mirrors so we
can revert hack that made things compile.

Undo Couchbase gradle hack

---

dd-java-agent/agent-tooling/agent-tooling.gradle
dd-java-agent/instrumentation/glassfish/glassfish.gradle
dd-java-agent/instrumentation/grpc-1.5/grpc-1.5.gradle
dd-java-agent/instrumentation/hystrix-1.4/hystrix-1.4.gradle
dd-java-agent/instrumentation/instrumentation.gradle
dd-java-agent/instrumentation/java-concurrent/akka-2.5-testing/akka-2.5-testing.gradle
dd-java-agent/instrumentation/java-concurrent/akka-testing/akka-testing.gradle
dd-java-agent/instrumentation/java-concurrent/kotlin-testing/kotlin-testing.gradle
dd-java-agent/instrumentation/java-concurrent/scala-testing/scala-testing.gradle
dd-java-agent/instrumentation/jetty-8/jetty-8.gradle
dd-java-agent/instrumentation/jsp-2.3/jsp-2.3.gradle
dd-java-agent/instrumentation/okhttp-3/okhttp-3.gradle
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/rabbitmq-amqp-2.7.gradle
dd-java-agent/instrumentation/servlet-3/servlet-3.gradle
dd-java-agent/testing/testing.gradle

This ensures that `dd-tracng-ot` gets included into shadow jar.
Before this patch it was included only 'by accident' via some
transitive dependencies of some instrumentations.

Make agent-tooling compile-depend on dd-tracing-ot directly

---

gradle/dependencies.gradle

Due to new security vulerablility.

Update Jackson Databind to 2.9.9

---

dd-java-agent/instrumentation/akka-http-10.0/src/test/groovy/AkkaHttpClientInstrumentationTest.groovy

We already have a hack to wait for client span to close after the
request because it is closed on separate thread. This patch extends
that hack to handle cases when original request throws an exception.

Make Akka client test more stable

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/DatabaseClientDecorator.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/DatabaseClientDecoratorTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/HttpClientDecoratorTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/OrmClientDecoratorTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Additional integration testing to follow in separate PR.

Add `dd.trace.db.client.split-by-instance` Config

---

.circleci/config.yml
gradle/java.gradle

This change allows submodules to set `forceJdk` property to an array of JVM names that this module would want tests to be run on. For example setting that to `IBM8` would run tests on `IBM JVM` even if they otherwise would not (because for example they are java11 only).

Make test setup more flexible

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpClientDecorator.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpServerDecorator.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/HttpClientDecoratorTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/HttpServerDecoratorTest.groovy
dd-java-agent/instrumentation/okhttp-3/src/test/groovy/OkHttp3Test.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/DDTags.java

Removes duplicate strings in HttpServerDecorator and HttpClientDecorator by replacing with a constant in DDTags

Add "http.query.string" and "http.fragment.string" to DDTags

---

dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/NettyChannelPipelineInstrumentation.java
dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ClientTest.groovy

Our previous implementation of the netty's channel pipeline assumed that the only way to add `ChannelHandler` was through `ChannelPipeline#add*` methods called from some other service.
In reality it might happen (and this is what happens with reactor 0.8.* when it registers the `HttpServerCodec` that the `addLast` method is called from a concrete channel handler extending a `ChannelInitializer`. In this case new handler can be added while the parent channel handler is added, where the the `initChannel` method [can be used to add additional handlers]( https://github.com/netty/netty/blob/1ad47282c335323a3a244be91f619dcb97b69d20/transport/src/main/java/io/netty/channel/ChannelInitializer.java#L39).
This PR adds the possibility to handle such cases, while preventing recursions that our …

Calculate depth per-handler class in netty channel pipeline instrumentation

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInstrumentation.java

Trace 'records(TopicPartitions)` in kafka consumer

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInstrumentation.java

Reverts DataDog/dd-trace-java#908
It doesn't work and this might cause confusion.

Revert "Trace 'records(TopicPartitions)` in kafka consumer"

---

dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/util/AbstractCouchbaseTest.groovy
dd-java-agent/instrumentation/datastax-cassandra-3/src/test/groovy/CassandraClientTest.groovy
dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
dd-java-agent/instrumentation/jedis-1.4/src/test/groovy/JedisClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/MongoClientTest.groovy
dd-java-agent/instrumentation/spymemcached-2.12/src/test/groovy/datadog/trace/instrumentation/spymemcached/SpymemcachedTest.groovy

Some DB’s don’t define an instance, so verify the setting has no effect for them.

Additional testing for split-by-instance config

---

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java

This PR applies changes required to run JmxFetch application as a daemon. Before when CLI apps were running with Jmx fetch enabled they would not exit and hangs forever in some cases.
https://github.com/DataDog/jmxfetch/pull/237

Run JmxFetch app as a daemon

---

dd-java-agent/instrumentation/jetty-8/jetty-8.gradle
dd-java-agent/instrumentation/servlet-3/servlet-3.gradle

Alpha version of Jetty 1 was released and it seems to be compiled for
java versions above 8 so tests fail on java8.
Limit latest dep Jetty tests to Jetty 9 for now.

Avoid Jetty 10

---

dd-trace-java.gradle

It doesn't look like it is doing anything useful but instead it seems
to set version in resulting build jar which is not expected.

Remove version from gradle wrapper definition

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCConnectionUrlParser.java
dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCConnectionUrlParserTest.groovy

It’s not very interesting and breaks the definition of “instance” when we want to see the db name when no instance name is defined.

Remove default instance

---

dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/ContinuableScope.java
dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/SimpleScope.java
dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanBuilderTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy

We want to be able to use `NoopSpan` to temporarily remove the current trace from scope for a period. 
In our instrumentation, we sometimes capture the parent span on one thread to restore as the parent on a different thread.  If that parent is null, we should be able to indicate that state. We will do so with a `NoopSpan`.
For example:
We have an async http client request that starts in one thread and finishes in another thread.  We want the callback to have the correct trace context, but not necessarily be a child of the client span, so the best option is to provide the parent span as the scope for the callback. If there is no parent, we need to identify such even if there's an existing trace for some reason where the callback is being executed.

Assert span in scope can't be null and add tests to verify

---

dd-java-agent/instrumentation/akka-http-10.0/src/test/groovy/AkkaHttpClientInstrumentationTest.groovy
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/test/groovy/ApacheHttpAsyncClientCallbackTest.groovy
dd-java-agent/instrumentation/jax-rs-client-2.0/src/test/groovy/JaxRsClientAsyncTest.groovy
dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/AttributeKeys.java
dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientRequestTracingHandler.java
dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientResponseTracingHandler.java
dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ClientTest.groovy
dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/AttributeKeys.java
dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientRequestTracingHandler.java
dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientResponseTracingHandler.java
dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ClientTest.groovy
dd-java-agent/instrumentation/ratpack-1.4/src/latestDepTest/groovy/RatpackTest.groovy
dd-java-agent/instrumentation/ratpack-1.4/src/test/groovy/RatpackTest.groovy
dd-java-agent/instrumentation/vertx/src/test/groovy/VertxHttpClientTest.groovy
dd-java-agent/instrumentation/vertx/src/test/groovy/VertxRxServerTest.groovy
dd-java-agent/instrumentation/vertx/src/test/groovy/VertxRxWebClientTest.groovy
dd-java-agent/instrumentation/vertx/src/test/groovy/VertxServerTest.groovy
dd-java-agent/instrumentation/vertx/src/test/java/VertxRxWebTestServer.java
dd-java-agent/instrumentation/vertx/src/test/java/VertxWebTestServer.java
dd-java-agent/instrumentation/vertx/vertx.gradle
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/TraceUtils.groovy

Previously the scope was the http client span, which could result in deep nesting.  Now it is the parent span.
Before
```
[--------------Parent--------------]
[ ^-----------Client------------]
[ ^---Callback---]
````
Now:
```
[--------------Parent--------------]
[ ^ --Client----] [ ^--Callback--]
```
Also improve the tests.

Change the scope for the netty client callback

---

dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Attempt to get hostname in the following way:
1. Using environment variables
2. Using the `hostname` command
3. Using `InetAddress.getLocalHost().getHostName()` (network/DNS)
This method is faster, and generally more accurate (See [this discussion](https://stackoverflow.com/questions/7348711/recommended-way-to-get-hostname-in-java?answertab=votes#tab-top)).  Although almost always the same, when the environment vars and network disagree, the environment vars are usually more correct.
Marked as a *breaking change* because there could be situations where environment variables and network are not the same and the user expects it to use the network hostname.
**Testing**
This is inherently difficult to test in an automated fashion: Windows/Mac/Linux differences; Spock in an IDE gives a …

Better hostname detection

---

dd-smoke-tests/README.md
dd-smoke-tests/cli/cli.gradle
dd-smoke-tests/cli/src/main/java/datadog/smoketest/cli/CliApplication.java
dd-smoke-tests/cli/src/test/groovy/datadog/smoketest/CliApplicationSmokeTest.groovy
settings.gradle

This adds a smoke test that ensures CLI applications correctly exit when running under the java agent.  There are 2 parts:
1. A simple cli application that quits after a delay
2. The smoke test that checks to make sure that the cli application exits
I also manually tested and ensured that the test failed when JMXFetch.daemon = false.  This was the issue that prompted the creation of the test.

Cli Application Smoke Test

---

dd-java-agent/instrumentation/vertx/vertx.gradle

4.0.0-milestone1 was just released and is incompatible.

Limit Vert.x tests to 3.x

---

dd-java-agent/instrumentation/instrumentation.gradle
dd-java-agent/instrumentation/netty-4.0/netty-4.0.gradle
dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/HttpServerRequestTracingHandler.java
dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ServerTest.groovy
dd-java-agent/instrumentation/netty-4.0/src/test/groovy/NettyServerTestInstrumentation.java
dd-java-agent/instrumentation/netty-4.1/netty-4.1.gradle
dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/HttpServerRequestTracingHandler.java
dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ServerTest.groovy
dd-java-agent/instrumentation/netty-4.1/src/test/groovy/NettyServerTestInstrumentation.java
dd-java-agent/instrumentation/okhttp-3/src/test/groovy/OkHttp3Test.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTestAdvice.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/TraceUtils.groovy

Includes change to netty instrumentation so `fireChannelRead` is also called "in scope".

Base HttpServerTest and updated Netty test

---

dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationBasicTests.groovy
dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ServerTest.groovy
dd-java-agent/instrumentation/netty-4.0/src/test/groovy/NettyServerTestInstrumentation.java
dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ServerTest.groovy
dd-java-agent/instrumentation/netty-4.1/src/test/groovy/NettyServerTestInstrumentation.java
dd-java-agent/instrumentation/servlet-3/servlet-3.gradle
dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Decorator.java
dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/TagSettingAsyncListener.java
dd-java-agent/instrumentation/servlet-3/src/test/groovy/AbstractServlet3Test.groovy
dd-java-agent/instrumentation/servlet-3/src/test/groovy/JettyServlet3Test.groovy
dd-java-agent/instrumentation/servlet-3/src/test/groovy/ServletTestInstrumentation.java
dd-java-agent/instrumentation/servlet-3/src/test/groovy/TestServlet3.groovy
dd-java-agent/instrumentation/servlet-3/src/test/groovy/TomcatServlet3Test.groovy
dd-java-agent/instrumentation/spring-web/src/test/groovy/test/SpringBootBasedTest.groovy
dd-java-agent/instrumentation/vertx/src/test/java/VertxWebTestServer.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TraceAssert.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTestAdvice.java

Currently missing the authentication tests which need to be added to the parent, but other than that, testing is more thorough.
Discovered that trace propagation for Jetty Async is currently busted so I commented that portion of the test out until we can get it fixed.
Also discovered that incorrect status code was being set on async dispatch and span was being finished too early.

Migrate servlet tests to HttpServerTest and ignoreActiveSpan for "root"

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/DatadogClassLoader.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/DatadogClassLoaderTest.groovy
dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Constants.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ClassLoaderMatcherTest.groovy
dd-java-agent/dd-java-agent.gradle
dd-java-agent/instrumentation/couchbase-2.0/couchbase-2.0.gradle
dd-java-agent/instrumentation/jboss-classloading/src/test/groovy/JBossClassloadingTest.groovy
dd-java-agent/instrumentation/osgi-classloading/src/test/groovy/OSGIClassloadingTest.groovy
dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java
dd-java-agent/src/test/groovy/datadog/trace/agent/AgentLoadedIntoBootstrapTest.groovy
dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy
dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
dd-java-agent/src/test/java/jvmbootstraptest/AgentLoadedChecker.java
dd-java-agent/src/test/java/jvmbootstraptest/LogManagerSetter.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/SpockRunner.java

This pull request removes the need for some temporary jars by doing the following:
* Modifying `DatadogClassloader` to directly load from an internal jar without extracting the internal jar
* Combining `agent-bootstrap` with the main `dd-java-agent` jar at compile time and appending the combo to the bootstrap classpath at runtime
This helps with #429.  However, ByteBuddy still creates temp jars for dynamic injection

Eliminate temporary jars for instrumentation, jmxfetch, and bootstrap

---

dd-java-agent/instrumentation/elasticsearch/transport-2/transport-2.gradle
dd-trace-ot/dd-trace-ot.gradle
dd-trace/dd-trace.gradle
gradle/dependencies.gradle

As recommended by https://nvd.nist.gov/vuln/detail/CVE-2019-14379

Update Jackson to 2.9.9.3

---

buildSrc/src/main/groovy/MuzzlePlugin.groovy
buildSrc/src/main/resources/META-INF/gradle-plugins/version-scan.properties
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakMap.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentTooling.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Cleaner.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/DDCachingPoolStrategy.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakMapSuppliers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGradlePlugin.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceMatcher.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/CleanerTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/EvictingCacheProviderTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/WeakConcurrentSupplierTest.groovy
dd-java-agent/instrumentation/servlet-3/servlet-3.gradle
tooling/dd_jvm_stats.sh

The guava cache used internally wasn’t cleaning (releasing references to) the expired entries properly, resulting in excessive memory overhead.
This PR also increases the size of the cache but reduces the last used expiration window.
I also added some tests to verify the expected behavior of the cache.

Add cleaner thread to EvictingCacheProvider’s cache

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpServerDecorator.java
dd-java-agent/instrumentation/glassfish/glassfish.gradle
dd-java-agent/instrumentation/glassfish/src/main/java/datadog/trace/instrumentation/glassfish/GlassFishInstrumentation.java
dd-java-agent/instrumentation/glassfish/src/test/groovy/GlassFishServerTest.groovy
dd-java-agent/instrumentation/glassfish/src/test/groovy/GrizzlyTestInstrumentation.java
dd-java-agent/instrumentation/glassfish/src/test/groovy/TestServlets.java
dd-java-agent/instrumentation/glassfish/src/test/resources/WEB-INF/web.xml
dd-java-agent/instrumentation/glassfish/src/test/resources/error.jsp
dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyHttpHandlerInstrumentation.java
dd-java-agent/instrumentation/grizzly-2/src/test/groovy/GrizzlyTest.groovy
dd-java-agent/instrumentation/jax-rs-annotations/src/test/groovy/JerseyTest.groovy
dd-java-agent/instrumentation/jax-rs-client-1.9/src/main/java/datadog/trace/instrumentation/jaxrs/v1/JaxRsClientV1Instrumentation.java
dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyHandlerAdvice.java
dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/AsyncContextInstrumentation.java
dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy

Otherwise it can interfere with the more common Servlet instrumentation (changing the root span name).
To enable, add the following config:
* System Property: `dd.jmxfetch.grizzly.enabled=true`
* Environment Variable: `DD_JMXFETCH_GRIZZLY_ENABLED=true`
Unify attribute/property name for saving span on a request/context.
Also add tests for embedded GlassFish.

Disable Grizzly instrumentation by default

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/DatadogClassLoader.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java
dd-java-agent/dd-java-agent.gradle
dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java

The changes in #934 created an additional memory overhead of ~30MB because all internal jar files were kept in an in-memory map.  
With this pull request, only the `JarEntry` objects are kept in memory by packaging internal jars in their expanded state under a subfolder.
The `.class` extension has been changed to `.classdata` to prevent accidental classpath pollution.

Change packaging of internal jars

---

dd-java-agent/dd-java-agent.gradle
dd-java-agent/instrumentation/hibernate/core-3.3/core-3.3.gradle
dd-java-agent/instrumentation/hibernate/core-4.0/core-4.0.gradle
dd-java-agent/instrumentation/hibernate/core-4.3/core-4.3.gradle
dd-java-agent/instrumentation/http-url-connection/http-url-connection.gradle
dd-java-agent/instrumentation/java-concurrent/akka-2.5-testing/akka-2.5-testing.gradle
dd-java-agent/instrumentation/java-concurrent/akka-testing/akka-testing.gradle
dd-java-agent/instrumentation/java-concurrent/java-concurrent.gradle
dd-java-agent/instrumentation/java-concurrent/scala-testing/scala-testing.gradle
dd-java-agent/instrumentation/jdbc/jdbc.gradle
dd-trace/src/test/groovy/datadog/trace/tracer/SpanImplTest.groovy
dd-trace/src/test/groovy/datadog/trace/tracer/TracerTest.groovy
gradle/java.gradle

Enables all tests on all jdk platforms unless:
* `minJavaVersionForTests` or `maxJavaVersionForTests` is specified in Gradle
* `@Requires` is specified in the test file
Previously, all tests were only run on Java 7, Java 11, and OpenJDK 8.  Only a small subset of tests were run on other jdks ( java 9, java 10, zulu 8, ibm 8, java 12).
Enabling everything has had no adverse affect on CircleCI workflow duration because of how jobs are run in parallel.

Run all tests on all java versions

---

dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-ot/src/main/java/datadog/opentracing/propagation/HaystackHttpCodec.java
dd-trace-ot/src/main/java/datadog/opentracing/propagation/HttpCodec.java
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/HaystackHttpExtractorTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/HaystackHttpInjectorTest.groovy

Implementation to support #717

Added support for Haystack trace propagation

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/ServerDecorator.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/ServerDecoratorTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/server/http/TestHttpServer.groovy
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

The core changes are in Config and ServerDecorator.
Moved default tagging from Config::getRuntimeTags to Config::getLocalRootSpanTags.  This changes the result of Config::getMergedJmxTags as well.
To preserve language for servers changed ServerDecorator::afterStart.
Other changes are in tests - the most complicated part is in TagsAssert::defaultTags.  This now contains a bit too much conditional logic for my liking.

Ensure "client" spans do not set the language tag

---

dd-java-agent/instrumentation/akka-http-10.0/src/lagomTest/groovy/LagomTest.groovy
dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableChainTest.groovy
dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableTest.groovy
dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixTest.groovy
dd-java-agent/instrumentation/java-concurrent/akka-testing/src/test/groovy/AkkaActorTest.groovy
dd-java-agent/instrumentation/java-concurrent/kotlin-testing/src/test/groovy/KotlinCoroutineInstrumentationTest.groovy
dd-java-agent/instrumentation/java-concurrent/scala-testing/src/test/groovy/ScalaInstrumentationTest.groovy
dd-java-agent/instrumentation/java-concurrent/scala-testing/src/test/scala/ScalaAsyncChild.java
dd-java-agent/instrumentation/java-concurrent/src/slickTest/groovy/SlickTest.groovy
dd-java-agent/instrumentation/reactor-core-3.1/src/test/groovy/ReactorCoreTest.groovy
dd-java-agent/instrumentation/spring-webflux/src/test/groovy/SpringWebfluxTest.groovy
dd-java-agent/instrumentation/spring-webflux/src/test/groovy/dd/trace/instrumentation/springwebflux/server/EchoHandler.groovy
dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAdvice.java
dd-java-agent/instrumentation/trace-annotation/src/test/groovy/ConfiguredTraceAnnotationsTest.groovy
dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationsTest.groovy
dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceConfigTest.groovy

This should help reduce issues with multiple top level spans.

Apply fixed default operation name for @Trace generated spans

---

dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcServerBuilderInstrumentation.java
dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcServerDecorator.java
dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy

At the moment there is a discrepancy with how spans are tagged in the client interceptor vs the server interceptor. This PR is meant to synchronize the behavior between the two.

Fix span error tagging in grpc server interceptor

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
dd-trace-ot/src/main/java/datadog/trace/common/sampling/RateByServiceSampler.java
dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/HttpExtractorTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/HttpInjectorTest.groovy
dd-trace-ot/src/test/groovy/datadog/trace/api/sampling/RateByServiceSamplerTest.groovy

This change avoids lock contention in a hot code path.
I also added double check locking in ClassLoaderMatcher to reduce the need of locking there.

Remove synchronization from RateByServiceSampler

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/DDCachingPoolStrategy.java

Reduce default cache size in EvictingCacheProvider, and return a NoOp CacheProvider when classloader is going to be skipped.

Optimize DDCachingPoolStrategy

---

dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/ApacheHttpAsyncClientDecorator.java
dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientDecorator.java

This covers both Sync and Async versions.

Avoid unnecessary objects creation in Apache Http Client instrumnentation

---

dd-java-agent/instrumentation/akka-http-10.0/src/lagomTest/groovy/LagomTest.groovy
dd-java-agent/instrumentation/http-url-connection/src/test/groovy/UrlConnectionTest.groovy
dd-trace-ot/dd-trace-ot.gradle
dd-trace-ot/src/jmh/java/datadog/opentracing/decorators/URLAsResourceNameBenchmark.java
dd-trace-ot/src/main/java/datadog/opentracing/decorators/URLAsResourceName.java
dd-trace-ot/src/test/groovy/datadog/opentracing/SpanFactory.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/URLAsResourceNameTest.groovy

Using `new URL()` just to parse the path out was rather expensive.  This should improve the situation.

Reduce overhead of URLAsResourceName decorator

---

dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/CleanerTest.groovy

This increases the timeout in the `CleanerTest`. On my laptop, the test failed 100% of the time with a 90ms timeout and ~10% of the time with a 100ms timeout. There is some variable delay/warmup before the scheduledExecutor is up and running

Cleaner test timeout fix

---

dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringRepositoryTest.groovy

`repo.deleteAll()`  creates a variable number of traces depending on the state of the repo.  On an empty repo, it creates one trace; otherwise it creates "1+the number of objects in the repo".  The lead to a race condition between the traces returned by `setup()` and and invocation of `TEST_WRITER.clear()` that happened at the beginning of each test.
Instead of a generic setup()/cleanup(), each test is now responsible for cleaning up the repo and waiting for the appropriate number of traces.

Fix Couchbase tests: attempt i+1

---

dd-java-agent/instrumentation/kafka-clients-0.11/kafka-clients-0.11.gradle
dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle

Pinning spring-kafka @ 2.2 to fix breaking changin in spring-kafka-test 2.3
spring-kafka-test 2.3 moved ..rule.KafkaEmbedded to ..rule.EmbeddedKafkaRule
Tried using reflection as is done elsewhere in the tests, but that exposed a deeper incompatibility.

Pin spring-kafka at 2.2

---

dd-java-agent/instrumentation/vertx/src/test/groovy/client/VertxRxCircuitBreakerWebClientTest.groovy
dd-java-agent/instrumentation/vertx/src/test/groovy/server/VertxRxCircuitBreakerHttpServerTest.groovy

Vert.x made some [deprecations and breaking changes](https://github.com/vert-x3/wiki/wiki/3.8.2-Deprecations-and-breaking-changes) in the latest 3.x release that affected some methods we used for tests.  The rxJava Vert.x code is autogenerated so the deprecations move to method removal quicker
This pull request changes the tests to be backwards and forwards compatible in 3.x

Update vertx tests to play nice with latest version

---

dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringTemplateTest.groovy

The `setupSpec()` method of the test class called `couchbaseManager.info()`.  This creates a span.  Usually, these spans are created before the `clear()` call that happens before every test.  Rarely though, `clear()` is called before all of the spans from the setup have returned.  This creates a race condition for only the first test.
This pull request rectifies the race condition by waiting for the `setupSpec()` spans

Another couchbase test race condition

---

dd-java-agent/instrumentation/ratpack-1.4/src/main/java8/datadog/trace/instrumentation/ratpack/RatpackServerDecorator.java
dd-java-agent/instrumentation/spring-web/src/main/java/datadog/trace/instrumentation/springweb/SpringWebHttpServerDecorator.java

Setting `dd.trace.analytics.enabled=true` enables analytics events in general and toggles "web server integrations" specifically to generate events.  For most web integrations, this works as expected.  For Spring, however, each request created 2-4 events (servlet, handler, controller, render) depending on on the type of request.
This pull request disables these extra events by default for Spring and Ratpack.  They will still produce a single event per request for `servlet` and `netty` respectively.  All other web server integrations already only produce one event per request.
To reenable, a user can set `dd.spring-web.analytics.enabled=true` and/or `dd.ratpack.analytics.enabled=true` as they would for any other integration.
Automated testing is very difficult in this situation.  It would …

Change default for Spring and Ratpack analytics to be off

---

dd-java-agent/instrumentation/osgi-classloading/src/main/java/datadog/trace/instrumentation/osgi/OSGIClassloadingInstrumentation.java
dd-java-agent/instrumentation/osgi-classloading/src/test/groovy/OSGIClassloadingTest.groovy

The OSGi instrumentation incorrectly overrode the bootstrap delegation property when run more than once.  This removed any custom values previously set and caused startup issues.
This pull request fixes that bug and adds some tests.

Fix OSGi bootstrap delegation property

---

dd-java-agent/instrumentation/netty-4.1/netty-4.1.gradle
dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ClientTest.groovy
dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAdvice.java

This pull request enables async propagation for the `@Trace` annotation instrumentation.
Without async propagation, annotating a method that calls an async instrumentation results in broken traces.  The accompanying addition to the netty4.1 tests illustrates this point.

Enable Async Propagation for @Trace Annotatation instrumentation

---

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
gradle/dependencies.gradle

This is primarily motivated by new CVE’s.
Upgrade jmxfetch to 0.32.1 which has the same change.

Upgrade Jackson to 2.10.0

---

dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java
dd-java-agent/src/test/groovy/datadog/trace/agent/LogLevelTest.groovy
dd-java-agent/src/test/java/jvmbootstraptest/LogLevelChecker.java

Priority: datadog.slf4j.simpleLogger.defaultLogLevel > dd.trace.debug > DD_TRACE_DEBUG
Tests written in LogLevelTest.groovy

new configuation key for setting debug log level

---

utils/test-utils/src/main/groovy/datadog/trace/util/test/DDSpecification.groovy

Loading `Config` in static section of `DDSpecification` happens before
bootstrap jar has been setup. This in turn causes problems down the
road because some of the classes are later loaded from bootstrap and
confuse things.

Avoid loading `Config` in `DDSpecification`

---

dd-trace-ot/dd-trace-ot.gradle
dd-trace-ot/src/compatabilityTest/groovy/OT31ApiTest.groovy

In preparation for merging #641

Add compatibility tests for OpenTracing 0.31.0

---

dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java

There’s still a possibility of a race condition and we could catch and handle the exception, but this should reduce the shutdown noise a bit.

Avoid submitting a job if executor is shutdown

---

dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java
dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/HostAndRequestAsHttpUriRequest.java
dd-java-agent/instrumentation/apache-httpclient-4/src/test/groovy/ApacheHttpClientTest.groovy

Previously, we only instrumented some of the `execute(...)` methods in Apache HttpClient.  This caused missing instrumentation for both direct Apache HttpClient users and users of frameworks that used Apache HttpClient (eg Zuul)

Add instrumentation for all of Apache HttpClient methods

---

dd-trace-ot/src/main/java/datadog/opentracing/ContainerInfo.java

Previously, an empty proc file cause a parse error to be thrown.  This pull request changes the behavior and treats an empty proc file the same as a missing proc file.

Treat empty proc file as `Not Running In Container`

---

dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java

While “tracing.agent” matches the class name, this applies to the whole tracer where most things are labeled just “trace” (ie, config).

Reduce tracer log line length - make name nicer

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/instrumentation/api/AgentSpan.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/instrumentation/api/AgentTracer.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/OpenTracing32.java
dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/JaxRsAnnotationsDecorator.java
dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/JaxRsAnnotationsInstrumentation.java
dd-java-agent/instrumentation/jax-rs-annotations-2/src/test/groovy/DropwizardTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerAdapterInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/SpringWebHttpServerDecorator.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/SpringBootBasedTest.groovy

For spring:
* Move more logic to the decorator.
* Use a fixed operation name, but set the resource name.
* Rename the root span instead of the parent span (If there are other spans in between this could make a difference.)  Not sure what impact this would have if multiple controllers are called (ie, forward/include).
For Jax-rs:
* Rename the root span instead of the parent span (same concern as above with spring)

Refactor JAX-RS Annotation and Spring Controller/Handler Instrumentation

---

dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
dd-trace-ot/dd-trace-ot.gradle
dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/Writer.java
dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDApiTest.groovy

A cleaned-up version of the original health monitoring branch/pull request - #1049 
The approach and final result are the same, but with a hopefully less noisy and easy to follow history.
This change introduces 2 significant API additions...
- DDApi.Response
- DDAgentWriter.Monitor
DDApi.Response replaces the prior boolean return values for the DDApi send methods.
Response.success() provides the same boolean result as previously returned.
But Response also carries...
- http response status
- exception - for both failed communication & malformed agent responses
- JSON payload
That additional information is used by the new DDAgentWriter.Monitor-s for metrics gathering.
By default, DDAgentWriter uses a NoopMonitor that maintains the same behavior as before -- including designing the Monitor …

Health Metrics

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/instrumentation/api/AgentScope.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/instrumentation/api/AgentTracer.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/OpenTracing32.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/ServletRequestSetter.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/RequestDispatcherDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/RequestDispatcherInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/ServletContextInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/filter/FilterDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/filter/FilterInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseInstrumentation.java
dd-java-agent/instrumentation/servlet/src/test/groovy/FilterTest.groovy
dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletResponseTest.groovy
dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletTest.groovy
dd-java-agent/instrumentation/servlet/src/test/groovy/RequestDispatcherTest.groovy
dd-java-agent/instrumentation/servlet/src/test/groovy/RequestDispatcherUtils.java

Disabled by default, and only creates a span if existing trace detected.
To enable all of them:
* System Property: `-Ddd.integration.servlet.enabled=true`
* Environment Variable: `DD_INTEGRATION_SERVLET_ENABLED=true`
(They have independent configs as well.  If needed, view the source below.)

Add new integration for Servlet Filters, HttpServlet, and RequestDispatcher

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DataSourceDecorator.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DataSourceInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DriverInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy

Disabled by default, and only creates a span if existing trace detected.
To enable:
* System Property: `-Ddd.integration.jdbc.enabled=true`
* Environment Variable: `DD_INTEGRATION_JDBC_ENABLED=true`
(Or more specifically `jdbc-datasource`.)

Add span when calling DataSource.getConnection with a trace.

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DataSourceDecorator.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DataSourceInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/RequestDispatcherDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/RequestDispatcherInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/ServletContextInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/filter/FilterDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/filter/FilterInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseInstrumentation.java
dd-java-agent/instrumentation/servlet/src/test/groovy/FilterTest.groovy
dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletResponseTest.groovy
dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletTest.groovy
dd-java-agent/instrumentation/servlet/src/test/groovy/RequestDispatcherTest.groovy

Postfix the existing config names with `-beta` for `servlet` and `jdbc`.
To avoid any risk that the config was explicitly enabled for an unrelated reason resulting in unexpected behavior when upgrading to the latest version.

Rename config key for beta/experimental instrumentation.

---

.circleci/config.yml

OkHttp seems to be inadvertently loading the java log manager.

Disable zulu8 test for time being due to test incompatibility

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java

This change excludes classes generated by Eclipse Sisu (part of Equinox DS).
These classes are created by https://github.com/eclipse/sisu.inject/blob/master/org.eclipse.sisu.inject/src/org/eclipse/sisu/space/CloningClassSpace.java
To the best of my understanding, the generated classes extends a class for which SISU wishes to defer loading.  Interestingly, the generated class simply implements a no-arg constructor and nothing more regardless of the class being extended / deferred.

Excluded classes generated by Eclipse Sisu

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java

Minor change to print all instrumentation names instead of just the primary named when an instrumentation is muzzled.  Helps with debugging.

Print all instrumentation names when muzzled

---

dd-java-agent/instrumentation/play-ws-1/src/main/java/datadog/trace/instrumentation/playws1/AsyncHandlerWrapper.java
dd-java-agent/instrumentation/play-ws-1/src/main/java/datadog/trace/instrumentation/playws1/HeadersInjectAdapter.java
dd-java-agent/instrumentation/play-ws-1/src/main/java/datadog/trace/instrumentation/playws1/PlayWSClientDecorator.java
dd-java-agent/instrumentation/play-ws-1/src/main/java/datadog/trace/instrumentation/playws1/PlayWSClientInstrumentation.java
dd-java-agent/instrumentation/play-ws-1/src/test/groovy/PlayWSClientTest.groovy
dd-java-agent/instrumentation/play-ws-2/src/main/java/datadog/trace/instrumentation/playws2/AsyncHandlerWrapper.java
dd-java-agent/instrumentation/play-ws-2/src/main/java/datadog/trace/instrumentation/playws2/HeadersInjectAdapter.java
dd-java-agent/instrumentation/play-ws-2/src/main/java/datadog/trace/instrumentation/playws2/PlayWSClientDecorator.java
dd-java-agent/instrumentation/play-ws-2/src/main/java/datadog/trace/instrumentation/playws2/PlayWSClientInstrumentation.java
dd-java-agent/instrumentation/play-ws-2/src/test/groovy/PlayWSClientTest.groovy

The fixes the play-ws instrumentation.  Previously, both the play-ws-1 and play-ws-2 instrumentations were in the `datadog.trace.instrumentation.playws` Java package.  When the dd-java-agent jar was created, only one set of classes was included.

Move play-ws-1 and play-ws-2 into separate packages

---

dd-java-agent/instrumentation/jsp-2.3/src/main/java/datadog/trace/instrumentation/jsp/JasperJSPCompilationContextInstrumentation.java

Changing Jasper instrumentation to not load the advice class.
This class was missed originally because it doesn't end in Advice.

Eliminate class expression to Advice class

---

dd-trace-ot/src/main/java/datadog/trace/common/sampling/DeterministicSampler.java
dd-trace-ot/src/main/java/datadog/trace/common/sampling/RateByServiceSampler.java
dd-trace-ot/src/main/java/datadog/trace/common/sampling/RuleBasedSampler.java
dd-trace-ot/src/test/groovy/datadog/trace/api/sampling/DeterministicSamplerTest.groovy

`KnuthSampler` was potentially confusing without any references to the particular algorithm.  This pull request instead uses the generic name `DeterministicSampler` instead.

Rename KnuthSampler to DeterministicSampler

---

.circleci/config.yml

See https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/29

Fix CircleCI muzzle build running out of memory

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java

This pull request makes some changes to `HelperInjector` to reduce memory usage, increase performance, and decrease the chance of deadlocks.
The `helperMap` was an injector-local cache of the `byte[]` representation of an instrumentation's helper classes.  Since each instrumentation has its own `HelperInjector`, each instrumentation had its own `helperMap`.  These arrays were never reclaimable by GC.
The performance impact of removing this cache should be negligible because:
- the helper classes are still only loaded once per target `classloader`
- the `DatadogClassloader` has its own internal class cache
There is only one `unnamed module` per classloader.  The new code takes advantage of this fact.
Internally, bytebuddy locks the `classloader` being injected.  The synchronization block …

HelperInjector optimization

---

dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/JaxRsAsyncResponseInstrumentation.java

In light of all the muzzle failures, I missed a real one when I merged the jax-rs annotation pull request.  This fixes the issue by adding the new helper classes to this other instrumentation

Fix muzzle issue with Jax-rs async instrumentation

---

dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringRepositoryTest.groovy

Hi all!
This is helping to resolve the sporadic test failures in `Elasticsearch53SpringRepositoryTest`, see https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/28.

Fix sporadic test failure in Elasticsearch53SpringRepositoryTest

---

dd-trace-ot/src/main/java/datadog/opentracing/ContainerInfo.java

Tested on docker. Although "/proc/self/cgroup" file is not empty, "/proc/self/cgroup".toFile().length() returns 0
as does Files.size("/proc/self/cgroup") so we should check that the content is not empty after reading it.

AllowUstoGetContainerInfoOnDocker

---

dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy

To prevent unbounded memory consumption, restricting the size of the sender queue.  Also, lowering the size of the Disruptor queue.
Unfortunately, our choice of a ScheduledExecutorService makes this a bit difficult, since ScheduledExecutorService doesn't allow us to supply the queue.
A bigger change is in-order but for now, this change restricts the queue size by introducing a Semaphore around the ScheduledExecutorService.
In effort to making testing easier, I introduced Monitor.onFlush.  This is used in the new slow response test which attempts to simulate a situation where the sending queue would back up.
To my chagrin, the current test doesn't fail reliably when the queue is unbounded; however, it does fail.

Restricting sender queue size

---

dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy

Prior to this change, DDSpanBuilder.withTag behaves different than DDSpan.setTag when decorators are triggered.
Specifically builder.withTag(a, val).withTag(b, val) can behave differently than span.setTag(a, val); span.setTag(b, val)
This change makes a small step towards determinism by changing the HashMap inside DDSpanBuilder into a LinkedHashMap.  That guarantees the tags from withTags translated to the same sequence of setTag calls.
The order of setTag calls is important when there's an interaction between decorators.
For instance, the PeerServiceDecorator and the ServiceNameDecorator.
Some test cases that were previously failing have been added to confirm consistency.
NOTE: Even with this change, there are inconsistencies when tags are removed or set to an empty value.

Ordering inconistency with DDSpanBuilder.withTag

---

dd-java-agent/instrumentation/play-2.6/play-2.6.gradle

Play 2.8 results in a muzzle failure:
```
datadog.trace.instrumentation.play26.PlayHttpServerDecorator:69 Missing method underlying#()Lplay/api/libs/typedmap/TypedKey;
```
This terminates the muzzle spec at <2.8.0.  Play 2.8 support can be added later.

End Play 2.6 muzzle spec at 2.8 because its breaking

---

dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Decorator.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Decorator.java

This is needed in order to tag the query string (when configured).
Full test suite will follow in future PR.

Capture full servlet URL in decorator

---

dd-java-agent/instrumentation/kafka-clients-0.11/kafka-clients-0.11.gradle
dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle

2.4.0 introduces test failures:
```
Caused by: java.lang.NoClassDefFoundError: org.I0Itec.zkclient.ZkClient
```
when executing `compileLatestDepTestGroovy`.

Pin kafka latestDepTest version to 2.3.x

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
dd-java-agent/src/test/groovy/datadog/trace/agent/AgentLoadedIntoBootstrapTest.groovy
dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy

An invalid statsd hostname causes an exception for jmxfetch.  This should be an error, but not prevent the app from starting.
Also improved log variable name consistency.

Add better exception handling in Agent initialization

---

dd-java-agent/instrumentation/google-http-client/src/test/groovy/AbstractGoogleHttpClientTest.groovy
dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java

This is currently only used by the GoogleHttpClient instrumentation, but may be used by customers too.

Capture error message even if no exception object provided.

---

buildSrc/src/main/groovy/MuzzlePlugin.groovy
dd-java-agent/instrumentation/http-url-connection/http-url-connection.gradle
dd-java-agent/instrumentation/java-concurrent/java-concurrent.gradle
dd-java-agent/instrumentation/jdbc/jdbc.gradle

This is still useful to validate various aspects of the integrations even if it doesn't need to check against maven.
@pawelchcki this should be helpful for your PR: #1128

Add option for muzzle validation on the specific JDK version

---

dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-ot/src/main/java/datadog/opentracing/decorators/DDDecoratorsFactory.java
dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy

Adds the ability to disable individual decorators with config.
Closes #1143

Disable decorators via config

---

dd-java-agent/instrumentation/jax-rs-client-2.0/src/main/java/datadog/trace/instrumentation/jaxrs/JaxRsClientInstrumentation.java
dd-java-agent/instrumentation/jax-rs-client-2.0/src/test/groovy/JaxMultithreadedClientTest.groovy

The `ClientBuilder` for JAX-RS is generally not thread safe, sometimes lazily resolved, and could be reused multiple times.  With the old instrumentation, this could lead to `register(..)` being called multiple times from the same or different threads.
This pull request changes the registration to be called at most once on the `Client` instead of the `ClientBuilder`.  I believe this closes #380.
----
The included test did not fail with the old code but it did produce a lot of log errors and warnings from JAX-RS.

JAX-RS ClientBuilder thread safety

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsProcessorInstrumentation.java

Similar to what we do elsewhere.  We want to allow async propagation if we don't think there is significant risk of getting the trace caught forever.  This isn't guaranteed, but a slow rollout of this has seemed to do well thus far.

Add async propagation flags for kafka consumer.

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java
dd-java-agent/instrumentation/jax-rs-annotations-1/jax-rs-annotations-1.gradle
dd-java-agent/instrumentation/jedis-1.4/jedis-1.4.gradle
dd-java-agent/instrumentation/servlet/request-2/request-2.gradle

- Adds the classloader matcher to the muzzle scan.
- Updates the muzzle directives of the three projects that use `classLoaderHasClasses`

Add classloader matcher to muzzle scan

---

dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/client/RmiClientDecorator.java
dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/server/RmiServerDecorator.java

- Add missing `rmi-client` and `rmi-server` instrumentation names to respective Decorators.
- remove default client service name to avoid extra hop in service map

[rmi] add instrumentation names to client and server decorators, remove default client service name

---

dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
dd-trace-ot/src/main/java/datadog/trace/common/sampling/RateByServiceSampler.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/Writer.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/ddagent/DDAgentResponseListener.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/ddagent/DisruptorEvent.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/ddagent/Monitor.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/ddagent/TraceConsumer.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/ddagent/TraceSerializingDisruptor.java
dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentApiTest.groovy
dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
dd-trace-ot/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy

Current class has grown too big and difficult to maintain.  This series of commits attempts to split them up in simple refactoring steps to demonstrate functionality hasn't changed.
Future refactor task is to split serialized traces onto a separate disruptor and apply back-pressure and retry logic.

Split DDAgentWriter into smaller classes

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ByteBuddyElementMatchers.java

Instead of filtering then iterating, just iterate through everything and apply filter inline.
This will help avoid allocation for filter iterator and improve if early match is found.
(See discussion here: https://github.com/raphw/byte-buddy/issues/772#issuecomment-571503721)

Optimize HasSuperMethodMatcher logic

---

dd-java-agent/instrumentation/couchbase-2.0/couchbase-2.0.gradle
dd-java-agent/instrumentation/couchbase-2.6/couchbase-2.6.gradle

They recently released 3.0.0 which is not compatible with our instrumentation.

Adjust version compatibility to only 2.x

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DataSourceDecorator.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DataSourceInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/HttpServletRequestExtractAdapter.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Instrumentation.java
dd-java-agent/instrumentation/servlet/servlet.gradle
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/ServletRequestSetter.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/RequestDispatcherDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/RequestDispatcherInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/ServletContextInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/filter/FilterDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/filter/FilterInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseInstrumentation.java
dd-java-agent/instrumentation/servlet/src/test/groovy/FilterTest.groovy
dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletResponseTest.groovy
dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletTest.groovy
dd-java-agent/instrumentation/servlet/src/test/groovy/RequestDispatcherTest.groovy
dd-java-agent/instrumentation/servlet/src/test/groovy/RequestDispatcherUtils.java

This PR adds back instrumentation that was previously reverted and enables some by default that are less likely to change the trace size significantly.
Original PR: #1050
Revert PR: #1085
I also adjusted the instrumentation for servlet forward/include to remove the span from the request so the resource name doesn't get stomped on by subsequent child calls.

Add servlet integrations for request and response dispatch back in.

---

gradle/dependencies.gradle

Updates from 1.10.4 to 1.10.6 .  The most notable change is that 1.10.5 fixes the maven source code attachment for Bytebuddy that's been broken for a few releases (breaking IDE integration)

Update bytebuddy to 1.10.6

---

buildSrc/build.gradle.kts
buildSrc/src/main/groovy/MuzzlePlugin.groovy
buildSrc/src/test/groovy/RangeQueryTest.groovy

Also add a test.
Muzzle tasks were failing because maven central is now blocking non-https requests.  This should fix that.

Update muzzle maven URL to use https

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakMap.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/WeakMapTest.groovy
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/DDCachingPoolStrategy.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakMapSuppliers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceMatcher.java
dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/AttributeKeys.java
dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/AttributeKeys.java

As part of the audit of `synchronized` blocks, I noticed a repeated pattern around WeakMap caches:
```java
synchronized (cache) {
value = cache.get(key);
if (value == null) {
value = .......
cache.put(key, value);
}
return value;
}
```
We had `getOrCreate()` but `ValueSupplier.get()` didn't take the key as an argument.  This pull request:
- Renames `getOrCreate()` to `computeIfAbsent()` (the Java 8 name for this method)
- Changes `ValueSupplier.get()` to take a key
- Simplifies the code wherever this pattern was used
In the future, adjusting or improving WeakMap locking will benefit all callers.
Additionally, I removed the unused `ClassLoaderMatcher`s of `classLaderHasClassWithMethod` and `classLoaderHasClassWithField`

Synchronized audit: WeakMap computeIfAbsent

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java

Before:
`JarInputStream` -> `ByteArrayOutputStream` -> `byte[]` (stored) -> `ByteArrayInputStream`
Now:
`JarInputStream`
The internal steps were vestigial from when the full bytes of every class was cached at startup.  This change shaves 6MB in old gen memory usage.

Use streams directly in DatadogClassLoader

---

dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
dd-trace-ot/src/main/java/datadog/trace/common/sampling/Sampler.java
dd-trace-ot/src/test/groovy/datadog/trace/api/sampling/RuleBasedSamplingTest.groovy

`trace.sampling.default.rate` -> `trace.sample.rate`
`trace.sampling.rate.limit` -> `trace.rate.limit`

Rename Rule Based Sampling properties

---

dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/ContextualScopeManager.java
dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/ContinuableScope.java
dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/DDScope.java
dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/SimpleScope.java
dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy

When limit is exceeded, a NoopScope is returned.
Allow custom ScopeManager to be provided, with the plan to remove `ScopeContext` customization in the future.

Add limit to trace scope depth

---

dd-java-agent/instrumentation/hibernate/src/main/java/datadog/trace/instrumentation/hibernate/HibernateDecorator.java

It seems that sometimes in later versions of hibernate the entities of type list will contain null as their first element. It is unclear whether other elements in the list are not null, or if there even would be a case where the list has a length greater than 1 and contained a null.

Add null check to hibernate decorator

---

dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/RequestDispatcherInstrumentation.java
dd-java-agent/instrumentation/servlet/src/test/groovy/RequestDispatcherTest.groovy
dd-java-agent/instrumentation/servlet/src/test/groovy/RequestDispatcherUtils.java

Clearing the span caused traces to be broken up and reported independently when calling forward/include.
#1195

Set dispatcher span on request instead of clear

---

dd-trace-ot/dd-trace-ot.gradle
dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java
dd-trace-ot/src/main/java/datadog/opentracing/DDSpanContext.java
dd-trace-ot/src/main/java/datadog/trace/common/sampling/RateByServiceSampler.java
dd-trace-ot/src/main/java/datadog/trace/common/serialization/FormatWriter.java
dd-trace-ot/src/main/java/datadog/trace/common/serialization/JsonFormatWriter.java
dd-trace-ot/src/main/java/datadog/trace/common/serialization/MsgpackFormatWriter.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/LoggingWriter.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/ddagent/DDAgentResponseListener.java
dd-trace-ot/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingDisruptor.java
dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanSerializationTest.groovy
dd-trace-ot/src/test/groovy/datadog/trace/api/sampling/RateByServiceSamplerTest.groovy
dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentApiTest.groovy
dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
dd-trace-ot/src/test/groovy/datadog/trace/api/writer/LoggingWriterTest.groovy
dd-trace-ot/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
gradle/dependencies.gradle

Reduced the size of dd-java-agent jar by about 2 MB.  Jackson is not removed completely though as it is still a dependency of jmxfetch.
Trace serialization is primarily done directly with msgpack.
Response deserialization and LoggingWriter serialization is done with mochi.
Msgpack Serialization buffer still not being reused though.
(PR based off of #1161... that should be merged first.  So focus on the [last commit](https://github.com/DataDog/dd-trace-java/pull/1185/commits/c3404ea61ce197f2bb3d278a9e66928d9405ae17).)

Remove Jackson from dd-trace-ot

---

CONTRIBUTING.md
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java

Specify explicit AgentInstaller class loader instead of storing reference to context class loader in current thread object. We can install agent by [ServiceLoader::load(Class, ClassLoader)](https://hg.openjdk.java.net/jdk7u/jdk7u-dev/jdk/file/70e3553d9d6e/src/share/classes/java/util/ServiceLoader.java#l470) and without this call 
https://hg.openjdk.java.net/jdk7u/jdk7u-dev/jdk/file/70e3553d9d6e/src/share/classes/java/util/ServiceLoader.java#l498

Reduce use of Thread::setContextClassLoader and hard references to DatadogClassLoader

---

dd-java-agent/instrumentation/hibernate/core-4.3/core-4.3.gradle

Based on changes made in [this PR](https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/143).

Limit Hibernate latest dependency test to 5.x

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/DatadogClassLoader.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/DatadogClassLoaderTest.groovy
dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ClassLoaderMatcherTest.groovy
dd-java-agent/dd-java-agent.gradle
dd-java-agent/instrumentation/http-url-connection/src/test/groovy/UrlConnectionTest.groovy
dd-java-agent/instrumentation/instrumentation.gradle
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/SpockRunner.java
gradle/dependencies.gradle

With this pull request, the agent classloader and jmx-fetch classloader share a common parent.  Added to the parent classloader are the libraries shared between them (currently only dogstatsd and guava).
**The main changes are:**
* Adding the parent in `Agent.java`
* Changing the packaging in gradle fo another internal jar
**The benefits are:**
| | 0.43.0-SNAPSHOT (post jackson removal) | This Pull |
| ------------- | ------------- | ------------- |
| dd-java-agent.jar file size | 20.8  | 15.2  |
| Old used (memcheck)  | 16.26 | 14.27 |
| Old comm (memcheck) | 156 | 152 |
plus minor decreases across other memory metrics.
Follow on work may include integrating `BootstrapProxy` into the hierarchy and changing the `DatadogClassloader`s not to inherit from `URLClassloader`

Shared classloader for agent and jmx-fetch

---

dd-java-agent/instrumentation/elasticsearch/transport-2/src/main/java/datadog/trace/instrumentation/elasticsearch2/TransportActionListener.java
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy

Related [issue](https://github.com/DataDog/dd-trace-java/issues/1210).

Fix NPE on TransportActionListener for elasticsearch 2

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakMapSuppliers.java

for each call to get method in WeakConcurrentMap, a LatentKey is
created. Considering the frequency of call it's significant.
Also, the classloader of the tracer can be considered as permanent
through the lifecycle of the JVM which is a prerequisite to be able
to reuse keys (otherwise classloader leak).

Enable reuseKeys on WeakConcurrentMap

---

dd-trace-ot/src/main/java/datadog/opentracing/DDSpanContext.java
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
dd-trace-ot/src/main/java/datadog/opentracing/PendingTrace.java
dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanBuilderTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanSerializationTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/PendingTraceTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/SpanFactory.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/URLAsResourceNameTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/B3HttpInjectorTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/DatadogHttpInjectorTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/HaystackHttpInjectorTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/HttpInjectorTest.groovy
dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
dd-trace-ot/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy

This allows the service name to be updated immediately instead of when the span is finished.
This is important because child spans inherit service name from the parent.

Move serviceNameMappings processing to DDSpanContext

---

dd-java-agent/instrumentation/jax-rs-annotations-1/src/main/java/datadog/trace/instrumentation/jaxrs1/JaxRsAnnotationsInstrumentation.java
dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/JaxRsAnnotationsInstrumentation.java

Paranthesys was missplaced leading to more complicated matcher than needed

Fix JaxRs matching

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java

To test the effectiveness of this change, a sample spring app was run multiple times with tracer 0.43.0 and 0.44.0 (the tracer with these changes) on non-debug mode. The average start-up time is shown below:
0.43.0 -> 12.996 s
0.44.0 -> 12.196 s
Not adding the listener on non-debug mode shaves a bit of time off start-up.

Create AgentBuilder with logging listeners only if in debug mode

---

dd-trace-ot/dd-trace-ot.gradle
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
dd-trace-ot/src/main/java/datadog/opentracing/StringCachingBigInteger.java

I'm currently testing out the new datadog profiling feature and am seeing a high number of MutableBigIntegers being allocated. Because it was pretty much exclusively due to `toString()`, I've created a simple wrapper that caches the result, which will (hopefully) reduce our overhead of logging the same trace id multiple times.

Cache the result of toString in BigInteger

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
dd-java-agent/instrumentation/cdi-1.2/src/test/groovy/CDIContainerTest.groovy
dd-java-agent/instrumentation/cdi-1.2/src/test/java/TestBean.java

Removing these matchers caused the time spent matching ignores in my sample app to go from greater than 1 second to less than 100 ms.

Remove costly matchers from ignore list

---

dd-java-agent/instrumentation/jsp-2.3/jsp-2.3.gradle

```
Instrumentation muzzled: [jsp, jsp-compile] -- datadog.trace.instrumentation.jsp.JasperJSPCompilationContextInstrumentation on jdk.internal.loader.ClassLoaders$AppClassLoader@2c13da15
-- datadog.trace.instrumentation.jsp.JSPDecorator:39 Missing method getServletContext#()Ljavax/servlet/ServletContext;
```

Tomcat 10.0.0-M1 release seems to have some issues

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ClassLoaderMatcherTest.groovy

string-switch statement  seems to be 0.5 seconds faster than HashSet::contains on petclinic app

SkipClassLoaderMatcher use str-switch in shouldSkipClass(ClassLoader)

---

dd-trace-ot/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentApiTest.groovy
dd-trace-ot/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy

This should remove http request from critical path during app load

Determine agent URL version on first upload call

---

dd-java-agent/benchmark/benchmark.gradle
dd-java-agent/benchmark/src/jmh/java/datadog/benchmark/ClassRetransformingBenchmark.java
dd-java-agent/benchmark/src/jmh/java/datadog/benchmark/classes/C.java
dd-java-agent/benchmark/src/jmh/java/datadog/benchmark/classes/D.java
dd-java-agent/benchmark/src/jmh/java/datadog/benchmark/classes/E.java
dd-java-agent/benchmark/src/jmh/resources/dd-trace.yaml
dd-trace-ot/dd-trace-ot.gradle

Benchmark is run with `./gradlew :dd-java-agent:benchmark:jmh` -- after updating the absolute paths to the various agents in `ClassRetransformingBenchmark`.  Unfortunately I was unable to have it launch correctly with a relative path.

Update JMH benchmarks

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ByteBuddyElementMatchers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/GlobalIgnoresMatcher.java
dd-java-agent/instrumentation/jax-rs-annotations-1/src/main/java/datadog/trace/instrumentation/jaxrs1/JaxRsAnnotationsInstrumentation.java
dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/JaxRsAnnotationsInstrumentation.java

This doesn't seem to provide immediate perf impact, but this should simplify matcher optimization later.

Single ignores matcher

---

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/RequestInstrumentation.java
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsClientInstrumentation.java
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsHttpClientInstrumentation.java
dd-java-agent/instrumentation/couchbase-2.6/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseNetworkInstrumentation.java
dd-java-agent/instrumentation/finatra-2.9/src/main/java/datadog/trace/instrumentation/finatra/FinatraInstrumentation.java
dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/HttpUrlConnectionInstrumentation.java
dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/UrlInstrumentation.java
dd-java-agent/instrumentation/play-ws-1/src/main/java/datadog/trace/instrumentation/playws1/PlayWSClientInstrumentation.java
dd-java-agent/instrumentation/ratpack-1.4/src/main/java/datadog/trace/instrumentation/ratpack/ContinuationInstrumentation.java

Saves about 300ms of startup time on test app

Avoid calling superclass matcher where possible

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AbstractExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/FutureInstrumentation.java

Otherwise it was "Skipping" every unrelated class.

Apply matcher if debug logging enabled to avoid confusing log output.

---

dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Introduce `dd.tags` system property and `DD_TAGD` env variable to configure tags that are applied to all parts of the agent

Introduce dd.tags

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategy.java
dd-java-agent/benchmark/benchmark.gradle
dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/SpringbootApplication.java

Caching focused on the expensive calls primarily used by our instrumentation.
This reduces startup by nearly a second.
I'm not sure what the impact of this on memory overhead will be.  We should consider increasing the cache size a bit to make this even more effective.

Return TypePool.Resolution that caches TypeDescription calls.

---

CONTRIBUTING.md

Updates `contributing.md` with the `--release` fix and the sdk name requirement

Add compiler settings for Intellij

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
dd-java-agent/instrumentation/jax-rs-annotations-1/src/main/java/datadog/trace/instrumentation/jaxrs1/JaxRsAnnotationsInstrumentation.java
dd-java-agent/instrumentation/jedis-1.4/src/main/java/datadog/trace/instrumentation/jedis/JedisInstrumentation.java
dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java

1. move to Guava Cache with weak references
1. split cache supplier(loader) and matcher
petclinic 100 runs avg start time:
before: 51ca42991522c2834863538cc7954aa452884aff avgTime : 18.49126000000000000000
after: 01b32d814fdcf1de9df46a7185ed78daf981434d avgTime : 17.60960000000000000000

ClassLoaderMatcher put to Guava Cache outside critical section

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceMatcher.java

Minimal CPU improvement unfortunately but does at least help some.
Memory stats should be treated as grain of salt. The test app results in 5:1 cache hit:miss ratio and 2 total mismatches (scala concurrent classes). So doesn't really exercise this cache.

Fail fast in the matcher, let the debug outputs use the cache

---

dd-java-agent/instrumentation/classloading/src/main/java/datadog/trace/instrumentation/classloading/ClassloadingInstrumentation.java

Need to reset CallDepthThreadLocalMap before leaving @OnMethodEnter (not waiting until @OnMethodExit).
Otherwise it will prevent the loadClass() instrumentation from being applied when loadClass() ends up calling a ClassFileTransformer which ends up calling loadClass() further down the stack (since the call depth check would then suppress the nested loadClass instrumentation). Which can lead to ClassNotFoundException/NoClassDefFoundError on the agent's bootstrap classes that should be visible to all class loaders.
Ran into this while testing on JBoss. 🙁

Fix class loading instrumentation

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/HasSuperMethodMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/LoggingFailSafeMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/SafeErasureMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/SafeExtendsClassMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/SafeHasSuperTypeMatcher.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/matcher/ExtendsClassMatcherTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/matcher/HasInterfaceMatcherTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/matcher/ImplementsInterfaceMatcherTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/matcher/SafeHasSuperTypeMatcherTest.groovy
dd-java-agent/instrumentation/ratpack-1.4/src/main/java/datadog/trace/instrumentation/ratpack/ServerErrorHandlerInstrumentation.java

I copied over the methods that would have been generated had the `HashCodeAndEqualsPlugin` actually been working.
Also updated the matcher tests to use the TypePool for more realistic values.

Add proper hashcode/equals methods to our matchers

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/AdditionalLibraryIgnoresMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/RequestInstrumentation.java
dd-java-agent/instrumentation/datastax-cassandra-3/src/main/java/datadog/trace/instrumentation/datastax/cassandra/CassandraClientInstrumentation.java
dd-java-agent/instrumentation/google-http-client/src/main/java/datadog/trace/instrumentation/googlehttpclient/GoogleHttpClientInstrumentation.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java

This seems to be improving pet clinic startup by ~3 seconds.

Add additional ignores

---

dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceDecorator.java

Specifically, this allows annotated/configured methods to be reported to App Analytics:
- System Property: `-Ddd.trace-annotation.analytics.enabled=true`
- Environment Variable: `DD_TRACE_ANNOTATION_ANALYTICS_ENABLED=true`
or
- System Property: `-Ddd.trace-config.analytics.enabled=true`
- Environment Variable: `DD_TRACE_CONFIG_ANALYTICS_ENABLED=true`

Add instrumentation name to allow configuring `@Trace`

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ClassLoaderMatcherTest.groovy

This is not needed anymore now that loadClass() is being instrumented to deal with non-delegating class loaders.
See https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/203

Remove non-delegating loader check

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/AdditionalLibraryIgnoresMatcher.java
dd-java-agent/instrumentation/akka-http-10.0/akka-http-10.0.gradle
dd-java-agent/instrumentation/apache-httpasyncclient-4/apache-httpasyncclient-4.gradle
dd-java-agent/instrumentation/aws-java-sdk-2.2/aws-java-sdk-2.2.gradle
dd-java-agent/instrumentation/cdi-1.2/cdi-1.2.gradle
dd-java-agent/instrumentation/dropwizard/dropwizard.gradle
dd-java-agent/instrumentation/finatra-2.9/finatra-2.9.gradle
dd-java-agent/instrumentation/grizzly-2/grizzly-2.gradle
dd-java-agent/instrumentation/grpc-1.5/grpc-1.5.gradle
dd-java-agent/instrumentation/hystrix-1.4/hystrix-1.4.gradle
dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableTest.groovy
dd-java-agent/instrumentation/instrumentation.gradle
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/CallableInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableInstrumentation.java
dd-java-agent/instrumentation/jax-rs-annotations-2/jax-rs-annotations-2.gradle
dd-java-agent/instrumentation/jax-rs-client-2.0/jax-rs-client-2.0.gradle
dd-java-agent/instrumentation/jetty-8/jetty-8.gradle
dd-java-agent/instrumentation/netty-4.0/netty-4.0.gradle
dd-java-agent/instrumentation/netty-4.1/netty-4.1.gradle
dd-java-agent/instrumentation/play-2.4/play-2.4.gradle
dd-java-agent/instrumentation/play-2.6/play-2.6.gradle
dd-java-agent/instrumentation/play-ws-1/play-ws-1.gradle
dd-java-agent/instrumentation/play-ws-2.1/play-ws-2.1.gradle
dd-java-agent/instrumentation/play-ws-2/play-ws-2.gradle
dd-java-agent/instrumentation/ratpack-1.4/ratpack-1.4.gradle
dd-java-agent/instrumentation/reactor-core-3.1/reactor-core-3.1.gradle
dd-java-agent/instrumentation/servlet/request-3/request-3.gradle
dd-java-agent/instrumentation/spring-webflux-5/spring-webflux-5.gradle
dd-java-agent/instrumentation/twilio/twilio.gradle
dd-java-agent/instrumentation/vertx/vertx.gradle

Include `java-concurrent` instrumentation in all instrumentations when running tests.
This has uncovered bugs in `java-concurrent` instrumentation and `grpc` instrumentation which should also be fixed by this PR.

Scale back ignores

---

dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/RequestDispatcherInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/filter/FilterInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletInstrumentation.java

Effectively reverting https://github.com/DataDog/dd-trace-java/commit/6703bd96bbbb2527dc7788a8785635563a3a2988
The expectation is that these are not really separate external requests, but a semantic way of processing a single request.

Stop creating a "top level" servlet span when in a forward/include situation

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/HelperInjectionTest.groovy

This change aims to avoid JAR file collisions by creating a per-injection temp dir inside the usual java.io.tmpdir.
The HelperInjector selects a temporary directory using Files.createTempDirectory for each injection.  This compensates for ByteBuddy's ClassInjector.UsingInstrumentation not using File.createTempFile which leads to occasional collisions.
This scheme was chosen in part to avoid modifying or recreating the logic in ClassInjector.UsingInstrumentation.  While the logic of that class is not complicated, many of the helper classes it calls are not public.

Avoid temporary Jar file collisions

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ClassLoaderMatcherTest.groovy

Reverts #1288, and adds comment explaining why the non-delegating class loader check is being kept

Revert removal of non-delegating loader check

---

dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyHttpHandlerInstrumentation.java
dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyHandlerAdvice.java
dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy

This pull request adds `traceId` and `spanId` as request attributes.  This allows the ids to be available to app server/container facilities like access logging (#1214).

Add traceId and spanId as request attributes

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/AdditionalLibraryIgnoresMatcher.java

Test failure in `FinatraServerTest` when running `latestDepTest`

Fix ignores for com.google.inject

---

dd-trace-java.gradle

This uses the [axion-release](https://axion-release-plugin.readthedocs.io/en/latest/) to automatically set the version for the gradle project by looking at git tags.
This removes 9 steps from the 21 step release process.
~I preserved our practice of generating a release commit but don't have strong feelings about it.~
Show current version:
```
./gradlew currentVersion
```
Do a dry-run of a release (no actions performed):
```
./gradlew release -Prelease.dryRun
```
Perform a release:
```
./gradlew release
```

Use plugin to automatically set version

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java
dd-trace-ot/src/main/java/datadog/opentracing/DDSpanContext.java
dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy

(But only when span is not errored or finished on a different thread.)
Use the following config:
```
-Ddd.trace.span.duration-above-average.stacktrace.millis=1000
```
(One second is the default, `0` disables.)

Add config to capture stacktrace when a span duration exceeds threshold

---

dd-java-agent/instrumentation/jms/jms.gradle

JDK 11 and newer removes the JavaEE classes.  Tests don't build on 11 without adding this dependency.

Fix jms tests with JDK11+

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ClientDecorator.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecorator.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ServerDecorator.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/BaseDecoratorTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ClientDecoratorTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecoratorTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecoratorTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecoratorTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ServerDecoratorTest.groovy

Removes one of the last places still using OpenTracing tags instead of `datadog.trace.bootstrap.instrumentation.api.Tags`
I noticed this when I did the bootstrap move but didn't want to muddy that PR.

Replace OT tags with api tags in decorators

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/GenericRunnable.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java

Last java-concurrent helper left behind in the last pull request.  Moves `GenericRunnable` to the bootstrap so injection is not needed.

Move ThreadPoolExecutor helper to bootstrap

---

dd-trace-java.gradle

During the 0.46.0 release, there was an "Auth Fail" error when the plugin tried to push the new tag.  Upgrading to the latest version of the plugin fixes that.
Tested on a private repo.

Fix release plugin auth with new version

---

dd-java-agent/instrumentation/jms/jms.gradle

#1314 broke tests with Java 7 (while fixing compiles under 11).  This pull request switches to an older version of `javax.annotation-api` that compiles under both.

Fix JMS test library for Java 7

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecorator.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecoratorTest.groovy
dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpClientDecorator.java
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/ApacheHttpAsyncClientDecorator.java
dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientDecorator.java
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWSClientTest.groovy
dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test_before_1_11_106/groovy/AWSClientTest.groovy
dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
dd-java-agent/instrumentation/commons-httpclient-2/src/main/java/datadog/trace/instrumentation/commonshttpclient/CommonsHttpClientDecorator.java
dd-java-agent/instrumentation/google-http-client/src/main/java/datadog/trace/instrumentation/googlehttpclient/GoogleHttpClientDecorator.java
dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/HttpUrlConnectionDecorator.java
dd-java-agent/instrumentation/jax-rs-client-1.1/src/main/java/datadog/trace/instrumentation/jaxrs/v1/JaxRsClientV1Decorator.java
dd-java-agent/instrumentation/jax-rs-client-2.0/src/main/java/datadog/trace/instrumentation/jaxrs/JaxRsClientDecorator.java
dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/NettyHttpClientDecorator.java
dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/NettyHttpClientDecorator.java
dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/OkHttpClientDecorator.java
dd-java-agent/instrumentation/play-ws/src/main/java/datadog/trace/instrumentation/playws/PlayWSClientDecorator.java
dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientDecorator.java

Was talking to @tylerbenson and saw that out profiles were doing a lot of parsing of URIs. I've found the culprit to be in the `hostname(REQUEST request)` and `port(REQUEST request)` methods. Since this data is already computed via the initial URI parse to build the url, I see no need to delegate the extra calls for tags.

Remove hostname and port from HttpClientDecorator

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/OpenTracing32.java

Otherwise split on an empty string may return an empty array.

Add check to ensure value isn't empty

---

.github/workflows/add-assets-to-release.yaml

Whenever a release is published on Github, this workflow pulls the jars from jcenter and adds them as release assets.  A Github actions solution was much simpler than a CircleCI solution.
Tested on a private repo.

Automatically add assets to release

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakCache.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/WeakMapTest.groovy
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentTooling.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassHierarchyIterable.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/GuavaWeakCache.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceMatcher.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/WeakCacheTest.groovy
dd-java-agent/dd-java-agent.gradle
dd-java-agent/instrumentation/jax-rs-annotations-1/src/main/java/datadog/trace/instrumentation/jaxrs1/JaxRsAnnotationsDecorator.java
dd-java-agent/instrumentation/jax-rs-annotations-1/src/test/groovy/JaxRsAnnotations1InstrumentationTest.groovy
dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/JaxRsAnnotationsDecorator.java
dd-java-agent/instrumentation/jax-rs-annotations-2/src/test/groovy/JaxRsAnnotations2InstrumentationTest.groovy
dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/AttributeKeys.java
dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/AttributeKeys.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java

The intention of this change is to replace (not change) our concurrent WeakMap abstraction.
Our concurrent WeakMap abstraction has a few problems… :
- unbounded size
- primary eviction policy isn’t size
- always uses synchronized even around ConcurrentMaps like Guava
- encourages computation under a lock
- needs better setting for concurrency level
New abstraction should be a “WeakCache” not for a “WeakMap”.  Maps may need to be unbounded, but caches should be bounded.
Abstraction should be quite minimal.  
It doesn’t need to be as complex as our current WeakMap.Provider scheme.
Just a simple factory function that returns a Guava Cache object with reasonable defaults.

WeakCache instead of WeakMap

---

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/RecordingUploader.java
dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/RecordingUploaderTest.java
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Add `DD_SITE` (and `dd.site`) configuration option to support sending profiles to different datadog sites (e.g. EU).

Add option to configure Datadog site used to send profiling information

---

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/RecordingUploader.java
dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/RecordingUploaderTest.java
dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java
dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/ProfilingIntegrationContinuousProfilesTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
dd-trace-api/src/test/resources/apikey.very-old

To stream line configuration in the future intropduce
`DD_API_KEY`/`DD_API_KEY_FILE` to provide agent with API
key. Currently this is only used for profiling but later may be used
for other parts of the agent too.

Introduce to API key config option

---

.circleci/config.yml

Regular expressions have to be enclosed with `/`s according to the [circleci docs](https://circleci.com/docs/2.0/configuration-reference/). 🙂

Fix reliability branch filter regex

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/OpenTracing32.java

Turns out the issue wasn't with an empty string returning an empty array, but a string with just `,`.
```
jshell> ",".split(",")
$1 ==> String[0] {  }
```
A non-intuitive edge case in my opinion.

Fix Extractor edge case with value of a single comma.

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/OpenTracing32.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Decorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/RequestDispatcherInstrumentation.java
dd-java-agent/instrumentation/servlet/src/test/groovy/RequestDispatcherTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/spring-webmvc-3.1.gradle
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/DispatcherServletInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerMappingResourceNameFilter.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/AppConfig.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SpringBootBasedTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/TestController.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/filter/FilteredAppConfig.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/filter/ServletFilterTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/filter/TestController.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy

Instead of waiting till the handler is called, otherwise if a response is returned by a filter then the proper name wouldn't be set and would fall back to the URL.
I tried to add comments for the parts that are interdependent.  Let me know if it's insufficient.

Add instrumentation to detect the route at the beginning of the spring request

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/OpenTracing32.java
dd-java-agent/instrumentation/jax-rs-annotations-1/src/main/java/datadog/trace/instrumentation/jaxrs1/JaxRsAnnotationsDecorator.java
dd-java-agent/instrumentation/jax-rs-annotations-1/src/main/java/datadog/trace/instrumentation/jaxrs1/JaxRsAnnotationsInstrumentation.java
dd-java-agent/instrumentation/jax-rs-annotations-1/src/test/groovy/JerseyTest.groovy
dd-java-agent/instrumentation/jax-rs-annotations-1/src/test/java/Resource.java
dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/JaxRsAnnotationsDecorator.java
dd-java-agent/instrumentation/jax-rs-annotations-2/src/test/groovy/JaxRsFilterTest.groovy
dd-java-agent/instrumentation/jax-rs-annotations-2/src/test/java/Resource.java
dd-trace-ot/src/main/java/datadog/opentracing/DDSpanContext.java

Previously the last called one was winning.  Now we check if the resource name is already set before applying the new name.

Properly handle resource name for nested JAX-RS calls

---

.github/workflows/add-milestone-to-pull-requests.yml

This github action adds the latest milestone to a pull request if:
- The pull request was merged
- The pull request was made against master
- The pull request didn't already have a milestone attached
Originally, I added the "Closed" milestone to "closed and unmerged" but I don't think its necessary if all relevant pull requests have milestones attached

Add milestone to merged pull requests

---

.github/workflows/update-issues-on-release.yaml

When Release Notes are published, this Github Action updates all issues in the milestone with the text:
:robot: This issue has been addressed in the latest release.  See full details in the [Release Notes]( ${{ github.event.release.html_url }}).'
and closes the issue

Update issues when Release Notes are published

---

.github/workflows/draft-release-notes-on-milestone-close.yaml

This github action creates draft release notes from a milestone when it is closed.  The release notes **still have to be manually edited** (because it doesn't know categories and pull request titles aren't always the best), but this should greatly reduce the effort and copy/paste involved.

Draft release notes on milestone close

---

buildSrc/src/main/groovy/MuzzlePlugin.groovy
dd-java-agent/instrumentation/apache-httpclient-4/apache-httpclient-4.gradle
dd-java-agent/instrumentation/commons-httpclient-2/commons-httpclient-2.gradle
dd-java-agent/instrumentation/elasticsearch/rest-6.4/rest-6.4.gradle
dd-java-agent/instrumentation/elasticsearch/transport-5.3/transport-5.3.gradle
dd-java-agent/instrumentation/elasticsearch/transport-5/transport-5.gradle
dd-java-agent/instrumentation/elasticsearch/transport-6/transport-6.gradle
dd-java-agent/instrumentation/jax-rs-client-1.1/jax-rs-client-1.1.gradle
dd-java-agent/instrumentation/play-ws-2.1/play-ws-2.1.gradle
dd-java-agent/instrumentation/play-ws-2/play-ws-2.gradle
dd-java-agent/instrumentation/servlet/servlet.gradle
dd-java-agent/instrumentation/spring-webmvc-3.1/spring-webmvc-3.1.gradle

For example in the latest release `jetty-server`'s version list was messed up:
https://repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/maven-metadata.xml
but still available in jcenter:
https://jcenter.bintray.com/org/glassfish/jersey/core/jersey-server/maven-metadata.xml
Add `skipVersions` to muzzle to handle bad versions found in various repositories.
Roll back various hacks around the broken versions.

Add jCenter as a muzzle repository to catch things that are different from Maven Central

---

.github/workflows/update-issues-on-release.yaml

Small update to #1388 to address handle pagination with issues and milestones.
Although it's unlikely that we'll have more than 30 actual issues on a release, "issues" includes pull requests and both of them adding to 30 is a lot more likely.

Handle pagination when auto-updating issues

---

dd-java-agent/instrumentation/grizzly-2/grizzly-2.gradle

New `3.0.0-M1` release seems to be breaking the tests.

Add limit for grizzly latestDepTest

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
dd-java-agent/instrumentation/jdbc/src/test/groovy/test/TestConnection.groovy

This should help resolve a situation where `getClientInfo` is not implemented and throws an `AbstractMethodError`.

Extend JDBC catch to include Errors

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java

Instead of having `java.lang.UnsupportedClassVersionError: com/datadog/profiling/agent/ProfilingAgent : Unsupported major.minor version 52.0` 
we don't show the stack trace and just indicating we need at least Open JDK8 and we are skipping profiling:
`Profiling requires OpenJDK 8 or above - skipping`

Improve message when running with < JDK8

---

dd-trace-ot/src/main/java/datadog/opentracing/propagation/HttpCodec.java

Seems like I missed this from https://github.com/DataDog/dd-trace-java/pull/1228

Http Trace and Span ID should be StringCachingBigInteger

---

dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

This change introduces merging of explicitly defined span properties and properties defined in   "dd.trace.global.tags". 
I ) For every property  we have 3 levels of defining it:
1. creating tracer with configuration via API and with explicit Properties argument with specifying this exact property inside this argument ( https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-api/src/main/java/datadog/trace/api/Config.java#L1384 )
1. java system property
1. linux environment variable
1. java property file
We take next one only if it's not defined the previous one. Eg. So we look into linux environment variables only 
II ) We have special container properties `tags` and `global.tags` which allow to aggregate other properties inside it.  
1. `dd.tags`(DD_TAGS) has precedence over …

merge DD_VERSION and DD_ENV with "dd.trace.global.tags"

---

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle

(integrations-core was previously on 6.14.0)

Upgrade jmxfetch to 0.36.1 and integrations-core modules to 7.19.0

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java

Trying to remove the shutdown hook in finalize often leads to an `IllegalStateException`.  This is expected if the jvm is already shutting down.
This pull request removes that logging

Reduce finalize() logspam in CoreTracer

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java
dd-java-agent/instrumentation/hibernate/src/main/java/datadog/trace/instrumentation/hibernate/HibernateDecorator.java

It would be nice to enforce this with static analysis.

replace collection.size() > 0 with not collection.isEmpty()

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java

Related to #1345 and similar to #1395 
The `datadog.trace.core.jfr.openjdk.ScopeEventFactory` class not being available happens in multiple common cases:
- Running without the agent
- Many tests that don't add the `jfr-openjdk` dependency
- JDK version < 8
Logging the exception creates the mistaken impression of an error and creates a lot of spam in the test logs.

Change logging for ScopeEventFactory creation exception

---

.github/workflows/draft-release-notes-on-tag.yaml
.github/workflows/update-issues-on-release.yaml

The draft release notes action [failed](https://github.com/DataDog/dd-trace-java/actions/runs/90459453) because the argument list was too long.
This pull request fixes that problem and a similar one with "update issues on release" that we didn't trip yet.

Fix Github action for drafting release notes

---

dd-java-agent/instrumentation/datastax-cassandra-3/src/main/java/datadog/trace/instrumentation/datastax/cassandra/TracingSession.java

This should not prevent application shutdown.

Fix cassandra instrumentation to use a daemon thread

---

dd-trace-ot/src/main/java/datadog/opentracing/TypeConverter.java
dd-trace-ot/src/test/groovy/datadog/opentracing/OpenTracingAPITest.groovy

The OT API expects null to be returned in certain cases, so we shouldn't returned a wrapped null.

Fix null span/scope handling for OpenTracing Bridge

---

dd-trace-api/src/main/java/datadog/trace/context/TraceScope.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContextualScopeManager.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScope.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/DDScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
dd-trace-ot/src/test/groovy/datadog/opentracing/CustomScopeManagerTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

**Note: These deprecated methods will be removed in the following release.**
The `finishOnClose` functionality will remain in the OpenTracing compatibility layer, but behavior may change if utilizing on continuations.
Migrating usage can impact the way span duration is calculated. For example given the following code:
```java
@Trace
def someMethod() {
executor.execute {
// Assume this executes after someMethod() already returned.
httpClient.request(url)
}
}
```
Historically, the Java Tracer prevented the top level span from finishing until the child work finished, resulting in a trace like this:
```
[-------------- someMethod --------------------]
[---clientRequest-----]
```
After this change, it will produce a trace more like this, which more accurately depicts the duration of the method …

[Breaking change for dd-trace-api] Deprecate scope finishOnClose and continuation close

---

dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Decorator.java
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServletHandlerTest.groovy

```
at datadog.trace.instrumentation.servlet3.Servlet3Decorator.onContext(Servlet3Decorator.java:81)
at datadog.trace.instrumentation.servlet3.Servlet3Decorator.onRequest(Servlet3Decorator.java:68)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:782)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
at …
```

Add null servlet context check

---

.circleci/config.yml
.circleci/copy_artifact_s3.py

Use context to securely handle secrets. It is a short term solution until moving the build to gitlab

Apply copy artifact to only master and *-reliability

---

dd-trace-ot/src/main/java/datadog/opentracing/OTSpan.java
dd-trace-ot/src/test/groovy/datadog/opentracing/OpenTracingAPITest.groovy

Our users expect to be able to cast between the two interfaces, so we need to allow that.

Make `OTSpan` implement `MutableSpan`

---

dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/BatchWritingDisruptor.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/Monitor.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/MsgPackStatefulSerializer.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/StatefulSerializer.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceBuffer.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingDisruptor.java
dd-trace-core/src/main/java/datadog/trace/core/StringTables.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/FormatWriter.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/MsgpackFormatWriter.java
dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentApiTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
dd-trace-core/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy

* Introduces `TraceBuffer` which may contain one or many traces, encapsulating the data buffer to avoid copying.
* Introduces `StatefulSerializer` which decouples the process of serializing traces from getting a buffer. This makes it possible to serialize several traces into the same buffer, though the responsibilities between the trace processor and batch processor are maintained for the time being.
* The `MsgPackStatefulSerializer` implementation has an adaptive buffer sizing algorithm based on a moving average of recently serialised traces and the number of traces last serialised into the buffer, which aims to minimise allocation.
* This allows reuse of a `MessagePacker` which prevents excessive allocation of `UTF_8$Encoder` objects. 
* Dead code in `DDAgentApi.sendTraces` was removed …

Reduce copy/allocation in trace serialization pipeline

---

dd-java-agent/instrumentation/lettuce-4/src/main/java8/datadog/trace/instrumentation/lettuce/InstrumentationPoints.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/LettuceAsyncCommandsAdvice.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/LettuceInstrumentationUtil.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/rx/LettuceFluxCreationAdvice.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/rx/LettuceMonoCreationAdvice.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/rx/LettuceMonoDualConsumer.java

Tried to keep the change set small, but there's some further cleanup that could be done here.

Migrate Lettuce instrumentation away from deprecated finishSpanOnClose

---

dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringTemplateTest.groovy
dd-java-agent/instrumentation/dropwizard/src/test/groovy/DropwizardTest.groovy
dd-java-agent/instrumentation/elasticsearch/rest-5/src/latestDepTest/groovy/Elasticsearch6RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/rest-5/src/test/groovy/Elasticsearch5RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/rest-6.4/src/latestDepTest/groovy/Elasticsearch6RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/rest-6.4/src/test/groovy/Elasticsearch6RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/Elasticsearch2NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/Elasticsearch2TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/Elasticsearch53NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/Elasticsearch53TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/Elasticsearch5NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-6/src/test/groovy/Elasticsearch6NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-6/src/test/groovy/Elasticsearch6TransportClientTest.groovy
dd-java-agent/instrumentation/jms/src/test/groovy/SpringListenerJMS1Test.groovy
dd-smoke-tests/wildfly/src/test/groovy/datadog/smoketest/WildflySmokeTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy

(Spock's `Retry` delay unit is milliseconds)

Make Retrys consistent

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/Config.java

In environments with mixed kafka-client versions, there can be errors when a producer that has the kafka integration enabled creates a message to be sent to brokers that use the kafka-client > 0.11. This causes the magic version (apiVersions.maxUsableProduceMagic()) to be 2 and the DD trace library injects headers into the record.
Consumer is using a version of kafka-client < 0.11 will fail when attempting to consume this record with an [IllegalArgumentException](https://github.com/apache/kafka/blob/3e9d1c1411c5268de382f9dfcc95bdf66d0063a0/clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java#L412) 
This change allows organizations that have a mixed kafka-client environment to keep the kafka integration enabled and manually disable the injection of headers by …

Adding an option to manually disable Kafka headers

---

dd-java-agent/instrumentation/instrumentation.gradle
dd-java-agent/instrumentation/lettuce-4/src/main/java/datadog/trace/instrumentation/lettuce4/LettuceAsyncCommandsInstrumentation.java
dd-java-agent/instrumentation/lettuce-4/src/main/java/datadog/trace/instrumentation/lettuce4/LettuceClientInstrumentation.java
dd-java-agent/instrumentation/lettuce-4/src/main/java8/datadog/trace/instrumentation/lettuce4/InstrumentationPoints.java
dd-java-agent/instrumentation/lettuce-4/src/main/java8/datadog/trace/instrumentation/lettuce4/LettuceAsyncCommandsAdvice.java
dd-java-agent/instrumentation/lettuce-4/src/main/java8/datadog/trace/instrumentation/lettuce4/LettuceClientDecorator.java
dd-java-agent/instrumentation/lettuce-4/src/main/java8/datadog/trace/instrumentation/lettuce4/RedisConnectionAdvice.java
dd-java-agent/instrumentation/lettuce-4/src/test/groovy/Lettuce4AsyncClientTest.groovy
dd-java-agent/instrumentation/lettuce-4/src/test/groovy/Lettuce4SyncClientTest.groovy
dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceAsyncCommandsInstrumentation.java
dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceClientInstrumentation.java
dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceReactiveCommandsInstrumentation.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/ConnectionFutureAdvice.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/LettuceAsyncBiFunction.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/LettuceAsyncCommandsAdvice.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/LettuceClientDecorator.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/LettuceInstrumentationUtil.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/rx/LettuceFluxCreationAdvice.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/rx/LettuceFluxTerminationRunnable.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/rx/LettuceMonoCreationAdvice.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/rx/LettuceMonoDualConsumer.java
dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5AsyncClientTest.groovy
dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ReactiveClientTest.groovy
dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5SyncClientTest.groovy

We missed this in review. Probably need to release ASAP

Rename java packages for lettuce 4 and 5 to not have collisions

---

.circleci/config.yml
buildSrc/src/main/groovy/MuzzlePlugin.groovy

This only works on the main directive, not the `assertInverse` portion.

Attempt to improve muzzle time by randomly ignoring versions until 10 remain.

---

.github/workflows/draft-release-notes-on-tag.yaml

This pull request does 3 things:
- Fix the issue that caused [this failure](https://github.com/DataDog/dd-trace-java/actions/runs/99391507) by escaping backticks
- Skip adding a pull request to the release notes if it has a `[no release notes]` label
- Add other labels to the draft release notes (eg `[Performance])

Escape backticks and add labels to release notes

---

.palantir/revapi.yml
dd-java-agent/instrumentation/hibernate/src/main/java/datadog/trace/instrumentation/hibernate/SessionMethodUtils.java
dd-trace-api/src/main/java/datadog/trace/context/TraceScope.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContextualScopeManager.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScope.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/DDScopeManager.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/SimpleScope.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
dd-trace-ot/src/main/java/datadog/opentracing/OTScopeManager.java
dd-trace-ot/src/main/java/datadog/opentracing/TypeConverter.java
dd-trace-ot/src/ot31CompatabilityTest/groovy/OT31ApiTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/CustomScopeManagerTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/OpenTracingAPITest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

`finishSpanOnClose` will still work at the OpenTracing API level, except for `ScopeManger.active()` which returns a wrapped scope without the original `finishSpanOnClose` boolean.
The motivation here is to prevent unconstrained memory usage growth resulting from a chain of `ContinuableScope`/`Continuation` references like so:
```java
ContinuableScope scope = tracer.scopeManager().active();
Continuation continuation = scope.capture();
scope.close();
while(true){
try(Scope scope = continuation.activate()) {
continuation = scope.capture();
}
}
```
Prior to this change the above would result in an OOM error. Now, the Continuation shouldn't hold on to the previous Scope which will allow it to be GC'd.
This PR should go out in the release following #1424.

Remove previously deprecated methods and make Continuation static

---

dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ControllerFactory.java
dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ControllerFactoryTest.java
dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java

When we was running profiling on a JVM that does not support it we
have improved the message but there is still a stacktrace remaining
adding a lot of noise
Remove that stack trace for the nominal case and put it in debug mode
previous message:
```
[dd.trace 2020-05-13 09:50:43:851 +0200] [main] WARN com.datadog.profiling.agent.ProfilingAgent - Failed to initialize profiling agent!
com.datadog.profiling.controller.UnsupportedEnvironmentException: The JFR controller could not find a supported JFR API, use OpenJDK 11+ or Azul zulu version 1.8.0_212+
at com.datadog.profiling.controller.ControllerFactory.createController(ControllerFactory.java:54)
at com.datadog.profiling.agent.ProfilingAgent.run(ProfilingAgent.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at …
```

Remove stacktrace when JVM is not supported

---

.gitlab-ci.yml
dd-trace-java.gradle

Adds an "MLT" suffix to the project version.  This allows MLT snapshots to be pushed to bintray without collisions with master.
I chose not to use "version per branch" because it's annoying to have to do a full rebuild every time you switch branches.  The the change in this pull request, it only happens between MLT and non-MLT branches.

Add unique version to MLT branch

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-trace-core/src/main/java/datadog/trace/core/util/JmxThreadStackProvider.java
dd-trace-core/src/main/java/datadog/trace/core/util/NoneThreadStackProvider.java
dd-trace-core/src/main/java/datadog/trace/core/util/ThreadStackAccess.java
dd-trace-core/src/main/java/datadog/trace/core/util/ThreadStackProvider.java
dd-trace-core/src/test/groovy/datadog/trace/core/util/ThreadStackAccessTest.groovy

provides a safe way to access stacktraces through JMX getThreadInfo
call

JMX StackTrace provider

---

dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DispatchingDisruptor.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingDisruptor.java

Because of #1454, the trace processor uses more CPU in high RPS environments. This reinstates throttling behaviour in the trace processor.

revert to sleeping wait strategy in trace processor

---

.circleci/config.yml

These don't really provide useful test feedback and are not widely used anymore.

Remove Java 9 and 10 from the build.

---

.palantir/revapi.yml
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
dd-trace-core/src/main/java/datadog/trace/core/MapAcceptor.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/FormatWriter.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/JsonFormatWriter.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/MsgpackFormatWriter.java

Creating the meta map is a minor CPU bottleneck in serialisation, this change avoids allocating a new map or any map resizing.

avoid materialising meta (baggage + tags) during serialisation

---

.gitlab-ci.yml

When using workflow rules, gitlab sets the state to be "blocked".  This keeps the Github check state to as "Pending"
Setting "allow_failure=true" unblocks the build.  This is the correct behavior because those manual jobs (copy to s3, deploy to bintray) are never necessary for the build to complete when not on master.

Unblock pending builds with allow_failure=true

---

.circleci/config.yml

It gets very big (5+ GB) and causes the job to take a long time just restoring and resaving the cache.

Disable CI cache for muzzle

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/StringTables.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InstrumentationTags.java

Adds visibility on how long transactions spend in a kafka queue
submits the time difference between the start of the consumer span and the record's [timestamp](https://github.com/a0x8o/kafka/blob/master/clients/src/main/java/org/apache/kafka/common/record/TimestampType.java) to generate an estimation of time spent in queue

add time in queue

---

dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/mlt/SamplerContext.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/mlt/SamplerWriter.java
dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/mlt/SamplerWriterTest.java

This simple patch adds the ability to write the 'context' event so we can track the current tracing context for each sampled thread.
The context is wrapped in its own type to make further evolution easier.

Add a context event type support for MLT sampler JFR recording

---

dd-trace-core/src/main/java/datadog/trace/core/util/JmxThreadStackProvider.java
dd-trace-core/src/test/groovy/datadog/trace/core/util/ThreadStackAccessTest.groovy

by default, getThreadInfo does not provide stacktraces

specify maxDepth

---

.palantir/revapi.yml
dd-trace-core/src/main/java/datadog/trace/core/StringTables.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/FormatWriter.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/MsgpackFormatWriter.java
dd-trace-core/src/test/groovy/datadog/trace/core/StringTablesTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/CommonTagValues.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InstrumentationTags.java

Sorry to churn on this. Adds some more keys and a few common tag values. Splits the tables into keys and tags since we know we won't be looking for a tag when we're looking for a key's encoding. Adds a test so we can track how large the tables are, both in terms of number of elements, and in terms of size. Currently the naive strategy has tiny overhead, but if this test fails we can investigate more sophisticated strategies, tailoring what gets interned to the activated instrumentations.

intern more common UTF-8 string encodings

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScope.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

Split up tracking between spans and continuations for better logging.
Restructure the logs for better consistency.

Allow traces to be reported if continuations are GC'd before activation.

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java

Relates to #1448, #1481. Need to be able to avoid calling `ConsumerRecord.timestamp` when there are old kafka clients present.

allow user to disable kafka time in queue tag

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakMap.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentTooling.java

Specifically it is used statically by `FieldBackedProvider` which was likely called before the `AgentTooling` class was initialized.

Register WeakMapProvider earlier in AgentInstaller

---

dd-trace-core/src/main/java/datadog/trace/core/StringTables.java

Sometimes, we have large tag values like SQL queries which definitely could not have been interned. These strings will likely never have had their hash code computed, and checking if they have been interned involves calculating their hash code. This PR adds two heuristics for avoiding the lookup:
* if the string is longer than the largest key in the map
* is no string in the map has the same first byte as the tag

avoid hashing tags when they can't be in the table

---

dd-java-agent/instrumentation/finatra-2.9/src/main/java/datadog/trace/instrumentation/finatra/FinatraInstrumentation.java
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/processor/rule/HttpStatusErrorRule.java

Replaces the HTTP statuses with a more compact data structure, because they're `static final` and surprisingly large:
```
java.util.HashSet@65ab7765d footprint:
COUNT       AVG       SUM   DESCRIPTION
1      1040      1040   [Ljava.util.HashMap$Node;
100        16      1600   java.lang.Integer
1        16        16   java.lang.Object
1        48        48   java.util.HashMap
100        32      3200   java.util.HashMap$Node
1        16        16   java.util.HashSet
204                5920   (total)
```
We have between 2 and 4 of the above. This means we could have overhead between 12 and 24KB (if there is an override with a lot of status codes) depending on what configuration overrides are in place.
Using a `BitSet` we have:
server errors:
```
java.util.BitSet@1b28cdfad footprint:
COUNT …
```

replace Set<Integer> with BitSet for HTTP statuses

---

dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/processor/rule/AnalyticsSampleRateRule.java
dd-trace-core/src/main/java/datadog/trace/core/processor/rule/DBStatementRule.java
dd-trace-core/src/main/java/datadog/trace/core/processor/rule/ErrorRule.java
dd-trace-core/src/main/java/datadog/trace/core/processor/rule/ResourceNameRule.java
dd-trace-core/src/main/java/datadog/trace/core/processor/rule/SpanTypeRule.java

Avoids looking up tags twice in several places in one of the hotspots seen in profiling. Previously in several rules the tag value would be looked up in an unmodifiable view over the tags map in `DDSpanContext` and then removed through `DDSpan.removeTag`, which would enter but immediately leave an uncontended synchronised block. Now, when we need to remove the tag, we get and remove it in one lookup via `ConcurrentHashMap.remove` (and might not need the unmodifiable view either).

reduce the number of ConcurrentHashMap lookups per span in rule processing

---

dd-java-agent/instrumentation/elasticsearch/rest-5/src/latestDepTest/groovy/Elasticsearch6RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/rest-5/src/test/groovy/Elasticsearch5RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/rest-6.4/src/latestDepTest/groovy/Elasticsearch6RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/rest-6.4/src/test/groovy/Elasticsearch6RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/Elasticsearch2NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/Elasticsearch2TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/Elasticsearch53NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/Elasticsearch53TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringRepositoryTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringTemplateTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/Elasticsearch5NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-6/src/test/groovy/Elasticsearch6NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-6/src/test/groovy/Elasticsearch6TransportClientTest.groovy
gradle/java.gradle

I think this is primarily improved by the `Retry.Mode.SETUP_FEATURE_CLEANUP` change.  Previously it would not run `AgentTestRunner.beforeTest()` which resets the list of collected traces, so any spans generated in a failed run would mess up the results from the retry.

Use Retry.Mode.SETUP_FEATURE_CLEANUP to improve Elasticsearch test flakiness

---

dd-java-agent/instrumentation/elasticsearch/rest-5/src/latestDepTest/groovy/Elasticsearch6RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/rest-5/src/test/groovy/Elasticsearch5RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/rest-6.4/src/latestDepTest/groovy/Elasticsearch6RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/rest-6.4/src/test/groovy/Elasticsearch6RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/Elasticsearch2NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/Elasticsearch2TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/Elasticsearch53NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/Elasticsearch53TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringTemplateTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/Elasticsearch5NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-6/src/test/groovy/Elasticsearch6NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-6/src/test/groovy/Elasticsearch6TransportClientTest.groovy

See what happens if we let elastic find a port to bind to and get the port back from the client.
From their [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#common-network-settings) can take a port number or a range, if a range is given, will find the first free port in the range, defaults are 100 port ranges.
Also prevent tests from communicating by assigning unique cluster names.

Fix elasticsearch test flakiness

---

dd-java-agent/instrumentation/elasticsearch/rest-5/src/latestDepTest/groovy/Elasticsearch6RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/rest-5/src/test/groovy/Elasticsearch5RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/rest-6.4/src/latestDepTest/groovy/Elasticsearch6RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/rest-6.4/src/test/groovy/Elasticsearch6RestClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/Elasticsearch2NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/Elasticsearch2TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/Elasticsearch53NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/Elasticsearch53TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringTemplateTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/Elasticsearch5NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-6/src/test/groovy/Elasticsearch6NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-6/src/test/groovy/Elasticsearch6TransportClientTest.groovy
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/TracedDelegatingConsumer.java
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy

Adds the time between sending the message and starting the consumer span to the tags of consumer spans.

add record.queue_time_ms to rabbitmq consumer span tags

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java

When we wrap these proxy classes we cause the bytecode within these proxies to break.
```
Caused by:java.lang.VerifyError: (class: 
org/postgresql/PGStatement$$EnhancerByProxool$$afb2abd7, method: 
executeWithFlags signature: (Ljava/lang/String;I)Z) Register 3 
contains wrong type	at 
java.base/java.lang.Class.getDeclaredMethods0(Native Method)	at 
java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)	at 
java.base/java.lang.Class.getDeclaredMethod(Class.java:2473)	at
```

Ignore proxool proxy classes

---

dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/CacheProviderTest.groovy

Saw this one fail on master, and reproduced it consistently after about 500 runs using IDEA's repeat until failure feature. Changing 0.8 to 0.75 ran so many test cases (hundreds of thousands) that IDEA crashed :)

change error bound so test should almost never fail

---

dd-trace-core/src/test/groovy/datadog/trace/core/StringTablesTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/serialization/MsgPackFormatWriterTest.groovy

It has a work around to ensure Config is modifiable before it is loaded and if Config is loaded before hand, it can cause other tests to fail.
For example:
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class datadog.trace.util.test.DDSpecification
```

Tests in dd-trace-core should extend DDSpecification

---

.palantir/revapi.yml
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java

A slightly complex interaction was occurring:
- `DDTracerBuilder` initializes from `Config.get()`
- `CoreTracerBuilder` initializes from `Config.get()`
- The `@Builder`-constructor for `DDTracer` sees `config` is not `null` so it passes it to `CoreTracerBuilder`
- `CoreTracerBuilder` initializes from config again
The end result is that classes built in `CoreTracerBuilder.config()` (eg `DeterministicSampler`, `ContinuableScopeManager`, etc) are created multiple times.
There is no need for the `DDTracerBuilder` to initialize from config because `CoreTracerBuilder` already does.

Remove duplicate "build from config" in DDTracer

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/CallDepthThreadLocalMap.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/CallDepthThreadLocalMapTest.groovy

Use ClassValue to store ThreadLocal call depth

---

.palantir/revapi.yml
dd-trace-api/src/main/java/datadog/trace/api/DDId.java
dd-trace-api/src/test/groovy/datadog/trace/api/DDIdTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/serialization/JsonFormatWriter.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/MsgpackFormatWriter.java
dd-trace-core/src/test/groovy/datadog/trace/core/serialization/JsonFormatWriterTest.groovy

As @richardstartin commented, the Datadog Agent  will probably decode our integers the right way even if we send a signed 64 bit when it expects an unsigned 64 bit, and lo and behold https://github.com/DataDog/datadog-agent/blob/f12fc7af659455c252ab4c251a666ee95f0b930a/pkg/trace/pb/decoder.go#L125 that is exactly what it does.

Always send id as long

---

dd-trace-core/src/main/java/datadog/trace/core/serialization/MsgpackFormatWriter.java

This removes roughly `30%` of all `byte[]` allocations and `70%` of all `sun.nio.cs.UTF_8$Encoder` allocations during a `pet-clinic` run.
Not sure about the cache size.

Cache byte[] for the last 64 tags

---

dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
dd-trace-ot/src/ot31CompatabilityTest/groovy/OT31ApiTest.groovy

The main bug is the handling of `PrioritySampling.UNSET` and how that interacts with `"$context.delegate.samplingPriority"`.  In the unset case, the sampling priority is set on propagation.
Depending on when `"$context.delegate.samplingPriority"` is evaluated it could be one of a couple different values.  This fix has explicit inputs -> outputs

Fix OT31 tests

---

dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/ApacheHttpClientRedirectInstrumentation.java
dd-java-agent/instrumentation/google-http-client/src/test/groovy/AbstractGoogleHttpClientTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy

ApacheHttpClientRedirectInstrumentation:
copy headers from original request to redirect request only if original redirect headers were empty without additinal headers

ApacheHttpClientRedirectInstrumentation copy headers from original request to redirect if original redirect headers were empty

---

dd-smoke-tests/cli/src/test/groovy/datadog/smoketest/CliApplicationSmokeTest.groovy
dd-smoke-tests/java9-modules/src/test/groovy/datadog/smoketest/Java9ModulesSmokeTest.groovy
dd-smoke-tests/opentracing/src/test/groovy/datadog/smoketest/OpenTracingSmokeTest.groovy
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/AbstractProfilingIntegrationTest.groovy
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/ProfilingIntegrationBogusApiKeyTest.groovy
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/ProfilingIntegrationContinuousProfilesTest.groovy
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/ProfilingIntegrationShutdownTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractServerSmokeTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy

This change should eradicate the spurious test failures due to port conflicts - at least for the profiling smoke tests by letting the profiling mock http server to use OS allocated transient ports.

Allow the mock http server get assigned a transient port.

---

dd-trace-core/src/main/java/datadog/trace/core/processor/TraceProcessor.java
dd-trace-core/src/main/java/datadog/trace/core/processor/rule/MethodLevelTracingDataRule.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/TraceProfilingScopeInterceptor.java
dd-trace-core/src/test/groovy/datadog/trace/core/processor/MethodLevelTracingDataRuleTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InstrumentationTags.java

Add sampling data from the MLT api to the span:
- Base64 encodes the bytes
- Chunks the resulting string into 5000 character parts
- Puts chunks into `_dd.mlt.{index}` tags
I went with the simplest approach (instead of having an encoding interface) because it's just a single method.

Add thread sampling data to span tag

---

.circleci/config.yml
buildSrc/src/main/groovy/MuzzlePlugin.groovy
dd-trace-java.gradle

This pull request splits the muzzle task using CircleCI's split function.  The goal being to avoid some of the 25+ min muzzle builds that happen sometime.
**Long muzzle build:**
https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/1360/workflows/881959e9-a14a-4555-a676-1937e7da9b83/jobs/66544
**New build in action:**
https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/1409/workflows/7b8f71e9-5f7a-43e1-9917-730775575a4a/jobs/66999/parallel-runs/6?filterBy=ALL
It's not a perfect split because it's split by project and not by `muzzle-AssertPass-*` and `muzzle-AssertFail-*` tasks.  Some executors take longer depending on their projects.  The reason for this is that splitting by subtask would mean repeating the `compileJava` and `bytebuddy` steps for the same project.  I …

Split muzzle across multiple executors

---

dd-java-agent/instrumentation/play-2.6/play-2.6.gradle
dd-java-agent/instrumentation/play-2.6/src/main/java8/datadog/trace/instrumentation/play26/PlayHttpServerDecorator.java

Possible fix for the problem shown in https://github.com/DataDog/dd-trace-java/pull/1138.
`play.api.libs.TypedKey.underlying` was deprecated in 2.7 and removed in 2.8 (https://github.com/playframework/playframework/commit/be442e255a1153ed6babe29bfb5ad00accbacb2e#diff-0cdc3904ffe7ccdcc86d04337cf912d9), `play.api.libs.TypedKey.asScala` was added in Play 26 instead.

Update play-2.6 instrumentation to support Play version 2.8.x

---

utils/thread-utils/src/main/java/datadog/common/exec/CommonTaskExecutor.java
utils/thread-utils/src/test/groovy/datadog/common/exec/PeriodicSchedulingTest.groovy

We should cancel futures when target is GCed. This was the intention that was overlooked in original implementation.

Fix future cancelation

---

.circleci/config.yml

#1554 didn't check if the build wasn't in a pull request.  This broke the master build (and would break any other non-pull request builds)

Don't fetch merge commit if not in pull request

---

dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
dd-java-agent/src/test/groovy/datadog/trace/agent/AgentLoadedIntoBootstrapTest.groovy
dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
dd-java-agent/src/test/java/jvmbootstraptest/MyClassLoaderIsNotBootstrap.java

If someone by mistake adds content of dd-java-agent.jar to application level "uber.jar" out agent installer will add this "uber.jar" to bootstrap classpath. And if some application level classes are loaded by bootstrap classpath we see random NPEs is user code where we never expect `MyAppClass.getClassLoader()` returns `null` .

disable agent if we may append wrong jar to boot classpath

---

.circleci/config.yml

General refactor of the CircleCI config.  Removes ~100 lines and gets rid of a lot of repetition.
- Use a matrix build instead of defining each job separately (`test_7`, `test_11`, etc )
- Have `agent_integration_tests` extend `default_test_job`
- extract common gradle flags
- split gradle commands over multiple lines for easier readability
- unifying `GRADLE_OPS` and `--max-workers` .  That will require some experimentation but I think we can use a global values for all instead of slightly different versions for each job
- Experimenting with different `resource_class` values for higher job throughput
- Pulling out "collect reports" and "collect test results" into reusable commands

Circleci config cleanup

---

dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/MsgPackStatefulSerializer.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/FormatWriter.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/JsonFormatWriter.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/MsgpackFormatWriter.java
dd-trace-core/src/main/java/datadog/trace/core/util/LRUCache.java
dd-trace-core/src/test/groovy/datadog/trace/core/util/LRUCacheTest.groovy

Two optimizations to the msgpack serialization:
* Changes to a very simple LRU cache, since serialization is single threaded, instead of  the more heavyweight guava one, and also limits the entry length to 32 characters.
* Adds direct writing of Long/Integer as a String without materializing a String

Change the LRU cache in MsgpackFormatWriter and also write out Long/Integer directly

---

dd-java-agent/instrumentation/play-ws-1/src/main/java/datadog/trace/instrumentation/playws1/PlayWSClientInstrumentation.java
dd-java-agent/instrumentation/play-ws-2.1/src/main/java/datadog/trace/instrumentation/playws21/PlayWSClientInstrumentation.java
dd-java-agent/instrumentation/play-ws-2/src/main/java/datadog/trace/instrumentation/playws2/PlayWSClientInstrumentation.java

Fix for https://github.com/DataDog/dd-trace-java/issues/1563
Stops the play-ws integration from trying to instrument the `WebsocketUpgradeHandler`

#1563 do not attempt to instrument websocket upgrade handlers

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTTracer.java
dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTTracer.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
dd-java-agent/testing/src/test/groovy/muzzle/ReferenceCreatorTest.groovy
dd-java-agent/testing/src/test/java/muzzle/TestClasses.java

The muzzle compile time check failed to detect invalid references in the advice helper classes because they were simply `instanceof` checks.
I've updated muzzle to detect this problem and removed the references since they are not really necessary.
This might increase the instrumentation class's resident size due to more reference types being detected.
Reported in: #1566

Fix Regression in 0.54.0 in OpenTracing `addReference` usage

---

dd-java-agent/instrumentation/exception-profiling/src/main/java/datadog/exceptions/instrumentation/ThrowableInstrumentation.java
dd-java-agent/instrumentation/exception-profiling/src/main/java11/datadog/exceptions/instrumentation/ThrowableInstanceAdvice.java
dd-java-agent/instrumentation/exception-profiling/src/main/java11/datadog/exceptions/instrumentation/ThrowableInstanceAdviceHelper.java
dd-java-agent/instrumentation/exception-profiling/src/test/java/datadog/exceptions/instrumentation/ThrowableInstanceAdviceHelperTest.java
dd-smoke-tests/profiling-integration-tests/profiling-integration-tests.gradle
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/AbstractProfilingIntegrationTest.groovy
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/ProfilingIntegrationBogusApiKeyTest.groovy
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/ProfilingIntegrationContinuousProfilesTest.groovy
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/ProfilingIntegrationShutdownTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy

The throwable instance instrumentation handler is using code which in turn will end up using lazily linked lambdas - and as a part of the linkage process a `LinkageError` is thrown. Which will enter the throwable instrumentation handler code and so on and so forth.
This patch is adding a TLS flag which is supposed to prevent re-entrant execution of the instrumentation handler.
In addition to the main fix the smoke tests were updated to detect this kind of failure (and also other failures manifesting as ERROR or WARN messages in the test application log file) such that it can be detected earlier in the future.

Prevent re-entering throwable instrumentation handler

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java

Uses the name we will lookup by as the key in the HashMap during building, which has two effects:
1. Don't need to allocate - this explains some of the unreferenced strings I found in a heap dump taken with EpsilonGC
2. Might not need to compute the hash code during the lookup
I don't _think_ this changes behaviour, but I'm not entirely sure.

avoid creating new strings prior to jar lookup

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/HasSuperMethodMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/SafeHasSuperTypeMatcher.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/matcher/HasInterfaceMatcherTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/matcher/ImplementsInterfaceMatcherTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/matcher/SafeHasSuperTypeMatcherTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/matcher/ThrowOnFirstElement.groovy

reduces allocation during type matching at startup.
Evaluation:
run spring pet-clinic with `-XX:+UnlockExperimentalVMOptions -XX:+UseEpsilonGC -mx1G -XX:+HeapDumpOnOutOfMemoryError` to capture every allocated object in the first GB allocated. Results in reduction in `ArrayList` allocations by 1% of total (4th most commonly allocated object during startup)
```
before:
java.util.ArrayList           636,997 (4.1%)     20,383,904 B (1.6%)
after:
java.util.ArrayList           484,917   (3%)     15,517,344 B (1.2%)
``` 
Some tests weren't actually testing handling of an exception thrown during iteration, but simulated this by throwing on the `getInterfaces()` call - I fixed those.

Iterate type interfaces without materialising a list during super type matching

---

dd-smoke-tests/cli/src/main/resources/remove.tls.properties
dd-smoke-tests/cli/src/test/groovy/datadog/smoketest/CliApplicationSmokeTest.groovy
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java

When TLS was not configured in the JVM, the OkHttp client failed to start with `java.lang.AssertionError: No System TLS` despite the fact that we don't use TLS to communicate with the agent.
This change fixes that issue by limiting the OkHttp client to `http` only.
Tests are added for this case.  I also added a check to the base CLI test to make sure traces are actually sent (similar to the OT smoketests)

Allow OkHttp client to start when TLS is not configured

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java

I introduced some bad behaviour in #1562 - relying on $ in anonymous classnames is not safe, this PR reverts this. I also found that `Class.getAnonymousClass` is a relatively expensive call (500-1000ns, native, allocates for anonymous classes) where all we really care about is whether we have a name we can use or not.

BaseDecorator shouldn't rely on $ in class names

---

dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/Writer.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DispatchingDisruptor.java
dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentApiTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
dd-trace-core/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
utils/thread-utils/src/main/java/datadog/common/exec/DaemonThreadFactory.java

This PR has two parts:
1. It increase the timeouts for communicating to the agent from `1` second to `10` seconds, since the communication happens on a separate thread and won't block application. It also tries to connect to the agent as soon as the `writer` is started, again on the separate thread, to get the http client creation out of the way of normal sending.
2. It makes logging the results of agent communication more uniform, adds more information, and also logs the first success after a failure on `info` level. The first success after failure logging is subject to the same quiet period as failure logging.
Have tested and verified logging locally, since I can't figure out how to test that in unit tests in a nice way.
The timeout configuration option should be added to the docs. …

Increase agent communication timeouts and add more logging

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/dd-java-agent.gradle

Looking at heapdumps, the names we choose here take up way more space than we might think because they are prefixed to every class in our private classloaders. I wanted to name them `a.ddcls`, `b.ddcls`, `c.ddcls`, `d.ddcls` but @tylerbenson talked me out of it.

shorten jar names (prefixes of runtime classnames)

---

dd-java-agent/agent-mlt/src/main/java/com/datadog/mlt/sampler/ScopeStackCollector.java
utils/mlt-support/mlt-support.gradle
utils/mlt-support/src/main/java/com/datadog/mlt/io/AbstractLEB128Writer.java
utils/mlt-support/src/main/java/com/datadog/mlt/io/FrameSequence.java
utils/mlt-support/src/main/java/com/datadog/mlt/io/IMLTChunk.java
utils/mlt-support/src/main/java/com/datadog/mlt/io/LEB128ByteArrayWriter.java
utils/mlt-support/src/main/java/com/datadog/mlt/io/LEB128ByteBufferWriter.java
utils/mlt-support/src/main/java/com/datadog/mlt/io/LEB128Writer.java
utils/mlt-support/src/main/java/com/datadog/mlt/io/LEB128WriterFactory.java
utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTChunk.java
utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTWriter.java
utils/mlt-support/src/test/java/com/datadog/mlt/io/AbstractLEB128WriterTest.java
utils/mlt-support/src/test/java/com/datadog/mlt/io/LEB128ByteArrayReaderTest.java

This PR contains 2 commits:
- FrameSequence.length computation fix (non-contentious simple fix)
- A ByteBuffer backed implementation of the LEB128Writer

Easy MLT binary format writer perf fixes

---

dd-trace-ot/dd-trace-ot.gradle

A new dependency was added recently that wasn't fully excluded from the pom which broke things.  The previous system required editing in multiple places and was error prone.  This change attempts to centralize the required change into a single list.

Prevent shadow'd dependencies from being added to the pom

---

dd-java-agent/instrumentation/exception-profiling/src/main/java11/com/datadog/profiling/exceptions/ExceptionHistogram.java

Be consistent and use Class.getName() for both exception sample and histogram events

Fix discrepancy between exception histo and sample events

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/AdditionalLibraryIgnoresMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/LogContextScopeListener.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/ThreadLocalWithDDTagsInitValue.java
dd-java-agent/instrumentation/log4j1/src/main/java/datadog/trace/instrumentation/log4j1/Log4j1MDCInstrumentation.java
dd-java-agent/instrumentation/log4j2/src/main/java/datadog/trace/instrumentation/log4j2/ThreadContextInstrumentation.java
dd-java-agent/instrumentation/slf4j-mdc/src/main/java/datadog/trace/instrumentation/slf4j/mdc/MDCInjectionInstrumentation.java
dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/log/injection/LogContextInjectionTestBase.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java

Injecting 3 new tags :
- dd.service
- dd.version
- dd.env
in MDC of *every* thread for 3 supported logger interfaces . 
Logger instrumentation is disabled by default. It can be enabled by `-Ddd.logs.injection=true` .

Inject dd.{service|version|env} in logs

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/DatadogClassLoaderTest.groovy

This cuts another second off time to install the agent in spring pet clinic with JDK11
```
./start.sh install  2.73s user 0.14s system 206% cpu 1.386 total
./start.sh install  2.78s user 0.15s system 208% cpu 1.405 total
./start.sh install  2.91s user 0.15s system 210% cpu 1.452 total
./start.sh install  2.82s user 0.15s system 209% cpu 1.416 total
./start.sh install  2.81s user 0.16s system 208% cpu 1.424 total
./start.sh install  2.86s user 0.15s system 209% cpu 1.433 total
./start.sh install  2.87s user 0.15s system 209% cpu 1.439 total
./start.sh install  2.90s user 0.15s system 210% cpu 1.446 total
./start.sh install  2.88s user 0.15s system 209% cpu 1.445 total
./start.sh install  3.01s user 0.16s system 210% cpu 1.502 total
```
On master (JDK11):
```
./start.sh install  4.26s user …
```

do not eagerly load classfiles at startup

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/AdditionalLibraryIgnoresMatcher.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Decorator.java
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/spring-webmvc-3.1.gradle
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/DispatcherServletInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerMappingResourceNameFilter.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/WebApplicationContextInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/AppConfig.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/AuthServerConfig.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SavingAuthenticationProvider.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SecurityConfig.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SpringBootBasedTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/filter/ServletFilterTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy

`HandlerMappingResourceNameFilter` was injected before the entire `FilterChain`.  This was so that if a filter handled a request instead of a controller, the correctly tagged spans were still generated.
One unintended side effect was that in certain configurations, HMRNF set the character encoding to the servlet container default.   `SetCharacterEncodingFilter` is responsible for setting the character encoding but HMRNF ran before all filters.  HMRNF's use of `mapping.getHandler()` forced the lazy evaluation.
This is highlighted in the `test character encoding of #testPassword` test
Instead of running specially, `HandlerMappingResourceNameFilter` is injected into the WebApplicationContext and loaded as any other filter.  It has a a precedence of `HIGHEST_PRECEDENCE + 1` so it will run …

Fix Spring handler mapping affecting character encoding

---

dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyHandlerAdvice.java
dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyHandlerTest.groovy
dd-java-agent/instrumentation/servlet/request-2/src/test/groovy/JettyServlet2Test.groovy

This improves resource naming for Jetty by not setting a resource name and relying on `URLAsResourceNameRule`.  In the common case, the resource name becomes the request path instead of a usually static 
> GET org.eclipse.jetty.server.handler.HandlerList
When JAX-RS is being used, JAX-RS will set an even better resource name from the jax-rs annotations.

Use request path for Jetty resource name

---

dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DispatchingDisruptor.java
dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy

* Creating and opening the client connection to the Datadog Agent socket eagerly fails some instrumentation tests on IBM Java 8
Reverts small part of #1590

Revert eager creation of Datadog Agent client socket

---

dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/DispatcherServletInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerAdapterInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/SpringWebHttpServerDecorator.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/WebApplicationContextInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SpringBootBasedTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/filter/ServletFilterTest.groovy

I noticed an anonymous class being used where a data parameter would do whilst investigating something else. This reduces a class load, is another class which doesn't need to be muzzled or otherwise matches, another entry which doesn't need to be cached anywhere, and so on. Also uses the class's simple name instead of full name for the "view.type" property.

remove anonymous class from spring webmvc-3.1

---

dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/DBTypeTagInterceptor.java
dd-trace-core/src/main/java/datadog/trace/core/util/FixedSizeCache.java
dd-trace-core/src/test/groovy/datadog/trace/core/util/FixedSizeCacheTest.groovy

It may not look like much, but it gets called often enough to account for ~4.5% of all `char[]` memory during `pet-clinic` steady state.

Cache Strings in DBTypeTagInterceptor

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/Reference.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceMatcher.java
dd-java-agent/testing/src/test/groovy/muzzle/ReferenceCreatorTest.groovy

* Prevents from repeatedly checking very common JDK classes
* Mismatches are exceptional so only allocate an `ArrayList` when they happen

Exclude JDK class references at build time, reduce allocation in ReferenceMatcher

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java

A line is logged every time the classloader didn't have a class.  It's very noisy in the debug logs

Remove noisy logging in InternalJarURLHandler

---

gradle/dependencies.gradle

This fixes the version of okio in the shared classloader.  Previously, the version of okio used by dd-trace-core for debug logging was pulled up to 1.16.0 by the com.squareup.moshi:moshi dependency.
Output of `./gradlew :dd-trace-core:dependencies --configuration runtimeClasspath`:
```
+--- com.squareup.okhttp3:okhttp:3.12.12
|    \--- com.squareup.okio:okio:1.15.0 -> 1.16.0
+--- com.squareup.moshi:moshi:1.9.2
|    \--- com.squareup.okio:okio:1.16.0
...
```
Since only okhttp was moved to the shared classloader and not moshi, the transitive dependency was no longer overridden
Output of `./gradlew :dd-java-agent:dependencies --configuration sharedShadowInclude` before this pull request:
```
+--- com.squareup.okhttp3:okhttp:3.12.12
|    \--- com.squareup.okio:okio:1.15.0
...
```
By …

Fix okio dependency in shared classloader

---

dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java

Because of the lazy determination of `tracesUrl`, the `toString()` of DDAgentApi showed as:
> DDApi { tracesUrl=null }
This has lead to user confusion on multiple occasions.
I did not change the `toString()` to use a more complicated algorithm (eg "unset") because we already have logging for when the URL is downgraded to v3 from v4.  We also have logging for agent host and agent port.

Remove confusing DDAgentApi toString

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInstrumentation.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/SpanAssert.groovy
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InstrumentationTags.java

Changes the handling of Kafka tombstones (where there are no headers and the body is null).
1. We don't propagate through tombstones, since they are logically terminal operations. We tag the producer span as being a tombstone.
2. If we detect a tombstone during consumption, we still create a span to indicate that a tombstone has been consumed, but tag as a tombstone and won't compute an e2e duration since no baggage can have been propagated in this case.
There is a [proposal](https://cwiki.apache.org/confluence/display/KAFKA/KIP-87+-+Add+Compaction+Tombstone+Flag) for a tombstone flag which we may be able to use in the future.

Handle kafka tombstones 

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java

#1606 introduced some dodgy handling of services loaded from META-INF, this change reverts it.

don't try to extract package names from META-INF

---

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/StreamUtils.java

Currently, our LZ4 compression is using LZ4 Frame format with default block size which is 4MB. The decompressor will then pre-allocated 4MB byte array for each chunk of data although it almost never needed. This is driving the increased allocation pressure in our backend without any other benefits.
The block size is controlled by the creator of the compressed data so the change must be in agent.

Change LZ4 config to reduce allocation rate during decompression

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
dd-java-agent/instrumentation/log4j2/src/main/java/datadog/trace/instrumentation/log4j2/ThreadContextInstrumentation.java
dd-java-agent/instrumentation/slf4j-mdc/src/main/java/datadog/trace/instrumentation/slf4j/mdc/MDCInjectionInstrumentation.java
dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java

1. Don't instrument org.apache.logging.log4j.ThreadContext's ThreadLocal field in case Log4j-to-SLF4J Adapter detected
1. delete casting to MDCAdapter because we shadowing it to datadog.slf4j.spi.MDCAdapter
1. `./gradlew spotlessApply`  also added some changes to this PR :)

Don't instrument org.apache.logging.log4j.ThreadContext's ThreadLocal field in case Log4j-to-SLF4J Adapter detected

---

.palantir/revapi.yml
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCMaps.java
dd-java-agent/instrumentation/opentelemetry/src/main/java/datadog/trace/instrumentation/opentelemetry/OtelSpan.java
dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTSpan.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTSpan.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/SpanAssert.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
dd-trace-api/src/main/java/datadog/trace/api/interceptor/MutableSpan.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
dd-trace-core/src/main/java/datadog/trace/core/processor/rule/DBStatementRule.java
dd-trace-core/src/main/java/datadog/trace/core/processor/rule/ResourceNameRule.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/FormatWriter.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/JsonFormatWriter.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/MsgpackFormatWriter.java
dd-trace-ot/src/main/java/datadog/opentracing/OTSpan.java
internal-api/internal-api.gradle
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/UTF8BytesString.java
internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/Utf8ByteStringTest.groovy

This PR drops time spent in encoding and serializing for the aggressive `pet-clinic` from 28% to 22% by not re-encoding the JDBC prepared statements, and the resource name. Looking at the profile this change seems to increase the overflow of the message buffer in msgpack somewhat.
It has two parts:
1. Switch the `Resource Name` from a `String` to a `CharSequence`. Yes, there are no immutability guarantees for a `CharSequence` but this is an internal API, and it's the one `interface` that can easily be implemented by something that want's to wrap a `String`, where you could just use a `String` instead.
2. Introduce a wrapper class `UTF8BytesString` that caches the `byte[]` and hands out the same one for every call to `getUtf8Bytes`, and change the JDBC decorator and prepared statement …

Cache the UTF8 bytes for prepared statements

---

dd-java-agent/agent-mlt/src/main/java/com/datadog/mlt/sampler/JMXSampler.java
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/ProfilingIntegrationMLTTest.groovy

This logging generates 50-100+ lines of 
> Collecting stacktraces for 1 thread
**per request** in petclinic

Remove overly verbose logging

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/DeadlockEvent.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/DeadlockEventFactory.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/DeadlockedThreadEvent.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/events/DeadlockEventFactoryTest.java
dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/ProfilingTestApplication.java
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/AbstractProfilingIntegrationTest.groovy
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/ProfilingIntegrationContinuousProfilesTest.groovy
dd-smoke-tests/profiling-integration-tests/src/test/resources/overrides.jfp

Periodically check for deadlocked threads using JMX `ThreadMXBean` and emit a series of events describing the locking cycle. 
Unfortunately, JFR user (Java) definable events do not support any non-scalar attributes and as such the list of affected threads had to be decomposed into a list of separate events. 
Additionally, it also makes it impossible to capture the full stack trace of threads in dead-lock so the information must be extracted and only the locker-waiter frames are reported if available (j.u.concurrent locks do not provide info about which frame locked them).
In addition to unit tests the profiling smoke test was extended to have a guaranteed deadlock and the test recording is then asserted for the presence of the deadlock related events.

Deadlock detection JFR events

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java

span.getTime() function looks to be inherited from MutableSpan which produces a [Nanosecond value](https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-api/src/main/java/datadog/trace/api/interceptor/MutableSpan.java#L7-L8)
Changing the converter for setting the start time so it is properly converted otherwise all e2e value calculations end up being 0

switch microseconds to nanoseconds

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TextMapExtractAdapter.java
dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/TextMapExtractAdapter.java

Based on the issue here: https://github.com/DataDog/dd-trace-java/issues/1631
Tested on our side, worked fine then: no more error, tracing is working on the service (we can see metrics in Datadog like trace.kafka.consume.duration)

Handle null header values

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java

Prevents the tracer from failing to instrument when micronaut tracing is present.

ignore micronaut tracing classes

---

dd-trace-api/dd-trace-api.gradle
dd-trace-api/src/main/java/datadog/trace/api/DDId.java
dd-trace-api/src/test/groovy/datadog/trace/api/DDIdTest.groovy

This one comes from a support issue where Kafka Mirrormaker was reportedly base64 encoding Kafka headers, and the user was complaining that we wouldn't parse the trace IDs. I've investigated and there is no way to detect that this has happened, except trying to base64 decode the headers. Doing this "just in case" in the Kafka instrumentation would give other users a significant performance regression so we don't want to do this unless absolutely necessary. This isn't really the tracer's fault and the user needs to prevent infrastructure from mangling header data, but attempting to base64 decode in a catch block in `DDId.from` helps the user diagnose and fix their problem, avoids breaking trace lineage if they can't fix it right away, whilst preventing other users from paying for it.

attempt to base64 decode invalid DDIds 

---

.palantir/revapi.yml
dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/Writer.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/Monitor.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
gradle/dependencies.gradle

Previously, the StatsD client was solely used by `DDAgentWriter` through the `Monitor` interface.  This pull request moves the client into `CoreTracer` so that other components will be able to report health metrics.
Additionally, the creation of DDAgentWriter was moved into `CoreTracer` for the following reasons:
- There was a confusing cycle of where the StatsD client was created and passed into the various builders
- CoreTracer still needs to do extra configuration to add the sampler as a ResponseListener on the writer (for RateByService sampling)
- `Writer.Builder` didn't have a real use case.  Users wanting customization could either pass in their own `Writer`, customize the default Writer with the `Config` class, or customize with `DDAgentWriter.Builder`.  `Writer.Builder` returned a …

Move the StatsDClient into CoreTracer

---

dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/StringTables.java
dd-trace-core/src/main/java/datadog/trace/core/processor/rule/MethodLevelTracingDataRule.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/FormatWriter.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/JsonFormatWriter.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/MsgpackFormatWriter.java

When disabled, the profile data will be added as a `blob` field on the msgpack span.
This should only impact the serialization thread, not necessarily improve the application thread request latency.
Use the following setting to disable:
```
-Ddd.method.trace.encode.data=false
```

Allow disabling of encoding MLT

---

dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/main/java/datadog/trace/api/env/CapturedEnvironment.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
dd-trace-api/src/test/groovy/datadog/trace/api/env/CapturedEnvironmentTest.groovy
dd-trace-api/src/test/groovy/datadog/trace/api/env/FixedCapturedEnvironment.java
utils/test-utils/src/main/groovy/datadog/trace/util/test/DDSpecification.groovy

As first approach, it will be consider either the JAR name or the main class name as substitute of the current `unnamed-java-service`, in case that this info could be calculated.
This PR has two parts:
1) Modification of the `Config`: Added a new step in the `getSettingFromEnvironment` to check if the requested property was set in the `CapturedEnvironment` properties.
2) Creation of the `CapturedEnvironment`: This class should keep all environment properties which are platform dependant. In this particular case, the Java System Property `sun.java.command` will be used to obtain the JAR/Main Class information.
Besides this property is not a standard, all main JDKs has set this property.
Tested on: `OracleJDK`, `OpenJDK`, `AdoptOpenJDK`, `IBM JDK`, `Azul Zulu JDK`, `Amazon Coretto JDK` …

Automatic service naming

---

dd-java-agent/instrumentation/opentelemetry/src/main/java/datadog/trace/instrumentation/opentelemetry/OtelTracer.java
dd-java-agent/instrumentation/opentelemetry/src/test/groovy/OpenTelemetryTest.groovy
dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTScopeManager.java
dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTTracer.java
dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTScopeManager.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTTracer.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerDepthTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
dd-trace-ot/src/main/java/datadog/opentracing/OTScopeManager.java
dd-trace-ot/src/test/groovy/datadog/opentracing/OpenTracingAPITest.groovy
internal-api/internal-api.gradle
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScopeManager.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ScopeSource.java

This pull requests addresses silent failures when trying to close scopes by:
1.  Incrementing a statsd counter when a scope is not closed because it is not on top
2. Adding the `dd.trace.scope.strict.mode` flag where this error throws a `RuntimeException` instead of being silent
To accomplish this, `ContinuableScope` now tracks whether the scope was created manually or through automatic instrumentation.  This change is completely internal.  No instrumentation or external APIs changed.

Strict mode and health metrics for scope close failures

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java

Do not log the failure to initialize the JMX thread deadlock detector at the 'error' level with full stacktrace as it may confuse the customers into thinking a real error occurred. Rather, provide a simple state describing message at 'info' level.

Make JMX thread deadlock detector init fail graciously

---

dd-java-agent/instrumentation/kafka-clients-0.11/kafka-clients-0.11.gradle
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/Base64Decoder.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInstrumentation.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TextMapExtractAdapter.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/TextMapExtractAdapterTest.groovy
dd-trace-api/dd-trace-api.gradle
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/main/java/datadog/trace/api/DDId.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
dd-trace-api/src/test/groovy/datadog/trace/api/DDIdTest.groovy
dd-trace-core/dd-trace-core.gradle

reverts the fallback to base 64 in `DDId` and moves a configuration enabled (default false) base 64 decoding setting to the kafka client instrumentation

add config based base64 decoding to kafka instrumentation

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/TextMapExtractAdapterTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java

`KafkaClientTest` was failing in some cases because `TextMapExtractAdapterTest` didn't extend `AgentTestRunner` and caused `Config` to be loaded on the system classpath before it could be injected into the bootstrap classpath by `KafkaClientTest`.
This adds an assertion in `AgentTestRunner` to help better identify the problem, and makes `TextMapExtractAdapterTest` extend `AgentTestRunner` instead to ensure the classpath is setup correctly regardless of which test executes first.

Config class should be loaded on the bootstrap for instrumentation tests.

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AkkaExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ScalaExecutorInstrumentation.java

Similar to what was done elsewhere.  This was missed because it is a child of the abstract class where the actual type matcher is at.

Add classloader matcher to validate scala/akka presence

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/DatadogClassLoader.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/DatadogClassLoaderTest.groovy

Since the introduction of the `DelegateClassloader` in `DatadogClassLoader` and the associated refactoring this entailed, the Datadog classloader has been susceptible to a race condition when multiple threads are initialised and attempt to load DataDog agent classes as the same time. This is due to the `loadFromPackage` in `DatadogClassLoader` and `loadClass` in `DelegateClassLoader` both un-synchronized calls to `findLoadedClass` and then `findClass` if this first call returns `null`. As repeated call to `findClass` cause the JVM to throw a `LinkageError` due to the attempt to define a class with the same fully-qualified name more than once, this race condition results in the affected threads failing to initialise.
To overcome this, the two impacted methods have both had …

Fix multi-threaded classloading of DataDog agent classes

---

dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/PropagationStyle.java
dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpExtractorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpInjectorTest.groovy

This led to weird test failures occasionally (where the method on `Config` wouldn't even get invoked, so it wasn't a case of the method throwing during `clinit`). 
```
java.lang.ExceptionInInitializerError
at datadog.trace.api.ConfigDefaults.<clinit>(ConfigDefaults.java:7)
at datadog.trace.common.writer.DDAgentWriter$DDAgentWriterBuilder.<init>(DDAgentWriter.java:50)
at datadog.trace.common.writer.DDAgentWriter.builder(DDAgentWriter.java:57)
at datadog.trace.api.writer.DDAgentWriterTest.check that are no interactions after close(DDAgentWriterTest.groovy:196)
Caused by: java.lang.NullPointerException
at datadog.trace.api.Config.parseStringIntoSetOfNonEmptyStrings(Config.java:1414)
at datadog.trace.api.Config.getPropagationStyleSetSettingFromEnvironmentOrDefault(Config.java:1156)
at …
```

break circular dependency between Config and ConfigDefaults

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/ConfigUtils.groovy
dd-trace-api/src/main/java/datadog/trace/api/Config.java
utils/test-utils/src/main/groovy/datadog/trace/util/test/DDSpecification.groovy

Avoid the need to modify at test runtime and add comment to help in future circumstance.

Simplify Config runtime id handling

---

dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerMappingResourceNameFilter.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/WebApplicationContextInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/filter/TestController.groovy

This is a backport of https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/705
Before this change, if the request attribute isn't set, then the rest of the filter chain would not be called.  This could only happen if our instrumentation was broken somehow but we should still guard against that.
I was unable to create a test for this condition.  Removing the attribute manually, the servlet instrumentation would readd a new span.  I think the only way might be to run with the Spring instrumentation but without the Servlet instrumentation.
Additionally I added a little javadoc and clarified the role of `TestController` in filter tests.

Fix Spring filter instrumentation edge case

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/AdditionalLibraryIgnoresMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/LogContextScopeListener.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/ThreadLocalWithDDTagsInitValue.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ClassLoaderMatcherTest.groovy
dd-java-agent/instrumentation/log4j1/src/main/java/datadog/trace/instrumentation/log4j1/Log4j1MDCInstrumentation.java
dd-java-agent/instrumentation/log4j1/src/test/groovy/Log4j1MDCTest.groovy
dd-java-agent/instrumentation/log4j2/src/main/java/datadog/trace/instrumentation/log4j2/ThreadContextInstrumentation.java
dd-java-agent/instrumentation/log4j2/src/test/groovy/Log4jThreadContextTest.groovy
dd-java-agent/instrumentation/log4j2/src/test/groovy/Log4jThreadContextWithEnableThreadLocalsTest.groovy
dd-java-agent/instrumentation/slf4j-mdc/src/main/java/datadog/trace/instrumentation/slf4j/mdc/MDCInjectionInstrumentation.java
dd-java-agent/instrumentation/slf4j-mdc/src/test/groovy/Slf4jMDCTest.groovy
dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/log/injection/LogContextInjectionTestBase.groovy
dd-java-agent/testing/src/main/java/datadog/trace/agent/test/utils/UnsafeUtils.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java

1. revert of this revert : https://github.com/DataDog/dd-trace-java/pull/1662revert of this revert : https://github.com/DataDog/dd-trace-java/pull/1662
1. fix for https://github.com/DataDog/dd-trace-java/issues/1654 and test for it: 
The issue https://github.com/DataDog/dd-trace-java/issues/1654 was introduced after instrumentation of log4j2. Original instrumentation assumed that interface ThreadContextMap always contains threadlocal field with instance of Map in generic parameter.
```
ThreadLocal<Map<?, ?>> localMap
```
In fact, log4j2 has 2 other implementations ( [CopyOnWriteSortedArrayThreadContextMap](https://github.com/apache/logging-log4j2/blob/master/log4j-api/src/main/java/org/apache/logging/log4j/spi/CopyOnWriteSortedArrayThreadContextMap.java) , …

Add DD tags to log instrumentations

---

dd-java-agent/agent-mlt/agent-mlt.gradle
dd-java-agent/agent-mlt/src/main/java/com/datadog/mlt/sampler/ScopeStackCollector.java
dd-java-agent/agent-mlt/src/test/java/com/datadog/mlt/sampler/ScopeManagerTest.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/TraceProfilingScopeInterceptor.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/TraceProfilingScopeInterceptorTest.groovy
utils/mlt-support/mlt-support.gradle
utils/mlt-support/src/main/java/com/datadog/mlt/io/FrameSequence.java
utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTChunk.java
utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTChunkCollector.java
utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTWriter.java
utils/mlt-support/src/test/java/com/datadog/mlt/io/FrameSequenceTest.java

Also increase span priority for MLT traces and use existing span priority as a signal for the heuristic.
Includes some changes for the decoder to allow iteration in both directions.

MLT - Avoid sending only base stacktrace

---

dd-java-agent/instrumentation/finatra-2.9/finatra-2.9.gradle
dd-java-agent/instrumentation/finatra-2.9/src/latestDepTest/groovy/FinatraServer270Test.groovy
dd-java-agent/instrumentation/finatra-2.9/src/latestDepTest/groovy/NettyServerTestInstrumentation.java
dd-java-agent/instrumentation/finatra-2.9/src/latestDepTest/scala/FinatraController.scala
dd-java-agent/instrumentation/finatra-2.9/src/latestDepTest/scala/FinatraServer.scala
dd-java-agent/instrumentation/finatra-2.9/src/latestDepTest/scala/ResponseSettingExceptionMapper.scala

At `20.7.0` Finatra removed the `started` property from HttpServer.  This caused `latestDepTest` to fail.
This pull request addresses the change by checking for the startup event.  After this pull request, there are 3 distinct test sets: 
- 19.12
- everything up until 20.7
- the latest.
At first, I attempted to reuse the test code more however I could not get the testSets plugin, scala, and Finatra to behave.  I'm sure it could be done with a little more effort.  For now, I just copy/pasted the test code.  The only difference between the tests is `startServer()`

Fix finatra tests for latest dependencies

---

utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTChunkCollector.java

This was expensive, so we want to do it the first time collect is called, which will be on a background thread.

MLT - Delay processing of stacktrace on construct

---

dd-java-agent/instrumentation/spring-webflux-5/spring-webflux-5.gradle
dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientDecorator.java

Allows support for non-standard HTTP status codes which webflux allows access to from 5.1.0+ via method handles. Still works with older webflux versions but the absence of `ClientResponse.rawStatusCode` will raise an error and default to the strict mode of webflux 5.0.0, which is all we can really do.
I muzzle all combinations of `spring-webflux/reactor-netty` except for webflux 5.0.0/reactor-netty 0.8.0 which can't exist.
I ruled out cloning the instrumentation for webflux 5.1.0+ because it would lead to too much duplication, and I found no good way to detect which webflux version was present. I also ruled out dropping support for webflux 5.0.0.

use spring-webflux-5.1+ ClientResponse.rawStatusCode when available

---

dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/Packer.java
dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/VerifyThatPackerDoesNotThrowInvalidMarkException.java

As of #1659 we no longer handle huge (over 2MB) traces gracefully. This is the first part of a fix for this, which prevents the `Packer`'s buffer from ever getting in to an unmarked state.

prevent packer's buffer from getting into unmarked state

---

dd-java-agent/instrumentation/spring-scheduling-3.1/src/main/java/datadog/trace/instrumentation/springscheduling/SpringSchedulingInstrumentation.java
dd-java-agent/instrumentation/spring-scheduling-3.1/src/main/java/datadog/trace/instrumentation/springscheduling/SpringSchedulingRunnableWrapper.java

This works around an edge case where Spring Sleuth tries to load the RunnableWrapper's enclosing class:
https://github.com/spring-projects/spring-framework/blob/v5.2.2.RELEASE/spring-core/src/main/java/org/springframework/core/annotation/AnnotationsScanner.java#L233
Since the enclosing class is on a separate class loader, this fails and results in an exception.

Move Spring Scheduling RunnableWrapper to separate class

---

dd-java-agent/instrumentation/log4j2/src/test/groovy/Log4jThreadContextWithEnableThreadLocalsTest.groovy
dd-java-agent/testing/src/main/java/datadog/trace/agent/test/utils/UnsafeUtils.java

log4j2:testJava14Generated crashes in VM G1 code after setting static final field by Unsafe. This change tries to fix this test problem

UnsafeUtils::setStaticFieldViaUnsafe should use putBooleanVolatile

---

dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapper.java
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanSerializationTest.groovy

While working on optimizing the tags map, I ran into this little gem, that can make us write a bad `msgpack` message with a map with higher count than actual entries. Been there since we stopped merging the baggage and tags into a common map before writing.

Don't double count baggage overridden by tag

---

dd-java-agent/agent-mlt/src/main/java/com/datadog/mlt/sampler/ScopeStackCollector.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/TraceProfilingScopeInterceptor.java
utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTChunkCollector.java

Turns out `getStackTrace` is quite expensive and not feasible to use on the critical path.  Hopefully `fillInStackTrace` isn't so expensive.

MLT - Attempt at using `fillInStackTrace` to reduce overhead

---

dd-java-agent/instrumentation/junit-4.10/junit-4.10.gradle
dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Instrumentation.java
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/Config.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java

Removed specific configuration properties for `JUnit` integration.
The property `dd.integrations.junit.enabled=true` will be used instead of that.

Remove specific configuration properties for JUnit integration.

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-trace-core/src/main/java/datadog/trace/core/util/ThreadCpuTimeAccess.java

* Put all "not initializing" messages at `info` level.  The log has messages like "Initializing ..." at info, but then the "Not started because..." messages are hidden unless at `debug`
* Don't print known exceptions at `debug`.  This continues to lead to confusion when users are running a jdk with JFR events

Consistent error messaging for profiling startup

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java

These classloaders are so cheap to skip that the check doesn't require caching.

don't cache classloaders which can be skipped by name

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/api/FixedSizeCache.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsDecorator.java

This caches the kafka resource names which avoids recomputing string hash codes during serialisation, once we start deduplicating strings this will become important.

cache kafka resource names

---

dd-trace-core/src/main/java/datadog/trace/common/writer/PrintingWriter.java
dd-trace-core/src/test/groovy/datadog/trace/api/writer/PrintingWriterTest.groovy

Annoyingly, I missed that `com.squareup.moshi.JsonWriter` can't be reused.  The PrintingWriter fails on the second call to `write()` 🤦 .

PrintingWriter fails on second trace

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/DatadogClassLoader.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/InternalJarURLHandlerTest.groovy

this just reproduces the default classloader locking behaviour which happens to reduce the granularity of the lock

finer grained synchronization for classloading of agent classes

---

dd-java-agent/instrumentation/hystrix-1.4/src/main/java/datadog/trace/instrumentation/hystrix/HystrixDecorator.java
dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableChainTest.groovy
dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableTest.groovy
dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

This disables most hystrix tags by default, which can be enabled by setting `DD_HYSTRIX_TAGS_ENABLED` to true if users are interested in these tags. The reason for doing this is that we have found that users are willing to disable the hystrix integration entirely to reduce trace size, but this integration tends to glue traces together. The tags in the hystrix integration tend to be very long (e.g. fully qualified class names), and are mostly duplicated in the resource name. These can still be enabled and haven't just been removed because there are users who find the tags beneficial.

disable hystrix tags by default, enabled by system property

---

dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/HaystackHttpCodec.java
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpExtractorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpInjectorTest.groovy

* Enhancement to the Haystack Codec to add support for common use of UUID as an identifier format
* Add tag for original Haystack Trace ID to be preserved for continuous stitching between multiple systems (HS -> DD -> HS)

Haystack Support with UUID

---

dd-java-agent/instrumentation/opentelemetry/src/test/groovy/OpenTelemetryTest.groovy
dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerDepthTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy

The functional part of this change is simply improving out-of-order close behavior.
Previously, given a stack C, B, A...
If B was closed out-of-order, then C would be left on-top.
Once C was closed, B would be restored to the top of stack.
But B would need to be closed again, which would in turn restore C.
This behavior could then lead to unbounded stack growth.
The new code behaves better -- given a stack C, B, A...
If B is closed out-of-order, then C would be left on-top
Once C is closed, the stack will skip over B, since it is already closed -- returning to A.
Then A can be closed properly (without any additional closes of B or C).
Ultimately, this doesn't entirely eliminate the possibility of having the stack grow indefinitely, 
but I believe it does reduce it significantly.
In …

Out-of-Order Scope Close Handling

---

dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy

I implemented this based on advice on a community issue that headers could prevent log compaction, without attempting to reproduce. I have since spoken to someone involved in the implementation of Kafka who reassured me that headers have no impact on log compaction whatsoever, so reverting the change, but keeping the tag in place because it seems useful.

allow context propagation for kafka tombstones

---

dd-java-agent/instrumentation/grizzly-http-2.3.20/src/main/java/datadog/trace/instrumentation/grizzlyhttp232/GrizzlyDecorator.java

This applies the same fix as https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/887
Thanks @trask!

Fix grizzly host/port identification

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakMap.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakMapSuppliers.java

~~The main effort here is to prevent the `WeakMap`s created by the hundreds of `HelperInjector` instances we create from creating a background chore, each of which executes for the entire application's life, since there's only one executor (second commit). This way we push the cost of expunging entries to when these maps are in use, i.e. early on.~~
The tweaks to `MapAdapter` are of secondary importance.

mapadapter tweaks

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java

This prevents copying the trace twice when partial spans occur

avoid unnecessary allocation in handoff between PendingTrace and CoreTracer 

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/ThreadLocalWithDDTagsInitValue.java
dd-java-agent/instrumentation/log4j1/src/test/groovy/Log4j1MDCTest.groovy
dd-java-agent/instrumentation/log4j2/src/main/java/datadog/trace/instrumentation/log4j2/ThreadContextInstrumentation.java
dd-java-agent/instrumentation/log4j2/src/test/groovy/Log4jThreadContextTest.groovy
dd-java-agent/instrumentation/slf4j-mdc/src/main/java/datadog/trace/instrumentation/slf4j/mdc/MDCInjectionInstrumentation.java
dd-java-agent/instrumentation/slf4j-mdc/src/test/groovy/Slf4jMDCTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/log/injection/LogContextInjectionTestBase.groovy

original threadlocal map value should be synchronized while copied to another map
Like it done here: https://github.com/qos-ch/logback/blob/a6356170acfa6ce6e2383477bf80e6cae8a82d80/logback-classic/src/main/java/ch/qos/logback/classic/util/LogbackMDCAdapter.java#L77 
issue: https://github.com/DataDog/dd-trace-java/issues/1753

Add synchronization while adding dd tags to thread context(MDC) map

---

dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy
dd-java-agent/testing/src/test/groovy/AgentTestRunnerTest.groovy
internal-api/internal-api.gradle
internal-api/src/main/java/datadog/trace/mlt/Invocation.java
internal-api/src/main/java/datadog/trace/mlt/InvocationImplDefault.java
internal-api/src/main/java9Impl/datadog/trace/mlt/InvocationImplStackWalker.java
internal-api/src/test/groovy/datadog/trace/mlt/InvocationTest.groovy

Adding a unified API to get the invocation caller which will dispatch to the appropriate runtime implementation.
For Java 7 and 8 we need to use a security manager based hack while for Java 9+ we can use StackWalker API to achieve the same effect (and provide even more information).

Add Invocation Caller API to internal-api

---

utils/mlt-support/mlt-support.gradle

I had to manually remove it from bintray before syncing with sonatype for 0.60.0 release.

MLT Support should not be published.

---

dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyHandlerAdvice.java
dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

This can be considered sensitive to some users, so better to require explicit config to enable.

Disable collection of user principal by default

---

dd-java-agent/instrumentation/elasticsearch/transport-2/src/main/java/datadog/trace/instrumentation/elasticsearch2/Elasticsearch2TransportClientInstrumentation.java
dd-java-agent/instrumentation/elasticsearch/transport-2/src/main/java/datadog/trace/instrumentation/elasticsearch2/TransportActionListener.java
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/main/java/datadog/trace/instrumentation/elasticsearch5_3/Elasticsearch53TransportClientInstrumentation.java
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/main/java/datadog/trace/instrumentation/elasticsearch5_3/TransportActionListener.java
dd-java-agent/instrumentation/elasticsearch/transport-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/Elasticsearch5TransportClientInstrumentation.java
dd-java-agent/instrumentation/elasticsearch/transport-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/TransportActionListener.java
dd-java-agent/instrumentation/elasticsearch/transport-6/src/main/java/datadog/trace/instrumentation/elasticsearch6/Elasticsearch6TransportClientInstrumentation.java
dd-java-agent/instrumentation/elasticsearch/transport-6/src/main/java/datadog/trace/instrumentation/elasticsearch6/TransportActionListener.java
internal-api/src/main/java/datadog/trace/api/utils/Strings.java
internal-api/src/test/groovy/datadog/trace/api/utils/StringsTest.groovy

This aims to remove one of our dependencies on guava, so we can get closer to removing it since it's nearly 20% of our artefact size. I followed the contract of JDK8+ `String.join` so we can replace the new method with that once JDK7 is dropped.

replace guava Joiner with Strings.join

---

dd-java-agent/agent-bootstrap/agent-bootstrap.gradle
dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
dd-java-agent/agent-logging/agent-logging.gradle
dd-java-agent/agent-logging/src/main/java/datadog/slf4j/impl/StaticLoggerBinder.java
dd-java-agent/agent-logging/src/main/java/datadog/slf4j/impl/StaticMDCBinder.java
dd-java-agent/agent-logging/src/main/java/datadog/slf4j/impl/StaticMarkerBinder.java
dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/DDLogger.java
dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/DDLoggerFactory.java
dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LogLevel.java
dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LoggerHelper.java
dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LoggerHelperFactory.java
dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatFactory.java
dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatHelper.java
dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatSettings.java
dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/DDLoggerTest.groovy
dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/LogLevelTest.groovy
dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/simplelogger/SLCompatHelperTest.groovy
dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/simplelogger/SLCompatSettingsTest.groovy
dd-java-agent/agent-logging/src/test/resources/slcompatsettingstest.properties
dd-java-agent/agent-profiling/agent-profiling.gradle
dd-java-agent/agent-tooling/agent-tooling.gradle
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Constants.java
dd-java-agent/dd-java-agent.gradle
dd-java-agent/instrumentation/instrumentation.gradle
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/SpockRunner.java
dd-smoke-tests/opentracing/opentracing.gradle
settings.gradle

This is the first step towards better logging.
It adds our own Logger implementation, using the shaded SLf4J API. This first logger is a drop in replacement for the SimpleLogger in both configuration and behavior so there should be no noticeable difference for the end user.
Going forward we can start to support markers, and runtime switchable log levels.

Replace SLF4J SimpleLogger with own compatible implementation

---

dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/Prioritization.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingWorker.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/PrioritizationTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/TraceProcessingWorkerTest.groovy

It's pretty clear that low core environments don't take kindly to busy spinning, and I think we're better off blocking for this use case.

Use blocking queue implementation for prioritisation

---

dd-java-agent/instrumentation/reactor-core-3.1/src/main/java8/datadog/trace/instrumentation/reactor/core/TracingSubscriber.java

Occasional NPEs when things race.

Fix double read of shared atomic in reactor instrumentation

---

dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Instrumentation.java
dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Utils.java
dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/TracingListener.java

In this PR, the JUnit4 tracing logic has been encapsulated in the `datadog.trace.instrumentation.junit4.TracingListener`, which is a JUnit4 [RunListener](https://junit.org/junit4/javadoc/4.12/org/junit/runner/notification/RunListener.html).
This `datadog.trace.instrumentation.junit4.TracingListener` is added as another listener when the `Runner.run(RunNotifier notifier)` method is invoked. This approach follows the standard way of listening to the test events based on its public API.

CI-App: JUnit4 - Use a RunListener to send traces

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/AdditionalLibraryIgnoresMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
dd-java-agent/instrumentation/classloading/src/main/java/datadog/trace/instrumentation/classloading/ClassloadingInstrumentation.java

As part of #1293 we started instrumenting a couple of spring class loaders that all delegate class loading properly. This can have a big impact on application startup time in some cases.

Don't instrument well behaved spring class loaders

---

dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerMappingResourceNameFilter.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/dynamic/ClearRequestContext.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/dynamic/DynamicHandlerMapping.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/dynamic/DynamicRoutingAppConfig.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/dynamic/DynamicRoutingConfig.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/dynamic/DynamicRoutingTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/dynamic/HandlerMappingConfiguration.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/dynamic/TestController.groovy

Currently, we invoke all of the `HandlerMapping`s from `HandlerMappingResourceNameFilter` hoping to get the property `BEST_MATCHING_PATTERN_ATTRIBUTE` set on the request as a side effect. This has other side effects like invoking a `HandlerMapping` too soon, such as before thread local `RequestAttributes` have been set in highly customised implementations - hitting the error condition below: in `RequestContextHolder`:
```
/**
* Return the RequestAttributes currently bound to the thread.
* <p>Exposes the previously bound RequestAttributes instance, if any.
* Falls back to the current JSF FacesContext, if any.
* @return the RequestAttributes currently bound to the thread
* @throws IllegalStateException if no RequestAttributes object
* is bound to the current thread
* @see …
```

Better instrumentation support for dynamic Spring HandlerMapping

---

dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/client/WebClientTracingFilter.java
dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientBase.groovy
dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientBasicTest.groovy
dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientBuilderReuseTest.groovy
dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientFilterBuilderReuseTest.groovy
dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientFilterTest.groovy

The `WebClient.Builder` can be reused and we would add our filter multiple times, creating multiple spans.

Don't add webflux filter multiple times

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/TestDecorator.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/BaseDecoratorTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/TestDecoratorTest.groovy
dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Decorator.java
dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/TracingListener.java
dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGDecorator.java
dd-java-agent/instrumentation/testng-6.4/src/test/groovy/TestNGTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/DDTags.java

**Description**
- Set `CI` and `Git` tags in test spans related to `Jenkins`.
- Set `CI` and `Git` tags in test spans related to `GitLab Pipelines`.
The `datadog.trace.bootstrap.instrumentation.decorator.TestDecorator` class is modified to obtain the CI and Git information available in the environment variables for the following CI providers:
* `Jenkins`
* `GitLab Pipelines`

CI-App: Set CI and git tags in test spans

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java

They inject classes that we can't resolve that results in noisy logging.

Add `cinnamon.*` classes to global ignore.

---

dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java

Reported repeated failures to probe the `agent` endpoints because of too low connect timeout.

Make agent connect timeout less aggressive

---

.gitignore
.palantir/revapi.yml
dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/util/AbstractCouchbaseTest.groovy
dd-java-agent/instrumentation/jedis-1.4/src/test/groovy/JedisClientTest.groovy
dd-java-agent/instrumentation/jedis-3.0/src/test/groovy/Jedis30ClientTest.groovy
dd-java-agent/instrumentation/rediscala-1.8.0/src/test/groovy/RediscalaClientTest.groovy
dd-java-agent/instrumentation/spymemcached-2.12/src/test/groovy/datadog/trace/instrumentation/spymemcached/SpymemcachedTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/log/injection/LogContextInjectionTestBase.groovy
dd-java-agent/testing/src/test/groovy/context/FieldBackedProviderTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
internal-api/internal-api.gradle
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/CapturedEnvironmentConfigSource.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/EnvironmentConfigSource.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/PropertiesConfigSource.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/SystemPropertiesConfigSource.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/PropertiesConfigSourceTest.groovy

This changes some semantics of config a bit... for example the order of precedence between aliases and other sources.
The big benefit this has is removing the additional config constructor which was generally not used.
I think we could improve consistency between when we load config with the `dd.` prefix and when we don't.  I tried to maintain existing semantics when possible.

Config changes that may impact precedence order for overlapping config defined in multiple places.

---

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
dd-java-agent/agent-profiling/profiling-uploader/profiling-uploader.gradle
dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
gradle/dependencies.gradle

Needs #1827 to be merged first.
Manually verified that guava classes are now under `inst` in the jar
```
jar -tf dd-java-agent/build/libs/dd-java-agent-0.61.0-SNAPSHOT.jar| grep 'com.google.common'
inst/com/google/common/
inst/com/google/common/escape/
inst/com/google/common/escape/Escapers$1.classdata
inst/com/google/common/escape/CharEscaperBuilder$CharArrayDecorator.classdata
...
```
@DataDog/profiling look at the second commit if reviewing this before rebasing after #1827 is merged.

remove guava from profiling

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java

The configuration parameter to disable v0.5 traces introduced in #1762 was intended for integration testing purposes and the PR was incomplete when @tylerbenson both renamed the PR and _rewrote my PR description_ before merging it. This PR allows actually disabling the v0.5 endpoint by config (but this should be discouraged because v0.5 payloads are ~4x smaller).

make it possible to disable v0.5 endpoint

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy

Adds service, env, and version tags to health metrics

Tag health metrics with service, env, and version

---

dd-trace-core/src/main/java/datadog/trace/core/monitor/Monitor.java
dd-trace-core/src/test/groovy/datadog/trace/core/monitor/MonitorTest.groovy

The extra space lead to metrics being tagged with `status:_200` instead of `status:200` (spaces are converted into underscores)

Fix status tag on health metrics

---

dd-java-agent/testing/src/main/java/datadog/trace/agent/test/utils/ThreadUtils.java
dd-java-agent/testing/src/test/groovy/utils/ThreadUtilsTest.groovy

Broke out this little helper utility from my `play` test. Tried to build a `spock` extension at first but it seems undoable, since state is entangled everywhere and nothing is thread safe.

Add test utility to run test closure concurrently

---

dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/TagSettingAsyncListener.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/TagSettingAsyncListener.java
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TestServlet3.groovy
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

For scenarios where clients disconnect without explicitly closing connections it is useful to not treat timeouts as errors when recording spans.
The default behaviour remains the same (async request timeouts are treated as errors) but you can now set:
```
dd.trace.servlet.async-timeout.error=false
```
to not treat them as errors. These spans will still have the "timeout" tag set regardless of this setting.

Add option to not treat async request timeouts as errors

---

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/Prioritization.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/PrioritizationTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/PrioritizationConstants.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Added a new `PrioritizationStrategy` tries to offer the trace to the primary queue until the `queue.offer(...)` method returns true. This type can be configured via `Config`.
This new type is needed to avoid losing spans in CI/Tests traces. It should not be used in applications in production mode.

Add the EnsureTrace prioritization strategy.

---

dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Instrumentation.java
dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Utils.java

Avoid adding the TracingListener multiple times since JUnit4 4.12

Ci-App: Avoid adding the TracingListener multiple times since JUnit4 4.12

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java

This fixes a test issue where the embedded Tomcat tests wipe out the logging configuration when Tomcat is shut down, causing any following tests run in the same JVM to not have any logging output.
We now detect this by checking if the root logger has any appenders attached before running the test. If it doesn't then we restore the default logging configuration and set the expected log levels.
Before:
After:

Restore logging configuration if a previous test wipes it out

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java
utils/thread-utils/src/main/java/datadog/common/exec/CommonTaskExecutor.java

Subclass ScheduledThreadPoolExecutor to avoid CommonTaskExecutor from being instrumented as this can cause cycles/deadlocks with WeakMap which uses CommonTaskExecutor to schedule its cleanup task.
Simplest way to do this was for CommonTaskExecutor to subclass ScheduledThreadPoolExecutor directly instead of embedding it as a separate instance. This also meant some delegation methods could be removed as they're no longer needed.

Avoid instrumenting WeakMap cleanup executor

---

.palantir/revapi.yml
dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/PayloadDispatcher.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingWorker.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/Monitoring.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/NoOpRecording.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/Recording.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/ThreadLocalRecording.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/Timer.java
dd-trace-core/src/test/groovy/datadog/trace/core/monitor/TimingTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/OpenTracingAPITest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

Disables more intrusive performance metrics (and distinguishes between health metrics and performance metrics), allowing them to be enabled with a flag `-Ddd.trace.perf.metrics.enabled=true`.
The distinction between health and performance is broadly based on intrusiveness and overhead. E.g. timing calls to the agent a few times a second on a single thread is a "health metric". Timing potentially thousands of accesses to a lock from an unbounded number of threads is a "performance metric".
Also uses a StatsD gauge instead of a timer for reporting summary stats from histograms, which avoids aggregations being done in the metrics pipeline.

disable performance metrics by default

---

dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ControllerFactory.java
dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ControllerFactoryTest.java

Here are the new error messages:
on OpenJDK < 8u262:
```
[dd.trace 2020-09-11 17:04:37:832 +0000] [main] WARN com.datadog.profiling.agent.ProfilingAgent - Not enabling profiling; it requires 1.8.0_262+ OpenJDK builds from the following vendors: AdoptOpenJDK, Amazon Corretto, Azul Zulu, BellSoft Liberica
openjdk version "1.8.0_252"
```
on [OpenJDK Official docker images](https://hub.docker.com/_/openjdk?)  <= openjdk:8u262 (upstream):
```
[dd.trace 2020-09-11 17:06:08:486 +0000] [main] WARN com.datadog.profiling.agent.ProfilingAgent - Not enabling profiling; it requires 1.8.0_272+ OpenJDK builds (upstream)
openjdk version "1.8.0_262"
```

[PROF-1574] Update agent error message for 8u262

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/httpurlconnection/HeadersInjectAdapter.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/httpurlconnection/HttpUrlConnectionDecorator.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/httpurlconnection/HttpUrlState.java
dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/HttpUrlConnectionInstrumentation.java
dd-java-agent/instrumentation/http-url-connection/src/test/groovy/HttpUrlConnectionResponseCodeOnlyTest.groovy
dd-java-agent/instrumentation/http-url-connection/src/test/groovy/HttpUrlConnectionTest.groovy
dd-java-agent/instrumentation/http-url-connection/src/test/groovy/HttpUrlConnectionUseCachesFalseTest.groovy
dd-java-agent/instrumentation/http-url-connection/src/test/groovy/SpringRestTemplateTest.groovy
dd-java-agent/instrumentation/http-url-connection/src/test/groovy/UrlConnectionTest.groovy

Similar to #1311, these helper classes are always injected into the bootstrap.  Moves us closer to supporting Read only filesystems (#429) while also reducing what needs to be done at startup

Move HttpUrlConnection helpers to bootstrap

---

dd-trace-core/src/main/java/datadog/trace/core/monitor/HealthMetrics.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/monitor/HealthMetricsTest.groovy

Updates health metrics names to be more in line with other tracers.  See https://github.com/DataDog/dd-trace-py/blob/0dc08305ebc12cfbc64270c1a5aa3cab040f4b8a/ddtrace/internal/writer.py#L193

Change health metrics names to be more consistent with other tracers

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/AdditionalLibraryIgnoresMatcher.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/BeanFactoryInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/CustomBeanClassloaderTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/CustomClassloaderConfig.groovy

Bean Factories can be set with a "beanClassloader" that is different from the injected classloader. This leads to a ClassNotFoundException at runtime.
This instrumentation ensures class lookups for the `HandlerMappingResourceNameFilter` don't fail by manually setting the class on the bean definition.  This can't be done at `BeanDefinition` construction time because Spring heavy use of `clone()` which sometimes only copies the classname.

Handle custom bean classloader in Spring

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/LogContextScopeListener.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerDepthTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/OpenTracingAPITest.groovy

This fixes various problems with ScopeListener and ScopeManager
* `ScopeListener.afterScopeActivated()` was only called for new scopes and not previous scopes being activated (starting with 0.52.0)
* Scope depth was incorrectly tracked with out-of-order scope closing
* Traces with scopes meeting the following conditions were never reported:
- a) resulting from Continuation activations
- b) closed out of order
* `ScopeListener.afterScopeClosed()` wasn't called for Scopes closed out of order until the `ScopeStack` was modified again
* Some closed scopes were never GC'd until a call to `activeScope()` or similar (you could have an entire stack of closed scopes with the right `.close()` ordering)
* The internal array in scope stack was almost always resized to 0.  Leading to a lot of churn …

ScopeListener and ScopeManager fixes

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/CallableWrapper.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExecutorInstrumentationUtils.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/RunnableWrapper.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/State.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaExecutorInstrumentation.java

This makes some small improvements to executor instrumentations
* Avoids creating continuations twice (need to win the CAS to create the continuation)
* Efficiency improvements when checking whether we need to wrap runnables and callables
* Avoid attempting to propagate context unless there is an active scope
The first two are cherry picked from #1883, which I don't think we can make work without more ambitious rework.

small efficiencies in inter-thread context propagation

---

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/OpenTracingAPITest.groovy

Followup to #1889 :
* Replaced `Array` with `ArrayDeque` to simplify code
* continuation.cancel() could throw (via a TraceInterceptor) leaving the stack in a bad state
* Closing a multi-activated scope out of order with strict mode enabled could leave the stack in a bad state

More ContinuableScopeManager fixes

---

gradle/test-with-scala.gradle

This change caused the scala library to be a runtime dependency of instrumentation resulting in it being bundled with the `dd-java-agent` release.
Problem introduced in #1810.

Stop bundling scala with `dd-java-agent`

---

dd-java-agent/instrumentation/spring-scheduling-3.1/src/main/java/datadog/trace/instrumentation/springscheduling/SpannedMethodInvocation.java
dd-java-agent/instrumentation/spring-scheduling-3.1/src/main/java/datadog/trace/instrumentation/springscheduling/SpringAsyncAdvice.java

I hadn't really appreciated the continuation mechanism when I added this instrumentation. This is partly here as a sample of a way to do this without field injection.

use continuation in Spring Async instrumentation

---

dd-trace-ot/src/main/java/datadog/opentracing/DefaultLogHandler.java

The log messages in `DefaultLogHandler` print out "doing nothing" even when they do.  (Probably a c/p error on my part a while ago)

Span.log() messages incorrect

---

dd-trace-core/src/main/java/datadog/trace/common/sampling/RateByServiceSampler.java

This shows up a lot in profiles

avoid copying tags (potentially twice) when sampling each span

---

dd-trace-core/dd-trace-core.gradle

This dependency leaked into the `pom` for `dd-trace-ot` in the published `0.63.0` version. Thanks @mar-kolya for finding this.

Don't leak an internal dependency

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AbstractExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ScheduledExecutorServiceInstrumentation.java
dd-smoke-tests/springboot-grpc/springboot-grpc.gradle
dd-smoke-tests/springboot-grpc/src/main_java8/java/datadog/smoketest/springboot/SpringbootGrpcApplication.java
dd-smoke-tests/springboot-grpc/src/main_java8/java/datadog/smoketest/springboot/controller/WebController.java
dd-smoke-tests/springboot-grpc/src/main_java8/java/datadog/smoketest/springboot/spanner/SpannerTask.java
dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcAsyncAnnotationTest.groovy
dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcAsyncConcurrentTest.groovy
dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcAsyncTest.groovy
dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcCompletableFutureTest.groovy
dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcSpannerNoAsyncTest.groovy
dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcSpannerTest.groovy
dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcSyncTest.groovy
dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootWithGRPCTest.groovy

`ScheduledExecutorService` is currently double instrumented because we instrument both `schedule` and `submit`, and `submit` calls `schedule`. `ScheduledExecutorService` is used in Spanner.
We are forced to create continuations which we can't close without instrumenting spanner itself, so the integration tests are dependent on pending changes to `PendingTrace` to relax reference counting semantics, in order to be able to trace creation of a session without actually connecting to spanner (or tolerating failure at all, for that matter).

Add instrumentation for ScheduledExecutorService, dormant integration testing for spanner session creation dependent on PendingTrace changes

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java

When "false" we configure the log level at startup to WARN to hide agent info messages at startup.
This doesn't affect agent warning or error messages.
The startup logs setting also has no effect when debug mode (dd.trace.debug) is enabled.
NOTE: as it stands this PR does not change the log level after the agent has finished startup, ie. it will continue to hide agent info messages but still log warnings and errors. This was considered acceptable because users setting this option typically will be only interested in warnings and errors. It also avoids introducing additional custom logging API and logic to bump the log level back once startup is "done", where we may already be dealing with multiple agent threads.

Support 'dd.trace.startup.logs' system property and 'DD_TRACE_STARTUP_LOGS' environment variable

---

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

(another PR to align our agent configuration with other language tracers)
When "false" it overrides specific metrics settings, such as 'dd.jmxfetch.enabled', turning off all runtime metrics involving statsd.
When "true" (the default) the specific metrics settings take precedence, for example JMX metrics on and tracer health/perf metrics off.

Support 'dd.runtime.metrics.enabled' system property and 'DD_RUNTIME_METRICS_ENABLED' environment variable

---

dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
dd-trace-ot/src/test/groovy/datadog/opentracing/CustomScopeManagerTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/OpenTracingAPITest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScopeManager.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

This is a real issue where a customer is using OT in an async application and it breaks up the customers spans.

Enable OpenTracing to inherit the async propagation from enclosing scope

---

dd-java-agent/agent-tooling/agent-tooling.gradle
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakMapSuppliers.java
dd-java-agent/instrumentation/elasticsearch/elasticsearch.gradle
dd-java-agent/instrumentation/exception-profiling/exception-profiling.gradle
dd-java-agent/instrumentation/glassfish/glassfish.gradle
dd-java-agent/instrumentation/instrumentation.gradle
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java
dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAnnotationsInstrumentation.java
dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceConfigInstrumentation.java
dd-java-agent/testing/testing.gradle
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-core/dd-trace-core.gradle
dd-trace-core/src/main/java/datadog/trace/common/sampling/RuleBasedSampler.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
dd-trace-core/src/main/java/datadog/trace/core/util/SimpleRateLimiter.java
dd-trace-core/src/test/groovy/datadog/trace/core/util/SimpleRateLimiterTest.groovy
dd-trace-ot/dd-trace-ot.gradle
dd-trace-ot/src/main/java/datadog/opentracing/resolver/DDTracerResolver.java
gradle/dependencies.gradle
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/api/RatelimitedLogger.java
internal-api/src/main/java/datadog/trace/api/time/ControllableTimeSource.java
internal-api/src/main/java/datadog/trace/api/time/SystemTimeSource.java
internal-api/src/main/java/datadog/trace/api/time/TimeSource.java
internal-api/src/main/java/datadog/trace/api/utils/MathUtils.java
internal-api/src/test/groovy/datadog/trace/api/ControllableTimeSourceTest.groovy
internal-api/src/test/groovy/datadog/trace/api/RateLimitedLoggerTest.groovy
internal-api/src/test/groovy/datadog/trace/api/utils/MathUtilsTest.groovy

* Removes the inadvertent dependencies on Guava because of the lines:
```
annotationProcessor deps.autoservice
implementation deps.autoservice
```
* Removes unneeded uses of Guava
* Implements a simple rate limiter that doesn't have all of the features of the guava version (smoothing, acquiring multiple tokens, etc) but gets the job done
After this pull request, the uses of Guava are:
* GuavaWeakCache in agent-tooling
* DDCachingPoolStrategy in agent-tooling
* Instrumentations on Guava interfaces ( ListenableFuture, Ratpack, Twilio, datastax-cassandra-3)
* Tests (I left these untouched)

Cleanup dependency on Guava

---

internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

to match other language tracers, for example:
* `DD_<INTEGRATION>_ENABLED` --> `DD_TRACE_<INTEGRATION>_ENABLED`
* `DD_<INTEGRATION>_ANALYTICS_<OPTION>` --> `DD_TRACE_<INTEGRATION>_ANALYTICS_<OPTION>`
but still accept use of the old settings

Support 'DD_TRACE' prefix when configuring integrations

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
dd-java-agent/agent-profiling/profiling-controller/profiling-controller.gradle
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java
dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ProfilingSystemTest.java
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
dd-smoke-tests/wildfly/src/test/groovy/datadog/smoketest/JFRStackDepthTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/util/JmxSystemAccessProvider.java
dd-trace-core/src/main/java/datadog/trace/core/util/NoneSystemAccessProvider.java
dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccess.java
dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccessProvider.java
dd-trace-core/src/test/groovy/datadog/trace/core/util/SystemAccessTest.groovy

Change Overview
------------------
* sets JFR profiles to use a 256 stack depth by default
* respects user-supplied over-ride for max stack depth
* limits clients to a 1024 max stack depth
* jboss (wildfly) integration tests
Observations
------------------
Based on [benchmark results](https://docs.google.com/spreadsheets/d/1E0ZuxqwrLXIK0w0n6n6ZZ9ASZ029lToB04SWK7OAW_I/edit#gid=831612831) there is little overhead increasing the `stackdepth` and not truncating typical java web application stacks, which can be regularly greater than 128.
Due to quirks in JFR initialization ([one-shot per JVM, sampling thread started as a side-effect of setting the sampling interval](https://github.com/openjdk/jdk/blob/e0cf023263fcd8ad5c8235828e025c5842807bfe/src/hotspot/share/jfr/periodic/sampling/jfrThreadSam …

[PROF-1988] default stackdepth

---

dd-java-agent/dd-java-agent.gradle

Add a limit to the agent jar to prevent accidental inclusions like #1810 (fixed with #1900 )
Current jar size is ~14-15 MB.  The limit is 16MB

Add file size limit to agent jar

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/DBTypeProcessingDatabaseClientDecoratorTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecoratorTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/OrmClientDecoratorTest.groovy
dd-java-agent/instrumentation/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseClientDecorator.java
dd-java-agent/instrumentation/datastax-cassandra-3/src/main/java/datadog/trace/instrumentation/datastax/cassandra/CassandraClientDecorator.java
dd-java-agent/instrumentation/elasticsearch/src/main/java/datadog/trace/instrumentation/elasticsearch/ElasticsearchRestClientDecorator.java
dd-java-agent/instrumentation/elasticsearch/src/main/java/datadog/trace/instrumentation/elasticsearch/ElasticsearchTransportClientDecorator.java
dd-java-agent/instrumentation/hibernate/src/main/java/datadog/trace/instrumentation/hibernate/HibernateDecorator.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
dd-java-agent/instrumentation/jedis-1.4/src/main/java/datadog/trace/instrumentation/jedis/JedisClientDecorator.java
dd-java-agent/instrumentation/jedis-3.0/src/main/java/datadog/trace/instrumentation/jedis30/JedisClientDecorator.java
dd-java-agent/instrumentation/lettuce-4/src/main/java8/datadog/trace/instrumentation/lettuce4/LettuceClientDecorator.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/LettuceClientDecorator.java
dd-java-agent/instrumentation/mongo/driver-3.1/src/main/java/datadog/trace/instrumentation/mongo/MongoClientDecorator.java
dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/RediscalaClientDecorator.java
dd-java-agent/instrumentation/spymemcached-2.12/src/main/java/datadog/trace/instrumentation/spymemcached/MemcacheClientDecorator.java

Adds `peer.hostname` to database spans, specifically JDBC.
In other instances, where hostname was immediately available, I also added it.  Many of the decorators (eg `jedis`) are generic on the wrong type, or generic on `Object`.  These can be fixed in another pull request.

Add `peer.hostname` to database spans

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/TestDecorator.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/AppVeyorInfo.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/AzurePipelinesInfo.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/BitBucketInfo.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/BuildkiteInfo.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/CIProviderInfo.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/CircleCIInfo.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/GitLabInfo.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/GithubActionsInfo.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/JenkinsInfo.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/NoopCIInfo.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/TravisInfo.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/TestDecoratorTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/AppVeyorInfoTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/AzurePipelinesInfoTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/BitBucketInfoTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/BuildkiteInfoTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/CIProviderInfoTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/CircleCIInfoTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/GitLabInfoTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/GithubActionsInfoTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/JenkinsInfoTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/NoopCIInfoTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/TravisInfoTest.groovy
dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
dd-java-agent/instrumentation/testng-6.4/src/test/groovy/TestNGTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java

Added CI/Git information to test spans for the following CI providers:
* TravisCI
* CircleCI
* Azure Pipelines
* GitHub Actions
* Buildkite
* BitBucket
* AppVeyor

Added CI/Git information to test spans for CI providers

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java

Please, review this trivial change which is meant to remove a scary error log coming from the deadlock detection initialization when a user is trying to run on Java 7.

Silently disable deadlock detection for Java 7

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/AsyncContextInstrumentation.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy

Previously, when using dispatch, propagation information was passed from the dispatching servlet to the dispatched servlet through HTTP headers.  Using this mechanism, the new servlet span was a "top level" span creating 2 toplevel spans in the trace.  This treatment was incorrect as the new servlet request is just a continuation of the same local trace.
To change the behavior, I use `DD_DISPATCH_SPAN_ATTRIBUTE` to pass the span from the dispatching servlet to the dispatched servlet.
For the tests, things are simplified somewhat.  The dispatching servlet is the `serverSpan` and the dispatched servlet is the `handlerSpan`.
I'll create another pull request to make span sorting the default.  For this pull request, I made minimal additions to get these tests to pass.

Don't treat dispatch servlet spans as top level

---

dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinPoolInstrumentation.java
dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinTaskInstrumentation.java
dd-java-agent/instrumentation/akka-concurrent/src/test/groovy/ForkJoinPoolPropagationTest.groovy
dd-java-agent/instrumentation/akka-concurrent/src/test/java/LinearTask.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AbstractExecutorInstrumentation.java
dd-java-agent/instrumentation/scala-concurrent/src/main/java/datadog/trace/instrumentation/scala/concurrent/ScalaForkJoinPoolInstrumentation.java
dd-java-agent/instrumentation/scala-concurrent/src/main/java/datadog/trace/instrumentation/scala/concurrent/ScalaForkJoinTaskInstrumentation.java
dd-java-agent/instrumentation/scala-concurrent/src/test/groovy/ForkJoinPoolPropagationTest.groovy
dd-java-agent/instrumentation/scala-concurrent/src/test/java/LinearTask.java

Our tests for FJP context propagation only ever test the case where the work gets stolen by the pushing thread, i.e. whenever tasks were invoked on another thread, context would fail to propagate. 
This fixes this by instrumenting `ForkJoinTask`'s lifecycle, and instrumenting `ForkJoinPool.externalPush`, and not attempting to handle FJPs with executor instrumentation.
This PR currently breaks a `CompletableFuture` test (`thenComposeAsyc`) but I expect this should be fixed by correct CF instrumentation.

fix akka/scala FJP internal push context propagation

---

.circleci/config.yml
CONTRIBUTING.md
dd-trace-java.gradle
gradle/java.gradle
gradle/publish.gradle
gradle/scm.gradle
gradle/spotless.gradle
gradle/util.gradle
gradle/version.gradle
test-published-dependencies/.gitignore
test-published-dependencies/build.gradle
test-published-dependencies/settings.gradle
test-published-dependencies/src/main/java/test/published/dependencies/App.java

Has been tested to fail when the leaking internal dependency change fixed in #1911 was added back.

Test published dependencies

---

dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy

This change ensures that we write out a trace as soon as its reference count reaches zero.

Write out a trace as soon as possible

---

dd-java-agent/instrumentation/scala-promise-2.10/src/main/java/datadog/trace/instrumentation/scala/promise/CallbackRunnableInstrumentation.java
dd-java-agent/instrumentation/scala-promise-2.10/src/test/groovy/Scala210PromiseTest.groovy
dd-java-agent/instrumentation/scala-promise-2.13/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseTransformationInstrumentation.java
dd-java-agent/instrumentation/scala-promise-2.13/src/test/groovy/Scala213PromiseTest.groovy

* Doesn't depend on `Runnable` being instrumented
* Doesn't pick up completing scope

specialised instrumentation for scala promises

---

dd-trace-core/src/main/java/datadog/trace/core/monitor/CPUTimer.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/Monitoring.java
dd-trace-core/src/main/java/datadog/trace/core/util/JmxSystemAccessProvider.java
dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccess.java
dd-trace-core/src/test/groovy/datadog/trace/core/monitor/TimingTest.groovy

This is the same access class used by the profiler's `ScopeEvent` to avoid premature loading/initialisation of JMX beans.

Use SystemAccess to query JMX in health metrics

---

dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingWorker.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java

We might stuck in busy loop in ShutdownHook when primary queue is full and we keep trying to insert into it. But "dd-trace-processor" was already interrupted and stopped and nobody is draining from that full primaryQueue anymore:
`"dd-tracer-shutdown-hook" #8 prio=5 os_prio=0 tid=0x00007fb591de0000 nid=0x59b8 runnable [0x00007fb5b43bf000]
java.lang.Thread.State: RUNNABLE
at datadog.trace.agent.common.writer.ddagent.TraceProcessingWorker.flush(TraceProcessingWorker.java:90)
at datadog.trace.agent.common.writer.DDAgentWriter.flush(DDAgentWriter.java:154)
at datadog.trace.agent.common.writer.DDAgentWriter.close(DDAgentWriter.java:181)
at datadog.trace.agent.core.CoreTracer.close(CoreTracer.java:493)
at datadog.trace.agent.core.CoreTracer$ShutdownHook.run(CoreTracer.java:882)`

Prevent trace flush from preventing shutdown

---

dd-smoke-tests/play-2.5/app/controllers/HomeController.java
dd-smoke-tests/play-2.5/play-2.5.gradle
dd-smoke-tests/play-2.5/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
dd-trace-core/src/main/java/datadog/trace/common/writer/MultiWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/MultiWriterTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/WriterConstants.java

* Adds some client calls to the `play-2.5` smoke test.
* Moves `Writer` creation out to a separate class, and adds a `MultiWriter` that delegates to multiple other writers.
* Allows `AbstractSmokeTest` to wait for a received trace count.

Add a play client request to the play 2.5 smoke test

---

dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinTaskInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java
dd-java-agent/instrumentation/scala-concurrent/src/latestDepTest/groovy/ScalaInstrumentationTest.groovy
dd-java-agent/instrumentation/scala-promise-2.10/src/main/java/datadog/trace/instrumentation/scala/promise/CallbackRunnableInstrumentation.java
dd-java-agent/instrumentation/scala-promise-2.13/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseTransformationInstrumentation.java

I can't wait until async propagation is the default behavior. I completely missed this during review.

Set missing async propagation on some java/scala/akka scopes

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/src/test/groovy/datadog/trace/agent/CustomMBeanServerBuilderTest.groovy
dd-java-agent/src/test/java/jvmbootstraptest/CustomMBeanServerBuilder.java
dd-java-agent/src/test/java/jvmbootstraptest/MBeanServerBuilderSetter.java

This takes a similar approach to how we deal with custom log managers, however unlike the logging case there is no clear activating class with a static initialization block. Instead we wait for the `MBeanServerBuilder` class to be loaded and use that as an indication that we can go ahead and access JMX.
This is acceptable because `MBeanServerBuilder` is the base class for all custom JMX builders and is only used in `MBeanServerFactory` which creates the custom builder instance. Note JMX doesn't let you supply an actual builder instance - it only lets you specify the class name which `MBeanServerFactory` attempts to load, first by the current thread's context classloader, then falling back to `Class.forName`.
The place where `MBeanServerBuilder` is loaded should be where …

Delay starting JMXFetch when there's a custom JMX builder

---

dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java

this skips creation of some additional background threads which we don't need because we already run JMXFetch on its own background thread:
https://github.com/DataDog/jmxfetch/blob/0.39.0/src/main/java/org/datadog/jmxfetch/AppConfig.java#L233
https://github.com/DataDog/jmxfetch/blob/0.39.0/src/main/java/org/datadog/jmxfetch/App.java#L97

Enable embedded mode for JMXFetch

---

dd-java-agent/instrumentation/dropwizard/src/test/groovy/DropwizardTest.groovy
dd-java-agent/instrumentation/finatra-2.9/src/latestDepTest/groovy/FinatraServer270Test.groovy
dd-java-agent/instrumentation/finatra-2.9/src/test/groovy/FinatraServerTest.groovy
dd-java-agent/instrumentation/play-2.3/src/test/groovy/server/PlayServerTest.groovy
dd-java-agent/instrumentation/play-2.4/src/test/groovy/server/PlayServerTest.groovy
dd-java-agent/instrumentation/play-2.6/src/test/groovy/server/PlayServerTest.groovy
dd-java-agent/instrumentation/ratpack-1.5/src/test/groovy/server/RatpackHttpServerTest.groovy
dd-java-agent/instrumentation/servlet/request-3/request-3.gradle
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServletHandlerTest.groovy
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TestServlet3.groovy
dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/RequestDispatcherDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/dispatcher/RequestDispatcherInstrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseInstrumentation.java
dd-java-agent/instrumentation/servlet/src/test/groovy/RequestDispatcherTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerAdapterInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/SpringWebHttpServerDecorator.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/AppConfig.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/CustomBeanClassloaderTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SpringBootBasedTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/dynamic/DynamicRoutingTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/filter/ServletFilterTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/SpanAssert.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TraceAssert.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy

This started as a fix to the RequestDispatcher commented out tests and ended up as much more.  Lots of changes so I'm being extra detailed with this description
* `RequestDispatcher` did not set the `HTTP_STATUS` tag (this required reflection because its only available in servlet 3)
* `RequestDispatcher` did not properly set 404 resource name when forwarding
* `RequestDispatcher` did not set 500 status when exception was thrown
* Synchronous `RequestDispatcher` did not set `servlet.dispatch` tag (only async dispatch did)
* `Spring-mvc` instrumentation did not set 404 resource name for 404 response status
* Newer versions of Jetty create multiple response spans on redirect
**Added `childOfPrevious()` to `SpanAssert`**
This simplifies span assertion declarations and allow for conditional …

Servlet RequestDispatcher and Spring MVC 404 fixes

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableFutureInstrumentation.java

I just noticed FutureTask context was backed by a weak map... It would be great to have a testing strategy for this.

Make sure FutureTask gets field injected

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RejectedExecutionHandlerInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/RejectedExecutionTest.groovy

Another issue came up trying to integrate `RunnableFuture` instrumentation while we still have `Runnable` instrumentation. I think this is the cause of the last 4 flaky executor tests.

don't double instrument RunnableFutures

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExcludeFilterProvider.java
dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinTaskInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/main/java/datadog/trace/instrumentation/java/completablefuture/CompletableFutureUniCompletionInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java
dd-java-agent/instrumentation/scala-promise-2.10/src/main/java/datadog/trace/instrumentation/scala/promise/CallbackRunnableInstrumentation.java
dd-java-agent/instrumentation/scala-promise-2.13/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseTransformationInstrumentation.java
dd-java-agent/testing/src/test/java/excludefilter/ExcludeFilterProviderTestInstrumentation.java

This method deciding if an `ExcludeFilterProvider` is enabled, doesn't serve any purpose anymore since there is no _default_ behavior to fall back to for a number of the instrumentations that use this.

Remove unnecessary and confusing isEnabled method on ExcludeFilterProvider

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RejectedExecutionHandlerInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/RejectedExecutionTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/test/java/ExecutingRejectedExecutionHandler.java

Ensuring Guava rejected tasks have their continuations closed reliably requires changing the way we instrument `Executor.execute` so this can be handled later on.

RejectedExecutionHandlerInstrumentation tests and fixes

---

dd-java-agent/instrumentation/opentelemetry/src/main/java/datadog/trace/instrumentation/opentelemetry/OtelSpan.java
dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTSpan.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTSpan.java
dd-trace-api/src/main/java/datadog/trace/api/interceptor/MutableSpan.java
dd-trace-core/src/main/java/datadog/trace/common/writer/DDSpanJsonAdapter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_5.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpanData.java
dd-trace-ot/src/main/java/datadog/opentracing/OTSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

This PR adds an accessor to the `span.metrics` through the `MutableSpan` interface.

Add setters to span.metrics from MutableSpan

---

dd-smoke-tests/opentracing/src/main/java/datadog/smoketest/opentracing/IncorrectSetupWithAgentApplication.java
dd-smoke-tests/opentracing/src/test/groovy/datadog/smoketest/IncorrectSetupWithAgentTest.groovy
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java

Historically, we would allow the creation of `DDTracer` even when the java agent was installed.  The failure to register was noted in the logs and the application continued normally.
Recently, creating `DDTracer` when the agent was installed causes `java.lang.NoSuchMethodError` because of class renaming.
In both cases, the newly created `DDTracer` can't be used.  This pull request changes the behavior to _fail fast_ by throwing an exception immediately.

Fail-fast manual tracer creation in presence of java agent

---

dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTSpan.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTSpan.java

It's not possible to check equality of opentracing32.OTSpan intances because it doesn't implement the equals and hashCode methods for the internal agent span. Also the opentracing32.OTSpan class is not part of public API and the getDelegate method is not assessible via the Span or MutableSpan inteface.
At the same time datadog.opentracing.OTSpan has proper implementations of the equals and hashCode methods.

Add missing equals and hashCode method into datadog.trace.instrumentation.opentracing32.OTSpan

---

internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/GitLabInfo.java
internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/GitLabInfoTest.groovy

This PR removes the `/-/` fragment in the GitLab Pipeline URL for tests to be aligned with the GitLab instrumentation (cc @AdrianLC )

Ci-App: Remove /-/ in Gitlab Pipeline URL for tests

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExcludeFilter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExcludeFilterProvider.java
dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinTaskInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/main/java/datadog/trace/instrumentation/java/completablefuture/CompletableFutureUniCompletionInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableFutureInstrumentation.java
dd-java-agent/instrumentation/scala-promise-2.10/src/main/java/datadog/trace/instrumentation/scala/promise/CallbackRunnableInstrumentation.java
dd-java-agent/instrumentation/scala-promise-2.13/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseTransformationInstrumentation.java
dd-java-agent/testing/src/test/java/excludefilter/ExcludeFilterProviderTestInstrumentation.java
dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy

This reduces the overhead of injected fields by manually excludes as many instrumentable `RunnableFuture`s as possible to prevent `RunnableInstrumentation` from injecting these types. These changes reduces field injection footprint from `2 * depth * width` to `depth * width` in most cases.

Reduce field injection footprint

---

internal-api/src/main/java/datadog/trace/util/DaemonThreadFactory.java

as suggested by @tylerbenson in https://github.com/DataDog/dd-trace-java/pull/1998#discussion_r507799700

Rename agent thread group to 'dd-trace-java'

---

dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ControllerFactory.java
dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ControllerFactoryTest.java

8u272 includes JFR and will be generally available October 20, 2020
From https://wiki.openjdk.java.net/display/jdk8u/Main
> Tuesday, October 20th 2020: GA; OpenJDK 8u272 released
[PROF-2013]
[PROF-2013]: https://datadoghq.atlassian.net/browse/PROF-2013

[PROF-2013] Update agent error message for 8u272

---

internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

This is the standard in the agent and we have integrations e.g. Heroku providing space-separated config to us, which we reject.

permit space-separated tags in config

---

dd-java-agent/instrumentation/grpc-1.5/grpc-1.5.gradle

We can still register an interceptor via `io.grpc.netty.NettyServerBuilder`'s delegate `io.grpc.internal.ServerImplBuilder`, but the interceptor is not called, which seems like a bug. It's easiest for now to cap the version and revisit this.

cap existing gRPC instrumentation at 1.32.2

---

dd-java-agent/instrumentation/play-2.3/src/main/java8/datadog/trace/instrumentation/play23/PlayAdvice.java
dd-java-agent/instrumentation/play-2.4/src/main/java8/datadog/trace/instrumentation/play24/PlayAdvice.java
dd-java-agent/instrumentation/play-2.6/src/main/java8/datadog/trace/instrumentation/play26/PlayAdvice.java

Not sure that this will ever happen in a real world setting, but it logs exceptions while running the `play` test suite with agent debug logging enabled.

Update Play root span only if there is one

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AbstractExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/NewTaskFor.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/WrapRunnableAsNewTaskInstrumentation.java

This will work for any subclass of `AbstractExecutorService` and makes the `RunnableInstrumentation` otherwise unnecessary once Kotlin coroutines are moved out of this module.

pass executed Runnables through AbstractExecutorService.newTaskFor to get free context propagation

---

dd-java-agent/instrumentation/exception-profiling/src/main/java11/com/datadog/profiling/exceptions/ExceptionSampleEvent.java

Apparently, there are exception types out there which will fail a call to `getMessage()` with throwing NPE 🤷 
Just to clarify - the problems are expected for exception types overriding `getMessage()` method and trying to access an additional information from the subclass. This is because the instrumentation is injected at exit point in `Throwable.<init>` and the rest of the subclassed instance may not be initialized at that moment. Unfortunately, there is no way to overcome this so the best thing we can do is to ignore the exception and pretend there is no message.

Be defensive about misbehaving exception types

---

.circleci/config.yml
.gitignore
dd-smoke-tests/play-2.7/application/build.sbt
dd-smoke-tests/play-2.7/play-2.7.gradle
dd-smoke-tests/play-2.8/application/build.sbt
dd-smoke-tests/play-2.8/play-2.8.gradle
settings.gradle

Our CircleCI build always build every commit to a PR completely from scratch and without any cached artifacts. This PR tries to fix that, by saving caches under two different keys, one used by the dependent steps, and one that acts as a _base_ for future commits to the PR. As a fallback, we also try to use a cache from the main branch, that is updated daily.

Update CircleCI caching

---

dd-smoke-tests/play-2.4/play-2.4.gradle
dd-smoke-tests/play-2.5/play-2.5.gradle
dd-smoke-tests/play-2.6/play-2.6.gradle

This `stage` the gradle based Play smoke tests during compilation (i.e. the `build` step on CircleCI), to avoid compiling and staging the Play application on every `test_X` step.

Stage gradle based Play smoke tests during compilation

---

dd-smoke-tests/opentracing/src/main/java/datadog/smoketest/opentracing/CorrectSetupWithAgentAndWriterApplication.java
dd-smoke-tests/opentracing/src/test/groovy/datadog/smoketest/CorrectSetupWithAgentAndWriterTest.groovy
dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java

After #1994, it's not possible to use the `DDTracer` with the `ListWriter` for tests and using the `dd-java-agent` in the test phase to report tests using the `JUnit4` instrumentation.
This `PR` modifies the logic to fail-fast only when the writer is `null` or `DDAgentWriter`.

Fail-fast on DDTracer.build when writer is null or DDAgentWriter

---

gradle/dependencies.gradle

The current version of test containers doesn't work with the latest version of Docker on Macs: https://github.com/testcontainers/testcontainers-java/issues/3166 .  I was waiting for the final release of 1.15.0, but it's been "coming soon" for a while now.

Update test containers version

---

dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingWorker.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/TraceProcessingWorkerTest.groovy

The idea here is to create a point in `CoreTracer` after all interceptors and rules have run where the contents of the the traces can't change. This will allow metrics to be computed against an immutable aggregation key. This also affects sampling decisions meaning transformations are applied before sampling which may depend on span attributes

move TraceProcessor to CoreTracer

---

dd-java-agent/instrumentation/spring-data-1.8/spring-data-1.8.gradle

`:dd-java-agent:instrumentation:spring-data-1.8:latestDepTest` Tests with `2.4.0` fails with the following exception:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in spring.jpa.JpaPersistenceConfig: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/hibernate/resource/jdbc/spi/PhysicalConnectionHandlingMode
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(Abstr …
```

Pin Spring Data's latest test

---

dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/TracingClientInterceptor.java
dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java

Default was recently flipped from false to true so if these comments are accurate then we should explicitly set it false here

Explicitly disable async propagation in GRPC client/server interceptors as per comments

---

dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatHelper.java
dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatSettings.java
dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/simplelogger/SLCompatHelperTest.groovy

To avoid receiving the stack trace over multiple lines and send receive it as a single message I have added an option (`embedException`, which defaults to false for backward compatibility).
The format in case this feature is enabled looks like
```
<usual logline> <message> [exception:<exception type>: <message> <stack frame>, <stack frame>, ..]
```
where the content of the exception tag can be pasted in IntelliJ stack analyzer too.

Added configuration to embed exception in message instead of using printStackTrace

---

dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java
dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ProfilingSystemTest.java
dd-trace-core/src/main/java/datadog/trace/core/util/JmxSystemAccessProvider.java

* stop logging scary errors when we can't run diagnostic commands; we make a best-effort attempt to set the stack depth and shouldn't log a scary warning and exception when we can't
* remove confusing log line by not explicitly setting the max stack depth when a user has already specified a valid value

better logging on JFR max depth setting

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
dd-java-agent/testing/src/test/groovy/context/FieldBackedProviderTest.groovy
dd-java-agent/testing/src/test/java/context/ContextTestInstrumentation.java

These classes may implicitly generate a serialVersionUID based on the modified class structure which would be different if we modified the class, making the serialization incompatible.

`FieldBackedProvider` should avoid modifying `Serializable` classes without `serialVersionUID`

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java
dd-trace-core/src/main/java/datadog/trace/core/processor/rule/URLAsResourceNameRule.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/UTF8BytesString.java
internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/Utf8ByteStringTest.groovy

This removes some well meaning but bad choices
* Gets rid of the constants in `UTF8BytesString` which actually put the array copies onto a slow path
* Gets rid of the `ThreadLocal<StringBuilder>` in `InternalJarURLHandler` - it was `ThreadLocal` based on the assumption that loads mostly came from very few threads but this isn't the case
* Gets rid of the `ThreadLocal<StringBuilder>` in `URLAsResourceNameRule` now we can't control which thread it runs on.

remove counterproductive optimisations

---

dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogHttpCodec.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/HaystackHttpCodec.java

This avoids spamming the logs when certain headers are blanked out during replay
If we want to keep some conditions logged as errors then let me know and I'll adjust the PR accordingly

Log context extraction exceptions at debug in codec classes

---

dd-java-agent/instrumentation/mongo/driver-4/driver-4.gradle

the legacy client API from 3.x continues to be shipped in 4.x, while the 4.x instrumentation is backwards compatible with early versions of the new client API that first appeared in 3.7: https://github.com/DataDog/dd-trace-java/pull/2043#discussion_r515260667

Add comment explaining the overlap situation involving Mongo 3.x and 4.x

---

dd-trace-core/src/main/java/datadog/trace/common/sampling/RateByServiceSampler.java
dd-trace-core/src/test/groovy/datadog/trace/common/sampling/RateByServiceSamplerTest.groovy

The idea here is that it's much cheaper to construct a small wrapper for lookups than to create a new string, because it allocates less memory, doesn't need to do the array copies, and doesn't invalidate the cached hash code. This comes at the cost of needing to parse the responses from the agent. Also treats the default rate specially, instead of needing to lookup in the map twice.

Reduce cost of rate lookup in RateByServiceSampler

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/NoOpMetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/AbstractSampler.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/AllSampler.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/DeterministicSampler.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/ForcePrioritySampler.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/PrioritySampler.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/RateByServiceSampler.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/RateSampler.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/RuleBasedSampler.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/Sampler.java
dd-trace-core/src/main/java/datadog/trace/common/sampling/SamplingRule.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/PayloadDispatcher.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapper.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_4.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_5.java
dd-trace-core/src/main/java/datadog/trace/core/CoreSpan.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SimpleSpan.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/sampling/AllSamplerTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceGenerator.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperRealAgentTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV04PayloadTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV05PayloadTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy

There are two motivations here
* I want to be able to write performance tests for isolated components without constructing `CoreTracer` or `PendingTrace`. The coupling of processing with `CoreTracer` via `DDSpan` is why I haven't written a suite of performance tests for processing.
* We want to be able to move to typed tracers and spans for efficiency. An F-bounded generic interface is the best way to do that.

typed spans

---

dd-java-agent/instrumentation/aerospike-4/src/test/groovy/datadog/trace/instrumentation/aerospike4/AerospikeBaseTest.groovy

... just in case the aerospike container takes longer to start than the client tests

Wait for aerospike container to start on CI

---

dd-java-agent/instrumentation/commons-httpclient-2/commons-httpclient-2.gradle

For some reason an old pre-release of `commons-httpclient`, `20020423`, is now appearing as the latest version. This pre-release didn't contain classes that were in the 2.0 release. This PR excludes this specific version from the accepted muzzle range as well as avoiding picking it up for the `latestDepTest`. ~The most reasonable solution for the last case was to use `3+` for the latest dependency version, since we know that `commons-httpclient` has 3.x releases and that the 4.x releases use a different group/artifact and are handled by a different instrumentation.~ Björn provided a better range for the latest dep test.

Exclude ancient 20020423 pre-release from commons-httpclient-2 latest version

---

dd-java-agent/instrumentation/commons-httpclient-2/commons-httpclient-2.gradle
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java

There was a small chance that the `completedSpanCount ` got below `0` if new spans were added while a write was in progress, and a new write happened directly after, before the `completedSpanCount` had been incremented properly.
Fixes #2076

Fix small diff between span deque and span count

---

gradle/java.gradle

Doesn't fix the issue, but fixes the logging around the issue. Something about this repo config causes an error when requesting a non-snapshot file from it

JMC snapshot repo for snapshots only

---

dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Instrumentation.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseInstrumentation.java

The context stores in the servlet instrumentations only serve the purpose of being certain that the response object is the one previously associated with the instrumented request, but this association is costly in memory, and when the association falls back to a weak map, it will not be cleared deterministically leading to unbounded memory consumption. 
It doesn't seem to be possible to entirely remove this context store, but setting a boolean value mitigates the impact when field injection fails.

Change context store to use Boolean values in servlet instrumentations

---

dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/ServletContextTagInterceptor.java
dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/CapturedEnvironmentConfigSource.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/SystemPropertiesConfigSource.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

The check in `ServletContextTagInterceptor` was insufficient.  If a user's service name matched the `CapturedEnvironment` service name (eg, by matching filename of the executable jar), the tracer overrode the user provided service name with the servlet context.
With this pull request, whether or not the service name was explicitly set by the user is tracked in config.  That flag is checked inside the tag interceptor.
The tracer still has incorrect behavior if the service name is set via tag.  Too many pervasive changes would be required to track the setting of the service tag everywhere and distinguish instrumentation calls versus user calls.  Setting the service name to the jar name (or `unnamed-java-app`) as a tag seems too rare to warrant those changes.

Don't override user-provided service name with servlet.context

---

internal-api/src/main/java/datadog/trace/util/AgentTaskScheduler.java
internal-api/src/test/groovy/datadog/trace/util/AgentTaskSchedulerTest.groovy

so we can pass it to Caffeine to use for background clean-up

Support using AgentTaskScheduler as a simple Executor

---

dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/ServletContextTagInterceptor.java

I noticed reviewing #2099 that there are numerous inefficiencies in this logic, including looking up a constant in a hashmap every time we set the tag, checking that the string is non-empty last, and (implicitly) checking twice that the string is equal to "/"

make servletcontexttaginterceptor more efficient

---

dd-trace-ot/dd-trace-ot.gradle

This avoids an issue where a project dependency is listed as a transitive dependency. In some situations, such as when running a task from a sub-directory instead of the root project, this transitive dependency may not be resolved yet and has a name of 'unspecified'. Adding it to the 'dd-trace-ot' model leads to a gradle error:
```
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
> Could not find :unspecified:.
Required by:
project : > com.datadoghq:dd-trace-ot:0.69.0-SNAPSHOT
```
Since we're bundling project dependencies we can safely exclude them from the dependencies to add to the pom.

Only consider external dependencies when deciding transitive dependencies to list in the 'dd-trace-ot' pom.

---

dd-java-agent/agent-tooling/agent-tooling.gradle

Reduces the number of classes we bundle from 9180 to 8751, reduces dd-java-agent size from 13.4MB to 13.2MB

exclude errorprone and checker-qual

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ContextStoreImplementationTemplate.java

When the `WeakMap` fallback is used, something has gone wrong anyway, and with this change we will degrade to incomplete instrumentation rather than unbounded memory usage.

add limit to WeakMap size in ContextStoreImplementationTemplate

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVisitor.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/Reference.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java

Inspired by OTel PR [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1770) (but the implementations have diverged somewhat). Also some cleanup of our usage of the Collections API in related places.

make reference creation deterministic plus Collections API usage cleanup

---

dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/WeakMapTest.groovy
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakMapSuppliers.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/WeakConcurrentSupplierTest.groovy

because some instrumentations put `null`s into their context-store and this matches field-inject behaviour
(noticed while running instrumentation tests with field-injection turned off)

Support putting null contexts when falling back to weak-map

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ContextStoreUtils.java

We apparently spend roughly 1% of time in `Pattern.compile` during a startup benchmark which loads 1000 classes, and this accounts for nearly 4% of time in actually transforming classes. The `replaceAll` in `getInternalName` isn't actually required at all. `convertToInnerClassName` shows up in several other places during startup and should have been doing `char` replacements. The nearby `getClassName` is only used during the build but similar changes were made.

remove unnecessary String.replaceAll

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/AggregateMetric.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy
utils/histograms/histograms.gradle
utils/histograms/src/main/java/datadog/trace/core/histogram/DDSketchHistogram.java
utils/histograms/src/main/java/datadog/trace/core/histogram/Histogram.java
utils/histograms/src/main/java/datadog/trace/core/histogram/StubHistogram.java

This makes a few changes
* Add a random delay to starting metrics, to stop applications starting at the same time synchronising. 
* Update the DDSketch library, which now has a more memory efficient storage implementation, and a method to clear sketches, so they don't need to be reallocated
* Reduce the relative accuracy of the sketch - we are recording latencies accurate to at best microseconds in nanosecond units

Delay starting metric aggregation, reduce DDSketch relative accuracy, pick up changes from sketches-java 0.5.0

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java

The current code checks a set to see if the context-store transformation for the classloader matcher has already been installed - but nothing updates this set, so it always applies the transformation.
The set update seems to have disappeared in https://github.com/DataDog/dd-trace-java/commit/ee4fecdad13216d480ecc6720c5eca7c488c636e#diff-63ba657f2e3bf6fda57f5e108775a3aa4d8171f14b735e786da4b41d4bbe663cL428
I assume this was an oversight so this PR puts that update back and combines it with the duplicate check.

Restore check to avoid repeatedly adding the same context-store transformer

---

dd-trace-core/dd-trace-core.gradle

There are some counters in this version which are especially efficient when there are multiple threads performing updates

bump JCTools version

---

dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/GlobalLogLevelSwitcherTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy

Before the fix in #2086, this test fails reliably if I add a sleep between these two lines in `PendingTrace`:
```
finishedSpans.addFirst(span);
completedSpanCount.incrementAndGet();
```

Add concurrency test for PendingTrace

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldInjectionVisitor.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/asm/SerialVersionUIDAdder.java
dd-java-agent/testing/src/test/groovy/context/FieldBackedProviderTest.groovy
dd-java-agent/testing/src/test/java/context/ContextTestInstrumentation.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

The generated serialVersionUID is based on the class shape before field-injection.
Some performance numbers of the additional cost of generating missing serialVersionUIDs, all values in milliseconds:
| Min.  | 1st Qu. | Median | Mean | 3rd Qu. | Max. |
|------|--------|---------|-------|--------|------|
| 0.001167 | 0.022716 | 0.037376 | 0.065079 | 0.060000 | 5.454832 |
(captured by accumulating elapsed `System.nanoTime()` around the additional work for each serializable class)
This cost happens once per field-injected class.
This PR leaves the new feature off by default, but we could consider changing the default if this cost is acceptable.

Automatically inject missing serialVersionUIDs when field-injecting Serializables

---

dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/LoggingWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/PrintingWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/Payload.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/PayloadDispatcher.java
dd-trace-core/src/main/java/datadog/trace/core/CoreSpan.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/HealthMetrics.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SimpleSpan.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentApiTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/PayloadDispatcherTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceGenerator.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperRealAgentTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/monitor/HealthMetricsTest.groovy
dd-trace-core/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy

We go to great lengths to track the number of traces dropped in order to maintain a "representative count" which we send to the trace agent as an HTTP header... where it apparently serves no purpose! This PR removes this and results in simpler code, and we lose an atomic. We report dropped traces via statsd anyway.
/cc @gbbr

remove representative count tracking

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ContextStoreReadsRewritingVisitor.java

The partial JVM simulation made this code more complex than it needed to be for the purposes of checking the last two constants loaded before the method invocation. Also replaced use of reflected method information with constants - this avoids repeated string transformations while still catching the necessary rewriting.

Simplify context store read check

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/AggregateMetric.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/Batch.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AggregateMetricTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy

ignore trailing zeros in a batch. The fact I noticed this calls into question whether the conflation mechanism is effective.

Fix metrics aggregation

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
dd-java-agent/instrumentation/google-http-client/src/main/java/datadog/trace/instrumentation/googlehttpclient/GoogleHttpClientDecorator.java

I found these two uses of inefficient `String` API methods in contexts where we should probably remove them (one in reference creation during the build, the other once per span in the Google HTTP client instrumentation).

improve string handling

---

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java

The event being logged here *should* happen, unless something has gone wrong.

remove excessive debug logging in ContinuableScopeManager

---

dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy

I believe this test fails because it is slow, and removing the backoff logic seems to speed the test up by around 70x. I will build this PR repeatedly and verify that I don't see this:
```
test default buffer size for v0.3/traces - datadog.trace.common.writer.DDAgentWriterCombinedTest
Too many invocations for:
0 * _   (1 invocation)
Matching invocations (ordered by last occurrence):
1 * api.sendSerializedTraces(<datadog.trace.common.writer.ddagent.TraceMapperV0_4$PayloadV0_4@1a63cfba traceCount=32670 body=java.nio.HeapByteBuffer[pos=0 lim=5194533 cap=5194533]>)   <-- this triggered the error
at org.spockframework.mock.runtime.MockInteraction.accept(MockInteraction.java:70)
at org.spockframework.mock.runtime.MockInteractionDecorator.accept(MockInteractionDecorator.java:50)
at …
```

remove busyspin backoff logic in flaky DDAgentWriterCombinedTest

---

buildSrc/src/main/groovy/MuzzlePlugin.groovy
buildSrc/src/main/groovy/VersionSet.groovy
buildSrc/src/test/groovy/VersionSetTest.groovy

This changes how we select versions to test in the muzzle step, to select  the low and high version in every `major.minor` range, and then limiting that to the max allowed number of versions by randomizing. This leads to a reduction  from `3982` muzzle tasks to `2289` since a lot of libraries have large `micro` ranges.

Select low and high version in every range for Muzzle

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseInstrumentation.java
dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletResponseTest.groovy

Up to and including 0.68.0, the servlet instrumentation associates `HttpServletResponse` with `HttpServletRequest` objects via field injection, so that it can be determined whether a response is the response associated with the incoming request or a wrapper. When field injection works, this is fine, but if it doesn't, a `WeakMap<HttpServletResponse, HttpServletRequest>` is populated, and isn't cleared out until GC events trigger reference processing, and if there are hard references to the `HttpServletResponse`, the map cannot be cleared out and will only grow, which results in a memory leak. 
Since 0.69.0, this has been mitigated in several ways:
* by reducing the size of what's stored in the map - we actually only need a boolean token, and not the much larger `HttpServletRequest` object …

remove entry from context store in servlet instrumentation

---

dd-trace-core/src/main/java/datadog/trace/core/monitor/Timer.java

allows to track continuously new max, p99

clear timer histogram counts on flush

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
dd-java-agent/testing/src/test/groovy/muzzle/ReferenceCreatorTest.groovy
dd-java-agent/testing/src/test/java/muzzle/TestClasses.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java

This will allow muzzle to fail if an implemented interface is missing.  Additional work should be done in the future to ensure the implementation satisfies the interfaces and abstract types. (https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1357)

Add Muzzle reference creation for interfaces

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecorator.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
dd-java-agent/instrumentation/datastax-cassandra-3/src/main/java/datadog/trace/instrumentation/datastax/cassandra/CassandraClientDecorator.java
dd-java-agent/instrumentation/elasticsearch/src/main/java/datadog/trace/instrumentation/elasticsearch/ElasticsearchRestClientDecorator.java
dd-java-agent/instrumentation/elasticsearch/transport-2/src/main/java/datadog/trace/instrumentation/elasticsearch2/TransportActionListener.java
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/main/java/datadog/trace/instrumentation/elasticsearch5_3/TransportActionListener.java
dd-java-agent/instrumentation/elasticsearch/transport-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/TransportActionListener.java
dd-java-agent/instrumentation/elasticsearch/transport-6/src/main/java/datadog/trace/instrumentation/elasticsearch6/TransportActionListener.java
dd-java-agent/instrumentation/elasticsearch/transport-7.3/src/main/java/datadog/trace/instrumentation/elasticsearch7_3/TransportActionListener.java
dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/UrlInstrumentation.java
dd-java-agent/instrumentation/lettuce-4/src/main/java8/datadog/trace/instrumentation/lettuce4/LettuceClientDecorator.java
dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/LettuceClientDecorator.java
dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitChannelInstrumentation.java

Consistently use the PORTS cache.  Where an `InetSocketAddress` was available, I made those places use the correct `onPeerConnection`

Use PORTS cache for `peer.port`

---

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
internal-api/src/main/java/datadog/trace/api/IOLogger.java
internal-api/src/test/groovy/datadog/trace/api/IOLoggerTest.groovy

We have 2 uploaders in dd-trace-java. The trace one has a lot of logic to prevent it from becoming too verbose if logger level is info or above while still keeping track of the most important info. The profiling uploader did a poorer job of this and actually printed stacktraces on every IOException.
Instead of just copying more behaviour from one uploader to the other, this PR attempts to standardize logging around uploading so both trace and profile uploading logs follow the same structure and behaviour (and test it).

Use same logging logic for APM and profile uploaders.

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java

The `analyticsSampleRate` field is unused in CoreSpanBuilder.  This removes it.

Remove unused analyticsSampleRate in CoreSpanBuilder

---

dd-java-agent/instrumentation/jetty-8/jetty-8.gradle
dd-java-agent/instrumentation/jsp-2.3/jsp-2.3.gradle
dd-java-agent/instrumentation/vertx-web-3.4/vertx-web-3.4.gradle

* Exclude Jetty 11 from muzzle as it requires servlet 5.0 which has different package names. Also pin the servlet spec version to fix a muzzle issue with Jetty 10 which pulls in servlet 4.0 that has a class compiled with Java 11 (it can still work with servlet 3)
* Update vertx-web muzzle range to exclude 4.0.0 which removes 'rawMethod' from its HttpServerRequest
* Update jsp muzzle range to exclude tomcat-jasper 10.0.0 as it requires servlet 5.0 which has different package names

Muzzle updates to reflect recent servlet 5 releases

---

dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWS1ClientTest.groovy

latest `AmazonRDSClient` seems to have extra `StartDBInstanceAutomatedBackupsReplicationPresignHandler`and the count of `requestHandler2s` becomes 5 instead of 4 in previous versions (+ we add our TracingRequestHandler during instrumentation).
This change:
- removes check for total count of requestHandler2s 
- checks that exactly one "TracingRequestHandler" was added during instrumentation

Don't check total count of request handlers in AmazonWebServiceClient

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcherTest.groovy

Also updates debug logging to only log failed redefines if we would have originally injected the class. This avoids log-spam when we inject the field into a superclass and later on the subclass is redefined.

Consider transitive interfaces when deciding which class to field-inject

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricKey.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/OkHttpSink.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AgentIntegrationTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AggregateMetricTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/OkHttpSinkTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy

* We don't need dbtype on the metrics any more
* We need a buffering mechanism for when the agent is in a degraded state

metric buffering + payload format change

---

dd-java-agent/dd-java-agent.gradle
dd-trace-core/src/main/java/datadog/trace/common/metrics/AggregateMetric.java
utils/histograms/histograms.gradle
utils/histograms/src/main/java/datadog/trace/core/histogram/DDSketchHistogram.java
utils/histograms/src/main/java/datadog/trace/core/histogram/Histogram.java
utils/histograms/src/main/java/datadog/trace/core/histogram/StubHistogram.java
utils/histograms/src/test/groovy/HistogramsTest.groovy

DDSketch no long requires `protobuf-java` in order to serialize to protobuf (See [implementation](https://github.com/DataDog/sketches-java/pull/32), [benchmarks](https://github.com/DataDog/sketches-java/pull/40)), so this drops the dependency on protobuf-java, and reduces the threshold on jar size.

bump DDSketch and drop protobuf-java dependency

---

dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy

Cleanup ScopeManagerTests:
* Remove unnecessary casts
* Splitting tests that did too much
* Renaming tests/adding inline comments to when/then
* Cleanup of when/then flows
* Removing redundant tests
* Removing unnecessary `@Timeout`
I did uncover an issue.  See
> "exception thrown in TraceInterceptor does not leave scope manager in bad state when reporting through PendingTraceBuffer"
I will fix that in a separate pull request.

Audit and cleanup ScopeManagerTest

---

dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy

`traceValid` was always true and never changed.
The nested `if..else` chain in `decrementRefAndMaybeWrite` is cleaner if everything is at the same level.

Remove unnecessary field and nesting in PendingTrace

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/AggregateMetric.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy

Previously we had the two following fields
- Hits: count of ok and errors spans
- HitsLatencies:  histogram of ok spans (does not include errors)
To avoid confusion with the hits prefix, renaming HitsLatencies to okLatencies. Change has already been [made on the agent]( https://github.com/DataDog/datadog-agent/blob/0bfe21364df9f1685e2a0e1f8ab7f0e67009c9e4/pkg/trace/pb/stats.proto#L32-L36)

Rename hitLatencies to okLatencies

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy

In the ScopeManager Audit PR, I discovered that throwing an exception in a `TraceInterceptor` crashes the PendingTraceBuffer thread and delayed reported traces never get reported again.
This PR fixes that problem with a simple `try..catch` around the interceptor call.

Exception in TraceInterceptor crashes PendingTraceBuffer

---

dd-java-agent/instrumentation/mongo/driver-3.1/src/main/java/datadog/trace/instrumentation/mongo/TracingCommandListener.java
dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/MongoClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-4/src/main/java/datadog/trace/instrumentation/mongo4/Tracing4CommandListener.java
dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ReactiveClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-async-3.3/src/test/groovy/MongoAsyncClientTest.groovy

`ServerAddress.getSocketAddress()` is implemented as follows, so isn't safe for a tracing library to call
```java
/**
* Gets the underlying socket address
*
* @return socket address
*/
public InetSocketAddress getSocketAddress() {
try {
return new InetSocketAddress(InetAddress.getByName(host), port);
} catch (UnknownHostException e) {
throw new MongoSocketException(e.getMessage(), this, e);
}
}
```

Avoid dns lookup in mongo instrumentations

---

.circleci/config.yml
dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy
dd-smoke-tests/slf4j-mdc/src/test/groovy/datadog/smoketest/Slf4jMDCSmokeTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy

Previously, for processes we created in the jvm, we were losing the crash file.  With this PR, everywhere we create a new process, dump the crash file in a well-known location instead of the default (the current working dir).
This should help diagnose some of failing smoke test issues.

Set -XX:ErrorFile everywhere for JVM crashes

---

gradle/jacoco.gradle

I ran into this issue locally where the `forkedTest` task had been run and was cached and the `executionData` for forked tests wasn't included in the report or verification, making the `check` fail.

Fix Jacoco test coverage verification failing because of cache

---

dd-java-agent/instrumentation/jms/src/latestDepTest/groovy/JMS2Test.groovy
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
dd-java-agent/instrumentation/jms/src/test/groovy/JMS1Test.groovy
dd-java-agent/instrumentation/spring-jms-3.1/src/test/groovy/SpringSAListenerTest.groovy

When consuming messages via JMS, messages sometimes includes a creation timestamp
If this is available, add the time spent in queue span tag in the consume calls

Extend JMS Integration to support Time Spent in Queue

---

dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerAdapterInstrumentation.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/SpringWebHttpServerDecorator.java
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SpringBootBasedTest.groovy
dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/TestController.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy

This can happen often for rest endpoints that explicitly return 404 to signal a requested resource is not available.
The main side effect being a resource name change to routes that match `/**` not being grouped. (Can potentially be considered a feature as that level of grouping is unlikely useful.)

Avoid grouping Spring Web routed requests into 404 bucket

---

dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceConfigInstrumentation.java
dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceConfigTest.groovy

PR to extend support of DD_TRACE_METHODS configuration to support wildcards in method calls
EX: `ClassName[*] `

Extend DD_TRACE_METHODS to support wildcarded method argument

---

dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy

* The CAS with the `WeakReference` when setting the root span was showing up in profiles. I don't see any harm in keeping a direct reference to the root span.
* `rootSpanWritten` could have been volatile, as currently implemented.

Make PendingTrace lighter-weight

---

dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/CallDepthThreadLocalMapTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/DatadogClassLoaderTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/ExcludeFilterTest.groovy
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/WeakMapTest.groovy
dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/WeakCacheTest.groovy
dd-java-agent/testing/src/test/groovy/utils/ThreadUtilsTest.groovy
dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ExcludedVersionsTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/MultiWriterTest.groovy
utils/test-utils/src/main/groovy/datadog/trace/test/util/DDSpecification.groovy

All tests that touch `Config` need to extend `DDSpecification` or issues occur.  It's easier just to have all tests extend `DDSpecification` (with a few exceptions).
Previously, when the `Config` class couldn't be transformed, the first test where it fails throws `IllegalStateException`->`ExceptionInInitializer` and the second test throws `NoClassDefFoundError` (since the first attempt to load the `DDSpecification` failed.
This PR improves the error messaging when the Config class can't be transformed and updates all applicable tests to extend `DDSpecification`

Fix NoClassDefFoundError with DDSpecification

---

dd-trace-api/src/main/java/datadog/trace/api/sampling/PrioritySampling.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapper.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_4.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_5.java
dd-trace-core/src/main/java/datadog/trace/core/CoreSpan.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SimpleSpan.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceGenerator.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

This avoids storing the sampling priority in a map. I chose to represent it as a `byte` since `PrioritySampling.UNSET` is a constant local to the tracer. Currently `DDSpanContext` is already at 80 bytes, so because of alignment it will grow to 88 bytes whether we choose `byte` or `int`, but assuming we can remove fields in the future, choosing a `byte` will pay off. The main aim of this PR is not to need to store or access the value in the map.

represent sampling priority as a byte

---

dd-trace-core/dd-trace-core.gradle
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy

* replace impossible null checks with annotations (this PR doesn't set up spotbugs in the build though)
* replace unnecessary trace id checks with trust between `DDSpan` and `PendingTrace`, with reduced access to `PendingTrace` mutators
* replace unnecessary time check with trust between `DDSpan` and `PendingTrace`, with reduced access to `PendingTrace` mutators
* ~don't call `PendingTrace.size()` twice before writing~

pendingtrace streamlining

---

dd-java-agent/benchmark-integration/play-perftest/play-perftest.gradle
dd-smoke-tests/play-2.4/play-2.4.gradle
dd-smoke-tests/play-2.5/play-2.5.gradle
dd-smoke-tests/play-2.6/play-2.6.gradle
dd-trace-java.gradle
gradle/repositories.gradle
test-published-dependencies/build.gradle

jcenter keeps returning `502` intermittently, so move it after maven central

Move jcenter after maven central

---

dd-trace-core/src/main/java/datadog/trace/core/processor/TraceProcessor.java
dd-trace-core/src/main/java/datadog/trace/core/processor/rule/URLAsResourceNameRule.java
dd-trace-core/src/test/groovy/datadog/trace/core/processor/TraceProcessorTest.groovy

This change allows 404 resource name rewriting to be disabled independent of the URL resource name rewriting.  It does this by making Status404Rule and Status404Decorator sub-features of URLAsResourceNameRule.
The background is that a previous pull request allowed the disabling of decorators via config with the specific example being the status404decorator (see https://github.com/DataDog/dd-trace-java/pull/1152).  A subsequent pull request combined the status404decorator setting into an uber setting and it could no longer be set independently (see https://github.com/DataDog/dd-trace-java/pull/1551).
I have a use case where a REST API returns 404 and I'd like to be able to identify those traces by the URL of the API.

Allow disabling Status404Rule leaving URLAsResourceNameRule enabled

---

internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

This is just a copy/override of the method on `MutableSpan`, but it allows it to be less particular about the public API version.
(In effort to fix the failing muzzle checks.)

Define `setResourceName` on internal API

---

dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java

I missed this class when I added support for configuring the agent URL in #1929 - in most cases there's no difference in the final logged value, but since `config.getAgentUrl()` is what the code uses we should be consistent. Also log the unix domain socket as it can be configured separately and it's useful to know if it's set.

Log the final configured agent URL and unix-domain-socket

---

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
dd-trace-core/src/main/java/datadog/trace/core/http/OkHttpUtils.java
internal-api/internal-api.gradle
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
internal-api/src/main/java/datadog/trace/util/AgentProxySelector.java

This will let users exclude agent hosts from being proxied without having to tweak their JVM or OS proxy settings.
This setting is specified in https://docs.datadoghq.com/agent/proxy/?tab=agentv6v7#environment-variables as:
```
DD_PROXY_NO_PROXY: Sets a list of hosts that should bypass the proxy. The list is space-separated
```

Support DD_PROXY_NO_PROXY setting for agent HTTP connections

---

dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java

This feature already exists in the codebase, this PR just changes the default setting to have it enabled out-of-the-box.
Performance testing indicates this doesn't introduce much overhead, and the work only occurs once per-affected-class.

Enable automatic generation of missing serialVersionUid for field-injected Serializable types

---

dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpServerInstrumentation.java
dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/DatadogServerRequestResponseFlowWrapper.java
dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/DatadogWrapperHelper.java
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/ApacheHttpAsyncClientInstrumentation.java
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/DelegatingRequestProducer.java
dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/TraceContinuedFutureCallback.java
dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java
dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/HelperMethods.java
dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/WrappingStatusSettingResponseHandler.java
dd-java-agent/instrumentation/finatra-2.9/src/main/java/datadog/trace/instrumentation/finatra/FinatraInstrumentation.java
dd-java-agent/instrumentation/finatra-2.9/src/main/java/datadog/trace/instrumentation/finatra/Listener.java
dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyHttpHandlerInstrumentation.java
dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/SpanClosingListener.java
dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/AbstractRequestContextInstrumentation.java
dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/RequestFilterHelper.java
dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/ChannelPipelineAdviceUtil.java
dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/NettyChannelPipelineInstrumentation.java
dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/OnCompleteHandler.java
dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/RediscalaInstrumentation.java
dd-java-agent/instrumentation/spring-data-1.8/src/main/java/datadog/trace/instrumentation/springdata/InterceptingRepositoryProxyPostProcessor.java
dd-java-agent/instrumentation/spring-data-1.8/src/main/java/datadog/trace/instrumentation/springdata/RepositoryInterceptor.java
dd-java-agent/instrumentation/spring-data-1.8/src/main/java/datadog/trace/instrumentation/springdata/SpringRepositoryInstrumentation.java
dd-smoke-tests/agent-isolation/agent-isolation.gradle
dd-smoke-tests/agent-isolation/src/main/java/datadog/smoketest/agentisolation/Agent.java
dd-smoke-tests/agent-isolation/src/main/java/datadog/smoketest/agentisolation/App.java
dd-smoke-tests/agent-isolation/src/test/groovy/datadog/smoketest/AgentIsolationSmokeTest.groovy
settings.gradle

Because some of `ApacheHttpClientInstrumentation`'s helper classes, which are visible to the application classloader are nested, but their enclosing class `ApacheHttpClientInstrumentation` is not made visible to the target classloader, calling `Class.getSimpleName` throws `NoClassDefFoundError`
```java
@Override
public String[] helperClassNames() {
return new String[] {
packageName + ".ApacheHttpClientDecorator",
packageName + ".HttpHeadersInjectAdapter",
packageName + ".HostAndRequestAsHttpUriRequest",
getClass().getName() + "$HelperMethods",
getClass().getName() + "$WrappingStatusSettingResponseHandler",
};
}
```

Move nested helper classes to top level, add smoke test for ApacheHttpClient classloader isolation

---

dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java

This branch will track [FJP changes](https://github.com/openjdk/jdk/pull/1646) which could break our instrumentation.

exclude new ForkJoinTask type from RunnableFuture instrumentation

---

dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricKey.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/OkHttpSink.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AgentIntegrationTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/OkHttpSinkTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/UTF8BytesString.java
utils/histograms/src/main/java/datadog/trace/core/histogram/DDSketchHistogram.java
utils/histograms/src/test/groovy/DDSketchHistogramTest.groovy

* micro-optimisation on allocations in `MetricKey` - avoid allocating the UTF-8 encoding of the empty string
* Make it possible to _enable_ buffering when the agent is slow to respond - disable by default
* Change sketch mode to collapse from below, add statistical tests to verify this change is valid while maintaining 1% relative error in the relevant quantiles

metrics performance

---

.circleci/config.yml
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java
dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ProfilingSystemTest.java
dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
dd-smoke-tests/agent-isolation/src/test/groovy/datadog/smoketest/AgentIsolationSmokeTest.groovy
dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/ProfilingIntegrationContinuousProfilesTest.groovy
dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/ProfilingIntegrationShutdownTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
utils/test-utils/src/main/java/datadog/trace/test/util/ForkedTestUtils.java

```
java.lang.IllegalStateException: Shutdown in progress
at java.base/java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
at java.base/java.lang.Runtime.addShutdownHook(Runtime.java:216)
at jdk.jfr/jdk.jfr.internal.SecuritySupport.lambda$registerShutdownHook$8(SecuritySupport.java:316)
at jdk.jfr/jdk.jfr.internal.SecuritySupport$2.run(SecuritySupport.java:210)
at jdk.jfr/jdk.jfr.internal.SecuritySupport$2.run(SecuritySupport.java:207)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:430)
at jdk.jfr/jdk.jfr.internal.SecuritySupport.doPrivileged(SecuritySupport.java:207)
at jdk.jfr/jdk.jfr.internal.SecuritySupport.registerShutdownHook(SecuritySupport.java:316)
at …
```

If process shuts down early then registration of shutdown hooks by JFR may fail

---

.circleci/config.yml
dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
dd-smoke-tests/agent-isolation/src/test/groovy/datadog/smoketest/AgentIsolationSmokeTest.groovy
dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
utils/test-utils/src/main/java/datadog/trace/test/util/ForkedTestUtils.java

The memory allocated for gradle was greater than the available memory on the machine.  This lead to random `error 137` depending on how the forked tests overlapped.
For smoke tests and `runOnSeparateJvm()` tests, we weren't setting any memory parameters leading to each forked process consuming up to `.25 * 16GB = 4GB` of memory each.
The XLarge machine in CircleCI has 16GB of memory.
**Build job**:
The build doesn't fork any processes other than through gradle.  Therefore:
7 max workers * 2GB = 14GB total for gradle
**Test Job**
Each test task can potentially create one forked process (smoke test or `runOnSeparateJvm()`).  Therefore:
7 max workers * 2 * 1GB = 14GB total for gradle
**Check Job**
Similar to the Build job, all forks are through gradle.  Therefore:
7 max workers * 2GB = 14GB …

Fix gradle memory overallocation

---

dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/BaseDecoratorTest.groovy

Reduces time to test decorator package from 6.5s to 1.5s

Avoid 5s pause for creation of unresolvable InetSocketAddress

---

dd-java-agent/instrumentation/datastax-cassandra-4/src/test/groovy/CassandraClientTest.groovy

Reduces test time from
Task | Duration
-- | --
:dd-java-agent:instrumentation:datastax-cassandra-4 | 4m25.78s
:dd-java-agent:instrumentation:datastax-cassandra-4:test | 2m16.78s 
:dd-java-agent:instrumentation:datastax-cassandra-4:testJava8Generated | 1m55.96s
to 
Task | Duration 
-- | -- 
:dd-java-agent:instrumentation:datastax-cassandra-4 | 2m8.67s 
:dd-java-agent:instrumentation:datastax-cassandra-4:testJava8Generated | 59.295s 
:dd-java-agent:instrumentation:datastax-cassandra-4:test | 54.630s
Another approach which setup a new keyspace for each test, but avoided deleting the old one (which would allow tests which could actually mutate the database to run in parallel) was ruled out, but had some impact too:
Task | Duration 
-- | -- 
:dd-java-agent:instrumentation:datastax-cassandra-4 …

reduce time spent in cassandra 4 client test by reusing the (readonly) database prerequisites

---

.circleci/config.yml
utils/test-utils/src/main/java/datadog/trace/test/util/ForkedTestUtils.java

This ups the test workers to 6 by reducing the memory slightly.
6 * 1940 + 6 * 512 = 14,712.  This leaves 1,672mb for the OS and native mem.

Add another gradle worker but use less memory

---

dd-java-agent/instrumentation/jax-rs-client-2.0/src/main/java/datadog/trace/instrumentation/jaxrs/ClientTracingFeature.java
dd-trace-core/dd-trace-core.gradle
dd-trace-core/src/main/java/datadog/trace/common/sampling/DeterministicSampler.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogHttpCodec.java

I don't see any value in any of this logging any more.
1. I have never needed to pay attention to sampling priorities or sampling decisions, this module is quite well tested and I trust that it works
2. PendingTrace used to be a component we were paranoid about - now the only interesting event is partial flushes.
3. I trust that the DatadogHttpCodec propagates the correct trace id
4. I don't think we care if or how many times the JAX-RS `ClientTracingFilter` is registered.

remove heavy debug logging

---

gradle/repositories.gradle

Hitting all of these repos has lead to rate limits.  Restrict them to only the groups we know they contain.

Restrict maven groups from certain repositories

---

dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/src/main/java/datadog/trace/instrumentation/scala/promise/CallbackRunnableInstrumentation.java
dd-java-agent/instrumentation/scala-promise/scala-promise-2.13/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseTransformationInstrumentation.java

This double counting and overwriting of `State` was _hidden_ by the fact that we write out partial traces. Probably not end user visible, apart from the tracer holding on to pending traces longer than necessary.
I would really like for there to be a strict mode for writing out traces, that we could use in tests to validate that the counts add up.
Oh, and this cuts the time for the tests on my machine from `26` to `13` seconds for `:dd-java-agent:instrumentation:scala-promise:scala-promise-2.10:test` and the same for `:dd-java-agent:instrumentation:scala-promise:scala-promise-2.13:test`

Fix double counting and State overwriting for Scala Promise/Future

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java

The previous log message was incorrect.  `Tracer.class` is not an open tracing class

Update misleading logging in ClassLoaderMatcher

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
gradle/dependencies.gradle

Update to the latest client.  The previous client added 1 second per call to `trace.close()` in our tests.  Release notes for the client can be found at: https://github.com/DataDog/java-dogstatsd-client/releases

Update java-dogstatsd-client to 2.11.0

---

dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy

When the target process in smoketest dies, the tests usually fail with a timeout from a client call, spans not being generated, or something else similarly opaque.
This simple checks that the target process is alive before all tests to fail fast.

Make sure process is alive before all smoke tests

---

dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

Agentless profiling is no longer officially supported at Datadog and there are other parts of Datadog that are now starting to add `DD_API_KEY` environment variables (example: cloudfoundry buildpack setup https://docs.datadoghq.com/integrations/pivotal_platform/#metric-collection). In these scenarios, customers are being forced to use the deprecated profiling agentless because the `DD_API_KEY` env gets exposed to the application.
This PR changes this behaviour. Instead of completely dropping agentless support which is useful for debugging certain situations in non-prod scenarios, it hides that behaviour under a separate flag that is separate from the presence of an api key.
This WILL stop profile uploading for orgs that are still using old datadog agents, haven't followed our agentless …

profiling: don't assume agentless if api key set.

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCWrappedInterfacesTest.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

This is here for review of the lists I have made of connection and preparedstatement implementations, in case any omissions jump out.
The motivation is twofold, both because JDBC involves lots of wrapping and we only want to create a single span:
* We currently rely on lawful unwrapping behaviour, and work around unlawful unwrapping _when we discover it_ with various approaches, including a `ClassValue<Boolean>` of bad unwrapping candidates, and _replacing_ the implementations of `unwrap` in some datanucleus wrappers. Targeting known non-delegating implementations makes this problem go away, so long as we can create a comprehensive enough list of implementation classes.
* Performance - see #2220 which improves `Connection` to `DBInfo` association, which interferes with datanucleus, but …

Match specific direct JDBC driver implementations

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/rmi/ContextDispatcher.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/rmi/ContextPayload.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/rmi/ContextPropagator.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/rmi/RmiClientDecorator.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/rmi/RmiServerDecorator.java
dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/client/RmiClientInstrumentation.java
dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/context/client/RmiClientContextInstrumentation.java
dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/context/server/RmiServerContextInstrumentation.java
dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/server/RmiServerInstrumentation.java

This avoids the need to inject them onto the bootclasspath at runtime (relies on the filesystem and doesn't work well in some environments.)

Move RMI helper classes to agent-bootstrap

---

dd-java-agent/instrumentation/classloading/src/main/java/datadog/trace/instrumentation/classloading/ClassloadingInstrumentation.java
dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ClassLoadingTest.groovy
dd-java-agent/src/test/java/jvmbootstraptest/IsolatedClassloading.java
dd-java-agent/src/test/java/jvmbootstraptest/IsolatingClassLoader.java

* Add test that recreates the classloader exception when instrumenting isolated classloaders
* Make sure we access agent types used in the call-depth block like `Constants` before entering it.
If we don't then we risk loading these agent types with a non-zero call-depth, which will fail.
* Minor improvement since we know `Class.forName` will only be called at most once
* Robustness: always fall back to original classloading behaviour in the face of advice errors

Fix classloader instrumentation error involving isolated classloaders

---

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeAndContinuationLayoutTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ScopeSource.java

While evaluating the change in #2215 I explored the microbenchmark below:
```java
import datadog.trace.bootstrap.instrumentation.api.AgentTracer;
import org.openjdk.jmh.annotations.*;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.FutureTask;
@State(Scope.Benchmark)
public class RunFutureTask {
@Param({"true", "false"})
boolean activeScope;
private Callable<?> callable;
@Setup(Level.Trial)
public void setup() {
if (activeScope) {
AgentTracer.activateSpan(AgentTracer.startSpan("foo"));
}
callable = (Callable<Object>) () -> "foo";
}
@Benchmark
public Object runFutureTask() throws ExecutionException, InterruptedException {
FutureTask<?> task = new FutureTask<>(callable);
task.run();
return task.get();
}
}
```
When no scope is …

scope manager efficiency improvements

---

dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeAndContinuationLayoutTest.groovy

This is functionally equivalent, so long as the _currently active_ span does not have more than 32768 scopes created per thread, and allow the reference count to be stored in an alignment gap, saving 8 bytes per scope.
**master**
```
datadog.trace.core.scopemanager.ContinuableScopeManager$ContinuableScope object internals:
OFFSET  SIZE                                                                   TYPE DESCRIPTION                               VALUE
0    12                                                                        (object header)                           N/A
12     4                                                                    int ContinuableScope.referenceCount           N/A
16     1                                                                boolean …
```

Use short for reference count in ContinuableScope

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/Batch.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/NoOpMetricsAggregator.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy

Aggregates which have been previously reported, but have not been updated in the last reporting cycle, would be reported as empty metrics. This PR changes this behaviour to expunge any metrics which have not been updated recently so they drop out of the LRU cache early.

expunge aggregates not updated within a reporting cycle

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/DBQueryInfo.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/DBQueryInfoTest.groovy
dd-java-agent/instrumentation/datanucleus-4/src/test/groovy/DatanucleusTest.groovy
dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/CriteriaTest.groovy
dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/QueryTest.groovy
dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/SessionTest.groovy
dd-java-agent/instrumentation/hibernate/core-4.0/src/test/groovy/CriteriaTest.groovy
dd-java-agent/instrumentation/hibernate/core-4.0/src/test/groovy/QueryTest.groovy
dd-java-agent/instrumentation/hibernate/core-4.0/src/test/groovy/SessionTest.groovy
dd-java-agent/instrumentation/hibernate/core-4.3/src/test/groovy/ProcedureCallTest.groovy
dd-java-agent/instrumentation/hibernate/core-4.3/src/test/groovy/SpringJpaTest.groovy
dd-java-agent/instrumentation/jdbc/scalikejdbc/src/test/groovy/ScalikeJDBCInstrumentationTest.groovy
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCWrappedInterfacesTest.groovy
dd-java-agent/instrumentation/scala-concurrent/src/slickTest/groovy/SlickTest.groovy
dd-java-agent/instrumentation/spring-data-1.8/src/test/groovy/SpringJpaTest.groovy

This adds the `db.operation` tag recently added to mongodb spans, as part of an investigation of how hard it would be to normalise SQL prior to metrics aggregation, and specifically how cacheable data derived from SQL is.

Add db.operation tag to JDBC spans

---

dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ScopeEventTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/api/writer/PrintingWriterTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/sampling/ForcePrioritySamplerTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/sampling/RateByServiceSamplerTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/sampling/RuleBasedSamplingTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentApiTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/TraceMapperTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanSerializationTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceStrictWriteTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTestBase.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/TraceCorrelationTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/TraceInterceptorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/processor/TraceProcessorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/processor/URLAsResourceNameRuleTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpInjectorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpInjectorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpInjectorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpInjectorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerDepthTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/test/DDCoreSpecification.groovy

So `tracer.close()` will shut down the `statsDClient`, which for some reason takes roughly 1 second. This means that every test that create and close a `tracer` will take 1 second extra. This change makes `dd-trace-core:test` go from 8 minutes to 1.5 minutes on my machine.

Use NoOpStatsDClient when possible to speed up tests

---

dd-trace-core/dd-trace-core.gradle
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy

The `flush` method (that is only used in tests) in `PendingTraceBuffer` drained the `MPSC` queue on the wrong thread, leading to a race where elements could be missed. The flushing now happens on the `worker` thread.
To speed up things by not having the `flush` method get stuck behind the `sleep` that was done after requeueing pending traces that were still _active_, the `sleep` has been replaced with a separate queue that is put back on the main queue after the appropriate time has elapsed.

Move PendingTraceBuffer flush to consumer thread and remove sleep

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ComparableRunnable.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExcludeFilter.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/Wrapper.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RejectedExecutionHandlerInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/WrapRunnableAsNewTaskInstrumentation.java
dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/test/java/TypeAwareThreadPoolExecutor.java

When we wrap, via `newTaskFor` or otherwise, the wrapper type leaks at template methods, and in rejected execution handlers. This solves `ClassCastException` in subclasses of `ThreadPoolExecutor`.

Targeted Instrumentation for ThreadPoolExecutor

---

dd-trace-core/dd-trace-core.gradle
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy

Reverts DataDog/dd-trace-java#2329
This change had a bad impact on CPU usage. The `flush` fix will be in a separate PR from any changes to the requeue logic.

Revert "Move PendingTraceBuffer flush to consumer thread and remove sleep"

---

dd-trace-core/src/main/java/datadog/trace/common/writer/PrintingWriter.java
dd-trace-core/src/test/groovy/datadog/trace/api/writer/PrintingWriterTest.groovy

Here is an example of PrintingWriter output:
```
{
"traces": [
{
"service": "lambdainternal.AWSLambda",
"name": "trace.annotation",
"resource": "Handler.handleRequest",
"trace_id": "4d16a13fbfd90a9f",
"span_id": "61bc913f36167bb7",
"parent_id": "0",
"start": 1611588270763038500,
"duration": 3574451,
"error": 0,
"metrics": {
"_dd.agent_psr": 1
},
"meta": {
"runtime-id": "14bfd33e-63a5-43f4-8550-b8c8bae7b2c2",
"language": "jvm",
"component": "trace",
"thread.name": "main",
"request_id": "e0ea9c2b-80ba-413a-a636-fba1da90b817",
"thread.id": "1"
}
}
]
}
```
The output of PrintingWriter did not quite conform to the specification here: https://github.com/DataDog/architecture/blob/master/rfcs/serverless/lambda-direct-tracing/rfc.md#export-traces-to-logs . Specifically, `traces` should be a list …

Update printing writer to output a Map<String, List<List<Span>>>>

---

dd-trace-core/dd-trace-core.gradle
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy

This PR only moves the `flush` (which is a method only used from tests) handling onto the `worker` consumer thread, since the queue is an MPSC queue and should only be read from the _consumer_. It does not change the `PendingTraceBuffer` queue processing behavior. This is done to fix flakiness in tests.

Move PendingTraceBuffer flush to consumer thread

---

dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/server/VertxRxCircuitBreakerHttpServerTest.groovy
dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/server/VertxRxHttpServerTest.groovy
dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/VertxHttpServerTest.groovy
dd-java-agent/instrumentation/vertx-web-3.4/src/test/java/server/VertxChainingTestServer.java
dd-java-agent/instrumentation/vertx-web-3.4/src/test/java/server/VertxTestServer.java

But exclude from the chaining variant. (It doesn't pick up the path properly.)

Add vertx path param test

---

dd-smoke-tests/dd-smoke-tests.gradle

I noticed that after the `core` tests started running faster again #2331 , and consuming more CPU on the CI box, there started to be timeouts in the `smoke-tests` again. This change limits the number of concurrent `smoke-tests` to 1, so that they don't interfere with each other and the rest of the tests too much.

Limit the number of concurrent smoke tests to 1

---

dd-java-agent/instrumentation/opentelemetry/src/main/java/datadog/trace/instrumentation/opentelemetry/OtelSpan.java
dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTSpan.java
dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTSpan.java
dd-trace-api/src/main/java/datadog/trace/api/interceptor/MutableSpan.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-ot/src/main/java/datadog/opentracing/OTSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java

also avoids nullability questions.
This is a breaking binary change for anyone downstream using the `isError()` method, but it should be source compatible (as the Java compiler will handle any boxing-related differences) so they would just need to recompile against the new agent.

Avoid span.isError() boxing

---

gradle/java.gradle

Missed this in #2352 , and just got timeouts on CI for `latestDepForkedTest`

Limit heap and concurrency for the generated forkedTest tasks

---

.circleci/config.yml
dd-java-agent/instrumentation/jdbc/jdbc.gradle
dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
dd-java-agent/instrumentation/jdbc/src/test/groovy/RemoteJDBCInstrumentationTest.groovy

This test needs some refactoring to support multiple drivers against the same db, e.g. mariadb-client/mysql-connector running against mysql.

add jdbc tests for mysql and postgresql

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategy.java
gradle/dependencies.gradle

This update has a low impact optimisation which prevents from allocating matchers which can be constant. See [release notes](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.10.20)

update byte-buddy to 1.10.20

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy

The most common failure right now is a read or connect timeout in an http client test.

Make test socket timeouts longer

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java

Avoids checking for something that no longer exists :)

Remove stale reference to CallableWrapper which was removed in #1973

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
dd-trace-api/src/main/java/datadog/trace/api/IdGenerationStrategy.java

This was never actually used for its intended purpose and now that context propagation works well, it will never serve any purpose, except to potentially create lots of thread locals.

remove THREAD_PREFIX id generation strategy

---

dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecoratorTest.groovy
dd-java-agent/instrumentation/exception-profiling/src/test/java/com/datadog/profiling/exceptions/ExceptionHistogramTest.java
dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

this is just cleaning up how config gets these constants, no functional change

Prefer static imports instead of copying the constant

---

gradle/wrapper/gradle-wrapper.properties

https://docs.gradle.org/6.8.2/release-notes.html
* fixes performance regression when file system watching is enabled on macOS / Windows
* [improved toolchain support](https://docs.gradle.org/6.8.2/release-notes.html#java-toolchain-improvements)
* [option to mark tests as flaky when re-running](https://docs.gradle.org/6.8.2/release-notes.html#test-re-run-junit-xml-reporting-enhancements)

Update Gradle to 6.8.2

---

dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy

I'm not sure this was testing anything `connection error non routable address` wasn't, so I've removed the test

remove test which targets a blocked port at google.com

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatDecorator.java

Some of what's changed here really adds up, larger than e.g starting or finishing spans
* IPV4 regex validation towards the left
* Removing tags from an empty map in `TomcatDecorator` because the attributes are null (purple bar in the middle)
* Building the normalised URL (yellow bar to the right)

HttpServerDecorator performance tweaks

---

dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/HealthMetrics.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/monitor/HealthMetricsTest.groovy

This batches up health metrics and publishes them to StatsD twice per minute.

prevent application threads from interacting directly with StatsD

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
dd-java-agent/src/test/groovy/datadog/trace/agent/CustomMBeanServerBuilderTest.groovy
dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
internal-api/src/main/java/datadog/trace/util/AgentTaskScheduler.java

Delay starting JMX related services in agent bootstrap 
Defaults to 15 seconds, can be configured with `-Ddd.jmxfetch.start-delay` or `DD_JMXFETCH_START_DELAY`

Delay starting JMXFetch (15s to match default check period)

---

dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy
dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
dd-java-agent/src/test/java/jvmbootstraptest/JmxStartedChecker.java

This should fix a test failure I saw recently because the local `JMXFETCH_CLASSLOADER` field wasn't initialized at the time this test ran. Tests should not rely on the status of any agent attached to the build process, so I changed this to use a forked process instead.

Update JMXFetchTest to test a real process rather than use flaky reflection hacks

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/DBQueryInfo.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
internal-api/src/main/java/datadog/trace/api/normalize/SQLNormalizer.java

* Use the concrete class names from the Oracle JDBC driver which are publicly documented in the Javadoc
* Remove the cache for `Statement` SQL since we don't know the access patterns (e.g. there could be millions of 100 character `select user.name from user where user.id = <user_id>`) and the normaliser is fast anyway
* Add paranoid error handling in the normaliser, and don't copy strings we don't need to modify.

jdbc tweaks

---

dd-java-agent/src/test/java/jvmbootstraptest/LogManagerSetter.java

Avoid accessing the CustomLogManager type in the LogManagerSetter test application
because this will load jul.LogManager, which triggers our class-loading hooks, and
ends up activating various Tracer services like JMX that initialize JUL.
If this happens before we've set the custom logger system property, ie:
```
System.setProperty("java.util.logging.manager", CustomLogManager.class.getName());
```
then there's a very small window where JUL could be initialized before the updated
system property has taken effect (since the class-loading hook and follow-on services
run on a different thread.)

Fix potential timing issue involving CustomLogManagerTest

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy
utils/histograms/src/main/java/datadog/trace/core/histogram/DDSketchHistogram.java

The overhead of serializing DDSketch is relatively costly:
When I wrote the serialization code I noted that serializing dense sketches was a lot faster, so this change should eliminate the overhead:
```
Benchmark            (count)                (generator)  (relativeAccuracy)  (sketchOption)        (unit)  Mode  Cnt   Score   Error  Units
Serialize.serialize   100000                    POISSON                0.01            FAST   NANOSECONDS  avgt    5   0.966 ± 0.003  us/op
Serialize.serialize   100000                    POISSON                0.01            FAST  MICROSECONDS  avgt    5   0.965 ± 0.011  us/op
Serialize.serialize   100000                    POISSON                0.01            FAST  MILLISECONDS  avgt    5   0.983 ± 0.003  us/op
Serialize.serialize   100000 …
```

ddsketch optimisation

---

internal-api/src/main/java/datadog/trace/api/normalize/SQLNormalizer.java
internal-api/src/test/groovy/datadog/trace/api/normalize/SQLNormalizerTest.groovy

Fixes bug which led to `INSERT INTO visits VALUES (2, 8, '2013-01-02', 'rabies shot')` being reduced to `INSERT INTO visits VALUES (?, ?, ?, ? ?)`

fix bug in SQL string replacement

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricWriter.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
dd-trace-core/src/main/java/datadog/trace/core/serialization/GrowableBuffer.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/GrowableBufferTest.java

Fixes a bug when writing a `ByteBuffer` into a `GrowableBuffer` and adds a defensive catch block to prevent the aggregator thread from shutting down when an unexpected error occurs.

aggregator bugs

---

internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java

Not all workers in the Java tracer include a catch clause for `Throwable` around their work loop. Rather than continually look out for this during code reviews it's simpler to define an uncaught exception handler for agent threads that logs any uncaught exceptions.

Set explicit handler to log uncaught exceptions in agent threads

---

dd-java-agent/agent-bootstrap/agent-bootstrap.gradle
dd-java-agent/agent-profiling/profiling-controller-openjdk/profiling-controller-openjdk.gradle
dd-java-agent/instrumentation/rmi/rmi.gradle
dd-java-agent/testing/testing.gradle
dd-trace-core/jfr-openjdk/jfr-openjdk.gradle
gradle/java.gradle

... and add ability to skip this when we need compiler access to packages like `sun.rmi`

When building with Java 9+ lazily set compiler `--release` flag to match target

---

dd-java-agent/agent-bootstrap/agent-bootstrap.gradle
dd-java-agent/agent-profiling/profiling-controller-openjdk/profiling-controller-openjdk.gradle
dd-java-agent/instrumentation/exception-profiling/exception-profiling.gradle
dd-trace-core/jfr-openjdk/jfr-openjdk.gradle

also make Java11 configuration in `agent-bootstrap` lazy so you can still run certain tasks without needing JAVA_11_HOME

Output clear error when building profiling code without setting JAVA_11_HOME first

---

dd-trace-java.gradle
gradle/dependencies.gradle

Upgrade to the latest for each.
I don't think the plugin needs to be Java 7 compatible since we compile with Java 8.
(Motivated by the following error in our CI `check` task: `The value for task ':dd-trace-core:installLombok' property 'mainClass' is final and cannot be changed any further.`)

Update Lombok and Gradle Lombok Plugin

---

dd-trace-core/dd-trace-core.gradle
dd-trace-core/src/main/java/datadog/trace/core/monitor/Monitoring.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/Timer.java
dd-trace-core/src/test/groovy/datadog/trace/core/monitor/TimingTest.groovy
gradle/spotbugs.gradle
internal-api/src/main/java/datadog/trace/api/Config.java

related to #2178 but means we stop using HdrHistogram. I dropped the granularity from nanoseconds to microseconds because it's wasteful for our use case.

drop hdrhistogram

---

.github/workflows/draft-release-notes-on-tag.yaml
.github/workflows/increment-milestones-on-tag.yaml
.github/workflows/update-issues-on-release.yaml

When testing the `update-issues-on-release` workflow via the manual trigger, I found out that I had messed up the `paginate` syntax, and there had been more changes to the `method` names in the github API. I have now tried to diff our actions against the breaking changes in the release notes for `octokit/plugin-rest-endpoint-methods.js`.

Change github actions to use correct paginate syntax and new names

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/TestDecorator.java
dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/TracingListener.java
dd-java-agent/instrumentation/junit-5.3/src/main/java8/datadog/trace/instrumentation/junit5/TracingListener.java
dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TracingListener.java

In this PR, we prevent the reporting of duplicate tests spans when there are test engines executed in a nested way.
E.g., `JUnit5` engine executes a `JUnit4` test.
- Without this fix: (`JUnit5` span ( `JUnit4` span ( ....  ) ) )
- With this fix: (`JUnit5` span ( ... ) )

[CIAPP] Avoid reporting duplicate test spans when nested test engines are executed.

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java

J9 JVMs can throw `InternalError` here, so to be safe we catch any throwable.

Widen catch block when attempting to install JFR ScopeEventFactory

---

dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageExtractAdapter.java
dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageInjectAdapter.java
dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

This is backward incompatible.
The consumer was updated in version 0.59.0 to start accepting `$` as a placeholder. The producer wasn't updates at that time to avoid breaking mixed deployments. This could probably be done now, with a migration note for mixed tracer version environments stating that producers >= 0.69.0 require consumers >= 0.59.0.

change JMS producers to use $ as replacement for -

---

dd-java-agent/instrumentation/reactor-core-3.1/src/main/java/datadog/trace/instrumentation/reactor/core/ReactorHooksInstrumentation.java

We will disable this by default for now so that it can be re-enabled, and merge #2455 in a later release to completely remove the instrumentation. 
To re-enable it, set `-Ddd.integration.reactor-hooks.enabled=true`

disable reactor hooks instrumentation

---

dd-trace-core/dd-trace-core.gradle

See [release notes](https://github.com/JCTools/JCTools/releases/tag/v3.3.0). This includes bug fixes to one of the queues we use.

bump JCTools dependency

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/TestDecorator.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/TestDecoratorTest.groovy
dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java

This PR adds the configuration tags to the `TestDecorator`. These tags will be used to detect test outliers based on the configuration where the test was executed.

[CIAPP] Add configuration tags to TestDecorator

---

dd-java-agent/instrumentation/mule-4/mule-4.gradle

```
> Could not resolve org.mule:mule-core:3.9.5.
> Could not parse POM https://repository.mulesoft.org/releases/org/mule/mule-core/3.9.5/mule-core-3.9.5.pom
> Could not find org.mule:mule:3.9.5.
Searched in the following locations:
- https://repo.maven.apache.org/maven2/org/mule/mule/3.9.5/mule-3.9.5.pom
- https://jcenter.bintray.com/org/mule/mule/3.9.5/mule-3.9.5.pom
- https://maven.anypoint.mulesoft.com/api/v2/maven/org/mule/mule/3.9.5/mule-3.9.5.pom
- https://repository.mulesoft.org/releases/org/mule/mule/3.9.5/mule-3.9.5.pom
- https://repository.mulesoft.org/nexus/content/repositories/public/org/mule/mule/3.9.5/mule-3.9.5.pom
> Could not resolve org.mule:mule-core:3.9.5.
> Could not parse POM https://repository.mulesoft.org/nexus/content/repositories/public/org/mule/mule-core/3.9.5/mu …
```

Exclude bad mule version from muzzle

---

dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/TracingClientInterceptor.java
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
dd-java-agent/instrumentation/grpc-1.5/src/test/proto/helloworld.proto
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

By setting `-Ddd.trace.grpc.ignored.outbound.methods=<comma separated list of full method names>` users can prevent tracing of specific outbound requests.

Allow gRPC users to ignore specific outbound RPC calls

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/DatadogClassLoader.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/InternalJarURLHandlerTest.groovy

This prevents deadlock with the caffeine cache when two classes are loaded from the same package from two different threads at the same time, where a class load from one thread obtains the package level lock first, but loses the race to caffeine's lock around the key (i.e. every class load with same classloader competes for this lock), but the holder of caffeine's lock can't get the package level lock and complete the compute because it's already held. I don't think there is a way to reliably reproduce this deadlock in a unit test.

Synchronize classloads at class not package granularity

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/api/Pair.java

I don't know why the varargs allocation doesn't get eliminated here, but it doesn't

avoid varargs allocation in Pair.hashCode

---

dd-java-agent/instrumentation/okhttp-3/src/test/groovy/OkHttp3Test.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

This change enables a feature which tracks metrics in the tracer instead of the trace agent, and allows the tracer to drop traces the trace agent would drop before serialising them, if the trace agent version is >= 7.27.0, which can significantly reduce the overhead of tracing. This feature has been behind a feature flag for several months and is now deemed stable enough to release.
The feature can be disabled with `-Ddd.trace.tracer.metrics.enabled=false` or `DS_TRACE_TRACER_METRICS_ENABLED=false`

enable tracer metrics

---

dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Config.groovy
dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/springdata/Config.groovy
dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringRepositoryTest.groovy
dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/client/VertxRxCircuitBreakerWebClientTest.groovy
dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/client/VertxRxWebClientTest.groovy
dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/client/VertxHttpClientTest.groovy

This shuts down vertx and elastic runtimes and thread pools so we don't keep ~100 threads hanging around. Hopefully this will help with the IBM tests throwing OOM.

Clean up some runtimes in tests

---

dd-java-agent/instrumentation/mongo/driver-3.1/src/main/java/datadog/trace/instrumentation/mongo/BsonScrubber.java
dd-java-agent/instrumentation/mongo/driver-3.1/src/main/java/datadog/trace/instrumentation/mongo/Context.java
dd-java-agent/instrumentation/mongo/driver-3.1/src/main/java/datadog/trace/instrumentation/mongo/MongoClientDecorator.java
dd-java-agent/instrumentation/mongo/driver-3.1/src/main/java/datadog/trace/instrumentation/mongo/MongoClientInstrumentation.java
dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/BsonScrubberTest.groovy
dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/MongoClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-4/src/main/java/datadog/trace/instrumentation/mongo4/BsonScrubber.java
dd-java-agent/instrumentation/mongo/driver-4/src/main/java/datadog/trace/instrumentation/mongo4/Context.java
dd-java-agent/instrumentation/mongo/driver-4/src/main/java/datadog/trace/instrumentation/mongo4/Mongo4ClientDecorator.java
dd-java-agent/instrumentation/mongo/driver-4/src/main/java/datadog/trace/instrumentation/mongo4/Mongo4ClientInstrumentation.java
dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/BsonScrubberTest.groovy
dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ReactiveClientTest.groovy
dd-java-agent/instrumentation/mongo/driver-async-3.3/src/main/java/datadog/trace/instrumentation/mongo/MongoAsyncClientInstrumentation.java
dd-java-agent/instrumentation/mongo/driver-async-3.3/src/test/groovy/MongoAsyncClientTest.groovy
dd-java-agent/instrumentation/mongo/src/test/groovy/MongoBaseTest.groovy

* Uses MongoDB's driver's ability to pipe a document reader through a writer. This implements a custom writer to give better control over obfuscation policy.
* Improves the obfuscation policy
* Include collection names for updates and deletes
* Include the database name
* Include whether the query was ordered or not, since this has a significant impact on query performance
* Include whether the query will yield an explain plan
* Exclude the contents of delete, insert, and update commands
* Exclude the contents of large sets, such as `$in` clauses and `$set`s used in upserts

Better mongo scrubbing

---

.github/workflows/draft-release-notes-on-tag.yaml
.github/workflows/increment-milestones-on-tag.yaml

This PR fixes the `draft release notes on tag` and `increment milestones on tag` github actions.  
`await` syntax and `then()` aren't mixable in the manner used in the file
**Submitter please read!**
NO are you making any modifications to a non thread-safe data structure in a method or an advice that might happen on multiple theads at the same time?

Fix milestone fetching in github actions

---

dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/ExcludedVersions.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java

The bug preventing usage of ScopeEvents introduced in 8u262 was fixed in 8u282.
As an additional change the error message printed when `ScopeEventFactory` is not available is enhanced by the exception message to make it easier to figure out the root cause for the factory being unavailable.
[no] are you making any modifications to a non thread-safe data structure in a method or an advice that might happen on multiple theads at the same time?

Update the OpenJDK 8 exclusion range.

---

dd-java-agent/instrumentation/junit-5.3/src/main/java8/datadog/trace/instrumentation/junit5/JUnit5Decorator.java
dd-java-agent/instrumentation/junit-5.3/src/main/java8/datadog/trace/instrumentation/junit5/TracingListener.java
dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestTemplate.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java

Add `test.parameters` tag to JUnit5 tests.

[CIAPP] Add test.parameters tag to JUnit5 tests

---

dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAnnotationsInstrumentation.java
dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceConfigInstrumentation.java
dd-java-agent/instrumentation/trace-annotation/src/test/groovy/ConfiguredTraceAnnotationsTest.groovy
dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceConfigTest.groovy

* Remove the class loader matcher from the trace annotation instrumentation since `@Trace` is always loaded by the bootstrap classloader, it never has any effect
* improve config parsing in trace annotation instrumentations

improvements in trace annotation instrumentation

---

.gitlab-ci.yml

This is the proper flow following publishing once all artifacts are uploaded.  Once it's closed it can be manually verified and released.
https://help.sonatype.com/repomanager2/staging-releases/managing-staging-repositories#ManagingStagingRepositories-ClosinganOpenRepository
Also extend the expiration window for the signing public key.

Try closing staging repo after publishing

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/OkHttpSink.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/Sink.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/FootprintTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/OkHttpSinkTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy

When an old agent is deployed with a new tracer, it takes a cycle of metrics publishing to figure out whether the agent supports metrics, which leads to queue build up and live locks the scheduler thread. This PR changes this behaviour so we check before enabling, and removes the live lock condition.

validate agent is capable of receiving metrics before enabling metrics aggregation

---

.dd-ci/ci-app-spec.json

This PR updates the feature tracking JSON with the following tags:
```
"git.commit.author.date",
"git.commit.author.email",
"git.commit.author.name",
"git.commit.committer.date",
"git.commit.committer.email",
"git.commit.committer.name",
"git.commit.message",
"os.architecture",
"os.platform",
"os.version",
"runtime.name",
"runtime.version",
"runtime.vendor"
```
This JSON updates the dynamic doc page to know which tags are supported by the tracer.

[CIAPP] Update feature tracking JSON

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java

#2549 was implemented hastily and should have included this change. Having excluded this change is benign, but this change prevents the attempts to report periodically.

cancel scheduled reporting task when metrics is disabled

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/LogContextScopeListener.java
dd-trace-api/src/main/java/datadog/trace/context/ScopeListener.java
dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/ScopeEventFactory.java
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ExtendedScopeListener.java
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
dd-trace-ot/src/test/groovy/datadog/opentracing/OpenTracingAPITest.groovy

Use a new interface (`ExtendedScopeListener`) rather than change the `ScopeListener` API

Create new interface instead of changing ScopeListener api

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/JDBCConnectionUrlParser.java
dd-java-agent/instrumentation/jdbc/jdbc.gradle
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractPreparedStatementInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DB2ConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DB2PreparedStatementInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DriverInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCConnectionUrlParserTest.groovy

This PR makes a few changes to the JDBC instrumentation
1. Caches connection URL parsing since some applications connect frequently, the parsing is quite slow, and connecting often takes a driver level lock. This should fix an issue for Apache Phoenix users where connection creation is more common than in applications using traditional connection pools.
2. Separates out and namespaces DB2 `Connection` and `PreparedStatement` instrumentations, which have expensive type matchers. This means that unless DB2 is being used, JDBC matching is about as cheap as it can get.
3. Add Redshift's `CallableStatement` implementation, which was missed in #2511

Address various JDBC instrumentation issues

---

.circleci/config.yml
.github/workflows/add-assets-to-release.yaml

Also download release artifacts from Sonatype rather than Maven Central as they're more immediately available there.

Update CircleCI config to not build on tags

---

dd-java-agent/instrumentation/mongo/driver-3.1/src/main/java/datadog/trace/instrumentation/mongo/ByteBufBsonDocumentInstrumentation.java
dd-java-agent/instrumentation/mongo/driver-3.1/src/main/java/datadog/trace/instrumentation/mongo/MongoClientDecorator.java
dd-java-agent/instrumentation/mongo/driver-3.1/src/main/java/datadog/trace/instrumentation/mongo/MongoClientInstrumentation.java
dd-java-agent/instrumentation/mongo/driver-3.1/src/main/java/datadog/trace/instrumentation/mongo/TracingCommandListener.java
dd-java-agent/instrumentation/mongo/driver-4/src/main/java/datadog/trace/instrumentation/mongo4/Mongo4ClientDecorator.java
dd-java-agent/instrumentation/mongo/driver-async-3.3/src/main/java/datadog/trace/instrumentation/mongo/MongoAsyncClientInstrumentation.java

Newer mongo driver versions allow more efficient reading of BSON documents. Unfortunately this isn't possible on older driver versions, so I added some instrumentation to extract the document's buffer and do the same thing manually.

avoid converting binary document to tree when possible on later mongo driver versions

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/OkHttpSink.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentFeaturesDiscovery.java
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/DDAgentFeaturesDiscoveryTest.groovy

There is a problem with the way trace agent 7.26.0 forwards metrics to the backend, this PR makes the minimal change to avoid sending metrics to trace agent 7.26.0. It does not attempt to refactor to make `DDAgentFeaturesDiscovery` available outside `DDAgentWriter`, which would be a nice thing to do in the future.

minimal change to avoid sending metrics to trace agent < 7.27.0

---

dd-java-agent/instrumentation/mongo/driver-4/driver-4.gradle

The newly released `4.3.0-beta1` version of the drivers fail on some of the tests.

Cap the latest Mongo 4 test version to 4.2.x

---

dd-smoke-tests/dd-smoke-tests.gradle
dd-smoke-tests/springboot-openliberty/snapshots/datadog.smoketest.SpringBootOpenLibertySnapshotTest.nested.snap
dd-smoke-tests/springboot-openliberty/snapshots/datadog.smoketest.SpringBootOpenLibertySnapshotTest.simple.snap
dd-smoke-tests/springboot-openliberty/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySmokeTest.groovy
dd-smoke-tests/springboot-openliberty/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySnapshotTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractTestAgentSmokeTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/ProcessManager.groovy

Added an extra abstract class for smoke tests to run a test agent the in background. This enables the testing of tags and other span info in smoketests through the comparison of snapshots (See `SpringBootOpenLibertySnapshotTest.groovy` for more details). Currently, this PR does not enable the test agent smoke tests to run on CI (will create another PR for that in the near future).

Added smoke test functionality to run a test agent in the background

---

dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy

This has two features:
1. Setting the tag `manual.keep:true` to keep a span is guaranteed to keep the local trace chunk, even if it has already propagated. Currently this is only guaranteed to work in a gateway process, which usually doesn't have enough context to keep traces. So if a user sets the tag early enough in manual instrumentation, they can keep large portions of traces despite sampling decisions made with less context upstream.
2. Changes the locking mechanism to use CAS ops, but changes the semantics slightly: setting the priority the first time to anything but `UNSET` effectively locks the sampling priority, and only `manual.keep:true` resulting in a call to`forceKeep()` can subsequently override it. If there are applications out there where our direct API is used to call …

enable bypassing of sampling priority lock to force keep local trace chunks, plus lock-free priority locking

---

dd-java-agent/instrumentation/hystrix-1.4/src/main/java/datadog/trace/instrumentation/hystrix/HystrixDecorator.java
dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableChainTest.groovy
dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableTest.groovy
dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixTest.groovy
dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixTestRunner.groovy
dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

Measured for hystrix spans stays off by default, but can be enabled by setting DD_HYSTRIX_MEASURED_ENABLED to true

setMeasured for hystrix spans by system property (off by default)

---

dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/FootprintTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SimpleSpan.groovy
internal-api/internal-api.gradle
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/util/CollectionUtils.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

This requirement was missed during analysis of the tracer metrics feature. This allows users to specify resources to skip via a config parameter.

allow exclusion of traces from metrics collection via a config property

---

dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractPreparedStatementInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java

It looks like we're using the wrong class names for Oracle JDBC drivers. This also adds supportability logging to help figure out when this happens. We need to add some Oracle specific testing since it is a popular database.

correct Oracle JDBC physical connection class names

---

dd-smoke-tests/profiling-integration-tests/profiling-integration-tests.gradle
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/ProfilingIntegrationTest.java
gradle/dependencies.gradle

An attempt to make the profiler smoke tests slightly more resilient to intermittent failures.
Unfortunately, there are still time dependencies when a particularly busy box can cause a profiler smoke test case fail.
Naively retrying of a failing test for several times seems to be helping (so far).
I tried using jupyter extensions as well as a gradle plugin for retriable tests but neither of them works nicely with the CI - and although the tests are re-run in case of a failure the failure is still reported and will fail the CI run.

Allow repeatable execution of flaky tests

---

dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/CouchbaseAsyncClientTest.groovy
dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AggregateMetricTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/FootprintTest.groovy

1. `AggregateMetricTest`: "consistent under concurrent attempts to read and write" - the reader fails to terminate every now and then because of the termination condition. 
2. `FootPrintTest`: The cause was that sometimes it can take a while for JOL to parse the object graph, leading to a timeout. The timeout is increased. Also previously only tested the size dominated by `aggregator.aggregator.aggregates`, which is brittle to refactoring, but now asserts about the relative increase (which allows for exclusion of things like classes and class loaders) in size dominated by the root class, which requires a larger threshold. 
3. `CouchbaseAsyncClientTest` - I believe this test fails because it is running in non-strict mode and is nondeterministic. I added instrumentation to disable async …

Various flaky test fixes

---

dd-trace-core/src/main/java/datadog/trace/common/metrics/OkHttpSink.java
dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentFeaturesDiscovery.java
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/FootprintTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/OkHttpSinkTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/DDAgentFeaturesDiscoveryTest.groovy
dd-trace-core/src/test/resources/agent-features/agent-info-with-client-dropping.json
dd-trace-core/src/test/resources/agent-features/agent-info.json
dd-trace-core/src/traceAgentTest/groovy/MetricsIntegrationTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/api/WellKnownTags.java
internal-api/src/test/groovy/datadog/trace/api/WellKnownTagsTest.groovy
utils/histograms/src/main/java/datadog/trace/core/histogram/DDSketchHistogram.java

* Add fields to uniquely identify payloads
* Target v0.6/stats endpoint as v0.5/stats has been retired
* Adjust relative accuracy to match format used elsewhere

metrics updates

---

dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java
dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/ProfilingIntegrationTest.java

The upload task is executed at fixed interval and due to thread scheduling the next interval can elapse shortly after the previous task has been finished. Perhaps, it would be more correct to have `scheduleWithFixedDelay` functionality in the `AgentTaskScheduler` but since we have been seeing this kind of failure only in CI so far we might get away with just not being so strict in expectations.
The retry logic was leaving orphaned target processes behind.

Reduce the number of intermittent failures

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/ProfilingIntegrationTest.java

I found this in a profile, apparently when you don't set the content length, you get a `NumberFormatException`

avoid exception during classloading

---

dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/ScopeEvent.java
dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/ScopeEventFactory.java

Calls to `getCurrentThreadCpuTime()` add up especially when there are a lot of scopes created. With this PR, there are at most 2 calls per `ScopeEvent` instead of a call at every pause and resume.
The simple case of a scope with two child scopes:
Activate Scope A
Activate Scope B
Finish Scope B
Activate Scope C
Finish Scope C
Finish Scope A
Goes from 10 calls down to 6.

Rearchitect ScopeEvents to reduce cputime calls

---

dd-trace-core/src/main/java/datadog/trace/common/writer/PrintingWriter.java
dd-trace-core/src/test/groovy/datadog/trace/api/writer/PrintingWriterTest.groovy

The JSON for traces and metrics on AWS Lambda are sometimes logged on the same line, leading to invalid JSON.

Force new line in PrintingWriter

---

utils/container-utils/src/test/groovy/ContainerInfoTest.groovy

Python recently had an issue with container ID parsing in https://github.com/DataDog/dd-trace-py/issues/2314. This adds the problematic format to our test suite to ensure we are not affected

Test for parsing ContainerID from another cgroups file format

---

.github/workflows/add-assets-to-release.yaml

This will enable the following URL to point to the latest version:
https://github.com/datadog/dd-trace-java/releases/latest/download/dd-java-agent.jar

Also upload javaagent to release without version

---

gradle/dependencies.gradle

This has some changes to flatten nested conjunction and disjunction matchers which will limit call stack depth for us.

upgrade bytebuddy

---

internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/EnvironmentConfigSource.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/PropertiesConfigSource.java
internal-api/src/main/java/datadog/trace/bootstrap/config/provider/SystemPropertiesConfigSource.java
internal-api/src/main/java/datadog/trace/util/Strings.java
internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy

I saw `String.format` and `Pattern` construction show up in premain in benchmarks which load thousands of classes and run for nearly 10 seconds, so this PR replaces them with manual alternatives.

premain low hanging fruit

---

dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/ScopeEvent.java
dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ScopeEventTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
internal-api/src/main/java/datadog/trace/api/Config.java

This change adds a configuration flag for enabling the code hotspots support in the agent.
By default this support is disabled due to possible performance  overhead it may incur.
When code hotspots support is disabled the whole scope event machinery is detached from the tracer and no residual overhead is present

Introduce configuration guard for scope events (code hotspots)

---

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/AgentStatsdReporter.java
dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDClient.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDConnection.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/LoggingStatsDClient.java
internal-api/src/main/java/datadog/trace/api/NoOpStatsDClient.java
internal-api/src/main/java/datadog/trace/api/StatsDClient.java

https://github.com/DataDog/jmxfetch/releases
JMXFetch 0.40.1 added tracking of client errors - this PR adds support for this with the shared StatsD connection.

Upgrade jmxfetch to 0.43.0

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/DDElementMatchers.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/FailSafe.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/NameMatchers.java

This bypasses a lot of setup, reduces the depth of the stack, and avoids calling no-op classloader/module matchers.

evaluate simple name based matching as RawMatcher

---

dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/GrpcClientBuilderInstrumentation.java
dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcServerBuilderInstrumentation.java
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/HierarchyMatcherGrpcStreamingTest.groovy
dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/HierarchyMatcherGrpcTest.groovy

The gRPC instrumentation will now only activate with a predefined set of `ServerBuilder` and `ManagedChannelBuilder`s. This can be disabled by setting `-Ddd.integration.grpc.matching.shortcut.enabled=false`

add shortcut matchers for gRPC

---

dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/ScopeEventFactory.java

This is a quick remedy for `NoSuchElementException` thrown from the `ScopeEventFactory`.
There still is the question of what happens to spans activated before the listener is added - currently, they will just disappear. This is rather sub-optimal but the correct solution will require more work - the stack tracking listener would need to be separated from the scope event factory so it can be added early in the startup without clashing with the JFR init prerequisites.
I would defer that work for the time when we are revisiting the tracer/profiler integration related to span activation.

Guard against NoSuchElementException

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/DatadogClassLoader.java
dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java
dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/InternalJarURLHandlerTest.groovy

The jar file is currently split in to 4 parts `shared`, `inst`, `metrics`, and `profiling`, one for each isolated class loader. When we load each class loader, we scan the entire jar file looking for packages below the prefix for the class loader, but we can do this all in one go by creating an "index". The sharing of the index isn't the prettiest, but this happens very early in the program so I want to keep it as simple and lean as possible.

unpack packages in internal jar file once

---

dd-java-agent/instrumentation/vertx-mysql-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_sql_client/CursorReadAdvice.java
dd-java-agent/instrumentation/vertx-mysql-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_sql_client/QueryAdvice.java
dd-java-agent/instrumentation/vertx-mysql-client-3.9/src/main/java8/datadog/trace/instrumentation/vertx_sql_client/QueryResultHandlerWrapper.java
dd-java-agent/instrumentation/vertx-mysql-client-3.9/src/test/groovy/VertxSqlClientForkedTest.groovy

The `handler` spans were incorrectly reported as a child of the `client` span instead of the span where the request originated.

Change Vert.x 3.9 MySQLClient spans to not enclose the handler

---

dd-smoke-tests/spring-boot-2.5-webflux/src/test/groovy/datadog/smoketest/SpringBootWebfluxIntegrationTest.groovy

Since WebFlux has problems with strict writing, there is a possibility that the response is received, checked, and the traces read and checked before the actual trace is written and flushed.

Make SpringBootWebfluxIntegrationTest wait for traces before checking

---

.circleci/config.yml
dd-smoke-tests/dd-smoke-tests.gradle
dd-smoke-tests/springboot-openliberty/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySnapshotTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractTestAgentSmokeTest.groovy
dd-smoke-tests/src/main/groovy/datadog/smoketest/ProcessManager.groovy

Changed the test agent from running in a test container to running as a process on the local machine. This avoids the process of setting up a separate test agent container in CI.

Change smoke test to run snapshots in CI

---

dd-smoke-tests/spring-boot-2.4-webflux/src/test/groovy/datadog/smoketest/SpringBootWebfluxIntegrationTest.groovy

Yes, there is another one #2649

Make SpringBootWebfluxIntegrationTest 2.4 wait for traces as well before checking

---

dd-java-agent/instrumentation/jboss-logmanager/src/main/java/datadog/trace/instrumentation/jbosslogmanager/ExtLogRecordInstrumentation.java
dd-java-agent/instrumentation/log4j-2.7/src/main/java/datadog/trace/instrumentation/log4j27/SpanDecoratingContextDataInjector.java
dd-java-agent/instrumentation/log4j1/src/main/java/datadog/trace/instrumentation/log4j1/LoggingEventInstrumentation.java
dd-java-agent/instrumentation/logback-1/src/main/java/datadog/trace/instrumentation/logback/LoggingEventInstrumentation.java
dd-smoke-tests/log-injection/src/test/groovy/datadog/smoketest/LogInjectionSmokeTest.groovy

Setting empty values for `dd.env` or `dd.version` in logs can interfere with tags set by the Datadog agent. See #2653

Don't inject empty tags in logging MDC

---

dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
dd-trace-api/src/main/java/datadog/trace/api/config/JmxFetchConfig.java
internal-api/src/main/java/datadog/trace/api/Config.java

A new feature has been added to jmxfetch allowing to have a configurable period for the 1st bean refresh (for more details, please refer to the related PR https://github.com/DataDog/jmxfetch/pull/349), the goal of this PR is to propagate the required changes to benefit from this new feature in the Java Agent
* Adds a system property  `jmxfetch.initial-refresh-beans-period` to be able to set the value
* Provides the value of this property to the configuration of jmxfetch
It is now possible to easily set a period for the 1st bean refresh from the Java Agent thanks to a System property

Expose jmxfetch "initial refresh beans period" config.

---

dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkOngoingRecording.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkOngoingRecordingTest.java
dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/JfrMBeanHelper.java
dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkOngoingRecording.java
dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkRecordingData.java
dd-java-agent/agent-profiling/profiling-controller-oracle/src/test/java/com/datadog/profiling/controller/oracle/OracleJdkControllerTest.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/OngoingRecording.java
dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java
dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ProfilingSystemTest.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/ProfilingIntegrationTest.java

The changes in #2587 shortened the diff between the `end` time in the `RecordingData` from the `snapshot` call and the next `start` time in the following `snapshot` call. Since the filtering of the `RecordingInputStream` that happens inside the JFR code will include chunks that started but didn't finish before `start`, and chunks that started but didn't finish before `end`, we could get some of the same chunks in consecutive snapshots that would lead to double counting.
This change tries to minimize the risk of getting the same chunks by using the actual time from the underlying `snapshot` recording as the `end` time of the `RecordingData` and add a small offset as the next `start` time.
Since the other change has not been released, there should not be a release note for this.

Try to avoid duplicate profiling data

---

buildSrc/src/main/groovy/MuzzlePlugin.groovy
dd-java-agent/instrumentation/play-2.3/play-2.3.gradle
gradle/repositories.gradle

And change play version we compile against to earliest version in maven central.
(Typesafe repo is not working right now and this seems like the easiest way to unblock.)

Remove Typesafe Repo

---

dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle

https://github.com/DataDog/jmxfetch/releases/tag/0.43.1
Includes a bugfix:
* Service tag should not be excluded if specified

Update jmxfetch to 0.43.1

---

dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/AvailableProcessorCoresEvent.java
dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/AvailableProcessorsEvent.java
dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/ProfilingIntegrationTest.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/ScopeEventFactory.java
dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ScopeEventTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

JFR reports the total number of processor - not taking into account any restrictions put by the container.
However, the CPU time heuristics in profiler backend needs convert the CPU load which is calculated using the number of available cores rather than the total number of cores. Therefore we need this information captured in an extra JFR event.

Add a JFR event to report available processors

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVisitor.java
dd-java-agent/instrumentation/rxjava-2/src/main/java/datadog/trace/instrumentation/rxjava2/ObservableInstrumentation.java

This mainly reduces the number of maps that need to be constructed and avoids the risk of sizing incorrectly.
This is just a preliminary step.  The stated benefits won't apply until subclasses have migrated.

Invert control when defining transformers

---

dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/RuleFlags.java
dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
internal-api/src/main/java/datadog/trace/api/Config.java

Can be reenabled: `-Ddd.trace.PeerServiceTagInterceptor.enabled=true`

Disable PeerServiceTagInterceptor by default

---

dd-java-agent/instrumentation/jsp-2.3/src/main/java/datadog/trace/instrumentation/jsp/JSPDecorator.java

The tag is not critical enough to warrant logging at `warn` level.

Reduce jsp exception log level to avoid risk of log spam

---

dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaActorCellInstrumentation.java
dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaMailboxInstrumentation.java

This change tries to minimize the work done when there is no span travelling across an akka message send.
Here are some numbers for an akka message sending benchmark that don't have any spans active.
|Version  | Average time (s) | stdev | overhead %|
|---------|------------------|-------|-----------|
|none     |            1.676 | 0.132 |      0.000|
|0.75.0   |            4.163 | 0.588 |    148.426|
|0.76.0   |            4.675 | 0.845 |    178.973|
|0.76.1   |            4.051 | 0.473 |    141.741|
|0.77.0   |           11.723 | 3.888 |    599.550|
|0.78.1   |            9.756 | 3.390 |    482.148|
|0.78.2   |            7.253 | 0.811 |    332.792|
|0.78.3   |            4.276 | 0.364 |    155.163|
|0.79.0   |            4.147 | 0.381 |    147.496|
|this PR |            1.980 | 0.218 | …

Don't create noop scopes for akka messaging unless necessary

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/CheckpointEvent.java
dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java
dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ScopeEventTest.groovy
dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTestBase.groovy
dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
internal-api/src/main/java/datadog/trace/api/Checkpointer.java
internal-api/src/main/java/datadog/trace/api/Config.java
internal-api/src/main/java/datadog/trace/api/SamplingCheckpointer.java
internal-api/src/main/java/datadog/trace/api/SpanCheckpointer.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
internal-api/src/test/groovy/datadog/trace/api/SamplingCheckpointerTest.groovy

Captures span start, finish and thread migration, allows instrumentation to trigger recording of CPU intensive work.
Mutually exclusive with scope events. Activated by `-Ddd.profiling.legacy.tracing.integration=false` (which disables scope events).

implement checkpoint API for profiler integration

---

dd-java-agent/instrumentation/jdbc/jdbc.gradle
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractConnectionInstrumentation.java
dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractPreparedStatementInstrumentation.java

In postgres jdbc 9.4-1201-jdbc41, `org.postgresql.jdbc4.Jdbc4Connection` implements `PreparedStatement` in an indirect way - it inherits the methods of the same name as `PreparedStatement` from `org.postgresql.jdbc2.AbstractJdbc2Statement` which does not implement `PreparedStatement`. So we correctly match `org.postgresql.jdbc4.Jdbc4Connection`  but it has no methods we can transform, and we cannot apply the advice to `org.postgresql.jdbc2.AbstractJdbc2Statement` because it doesn't implement `PreparedStatement`.
This relaxes the supertype requirement to `Statement`, and adds a test for an old postgres library. In the future I will refactor the tests to add a test directory per database, and test set per version worth testing to reduce the cost of testing multiple driver versions.

add test + fix for old postgres driver

---

dd-java-agent/agent-profiling/profiling-uploader/profiling-uploader.gradle
dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/CompressingRequestBody.java

We are adding ~500kB of JMC core libraries worth just for one call.
It feels much better to copy-paste those 6 lines and get rid off 500kB library.

Remove jmc core library to save 500kB

---

dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/CheckpointEvent.java
dd-trace-core/src/main/java/datadog/trace/core/util/JmxSystemAccessProvider.java
dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccess.java
internal-api/src/main/java/datadog/trace/api/Checkpointer.java

* Stricter meaning of `CPU` in checkpoint events - it now means "record CPU time" in memory and means "CPU time was recorded" to the backend
* Don't initialise the `JmxSystemAccessProvider` class when loading it
* Make `JmxSystemAccessProvider`'s state static as it's a singleton and this leads to the elimination of the enabled check
* Return zero when CPU time can't be recorded since it can be varint encoded in 1 byte instead of 10.

CPU time improvements

---

buildSrc/src/main/groovy/MuzzlePlugin.groovy
dd-java-agent/dd-java-agent.gradle
dd-java-agent/instrumentation/instrumentation.gradle

With `org.gradle.configureondemand=true` in gradle.properties, some
subprojects (incl. all the instrumentation subprojects) were not
evaluated unless some task is requested from them in the same gradle
invocation. This results in a bogus shadow jar, which is missing  most
of the files.

Fix :dd-java-agent:shadowJar build with config on demand

---

dd-java-agent/instrumentation/jdbc/jdbc.gradle

As noted by @tylerbenson in #2694 `gradle` needs to force override the version of the old postgres driver.

Force the old version of postgres and run the tests

---

dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDConnection.java

This reduces log-spam when there are lots of client errors at the same time (eg. due to a misconfigured UnixDomainSocket)

Use IoLogger to log StatsD client errors

---

dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java

There have been various mitigations which improve clojure performance since these were added
* Field injection fixes (these won't fall back to weak maps any more)
* Callable instrumentation was removed
This PR does not regress on the simple clojure startup benchmark used to justify the change in the first place. We still ignore the clojure standard library.

remove clojure class patterns from GlobalIgnoresMatcher

---

.circleci/config.yml

As noted by @tylerbenson CircleCI uses prefix matching for the cache keys. This PR removes the complicated checksum and double saving scheme and instead only use the prefix matching.

Only save CircleCI cache once and use key prefix matching

---

.circleci/config.yml
dd-java-agent/instrumentation/instrumentation.gradle
dd-java-agent/instrumentation/mule-4/mule-4.gradle
dd-smoke-tests/dd-smoke-tests.gradle
dd-smoke-tests/play-2.4/play-2.4.gradle
dd-smoke-tests/play-2.5/play-2.5.gradle
dd-smoke-tests/play-2.6/play-2.6.gradle
dd-smoke-tests/play-2.7/play-2.7.gradle
dd-smoke-tests/play-2.8/play-2.8.gradle
dd-smoke-tests/quarkus/quarkus.gradle
dd-smoke-tests/springboot-openliberty/springboot-openliberty.gradle
dd-trace-java.gradle

This also runs smoke tests separately on a smaller instance because we force them to run serially, so it doesn't make sense tying up a big resource waiting for that.
For reference: https://circleci.com/docs/2.0/configuration-reference/#resourceclass

Optimize circleci resource_class and run instrumentation tests as a separate task

---

gradle/spotless.gradle

This makes the `check` task pass again. For some reason the changed configuration ran `spotlessXml` without excluding the `build` directories.

Revert check configuration of spotless dependency

---

dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java

Since https://github.com/DataDog/dd-trace-java/pull/2705 the only direct use of JMX in the tracer involves JMXFetch (MBean reporting) and profiling's support for ScopeEvents (CPU timing) - therefore when both of these features are off we can avoid JMX access which should help users of frameworks where early JMX access can disturb startup.

Avoid JMX access during boot when JMXFetch and Profiling are both disabled

---

dd-java-agent/agent-tooling/agent-tooling.gradle
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentTooling.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDClassFileTransformer.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDRediscoveryStrategy.java
dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
dd-java-agent/agent-tooling/src/main/java11/datadog/trace/agent/tooling/bytebuddy/DDJava9ClassFileTransformer.java

This PR decorates ByteBuddy's class transformers so we can do some preliminary filtering of class load events before entering ByteBuddy. It also introduces a custom strategy for discovering classes that we missed while installing the actual agent and now need to re-transform.
Most of the complexity here is to handle different `ClassFileTransformer` decorators for Java8 vs Java9 and above, which introduced a new callback for classes loaded from the modulepath. The default implementation of this new callback calls the non-module method, but this drops the module information breaking ByteBuddy's support for patching modules so key types are visible. We need to have a Java9 specific `ClassFileTransformer` that delegates each `transform` method to its equivalent in ByteBuddy.

Early filtering of transformation and re-transformation requests

---

gradle/spotless.gradle

Spurious CI failures on this form keeps happening in the `check` job:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':spotlessXml'.
...
Caused by: org.gradle.api.UncheckedIOException: Unable to store input properties for task ':spotlessXml'. Property 'lineEndingsPolicy' with value 'com.diffplug.spotless.extra.GitAttributesLineEndings$RelocatablePolicy@16138' cannot be serialized.
...
Caused by: org.gradle.api.GradleException: Could not read path '/home/circleci/dd-trace-java/workspace/dd-java-agent/build/resources/main/shared/jnr/ffi/util'
...
```

Remove spotlessXml since it keeps processing build artifacts
