- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot31.java
Rewrite the algorithm for hoisting local vars:
Go through all local vars defined in the method and determine by name all local var that are hoistable.
local vars are hoistable if there is no conflict by slot or by name with another.
If conflict by slot and same name we cancel hoisting for this name. if
name is different we allocating a new slot for one of the local.
If conflict by name and type are not compatible we cancel hoisting for this name. If type compatible, we can add in hoistable list. Then we are considering all hoistable variables by name and if there are multiple occurrence for a name, we are merging those variables in a new slot and rewrite var instructions to use this new slot. if only one variable we just assign a new slot and rewrite the instructions in the range.
Fixing …
> Fix local var hoisting

- .circleci/config.continue.yml.j2
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
See [Circle CI's price list](https://circleci.com/pricing/price-list/). Linux VM / (x86) Remote Docker's xlarge has 8 CPUs for 100 credits/min (12.5 credits per CPU/min), large has 4 CPUs for 20 credits/min (5 credits per CPU/min). So:
* Change instrumentation test jobs from `xlarge` to `large` resource class.
* Increase parallelism from 4 to 12 (still cheaper job/minute).
* Set workers to 3. This is a higher worker per CPU ratio than before, leading to better resource utilization, but also more flaky tests being triggered because of high load. I'm opening separate PRs to fix flaky tests resulting from this change:
* https://github.com/DataDog/dd-trace-java/pull/7598
* https://github.com/DataDog/dd-trace-java/pull/7551
* https://github.com/DataDog/dd-trace-java/pull/7550
* …
> Adjust CircleCI resource classes

- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScope.java
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
Prevents from clearing the profiling context when a duplicate scope (reference count > 1) is closed, leaving all samples for the ancestor scopes unlabeled.
Jira ticket: [PROF-10567]
> delay closing profiling state when scope reference count > 1

- dd-trace-api/src/main/java/datadog/trace/api/config/CiVisibilityConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Updates the name of the environment variable that is used for setting test session name.
Being consistent across different tracers.
Jira ticket: [SDTEST-784](https://datadoghq.atlassian.net/browse/SDTEST-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
[SDTEST-784]: https://datadoghq.atlassian.net/browse/SDTEST-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update test session environment variable name

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/JarScanner.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/JarScannerTest.java
Spring boot use a special jar organisation for nested ones. It uses a new jar protocol for URL: `jar:nested:`
Jira ticket: [DEBUG-2852]
[DEBUG-2852]: https://datadoghq.atlassian.net/browse/DEBUG-2852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add support of spring boot nested jar for SymDB

- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/MessagesAvailableInstrumentation.java
Makes it possible to disable the gRPC message spans with `-Ddd.integration.grpc-message.enabled=false`
> make it possible to disable gRPC message spans

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiHelper.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiSnapshotHelper.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
- dd-java-agent/agent-debugger/src/test/resources/test_log_probe.json
Watches collect specific (deep) fields to add them exclusively into
the snapshot instead of locals/arguments/statics/...
Watches are defined using probe definition predefined tags:
- `dd_watches_dsl`
- `dd_watches_json`
When you just want to reference deep fields just `a.b.c` you can use the
dsl syntax (like Expression Language). But if you need more advanced
(accessing map or list, using filter, any, ... functions) you need to
use `dd_watches_json` and put the Json AST for Expression Language
(like log message template with segments).
Once the probe is executed, it interprets watches tags to evaluate the
expression then add it in the snapshot as special attributes `watches`.
Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the …
> Add watches support through probe tags

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ExceptionDebuggerIntegrationTest.java
Make sure Exception Replay can be started up without DI. Remote Config subscription is not started if DI is not enabled now. The debugger agent is initialized if either Dynamic Instrumentation or
Exception Replay is enabled
Jira ticket: [DEBUG-2735]
[DEBUG-2735]: https://datadoghq.atlassian.net/browse/DEBUG-2735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Refactor DI startup to make Exception Replay can be started up alone

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerConfig.java
It does fix the incorrect check for the experimental JVMTI wallclock sampler enablement in #7641
> Allow enabling experimental JVMTI wallclock sampler (take 2)

- dd-java-agent/instrumentation/mongo/driver-3.1-core-test/src/test/groovy/MongoCore31ClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/MongoJava31ClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-3.10-sync-test/src/test/groovy/MongoSyncClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-3.3-async-test/src/test/groovy/MongoAsyncClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-3.4/src/test/groovy/MongoJava34ClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-3.7-core-test/src/test/groovy/MongoCore37ClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/Mongo4ClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/MongoReactiveClientTest.groovy
Avoid unstable test names, such as `test create collection [collectionName: testCollection-806d900f-caae-483d-ad69-df899f2169bc, renameService: false, #0]`. These prevent flakiness detection.
> Stable test names in Mongo instrumentation tests

- dd-java-agent/appsec/build.gradle
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
Updates libsqreen library to 11.0.1 that includes a fix handling derivatives from the WAF.
Schema derivatives are gziped and encoded in base64, meanwhile fingerprints should be sent as clear text. 
Jira ticket: [APPSEC-54547]
[APPSEC-54547]: https://datadoghq.atlassian.net/browse/APPSEC-54547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update libsqreen library to 11.0.1 fixing fingerprint generation

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/WellKnownClasses.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
Since jdk 17 it's not possible to do deep reflection. The content of File or Path instances are difficult to see content with deep reflection, though the meaningful value is the toString representation We are adding File and Path instances serialized as string primitive and evaluated in EL as String as well
Jira ticket: [DEBUG-2853]
[DEBUG-2853]: https://datadoghq.atlassian.net/browse/DEBUG-2853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add File and Path as string primitive

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/LogProbeTest.java
evaluation error snapshots were sent even if rate limited now we are checking sampled state before sending
Jira ticket: [DEBUG-2892]
[DEBUG-2892]: https://datadoghq.atlassian.net/browse/DEBUG-2892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix evaluation errors sampling

- dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDLoggerFactory.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Enable telemetry logs by default. These were already enabled by default for services using JDK 8, Code Security (IAST), Dynamic Instrumentation, or CI Visibility. They will be enabled for all services from now on.
Users who want to opt out can set `-Ddd.telemetry.log-collection.enabled=false` (system property) or `DD_TELEMETRY_LOG_COLLECTION_ENABLED=false` (environment variable).
Note that these are not application logs, but internal dd-trace-java logs which we use for troubleshooting. They are heavily redacted by sending only the log formats and not log parameters (e.g. when we do `log.error("An error happened at url: {}", url)`), we will send just `"An error happened at url: {}"`, without any placeholder substitution. We also send error stacktraces, including exception type (but not …
> Enable telemetry logs by default

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
For log message `WAF object had not been closed (probably missed request-end event)`:
* Reduce log level to debug.
* Send it to telemetry logs.
These rarely happen, but when they happen, they tend to happen frequently. The insistent logging becomes a problem in itself, and the error is not directly actionable by our customers. Hence the debug level. However, this indicates a bug in the tracer, so we'll force it to telemetry logs (if telemetry logs are enabled) so that we still have info on any regression.
Jira …
> Reduce log level for "WAF object had not been closed"

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
(cherry picked from commit 7f040c5f8265393160743537d06b3f13cc52e72b)
(#7657)
> [🍒 7657] Reduce log level for "WAF object had not been closed"

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/LogProbeTest.java
set the message in snapshot with the content of the first evaluation errors
Jira ticket: [DEBUG-2704]
[DEBUG-2704]: https://datadoghq.atlassian.net/browse/DEBUG-2704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix message for snapshots with evaluation errors

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- `DD_EXCEPTION_REPLAY_CAPTURE_MAX_FRAMES` alias on`DD_EXCEPTION_REPLAY_MAX_FRAMES_TO_CAPTURE`
- `DD_EXCEPTION_REPLAY_CAPTURE_INTERVAL_SECONDS` interval in seconds between 2 capture of the same exceptions
- `DD_EXCEPTION_REPLAY_CAPTURE_INTERMEDIATE_SPANS_ENABLED` inverted alias on `DD_EXCEPTION_REPLAY_ONLY_LOCAL_ROOT`
Jira ticket: [DEBUG-2882]
[DEBUG-2882]: https://datadoghq.atlassian.net/browse/DEBUG-2882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Exception Replay config parameters

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/JarScanner.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/JarScannerTest.java
This is a cherry-pick of #7635 
Spring boot use a special jar organisation for nested ones. It uses a new jar protocol for URL: jar:nested:
> [🍒 7635] Add support of spring boot nested jar for SymDB

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/decorator/TestDecoratorImpl.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/decorator/TestDecoratorImplTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
Adds new `_dd.host.vcpu_count` tag with the count of available CPUs to all Test Visibility events: tests, suites, modules, sessions.
This is needed by Datadog backend for evaluating CI costs.
Jira ticket: [SDTEST-867]
[SDTEST-867]: https://datadoghq.atlassian.net/browse/SDTEST-867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add CPU count tag to Test Visibility events

- dd-java-agent/instrumentation/rxjava-1/src/main/java/datadog/trace/instrumentation/rxjava/TracedOnSubscribe.java
Avoid capturing continuations on observables but carry spans instead for the parentship. 
Using continuations might be not correct here since they can be captured more than once 
> Improve context propagation for rxjava1 observables

- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/LogProbeTest.java
rate limiting when evaluating probe can be triggered because of the previous test speed. need o force the sampling anyway make the test passes as expected
test flakiness
> Fix flaky log probe tests

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Instrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java
When hoisting local variables remove the locals that could be have the
same name than arguments.
This could happen resulting of the instrumentation by the tracer that reshuffle the local variable table and then reassign dedicated slots to those arguments
Jira ticket: [DEBUG-2901]
[DEBUG-2601]: https://datadoghq.atlassian.net/browse/DEBUG-2601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEBUG-2901]: https://datadoghq.atlassian.net/browse/DEBUG-2901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix duplicated locals with arguments

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterModule.java
- dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/StringBuilderCallSiteTest.groovy
- dd-java-agent/instrumentation/owasp-esapi-2/src/test/groovy/datadog/trace/instrumentation/owasp/esapi/EncoderCallSiteTest.groovy
- dd-java-agent/instrumentation/tomcat-appsec-7/src/test/groovy/datadog/trace/instrumentation/tomcat7/ErrorReportValueInstrumentationForkedTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/SpockRunner.java
- dd-java-agent/testing/src/test/groovy/TooManyInvocationsErrorListenerTest.groovy
- internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
Fixes tests failures when a `org.spockframework.mock.TooManyInvocationsError` triggers a `java.lang.StackOverflowError` while composing the failure message.
When a mocked class captures the assertion error (e.g. TooManyInvocationsError), spock will throw an StackOverflowError while building the accepted invocations failure message, it causes the test to be ignored and won't be reported as a failure. As an example:
Before (warning message and test ignored):
```
Sep 24, 2024 11:35:27 AM org.junit.platform.launcher.core.CompositeTestExecutionListener lambda$notifyEach$19
WARNING: TestExecutionListener [org.junit.platform.runner.JUnitPlatformRunnerListener] threw exception for method: executionFinished(TestIdentifier [uniqueId = [engine:spock]/[spec:datadog.trace.instrumentation.java.lang.Stri …
```
> Fix stack overflow in spock making junit ignore test failures

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
- dd-smoke-tests/appsec/springboot/src/main/java/datadog/smoketest/appsec/springboot/AsyncConfig.java
- dd-smoke-tests/appsec/springboot/src/main/java/datadog/smoketest/appsec/springboot/MyAsyncService.java
- dd-smoke-tests/appsec/springboot/src/main/java/datadog/smoketest/appsec/springboot/controller/WebController.java
- dd-smoke-tests/appsec/springboot/src/main/java/datadog/smoketest/appsec/springboot/service/AsyncService.java
- gradle/spotbugFilters/exclude.xml
Added extra checks to prevent occurring exceptions, in case the WAF context was closed earlier during the race condition.
Reported exception from customers' service
```
io.sqreen.powerwaf.exception.UnclassifiedPowerwafException: Error calling WAF
io.sqreen.powerwaf.exception.UnclassifiedPowerwafException
at (redacted: 2 frames)
at com.datadog.appsec.powerwaf.PowerWAFModule.runPowerwafTransient(PowerWAFModule.java:634)
at com.datadog.appsec.powerwaf.PowerWAFModule.access$700(PowerWAFModule.java:74)
at com.datadog.appsec.powerwaf.PowerWAFModule$PowerWAFDataCallback.doRunPowerwaf(PowerWAFModule.java:617)
at com.datadog.appsec.powerwaf.PowerWAFModule$PowerWAFDataCallback.onDataAvailable(PowerWAFModule.java:439)
at com.datadog.appsec.event.EventDispatcher.publishDataEvent(EventDispatcher.java:1 …
```
> Fixed closing WAF context

- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/origin/CodeOriginTest.java
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
unify that definition to one constant instead of two
Updates the flag name to enable code origin for spans to bring it in the alignment with the [RFC](https://docs.google.com/document/d/1lhaEgBGIb9LATLsXxuKDesx4BCYixOcOzFnr4qTTemw)
Jira ticket: [DEBUG-2728]
[DEBUG-2728]: https://datadoghq.atlassian.net/browse/DEBUG-2728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update the config parameter name to enable code origin

- dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/parsers/HotspotCrashLogParser.java
- dd-java-agent/agent-crashtracking/src/test/java/com/datadog/crashtracking/parsers/HotspotCrashLogParserTest.java
This PR fixes the date time parser from the crashtracking log parser to support:
* Single digit day of month
* Both offset and timezone date times
It also adds some unit tests that cover this change to quickly test for new values. 
The Summary section uses time format with space padding for days of the month while our parser uses zero padded number (`dd`, [reference](https://docs.oracle.com/en/java/javase/23/docs/api/java.base/java/time/format/DateTimeFormatter.html#:~:text=Number%3A%20If%20the%20count%20of%20letters%20is%20one%2C%20then%20the%20value%20is%20output%20using%20the%20minimum%20number%20of%20digits%20and%20without%20padding.%20Otherwise%2C%20the%20count%20of%20digits%20is%20used%20as%20the%20width%20of%20the%20output%20field%2C%20with%20the%20value%20zero%2Dpadded%20as%20neces …
> Fix crashtracking log parser

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
- dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/SpringBootBasedTest.groovy
Avoid publishing the same `usr.id` to the WAF more than once in a request.
Calls to the WAF are expensive due to the switch between java and native code, this PR should reduce the number of jumps.
> Prevent publishing the same usr.id to the WAF twice

- dd-java-agent/instrumentation/java-concurrent/src/test/groovy/executor/ContextLeakTest.groovy
I'm investigating a case where a trace appears to have leaked into an idle thread pool executor. This test doesn't reproduce the behaviour, but seems useful to prevent it from ever regressing.
> add test to verify trace does not propagate when TPE is instantiated

- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_junit_platform_runner/pom.xml
> Fix 'Failed to parse plugin descriptor' error in Maven smoke tests

- tooling/backport-pr-to-patch-release.sh
This PR introduces a script to backport pull request to patch release branch.
The script takes care of:
* The patch release branch exists
* The PR to backport exists
* The tools needed (`gh` and `jq`) are installed
* There is no local change to your git working copy
It will then:
* Starts a branch from the release branch
*  Find the PR commit, title, and tags
* Cherry pick the PR merge commit
* Push the backport branch and create a new PR with copied tittle and tags.
And it finally restore your original git branch.
This should fasten backporting PRs and issuing patch release.
Here is a demo:
```shell
$ tooling/backport-pr-to-patch-release.sh v1.40.x 7697
- Checking gh is installed
- Checking jq is installed
- Checking there is no local changes
- Checking remote release branch exists
- …
```
> Add backport script

- dd-java-agent/instrumentation/armeria-grpc/src/main/java/datadog/trace/instrumentation/armeria/grpc/client/ClientCallImplInstrumentation.java
- dd-java-agent/instrumentation/armeria-grpc/src/test/groovy/ArmeriaGrpcStreamingTest.groovy
- dd-java-agent/instrumentation/armeria-grpc/src/test/groovy/ArmeriaGrpcTest.groovy
- dd-java-agent/instrumentation/google-pubsub/src/test/groovy/PubSubTest.groovy
- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/MessagesAvailableInstrumentation.java
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
- dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcAsyncAnnotationTest.groovy
- dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcAsyncConcurrentTest.groovy
- dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcCompletableFutureTest.groovy
Disable `grpc.message` span generated by `grpc-client` (not server) by default. Those spans may add noise to the traces hence we are turning them off.
This will apply for both google grpc client and armeria grpc client.
However they can be enabled back by explicitly:
* Set the system property `-Ddd.integration.grpc-message.enabled=true`
* Set the env var `DD_INTEGRATION_GRPC_MESSAGE_ENABLED=true`
> Disable grpc client message span by default

- .gitlab-ci.yml
- .gitlab/prepare-oci-package.sh
- metadata/base-requirements.json
- metadata/build-requirements.sh
- metadata/denied-arguments.tsv
- metadata/denied-environment-variables.tsv
- metadata/requirements-allow.json
- metadata/requirements-block.json
- metadata/requirements.json
This PR enables SSI guardrails by defining auto injector requirements.
When SSI will be enabled by default, guardrails will make sure injection does not apply every time, skipping known incompatible configurations.
Additional blocking mechanism is added on injector repository: https://github.com/DataDog/auto_inject/pull/436
Jira ticket: [APMLP-100]
[APMLP-100]: https://datadoghq.atlassian.net/browse/APMLP-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Enable Single Step Instrumentation Guardrails

- dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableTest.groovy
Disable Hystrix flaky test
Currently the most failing flaky test in CI
> Disable Hystrix flaky test

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
Replace `#url` by `#path` where `#url` is `"http://localhost:<port>/#path"`.
As the port is random, the name is random and removing both the host (localhost) and the port (random) does not cause issue for troubleshooting.
As example, `basic GET request http://localhost:35459/success - tagQueryString=true` will become `basic GET request /success - tagQueryString=true`
This will help with CI monitoring to keep track of test execution.
> Fix test name uniqueness

- dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
Add support to handle `TRACE_HTTP_SERVER_ERROR_STATUSES` tag as well as the original `HTTP_CLIENT_ERROR_STATUSES` tag in efforts to be more consistent with the tags from other languages.
Our goal is to make the implementation of configuration variables consistent for all languages as part of the config consistency effort listed in the following [RFC](https://docs.google.com/document/d/1kI-gTAKghfcwI7YzKhqRv2ExUstcHqADIWA4-TZ387o/edit).
Jira ticket: [APMAPI-479](https://datadoghq.atlassian.net/browse/APMAPI-479)
[APMAPI-477]: https://datadoghq.atlassian.net/browse/APMAPI-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> Add support for `TRACE_HTTP_SERVER_ERROR_STATUSES`

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/CodeOriginProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/origin/CodeOriginTest.java
- dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
Moves the code origin tags under their own namespace `_dd.code_origin`
Jira ticket: [DEBUG-2951]
[DEBUG-2951]: https://datadoghq.atlassian.net/browse/DEBUG-2951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Rename the code origin tags

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/codeorigin/CodeOriginProbeManager.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Types.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/Where.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerProbeInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/instrumentation/TypesTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/WhereTest.java
in `Where::convertLineToMethod` method we are converting a Where with a line to a new Where as a method + signature matching the line However the signature was the JVM descriptor and therefore does not match with the way we are using it for matching instrumentation that expect a java signature
> Fix Where signature

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/Configuration.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerProductChangesListener.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/TriggerProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/TriggerProbeInstrumentationTest.java
Renames the `DebuggerProbe` to `TriggerProbe` and updates all references accordingly.
Jira ticket: [DEBUG-2952]
[DEBUG-2952]: https://datadoghq.atlassian.net/browse/DEBUG-2952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> rename the DebuggerProbe to TriggerProbe

- dd-java-agent/agent-ci-visibility/build.gradle
Updates Jacoco version that is bundled with the tracer.
Jacoco is used, among other things, for parsing coverage data gathered by the JVMs that run the tests.
If the customer's project is using a newer version of Jacoco, the coverage data may not be compatible with the older version that the tracer uses.
Jira ticket: [SDTEST-998]
[SDTEST-998]: https://datadoghq.atlassian.net/browse/SDTEST-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update bundled Jacoco version

- communication/src/main/java/datadog/communication/BackendApiFactory.java
- communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
- dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java
Partially reverts the changes done in https://github.com/DataDog/dd-trace-java/pull/7689
Shared HTTP client is replaced with dedicated HTTP clients for events intake, coverage intake, and backend API - the way it was before the changes.
Sharing HTTP client results in performance regression in the Java test environment.
Jira ticket: [SDTEST-999]
[SDTEST-999]: https://datadoghq.atlassian.net/browse/SDTEST-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert HTTP client sharing in CI Vis components

- .gitlab-ci.yml
libgcc scenario got removed as the injector does not require libgcc anymore https://github.com/DataDog/system-tests/pull/3174
I missed that the tracer reference it. Here's a [broken pipeline ](https://github.com/DataDog/dd-trace-java/pull/7661)
> Fix integration tests - remove libgcc test reference

- internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/ConfigProviderTest.groovy
Add missing tests useful to #7694
Config aliases were untested and should not be tested for every feature that use it but rather in config tests. 
> Add config provider alias priority test

- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
We emit endpoint events for any local root span, but the local root span isn't necessarily associated with an endpoint. If tracing context propagation breaks for some reason, or if instrumented client code is otherwise invoked in the absence of a trace, we can end up with the profiler reporting things like SQL queries as "endpoints." These aren't very useful for analysis, and can also mean using a lot of native memory to store them in a constant pool, so this change explicitly prevents endpoint profiling when the root span is a client or producer span.
Jira ticket: [PROF-10666]
[PROF-10666]: https://datadoghq.atlassian.net/browse/PROF-10666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
> avoid emission of endpoint events for client and producer root spans

- dd-java-agent/instrumentation/avro/src/main/java/datadog/trace/instrumentation/avro/SchemaExtractor.java
- dd-java-agent/instrumentation/avro/src/test/groovy/AvroDatumReaderTest.groovy
Previously we were ignoring nested Avro messages for schema tracking and just going labelling them `object`. This uses the protobuf object expansion as a guide and displays the subschemas of avro messages
see the pretty expanded schema
> [DSM] Add avro schema object extraction

- .circleci/config.continue.yml.j2
- dd-java-agent/instrumentation/protobuf/build.gradle
This PR fixes muzzle pipeline issue by:
* giving more RAM to the `writeMuzzleTasksToFile` tasks,
* fixing current protobuf instrumentation issue,
* requiring muzzle as part of the PR checks.
This failure is blocking PR to get merged.
In addition, we want to have muzzle check required to make sure we won’t introduce regression in our code base (it could be unintended in case of PR auto-merge for example). If it’s blocking a PR, we can still leverage repository admin to force approve / merge if needed. But this change would move toward the pipeline towards the default behavior (having stable `master` branch and allowing contributor to enable auto-merge GitHub feature).
This is a workaround and we still need to figure out why this simple task need so much RAM (4.3Gio when running on local …
> Fix muzzle CI step

- dd-java-agent/agent-debugger/build.gradle
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/ASMHelper.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot302.kt
Recent Kotlin compiler generates multiple range for same local vars and mess up our algorithm for adjustment.
Fix this by made a list of unique local vars
Jira ticket: [DEBUG-2948]
[DEBUG-2948]: https://datadoghq.atlassian.net/browse/DEBUG-2948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix mixed local vars for suspend funs in Kotlin

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot303.kt
`javac` begins the range of a local var in the LocalVariableTable just after the store instruction at the init.
`kotlinc` is more free to introduce nop/other instructions in-between. need to scan backward from the start of the range to find the last store of this slot to begin the rewrite of the slot needed to hoist correctly local vars.
Jira ticket: [DEBUG-2974]
[DEBUG-2974]: https://datadoghq.atlassian.net/browse/DEBUG-2974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix hoisting local vars for Kotlin code

- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
> Disable kotlin tests for IBM8

- dd-java-agent/agent-iast/build.gradle
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/ObjectVisitor.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/GrpcRequestMessageHandlerTest.groovy
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/ObjectVisitorTest.groovy
Limits the types of collections that IAST object visitor can handle to:
- Java collections
- Apache commons collections
- Guava collections
- Protobuf collections
When an hibernate persistent collection is added to the session scope, we will try to visit the different elements in order to detect trust boundary violation vulnerabilities and we might trigger issues further down the line due to lazy loading in ORMs.
Jira ticket: [SCRS-1113]
[SCRS-1113]: https://datadoghq.atlassian.net/browse/SCRS-1113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Limit the collections that the iast visitor can handle

- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/LegacySqsClientForkedTest.groovy
- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/SqsClientTest.groovy
- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/TimeInQueueForkedTest.groovy
- dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/LegacySqsClientForkedTest.groovy
- dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/SqsClientTest.groovy
- dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/TimeInQueueForkedTest.groovy
Ignore exceptions on closing the elasticmq sqs server used in tests
That should happen when the test class shuts down
```
java.util.concurrent.ExecutionException: Boxed Exception
at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolve(Promise.scala:99)
at scala.concurrent.impl.Promise$Transformation.handleFailure(Promise.scala:444)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:506)
at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
at …
```
> Ignore timeouts on closing elasticmq for sqs tests

- dd-java-agent/instrumentation/google-pubsub/src/test/groovy/PubSubTest.groovy
The new image just published seems not having java installed in the container hence the emulator does not start. Here we pin the emulator to the latest working one
> Pin pubsub emulator docker version

- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/uploader/BatchUploaderTest.java
- internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
add unit test for avoid regression like #7166 
> Add unit test for unix domain socket support

- dd-java-agent/agent-ci-visibility/build.gradle
Cherry pick #7736
Updates Jacoco version that is bundled with the tracer.
Jacoco is used, among other things, for parsing coverage data gathered by the JVMs that run the tests.
If the customer's project is using a newer version of Jacoco, the coverage data may not be compatible with the older version that the tracer uses.
> [🍒 7736] Update bundled Jacoco version

- .circleci/config.continue.yml.j2
1. removes `TEST_LIBRARY` for `build runner` step as it's not needed here.
* Nothing positive to get from this change, appart a slightly cleaner yaml file
3. removes `TEST_LIBRARY` for run step, replacing it with the `-L` parameter, which is the clean way to have this
* Nothing positive to get from this change, appart a slightly cleaner yaml file
4. removes `PYTEST_XDIST_AUTO_NUM_WORKERS` env var : by default, parametric test will use the optimal numbers of workers
* it was previously set to 6, where the runner in circle CI has only 4 CPU. Having more workers than CPU is a known cause of instability, and in theory, should not make the run faster.  
5. increase the timeout from 12mn to 20mn  to see if it really hangs out forever, or if it happen to take 12mn + few seconds
* this time out …
> Fix parametric tests (timeouts, worker allocation)

- dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/EndHandlerWrapper.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/EndHandlerWrapper.java
This PR avoid enriching with the route the parent span when it's not available.
It solves #7773 
> Avoid NPE on vertx end advice when parent span is not available

- dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5AsyncClientTest.groovy
- dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ReactiveClientTest.groovy
- dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5SyncClientTest.groovy
Lettuce tests are quite flaky because:
```
io.lettuce.core.RedisConnectionException: Unable to connect to 127.0.0.1/<unresolved>:32794
at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:45)
at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:233)
at io.lettuce.core.RedisClient.connectStandalone(RedisClient.java:253)
at io.lettuce.core.RedisClient.connect(RedisClient.java:202)
at io.lettuce.core.RedisClient.connect(RedisClient.java:188)
at Lettuce5ReactiveClientTest.setup(Lettuce5ReactiveClientTest.groovy:58)
Suppressed: java.lang.NullPointerException: Cannot invoke method close() on null object
at Lettuce5ReactiveClientTest.cleanup(Lettuce5ReactiveClientTest.groovy:70)
Caused by: …
```
> Use real docker IP on lettuce tests

- dd-java-agent/instrumentation/mule-4/src/test/groovy/mule4/MuleForkedTest.groovy
Often `mule remote client test` is failing because the asserted spans are not in the expected order. It's a matter of collection and not parentship so ensuring the order should fix the issue
> Ensure right ordering when asserting mule remote test

- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
Avoid throwing NPE when the instrumentation context for dbinfo is accessed with a null connection
> Do not parse DBInfo when no connection

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilityRepoServices.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/CiVisibilityRepoServicesTest.groovy
Fixes module name detection for headless test sessions (i.e. sessions for JVMs that are not part of an instrumented Maven/Gradle build).
When a JVM is a part of an instrumented Maven/Gradle build, the parent process provides module names to the children processes via system properties.
For headless sessions the module name is not provided, so there is a fallback that tries to derive module name from current path and repository root (e.g. if repo root is `/my/repo/root` and current path is `/my/repo/root/submodule`, then the module name is set to `submodule`).
This fallback logic works incorrectly when repo root is `/my/repo/root` and the current path is `/my/repo/root/`: in this case module name is empty, which is not allowed.
The fix detects these cases, and uses service name as the last …
> Fix module name detection for headless sessions

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/buildsystem/BuildSystemModuleImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/buildsystem/BuildSystemSessionImpl.java
- dd-java-agent/instrumentation/gradle-3.0/src/main/groovy/datadog/trace/instrumentation/gradle/legacy/GradleProjectConfigurator.groovy
- dd-java-agent/instrumentation/gradle-8.3/src/main/java/datadog/trace/instrumentation/gradle/CiVisibilityPluginExtension.java
- dd-java-agent/instrumentation/gradle-8.3/src/main/java/datadog/trace/instrumentation/gradle/CiVisibilityService.java
- dd-java-agent/instrumentation/jacoco/src/main/java/datadog/trace/instrumentation/jacoco/ProbeInserterInstrumentation.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenProjectConfigurator.java
- internal-api/src/main/java/datadog/trace/api/civisibility/domain/BuildSessionSettings.java
Changes the logic for computing the list of packages included/excluded from Jacoco code coverage.
The old version of the logic checked the list of included packages and filtered out everything that was in the list of excluded packages, and then passed the resulting list of includes to Jacoco plugin.
The new version does two things:
1. passes the list of included/excluded packages to Jacoco plugin as is
2. in the instrumentation that is built on-top of the Jacoco plugin it checks excludes/includes before deciding whether a custom DD coverage probe needs to be inserted.
Motivation for 1 is simplification.
Motivation for 2 is to decouple ITR code coverage logic from Jacoco coverage logic: a traced project may have pre-configured Jacoco which already have its includes/excludes configured by …
> Fix Jacoco coverage exclusion

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/ConcurrentCoverageStore.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/file/FileCoverageStore.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/line/LineCoverageStore.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/percentage/JacocoCoverageCalculator.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestSuiteImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/BestEffortSourcePathResolver.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/SourcePathResolver.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/SourceResolutionException.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndex.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexBuilder.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexSourcePathResolver.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/index/RepoIndexSourcePathResolverTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/index/RepoIndexTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/config/CiVisibilityConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Updates repo indexing logic: the logic now stores the list of classes whose path relative to source root is the same (e.g. `src/java/main/my/package/MyClass.java` and `src/java9/main/my/package/MyClass.java`).
When a source path lookup is performed with the repo index, if the class if one of those "duplicates", an exception will be thrown to indicate that we cannot reliably detect the source path for this class.
The motivation is to skip code coverage report creation and submission for test cases that cover such classes.
The idea is that since we cannot reliably detect all the source paths, we do not want ITR to skip these test cases, which is why we will not be submitting code coverage reports for them. …
> Throw exception when using repo index to resolve source path for classes with identical names

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilityRepoServices.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/CiVisibilityRepoServicesTest.groovy
Cherry pick #7779
Fixes module name detection for headless test sessions (i.e. sessions for JVMs that are not part of an instrumented Maven/Gradle build).
When a JVM is a part of an instrumented Maven/Gradle build, the parent process provides module names to the children processes via system properties.
For headless sessions the module name is not provided, so there is a fallback that tries to derive module name from current path and repository root (e.g. if repo root is `/my/repo/root` and current path is `/my/repo/root/submodule`, then the module name is set to `submodule`).
This fallback logic works incorrectly when repo root is `/my/repo/root` and the current path is `/my/repo/root/`: in this case module name is empty, which is not allowed.
The fix detects these cases, and uses …
> [🍒 7779] Fix module name detection for headless sessions

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/buildsystem/BuildSystemModuleImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/buildsystem/BuildSystemSessionImpl.java
- dd-java-agent/instrumentation/gradle-3.0/src/main/groovy/datadog/trace/instrumentation/gradle/legacy/GradleProjectConfigurator.groovy
- dd-java-agent/instrumentation/gradle-8.3/src/main/java/datadog/trace/instrumentation/gradle/CiVisibilityPluginExtension.java
- dd-java-agent/instrumentation/gradle-8.3/src/main/java/datadog/trace/instrumentation/gradle/CiVisibilityService.java
- dd-java-agent/instrumentation/jacoco/src/main/java/datadog/trace/instrumentation/jacoco/ProbeInserterInstrumentation.java
- dd-java-agent/instrumentation/maven-3.2.1/src/main/java/datadog/trace/instrumentation/maven3/MavenProjectConfigurator.java
- internal-api/src/main/java/datadog/trace/api/civisibility/domain/BuildSessionSettings.java
Cherry pick #7783
Changes the logic for computing the list of packages included/excluded from Jacoco code coverage.
The old version of the logic checked the list of included packages and filtered out everything that was in the list of excluded packages, and then passed the resulting list of includes to Jacoco plugin.
The new version does two things:
1. passes the list of included/excluded packages to Jacoco plugin as is
2. in the instrumentation that is built on-top of the Jacoco plugin it checks excludes/includes before deciding whether a custom DD coverage probe needs to be inserted.
Motivation for 1 is simplification.
Motivation for 2 is to decouple ITR code coverage logic from Jacoco coverage logic: a traced project may have pre-configured Jacoco which already have its …
> [🍒 7783] Fix Jacoco coverage exclusion

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilitySystem.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Cherry pick #7784
Fixes automatic configuration of code coverage-enabled packages for headless sessions.
"Headless" sessions are those where the build system is not instrumented.
At the moment we support instrumenting Maven and Gradle, so when a Maven or a Gradle build is traced, the tracer is injected into the parent build system process. The list of coverage-enabled packages is computed in the parent process and is then propagated to children.
For headless sessions, where there is no instrumented parent process, the list of packages needs to be computed inside the child process (JVM that runs the tests).
Jira ticket: [SDTEST-1130]
[SDTEST-1130]: …
> [🍒 7784] Fix automatic coverage includes calculation for headless test sessions

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/ConcurrentCoverageStore.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/file/FileCoverageStore.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/line/LineCoverageStore.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/percentage/JacocoCoverageCalculator.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestSuiteImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/BestEffortSourcePathResolver.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/SourcePathResolver.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/SourceResolutionException.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndex.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexBuilder.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexSourcePathResolver.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/index/RepoIndexSourcePathResolverTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/source/index/RepoIndexTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/config/CiVisibilityConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Cherry-pick #7793
Updates repo indexing logic: the logic now stores the list of classes whose path relative to source root is the same (e.g. `src/java/main/my/package/MyClass.java` and `src/java9/main/my/package/MyClass.java`).
When a source path lookup is performed with the repo index, if the class if one of those "duplicates", an exception will be thrown to indicate that we cannot reliably detect the source path for this class.
The motivation is to skip code coverage report creation and submission for test cases that cover such classes.
The idea is that since we cannot reliably detect all the source paths, we do not want ITR to skip these test cases, which is why we will not be submitting code coverage reports for them. …
> [🍒 7793] Throw exception when using repo index to resolve source path for classes with identical names

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
Cherry pick https://github.com/DataDog/dd-trace-java/pull/7795
Change the default config values for DJM before the first call to `Config.get()` that resolve the Config values.
Long running spans not being enabled when using `-Ddd.data.jobs.enabled=true` since the config values were already resolved before the default values are changed
> [🍒 7795] Fix default value for long-running spans with DJM

- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DriverInstrumentation.java
Looks for the `oracle.jdbc.useShardingDriverConnection` connection property.
If this is set to `"true"` then avoid accessing `DatabaseMetaData` methods during the `Driver.connect` advice.
Accessing sharded metadata at this point could loop back into the pool, leading to starvation.
Jira ticket: [APMS-13516]
[APMS-13516]: https://datadoghq.atlassian.net/browse/APMS-13516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Avoid metadata access in driver connect advice for Oracle sharded connections

- communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
Widen catch blocks to make agent discovery more tolerant of underlying errors, like `UnsatisfiedLinkError`
Otherwise if an underlying transport throws an non I/O related error, such as JFFI throwing `UnsatisfiedLinkError` when it fails to load native components, then the exception will bubble up and installation of the tracer will be cancelled.
Jira ticket: [APMS-13480]
[APMS-13480]: https://datadoghq.atlassian.net/browse/APMS-13480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Widen catch blocks to make agent discovery more tolerant

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/DatadogClassLoader.java
- dd-java-agent/build.gradle
- utils/socket-utils/src/main/java/com/kenai/jffi/PatchInit.java
Isolates our embedded JFFI dependency from other versions that might be on the boot or system class-paths.
Avoids some obscure linkage exceptions that can happen when multiple versions of JFFI are on the class-path.
This PR contains two changes:
* Removing parent delegation when looking up `com.kenai.jffi` classes from our isolatiing `DatadogClassLoader`
* Replacing [`com.kenai.jffi.Init`](https://github.com/jnr/jffi/blob/master/src/main/java/com/kenai/jffi/Init.java#L59) with a much simpler `PatchInit` class that loads from the same isolating class-loader
Note we cannot fully shade JFFI (or the related JNR dependency) because it has a native component which would also need to be updated and recompiled for every platform. …
> Improve isolation of embedded JFFI dependency

- dd-java-agent/instrumentation/kafka-clients-3.8/build.gradle
- dd-java-agent/instrumentation/kafka-clients-3.8/src/test/groovy/KafkaClientCustomPropagationConfigTest.groovy
- dd-java-agent/instrumentation/kafka-clients-3.8/src/test/groovy/KafkaClientTestBase.groovy
This PR reenables the kafka-client tests that were disabled due to CI issues in [the new kafka integration](https://github.com/DataDog/dd-trace-java/pull/7626)
> Reenable kafka client tests

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Source.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/SinkModuleBase.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/AbstractSinkModuleTest.groovy
Makes sure that all sink modules are able to deal with `datadog.trace.api.iast.Taintable` references when reporting a vulnerability.
Taintable references were never expected to reach sinks, as they are just propagation utilities to improve performance, we have detected that in some cases they might reach sinks hiding vulnerabilities.
> Ensure vulnerabilities are reported with taintable values

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
Change the default config values for DJM **before** the first call to `Config.get()` that resolve the Config values.
Long running spans not being enabled when using `-Ddd.data.jobs.enabled=true` since the config values were already resolved before the default values are changed
> Fix default value for long-running spans with DJM

- dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
- dd-java-agent/src/main/java/datadog/trace/bootstrap/BootstrapInitializationTelemetry.java
Fix the SSI telemetry by adding `library_entrypoint` as the first argument to the telemetry forwarder command.
[Specifications](https://docs.google.com/document/d/1kH8wnGDBWJcGw7s5J9dl2McG9H7-pvl0gA6NL0IJ3BQ/edit?tab=t.0) say
```
In addition tracers should add library_entrypoint  as the first argument to the execution, which is necessary for the lib injection script to follow the code path for receiving telemetry.
```
We noticed we weren't getting any telemetry
https://datadoghq.atlassian.net/browse/INPLAT-11
> [SSI/Onboarding] Fix telemetry

- dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlarePoller.java
For changing the log level of the logs in the tracer flare , we were relying on configID starting with "flare-log-level.".
But we shouldn't: The configId could change in the future, so in order to be future-proof, the tracer should rely on the content of the config instead.
In addition, since for resetting the log level to its original value, we stop sending the configuration, we need to keep the action associated with this configId.
- [ ✅ ] Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-format)
- [ ✅  ] Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any useful labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labels)
- [ n/a] Squash your commits prior …
>  Fix relying on configId for remote config log level tracer flare change

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexBuilder.java
Lowers log level (from `WARN` to `DEBUG`) of the warning message that lists duplicate repo index keys.
To not spam the customer's logs.
> Lower log level for duplicate repo index keys warning

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/DebuggerSink.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/ProbeStatusSink.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SnapshotSink.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SymbolSink.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/SymbolSinkTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/uploader/BatchUploaderTest.java
Add a mechanism to retry on network failure or 500 response code. The retry policy store the call made to OkHttp to track number of retries made and the maximum retries allowed by failure categories: network or 500.
3 retries are allowed for snapshots, 10 for probe statuses & symdb
> Add retry policy for uploading requests to agent

- dd-java-agent/appsec/build.gradle
Upgrade to libddwaf 1.20.1 (libddwaf-java 11.1.0)
New version of libddwaf been released. It brings new functionality for ASM
> Upgrade to libddwaf 1.20.1 (libddwaf-java 11.1.0)

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HeaderInjectionModuleImpl.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/HttpHeader.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/HeaderInjectionModuleTest.groovy
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintUtils.groovy
Adds new exclusions for the header inject module:
- `Transfer-Encoding`/`Content-Encoding`: when sources come from `Accept-Encoding`
- `Pragma`: when sources come from `Cache-Control`
- `Vary`: when sources are coming only from http header names
Some customers were reporting false positive issues due to frameworks adding these types of hteaders
Jira ticket: [APPSEC-52833]
[APPSEC-52833]: https://datadoghq.atlassian.net/browse/APPSEC-52833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update header injection exclusions (reduce false positives)

- .github/workflows/update-gradle-dependencies.yaml
Fixes `update-gradle-dependencies.yaml` to add the missing `\`
The `update-gradle-dependencies` workflow failed last week due to it failing to create the PR so no updates were made.
A change was made in [#7760](https://github.com/DataDog/dd-trace-java/pull/7760) to make sure that code fixes get added to the PR, but this caused the workflow to fail with the following error:
```
must provide `--title` and `--body` (or `--fill` or `fill-first` or `--fillverbose`) when not running interactively
```
See: https://github.com/DataDog/dd-trace-java/actions/runs/11423279997/job/31782287313
A bit tricky to run these workflows without impacting the repository, so I copied this down and ran it locally to a different repository and it appeared to work.
Additionally, we could also just use `$'...'` bash …
> Fix `update-gradle-dependencies` for missing `\`

- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
* Set `DEFAULT_TELEMETRY_LOG_COLLECTION_ENABLED` to `true`.
* This was supposed to be done in v1.40.0, per https://github.com/DataDog/dd-trace-java/pull/7631, but the default value was not correctly set. This effectively enabled the telemetry logger by default, but not sending the logs to the backend.
* This is a telemetry logs regression in v1.40.0 for services that had it enabled by default until then (those using IAST, CI Visibility, Dynamic Instrumentation, or Java 8).
* This is now tested on system-tests, but requires https://github.com/DataDog/system-tests/pull/3301 which will be effective only after merging this PR.
- ~[ ] Update the [public …
> Fix telemetry logs default flag

- .github/ISSUE_TEMPLATE/config.yml
This PR add two links to the official support page for the customers to get quick support for bug and feature requests.
We should be able to better track feature requests and escalate bugs faster.
In addition, support team should be able to gather more data from the customer in a safer way.
> Enable repository issue templates

- .circleci/config.continue.yml.j2
* Make sure to always upload parametric tests logs and results as 
* Disabled (left but documented for later re-activation if needed) retries as the execution is supposed to be stable following #7756
Always uploading logs will help with parametric tests investigations
@cbeauchesne recommended to disable retries.
> Improve system tests execution

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SymbolSink.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/SymbolSinkTest.java
SymDB payload cannot be larger than 50MB otherwise datadog agent will generate an error. When serializing the upload request we are now verifying that we are below this limit, otherwise we are splitting the payload first by uploading by jar scope, but if a jar scope is still large we are splitting by class scopes. If down to one class the payload is still too large we are dropping the upload.
Jira ticket: [DEBUG-3068]
[DEBUG-3068]: https://datadoghq.atlassian.net/browse/DEBUG-3068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Split SymDB payload when too large

- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
- dd-java-agent/instrumentation/jdbc/src/test/groovy/RemoteJDBCInstrumentationTest.groovy
Add `_dd.dbm_trace_injected` tag to SQL Server spans.
Front end uses the tag to display the DBM information in APM trace panel.
> Add DBM_TRACE_INJECTED tag to SQL Server

- dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
This PR prevents throwing exception due to bad API call.
The baggage collection doesn’t handle null.
Relates to #7637 
> Prevent NPE setting null span baggage

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/CurrentAppSecConfig.java
Remote config merge set metadata in all cases.
After updating remote config, tracer doesn't report `_dd.appsec.event_rules.version` because of missing metadata.
Issue found with test from [PR-3256](https://github.com/DataDog/system-tests/pull/3256)
> Fixed remote config update operation

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/Where.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturingTestBase.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/WhereTest.java
Conversion must create a Where instance with no SourceLine (null)
> Fix `Where` conversion for CodeOrigin probes

- .gitlab-ci.yml
Remove weblogs from onboarding tests
This weblog are tested on the nightly build.
The onboarding tests should be lightweight due to in the near future we are going to add more vms
> Remove onboarding container jdk15 and buildpack tests

- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractPreparedStatementInstrumentation.java
- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
- dd-java-agent/instrumentation/jdbc/src/test/groovy/RemoteJDBCInstrumentationTest.groovy
Add `_dd.dbm_trace_injected` tag to `PreperedStatement` advisor for SQL Server.
Full mode APM/DBM support for prepared statements.
> Add _dd.dbm_trace_injected tag to SQL Server prepared statements

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/ProbeStatusSink.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SymbolSink.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/SymbolSinkTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/uploader/BatchUploaderTest.java
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Add support of SymDB payload compresion using gzip. an option is still available to disable compression.
The usual factor of compression is 40:1 which is very effective for json payload and therefore reaching the 50MB limitation is very unlikely.
Jira ticket: [DEBUG-3074]
[DEBUG-3074]: https://datadoghq.atlassian.net/browse/DEBUG-3074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add compression support for SymDB paylods

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/QueueTimerHelper.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/State.java
- dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/QueueTimeEvent.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/QueueTimeTracker.java
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TestProfilingContextIntegration.groovy
- internal-api/src/main/java/datadog/trace/api/profiling/Timing.java
Applies rate limiting to the known outliers, not to every queue transaction.
> delay queue time rate limiting until event is committed

- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
Upload is triggered by Remote Config enablement
> Make SymDB upload enabled by default for DI

- metadata/denied-environment-variables.tsv
- metadata/requirements.json
Cherry pick https://github.com/DataDog/dd-trace-java/pull/7866
DJM relies on the Hadoop instrumentation to integrate with Spark jobs. We didn't originally consider DJM to be in scope for SSI, hence the original addition. However as some customers are already using DJM with SSI we are removing it from the list.
DJM will add additional integration tests for the integration and SSI at a later date
> [🍒 7866] Remove hadoop from the denylist

- dd-java-agent/instrumentation/lettuce-5/build.gradle
- dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceInstrumentationUtil.java
Add support for lettuce 6.5 and extend testing.
Avoid using `name` while using `toString` (generally works ok on previous versions since commandKeyword are enums and toString is not overridden)
> Support lettuce 6.5

- .github/workflows/analyze-changes.yaml
This PR tries to reduce failure with Trivy scans by adding another repository to get the default and Java databases from.
The issue is still not fixed by Trivy. I keep adding mitigations.
Jira ticket: [APMLP-266]
[APMLP-266]: https://datadoghq.atlassian.net/browse/APMLP-266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add another repository for Trivy database

- dd-java-agent/instrumentation/reactive-streams/src/main/java/datadog/trace/instrumentation/reactivestreams/PublisherInstrumentation.java
- dd-java-agent/instrumentation/reactive-streams/src/main/java/datadog/trace/instrumentation/reactivestreams/SubscriberInstrumentation.java
- dd-java-agent/instrumentation/reactor-core-3.1/src/latestDepTest/groovy/ReactorCoreTest.groovy
- dd-java-agent/instrumentation/reactor-core-3.1/src/main/java/datadog/trace/instrumentation/reactor/core/CoreSubscriberInstrumentation.java
- dd-java-agent/instrumentation/reactor-core-3.1/src/test/groovy/ReactorCoreTest.groovy
`CoreSubscriber` instrumentation access to the subscriber context via the `currentContext` method.
While this is not expected to throw, it may happen that inner operators like `reactor.core.publisher.FluxWindowPredicate$WindowFlux` might throw a NPE because it's implementation is defined as 
```
interface InnerOperator<I, O> extends InnerConsumer<I>, InnerProducer<O> {
default Context currentContext() {
return this.actual().currentContext();
}
}
```
and `actual()` returns null
I also put a test to ensure that we do not have unhandled exception in that instrumentation. As well I protected other potential unsafe access context and cleaned up a leftover
Jira ticket: …
> Protect currentContext access for reactor inner operators

- .github/workflows/README.md
- .github/workflows/check-pull-requests.yaml
- .github/workflows/tests/check-pull-requests/payload-pull-request-draft.json
- .github/workflows/tests/check-pull-requests/payload-pull-request-missing-label.json
- .github/workflows/tests/check-pull-requests/payload-pull-request-no-release-notes.json
- .github/workflows/tests/check-pull-requests/payload-pull-request-title-tag.json
- .github/workflows/tests/check-pull-requests/payload-pull-request.json
- .github/workflows/tests/check-pull-requests/test-pull-request.sh
- .github/workflows/tests/env.sh
This PR introduces a workflow to check that PRs labels and title match the contributing guidelines.
The check won’t be blocking but the action will add a comment for awareness.
This will reduce the load of reviewers / releasers and get contributors more involved.
> feat(ci): Add pull request checks

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/codeorigin/DefaultCodeOriginRecorder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/CodeOriginProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturingTestBase.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/origin/CodeOriginTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CodeOrigin04.java
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Update the code origin code to check for an environment variable when configuring the maximum number of user frames to include in a code origin probe's output.
Jira ticket: [DEBUG-2727]
[DEBUG-2727]: https://datadoghq.atlassian.net/browse/DEBUG-2727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Consult the environment variable when setting the max users frames in code origin probes

- dd-java-agent/instrumentation/reactive-streams/src/main/java/datadog/trace/instrumentation/reactivestreams/PublisherInstrumentation.java
- dd-java-agent/instrumentation/reactive-streams/src/main/java/datadog/trace/instrumentation/reactivestreams/SubscriberInstrumentation.java
- dd-java-agent/instrumentation/reactor-core-3.1/src/latestDepTest/groovy/ReactorCoreTest.groovy
- dd-java-agent/instrumentation/reactor-core-3.1/src/main/java/datadog/trace/instrumentation/reactor/core/CoreSubscriberInstrumentation.java
- dd-java-agent/instrumentation/reactor-core-3.1/src/test/groovy/ReactorCoreTest.groovy
Backport #7883 to release/v1.42.x
> [🍒 7883] Protect currentContext access for reactor inner operators

- tooling/backport-pr-to-patch-release.sh
This PR add support for PRs with multiple commits to be back-ported to patch release using the `tooling/backport-pr-patch-release.sh` script.
Only single commit PR worked.
So when PR are merged using the squash feature, the script failed to back-port them.
> Add support for multiple commits PR backport

- dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
This handles scenarios where the profiling context may not be able to store the thread context because the user has increased the value of pid_max during the process lifetime.
Jira ticket: [PROF-10861]
[PROF-10861]: https://datadoghq.atlassian.net/browse/PROF-10861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> paranoid exception handling when setting profiling thread context

- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/ConsumerCoordinatorInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/KafkaConsumerInfoInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/KafkaConsumerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/KafkaProducerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/LegacyKafkaConsumerInfoInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/MetadataInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/OffsetCommitCallbackInvokerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/test/groovy/KafkaClientCustomPropagationConfigTest.groovy
- dd-java-agent/instrumentation/kafka-clients-3.8/src/test/groovy/KafkaClientTestBase.groovy
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
This reverts commit 8c7495a542f34a947edb7dae7e7b99f86d15fcac.
> Revert "Removed config variable for disabling kafka-clients"

- .github/workflows/check-pull-requests.yaml
This PR will avoid duplicating PR check messages by updating the original one.
GitHub workflow trigger event are somewhat messy to keep track of.
So the last run will update the message accordingly.
The workflow is disabled until the fix PR is merged.
Originally reported by @amarziali 
> Fix duplicate PR check comments

- .circleci/render_config.py
This PR updates the builder image to the latest version:
https://github.com/DataDog/dd-trace-java-docker-build/actions/runs/11571570798
Building and testing with the latest JDKs
> Update to latest builder image

- telemetry/src/test/groovy/datadog/telemetry/dependency/JarReaderSpecification.groovy
Add missing test case for `JarReader` for nested jar path with trailing `!/`.
Jira ticket: [APPSEC-55773](https://datadoghq.atlassian.net/browse/APPSEC-55773) (related)
[APPSEC-55773]: https://datadoghq.atlassian.net/browse/APPSEC-55773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add missing test for JarReader with trailing separator

- dd-smoke-tests/asm-standalone-billing/src/test/groovy/datadog/smoketest/asmstandalonebilling/AsmStandaloneBillingSmokeTest.groovy
- dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
https://github.com/datadog/dd-trace-java/pull/7257 introduced the `/info` endpoint for the mock agent in smoke-tests, but it was malformed, leading to logged exceptions:
```
[dd.trace 2024-11-11 16:38:35:249 +0100] [main] DEBUG datadog.communication.ddagent.DDAgentFeaturesDiscovery - Error parsing trace agent /info response
com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $.endpoints[3]
at com.squareup.moshi.JsonReader.syntaxError(JsonReader.java:243)
at com.squareup.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:1152)
at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:349)
at com.squareup.moshi.JsonUtf8Reader.hasNext(JsonUtf8Reader.java:197)
at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdap …
```
> Fix /info endpoint in smoke tests

- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/TaskUnwrappingInstrumentation.java
`io.grpc.internal.LogExceptionRunnable` wraps a field called `task` - which we'd like to report queue time against instead.
> unwrap LogExceptionRunnable

- .circleci/upload_ciapp.sh
- .github/workflows/README.md
- .github/workflows/analyze-changes.yaml
This PR sends tests and static analysis result reports to Datadog production environment.
This was previously set up for staging, but all the repositories moved to production.
In order to have a complete view of the different projects and CI, this uploads the results to the production environment.
We will still send data to the staging environment to benefit from staging features.
> Update CI reports to prod

- metadata/denied-environment-variables.tsv
- metadata/requirements.json
This PR removes SSI guardrails entries for HBase and Hive.
Hadoop, Hbase and Hive will be blocked using the shell script blocking rules from the injector repository.
Jira ticket: [APMLP-177] [APMLP-178]
[APMLP-177]: https://datadoghq.atlassian.net/browse/APMLP-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove SSI guardrails entries for hbase and hive

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ExceptionProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/Snapshot.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/ExceptionHelper.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/DefaultExceptionDebuggerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeManagerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/ExceptionHelperTest.java
In some cases, the innermost exception could contain only third-party frames and no instrumentation is performed while the exception could be re-throw up in the stack where the call originated. This could help to root cause the inner exception.
Now in that case we are climbing up the chained of exceptions to find user frames to instrument.
when finding the innermost exception, we are reporting the list of all outer exceptions beginning by the innermost. The chained index is also kept in the probe and injected into the snapshot to be able to remap the frame index correctly and report it to the span as tag.
Jira ticket: [DEBUG-3107]
[DEBUG-3107]: …
> Add outer exceptions support for Exception Replay

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymDBEnablement.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymbolAggregator.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymbolExtractionTransformerTest.java
We need to track all classes loaded and extracted into ClassNameTrie that is space efficient prefix tree. That way we prevent any duplicates reaching SymDB backend
Same classes can be loaded in different classloader, but symbol-wise they are the same. In some situation (like Groovy script) we can a lot
of class loaded for same symbols which pollute SymDB backend.
Jira ticket: [DEBUG-3114]
[DEBUG-3114]: https://datadoghq.atlassian.net/browse/DEBUG-3114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Avoid duplicate class symbol extraction

- dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
Exclude `spark.*` from vunerability locations.
Avoid vulnerabilities such as header injection being reported with `spark.Response` as its location. The vulnerabilities will still be reported, but with the caller code as location.
Jira ticket: [APPSEC-55756](https://datadoghq.atlassian.net/browse/APPSEC-55756)
[
[APPSEC-55756]: https://datadoghq.atlassian.net/browse/APPSEC-55756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Exclude spark web from vulnerability locations

- dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
Exclude IAST instrumentation from `dev.failsafe.*`.
Avoids weak randomness false positive. Instrumentation fully exclude since there's little value in running for this library (retry operations).
Jira ticket: [APPSEC-55801](https://datadoghq.atlassian.net/browse/APPSEC-55801)
[APPSEC-55801]: https://datadoghq.atlassian.net/browse/APPSEC-55801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Exclude dev.failsafe from IAST instrumentation

- dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
Exclude `okio.*` from vunerability locations
Avoid `okio.*` as vulnerability location (e.g. weak hash being reported at okio itself when using `okio.ByteString#digest`. The vulnerabilities will still be reported, but with the caller code as location.
Jira ticket: [APPSEC-55765](https://datadoghq.atlassian.net/browse/APPSEC-55765)
[APPSEC-55765]: https://datadoghq.atlassian.net/browse/APPSEC-55765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Exclude okio from vulnerability locations

- dd-java-agent/instrumentation/spring-security-5/src/main/java/datadog/trace/instrumentation/springsecurity5/AuthenticationManagerInstrumentation.java
- dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/SecurityConfig.groovy
- dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/SpringBootBasedTest.groovy
- dd-java-agent/instrumentation/spring-security-5/src/test/java/custom/FailingAuthenticationProvider.java
- dd-java-agent/instrumentation/spring-security-6/src/test/groovy/datadog/trace/instrumentation/springsecurity6/SecurityConfig.groovy
- dd-java-agent/instrumentation/spring-security-6/src/test/groovy/datadog/trace/instrumentation/springsecurity6/SpringBootBasedTest.groovy
- dd-java-agent/instrumentation/spring-security-6/src/test/java/custom/FailingAuthenticationProvider.java
Changes spring-security instrumentation from `org.springframework.security.authentication.AuthenticationProvider` (multiple providers can coexist causing false triggers of failure) to `org.springframework.security.authentication.AuthenticationManager` that should be stable and generate only login success or failure but never both.
Having both login success and failure can cause problems specially in terms of ATO (account take over), this PR ensures that we don't get false positives in the events.
> Prevent spans from having login success and failure events simultaneously

- telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java
- telemetry/src/main/java/datadog/telemetry/dependency/JarReader.java
- telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverSpecification.groovy
- telemetry/src/test/groovy/datadog/telemetry/dependency/JarReaderSpecification.groovy
Add support for new Spring Boot loader jars (using `jar:nested:` URLs) on dependency collection.
Some more info at https://docs.spring.io/spring-boot/specification/executable-jar/jarfile-class.html
It seems we could optimize access to these nested jars.
Jira ticket: [APPSEC-55773](https://datadoghq.atlassian.net/browse/APPSEC-55773)
[APPSEC-55773]: https://datadoghq.atlassian.net/browse/APPSEC-55773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix dependency collection for new Spring Boot nested jars

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-java-agent/instrumentation/armeria-jetty/src/test/jetty11/groovy/ArmeriaJetty11ServerTest.groovy
- dd-java-agent/instrumentation/jetty-11/src/main/java/datadog/trace/instrumentation/jetty11/RequestInstrumentation.java
- dd-java-agent/instrumentation/jetty-11/src/main/java11/datadog/trace/instrumentation/jetty11/SetRequestedSessionIdAdvice.java
- dd-java-agent/instrumentation/jetty-11/src/test/groovy/Jetty11Test.groovy
- dd-java-agent/instrumentation/jetty-11/src/test/groovy/JettyAsyncHandlerTest.groovy
- dd-java-agent/instrumentation/jetty-11/src/testFixtures/groovy/JettyServer.groovy
- dd-java-agent/instrumentation/jetty-12/build.gradle
- dd-java-agent/instrumentation/jetty-12/src/main/java/datadog/trace/instrumentation/jetty12/AbstractSessionManagerInstrumentation.java
- dd-java-agent/instrumentation/jetty-12/src/main/java17/datadog/trace/instrumentation/jetty12/ResolveRequestedSessionIdAdvice.java
- dd-java-agent/instrumentation/jetty-12/src/test/ee8/groovy/Jetty12Test.groovy
- dd-java-agent/instrumentation/jetty-12/src/test/ee8/groovy/JettyServer.groovy
- dd-java-agent/instrumentation/jetty-7.0/src/main/java/datadog/trace/instrumentation/jetty70/RequestInstrumentation.java
- dd-java-agent/instrumentation/jetty-7.0/src/test/groovy/Jetty70Test.groovy
- dd-java-agent/instrumentation/jetty-7.6/src/main/java/datadog/trace/instrumentation/jetty76/RequestInstrumentation.java
- dd-java-agent/instrumentation/jetty-7.6/src/test/groovy/Jetty76Test.groovy
- dd-java-agent/instrumentation/jetty-9/src/main/java/datadog/trace/instrumentation/jetty10/RequestInstrumentation.java
- dd-java-agent/instrumentation/jetty-9/src/main/java/datadog/trace/instrumentation/jetty9/RequestInstrumentation.java
- dd-java-agent/instrumentation/jetty-9/src/main/java_jetty10/datadog/trace/instrumentation/jetty10/SetRequestedSessionIdAdvice.java
- dd-java-agent/instrumentation/jetty-9/src/test/groovy/datadog/trace/instrumentation/jetty9/Jetty9Test.groovy
- dd-java-agent/instrumentation/jetty-common/src/main/java/datadog/trace/instrumentation/jetty/JettyBlockingHelper.java
- dd-java-agent/instrumentation/servlet/request-2/src/test/groovy/TestServlet2.groovy
- dd-java-agent/instrumentation/servlet/request-3/src/testFixtures/groovy/datadog/trace/instrumentation/servlet3/TestServlet3.groovy
- dd-java-agent/instrumentation/servlet/request-5/src/testFixtures/groovy/datadog/trace/instrumentation/servlet5/TestServlet5.groovy
Adds support for session tracking in all versions of jetty.
Jira ticket: [APPSEC-55559]
[APPSEC-55559]: https://datadoghq.atlassian.net/browse/APPSEC-55559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add support for session tracking in jetty

- .circleci/upload_ciapp.sh
Avoid DATADOG_API_KEY in test visibility upload, just in case it's picked up by the upload script.
We have a legacy `DATADOG_API_KEY` in Circle CI env. This might be the cause of results not being uploaded to prod.
Jira ticket: [APMSP-1519](https://datadoghq.atlassian.net/browse/APMSP-1519)
[APMSP-1519]: https://datadoghq.atlassian.net/browse/APMSP-1519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Avoid DATADOG_API_KEY in test visibility upload

- .circleci/config.continue.yml.j2
Parallelize system-tests at scenario level. We just use `circleci tests` for splitting, which will be quite naive, but might just do the job at the moment.
I'll be expanding the number of scenarios that are run, and running them linearly will increase the wall clock time for the full pipeline. Parallelization here is quite reasonable since there's just ~2min of the job that is redundant, and these are medium size runners anyway.
> Parallelize system-tests

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-0.3/src/test/groovy/TypeConverterTest.groovy
- dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/TypeConverterTest.groovy
- dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/TypeConverterTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
- dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
- dd-trace-ot/src/test/groovy/datadog/opentracing/TypeConverterTest.groovy
- internal-api/src/main/java/datadog/trace/api/Config.java
Removes the internal `dd.trace.scope.inherit.async.propagation` feature flag, which has always defaulted to `true`
This flag was added in #1850 (v0.64.0) in case we needed to revert the fixed behaviour, but we have never needed to do that. Removing it simplifies some of the code and helps with future refactoring.
> Remove internal `dd.trace.scope.inherit.async.propagation` feature flag

- dd-smoke-tests/asm-standalone-billing/src/test/groovy/datadog/smoketest/asmstandalonebilling/AsmStandaloneBillingSamplingSmokeTest.groovy
At least two of the test cases are flaky right now so I decided to mark all the smoke test to avoid more problems until it will be fixed.
Note: this feature is well covered by system-tests
> Mark AsmStandaloneBillingSamplingSmokeTest as flaky

- .github/workflows/analyze-changes.yaml
Remove the run of datadog-static-analysis.
Already done automatically by datadog hosted scan, this duplicates the results.
> Remove datadog-static-analysis workflow

- metadata/denied-arguments.tsv
- metadata/requirements-block.json
- metadata/requirements.json
This PR excludes DataDog JMXFetch from the processes being automatically instrumented. 
There is no use instrumenting JMXFetch and it will add noise while troubleshooting (using flare).
Jira ticket: [APMLP-325]
[APMLP-325]: https://datadoghq.atlassian.net/browse/APMLP-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add JMXFetch to SSI Guardrails denylist

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/overhead/OverheadController.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/overhead/OverheadControllerTest.groovy
Until now, every 30s we did reset some values for IAST overhead control, including the counter for maximum concurrent requests. This change does:
* Avoid resetting the counter of available requests. This may lead to IAST starving if coupled with a bug in end of request event handling, but the alternative is worse: producing an uncontrolled increase in memory overhead.
* If we're starved of available requests for 1 hour, we'll emit a telemetry log. This will help us finding any case where we might have a bug here.
We observed an akka-http service with an abnormal number of IAST contexts in the heap:
* These exceeded, by large, the default number of concurrent IAST contexts (at the moment, 2).
* It seems IAST request contexts leaked to Akka objects beyond the request scope. This should not …
> Do not reset IAST concurrent request counter

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastGlobalContext.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastOptOutContext.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastRequestContext.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/IastRequestContextTest.groovy
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/IastSystemTest.groovy
- dd-java-agent/agent-iast/src/testFixtures/groovy/com/datadog/iast/test/IastAgentTestRunner.groovy
- dd-java-agent/agent-iast/src/testFixtures/groovy/com/datadog/iast/test/IastRequestContextPreparationTrait.groovy
- dd-java-agent/instrumentation/kafka-clients-0.11/src/iastLatestDepTest3/groovy/iast/KafkaIastDeserializerTest.groovy
- dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/iast/KafkaIastDeserializerForkedTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
- internal-api/src/main/java/datadog/trace/api/iast/IastContext.java
Resets all IAST request context data structures when the root span of a trace is published.
We observed an akka-http service with a very high number of IAST contexts in the heap probably related to pending traces, once a trace has been published we should not hold down to any references.
Jira ticket: [APPSEC-55869]
[APPSEC-55869]: https://datadoghq.atlassian.net/browse/APPSEC-55869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Reset iast request context on root span published

- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Fix baggages mapping when only keys are provided.
Before that, setting a baggage mapping with key only was not taken into tracer configuration: for example, setting 
`dd.trace.header.baggage=thisisabaggage` leads to `baggageMapping={}`.
Workaround without this fix: use `dd.trace.header.baggage=thisisabaggage:thisisabaggage` instead of `dd.trace.header.baggage=thisisabaggage`
Run into this while working on [APMS-13920](https://datadoghq.atlassian.net/browse/APMS-13920).
Fix how this is supposed to work according to our specification/documentation.
[APMS-13920]: https://datadoghq.atlassian.net/browse/APMS-13920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> Fix baggages mapping configuration when only keys are provided

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitClient.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/utils/ShellCommandExecutor.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterState.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/main/java/datadog/trace/instrumentation/elasticsearch2/TransportActionListener.java
- dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/main/java/datadog/trace/instrumentation/elasticsearch5_3/TransportActionListener.java
- dd-java-agent/instrumentation/elasticsearch/transport-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/TransportActionListener.java
- dd-java-agent/instrumentation/elasticsearch/transport-6/src/main/java/datadog/trace/instrumentation/elasticsearch6/TransportActionListener.java
- dd-java-agent/instrumentation/elasticsearch/transport-7.3/src/main/java/datadog/trace/instrumentation/elasticsearch7_3/TransportActionListener.java
- dd-java-agent/instrumentation/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/hazelcast36/DistributedObjectDecorator.java
- dd-java-agent/instrumentation/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/hazelcast39/ClientInvocationDecorator.java
- dd-java-agent/instrumentation/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/hazelcast4/HazelcastDecorator.java
- dd-java-agent/instrumentation/opensearch/transport/src/main/java/datadog/trace/instrumentation/opensearch/TransportActionListener.java
- dd-java-agent/instrumentation/redisson/redisson-2.0.0/src/main/java/datadog/trace/instrumentation/redisson/RedissonInstrumentation.java
- dd-java-agent/instrumentation/redisson/redisson-2.3.0/src/main/java/datadog/trace/instrumentation/redisson23/RedissonInstrumentation.java
- dd-java-agent/instrumentation/redisson/redisson-3.10.3/src/main/java/datadog/trace/instrumentation/redisson30/RedissonInstrumentation.java
- dd-trace-core/src/main/java/datadog/trace/core/flare/TracerFlareService.java
- internal-api/src/main/java/datadog/trace/api/naming/v1/CloudNamingV1.java
- internal-api/src/main/java/datadog/trace/util/Strings.java
- internal-api/src/test/groovy/datadog/trace/util/StringsTest.groovy
This PR cleans up custom `Strings.join` to use the JDK `String.join` instead.
This API should date from pre 1.0 which was Java 7 compatible while `String.join` was introduced in Java 8.
The JDK method pass our custom `Strings.join` tests too.
> Remove Strings.join API in favor of JDK String.join

- .github/workflows/check-pull-requests.yaml
- .github/workflows/tests/check-pull-requests/payload-pull-request-instrumentation.json
- .github/workflows/tests/check-pull-requests/test-pull-request.sh
This PR fixes instrumentation label detection during PR check.
Prevent wrong negative from the PR checker.
Reported by @amarziali 
> Fix PR label check

- dd-java-agent/instrumentation/okhttp-2/src/test/groovy/OkHttp2AsyncTest.groovy
- dd-java-agent/instrumentation/okhttp-3/src/test/groovy/OkHttp3AsyncTest.groovy
```
callbacks should carry context.callbacks should carry context [url: http://localhost:39281/success, error: false, method: GET, #0]
```
> Unique test names for okhttp

- .circleci/config.continue.yml.j2
Add the following system-tests scenarios relevant to the upcoming GA release of Exploit Prevention (aka RASP):
* `APPSEC_RASP`
* `APPSEC_RUNTIME_ACTIVATION`
* `REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD`
And the following related to blocking:
* `APPSEC_BLOCKING`
* `APPSEC_REQUEST_BLOCKING`.
Jira ticket: [APPSEC-55833](https://datadoghq.atlassian.net/browse/APPSEC-55833)
[APPSEC-55833]: https://datadoghq.atlassian.net/browse/APPSEC-55833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
> Run system-tests scenarios related to RASP

- static-analysis.datadog.yml
Ignore a few static analysis rules:
* `one-declaration-per-line`, `control-statement-braces`: stylistic choices that are currently in use, any enforcement here should be done through a formatter, if any.
* `avoid-dollar-signs`: We use dollar signs in some class and method names, and there's no way around it (e.g. referencing Scala classes from Java, manipulating auto-generated classes).
* `literals-first-in-comparison`: not in line with our current practice at all, prefer nullability analysis (e.g. NullAway).
* `redundant-initializer`: No consensus, and low value.
- ~[ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/jav …
> Mute some static analysis rules

- dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/StringBuilderCallSiteTest.groovy
- dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringBufferSuite.java
- dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringBuilderSuite.java
This refactors the test suite of the `StringBuffer` to his proper file. Previously was inside the `StringBuilder` test suite
Jira ticket: [APPSEC-55369]
[APPSEC-55369]: https://datadoghq.atlassian.net/browse/APPSEC-55369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Refactor tests of StringBuffer substring

- buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/impl/AdviceGeneratorImpl.java
- buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/AdviceGeneratorTest.groovy
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteTransformer.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteUtils.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/csi/CallSiteAdvice.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/BaseCallSiteTest.groovy
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteInstrumentationTest.groovy
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteUtilsTest.groovy
- dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/csi/SuperInCtorExample.java
- dd-java-agent/instrumentation/java-io/src/test/groovy/datadog/trace/instrumentation/java/io/StringReaderCallSiteTest.groovy
- dd-java-agent/instrumentation/java-io/src/test/java/foo/bar/TestCustomStringReader.java
- dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
Fixes an issue in IAST with call-sites instrumenting constructor super calls. The Java compiler generates different bytecode when the `<init>` method is called from a `new` instruction or via `super`:
* **new**
```java
public class TestStringReaderSuite {
public static void init(String input) {
new StringReader(input);
}
}
```
```
NEW java/io/StringReader
DUP
ALOAD 0
INVOKESPECIAL java/io/StringReader.<init> (Ljava/lang/String;)V
```
* **super**
```java
public class TestStringReaderIssue extends StringReader {
public TestStringReaderIssue(String s) {
super(s);
}
}
```
```
ALOAD 0
ALOAD 1
INVOKESPECIAL java/io/StringReader.<init> (Ljava/lang/String;)V
```
This PR ensures that the `CallSiteTransformer` is able to deal with both cases successfully.
One customer reported an issue when …
> Fix issue with call sites in super calls to constructor

- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/TempLocationManager.java
Fix up of #7971 
Due to a different mechanism to retrieve running JVM processes the cleanup is not correct on J9
> Fix the temp location manager on J9

- dd-java-agent/instrumentation/kafka-clients-0.11/build.gradle
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/ConsumerCoordinatorInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInfoInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDeserializerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/MetadataInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/build.gradle
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/ConsumerCoordinatorInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/KafkaConsumerInfoInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/KafkaConsumerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/KafkaProducerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/LegacyKafkaConsumerInfoInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/MetadataInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/OffsetCommitCallbackInvokerInstrumentation.java
Use existence of `MetadataRecoveryStrategy` to decide whether to apply pre-3.8 or post-3.8 `kafka-clients` instrumentation
Avoids double instrumentation of `kafka-clients` versions from 3.8 onwards.
One exception: IAST's `KafkaDeserializerInstrumentation` is compatible with all 3.x versions of `kafka-clients`
Also note this doesn't address the warning instrumenting `kafka-clients` 3.7 where `KafkaConsumerInfoInstrumentation` doesn't apply because the `metadata` field has been removed from `KafkaConsumer`. This is unrelated to the double-instrumentation issue, and will be addressed in another PR.
> Avoid double instrumentation of kafka-clients 3.8+

- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/ConsumerCoordinatorInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInfoInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaConsumerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/MetadataInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/ConsumerCoordinatorInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/KafkaConsumerInfoInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/KafkaConsumerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/KafkaProducerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/LegacyKafkaConsumerInfoInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/MetadataInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/OffsetCommitCallbackInvokerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/test/groovy/KafkaClientCustomPropagationConfigTest.groovy
- dd-java-agent/instrumentation/kafka-clients-3.8/src/test/groovy/KafkaClientTestBase.groovy
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Re-enables kafka 3.8 because the double instrumentation issue has been resolved in https://github.com/DataDog/dd-trace-java/pull/8006
Jira ticket: [AIDM-477]
[AIDM-477]: https://datadoghq.atlassian.net/browse/AIDM-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Reenable kafka 3.8 by default

- dd-java-agent/instrumentation-annotation-processor/src/main/java/datadog/apt/LogUtils.java
This PR only shows the annotation processor notes when notes is enabled.
This aims to reduce the noise of the tool running to only the detected issues.
> Hide static checker notes when notes is enabled

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OpenTelemetryContextInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OpenTelemetryContextStorageInstrumentation.java
- dd-smoke-tests/opentelemetry/build.gradle
- dd-smoke-tests/opentelemetry/src/main/java/datadog/smoketest/opentelemetry/Application.java
- dd-smoke-tests/opentelemetry/src/test/groovy/datadog/smoketest/OpenTelemetrySmokeTest.groovy
Adds `OtelSpanEvent` to the helpers injected when interacting with the OpenTelemetry Context API.
This helper is needed to support Event API calls made inside contexts produced by `@WithSpan` before the main `OpenTelemetry` API is touched.
One workaround is to add a static reference to `GlobalOpenTelemetry` in your application:
```
static {
GlobalOpenTelemetry.get();
}
```
which will trigger injection of `OtelSpanEvent` via `OpenTelemetryInstrumentation`
> Support using OpenTelemetry Event API inside `@WithSpan` annotated method

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/spanorigin/CodeOriginInfo.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/codeorigin/DefaultCodeOriginRecorder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/CodeOriginProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/Where.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/origin/CodeOriginTest.java
Currently the fingerprinting used to prevent repeat instrumentations uses the stack trace to track existing probe definitions.  This PR cleans that up to use a cheaper fingerprint that doesn't rely on walking the stack each time.
Jira ticket: [DEBUG-3147]
[DEBUG-3147]: https://datadoghq.atlassian.net/browse/DEBUG-3147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update the CodeOriginProbe fingerprint to not rely on a stack walk

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
To be able to match probe with more flexibility (probes targeting a method with or without signature) we are iterating over all methods of a class and using Where::isMethodMatching to select probe definitions that will be apply on the current method. With this new approach we are dropping the support of overloaded methods: only one method is instrumented or a definition is applied only once.
Jira ticket: [DEBUG-3149]
[DEBUG-3149]: https://datadoghq.atlassian.net/browse/DEBUG-3149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Refactor probe matching for methods

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/StringModuleImpl.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/StringModuleTest.groovy
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintUtils.groovy
- dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringCallSite.java
- dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/StringCallSiteTest.groovy
- dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringSuite.java
- internal-api/src/main/java/datadog/trace/api/iast/propagation/StringModule.java
This adds the instrumentation to propagate the taint values through the following method of `String`:
- `valueOf(Object)`
Increase IAST propagation of String methods.
Jira ticket: [APPSEC-55357]
[APPSEC-55357]: https://datadoghq.atlassian.net/browse/APPSEC-55357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add IAST propagation to String valueOf

- dd-java-agent/instrumentation/twilio/src/main/java/datadog/trace/instrumentation/twilio/TwilioClientDecorator.java
- dd-java-agent/instrumentation/twilio/src/test/groovy/test/TwilioClientTest.groovy
Allows using `DD_SERVICE` when the naming schema is `v1` or if `DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED=true`
Jira ticket: [APMS-13987]
[APMS-13987]: https://datadoghq.atlassian.net/browse/APMS-13987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Twilio: allow service name flattening

- .circleci/collect_results.sh
This PR will alter JUnit test reports that are uploaded to CI Visibility to remove Java object hashCode from the test case name, replacing them by `HASHCODE`.
This will help with CI monitoring to keep track of test execution.
In addition, the script will now dump the collected result files, their mapping, and warn about hashCode presence.
Output example:
```
Saving test results:
- ./internal-api/build/test-results/forkedTest/TEST-datadog.trace.api.WithGlobalTracerForkedTest.xml as internal-api_forkedTest_TEST-datadog.trace.api.WithGlobalTracerForkedTest.xml
- ./internal-api/build/test-results/forkedTest/TEST-datadog.trace.api.naming.NamingV0ForkedTest.xml as internal-api_forkedTest_TEST-datadog.trace.api.naming.NamingV0ForkedTest.xml
- …
```
> Fix JUnit test case name uniqueness when uploading results

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitDataUploaderImpl.java
Makes sure `Failed to upload git tree data` error logs are not uploaded to telemetry.
This error happens often if `git` executable is not available in user's CI.
Jira ticket: [SDTEST-1267]
[SDTEST-1267]: https://datadoghq.atlassian.net/browse/SDTEST-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Exclude git data upload errors from telemetry logging

- dd-java-agent/agent-bootstrap/build.gradle
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturingTestBase.java
- dd-java-agent/instrumentation/grpc-1.5/build.gradle
- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/MethodHandlersInstrumentation.java
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcCodeOriginTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
This updates the grpc integration to enable code origin support for grpc servers.
Jira ticket: [DEBUG-3109]
[DEBUG-3109]: https://datadoghq.atlassian.net/browse/DEBUG-3109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Implement code origin support for grpc server entry spans

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/AsyncResultDecorator.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AsyncResultExtension.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AsyncResultExtensions.java
- dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java
- dd-java-agent/instrumentation/guava-10/src/main/java/datadog/trace/instrumentation/guava10/GuavaAsyncResultExtension.java
- dd-java-agent/instrumentation/guava-10/src/main/java/datadog/trace/instrumentation/guava10/ListenableFutureInstrumentation.java
- dd-java-agent/instrumentation/guava-10/src/test/groovy/GuavaAsyncResultExtensionTest.groovy
- dd-java-agent/instrumentation/reactive-streams/src/main/java/datadog/trace/instrumentation/reactivestreams/PublisherInstrumentation.java
- dd-java-agent/instrumentation/reactive-streams/src/main/java/datadog/trace/instrumentation/reactivestreams/ReactiveStreamsAsyncResultExtension.java
- dd-java-agent/instrumentation/reactive-streams/src/test/groovy/ReactiveStreamsAsyncResultExtensionTest.groovy
- dd-java-agent/instrumentation/reactor-core-3.1/src/latestDepTest/groovy/ReactorAsyncResultExtensionTest.groovy
- dd-java-agent/instrumentation/reactor-core-3.1/src/main/java/datadog/trace/instrumentation/reactor/core/BlockingPublisherInstrumentation.java
- dd-java-agent/instrumentation/reactor-core-3.1/src/main/java/datadog/trace/instrumentation/reactor/core/ReactorAsyncResultExtension.java
- dd-java-agent/instrumentation/reactor-core-3.1/src/test/groovy/ReactorAsyncResultExtensionTest.groovy
- dd-java-agent/instrumentation/rxjava-2/src/main/java/datadog/trace/instrumentation/rxjava2/RxJavaAsyncResultExtension.java
- dd-java-agent/instrumentation/rxjava-2/src/main/java/datadog/trace/instrumentation/rxjava2/RxJavaPluginsInstrumentation.java
- dd-java-agent/instrumentation/rxjava-2/src/test/groovy/RxJava2ResultExtensionTest.groovy
Refactors registration of `AsyncResult` extensions so it doesn't pull in `AsyncResultDecorator` and all the associated decorator and function classes at bytecode transformation time, which would pollute the analyzed heap and lead to them all needing to be marked as build-time.
Also marks the runtime holder of `AsyncResult` extensions as re-runnable. This avoids having to list all the different extensions that might end up registered as build-time, but also avoids double registrations where the same extension is registered at build-time via native-image - and at runtime via the compiled type initializer.
The recent refactoring of `AsyncResult` extensions caused a regression in our native-image support, but only when a reactive library was on the application class-path.
Use `solves` …
> Fix native-image generation of reactive applications

- dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyBlockingHelper.java
- dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyDecorator.java
- dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyHttpHandlerInstrumentation.java
- dd-java-agent/instrumentation/grizzly-http-2.3.20/src/main/java/datadog/trace/instrumentation/grizzlyhttp232/FilterAdvice.java
We don't need access to the scope, checking to see if there's an active span is enough.
> Update Grizzly instrumentation to check active span instead of scope

- dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
Ignores unstable `4.0.0-rc` versions when running Maven tests. 
> Ignore RC versions when running Maven smoke tests

- buildSrc/src/main/groovy/MuzzlePlugin.groovy
excluded deps should also affect extra ones.
> Muzzle exclude dep from extras

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
Errors in telemetry:
```
Error : Failed to inject helper classes - instrumentation.class={} instrumentation.target.classloader={} instrumentation.target.class={}
```
Having at least the instrumentation class, which is not a sensitive parameter, will help us group errors in telemetry.
> Ensure instrumentation class is logged if helper class fails to be injected

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/http/ClientIpAddressResolver.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/http/ClientIpAddressResolverSpecification.groovy
- dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
- dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/NoneHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/W3CHttpExtractorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpExtractorTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TagContext.java
Remove `X-Forwarded` header from default client IP resolution.
Unclear evidence of real world usage of this header, as well as its format. Support is dropped from default client IP resolution, but it can still be used with `dd.trace.client-ip-header=x-forwarded`  (system property) of `DD_TRACE_CLIENT_IP_HEADER=x-forwarded` (environment variable).
The header is still collected on security events.
Support for parsing RFC 7239 (`Forwarded` format) is still maintained.
Jira ticket: …
> Remove support for X-Forwarded in client IP resolution

- dd-smoke-tests/springboot-openliberty-20/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySmokeTest.groovy
- dd-smoke-tests/springboot-openliberty-20/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySmokeVulnerabilityTest.groovy
- dd-smoke-tests/springboot-openliberty-23/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySmokeTest.groovy
- dd-smoke-tests/springboot-openliberty-23/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySmokeVulnerabilityTest.groovy
This PR replaces usage of the `JAVA_TOOL_OPTIONS` environment variable by the `jvm.options` server configuration file from OpenLiberty.
The `JAVA_TOOL_OPTIONS` is limited to 1024 characters on some Java versions and it starts reaching the limit.
I also tried `JVM_ARGS` environment variable but it was not picked by our deployment method (runnable jar).
As multiple specifications can use the same runnable jar at the same time (when running tests in parallel), the jar is copied before injecting configuration.
This is a fix required to enable crash-tracking more widely in our system tests #7855 
> Replace JAVA_TOOL_OPTIONS by jvm.options OpenLiberty server configuration file

- dd-java-agent/agent-bootstrap/src/main/resources/META-INF/native-image/com.datadoghq/dd-java-agent/reflect-config.json
Both fromJson and toJson methods need to be registered even if only one is used, do the same for other JSON entries to be consistent.
When an incoming request has both Datadog and W3C headers we add a span link to the local trace. For traced native-images this will result in `NoClassDefFoundError: Could not initialize class DDSpanLink$EncoderHolder` caused by the missing `fromSpanLinkJson` reference, even though it's not used in practice.
Also declare some JsonRule types need reflective access for a related issue using DD_TRACE_SAMPLING_RULES
Jira ticket: [APMAPI-928]
[APMAPI-928]: https://datadoghq.atlassian.net/browse/APMAPI-928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
> Fix NoClassDefFoundError: Could not initialize class DDSpanLink$EncoderHolder in Graal native-image

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/PortUtils.java
- dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractServerSmokeTest.groovy
- dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
- dd-smoke-tests/src/main/groovy/datadog/smoketest/ProcessManager.groovy
Adds crash tracking into integration tests
Now that single step installer is using crash tracking, want to expand crash tracking coverage in CI
For now, crash tracking is selectively enabled for a subset of integration tests.
The intention is that future pull requests will broadened the coverage.
Right now, the means of argument construction is incompatible with the tests that pass arguments via JAVA_TOOL_OPTIONS.
IAST tests have also been excluded
> Adding crash tracking to integration tests

- dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringBuilderCallSite.java
- dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/StringBuilderCallSiteTest.groovy
- dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestAbstractStringBuilderSuite.java
- dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringBufferSuite.java
- dd-java-agent/instrumentation/java-lang/src/test/java/foo/bar/TestStringBuilderSuite.java
This adds the instrumentation to propagate the taint values through the following methods of `StringBuilder`:
- `subSequence(int, int)`
Increase propagation of `StringBuilder` methods.
In this PR it has been made one refactor in the tests to make them clear.
Jira ticket: [APPSEC-55360]
[APPSEC-55360]: https://datadoghq.atlassian.net/browse/APPSEC-55360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Increase IAST propagation to StringBuilder subSequence

- dd-smoke-tests/jersey-2/src/test/groovy/datadog/smoketest/Jersey2SmokeTest.groovy
- dd-smoke-tests/jersey-3/src/test/groovy/datadog/smoketest/Jersey3SmokeTest.groovy
- dd-smoke-tests/play-2.4/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy
- dd-smoke-tests/play-2.5/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy
- dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/PlaySmokeTest.groovy
- dd-smoke-tests/play-2.7/src/test/groovy/datadog/smoketest/PlaySmokeTest.groovy
- dd-smoke-tests/play-2.8-otel/src/test/groovy/datadog/smoketest/Play28OTelSmokeTest.groovy
- dd-smoke-tests/play-2.8-split-routes/src/test/groovy/datadog/smoketest/PlaySmokeTest.groovy
- dd-smoke-tests/play-2.8/src/test/groovy/datadog/smoketest/PlaySmokeTest.groovy
- dd-smoke-tests/resteasy/src/test/groovy/smoketest/ResteasySmokeTest.groovy
- dd-smoke-tests/springboot-tomcat/src/test/groovy/datadog/smoketest/SpringBootTomcatSmokeTest.groovy
- dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
- dd-smoke-tests/wildfly/src/test/groovy/datadog/smoketest/WildflySmokeTest.groovy
While crash tracking was enabled in #7855 invalid escaping was put in place, leading the install the crash tracking uploader script at a wrong location.
This PR removes the escaping which was not needed for the Java Process API nor OpenLiberty `jvm.options` file and make sure escaping is set up for environment variables like tomcat `CATALINA_OPT` and Netty / Wildfly `JAVA_OPTS`.
Trying to escape the space ` ` lead to installing the crash tracking uploader script in `<current_dir>/"/tmp/dd_crash_uploader.sh`.
This PR is a follow up of #7855 
> Fix crash tracking setup in smoke test

- internal-api/src/main/java/datadog/trace/api/iast/IastModule.java
Set logs from `IastModule#onUnexpectedException` to debug level.
Unexpected exceptions in IAST, when caught by `IastModule#onUnexpectedException` should be safe for the application. Logging to warning level has sometimes become the source of problems for some customers (e.g. most recently, broken log format).
These exceptions should not happen, but when they do, they may happen frequently.
We will still received redacted exceptions through telemetry, so we'll continue to proactively fix them without bothering end users.
- ~[ ] Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new configuration flag or …
> Set unexpected IAST exceptions to debug log level

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/BaseDecoratorTest.groovy
- dd-java-agent/instrumentation/armeria-grpc/src/main/java/datadog/trace/instrumentation/armeria/grpc/server/GrpcServerDecorator.java
- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcServerDecorator.java
Avoid overriding the error flag of grpc server spans if manually set. This leverage using a lower priority when setting the error flag by the decorator.
This solves #8042 
> Use lower priorities for grpc server errors

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/InstrumentationResult.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MethodInfo.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/CodeOriginProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/ClassFileLines.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/origin/CodeOriginTest.java
This PR uses the class parsing during instrumentation to extract out more accurate entry span information
caches that information to reuse it on commit()
Jira ticket: [DEBUG-3159]
[DEBUG-3159]: https://datadoghq.atlassian.net/browse/DEBUG-3159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cache entry span code origin information to avoid unnecessary repeated stack walks.

- dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/OOMENotifierScriptInitializer.java
This PR avoids logging stack trace when failing to clean up previous crash tracking configuration files.
Avoid showing exception message to the customers for clean up operations
> Improve crash tracking install logging

- dd-java-agent/instrumentation/grpc-1.5/build.gradle
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcCodeOriginTest.groovy
Simplifies even further by dropping the use of mocks
> Use stubs instead of mocks

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/codeorigin/DefaultCodeOriginRecorder.java
- dd-java-agent/instrumentation/micronaut/build.gradle
- dd-java-agent/instrumentation/micronaut/http-server-netty-4.0/build.gradle
- dd-java-agent/instrumentation/micronaut/http-server-netty-4.0/src/main/java/datadog/trace/instrumentation/micronaut/v4_0/MicronautCodeOriginInstrumentation.java
- dd-java-agent/instrumentation/micronaut/http-server-netty-4.0/src/test/groovy/MicronautTest.groovy
- dd-java-agent/instrumentation/micronaut/src/main/java/datadog/trace/instrumentation/micronaut/MicronautCodeOriginInstrumentation.java
- dd-java-agent/instrumentation/span-origin/src/main/java/datadog/trace/instrumentation/codeorigin/CodeOriginInstrumentation.java
- dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Make Code Origin for spans feature independent from dynamic instrumentation so it could be enabled while DI is not Add in Status Logger the code origin feature status
Jira ticket: [DEBUG-3162]
[DEBUG-3162]: https://datadoghq.atlassian.net/browse/DEBUG-3162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Micronaut 4 support for code origin for spans

- dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
Notification that support for custom OpenTracing `ScopeManager`s in `dd-trace-ot` will soon be removed (expected v1.45.0) as part of a refactoring to improve support for generic `Context`s across the `dd-trace-java` codebase.
Jira ticket: [APMAPI-953]
[APMAPI-953]: https://datadoghq.atlassian.net/browse/APMAPI-953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Custom ScopeManagers are deprecated and will be removed in a future release of dd-trace-ot

- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
- dd-trace-api/src/main/java/datadog/trace/api/interceptor/AbstractTraceInterceptor.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/traceinterceptor/LatencyTraceInterceptor.java
- dd-trace-core/src/test/groovy/datadog/trace/core/traceinterceptor/LatencyTraceInterceptorTest.groovy
- internal-api/src/main/java/datadog/trace/api/Config.java
Add the possibility to enable a latency trace interceptor 
This latency trace interceptor is disabled by default.
We can activate it by setting the value of `dd.trace.experimental.keep.latency.threshold.ms`  or `DD_TRACE_EXPERIMENTAL_KEEP_LATENCY_THRESHOLD_MS` to a positive value
This value should be **in milliseconds** and this interceptor will retain any local trace who has a root span duration greater than this value.
The activation of this interceptor is ignored if partial flush is enabled in order to avoid incomplete local trace (incomplete chunk of trace).
Note that since we're changing the sampling priority at the end of local trace, there is no guarantee to get complete traces,
since the original sampling priority for this trace may have already been propagated.
**### Usage:** …
> Add a built-in trace interceptor for keeping traces depending of their latency

- dd-java-agent/instrumentation/jakarta-jms/src/main/java/datadog/trace/instrumentation/jakarta/jms/MDBMessageConsumerInstrumentation.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MDBMessageConsumerInstrumentation.java
Ensure that we do not create multiple span for `jms.consume` if proxies are delegating the same method call in a nested way
> Protect mdb from instrumenting multiple time the same event

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ProxyClassIgnores.java
Jboss creates synthetic proxies for each mdb onMessage. They are marked by the `$$$endpointXXX` name
> Exclude jboss mdb proxies from instrumenting

- .circleci/config.continue.yml.j2
Fix debugger system tests logs upload
> Fix debugger system tests CI logs upload

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ConfigurationApiImpl.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/config/ConfigurationApiImplTest.groovy
Fixes NPE in logic that parses the list of flaky tests received from the backend.
The error only happens when a "partial build" is run for a single module.
> Fix NPE in logic that parses flaky tests list

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/messaging/DatadogAttributeParser.java
- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/MessageExtractAdapter.java
- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/SqsClientTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
For SQS v1, when raw message delivery is disabled (when sns is upstream) parse the message to extract message attributes.
The extraction is behind a flag to avoid unwanted overhead.
For v2 of SQS, I will probably need to add a dependency on Jackson, that is there by default for Sqs v1, which makes things easier.
> Data streams support in sqs without raw message delivery

- .github/pull_request_template.md
- .github/workflows/check-pull-requests.yaml
- .github/workflows/tests/check-pull-requests/payload-pull-request-draft.json
- .github/workflows/tests/check-pull-requests/payload-pull-request-instrumentation.json
- .github/workflows/tests/check-pull-requests/payload-pull-request-linking-issue.json
- .github/workflows/tests/check-pull-requests/payload-pull-request-missing-label.json
- .github/workflows/tests/check-pull-requests/payload-pull-request-no-release-notes.json
- .github/workflows/tests/check-pull-requests/payload-pull-request.json
- .github/workflows/tests/check-pull-requests/test-pull-request.sh
This PR improves the PR checks automation and template:
* Fix missing ready_for_review event
* Add issue liking keyword detection
* Replace the checklist by a simple list as the workflow does most of the checks automatically
* Remove the squash your commits entry from the checklist as it is now enforced in GitHub repository settings
Automate more checks
> Update PR checks automation

- dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- telemetry/src/main/java/datadog/telemetry/dependency/DependencyService.java
Add new APPSEC_DEPENDENCY_RESOLUTION_PERIOD_MILLIS env variable to be able to configure the dependency service resolution period
For testing environments the default 1 second period is excessive
> Add configurable Dependency service resolution period

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Instrumentor.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
suspend methods in Kotlin generates a special bytecode for the method with a state machine and could return different objects. for each return branch we need to have a specific return handler to avoid having mismatch stack maps.
Add new config parameter to be able to disable local var hoisting that can be problematic in some situations.
Detects language and only enable hoisting for Java. 
support `suspend` Kotlin methods …
> Fix suspend Kotlin methods instrumentation

- dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringBuilderCallSite.java
- dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/StringBuilderCallSiteTest.groovy
This adds the instrumentation to propagate the taint values through the following methods of `StringBuffer`:
- `append(CharSequence, int, int)`
- `append(StringBuffer)`
Increase propagation of `StringBuffer` methods. …
> Increase IAST propagation to StringBuffer append

- dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
Adds `lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler` to the list of ignored classes.
It seems that, under the hood, aws lambda wraps non-streaming handlers in an internal streaming handler class. This allows them to execute these two different kinds of lambda functions in a single unified way.
However, since this internally wrapping handler is also matching our advice matchers, it gets instrumented as well. Mostly, that is not an issue, except for the fact that it means we're unable to capture the return value of the original handler function.
In the non-streaming case, since the internal streaming handler class is wrapping the customer's handler function, the streaming instrumentation gets executed first. This means that, for the `OnMethodExit` we cannot grab the handler's …
> Add avoid double instrumenting lambda non-streaming handlers.

- .circleci/config.continue.yml.j2
```
Build runner
Build virtual env
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.
apt install python3.12-venv
You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.
Failing command: /home/circleci/project/system-tests/venv/bin/python3.12
```
- Don't use `close`, `fix` or any …
> Fix system-tests build: requires python3.12-venv

- buildSrc/build.gradle.kts
- buildSrc/call-site-instrumentation-plugin/build.gradle.kts
- gradle/libs.versions.toml
https://asm.ow2.io/versions.html
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java …
> Upgrade to ASM 9.7.1 (adds new constant for Java 24)

- dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleLauncherSmokeTest.groovy
Disables Git data upload in Gradle Launcher smoke test: the mock backend that is used by the test does not implement endpoints that are called for Git data upload.  …
> Fix flakiness in Gradle Launcher smoke test

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
- internal-api/src/main/java/datadog/trace/api/gateway/IGSpanInfo.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Refactored `requiresPostProcessing` flag. Now we are able to set post-processing flag from `AppSec` module
This is preparation work for new API Security Sampling …
> Refactored requires post-processing flag

- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/main/java/datadog/trace/instrumentation/aws/v1/sqs/SqsDecorator.java
- dd-java-agent/instrumentation/aws-java-sqs-1.0/src/test/groovy/SqsClientTest.groovy
- dd-java-agent/instrumentation/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/SqsDecorator.java
- dd-java-agent/instrumentation/aws-java-sqs-2.0/src/test/groovy/SqsClientTest.groovy
- dd-java-agent/instrumentation/google-pubsub/src/main/java/datadog/trace/instrumentation/googlepubsub/PubSubDecorator.java
- dd-java-agent/instrumentation/jakarta-jms/src/main/java/datadog/trace/instrumentation/jakarta/jms/JMSDecorator.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java17/datadog/trace/instrumentation/kafka_clients38/KafkaDecorator.java
- dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsDecorator.java
- dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
- dd-trace-core/src/jmh/java/datadog/trace/api/naming/MessagingNamingBenchmark.java
- internal-api/src/main/java/datadog/trace/api/naming/NamingSchema.java
- internal-api/src/main/java/datadog/trace/api/naming/v0/MessagingNamingV0.java
- internal-api/src/main/java/datadog/trace/api/naming/v1/MessagingNamingV1.java
- internal-api/src/test/groovy/datadog/trace/api/naming/NamingV0ForkedTest.groovy
If a split-by-jee-deployment is used and the legacy tracing is disabled,  the service name for the message consumers spans will be initialized once with the first value it's obtained. 
This is not correct since in this case it has to be evaluated every time. This PR forces using a supplier for the service name and evaluates it every time when the decorator is setting the service name. In the general case, it will always returns a constant so it should not impact any performance.
- Don't …
> Dynamically evaluate service name for message consumers

- dd-smoke-tests/java9-modules/src/test/groovy/datadog/smoketest/Java9ModulesSmokeTest.groovy
- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/api/Platform.java
... and add warning about accessing JMX too early
> Remove unused Platform.GC code

- internal-api/src/main/java/datadog/trace/api/remoteconfig/ServiceNameCollector.java
ServiceNameCollector.add is called very frequently. This PR aims moving the expensive operations inside it (i.e. string case transformation, default service name deduplication) to the `getServices` method that's called way more infrequently 
Use `solves` …
> Improves ServiceNameCollector

- dd-smoke-tests/armeria-grpc/src/test/groovy/datadog/smoketest/ArmeriaSmokeTest.groovy
- dd-smoke-tests/asm-standalone-billing/src/test/groovy/datadog/smoketest/asmstandalonebilling/AsmStandaloneBillingSmokeTest.groovy
- dd-smoke-tests/custom-systemloader/src/test/groovy/datadog/smoketest/CustomSystemLoaderSmokeTest.groovy
- dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/SsrfController.java
- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastServerSmokeTest.groovy
- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastSpringBootTest.groovy
- dd-smoke-tests/java9-modules/src/test/groovy/datadog/smoketest/Java9ModulesSmokeTest.groovy
- dd-smoke-tests/jboss-modules/src/test/groovy/datadog/smoketest/AbstractModulesSmokeTest.groovy
- dd-smoke-tests/log-injection/src/test/groovy/datadog/smoketest/LogInjectionSmokeTest.groovy
- dd-smoke-tests/osgi/src/test/groovy/datadog/smoketest/AbstractOSGiSmokeTest.groovy
- dd-smoke-tests/quarkus-native/src/test/groovy/datadog/smoketest/QuarkusNativeSmokeTest.groovy
- dd-smoke-tests/quarkus/src/test/groovy/datadog/smoketest/QuarkusSmokeTest.groovy
- dd-smoke-tests/spring-boot-3.0-native/src/test/groovy/SpringBootNativeInstrumentationTest.groovy
- dd-smoke-tests/spring-boot-rabbit/src/test/groovy/datadog/smoketest/SpringBootRabbitIntegrationTest.groovy
- dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
- dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
- dd-smoke-tests/src/main/groovy/datadog/smoketest/ProcessManager.groovy
* Add `boolean isErrorLog(String line)` defining what is considered an error log for a given smoke test. Most smoke tests can just rely on the default. This PR includes several examples on how to extend it, both to add additional errors, or to exclude some errors.
* Add `void assertNoErrorLogs(final Closure<Boolean> errorFilter)`, which can be used to assert there are no error logs. Most tests should not use directly, and when they do, they should do it only after the test process has finished (otherwise, the test may be flaky).
* Call `assertNoErrorLogs` on `cleanupSpec` for every smoke test. Most suites were not checking error logs.
* Use `processTestLogLines` when we need to wait for a log line that is supposed to be printed. This should be less flaky than `assertNoErrorLogs` in the …
> Check logs for errors at smoke tests cleanup

- communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerAgentTest.java
- dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsMonitoring.java
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpInjectorTest.groovy
Agent discovery potentially involves a blocking I/O operation. This should only be run from our own background threads and not from application threads. Note we shouldn't need to wait for the result on the application thread because the tracer code already handles asynchronous upgrade/downgrade scenarios.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-iss …
> Avoid performing blocking I/O operation on application thread

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/DBInfo.java
- dd-java-agent/instrumentation/jdbc/build.gradle
- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractPreparedStatementInstrumentation.java
- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
- dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCDecoratorTest.groovy
- dd-java-agent/instrumentation/jdbc/src/test/groovy/RemoteJDBCInstrumentationTest.groovy
Adding trace injection (full mode APM/DBM) to the Oracle database.
Customers want to get execution plans for SQL spans.
Trace context is passed through the V$SESSION.ACTION field and sampled by the agent. This process adds no database overhead or extra roundtrip, as the JDBC driver defers the instrumentation call and sends it with the next statement.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-reques …
> Add full APM/DBM mode for Oracle

- buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/impl/CallSiteSpecification.java
- buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/util/ErrorCode.java
- buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/AdviceGeneratorTest.groovy
- buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/AdviceSpecificationTest.groovy
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/BaseCallSiteTest.groovy
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteTransformerTest.groovy
- dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/csi/StringBuilderSetLengthCallSite.java
- dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/csi/StringBuilderSetLengthExample.java
Adds support for After callsites in void methods, validations have been updated so:
- Void methods should have void callsites not annotated with `@Return`
- Non void methods should have a return parameter compatible with the call site annotated with `@Return`
As an example:
```java
@CallSite(spi = CallSites)
class AfterAdviceWithVoidReturn {
@CallSite.After("void java.lang.StringBuilder.setLength(int)")
static void after(@CallSite.This StringBuilder self, @CallSite.Argument(0) int length) {
}
}
```
- Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING …
> Add After callsites support for void methods

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/CodeOriginProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/origin/CodeOriginTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CodeOrigin05.java
There are scenarios where multiple code origin probes might want to decorate the local root span, e.g., with information.  This PR ensures this only happens once. …
> Only decorate spans without code origin information 

- components/context/build.gradle.kts
- components/context/src/main/java/datadog/context/Context.java
- components/context/src/main/java/datadog/context/ContextBinder.java
- components/context/src/main/java/datadog/context/ContextKey.java
- components/context/src/main/java/datadog/context/ContextManager.java
- components/context/src/main/java/datadog/context/ContextProviders.java
- components/context/src/main/java/datadog/context/ContextScope.java
- components/context/src/main/java/datadog/context/EmptyContext.java
- components/context/src/main/java/datadog/context/ImplicitContextKeyed.java
- components/context/src/main/java/datadog/context/IndexedContext.java
- components/context/src/main/java/datadog/context/SingletonContext.java
- components/context/src/main/java/datadog/context/ThreadLocalContextManager.java
- components/context/src/main/java/datadog/context/WeakMapContextBinder.java
- components/context/src/test/java/datadog/context/ContextBinderTest.java
- components/context/src/test/java/datadog/context/ContextKeyTest.java
- components/context/src/test/java/datadog/context/ContextManagerTest.java
- components/context/src/test/java/datadog/context/ContextProviderForkedTest.java
- components/context/src/test/java/datadog/context/ContextTest.java
- settings.gradle
This is an initial implementation of the Evolving Context RFC. …
> Introduce a shared context component, independent of tracing.

- communication/build.gradle
- communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
- dd-java-agent/agent-logs-intake/src/main/java/datadog/trace/logging/intake/LogsIntakeSystem.java
- dd-java-agent/agent-logs-intake/src/main/java/datadog/trace/logging/intake/LogsWriterImpl.java
- dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
- dd-java-agent/src/test/groovy/datadog/trace/agent/CustomMBeanServerBuilderTest.groovy
- dd-java-agent/src/test/java/jvmbootstraptest/LogManagerSetter.java
- dd-java-agent/src/test/java/jvmbootstraptest/MBeanServerBuilderSetter.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
1. Add ability to pause remote components until SharedCommunicationObjects is ready for remote I/O
2. Use this to install tracer and logs-intake as soon as necessary, but still defer any remote components until when use of OkHttp is allowed
3. Remove exemption where we didn't defer if the custom logging manager or JMX builder was on the system classpath (because previously the main thread would find it there if OkHttp triggered initialization of JUL.)
We now make OkHttp calls from our own background threads to avoid blocking the main thread, but our threads are isolated from the system classloader - so this exemption no longer makes sense and should be removed
Resolves some spurious failures in the log-injection smoke tests for the IBM Java 8 JDK.
- Format the title [according the …
> Defer remote components to avoid OkHttp class-loading side-effects

- components/context/src/main/java/datadog/context/Context.java
- components/context/src/main/java/datadog/context/ContextBinder.java
- components/context/src/main/java/datadog/context/ContextKey.java
- components/context/src/main/java/datadog/context/ContextManager.java
- components/context/src/main/java/datadog/context/ContextScope.java
- components/context/src/main/java/datadog/context/EmptyContext.java
- components/context/src/main/java/datadog/context/ImplicitContextKeyed.java
- components/context/src/main/java/datadog/context/IndexedContext.java
- components/context/src/main/java/datadog/context/SingletonContext.java
- components/context/src/main/java/datadog/context/ThreadLocalContextManager.java
- components/context/src/main/java/datadog/context/WeakMapContextBinder.java
- components/context/src/test/java/datadog/context/ContextBinderTest.java
- components/context/src/test/java/datadog/context/ContextKeyTest.java
- components/context/src/test/java/datadog/context/ContextManagerTest.java
- components/context/src/test/java/datadog/context/ContextProviderForkedTest.java
- components/context/src/test/java/datadog/context/ContextTest.java
- components/context/src/test/java/datadog/context/ImplicitContextKeyedTest.java
This PR is a follow up of #8117:
* Improve Javadoc about usage and thread safety
* Improve null handling and document parameters and results
* Improve tests to cover all context implementations
The goal is to make the most explicit possible the new API and document how it is supposed to behave with unexpected cases.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-reques …
> Improve Context API null handling and Javadoc

- .github/workflows/analyze-changes.yaml
- .github/workflows/check-pull-requests.yaml
- .github/workflows/update-download-releases.yaml
This would avoid having some GitHub workflows running in parallel.
The goal is to prevent race conditions (PR checks, release asset upload) and save execution time from long running jobs (CodeQL). …
> Add GitHub workflow concurrency settings

- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkModule.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/HandlerChainFactoryInstrumentation.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/RequestExecutorInstrumentation.java
- docs/how_instrumentations_work.md
Provides an example of how to group related instrumentations under a single module.
Grouping related instrumentations reduces repeated declarations of helpers and context store use.
Grouping also makes it easier to re-use instrumentations.
Use `solves` …
> Example of how to group related instrumentations under a single module (AwsSdkModule)

- dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleLauncherSmokeTest.groovy
Increase Gradle build timeout in Gradle Launcher smoke tests from 30s to 60s.
Reduce tests flakiness.
When running the test on IBM Semeru 17 Gradle builds may take longer than 30 seconds. …
> Increase timeout in Gradle Launcher smoke tests

- dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ReactiveClientTest.groovy
Retry opening a connection on lettuce 5 reactive tests
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collecti …
> Retry open connection on lettuce 5 tests

- dd-java-agent/instrumentation/commons-fileupload/src/main/java/datadog/trace/instrumentation/commons/fileupload/CommonsFileuploadInstrumentation.java
- dd-java-agent/instrumentation/commons-fileupload/src/main/java/datadog/trace/instrumentation/commons/fileupload/FileItemInstrumentation.java
- dd-java-agent/instrumentation/commons-fileupload/src/main/java/datadog/trace/instrumentation/commons/fileupload/FileItemIteratorInstrumentation.java
- dd-java-agent/instrumentation/commons-fileupload/src/main/java/datadog/trace/instrumentation/commons/fileupload/FileItemStreamInstrumentation.java
- dd-java-agent/instrumentation/commons-fileupload/src/main/java/datadog/trace/instrumentation/commons/fileupload/ServletFileUploadInstrumentation.java
- dd-java-agent/instrumentation/commons-fileupload/src/test/groovy/FileItemInstrumentationTest.groovy
- dd-java-agent/instrumentation/commons-fileupload/src/test/groovy/FileItemIteratorInstrumentationTest.groovy
- dd-java-agent/instrumentation/commons-fileupload/src/test/groovy/FileItemStreamInstrumentationTest.groovy
- dd-java-agent/instrumentation/commons-fileupload/src/test/groovy/ServletFileUploadInstrumentationTest.groovy
This is so we can direct load requests to a special class-loader that can be unloaded after use.
See https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/DatadogClassLoader.java#L97
Use …
> Consistency: instrumentation classes should be in files ending with `Instrumentation.java`

- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/CombiningTransformerBuilder.java
- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/ShadedAdviceLocator.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AdviceShader.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterModule.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGenerator.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
Introduces the concept of an advice "shader" that can relocate type references before applying the advice or injecting advice helpers into the library/application class-loader.
This makes it possible to share and re-use advice for libraries which may appear under different namespaces, for example `javax.jms` vs. `jakarta.jms`. (Reminder that advice is never loaded directly, instead its bytecode is parsed and patched into the target class.)
We can already account for relocated packages in matchers by providing a namespace when creating `Instrumenter`s from an `InstrumenterModule`, but doing the same for advice bytecode requires using an ASM based remapper.
This is tested by https://github.com/DataDog/dd-trace-java/pull/8155 which uses it to share the `javax` JMS instrumentation with the …
> Support instrumentation of repackaged libraries

- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageProducerInstrumentation.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JavaxJmsModule.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MDBMessageConsumerInstrumentation.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageInstrumentation.java
- dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/SessionInstrumentation.java
Preparation for using the new feature that [supports instrumentation of repackaged libraries](https://github.com/DataDog/dd-trace-java/pull/8153)
Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the …
> Group `javax.jms` instrumentations under a single module

- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSHttpClientInstrumentation.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkModule.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/EmrSdkModule.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/HandlerChainFactoryInstrumentation.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/RequestExecutorInstrumentation.java
Uses the new  [support for instrumentation of repackaged libraries](https://github.com/DataDog/dd-trace-java/pull/8153) to instrument EMR's relocated AWS SDK under `com.amazon.ws.emr.hadoop.fs.shaded`.
Provides observability of AWS SDK calls made from EMR. …
> Instrument EMR's relocated AWS SDK

- dd-java-agent/instrumentation/vertx-web-4.0/build.gradle
edit gradle file to remove exclusion for java 17 for latest dep tests
this restriction was probably copy-pasted from the previous version's gradle file:
https://github.com/DataDog/dd-trace-java/blob/ec18d0e8627c7a4e4f6040778d54685fb99709f4/dd-java-agent/instrumentation/vertx-web-3.9/build.gradle#L3
But vertx supports java 17 now, so we need to test the latest version with it.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-is …
> Remove restriction to not run vertx4 latest tests on java 17

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ReflectiveFieldValueResolver.java
disable telemetry for MethodHandle lookups
can happen frequently (every startup on jdk8) …
> disable telemetry for MethodHandle lookups

- dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/trace/OtelConventions.java
- dd-trace-core/src/main/java/datadog/trace/core/DDSpanLink.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpanLink.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/SpanAttributes.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/SpanLink.java
`AgentSpan.Attributes` has only one implementation and isn't likely to have another, so squash it into `SpanAttributes`.
- Update the …
> Squash AgentSpan.Attributes with SpanAttributes

- .github/workflows/check-pull-requests.yaml
This PR tries to improve blocked PR checks by cancelling already running checks. 
Previously, only pending jobs were canceled. Cancelling running checks might help to have the _latest_ trigger to run instead of being cancelled, leaving the PR check requirements blocked. …
> Cancel running PR check jobs

- dd-java-agent/instrumentation/google-pubsub/src/main/java/datadog/trace/instrumentation/googlepubsub/TextMapExtractAdapter.java
- dd-java-agent/instrumentation/google-pubsub/src/main/java/datadog/trace/instrumentation/googlepubsub/TextMapInjectAdapter.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/NoopTextMapInjectAdapter.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TextMapExtractAdapter.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TextMapInjectAdapter.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TextMapInjectAdapterInterface.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java17/datadog/trace/instrumentation/kafka_clients38/NoopTextMapInjectAdapter.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java17/datadog/trace/instrumentation/kafka_clients38/TextMapExtractAdapter.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java17/datadog/trace/instrumentation/kafka_clients38/TextMapInjectAdapter.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java17/datadog/trace/instrumentation/kafka_clients38/TextMapInjectAdapterInterface.java
- dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/ProcessorRecordContextSetter.java
- dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/ProcessorRecordContextVisitor.java
- dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/StampedRecordContextSetter.java
- dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/StampedRecordContextVisitor.java
- dd-trace-core/src/main/java/datadog/trace/core/datastreams/DataStreamContextInjector.java
- dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
- dd-trace-core/src/test/groovy/datadog/trace/core/datastreams/DefaultPathwayContextTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentPropagation.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/PathwayContext.java
This PR cleans up the `BinarySetter` API used to inject binary data during context propagation.
This API was only used by DSM for Pathway context injection and is no more used.
Currently, only the `dd-pathway-ctx-base64` key is injected / extracted and is a base64 string.
The legacy `dd-pathway-ctx` was already no more used.
This is preliminary refactoring work for the new context propagation API.  …
> Clean up DSM pathway binary encoding

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- fixes the issue create screen to allow github issues
- note the errors on these two screens
- https://github.com/DataDog/dd-trace-java/blob/master/.github/ISSUE_TEMPLATE/bug_report.yaml
- https://github.com/DataDog/dd-trace-java/blob/master/.github/ISSUE_TEMPLATE/feature_request.yaml
- seems to be a parsing issue of the YAML files
- missing entries on this screen
- https://github.com/DataDog/dd-trace-java/issues/new/choose
- YAML is horrible …
> fix github issue creation

- internal-api/build.gradle
Skip coverage checks for `ClassloaderConfigurationOverrides` …
> Skip jacoco coverage for internal class

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
capture of traceId/SpanId was directly instrumented.
it means that every execution of the probe try to fetch from the span
the traceId and the spanId with eventual conversion to make it a
string. While in the end we may have a condition that is not met or
the sampling does not generate a snapshot. which is wasteful.
We just move the capture at the commit time when we are sure to send a
snapshot with these information.
optimization …
> Move Trace/SpanId capture at commit time

- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/CombiningTransformerBuilder.java
- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/ShadedAdviceLocator.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AdviceShader.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
Backport #8192 to release/v1.45.x
> Ensure shaded helpers have unique names when injected into class-loaders

- dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/RoutingContextImplInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/RoutingContextSessionAdvice.java
- dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/VertxHttpServerForkedTest.groovy
- dd-java-agent/instrumentation/vertx-web-3.4/src/test/java/server/VertxTestServer.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextImplInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextSessionAdvice.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/server/VertxHttpServerForkedTest.groovy
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/java/server/VertxTestServer.java
Adds support for session tracking in vert.x 3.x and 4.x
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collect …
> Add support for session tracking in Vertx

- dd-java-agent/instrumentation/gradle-8.3/src/main/groovy/datadog/trace/instrumentation/gradle/AndroidGradleUtils.groovy
Backport #8190 to release/v1.45.x
> 🍒 8190 Fix source and destination folders computation for Android Gradle projects

- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/TempLocationManager.java
- dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/TempLocationManagerTest.java
It fixes the the problem caused by the usage of `CompletableFuture` in the manager.
It avoids forking `jps` unless there is something to clean up.
It avoids removing JFR repository during self-cleanup in order to avoid clashing with the JFR shutdown.
Prevent unexpected behaviour, reduce the overhead.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-us …
> TempLocationManager Fixes and Improvements

- components/context/src/main/java/datadog/context/Context.java
- components/context/src/main/java/datadog/context/ContextBinder.java
- components/context/src/main/java/datadog/context/ContextKey.java
- components/context/src/main/java/datadog/context/package-info.java
- components/context/src/main/java/datadog/context/propagation/CarrierSetter.java
- components/context/src/main/java/datadog/context/propagation/CarrierVisitor.java
- components/context/src/main/java/datadog/context/propagation/CompositePropagator.java
- components/context/src/main/java/datadog/context/propagation/Concern.java
- components/context/src/main/java/datadog/context/propagation/NoopPropagator.java
- components/context/src/main/java/datadog/context/propagation/Propagator.java
- components/context/src/main/java/datadog/context/propagation/Propagators.java
- components/context/src/main/java/datadog/context/propagation/package-info.java
- components/context/src/test/java/datadog/context/propagation/ConcernTest.java
- components/context/src/test/java/datadog/context/propagation/PropagatorsTest.java
This PR introduce the new context propagation API based on the new context tracking API.
It is similar to the original Agent Tracing propagation API but:
* decouples propagation from tracing
* allows declaration and registration of multiple propagators, not only tracing
* allows using default propagators or specific ones
* introduce concerns as a way to distinguish propagators, their features, and their ordering
Allows products and feature teams to propagate their own data from / to upstream service without relying on Tracing / Spans / Propagation Tags.
This PR only introduces the API. Porting the existing Tracing propagation implementation, decoupling product / feature data Tracing data model will come in following PRs.
- Format the title [according the contribution …
> Introduce context propagation API

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ExceptionProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/TriggerProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
method probe when `evaluateAt` is `EXIT` and no condition should capture entry values. When there is a condition, entry values are not captured instrumentation check the presence of the condition to generate the entry instrumentation or not. therefore, the dummy definition used when duplicate probes need to merge the probe conditions if at least one probe has one condition.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issu …
> Capture values at entry for method probe

- dd-smoke-tests/field-injection/src/main/java/datadog/smoketest/fieldinjection/FieldInjectionApp.java
- dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy
Separate stdout from stderr to avoid tracer logging from interfering with smoke-test parsing
Avoids tracer logging (which goes to stderr) from interfering with the test application logging. For example an I/O exception stack trace caused by there not being an agent to connect to might break up logging from the test application, making those lines non-parseable and failing the test.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-w …
> Remove flakiness from field-injection smoke test

- .circleci/config.continue.yml.j2
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/Redaction.java
Remove `env` from list of tokens to redact from Dynamic Instrumentation probe snapshots.
Depends on: https://github.com/DataDog/system-tests/pull/3827
Feature parity …
> Don't redact env tokens from debugger probe snapshots

- dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/ScriptInitializer.java
- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/TempLocationManager.java
We use the thread group to avoid doing certain work (such as exception profiling) on our own threads. …
> Make sure background/shutdown threads are in AGENT_THREAD_GROUP

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/Ranges.java
This modifies how excluded sources are added to the builder.
The previous implementation was flawed because the constructor’s parameter represented the size of the bitset in bits, corresponding to the largest bit addressable. …
> Fix BitSet builder in VulnerabilityTypes

- dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/RoutingContextSessionAdvice.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextSessionAdvice.java
Move blocking behavior to method enter in vert.x session tracking. …
> Use method enter advices for vert.x session blocking

- communication/src/test/groovy/datadog/communication/ddagent/SharedCommunicationsObjectsSpecification.groovy
- internal-api/src/main/java/datadog/trace/api/Config.java
Handles IPv6 values for `DD_AGENT_HOST` by removing potential brackets, and adding them back to ipv6 hosts when compiling the value for `DD_TRACE_AGENT_URL`. This PR is tested through system-tests specific to ipv6 addresses. ([IPv6 Test](https://github.com/DataDog/system-tests/pull/3624/files#diff-c76e1dc0fb4d7f8be2b6841b5b99eeef909d085edb2ea69d5820e3ee40c9f5b7R1-R11), [DD_AGENT_HOST vs DD_TRACE_AGENT_URL priority tests](https://github.com/DataDog/system-tests/pull/3745/files#diff-8602b9b4b892f35d1f563f4339c5e9a07b6b55663e3f25202a7fc23edbf339a1R173-R215))
There have previously been escalation issues with IPv6 addresses used for `DD_AGENT_HOST` where the lack of brackets in the compiled `DD_TRACE_AGENT_URL` is missing brackets and leading to errors with calls being made from …
> Support IPv6 values for `DD_AGENT_HOST` and `DD_TRACE_AGENT_URL`

- dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
Use parallelism to execute http server request for the scenario `test success with #count requests` 
Improves issue detection of multithreaded cases. I'll need also to test a fix for vertx worker context propagation in case of multiple parallel requests
Use …
> Test http server requests in parallel

- dd-java-agent/instrumentation/karate/build.gradle
Avoid using the version of the JDK used to run gradle (always 8 in CI) to select karate version to test. Before this PR, `test` tested karate 1.0.0, and `latestDepTest` always tested karate 1.3.1 and never 1.4.0+ (in CI). Now:
* `test` -> 1.0.0
* `karate131Test` -> 1.3.1
* `latestDepTest` -> 1.4.0+
Part of fixes to decouple the JDK used for compile/test from the one used by gradle.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-w …
> Decouple test JDK and gradle JDK in karate latestDepTest

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
Clears all cached subscriptions when a new configuration is pulled from RC.
In certain scenarios (specially in system-tests) configs might contain rules only for a subset of addresses, meanwhile a future config might change them completely. Every time we pull a new configuration from RC we must clear all cached subscriptions to ensure consistency.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-t …
> Ensure cached subscriptions are cleared on reconfiguration via RC

- dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
- dd-java-agent/src/test/groovy/datadog/trace/agent/CustomMBeanServerBuilderTest.groovy
These tests historically set a dummy DD_API_KEY because that was required by the profiler. However setting DD_API_KEY will now result in these tests reaching out to the intake/backend because they won't be able to connect to an agent and the fallback for certain features like telemetry is to try and contact intake (these tests are not run alongside any test agent.)
When the call to intake/backend stalls this can lead to flaky timeouts.
We shouldn't be contacting the real intake during testing so this removes the dummy api-keys from CustomLogManagerTest and CustomMBeanServerBuilder.
This is ok because profiling no longer needs DD_API_KEY set locally.
> Remove flakiness from CustomLogManagerTest and CustomMBeanServerBuilder

- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/WrapRunnableAsNewTaskInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-4.0/build.gradle
- dd-java-agent/instrumentation/vertx-web-4.0/src/latestDepTest/groovy/server/VertxHttpServerForkedTest.groovy
- dd-java-agent/instrumentation/vertx-web-4.0/src/latestDepTest/groovy/server/VertxServer.groovy
- dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/client/HttpClientRequestBaseInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/client/VertxHttpClientForkedTest.groovy
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/server/IastVertxHttpServerTest.groovy
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/server/VertxHttpServerForkedTest.groovy
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/server/VertxServer.groovy
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/java/server/VertxTestServer.java
This PR fixes broken context propagation between the netty event loop and the vertx worker. The issue seems to be present only for latest 4.x (i.e 4.5.x) version where vertx uses a dedicated executor service to dispatch worker tasks.
It's not present on 5.x nor in early 4.0 version where a task queue was used.
It also fixes vertx http client http error capturing that was broken on 4.5+ …
> Fix vertx worker propagation and error handling

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/DebugSessionStatus.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/TriggerProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/DebuggerSink.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturingTestBase.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/LogProbeTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/trigger/TriggerProbeTest.java
Enhances log probes to honor session id tags for live debugger support. …
> Enhance log probes to honor debug session tags

- dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
Reverts DataDog/dd-trace-java#8073
This caused a tracing regression on Lambda (serverless) where AWS inferred spans were no longer being created.
Built and test manually; inferred spans now work on this branch:
> Revert "Add avoid double instrumenting lambda non-streaming handlers."

- dd-java-agent/instrumentation/karate/build.gradle
Updates Gradle task that compiles latest dependency tests for Karate to use Java 11.
Karate 1.4.0+ is built with Java 11.
- Update the …
> Compile latest dep tests for Karate with Java 11

- .circleci/config.continue.yml.j2
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ReflectiveFieldValueResolver.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
Adds a `check_debugger` job to CI.
Add forbidden apis suppressions required to pass.
It seems that ever since we split the `check` job, the debugger variant was never added. …
> Add check_debugger job to CI

- dd-java-agent/instrumentation/gradle-8.3/src/main/groovy/datadog/trace/instrumentation/gradle/AndroidGradleUtils.groovy
- dd-java-agent/instrumentation/gradle-8.3/src/main/groovy/datadog/trace/instrumentation/gradle/CiVisibilityGradleListenerInjector_8_10.java
- dd-java-agent/instrumentation/gradle-8.3/src/main/groovy/datadog/trace/instrumentation/gradle/CiVisibilityGradleListenerInjector_8_3.java
- dd-java-agent/instrumentation/gradle-8.3/src/main/groovy/datadog/trace/instrumentation/gradle/CiVisibilityPlugin.java
- dd-java-agent/instrumentation/gradle-8.3/src/main/groovy/datadog/trace/instrumentation/gradle/CiVisibilityPluginExtension.java
Adds some debug logging to the logic that determines module layouts for Android Gradle projects.
Simplify debugging issues in Android Gradle projects. …
> Add debug logging to Android Gradle module layout logic

- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGUtils.java
Fixes an NPE that was written to the logs when trying to get Test NG retry analyzer for test result instances that had no test method associated with them.
The exception was caught and null was returned.
Now a null-check is done and null is returned without throwing an exception, so the there is no spamming the logs.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-reque …
> Fix NPE when trying to get retry analyzer in Test NG

- tooling/backport-pr-to-patch-release.sh
This PR fixes the back porting PR script to not use tag in PR names.
PR tags are forbidden from contribution guidelines and the recent PR check automation block them. …
> Remove tag from backported PR titles

- dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.3/src/test/kotlin/KotlinCoroutineTests.kt
- dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.5/src/test/kotlin/KotlinCoroutineTests.kt
- dd-java-agent/instrumentation/kotlin-coroutines/src/testFixtures/groovy/datadog/trace/instrumentation/kotlin/coroutines/AbstractKotlinCoroutineInstrumentationTest.groovy
- dd-java-agent/instrumentation/kotlin-coroutines/src/testFixtures/kotlin/datadog/trace/instrumentation/kotlin/coroutines/CoreKotlinCoroutineTests.kt
This PR is a follow up PR of #8238 to add more failing test cases of kotlin coroutine context tracking instrumentation.
The current context tracking improvements might help with tackling such issues.
Adding them to the test suite to check our improvements against the failing cases.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) …
> Add failing Kotlin coroutine tests

- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/user/AppSecEventTrackerSpecification.groovy
- dd-java-agent/instrumentation/spring-security-5/src/main/java/datadog/trace/instrumentation/springsecurity5/AppSecDeferredContext.java
- internal-api/src/main/java/datadog/trace/api/appsec/AppSecEventTracker.java
Prevents a NPE reported by a customer when a user login action is triggered and no callbacks have been subscribed for the user event.
- …
> Prevents a NPE when there is no subscriber for user events

- dd-smoke-tests/java9-modules/src/test/groovy/datadog/smoketest/Java9ModulesSmokeTest.groovy
It reverts the change disabling profiling in Java9ModulesSmokeTest
The underlying bug in the profiler was fixed so it is safe to enable it again such that we have also profiling coverage. …
> Re-enable profiler for Java9ModulesSmokeTest

- .github/workflows/analyze-changes.yaml
This PR upgrade the actions/cache action as it's deprecated and will stop working.
Check https://github.com/actions/cache/discussions/1510 for context …
> Upgrade actions/cache before it breaks

- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/user/AppSecEventTrackerSpecification.groovy
- dd-java-agent/instrumentation/spring-security-5/src/main/java/datadog/trace/instrumentation/springsecurity5/AppSecDeferredContext.java
- internal-api/src/main/java/datadog/trace/api/appsec/AppSecEventTracker.java
Backport #8258 to release/v1.45.x
> 🍒 8258 - Prevents a NPE when there is no subscriber for user events

- components/context/src/main/java/datadog/context/Context.java
- components/context/src/test/java/datadog/context/ContextTest.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Constants.java
- dd-java-agent/build.gradle
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/SpockRunner.java
- gradle/dependencies.gradle
- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InternalContextKeys.java
Supports using implementations of `AgentSpan` as `Context`.
Helps migration of tracing towards the context-based approach.
A convenience method was added to `Context` that accepts a pair of key-value mappings. This lets custom root context implementations skip creation of the interim context when adding two entries at the same time, for example a span and a baggage holder. We do not expect to require further variants of this method, but this particular case is worth adding to reduce copying when inflating spans into full contexts. …
> Allow use of span as a primordial context

- internal-api/src/main/java/datadog/trace/api/git/GitInfoProvider.java
Moves computation of git repository null path into static variable
Provides a 3% improvement on span creation benchmarks
> Optimize Git repository information computation

- dd-java-agent/instrumentation/avro/src/main/java/datadog/trace/instrumentation/avro/SchemaExtractor.java
- dd-java-agent/instrumentation/protobuf/src/main/java/datadog/trace/instrumentation/protobuf_java/SchemaExtractor.java
- dd-java-agent/instrumentation/protobuf/src/test/groovy/com/datadog/instrumentation/protobuf/AbstractMessageInstrumentationTest.groovy
- dd-java-agent/instrumentation/protobuf/src/test/groovy/com/datadog/instrumentation/protobuf/DynamicMessageInstrumentationTest.groovy
- dd-trace-core/src/main/java/datadog/trace/core/datastreams/SchemaBuilder.java
- dd-trace-core/src/test/groovy/datadog/trace/core/datastreams/SchemaBuilderTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/SchemaBuilder.java
Change the way the hash is computed for protobuf schemas:
- to catch some changes that impact the wire format but were not changing the hash before (like changing a field number for instance)
- to stay constant on changes that don't impact the wire format, but were changing the hash before (like reorganizing fields without changing their number)
It should also be marginally faster as we don't hash a whole string, and also isolates the hash from json shennanigans like the OpenAPI version for instance.
This new hash computation is aligned with what's done in the dotnet version of the instrumentation in https://github.com/DataDog/dd-trace-dotnet/pull/6166
ℹ️  Also add protobuf number to the OpenAPI schema saved, so that we can reconstruct the hash if needed, and also because it's an …
> Change hash computation for protobuf to better represent impacting changes + save proto number in schema

- dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/ApacheHttpAsyncClientInstrumentation.java
- dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/TraceContinuedFutureCallback.java
- dd-java-agent/instrumentation/apache-httpclient-5/src/test/groovy/ApacheHttpAsyncClient5Test.groovy
- dd-java-agent/instrumentation/apache-httpclient-5/src/test/groovy/ApacheHttpClientTest.groovy
Re-enable testing of latestDep for the async client case. In fact, because all those tests was forked, we were not executing them on the latestDep since there was no declaration of `latestDepForkedTest`
Instead adding a task we can run not forked the V0 naming test cases since they do not need to run forked. There is no need to run the v1 naming test on the latestDep since the naming is not depending to the version we're testing.
Running the tests I observed that the async test cases were timeouting because the spans was never finished. In fact, `extractResponseFromContext` was not protecting the context object access with a null check. The latest versions of http client 5 seems not to provide a context. However the future contains the response that can be used. That fix mitigate this …
> Properly finish spans and support latest apache httpclient5

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ConfigurationApiImpl.java
- dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
- dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/dto/CrashLog.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/ProbeId.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/Snapshot.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/taint/TaintedObjects.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
- gradle/forbiddenApiFilters/main.txt
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/main/java/datadog/trace/util/RandomUtils.java
- internal-api/src/test/java/datadog/trace/util/RandomUtilsTest.java
- remote-config/remote-config-core/src/main/java/datadog/remoteconfig/PollerRequestFactory.java
This avoids a potential side-effect of loading `java.util.logging` too early when the Amazon Corretto Crypto Provider (ACCP) is plugged into `SecureRandom`
Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestone …
> Replace UUID.randomUUID() with RandomUtils.randomUUID()

- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturingTestBase.java
make a clear distinction when creating method probes and line probes Removing lines varargs to use int for helper methods Use dedicated line probe ids in preparation of
id-based line probe source matching …
> Refactor CapturedSnapshotTest method/line probes

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/ExceptionInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ExceptionProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/exception/ExceptionProbeInstrumentationTest.java
When there is only exception probes at a specific ode location we strip down the instrumentation to only capture values inside the catch (when an exception happens). this way, in normal execution no overhead is pay for an exception probe
Decrease overhead for exception probes when no exception
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-k …
> Add Exception probe custom instrumentation

- .github/workflows/update-docker-build-image.yaml
This PR fixes the CircleCI builder image configuration (no `-base` should be included, only the base of the tag) 
This is a follow up PR of #8206 
I could not find a way to test locally without messing with repository PRs. 
At some point, I stopped testing on prod and this bug slipped in 😬 
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyw …
> Fix Docker build image update automation

- dd-java-agent/agent-profiling/profiling-uploader/build.gradle
- dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
- dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Adds a tag for profiles collected on serverless
Avoid over-billing …
> Tag profiles for serverless

- .circleci/config.continue.yml.j2
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/DefaultExceptionDebugger.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/exception/ExceptionProbeManager.java
As Exception replay is supported by default for intermediate spans we can end up in a situation where 2 spans are attaching the same exception with the snapshots. in that case
DebuggerContext::handleException is called twice, once for each span and we are also sending the same snapshots to the backend while only one version is necessary and we tag it to the according spans. We can just make sure we are sending the snapshots only once. …
> Avoid double snapshots for Exception Replay

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SnapshotSink.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/LogProbeTest.java
> Institute a 10 snapshot per probe per trace budget

- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/MetricProbesInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SpanDecorationProbeInstrumentationTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/trigger/TriggerProbeTest.java
- dd-java-agent/agent-debugger/src/test/java/utils/InstrumentationTestHelper.java
- dd-java-agent/agent-debugger/src/test/java/utils/TestHelper.java
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot01.java
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot02.java
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot03.java
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot04.java
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot05.java
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot06.java
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot07.java
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot08.java
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot101.scala
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot201.groovy
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot301.kt
- dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot302.kt
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot10.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot11.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot18.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot20.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot21.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CapturedSnapshot29.java
line probe in unit tests are created by searching probe id (UUID) inside the targeted source file.
uuid are added as comment on the line we want to put a line probe. Add helper method to search a uuid inside the targeted source file and returns the line number used to create the line probe
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keywo …
> Introduce id-based line probe source matching

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SnapshotSink.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/LogProbeTest.java
This makes distinct budgets for capturing vs non-capture snapshot probes. …
> Use two budgets depending on type

- dd-java-agent/instrumentation/java-lang/build.gradle
- dd-java-agent/instrumentation/java-net/build.gradle
- dd-java-agent/instrumentation/javax-naming/build.gradle
Remove redundant calls to `setJavaVersion(it, 8)` in `build.gradle` files. This is already the default.
Prep work for decoupling of gradle JDK and build/test JDK.
Split out from https://github.com/DataDog/dd-trace-java/pull/7506 …
> Remove redundant setJavaVersion calls in gradle

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestFrameworkModule.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestSuiteImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/buildsystem/ProxyTestModule.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/headless/HeadlessTestModule.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/manualapi/ManualApiTestModule.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/NoOpTestEventsHandler.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestEventsHandlerImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/test/ExecutionResults.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/test/ExecutionStrategy.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/domain/TestImplTest.groovy
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/domain/TestSuiteImplTest.groovy
- dd-java-agent/instrumentation/junit-4.10/cucumber-junit-4/src/main/java/datadog/trace/instrumentation/junit4/JUnit4CucumberItrInstrumentation.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4ItrInstrumentation.java
- dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/main/java/datadog/trace/instrumentation/junit5/JUnit5CucumberItrInstrumentation.java
- dd-java-agent/instrumentation/junit-5.3/spock-junit-5/src/main/java/datadog/trace/instrumentation/junit5/JUnit5SpockItrInstrumentation.java
- dd-java-agent/instrumentation/junit-5.3/spock-junit-5/src/main/java/datadog/trace/instrumentation/junit5/retry/JUnit5SpockParameterizedRetryInstrumentation.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnit5ItrInstrumentation.java
- dd-java-agent/instrumentation/karate/src/main/java/datadog/trace/instrumentation/karate/KarateTracingHook.java
- dd-java-agent/instrumentation/scalatest/src/main/java/datadog/trace/instrumentation/scalatest/RunContext.java
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGItrInstrumentation.java
- internal-api/src/main/java/datadog/trace/api/civisibility/events/TestEventsHandler.java
Removes `shouldBeSkipped` and `skip` methods from `TestEventsHandler` interface and replaces them with `isSkippable`.
Laying the groundwork for future test quarantining: when test quarantine is implemented, ITR will no longer be the only reason for skipping tests, so some adjustments to skipping logic will have to be made.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull …
> Remove skip and shouldBeSkipped methods from TestEventsHandler in favor of isSkippable

- .gitlab-ci.yml
- gradle/wrapper/gradle-wrapper.properties
The current Gitlab definition has a single "dependency cache". This PR adds a second "build cache".
**dependency cache**: is a cache of *external* dependencies. It is refreshed nightly based on the contents of `master`.
**build cache**: contains the products of the current pipeline. This allows gradle to skip, for instance, recompiling class files in later jobs. Unfortunately, I have not been able to solve `UP-TO-DATE` failing so some effort is repeated.
Additionally, the default tag for running jobs is `arch:amd64` because this is needed to use the latest gitlab runners.
I had a second `build_again` job that ran directly after `build`. This showed that most gradle tasks had the status `FROM-CACHE`
In moving from CircleCI to Gitlab, having a reasonable cache will save a lot of build time …
> Improve gitlab caching by adding a second cache

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/IastSystemTest.groovy
When OkHttp might trigger loading of `java.util.logging` we need to delay starting components that make remote calls. However there's no reason to delay starting components which don't actively make remote calls (if they record data that is sent out by another component then that's fine because the collected data will be sent when that component is started after premain.)
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues …
> IAST doesn't actively make remote calls, so never delay starting it

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
follow-up to https://github.com/DataDog/dd-trace-java/pull/8276 …
> Consider any custom security provider as potentially loading JUL

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/NoOpTestEventsHandler.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestEventsHandlerImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/retry/NeverRetry.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/retry/RetryIfFailed.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/retry/RetryNTimes.java
- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/retry/RetryAwareNotifier.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnitPlatformUtils.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/retry/JUnit5RetryInstrumentation.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/retry/TestDescriptorHandle.java
- dd-java-agent/instrumentation/karate/src/main/java/datadog/trace/instrumentation/karate/KarateRetryInstrumentation.java
- dd-java-agent/instrumentation/karate/src/main/java/datadog/trace/instrumentation/karate/KarateTracingHook.java
- dd-java-agent/instrumentation/scalatest/src/main/java/datadog/trace/instrumentation/scalatest/retry/TestExecutionWrapper.java
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TracingListener.java
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/retry/RetryAnalyzer.java
- dd-java-agent/instrumentation/testng/testng-7/src/main/java/datadog/trace/instrumentation/testng7/TestNGClassListenerInstrumentation.java
- dd-java-agent/instrumentation/testng/testng-7/src/main/java/datadog/trace/instrumentation/testng7/TestNGRetryInstrumentation.java
- dd-java-agent/instrumentation/weaver/src/main/java/datadog/trace/instrumentation/weaver/DatadogWeaverReporter.java
- internal-api/src/main/java/datadog/trace/api/civisibility/events/TestEventsHandler.java
- internal-api/src/main/java/datadog/trace/api/civisibility/retry/TestRetryPolicy.java
- internal-api/src/main/java/datadog/trace/api/civisibility/telemetry/tag/RetryReason.java
Does some updates to `TestRetryPolicy` and the code that uses it:
- retry reason is now an enum instead of a String
- the contract of `suppressFailures()` method is changed to return whether failures should be suppressed for the __current__ execution 
- `currentExecutionIsRetry()` method is removed
Preparing for future flaky tests management changes: quarantined tests will have to be executed without affecting the status of the build. …
> Generalize test retry logic

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ConfigurationApi.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ConfigurationApiImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ExecutionSettings.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ExecutionSettingsFactoryImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/SkippableTests.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/percentage/JacocoCoverageCalculator.java
Obtaining CI Visibility settings from the backend is done with multiple requests:
- request the list of enabled features
- depending on enabled features, request skippable tests data
- depending on enabled features, request known tests data
- depending on enabled features, request flaky tests data
- depending on enabled features, changed files data
Currently all of these requests are done sequentially.
This PR changes the logic so that all of the requests apart from the first one are done in parallel.
Speeding up settings construction. …
> Parallelize CI Visibility settings requests

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/JarScanner.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymDBEnablement.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymDBReport.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymbolAggregator.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/JarScannerTest.java
Any bail out when resolving or scanning for jars will be reported into SymDBReport and logged as a single INFO log line at the end of SYMDB extraction process from SymDB enablement
example:
```
[dd.trace 2025-01-29 14:32:07:763 +0100] [dd-task-scheduler] INFO com.datadog.debugger.symbol.SymDBReport - == SymDB Report == Location errors:[jrt:/java.xml.crypto, jrt:/java.xml.crypto, jrt:/java.xml.crypto, jrt:/java.xml.crypto] Missing jars: [] Directory jars: [/private/var/folders/_n/13tq16fx0f32x08gb9cszskc0000gp/T/jetty-0_0_0_0-8080-ee10-demo-simple_war-_ee10-demo-simple-any-5827001407483628327/webapp/WEB-INF/classes] IOExceptions: {}
```
- Assign the …
> Add SymDB report for any jar scanning failures

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/utils/SpanUtils.java
Fixes an issue introduced in https://github.com/DataDog/dd-trace-java/pull/8252
`test.framework_version` tag should not be set on test spans if its value is `null`. …
> Do not set test framework version tag if the value is null

- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/TempLocationManager.java
The `Files.createDirectories(path, attributes)` is using `PosixFilePermissions` to create the file attribute but this is not platform independent (although the `FileAttribute` looks like it might).
Therefore, we check for the presence of posix support and use the file attributes only if we are on posix.
Allow running tracer on Windows again
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-is …
> Avoid unsupported API call for creating folders on windows

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymDBEnablement.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymDBReport.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymDBEnablementTest.java
When the location of loaded class is a directory (directory provided into the classpath or war extracted into a temp dir) we need to walk the directory for scanning class files.
We avoid following the file link to prevent cycles. …
> Add support for SymDB to scan directories

- dd-trace-ot/build.gradle
- test-published-dependencies/ot-is-shaded/build.gradle
Makes `jnr-unixsocket` an explicit dependency of `dd-trace-ot` instead of (partially) shading it.
Avoids duplicate class error reported by `maven-enforcer-plugin` when both `dd-trace-ot` and `java-dogstatsd-client` are included in the same Maven project - see https://github.com/DataDog/dd-trace-java/issues/5951
There is a single leftover class under `ddtrot/com/kenai/jffi/PatchInit.class` which is our patched `Init` class used when isolating the embedded library in `dd-java-agent`. Unfortunately the shadow plugin stubbornly refuses to remove this dangling class despite trying various options. We therefore leave this class in its shaded location - it won't ever be loaded and won't interact with the classes brought in by the `jnr-unixsocket` dependency.
- Format the title [according the …
> Make jnr-unixsocket an explicit dependency of dd-trace-ot

- components/context/src/main/java/datadog/context/EmptyContext.java
- components/context/src/main/java/datadog/context/IndexedContext.java
- components/context/src/main/java/datadog/context/SingletonContext.java
- components/context/src/main/java/datadog/context/propagation/CarrierSetter.java
- components/context/src/main/java/datadog/context/propagation/Propagators.java
- components/context/src/test/java/datadog/context/ContextTest.java
- components/context/src/test/java/datadog/context/propagation/PropagatorsTest.java
This PR introduces the capability for registering propagators that are not used by default.
The goal is to have product to register custom propagators that can be retrieved by concern, but not automatically used for every context extraction / injection by default.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an …
> Add non default propagator registration

- dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastServerSmokeTest.groovy
Ensures all IAST related smoke tests wait for the product to be fully initialized before triggering any request. …
> Ensure IAST smoke tests wait for the product to be started

- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/TracingPropagator.java
- dd-trace-core/src/test/groovy/datadog/trace/core/propagation/TracingPropagatorTest.groovy
- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentPropagation.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
- internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ExtractedSpanTest.groovy
This PR introduce the Tracing propagator. It is register and available from the new propagator API but not used yet in instrumentation (next PR to come).
The PR also introduces the `ExtractedSpan` implementation, a wrapper of a span context to provide a span instance without the cost of creating a `DDSpan`, to be able to use span-based API without requiring a full-fledge span. It will be mainly used from extracted span context. 
The existing `HttpCodec.Extractor` is based on span context while the new context API can store span, hence the introduction of the `ExtractedSpan`.
Note the behavior is similar and will be compatible with OTel.
I plan to get rid of the original getter / setter for `HttpCodec` in favor of the ones introduced in the context component.
- Format the title [according …
> Introduce tracing propagator

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/CodeOriginProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/MetricProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanDecorationProbe.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanProbe.java
add toString
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new …
> Fix equals/hashCode for CodeOrigin probe

- .circleci/config.continue.yml.j2
This introduces a new scenario for running **WAF** telemetry tests within the _system-tests_.
Currently, changes to **WAF** telemetry do not verify whether the _system-tests_ execute correctly. We aim to prevent misalignment between the _system-tests_ and the _tracer_.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing …
> Add APPSEC_WAF_TELEMETRY to system-tests

- .github/workflows/check-pull-requests.yaml
Try to fix blocked PR with waiting checks.
With better concurrency setting, try to add synchronize event back to prevent blocked PR checks. …
> Fix blocked PR checks 

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/VulnerabilityTypeTest.groovy
Change the evidence hash calculation for the location one
Using evidence for the cookie vulnerabilities hash is not the most effective approach. In some applications, a different cookie name is used per request or session. This leads to a large number of duplicate vulnerabilities. Deduplicating by location leads to a predictably low and bounded number of vulnerabilities.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/ …
> Address cookie vulnerability cardinality issues

- dd-java-agent/instrumentation/ignite-2.0/build.gradle
> Update muzzle to record that the Ignite 2.0 instrumentation is not compatible with Ignite 3.0

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SymbolSink.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/SymbolSinkTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymDBEnablementTest.java
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
debuggerSymbol -> SymbolDatabase
make it less tight to debugger
Remove unused config `DD_SYMBOL_DATABASE_INCLUDES` (should be third party includes)
Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to …
> Rename debugger symbol to symbol database

- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java
> Fix smoke test

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
useless log
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) in case of new …
> Remove debug log on log probe critical path

- internal-api/src/main/java/datadog/trace/api/telemetry/WafMetricCollector.java
- internal-api/src/test/groovy/datadog/trace/api/telemetry/WafMetricCollectorTest.groovy
Updates metrics: appsec.rasp.rule.eval, appsec.rasp.rule.match and appsec.rasp.timeout (adds event_rules_version tag)
Part of a project to expand metrics information …
> Update appsec metrics with event_rules_version tag

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/codeowners/EntryBuilder.java
- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/codeowners/EntryBuilderTest.groovy
Updates CODEOWNERS parsing logic: when there is a comment with a leading whitespace, there will be no error logged. …
> Update CODEOWNERS parser to not log errors on comments with leading whitespace

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
- dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/muzzle/TestAdviceClasses.java
If a helper/advice class contains this kind of code:
```
if (something instanceof byte[]) {
..
}
```
muzzle will create a reference for `B` since, for methods, it checks only the underlying type without checking if it's a primitive array `[B`
Use `solves` …
> Muzzle: do not generate references for primitive arrays in method body

- .gitlab/benchmarks.yml
Makes benchmarks optional and manual during releases.
Most of the benchmarks make incorrect assumptions about artifacts that are not true for releases. This leads to the benchmark jobs failing on the release
> Skip benchmarks on release

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MethodInfo.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/CodeOriginProbe.java
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcCodeOriginTest.groovy
- dd-java-agent/instrumentation/kafka-clients-3.8/build.gradle
- dd-java-agent/instrumentation/kafka-clients-3.8/src/main/java/datadog/trace/instrumentation/kafka_clients38/MessageListenerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-3.8/src/test/groovy/KafkaCodeOriginForkedTest.groovy
- dd-java-agent/instrumentation/span-origin/src/main/java/datadog/trace/instrumentation/codeorigin/EntrySpanOriginAdvice.java
- dd-java-agent/testing/build.gradle
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
Adds code origin information to client handlers for processing kafka events. …
> Add code origin support to kafka message listeners

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
Due to overhead induced by capturing entry values because we need to freeze them (serialize as Json) immediately before even know if we are
sampling it or not, compared to the usefulness of having those values
we only capture at exit by default.
Performance …
> Disable capture of entry values

- .circleci/config.continue.yml.j2
Updates the pinned commit to fix the issue with a broken mssql-jdbc transitive dependency. …
> Update system-tests commit

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/codeorigin/DefaultCodeOriginRecorder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/CodeOriginProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/origin/CodeOriginTest.java
- dd-java-agent/instrumentation/micronaut/http-server-netty-4.0/src/test/groovy/MicronautTest.groovy
- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAdvice.java
- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceDecorator.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/CodeOriginIntegrationTest.java
add a param for captureCodeOrigin method to indicate if we need to
instrument for the CodeOriginProbe. the instrumentation for the
`@trace` annotation insert a call to start and activate the span.
so we just need to call captureCodeOrigin after the activation so we
benefit from tracer instrumentation without generating a call to
CodeOrigin probe.
That way are in sync with the tracer instrumentation.
add smoke test …
> Fix CodeOrigin for `@Trace` annotation

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
Makes sure that the automated instrumentation does not override the span tag `appsec.events.users.login.failure.usr.exists` when already provided by a call to the SDK. …
> Ensure usr.exists tag is not overridden by auto instrumentation

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/user/AppSecEventTrackerSpecification.groovy
- internal-api/src/main/java/datadog/trace/api/appsec/AppSecEventTracker.java
This is a follow-up PR to https://github.com/DataDog/dd-trace-java/pull/8374 that includes a missing operation when a `org.springframework.security.core.userdetails.UsernameNotFoundException` is thrown. …
> Ensure usr.exists tag is not overridden when UsernameNotFoundException is thrown

- dd-java-agent/instrumentation/ignite-2.0/build.gradle
Updates the muzzle directive for the `ignite` instrumentation. Version `2.17.0` released on Feb, 9th is compiled with Java 11, causing a failure in the muzzle check. …
> Update muzzle directive for ignite 2.17.0 to use Java 11

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-0.3/src/main/java/datadog/trace/instrumentation/opentelemetry/OtelScope.java
- dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTScopeManager.java
- dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTScopeManager.java
- dd-java-agent/instrumentation/play-ws-1/src/main/java/datadog/trace/instrumentation/playws1/AsyncHandlerWrapper.java
- dd-java-agent/instrumentation/play-ws-2.1/src/main/java/datadog/trace/instrumentation/playws21/AsyncHandlerWrapper.java
- dd-java-agent/instrumentation/play-ws-2/src/main/java/datadog/trace/instrumentation/playws2/AsyncHandlerWrapper.java
- dd-java-agent/instrumentation/servicetalk/src/test/groovy/ContextPreservingInstrumentationTest.groovy
- dd-java-agent/instrumentation/zio/zio-2.0/src/main/java/datadog/trace/instrumentation/zio/v2_0/FiberContext.java
- dd-trace-api/src/main/java/datadog/trace/api/GlobalTracer.java
- dd-trace-api/src/main/java/datadog/trace/api/Tracer.java
- dd-trace-api/src/main/java/datadog/trace/context/NoopTraceScope.java
- dd-trace-api/src/main/java/datadog/trace/context/TraceScope.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
- dd-trace-ot/src/main/java/datadog/opentracing/OTScopeManager.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
`TraceScope.capture()` now delegates to `Tracer.captureActiveSpan()` - when asynchronous propagation is enabled, this method prevents the currently active trace from reporting until the returned continuation is either activated (and the returned scope is closed) or the continuation is canceled  
Note: previously it was technically possible to call `TraceScope.capture()` on a scope which wasn't part of the currently active trace. This is no longer allowed, calling `capture()` will now always capture the active trace at that point. In practice this shouldn't make any difference because this API was used to capture active scopes.
We want to move away from the old scope-specific API towards tracer methods that work on the active span/trace.
Further migration/evolution of the `AgentTracer` API …
> Move continuation capture methods from scope to tracer

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ExecutionSettingsFactoryImpl.java
- dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/config/CiVisibilityConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Disables requests to `ci/tests/diffs` backend endpoint, unless they are explicitly enabled with a config property.
The endpoint is not implemented in the backend yet.
This is a part of the Impacted Tests Detection feature (https://github.com/DataDog/dd-trace-java/pull/8188) that is currently disabled for everyone by org 2.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull …
> Disable backend requests for impacted tests data

- dd-trace-core/src/main/java/datadog/trace/common/sampling/Sampler.java
- dd-trace-core/src/test/groovy/datadog/trace/common/sampling/SamplerTest.groovy
- internal-api/src/main/java/datadog/trace/api/Config.java
Fix the Sampler to enable ASMStandaloneSampler also when SCA is enabled …
> Fix APM Tracing disabled for SCA

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Location.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Vulnerability.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
Move stackId from Vulnerability to Location
The RFC specifies that 
> Location
> In order to link the stack with the vulnerability, we will add a stack field to the vulnerability’s location, containing the stack id in the vulnerabilities section of stacks of the span.
However, this stackId was incorrectly added to the vulnerability instead of to the Location.
[RFC](https://docs.google.com/document/d/1ga7yCKq2htgcwgQsInYZKktV0hNlv4drY9XzSxT-o5U/edit?tab=t.0#heading=h.e4lbumn4upwy)
- …
> Move stackId from Vulnerability to Location

- telemetry/src/main/java/datadog/telemetry/EventSource.java
- telemetry/src/test/groovy/datadog/telemetry/EventSourceTest.groovy
When support for **product change events** was added, it was not included in the `isEmpty` method. …
> Add hasProductChangeEvent check to isEmpty

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
If multiple vulnerabilities share the same location, it is not necessary to generate the stack trace again, as they should share it
- …
> Fix IAST Vulnerabilities stack trace generation when multiple vulnerabilities share location

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy
- internal-api/src/main/java/datadog/trace/api/telemetry/WafMetricCollector.java
- internal-api/src/test/groovy/datadog/trace/api/telemetry/WafMetricCollectorTest.groovy
Creates appsec.rasp.error: this metric can be used to count the number of errors generated when calling ddwaf_run on RASP-specific instrumentation
RASP metrics  provide an aggregate view of the deployment health for the deployment of RASP rules. 
This metric notably holds the field waf_error that contains the numeric code returned by the ddwaf_run
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-t …
> Create metric: appsec.rasp.error

- communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
Changes trace endpoint probing to use a valid payload of empty arrays
This was originally applied in https://github.com/DataDog/dd-trace-java/commit/210fd39938b5250300ad15852d8ee37eab0bae82 but was reverted because an old test agent we were using at the time expected empty requests (whereas the real agent expects valid non-empty payloads.)
Avoids probing real agents with invalid payloads - while this doesn't affect the probing (as it looks for any response that's not 404) it is always better to use a valid payload for probing. 
Probing only applies when the tracer has not been able to query the `/info` endpoint, as that output includes the appropriate trace endpoint to use.
We may want to consider using a `HEAD` request for probing in the future.
- Format the title [according the …
> Probe trace endpoints with a valid payload of empty arrays

- dd-java-agent/instrumentation/mule-4/build.gradle
Skip mule-core 4.9.1 due to missing mule-artifact-ast:1.5.1 dependency - looks like a partial deployment issue
also removed redundant muzzle block, which appears to duplicate one of the blocks above
> Skip mule-core 4.9.1 due to missing mule-artifact-ast:1.5.1 dependency

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExecutorInstrumentationUtils.java
- dd-java-agent/instrumentation/armeria-grpc/src/test/groovy/ArmeriaGrpcStreamingTest.groovy
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcCodeOriginTest.groovy
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
- dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/KafkaClientTestBase.groovy
- dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
- dd-java-agent/instrumentation/kafka-clients-3.8/src/test/groovy/KafkaClientTestBase.groovy
- dd-java-agent/instrumentation/kafka-clients-3.8/src/test/groovy/KafkaCodeOriginForkedTest.groovy
- dd-java-agent/instrumentation/scala-promise/src/main/java/datadog/trace/instrumentation/scala/PromiseHelper.java
- dd-java-agent/instrumentation/vertx-web-3.4/src/test/java/server/VertxTestServer.java
- dd-java-agent/instrumentation/vertx-web-3.9/src/test/java/server/IastVertx39TestVerticle.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/latestDepTest/java/server/VertxTestServer.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/java/server/VertxTestServer.java
- dd-java-agent/instrumentation/vertx-web-5.0/src/test/java/server/VertxTestServer.java
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
Migrates tests and helpers to check async-propagation flag via `AgentTracer`
Removes use of deprecated scope method in our code.
- Update …
> Check async propagation flag via agent tracer

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/LogProbeTest.java
Make sure budgets apply to line probes, too.
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library …
> Make sure budgets apply to line probes, too.

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy
- internal-api/src/main/java/datadog/trace/api/telemetry/WafMetricCollector.java
- internal-api/src/test/groovy/datadog/trace/api/telemetry/WafMetricCollectorTest.groovy
This metric can be used to count the number of errors generated when calling ddwaf_run when evaluating WAF addresses, or rather non-RASP addresses. 
Counterpart to the appsec.rasp.error found here https://github.com/DataDog/dd-trace-java/pull/8364
Use …
> Create metric: appsec.waf.error

- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/TempLocationManager.java
This task was never scheduled or executed, but its countdown-latch was waited on during shutdown.
This resulted in the following log message each time a process was launched with profiling enabled:
```
[dd.trace 2025-02-18 15:07:21:489 +0000] [Temp Location Manager Cleanup] INFO com.datadog.profiling.controller.TempLocationManager - Cleanup task timed out. /var/folders/6l/65lfwqj14ps6w4gt7495gly80000gq/T/ddprof/pid_4866 temp directory might not have been cleaned up properly
```
- Don't …
> Actually use CleanupTask in TempLocationManager

- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
- telemetry/src/test/groovy/datadog/telemetry/HostInfoTest.groovy
Revert "FIXME: temporarily ignore hostname assertions on CircleCI (#8411)
This reverts commit ebdbdd43a21b0c229ba18441eac014ee509d8489.
Circle CI confirmed this was an issue on their side, and it should be fixed now. …
> Revert "FIXME: temporarily ignore hostname assertions on CircleCI (#8411)"

- dd-java-agent/instrumentation/spring-webmvc-6.0/build.gradle
- dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java/datadog/trace/instrumentation/springweb6/SpringWebCodeOriginInstrumentation.java
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
This adds the functionality itself but is tested via the system-tests. …
> Add code origin support for spring-webmvc

- dd-java-agent/instrumentation/kafka-connect-0.11/src/test/groovy/ConnectWorkerInstrumentationTest.groovy
- dd-trace-core/src/main/java/datadog/trace/core/datastreams/DataStreamContextExtractor.java
- dd-trace-core/src/main/java/datadog/trace/core/datastreams/DataStreamPropagator.java
- dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsMonitoring.java
Service name override used to be fixed in Extractor / Propagator, which are not created in the same thread as the thread where extraction is happening.
This lead to incorrect service name overrides.
This was reported as a bug on Snowflake sink connectors, where we failed to override service names properly.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-is …
> Fix service name overrides in consumers

- dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
- dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
- dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/util/JfrCliHelperTest.java
- dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/CompositeController.java
- dd-java-agent/testing/src/test/groovy/AgentTestRunnerTest.groovy
- internal-api/src/main/java/datadog/trace/api/Platform.java
It adjusts the checks for the availability of JFR on a particular JVM instance
In the latest J9 JVM there is JFR implementation available in technical preview. This means that the support is there (eg. we can load and initialize `jdk.jfr.Event` class but the engine itself is disabled unless `-XX:+FlightRecorder` JVM arg is provided.
This does confuse the checks for the availability of JFR and the profiler would try using disabled JFR, leading to errors.
- Don't use `close`, `fix` or any …
> Adjust JFR checks for J9

- dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/OOMENotifierScriptInitializer.java
- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/TempLocationManager.java
- dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/TempLocationManagerTest.java
Ideally we wouldn't need to use `jps` at all, but we can still avoid calling it until necessary to reduce overhead - as well as reducing the risk of port collisions, such as reported in #8148
We might want to introduce a `CachingSupplier` helper class or similar to simplify this approach if we end up using it in more places.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pu …
> Only fork jps when required

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
Backport #8369 to release/v1.46.x
> 🍒 8369 - Disable capture of entry values

- telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java
- telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverSpecification.groovy
- Add support for JBoss jar:file format to DependencyResolver
- improve tests
The current implementation only considered dependency analysis with the `jar:file` format for nested jars. However, thanks to the bug reported in APPSEC-56111, we discovered that this format is also used in JBoss to reference jar files instead of nested jars
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#li …
> Add support for JBoss jar:file format to DependencyResolver

- .circleci/config.continue.yml.j2
Revert CircleCI changes from #8385 until:
* GitLab CI runs enough to check for stability and compare with CircleCI output
* The continuous integration dashboard to be updated
* The PR checks to updated …
> Revert job removal from CircleCI

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/codeorigin/DefaultCodeOriginRecorder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/CodeOriginProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/origin/CodeOriginTest.java
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcCodeOriginTest.groovy
- dd-java-agent/instrumentation/ignite-2.0/build.gradle
- dd-java-agent/instrumentation/micronaut/http-server-netty-4.0/src/test/groovy/MicronautTest.groovy
- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAdvice.java
- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceDecorator.java
Backport https://github.com/DataDog/dd-trace-java/pull/8344 to release/v1.46.x
> 🍒 8344 - Fix CodeOrigin for @Trace annotation

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/codeorigin/DefaultCodeOriginRecorder.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/origin/CodeOriginTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/LogProbeTest.java
- dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
- dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
- dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Adds a new configuration option specifically for dynamic instrumentation's live debugger …
> Introduce new flag to enable the live debugger specifically

- dd-java-agent/instrumentation/ignite-2.0/build.gradle
* Set latestDepTest for ignite-2.0 compile with Java 11+, since ignite-2.17.0+ requires it (discovered on dependency bump: https://github.com/DataDog/dd-trace-java/pull/8398).
* Add a new test variant for ignite 2.16.0 (last version compatible with Java 8).
* Note that latestDepTest do not run with Java 11+. This was an old problem, and still not addressed by this PR.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/lin …
> Fix ignite-2.0 latestDepTest compilation

- .github/workflows/README.md
- .github/workflows/prune-github-container-registry.yaml
System tests start pushing new tags using architecture.
Those are new pruned from the registry.
Keep the registry healthy.
We can expect system tests disruption as we will reach API call limits when trying to clean up 10k tags from the registry.
Use …
> Fix GHCR registry pruning

- dd-java-agent/instrumentation/scalatest/src/main/java/datadog/trace/instrumentation/scalatest/ScalatestInstrumentation.java
Fixes https://github.com/DataDog/dd-trace-java/issues/8435
Scalatest instrumentation works by plugging into `org.scalatest.DispatchReporter` and intercepting events reported by the framework.
When running async test cases, another reporter is used: `org.scalatest.tools.TestSortingReporter`. This reporter stores received events in memory and reports them asynchronously, potentially in a different thread.
The fix is to intercept the events as they're passed to the async reporter (the same way it is done for dispatch reporter) and suppress interception when they're "re-fired" asynchronously (as they've already been traced at initial interception point).
I could not find a way to re-create the problem with instrumentation tests, so testing is covered by a new test-environment project: …
> Fix Scalatest tracing for tests that are reported asynchronously

- dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Utils.java
Fixes https://github.com/DataDog/dd-trace-java/issues/8441
With some JUnit4-based frameworks (such as Scala MUnit) it is expected that the tracer cannot determine test case method (with Scala MUnit the necessary information is not available at runtime).
Therefore we should not be reporting this as a warning, and clutter the users' logs.
It will still be reported with debug logging level and will be available in telemetry logs. …
> Remove warning log when JUnit 4 test method cannot be retrieved

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
The premain `Agent` class was looking up config values using system property names prefixed with `dd.` whereas `StableConfigSource` was expecting internal config keys without that prefix.
We now store both the config key and system property form in each feature in `Agent` and use the appropriate name when looking up system properties vs stable config.
This PR also fixes an issue where `Agent.isFullyDisabled` wasn't checking stable-config. …
> Fix stable-config lookup from Agent in premain

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/ClassNameFiltering.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/ClassNameFilteringTest.java
- dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/ServerDebuggerTestApplication.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/CodeOriginIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ExceptionDebuggerIntegrationTest.java
If JVM is started with `-XX:+ShowHiddenFrames` lambda proxy classes dynamically generated are shown in the stacktraces which may be used in the fingerprinting for Exception Replay. The proxy class generated contains an id that is different for each loading of the class. Upon re-transformation this id is changing which led to a different fingerprint for the same stacktrace which will trigger a new instrumentation and a re-transformation. And again new fingerprint... We are fixing this by filtering out lambda proxy classes if detected. …
> Fix Exception Replay with Lambda proxy classes

- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/executor/ThreadPoolExecutorInstrumentation.java
It excludes Apache Mina `OrderedThreadPoolExecutor` from queue-time related instrumentation.
That particular executor is 'peculiar' in a sense that it circumvents the functionality of the base class and for `getQueue()` method throws `UnsupportedOperationException`. Since `getQueue()` is essential for measuring the time a task spent in a queue the instrumented code happens to call it very often and this leads to the system being completely flooded by `UnsupportedOperationException`.
The main motivation is to avoid breaking the traced application because of this problem. …
> Exclude OrderedThreadPoolExecutor from queue-time measurements

- internal-api/build.gradle
- internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
task ':internal-api:jacocoTestCoverageVerification' is failing due to current datadog.trace.api.Config coverage it's lower than 0.8
- …
> Exclude datadog.trace.api.Config from coverage verification

- .circleci/config.continue.yml.j2
- dd-java-agent/appsec/build.gradle
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFStatsReporterSpecification.groovy
- internal-api/src/main/java/datadog/trace/api/telemetry/TruncatedType.java
- internal-api/src/main/java/datadog/trace/api/telemetry/WafMetricCollector.java
- internal-api/src/main/java/datadog/trace/api/telemetry/WafTruncatedType.java
- internal-api/src/test/groovy/datadog/trace/api/telemetry/WafMetricCollectorTest.groovy
- telemetry/src/test/groovy/datadog/telemetry/metric/WafMetricPeriodicActionSpecification.groovy
This adds a new value to some metrics which is necessary for the consolidation of ASM Span Tags, Metrics, and Logs across all supported languages. The newly value will be implemented in the following metrics:
- **appsec.waf.requests**:
- _waf_error_: If WAF has failed (except timeout)
- _block_failure_: If the block has failed
- _rate_limited_: Wheter the trace has been rate limited
- _input_truncated_: Wheter the data provided to the libddwaf has been truncated
Our goal is to implement all the missing ASM Span Tags, Metrics, and Logs. …
> Update metrics: appsec.waf.requests

- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/util/NonBlockingSemaphore.java
- dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/util/NonBlockingSemaphoreTest.groovy
* Move `NonBlockingSemaphore` to `internal-api`.
* Extend its tests.
* Make `release` for the boolean semaphore truly atomic. By definition, a release there always leads to `1` available. While first releasing and then getting the available count will return `0` or `1` inconsistently.
`NonBlockingSemaphore` was written originally for IAST, but we plan to reuse it in AppSec (https://github.com/DataDog/dd-trace-java/pull/8178), and it may be useful for others.
- Don't use `close`, `fix` …
> Extend NonBlockingSemaphore and make release for 1-permit case atomic

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/AgentJarIndex.java
This PR adds a log warning when duplicated content is found in a directory of the AgentJarIndex. In this case, the AgentJarIndex will map the content to the last directory that the content was found under.
While developing #8314 UDS support, we came across the issue where certain classes were incorrectly added under multiple directories. Since the AgentJarIndex only maintains the last class-directory mapping, the indexing was incorrect and our build was unable to find the relevant classes. Adding this warning should help highlight this issue when content is duplicated. …
> Add log warning in AgentJarIndex if an entryKey has multiple prefixIds.

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
- internal-api/src/main/java/datadog/trace/api/ConfigOrigin.java
- internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
- internal-api/src/main/java/datadog/trace/bootstrap/config/provider/StableConfigSource.java
- internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/StableConfigSourceTest.groovy
This PR fixes Stable Config source names:
- `managed_stable_config` --> `fleet_stable_config`
- `user_stable_config` --> `local_stable_config`
Align with other languages, the RFC, & system tests. The goal is to enable system tests for Java.
Use `solves` …
> Fix Stable Config telemetry source names

- .gitlab-ci.yml
Don't skip muzzle and test_published_artifacts for the nightly Gitlab build
Test should run nightly. Skipping them broke the pipeline because `required` was not also skipped …
> Don't skip muzzle and test_published_artifacts for the nightly Gitlab build

- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/MethodHandlersInstrumentation.java
The version of grpc used by the tracer’s testing is older than the version used by logs-backend and so the generated code is slightly different.  In the tracer version, the proto interface gets generated into a `FooImplBase` for the proto type `foo`.  In logs-backed, `FooImplBase` implements an interface called `AsyncService` and all the pertinent method definitions are there instead.  The fix here, then, is to look first at the `ImplBase` type and if the only method is `bindService()`, look for the methods on the generated `AsyncService` interface instead. …
> Look in another location for grpc service methods

- dd-java-agent/instrumentation/couchbase/couchbase-2.6/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseCoreInstrumentation.java
- dd-java-agent/instrumentation/cucumber/src/main/java/datadog/trace/instrumentation/cucumber/CucumberInstrumentation.java
- dd-java-agent/instrumentation/cucumber/src/main/java/datadog/trace/instrumentation/cucumber/CucumberStepDecorator.java
- dd-java-agent/instrumentation/enable-wallclock-profiling/src/main/java/datadog/trace/instrumentation/wallclock/EnableWallclockProfilingInstrumentation.java
- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/ClientStreamListenerImplInstrumentation.java
- dd-java-agent/instrumentation/http-url-connection/src/test/groovy/HttpUrlConnectionConnectFirstTest.groovy
- dd-java-agent/instrumentation/http-url-connection/src/test/groovy/HttpUrlConnectionTest.groovy
- dd-java-agent/instrumentation/http-url-connection/src/test/groovy/HttpUrlConnectionUseCachesFalseTest.groovy
- dd-java-agent/instrumentation/http-url-connection/src/test/groovy/UrlConnectionTest.groovy
- dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/test/java/Fanout.java
- dd-java-agent/instrumentation/java-concurrent/src/test/java/runnable/CheckpointTask.java
- dd-java-agent/instrumentation/junit-4.10/munit-junit-4/src/main/java/datadog/trace/instrumentation/junit4/MUnitTracingListener.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnitPlatformUtils.java
- dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/OnCompleteHandler.java
Most of the time we're only interested in whether there's an active span - we don't need the actual closeable handle. …
> Reduce use of activeScope() in instrumentation

- dd-java-agent/agent-debugger/debugger-el/build.gradle
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/EvaluationException.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/TriggerProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/trigger/TriggerProbeTest.java
If the distributed debugger is disabled for a service, do not instrument any trigger probe definitions received from the backend.
- Update …
> Don't instrument trigger probes if the distributed debugger is disabled

- dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/MethodHandlersInstrumentation.java
Corrects the interface lookup.
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) …
> Use proper class def to find interfaces

- .github/workflows/prune-github-container-registry.yaml
There is no point keep tags of old versions as 1. there are not used, 2. clean up is broken with multi-arch packaging. …
> Remove all old testing OCI images

- dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/TempLocationManagerTest.java
Looks like I marked the wrong method as flaky as the CI isn't any better.
Fix #8459 …
> Mark profiling test as flaky

- dd-java-agent/instrumentation/gradle-8.3/src/main/groovy/datadog/trace/instrumentation/gradle/CiVisibilityGradleListener.java
Fixes a possible NPE in Android Gradle projects instrumentation. …
> Fix an NPE in Gradle Android instrumentation

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestFrameworkModule.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/buildsystem/ProxyTestModule.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/headless/HeadlessTestModule.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/NoOpTestEventsHandler.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/TestEventsHandlerImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/test/ExecutionStrategy.java
- dd-java-agent/instrumentation/junit-5.3/junit-5.8/src/main/java/datadog/trace/instrumentation/junit5/order/FailFastClassOrderer.java
- dd-java-agent/instrumentation/junit-5.3/junit-5.8/src/main/java/datadog/trace/instrumentation/junit5/order/FailFastMethodOrderer.java
- dd-java-agent/instrumentation/testng/src/main/java/datadog/trace/instrumentation/testng/TestNGUtils.java
- dd-java-agent/instrumentation/testng/testng-7/src/main/java/datadog/trace/instrumentation/testng7/order/FailFastOrderInterceptor.java
- internal-api/src/main/java/datadog/trace/api/civisibility/events/TestEventsHandler.java
When applying fail-fast tests ordering, "impacted tests" (test cases whose body was modified) are considered for reordering along with new and flaky tests.
"Execution priority" heuristic is added to the execution strategy to encapsulate ordering logic and reuse it for different testing frameworks.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using …
> Consider modified tests when applying fail-fast tests ordering

- dd-java-agent/instrumentation/akka-http/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/DatadogServerRequestResponseFlowWrapper.java
- dd-java-agent/instrumentation/pekko-http-1.0/src/main/java/datadog/trace/instrumentation/pekkohttp/DatadogServerRequestResponseFlowWrapper.java
- dd-java-agent/instrumentation/sslsocket/src/main/java/datadog/trace/instrumentation/sslsocket/SocketConnectInstrumentation.java
- dd-java-agent/instrumentation/undertow/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/HandlerInstrumentation.java
Continuation of #8470 - most of the time we're only interested in whether there's an active span - we don't need the actual closeable handle.
Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the …
> Prefer using activeSpan() over activeScope()

- internal-api/src/main/java/datadog/trace/api/Config.java
Add the value of the configuration key `dd.dbm.trace_prepared_statements` to  the tracer configuration log in order to help troubleshooting any issue related to this feature
Help troubleshooting issues related to the DBM feature, involving prepared statements.
> Add DBMTracePreparedStatements to tracer configuration log

- dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/GlobalTracerInstrumentation.java
- dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTScopeManager.java
- dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
- dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/GlobalTracerInstrumentation.java
- dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTScopeManager.java
- dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScope.java
- dd-trace-ot/build.gradle
- dd-trace-ot/src/main/java/datadog/opentracing/OTScopeManager.java
- dd-trace-ot/src/ot33CompatibilityTest/groovy/OT33ApiTest.groovy
- dd-trace-ot/src/test/groovy/datadog/opentracing/IterationSpansForkedTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
This was only used to implement the deprecated 'active()' OpenTracing method. We take a best effort approach of using a 'fake' scope which lets the caller close the active scope if it matches the expected span, and otherwise logs a warning (or throws an exception in strict mode.) …
> Remove activeScope() use in OpenTracing shim

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestSuiteImpl.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSHttpClientInstrumentation.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/RequestExecutorInstrumentation.java
- dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsHttpClientInstrumentation.java
- dd-java-agent/instrumentation/google-http-client/src/main/java/datadog/trace/instrumentation/googlehttpclient/GoogleHttpClientInstrumentation.java
- dd-java-agent/instrumentation/karate/src/main/java/datadog/trace/instrumentation/karate/KarateTracingHook.java
- dd-java-agent/instrumentation/undertow/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/HttpRequestParserInstrumentation.java
These instrumentations just want to close the active span when it matches certain criteria.
Since #8478 they can now use `activeSpan()` to check the active span and `closeActive()` to close it  …
> Migrate certain instrumentations to use closeActive() to close outstanding spans

- dd-java-agent/appsec/build.gradle
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy
- dd-java-agent/appsec/src/test/resources/logback-test.xml
Improve detection of missing or out of order request events.
This has been a problem for a while, and there are still some cases with unknown root cause. …
> Improve detection of missing request end events

- dd-java-agent/instrumentation/reactor-netty-1/src/test/groovy/ReactorNettyHttp2ClientTest.groovy
- dd-java-agent/instrumentation/reactor-netty-1/src/test/groovy/ReactorNettyHttpClientTest.groovy
Ignores Netty reactor http tests when running on J9.
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection …
> Ignore IBM jdk when running Netty reactor tests

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ClassesToRetransformFinder.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/InnerHelper.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SourceFileTrackingTransformerTest.java
classNamesBySourceFile map used for SourceFile tracking can have a lot of entries (different SourceFiles) and for each entry we have a list (If any inner classe or non-public top-level classes). Compacting to a comma-separated list reduce the footprint of this map. As the usage is very unfrequent we can pay the price to "deserialize" the list to go through the classname that we need to retransform as a dependency …
> Reduce footprint of SourceFile tracking

- dd-java-agent/instrumentation/zio/zio-2.0/src/main/java/datadog/trace/instrumentation/zio/v2_0/FiberContext.java
That's why the target of this PR is the `project/context` feature branch. …
> Migrate zio instrumentation to new Context API

- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ScopeState.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ScopeStateAware.java
With the kotlin coroutines and zio fiber instrumentations migrated to use the new `Context` API, the `ScopeStateAware` API can be removed.
That's why the final target of this stacked PR is the `project/context` feature branch.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue …
> Remove unused ScopeStateAware API

- dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/OtelContext.java
- dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/OtelScope.java
- dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/propagation/AgentTextMapPropagator.java
- dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/trace/OtelSpanBuilder.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OpenTelemetryContextInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OpenTelemetryContextStorageInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/ContextTest.groovy
That's why the final target of this stacked PR is the `project/context` feature branch. …
> Migrate OtelContext wrapper to new Context API

- dd-java-agent/instrumentation/akka-concurrent/src/akka23Test/scala/AkkaActors.scala
- dd-java-agent/instrumentation/pekko-concurrent/src/test/scala/PekkoActors.scala
- dd-java-agent/instrumentation/scala-concurrent/src/latestDepTest/scala/ScalaConcurrentTests.scala
- dd-java-agent/instrumentation/scala-concurrent/src/test/scala/ScalaConcurrentTests.scala
- dd-java-agent/instrumentation/slick/src/test/scala/SlickUtils.scala
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Additional Notes
That's why the final target of this stacked PR is the `project/context` feature branch. …
> Remove unused activeScope method

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilityRepoServices.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ExecutionSettingsFactoryImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/coverage/percentage/JacocoCoverageCalculator.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/events/NoOpTestEventsHandler.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitClient.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/NoOpGitClient.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/ShellGitClient.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/CachingRepoIndexBuilderFactory.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexBuilder.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/source/index/RepoIndexProvider.java
Fixes a `NullPointerException` when initializing Test Optimization in an environment where Git repository root cannot be determined.
Marks `CiVisibilityRepoServices#repoRoot` as `@Nullable`. …
> Fix Test Optimization init when repo root cannot be determined

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-0.3/src/main/java/datadog/trace/instrumentation/opentelemetry/TypeConverter.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-0.3/src/test/groovy/TypeConverterTest.groovy
- dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/TypeConverter.java
- dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/TypeConverterTest.groovy
- dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/TypeConverter.java
- dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/TypeConverterTest.groovy
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScope.java
- dd-trace-ot/src/main/java/datadog/opentracing/TypeConverter.java
- dd-trace-ot/src/test/groovy/datadog/opentracing/TypeConverterTest.groovy
In the majority of cases the scope wrapper will only be accessed once when activating a span or context. The other cases are deprecated calls to check the active scope, where the returned scope wrapper is short-lived and cheap to recreate.
The Kotlin, Zio, and some Otel context tests are expected to fail as the scope manager rework is still in-flight
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-reques …
> Remove AttachableWrapper aspect from scopes

- internal-api/build.gradle
- internal-api/src/main/java/datadog/trace/bootstrap/config/provider/EnvironmentConfigSource.java
- internal-api/src/main/java/datadog/trace/bootstrap/config/provider/SystemPropertiesConfigSource.java
If we don't have permission to access system properties or the environment then fall back to defaults.
Supports installation of helpers, even when their target location is lacking permission to lookup configuration.   …
> Make the default config sources more robust when a security manager is installed

- dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ci/CITagsProviderTest.groovy
- internal-api/src/main/java/datadog/trace/api/git/GitInfo.java
- internal-api/src/main/java/datadog/trace/api/git/UserSuppliedGitInfoBuilder.java
- internal-api/src/test/groovy/datadog/trace/api/git/UserSuppliedGitInfoBuilderTest.groovy
Updates the class that reads user-provided git metadata to use common config sources (env vars, system props, property files, etc).
Current implementation only uses the environment variables. …
> Support common config sources for user-provided git info

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AdviceUtils.java
- dd-java-agent/instrumentation/akka-concurrent/src/test/groovy/AkkaExecutorInstrumentationTest.groovy
- dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/TraceContinuedFutureCallback.java
- dd-java-agent/instrumentation/apache-httpclient-5/src/main/java/datadog/trace/instrumentation/apachehttpclient5/TraceContinuedFutureCallback.java
- dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/test/groovy/CompletableFutureTest.groovy
- dd-java-agent/instrumentation/java-concurrent/java-concurrent-21/src/test/groovy/VirtualThreadTest.groovy
- dd-java-agent/instrumentation/java-concurrent/src/test/groovy/executor/ExecutorInstrumentationTest.groovy
- dd-java-agent/instrumentation/java-concurrent/src/test/groovy/executor/NettyExecutorInstrumentationTest.groovy
- dd-java-agent/instrumentation/java-concurrent/src/test/groovy/executor/RejectedExecutionTest.groovy
- dd-java-agent/instrumentation/jetty-util/src/test/groovy/JettyExecutorInstrumentationTest.groovy
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-0.3/src/test/groovy/OpenTelemetryTest.groovy
- dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
- dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
- dd-java-agent/instrumentation/play-2.3/src/main/java/datadog/trace/instrumentation/play23/RequestCompleteCallback.java
- dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play24/RequestCompleteCallback.java
- dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/RequestCompleteCallback.java
- dd-java-agent/instrumentation/play-ws-1/src/main/java/datadog/trace/instrumentation/playws1/AsyncHandlerWrapper.java
- dd-java-agent/instrumentation/play-ws-2.1/src/main/java/datadog/trace/instrumentation/playws21/AsyncHandlerWrapper.java
- dd-java-agent/instrumentation/play-ws-2/src/main/java/datadog/trace/instrumentation/playws2/AsyncHandlerWrapper.java
- dd-java-agent/instrumentation/scala-concurrent/src/test/groovy/ScalaExecutorInstrumentationTest.groovy
- dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
- dd-java-agent/instrumentation/spring-scheduling-3.1/src/main/java/datadog/trace/instrumentation/springscheduling/SpannedMethodInvocation.java
- dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceStrictWriteTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
Most of these are calls after activating a continuation - but scopes created from continuations have async propagation enabled already: https://github.com/DataDog/dd-trace-java/blob/v1.47.0/dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java#L160
The other non-test changes are a few places in the servlet / play instrumentations where we turned off async propagation for scopes that we've closed and are about to remove from the scope stack. Setting async propagation at this point has no affect.
The remaining cases are leftovers from refactoring in test code
Helps make it clearer where we really need/want to change the async propagation flag.
- Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CON …
> Remove unnecessary calls to setAsyncPropagationEnabled

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AdviceUtils.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExecutorInstrumentationUtils.java
- dd-java-agent/instrumentation/guava-10/src/main/java/datadog/trace/instrumentation/guava10/ListenableFutureInstrumentation.java
- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/executor/JavaExecutorInstrumentation.java
- dd-java-agent/instrumentation/scala-promise/src/main/java/datadog/trace/instrumentation/scala/PromiseHelper.java
i.e. we should have a non-null, valid span and the async propagation flag should be set
(also remove some unused variables in the executor advice)
Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to …
> Be consistent when deciding when to do async propagation

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AdviceShader.java
When having more than 1 shaded instrumentation module, the wrong helpers are injected since we do not have uniqueness in the package name for each shaded module but we just use 'shaded' for the shaded version.
I'm proposing using the hashcode of the relocation maps to ensure that. …
> Ensure shaded helpers have unique names

- .gitlab-ci.yml
Integrate the latest changes on one-pipeline.
Configure and run the system-tests pipeline (only for ssi tests)
Simplify the pipeline to run the system-tests ssi tests …
> ssi tests one-pipeline

- dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaActorCellInstrumentation.java
- dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaMailboxInstrumentation.java
- dd-java-agent/instrumentation/pekko-concurrent/src/main/java/datadog/trace/instrumentation/pekko/concurrent/PekkoActorCellInstrumentation.java
- dd-java-agent/instrumentation/pekko-concurrent/src/main/java/datadog/trace/instrumentation/pekko/concurrent/PekkoMailboxInstrumentation.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
These remaining cases were no-op spans which are already not propagated …
> Simplify activateSpan API to not include async propagation flag

- dd-smoke-tests/log-injection/src/test/groovy/datadog/smoketest/LogInjectionSmokeTest.groovy
- dd-smoke-tests/sample-trace/src/test/groovy/datadog/smoketest/SampleTraceSmokeTest.groovy
Mark the top flaky tests of the week as flaky.
Keep the CI as stable as possible
I can't find IBM8 JVM to setup locally so I didn't try to fix it in the first place. …
> Mark tests as flaky

- buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/impl/AdviceGeneratorImpl.java
- buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/impl/ext/IastExtension.java
- buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/util/CallSiteConstants.java
- buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/AdviceGeneratorTest.groovy
- buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/assertion/AdviceAssert.groovy
- buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/assertion/AssertBuilder.groovy
- buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/ext/IastExtensionTest.groovy
- dd-java-agent/agent-tooling/src/jmh/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteBenchmarkInstrumentation.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/Advices.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteTransformer.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/csi/CallSiteAdvice.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/csi/CallSites.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/BaseCallSiteTest.groovy
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteInstrumentationTest.groovy
- dd-java-agent/instrumentation/iast-instrumenter/src/test/java/MockCallSites.java
- dd-java-agent/instrumentation/iast-instrumenter/src/test/java/MockRaspCallSites.java
- dd-java-agent/instrumentation/java-io/src/test/groovy/datadog/trace/instrumentation/java/io/ObjectInputStreamCallSiteTest.groovy
- dd-java-agent/instrumentation/java-io/src/test/java/foo/bar/TestCustomObjectInputStream.java
Disallows the usage of before call sites in calls to super in constructors which is not allowed by the JVM.
We got a report from a customer with an issue blocking the startup of a app due to:
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
Location:
org/redisson/codec/CustomObjectInputStream.<init>(Ljava/lang/ClassLoader;Ljava/io/InputStream;Ljava/util/Set;)V @32: invokestatic
Reason:
Type uninitializedThis (current frame, stack[3]) is not assignable to 'java/io/InputStream'
Current Frame:
bci: @32
flags: { flagThisUninit }
locals: { uninitializedThis, 'java/lang/ClassLoader', 'java/io/InputStream', 'java/util/Set' }
stack: { '[Ljava/lang/Object;', uninitializedThis, 'java/io/InputStream', uninitializedThis }
Bytecode:
0000000: 2a2c b200 8110 1e04 b800 8604 bd00 …
```
> Prevent before callsites targeting constructors in super calls

- dd-smoke-tests/play-2.4/conf/logback.xml
- dd-smoke-tests/play-2.5/conf/logback.xml
- dd-smoke-tests/play-2.6/conf/logback.xml
- dd-smoke-tests/play-2.7/conf/logback.xml
- dd-smoke-tests/play-2.8-otel/conf/logback.xml
- dd-smoke-tests/play-2.8-split-routes/conf/logback.xml
- dd-smoke-tests/play-2.8/conf/logback.xml
Simplify logging config for Play smoke tests.
In some modules (`play-2.4`) this led to errors, which were masked because the suite was marked as flaky;
```
Condition not satisfied:
errorLogs.isEmpty()
|         |
|         false
[16:23:12,038 |-ERROR in ch.qos.logback.core.pattern.parser.Compiler@b27b210 - Failed to instantiate converter class [play.api.libs.logback.ColoredLevel] for keyword [coloredLevel] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type play.api.libs.logback.ColoredLevel, 16:23:12,039 |-ERROR in ch.qos.logback.core.pattern.parser.Compiler@b27b210 - [coloredLevel] is not a valid conversion word, 16:23:12,038 |-ERROR in ch.qos.logback.core.pattern.parser.Compiler@b27b210 - Failed to instantiate converter class …
```
> Fix PlayNettySmokeTest logging config

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/WebsocketDecorator.java
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
As part of websocket tracing, the tag `_dd.dm.inherited` is a meta and not a metric. Hence let's stringify it …
> Inherited decision maker is a meta

- components/context/src/main/java/datadog/context/Context.java
- components/context/src/main/java/datadog/context/ContextManager.java
- components/context/src/main/java/datadog/context/ThreadLocalContextManager.java
- components/context/src/test/java/datadog/context/ContextProviderForkedTest.java
- components/context/src/test/java/datadog/context/ContextTest.java
We haven't needed a non-empty root context, and collapsing these concepts together simplifies the code. …
> Simplification: Context.root() is always empty

- buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/impl/AdviceGeneratorImpl.java
- buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/impl/ext/IastExtension.java
- buildSrc/call-site-instrumentation-plugin/src/main/java/datadog/trace/plugin/csi/util/CallSiteConstants.java
- buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/AdviceGeneratorTest.groovy
- buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/assertion/AdviceAssert.groovy
- buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/assertion/AssertBuilder.groovy
- buildSrc/call-site-instrumentation-plugin/src/test/groovy/datadog/trace/plugin/csi/impl/ext/IastExtensionTest.groovy
- dd-java-agent/agent-tooling/src/jmh/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteBenchmarkInstrumentation.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/Advices.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteTransformer.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/csi/CallSiteAdvice.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/csi/CallSites.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/BaseCallSiteTest.groovy
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteInstrumentationTest.groovy
- dd-java-agent/instrumentation/iast-instrumenter/src/test/java/MockCallSites.java
- dd-java-agent/instrumentation/iast-instrumenter/src/test/java/MockRaspCallSites.java
- dd-java-agent/instrumentation/java-io/src/test/groovy/datadog/trace/instrumentation/java/io/ObjectInputStreamCallSiteTest.groovy
- dd-java-agent/instrumentation/java-io/src/test/java/foo/bar/TestCustomObjectInputStream.java
Backport #8549 to release/v1.47.x
> 🍒 8549 - Prevent before callsites targeting constructors in super calls

- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/user/AppSecEventTrackerSpecification.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/user/EventTrackerAppSecDisabledForkedTest.groovy
- dd-java-agent/appsec/src/testFixtures/groovy/com/datadog/appsec/AppSecHttpServerTest.groovy
- dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/SpringBootBasedTest.groovy
- dd-java-agent/instrumentation/spring-security-5/src/test/groovy/datadog/trace/instrumentation/springsecurity5/UserController.groovy
- dd-trace-api/build.gradle
- dd-trace-api/src/main/java/datadog/appsec/api/user/User.java
- dd-trace-api/src/main/java/datadog/appsec/api/user/UserService.java
- internal-api/src/main/java/datadog/trace/api/appsec/AppSecEventTracker.java
Adds a public API for customers to set user related data in the spans aligned with what other tracers are [doing](http://docs.datadoghq.com/security/application_security/threats/add-user-info/?tab=set_user&code-lang=python#adding-authenticated-user-information-to-traces-and-enabling-user-blocking-capability). 
Before:
```java
import io.opentracing.Span;
import io.opentracing.util.GlobalTracer;
import datadog.appsec.api.blocking.Blocking;
import datadog.trace.api.interceptor.MutableSpan;
// Get the active span
final Span span = GlobalTracer.get().activeSpan();
if ((span instanceof MutableSpan)) {
MutableSpan localRootSpan = ((MutableSpan) span).getLocalRootSpan();
// Setting the mandatory user id tag
localRootSpan.setTag("usr.id", "d131dd02c56eec4");
// Setting optional user monitoring …
```
> Add setUser to user monitoring SDK

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/codeorigin/DefaultCodeOriginRecorder.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/CodeOriginProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/origin/CodeOriginTest.java
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/CodeOriginIntegrationTest.java
- dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
Eliminates some unnecessary calls to String.format() so that they don't show up in the flamegraph when looking at traces.
- Update the …
> Introduce constants to eliminate unnecessary calls to String.format()

- static-analysis.datadog.yml
> Disable some static analysis rules

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
When Data **Jobs** Monitoring is enabled, we also enable Data **Streams** Monitoring (set `data.streams.enabled` to true) and two integrations required for end to end pipeline monitoring:
- `integration.aws-sdk.enabled`
- `integration.kafka.enabled`
For end to end pipeline monitoring, we want the onboarding of customers to be easy: adding `DD_DATA_JOBS_ENABLED=true` will suffice with this PR …
> e2e pipeline configuration when data jobs is enabled

- dd-trace-core/src/main/java/datadog/trace/core/baggage/BaggagePropagator.java
It also generates a large amount of log messages when tracer debug is on.
> Most contexts won't have baggage, so this debug line is not that helpful

- .circleci/config.continue.yml.j2
Add TRACING_CONFIG_NONDEFAULT, TRACING_CONFIG_NONDEFAULT_2 and TRACING_CONFIG_NONDEFAULT_3 in CI
Two days ago, a possible regression has been pushed to `master` ([nightly job](https://github.com/DataDog/system-tests-dashboard/actions/runs/13984998284/job/39157640605#step:33:50)). Those scenario will prevent this (and other) in the future.
Wait for DataDog/system-tests#4355 before merging this …
> Add scenario TRACING_CONFIG_NONDEFAULT in system-tests

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Mitigates potential delays in mapping IP addresses back to their hostnames.
The `peer.hostname` tag feature can also be turned off completely by adding this JVM option:
```
-Ddd.trace.peer.hostname.enabled=false
```
or setting this environment variable:
```
DD_TRACE_PEER_HOSTNAME_ENABLED=false
```
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using …
> Introduce cache for peer.hostname lookup

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Backport #8601 to release/v1.47.x
Mitigates potential delays in mapping IP addresses back to their hostnames.
The `peer.hostname` tag feature can also be turned off completely by adding this JVM option:
```
-Ddd.trace.peer.hostname.enabled=false
```
or setting this environment variable:
```
DD_TRACE_PEER_HOSTNAME_ENABLED=false
```
> 🍒 8601 - Introduce cache for peer.hostname lookup

- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/TempLocationManager.java
- dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/TempLocationManagerTest.java
It makes the temp location base dir to be 'username' specific.
Allow parallel runs of multiple services under multiple users without fighting for the ownership of the base dir.
Also, it is highly probably that the temporary artifacts created for one user will not be deletable by other user, so having the basedir per-user makes sense.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#lin …
> Make TempLocationManager USER aware

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/TestManagementSettings.java
Fixes a bug where if the backend doesn't provide a number of retries for Attempt to Fix tests the test won't be retried at all, as it defaulted to -1. Now it defaults to 20 (the original number of retries planned in the RFC). …
> Set default Attempt to Fix retries if none provided from the backend

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ThirdPartyLibraries.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/symbol/SymbolExtractionTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/ClassNameFiltering.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ThirdPartyLibrariesTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymDBEnablementTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymbolExtractionTransformerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/ClassNameFilteringTest.java
- dd-trace-api/src/main/java/datadog/trace/api/config/DebuggerConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/main/java/datadog/trace/util/ClassNameTrie.java
- internal-api/src/test/groovy/datadog/trace/util/ClassNameTrieTest.groovy
Add filtering on shading identifiers
Add option to add more shading idententifiers …
> Add support for filtering shaded third-party libs

- dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaActorCellInstrumentation.java
- dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaMailboxInstrumentation.java
- dd-java-agent/instrumentation/pekko-concurrent/src/main/java/datadog/trace/instrumentation/pekko/concurrent/PekkoActorCellInstrumentation.java
- dd-java-agent/instrumentation/pekko-concurrent/src/main/java/datadog/trace/instrumentation/pekko/concurrent/PekkoMailboxInstrumentation.java
Activate the task scope before checkpointing to make sure we can close it out in the right order, regardless whether it's already active or not before the advice. We can then simplify the rest of the advice because the checkpointing feature will close out any scopes that leaked out after the checkpoint.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue …
> Simplify the Akka/Pekko checkpointing advice

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestImpl.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/domain/TestSuiteImpl.java
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
- dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java
- dd-java-agent/instrumentation/karate/src/main/java/datadog/trace/instrumentation/karate/KarateTracingHook.java
- dd-java-agent/instrumentation/undertow/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/HttpRequestParserInstrumentation.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
This PR adds an `activateSpanWithoutScope(span)` method to self-document this behaviour and explicitly tie it to the use of `closeActive()`.
There are a few instrumentations where the instrumented code does not align with scopes. In such situations the span is activated, but the scope is thrown away. The span is then closed in another section of code using `closeActive()`.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issue …
> Document when we manage a span's lifecycle without scopes

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
- dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/ServerDebuggerTestApplication.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/InProductEnablementIntegrationTest.java
Wait for feature started before sending request to avoid racy startup …
> Fix flaky InProduct enablement smoke test

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/user/AppSecEventTrackerSpecification.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/user/EventTrackerAppSecDisabledForkedTest.groovy
- dd-java-agent/instrumentation/spring-security-5/src/main/java/datadog/trace/instrumentation/springsecurity5/SpringSecurityUserEventDecorator.java
- dd-trace-api/build.gradle
- dd-trace-api/src/main/java/datadog/appsec/api/login/EventTrackerService.java
- dd-trace-api/src/main/java/datadog/appsec/api/login/EventTrackerV2.java
- dd-trace-api/src/main/java/datadog/trace/api/EventTracker.java
- dd-trace-api/src/main/java/datadog/trace/api/GlobalTracer.java
- internal-api/src/main/java/datadog/trace/api/appsec/AppSecEventTracker.java
- internal-api/src/main/java/datadog/trace/api/telemetry/LoginEvent.java
- internal-api/src/main/java/datadog/trace/api/telemetry/LoginVersion.java
- internal-api/src/main/java/datadog/trace/api/telemetry/WafMetricCollector.java
- internal-api/src/test/groovy/datadog/trace/api/telemetry/WafMetricCollectorTest.groovy
Introduces V2 of the ATO public SDK which main difference is the disctintion between user logins and user ids. Previous version V1 of the SDK is marked as deprecated and won't be removed until the next major release of the tracer. …
> Update login events public SDK to V2

- settings.gradle
Changelog since 3.18:
```
3.18.1:
- [NEW] Build Cache: Increase parallel remote build cache operation limit
- [FIX] Build Scan: Resource usage capturing causes excessive logging on Linux when udev is absent
- [FIX] Build Scan: Display name extraction for Java commands with multiple -jar arguments fails when resource usage capturing is enabled
3.18.2:
- [NEW] Test Retry: Add a `failOnSkippedAfterRetry` property to control whether the test task should fail if a failed test got skipped on retry
- [FIX] Build Scan: Resource usage capturing fails silently when the build uses an incompatible JNA version
3.19:
- [NEW] Build Cache: Support Edge discovery based on a Develocity user's location preference
- [NEW] Build Scan: Capture actual CPU load for the top 5 processes by CPU usage
- [NEW] Build …
```
> Upgrade to develocity plugin 3.19.2

- .circleci/config.continue.yml.j2
- .circleci/no_circleci_changes.sh
- .circleci/render_config.py
* Skip Circle CI if only GitLab files change
* Disable flaky jobs in master
* Move jdk 11 jobs to master-only in Circle CI
* Move ssi_smoke tests to master-only in Circle CI …
> Reduce number of jobs running in Circle CI

- dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
- dd-trace-core/src/main/java/datadog/trace/core/StreamingTraceCollector.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ScopeContinuation.java
- dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceStrictWriteTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTraceCollector.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Move capture and canceled continuation metrics to the same class (previously we only recorded a canceled continuation metric when pending trace was enabled, not when streaming spans)
Fixed finished continuation metric (this was in the wrong place which meant it was only recorded when closing message spans)
More accurate metrics for continuations
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to- …
> Fix continuation metrics

- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
Follow-up to #8636 to handle the edge case where non-span context is already active when activating a span. …
> When activating a span merge it with any non-span context

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CodeOriginInstrumentor.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/CodeOriginProbe.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/origin/CodeOriginTest.java
- dd-java-agent/agent-debugger/src/test/resources/com/datadog/debugger/CodeOrigin05.java
With the changes to how code origins are instrumented and the deferral of exit span support, the application of the instrumentation for these exit spans ended up at the beginning of the method rather than the line itself.  Largely, i think is also a side effect of these probes starting off as context capturing probes which would always get instrumented at the method start for $reasons.  This PR moves the exit span instrumentation down to the exact line where it "should" be.
> Fix the instrumentation to instrument at the exit line

- dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/OtelContext.java
- dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/OtelScope.java
- dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/propagation/AgentTextMapPropagator.java
- dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/trace/OtelSpanBuilder.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OpenTelemetryContextInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/context/OpenTelemetryContextStorageInstrumentation.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/opentelemetry14/context/ContextForkedTest.groovy
The new internal Context API aligns better with OpenTelemetry and lets us simplify management of contexts from manual instrumentation (no need to shadow the scope management with an attachable wrapper. and therefore no need for scopes or their wrappers to have state - they are true closeables)
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-k …
> Migrate OtelContext wrapper to new internal Context API

- .circleci/config.continue.yml.j2
- dd-java-agent/appsec/build.gradle
- dd-java-agent/appsec/src/jmh/java/datadog/appsec/benchmark/BenchmarkUtil.java
- dd-java-agent/appsec/src/jmh/java/datadog/appsec/benchmark/WafBenchmark.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/api/security/AppSecSpanPostProcessor.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/ddwaf/WAFInitializationResultReporter.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/ddwaf/WAFModule.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/ddwaf/WAFResultData.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/ddwaf/WAFStatsReporter.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/ddwaf/WafInitialization.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/report/AppSecEvent.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/util/StandardizedLogging.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/AppSecSystemSpecification.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/api/security/AppSecSpanPostProcessorTest.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/ddwaf/DataBundleMapWrapperSpecification.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/ddwaf/WAFModuleSpecification.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/ddwaf/WAFStatsReporterSpecification.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/data/KnownAddressesSpecificationForkedTest.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/report/AppSecEventWrapperTest.groovy
- internal-api/src/main/java/datadog/trace/api/telemetry/WafMetricCollector.java
- telemetry/src/main/java/datadog/telemetry/log/LogPeriodicAction.java
Renames classes to reflect better for libddwaf upgrade 1.23.0. Also a minor change to KnownAddressSpecification test as it is affected by other tests(switch to forked) …
> Rename classes to better reflect their counterparts in libddwaf

- dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.5/src/test/groovy/KotlinCoroutineInstrumentationTest.groovy
- dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.5/src/test/kotlin/KotlinCoroutineTests.kt
- dd-java-agent/instrumentation/kotlin-coroutines/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/CoroutineContextHelper.java
- dd-java-agent/instrumentation/kotlin-coroutines/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/ScopeStateCoroutineContext.java
- dd-java-agent/instrumentation/kotlin-coroutines/src/testFixtures/groovy/datadog/trace/instrumentation/kotlin/coroutines/AbstractKotlinCoroutineInstrumentationTest.groovy
- dd-java-agent/instrumentation/kotlin-coroutines/src/testFixtures/kotlin/datadog/trace/instrumentation/kotlin/coroutines/CoreKotlinCoroutineTests.kt
Restore parent scope stack after completing coroutines
Uses method handles to extract the parent for different versions of Kotlin coroutines. We could avoid this by moving the helpers into the version specific instrumentations and specializing them, but then we'd need to duplicate several classes.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using …
> Avoid disconnected traces when using Kotlin flowOn

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AsyncResultExtensions.java
- dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
- dd-java-agent/instrumentation/spring-webmvc-3.1/build.gradle
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/AppConfig.groovy
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/SpringBootBasedTest.groovy
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/latestDepTest/groovy/test/boot/TestController.groovy
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerAdapterInstrumentation.java
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/InvocableHandlerMethodInstrumentation.java
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/SpringWebHttpServerDecorator.java
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SpringBootBasedTest.groovy
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/TestController.groovy
- dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java/datadog/trace/instrumentation/springweb6/InvocableHandlerMethodInstrumentation.java
- dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java17/datadog/trace/instrumentation/springweb6/ControllerAdvice.java
- dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java17/datadog/trace/instrumentation/springweb6/SpringWebHttpServerDecorator.java
- dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java17/datadog/trace/instrumentation/springweb6/WrapContinuableResultAdvice.java
- dd-java-agent/instrumentation/spring-webmvc-6.0/src/test/groovy/datadog/trace/instrumentation/springweb6/boot/TestController.groovy
This PR allows tracking the right span duration when `CompletableFuture` are returned on spring controllers. 
In fact, we were just finishing the span right after the controller calls returned instead of waiting that the future completed.
It also avoids async controllers to be traced twice since the advices was kicking in the first time when the handler was called and the second time when the future is resolved. (see the linked issue below in which we can see that the controller span twice).
Note: this PR will then change the duration of impacted controller span hence also their metrics. However, those spans are not entry point hence service RED metrics will not be impacted.
Now the duration looks more realistic. 
Given that code:
```
@RestController
public class TestController { …
```
> Support CompletableFuture on spring webmvc controllers

- dd-java-agent/instrumentation/vertx-mysql-client-3.9/src/test/groovy/VertxSqlClientForkedTest.groovy
- dd-java-agent/instrumentation/vertx-mysql-client-4.0/src/test/groovy/VertxSqlClientForkedTest.groovy
Removes strict trace buffering since, when the root span is missing, the handler span (the result callback) is not guaranteed to finish before the sql call span (there can be wait when the CPU is busy especially in CI)
Relates to `test #type without parent` from `VertxSqlClientForkedTest` flakiness
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-usin …
> Don't use strict trace writing for vertx sql tests

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/test/ExecutionStrategy.java
Lowers the level of the log from `error` to `debug` when the source path resolution fails on a `isModified` check.
Got feedback and questions from customers regarding the error log they were finding in their runs when having duplicate class names in their projects. Lowering it to debug level as it is not actionable on their side.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking …
> Remove error log when source path resolution fails on isModified check

- utils/socket-utils/src/main/java17/datadog/common/socket/TunnelingJdkSocket.java
- utils/socket-utils/src/test/java/datadog/common/socket/TunnelingJdkSocketTest.java
Following #8314, this PR allows users to set the send and receive buffer sizes by overriding the `setSendBufferSize` and `setReceiveBufferSize` `Socket` methods. The default size is set to `8192`.
Allow custom buffer sizes for the JDK support of UDS.
Use …
> Add buffer size customizability to JDK UDS support

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/ddwaf/WAFModule.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/ddwaf/WAFModuleSpecification.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy
- internal-api/src/main/java/datadog/trace/api/telemetry/WafMetricCollector.java
- internal-api/src/test/groovy/datadog/trace/api/telemetry/WafMetricCollectorTest.groovy
- Remove counters from AppsecRequestContext as they are not used in the metrics
- Fix appsec.waf.error metric tags as they didn't match the RFC
- Fix that appsec.waf.error was created in the same loop using the rasp counter instead of using the waf counter
- Increment metrics if UnclassifiedPowerwafException is thrown
- Replace ConcurrentHashMap with AtomicLongArray for raspErrorCodeCounter to improve performance and memory efficiency
- Add test to cover WafModule implementation
[RFC](https://docs.google.com/document/d/1D4hkC0jwwUyeo0hEQgyKP54kM1LZU98GL8MaP60tQrA/edit?tab=t.0#heading=h.6shrh2msb59g)
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-da48a29c-7fff-7e4c-94ec-72d5ae20b262"><div dir="ltr" style="margin-left:0pt;" align="center">
appsec.waf.error | …
> Fix appsec.rasp.error and appsec.waf.error telemetry metrics

- dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/OOMENotifierScriptInitializer.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/profiler/EnvironmentChecker.java
- dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentJar.java
- internal-api/src/main/java/datadog/trace/api/Platform.java
It adds a new CLI command to quickly check the environment requirements for profiler
Provide a quick and easy check for whether profiler would run properly in the given environment …
> Add profiler env check command to AgentCLI

- .circleci/config.continue.yml.j2
- dd-java-agent/instrumentation/scalatest/src/main/java/datadog/trace/instrumentation/scalatest/DatadogReporter.java
- dd-java-agent/instrumentation/scalatest/src/main/java/datadog/trace/instrumentation/scalatest/RunContext.java
- dd-java-agent/instrumentation/scalatest/src/main/java/datadog/trace/instrumentation/scalatest/ScalatestForkInstrumentation.java
- dd-trace-api/src/main/java/datadog/trace/api/config/CiVisibilityConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Prevents double reporting of Scalatest events when using SBT with test forking.
When running an SBT build with Test/fork set to true, Scalatest reporter that we instrument is initialised both in the parent process and in the child process.
We only want to instrument the one in the child process, since the child process is where the tests are actually executed.
We distinguish the child process from the parent process by examining the "remote arguments" of the Scalatest runner: in the child process the remote arguments are not empty (as they define how to interact with the parent).
I could not find a way to determine SBT + Test/fork + Scalatest case automatically, so for the time being the instrumentation has to be activated manually with the `DD_CIVISIBILITY_SCALATEST_FORK_MONITOR_ENABLED` …
> Prevent double reporting of Scalatest events when using SBT with test forking

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DefaultProductConfigUpdater.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DefaultProductConfigUpdaterTest.java
should not stop the product with empty config
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/librar …
> Fix In-Product when config is empty

- utils/socket-utils/src/main/java17/datadog/common/socket/TunnelingJdkSocket.java
Deletes print line creating *millions of log messages for customers.
Address support tickets such as: https://datadog.zendesk.com/agent/tickets/2101785, https://datadog.zendesk.com/agent/tickets/2101966 …
> Delete print line

- communication/src/main/java/datadog/communication/monitor/DDAgentStatsDClientManager.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Currently, the `DD_DOGSTATSD_PORT` environment variable and `dd.dogstatsd.port` system property only affect the dogstatsd port used by the embedded JMXFetch client. With this change, the configured port is also used by the tracer's dogstatsd client unless overridden by the agent.
With Crashtracking tests, it was impossible to supply another port. Additionally, respecting the environment variable makes the tracer more consistent.
It's impossible to test this change directly because `DDAgentStatsDClientManager` makes heavy use of `static` fields and methods. It's tested indirectly in #8685
- Assign the `type:` and (`comp:` or `inst:`) labels in …
> Allow dogstatsd port to be configurable with DD_DOGSTATSD_PORT

- dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
- dd-java-agent/src/main/java/datadog/trace/bootstrap/SystemUtils.java
Add the possibility to use a system property to force injection of the tracing library even though multiple javaagents have been detected.
Forcing the library injection can now be done:
- by setting the env variable `DD_INJECT_FORCE` to 1 or true
- by setting the system property `dd.inject.force` to 1 or true
[APMS-15377](https://datadoghq.atlassian.net/browse/APMS-15377)
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues …
> Add system property to force injection of the tracing library even though multiple javaagents have been detected

- internal-api/src/main/java/datadog/trace/api/Config.java
Changes the default value of `dd.jdk.socket.enabled` to `false`
Mitigation for https://github.com/DataDog/dd-trace-java/issues/8696 while we address some differences in behaviour between the JFFI and JDK tunnelling socket implementations. 
Use `solves` …
> Turn off JDK socket support by default

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ValueReferences.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/PrettyPrintVisitor.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/FilterCollectionExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/HasAllExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/HasAnyExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/FilterCollectionExpressionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/HasAllExpressionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/HasAnyExpressionTest.java
Introduce 2 synthetic variables in Expression Language:
- `@key`
- `@value`
to reference directly key or value when filtering on a map (filter, any, all) on top of existing @it variable. fix pretty print for filtering expression to add curly braces
Use …
> Add support for @key and @value for Map filtering

- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScope.java
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
Akka/Pekko actor instrumentations use the scope checkpoint and rollback mechanism to clean up scopes after async operations. To properly handle reentrant scope checkpointing and rollback we need to use a count in `ContinuableScope` like `referenceCount` rather than just a flag.
This is necessary because ContinuableScopeManager re-uses scope instances when activating the same span twice.
If scopes weren't re-used in this way then we could use a simple flag per scope.
- Don't use `close`, …
> Handle reentrant scope cleanup in Akka/Pekko actor instrumentations

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/SourceFileTrackingTransformer.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SourceFileTrackingTransformerTest.java
- dd-smoke-tests/debugger-integration-tests/src/main/java/datadog/smoketest/debugger/ServerDebuggerTestApplication.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/CodeOriginIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/InProductEnablementIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ServerAppDebuggerIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/SimpleAppDebuggerIntegrationTest.java
Source file tracking is enqueueing classfile buffer to be processed by a background thread avoiding startup delay. …
> Make source file tracking asynchronous

- dd-java-agent/instrumentation/spark/spark_2.12/src/test/groovy/SparkListenerTest.groovy
- dd-java-agent/instrumentation/spark/spark_2.13/src/test/groovy/SparkListenerTest.groovy
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/AbstractDatadogSparkListener.java
- dd-java-agent/instrumentation/spark/src/main/java/datadog/trace/instrumentation/spark/OpenlineageParentContext.java
- dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/AbstractSparkListenerTest.groovy
- dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/OpenlineageParentContextTest.groovy
This utilizes [newly added root parent information](https://docs.google.com/document/d/18mM5dvkRyEfu_bdnncnKqESy_OxryhQCoNpaiETGvFE/edit?tab=t.0#heading=h.ybn2wcihja7v) in OpenLineage context to deterministically generate TraceId and SpanId out of it.
[This allows us to generate consistent traces across data jobs.](https://dd.datad0g.com/data-jobs/jobs/emr_livy_iceberg_jobs_manual_tracer/runs/9066186736484372620?colorByAttr=name&fromUser=false&graphType=flamegraph&runsSortColumn=started&runsSortDirection=desc&shouldShowLegend=true&sort=time&spanID=9066186736484372620&start=1744805082953&end=1745409882953&paused=false)
- Assign the `type:` and …
> Use OpenLineage root parent information to generate trace id

- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactoryForkedTest.groovy
- utils/test-utils/src/main/groovy/datadog/trace/test/util/ConfigTransformSpockExtension.groovy
This matches the same setting used by AgentInstaller which avoids spurious test failures in agent-tooling, specifically TypeFactoryForkedTest. This requires raw-types enabled to match the behaviour when installing the tracer with -javaagent. Without this byte-buddy will use dufferent code paths involving generic checks, which can lead to test failures using recent versions of byte-buddy (specifically going between full and outline types, where outlines are always raw-types by their nature.)
These failures would not happen when using -javaagent because AgentInstaller forces the use of the raw-types setting. ConfigTransformSpockExtension should therefore do the same.
Note we can't set this property in TypeFactoryForkedTest because by then it is too late, byte-buddy is already confgured by …
> Ensure net.bytebuddy.raw is set to true when ConfigTransformSpockExtension is installed

- .circleci/config.continue.yml.j2
- dd-java-agent/instrumentation/mule-4/build.gradle
- dd-java-agent/instrumentation/spark/src/testFixtures/groovy/datadog/trace/instrumentation/spark/AbstractSparkListenerTest.groovy
Reverts DataDog/dd-trace-java#8709
This change is unnecessary given our excluding extra classes in the latest byte-buddy upgrade. It also caused us to miss some testing on PRs, namely with #8720 (resolved by #8728).
> Revert "Update config line to account for large binary files"

- dd-trace-core/src/main/java/datadog/trace/common/sampling/DeterministicSampler.java
- dd-trace-core/src/test/groovy/datadog/trace/common/sampling/DeterministicTraceSamplerTest.groovy
The sampling formula has changed a bit to have an consistent one across all tracers. The change is relatively small in Java as it only require a change from `<` to `<=`
We are aiming to have consistent sampling over all tracers.
I added a new TraceID to the unit test that lands exactly on `0.5 * (2^64 -1)` when multiplicated by the knuth
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue …
> Update trace sampling formula

- dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
- dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy
Adds process tags to stats client payload. 
See https://github.com/DataDog/datadog-agent/pull/35746 and https://github.com/DataDog/dd-trace-java/pull/8698
Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones …
> Add process tags to client stats payload

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/Redaction.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/test/java/datadog/trace/bootstrap/debugger/util/RedactionTest.java
exclude identifiers provided by configuration were not normalized …
> Fix exclude identifiers normalization

- dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkControllerTest.java
- dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkOngoingRecordingTest.java
- dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkRecordingDataTest.java
- dd-java-agent/instrumentation/exception-profiling/src/test/groovy/datadog/trace/bootstrap/instrumentation/jfr/exceptions/KnownExcludesForkedTest.groovy
- dd-java-agent/instrumentation/exception-profiling/src/test/java/datadog/trace/bootstrap/instrumentation/jfr/exceptions/ExceptionHistogramTest.java
- dd-java-agent/instrumentation/java-directbytebuffer/src/test/groovy/DirectAllocationTrackingTest.groovy
It does what it says - it will prevent unexpected test failures on J9 with JFR stub implementation.
> Do not run JFR specific tests on J9

- dd-java-agent/instrumentation/reactor-core-3.1/src/main/java/datadog/trace/instrumentation/reactor/core/ContextSpanHelper.java
Our reactor-core instrumentation needs to access to the `currentContext()` in order to _eventually_ propagate the active span the user can provide under the `dd.span` key.
The issue, raised by one customer, is that access can eat a lot of cpu time because of the way reactor is working.
In fact, the reactor operators, are nested and for InnerOperators (https://github.com/reactor/reactor-core/blob/718cc691dc3610e6a46636b2e90f1a37bb434669/reactor-core/src/main/java/reactor/core/publisher/InnerOperator.java#L33) the call is delegating to the enclosed one.
This means that on each subscribe and onNext we're calling a lot of method wasting time and causing performance issue.
That PR is addressing the issue by limiting that context access only when needed
- Format the title [according the …
> Do not inspect reactor context when not needed

- dd-java-agent/agent-tooling/build.gradle
- dd-java-agent/agent-tooling/src/jmh/java/datadog/trace/agent/tooling/ProxyIgnoreBenchmark.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ProxyClassIgnores.java
- dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/proxy_ignored_class_name.trie
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/matcher/ProxyClassIgnoresTest.groovy
When loading a class we go through different check to know if ignore the class directly or go through the bytebuddy matchers.
One of the reason of ignoring a class is that is a generated proxy (see `ProxyClassIgnored`). 
This class is running several `String.contains` in order to match possible prefixes. Since this list is subjected to grow, running `String.contains` is not looking performant also because we run this code for each inner class (containing `$` that's loaded).
A possible optimization is to leverage our `ClassNameTrie` that we are already already using. The different, for the proxy, is that we need to match starting from a group of dollars since they are inner classes
This PR introduces hence the `proxy_ignored_class_name.trie` that can be used to drive this particular prefix …
> Use prefix trie for proxy ignores

- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/TempLocationManager.java
- dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/CompositeController.java
- dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java
This modifies the way how we report the failures to initialize profiler components to DD telemetry and enhances the visibility to why the expected temporary directory structure may not get properly created.
Improve the supportability of the profiler configuration issues …
> Improve error reporting on profiler startup

- dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/proxy_ignored_class_name.trie
Excludes jackson afterburner classes from instrumentations. See https://github.com/search?q=org%3AFasterXML+4Jackson+repo%3AFasterXML%2Fjackson-module-afterburner&type=code …
> Exclude jackson afterburner dynamic classes from instrumentation

- internal-api/src/main/java/datadog/trace/api/ProcessTags.java
- internal-api/src/test/groovy/datadog/trace/api/ProcessTagsForkedTest.groovy
- remote-config/remote-config-core/src/main/java/datadog/remoteconfig/tuf/RemoteConfigRequest.java
- remote-config/remote-config-core/src/test/groovy/datadog/remoteconfig/PollerRequestFactoryTest.groovy
Adds Process tags in the remote config payload under `client_tracer.process_tags`
See also https://github.com/DataDog/datadog-agent/pull/36049/files and https://github.com/DataDog/dd-trace-java/pull/8698 …
> Add process tags as list to remote config payload

- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/TempLocationManager.java
- dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/TempLocationManagerTest.java
After #8714 the profiling tests started failing. The reason is that the `Path.getRoot()` will return `null` for a single element path because it considers it not having a root 🤷 
As a part of this change I removed the `testShortCircuit` test - because the base temp directory is now created eagerly and not lazily so it can not happen that it will not exist, and this test was asserting that exact 'short-circuit' to avoid scanning the dir structure when there is guaranteed nothing in there. …
> Fix incorrect use of Path.getRoot()

- dd-java-agent/instrumentation/kotlin-coroutines/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/ScopeStateCoroutineContext.java
- dd-java-agent/instrumentation/zio/zio-2.0/src/main/java/datadog/trace/instrumentation/zio/v2_0/FiberContext.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ScopeStack.java
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ScopeState.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ScopeStateAware.java
This PR applies some short-term defensive fixes:
* Remove `newScopeState().fetchFromActive()` code path in favour of `oldScopeState()` which does both
* Remove the cached coroutine context item when we first start closing the coroutine, not at the end
* Take defensive copy of parent scope stack when closing nested child coroutines
The parent coroutine scope stack is only used for cleanup purposes in certain situations and using a defensive copy avoids potential concurrent modification issues when different child coroutines are closed at the same time across multiple threads.
This code is being refactored as part of further context improvements, so these defensive fixes are only needed in the short-term.
- Format the title [according the contribution …
> Take defensive copy of parent scope stack when closing nested coroutines

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/api/Java8BytecodeBridge.java
Introduce Java 8 bytecode bride.
> In instrumentation, we may need to call these methods in code that is inlined into an instrumented class, however many times the instrumented class has been compiled to a previous version of bytecode, and so we cannot inline calls to static interface methods, as those were not supported prior to Java 8 and will lead to a class verification error.
Add has context API helpers …
> Introduce Java 8 bytecode bridge for instrumentation API

- dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/TempLocationManager.java
- dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/TempLocationManagerTest.java
It removes the 'cleanup-on-shutdown' functionality from the `TempLocationManager`
This cleanup can race against profiling-snapshot-on-shutdown and prevent those profiling snapshots to be sucessfully generated.
All of this for a small benefit of not having a few MiB of temp files for slightly longer time - the cooperative cleanup, when any other java process with the profiler starts up, will take care of those file anyway. …
> Remove cleanup-on-shutdown for temporary files

- setup.sh
The setup.sh check needs an additional condition if `java` binary is not Java 8. Else, gradle fails:
```
./gradlew clean spotlessApply shadowJar --rerun-tasks
(...)
> Task :dd-smoke-tests:iast-propagation:compileKotlin FAILED
FAILURE: Build failed with an exception.
Execution failed for task ':dd-smoke-tests:iast-propagation:compileKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileJava' (1.8) and 'compileKotlin' (17).
```
- Don't use `close`, …
> setup.sh should check for JAVA_HOME if  version is not 1.8

- .github/workflows/draft-release-notes-on-tag.yaml
Improve changelog generation to cleanup generated cherry pick prefix
Feedback from releaser …
> Clean up cherry-pick tags from generated changelog

- internal-api/src/main/java/datadog/trace/api/env/CapturedEnvironment.java
During #8698 the `CapturedEnvironment` has been refactored to expose the jar file info. However, some logic has been improved (like matching case-insensitive filename extension or stripping the extension with substring instead of using replace).
To avoid risks of changes in the default service naming algorithm, this PR uses the exact code that we had before
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull …
> Preserve old logic to extract jar file name

- .github/workflows/system-tests.yaml
Increase heap memory size for build step of system-tests, as we're experiencing sometimes GC memory issue : https://github.com/DataDog/dd-trace-java/actions/runs/14780117568/job/41497030067?pr=8755 
Stable CI …
> increase heap memory for build step on system-tests

- dd-java-agent/build.gradle
Remove top-level maven `pom.properties` of vendored packages as they could trigger unwanted framework checks. See APMS-15680 for an example of such a check.
Also remove some empty `META-INF/versions` directories leftover from vendoring SnakeYaml
Use …
> Remove top-level maven pom.properties of vendored packages

- dd-java-agent/instrumentation/pekko-concurrent/src/main/java/datadog/trace/instrumentation/pekko/concurrent/PekkoSchedulerInstrumentation.java
- dd-java-agent/instrumentation/pekko-concurrent/src/test/groovy/PekkoActorTest.groovy
- dd-java-agent/instrumentation/pekko-concurrent/src/test/scala/PekkoActors.scala
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
Implements propagation of span context for Pekko's asynchronous scheduled tasks. 
The new instrumentation plugs into `LightArrayRevolverScheduler#schedule` method: when a `Runnable` is scheduled, the context of currently active span is captured and attached to that `Runnable`.
Later the existing runnable instrumentation activates this context when the task is executed (potentially in a different thread).
Activating a continuation of a span is one-time only, meaning that a context that was captured can only be activated once. For this reason this specific method is instrumented, because it works by re-scheduling periodic tasks after they finish executing (so a new continuation is captured every time a periodic task is triggered).
CI Visibility's per-test code coverage relies on spans …
> Add span propagation for Pekko scheduled tasks

- dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinExecutorTaskInstrumentation.java
- dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinPoolInstrumentation.java
- dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinTaskInstrumentation.java
- dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
- internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
Update Akka's ForkJoinPool instrumentations to also instrument backported fork of the pool that is used by logs-backend (existing instrumentations can now be configured to instrument custom class names; logs-backend-specific class names will be provided in logs-backend tracer config).
CI Visibility's per-test code coverage relies on spans propagation to capture coverage data from different threads.
Without this instrumentation coverage data for test cases that use Akka is incomplete.
More context as to why logs-backend has its own ForkJoinPool implementation can be found in [this PR](https://github.com/DataDog/logs-backend/pull/74238).
- Assign the …
> Make Akka's ForkJoin pool instrumented class names configurable

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/JDBCConnectionUrlParser.java
- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DefaultConnectionInstrumentation.java
- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
- dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCConnectionUrlParserTest.groovy
Add jdbc support for sybase tds proprietary driver
- Update the [public documentation](https://docs.datadoghq.com/tracing/trace_collection/l …
> Add support for sybase tds jdbc driver

- .github/workflows/README.md
- .github/workflows/all-green.yml
Add a job in the CI that runs in PR. The job will be a success if all other jobs are skipped/success, and fails otherwise
While it's possible to enforce a green CI policy using GitHub's native "required status checks" feature, doing so requires explicitly listing all job names under branch protection rules. This approach has two key drawbacks:
- It does not support optional jobs
- It introduces ongoing maintenance overhead as the job list evolves
This jobs will check ALL other job, and we'll be able to set this as a requirement. The action used offers a `ignored-name-patterns` parameters`, I added few job that failed more than 10% over the last 60 days on merges.
The plan is to merge this PR, wait few days to be sure that everything is fine. Then add it as a requirement.
- Format the …
> Add a gatekeeper job for PR

- buildSrc/src/main/groovy/MuzzlePlugin.groovy
- dd-java-agent/instrumentation/play-2.3/build.gradle
- dd-java-agent/instrumentation/play-2.4/build.gradle
- dd-java-agent/instrumentation/play-2.6/build.gradle
- dd-java-agent/instrumentation/restlet-2.2/build.gradle
Follow up to #8554 and #8592 . Has muzzle use the internal proxy. Additionally, special case repositories were moved from the muzzle plugin to the `extraRepository` directive of individual projects.
Testing was done by remove `central` as a repository to ensure muzzle still passed with only the proxy working.
Muzzle checks were not using the internal proxy and susceptible to maven central rate limits …
> Have muzzle checks use internal artifact proxy

- internal-api/src/main/java/datadog/trace/api/Config.java
- utils/socket-utils/src/main/java17/datadog/common/socket/TunnelingJdkSocket.java
- utils/socket-utils/src/test/java/datadog/common/socket/TunnelingJdkSocketTest.java
Address file leakage issue with the native UDS implementation.
Update closing technique such that when the input stream, output stream, or socket is closed, all resources (i.e. input stream, output stream, channel, selector, and socket) are closed. This better matches expected socket behavior.
Turn JDK socket support by default back on.
Resolve issue: https://github.com/DataDog/dd-trace-java/issues/8696
Update closing technique to match expected behavior - [closing the input stream should close the socket](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/net/Socket.java#L922-L923), [closing the output stream should close the socket](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/net/Socket.java#L1040-L1041), and [closing the socket …
> Solve file leakage and turn JDK socket support on by default

- dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/OtelContext.java
- dd-java-agent/agent-otel/otel-shim/src/main/java/datadog/opentelemetry/shim/context/propagation/AgentTextMapPropagator.java
This PR adds context API support to OTel propagators
This will propagate the full internal Datadog context using OTel propagator, not only the tracing one.
Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestone …
> Add context API support OTel propagators

- dd-java-agent/instrumentation/java-security/src/test/groovy/test/WeakCipherTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/sampling/SamplerTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/PrioritizationTest.groovy
- telemetry/src/test/groovy/datadog/telemetry/TelemetryRouterSpecification.groovy
Observed when doing some testing locally - gradle only seems to notice when you add/remove a test class in the same module which I assume causes it to do a full compile (see https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-java/-/jobs/932703279)
Quick scan using `grep` revealed the following duplicates per test file:
```
2 dd-java-agent/instrumentation/java-security/src/test/groovy/test/WeakCipherTest.groovy:  def "test weak cipher instrumentation with provider string"() {
2 dd-java-agent/instrumentation/java-security/src/test/groovy/test/WeakCipherTest.groovy:  def "test weak cipher instrumentation with provider"() {
2 dd-java-agent/instrumentation/java-security/src/test/groovy/test/WeakCipherTest.groovy:  def "test weak cipher instrumentation"() {
2 …
```
> Rename test methods to remove duplicate method names

- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
We should notify registered listeners when the scope changes after switching the scope stack for coroutines or fibers - previously we switched scope stacks without notifying listeners. (This includes notifying the profiling integration that the context has switched for this thread.)
Note that switching the scope stack doesn't imply the previous scope was closed - the [ScopeListener javadoc](https://github.com/DataDog/dd-trace-java/blob/f494c33b01b4edb75bc2d47c82b9e2d3b8eb6814/internal-api/src/main/java/datadog/trace/api/scopemanager/ScopeListener.java#L11) clearly states that there may be many calls to `afterScopeActivated` as the context flows between parent and child scopes and back again. Switching between coroutines should therefore also trigger `afterScopeActivated`.
- Format the …
> Notify listeners when the scope top changes after switching scope stacks

- internal-api/src/main/java/datadog/trace/api/ProcessTags.java
> Avoid potential race conditions on collecting process tags

- dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
- dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
- internal-api/src/main/java/datadog/trace/api/ProcessTags.java
For service renaming we're surfacing all the process tags to all the payloads.
This PR adds the process tags to the profile upload request on the field `process_tags` (as other products are already doing).
The value is a comma separated list of tags encoded as `key:value` . The value is already normalized according to our tag standards.
The collection of this tag is today behind a feature flag and not enabled by default …
> Collect process tags for profiling upload requests

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/JsonSnapshotSerializer.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/SnapshotSinkTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java
Adds process tag collection to dynamic instrumentation payload. It will be put in the intake request in the `process_tags` field in the same location than  the service name field.
The `process_tag` field will contain the process tags encoded as a comma separated list. Each entry is encoded using the `key:value` format. The values are tag normalized according our standards.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issue …
> Add process tags to dynamic instrumentation intake payload

- .github/workflows/check-ci-pipelines.yml
> Fix Check Pull Request CI Status job

- dd-java-agent/instrumentation/kotlin-coroutines/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/DatadogThreadContextElement.java
- dd-java-agent/instrumentation/zio/zio-2.0/src/main/java/datadog/trace/instrumentation/zio/v2_0/FiberContext.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
- dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ScopeContext.java
- dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ScopeState.java
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ScopeStateAware.java
and use it for Kotlin coroutines and Zio fibers
Lets us remove the earlier `ScopeState` abstraction in favour of the new Context API.
We're now close to the point we can have switchable scope manager implementations 🎉 
Use `solves` instead, and assign the …
> Implement Context.swap() on top of scope stacks

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/ddwaf/WAFModule.java
- internal-api/src/main/java/datadog/trace/api/telemetry/WafMetricCollector.java
- internal-api/src/test/groovy/datadog/trace/api/telemetry/WafMetricCollectorTest.groovy
This PR adds support for a new telemetry metric: `appsec.waf.input_truncated`. This is a count metric that tracks the number of times a WAF input was truncated, which may happen multiple times per request. The metric includes a truncation_reason tag, represented as a bitfield, with the following values:
-  1: string too long
-  2: list or map too large
-  4: object too deep
[RFC](https://docs.google.com/document/d/1D4hkC0jwwUyeo0hEQgyKP54kM1LZU98GL8MaP60tQrA/edit?tab=t.0)
For every call to WAF, if truncation occurred during serialization, we should emit the metric. This will increment the count for each run where truncation was detected, and each metric will include the bitfield indicating the types of truncation that occurred.
This metric should also be triggered when ObjectInstrospector …
> Add appsec.waf.input_truncated metric

- dd-java-agent/instrumentation/aws-lambda-handler/src/main/java/datadog/trace/instrumentation/aws/v1/lambda/LambdaHandlerInstrumentation.java
- dd-java-agent/instrumentation/aws-lambda-handler/src/test/groovy/LambdaHandlerInstrumentationTest.groovy
Every Lambda invocation has a unique request_id:
```
START RequestId: 5c6da654-d88b-4de6-b382-4ebc8a854daa
// Application logs here
END RequestId: 5c6da654-d88b-4de6-b382-4ebc8a854daa
```
In the Lambda Extension, we can use this `request_id` to enrich the Lambda span generated by the extension with the metadata from the tags: https://github.com/DataDog/datadog-lambda-extension/blob/3b10c17426572d79e98cf5a8a1d02a778c239ee7/bottlecap/src/lifecycle/invocation/processor.rs#L931-L939
Without the request ID, the Lambda Extension doesn't know which span belongs to which Lambda invocation, so we can't enrich the span properly.
To make sure tracer tags actually work in Lambda. This is required to support several features in Lambda, such as:
- Exception Replay
- Pass the `_dd.rule_psr` metrics so …
> Pass Lambda Request ID to Extension

- .github/workflows/update-docker-build-image.yaml
Fixes the automation the updates the java build image.
With recent changes to `.gitlab-ci.yml` the old script was no longer correct
- …
> Fix java build image update automation

- .circleci/config.continue.yml.j2
The build_inst job (`./gradlew clean :instrumentationTest ...`) memory usage is close to 16GiB, this is very likely cause to builds failing a daemon disappearing (`org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)`) 
https://circleci.com/docs/configuration-reference/#resourceclass
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-w …
> Bump build-inst resource class on circle ci

- dd-java-agent/instrumentation/kotlin-coroutines/src/main/java/datadog/trace/instrumentation/kotlin/coroutines/LazyCoroutineInstrumentation.java
This covers coroutines that don't extend `LazyDeferredCoroutine` or that override `onStart` but don't call the overridden method. Eager coroutines are already covered by the base constructor advice that captures the context when the coroutine starts already activated.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing …
> Widen lazy coroutine matcher to cover all definitions of onStart

- dd-java-agent/instrumentation/kotlin-coroutines/src/test/groovy/KotlinCoroutineInstrumentationTest.groovy
- dd-java-agent/instrumentation/kotlin-coroutines/src/test/kotlin/KotlinCoroutineTests.kt
- gradle/java_no_deps.gradle
JVM memory settings for the kotlin compiler daemon are now passed to the correct property.
Also, use parallel gc and explicitly opt in for coroutine api to avoid unnecessary opt-in warnings.
Follow-up to #8833 
Help fix CircleCI …
> fix: kotlin compiler daemon memory settings

- dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/NettyChannelPipelineInstrumentation.java
- dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/websocket/WebSocketServerInboundTracingHandler.java
- dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/websocket/WebSocketServerOutboundTracingHandler.java
- dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/websocket/WebSocketServerTracingHandler.java
- dd-java-agent/instrumentation/spring-webflux-5/src/bootTest/groovy/SpringWebfluxTest.groovy
- dd-java-agent/instrumentation/spring-webflux-5/src/bootTest/groovy/dd/trace/instrumentation/springwebflux/server/SpringWebFluxTestApplication.groovy
- dd-java-agent/instrumentation/spring-webflux-5/src/bootTest/groovy/dd/trace/instrumentation/springwebflux/server/WsHandler.java
- dd-java-agent/instrumentation/spring-webflux-6/src/bootTest/groovy/SpringWebfluxTest.groovy
- dd-java-agent/instrumentation/spring-webflux-6/src/bootTest/groovy/dd/trace/instrumentation/springwebflux/server/SpringWebFluxTestApplication.groovy
- dd-java-agent/instrumentation/spring-webflux-6/src/bootTest/groovy/dd/trace/instrumentation/springwebflux/server/WsHandler.java
Extend the in-place netty pipeline to trace websocket messages when reactor-netty is used. Spring webflux is composing the pipeline by adding separately frame decoder/encoder hence our instrumentation was not applied correctly.
This applies only to netty 4.1+ (since reactor-netty at worst uses a 4.1+ version). I also did a small refactoring of what was in place 
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a …
> Trace websocket for spring webflux reactive handlers

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/CapturedContextInstrumentor.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
To avoid premature class loading and potential LinkageError we are not collecting the static inherited fields of a class
- Update the …
> Remove static inherited fields collection

- .gitlab-ci.yml
- dd-java-agent/instrumentation/exception-profiling/src/test/java/datadog/trace/bootstrap/instrumentation/jfr/exceptions/ExceptionHistogramTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ProcessBuilderHelper.java
- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/SmokeTestUtils.java
- utils/test-utils/src/main/java/datadog/trace/test/util/ForkedTestUtils.java
* Bump memory for tests
* Increase memory for forked tests
* Fix `ExceptionHistogramTest` on J9
I was regularly seeing OOMs on forked tests when running on all JDKs (the nightly). The `512mb` limit is lower than the limit for regular tests. Some of these OOMs were nonobvious because the job would fail much later
This PR aligns forks to use `1024mb` across all the ways tests could be forked.
Additionally, I fixed the `ExceptionHistogramTest`, which only failed during the nightly.
- Don't …
> Various Gitlab tweaks and test fixes

- dd-java-agent/instrumentation/vertx-mysql-client-3.9/build.gradle
- dd-java-agent/instrumentation/vertx-pg-client-4.0/build.gradle
- dd-java-agent/instrumentation/vertx-pg-client-4.4.2/build.gradle
- dd-java-agent/instrumentation/vertx-redis-client-3.9/build.gradle
- dd-java-agent/instrumentation/vertx-sql-client-3.9/build.gradle
- dd-java-agent/instrumentation/vertx-web-3.9/build.gradle
- dd-java-agent/instrumentation/vertx-web-4.0/build.gradle
Make the same adjustments as the following [PR](https://github.com/DataDog/dd-trace-java/pull/8828).
- Update the …
> Adjust muzzle limit for vertx instrumentations

- components/cli/build.gradle.kts
- components/context/build.gradle.kts
- components/yaml/build.gradle.kts
Remove jmh gradle plugin when the project actually has no benchmarks
- Update the …
> chore: remove jmh from projects that don't have any benchmarks

- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/JsonToExpressionConverter.java
- dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_one_liner_value_expr_01.txt
- dd-java-agent/agent-debugger/debugger-el/src/test/resources/test_value_expr_01.json
Add isDefined as top level predicate for log template values
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master/ …
> Add support for isDefined in log template

- .gitlab-ci.yml
- .gitlab/gitlab-utils.sh
Adds a link to Datadog test results
This makes it easier to pivot to test failures/results as Gitlab has a subpar test experience
- Update …
> Show link to datadog CI app in test results

- dd-java-agent/instrumentation/classloading/src/main/java/datadog/trace/instrumentation/classloading/ClassloadingInstrumentation.java
This avoids potential class-loading delegation issues when using other products in dd-java-agent
- Update the …
> Ensure ClassloadingInstrumentation is always applied even with `DD_TRACE_ENABLED=false`

- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnit5Instrumentation.java
- dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnitPlatformUtils.java
- Updates JUnit 5 instrumentation to reflect changes introduced in version 5.13-RC1 to `org.junit.platform.engine.ExecutionRequest`, adding two new fields to the class, at least one of them required for the execution of tests. The instrumentation now chooses the available method to create objects of the class through reflection.
Unblocks https://github.com/DataDog/dd-trace-java/pull/8842
Tested locally by upgrading the gradle dependencies on `junit-5.3` and `junit-5.8` instrumentations and running both `test` and `latestDepTest`. 
Passing results for `junit-5.3`:
Passing results for `junit-5.8`:
- Assign the `type:` and (`comp:` or `inst:`) labels …
> Add support for JUnit 5.13-RC1

- telemetry/src/main/java/datadog/telemetry/TelemetryRequestBody.java
- telemetry/src/test/groovy/datadog/telemetry/TelemetryRequestBodySpecification.groovy
Surface process tags in telemetry request as a comma separated string under `/application/process_tags` …
> Surface process tags on telemetry payloads

- .github/workflows/check-ci-pipelines.yml
- dd-java-agent/instrumentation/spark/spark_2.13/build.gradle
- Updates the muzzle directive por `spark_2.13` to use Java 17 from `4.0.0` onwards
Version `4.0.0` was released a couple of days ago: https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.13/4.0.0/ …
> Update muzzle directive for spark-2.13

- .gitlab-ci.yml
Update our docker image to v25.05 from https://github.com/DataDog/dd-trace-java-docker-build
With our transition from CircleCI to Gitlab, we want to replace the `cimg` base image with the `ubuntu:24.04` image. This update includes this change.
Use `solves` …
> Update docker image to v25.05

- dd-smoke-tests/iast-util/iast-util-11/build.gradle
- dd-smoke-tests/iast-util/iast-util-17/build.gradle
- dd-smoke-tests/java9-modules/build.gradle
- dd-smoke-tests/springboot-java-11/build.gradle
- dd-smoke-tests/springboot-java-17/build.gradle
- gradle/java_no_deps.gradle
Modify `setJavaVersion` to support JavaCompile, GroovyCompile and ScalaCompile. The later two were already supported, but in a non-stanard way. They did set `options.forkOptions.javaHome` to the desired version, while they kept `javaLauncher` untouched. While this worked in practice, it makes the result confusing when debugging, as `javaLauncher` will correspond to a JDK other than the effective one.
Part of a series of changes to use JDK 17 to run gradle.
- Don't use `close`, `fix` or …
> Improve setJavaVersion to set standard javaLauncher for Groovy and Scala

- build.gradle
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/datadog.gradle-debug.gradle.kts
Add gradle plugin to log metadata of configured projects when `-PddGradleDebug` is set.
This will generate `build/datadog.gradle-debug.log` with content as follows:
```
[...]
{"task":":dd-smoke-tests:springboot-java-17:compileGroovy", "jdk":"8", "java_home":"17"}
{"task":":dd-smoke-tests:springboot-java-17:compileJava", "jdk":"17"}
{"task":":dd-smoke-tests:springboot-java-17:compileMain_java17Groovy", "jdk":"8", "java_home":"17"}
{"task":":dd-smoke-tests:springboot-java-17:compileMain_java17Java", "jdk":"17"}
{"task":":dd-smoke-tests:springboot-java-17:compileTestFixturesGroovy", "jdk":"8", "java_home":"17"}
{"task":":dd-smoke-tests:springboot-java-17:compileTestFixturesJava", "jdk":"17"}
{"task":":dd-smoke-tests:springboot-java-17:compileTestGroovy", "jdk":"8", "java_home":"17"} …
```
> Add gradle debug plugin

- .gitlab-ci.yml
- dd-java-agent/instrumentation/scala/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
> Upgrade to gradle v8.5

- dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/EndHandlerWrapper.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/EndHandlerWrapper.java
prevent vertx instrumentation from overriding http route if it has already been set by an other instrumentation AND it was going to set the route to `/`, in which case we know we're not going to do better than whatever is already there.
TODO: add a test
customer report
adding a unit test looks... not easy
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-iss …
> don't override route with / in vertx instrumentation

- internal-api/src/main/java/datadog/trace/bootstrap/config/provider/stableconfig/Selector.java
- internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/StableConfigParserTest.groovy
Modifies stableconfig yaml parsing to account for Selectors without a `matches` entry. 
Stableconfig yaml parsing was modified since the v1.49.0 release in this [PR](https://github.com/DataDog/dd-trace-java/pull/8790). With the latest dev version, I encountered null ptr exception while testing the following **valid** file:
```
apm_configuration_rules:
- selectors:
- origin: process_arguments
key: "-Darg1"
operator: exists
configuration:
SOME_KEY: "value"
```
See: https://github.com/DataDog/system-tests/actions/runs/15278035597/job/42969611110?pr=4333
```
[dd.trace 2025-05-27 14:34:32:780 +0000] [main] WARN datadog.trace.bootstrap.config.provider.StableConfigSource - Encountered the following exception when attempting to read stable configuration file at path: …
```
> Stable Config: make Selector.matches field optional

- dd-java-agent/build.gradle
Fixed build logic for dd-java-agent to correctly handle classes compiled with Java 6.
Gradle's caching logic did not correctly handle the previous implementation.
To test, just execute 2 times without changing any in sources:
```
./gradlew clean assemble
java -javaagent:dd-java-agent/build/libs/dd-java-agent-1.50.0-SNAPSHOT.jar -version
```
Previous implementation worked for the first run and failed with `Exception in thread "main" java.lang.ClassNotFoundException: datadog.trace.bootstrap.AgentPreCheck` on second run.
Gradle's caching logic did not copy `AgentPreCheck` class from cache.
- Assign the `type:` and (`comp:` or `inst:`) labels in …
> Fixed build logic for dd-java-agent to correctly handle classes compiled with Java 6.

- .gitlab-ci.yml
Instead of running all tests on all jdks as part of every master pipeline, with this PR, those tests only run on nightly.
The nondefault jdks have tests that are always failing. This has prevented `master` from having a green build in weeks.
Use `solves` …
> Run tests on all jdks as part of nightly instead of every master pipeline

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/CapturedContext.java
- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/el/ValueReferenceResolver.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/FilterCollectionExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/HasAllExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/HasAnyExpression.java
We were allocating some unnecessary objects for each item in the collection we attempt to filter with any, all and filter expression. introduced withExtension/removeExtension method to reduce those allocations …
> Optimized allocations for collection filter functions

- dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/proxy_ignored_class_name.trie
Ignores jaxrs client interface stubs from being instrumented (also because we should trace jaxrs server interfaces and not the client ones).
Same for CDI proxies that should not be traced. …
> Ignore quarkus jaxrs stubs and cdi wrapper proxies

- .gitlab-ci.yml
SSI smoke tests are extremely flaky and should only run as part of the nightly build, for now. This was missed as part of #8900 
- Update …
> SSI smoke tests should only run as part of nightly

- dd-java-agent/agent-bootstrap/build.gradle
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/net/HostNameResolver.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/java/net/HostNameResolverForkedTest.groovy
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/java/net/HostNameResolverTest.groovy
It may happen to have different hostnames pointing to the same IP. In this case, our hostname cache will hit the first resolved hostname giving a bad result.
In the case we have an already resolved hostname, this PR will avoid using the cache by using introspection to gather the already known hostname on the internal holder.
Note: as an additional mechanisms,  if this is not enough, we can also compare the host provided by `http.url` with the one extracted from the inet address and force a resolution if not matching. This is not implemented here …
> Use resolved address for peer.hostname when available without hitting the cache

- .gitlab-ci.yml
Reverts DataDog/dd-trace-java#8914
We cannot proceed to a release without validating the smoke tests.
Related to #8925
> Revert "SSI smoke tests should only run as part of nightly"

- .circleci/collect_results.sh
Add initial `\` to test source file paths in order to match changes made to the CODEOWNERS file in #8830 
After updating the CODEOWNERS file in #8830, our reported test case source file paths no longer matched. This resulted in a loss of codeowner data (see [the past week's reports](https://app.datadoghq.com/ci/test/runs?query=test_level%3Atest%20%40test.service%3Add-trace-java&agg_m=count&agg_m_source=base&agg_t=count&fromUser=false&index=citest&start=1748552349906&end=1749157149906&paused=false) vs [a month ago's reports](https://app.datadoghq.com/ci/test/runs?query=test_level%3Atest%20%40test.service%3Add-trace-java&agg_m=count&agg_m_source=base&agg_t=count&fromUser=true&index=citest&start=1745812800000&end=1746503999999&paused=true)).
We can check this change by looking at the test …
> Update test source file reporting to match codeowners file

- .github/workflows/update-docker-build-image.yaml
- .gitlab-ci.yml
You should be able to run CI with latest docker build image when setting an empty version of the docker build image.
This will help with the current CI effort.
A follow up commit will come to set an empty prefix as default value during the CI effort.
It takes into account this PR too: #8942 
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-key …
> Allow CI to use unpinned version of docker build image

- .gitlab-ci.yml
Remove ubuntu17 from test variants
This variant was used by profiling to test against with a JVM without debug symbols.
It is now tested of the profiling product side.
See https://github.com/DataDog/dd-trace-java-docker-build/pull/103
Use `solves` instead, …
> Remove ubuntu17 from test variants

- dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
- dd-smoke-tests/gradle/src/test/resources/test-succeed-gradle-plugin-test/coverages.ftl
- dd-smoke-tests/gradle/src/test/resources/test-succeed-gradle-plugin-test/events.ftl
- dd-smoke-tests/gradle/src/test/resources/test-succeed-gradle-plugin-test/src/test/java/datadog/smoke/HelloPluginFunctionalTest.java
Fixes flaky Gradle Daemon instrumentation test: `test-succeed-gradle-plugin-test`.
This test case is different from the others because the _instrumented project_ builds a Gradle plugin and uses Gradle Test Kit to test it.
There was an [issue](https://github.com/DataDog/dd-trace-java/pull/8465) where our Gradle Launcher instrumentation interfered with Gradle Test Kit, and this test case was added to ensure the issue does not reappear.
The test inside the instrumented project runs a Gradle build. So we have three nested Gradle builds:
- the "outermost" build of the tracer (run with whatever Gradle version is used to build the tracer at the moment)
- the build that is run by smoke test (run with Gradle Test Kit and uses Gradle version that is specified in the smoke test case)
- the …
> Fix flaky Gradle Daemon instrumentation smoke test

- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java
> Disable Debugger tracer smoke tests for j9

- benchmark/load/petclinic/benchmark.json
- benchmark/startup/petclinic/benchmark.json
This scenario corresponds to a combination of AppSec enabled explicitly and IAST disabled explicitly. It is an uncommon scenario used back in the day to validate some features, but of little use today. And slightly confusing, because having appsec and appsec_no_iast misleads into thinking that "appsec" has IAST enabled. Let's make some room for useful scenarios.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a …
> Remove appsec_no_iast benchmark scenarios

- dd-java-agent/src/test/groovy/datadog/trace/agent/InstrumenterUnloadTest.groovy
- dd-java-agent/src/test/java/jvmbootstraptest/UnloadingChecker.java
Introduces a canary class which we use to detect when we've done enough to trigger class unloading. If we weren't able to trigger any class unloading then we effectively skip this test, because the results are inconclusive.
Hopefully less flakiness
Use …
> Improve stability of InstrumenterUnloadTest

- benchmark/Dockerfile
Spring Petclinic in benchmark for reproducibility.
Pinned to latest commit in main brach. Spring Petclinci repo has no tags.
> Pin Spring Petclinic in benchmarks

- utils/test-utils/src/main/java/datadog/trace/test/util/GCUtils.java
Just in case the reference passed in has already been cleared via a partial GC, this way we at least try to force a full GC at least once.
There are other improvements we could make, but I don't think we need to invest too much into this test method as it's only used in a very few places.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keywor …
> Always call System.gc() and System.runFinalization() at least once in `awaitGC`

- dd-smoke-tests/gradle/build.gradle
- dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
- dd-smoke-tests/gradle/src/test/resources/test-corrupted-config-legacy-instrumentation/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-corrupted-config-new-instrumentation/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-failed-flaky-retries/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-failed-legacy-instrumentation/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-failed-new-instrumentation/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-skip-legacy-instrumentation/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-skip-new-instrumentation/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-succeed-gradle-plugin-test/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-succeed-junit-4-class-ordering/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-succeed-junit-5/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-succeed-legacy-instrumentation/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-succeed-multi-forks-legacy-instrumentation/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-succeed-multi-forks-new-instrumentation/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-succeed-multi-module-legacy-instrumentation/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-succeed-multi-module-new-instrumentation/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-succeed-new-instrumentation/build.gradleTest
- dd-smoke-tests/gradle/src/test/resources/test-succeed-old-gradle/build.gradleTest
Updates Gradle Daemon smoke tests to use Maven repository proxy when available.
The proxy URL is retrieved from a Gradle project property, then propagated to the tests as an environment variable, and then propagated to the "nested" Gradle builds started by the tests, again as an environment variable.
The reason it is not propagated as a project property is that project property is a part of Gradle command, and Gradle command is reported as a span tag by the Test Optimization, which makes it a part of the test fixtures.
The proxy not always being present would make the test command (and the test fixtures) unstable.
Gradle Daemon smoke tests need to use caching Maven proxy, otherwise the nested Gradle builds downloading their artifacts (e.g. JUnit) can be rate-limited by Maven Central …
> Update Gradle Daemon smoke tests to use Maven repository proxy when available

- dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
- dd-smoke-tests/gradle/src/test/resources/test-succeed-junit-4-class-ordering/build.gradleTest
- dd-smoke-tests/maven/build.gradle
- dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
- dd-smoke-tests/maven/src/test/resources/test_failed_maven_run_flaky_retries/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_builtin_coverage/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_child_service_propagation/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_impacted_tests/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_junit4_class_ordering/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_junit4_class_ordering_parallel/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_junit_platform_runner/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_multiple_forks/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_surefire_3_0_0/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_surefire_3_5_0/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_test_management/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_with_arg_line_property/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_with_cucumber/settings.xml
- dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_with_jacoco_and_argline/settings.xml
Updates Maven smoke tests to use caching Maven repository proxy in CI.
The tests need to download Maven artifacts for the tested projects.
When downloading directly from Maven Central, the tests fail because of download query rate limits.
Use `solves` …
> Update Maven smoke tests to use repository proxy

- .gitlab-ci.yml
Avoids
```
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 429 for URL: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.3/apache-maven-3.6.3-bin.zip
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1917)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:90)
at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:76)
at org.apache.maven.wrapper.Installer.createDist(Installer.java:72)
at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor. …
```
> additional-maven-proxy-fixes

- dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/test/groovy/datadog/trace/api/ConfigForkedTest.groovy
Add one configuration alias (`DD_RUNTIME_METRICS_RUNTIME_ID_ENABLED`) to drive runtime_id generation.
- Update the …
> Add DD_RUNTIME_METRICS_RUNTIME_ID_ENABLED alias for runtime id generation

- dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
`System.nanoTime` is a better fit for time measurement.
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master/.gith …
> Replace `System.currentTimeMillis` by `nanoTime`

- dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
Increases the maven smoke test timeout for CI. Numerous maven smoke tests are failing in CI, du to process timeout. Locally the tests are passing, let's increase a tad the timeouts.
```
java.util.concurrent.TimeoutException: Instrumented process failed to exit
at datadog.smoketest.MavenSmokeTest.runProcess(MavenSmokeTest.groovy:336)
at datadog.smoketest.MavenSmokeTest.retryUntilSuccessfulOrNoAttemptsLeft(MavenSmokeTest.groovy:312)
at datadog.smoketest.MavenSmokeTest.givenMavenDependenciesAreLoaded(MavenSmokeTest.groovy:294)
at datadog.smoketest.MavenSmokeTest.test #projectName, v#mavenVersion(MavenSmokeTest.groovy:65)
```
- Assign the `type:` and …
> Fix Maven smoke test timeout in CI

- dd-trace-core/src/main/java/datadog/trace/common/writer/ListWriter.java
Refactored await logic from quite complex manipulations with list of latches with simple `wait/notifyAll` approach.
Green CI.
PekkoHttpServerInstrumentationAsyncTest failed from time to time with `TimeoutException`:
```
PekkoHttpServerInstrumentationAsyncTest > propagate trace id when we ping pekko-http concurrently FAILED
org.spockframework.runtime.ConditionFailedWithExceptionError at PekkoHttpServerInstrumentationTest.groovy:74
Caused by: java.util.concurrent.TimeoutException at ListWriter.java:86
```
- Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIB …
> Simplified ListWriter await logic.

- dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
Bumps the command timeout to 120s. Follow up to #8993.
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master/.githu …
> Increase again Maven smoke tests timeout

- .gitlab-ci.yml
This folder may not exist when there's no gitlab cache.
Followup to #8975 
- Update the …
> Earlier `.gradle` creation to fix `populate_dep_cache`

- dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
- gradle/configure_tests.gradle
Retry tests in CI, I wonder however if these should be tracked ? Maybe Test Optim has that?
Note:
When a test fails it is captured by [_Test Optimization_](https://app.datadoghq.com/ci/test/runs?query=test_level%3Atest%20%40git.branch%3Atest-retry-in-ci%20%40test.status%3A%28fail%20OR%20pass%29%20%40test.suite%3APekkoHttpServerInstrumentationAsyncHttp2Test%20%40ci.job.name%3A%22test_inst%3A%20%5B17%2C%205%2F6%5D%22&agg_m=count&agg_m_source=base&agg_t=count&citest_explorer_sort=timestamp%2Cdesc&cols=%40test.status%2Ctimestamp%2C%40test.suite%3A327%2C%40test.name%3A386%2C%40duration%3A146%2C%40test.service%3A129%2C%40git.branch%2C%40ci.job.name&currentTab=overview&eventStack=&fromUser=true&index=citest&start=1749643041273&end=1750247841273&paused=true).
```
@git.branch:test-retry-in-ci …
```
> Enable test retry in CI

- .github/workflows/run-system-tests.yaml
This PR adds a name to clary the expected PR status check.
The current check is `check` which is pretty generic.
I hope adding a job name will allow to use it for PR status check (otherwise, I will update the job name too in a following PR).
Follow up of #9007
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing an …
> Add system test job name to help with PR checks 

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ClassLoaderMatchers.java
Skips `com.ibm.xml.xlxp2.jaxb.codegen.AbstractGeneratedStubFactory$RootStubClassLoader`.
Before client had to do manually add the following arg: `-Ddd.trace.classloaders.exclude=com.ibm.xml.xlxp2.jaxb.codegen.AbstractGeneratedStubFactory$RootStubClassLoader`
In a OSGI environment JAXB code generation creates a lot `com.ibm.xml.xlxp2.jaxb.codegen.AbstractGeneratedStubFactory$RootStubClassLoader` this classloader is used to define generated classes that must be actually defined in the correct OSGI bundle.
Given the tracer needs to instrument classloading and also perform osgi bundle lookup this interaction create a lot of load in the tracer when these generated classes are defined.
Given this classloader is used for the generated classes, it is safe to exclude skip it.
- Format the title …
> Skip JAXB generated classes classloader

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
- dd-java-agent/instrumentation/play-2.3/src/main/java/datadog/trace/instrumentation/play23/PlayHttpServerDecorator.java
- dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play24/PlayHttpServerDecorator.java
- dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/PlayHttpServerDecorator.java
- dd-smoke-tests/play-2.4/app/controllers/AppSecController.scala
- dd-smoke-tests/play-2.4/build.gradle
- dd-smoke-tests/play-2.4/conf/routes
- dd-smoke-tests/play-2.4/src/test/groovy/datadog/smoketest/AppSecPlayNettySmokeTest.groovy
- dd-smoke-tests/play-2.5/app/controllers/AppSecController.scala
- dd-smoke-tests/play-2.5/build.gradle
- dd-smoke-tests/play-2.5/conf/routes
- dd-smoke-tests/play-2.5/src/test/groovy/datadog/smoketest/AppSecPlayNettySmokeTest.groovy
- dd-smoke-tests/play-2.6/app/controllers/AppSecController.scala
- dd-smoke-tests/play-2.6/build.gradle
- dd-smoke-tests/play-2.6/conf/routes
- dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/AppSecPlaySmokeTest.groovy
- dd-smoke-tests/play-2.7/app/controllers/AppSecController.scala
- dd-smoke-tests/play-2.7/build.gradle
- dd-smoke-tests/play-2.7/conf/routes
- dd-smoke-tests/play-2.7/src/test/groovy/datadog/smoketest/AppSecPlaySmokeTest.groovy
- dd-smoke-tests/play-2.8/app/controllers/AppSecController.scala
- dd-smoke-tests/play-2.8/build.gradle
- dd-smoke-tests/play-2.8/conf/routes
- dd-smoke-tests/play-2.8/src/test/groovy/datadog/smoketest/AppSecPlaySmokeTest.groovy
- internal-api/src/main/java/datadog/trace/api/gateway/Events.java
- internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java
- internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java
Store the `http.route` tag value inside the appsec request context in Play framework instrumentation
AppSec API protection requires the `http.route` span tag to be set on the local root span so it can be used for its sampling decision. Since Play does not use the local root span for the `http.route` we have to store it in the appsec request context before the sampling decision is made. …
> Store the http.route tag value inside the appsec request context in Play

- .gitlab-ci.yml
This PR updates the GitLab CI pipeline to cancel running PR pipeline on new commit push.
Avoid waiting resources and start building / testing the new commit from your PRs.
This was the default behavior of the previous CircleCI jobs.
Use `solves` instead, …
> Cancel GitLab running pipeline on new PR push

- dd-java-agent/appsec/build.gradle
Updates libddwaf-java version to have the new regex key for obfuscation
- Update the …
> Default obfuscation regexp update

- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
https://datadoghq.atlassian.net/browse/SDBM-1829
> Set trace_injected in try block

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
When Di is enabled we are automatically starting the Code  Origin for Spans product
- Update the …
> Enable Code Origin with Dynamic instrumentation

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/ObjectIntrospection.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/data/ObjectIntrospectionSpecification.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
- dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextInstrumentation.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextJsonResponseAdvice.java
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/server/VertxHttpServerForkedTest.groovy
- dd-java-agent/instrumentation/vertx-web-4.0/src/test/java/server/VertxTestServer.java
- dd-java-agent/instrumentation/vertx-web-5.0/src/test/groovy/server/VertxHttpServerForkedTest.groovy
- dd-java-agent/instrumentation/vertx-web-5.0/src/test/java/server/VertxTestServer.java
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
- dd-smoke-tests/vertx-4.2/application/src/main/java/datadog/vertx_4_2/MainVerticle.java
- dd-smoke-tests/vertx-4.2/src/test/groovy/AppSecVertxSmokeTest.groovy
- internal-api/src/main/java/datadog/trace/api/gateway/Events.java
- internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java
- internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java
Adds response body extraction for Vert.x JSON endpoints to enable automatic API schema discovery and protection by the Web Application Firewall (WAF).  Support is for Vert.x >= 4.x (leverages new [JSON](https://github.com/vert-x3/vertx-web/blob/4.0.0/vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java#L678) response API introduced in v4.x)
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request- …
> Extract Vert.x json body response schemas

- dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play25/appsec/ResultsStatusInstrumentation.java
- dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play25/appsec/StatusHeaderInstrumentation.java
- dd-java-agent/instrumentation/play-2.4/src/main/java_play25/datadog/trace/instrumentation/play25/appsec/BodyParserHelpers.java
- dd-java-agent/instrumentation/play-2.4/src/main/java_play25/datadog/trace/instrumentation/play25/appsec/ResultsStatusApplyAdvice.java
- dd-java-agent/instrumentation/play-2.4/src/main/java_play25/datadog/trace/instrumentation/play25/appsec/StatusHeaderSendJsonAdvice.java
- dd-java-agent/instrumentation/play-2.4/src/test/groovy/datadog/trace/instrumentation/play25/server/PlayRouters.groovy
- dd-java-agent/instrumentation/play-2.4/src/test/groovy/datadog/trace/instrumentation/play25/server/PlayServerTest.groovy
- dd-java-agent/instrumentation/play-2.4/src/test/scala/datadog/trace/instrumentation/play25/PlayController.scala
- dd-java-agent/instrumentation/play-2.4/src/test/scala/datadog/trace/instrumentation/play25/PlayRoutersScala.scala
- dd-java-agent/instrumentation/play-2.6/src/baseTest/groovy/datadog/trace/instrumentation/play26/server/PlayRouters.groovy
- dd-java-agent/instrumentation/play-2.6/src/baseTest/groovy/datadog/trace/instrumentation/play26/server/PlayServerTest.groovy
- dd-java-agent/instrumentation/play-2.6/src/latestDepTest/groovy/datadog/trace/instrumentation/play26/server/latestdep/PlayRouters.groovy
- dd-java-agent/instrumentation/play-2.6/src/latestDepTest/scala/datadog/trace/instrumentation/play26/server/latestdep/PlayController.scala
- dd-java-agent/instrumentation/play-2.6/src/latestDepTest/scala/datadog/trace/instrumentation/play26/server/latestdep/PlayRoutersScala.scala
- dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/appsec/BodyParserHelpers.java
- dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/appsec/ResultsStatusInstrumentation.java
- dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/appsec/StatusHeaderInstrumentation.java
- dd-smoke-tests/play-2.5/app/controllers/AppSecController.scala
- dd-smoke-tests/play-2.5/conf/routes
- dd-smoke-tests/play-2.5/src/test/groovy/datadog/smoketest/AppSecPlayNettySmokeTest.groovy
- dd-smoke-tests/play-2.6/app/controllers/AppSecController.scala
- dd-smoke-tests/play-2.6/conf/routes
- dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/AppSecPlaySmokeTest.groovy
- dd-smoke-tests/play-2.7/app/controllers/AppSecController.scala
- dd-smoke-tests/play-2.7/conf/routes
- dd-smoke-tests/play-2.7/src/test/groovy/datadog/smoketest/AppSecPlaySmokeTest.groovy
- dd-smoke-tests/play-2.8/app/controllers/AppSecController.scala
- dd-smoke-tests/play-2.8/conf/routes
- dd-smoke-tests/play-2.8/src/test/groovy/datadog/smoketest/AppSecPlaySmokeTest.groovy
Adds response body extraction for Play JSON endpoints to enable automatic API schema discovery and protection by the Web Application Firewall (WAF). Support is for Play >= 2.4+ (leverages new [JSON](https://github.com/playframework/playframework/blob/2.4.0/framework/src/play/src/main/java/play/mvc/Results.java#L79) response API)
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking- …
> Extract Play json body response schemas

- dd-smoke-tests/maven/build.gradle
- Increases the Maven smoke test timeout to 20 minutes, due to the tests taking longer after increasing their timeout limit.
After the Maven smoke tests were updated to use the Maven proxy for dependencies, they started to time out in CI. Their timeout value was doubled to keep them from failing because of this (#8997). With this change, although the smoke tests don't timeout individually anymore, the `:smokeTest` target does sometimes go over the timeout limit for Gradle tests configured in `configure_tests.gradle` ([example failure](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-java/-/jobs/999738668) and [failed jobs on master](https://app.datadoghq.com/ci/pipeline-executions?query=ci_level%3Ajob%20%40git.repository.id%3A%22gitlab.ddbuild.io%2FDataDog%2Fapm-reliability%2Fdd- …
> Increase MavenSmokeTest timeout

- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/baggage/BaggagePropagator.java
- dd-trace-core/src/test/groovy/datadog/trace/core/baggage/BaggagePropagatorTest.groovy
Previously, baggage was not being dropped when `TracePropagationBehaviorExtract=IGNORE`. This PR fixes that bug and addresses failures in [APMAPI-1443](https://datadoghq.atlassian.net/browse/APMAPI-1443).
Also fixes bug in call to base `BaggagePropagator` constructor.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing …
> Fixing bug with dropping baggage when `TracePropagationBehaviorExtract=IGNORE`

- dd-java-agent/instrumentation/akka-http/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/DatadogServerRequestResponseFlowWrapper.java
- dd-java-agent/instrumentation/pekko-http-1.0/src/main/java/datadog/trace/instrumentation/pekkohttp/DatadogServerRequestResponseFlowWrapper.java
Backport #9019 to release/v1.50.x
> 🍒 9019 - Fix NPE in akka-http and pekko-http integrations

- .gitlab-ci.yml
- dd-trace-core/src/test/groovy/datadog/trace/TracerConnectionReliabilityTest.groovy
Update ddapm-test-agent from v1.11.0 to v1.24.1
Update to latest version to stay current with improvements and fixes.
- Update the …
> Update ddapm-test-agent from v1.11.0 to v1.24.1

- .gitlab-ci.yml
- .gitlab/find-gh-base-ref.sh
- If `aws ssm` fails, print an error.
- If `.gitlab/find-gh-base-ref.sh` does not determine any base branch, do not set `-PgitBaseRef=` at all.
- Cache the result.
- Some pipelines fail with an empty git base ref, most likely because of an incorrectly handled rate limit.
Doing this for quick CI recovery, but ideally:
- Could use `gh` CLI with `gh pr view -R DataDog/dd-trace-java $CI_COMMIT_REF_NAME --json baseRefName --jq .baseRefName` as suggested by @PerfectSlayer.
- Don't use …
> Graceful error handling in .gitlab/find-gh-base-ref.sh

- .gitlab-ci.yml
Disable https://github.com/DataDog/dd-trace-java/pull/9039
We hit GitHub API rate limits too easily. This needs either being called just once per pipeline in an early step, or use pure git heuristics. …
> Disable skipping tests based on git changes

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/Advices.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteTransformer.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/BaseCallSiteTest.groovy
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteInstrumentationTest.groovy
- dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/csi/SuperInCtorExample.java
- dd-java-agent/instrumentation/java-io/src/test/groovy/datadog/trace/instrumentation/java/io/InputStreamReaderCallSiteTest.groovy
- dd-java-agent/instrumentation/java-io/src/test/java/foo/bar/TestCustomInputStreamReader.java
This PR fixes an issue with call sites that incorrectly handle `super` calls inside constructors. Specifically, it ensures the return value of constructor-targeted call sites is properly managed when used in a `super` context.
Constructor-targeted call sites are designed to return the newly constructed instance to maintain correct stack behavior. However, when such call sites are used within `super` calls, the returned value must be discarded (i.e., popped off the stack). Failing to do so can lead to incorrect behavior or runtime issues—such as the one recently reported by a customer
```
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 57
Exception Details:
Location:
x/y/z/ResourceStreamReader.<init>(Lx/y/z/Resource;Ljava/io/InputStream;Ljava/nio/charset/Char …
```
> Fix verify error when ctor params are used after a call site

- build.gradle
No need to get the full distribution, it's heavier as it includes Gradle sources, but IntelliJ is capable to grab the sources now.
- Update …
> Drop useless Gradle wrapper config

- dd-java-agent/instrumentation/opensearch/rest/src/test/groovy/OpensearchRestClientTest.groovy
- dd-java-agent/instrumentation/opensearch/transport/src/test/groovy/OpensearchNodeClientTest.groovy
- dd-java-agent/instrumentation/opensearch/transport/src/test/groovy/OpensearchTransportClientTest.groovy
Logs shows that the trace is discarded since spans are not received in the correct order. Removing strict trace writing as a workaround
- …
> Don't be strict on opensearch tests

- .gitlab-ci.yml
- dd-java-agent/instrumentation/akka-http/akka-http-10.6/build.gradle
Use a secure URL for akka dependencies.
Akka recently requires this: https://doc.akka.io/libraries/akka-core/current/project/migration-guide-2.8.x-2.9.x.html …
> Use token to access Akka secure repository

- components/environment/src/test/java/datadog/environment/CommandLineTest.java
- components/environment/src/test/java/datadog/environment/JavaVirtualMachineTest.java
This PR fixes environment unit tests related to IBM / J9
I missed those tests as they aren't running on PR check
- Update the …
> Fix environment unit tests related to IBM / J9

- dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
- Sets `-Dmaven.artifact.threads=10` for Maven smoke tests to boost the dependency resolution speed
- Even with increased timeouts some smoke tests were still timing out while resolving their dependencies. …
> Use parallel artifact resolution in Maven Smoke tests

- dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
- dd-trace-core/src/test/groovy/datadog/trace/common/metrics/MetricsReliabilityTest.groovy
In case of downgrade the client stats thread is interrupted. However the `DDAgentFeatureDiscovery` maintains a state based on the info endpoint that is then driving the fact that we inform the agent we are calculating or not the client stats (header `Datadog-Client-Stats-Computed`)
If the client stats thread exit, and we discover again that the agent supports the client stats, we will end up in a situation where nobody will calculate the stats (since the thread is exited).
This PR avoid shutting down that thread. In any case there is always a guard (features.clientStatsSupported) in any metric writer method. 
It also adds reliability test for this scenario
- Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#title-f …
> Make client stats reliable in case of downgrade

- communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
If multiple calls are done to `SharedCommunicationObjects.featureDiscovery(..)` it might happen that multiple `DDAgentFeatureDiscovery` instances are created.
This discovery instance must be unique in order to ensure that, tracer-wise, we keep the same vision of the state of the agent.
This PR just add a synchronized block around that creation
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an …
> Avoid race conditions and multiple agent discovery feature states

- dd-java-agent/instrumentation/java-concurrent/java-concurrent-21/src/previewTest/groovy/StructuredConcurrencyTest.groovy
Fixes the structured concurrency test that is failing quite often (expecially on 24.x)
I observed locally that the wait can time out. hence the parent span is reported before the child are finished and spans are dropped because of the strict write policy. Hence the test times out
We just give more time to the join (better always give a larger timeout even if it won't be reached...)
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-w …
> Give more time to structured concurrency tests

- dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
* Avoid using ReenterantLock, use `synchronized` instead
* Removed unnecessary long -> string conversion
This reduces DSM overhead by about 1/3.
> DSM optimizations for high throughput scenarios

- dd-java-agent/agent-llmobs/build.gradle
Specify the version for `junit-platform-launcher` in the `:dd-java-agent:agent-llmobs` project
Address the failure on `master`:
```
FAILURE: Build failed with an exception.
Execution failed for task ':dd-java-agent:agent-llmobs:resolveAndLockAll'.
> Could not resolve all files for configuration ':dd-java-agent:agent-llmobs:testRuntimeOnlyDependenciesMetadata'.
> Could not find org.junit.platform:junit-platform-launcher:.
Required by:
project :dd-java-agent:agent-llmobs
```
- Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#lab …
> Specify junit version for llmobs agent

- dd-smoke-tests/jboss-modules/src/test/groovy/datadog/smoketest/JBossModulesV1SmokeTest.groovy
- dd-smoke-tests/jboss-modules/src/test/groovy/datadog/smoketest/JBossModulesV2SmokeTest.groovy
- dd-smoke-tests/quarkus/build.gradle
- dd-smoke-tests/quarkus/src/test/groovy/datadog/smoketest/QuarkusJBossLoggingSmokeTest.groovy
- dd-smoke-tests/quarkus/src/test/groovy/datadog/smoketest/QuarkusSlf4jSmokeTest.groovy
Ignore jboss and quarkus smoke tests for JDK 24+
They do not support JDK 24+
- Update the …
> Ignore jboss and quarkus smoke tests for JDK 24+

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
Apache http client tests are quite flaky. Especially those couple with parent and errors.
This PR just try to remove the flakiness by sorting the spans by start in order to make the assertions reliable …
> Fix flaky out of order comparison for http client test

- dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/appsec/StatusHeaderInstrumentation.java
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
Fix the AppSec instrumentation issue with `play.mvc.StatusHeader` that was causing failures in `PlayAsyncServerTest`. The `OnMethodExit` hook was incorrectly placed, leading to the callback not always being called. …
> Fix AppSec play.mvc.StatusHeader instrumentation for play 2.6

- dd-java-agent/instrumentation/karate/src/test/groovy/KarateTest.groovy
Update ignoreif reason for karate tests on JDK 24+
Clarify why we are skipping these tests for JDK 24+
- Update the …
> Update ignoreif reason for karate tests on jdk 24

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
Apache http client tests are quite flaky. Especially those couple with parent and errors.
This PR just try to remove the flakiness by sorting the spans by start in order to make the assertions reliable.
Green CI. …
> Fix flaky out-of-order comparison for http client test.

- dd-smoke-tests/play-2.4/src/test/groovy/datadog/smoketest/IastPlayNettySmokeTest.groovy
It’s being marked as flaky while a fix is being investigated.
The test has been flaky since it was merged on July 10th.
- Update the …
> Mark Play 2.4 IastPlayNettySmokeTest as flaky

- dd-java-agent/appsec/src/main/java/com/datadog/appsec/ddwaf/WAFModule.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/ObjectIntrospection.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/data/ObjectIntrospectionSpecification.groovy
Unifies truncation limits to prevent using different thresholds, it also aligns them with what is specified in the [API Security RFC](https://docs.google.com/document/d/1VK_A63izyRR1vHRxOevCELSZ2yvTy93WxhJfBS0ep3k/edit?tab=t.0#heading=h.8d3o7vtyu1y1).
Use …
> Unify truncation limits between ObjectIntrospection and WAFModule

- communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
Backport #9135 to release/v1.51.x
> 🍒 9135 - Avoid race conditions and multiple agent discovery feature states

- gradle/jacoco.gradle
Upgrade Jacoco to 0.8.13. Cleanup Gradle script.
Gradle scripts maintenance.
- Update the …
> Upgrade Jacoco to 0.8.13. Cleanup Gradle script.

- dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
- dd-trace-core/src/test/groovy/datadog/trace/common/metrics/MetricsReliabilityTest.groovy
- internal-api/src/main/java/datadog/trace/api/Config.java
Use `DD_TRACE_STATS_COMPUTATION_ENABLED` as preferred configuration key for client stat computation (works across tracers)
Add the old one (`DD_TRACE_TRACER_METRICS_ENABLED`) as an alias for backward compatibility …
> Change primary client stats configuration key

- components/environment/src/main/java/datadog/environment/EnvironmentVariables.java
- components/environment/src/main/java/datadog/environment/SystemProperties.java
- components/environment/src/test/java/datadog/environment/EnvironmentVariablesTest.java
- components/environment/src/test/java/datadog/environment/SystemPropertiesTest.java
This PR improves null values handling of environment component.
Following feedback on #9170 from @sarahchen6 
Environment component related stacked PRs:
* https://github.com/DataDog/dd-trace-java/pull/9071
* https://github.com/DataDog/dd-trace-java/pull/9072
* https://github.com/DataDog/dd-trace-java/pull/9091
* https://github.com/DataDog/dd-trace-java/pull/9093
* https://github.com/DataDog/dd-trace-java/pull/9100
* https://github.com/DataDog/dd-trace-java/pull/9188
* https://github.com/DataDog/dd-trace-java/pull/9190
* https://github.com/DataDog/dd-trace-java/pull/9191 …
> Improve environment component null values handling

- .github/workflows/analyze-changes.yaml
Attempt to fix OOM for GitHub actions.
GitHub actions maintenance.
After recent upgrade to Gradle 8.14.3 and overall project size actions started to fail with OOM.
> Attempt to fix OOM for GitHub actions.

- dd-java-agent/src/test/groovy/datadog/trace/agent/InitializationTelemetryTest.groovy
Introduced more granular test exclusions for SecurityManager behavior under Java 24+.
Exclude only required tests and keep the rest.
> Granular test exclusions for SecurityManager behavior under Java 24+.

- .github/chainguard/self.gitlab.release.sts.yaml
This PR adds the trust policy for `dd-octo-sts` usage.
We want to use `dd-octo-sts` for github PATs instead of our current fine-grained tokens. Since trust policies must be read from the `master` branch to be valid, the policy needs to be merged in before we can test the token workflow.
The github release token is needed when we tag a release, so the policy is tailored for git tags. The policy is tested to work with [this dd-octo-sts-sandbox example run](https://gitlab.ddbuild.io/DataDog/dd-octo-sts-sandbox/-/jobs/1033180338). …
> Add dd-octo-sts trust policy

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/SourceFileTrackingTransformer.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SourceFileTrackingTransformerTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/InProductEnablementIntegrationTest.java
Initialize ClassNameFiltering in background thread to avoid startup latency
- Update the …
> Add third-party filtering in SourceFile tracking

- dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/KafkaClientTestBase.groovy
- dd-java-agent/instrumentation/kafka-connect-0.11/src/test/groovy/ConnectWorkerInstrumentationTest.groovy
Fix for a flaky test
Elements in the collection were not sorted properly. Now this test should work as expected. 
The issue was introduced in [this](https://github.com/DataDog/dd-trace-java/pull/9151) PR.
> Fixed flaky test

- dd-java-agent/appsec/build.gradle
- gradle/repositories.gradle
Migrate the libddwaf artifact from an S3 bucket to Maven Central by:                                                                                                                                                                                                                                          
- Removing the custom Ivy repository configuration that pointed to `https://sqreen-ci-java.s3.amazonaws.com/jars/`                                                                                                                                                                                            
- Adding `io.sqreen` group to the existing Maven Central Sonatype snapshots repository …
> Migrate libddwaf to maven central

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
- dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/SmapEntryFactory.java
What title says
Avoid errors when trying to initialize the support on JDKs without JFR
- Update the …
> Avoid initializing SMAP events on JDKs with no JFR

- .github/workflows/add-milestone-to-pull-requests.yaml
This PR adds retry to the workflow in charge of assigning milestone to PR to fix Resource not accessible by integration error
This sometimes fails due to GH API request error like https://github.com/DataDog/dd-trace-java/actions/runs/16317277156/job/46086120541#step:2:84 …
> Add workflow retry to fix Resource not accessible by integration error

- .gitlab/macrobenchmarks.yml
Skip check-slo-breaches during POPULATE_CACHE pipelines
During POPULATE_CACHE pipelines, none of the jobs that the slo check depends on are run and the pipeline is broken. This PR aligns the slo check with the benchmark runs
Use `solves` instead, and assign …
> Skip check-slo-breaches during POPULATE_CACHE pipelines

- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymbolExtractionTransformerTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/ClassFileLinesTest.java
Since JDK 24, lambdas are renumbered from the local scope and not
from the whole classfile
- Update the …
> Fix debugger test for stable JVM

- dd-java-agent/instrumentation/spark-executor/build.gradle
- dd-java-agent/instrumentation/spark/spark_2.13/build.gradle
Basically reverts https://github.com/DataDog/dd-trace-java/pull/8895
This closes https://datadoghq.atlassian.net/browse/DJM-841 
The previous PR had limited spark deps to 3.5.6 bcz some artifacts for scala 2.13 and 3.5.6 were not available.
> Unlimit latestdep for spark 3.x

- .gitlab-ci.yml
Cleans up the `dd-octo-sts` workflow that retrieves a github token for publishing during releases. This also adds a pre-release check to ensure that the trust policy and token work before proceeding.
The workflow was proven successful during the `1.51.2` patch release, so no need for a back up job anymore.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-is …
> Clean dd-octo-sts workflow and add pre-release check

- .gitlab-ci.yml
Properly runs tests using the default `test_matrix`.
There's an interaction where `parallel` isn't being used for test splitting but just for separate jvms. he script sees CI_NODE_TOTAL=12 and CI_NODE_INDEX=1, because is a test_matrix (8, 11, 17, etc). It then uses our modulo test splitting to assign tests to nodes and sees that no tests are assigned to the current node. By explicitly setting `1/1`, no tests are improperly skipped.
For `test_debugging` and `test_profiling`, many tests were skipped that should not have been. …
> Fix CI_SPLIT for base case test matrix

- .gitlab/macrobenchmarks.yml
I missed a job in #9243 . This add a rule not to run `notify-slo-breaches` during `POPULATE_CACHE`
During POPULATE_CACHE pipelines, none of the jobs that the slo check depends on are run and the pipeline is broken. This PR aligns the slo check with the benchmark runs
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when referencing …
> Fix notify-slo-breaches interaction with POPULATE_CACHE

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitDataApi.java
- dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sensitive/HeaderRegexpTokenizer.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
- dd-trace-core/src/main/java/datadog/trace/core/TracingConfigPoller.java
- dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
- internal-api/src/main/java/datadog/trace/api/Config.java
Code cleanup. Found by Trivy.
Find and fix poor code.
See dashboard: [link](http://app.datadoghq.com/ci/code-analysis/github.com%2Fdatadog%2Fdd-trace-java/master/c938629f30f07ec3b3687394562aa62007ebf66c/code-quality?query=%40git.repository.id%3Agithub.com%2Fdatadog%2Fdd-trace-java%20%40git.branch%3Amaster%20%40git.commit.sha%3Ac938629f30f07ec3b3687394562aa62007ebf66c%20-%40static_analysis.result.category%3Asecurity%20%40static_analysis.result.item_type%3Astatic_analysis_violation&fromUser=false&index=cicodescan&start=1753023746022&end=1753482824234&paused=false)
> Minor code cleanup.

- tooling/cleanup-gradle-module.sh
This script cleans up the old Gradle modules.
When relocating Gradle modules, working copy ends up with empty folders, only containing `build` output. This script will find and remove them. 
There is also a `--backup` option that will remove them from repo to move them near the script if you would like to check what will be clean up. It can be restored by moving the backup at the root of the working copy. …
> Add script to clean up old Gradle modules

- .gitlab-ci.yml
- dd-trace-core/src/traceAgentTest/groovy/AbstractTraceAgentTest.groovy
Use an datadog agent image that's mirrored internally
docker rate limits (rarely). I also changed the image used to run locally so that they match
Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to …
> Use mirrored agent image in CI

- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/AwsCodePipelineInfo.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/AzurePipelinesInfo.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/BuildkiteInfo.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/CIInfo.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/CITagsProvider.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/CircleCIInfo.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/GitLabInfo.java
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/GithubActionsInfo.java
- dd-java-agent/agent-ci-visibility/src/test/resources/ci/awscodepipeline.json
- dd-java-agent/agent-ci-visibility/src/test/resources/ci/azurepipelines.json
- dd-java-agent/agent-ci-visibility/src/test/resources/ci/buildkite.json
- dd-java-agent/agent-ci-visibility/src/test/resources/ci/circleci.json
- dd-java-agent/agent-ci-visibility/src/test/resources/ci/github.json
- dd-java-agent/agent-ci-visibility/src/test/resources/ci/gitlab.json
- internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java
- Adds the `ci.job.id` tag for the following CI providers:
- AWS
- Azure
- Buildkite
- CircleCI
- Gitlab
- GHA
- Previously the values were sent only in `_dd.ci.env_vars` …
> Add `ci.job.id` tag

- dd-java-agent/ddprof-lib/build.gradle
- gradle/libs.versions.toml
Bump ddprof to 1.29.0
Improve performance and stability
* Split debug by @r1viollet in https://github.com/DataDog/java-profiler/pull/233
* Add the micro-benchmark for thread filtering by @jbachorik in https://github.com/DataDog/java-profiler/pull/237
* Flaky test - j9 OSR by @r1viollet in https://github.com/DataDog/java-profiler/pull/239
* Fix flaky allocation test by @r1viollet in https://github.com/DataDog/java-profiler/pull/241
* Remove debugging code from ActiveBitmap by @zhengyu123 in https://github.com/DataDog/java-profiler/pull/242
* Potential memory leak and race with the JVMTI wallclock sampler by @zhengyu123 in https://github.com/DataDog/java-profiler/pull/234
* Stresstest fix - Add limits to the graph mutation stress test by @r1viollet in …
> Bump ddprof to 1.29.0

- dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/util/WellKnownClasses.java
- dd-java-agent/agent-debugger/debugger-el/src/main/java/com/datadog/debugger/el/expressions/SubStringExpression.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/EndsWithExpressionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/MatchesExpressionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/StartsWithExpressionTest.java
- dd-java-agent/agent-debugger/debugger-el/src/test/java/com/datadog/debugger/el/expressions/SubStringExpressionTest.java
To be able to use substring and string predicates on URI variables
- Update the …
> Add URI in string primitives

- .github/chainguard/self.update-docker-build-image.create-pr.sts.yaml
- .github/chainguard/self.update-gradle-dependencies.create-pr.sts.yaml
- .github/workflows/update-docker-build-image.yaml
- .github/workflows/update-gradle-dependencies.yaml
> Avoid using GITHUB_TOKEN for PR creation

- dd-trace-core/build.gradle
- dd-trace-core/src/test/groovy/datadog/trace/common/metrics/FootprintForkedTest.groovy
Removes the 'features' mock that made the test a bit unpredictable. 
This is a cherry pick from 
* https://github.com/DataDog/dd-trace-java/pull/9178/commits/b7aa90dbf3f2a27271943665842590742b0005d0
* https://github.com/DataDog/dd-trace-java/pull/9178
The memory footprint of `aggregator` was including the `features` Spock mock which included its stubs and its recorded invocations. This single mock could amount to ~22 MiB. …
> Fix `FootprintForkedTest` that was also measuring Spock mock

- .github/chainguard/self.update-jmxfetch-submodule.create-pr.sts.yaml
This PR supercedes #9302. Only policies on `master` are valid, so merging this PR separately will allow testing #9302.
- Update the …
> Add policy for GHA workflow

- .github/workflows/update-docker-build-image.yaml
The extra `''` is only needed for macOS environments.
Fix failing GHA workflow.
See `Update the Docker build image in GitLab CI config` step in this failing GHA workflow: https://github.com/DataDog/dd-trace-java/actions/runs/16662709587/job/47163137648
VS. the step in a previously successful one: https://github.com/DataDog/dd-trace-java/actions/runs/15004105028/job/42158228806
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-i …
> Fix docker build update workflow

- dd-java-agent/instrumentation/liberty-20/build.gradle
- dd-java-agent/instrumentation/liberty-23/build.gradle
- dd-java-agent/instrumentation/servlet/request-3/build.gradle
- dd-java-agent/instrumentation/servlet/request-5/build.gradle
- dd-smoke-tests/springboot-tomcat/build.gradle
- dd-smoke-tests/wildfly/build.gradle
- gradle/publish.gradle
Fix misplaced API usage, confusing API usage, and misuse of testFixtures API.
- Update the …
> Fix small gradle mistakes

- .github/workflows/update-docker-build-image.yaml
- .github/workflows/update-jmxfetch-submodule.yaml
Following @AlexeyKuznetsov-DD 's recommendation in #9305, this PR updates the `update-docker-build-image` and `update-jmxfetch-submodule` workflows such that they only create PRs if there are changes to commit.
The `update-docker-build-image` created a PR with no changes: https://github.com/DataDog/dd-trace-java/pull/9305
The `update-jmxfetch-submodule` failed to create a PR because there were no commits made: https://github.com/DataDog/dd-trace-java/actions/runs/16737254881/job/47378527957
- Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/CONTRIBUTING.md#labe …
> Update GHA workflows to avoid creating PRs if no changes to commit

- buildSrc/src/main/groovy/MuzzlePlugin.groovy
Use lazy configuration API, in particular
* Register configurations (and configure them on-demand) instead of eagerly realize them.
* Register tasks and configure them lazily instead of eagerly creating them.
Also, simplified a bit the task registration with regular for-loop, instead of Groovy's `.inject`.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-is …
> Configure lazily `MuzzlePlugin`

- gradle/java_no_deps.gradle
Allow `testJvm` property to have paths.
Locally this allows to easily use a different JVM from the IDE, without having to set-up an environment variable before. In practice this allows to use either `-PtestJvm=JAVAMY_JVM_HOME` or `-PtestJvm=/path/to-/my-jvm` …
> Allow `testJvm` property to receive paths

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/buffer/InjectingPipeOutputStream.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/buffer/InjectingPipeWriter.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/buffer/InjectingPipeOutputStreamTest.groovy
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/buffer/InjectingPipeWriterTest.groovy
Make `InjectingPipeOutStream` and `InjectingPipeWriter` more deterministic when an `IOException` is thrown by the downstream.
In this particular case, the wrappers stop trying to inject to the downstream and just delegate the writes since the underlying  buffer is now in an inconsistent state (we do not know in advance which portion of the buffer has been eventually written and what will be the retry policy of the user). This implies that eventually data can be corrupted or lost (but this would also have happened without this wrapper)
However, if the error arose when draining, the draining is resumed from the position that broke.
- Assign the …
> Make rum injector stream/writer more resilient to errors

- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
It fixes handling of the tracer agent IPv6 addresses in profiling
The construction of URL to upload the profiling data is mishandling the IPv6 addresses …
> Properly handle trace agent IPv6 URL in profiling

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/buffer/InjectingPipeOutputStream.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/buffer/InjectingPipeWriter.java
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/buffer/InjectingPipeOutputStreamTest.groovy
- dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/buffer/InjectingPipeWriterTest.groovy
Backport #9184 to release/v1.52.x
> 🍒 9184 - Make rum injector stream/writer more resilient to errors

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/buffer/InjectingPipeOutputStream.java
- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/buffer/InjectingPipeWriter.java
- dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/RumAsyncContextInstrumentation.java
- dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/RumHttpServletRequestWrapper.java
- dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/RumHttpServletResponseWrapper.java
- dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
- dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Instrumentation.java
- dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/WrappedServletOutputStream.java
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/JakartaServletInstrumentation.java
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/RumAsyncContextInstrumentation.java
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/RumHttpServletRequestWrapper.java
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/RumHttpServletResponseWrapper.java
- dd-java-agent/instrumentation/servlet/request-5/src/main/java/datadog/trace/instrumentation/servlet5/WrappedServletOutputStream.java
- dd-java-agent/instrumentation/servlet/request-5/src/testFixtures/groovy/datadog/trace/instrumentation/servlet5/AsyncRumServlet.groovy
- dd-java-agent/instrumentation/tomcat-5.5/src/latestDepTest/groovy/TomcatServletTest.groovy
- dd-smoke-tests/rum/src/main/groovy/datadog/smoketest/rum/AbstractRumServerSmokeTest.groovy
- dd-smoke-tests/rum/tomcat-10/src/main/java/com/example/HtmlAsyncServlet.java
- dd-smoke-tests/rum/tomcat-10/src/main/java/com/example/Main.java
- dd-smoke-tests/rum/tomcat-11/src/main/java/com/example/HtmlAsyncServlet.java
- dd-smoke-tests/rum/tomcat-11/src/main/java/com/example/Main.java
- dd-smoke-tests/rum/tomcat-9/src/main/java/com/example/HtmlAsyncServlet.java
- dd-smoke-tests/rum/tomcat-9/src/main/java/com/example/Main.java
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
- internal-api/src/main/java/datadog/trace/api/rum/RumInjector.java
- internal-api/src/test/groovy/datadog/trace/api/rum/RumInjectorTest.groovy
Support RUM injection also for async servlet 3+
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master/.github/CODEO …
> Support async servlet for RUM injection

- dd-trace-core/src/jmh/java/datadog/trace/common/metrics/ConflatingMetricsAggregatorBenchmark.java
- dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
- dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricKey.java
- dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
- dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AggregateMetricTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy
- dd-trace-core/src/traceAgentTest/groovy/MetricsIntegrationTest.groovy
Improves CSS serializer performances by caching peer tags creations (avoids also utf8 conversions)
The cache has been choosen big enough to contains high cardinality tag values like (peer.hostname). -> tested with org2
A JMH test shows that in case of cache hit (obviously) performs better (see below).
The peer tags cache is unbounded since those tags have low cardinality (they are fixed and returned by the agent).
```
Benchmark  (NO CACHE)                                                        Mode  Cnt      Score     Error   Units
ConflatingMetricsAggregatorBenchmark.benchmark                     avgt    3      9.223 ±   0.622   us/op
ConflatingMetricsAggregatorBenchmark.benchmark:gc.alloc.rate       avgt    3   2177.221 ± 147.254  MB/sec …
```
> Improves CSS peer tag aggregation

- communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
Fixes NPE like
```
java.lang.NullPointerException: Cannot invoke "datadog.communication.ddagent.DDAgentFeaturesDiscovery.discoverIfOutdated()" because "this.ddAgentFeaturesDiscovery" is null
```
linked to the fact that, if the object is created in parallel, the non-first call will return null.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-k …
> Avoid NPE on featureDiscovery creation

- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Backport #9334 to release/v1.52.x
> 🍒 9334 - Properly handle trace agent IPv6 URL in profiling

- .github/chainguard/self.add-release-to-cloudfoundry.sts.yaml
Add trust policy for `add-release-to-cloudfoundry` workflow
Update `add-release-to-cloudfoundry` to use a `dd-octo-sts` token to sign and push the commit made in the workflow.
Checked this policy with the [#sdlc-security](https://dd.enterprise.slack.com/archives/C027P1CK07N) team for the `add-release-to-cloudfoundry` workflow. TY!
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linkin …
> Add policy for add-release-to-cloudfoundry

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
1. Removed references to`ApacheHttpAsyncClient5Test` - it is an abstract class now.
2. Marked couple of tests as flaky for `ApacheHttpAsyncClient5NamingV0Test`.
Green CI.
Task ':dd-java-agent:instrumentation:apache-httpclient:apache-httpclient-5.0:test' is failing on CI quite often.
> Updated flaky tests.

- communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
- dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
- dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricsAggregatorFactory.java
- dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
- dd-trace-core/src/main/java/datadog/trace/core/monitor/HealthMetrics.java
- dd-trace-core/src/main/java/datadog/trace/core/monitor/TracerHealthMetrics.java
- dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/metrics/FootprintForkedTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/metrics/MetricsAggregatorFactoryTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/metrics/MetricsReliabilityTest.groovy
Adds the following statsD metrics for CSS:
* `stats.traces_in` -> the number of traces included in the stats calculation
* `stats.spans_in` -> the number of spans included in the stats calculation (same as dd-trace-go)
* `stats.p0_dropped_traces` -> the number of traces that could be dropped if not sampled
* `stats.p0_dropped_spans` -> the number of spans that could be dropped if not sampled
* `stats.flushed_payloads` -> the number of total requests to the agent (`/v0.6/stats`) - same as dd-trace-go
* `stats.flushed_errors` -> the number of errors received when sending the stats  -same as dd-trace-go
* `stats.downgrades`-> the number of downgrades detected (downgrade is detected when the client stats was enabled but the agent suddenly answer with a 404 meaning that the endpoint is no more …
> Implement health metrics for client stats

- dd-trace-core/src/main/java/datadog/trace/core/monitor/TracerHealthMetrics.java
Ensure previous metrics in TracerHealthMetrics is correctly sized. Avoid warnings
- Update the …
> Fix health metrics report size

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
Test `PekkoHttpServerInstrumentationAsyncHttp2Test.test exception` marked as flaky.
Green CI.
Test failed more than 200 times during last month on GitLab CI.
> Test `PekkoHttpServerInstrumentationAsyncHttp2Test.test exception` marked as flaky.

- dd-java-agent/instrumentation/opentelemetry/opentelemetry-annotations-1.20/src/main/java/datadog/trace/instrumentation/opentelemetry/annotations/WithSpanDecorator.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-annotations-1.20/src/test/groovy/SpanAttributeAnnotationTest.groovy
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-annotations-1.20/src/test/java/annotatedsample/TracedMethods.java
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-annotations-1.26/src/test/groovy/AddingSpanAttributesAnnotationTest.groovy
- dd-java-agent/instrumentation/opentelemetry/opentelemetry-annotations-1.26/src/test/java/annotatedsample/AnnotatedMethods.java
Allow multiple span attributes to be set on the same span using the OpenTelemetry annotation `@SpanAttribute`.
```
@WithSpan
public static String sayHelloWithMultipleAttributes(
@SpanAttribute("custom-tag1") String param1, @SpanAttribute("custom-tag2") String param2) {
return "hello!";
}
```
**Result before this PR:**
A span with a tag `custom-tag1:param1`
**Result before this PR:**
A span with tags `custom-tag1:param1` and `custom-tag2:param2`
Customer's reaching out to our support team as only the first @SpanAttribute set was included in the span
Jira ticket: [APMS-16924]
[APMS-16924]: https://datadoghq.atlassian.net/browse/APMS-16924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix using SpanAttribute annotation on multiple parameters

- dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastOverheadControlSpringBootSmokeTest.groovy
Test `IastOverheadControlSpringBootSmokeTest.Test that all the vulnerabilities are detected` marked as flaky.
Green CI.
Discussed with @jandro996 to mark it flaky for now.
> Test `IastOverheadControlSpringBootSmokeTest.Test that all the vulnerabilities are detected` marked as flaky.

- dd-java-agent/instrumentation/aws-java/aws-java-dynamodb-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/dynamodb/DynamoDbInterceptor.java
- dd-java-agent/instrumentation/aws-java/aws-java-eventbridge-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/eventbridge/EventBridgeInterceptor.java
- dd-java-agent/instrumentation/aws-java/aws-java-s3-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/s3/S3Interceptor.java
- dd-java-agent/instrumentation/aws-java/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
- dd-java-agent/instrumentation/aws-java/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java
- dd-java-agent/instrumentation/aws-java/aws-java-sfn-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sfn/SfnInterceptor.java
- dd-java-agent/instrumentation/aws-java/aws-java-sns-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sns/SnsInterceptor.java
- dd-java-agent/instrumentation/aws-java/aws-java-sqs-2.0/src/main/java/datadog/trace/instrumentation/aws/v2/sqs/SqsInterceptor.java
This PR keeps migrating instrumentations to the Context API
Decoupling DSM from Tracing.
This PR will focus on instrumentation that tightly coupled DSM and Tracing to introduce Context tracking instead.
The introduced TODO is a marker for following work with the DSM team.
This is a follow up PR of:
* https://github.com/DataDog/dd-trace-java/pull/9358
* https://github.com/DataDog/dd-trace-java/pull/9378 …
> Migrate instrumentations to Context API

- dd-java-agent/instrumentation/java-concurrent/java-concurrent-21/build.gradle
- dd-java-agent/instrumentation/java-concurrent/java-concurrent-21/src/test/groovy/VirtualThreadTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
- gradle/slf4j-simple.gradle
Tests: implemented switch from `logback` to `slf4j-simple` when needed.
Green CI.
Use slf4j-simple as default; logback has a high chance of getting stuck in a deadlock on CI.
> Tests: implemented switch from `logback` to `slf4j-simple` when needed.

- dd-java-agent/instrumentation/spring-security-6/build.gradle
This PR restricts the maximum supported version of Spring Boot to the 3.x release line. Excluded versions: 4.0.0-M1 and later (currently available as milestones and snapshots)
Spring Boot 4.x has already published several milestone releases that introduce breaking changes. These incompatibilities currently cause our test suite to fail, and migrating requires further investigation to assess impact. …
> Limit latest deps of spring-boot to 3.x

- dd-trace-core/src/main/java/datadog/trace/core/monitor/TracerHealthMetrics.java
Fix naming on CSS health metrics and add base tags
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master/.github/CO …
> Align CSS health metrics

- dd-java-agent/agent-bootstrap/src/main/resources/META-INF/native-image/com.datadoghq/dd-java-agent/reflect-config.json
ConflatingMetricsAggregator is using some jctools classes using unsafe reflection that were not declared.
Example:
```
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: producerIndex
at datadog.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:111)
at datadog.jctools.queues.SpmcArrayQueueProducerIndexField.<clinit>(SpmcArrayQueue.java:48)
... 17 more
Caused by: java.lang.NoSuchFieldException: producerIndex
at java.base@22/java.lang.Class.checkField(DynamicHub.java:1051)
at java.base@22/java.lang.Class.getDeclaredField(DynamicHub.java:1182)
at datadog.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:107)
```
Tests are enforced on system tests
- Format the title [according the contribution guidelines](https://github.com/DataDog/dd-trace-java/blob/master/CONT …
> Add reflect config for CSS and graalvm

- dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilerSettingsSupport.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
- telemetry/src/main/java/datadog/telemetry/log/LogPeriodicAction.java
- telemetry/src/test/groovy/datadog/telemetry/log/LogPeriodicActionTest.groovy
Prevents passing exception messages and dynamically concatenated strings as an error message to the telemetry
Sensitive data leaks prevention
Use `solves` instead, and assign the PR [milestone](https://github.com/DataDog/dd-trace-java/milestones) to the …
> Error Logs Remediation

- dd-java-agent/instrumentation/lettuce-4/src/test/groovy/Lettuce4ClientTestBase.groovy
- dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ClientTestBase.groovy
Adds a **maximum 10-second timeout** for the Redis client shutdown.  
Previously, this test had a high chance of freezing on CI.
After multiple retries, I collected a thread dump from a hung test:
```
"Test worker" #1 [10060] prio=5 os_prio=0 cpu=7203.66ms elapsed=421.50s tid=0x00007fecf0031970 nid=10060 in Object.wait()  [0x00007fecf764c000]
java.lang.Thread.State: WAITING (on object monitor)
at java.lang.Object.wait0(java.base@21.0.7/Native Method)
- waiting on <no object reference available>
at java.lang.Object.wait(java.base@21.0.7/Object.java:366)
at java.lang.Object.wait(java.base@21.0.7/Object.java:339)
at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:254)
- locked <0x00000000d816e6f8> (a io.netty.util.concurrent.DefaultPromise)
at …
```
> Added guard for restClient shutdown freeze.

- internal-api/src/main/java/datadog/trace/api/TagMap.java
- internal-api/src/test/java/datadog/trace/api/TagMapEntryTest.java
- internal-api/src/test/java/datadog/trace/api/TagMapFuzzTest.java
- internal-api/src/test/java/datadog/trace/api/TagMapScenario.java
- internal-api/src/test/java/datadog/trace/api/TagMapTest.java
- internal-api/src/test/java/datadog/trace/api/TagMapType.java
Reduces the randomness in TagMap tests
Tests that were using a single randomly selected size -- now use TagMapScenario which is a mix of TagMapType and a pre-populated size
The pre-populating helps hit the 3 common branch paths inside OptimizedTagMap: null, TagMap.Entry, and BucketGroup
Eliminate sporadic coverage failures in CI
> Improving TagMap coverage

- dd-java-agent/instrumentation/graphql-java/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
same as https://github.com/DataDog/dd-trace-java/pull/9128 but for graphql v14.0
- Update the …
> apply the fix from #9128 to the other instance of the test

- dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
- dd-trace-core/src/main/java/datadog/trace/common/metrics/TriState.java
- dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy
Avoid magic values for IsTraceRoot
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master/.github/CODEOWNERS) file …
> Use constant instead of magic values for IsTraceRoot

- metadata/denied-arguments.tsv
- metadata/requirements.json
Added `ikeycmd` and `ikeyman` utilities from `IBM SDK, Java Technology Edition` to exclusion list.
Exclude `UtilityMain` class that is using for running some short-living commands from SSI.
There no MacOS `IBM SDK, Java Technology Edition` [distributives available](https://www.ibm.com/support/pages/java-sdk-downloads-version-80).
[LANGPLAT-771]
[LANGPLAT-771]: https://datadoghq.atlassian.net/browse/LANGPLAT-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added `ikeycmd` and `ikeyman` utilities from `IBM SDK, Java Technology Edition` to exclusion list.

- dd-java-agent/appsec/build.gradle
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/ddwaf/WAFModule.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/ObjectIntrospection.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
- dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplJsonAdapterTest.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/ddwaf/WAFModuleSpecification.groovy
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy
- dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/TraceTaggingSmokeTest.groovy
Adds trace tagging features in accordance with https://docs.google.com/document/d/1bqDtGgMJgsTW6I16iEcRn1lb9RRQjFRDGim8zRrbs0s/edit?tab=t.0 …
> Add new features for trace tagging rules

- dd-java-agent/agent-ci-visibility/build.gradle
- dd-java-agent/agent-debugger/build.gradle
- dd-java-agent/agent-llmobs/build.gradle
- gradle/java_deps.gradle
- gradle/libs.versions.toml
Adds `junit-platform-launcher` as a test runtime dependency to all modules
- Use the same `junit-platform-launcher` version in every project, and make sure it is compatible with our `junit-jupiter` version 
- Fix `resolveAndLockAll` failures in projects that depend `junit-platform-launcher` (`agent-ci-visibility`, `junit-4.10`)
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a …
> Add junit-platform-launcher as a test runtime dependency to all modules

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/Where.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/WhereTest.java
We avoid to instrument Bridge method but we don't want to log error for method not found. So introduce a skip status for method matching to differentiate if we skip instrumentation but still we have found the method …
> Fix error logged for Bridge methods

- dd-smoke-tests/appsec/spring-tomcat7/build.gradle
- dd-smoke-tests/appsec/springboot-graphql/build.gradle
- dd-smoke-tests/appsec/springboot-security/build.gradle
- dd-smoke-tests/appsec/springboot/build.gradle
- dd-smoke-tests/datastreams/kafkaschemaregistry/build.gradle
Replace the final instances of eager APIs in our `build.gradle` files with lazy APIs
Upgrade our build tools
- Update the …
> Convert eager APIs to lazy APIs

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/JsonSnapshotSerializer.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ProbeStatus.java
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SymbolSink.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/ProbeStatusSinkTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/SymbolSinkTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ExceptionDebuggerIntegrationTest.java
- dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java
help to discriminate type of content when processing by intake
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/maste …
> add type to requests sent to intake

- dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/CompressingRequestBody.java
- dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/CompressionType.java
- dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/CompressingRequestBodyTest.java
- dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
- dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
This provides the fix for the profiler smoke-tests when running on Oracle JDK 8
Oracle JDK 8 JFR is storing the recordings compressed by GZip - our library detects that and avoids re-compression.
But this will cause issues when we try to decompress the gzip stream using zstd in the smoke tests.
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a- …
> Correct the mixup in compression algorithms on Oracle JDK 8

- dd-java-agent/agent-ci-visibility/build.gradle
- dd-java-agent/instrumentation/aws-java/aws-java-sqs-1.0/build.gradle
- dd-java-agent/instrumentation/aws-java/aws-java-sqs-2.0/build.gradle
- dd-java-agent/instrumentation/kafka/kafka-clients-0.11/build.gradle
- dd-java-agent/instrumentation/vertx/vertx-rx-3.5/build.gradle
- dd-smoke-tests/gradle/build.gradle
- dd-smoke-tests/maven/build.gradle
- gradle/configure_tests.gradle
- gradle/dump_hanging_test.gradle
Unified timeout of 15 minutes. Improved logic of taking thread and heap dumps.
Make build configuration simpler.
Follow up for #9414.
> Unified timeout of 15 minutes. Improved logic of taking thread and heap dumps.

- .github/workflows/run-system-tests.yaml
Adds system-tests on pushes on master
* reflect system-tests health on [APM health SLI](https://app.datadoghq.com/dashboard/wfj-m48-tq7?fromUser=false&offset=0&refresh_mode=yearly&from_ts=1735686000119&to_ts=1758191644293&live=true)
* tackle more precisely when an issue is introduced in master
* schedules will handles (rare)  use case when there are no commit (integration tests with last released agent) …
> Add system-tests on pushes on master + schedules

- dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
Disable byte-buddy's Nexus mechanism by setting the system property defined in https://javadoc.io/doc/net.bytebuddy/byte-buddy-dep/latest/constant-values.html#net.bytebuddy.dynamic.Nexus.PROPERTY
We don't need byte-buddy's Nexus mechanism, and it triggers use of Unsafe.
The simple constructor for `AgentBuilder.Default` calls the more complex `AgentBuilder` constructor with `new InitializationStrategy.SelfInjection.Split()` as the default initialization strategy. We override this setting later on when we call `disableClassFormatChanges()`, but this doesn't stop the eager construction of  `InitializationStrategy.SelfInjection.Split`, even though it is not actually used.
The `Split` constructor creates a `NexusAccessor` which uses `Unsafe` via reflection to inject the Nexus mechanism (a way …
> Disable byte-buddy's Nexus mechanism

- dd-java-agent/instrumentation-testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
- dd-java-agent/instrumentation/pekko-http-1.0/src/baseTest/groovy/PekkoHttpServerInstrumentationTest.groovy
- dd-java-agent/instrumentation/pekko-http-1.0/src/baseTest/scala/PekkoHttpTestWebServer.scala
- revert #9493 
- close span in the exception handling code in the test server
honestly this is a bit beyond my comprehension, and AI helped me find this, but it seems there is a race condition in which handler gets to treat the exception, if it's the instrumentation handler things work fin, but if it's the test server handler, then the span is not finished. At least that's how I understand it.
Pekko's instrumentation was submitted by an external contributor 2 years ago.
- Don't use …
> Fixing pekko test: revert previous change and fix test server

- dd-java-agent/agent-ci-visibility/src/test/resources/ci/git/impacted/no_remote/git/config
Fixes a hanging test: `test get base branch sha: no remote clone`.
The test was failing with: `Timeout while waiting for git ls-remote -.-heads origin main`.
Green CI
After enabling debug logs for git, I discovered the issue came from ssh being used by default. Since ssh has no built-in timeout, the process could hang indefinitely.
For the record, there are two possible approaches:
1. Set an SSH timeout: `sshCommand = ssh -o ConnectTimeout=2`.
2. Use an HTTPS URL to bypass SSH entirely: `url = https://some-host/datadog/non_existing_repo.git`
This PR applies option (1), using a timeout.
> Fixed git command hangs in case if no remote exists.

- .gitlab/macrobenchmarks.yml
Changes performance SLO check notifications destination channel to #apm-java.
Other options were discussed [here](https://dd.slack.com/archives/C092V5HHT9S/p1758204655078249).
Currently, SLO notifications are being sent to [#apm-release-platform](https://dd.enterprise.slack.com/archives/C07AFGS1N81), which is leading to some [confusion](https://dd.slack.com/archives/C07AFGS1N81/p1758137069837959) since that channel gets notifications from the One Pipeline for all SDKs.
- Don't use …
> Change SLO check notifications channel

- .github/workflows/update-gradle-dependencies.yaml
Fix the pipeline Update Gradle Dependencies
In #7362, the simple `git add "**/gradle.lockfile"` has been replaced by a slightly more complex script that handles signed commit. Though some files or folders that are not `gradle.lockfile` files are included in the commit, causing some [errors](https://github.com/DataDog/dd-trace-java/actions/runs/17888755085/job/50866397699#step:8:66)
~Test run : https://github.com/DataDog/dd-trace-java/actions/runs/17917057938~ No test run, octo-sts allow it only on `master` 😢 
- Assign the `type:` and (`comp:` or `inst:`) labels in addition to [any usefull labels](https://github.com/DataDog/dd-trace-java/blob/master/C …
> Fix gradle update pipeline

- communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
- communication/src/test/groovy/datadog/communication/ddagent/DDAgentFeaturesDiscoveryTest.groovy
- communication/src/test/resources/agent-features/agent-info-with-telemetry-proxy.json
- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturingTestBase.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerAgentTest.java
- dd-java-agent/instrumentation-testing/src/main/groovy/datadog/trace/agent/test/InstrumentationSpecification.groovy
- internal-api/src/main/java/datadog/trace/api/Config.java
- internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
snapshots should always send to DEBUGGER track through v2/input or v1/diagnostics endpoints. v1/input is unredacted.
v1/diagnostics endpoint was introduced since DD agent 7.49 …
> Prevent using v1/input endpoint for snapshots

- gradle/dump_hanging_test.gradle
Reference to scheduled action should be inside task (not project) to avoid race condition.
Green CI.
This is a follow-up on #9414.
> Reference to scheduled action should be inside task to avoid race condition.

- settings.gradle.kts
Remove extra `:dd-smoke-tests:jersey` module in settings file
Address warning: `
Configuring project ':dd-smoke-tests:jersey' without an existing directory is deprecated. The configured projectDirectory '.../dd-trace-java/dd-smoke-tests/jersey' does not exist, can't be written to or is not a directory. This behavior has been deprecated.`
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue …
> Remove extra jersey smoke test module

- .github/pull_request_template.md
- .github/workflows/README.md
- .github/workflows/check-pull-request-labels.yaml
This PR ensures that pull requests don't introduce unexpected labels. 
This should reduce the manual housekeeping effort.
- Update the …
> Ensure no unexpected labels are introduced

- .github/CODEOWNERS
Team name changed from API to Capabilities a while ago - this change is required to reflect this in Github teams
- Update the …
> Update CODEOWNERS (rename apm-sdk-api to apm-sdk-capabilities)

- dd-java-agent/instrumentation/wildfly-9.0/build.gradle
Task declaration was misplaced in the dependencies block. And the `forkedTest` and `latestDepForkedTest` tasks had an awkward setup depending on the resolved version. Moreover, the extract tasks where using the `buildDir` as destination which overlapped with every other tasks input in this project. 
Now the tasks are properly wired and extracted in proper subfolders.  
- Don't use `close`, `fix` or any [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/lin …
> wildfly-9.0 configuration was eager and misplaced

- dd-java-agent/instrumentation/liberty-20/build.gradle
- dd-java-agent/instrumentation/liberty-23/build.gradle
Open liberty 2.0/2.3 project configurations weren't lazy and had a few other issues around
* Made a proper openliberty extract task
* Properly wired task's output as dependencies
* Clean up incorrectly configured tasks
* Access task and configurations lazily …
> Improves openliberty project laziness

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/HelperInjectionTest.groovy
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPluginTest.groovy
- internal-api/internal-api-9/src/main/java/datadog/trace/util/JDK9ModuleAccess.java
* Replace use of ByteBuddy's ClassInjector when redefining modules to add reads
* Test helper consistency in MuzzleVersionScanPlugin without requiring HelperInjector
This helps decouple internals and provides the same feedback with simpler code
* Remove duplicate test: we already test unloading of an injected class-loader in this class
Makes it easier to switch out the underlying approach. …
> Simplify `HelperInjector` to make it easier to switch out the underlying approach

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SymbolSink.java
Current SymDB serialization use intermediate full large buffer for every intermediate operation:
- serializing to string
- converting to UTF-8 byte array
- compressing with gzip every operation imply potentially large buffer (several 10MBs). On constraint heaps it can lead to OOME. we now stream this process using outputstream, buffered sink for serialization so we have less large buffers in flight. …
> Stream the SymDB serialization and compression

- dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/AnnotationSubstitutionProcessorInstrumentation.java
- dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/Target_com_datadog_profiling_agent_ProcessContext.java
This PR fixes the native build failure related to the process context sharing introduced in profiling: https://github.com/DataDog/dd-trace-java/pull/9472
Related error:
```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.datadog.profiling.agent.ProfilingAgent.run(ProfilingAgent.java:94)
Parsing context:
3,303 types,   154 fields, and 3,224 methods registered for reflection
at datadog.trace.agent.tooling.ProfilerInstaller.installProfiler(ProfilerInstaller.java:10)
at datadog.trace.agent.tooling.nativeimage.TracerActivation.activate(TracerActivation.java:20)
1 native library: -framework CoreServices
at org.graalvm.nativeimage.VMRuntime.initialize(VMRuntime.java:65)
-------------------------------------------------------------------- …
```
> Disable process context sharing when using native image

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
Ignore java.lang.Object methods (identified by method name plus method descriptor) when creating muzzle references.
This helps when compiling with Java 18+ because javac will now use INVOKEINTERFACE with the interface name to call java.lang.Object methods (so the 'owner' is now seen as the interface) whereas before it was using INVOKEVIRTUAL with java.lang.Object as the method 'owner'.
The key change is described in https://bugs.openjdk.org/browse/JDK-8272715:
> "invocations of java.lang.Object methods on interfaces in the classfile will use invokeinterface referring
> to the interface, which is consistent with JLS 9.2. This will be done regardless of whether the interface
> declares the method explicitly or not."
- Format the title [according the contribution …
> Ignore java.lang.Object methods when creating muzzle references

- dd-java-agent/agent-tooling/build.gradle
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/muzzle/ReferenceCreatorTest.groovy
- dd-java-agent/agent-tooling/src/test/java21/datadog/trace/agent/tooling/muzzle/CompiledWithInvokeinterfaceForObjectMethods.java
Complement #9649 with a test.
After JDK 18/19 `javac` compiles differently `Object` methods, while there is a ignore mechanism on `java.*` packages after the key change is described in [JDK-827271](https://bugs.openjdk.org/browse/JDK-827271), `Object`'s methods are applied to interfaces which may belong to another package.
Key change of JDK-827271
> "invocations of `java.lang.Object methods` on interfaces in the classfile will use `invokeinterface` referring to the interface, which is consistent with JLS 9.2. This will be done regardless of whether the interface declares the method explicitly or not."
- Assign the `type:` and (`comp:` or `inst:`) …
> Adds a test for JDK-827271

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/OutlineTypeParser.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeOutline.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/outline/OutlineTypeParserTest.groovy
- dd-java-agent/instrumentation/iast-instrumenter/src/main/java/datadog/trace/instrumentation/iastinstrumenter/IastInstrumentation.java
These methods are not used for matching purposes, so don't need to be maintained in outlines.
There is one use of type.isAnonymousType() in IAST, but this is under a support flag - I could not find any active use of that support flag. To satisfy the original use-case (involving MyBatis) we add a simple anonymous type heuristic to that particular instrumentation, based on the '$number' Java language convention for anonymous class names.
( If necessary we can further enhance that specialized matcher without incurring overhead for all outline parsing )
Note: if anything does touch type.getDeclaringType() / type.getEnclosingType() later on when doing the final transformation then the outline type is automatically inflated to a full type. (This is already the case for other methods that aren't …
> Simplify type outlines to not implement type.getDeclaringType() and type.getEnclosingType()

- dd-trace-core/src/main/java/datadog/trace/common/writer/RemoteApi.java
- dd-trace-core/src/main/java/datadog/trace/core/monitor/TracerHealthMetrics.java
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentApiTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDIntakeWriterCombinedTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddintake/DDEvpProxyApiTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddintake/DDIntakeApiTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/monitor/HealthMetricsTest.groovy
- dd-trace-core/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
This PR fixes a leftover after Java 8+ migration.
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master/.github/COD …
> Port remote API response to Java 8+

- gradle/version.gradle
The current version generation was writing directly to the output dir which could be replaced by a another tasks that runs later. This change makes this task generate the file in another location and makes the sourceSet use this task output as source dir. …
> Version file was not always generated on first jar generation

- dd-java-agent/agent-debugger/build.gradle
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
- dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturingTestBase.java
upgraded the Kotlin compiler version to 2.1.21
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master/.github/CODEOWN …
> Fix Kotlin unit test running on JDK 25

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ClassesToRetransformFinder.java
Use getTypeName instead of getName to get proper array syntax. unlikely it will happen as a probe definition on array is useless
- Update …
> Fix Retransform dependent classes for arrays

- .github/workflows/update-gradle-dependencies.yaml
Add akka repository token to update Gradle dependencies action.
Akka locked down their repository so that requests without the token are blocked. This mirrors the change in [gitlab](https://github.com/DataDog/dd-trace-java/blob/6c26663efeb2f13effc62a30cc2a5b45d1c1e28c/.gitlab-ci.yml#L167-L179)
This is one more attempt to fix build (see #9661), as it could be tested only from master.
See Gradle [docs](http://sorcersoft.org/project/site/gradle/userguide/tutorial_this_and_that.html).
> Add akka repository token to update Gradle dependencies action.

- dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV04PayloadTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV05PayloadTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanSerializationTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/datastreams/DataStreamsWritingTest.groovy
> Removes flakes from mapper tests

- communication/src/main/java/datadog/communication/BackendApiFactory.java
- communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
- communication/src/main/java/datadog/communication/http/OkHttpUtils.java
- communication/src/test/groovy/datadog/communication/ddagent/SharedCommunicationsObjectsSpecification.groovy
- dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilityServices.java
- dd-java-agent/appsec/src/jmh/java/datadog/appsec/benchmark/AppSecBenchmark.java
- dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/AppSecSystemSpecification.groovy
- dd-java-agent/instrumentation-testing/src/main/groovy/datadog/trace/agent/test/InstrumentationSpecification.groovy
- dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
- dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
- dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
- dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java
- dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultDataStreamsMonitoring.java
- dd-trace-core/src/test/groovy/datadog/trace/TracerConnectionReliabilityTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/common/writer/WriterFactoryTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/TracingConfigPollerTest.groovy
- dd-trace-core/src/test/groovy/datadog/trace/core/datastreams/DataStreamsWritingTest.groovy
- dd-trace-core/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
- internal-api/src/main/java/datadog/trace/api/Config.java
- telemetry/src/main/java/datadog/telemetry/TelemetryClient.java
- telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
- telemetry/src/test/groovy/datadog/telemetry/TelemetryClientTest.groovy
- telemetry/src/test/groovy/datadog/telemetry/TelemetrySystemSpecification.groovy
- utils/flare-utils/src/main/java/datadog/flare/TracerFlarePoller.java
Adds a single shared lazily-initialized HTTP client to send requests to Datadog backend.
Previously each component talking to the backend created its own HTTP client, so we ended up with 4-5 clients in agentless mode (tests intake, telemetry, API, logs intake, coverage report intake).
OKHTTP docs advice creating a single HTTP client per JVM (the client creates its own thread and connection pools, so having multiple clients adds some load).
By default the new single client does NOT force clear-text HTTP.
Prior to the changes, each component's URL was examined and if the schema was `http`, clear text connections were forced for corresponding client.
This was needed to support running in JVMs that had no modern TLS implementations.
This check is > 5 years old, nowadays it should be rare to …
> Create shared DD intake HTTP client

- .github/workflows/run-system-tests.yaml
Fix the pull request check that enforce system tests to build and run successfully.
If the system tests fails to build or run is skipped for whatever reason, the `check` job will be skipped and PR won’t be blocked. …
> Fix system tests PR check

- dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
decrease to Debug level
- Update the [CODEOWNERS](https://github.com/DataDog/dd-trace-java/blob/master/.github/CODEOWNERS) file on source …
> Fix log level ClassWriter

- dd-java-agent/agent-crashtracking/src/main/java/datadog/crashtracking/CrashUploader.java
- dd-java-agent/agent-crashtracking/src/test/java/datadog/crashtracking/CrashUploaderTest.java
Allows the telemetry intake to recognise properly as a crash
* Adds the `origin` header field set to `crashtracker` 
* Adds `is_crash` set to `true` to each Log entry …
> Add origin header to crashtracking telemetry
